### ISSUE TITLE
I have a seed error

### ISSUE THREAD

**Issue by gracenjambi** [ga-wdi-boston/full-stack-project#10]
Whenever I run rake db:seed I keep getting an error of unknown attribute kind for crop.
- I have gone ahead and made sure that the column is present in my controller.
  - In my schema the column kind is seen as part of the crop table.
  - the error seems to point to the syntax I have in my seeds file. 
  - In the database, the column kind does not exist even though it is part of my schema. Please see my schema below:

Please help me resolve this issue.

**Comment by gracenjambi** [comment]
ActiveRecord::Schema.define(version: 20151110154726) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "books", force: :cascade do |t|
    t.string   "title"
    t.string   "isbn"
    t.integer  "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "crops", force: :cascade do |t|
    t.string   "name"
    t.string   "season"
    t.integer  "garden_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "crops", ["garden_id"], name: "index_crops_on_garden_id", using: :btree

  create_table "gardens", force: :cascade do |t|
    t.string   "name"
    t.string   "kind"
    t.integer  "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "gardens", ["user_id"], name: "index_gardens_on_user_id", using: :btree

  create_table "users", force: :cascade do |t|
    t.string   "email",           null: false
    t.string   "token",           null: false
    t.string   "password_digest", null: false
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
  end

  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["token"], name: "index_users_on_token", unique: true, using: :btree

  add_foreign_key "crops", "gardens"
  add_foreign_key "gardens", "users"
end

**Comment by gracenjambi** [comment]
class AddKindToCrops < ActiveRecord::Migration
  def change
    add_column :crops, :kind, :string
  end
end

**Comment by gaand** [comment]
Please reply with the code from `db/seeds.rb`.

**Comment by gracenjambi** [comment]
Garden.delete_all
User.delete_all
Crop.delete_all

%w(grace susan john james).each do |name|
  email = "#{name}@example.com"
  user = User.create!(email: email, password: '123', password_confirmation: '123')
  garden = Garden.create!(name:name, kind: 'vegetable')

3.times do |i|
  user.gardens.create!(name: 'garden_#{i}_#{name}', kind: 'box')
end

3.times do |i|
    garden.crops.create!(name: 'crop_#{i}_#{garden}', kind: 'crop_#{i}_#{kind}', season: 'spring')
  end
end

**Comment by gaand** [comment]
Did you run `rake db:migrate`?  The schema you posted doesn't show a kind column for crops.

**Comment by gracenjambi** [comment]
the migration: 

class AddKindToCrops < ActiveRecord::Migration
  def change
    add_column :crops, :kind, :string
  end
end

**Comment by gracenjambi** [comment]
No my schema does not

**Comment by gracenjambi** [comment]
create_table "crops", force: :cascade do |t|
    t.string   "name"
    t.string   "season"
    t.integer  "garden_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

**Comment by gracenjambi** [comment]
That is my question not sure how to fix it.

**Comment by gracenjambi** [comment]
ok on my way to Classroom 1

**Comment by gaand** [comment]
Resolved:  database and migrations out of sync (unknown reasons).
`rake db:drop db:create db:migrate: db:seed`
Grace didn't need the data in the database so this was the easiest solution.
