### ISSUE TITLE
post request front end & requiring file 

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/full-stack-project#1000]
I can't get my post request to work for when users want to create an exercise and save it to the database. Nothing is happening and I think it might be a problem with requiring the file. Any logs I put in the addExercise file do not appear. 

all of these files are in the 'scripts' directory
```js
addExercise.js: 
'use strict'
const ui = require('./ui')
const config = require('./config')
const store = require('./store')
const getFormFields = require('../../lib/get-form-fields')

const check = function () {
  console.log('file required properly')
}

const onAddExercise = (event) => {
  console.log('on addexercise invoked')
  const data = getFormFields(this)
  event.preventDefault()
  addExercise(data)
  .then(ui.addExerciseSuccess)
  .catch(ui.addExerciseFail)
}

// this is the POST request used to add exercises to db
const addExercise = (data) => {
  console.log('create entry in api running')
  console.log(data)
  return $.ajax({
    url: config.apiOrigin + '/exercises',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

module.exports = {
  onAddExercise,
  check
}

eventHandling.js: 
'use strict'
const ui = require('./ui')
const changePass = require('./changePassword')
const addExercise = require('./exerciseActions/addExercise')

const addHandlers = function () {
  $('.buttonCloseSignUp').on('click', ui.modalEscapeSignUp)
  $('.buttonCloseSignIn').on('click', ui.modalEscapeSignIn)
  $('.buttonCloseChangePassword').on('click', ui.changePasswordEscape)
  $('#change-pwd').on('submit', changePass.onChangePassword)
  $('#addExerciseButton').on('submit', addExercise.check)
}

module.exports = {
  addHandlers
}

index.js:
$(() => {
  showHide.frontPage()
  eventHandling.addHandlers()
})
```
I've tried everything for hours....
the 'addExerciseButton' works, I put a log in there:
  $('#addExerciseButton').on('submit', console.log('its working'))
that works but nothing in the 'addExercise" file works

@MicFin @jordanallain @sdavidson140 @benjimelito @Jcornmanhomonoff @payne-chris-r @BenGitsCode @tvlangley @danman01

**Comment by benjimelito** [comment]
So I'm not in front of a computer right now, but one thing to watch out for
is a 'circular dependency'. This is when two files require each other, and
will cause your code to simply not work without any error messages.

**Comment by payne-chris-r** [comment]
I think Ben is right. It sounds like a circular dependency. Make sure you don't have two files requiring each other. Also make sure you don't have A req B, B req C, and C req A. That will also cause a CD error.

**Comment by ryanwk** [comment]
Ya i think that was it, so I refactored all my code, re-organized the file structure and it works.
