### ISSUE TITLE
unable to link handlebars 'delete' buttons with event handler

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/full-stack-project#1001]
Hello!

I'm unable to link the 'delete' buttons I have next to each entry (generated by handlebars) to any kind of event listener. I tried to add 
`$(document).on('submit', '.remove-button', function () {
    console.log('index.js running')
    beachEvents.onDeleteBeach(this.id)`

to my index.js file and required the events file as beachEvents.

However, when I click the 'delete' button nothing happens and nothing console logs at all.

**Comment by benjimelito** [comment]
One thing to think about is when is this submit handler being called? Make sure that the handler is not being called before your handlebars buttons are actually being rendered on the page.

**Comment by benjimelito** [comment]
Can you show the file where this code is contained?

**Comment by jingrid** [comment]
Hm, I have it in my UI file, under the function that runs when handlebars run. Here's what I have:
```js
const showBeachesTemplate = require('./templates/beach-listing.handlebars')
const beachEvents = require('./events')

const viewBeachesSuccess = (data) => {
  console.log(data.beaches)
  $('p').html('')
  const showBeachesHtml = showBeachesTemplate({ beaches: data.beaches })
  $('p').append(showBeachesHtml)
  console.log('view beaches in UI working')
  $('.remove-button').on('submit', function () {
    beachEvents.onDeleteBeach(event.target)
  })
}
```

**Comment by benjimelito** [comment]
That looks like the correct order to me. Are you able to get a simple `console.log` function to run when clicking submit on `.remove-button`?

**Comment by payne-chris-r** [comment]
I've fixed your code block by adding the code fence "```js [code goes here] "

**Comment by tvcrawley** [comment]
@jingrid Has this been resolved?

**Comment by jingrid** [comment]
Resolved by changing 'submit' to 'click', getting rid of circular dependency,
and then referencing the data-id of the button when running onDeleteBeach.
