### ISSUE TITLE
404 on sign up/in

### ISSUE THREAD

**Issue by jillrizley** [ga-wdi-boston/full-stack-project#1003]
I am getting this error when signing up/in. I am pretty sure it was working earlier but I am not totally sure what is causing the issue. I have made sure my urls are correct. Thoughts?

jquery.js:9566 POST http://localhost:7165/undefinedsign-up/ 404 (Not Found)

**Comment by jillrizley** [comment]
realized it's going to 7165 instead of connecting to 4741, not too sure how to fix it though!

**Comment by jillrizley** [comment]
this is what is in my config.js file looks like

```javascript
'use strict'

const config = {
  apiOrigins: {
    production: 'https://myshowcalendar.herokuapp.com/',
    development: 'http://localhost:4741'
  }
}
module.exports = config
```

and here is the error i'm getting now when I hit sign-up

POST http://localhost:7165/[object%20Object]/sign-up/ 404 (Not Found)

**Comment by MicFin** [comment]
What does your AJAX call look like?

**Comment by jillrizley** [comment]
```javascript
const signUp = function (data) {
  console.log(config.apiOrigin)
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data
  })
}
```

i did a console log and it says its going to 4741, but then I still get the same error

**Comment by MicFin** [comment]
Show me what `console.log(config.apiOrigin)` prints and what the error message says shortly after that.

**Comment by payne-chris-r** [comment]
```js
'someString' + {} => 'someString[Object object]'
```
in javascript

**Comment by jillrizley** [comment]
Luke fixed it! Some slashes and changing the apiorigin to localhost for now
