### ISSUE TITLE
'Module not found' when requiring handlebars file within another file.  

### ISSUE THREAD

**Issue by Fcarrion001** [ga-wdi-boston/full-stack-project#1004]
I am receiving this error when upon attempting to do so.
<img width="710" alt="screen shot 2017-07-24 at 8 36 30 am" src="https://user-images.githubusercontent.com/28816109/28523632-49fa3a6e-704b-11e7-8085-8984c6dcf246.png">

This is where my files are located in relation to one another.
<img width="288" alt="screen shot 2017-07-24 at 8 28 36 am" src="https://user-images.githubusercontent.com/28816109/28523408-43450e84-704a-11e7-811b-96087a5adf25.png">

This is how I am requiring the file
<img width="839" alt="screen shot 2017-07-24 at 8 33 07 am" src="https://user-images.githubusercontent.com/28816109/28523662-6768afd6-704b-11e7-8571-1245997f972d.png">

All research I have done on the matter suggests that there is a discrepancy with a file within the "node_modules" directory.  However, when I look at the areas that google suggests may be problematic, and compare them with the respective files within the handlebars practice repository, they are identical. 
I have also tried deleting the file and npm installing for a fresh copy.
Required the file from different files.
required the file via and absolute path
renaming the file (I was desperate at this point)

I dare not alter anything in the node_module files like some google responses have suggested

**Comment by benjimelito** [comment]
Ya, I don't think you need to me altering anything in your `node-modules`. Would you mind posting that handlebars file? It's possible there is an error in there.

**Comment by benjimelito** [comment]
When you get something like `module not found`, many times the issue is not that your file path is wrong, but that there is an error in the file that is being referenced.

**Comment by Fcarrion001** [comment]
Ah I see, I left this out of the list of what I have done but I also compared the contents to the file to handlebars training file several times. Hopefully you can see something that I missed. 

<img width="656" alt="screen shot 2017-07-24 at 9 39 39 am" src="https://user-images.githubusercontent.com/28816109/28526101-7d5a9c9c-7054-11e7-8498-d18c3ff52f45.png">

**Comment by payne-chris-r** [comment]
Have you checked your file path to make sure it matches?

**Comment by Fcarrion001** [comment]
Yes, I've even tried relocating the file and experimented with the path used to require just to make sure.

**Comment by Fcarrion001** [comment]
Update

Issue is still unresolved

**Comment by Fcarrion001** [comment]
Issue Resolved
changed .handlebars to .hbs and deleted the (partial) portion of the handlebars file completely instead of just commenting it out.
