### ISSUE TITLE
Unable to connect to my heroku server

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/full-stack-project#1005]
Hello! 

I was setting up heroku, got up to [the step](https://git.generalassemb.ly/ga-wdi-boston/rails-heroku-setup-guide#push-master-to-heroku) about git push heroku master. I'm unable to do that, or any subsequent step.

**Comment by MicFin** [comment]
What is stopping you?  Do you receive an error message?

**Comment by jingrid** [comment]
Yes, this is what I get in terminal: 
$ git push heroku master
Counting objects: 120, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (104/104), done.
Writing objects: 100% (120/120), 51.59 KiB | 0 bytes/s, done.
Total 120 (delta 10), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote:  !     No default language could be detected for this app.
remote: 			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
remote: 			See https://devcenter.heroku.com/articles/buildpacks
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to sheltered-everglades-72621.
remote: 
To https://git.heroku.com/sheltered-everglades-72621.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/sheltered-everglades-72621.git'

**Comment by MicFin** [comment]
What folder are you in?
What branch are you on?
What does `git status` show?

**Comment by jingrid** [comment]
I'm in my rails-api-template-master folder, master branch
git status shows: 
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    scripts/create-example.sh
	deleted:    scripts/get-examples.sh

no changes added to commit (use "git add" and/or "git commit -a")

Just 2 files I've deleted

**Comment by MicFin** [comment]
What does `git log` show us?

**Comment by jingrid** [comment]
```
commit f669276610770ea1e1e52491606ecdc5b2674aa5 (HEAD -> master, origin/master)
Author: jingrid <ijin@bu.edu>
Date:   Thu Jul 20 11:57:04 2017 -0400

    add readme
    
    add readme

commit dc119d802eabd15f6a2d4b9031e36c094f8bf55f
Author: jingrid <ijin@bu.edu>
Date:   Thu Jul 20 11:56:06 2017 -0400

    first commit
    
    add rails api template
```

**Comment by MicFin** [comment]
You should have a clean working directory when pushing to heroku.  You need to `git add` and then `git commit` or `git check out -- ` the files that you see when you do a `git status`

**Comment by jingrid** [comment]
Okok, I git added them, then merged my working branch into master, pushed master to github. 

git push heroku master is still failing 

sos

**Comment by cpearce31** [comment]
Did the error message change at all after committing?

**Comment by jingrid** [comment]
no :/ 

```
$ git push heroku master
Counting objects: 208, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (191/191), done.
Writing objects: 100% (208/208), 61.54 KiB | 0 bytes/s, done.
Total 208 (delta 57), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote:  !     No default language could be detected for this app.
remote: 			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
remote: 			See https://devcenter.heroku.com/articles/buildpacks
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to sheltered-everglades-72621.
remote: 
To https://git.heroku.com/sheltered-everglades-72621.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/sheltered-everglades-72621.git'
```

**Comment by jingrid** [comment]
fixed by moving rails files up 1 directory
