### ISSUE TITLE
Heroku Issue Connecting to Client 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#1006]
I have successfully deployed my heroku app, but whenever I load up my client through my github pages front end link it does not render the back end properly and I am left with a static html page.

**Comment by MicFin** [comment]
Please share the links to your deployed client and server applications.

**Comment by ghost** [comment]
Deployed Client: https://parthgpatel.github.io/Meal-Tracker-Front-End
Server Application: https://mealtrackingapp.herokuapp.com/

**Comment by MicFin** [comment]
Do you have a successful curl script making a request to the server?

**Comment by ghost** [comment]
yes

**Comment by MicFin** [comment]
What does your curl script look like and what response does your API send back?

**Comment by ghost** [comment]
<img width="392" alt="screen shot 2017-07-24 at 9 53 02 am" src="https://user-images.githubusercontent.com/28744159/28526581-f3bbe1d8-7055-11e7-919b-f9c2f4a17278.png">

**Comment by MicFin** [comment]
That is being sent to your localhost.  
Try replacing the URL with the URL to your deployed heroku application.  
You will need to do a sign in curl script to get a token from the heroku application first.

**Comment by ghost** [comment]
Still getting the same issue. Whenever I try to interact in some way with the page I am getting a 405 Not Allowed Response.

**Comment by ghost** [comment]
Also, a response to your earlier edit I have already created a sign in curl script. 
<img width="516" alt="screen shot 2017-07-24 at 10 08 38 am" src="https://user-images.githubusercontent.com/28744159/28527288-17ef1078-7058-11e7-841b-d0a7bcfb27fa.png">

**Comment by MicFin** [comment]
`405 Not Allowed Response.` https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
Review your curl script syntax for the `request`.

**Comment by MicFin** [comment]
Please show me the entire error message including the request being made.

**Comment by ghost** [comment]
<img width="476" alt="screen shot 2017-07-24 at 10 17 26 am" src="https://user-images.githubusercontent.com/28744159/28527688-5294cf6e-7059-11e7-8407-0b9de823e690.png">
<img width="1392" alt="screen shot 2017-07-24 at 10 16 46 am" src="https://user-images.githubusercontent.com/28744159/28527689-5296b4aa-7059-11e7-975e-d2379eab1978.png">

**Comment by MicFin** [comment]
When you run that curl script in the terminal with a TOKEN and all of the data, what response do you get in the terminal?

**Comment by ghost** [comment]
<img width="654" alt="screen shot 2017-07-24 at 10 24 16 am" src="https://user-images.githubusercontent.com/28744159/28527968-45b4c212-705a-11e7-8711-191cafbc9b15.png">

**Comment by MicFin** [comment]
There should be more to that error.  Don't take a screen shot, just copy the whoooole error starting with the request being made.

**Comment by parthgpatel** [comment]
`$ curl create.sh
<html>
    <head>
        <title>create.sh</title>
        <meta name="author" content="Samuel Douglas Caldwell, Jr." />
        <meta name="copyright" content="Sam Caldwell" />
        <meta name="keywords" content="Samuel,Douglas,Caldwell,Jr,Round,Rock,Texas,78665,5948 Pescia St" />
        <meta name="description" content="Scripted installation deploy point" />
        <style type="text/css">
    			*{
    				font-family:arial;
    				font-size:10pt;
    			}
    			body{
    				background-color:#333333;
    				width:100%;
    				min-width:100%;
    				max-width:100%;
    				height:100%;
    				min-height:100%;
    				max-height:100%;
    			}
    			#page{
    				background-color:#FFFFFF;
    				width:60%;
    				min-width:60%;
    				max-width:60%;
    				margin-left:20%;
    				margin-right:20%;
    				margin-top:100px;
    				margin-bottom:100px;
    				padding:20px 20px 20px 20px;
    				border:1px solid;
    				border-radius:5px;
    				box-shadow:10px 10px 5px #111111;
    			}
    		</style>
    </head>
    <body>
        <div id="page">
            <div style="text-align:center">
                <h1>Scripted Installer Deployment Point</h1>
            </div>
        </div>
    </body>
</html>`

**Comment by parthgpatel** [comment]
$ curl create.sh
<html>
    <head>
        <title>create.sh</title>
        <meta name="author" content="Samuel Douglas Caldwell, Jr." />
        <meta name="copyright" content="Sam Caldwell" />
        <meta name="keywords" content="Samuel,Douglas,Caldwell,Jr,Round,Rock,Texas,78665,5948 Pescia St" />
        <meta name="description" content="Scripted installation deploy point" />
        <style type="text/css">
    			*{
    				font-family:arial;
    				font-size:10pt;
    			}
    			body{
    				background-color:#333333;
    				width:100%;
    				min-width:100%;
    				max-width:100%;
    				height:100%;
    				min-height:100%;
    				max-height:100%;
    			}
    			#page{
    				background-color:#FFFFFF;
    				width:60%;
    				min-width:60%;
    				max-width:60%;
    				margin-left:20%;
    				margin-right:20%;
    				margin-top:100px;
    				margin-bottom:100px;
    				padding:20px 20px 20px 20px;
    				border:1px solid;
    				border-radius:5px;
    				box-shadow:10px 10px 5px #111111;
    			}
    		</style>
    </head>
    <body>
        <div id="page">
            <div style="text-align:center">
                <h1>Scripted Installer Deployment Point</h1>
            </div>
        </div>
    </body>
</html>

**Comment by ghost** [comment]
```$ curl create.sh
<html>
    <head>
        <title>create.sh</title>
        <meta name="author" content="Samuel Douglas Caldwell, Jr." />
        <meta name="copyright" content="Sam Caldwell" />
        <meta name="keywords" content="Samuel,Douglas,Caldwell,Jr,Round,Rock,Texas,78665,5948 Pescia St" />
        <meta name="description" content="Scripted installation deploy point" />
        <style type="text/css">
    			*{
    				font-family:arial;
    				font-size:10pt;
    			}
    			body{
    				background-color:#333333;
    				width:100%;
    				min-width:100%;
    				max-width:100%;
    				height:100%;
    				min-height:100%;
    				max-height:100%;
    			}
    			#page{
    				background-color:#FFFFFF;
    				width:60%;
    				min-width:60%;
    				max-width:60%;
    				margin-left:20%;
    				margin-right:20%;
    				margin-top:100px;
    				margin-bottom:100px;
    				padding:20px 20px 20px 20px;
    				border:1px solid;
    				border-radius:5px;
    				box-shadow:10px 10px 5px #111111;
    			}
    		</style>
    </head>
    <body>
        <div id="page">
            <div style="text-align:center">
                <h1>Scripted Installer Deployment Point</h1>
            </div>
        </div>
    </body>
</html>```

**Comment by MicFin** [comment]
Your curl script requires 5 variables to be passed into it.
1.  TOKEN=""
2.  DATE=""
3.  TITLE=""
4.  DESCRIPTION=""
5.  FEELING=""

Depending on what folder you are in, using that curl script should look more like:
```
 > curl create.sh TOKEN="dasfdfdasf" DATE="2017-04-01" TITLE="stuff" DESCRIPTION="stuff" FEELING="stuff"
```
The TOKEN value must be a real token that you got from a `sign_in` success response from the API.

**Comment by ghost** [comment]
when running that script I get a bunch of could not resolve host error messages back.

**Comment by MicFin** [comment]
@parthgpatel status on this one?  I do not see the new error message that I last left you with?

**Comment by ghost** [comment]
I had opened up another issue, but working on it
