### ISSUE TITLE
handlebars & "updated_at"

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/full-stack-project#1007]
I'm able to display a record with the fields "name" and "weight" from my DB. I have a button that triggers a GET request and indexes all records and I'm using handlebars to display a bulleted list of these records from the "Exercise" table. I've got "name" and "weight" to display but I would also like to add "updated_at" to the list. I've console logged "data"  (array of objects), which I think comes from getFormFields. So in "data" I don't see "updated_at" probably because it's not a value that getFormFields grabs. So how can I add "updated_at" (which is a property of 'exercises' in my back-end) and display it in my handlebars list of exercises?

and once I've accomplished that, how can I parse the "update_at" data to be more readable?

```js
events:
const onShowAllExercisesSubmit = (e) => {
  console.log('on show all exercises submit button, events, invoked')
  const data = getFormFields(event.target)
  e.preventDefault()
  exerciseApi.showAllExercisesRequest(data)
    .done(exerciseUi.showAllExercisesSuccess)
    .fail(exerciseUi.showAllExercisesFail)

ui:
const showAllExercisesSuccess = (data) => {
  $('#directions').text('These are all of your exercises')
  console.log('index exercises worked')
  console.log(data.exercises)
  $('#content').html('')
  const showExercisesHTML = showExercisesTemplate({ exercises: data.exercises })
  $('#content').append(showExercisesHTML)
}
}

api:
const showAllExercisesRequest = function (data) {
  console.log('show all exercises request in api invoked')
  return $.ajax({
    url: config.apiOrigin + 'exercises',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```
```rb
backend:
  create_table "exercises", force: :cascade do |t|
    t.string   "name"
    t.integer  "weight"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
    t.index ["user_id"], name: "index_exercises_on_user_id", using: :btree
  end
```

**Comment by benjimelito** [comment]
So you don't actually need to create this field on your own, as long as you have `t.timestamps` in your model it will automatically be created for you by ActiveRecord. I would make sure that this field is part of your model, migrate, and then check to see if you can see this field in the database after creating a new exercise.

**Comment by MicFin** [comment]
You will need to define `updated_at` on your serializer too because Rails does not include it in the serializer by default.

**Comment by ryanwk** [comment]
adding it to the serializer worked! How do I parse it to just display '2017-07-23'?

**Comment by benjimelito** [comment]
You should be able to do some parsing with Javascript string methods (`split`, `slice`, etc.). What does is look like currently?

**Comment by ryanwk** [comment]
"2017-07-24T14:25:38.728Z"
would like just date: "2017-07-24"

**Comment by benjimelito** [comment]
Maybe something like `"2017-07-24T14:25:38.728Z".split('T')[0]`?

**Comment by tvcrawley** [comment]
@ryanwk Update?

**Comment by ryanwk** [comment]
i put that:  <ul>Last Updated: {{exercise.updated_at.split('T')[0]}}</ul>
in my handlebars file. didn't seem to work.

**Comment by tvcrawley** [comment]
Sounds like this is a job better suited for the api as opposed to the client. Can you post the serializer for this resource?

**Comment by ryanwk** [comment]
```rb
class ExerciseSerializer < ActiveModel::Serializer
  attributes :id, :name, :weight, :updated_at
end
```

**Comment by benjimelito** [comment]
Right, you can't actually put Javascript in Handlebars. Toni is correct, this is a task much better suited for the api. Try putting that code either in the serializer, something like:
```
def updated_at
  object.updated_at.split('T')[0]
end
```

**Comment by ryanwk** [comment]
gotcha, so I put it in the class and got an internal server error 500,
then I put it outside of the class and it had no effect
```rb
class ExerciseSerializer < ActiveModel::Serializer
  attributes :id, :name, :weight, :updated_at

  def updated_at
    object.updated_at.split('T')[0]
  end
end
```

**Comment by ryanwk** [comment]
this did the trick! 
```rb
    object.updated_at.to_date
```
Thank you all and chris!
