### ISSUE TITLE
Password can't be blank curl request error 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#1010]
Whenever I try to run a curl request for my sign up or sign in requests I get an error message saying that the password cannot be blank despite passing in a token and values for the password.

**Comment by ghost** [comment]
```$ scripts/sign-up.sh EMAIL="tacos@yahoo.com" PASSWORD="cat"
HTTP/1.1 400 Bad Request
Server: Cowboy
Date: Mon, 24 Jul 2017 15:02:53 GMT
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: b79e9a0f-b40f-4a8a-b2e3-33eea6dc1d1e
X-Runtime: 0.110209
Vary: Origin
Transfer-Encoding: chunked
Via: 1.1 vegur

{"password":["can't be blank"]}```

**Comment by benjimelito** [comment]
Can I see the `curl` request you're using?

**Comment by ghost** [comment]
`#!/bin/bash

API="${API_ORIGIN:-https://mealtrackingapp.herokuapp.com}"
URL_PATH="sign-up"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "'"${EMAIL}"'",
      "password": "'"${PASSWORD}"'",
      "password_confirmation": "'"${PASSWORD}"'"
    }
  }'

echo`
