### ISSUE TITLE
Add button not working

### ISSUE THREAD

**Issue by jillrizley** [ga-wdi-boston/full-stack-project#1013]
I'm getting another error, this is for when I am trying to add something from my table to my join table.

PATCH http://localhost:4741/user_show/undefined 404 (Not Found)

The array is showing up in the console when I click my button, but thats about it!

API
``` javascript
const addShow = (data) => {
  console.log('addShow data = ' + data)
  return $.ajax({
    url: config.localhost + 'user_show/' + data,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  }
)
}
```

Events
``` javascript
const onAddShow = function (event) {
  console.log('sup b')
  const data = ($(this).parent().attr('data-id'))
  api.addShow(data)
    .done(ui.addShowSuccess)
    .fail(ui.failure)
}
```

UI
```javascript
const addShowSuccess = (data) => {
  console.log('addShowSuccess data = ' + data)
  console.log(data.user_shows)
}
```

**Comment by tvcrawley** [comment]
`http://localhost:4741/user_show/undefined` 

What do you expect `undefined` to be?

What data is contained in `data`?

**Comment by tvcrawley** [comment]
@jillrizley ☝️

**Comment by benjimelito** [comment]
Status?

**Comment by jillrizley** [comment]
The button is now recognizing the url, from updating the API, but it is now getting a 400 - bad request error when I click it

```
const addShow = (data) => {
  return $.ajax({
    url: config.localhost + 'shows',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: {
      'show_id': data
    }
  }
)
}
```

**Comment by jillrizley** [comment]
update: changed some API stuff and now were getting a 500 internal server error in the console, 

```
const addShow = (data) => {
  console.log('this is addshow data' + data)
  console.log('this is the user ', store.user)
  return $.ajax({
    url: config.localhost + 'shows_users',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: {
      'shows_user':
      {'user_id': store.user.id,
        'show_id': data
      }
    }
  }
)
}
```

and when we look at the terminal, we have this error

```
NameError (uninitialized constant ShowsUsersController::ShowsUsers):
```

**Comment by jordanallain** [comment]
@jillrizley any progress on this?

**Comment by jillrizley** [comment]
Not since working with Ben, was deploying heroku and stuff....but not really sure to go with my add button next!

**Comment by jordanallain** [comment]
can you post the relevant code that changed when you sat down with ben?

**Comment by jillrizley** [comment]
API:
```
const addShow = (data) => {
  console.log('this is addshow data' + data)
  console.log('this is the user ', store.user)
  return $.ajax({
    url: config.localhost + 'shows_users',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: {
      'shows_user':
      {'user_id': store.user.id,
        'show_id': data
      }
    }
  }
)
}
```

and in routes, we added this:

```  resources :shows_users, except: [:new, :edit] ```

**Comment by payne-chris-r** [comment]
Do you have a `ShowsUsersController` ? What route are you trying to hit?

**Comment by jillrizley** [comment]
I do and I have 
```
  post '/my-shows' => 'users#addshow'
```

for the route as of right now

**Comment by cpearce31** [comment]
So that route is expecting a POST request to `/my-shows`, but in `addShow` you're submitting a POST to `/shows_users`. Maybe you need to add a route for `/shows_users`.

**Comment by jillrizley** [comment]
added to routes, but still getting errors, even messing around with different api things, always an error
```
post '/shows_users' => 'users#addshow'
```

**Comment by jordanallain** [comment]
> `Do you have a ShowsUsersController ? What route are you trying to hit?`

do you have a ShowsUsersController? because you are routing to the users controller in that route.

> post '/shows_users' => 'users#addshow'

**Comment by jillrizley** [comment]
so I tried changing it to this:
```
  post '/shows_users' => 'showsusers#addshow'
```
and also with an underscore, but neither worked

**Comment by jordanallain** [comment]
` post '/shows_users' => 'showsusers#addshow'`

is addshow the name of a method inside your controller?

**Comment by jillrizley** [comment]
dont think so? this is what is in my controller

```
  def create
    @shows_user = ShowsUsers.new(shows_user_params)

    if @shows_user.save
      render json: @shows_user, status: :created, location: @shows_user
    else
      render json: @shows_user.errors, status: :unprocessable_entity
    end
  end
```

and in my api its

```
const addShow = (data) => {
  console.log('this is addshow data' + data)
  console.log('this is the user ', store.user)
  return $.ajax({
    url: config.localhost + 'shows_users',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: {
      'shows_user':
      {'user_id': store.user.id,
        'show_id': data
```

**Comment by jordanallain** [comment]
maybe try hitting the showsuser#create endpoint in that route?

**Comment by jillrizley** [comment]
also does not work. if i change it back to  my-shows, instead of showsuser, i get a 500 error, which is better right? I'm literally just trying to type any combination of things to make this work.....could someone maybe come sit with me....I'm starting to freak out about time, because if this does end up working...ever...and once I get in there, the rest doesn't work, I'm nervous about figuring that out by the end of the day

**Comment by jordanallain** [comment]
yeah lets meet up in the kitchen and try to figure it out.

**Comment by jillrizley** [comment]
so many things changed.... :(
