### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#1014]
I get the following message when trying to sign up or add content to my list of items. 

XMLHttpRequest cannot load https://hidden-spire-77972.herokuapp.com/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://parthgpatel.github.io' is therefore not allowed access. The response had HTTP status code 400.

**Comment by tvcrawley** [comment]
Do you have the `CLIENT_ORIGIN` set in your Heroku app?

**Comment by ghost** [comment]
yes I set it up earlier with Michael

**Comment by tvcrawley** [comment]
Can you post the code for the `config.js` in the client?

**Comment by ghost** [comment]
<img width="518" alt="screen shot 2017-07-24 at 2 38 28 pm" src="https://user-images.githubusercontent.com/28744159/28538891-ce30f4d0-707d-11e7-9b94-c65e3df4b921.png">

**Comment by kailinc** [comment]
www.parthgpatel.github.com.io does not exist when I went into the link. When I go to www.kailinc.github.io it works. I think the problem is there

**Comment by tvcrawley** [comment]
What's the output of `heroku config`?

**Comment by ghost** [comment]
```terminal 
CLIENT_ORIGIN:            https://parthgpatel.github.io
DATABASE_URL:             postgres://yszfczfoixflyc:30732a8ca8d25d8d004cca3cc0f634fbeb0485e71541f66d8023b7ae79a1efc5@ec2-50-17-217-166.compute-1.amazonaws.com:5432/d481nvprjd9pi4
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_LOG_TO_STDOUT:      enabled
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:          
SECRET_TOKEN:  
```

**Comment by kailinc** [comment]
The secret key bas and secret token exists, but it is not showing

**Comment by tvcrawley** [comment]
Was this step in the rails-api-template followed:
```
In order to make requests to your deployed API, you will need to set SECRET_KEY_BASE in the environment of the production API (using heroku config:set or the Heroku dashboard).
```
This is in addition to creating secret keys locally.

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
heroku config:set SECRET_KEY_BASE=$(rake secret)
Setting SECRET_KEY_BASE and restarting ⬢ mealtrackingapp... done, v20
~/desktop/Meal-Tracker-API-master (master)

heroku config:set SECRET_TOKEN=$(rake secret)
Setting SECRET_TOKEN and restarting ⬢ mealtrackingapp... done, v20

**Comment by benjimelito** [comment]
Please close this out when you get a chance!

**Comment by ghost** [comment]
solved

**Comment by Fcarrion001** [comment]
solution?
