### ISSUE TITLE
heroku origin

### ISSUE THREAD

**Issue by jillrizley** [ga-wdi-boston/full-stack-project#1020]
The back end repo has both heroku and origin in the command line, but I can't seem to get my front end to connect to origin.

When I run git remote -v on the back end, I get this

```
heroku	https://git.heroku.com/shrouded-reef-79923.git (fetch)
heroku	https://git.heroku.com/shrouded-reef-79923.git (push)
origin	https://shrouded-reef-79923.herokuapp.com/ (fetch)
origin	https://shrouded-reef-79923.herokuapp.com/ (push)
```

When I run git remote -v on the front end, I only get 
```
heroku	https://git.heroku.com/shrouded-reef-79923.git (fetch)
heroku	https://git.heroku.com/shrouded-reef-79923.git (push)
```

**Comment by jordanallain** [comment]
you need a back end repo and a front end repo, do you have 2?

**Comment by jordanallain** [comment]
you only need to push the back end to heroku

**Comment by jillrizley** [comment]
Caleb helped me get rid of the accidental front end heroku, fix my repo situation and deploy both front and back!
