### ISSUE TITLE
incorporating bootstrap

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/full-stack-project#1022]
I tried last night to download a bootstrap theme and place the files into my front end rep. Moved files around and couldn't seem to get the theme to display. Kept getting an error concerning requiring files / couldn't find modules. 

In my front end repo I noticed an index.scss file with something resembling this: @import ~/bootstrap ... etc 

How do I set up my theme? 

I was able to do this with my personal portfolio quite easily by simply placing the files into my repo and adding the themes html/header/footer links to my index.html file. However, this time around that's not working.

**Comment by cpearce31** [comment]
Is the theme a group of CSS files?

**Comment by ryanwk** [comment]
yes

**Comment by payne-chris-r** [comment]
Webpack != vanilla html/js/css
Smashing a bootstrap template into browser template is probably not worth your time. Your'e much better off looking at how they did certain things, and trying to replicate them inside the template like you know how than trying to "cut and paste" a boostrapped template.

**Comment by ryanwk** [comment]
ok, thanks!
