### ISSUE TITLE
Issues with get

### ISSUE THREAD

**Issue by mak1323** [ga-wdi-boston/full-stack-project#1024]
I thought I had a working api, but my adjectives column is coming back as a 500 error.
```json
"status": 500,
"error": "Internal Server Error",
"exception": "#<ActiveRecord::DangerousAttributeError: attribute is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.>",
"traces": {
"Application Trace": [
{
"id": 50,
"trace": "app/controllers/adjectives_controller.rb:8:in `index'"
}
```

I originally had a column as attributes, so I changed that to attribute. That didn't work. So then I changed it to type. Still not working. My curl requests and my db is working, so I'm not sure where to go.

**Comment by payne-chris-r** [comment]
"Type" is also not allowed.

**Comment by mak1323** [comment]
Created a new migration and changed type to description. Migrated, updated controller and serializer, and I'm running into same problem.

**Comment by cpearce31** [comment]
Is the error message exactly the same? Does it still say `DangerousAttributeError: attribute is defined by Active Record`?

**Comment by mak1323** [comment]
rails server prevented migration from taking affect. Restarting server allowed it to work.

Anyone else running into this, rails server does not work the same as grunt.
