### ISSUE TITLE
Patch and Delete are looking for an ID

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/full-stack-project#1026]
My Patch and Delete are not working because I seem to not be passing the id they are looking for.  I have tried adding a user Id and movie Id and the feedback below still lists a third: "id"=>"[object Object]"

![image](https://user-images.githubusercontent.com/28842407/28581212-afb07690-712f-11e7-8773-7c12bfa1f197.png)

I think the issue is how I am labeling Id in my modal.

```html
<div class="form-group">
                  <label for="inputMovieId">Movie Id</label>
                  <input type="number" class="form-control" name="movie[id]"
                  id="inputMovieId" placeholder="Movie Id">
                </div>
```
I would love some direction on this.

**Comment by 3point14guy** [comment]
update:

Now getting error about unpermitted parameters: id, movie

![image](https://user-images.githubusercontent.com/28842407/28583801-6d9fc144-7138-11e7-9e94-1a3eba18bbb8.png)

**Comment by 3point14guy** [comment]
Patch looks like it goes through on the front end, but it doesn't show the update when I refresh the GET request:

![image](https://user-images.githubusercontent.com/28842407/28583942-f1c5caa4-7138-11e7-94a5-799234985147.png)

**Comment by cpearce31** [comment]
Can you go to the network tab in Chrome devtools and see what response you're getting to that PATCH?

**Comment by 3point14guy** [comment]
200 ok

**Comment by 3point14guy** [comment]
Now, I am thinking it is because my movie controller is inheriting from openReadController.  I need to pass a user is somehow as well then, correct?

**Comment by 3point14guy** [comment]
*user id

**Comment by cpearce31** [comment]
Take a look at the third line of your most recent screen shot, where it shows what params are making it to the controller. It appears that you have a `movie` object nested within another `movie` object, and I notice that `id` appears in both of those.

**Comment by 3point14guy** [comment]
A-hah!  Ok, I fixed how I was defining my constant data and now the PATCH is successful and presents correctly with the GET request
