### ISSUE TITLE
grunt deploy sos

### ISSUE THREAD

**Issue by Azinck94** [ga-wdi-boston/full-stack-project#1029]
Just deployed front end but am now getting weird errors at local host testing url and in grunt serve 
```
ERROR in ./index.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/firstuser/Downloads/Fullstack-Front-End/index.js'
    at Error (native)
 @ multi application

ERROR in ./spec/_all.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/firstuser/Downloads/Fullstack-Front-End/spec/_all.js'
    at Error (native)
 @ multi specs
```

**Comment by Azinck94** [comment]
Planning on redeploying but want to sit down with someone if possible before I make anything worse, thanks!

**Comment by Azinck94** [comment]
Also can't see my site at the gh pages url but will update if that changes.

**Comment by jordanallain** [comment]
did you modify the index.js file in the root of the repo?

**Comment by Azinck94** [comment]
no i didn't that error came up when I deployed, hence why I am very confused!!

**Comment by cpearce31** [comment]
I can take a look

**Comment by Azinck94** [comment]
am deployed all set now, and can log in and out, but am getting an error on trying to show my list of players:
``` 
GET https://ballerhub.herokuapp.com/ballers 500 (Internal Server Error)

**Comment by Azinck94** [comment]
we are still having issues, event though routes seem to be in order as well as the controller. we can't seem to find where the issue is other than that it is not on the front end(everything works for local host)

**Comment by Azinck94** [comment]
ran a heroku db: migrate and the heroku run rake db:seed in order to re seed heroku database which worked!
