### ISSUE TITLE
database issue? 

### ISSUE THREAD

**Issue by rtuttle611** [ga-wdi-boston/full-stack-project#1034]
bin/rails db

psql: FATAL:  database "vacation-finder_development" does not exist
~/wdi/projects/full stack back end (basic)

__no sure what issue to be filing__

**Comment by benjimelito** [comment]
Maybe try creating it manually?
`psql -c CREATE DATABASE vacation-finder_development`

**Comment by rtuttle611** [comment]
did not seem to work, could i sit down with you to get another pair of eyes on this?

**Comment by rtuttle611** [comment]
database issue resolved, manually installed
