### ISSUE TITLE
deployed, now my entity CRUD actions do not work on ryanwk.github.io/StrongerFrontEnd

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/full-stack-project#1037]
just merged everything, back end / front end, pushed heroku to master, then grunt deployed

if I go to ryanwk.github.io/StrongerFrontEnd and try to test it and I discovered that:
sign-in/up/out/chng password work 
any exercise actions do not: show all exercises, add exercise, etc. 

Everything worked just fine locally. 
I'm getting this error when I try to show exercises or add exercises:  

stronger.herokuapp.com/exercises:1 POST https://stronger.herokuapp.com/exercises 500 (Internal Server Error)

**Comment by 3point14guy** [comment]
Ryan check out this issue that I closed earlier...it sounds like something a few of us went through:

https://github.com/ga-wdi-boston/full-stack-project/issues/1031

**Comment by jordanallain** [comment]
@ryanwk still having trouble with this?
