### ISSUE TITLE
Mixed Content Issue deployment

### ISSUE THREAD

**Issue by jillrizley** [ga-wdi-boston/full-stack-project#1039]
```
Mixed Content: The page at 'https://jillrizley.github.io/full-stack-project-front-end/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:4741/sign-in'. This request has been blocked; the content must be served over HTTPS.
```

After deployment I got this error, I changed the http to an https for local host, and made sure my apis were fixed, I just did to them what I had for tic tac toe and redeployed but I can't use anything on my page at all. today was a fun one... -___-

**Comment by cpearce31** [comment]
Sorry no one got back to you on this. Is it still an issue?

**Comment by jillrizley** [comment]
I have been updated my project to get MVP on my local host for now so I'm not sure......not getting that error right now though, so we can close it and if I have issues when I try to get it back online I can open a new issue!

**Comment by jordanallain** [comment]
@jillrizley  ?

**Comment by jillrizley** [comment]
we can close this, i reverted back to how everything was set up originally
