### ISSUE TITLE
.empty and .remove not working

### ISSUE THREAD

**Issue by mak1323** [ga-wdi-boston/full-stack-project#1040]
Just having issues with my list display. I have it as handlebars populated list, and I try to clear it with .empty (didnt work) so now I'm using .remove(didn't work) so kinda at a lost. Current method is to target all boxes made with handlebars and destroy them. 

```js
const clearFavorites = (array) => {
  $('.box').remove()
  array = []
}
```

It sort of updates but not enough for me to declare bug free.

**Comment by mak1323** [comment]
Also, definitely want to schedule a 1:1 over project if I can.

**Comment by jordanallain** [comment]
@mak1323 still having an issue with this?

**Comment by jordanallain** [comment]
@mak1323 !!!

**Comment by mak1323** [comment]
Ah sorry I didnt see this. Yeah for some reason I got this to work, there must have been a conflict somewhere that disallowed it. I'm not sure what I did to fix it.
