### ISSUE TITLE
Seeding example for every user

### ISSUE THREAD

**Issue by jbculbertson** [ga-wdi-boston/full-stack-project#1042]
Hi - I'd like to update my project so that when a new user signs up, instead of seeing an empty app and needing to create a recipe to see the functionality, I'd like to seed it with one sample recipe to prompt them to click around. 

I am already seeding one user with recipes for testing purposes, but how can I seed the db so that every user can see the same sample recipe?  Because my recipe resource is OpenRead protected, users can only see their own recipes.

**Comment by cpearce31** [comment]
Hey, sorry no one got back to you on this. Are you still working on this?

**Comment by jbculbertson** [comment]
thanks Caleb - yep, I would still like to do this.  I haven't had much of a chance to dig deeper though

**Comment by jbculbertson** [comment]
Caleb started me down the right path here.  Haven't had time to look into since then, so I'll close this and update later as needed.  thanks Caleb!
