### ISSUE TITLE
Data is seeding twice

### ISSUE THREAD

**Issue by jillrizley** [ga-wdi-boston/full-stack-project#1044]
I used `rails db:nuke_pave' to update my tables in my db.
 I had added a column to the table as well as updated the seeded data.
Everything looks great and works perfectly, except for two things.
    1. the data is all being duplicated, so they are showing up, but appearing twice.
   2. The column I added shows up, but without data. The rest of data is present.

I have been looking online, but I can't seem to figure out what would cause the duplication, or the missing data.
I am using handlebars, and added my newest column to those files, but only the name of the column is appearing on the page.

Not sure what code to post, if any. So let me know if seeing that would be helpful.

**Comment by jillrizley** [comment]
fixed problem 2! 

Data is still doubling though

**Comment by jordanallain** [comment]
so what is the actual problem? a user is able to add the same show to the join table? are you trying to make it so they can only add a show once?

**Comment by payne-chris-r** [comment]
If you have your server running, and it can't `db:drop` then it just does `db:seed` again. Make sure your server isn't running, and watch the output of EACH command that `db:nuke_pave` does for you. If that's still not working run the commands one at a time.

**Comment by jillrizley** [comment]
@jordanallain I have already made it so users can only add a show once, the actual shows are all listed twice. I pasted down below if thats confusing (and removed the other data for the issue)
@payne-chris-r  I will try that and let you know what happens!

Artist: John Digweed
Artist: Damien Lazarus
Artist: Flosstradamus
Artist: Zeds Dead
Artist: Bonobo
Artist: Chris Lake
Artist: Thundercat
Artist: Gorgon City
Artist: Rezz
Artist: John Digweed
Artist: Damien Lazarus
Artist: Flosstradamus
Artist: Zeds Dead
Artist: Bonobo
Artist: Chris Lake
Artist: Thundercat
Artist: Gorgon City
Artist: Rezz

**Comment by jordanallain** [comment]
you could do a similar thing to your shows table where you validate the uniqueness of something from that table

**Comment by jillrizley** [comment]
Went through the steps individually (finally had time to do so) and it worked!!!

Closing!
