### ISSUE TITLE
cannot set secret keys :(

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/full-stack-project#1045]
Tried to run bin/rails server, kept getting errors, even though I had the secret keys in .env from when I originally worked on the project prior to presentations. 

So I hardcoded one into secrets.yml, but I feel like that's not what I should be doing. Not sure how I can get the .env file working?

**Comment by cpearce31** [comment]
Did you maybe have the name of the secret key wrong in `.env`? It has to be exactly `SECRET_KEY_BASE_DEVELOPMENT=<your_secret_key>` and  `SECRET_KEY_BASE_TEST=<your_secret_key>`

**Comment by jordanallain** [comment]
@jingrid ?

**Comment by tvcrawley** [comment]
@jingrid Is this still an issue?

**Comment by jingrid** [comment]
Yea i think it was the naming, changed it to what @cpearce31 has above and it worked.

Also sorry for taking so long to update/respond.
