### ISSUE TITLE
object%20Object error

### ISSUE THREAD

**Issue by jillrizley** [ga-wdi-boston/full-stack-project#1047]
I am getting this object%20Object error, I haven't updated everything to be deployed yet, but this sort of thing was happening during the first submittal but with undefined instead of this object error, and if it's something occurring from my code rather than the fact it isn't deployed yet, I'd rather figure it out before I go to that step again. I've googled it, but I didn't really find anything I could understand.

This is when I click sign-up, sign-in does the same

`POST http://localhost:7165/[object%20Object]sign-up/ 404 (Not Found)`

my config.js file

```
'use strict'

const config = {
  apiOrigin:
  {
    development: 'https://localhost:4741',
    production: 'https://shrouded-reef-79923.herokuapp.com'
  }
}
module.exports = config
```

API Post file

```
const addShow = (data) => {
  const buttonID = event.target.id
  $(`#${buttonID}`).hide()
  return $.ajax({
    url: config.apiOrigin + 'shows_users',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: {
      'shows_user': {
        'user_id': store.user.id,
        'show_id': data
      }
    }
  })
}
```

**Comment by jordanallain** [comment]
did you change the object in config from `apiOrigins` to `apiOrigin` ?

**Comment by jillrizley** [comment]
I'm not sure.....there was a whole debacle of it being messed up before and I'm not totally sure where it started anymore. Should it be apiOrigins instead?

**Comment by tvcrawley** [comment]
@jillrizley Did Jordan's suggestion fix this issue?

**Comment by jillrizley** [comment]
Success!! Thanks y'all!!
