### ISSUE TITLE
Link for deployed Heroku app is bad

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/full-stack-project#1051]
I was just sending in my resubmit for the full stack project and was testing the links for the repos and deployed apps when I discovered that the link to my deployed Heroku app is bad:

![image](https://user-images.githubusercontent.com/28842407/29004072-c414873e-7a8f-11e7-8da6-df0191e1f975.png)

I am using the URL provided by Heroku:

![image](https://user-images.githubusercontent.com/28842407/29004116-5e1c7a08-7a90-11e7-8540-692018a760dc.png)

I checked the log as indicated in the error message and nothing there seems awry to my novice eyes. It also indicates the same URL I am attempting:

-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.3.1
-----> Installing dependencies using bundler 1.15.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/.........
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Using rake 12.0.0
       Using concurrent-ruby 1.0.4
       Using i18n 0.7.0
       Using minitest 5.10.1
       Using thread_safe 0.3.5
       Using builder 3.2.3
       Using erubis 2.7.0
       Using mini_portile2 2.1.0
       Using rack 2.0.1
       Using nio4r 1.2.1
       Using websocket-extensions 0.1.2
       Using mime-types-data 3.2016.0521
       Using jsonapi-parser 0.1.1.beta3
       Using jsonapi-renderer 0.1.1.beta1
       Using arel 7.1.4
       Using bcrypt 3.1.11
       Using bundler 1.15.2
       Using method_source 0.8.2
       Using pg 0.19.0
       Using puma 3.7.0
       Using rack-cors 0.4.0
       Using thor 0.19.4
       Using rails_serve_static_assets 0.0.5
       Using rails_stdout_logging 0.0.5
       Using tzinfo 1.2.2
       Using nokogiri 1.7.0.1
       Using rack-test 0.6.3
       Using sprockets 3.7.1
       Using mime-types 3.1
       Using jsonapi 0.1.1.beta6
       Using websocket-driver 0.6.5
       Using rails_12factor 0.0.3
       Using activesupport 5.0.1
       Using loofah 2.0.3
       Using mail 2.6.4
       Using rails-html-sanitizer 1.0.3
       Using rails-dom-testing 2.0.2
       Using globalid 0.3.7
       Using activemodel 5.0.1
       Using case_transform 0.2
       Using activejob 5.0.1
       Using activerecord 5.0.1
       Using actionview 5.0.1
       Using actionpack 5.0.1
       Using actioncable 5.0.1
       Using actionmailer 5.0.1
       Using active_model_serializers 0.10.4
       Using railties 5.0.1
       Using sprockets-rails 3.2.0
       Using rails 5.0.1
       Bundle complete! 17 Gemfile dependencies, 50 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       The latest bundler is 1.15.3, but you are currently running 1.15.2.
       To update, run `gem install bundler`
       Bundle completed (3.52s)
       Cleaning up the bundler cache.
       The latest bundler is 1.15.3, but you are currently running 1.15.2.
       To update, run `gem install bundler`
-----> Detecting rake tasks
-----> Discovering process types
       Procfile declares types     -> web
       Default types for buildpack -> console, rake, worker
-----> Compressing...
       Done: 25.7M
-----> Launching...
       Released v11
       https://groovy-movie.herokuapp.com/ deployed to Heroku

The issue queue has many entries about problems with Heroku deployment, but none about bad links.

I searched google and Heroku's support page and the issues with the same error message are discussing routes within code, which is not my problem; all my code and deployed front end is working just fine.  

How can I find the correct deployed Heroku link to include in my resubmittal?

Thanks!!

**Comment by payne-chris-r** [comment]
Try a different route. That looks normal.

**Comment by 3point14guy** [comment]
So, the error message I am getting is normal for when I navigate to the link for a deployed Heroku app?

**Comment by jordanallain** [comment]
Yes if you refer back to the heroku deployment guide you will see that the image you posted is the standard one. Not sure why they chose that one because it does sound like it didn't work.

**Comment by jordanallain** [comment]
Is your deployed client working as it should?

**Comment by 3point14guy** [comment]
Thanks Chris and Jordan for the prompt responses! 

Yes, the deployed client is working just fine.  I just got confused about the error message when I tried to navigate to my deployed heroku and didn't remember that response from the first submittal or from the deployment guide until you mentioned it.
