### ISSUE TITLE
no access control allow origin 

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/full-stack-project#1052]
I bought a domain name and have changed my portfolio to my custom domain name,CNAME and DNS are set up properly. However, this seems to have effected gh-pages in that my projects that used to use the ryanwk.github.io are disrupted. 

This is the error I'm getting:
```js
www.ryanwkoch.com/:1 XMLHttpRequest cannot load https://stronger.herokuapp.com/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.ryanwkoch.com' is therefore not allowed access. 
```

I've read these SO issue:
https://stackoverflow.com/questions/20035101/no-access-control-allow-origin-header-is-
https://stackoverflow.com/questions/26416727/cross-origin-resource-sharing-on-github-pages/26417091present-on-the-requested-resource
this article:
https://www.html5rocks.com/en/tutorials/cors/

From these articles I gather that I might need to implement something called CORS, change somethings in the backend, or reconfigure my DNS settings with my provider and custom domain settings on GH.

I'm also contacting Github's support team to figure out what I need to do to fix this. 

If anyone has encountered something like this please reach out.

**Comment by payne-chris-r** [comment]
You basically just want your new domain to mirror what's on gh pages. Starting with gh support is probably the right avenue. If they aren't helpful let me know.

**Comment by ryanwk** [comment]
I had google support help me register my DNS and set up CNAME. Then I had a build issue so I contacted gh support and they had me change what google told me to do. Should I contact gh support again with this current issue?

**Comment by jordanallain** [comment]
you have to configure the github repo which github support can help walk you through

**Comment by ryanwk** [comment]
ok I reached out to them, I'll update when resolved

**Comment by jordanallain** [comment]
this link might help too https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by ryanwk** [comment]
I read through those docs when I initially set up the custom domain name.

this is what gh support told me

Hi Ryan,Just so I'm clear on what your issue is, you added a custom domain to your ryanwk.github.io site and now you're having trouble with other Pages sites you host?When you add a custom domain to a *.github.io repository this replaces all instances of that domain over all your projects. So if you hosted a project at ryanwk.github.io/my-project the domain would now be ryanwkoch.com/my-project. We do redirect requests to this domain, but that could be a cause of the issue you're experiencing.Secondly, it could be due to the fact that you're requesting an insecure resource from a secure domain. GitHub Pages currently doesn't support HTTPS for sites with custom domains, and I've seen similar (unhelpful) errors in the past from similar situations.Hope this helps! Let me know if you need anything else—or if I completely missed the point of your question

I'm not sure what that means

**Comment by jordanallain** [comment]
i think maybe he misunderstood what you were trying to do. you're just trying to redirect someone so that when they type in www.ryanwkoch.com it loads www.ryanwkoch.github.io/portfolio

(or whatever the actual links would be)

**Comment by ryanwk** [comment]
so thomas told me to do this: 

Keep ryanwk.github.io as your main domain name, have custom domain redirect to that

We don't offer the ability to redirect from a custom domain to a *.github.io domain directly. When you add a custom domain on GitHub we replace the *.github.io part entirely and put the appropriate redirects in place.

If your DNS provider supports it, you may be able to set up a redirect so that any time someone enters www.ryanwkoch.com it will be redirected to your ryanwk.github.io domain instead.

Use your custom domain on your Portfolio site, but not on any other GitHub project page

If you'd like to use your custom domain only on your portfolio, but not on any other project, then the solution to this is simply to rename your repository to something other than ryanwk.github.io.

This naming scheme denotes a special user page, meaning that the custom domain set here will automatically be applied to all repositories under your account. Changing the name will "demote" this site to being a regular project page, meaning the domain will only apply to that repository.

Be aware that after renaming you may need to reactivate Pages from the repository settings.

which option do you recommend?

**Comment by jordanallain** [comment]
`If your DNS provider supports it, you may be able to set up a redirect so that any time someone enters www.ryanwkoch.com it will be redirected to your ryanwk.github.io domain instead.`

this is the way that i did it. it was easy through hover.com, not sure what website you used to purchase your domain.

**Comment by ryanwk** [comment]
ok I'll try it out, thanks!
