### ISSUE TITLE
Commas within input in CSV's

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/full-stack-project#107]
I have a data type of text in my 'desc' column in one of my tables. Within 'desc', it's likely that a comma will be within the data. I know this will be problem and the CSV will think I'm changing to the next column. I have researched the docs and there are multiple ways of going about this. All of which I'm relatively confused about.

**Comment by GA-MEB** [comment]
The common way of dealing with this is to use quotes in your CSV file.

**Comment by gaand** [comment]
@kpie89 See :quote_char in http://ruby-doc.org/stdlib-2.2.4/libdoc/csv/rdoc/CSV.html#method-c-new
