### ISSUE TITLE
ERD Review

### ISSUE THREAD

**Issue by ajordon** [ga-wdi-boston/full-stack-project#108]
I just need another set of eyes to review my DB table layout

**Comment by ajordon** [comment]
![image](https://cloud.githubusercontent.com/assets/6088950/13322865/9e07053e-dba4-11e5-9834-8e2cf0b37a5f.png)

**Comment by GA-MEB** [comment]
Originally, this plan called for a couple of different models. We discussed the ERD, and decided that the above plan worked better.

**Comment by ajordon** [comment]
Would the Users table have a one-to-many representation to Polls because  a user can create many Polls as well has have many votes in different Polls. Possibly closer to this:

![image](https://cloud.githubusercontent.com/assets/6088950/13325776/4031ab50-dbb1-11e5-898a-2cd3a03de469.png)

**Comment by GA-MEB** [comment]
If a user can create many polls, and polls know which user created them, then one user is associated with many polls.

Is a user only able to make one vote? Or can they cast many votes?

**Comment by GA-MEB** [comment]
If you want
(a) users to be able to make multiple votes, and
(b) for multiple votes to be attached to a given poll
then you need a 'has many... through...'

If you want to constrain things so that one user can only vote once on any given poll,
then what you really need to do is ensure that each vote has a unique combination of user_id and poll_id.

**Comment by ajordon** [comment]
i will be utilizing validations to ensure only one user can vote per Vote.

**Comment by jrhorn424** [comment]
Matt is suggesting that in addition to validations, you add a DB constraint. Recall unique e-mails? You'd be doing something similar, with what's called a composite constraint. http://stackoverflow.com/questions/3370271/a-migration-to-add-unique-constraint-to-a-combination-of-columns

**Comment by jrhorn424** [comment]
@ajordon And I discussed denormalizing his model to extract options as its own entity. An option belongs to a poll, and a poll has many options. Options have labels. Votes are responses by users for a particular poll and with a particular option (three-way join).
