### ISSUE TITLE
Issues with Sass for front end template

### ISSUE THREAD

**Issue by jenweber** [ga-wdi-boston/full-stack-project#111]
Sass does not seem to be working for me (viewing the site using grunt serve). I'm setting up the templates for my two repos and making sure they work as expected before I start changing things. Bootstrap is fine, and my css is working, but not my color variables. I tried following the gem installation instructions on the Sass website but this did not have any effect. I'll just not use Sass in the meantime.

**Comment by GA-MEB** [comment]
Can you paste in your SASS code?

**Comment by jenweber** [comment]
`$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import '~bootstrap-sass/assets/stylesheets/bootstrap';

$redbackground: 9D2E2C;
$pale-yellow: F9EA99;
$pale-blue: 7DB6D5;
$pale-orange: E7A555;
$charcoal: 4A4747;

body {
  background-color: $redbackground;
  font-family: Arial, Helvetica, sans-serif;
  width: 100%;
}

.featured {
  background-color: $redbackground;
  font-size: 55px;
}`

**Comment by GA-MEB** [comment]
Not sure if those Hex codes need a `#`, but otherwise, the main part of your SASS looks syntactically correct.

Are you sure that `bootstrap-sass` is in your `grunt/webpack.js` file?

**Comment by RealWeeks** [comment]
@jenweber What Matt said.  When did you grab the js-template?

**Comment by jenweber** [comment]
It does need the #, apparently. Thanks team!
