### ISSUE TITLE
ERD issue

### ISSUE THREAD

**Issue by nwilcox11** [ga-wdi-boston/full-stack-project#112]
![fullsizerender](https://cloud.githubusercontent.com/assets/15088171/13324167/81db47a2-dbaa-11e5-80d0-e7b7198dba0e.jpg)

**Comment by RealWeeks** [comment]
Is this a high level issue you want to meet with someone about?

**Comment by nwilcox11** [comment]
## Matt talked with me about it already

Nick Wilcox

**Comment by gaand** [comment]
@nwilcox11 Is this issue resolve?  If so, please close it.  Thanks.
