### ISSUE TITLE
database issue

### ISSUE THREAD

**Issue by apalmer0** [ga-wdi-boston/full-stack-project#113]
Process that led to issue:
1) i tried starting in a directory called 'gym-news-api' before i realized there was a rails-api-template
2) after realizing the template existed, i changed my directory name to gym-news-api-trash so i could save the files i had written
3) downloaded the zip, renamed it to gym-news-api, ran through the rest of the steps in rails api template repo readme
4) tried creating a migration to generate a 'Gym' model, but it generated in gym-news-api-trash
5) tried recreating migration with new database, migration tells me the files already exist. files still only exist in the -trash directory, not in the new directory

![image](https://cloud.githubusercontent.com/assets/6477457/13325353/73de2520-dbaf-11e5-9f27-7971a7e8f441.png)

**Comment by GA-MEB** [comment]
Bizarre issue; calling `rails g` from the new rails repo was generating files in the old rails repo. 

Resetting the console brought things back to normal.

**Comment by jrhorn424** [comment]
If you trash or rename a directory outside the terminal, the terminal switches to that new directory without telling you. I've run into this a few times when trashing a directory.
