### ISSUE TITLE
SQL: Can I store an array in a column?

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/full-stack-project#115]
I'd like to store an array of time values in one of my columns. The context is that I will have a table of medicines, and I would like a column in that table saying when that medicine should be taken on a daily basis.

**Comment by MFBrewster** [comment]
It seems like the most appropriate solution is to create a join table connecting users with medicines, which will be called "doses" or something similar thereto!

**Comment by jrhorn424** [comment]
That makes sense. Adding an array as a column is usually an indication that you want another table, since you can usually give the array a good name (database table name) and the elements in the array are individual rows in the database.
