### ISSUE TITLE
help with project

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/full-stack-project#116]
Hi, 

I need help to figure out if my project is feasible with the amount of time I have left. As well as advice on my project idea

Thanks,
Khanhat

**Comment by gaand** [comment]
Can you describe your project idea?

**Comment by Knguyen21** [comment]
I want to create a web app that allows users to review and rate individual menu items from restaurants.

**Comment by gaand** [comment]
Have you drawn an ERD?  User, Review, Menu, MenuItem, etc?

**Comment by RealWeeks** [comment]
As a point of clarity she is wondering whether descoping from her current idea makes sense.  (which is to include a 3rd party menu api as well)

**Comment by Knguyen21** [comment]
Yes. I might drop the 3rd party api because it seems too time consuming to figure out how to use.  Is it okay if I just  display 2-3 restaurants' menus in my web app

**Comment by gaand** [comment]
Without and ERD, I'm not sure I know the scope.

**Comment by gaand** [comment]
Starting with a few preloaded restaurants is fine.  Later you can add the API or allow users to add/update resteraunt data.

**Comment by Knguyen21** [comment]
I made a ERD, would you be able to help me determine if my project needs to be scaled back?

**Comment by gaand** [comment]
Sure.

**Comment by gaand** [comment]
@Knguyen21: I think this issues is resolved.  Would you please close it?  Thanks.

If you have additional questions, please open a new issue.
