### ISSUE TITLE
Need a live chart

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/full-stack-project#117]
I'm looking to add a necessary feature to my project which is to have a live, constantly updated by the user, chart. I have tried google and have been directed to different types of libraries(one including Charts.js). Only problem is I'm not sure how to implement these outside libraries or even know if they have what I need for my project. The whole goal is to get a chart that plots submissions or points when a user makes a submission in a input field on the side of the chart. Also the x and y-axis parameters will have to change to fit that specific user's submission. If anyone is familiar which using charts that can be constantly altered, I would definitely like the help as this chart makes up most of my project.

**Comment by GA-MEB** [comment]
Chart.js is a great tool for adding charts and graphs to an application. However, unless displaying graphs is a core feature of your application, I would hold off on working on this - trying to add an external library into your project always has a learning curve, and I wouldn't want you to spend all your time trying to get Charts.js to work if your back-end isn't done.

**Comment by GA-MEB** [comment]
If it is core, then I'd begin by reading the documentation very carefully, while still working on the back-end.
