### ISSUE TITLE
ERD guidance

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/full-stack-project#118]
![20160225_154201](https://cloud.githubusercontent.com/assets/12851296/13333796/cede5806-dbd6-11e5-8994-4c45350bb2fb.jpg)
![20160225_154213](https://cloud.githubusercontent.com/assets/12851296/13333804/d8347872-dbd6-11e5-841f-56546db3b6fa.jpg)

Feeling lost just want some reinsurance if i am going about this in the right manner.

**Comment by RealWeeks** [comment]
Very much so. I like this idea.

**Comment by RealWeeks** [comment]
Do it well and hit it out the park.  You have my official assurance you are on the right path and this is a good idea.
