### ISSUE TITLE
I'm trying to better understand routes and controllers.

### ISSUE THREAD

**Issue by faetea** [ga-wdi-boston/full-stack-project#12]
My register/POST requests ARE working.  I can enter the email/password into my front-end application and they DO get saved to my users table in my database, yay!  

My Question:  What I'm curious about is this, when I tested it in postman why does it say current_user: false?  Is current_user always false?  Like I said it seems to be functioning, but I was curious.

{"user":{"id":4,"email":"an@example.email","current_user":false}}

**Comment by jrhorn424** [comment]
This might be due to an order of operations in the auth app. It could also be a quirk of Postman.

@faetea Can you please try doing the same process in curl and pasting your output? Please record all steps and paste all output from a fresh terminal session.

**Comment by jrhorn424** [comment]
I'm not sure this has anything to do with your understanding of controllers and routes. It might just be a tooling concern. After you've posted your output, I'll review it and we can discuss further in person if needed.

**Comment by faetea** [comment]
I think you are right that it just was postman.  I moved on to working on the Login and other Table stuff since Register is working.  I will ask more questions if I run into any actual walls.

**Comment by jrhorn424** [comment]
Thanks for the update!
