### ISSUE TITLE
User Story, Wireframe, ERD Approval

### ISSUE THREAD

**Issue by msyao** [ga-wdi-boston/full-stack-project#120]
Hi guys, :computer: 
Please let me know if any of you (perhaps Matt who I have spoken to about my project idea, which now looks to be a blog) look at the 2 links below? :bow: 

:coffee: Thank you very much! :+1: 

User story:
https://docs.google.com/spreadsheets/d/19IUXzDiCOk4CeVkASmtYHsvOuLk50Mcr-rlMH1XYaAA/edit?usp=sharing

Wireframe & ERD:
https://drive.google.com/file/d/0B6ccxHoU5CU8X0lhNnBsbHM5SDg/view?usp=sharing

**Comment by gaand** [comment]
Is the app read-only unless you login as an administrator?

Is there anything that requires a regular user to login?

**Comment by msyao** [comment]
Yes the app would be read-only unless logged in as administrator. Regular users/viewers of the web app will not need to log in (for now).

**Comment by gaand** [comment]
Okay.  But the admin will create/change/remove articles?  I think that's enough to meet the project requirements.  

Please proceed.  Also, please close this issue if I've answered your question (please open a new issue for new questions, etc).

**Comment by msyao** [comment]
Ok thank you very much!!
