### ISSUE TITLE
SyntaxError in BeersController#index

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/full-stack-project#123]
```
/Users/kevinpie/wdi/projects/drunken-critic-rails-api/app/models/beer.rb:3: syntax error, unexpected tCONSTANT, expecting ')' ...beers/?key= ENV['BREWERY_DB_KEY']') ... ^ /Users/kevinpie/wdi/projects/drunken-critic-rails-api/app/models/beer.rb:3: syntax error, unexpected ')', expecting keyword_end
```

```
class Beer
  def self.all
    HTTParty.get('http://api.brewerydb.com/v2/beers/?key=ENV['BREWERY_DB_KEY']')
  end
end
```

I can't figure out what my syntax error is. I have tried to alter in a dozen or more times (after researching docs) to no avail. I know that I'm missing something simple but can't figure it out.

**Comment by gaand** [comment]
You're using the wrong quotes around the url: `"`, not `'`.  Also, you need to use `#{ENV['BREWERY_DB_KEY']}` after you fix the quotes.

**Comment by kpie89** [comment]
I feel silly. Thank you.
