### ISSUE TITLE
no implicit conversion of HTTParty::Response into String

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/full-stack-project#124]
```
  def self.all
    ActiveSupport::JSON.decode(HTTParty.get("http://api.brewerydb.com/v2/beers/?key=#{ENV["BREWERY_DB_KEY"]}"))
  end
```

Not sure what I'm doing wrong. The error message is confusing because it says there is no conversion into string but the code is supposed to convert FROM a JSON string.

**Comment by gaand** [comment]
Assign the return from HTTParty to a variable in the rails console and check its class.  It's not a string and probably doesn't have a to_s method.  So, check the docs to see how to get a string representing the data out of the HTTParty::Response.  Also, you probably want to check for errors when making the request (probably something the response can tell you).
