### ISSUE TITLE
1-on-1 with Jeff: project planning, scope

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/full-stack-project#125]
During our 1-on-1 today, I'd like to ask general questions about my project plan, whether I should expand it, whether what I have will meet the project specs, etc. If there is a scanner around I can scan in my ERDs and user stories, but if not then it shouldn't take too long to explain where I am at and what I want to try and accomplish. Thanks!

**Comment by GA-MEB** [comment]
Why don't you take a picture of your ERD with your phone, and upload it here?

**Comment by MFBrewster** [comment]
![image](https://cloud.githubusercontent.com/assets/8867447/13357020/5f0de082-dc76-11e5-9c3c-69daf56c02df.png)

**Comment by MFBrewster** [comment]
I've since pared it back a little, so I'm starting with just Users, insulins ("medicines"), and injections ("doses").... meals and blood sugars to be added later if I have time after the minimum specs are met.

**Comment by GA-MEB** [comment]
So this app is used to manage insulin level? 
And a user records both the meals they take and the insulin injections they receive in conjunction with each meal?
Is that all correct?

**Comment by MFBrewster** [comment]
That is what I will eventually do... in order to meet the minimum specs, I'm just making an app which will allow a user to create a list of their regularly scheduled injections, and retrieve/update that list, and check off an injections after they've taken it on a given day.

**Comment by GA-MEB** [comment]
So a person has many injections, and can do crud on it? Seems reasonable.

One suggestion:
I would recommend that you separate out the User resource from how you represent a person in your business logic. For instance, you could create another resource (e.g. 'Person', or 'UserProfile') to relate to the other models, and then associate that new resource 1:1 with a User. 
An advantage to this is that you can test your business logic independently of your authentication system.

**Comment by GA-MEB** [comment]
@MFBrewster Can we close this?

**Comment by MFBrewster** [comment]
Yep, closing it now

**Comment by jrhorn424** [comment]
@MattB-GA-Boston It's a 1on1 issue, so I'll check-in with Mike. Thanks for being on top of this!
