### ISSUE TITLE
float

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/full-stack-project#126]
Since I didn't migrate, can I change my column's type in the migration file?

 replace the price column into  `t.decimal :price :precision => 5, :scale => 2, :default => 0.00`

``` ruby
class CreateMenus < ActiveRecord::Migration
  def change
    create_table :menus do |t|
      t.string :image
      t.string :meal_type
      t.string :name
      t.string :desc
      t.float :price  

      t.timestamps null: false
    end
  end
end
```

``` ruby
  t.float :price :precision => 5, :scale => 2, :null => false, :default => '0'
```

**Comment by GA-MEB** [comment]
Up until the time you run `rake db:migrate`, you can change the type of any column in you migration without any issue.

If you _have_ run `rake db:migrate`, you need to roll back to before that migration has run  (`rake db:rollback`) before editing it - otherwise, you can seriously mess up your migrations.

**Comment by Knguyen21** [comment]
great thanks

**Comment by RealWeeks** [comment]
I could recommend reading this. Let me know if it doesnt work:

http://stackoverflow.com/questions/3063968/string-decimal-or-float-datatype-for-price-field

**Comment by Knguyen21** [comment]
I didn't migrate, so I'm going to change it in my migration file manually. 

t.decimal :price :precision => 5, :scale => 2, :default => 0.00

However, when I typed in atom, there was many errors.

**Comment by RealWeeks** [comment]
Did you already debug these errors or do you need help with them as well?

**Comment by Knguyen21** [comment]
yes I need help with them.

**Comment by GA-MEB** [comment]
@Knguyen21 What errors did you get in Atom?

**Comment by RealWeeks** [comment]
Please paste in

**Comment by Knguyen21** [comment]
``` ruby
class CreateMenus < ActiveRecord::Migration
  def change
    create_table :menus do |t|
      t.string :meal_type
      t.string :name
      t.string :desc
      t.decimal :price :precision => 5, :scale => 2

      t.timestamps null: false
    end
  end
end
```

![image](https://cloud.githubusercontent.com/assets/16465193/13358544/cb58534c-dc7d-11e5-81e6-e4fd61a5ffd6.png)

**Comment by GA-MEB** [comment]
Is `class CreateMenus < ActiveRecord::Migration` line 1?

If so, then line 7 is `t.decimal :price :precision => 5, :scale => 2`

Should there be a comma after `:price`?

**Comment by RealWeeks** [comment]
@Knguyen21 was this issue resolved?

**Comment by Knguyen21** [comment]
yes. Thanks matt

**Comment by Knguyen21** [comment]
Is this okay? my price value looks off.  I entered in 3.00 and when I tried to get the data for cake, the price value was #<BigDecimal:7fceba648d78,'0.3E1',9(18)>.

``` sh
# @jrhorn424 added a fenced code block
[24] pry(main)> cake.price = 3.00
=> 3.0
[25] pry(main)> cake
=> #<Meal:0x007fcebcb0d668
 id: 1,
 meal_type: "dessert",
 name: "Tiramisu",
 desc: "Sweet chocolate italian dessert",
 price: #<BigDecimal:7fceba648d78,'0.3E1',9(18)>,
 created_at: Fri, 26 Feb 2016 19:50:13 UTC +00:00,
 updated_at: Fri, 26 Feb 2016 19:51:59 UTC +00:00>
```

**Comment by jrhorn424** [comment]
What did it look like before you changed the price?

Please surround output in backticks.

**Comment by jrhorn424** [comment]
After I added backticks, I can see that the price looks right. Google "ruby bigdecimal money" and see why this works out to be a good thing.

**Comment by jrhorn424** [comment]
If this resolves your issue, please close.

**Comment by Knguyen21** [comment]
Sorry, this is the code 

```
[25] pry(main)> cake
=> #<Meal:0x007fcebcb0d668
 id: 1,
 meal_type: "dessert",
 name: "Tiramisu",
 desc: "Sweet chocolate italian dessert",
 price: #<BigDecimal:7fceba648d78,'0.3E1',9(18)>,
 created_at: Fri, 26 Feb 2016 19:50:13 UTC +00:00,
 updated_at: Fri, 26 Feb 2016 19:51:59 UTC +00:00>
```

**Comment by Knguyen21** [comment]
I manually changed the float to decimal. But now I realized it is causing errors. Should I just go back to float type for my price column?

**Comment by jrhorn424** [comment]
What error?

**Comment by jrhorn424** [comment]
Floats are not precise. They are not good for money. Please google "ruby float big decimal money".

**Comment by Knguyen21** [comment]
The price error is 

```
# code block added by @jrhorn424
price: #<BigDecimal:7fceba648d78,'0.3E1',9(18)>,
```

**Comment by gaand** [comment]
Did you create a migration for the change of type?

**Comment by jrhorn424** [comment]
This line `price: #<BigDecimal:7fceba648d78,'0.3E1',9(18)>` tells me that the price is `3.0`. It's written in scientific notation, where `0.3E1` is equivalent to `0.3 x 10^1` which is equivalent to `3.0`.

**Comment by jrhorn424** [comment]
Please use backticks.

**Comment by jrhorn424** [comment]
That's not an error. That's a decimal.

**Comment by Knguyen21** [comment]
Oh ok. Sorry, I didn't realize I needed to add the backtic for price . Yes, after I manually changed the
 float to decimal on atom, I migrated the database for the first time.  OK. I will keep my decimal. Thanks

**Comment by jrhorn424** [comment]
To display a BigDecimal as a string, we need something like this in the appropriate serializer:

``` ruby
"%.2f" % object.price.truncate(2)
```

**Comment by jrhorn424** [comment]
@Knguyen21 Please close if this is resolved. Thanks!
