### ISSUE TITLE
float to decimal

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/full-stack-project#127]
Since I didn't migrate, can I change my column's type in the migration file?

 replace the price column into  t.decimal :price :precision => 5, :scale => 2, :default => 0.00

class CreateMenus < ActiveRecord::Migration
  def change
    create_table :menus do |t|
      t.string :image
      t.string :meal_type
      t.string :name
      t.string :desc
      t.float :price  

```
  t.timestamps null: false
end
```

  end
end

**Comment by GA-MEB** [comment]
Is this the same as #126 ?
