### ISSUE TITLE
Ruby: Unsure of how to user current_user

### ISSUE THREAD

**Issue by jpfriedman18** [ga-wdi-boston/full-stack-project#128]
Trying to use current_user in StockPurchasesController. When trying to access the route to stock_purchases#index in the browser, I receive the following error:

undefined method `stock_purchases' for nil:NilClass

pointing to the following line in the index method:

``` ruby
@stock_purchases = current_user.stock_purchases
```

I have already temporarily changed the StockPurchasesController to inherit from ApplicationController, so it is not an issue of access being denied. Unsure of how to proceed with testing.

**Comment by jpfriedman18** [comment]
Also tried putting a binding before the line mentioned above, and found that current_user = nil

**Comment by RealWeeks** [comment]
I miss @gaand "current_user" talk but is there currently a current user?

ref this for current user understanding:

http://stackoverflow.com/questions/12719958/rails-where-does-the-infamous-current-user-come-from

**Comment by jpfriedman18** [comment]
I suppose there isn't a current user as I am simply going to the localhost:3000/stock_purchases route. How can I set a current_user for the purpose of testing in the browser?

**Comment by GA-MEB** [comment]
One way would be to actually log in, get a token, and then pass in that token as part of a CURL request.

`current_user` works by comparing the token passed in to the list of tokens in the `users` table, and retrieving the User whose token matches.

**Comment by jpfriedman18** [comment]
Tried signing up/in with curl requests, then ran my stock_purchases script and received:
-bash: ./scripts/stock_purchases.sh: Permission denied

**Comment by GA-MEB** [comment]
Can you paste the content of that script here?

On Fri, Feb 26, 2016 at 11:39 AM, jpfriedman18 notifications@github.com
wrote:

> Tried signing up/in with curl requests, then ran my stock_purchases script
> and received:
> -bash: ./scripts/stock_purchases.sh: Permission denied
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-wdi-boston/full-stack-project/issues/128#issuecomment-189363690
> .

## 

_Matt Brendzel_
_Developer In Residence_
General Assembly - Boston | 51 Melcher Street, Boston, MA 02210
matt.brendzel@generalassemb.ly | @mattbrendzel | @GA_Boston | (215) 839 9428
http://generalassemb.ly

Join the party. Sign up for the GA newsletter
https://generalassemb.ly/locations/boston/.

**Comment by jpfriedman18** [comment]
Sign-in:

``` sh
#!/bin/bash

curl --include --request POST http://localhost:3000/sign-in \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "an@example.email",
      "password": "an example password"
    }
  }'
```

sign-out:

``` sh
#!/bin/bash
TOKEN='17f1b3866ed963114be1397b82908f93'
ID='3'

curl http://localhost:3000/sign-out/${ID} \
  --include \
  --request DELETE \
  --header "Authorization: Token token=${TOKEN}"

  echo
```

I've been updating the token each time I sign in to reflect the latest token

**Comment by jpfriedman18** [comment]
I'm receiving a 401 response when I run the sign-out script

**Comment by jpfriedman18** [comment]
SOLUTION:
- check server logs, see that request is being processed and route is correct and hitting right controller method
- check sign-out controller method, put binding at beginning of method, in console see that current_user is nil
- check applicationController (from which UserController inherits) see that current_user is set by authenticate method, but that authenticate method is not being called
- tried calling manually from within sign-out method, successfully authenticated/created current_user
- authenticate method wasn't being called because UserController inherited directly from ApplicationController (which does not authenticate before actions), but needed to inherit from ProtectedController (which does authenticate before actions)

**Comment by jrhorn424** [comment]
Permission denied indicates that whatever request you're making (in your case, `GET /stock_purchases`) needs to have a token in the header. If you're providing a token and you're still getting this error, it's because the token is invalid (the user is no longer logged in... being logged in is equivalent to having a current token).

**Comment by jpfriedman18** [comment]
current_user is not being set when I try to use it in another controller (stock_purchases_controller) and as such I cannot access stock_purchases associated with current_user by calling current_user.stock_purchases. Added a binding to index method on stock_purchases_controller and found that when the method is called, current_user is nil. How can I make sure that current_user is passed to the stock_purchases_controller?

**Comment by jpfriedman18** [comment]
Also, I tried bypassing the current_user issue by changing the index method to get a specific user's stock purchases which I already know exists:

``` ruby
def index
    @stock_purchases = User.find(2).stock_purchases

    render json: @stock_purchases
  end
```

This works when StockPurchasesController inherits from ApplicationController, but when it inherits from ProtectedController, it gives HTTP Token: Access denied.

**Comment by GA-MEB** [comment]
> current_user is not being set when I try to use it in another controller

Is StockPurchasesController inheriting from ProtectedController? Is it authenticating?

**Comment by GA-MEB** [comment]
The `HTTP Token: Access denied.` error you're getting means that StockPurchasesController is authenticating, and you've passed it the wrong token. Are you sure that the token you got when you logged in is the same as the one you're sending with your StockPurchases request?

**Comment by GA-MEB** [comment]
`Permission Denied` was coming from Bash, not the API.

**Comment by jrhorn424** [comment]
@MattB-GA-Boston So this was a `chmod` fix?

**Comment by GA-MEB** [comment]
@jrhorn424 It came from him trying run the script without specifying `bash  ...` or `. ...`

**Comment by jrhorn424** [comment]
:+1:
