### ISSUE TITLE
Rails: defining parameters in controller

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/full-stack-project#129]
I'm trying to write my controller actions and want to know how the params method works. For example, in the included users_controller, I see the create method calls on user_creds:

``` rb
  # POST '/sign-up'
  def signup
    user = User.create(user_creds)
    if user.valid?
      render json: user, status: :created
    else
      head :bad_request
    end
  end
```

Which is defined using params.require(:credentials): 

``` rb
  def user_creds
    params.require(:credentials)
      .permit(:email, :password, :password_confirmation)
  end
```

My question is, where does that :credentials key come from? Where is that defined? If I want to include parameters in my controller in the same way, would I write something like:

``` rb
def medicine_param
   params.require(:medicine).permit(:name, :unit, :notes)
end
```

?

**Comment by GA-MEB** [comment]
I can answer this.

It's a reference to how the data should be structured in the request. `require` says "make a new hash, with :credentials as the root key". `permit` says "keep only the keys specified here". Thus, the resulting hash looks like this:

``` ruby
{ credentials: { #required
     email: ..., #optional, but allowed
     password: ...,  #optional, but allowed
     password_confirmation: ...,  #optional, but allowed
} }
```

**Comment by GA-MEB** [comment]
By setting up our 'strong params' method in this way, we require that all data sent from the front-end have a root key of `credentials:` (or in your case, `medicine:`).

**Comment by GA-MEB** [comment]
@MFBrewster OK to close this?

**Comment by MFBrewster** [comment]
I haven't tested it, but your answer is clear.... so, sure!

**Comment by GA-MEB** [comment]
For the 404 error you got, it was because you tried to `set_medicine` in your `create` action; since `create` doesn't get passed an id, `set_medicine` was erroring out.

**Comment by MFBrewster** [comment]
Yeah, I had a before_action error for my index request as well, which I was able to solve after going over the POST action with you. Thank you!
