### ISSUE TITLE
I'm not sure if my models fit what I'm trying to accomplish in my app

### ISSUE THREAD

**Issue by resource11** [ga-wdi-boston/full-stack-project#13]
So... I've successfully created a one-many relationship between two tables, however, I'm not sure if I've created the models correctly to integrate with the other model (or two) that I'm looking to use for this project. 

I have the a map of the erd, yet I'm not sure my thought process is sound with respect to tying together certain relationships between users and my models. Can someone look at my erd and how I've set up my models so I can be sure I'm on track when I try more tests with dummy data?

**Comment by jrhorn424** [comment]
Could you be clearer about why you want us to look at your ERD?

If it's to boost your confidence, I'm happy to help! But if it's also in support of an example script you're writing to fill your database, could you share that script in a [gist](https://gist.github.com)? Include appropriate models and your schema as well.

**Comment by resource11** [comment]
I could use a bit of a confidence boost on how my models are relating...

Currently, I have a User model and a Bike model. Currently, a user has many bikes, and a bike belongs_to user.

I can successfully CRUD both from the backend, and Create/Read from the front end using data from the users and bikes tables. I have also successfully created user_id as a foreign key on the bikes table, and can create a new bike with a user_id designation both from the front and back end.

One of my next tasks is to be able to allow a user to favorite one bike through a Favorite model. 

I tried playing with how the user will relate to a bike as a favorite last night in the models files, and considered adding a profile model into the mix, but I broke the functionality of my user-bike relationship.

Somehow, tying those three together prevented the user_id value to populate in my bikes table once I populated my bikes table with some seed data. I then commented out what I added in the models so I could revisit how my models relate to each other without losing the progress I had made with the one user--many bikes relationship.

I do have a sketch of my ERD, so I want to be sure I'm not creating a conflict when adding another model to the mix and I'm not sure if what I already have is relating correctly on paper.

Is that clearer?

**Comment by jrhorn424** [comment]
Yes, thanks! I'll ping you when I can speak with you directly about this.

My suspicion is that you might be missing a call to `.save` after you create the association between `User` and `Bike`. Happy to look at your ERD as well, but a "conflict" is less likely.

**Comment by resource11** [comment]
OK, cool.

**Comment by jrhorn424** [comment]
The issue was that we have two associations between `User` and `Bike`. A user can own a bike, but a user can also favorite a bike. So we should use ActiveRecord to model our domain appropriately with something like:

```
# bike.rb
# ...
belongs_to :owner, class_name: 'User'

has_many :favorers, through: :favorites, class_name: 'User', foreign_key: 'user_id'
has_many :favorites
```

Some similar options were set in `User`.
