### ISSUE TITLE
Selecting random input from CSV

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/full-stack-project#130]
I have a massive CSV file of 40,000 line that I'm trying to reduce to a more practical size for testing and for uploading to Heroku. I would like to grab the header from the original CSV file and then grab a arbitrary number of random lines (excluding the header!) and output them to a new CSV. The code I've written works except that it seems to overwrite the header in the new CSV. Also it's clunky. Is there a better way to do this?

```
require 'csv'
data_file = '../data/catalog.csv'
new_file = '../data/catalog2.csv'

def random_lines(input_file, output_file, num)


  old_csv = CSV.open(input_file, 'r', col_sep: ';', headers: true)
  new_csv = CSV.open(output_file, 'a+', col_sep: ';', headers: old_csv.headers)

  rows = old_csv.to_a.slice(1..-1)
  random_rows = rows.sample(num)

  random_rows.each do |row|
    new_csv << row
  end

end
```

**Comment by gaand** [comment]
Would you please explain what you mean by "overwrite the header in the new CSV"? Please show an example.

As to "is there a better way".  Possibly, but if you get it to work correctly, I don't think figuring that out is a good use of your time (at least until you've implemented the requirements).

**Comment by rchezrutt88** [comment]
Yeah, forget it. I’ve moved on. Basically, it wasn’t writing the header to the new target table because I set header==true on the source table and thus that line was being ignored. 

I’ll close the issue.

**Comment by gaand** [comment]
@rchezrutt88 Would you please close this issue?  Thanks.

**Comment by rchezrutt88** [comment]
Nonetheless, it might be instructive if we could work through this problem together? The problem itself is trivial but I’m concerned that my confusion stems from a deeper confusion about Ruby syntax. If we worked through it together, my hope would be that I might avoid a lot of other difficulty going forward.

**Comment by gaand** [comment]
I don't see anything in the code to indicate confusion about ruby syntax.  You could write `slice(1..-1)` as `[1..-1]` but that's a style thing, see: http://ruby-doc.org/core-2.2.4/Array.html#method-i-5B-5D
