### ISSUE TITLE
1 on 1 with Antony: Discussing ERD and problems

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/full-stack-project#132]
Continuing on our first conversation about my project. Sharing what I've learned and what I'm struggling with as well as asking for advice on possible change to ERD.

**Comment by gaand** [comment]
Antony without and 'h' :-).

**Comment by kpie89** [comment]
I’m sorry! I edited it immediately after I posted it.

**Comment by gaand** [comment]
Do you want to get a conference room?  If so I'll schedule one.

Also, please post your ERD to this issue.  Thanks.

**Comment by gaand** [comment]
Would you like to get a conference room, or can we chat in here?  I'll schedule one if that's your preference.

Also, please post your ERD to this issue.  Thanks.

**Comment by kpie89** [comment]
We can chat in here.

**Comment by gaand** [comment]
Do you have an ERD image?
