### ISSUE TITLE
CSV file question

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/full-stack-project#134]
Hi, 

I want to associate my data in my meals.csv file with certain restaurants. What would be the best way to do this?

**Comment by GA-MEB** [comment]
Hey! Sorry for the holdup. My recommendation would be to do the association in Ruby, rather than hard-coding it in your CSV file.

The reason for this is that if there is existing data in the database when you load this seed data, the hard-coded ids will not be correct. 

Since you'll presumably be using a Ruby script to load the CSV file and plug it into `Meal.create` and `Restaurant.create`, just add some additional Ruby code to handle all of the associations there.

**Comment by jrhorn424** [comment]
Can you describe more of what you intend? When I think "associations", I think database, not CSV file. If you want to fill in the database with records from a CSV, you can do that in a seed or example file (depending on whether or not the data is required for the app to work). Then, after importing the CSVs, you can associate the records more easily using ActiveRecord. You can for example search for a restaurant by name and then associate it with a meals by id, or whatever combination works best for your application.

**Comment by gaand** [comment]
@Knguyen21: Do you still need assistance with this issue?

**Comment by Knguyen21** [comment]
Yes.. I haven't got a chance to look at it because I have other issues to fix. Can I put this on hold?

**Comment by gaand** [comment]
Sure.  I just wanted to make sure this wasn't forgotten.

**Comment by Knguyen21** [comment]
Is it okay if I do rake db:populate?

**Comment by GA-MEB** [comment]
In what context? Locally? On Heroku?

**Comment by Knguyen21** [comment]
locally?

**Comment by GA-MEB** [comment]
Yes, you can absolutely use `rake db:populate` (assuming you've set up the rake task) to populate data locally. In production (i.e. Heroku), you'll probably want to use `rake db:seed`.

**Comment by jrhorn424** [comment]
If you use the template, `rake db:examples` will run the script your write in `db/examples.rb`, `rake db:seed` runs the script you write in `db/seeds.rb`. Seeds are only for necessary data. If you want to use seeds, think twice and check with a consultant. You probably want examples.

To run your examples on heroku, do `heroku run rake db:examples`.

**Comment by Knguyen21** [comment]
I have my restaurant's data(3 restaurants) in the examples.rb. My meals ( a lot of data) in data/meals.csv.  How can I run the meals.csv?

**Comment by jrhorn424** [comment]
You don't run a CSV file. Did you write a script somewhere to load the CSV using ruby? How did you load the CSV previously? Or is this the first time?

If it's the first time, @gaand had a lesson where he loaded data from a CSV file. I'd start there.

**Comment by Knguyen21** [comment]
I wrote rake db:drop db:create db:migrate and it caused a lot of error in my console.
`PG::ObjectInUse: ERROR:  database "menu-review-api_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
: DROP DATABASE IF EXISTS "menu-review-api_development"`

in my db.rake file I wrote: 

``` rake
 namespace :db do
  desc "Load example data from db/examples.rb"
  task examples: :environment do
    require_relative '../../db/examples'
  end

  unless Rails.env == "production"
    desc "Drop and setup the development database with examples"
    task nuke_pave: %w(environment db:drop db:create db:migrate db:seed db:examples) do
      puts "Nuke and pave of #{Rails.env} complete."
    end
  end
end


require 'csv'
namespace :db do
  namespace :populate do
    desc 'Fill the meals table with meal data'
    task meals: :environment do
      Meal.transaction do
        CSV.foreach(Rails.root + 'data/meals.csv',
        headers: true) do |meal_row|
          meal = meal_row.to_hash
          next if Meal.exists? meal
          Meal.create!(meal)
        end
      end
    end
  end
end
```

**Comment by Knguyen21** [comment]
Thanks matt for your help!
