### ISSUE TITLE
RSpec issues

### ISSUE THREAD

**Issue by apalmer0** [ga-wdi-boston/full-stack-project#135]
1) when trying to test a POST request, I'm only able to pass the test when I don't use a hash... but the example tests all seem to require that syntax. Specifically:

this fails:
`post '/gyms', { gym: gym_params }, headers`

but this passes:
`post '/gyms', gym_params, headers`

For my own knowledge, can someone help me understand why?

2) I'm trying to test to ensure that a climb cannot be created without an associated gym, following exactly the same pattern that was used for the comments -> articles relationship example (one gym has_many climbs, climbs belong_to one gym, etc). I'm not sure where in the article_comments example we required a token but creating a comment was only possible for an authenticated user... I'm trying to create the same system and restrictions for creating climbs, but I think I'm missing where to specify that token.

**Comment by GA-MEB** [comment]
1) The two requests are not passing the same data. Since this is happening on a POST request, I suspect that this may have something to do with your 'strong params' method; that method ensures the data hash has a particular structure.

2) You could specify a NOT NULL constraint on the `gym_id` column in the `climbs` table - that would ensure that you could not create a climb without an associated gym. I'm not sure how tokens and auth tie into your question.

**Comment by jrhorn424** [comment]
> this fails:
> `post '/gyms', { gym: gym_params }, headers`

This could happen if `gym_params` looks like this:

``` ruby
def gym_params
  {
    gym: {
      foo: 'bar'
    }
  }
end
```

Since the `post` method call would evaluate to `gym: { gym: { foo: 'bar' } }`.

**Comment by apalmer0** [comment]
1) in my controller, i had the gym_params set up as:
`params.permit(:name, :city, :state)`
this generates a hash of the structure:
`{:name, :city, :state}`

the test was looking for a hash of the structure:
`{ gym: {:name, :city, :state} }`

in order to fix this, i switched the test back to jeff's example and updated the structure of my gym params in the gyms controller.

2) in the post request of the climbs test, it was failing bc it lacked a token. it was looking for a token in the first place because i had copied/pasted too liberally and didn't realize that i had set up the climbs controller to inherit from the protected controller, which prevented access on everything but index and show. in order to fix this i'll have to follow jeff's articles controller spec example and 1) create a user in the spec, and 2) update the header to include a token before the post/patch/delete tests using the following, from the article controllers test:

```
before(:each) do
   request.env['HTTP_AUTHORIZATION'] = "Token token=#{user.token}"
end
```

**Comment by jrhorn424** [comment]
:+1:

**Comment by apalmer0** [comment]
I tried adding that chunk of code to the spec, but now I'm getting an error telling me that `request` isn't defined.

```
Gym Climbs API when authenticated POST /gyms/:id/climbs creates a climb in a given gym
     Failure/Error: request.env['HTTP_AUTHORIZATION'] = "Token token=#{user.token}"

     NoMethodError:
       undefined method `env' for nil:NilClass
     # ./spec/requests/gym_climbs_spec.rb:80:in `block (3 levels) in <top (required)>'
```

Also - I'm having trouble understanding what the difference between the article_comments_spec and comments_spec would be... since comments can't exist without an article, wouldn't you necessarily have to add an article into your comments spec, effectively turning it into article_comments_spec?

**Comment by jrhorn424** [comment]
You can't use `request.env['HTTP_AUTHORIZATION'] = "Token token=#{user.token}"` in request specs. You have to use the pattern from the `spec/requests/articles_spec.rb`. I defined a headers method that returned a hash.

**Comment by gaand** [comment]
@apalmer0:  Do you still need assistance with this?  If so, please comment.  If not, please close.  Thanks.

**Comment by apalmer0** [comment]
I'd still like to understand my second question- aren't  article_comments_spec and comment_spec essentially doing the same thing?

**Comment by gaand** [comment]
Comments are created and listed in the context of an article, but are updated, shown and destroyed by id.  So you need to know the associated article (really the id) to list or create a comment, but not to update, show, or destroy.

So article_comments_spec tests creating and listing comments in the context of a known article, but comment_spec tests showing, updating, and destroying a comment, no article needed.

**Comment by apalmer0** [comment]
Ah okay, that makes sense. Thanks!
