### ISSUE TITLE
Javascript Handlebars confusion

### ISSUE THREAD

**Issue by dumplingpuff** [ga-wdi-boston/full-stack-project#136]
So in the screenshot below is how the json data is being spit out.  When I use handlebars I notice I have to use double block {{#}}{{/}} expressions to access the keys such as restaurant, id, and etc...  Is there a clean way of spitting out the data without the extra "entries" or accessing the data more efficiently?

![screenshot from 2016-02-26 14-53-49](https://cloud.githubusercontent.com/assets/14882368/13363696/c6dbe1d8-dc98-11e5-86bb-bd3e6d34eba1.png)

**Comment by jrhorn424** [comment]
@dumplingpuff Please add a snippet of your actual handlebars template.

**Comment by jrhorn424** [comment]
Also, show me the snippet of code where you are passing data to the template.

**Comment by dumplingpuff** [comment]
Ajax.js is handling the data, it is point to the entry.handlebars, and that points to the partial entry-listing.handlebars
![handlebarissue](https://cloud.githubusercontent.com/assets/14882368/13364022/9f4d326e-dc9a-11e5-8627-2821be5559c9.png)

**Comment by gaand** [comment]
Please put in the code as text in code blocks.

**Comment by dumplingpuff** [comment]
**edited by @jrhorn424**

``` js
let getEntries = function(){
  $.ajax({
    url: "http://localhost:3000/entries",
    method: 'GET',
    dataType: 'json'
  }).done(function(entries){
    displayEntries(entries);
    console.log(entries);
  });
};

let displayEntries = function(entries){
  let entryListingTemplate = require('./entry-listing.handlebars');
    $('.my-entries').append(entryListingTemplate({entries}));
};
```

``` handlebars
<div>
  {{#entries}}{{#entries}}{{>entry}}{{/entries}}{{/entries}}
</div>
```

Partial:  entry-listing.handlebars

``` handlebars
<div>
  {{id}}
  {{restaurant}}
</div>
```

**Comment by jrhorn424** [comment]
Backticks have to be followed by a newline. Please also indicate the extension after the opening backticks. Click "edit" on your comment to see the format that is needed.

**Comment by RealWeeks** [comment]
`{{#entries}}{{#entries}}{{>entry}}{{/entries}}{{/entries}}`

why do you open entries twice? are you trying to use ``{{#each}}` ?

**Comment by RealWeeks** [comment]
this is what i did in the book example:

```
<div>
  {{#books}}{{> book}}{{/books}}
</div>
```

and this was the partial:

```
<div>
  {{#if desc}}
    {{desc}}
  {{else}}
    No description.
  {{/if}}
</div>
```

**Comment by jrhorn424** [comment]
If you inspected `entries` in this snippet:

``` js
let displayEntries = function(entries){
  let entryListingTemplate = require('./entry-listing.handlebars');
    $('.my-entries').append(entryListingTemplate({entries}));
};
```

You'd see that it looks like this: `{ entries: [ ... ] }`. I'd change the named argument `entries` to `response`, and then access the `entries` key in response.

``` diff
- let displayEntries = function(entries){
+ let displayEntries = function(response){
  let entryListingTemplate = require('./entry-listing.handlebars');
-    $('.my-entries').append(entryListingTemplate({entries}));
+    $('.my-entries').append(entryListingTemplate({response.entries}));

};
```

**Comment by jrhorn424** [comment]
@J-Weeks I'm almost certain its a root key issue.

**Comment by RealWeeks** [comment]
@jrhorn424 okay, I got caught up on the handlebars syntax issue

**Comment by jrhorn424** [comment]
@J-Weeks I think that's valid syntax for the data format he had.

**Comment by gaand** [comment]
I'm going to look it over.

**Comment by RealWeeks** [comment]
@jrhorn424 `{{#entries}}{{#entries}}{{>entry}}{{/entries}}{{/entries}}` Enteries twice?

**Comment by gaand** [comment]
@jrhorn424 was correct.  A root key issue.

**Comment by dumplingpuff** [comment]
For future problems my code for solution

``` js
let displayEntries = function(response){
  let entries = response.entries
  let entryListingTemplate = require('./entry-listing.handlebars');
    $('.my-entries').append(entryListingTemplate({entries}));
};
```

*note: the entries variable when passed into the object will also serve as a key
It is equivalent to 

``` js
entries: response.entries
```

**Comment by RealWeeks** [comment]
@jrhorn424 for my own clarification can you comment on the entires?

**Comment by jrhorn424** [comment]
@J-Weeks What isn't clear?
