### ISSUE TITLE
Planning using a third party api

### ISSUE THREAD

**Issue by dumplingpuff** [ga-wdi-boston/full-stack-project#137]
I am thinking of using a yelp api to automatically populate pictures and other data however I feel my current ERD doesn't accommodate this as well and will this be a feature that is out of my scope?

**Comment by jrhorn424** [comment]
If you're just querying to get pictures, I don't think you'll need to adjust modeling. We can discuss if you'd like.

**Comment by jrhorn424** [comment]
I wouldn't add a yelp feature until all your other features are complete.

**Comment by dumplingpuff** [comment]
I just want to be lazy and auto-populate pictures to my journal entry posts instead of manually adding it.  I thought yelp api would help to make it work and look nicer.  I can table this topic for a later discussion once I get parts working.

**Comment by gaand** [comment]
@dumplingpuff: Would you please close this issue and reopen (or create a new one) when you get to there?  Thanks.
