### ISSUE TITLE
Table Issue

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/full-stack-project#138]
I am using this code:

```
let table = document.getElementById('bankroll-updates-table')
let myDate = new Date();
myDate.setDate(myDate.getDate());
for(var i = 0; i < 7; i++) {
    let row = document.createElement('tr');
    let cell = document.createElement('td');
    cell.innerText = (myDate.getMonth() + 1) + "/" + myDate.getDate() + "/"  + (myDate.getYear() - 100);
    myDate.setDate(myDate.getDate() + 1);
    row.appendChild(cell);
    table.tBodies[0].appendChild(row);
};
```

to represent getting the current date and applying into the date column on my table. The dates are spit out correctly, but 7 new cells are added to the bottom of my already existing 7 empty cells. I tried to use jQuery to grab the cells and have the dates fill into those cells but it broke the page. Any clue on how I can get those 7 correct cells to replace my empty 7 cells above them?

![screenshot from 2016-02-26 15-25-52](https://cloud.githubusercontent.com/assets/16493127/13364528/498427f4-dc9d-11e5-9c36-6ebe6bb13def.png)

**Comment by gaand** [comment]
You're appending not updating.

**Comment by jdamiron** [comment]
what is the correct function to update rather than append? I tried updateChild but it isn't a function in JS.

**Comment by jdamiron** [comment]
I am trying replaceChild but it requires two arguments. Not sure what to do to fulfill that.

**Comment by jdamiron** [comment]
@gaand

**Comment by gaand** [comment]
You probably need to find the `td`s then set their text.

**Comment by jdamiron** [comment]
@gaand I'm not sure I understand how to do that. When I think of setting text, I think of the .val(setTextHere) method and as soon as I attempt to grab the original date fields using jQuery, the app breaks, sometimes with no errors.

**Comment by RealWeeks** [comment]
find the td you want to alter and replace it with the correct data. Appending just adds to the bottom.

**Comment by RealWeeks** [comment]
refer to the jquery lesson https://github.com/ga-wdi-boston/jquery-dom

**Comment by jdamiron** [comment]
Having the code that I have, I don't understand how I would do that. I can grab the correct fields in the table using jQuery but can't set them with the correct dates. What would I need to change in the code that I provided earlier? What is right in the code, what is wrong?

**Comment by jdamiron** [comment]
@J-Weeks I also understand why append is wrong, and would like to use replaceChild, but I set a variable to grab the empty field and set that as the second argument but get an error that says, the second argument isn't the correct "type" for the replaceChild function.

**Comment by RealWeeks** [comment]
Try using another method maybe .find()?

https://api.jquery.com/find/

**Comment by RealWeeks** [comment]
Also I'd recommend using jQuery, you're using alot of vanilla.

**Comment by RealWeeks** [comment]
Refactored vanilla to jquery. Wrapped grabbed element index and jquery and incremented.

**Comment by jdamiron** [comment]
Correct Code:

```
let setupTable = function(){
  let table = $('#bankroll-updates-table');
  let myDate = new Date();
  myDate.setDate(myDate.getDate());
  for(var i = 0; i < 7; i++) {

      let currDate = (myDate.getMonth() + 1) + "/" + myDate.getDate() + "/"  + (myDate.getYear() - 100);
       myDate.setDate(myDate.getDate() + 1);
      $($('.date-column')[i]).html(currDate);
  };
}

$(document).ready(function(){
  setupTable();
});
```

**Comment by MaxBlaushild** [comment]
DO NOT TRUST JASON WEEKS #ghostinashell
