### ISSUE TITLE
config/database.yml

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/full-stack-project#139]
My database.yml is displaying some errors in the atom. I don't know why it's making the error.
![image](https://cloud.githubusercontent.com/assets/16465193/13365207/aa2ef47c-dca1-11e5-95af-0b40ec7c87a8.png)

```<% project_name = 'menu-review-api' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= project_name %>_development

test:
  <<: *default
  database: <%= project_name %>_test ```

**Comment by gaand** [comment]
Nick has a similar message. Please search the closed issues to find his resolution.
