### ISSUE TITLE
I cannot access my tables through Curl

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/full-stack-project#14]
It's not even hitting my database.  Trying to use the curl commands in the README for the api.  Grabbing a token from the server and plugging it in.

My controllers are inheriting from OpenReadController and at least Locations worked when it was inheriting from ApplicationController

**Comment by jrhorn424** [comment]
More information would be helpful. Please paste your commands and your output in a [gist](https://gist.github.com). Also include appropriate code, like an example controller.

Which table can you not access? What is the curl command you are using? What are your routes? Show the controller the route is connecting to.

**Comment by jcmeyer10** [comment]
https://gist.github.com/jrhorn424/cc76cc9e4e8c9fe8ca49

**Comment by jrhorn424** [comment]
There were several issues with your `curl` command.

```
curl --request POST --header "Authorization: Token token="d168c8333a2b72bf7ad7bfe4bb9c669d" # snip ... #
```

You can't nest double-quotes in an argument. You should begin your argument to `--header` with a single-quote, and also end it with a single quote.

```
curl --request POST --header 'Authorization: Token token="d168c8333a2b72bf7ad7bfe4bb9c669d"'
```

```
# snip ... -d 
'{
  "beer": {
    "name":"UFO"
    "brewery":"Harpoon"
    "style":"Hefe"
    "location_id":"11"
  }
}' 
```

You are missing all your commas in this JSON.

```
# snip ... -d 
'{
  "beer": {
    "name":"UFO",
    "brewery":"Harpoon",
    "style":"Hefe",
    "location_id":"11"
  }
}' 
```

**Comment by jrhorn424** [comment]
You were also missing an association in your models.

`undefined method beers` indicated that `User` needed to have `has_many :beers` defined.

**Comment by jrhorn424** [comment]
You were also missing an association in `Beer`. if `User` `has_many :beers`, then `Beer` should `belongs_to :user`.
