### ISSUE TITLE
Create new item with associated id

### ISSUE THREAD

**Issue by seatuna** [ga-wdi-boston/full-stack-project#141]
I have a stores table and drinks table, one store has many people.  I ran my curl script for create, and it works.  However, I can't get the store_id foreign key to populate.

I ran my create script and got this:

``` json
// edited by @jrhorn424
{
  "drink": {
     "id":15,
     "name": "Taro Milk Tea",
     "ingredients":"Taro powder, milk, green tea",
     "toppings":"Tapioca pearls",
     "notes": "Taro is a root veggie.",
     "store":null
  }
}
```

I want to be able to enter a store name (example:  'Kung Fu Tea'), and for the association to be created as well (so "store_id" column would automatically populate with the id matching store.name 'Kung Fu Tea')

Do I need to edit the create method?  My idea is somehow getting it to run 
Store.find_by(name:'Kung Fu Tea').drinks.new(name:'coffee'), but I'm not sure where to put it.  I would also need to change 'Kung Fu Tea' into a variable?  

I hope I'm on the right track here!

This is what I have for def create:

``` ruby
  def create
    @drink = Store.find_by(name:"")drinks.new(drink_params) 

    if @drink.save
      render json: @drink, status: :created, location: @drink
    else
      render json: @drink.errors, status: :unprocessable_entity
    end
  end
```

and my drink_params:

```
  def drink_params
    params.require(:drinks).permit(:name, :ingredients, :toppings, :notes, :store_id)
  end
```

backticks added by @gaand

**Comment by gaand** [comment]
There seems to be a `.` missing in the `@drink = ...` line.  Unless it's a copy and paste error.

**Comment by RealWeeks** [comment]
@seatuna Was this resolved?

**Comment by seatuna** [comment]
Yes! I will close :)
