### ISSUE TITLE
Problem querying back-end from front end

### ISSUE THREAD

**Issue by jpfriedman18** [ga-wdi-boston/full-stack-project#142]
When trying to sign in from front end, console shows the following error:

XMLHttpRequest cannot load localhost:3000/sign-in. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

All routes and methods have been checked on back-end and are functional, so it's not a back-end issue. Unsure of what needs to be changed in order for the request to work

**Comment by RealWeeks** [comment]
are you passing the right headers?

**Comment by gaand** [comment]
You'll usually get this error following the actual error.

Is there an error in the console above the one you pasted in?

**Comment by jpfriedman18** [comment]
Solved: this was a flagrant oversight on my part, my base URL did not include http://
