### ISSUE TITLE
PATCH Request 204 No Content

### ISSUE THREAD

**Issue by seatuna** [ga-wdi-boston/full-stack-project#143]
I ran my curl script for PATCH, and I get a "204 No Content" message.  I checked in rails console and server, the change from the PATCH went through.  Is a 204 No Content message ok to get or will I come across problems later on?

**Comment by gaand** [comment]
What's the code in your update action?

**Comment by seatuna** [comment]
`#!/bin/bash

curl --include --request PATCH http://localhost:3000/drinks/11 \
  --header "Authorization: Token token=f1db76d1212437a43dd1fae030b4d39d" \
  --header "Content-Type: application/json" \
  --data '{
    "drinks": {
      "name": "Taro Milk Tea",
      "ingredients": "Taro",
      "toppings": "Tapioca pearls and more!",
      "notes": "Taro is a root veggie",
      "store_id": "3"
    }
  }'
`

**Comment by seatuna** [comment]
`  def update
    @drink = Drink.find(params[:id])

```
if @drink.update(drink_params)
  head :no_content
else
  render json: @drink.errors, status: :unprocessable_entity
end
```

  end`

**Comment by gaand** [comment]
So, you're code specifies that no data should be sent, `head :no_content`, but only when the update is successful (the changes are saved to the database).  So I don't see why that would cause problems.  Now or later.  You could render the updated drink as json, if that's useful.

**Comment by seatuna** [comment]
Thanks!
