### ISSUE TITLE
Creating an Admin

### ISSUE THREAD

**Issue by dumplingpuff** [ga-wdi-boston/full-stack-project#144]
I have a question about creating user data for the admin.  For my site I want to have preloaded user data for the admin.  What way would you recommend going about this?  Should I store the information in a csv file?

**Comment by gaand** [comment]
To preload the admin, I'd use `db/seed.rb`.  Don't store the admin's password there or in any other file you check into git.  I'd set the admin's password using the rails console.

You can put something like:

``` ruby
User.create! email: 'foo@bar.com', admin: true`
```

directly in the seed file.  Make sure to exclude `:admin` from the params permit list in the controller.

**Comment by dumplingpuff** [comment]
Thanks, Antony!  I'll close the issue and try it out.
