### ISSUE TITLE
Requested 1:1 for Monday

### ISSUE THREAD

**Issue by jenweber** [ga-wdi-boston/full-stack-project#145]
I would like to check in with someone on Monday to figure out where to focus the time that remains. As of Saturday night, I have a bootstrap tabbed-navigation blog that GETs data from the server and renders it using handlebars. Admin login via form works but doesn't do anything yet.

Edit: as of Sunday night, an admin can login and do all POST functionality.

[Front-end repo and user stories](https://github.com/jenweber/plot-point-o-front-end)
[API](https://github.com/jenweber/plot-point-o-api)
[Wireframes and ERDs](https://drive.google.com/folderview?id=0BxL5EMSDOzzwQkVNQkN6N1VVWFU&usp=sharing)

Thanks!

**Comment by gaand** [comment]
I was just editing the issue for markdown syntax :-).
