### ISSUE TITLE
Error bulk uploading csv file

### ISSUE THREAD

**Issue by seatuna** [ga-wdi-boston/full-stack-project#146]
ERROR:  null value in column "created_at" violates not-null constraint

``` psql
\copy drinks(name,ingredients,toppings,notes,store_id) FROM 'data/drinks.csv' WITH (HEADER true, FORMAT csv)
```

**Comment by gaand** [comment]
You should load the data using ActiveRecord. It will make sure those columns are set correctly.

**Comment by rchezrutt88** [comment]
@seatuna I spent WAY too much time trying to wrap my mind around the ruby CSV class the other day. Good use of my time? No. Did I learn a thing or two and could I possibly help you out as a result? Yeah! 

Are you going into GA today?

**Comment by rchezrutt88** [comment]
The problem here is that you've created your tables using Rails, which specifies and enforces a "created_at" column by default. Now you're trying to load data into that table directly using Postgres, thus bypassing all the Rails machinery that generates and inserts that created_at data.

**Comment by rchezrutt88** [comment]
HINT 
Take a look at the custom rake tasks in the solution branch of the rails-activerecord-crud repo
https://github.com/ga-wdi-boston/rails-activerecord-crud/blob/solution/lib/tasks/db.rake

**Comment by seatuna** [comment]
Thanks Antony and Robert! It worked! I need a break from the building, so I won't be in today!
