### ISSUE TITLE
handlebars if statements

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/full-stack-project#147]
Hi, 

I'm trying to user Handlebars to display the meal items in the meal model with restaurant_id(foreign key) of a certain number, e.g. 1. I tried using the each and if statements in handlebars, but it doesn't work. I don't know how I can do equality statements in handlebars. I can only display every single meals from all restaurants. 

Do you know how I can do something like this: 
for each meals
if restaurant_id === 1
display meal_type, name, desc, and price.

**Comment by gaand** [comment]
If you want to display only one meal, you want a template designed to do only that and then pass just one meal to the template from javascript.

**Comment by Knguyen21** [comment]
I want to display meals from only a specific restaurant.

**Comment by Knguyen21** [comment]
Would creating my own registerHelper be a good idea?

**Comment by gaand** [comment]
Search for meals by restaurant and render only those in the controller.  Then pass those meals to handlebars.  Don't get data from the API you don't want to display in the client.

Retrieving comments within articles from Jeff's lesson may help you figure out what to do in rails.

**Comment by Knguyen21** [comment]
Thank you!
