### ISSUE TITLE
Assigning id to column in my database from third party API

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/full-stack-project#148]
I'm pretty sure I'm completely off track here. 

```
current_user.ratings.build(beer_id =>  'something' - possibly a method like 'set_beer')
```

I have a beer_id column in my ratings table and I need to assign the id from the beer returned from breweryDB. I have no idea what params to give it because there is no beer table it can communicate with in my database, but rather it retrieves the data from the BreweryDB.

**Comment by kpie89** [comment]
I'm having trouble finding good info on the problem. I'm not even exactly sure what to google. The pages I've seen so far don't really address my problem.

**Comment by gaand** [comment]
Don't you have the beer_id returned from BreweryDB when you invoke create for ratings?  If so, then send it to the create action and permit it in the rating_params

Assign the return from build to a variable so you can save it.

**Comment by kpie89** [comment]
Well the beer id (beer.id) is sent back from BreweryDB from this function:

```
  let randomBeer = function(){
    $.ajax({
      url: myApp.BASE_URL + '/beer/random',
      method: 'GET',
      dataType: 'json'
    }).done(function(beer){
      console.log(beer);
      displayBeer(beer);
    }).fail(function(jqxhr) {
      console.error(jqxhr);
    });
  };
```

Then if the user click "Yes, I'll rate it" a form pops up and they rate it. On submit of that form, another AJAX request fires that creates the rating. 

So I guess I have to somehow store the beer id from the randomBeer request and attach it to the rating via formdata or something?

**Comment by jrhorn424** [comment]
Or you can store it in memory. Did you create a `game` object and store data on it in the TTT project? How did you store `user.token` and `user.id` in that project?

**Comment by gaand** [comment]
Please show the code that creates a rating.

**Comment by gaand** [comment]
Sorry, the client code.

**Comment by kpie89** [comment]
```
  $('.rating').on('submit', function(e) {
    e.preventDefault();
    console.log('here');
    let formData = new FormData(e.target);
    $.ajax({
      url: myApp.BASE_URL + '/ratings',
      method: 'POST',
      headers: {
        Authorization: 'Token token=' + myApp.user.token,
      },
      contentType: false,
      processData: false,
      data: formData,
    }).done(function(data) {
      myApp.user = data.user;
      console.log(data);
      $('.rating').hide();

    }).fail(function(jqxhr) {
      console.error(jqxhr);
    });
  });
```

**Comment by kpie89** [comment]
So something like defining const = beerData {};

and then in my randomBeer function saying 

```
beerData.id = beer.id 

```

And then using beer.id in my createRating function. I'm assuming with formData.append()?
I think that's what you're getting at Jeff?

**Comment by gaand** [comment]
Or you could use a hidden form field to hold the data.  

You're displaying the beer, so you could save the beer id in a `data-` attribute (e.g. `data-beer-id`) or an object then add it to the rating form or use `.append`. on submit.

Too many options?  :-).

**Comment by jrhorn424** [comment]
Yes, that's what I'm driving at.

**Comment by jrhorn424** [comment]
@gaand Does `.append` work with FormData?

Answered my own question. @kpie89, what @gaand is suggesting is to append the beer id onto the formdata object when you make the request. Here's the API method he mentioned. https://developer.mozilla.org/en-US/docs/Web/API/FormData/append

**Comment by RealWeeks** [comment]
It does, make sure not to use set.  I wasn't reading clearly and use it this weekend myself and had a bad time.

**Comment by jrhorn424** [comment]
@kpie89 If you're back on track with this, would you please close it? Thanks.

**Comment by kpie89** [comment]
Thanks all!
