### ISSUE TITLE
CRUD q 

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/full-stack-project#15]
Similar question to Jeff's earlier; I've gone through the lessons and I think I just need to run through CRUD as it relates to my project with someone. One specific issue: Because I added conditions to the queries in my models (I think this is maybe the right way to say that?) I don't know which words to point to in my routes. Or, here are my models and I don't know if I should get sites or my_sites, etc.:

class User < ActiveRecord::Base
  has_many :my_sites, class_name: 'Site'
end

class Site < ActiveRecord::Base
  belongs_to :creator, class_name: 'User'
end

Sorry -- this isn't elegantly asked.

**Comment by gaand** [comment]
Helping.

**Comment by gaand** [comment]
Resolved.  Walked through controllers actions using activerecord record.
