### ISSUE TITLE
Issues with displaying data

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/full-stack-project#150]
I need help trying to display only meals that have a specific meal_type. Each Restaurant has a Menu w/ 3 meal types: breakfast, lunch and dinner. And I want o put many meals in each meal_type. However,  I only have one model call Meals that have attributes( name, meal_type, desc, price, and restaurant_id (foreign key).. Should I change the routes/ controllers ?

**Comment by gaand** [comment]
You want to search by meal_type?  You can pass a parameter to the controller (e.g. `/meals?meal_type=breakfast`) and then limit your search based on that (e.g. `Meal.where meal_type: params[:meal_type]`.

**Comment by Knguyen21** [comment]
Would I pass the parameter in Meals controller's index method?

**Comment by gaand** [comment]
In your ajax request, something like:

``` js
  url: baseUrl + '/meals?meal_type=breakfast',
```

In your controller, something like:

``` ruby
  @meals = Meal.where meal_type: params[:meal_type]
```

**Comment by Knguyen21** [comment]
Thank you!
