### ISSUE TITLE
Stylesheet link: weird console error

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/full-stack-project#151]
When my page loads I am getting this back from the console. 

```
Navigated to http://localhost:8080/
localhost/:8 Resource interpreted as Stylesheet but transferred with MIME type text/x-scss:
"http://localhost:8080/assets/styles/index.scss".
```

It's not causing any problems, but I would like to know what it means and how it might affect my code.

**Comment by gaand** [comment]
What's the output of `grunt serve`?

**Comment by RealWeeks** [comment]
@MFBrewster was this issue resolved?

**Comment by jrhorn424** [comment]
@MFBrewster This is related to one of the things we reviewed in your TTT project.

You cannot link `scss` files in the head of your HTML documents. The browser doesn't know what to do with sass files. Instead, remove the link. The tooling takes care of loading your sass for you.

**Comment by MFBrewster** [comment]
That took care of it, thank you
