### ISSUE TITLE
1:1 meeting

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/full-stack-project#152]
Hi, 
Can I have a 1:1 meeting? I'm starting to realize that my project is more complicated than I anticipated.  Since there are only 2 days left to work on the project, I'm worried I won't finish on time. I would like to know if I should change anything in my project in order to make it more manageable. Or any advice on what I should focus on to complete the project.

**Comment by jrhorn424** [comment]
@Knguyen21 When can you meet?

**Comment by Knguyen21** [comment]
Can we meet at 10:00?

**Comment by jrhorn424** [comment]
Sure!

**Comment by jrhorn424** [comment]
I think you're on the right track @Knguyen21. Try some of the things we discussed and get back to us if you run into issues. Would you please close this for now and open new issues as they come up?
