### ISSUE TITLE
Getting form values into ajax url

### ISSUE THREAD

**Issue by seatuna** [ga-wdi-boston/full-stack-project#154]
I'm trying to POST to stores/:id/drinks (drinks route is nested under stores in my routes.rb)

I'm having trouble getting the store_id into the url in my ajax for posting a new drink.  Currently, upon submission of the form, the information shows up as a long string in the url field of my browser instead of actually creating a new drink.

``` js
let $store_id = $('#add-drink').submit(function() {
$("input[name='drinks[store_id]']").val();
});

  // Create drink
let createDrink = function(e) {
  console.log('add drinks button works');
  let url = bubbleTea.baseUrl + '/stores/' + $store_id + '/drinks';
  console.log(url);
  e.preventDefault();
  let formData = new FormData(e.target);
    $.ajax({
      url: bubbleTea.baseUrl + '/stores/' + $store_id + '/drinks',
      headers: {
        Authorization: 'Token token=' + bubbleTea.user.token,
      },
      method: 'POST',
      contentType: false,
      processData: false,
      data: formData,
    }).done(function(data) {
      console.log(data);
      console.log('Drink created!');
    }).fail(function(jqxhr) {
      console.error(jqxhr);
    });
};
```

``` html
<!-- Create drink modal -->
<div class="modal fade" id="addDrinkModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close"
                   data-dismiss="modal">
                       <span aria-hidden="true">&times;</span>
                       <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    Add Drink
                </h4>
            </div>

            <!-- Modal Body -->
            <div class="modal-body">

                <form class="form add-drink" id='add-drink' role="form">
                  <div class="form-group">
                    <label for="addName">Name</label>
                      <input type="text" class="form-control" name="drink[name]"/>
                  </div>
                  <div class="form-group">
                    <label for="addIngredients">Ingredients</label>
                      <input type="text" class="form-control" name="drink[ingredients]"/>
                  </div>
                  <div class="form-group">
                    <label for="addToppings">Toppings</label>
                      <input type="text" class="form-control" name="drink[toppings]"/>
                  </div>
                  <div class="form-group">
                    <label for="addNotes">Notes</label>
                      <input type="text" class="form-control" name="drink[notes]"/>
                  </div>
                  <div class="form-group">
                    <label for="addStoreId">Store ID</label>
                      <input type="text" class="form-control" name="drink[store_id]" id="storeId"/>
                  </div>
                  <button type="submit" class="btn btn-default">Submit</button>
                </form>


            </div>

            <!-- Modal Footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">
                            Close
                </button>
            </div>
        </div>
    </div>
</div>

<!-- End create drink modal -->
```

This is what appeared in my browser's url after I submitted the form:
http://localhost:8080/?drink%5Bname%5D=asdf&drink%5Bingredients%5D=afd&drink%5Btoppings%5D=afd&drink%5Bnotes%5D=afd&drink%5Bstore_id%5D=2

That very last number is what I want to grab... :(

**Comment by gaand** [comment]
Your code is adding an event handler that gets the store_id but doesn't save it anywhere.  It also defines a function that looks like an event handler but isn't attached to an event.

**Comment by jrhorn424** [comment]
This line creates registers an event handler.

``` js
let $store_id = $('#add-drink').submit(function() {
```

This line references the `#add-drink` jQuery object (your form). https://api.jquery.com/submit/

``` js
let url = bubbleTea.baseUrl + '/stores/' + $store_id + '/drinks';
```

Unrelated to your issue, but you should prefer `.on('submit', ...)` to `.submit()`.

**Comment by gaand** [comment]
@jrhorn424: Sorry, I helped Celena correct that while it was assigned to me..

**Comment by seatuna** [comment]
Thanks! I appreciate all the help.

I can get the right url now, but I'm getting this error:

"Uncaught TypeError: Cannot read property 'token' of undefinedcreateDrink @ ajax-drinks.js:22jQuery.event.dispatch @ jquery.js:4732elemData.handle @ jquery.js:4544"

I haven't changed the authentication header, and it works elsewhere.

**Comment by gaand** [comment]
Your sign-in probably hasn't run.

**Comment by jrhorn424** [comment]
@gaand No worries! 😄

**Comment by seatuna** [comment]
I have it so that the "add drink" button only shows when I'm logged in
![screen shot 2016-02-29 at 9 29 58 am](https://cloud.githubusercontent.com/assets/16471076/13397225/10ec6060-dec7-11e5-847e-27f1dfec75cb.png)

**Comment by gaand** [comment]
Are you saving the user in `bubbleTea.user` when you sign in?

**Comment by seatuna** [comment]
Thank you! It turns out it was because I defined the same constant twice in two different files. I solved the authentication issue -- I have another one, but I want to try to fix it myself first.  I'll file another issue if I can't get it to work!

**Comment by seatuna** [comment]
IT WORKEDDDDDDDDDD!!!!!!! _victory dance_
