### ISSUE TITLE
Using variables defined in a for loop, outside of the loop.

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/full-stack-project#155]
I have a function called setUpDates, which correctly sets up a week's worth of dates on my table. Here is the code:

```
let setupDates = function(){
  // let table = $('#bankroll-updates-table');
  let myDate = new Date();
  myDate.setDate(myDate.getDate());
  for(var i = 0; i < 7; i++) {

      let currDate = (myDate.getMonth() + 1) + "/" + myDate.getDate() + "/"  + (myDate.getYear() - 100);
       myDate.setDate(myDate.getDate() + 1);
      $($('.date-column')[i]).html(currDate);
  }
};
```

Later in my code I am trying to create an inputCorrectly function which I'm trying to access the current date variable currDate. How can I use this variable outside of the for loop?

```
let inputCorrectly = function () {
  if (date-column1 === currDate) {
    setCurrentBalance1();
  }
```

**Comment by RealWeeks** [comment]
To clarify : So currDate works in the for loop but not outside?

**Comment by jdamiron** [comment]
@J-Weeks correct, I'm trying to use it in the inputCorrectly function as well, but I can't remove it out of the for loop because it uses the myDate variable, which is defined in the first function as well.

**Comment by jdamiron** [comment]
can't*

**Comment by RealWeeks** [comment]
You could return it, try defining it someplace else or pass currDate to the function.

**Comment by jrhorn424** [comment]
> How can I use this variable outside of the for loop?

Use `var` instead of `let`. There's a better way to approach this problem, however. Create a bunch of dates in the object you're passing to your handlebars template instead of directly manipulating the DOM.

**Comment by gaand** [comment]
@jdamiron What's your goal?  At a high level?  You just need seven days worth of dates anchored at some date?

**Comment by jdamiron** [comment]
I need my inputCorrectly function to match today's current date with one of the dates on the table and allow the cell to the right of it on the table to be the only one that is set for that entire day. Therefore people can only make one daily update on the table and only the correct cell will be manipulated.

**Comment by jdamiron** [comment]
@J-Weeks do I need to refine outside of the loop, then pass currDate to the function?

**Comment by RealWeeks** [comment]
@jdamiron I would defer to @jrhorn424 advice here

**Comment by jrhorn424** [comment]
If this is a front-end validation issue, I want to ask if you have any other features pending that you need to work on?

If you can just check the date on submit to the backend, you can use rails to validate the date and reject it if it has already been used.

**Comment by jdamiron** [comment]
I don't understand this statement, @jrhorn424 

If you can just check the date on submit to the backend.

But yes, I am currently working on other features as well.

**Comment by jrhorn424** [comment]
I mean validate uniqueness of date in the appropriate model.

**Comment by jdamiron** [comment]
@jrhorn424 should I not be using these functions at all? I can't relate the backend to what I am trying to do when making this function on the logic.

**Comment by GA-MEB** [comment]
@jdamiron What @jrhorn424 is talking about is that you're trying to do _validation_ - constraining data to a set of valid options. It sounds like you want to ensure that no two rows share the same date, and when once particular cell is updated, it updates only that row in your database. Is that correct? 

If so, you can accomplish the first thing by doing what Jeff suggested - adding a uniqueness constraint will ensure that no two records get created with the same date. To do the second, there are a variety of approaches you could take.

**Comment by GA-MEB** [comment]
Rereading your post, it also sounds like you only want the row with today's date to be editable. Is that right?

**Comment by jdamiron** [comment]
![screenshot from 2016-02-29 09-53-39](https://cloud.githubusercontent.com/assets/16493127/13397996/5fe1a790-deca-11e5-8ea2-f42078437ce0.png)

When someone clicks the update button I need the value inside the input field to be set at the cell in the Current Balance column that is adjacent to the current date. For example if today is 3/1/2016, When I click update to update my balance, that integer needs to be placed inside the Current Balance column at the cell right next to 3/1/2016.

**Comment by GA-MEB** [comment]
OK, I think I understand what you mean. You want that button to populate the 'Current Balance' field in today's row in the table, whatever today may be.

Questions:
- Should this process also update the back end?
- What if there's no row for today on the table?

**Comment by jdamiron** [comment]
@MattB-GA-Boston Yes, the backend should be able to grab the current state of the table. The user will be able to push a button that will get the last updated and completed weekly table so they can have access to see tables of previous week's even though it may currently be a later week. I believe there will always be a row for the current date based on how I set up the table.

**Comment by GA-MEB** [comment]
> "The user will be able to push a button that will get the last updated and completed weekly table so they can have access to see tables of previous week's even though it may currently be a later week."

I'm a little unclear on what this means. Are you saying that users should be able to see tables from previous weeks? 

In the problem you've outlined, there are two things that need to be updated every time you click that button: (1) the database record for today's date, and (2) the HTML table being shown on your front end.
I would _not_ recommend trying to parse the HTML table each time to figure out what which row corresponds with today's date, so see if you can find another way.

**Comment by jrhorn424** [comment]
@MattB-GA-Boston @jdamiron Did this reach resolution?

**Comment by jdamiron** [comment]
@jrhorn424 The idea is that how I structured my logic was incorrect. I should be getting the data from the backend to directly set up the table, and recreate a new table each time, rather than have everything hard coded in.
