### ISSUE TITLE
submitting multiple forms with a single button click

### ISSUE THREAD

**Issue by apalmer0** [ga-wdi-boston/full-stack-project#156]
I've got a system that creates multiple forms, and I'd like to submit them all using a single button click. For now I've got a listener for that button click - it loops through all of the forms with the same class, and I'm trying to use the `.trigger('submit')` event on each form to call a submit event listener that would actually run the ajax call I need. 

```
$('.new-climbs-button').on('click', function() {
    for (let i = 0; i < $('.add-new-climb-form').length; i++) {
      let $form = $('.add-new-climb-form')[i];
      $form.trigger('submit');
    }
  });
```

```
$('.add-new-climb-form').on('submit', function (event) {
    event.preventDefault();
    // ajax stuff goes here
  });
```

Unfortunately, when I use this, the page just reloads instead of actually submitting anything. Is there something I'm missing about event propagation or something here? Or is there a better way to do this?

**Comment by gaand** [comment]
Do you get form parameters in the url when the page reloads?

Do you need multiple forms, or could you send this all in one form (possibly a better choice)?

**Comment by apalmer0** [comment]
Huh - hadn't noticed but yes, there are form parameters in the url when the page reloads. What's that mean? Also I'm finding that the page only reloads when I use `$form.submit();`, not `$form.trigger('submit');`. 

My goal is actually just to create multiple instances of a Climb when I hit the submit button, and I thought forms would be the easiest way to do that. If not then I'm not tied to it at all - the only issue is that a user will likely want to create probably 5-10 of these at any time, so submitting each one individually isn't ideal.

**Comment by jrhorn424** [comment]
> Unfortunately, when I use this, the page just reloads instead of actually submitting anything. 

That could be because the following code doesn't `event.preventDefault()`:

``` js
$('.new-climbs-button').on('click', function() {
    for (let i = 0; i < $('.add-new-climb-form').length; i++) {
      let $form = $('.add-new-climb-form')[i];
      $form.trigger('submit');
    }
  });
```

Might need to look into how to get `$form.trigger('submit');` to `.preventDefault()`, or perhaps just add it to the line before.

**Comment by gaand** [comment]
The data in the url means that the prevent default didn't execute.

**Comment by gaand** [comment]
One form also means that the data all goes together.  If it's related data that's probably what you want.

**Comment by apalmer0** [comment]
Ah okay - so it's following the default action instead of going to my `submit` method? I'll look into how to prevent that... I'm not sure what the event is in this case because it's usually a submit event. Could I still use `event` for a generic button click?

And in terms of submitting it all via one form - if it all were in one form, how would I distinguish what data to pass through the ajax call?

**Comment by gaand** [comment]
Are they the same data repeated?  So you'd want to send an array?

**Comment by apalmer0** [comment]
No, it'd be all different data - one red climb of grade 5, one green climb of grade 10, etc

**Comment by gaand** [comment]
``` ruby
Rack::Utils.parse_nested_query 'climbs[][color]=blue&climbs[][rating]=5&climbs[][color]=aqua&climbs[][rating]=7'
=> {"climbs"=>[{"color"=>"blue", "rating"=>"5"}, {"color"=>"aqua", "rating"=>"7"}]}
```

Basically, group e.g.  `<input name="climbs[][color]"> <input name="climbs[][rating]">` for each individual climb and repeat for additional climbs.  This will be handled by rails as an array of climbs.

**Comment by apalmer0** [comment]
I'm feeling good about this direction but I _think_ the form is being submitted without the constituent fieldsets because they're being added by handlebars after the initial page load (maybe?)... if that's the case, do you have any idea how to ensure the form is including everything before it's submitted?

**Comment by gaand** [comment]
To use with strong params:

params.permit(climbs: [:color, :rating])[:climbs]

**Comment by gaand** [comment]
Please port the code that adds the fieldsets to the form and the html that defines the form.

**Comment by apalmer0** [comment]
form itself, inside modal:

```
          <div class="modal-content">
            <form id="add-new-climb-form">
              <div class="modal-header">

             --- header stuff ---

              </div>
              <div class="modal-body">
                <div class="row">
                  <div class="col-md-6">
                    <div class="color-options">
                      <p>Select Color</p>
                      <div class="new-climb-square create-active bk-black" data-color-id="black"></div>

                      --- more color options ---

                    </div>
                    <div class="type-options">
                      <p>Select Grade</p>
                      <div class="type-square inactive" data-type-id="5.">5.</div>
                      <div class="type-square inactive" data-type-id="v">v</div>
                    </div>
                    <div class="grade-options">
                      <div class="grade-square inactive" data-grade-id="0">0</div>

                      --- more grade options ---

                    </div>
                    <div class="modifier-options">
                      <div class="modifier-square inactive" data-modifier-id="-">-</div>
                      <div class="modifier-square inactive" data-modifier-id="+">+</div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="new-climbs-list">
                      <p>New Climb(s) Preview</p>

                      --- handlebars appends climb preview & fieldsets here ---

                    </div>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" name="submit" class="btn btn-success new-climbs-button modal-button">Create <span class="climbs-count"></span> climbs</button>
              </div>
            </form>
```

whenever  I click the 'color-options' div, i call the handlebars file to add a new climb preview and fieldset:

```
  $('.color-options').on('click', 'div', function () {
    climbNumber++;
    if ($(this).hasClass('create-active')) {
      color = $(this)[0].dataset.colorId;

     --- change classes and stuff ---

      let newClimbTemplate = require('./handlebars/climbs/new-climb.handlebars');
      $('.new-climbs-list').append(newClimbTemplate({climbNumber}));

     --- add data to fields ---

    }
  });
```

handlebars for fieldsets and climb preview

```
<div class="new-climb-preview-square climbNumber{{climbNumber}}" data-climb-id="{{climbNumber}}">
</div>
<fieldset>
  <input type="text" class="form-control add-climbs inputClimbColor climbNumber{{climbNumber}}" data-climb-id="{{climbNumber}}" name="climbs[][color]" value="">
  <input type="text" class="form-control add-climbs inputClimbType climbNumber{{climbNumber}}" data-climb-id="{{climbNumber}}" name="climbs[][type]" value="">
  <input type="text" class="form-control add-climbs inputClimbGrade climbNumber{{climbNumber}}" data-climb-id="{{climbNumber}}" name="climbs[][grade]" value="">
  <input type="text" class="form-control add-climbs inputClimbModifier climbNumber{{climbNumber}}" data-climb-id="{{climbNumber}}" name="climbs[][modifier]" value="">
  <input type="text" class="form-control add-climbs inputClimbGym climbNumber{{climbNumber}}" data-climb-id="{{climbNumber}}" name="climbs[][gym_id]" value="">
</fieldset>
```

let me know if you're looking for anything else! thanks for your help here

**Comment by apalmer0** [comment]
oh, and here's my form submission listener:

```
  $('#add-new-climb-form').on('submit', function (event) {
    event.preventDefault();
    console.log('starting new climb addition');
    var formData = new FormData(event.target);
    console.log(formData);
  });
```

it's returning this in the console:

```
starting new climb addition
FormData {}
```

**Comment by gaand** [comment]
FormData is an opaque type, so not seeing it there is fine.  What does the rails server log show?

**Comment by RealWeeks** [comment]
If you send data to here you can inspect the formData in the network request

```
"https://www.googleapis.com/upload/mirror/v1/"
```

**Comment by apalmer0** [comment]
If I console.log the event.target instead of the FormData I can see that the form does in fact include the fieldsets when it gets submitted, so I was wrong about that - I think what Antony said about FieldData being opaque is why I was thinking it wasn't working. I'm playing with submitting the form now but it looks like it's only sending a single item rather than the group, and not actually saving any of the attributes in that single item, so I've still got a little ways to go. I think I'm getting somewhere though.

**Comment by jrhorn424** [comment]
> ... and not actually saving any of the attributes in that single item...

This can be an indication to check your server log, if you haven't done so already.

**Comment by apalmer0** [comment]
I'm getting this right now:

```
ArgumentError (When assigning attributes, you must pass a hash as an argument.):
  app/controllers/climbs_controller.rb:17:in `create'
```

But it looks like I am passing in a hash:

```
Started POST "/gyms/1/climbs" for ::1 at 2016-02-29 11:03:29 -0500
Processing by ClimbsController#create as */*
  Parameters: {"climb"=>[{"color"=>"orange", "type"=>"5.", "grade"=>"2", "modifier"=>"+", "gym_id"=>"1"}], "submit"=>"", "gym_id"=>"1"}
```

Someone mind looking at it with me? I feel like there's a bunch of places I could be making a mistake here.

**Comment by gaand** [comment]
Would you please post the create code?  Also, are you using the strong params line I posted above?

**Comment by jrhorn424** [comment]
I'm happy to take a look, but I think this might be part of the issue:

``` diff
- Parameters: {"climb"=>[{"color"=>"orange", "type"=>"5.",
+ Parameters: {"climbs"=>[{"color"=>"orange", "type"=>"5.",
```

**Comment by gaand** [comment]
You should be able to pass the array returned from that to create and it should create multiple climbs.

**Comment by gaand** [comment]
``` ruby
params.permit(climbs: [:color, :rating])[:climbs]
```

**Comment by apalmer0** [comment]
Here's my form submission code - I've hardcoded gym # 1 for now, I'll enter that dynamically later on. 

```
  $('#add-new-climb-form').on('submit', function (event) {
    event.preventDefault();
    console.log('starting new climb addition');
    var formData = new FormData(event.target);
    $.ajax({
      url: myApp.baseUrl + '/gyms/1/climbs',
      headers: {
        Authorization: 'Token token=' + myApp.user.token,
      },
      method: 'POST',
      contentType: false,
      processData: false,
      data: formData,
    }).done(function (data) {
      console.log(data);
      console.log('climbs added!');
    }).fail(function (jqxhr) {
      console.error(jqxhr);
    });
  });
```

And here's my climb_params in the climbs controller:

```
  def climb_params
    params.permit(climbs: [:color, :type, :grade, :modifier])[:climbs]
  end
```

**Comment by gaand** [comment]
How about the create action on ClimbsController?

**Comment by apalmer0** [comment]
```
  before_filter :set_climb, only: [:show, :update, :destroy]
  before_filter :set_gym, only: [:index, :create]
```

```
  def create
    @climb = Climb.new(climb_params)
    @climb.gym = @gym

    if @climb.save
      render json: @climb, status: :created
    else
      render json: @climb.errors, status: :unprocessable_entity
    end
  end
```

```
 def set_climb
    @climb = Climb.find(params[:id])
  end

  def set_gym
    @gym = Gym.find(params[:gym_id])
  end
```
