### ISSUE TITLE
Confusion about referencing @current_user...

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/full-stack-project#157]
I have a vote model in my app. I would like to associate votes with both a user and a piece of art. However, I'm confused about how to reference the current art and the current user when I create a vote. 

Do I accomplish this by passing in params? Is there someway to reference the currently signed-in user from within the backend?

I would appreciate a few minutes to hash this out verbally.

**Comment by gaand** [comment]
`current_user` will return the current user or `nil`.

**Comment by gaand** [comment]
The `art_id` you'll have to pass in as parameter.

**Comment by jrhorn424** [comment]
I'll need to see your routes. Would you mind adding the output of `rake routes`? Then we can meet briefly to discuss. Thanks!

**Comment by rchezrutt88** [comment]
```
     Prefix Verb   URI Pattern                    Controller#Action
    sign_up POST   /sign-up(.:format)             users#signup
    sign_in POST   /sign-in(.:format)             users#signin
            DELETE /sign-out/:id(.:format)        users#signout
            PATCH  /change-password/:id(.:format) users#changepw
      users GET    /users(.:format)               users#index
       user GET    /users/:id(.:format)           users#show
arts_random GET    /arts/random(.:format)         arts#random
       arts GET    /arts(.:format)                arts#index
            POST   /arts(.:format)                arts#create
        art GET    /arts/:id(.:format)            arts#show
            PATCH  /arts/:id(.:format)            arts#update
            PUT    /arts/:id(.:format)            arts#update
            DELETE /arts/:id(.:format)            arts#destroy
      votes GET    /votes(.:format)               votes#index
            POST   /votes(.:format)               votes#create
       vote GET    /votes/:id(.:format)           votes#show
            PATCH  /votes/:id(.:format)           votes#update
            PUT    /votes/:id(.:format)           votes#update
            DELETE /votes/:id(.:format)           votes#destroy
```

**Comment by rchezrutt88** [comment]
Lots of stubs...

**Comment by gaand** [comment]
@jrhorn424 Or as a nested route?

**Comment by jrhorn424** [comment]
One way to get the art id would be to use a nested route. So instead of `POST /votes` you'd have something like `POST /art/:id/votes`. See the pattern used for routes and controllers in the `rails-api-bdd-iteration` lesson, specifically the `article_comments` feature.

**Comment by rchezrutt88** [comment]
A nested route? I thought it was simplest--if not the most elegant--approach to have three separate routes.

**Comment by jrhorn424** [comment]
But you need the id of the art piece right? And votes only occur in the context of an art piece?

**Comment by rchezrutt88** [comment]
Sure. But it's easy to pass the id of the current art piece to POST /votes

**Comment by rchezrutt88** [comment]
Semantically, yes, that makes more sense, but I'm going for maximum simplicity.

**Comment by jrhorn424** [comment]
If votes only occur in the context of an art piece, then they are by definition a nested resource. In this case the elegant solution, IMO, is a nested route, since that communicates the fact that votes don't mean anything without an attached piece of art.

**Comment by jrhorn424** [comment]
http://quoteinvestigator.com/2011/05/13/einstein-simple/

**Comment by jrhorn424** [comment]
In this case you're running into complexity in your front-end because of a back-end modeling decision. It's just about where you want to put the complexity.

**Comment by rchezrutt88** [comment]
A vote also only occurs within the context of a user. Which makes more sens? user:id/votes or arts:id/votes? I don't know, so my compromise was to make it separate.

**Comment by gaand** [comment]
The context of current user isn't captured in a route but in a state of the request.

**Comment by rchezrutt88** [comment]
I see. All right, I'll nest votes under arts. Thought it would remove a layer of complication to have all three models at the root level...but I trust you doods.

**Comment by rchezrutt88** [comment]
voila.

```
 Prefix Verb   URI Pattern                       Controller#Action
    sign_up POST   /sign-up(.:format)                users#signup
    sign_in POST   /sign-in(.:format)                users#signin
            DELETE /sign-out/:id(.:format)           users#signout
            PATCH  /change-password/:id(.:format)    users#changepw
      users GET    /users(.:format)                  users#index
       user GET    /users/:id(.:format)              users#show
arts_random GET    /arts/random(.:format)            arts#random
  art_votes GET    /arts/:art_id/votes(.:format)     votes#index
            POST   /arts/:art_id/votes(.:format)     votes#create
   art_vote GET    /arts/:art_id/votes/:id(.:format) votes#show
            PATCH  /arts/:art_id/votes/:id(.:format) votes#update
            PUT    /arts/:art_id/votes/:id(.:format) votes#update
            DELETE /arts/:art_id/votes/:id(.:format) votes#destroy
       arts GET    /arts(.:format)                   arts#index
            POST   /arts(.:format)                   arts#create
        art GET    /arts/:id(.:format)               arts#show
            PATCH  /arts/:id(.:format)               arts#update
            PUT    /arts/:id(.:format)               arts#update
            DELETE /arts/:id(.:format)               arts#destroy
```

**Comment by jrhorn424** [comment]
@rchezrutt88 and I discussed how `params` gets filled from the router layer before the controller action is fired. We also used what I think is a better pattern for creating associated records than the one I presented previously. This is how we created a vote associated with a piece of art:

``` ruby
def create
  @vote = @art.votes.build(params[:vote])

  if @vote.save
  # ...
  end
end

# set_art finds art by art_id, which is filled in from the nested route, and is called during create
```

**Comment by jrhorn424** [comment]
We also clarified how the controller inheritance chain worked, including what was setting `current_user` and how using the `ProtectedController` was essential for that.

@rchezrutt88 If the confusion about `current_user` is cleared up, and if you are getting a user attached to a vote, do you mind closing this issue? Feel free to open another one if you have issues creating an art associated vote. Thanks!
