### ISSUE TITLE
Implementing a search bar on the front-end

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/full-stack-project#159]
I'm having trouble installing a search function in my nav-bar. I have the search bar 

```
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
```

and in my controller I suppose I'll have to def self.search with some search params and tie it to the Beer model with def index?

I suppose I need to tie them together with an AJAX GET? 

Would love to sit down and be put in the right direction.

**Comment by jrhorn424** [comment]
Please add any notes from your discussion @kpie89. Thanks!

**Comment by GA-MEB** [comment]
@kpie89 Can you add those notes that we talked about?

**Comment by kpie89** [comment]
In order to implement a search feature I had to add 

```
  def search_by_key
    @beer = Beer.search_by_key(params[:search_key])

    render json: @beer
  end
```

to my controller and 

```
  def self.search_by_key(key)
    if key
      response = HTTParty.get("http://prost.herokuapp.com/api/v1/beer/#{key}")
      {beer: response['title'], key: response['key'], abv: response['abv'], style: response['tags'], brewery: response['brewery']}
    end
  end
```

to my model. This let me specify a route 

```
get '/beer' => 'beers#search_by_key'
```

I could then call a GET request on my front end like 

```
// search beers
$('.search-it').on('click', function(e) {
  e.preventDefault();
  $.ajax({
    url: myApp.BASE_URL + '/beer?search_key=' + $('#search-bar').val(),
    method: 'GET',
    dataType: 'json'
  }).done(function(beer){
    console.log(beer);
    $('.search').val('');
  }).fail(function(jqxhr) {
    console.error(jqxhr);
  });
  });
});
```

which would fire when I clicked the submit button next to the search bar (labeled 'search-it) and it wouLd pass the value of the input form into the URL, thus corresponding to the route I specified in my back-end

**Comment by GA-MEB** [comment]
Thanks, @kpie89 !

**Comment by jrhorn424** [comment]
The only change I would make is how you're routing to the BeersController. Happy to discuss, it's a small change.

**Comment by jrhorn424** [comment]
Preview:

``` diff
-  def search_by_key
-    @beer = Beer.search_by_key(params[:search_key])
+  def index
+    @beers = if params[:search_key].present?
+      Beer.search_by_key(params[:search_key])
+    else
+      Beer.all
+    end

-   render json: @beer
+   render json: @beers
  end
```
