### ISSUE TITLE
Controller & routes syntax

### ISSUE THREAD

**Issue by ajordon** [ga-wdi-boston/full-stack-project#160]
I need help ironing out my controllers and routes for the ERD listed below.

![image](https://cloud.githubusercontent.com/assets/6088950/13402632/24f609a4-dedf-11e5-94c0-3fb5ddd1d471.png)

**Comment by jrhorn424** [comment]
Looks fine at first glance. Do you have a specific modeling question? What friction are you running into currently?

**Comment by ajordon** [comment]
I just wanted a second pair of eyes on my routes 

```
Rails.application.routes.draw do
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'

  resources :users, only: [:index, :show] do
    resources :polls, except: [:edit]
  end

  resources :polls, except: [:edit] do
    resources :votes, only: [:new, :index]
    resources :options, only: [:new, :index]
  end

  post '/create-poll' => 'polls#createpoll'
  patch '/update-poll/:id' => 'polls#updatepoll'
  delete '/delete-poll/id' => 'polls#deletepoll'
end
```

As well as my poll_controller, which Im struggling with.

**Comment by GA-MEB** [comment]
@ajordon @jrhorn424 Has this been resolved?

**Comment by jrhorn424** [comment]
Nothing should be nested under `:users` except data directly related to a user, such as a `Profile`, which your app doesn't have.

Your last three routes indicate that you are fighting Rails conventions. Don't do that.

Try this:

``` diff
Rails.application.routes.draw do
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'

  resources :users, only: [:index, :show] do
-    resources :polls, except: [:edit]
  end

-  resources :polls, except: [:edit] do
+  resources :polls, except: [:edit, :new] do
-    resources :votes, only: [:new, :index]
+    resources :votes, only: [:create, :index]
    resources :options, only: [:new, :index] # same thing here
  end

-  post '/create-poll' => 'polls#createpoll'
-  patch '/update-poll/:id' => 'polls#updatepoll'
-  delete '/delete-poll/id' => 'polls#deletepoll'
end
```

**Comment by jrhorn424** [comment]
RESTful conventions are explored more in this [guide](http://guides.rubyonrails.org/routing.html).

**Comment by RealWeeks** [comment]
So the question is are your routes correct?

**Comment by RealWeeks** [comment]
I would recommend building, and if you come across on that you can't adjust.  As I'm building and frequently when I'm coding I find the needs of my front end sometimes change and need to go back and adjust and clean up.  if your rails server says something like "cannot get Route blah". Go back and change.

**Comment by ajordon** [comment]
No that question was answered by Jeff, my remaining question is to have someone help me with my controllers for Poll, Vote, and Option.

**Comment by RealWeeks** [comment]
So if this is a new issue, could you close this and open another, unless it's related than don't.

If it is related what do you need help with?

**Comment by ajordon** [comment]
Im getting an undefined method user

```
class PollsController < ProtectedController
  # before_action :authenticate :set_user, only: [:show]
  skip_before_action :authenticate, only: [:index, :show, :update]

  def index
    render json: Poll.all
  end

  def user_index
    @poll = current_user.polls
    render json: @poll
  end

  def show
    poll = Poll.find(params[:id])
    render json: poll
  end

  def create
    @poll = Poll.new(poll_params)

    if @poll.save
      render json: @poll, status: :created
    else
      rencer json: @poll.errors, status: :unprocessable_entity
    end
  end
end
```

It says the error is on 

```
def show
    poll = Poll.find(params[:id])
    render json: poll
  end
```

**Comment by RealWeeks** [comment]
sorry Aaron, can you paste in the error?

**Comment by RealWeeks** [comment]
Also looks like you're commenting out something having to do with setting the user. You may need another before action that doesn't auth, but I would need to see your error further.

**Comment by ajordon** [comment]
I commented the first line out to focus on one issue at a time. The error is on my rails side so its a full webpage. The second code clip is all it says `undefined method user for #<Poll:0x007fa69449c4c8>`

**Comment by RealWeeks** [comment]
Ok, I'll give Matt, Jeff, Antony a few minutes to see if they have anything before I self-assign and come over.

**Comment by RealWeeks** [comment]
I referred Aaron to a demo we did earlier and asked him to look at it to see if it helped then ask follow ups from there

**Comment by gaand** [comment]
You don't seem to be relying on the rails conventions.  Why define `user_index`?

I think the undefined method might be coming from your serilaizer.

**Comment by RealWeeks** [comment]
@ajordon any luck with the review or the advice @gaand gave?

**Comment by ajordon** [comment]
It worked. But Im still struggling with my controllers

**Comment by RealWeeks** [comment]
Keep asking questions, what else do you need help with?

**Comment by jrhorn424** [comment]
@J-Weeks I spoke with @ajordon earlier. It's a misunderstanding of how routes connect to controllers. Would you meet with @ajordon and discuss REST conventions and help him cleanup his controllers? I will follow up as well.

**Comment by ajordon** [comment]
- Updated the relation between Poll and User. Missing `foreign_key: :created_by`
- Added current user constraint to Poll controller. Allowing anyone to make a poll along with users.
- Reordered routes
- Updated serializes  with corrected syntax. Removed an unnecessary `has_one`

**Comment by jrhorn424** [comment]
Thanks!
