### ISSUE TITLE
JS - Storing User Data and Using It with Require/Export

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/full-stack-project#166]
Is there a way to hold a global Object which can be updated and used by separate .js files to which it is exported?

**Comment by gaand** [comment]
Did you try requiring the same file?   I'm pretty sure it works.

**Comment by RealWeeks** [comment]
@MFBrewster Did you get it working?

**Comment by MFBrewster** [comment]
Not yet, still playing with it.

**Comment by MFBrewster** [comment]
I think I have it working, but I feel like there's still a chance it can break. Can I close, and reopen later if there are more problems?

**Comment by GA-MEB** [comment]
@MFBrewster Totally!

**Comment by gaand** [comment]
@MFBrewster Would you please post your solution?  Thanks!

**Comment by MFBrewster** [comment]
I have a file global-objects.js:

``` js
'use strict';

let user = {};
let app = {};

module.exports = {
  user,
  app,
};
```

Which I require into each of my javascript files. For example, when `globalObjects.user = data.user;` is executed upon a completed AJAX request, the value of globalObjects.user is updated for all other javascript files which use the global object.
