### ISSUE TITLE
PATCH error - missing params, possibly simple ajax syntax problem

### ISSUE THREAD

**Issue by jenweber** [ga-wdi-boston/full-stack-project#167]
I am trying to do a simple PATCH to a blog post, in the table no_spoilers_posts. Instead of using formdata, I want to give the request as individual variables, so I began testing by giving it strings and directing it to one id manually. However the server gives the following error:

> Completed 400 Bad Request in 4ms (ActiveRecord: 0.6ms)
> ActionController::ParameterMissing (param is missing or the value is empty: no_spoilers_post):
>   app/controllers/no_spoilers_posts_controller.rb:58:in `no_spoilers_post_params'
>   app/controllers/no_spoilers_posts_controller.rb:35:in`update'

Here is my ajax (located inside the working click handler):

```
$.ajax({
    url: myApp.baseUrl + '/no_spoilers_posts/5',
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + myApp.user.token,
    },
    contentType: false,
    processData: false,
    data: {
      no_spoilers_post: {
        title: 'maybe it will work this time'
      }
    },
```

Here is my controller, including line 35 referenced in the error:
def update
    @no_spoilers_post = NoSpoilersPost.find(params[:id])

```
if @no_spoilers_post.update(no_spoilers_post_params)
  head :no_content
else
  render json: @no_spoilers_post.errors, status: :unprocessable_entity
end
```

  end

And this contains line 58 from the error:

```
    def no_spoilers_post_params
      # params[:no_spoilers_post]
      params.require(:no_spoilers_post).permit(:title, :content, :game_id)
    end
```

All my testing has been variations of adding and removing S's and single quotes and double quotes, without any luck.

**Comment by jenweber** [comment]
I should add that here's the working curl request:

```

  curl --include --request PATCH http://localhost:3000/no_spoilers_posts/5 \
    --header "Content-Type: application/json" \
    --data '{
      "no_spoilers_post": {
        "title": "I did a patch for this title"
      }
    }'
```

And the object at http://localhost:3000/no_spoilers_posts/5

```
{
"no_spoilers_post": {
"id": 5,
"title": "I did a patch for this title",
"content": "a sample body",
"game_id": null,
"game": null
}
}
```

**Comment by GA-MEB** [comment]
Hmm. I seem to remember some of the AJAX options having to do with FormData. 

What happens if you take `contentType` and `processData` out of the AJAX request?

**Comment by jenweber** [comment]
What happens is it works. _headdesk_
