### ISSUE TITLE
Creating users from CSV

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/full-stack-project#168]
I'm confused about what sort of data the User.create method is looking for as you've speced it. How should the headers in a csv file of users look? Like email,password? like credentials[email],credentials[password],credentials[password_confirmation]? 

Essentially I'm having trouble tracing the through the code that creates a new user.

**Comment by gaand** [comment]
Creating users from a csv is fine, but not with passwords.  That would be a security issue.

**Comment by rchezrutt88** [comment]
…even for the sake of testing locally?

**Comment by rchezrutt88** [comment]
Signing up every time I nuke and pave the database is getting a little tedious. I want to write a task in example to load a few users.

**Comment by gaand** [comment]
Ah.  Then you just need to pass in email and password to create (and whatever else you want to call them).  I do not endorse this.

**Comment by jrhorn424** [comment]
@rchezrutt88 If you go down this road, be sure to use a fake e-mail and a very stupid password, and put the user you create in `db/examples.rb`. Do not (!) put it in `db/seeds.rb`.

If you want to keep the password out altogether, you can use an environment variable to set the password when you invoke the nuke task. In other words, write code in `db/examples.rb` so that `EXAMPLE_PASS=sekrit rake db:nuke_pave` works.

**Comment by rchezrutt88** [comment]
That is what I've been doing. I already put a task that loads art from a csv in the examples.rb. My question is what should the hash that I pass to Vote.create!(hash) look like? email=>something@something.com, password=>something ?

**Comment by gaand** [comment]
What does the user controller use?

**Comment by rchezrutt88** [comment]
```
#
class UsersController < ProtectedController
  skip_before_action :authenticate, only: [:signup, :signin]

  # POST '/sign-up'
  def signup
    user = User.create(user_creds)
    if user.valid?
      render json: user, status: :created
    else
      head :bad_request
    end
  end

  # POST '/sign-in'
  def signin
    creds = user_creds
    if (user = User.authenticate creds[:email],
                                 creds[:password])
      render json: user, serializer: UserLoginSerializer, root: 'user'
    else
      head :unauthorized
    end
  end

  # DELETE '/sign-out/1'
  def signout
    if current_user == User.find(params[:id])
      current_user.logout
      head :no_content
    else
      head :unauthorized
    end
  end

  # PATCH '/change-password/:id'
  def changepw
    if !current_user.authenticate(pw_creds[:old]) ||
       (current_user.password = pw_creds[:new]).blank? ||
       !current_user.save
      head :bad_request
    else
      head :no_content
    end
  end

  def index
    render json: User.all
  end

  def show
    user = User.find(params[:id])
    render json: user
  end

  def update
    head :bad_request
  end

  private

  def user_creds
    params.require(:credentials)
      .permit(:email, :password, :password_confirmation)
  end

  def pw_creds
    params.require(:passwords)
      .permit(:old, :new)
  end

  private :user_creds, :pw_creds
end
```

**Comment by jrhorn424** [comment]
You won't pass a hash to `Vote` for a user. Instead, you'll use something like `example_user.votes.create!(vote_params)` in `db/examples.rb`.

**Comment by jrhorn424** [comment]
This should look similar to the code you used in your controller. The docs we referenced earlier today is at http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html

**Comment by gaand** [comment]
@rchezrutt88 I wasn't asking you to post the user controller, I was asking what does the user controller do to create a user.

**Comment by rchezrutt88** [comment]
Okay, so let's say I now want get all the votes associated with a piece of art when I get that piece back from the server. Would it be as simple as adding :votes to the art serializer?

**Comment by gaand** [comment]
You have two issue open and the questions aren't always in the correct one.

**Comment by rchezrutt88** [comment]
@gaand Shit. I was about to accuse you of that very crime. 

But as it turns out I am the cyber terrorist.

**Comment by rchezrutt88** [comment]
Okay, I am reoriented. User.create( ) takes the output from user_creds. But user_creds seems to imply that to create a new user I NEED a :credentials field and I'm PERMITTED to have an :email, :password, and password_confirmation. Is :credentials a hash with the values :email, :password, and :password_confirmation? How does that translate into structuring the headers of the CSV? Do I take the email,password,password_confirmation headers and nest them in a credentials hash before passing them to User.create()?

**Comment by gaand** [comment]
Try this in the rails console:

``` ruby
params = ActionController::Parameters.new({root: {name: 'foo', pw: 'bar' }})
params.require(:root)
```

**Comment by rchezrutt88** [comment]
@gaand  I need you to elaborate on this. I don't know what this does.

**Comment by gaand** [comment]
Did you run it?

**Comment by rchezrutt88** [comment]
Yep.

**Comment by rchezrutt88** [comment]
Did this make some change to my code that's going to need to be undone when I deploy?

**Comment by rchezrutt88** [comment]
Well, actually, I can see that it changed nothing.

**Comment by gaand** [comment]
`params` in a controller is an instance of ActionController::Parameters.

That code simulates what happens with parameters in a controller.  

You're question was about what to pass to create.  Which in the controller is usually something from params.

**Comment by rchezrutt88** [comment]
I get it. The point is that the :credentials{} wrapper is stripped.

**Comment by gaand** [comment]
And so what gets passed to `User.create`?

And if that resolves this issue, please close.  Thanks

**Comment by rchezrutt88** [comment]
Playing around with the console now. Looks like I can create a user without the password_confirmation argument? Is that right?

**Comment by gaand** [comment]
If it worked, then you can.

**Comment by rchezrutt88** [comment]
email: "...", password: "..."

**Comment by rchezrutt88** [comment]
Must be an error in my bulk loader that I was attributing to a deeper misunderstanding of how the User model operates.

**Comment by rchezrutt88** [comment]
So then what's peculiar is that I get this error when trying to bulkload: 

```
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column users.password does not exist
LINE 1: ...S one FROM "users" WHERE "users"."email" = $1 AND "users"."p...
                                                             ^
: SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."password" = 'z' LIMIT 1
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/examples.rb:40:in `block (2 levels) in populate_users'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/examples.rb:38:in `block in populate_users'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/examples.rb:37:in `populate_users'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/examples.rb:59:in `<top (required)>'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/lib/tasks/db.rake:4:in `require_relative'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/lib/tasks/db.rake:4:in `block (2 levels) in <top (required)>'
PG::UndefinedColumn: ERROR:  column users.password does not exist
LINE 1: ...S one FROM "users" WHERE "users"."email" = $1 AND "users"."p...
```

With this code: 

```
def populate_users(path)
  User.transaction do
    CSV.foreach(Rails.root + path, headers: true) do |user_row|
      user = user_row.to_hash
      next if User.exists? user
      User.create!(user)
    end
  end
end
```

**Comment by rchezrutt88** [comment]
I understand that password isn't a column in users (password are hashed to pasword_digest)...but why would that matter in this case?

**Comment by gaand** [comment]
What is `User.exist?` searching for?

**Comment by rchezrutt88** [comment]
...the existence of a User table in the database?

**Comment by rchezrutt88** [comment]
I'm following the same pattern as I did for bulk loading art. That's what is confusing me.
This works just fine:

```
def populate_arts(path)
  Art.transaction do
    CSV.foreach(Rails.root + path, headers: true, col_sep: ';', header_converters: :downcase) do |art_row|
      art = art_row.to_hash
      next if Art.exists? art
      Art.create!(art)
    end
  end
end
```

**Comment by jrhorn424** [comment]
Instead of:

```
      next if Art.exists? art
      Art.create!(art)
```

You can

```
      Art.find_or_create_by!(art)
```

Does making a similar change for `User` help?

**Comment by jrhorn424** [comment]
Instead of using `next`, use `.find_or_create_by` in ActiveRecord. The problem with `User` is that the `user` instance has a `password`, which is a virtual attribute and therefore doesn't have an associated column. If you use `.find_or_create_by`, it knows its a virtual attribute, so you shouldn't get this error.

**Comment by gaand** [comment]
`User.exists?` searches for a match to the parameters you supply.  If one of those is password, then it does the wrong thing.

**Comment by rchezrutt88** [comment]
@jrhorn424 Good. To. Know.  
@gaand I was following a pattern I found in the solution branch of this repo:
https://github.com/ga-wdi-boston/rails-activerecord-crud/blob/solution/lib/tasks/db.rake
where ClassName.exists? is used without any arguments.

**Comment by rchezrutt88** [comment]
Still no go on creating users, even with the find_or_create_by! method (it works for Art). 

```
ctiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column users.password does not exist
LINE 1: ...rs".* FROM "users" WHERE "users"."email" = $1 AND "users"."p...
                                                             ^
: SELECT  "users".* FROM "users" WHERE "users"."email" = $1 AND "users"."password" = 'z' LIMIT 1
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/examples.rb:40:in `block (2 levels) in populate_users'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/examples.rb:38:in `block in populate_users'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/examples.rb:37:in `populate_users'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/examples.rb:58:in `<top (required)>'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/lib/tasks/db.rake:4:in `require_relative'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/lib/tasks/db.rake:4:in `block (2 levels) in <top (required)>'
PG::UndefinedColumn: ERROR:  column users.password does not exist
LINE 1: ...rs".* FROM "users" WHERE "users"."email" = $1 AND "users"."p...
```

**Comment by jrhorn424** [comment]
I'll defer to @gaand on this.

**Comment by gaand** [comment]
In that example, each call to `exists?` recieves argument

**Comment by rchezrutt88** [comment]
I mean, I could just write this all off as a total waste of my time but now I really am curious why it is that I can create new users from the console but not inside my script.

**Comment by gaand** [comment]
Why not just search for the user without password?

**Comment by rchezrutt88** [comment]
I don't understand. Why would I want to do that?

**Comment by gaand** [comment]
Because the users table doesn't have a password column?  Searching for something and creating it are distinct.

**Comment by rchezrutt88** [comment]
I still do not understand. 

I'm really trying, I promise.

**Comment by rchezrutt88** [comment]
I'm going to work on something else because it doesn't feel like we're connecting here. I'm still curious—not because it really matters in the context of getting this project done but because I believe the answer might be revealing and have implications for how I understand Rails more generally--so if you're not totally exasperated with this topic, ping me and I'll be happy to listen.

**Comment by gaand** [comment]
``` ruby
user = user_row.to_hash
search_user = user.reject {|k,v| k == :password}
next if User.exists? search_user
User.create!(user)
```

**Comment by rchezrutt88** [comment]
[in sing-songy voice] Still doesn't work!

**Comment by jrhorn424** [comment]
What's the error message now?

**Comment by rchezrutt88** [comment]
La misma.

```
: SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."password" = 'z' LIMIT 1
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/examples.rb:41:in `block (2 levels) in populate_users'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/examples.rb:38:in `block in populate_users'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/examples.rb:37:in `populate_users'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/examples.rb:59:in `<top (required)>'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/lib/tasks/db.rake:4:in `require_relative'
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/lib/tasks/db.rake:4:in `block (2 levels) in <top (required)>'
PG::UndefinedColumn: ERROR:  column users.password does not exist
LINE 1: ...S one FROM "users" WHERE "users"."email" = $1 AND "users"."p...
```

**Comment by jrhorn424** [comment]
@rchezrutt88 Want to stop by? I'll have a look.

**Comment by jrhorn424** [comment]
The fix:

``` diff
- search_user = user.reject {|k,v| k == :password}
+ search_user = user.reject {|k,v| k == 'password'}
```
