### ISSUE TITLE
(Rails) Posting to my API (curl)

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/full-stack-project#169]
this is the summary of what i get back from my curl request and it being piped through BCAT.

795: unexpected token at '{"lists": { "category": "Party Gifts", "user_id": 3 , }}'

``` bash
#!/bin/bash
TOKEN='951473cfb9adf638cb12eb994c2679e3'
URL='http://localhost:3000'
#URL="http://httpbin.org/post"
#   POST   /lists(.:format)   lists#create
echo '-----------------------------------------'
curl ${URL}/lists \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}"\
  --data '{"lists": {
    "category": "Party Gifts",
    "user_id": 3 ,
  }}' | bcat -h
  # head -n 15
  #/Users/erdesi90562/wdi/projects/toDo/backend/tmp/junk/erro.html

# --silent
echo '-----------------------------------------'

```

I have tried many combos. That's bad because that means the I don't understand how to send a post request and what information is required. Hopefully its just the the rake routes.

**Comment by gaand** [comment]
Your data is not valid JSON.  You have an extraneous `,`.

**Comment by edesilets** [comment]
I have fixed the extraneous `,` and the spelling error of `lists` to `list`.  Problem solved. Thank you.
