### ISSUE TITLE
after logging in cannot get an activity requiring token to succeed.  activities not requiring toekn authentication happen successfully 

### ISSUE THREAD

**Issue by bbarbersox** [ga-wdi-boston/full-stack-project#17]

**Comment by gaand** [comment]
Hey Bill.  Is this the same issue as the one on the project2-api repo?

**Comment by srhoulam** [comment]
I've got this.

**Comment by gaand** [comment]
Okay.  If it's the same issue Bill opened on the project2-api repo, I'll close that one.

**Comment by jrhorn424** [comment]
@srhoulam Please let us know the resolution once you've addressed it.

**Comment by srhoulam** [comment]
Bill could not reproduce the problem after making some changes to his code between now and when he put this issue up.
