### ISSUE TITLE
Cannot create/post article due to Uncaught TypeError: Illegal invocation

### ISSUE THREAD

**Issue by msyao** [ga-wdi-boston/full-stack-project#170]
I cannot create/post an article due to "**// If value is a function, invoke it and return its value
value = jQuery.isFunction( value ) ? value() : ( value == null ? "" : value );**"

I am not sure how to refactor the code to solve this problem--I have tried to require or set variable to the baseURL and paste the function to the other js files.

My code is 

``` javascript
 let createArticle = function(e){
   e.preventDefault();
   let formData = new FormData(e.target);
   $.ajax({
     url: apiAuth.myApp.baseUrl + '/articles',
     method: 'POST',
     headers: {
       Authorization: 'Token token=' + apiAuth.myApp.user.token,
     },
     data:formData
   })
   .done(function(data){
     console.log(data);
   })
   .fail(function(jqxhr) {
     console.error(jqxhr);
   });
 };

```

Thank you!

![screen shot 2016-02-29 at 3 40 30 pm](https://cloud.githubusercontent.com/assets/16352837/13408268/ece2d6de-defa-11e5-9e5d-70a6f22e774f.png)

**Comment by gaand** [comment]
contentType: false, processData: false

**Comment by msyao** [comment]
Thank you Anthony :neckbeard:
