### ISSUE TITLE
Adding reference to votes to art

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/full-stack-project#171]
I would like to be able to reference all the votes associated with a piece of art. I did not take this into account into my initial art model, the migration for which looks like this: 

```
class CreateArts < ActiveRecord::Migration
  def change
    create_table :arts do |t|
      t.string :author
      t.string :born_died
      t.string :title
      t.string :date
      t.string :technique
      t.string :location
      t.string :url
      t.string :form
      t.string :style
      t.string :school
      t.string :timeframe

      t.timestamps null: false
    end
  end
end
```

Now I'm running a migration that looks like this, to add a reference to votes to each art piece:

```
class AddVotesRefToArts < ActiveRecord::Migration
  def change
    add_reference :arts, :votes, index: true, foreign_key: true
  end
end
```

However, when I run the migration, I get this:

```
PG::UndefinedColumn: ERROR:  column "vote_id" referenced in foreign key constraint does not exist
: ALTER TABLE "arts" ADD CONSTRAINT "fk_rails_25604e267c"
FOREIGN KEY ("vote_id")
  REFERENCES "votes" ("id")
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/migrate/20160229210024_add_votes_ref_to_arts.rb:3:in `change'
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "vote_id" referenced in foreign key constraint does not exist
: ALTER TABLE "arts" ADD CONSTRAINT "fk_rails_25604e267c"
FOREIGN KEY ("vote_id")
  REFERENCES "votes" ("id")
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/migrate/20160229210024_add_votes_ref_to_arts.rb:3:in `change'
PG::UndefinedColumn: ERROR:  column "vote_id" referenced in foreign key constraint does not exist
/Users/RobertRuttenberg/Dropbox/wdi/projects/full-stack-app/back-end/db/migrate/20160229210024_add_votes_ref_to_arts.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

What am I missing here?

**Comment by jrhorn424** [comment]
I think you'll find that you want to do the inverse. Your migration adds `vote_id` to `arts`, which would imply that `Art` `belongs_to :vote`. Instead, I would venture that `Art` `has_many :votes` and that `Vote` `belongs_to :art`.

If you follow this advice, you can access votes from an instance of `Art` with `art.votes` and then when you have a single `vote`, you can look at `vote.art`.

**Comment by jrhorn424** [comment]
> I would like to be able to reference all the votes associated with a piece of art

That suggests you want to be able to `art.votes`, which would imply `Art` `has_many :votes`.

**Comment by rchezrutt88** [comment]
This was my hunch. So here's where I am now:

```
class Art < ActiveRecord::Base
  has_many :votes, inverse_of: :art
end
```

```
class Vote < ActiveRecord::Base
  belongs_to :art, inverse_of :votes
  belongs_to :user, inverse_of :votes
end
```

**Comment by jrhorn424** [comment]
That looks right. You shouldn't need the migration you mentioned in your original post.

**Comment by GA-MEB** [comment]
@rchezrutt88 
Per [this question](https://github.com/ga-wdi-boston/full-stack-project/issues/168#issuecomment-190410857), yes: just add `has_many :votes` to your serializer.

**Comment by rchezrutt88** [comment]
Huh. Still not seeing any reference to the votes when an JSON art object is returned. Are you certain I don't need to run a migration to add a foreign_key reference to the Arts table?

**Comment by GA-MEB** [comment]
Oh! I'm sorry - I assumed you'd already associated them at the database level. Yes, you need migrations to associate the records, and you'll also need to generate relationship methods in order for the serializer to work.

**Comment by rchezrutt88** [comment]
```
class AddVotesRefToArts < ActiveRecord::Migration
  def change
    add_reference :arts, :votes, index: true, foreign_key: true
  end
end
```

So something like I did earlier?

**Comment by GA-MEB** [comment]
Hold on. Doesn't Vote belong to Art and User? In that case, `votes` should have foreign keys referring to `arts` and `users`.

You could either set it up that way in the initial `create_table` migration, or you could create separate migrations to create innate (i.e. non-relationship) properties and to create each foreign key.

**Comment by rchezrutt88** [comment]
Correct. And that's why I already applied this migration: 

```
class CreateVotes < ActiveRecord::Migration
  def change
    create_table :votes do |t|
      t.boolean :liked
      t.references :art, index: true, foreign_key: true
      t.references :user, index: true, foreign_key: true

      t.timestamps null: false
    end
  end
end
```

**Comment by GA-MEB** [comment]
Then you should be fine. Assuming that you've run that migration and have the proper methods, your serializer should just work. 

Have you tested your relationship methods in `rails c`?

**Comment by jrhorn424** [comment]
@rchezrutt88 That's the only migration you need. You do not need to add references to `votes` on `arts` since references to `arts` already exist on `votes`.

**Comment by rchezrutt88** [comment]
My super practical end goal here: When I get an art object back from the server, I'd like it to contain an array of vote objects. I'm wondering how I make this happen, because right now art objects look like this: 
![screenshot 2016-02-29 17 15 16](https://cloud.githubusercontent.com/assets/2382361/13410943/76dada46-df08-11e5-8c32-917b74a971f0.jpeg)

**Comment by rchezrutt88** [comment]
Well, it's not my end goal. Any old user shouldn't be able to view the details of who voted on a piece of art. But while developing this seems like a useful piece of information to be getting back from the server.

**Comment by jrhorn424** [comment]
Can you show me your art serializer?

**Comment by rchezrutt88** [comment]
@jrhorn424 

```
class ArtSerializer < ActiveModel::Serializer
  attributes :id, :author, :born_died, :title, :date, :technique, :location, :url, :form, :style, :school, :timeframe

  has_many :votes

end
```

**Comment by jrhorn424** [comment]
Try the request again with these changes to the serializer:

``` diff
-  attributes :id, :author, :born_died, :title, :date, :technique, :location, :url, :form, :style, :school, :timeframe
+  attributes :id, :author, :born_died, :title, :date, :technique, :location, :url, :form, :style, :school, :timeframe, :votes

-  has_many :votes
```

**Comment by rchezrutt88** [comment]
Apparently a circular association between the ArtSerializer and VoteSerializer. Going to add method on front end that returns the art object (with votes) separately from the new vote.
