### ISSUE TITLE
(Rails) Check Table for uniqueness under condition.

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/full-stack-project#172]
pseudo code
Users--<Lists--<Items (relationships)

I would like guidance on how to check for uniqueness on a column when X condition is met.

Check list category for uniqueness Where :user_id = 'id'. If category = new category then enforce uniqueness or deny entry.

I think I am close but I might not be understanding the interworking of ....

``` ruby
class List < ActiveRecord::Base
  #validates :list, uniqueness: true #, if: params[:user_id].present?
  validates_uniqueness_of :list, scope: :user_id                 # ...... of this line.
  has_many :items, inverse_of: :list, foreign_key: :list_id
  belongs_to :user
end
```

**Comment by GA-MEB** [comment]
`validate_uniqueness_of` expects a symbol for a property, and List doesn't have a `list` property. What is the thing that must be unique for a List? The User it's attached to?

**Comment by edesilets** [comment]
@MattB-GA-Boston A name of my column is list. I am not looking to list.

**Comment by GA-MEB** [comment]
To validate the uniqueness of column A over a scope of B and C (in other words, 'within any combination of B and C values, there are no duplicate values of A'), write

``` ruby
validates_uniqueness_of :column_A, scope: [ :column_B, :column_C ]
```
