### ISSUE TITLE
Post in front end

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/full-stack-project#173]
Hi, 

I can't seem to be able to get the value of a radio button? I need it to do a POST request to create a review w/ comments and rating attributes.

**Comment by jrhorn424** [comment]
We need to see code.

**Comment by Knguyen21** [comment]
``` html
<!-- edited by @jrhorn424 -->
<form id="review-form">

          <fieldset class="form-group">
            <label for="exampleSelect2">Rating: (disgusting) 1 - 5 (Taste like heaven)</label>
            <label class="radio-inline rating">
                <input type="radio" name="reviews[rating]" id="inlineRadio1" value="option1"> 1
              </label>
              <label class="radio-inline">
                <input type="radio" name="reviews[rating]" id="inlineRadio2" value="option2"> 2
              </label>
              <label class="radio-inline">
                <input type="radio" name="reviews[rating]" id="inlineRadio3" value="option3"> 3
              </label>
              <label class="radio-inline">
                <input type="radio" name="reviews[rating]" id="inlineRadio2" value="option2"> 4
              </label>
              <label class="radio-inline">
                <input type="radio" name="reviews[rating]" id="inlineRadio3" value="option3"> 5
              </label>
          </fieldset>
          <fieldset class="form-group">
            <label for="exampleTextarea">Your Review</label>
            <textarea class="form-control" name="reviews[comment]" id="exampleTextarea review-comment" rows="3"></textarea>
          </fieldset>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary write-review-button">Submit</button>
          </div>
```

``` js
// edited by @jrhorn424
 const myApp = {
  baseURL: 'http://localhost:3000'
};
//
let createReview = function(e) {
  console.log("button works");
  let mealId = $(this).parent().data('meal-id');
  console.log('meal id: ' + mealId);
  e.preventDefault();
  let formData = new FormData(e.target);
  $.ajax({
    url: myApp.baseURL + "/meals/" + mealId+ "/reviews",
      method: 'POST',
      contentType: false,
      processData: false,
      data: formData,
    }).done(function(data) {
      console.log("writing review");
      console.log(data);
    }).fail(function(jqxhr) {
      console.error(jqxhr);
    });
  };

    console.log(response.meals);
    $(".write-review-button").on('click', createReview());
  };  
```

**Comment by jrhorn424** [comment]
Please use correct syntax for code blocks. It's three backticks plus an extension (like js or html), followed by a _newline_. Then the closing three backticks also need to appear on their own line.

You need to beautify your code and run grunt nag. I can't tell from the indentation if you're accidentally including event registration inside a handler definition or if it's just the way it looks. Instead I have to count curly braces, which is prone to error.

**Comment by jrhorn424** [comment]
What isn't working?

**Comment by jrhorn424** [comment]
You need to beautify your code and run grunt nag. I can't tell from the indentation if you're accidentally including event registration inside a handler definition or if it's just the way it looks. Instead I have to count curly braces, which is prone to error.

**Comment by jrhorn424** [comment]
What isn't working? I need to know what error you're getting before I can render assistance.

**Comment by Knguyen21** [comment]
![screen shot 2016-02-29 at 7 01 53 pm](https://cloud.githubusercontent.com/assets/16465193/13413257/3252c348-df17-11e5-83b9-a90d2f4af117.png)

**Comment by jrhorn424** [comment]
Please fix those warnings.

Also, I still do not know the original reason for your issue. I could have been clearer, sorry about that. When I asked for errors, I wanted to know what prompted you to say:

> I can't seem to be able to get the value of a radio button?

**Comment by Knguyen21** [comment]
I need to do a post request. Therefore, I need to get the value of a radio button in order to get the ratings for my reviews data

**Comment by jrhorn424** [comment]
I can't come up with a debugging strategy without knowing what's failing. I need to see an error message, ideally with a line of code attached, so we can trace through it together.

**Comment by Knguyen21** [comment]
I came across another issue. My post request to create a new review works. However, it's returning the comment's and rating's value as null. In addition, it's not inserting the values into the database. 

![screen shot 2016-02-29 at 9 54 24 pm](https://cloud.githubusercontent.com/assets/16465193/13416306/87ba3f7e-df2f-11e5-9cf9-68fcd847a46f.png)

![screen shot 2016-02-29 at 9 55 11 pm](https://cloud.githubusercontent.com/assets/16465193/13416311/8ee63e92-df2f-11e5-93fb-0e57db1b27ad.png)

**Comment by RealWeeks** [comment]
To fix this issue we went through a number of steps to correct initial problems.

-We corrected files that were not properly exporting modules
-Found functions that weren't being called, because button events weren't properly registered.
-Properly registered events.  Passed events to functions that were previously not being called.
-Cleaned up/ refactored markup so form data could be used.
-Cleaned up/refactored handlebars templates to pass id data.
-Learned how to use the rails server to check for errors.
-Changed params to permit the correct data.
-Exported const "myApp" to pass token.

**Comment by Knguyen21** [comment]
I had another issue. CAn I still repoen this issue? or submit another one?

**Comment by RealWeeks** [comment]
@Knguyen21 what is the issue. We saw the post go through last night before I left.

**Comment by RealWeeks** [comment]
Issue in returning data, advised to open a separate issue.
