### ISSUE TITLE
Patching in front end

### ISSUE THREAD

**Issue by msyao** [ga-wdi-boston/full-stack-project#174]
Hi - I have problem patching on front end.

My code for Edit is

``` js
let articleId;
let getArticleId = function(e){
  articleId = $(e.target).attr('data-id');
  console.log(articleId);
};

let editArticle = function(e, i){
  e.preventDefault();
  console.log('edit working');
  $.ajax({
    url: apiAuth.myApp.baseUrl + '/articles/' + i,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + apiAuth.myApp.user.token,
    },
    contentType: false,
    processData: false,
    data: new FormData(e.target)
  }).done(function(data) {
    console.log(data);
  }).fail(function(jqxhr) {
    console.error(jqxhr);
  });
};
```

And I am calling it in index.js here

``` js
$('.content').on('click', '.edit-article', articleCrud.getArticleId);
$('#edit-article').on('submit', function(e) {
  articleCrud.editArticle(e, articleCrud.getArticleId);
});
```

I hit an error in my terminal that shows:

`Started PATCH "/articles/undefined" for ::1 at 2016-02-29 18:32:18 -0500
Processing by ArticlesController#update as */*
  Parameters: {"article"=>{"title"=>"trial", "author"=>"", "body"=>""}, "id"=>"undefined"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "5198c1885893eab80fb62c90cd3396f6"]]
  Article Load (0.2ms)  SELECT  "articles".* FROM "articles" WHERE "articles"."id" = $1 LIMIT 1  [["id", 0]]
Completed 404 Not Found in 3ms (Views: 0.8ms | ActiveRecord: 0.5ms)`

And from the console - the error is this
![screen shot 2016-02-29 at 6 41 23 pm](https://cloud.githubusercontent.com/assets/16352837/13412838/1fbabe5a-df14-11e5-9e5a-83b8126a77b7.png)

**Comment by jrhorn424** [comment]
I need to see the controller that's responsible for this.

**Comment by jrhorn424** [comment]
Sorry! Cancel that. The clue is here:

```
Started PATCH "/articles/undefined"
```

ID is undefined.

**Comment by jrhorn424** [comment]
I see your attempting to log the ID. What do you see? Also, try changing this to make it more obvious:

``` diff
let getArticleId = function(e){
  articleId = $(e.target).attr('data-id');
-  console.log(articleId);
+  console.log("Article ID is ", articleId);
};
```

**Comment by msyao** [comment]
Hi - Jeff

I am still getting an error. But it logs the right ID.
![screen shot 2016-02-29 at 7 01 53 pm](https://cloud.githubusercontent.com/assets/16352837/13413223/fac967ec-df16-11e5-8be8-4966a5615dad.png)

**Comment by jrhorn424** [comment]
OK. Please post controller code and I'll come take a look if I can't think of anything else to try.

**Comment by jrhorn424** [comment]
Also, could you please let me know if you changed anything else aside from the `console.log` line I mentioned? Some of the console output in your screenshot looks different.

**Comment by msyao** [comment]
Here is my code from **class ArticlesController < OpenReadController**

`````` ruby
def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      head :no_content
    else
      render json: @article.errors, status: :unprocessable_entity
    end
  end```
``````

**Comment by msyao** [comment]
Yes - I realized the .attr was targeting the wrong data id, which is actually **data-edit-id**

`````` js
let getArticleId = function(e){
  let articleId = $(e.target).attr('data-edit-id');
  console.log(articleId);
  console.log("Article ID is ", articleId);
};

let editArticle = function(e, i){
  e.preventDefault();
  console.log('edit working');
  $.ajax({
    url: apiAuth.myApp.baseUrl + '/articles/' + i,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + apiAuth.myApp.user.token,
    },
    contentType: false,
    processData: false,
    data: new FormData(e.target)
  }).done(function(data) {
    console.log(data);
  }).fail(function(jqxhr) {
    console.error(jqxhr);
  });
}; ```

And module exported those.

``````

**Comment by jrhorn424** [comment]
It looks like you're trying to do this in too many ways. The `articleId` in the snippet below is being set as a side-effect of running the `getArticleId` function; that is, `getArticleId()` returns `undefined`.

``` js
let articleId;
let getArticleId = function(e){
  articleId = $(e.target).attr('data-id');
  console.log(articleId);
};
```

Since `getArticleId()` returns `undefined`, the following snippet has `i` set to `undefined`.

``` js
//somewhere
let editArticle = function(e, i){ // 👀 here
  e.preventDefault();
  console.log('edit working');
  $.ajax({
    url: apiAuth.myApp.baseUrl + '/articles/' + i, // 👀 here
//...
// elsewhere
$('#edit-article').on('submit', function(e) {
  articleCrud.editArticle(e, articleCrud.getArticleId); // 👀 here
});
```

**Comment by msyao** [comment]
Hi Jeff - this code (including the horrid global variable :-1: ) made the patch work. It's not noticeable from the initial code. 

``` js
let articleId; //global variable
let getArticleId = function(e) {
  articleId = $(e.target).attr('data-id');
  console.log('Article ID is',articleId);
};

let editArticle = function (e) {
  e.preventDefault();
  console.log('Edit Button Works');
  $.ajax({
    url: apiAuth.myApp.baseUrl + '/articles/' + articleId,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + apiAuth.myApp.user.token,
    },
    contentType: false,
    processData: false,
    data: new FormData(e.target)
  }).done(function(data) {
    console.log('Edit Article Works');
    console.log(data);
  }).fail(function(jqxhr) {
    console.error(jqxhr);
  });
};
```

Interestingly my delete code cannot reference **articleId**, I had to use **$(e.target).attr('data-id')**

`````` js
$('.content').on('click', '.delete-article', function(e) {
  e.preventDefault();
  alert('Are you sure you want to delete?');
  console.log('Delete Button Works');
  if (!apiAuth.myApp.user) {
    console.error('Wrong!');
    return;
  }
  $.ajax({
    url: apiAuth.myApp.baseUrl + '/articles/' + $(e.target).attr('data-id'),
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + apiAuth.myApp.user.token,
    },
  }).done(function(data) {
    console.log(data);
  }).fail(function(jqxhr) {
    console.error(jqxhr);
  });
});```
``````
