### ISSUE TITLE
Cannot post, but can get successfully

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/full-stack-project#175]
My rails server is throwing this error when I try to post to records that I'm holding on the back end:

```
Started POST "/balance_records" for 127.0.0.1 at 2016-02-29 18:42:45 -0500
Processing by BalanceRecordsController#create as */*
Completed 400 Bad Request in 1ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: balance_record):
  app/controllers/balance_records_controller.rb:42:in `balance_record_params'
  app/controllers/balance_records_controller.rb:14:in `create'
```

I got a similar error to this and was able to fix it by adjusting my HTML. This post has no HTML related to it, it is simply an ajax request that is suppose to create records which include a date and a balance update. I have suspicion that my date column is messing things up because on my webpage you cant specify the date and I'm not sure how to get the correct date aside from the time stamp.

**Comment by RealWeeks** [comment]
post your controller please

**Comment by jdamiron** [comment]
```
class BalanceRecordsController < ApplicationController
  before_filter :set_balance_record, only: [:show, :update, :destroy]
  skip_before_action :authenticate, only: [:index, :show]

  def index
    render :json => BalanceRecord.all
  end

  def show
    render :json => @balance_record
  end

  def create
    @balance_record = BalanceRecord.new(balance_record_params)

    if @balance_record.save
      render json: @balance_record, status: :created
    else
      render json: @balance_record.errors, status: :unprocessable_entity
    end
  end

  def update
    if @balance_record.update(balance_record_params)
      render json: @balance_record, status: :ok
    else
      render json: @balance_record.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @balance_record.destroy
    head :no_content
  end

  def set_balance_record
    @balance_record = BalanceRecord.find(params[:id])
  end
  private :set_balance_record

  def balance_record_params
    params.require(:balance_record).permit(:date, :daily_balance)
  end
  private :balance_record_params
end
```

**Comment by jrhorn424** [comment]
I need to see the ajax responsible for this, and possibly the form. The problem is the data the server is receiving. It has to have a root key of `balance_record`.

**Comment by jdamiron** [comment]
Here is the ajax:

```
let createRecords = function() {
  let data= new FormData();
  $.ajax({
    url: myApp.baseUrl + '/balance_records',
    type: 'POST',
    headers: {
      Authorization: 'Token token=' + myApp.user.token,
    },
    contentType: false,
    processData: false,
    data: data
  }).done(function(data) {
    console.log('Successfully created records');
    console.log(data);
  }).fail(function(jqxhr) {
    console.error(jqxhr);
  });
};
```

**Comment by jrhorn424** [comment]
Because you have `let data= new FormData();`, I can't debug this without the markup for the form.

**Comment by jdamiron** [comment]
```
<div class="begin-tracking">
              <p class="begin-statement statement">Update your current bankroll
              <br>balance here.</p>
              <input type="text" class="balance-input"></input>
              <button class="submit-balances">Update</button>
            </div>
```

Could the problem be that this is not a form and simply an input?

**Comment by RealWeeks** [comment]
You can only grab form data from a form

**Comment by jdamiron** [comment]
@J-Weeks I've wrapped the input in a form, but still getting 404 not found, working through it now.

**Comment by jdamiron** [comment]
I'm getting this error:

```
POST http://localhost:3000/balance_records 404 (Not Found)send @ jquery.js:9175jQuery.extend.ajax @ jquery.js:8656createRecords @ index.js:18(anonymous function) @ index.js:155jQuery.event.dispatch @ jquery.js:4732elemData.handle @ jquery.js:4544
index.js:32 Object {readyState: 4, responseText: "{"error":{"message":"Not Found"}}", responseJSON: Object, status: 404, statusText: "Not Found"}
```

**Comment by RealWeeks** [comment]
what does your server say?

**Comment by jdamiron** [comment]
```
Started POST "/balance_records" for 127.0.0.1 at 2016-03-01 10:02:37 -0500
Processing by BalanceRecordsController#create as */*
  BalanceRecord Load (0.9ms)  SELECT  "balance_records".* FROM "balance_records" WHERE "balance_records"."id" = $1 LIMIT 1  [["id", nil]]
Completed 404 Not Found in 7ms (Views: 2.9ms | ActiveRecord: 0.9ms)
```

**Comment by J-Weeks** [comment]
is you're js the same as it was yesterday?

**Comment by RealWeeks** [comment]
is your js still the same?

**Comment by jdamiron** [comment]
@J-Weeks my ajax request? yes.

**Comment by RealWeeks** [comment]
put a debugger after you open up the createRecords function, is data defined?

**Comment by jdamiron** [comment]
well I didn't pass in any data, I define data as a new form data on the second line, so data equals an empty form data.

**Comment by gaand** [comment]
If you're not passing in any data, then that explains the missing parameter.

**Comment by jdamiron** [comment]
@gaand how would I pass in data if I haven't created it yet?

**Comment by gaand** [comment]
A POST is to create something.  You have to send that data you want in the thing to create.

**Comment by jdamiron** [comment]
I want each post to create an additional object like so:

```
"balance_records": [
{
"id": 1,
"date": "2016-03-01",
"daily_balance": 20
},
{
"id": 2,
"date": "2016-03-02",
"daily_balance": 40
},
```

I am manually entering the daily balance in the input field, how can I get the post to create a new object with a new id, the current date, and the balance that I submitted in the form?

**Comment by RealWeeks** [comment]
refer to how you used form data for ti-tac-toe

**Comment by gaand** [comment]
You don't specify an id.  That is set when you create a row.  

You can send the other data from a properly configured form or as JSON.  You could also write code in the controller to set defaults.

**Comment by jdamiron** [comment]
@gaand I am attempting to send data as so:

```
data: {
            "balance_records": [
              {
                "daily_balance": 20
              }
            ]
          }
```

I'm not sure on what to put after semicolon of daily balance. The data I want to be sent under that key is the value that's submitted in the input field.

**Comment by jdamiron** [comment]
@J-Weeks I used the post in my tic tac toe game for create games but it didn't work.

**Comment by jrhorn424** [comment]
A POST creates a single item. So the root key can't be `"balance_records"` since that's the wrong number. Also, since you're only creating a single item, you can't use an Array as the key. @erdesi90562 had a similar issue yesterday evening.

**Comment by jrhorn424** [comment]
This is the same comment I made yesterday evening. Scroll up and look at the method `balance_record_params`. What root key does it require?

**Comment by jrhorn424** [comment]
#176

**Comment by jdamiron** [comment]
@jrhorn424 

```
def balance_record_params
    params.require(:balance_record).permit(:date, :daily_balance)
  end
```

It seems like it requires balance record as the root key which is what is confusing me.

**Comment by jrhorn424** [comment]
It does. What is your root key?

**Comment by jdamiron** [comment]
It should be:

```
data: {
            "balance_record": 
              {
                "daily_balance": 20
              }
          }
```

I think, the confusion comes from the hard coding of the integer 20. How can I get value of the input when submitted to be where 20 is, or better yet, what should come after the colon on daily_balance, that is what is really confusing me.

**Comment by jrhorn424** [comment]
That is not what you originally pasted. It was plural before. Your most recent paste is correct, and it should solve the original error you posted:

> ActionController::ParameterMissing (param is missing or the value is empty: balance_record)

**Comment by jdamiron** [comment]
@jrhorn424 the post is still failing. getting this error:

```
OST http://localhost:3000/balance_records 404 (Not Found)send @ jquery.js:9175jQuery.extend.ajax @ jquery.js:8656createRecords @ index.js:17(anonymous function) @ index.js:210jQuery.event.dispatch @ jquery.js:4732elemData.handle @ jquery.js:4544
index.js:36 Object {readyState: 4, responseText: "{"error":{"message":"Not Found"}}", responseJSON: Object, status: 404, statusText: "Not Found"}
```

**Comment by GA-MEB** [comment]
What do your Rails server logs say?

**Comment by jdamiron** [comment]
```
Started POST "/balance_records" for 127.0.0.1 at 2016-03-01 14:08:03 -0500
Processing by BalanceRecordsController#create as */*
  BalanceRecord Load (1.1ms)  SELECT  "balance_records".* FROM "balance_records" WHERE "balance_records"."id" = $1 LIMIT 1  [["id", nil]]
Completed 404 Not Found in 13ms (Views: 2.6ms | ActiveRecord: 1.1ms)
```

**Comment by GA-MEB** [comment]
Can you paste in the `create` method from your BalanceRecordsController?

**Comment by jdamiron** [comment]
```
def create
    @balance_record = BalanceRecord.new(balance_record_params)

    if @balance_record.save
      render json: @balance_record, status: :created
    else
      render json: @balance_record.errors, status: :unprocessable_entity
    end
  end
```

**Comment by GA-MEB** [comment]
Put in a `binding.pry` at the beginning of that method, and step through it using `next`. Can you confirm that the program is going to the 'error' side of that `if` statement?

**Comment by jrhorn424** [comment]
A `404` during an otherwise normal-looking controller action usually indicates an error with a `before_filter`. @MattB-GA-Boston

**Comment by jdamiron** [comment]
When before filter is set like this:

```
before_filter :set_balance_record, only: [:show, :update, :destroy]
```

nothing fires. When it's set like this:

```
before_filter :set_balance_record, only: [:create,:show, :update, :destroy]
```

I get the 404 error.

**Comment by GA-MEB** [comment]
There's your error. `set_balance_record` is probably expecting an id value from the path, but you're not giving it one because you're POSTing to `/balance_records`. 

The answer is just to leave it out for `create`.

**Comment by jdamiron** [comment]
new error:

```
XMLHttpRequest cannot load http://localhost:3000/balance_records. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
```

**Comment by GA-MEB** [comment]
What errors do you see in the Rails server log? Those errors are more meaningful than the ones you see on the front end.

**Comment by jdamiron** [comment]
```
Started POST "/balance_records" for 127.0.0.1 at 2016-03-01 14:22:21 -0500
Processing by BalanceRecordsController#create as */*
Completed 400 Bad Request in 8ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: balance_record):
  app/controllers/balance_records_controller.rb:42:in `balance_record_params'
  app/controllers/balance_records_controller.rb:14:in `create'
```

**Comment by GA-MEB** [comment]
`contentType` and `processData` were left in from when FormData had previously been used.

Additionally, there was an async issue between creating a new record and getting the full list of records.
