### ISSUE TITLE
help with file upload/manipulation of a csv file

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/full-stack-project#18]
I'm trying to do a different kind of thing with file uploading than we talked about this morning. I want to upload a csv file, save it's data to the database, and not save the file.  I've been looking at http://guides.rubyonrails.org/form_helpers.html#uploading-files, but I'm having trouble understanding it/applying it to my project. I'd love to talk through the steps with someone.

**Comment by gaand** [comment]
You don't want to go that way.

Can you do everything you want if you submit rows of csv data in a textarea or some such?

**Comment by jrhorn424** [comment]
:+1: to using a textarea.

**Comment by raq929** [comment]
Sounds weird by great, thanks!
