### ISSUE TITLE
Redraw table function

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/full-stack-project#181]
I am working on a function which takes the data passed to it and creates a table based on that data. The data that is being passed is an object literal containing currently 5 records. I can successfully create table headings using the line of code before the debugger. The problem I reach is date and daily balance are my key names in the object literal and I am trying to access them using .balance_records.data and .balance_records.daily_balance. I need this data in order to build a current table after each submission. Getting the for loop to grab the columns data and daily balance is what I am tripped up on.

```
const redrawTable = function(data){
  // Build column headings
  $('tbody').html('<tr><th>Date</th><th>Current Balance</th><th>Profits</th></tr>')
  debugger;
  // Iterate through data and write new HTML for each piece of data
  for (var i = 0; i < data.balance_records.length; i++) {
    $('tbody').append(
      "<tr>" +
        "<td>" + data[i].balance_records.date + "</td>" +
        "<td>" + data[i].balance_records.daily_balance + "</td>" +
        "<td>" + (data[i+1].balance_records.daily_balance - data[i].balance_records.daily_balance) + "</td>" +
      "</tr>"
    );
  }
};
```

**Comment by jdamiron** [comment]
@MattB-GA-Boston

**Comment by RealWeeks** [comment]
use handlebars

**Comment by RealWeeks** [comment]
lines like this are what we call spaghetti

`$('tbody').html('<tr><th>Date</th><th>Current Balance</th><th>Profits</th></tr>')`

Develop good habits now and don't do this. Handlebars is a very easy tool that will make you life easier and the life of those who come after you or have to maintain your code... or even yourself later should you decide to make a change.

HTML in JS is generally a bad idea.

**Comment by GA-MEB** [comment]
@J-Weeks is right, Handlebars is really the right tool for the job here. However, if you don't have time to implement it before tomorrow, I'd recommend holding off until after the presentations to add it in.

In terms of your specific question above, what are you passing into the function as `data`? What structure does it have?

**Comment by jdamiron** [comment]
data[i] was undefined in the for loop. I needed to use data.balance_records[i], in order to access the records, that was the fix.
