### ISSUE TITLE
Two methods of making art/user/vote unique

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/full-stack-project#183]
I'd like to have my back-end guarantee that a user may only make one vote on a piece of art. It appears there are many ways to go about doing this. The two approaches at the top of this page seem promising but I am unsure which I ought to prefer. Thoughts? The first solution entails more direct modification of the model (rather than the controller) than we've done. Should that make me wary? 

http://stackoverflow.com/questions/6776787/how-to-implement-one-vote-per-user-per-comment

**Comment by gaand** [comment]
Enforcing uniqueness is something done in the model (and the database).  Have you looked at the `rails-model-validations` repository?

**Comment by GA-MEB** [comment]
I prefer the first solution (ensuring uniqueness across art pieces and users) because it's pretty straightforward for someone to change their vote after the fact; that's less true of the second solution.

**Comment by rchezrutt88** [comment]
Yes, I’m looking at it now. 

I’m confused about the first solution. That first block of code (`def vote(value, user)`) looks like it ought to belong in the controller but he’s tagged it as going to the model?

**Comment by rchezrutt88** [comment]
@MattB-GA-Boston How's that? Wouldn't I just need to patch an existing vote?

**Comment by GA-MEB** [comment]
> "I’m confused about the first solution. That first block of code (`def vote(value, user)`) looks like it ought to belong in the controller but he’s tagged it as going to the model?" 

That's actually not the significant part, I think. The migration and/or model set the uniqueness constraint.  The method is just there to ensure that the only values are 1 and -1, and to allow you to call it by writing `vote(:for)` or `vote(:against)`.

**Comment by rchezrutt88** [comment]
So following the second solution (not being contrary here; I just understand it better) my Vote model now looks like this: 

```
class Vote < ActiveRecord::Base
  belongs_to :art, inverse_of: :votes
  belongs_to :user, inverse_of: :votes

  validates_uniqueness_of :user_id, scope: :art_id 
end
```

And you're anticipating this is going to cause me some headaches going forward?

**Comment by GA-MEB** [comment]
No, sorry - I think I misunderstood your question. At the end of the day, validating uniqueness ensures one vote per person. The other stuff (in both solutions) is just window dressing.

[ EDIT: It looks like I misread the solutions as well - I thought the second was keeping votes as a tally instead of using the model. ]

**Comment by rchezrutt88** [comment]
Another related question: I'm looking at the different validation configurations now and I'm wondering about how conflicts might arise between migrations and the models. For instance, what if I were to write `validates_presence_of :liked` in my model and then modify my migration to create the vote column as `t.boolean :liked, null: true`. 

What's the correct flow here?

**Comment by GA-MEB** [comment]
In that case, your model would validate that it's value of `liked` was never null, even if the database didn't prevent a null value (BTW, `null: true` doesn't do anything, since null is an accepted value by default).

It is better practice, however, to both validate the model AND add constraints.

**Comment by rchezrutt88** [comment]
So then what’s the preferred approach? Higher level, with validation on the model? Or database level, with column constraints?

**Comment by GA-MEB** [comment]
See my last edit on the previous comment.

If this issue is resolved, may I close it?

**Comment by rchezrutt88** [comment]
Yes. But I reserve the right to reopen it goddamnit.
