### ISSUE TITLE
Need help constructing search functionality

### ISSUE THREAD

**Issue by ajordon** [ga-wdi-boston/full-stack-project#184]
I have review Kevin's issue on making a search function, but his model code is very confusing to follow. I know I will need something simular to:

```
def self.search_by_key(key)
    if key
      find(:all, conditions => ['question LIKE?', "%{key}%"])
    end
  end
```

My goal is to be able to find a specific poll by its `question`. I also updated my polls_controller to reflect the new index method definition

```
def index
    @polls = if params[:search_key].present?
      Poll.search_by_key(params[:search_key])
    else
      Poll.all
    end

    render json: @polls
  end
```

I also have my route.rb as is: 

```
get '/poll' => 'polls#search_by_key'
```

ajax request:

``` js
$('.find-poll').on('submit', function(e) {
    $.ajax({
     url: myApp.baseUrl + '/poll?search_key=' + $('#poll-search-bar').val(),
     method: 'GET',
     dataType: 'json'
   }).done(function(data) {
     myApp.poll = data.poll;
     findPollComplete();
    updateDataChart(data);
   }).fail(function(jqxhr) {
     console.error(jqxhr);
   });
  });
```

**Comment by gaand** [comment]
Have a look at `where` in ActiveRecord

**Comment by jrhorn424** [comment]
Yes, `where` most likely does what you want. Any updates @ajordon?

**Comment by ajordon** [comment]
I'm still working on it. I haven't had a successful search yet.

**Comment by gaand** [comment]
Have you tried searching in the rails console (`Model.where`)?  I find this can help since you focus on the one layer.

Edit: replace `,` with `.`

**Comment by ajordon** [comment]
Every time I submit for my search somehow generate a page reload. I had a similar issue before, which had to do with the button type, but my fix isnt working. Ill continue to update.

**Comment by gaand** [comment]
If the page reloads, that usually means preventDefault hasn't been called on the submit event.

**Comment by ajordon** [comment]
Im getting a much better failure now. The error is not in my back end regarding my controller. It says:

```
action search_by_key could not be found in PollsController
```

**Comment by jrhorn424** [comment]
This is why: `get '/poll' => 'polls#search_by_key'`

**Comment by jrhorn424** [comment]
What action do you want to call?

**Comment by ajordon** [comment]
A get

**Comment by jrhorn424** [comment]
That's not a controller action. That's an HTTP verb.

**Comment by jrhorn424** [comment]
What controller action did you put your custom search code into? It's in your OP.

**Comment by ajordon** [comment]
Index

**Comment by jrhorn424** [comment]
I suspect you already have a route to `polls#index`. So you don't need to define another one, like `get '/poll' => 'polls#search_by_key'`.

**Comment by jrhorn424** [comment]
If you do `rake routes` right now, you'll see you've defined two `get /polls` routes.

**Comment by ajordon** [comment]
Ahhhh I understand. Since I added the custom ruby logic for the search key, I dont need to generate another custom route.

**Comment by ajordon** [comment]
I successfully searched but the returned polls array is empty. Moving onto `where` debugging.

**Comment by jrhorn424** [comment]
:+1:

**Comment by ajordon** [comment]
Where syntax was incorrect. I had to take into account the `?` in the key.
