### ISSUE TITLE
Making a table editable and deletable after clicking a button

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/full-stack-project#185]
I have an update button on my chart next to each row. I want this button to be able to make the current balance column writable to the user. For instance, they make a mistake in updating their current balance and when the button is clicked, they can now edit that single cell and only that cell. My first thought is create a function which gives that cell an attr_writer method to make the cell editable, but I'm not sure if this is the best way to go about this feature. The delete button should also delete the entire row, this feature is simpler than the update button which is my main concern. Also would that update feature satisfy the CRUD requirements even though there is no patch request?

![screenshot from 2016-03-01 11-15-01](https://cloud.githubusercontent.com/assets/16493127/13433267/1281043e-df9f-11e5-96f3-0c5b4882736b.png)

**Comment by jdamiron** [comment]
@MattB-GA-Boston

**Comment by jrhorn424** [comment]
PATCH is something you do to the server. If you just edit data in your front-end, that is not communicating with the server, so it does not PATCH and it will not meet the requirements.

**Comment by jdamiron** [comment]
@jrhorn424 the data is coming from the backend. The table is made after each click of the update button on the left using this function.

```
const redrawTable = function(data){
  // Build column headings
  $('tbody').html('<tr><th>Date</th><th>Current Balance</th><th>Profits</th><th>Update/Delete</th></tr>')
  // Iterate through data and write new HTML for each piece of data
  for (var i = 0; i < data.balance_records.length; i++) {
    $('tbody').append(
      "<tr>" +
        "<td>" + data.balance_records[i].date + "</td>" +
        "<td>" + data.balance_records[i].daily_balance + "</td>" +
        "<td class='profit-column'>" + (data.balance_records[i+1].daily_balance - data.balance_records[i].daily_balance) + "</td>" +
        "<td>" + "<button class='update-row'>update</button><button class='delete-row'>delete</button>" + "</td>" +
      "</tr>"
    );
  }
};
```

P.S. I know this is spaghetti, jason told me, I will refactor after I present.

**Comment by jrhorn424** [comment]
That comes from a GET request. A PATCH changes already-existing data on the server.

**Comment by GA-MEB** [comment]
@jdamiron it sounds like what you want is to be able to click on a table, and have that become an editable box, which (after you're done editing) updates the back-end. Is that correct?

**Comment by jrhorn424** [comment]
There is literally no way to "meet the CRUD requirements" without a PATCH.

**Comment by jdamiron** [comment]
@MattB-GA-Boston yes and on click of that update button on the table, a patch request should fire and directly change the data on the backend which would redraw the table using the new data.

**Comment by GA-MEB** [comment]
Right. The feature you're describing is a little fancy - it's something that you'll often see when a front-end framework like Ember or Angular is involved. 

Something relatively simple that you could do to get you close might be to fill the `<td>`s in your table with `<input>` boxes rather than `<p>`s, and have the values you get from the back-end be written as the default values.

**Comment by jdamiron** [comment]
@MattB-GA-Boston I am attempting to put an input box and have the values go inside of that input box but I can't get it right. They keep falling either to the right of the input box or under it.

```
        "<td>" + "<input>" + data.balance_records[i].daily_balance + "</input>" + "</td>" +
```

This is to the outside of the input box on the right hand side.

**Comment by GA-MEB** [comment]
Don't put it inside the body of the input box; set it as the box's "value" property:

```
... "<input value=" + data.balance_records[i].daily_balance + "></input>" ...
```

**Comment by jrhorn424** [comment]
This is not how inputs work. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by RealWeeks** [comment]
@jdamiron are you still working on this?

**Comment by jdamiron** [comment]
@J-Weeks yes, i need a working post ajax request to attach to my update button. I am still working on post though.

**Comment by GA-MEB** [comment]
@jdamiron You'll need to do a PATCH to update, not a POST.

**Comment by jrhorn424** [comment]
@jdamiron Is your last comment meant for this issue instead? https://github.com/ga-wdi-boston/full-stack-project/issues/176

**Comment by jrhorn424** [comment]
Please close one issue for now if you can. You're free to reopen it when you're working on it again.

**Comment by jdamiron** [comment]
I meant a working patch request

**Comment by jrhorn424** [comment]
Discussed using `data-id` attribute on the button to store the id of the item to delete. @jdamiron will lookup the `.data()` method for jQuery to get the id out before making a DELETE request.

When the response comes back as success, he will repaint the table.

**Comment by jdamiron** [comment]
I am capable of only grabbing the first's button's ID using:

```
$('.delete-row').data("id")
```

I'm am stuck on what do with this ID and also how to get the 2nd, or 3rd, or Nth's button's IDs.

**Comment by jdamiron** [comment]
Properly fixed my ajax requests for patch and delete and assigned them to the click of the buttons.
