### ISSUE TITLE
creating a new association

### ISSUE THREAD

**Issue by apalmer0** [ga-wdi-boston/full-stack-project#186]
I'd like to add a 'bulletins' model with an association to gyms, such that a `gym` `has_many` `:bulletins`. In english, each bulletin would be a news story about new climbs that were recently created, so I assume a `bulletin` `has_many` `:climbs`. Currently, a `climb` `belongs_to` `:gym`, and my once i create them, a `bulletin` `belongs_to` `:gym`. However, I'd still like to be able to access climbs from the gym model. Is there a way I could set that up so that I can still see all climbs through either `gyms/1/bulletins/1/climbs` AND `gyms/1/climbs`?

**Comment by GA-MEB** [comment]
Short answer - yes. Those two relationships don't cancel each other out.

**Comment by gaand** [comment]
There's strong opinion that you shouldn't nest routes more than two deep.

But there's nothing wrong with associating bulletins with climbs. So climb belongs_to both gym and bulletin (not syntactically correct :-).).

**Comment by gaand** [comment]
I suggest asking Jeff about how to handle the routes.

**Comment by GA-MEB** [comment]
The trouble is that if you use a simple has_many/belongs_to for bulletins and climbs, then a climb can only be referenced by one bulletin, and I'm not sure that's what you want.

If you want a bulletin to reference many climbs, and you want a climb to be referenced by many bulletins, you'll want a many-to-many, probably through some third resource like a 'Tag' or a 'Mention'.

**Comment by jrhorn424** [comment]
After speaking with @apalmer0, I suggested choosing a simple route like `gym/:id/bulletins` that returns embedded `climbs` as part of the response.

**Comment by apalmer0** [comment]
I'm going to dig into this now - my plan is to create a new bulletins model that belongs_to a gym, and then add a reference to bulletins into the climb model, so i can show all bulletins when i load the gym, and within each bulletin show all climbs that have a matching bulletin_id.

Let me know if I missed something or there's something dumb about that?

Thanks!

**Comment by jrhorn424** [comment]
Seems right. `Climb` `belongs_to :bulletin` as well, right?
