### ISSUE TITLE
Posting foreign_key

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/full-stack-project#187]
After I changed the strong parameters, the comment and rating values are inserted to the reviews database, but the meal_id is not. Now the he meal_id is returning null. The POST request is not posting the meal_id(foreign key) to the database. I was able to do it before, but now I can't

**Comment by GA-MEB** [comment]
Can you paste in the content of your strong params method?

**Comment by Knguyen21** [comment]
```
    def review_params
         params.require(:review).permit(:comment, :rating, :meal_id)
    end
```

**Comment by gaand** [comment]
Please post the output from the rails server when you POST.

**Comment by Knguyen21** [comment]
``` Ruby
 Started POST "/meals/2/reviews" for ::1 at 2016-03-01 15:02:54 -0500
Processing by ReviewsController#create as */*
  Parameters: {"review"=>{"rating"=>"4", "comment"=>"hella good"}, "meal_id"=>"2"}
  User Load (1.0ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "4cd09add6147aa3804cb4b2ead6f0d1f"]]
   (4.9ms)  BEGIN
  SQL (0.8ms)  INSERT INTO "reviews" ("comment", "rating", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["comment", "hella good"], ["rating", 4], ["user_id", 6], ["created_at", "2016-03-01 20:02:54.924175"], ["updated_at", "2016-03-01 20:02:54.924175"]]
   (3.0ms)  COMMIT
Completed 201 Created in 18ms (Views: 2.6ms | ActiveRecord: 9.7ms)
```

**Comment by gaand** [comment]
meal_id is not inside the review parameters, so it's not getting passed to create.  This is a problem with how the client is sending the data.

**Comment by jrhorn424** [comment]
@Knguyen21 Has this method changed in the `ReviewsController`?

``` ruby
  def create
    @review = current_user.reviews.new(review_params)

    if @review.save
      render json: @review, status: :created, location: @review
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
```

I agree with @gaand. The problem is likely with the data being sent by AJAX.

**Comment by Knguyen21** [comment]
no.. This is what I have 

``` ruby
# edited by @jrhorn424
def create
    @review = current_user.reviews.new(review_params)

    if @review.save
      render json: @review, status: :created, location: @review
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
```

**Comment by jrhorn424** [comment]
@Knguyen21 Please use correct formatting https://help.github.com/articles/creating-and-highlighting-code-blocks/. I'll go ahead and edit your comment again.

**Comment by jrhorn424** [comment]
That is *literally* the same code I pasted.

**Comment by jrhorn424** [comment]
Thanks for confirming.

**Comment by J-Weeks** [comment]
problem with for form in the html is what i'd assume from this ``` Parameters: {"review"=>{"rating"=>"4", "comment"=>"hella good"}, "meal_id"=>"2"} ```

try changing the markup

**Comment by RealWeeks** [comment]
markup change is what im getting from this `Parameters: {"review"=>{"rating"=>"4", "comment"=>"hella good"}, "meal_id"=>"2"}`

**Comment by Knguyen21** [comment]
I"m confused. How would you suggest I fix the error?

**Comment by gaand** [comment]
Please post the html from the form you use to submit the request.

**Comment by Knguyen21** [comment]
``` <div class="modal fade" id="write-review" tabindex="-1" role="dialog" aria-labelledby="reviewsLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Reviews</h4>
        </div>
        <div class="modal-body" id="create-review" >

```
      <form id="review-form">

      <fieldset class="form-group">
        <label for="exampleSelect2">Rating: (disgusting) 1 - 5 (Taste like heaven)</label>
        <label class="radio-inline rating">
            <input type="radio" name="review[rating]" id="inlineRadio1" value=1> 1
          </label>
          <label class="radio-inline">
            <input type="radio" name="review[rating]" id="inlineRadio2" value=2> 2
          </label>
          <label class="radio-inline">
            <input type="radio" name="review[rating]" id="inlineRadio3" value=3> 3
          </label>
          <label class="radio-inline">
            <input type="radio" name="review[rating]" id="inlineRadio2" value=4> 4
          </label>
          <label class="radio-inline">
            <input type="radio" name="review[rating]" id="inlineRadio3" value=5> 5
          </label>
      </fieldset>
      <fieldset class="form-group">
        <label for="exampleTextarea">Your Review</label>
        <textarea class="form-control" name="review[comment]" id="exampleTextarea review-comment" rows="3"></textarea>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary write-review-button">Submit</button>
      </fieldset>
      <div class="modal-footer">

      </div>

    </form>

    </div>

  </div>
</div>
```

  </div>```

**Comment by gaand** [comment]
Okay, I don't see the meal_id in the form.  Are you sending it in the url?

Please post your `$.ajax` request.

**Comment by Knguyen21** [comment]
``` js
 let createReview = function(e) {
  // debugger;
  console.log("button works");
  let mealId = $('.write-review-button').attr('data-id');
  // $('.write-review-button').attr('data-id', mealId);
  // $('.write-review-button').attr('data-id', mealId);
  console.log('meal id: ' + mealId);

  let formData = new FormData(e.target);
  console.log(formData);
  $.ajax({
    url: userApi.myApp.baseURL + "/meals/" + mealId+ "/reviews",
      method: 'POST',
      headers: {
        Authorization: 'Token token=' + userApi.myApp.user.token,
      },
      contentType: false,
      processData: false,
      data: formData,
    }).done(function(data) {
      console.log("writing review");
      console.log(data);
    }).fail(function(jqxhr) {
      console.error(jqxhr);
    });
  };
```

@gaand added js and new line to opening backticks.

**Comment by gaand** [comment]
You need to merge `{meal_id: params[:meal_id}]` into the hash passed to create.

**Comment by Knguyen21** [comment]
in the controller?

**Comment by gaand** [comment]
Yes.

You should be able to use http://ruby-doc.org/core-2.2.4/Hash.html#method-i-merge

before or at this line:

``` ruby
@review = current_user.reviews.new(review_params)
```

To accomplish the task.

**Comment by Knguyen21** [comment]
Do you mean like this? 
`review_params ={meal_id: params[:meal_id]}.merge(review_params)`
should it be in private of the create function? I tried both, but it didn't work. I assume it's because my merge is incorrect

**Comment by Knguyen21** [comment]
all set. thanks!
