### ISSUE TITLE
Trying to use scripts in Handlebars

### ISSUE THREAD

**Issue by jpfriedman18** [ga-wdi-boston/full-stack-project#188]
I'm trying to use a script tag in handlebars to generate a Google Chart, however I am unable to use the variables (an array in this case) inside the script.

**Comment by jrhorn424** [comment]
What was the solution?

**Comment by RealWeeks** [comment]
I am god

**Comment by RealWeeks** [comment]
solution. Don't follow the google docs 100% do what you think is write.

-Didn't use handlebars
-Wrapped in function
-Used global for data
-called

**Comment by jrhorn424** [comment]
> I am god

I think you might be over-generalizing, @J-Weeks. 😉
