### ISSUE TITLE
Odd behavior with delete

### ISSUE THREAD

**Issue by mkutter72** [ga-wdi-boston/full-stack-project#19]
I was having trouble with a delete function in a controller so I stripped everything out of it:

def destroy
end

and it still reports and error (in server window),  I'm confused about where the second query is coming from:
Started DELETE "/messages/1" for ::1 at 2015-11-10 13:45:25 -0500
Processing by MessagesController#destroy as HTML
  Parameters: {"id"=>"1"}
  User Load (0.2ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "81d3f9418f2c65c04055f50239265398"]]
  Message Load (0.3ms)  SELECT  "messages".\* FROM "messages" WHERE "messages"."id" = $1 LIMIT 1  [["id", 1]]
Completed 404 Not Found in 3ms (Views: 0.9ms | ActiveRecord: 0.6ms)

**Comment by gaand** [comment]
Are you using strong parameters (i.e. params.require)?

**Comment by mkutter72** [comment]
yes, they are set up but i'm not using it literally there is nothing in the function.   I tried the same with my POST function (gutted it) and it did not report errors

**Comment by gaand** [comment]
Did you restart the server?  Because that's odd.

**Comment by mkutter72** [comment]
lol,  yes,  even rebooted my computer

**Comment by mkutter72** [comment]
should I try deleting the db and starting over?

**Comment by gaand** [comment]
If you can wait a few, I'd like to take a look.

**Comment by mkutter72** [comment]
sure,   rebuilt db and same issue

**Comment by gaand** [comment]
If you don't mind me snacking, I can have a look now.

**Comment by tdyer** [comment]
try putting this at the end of  your destroy action

head :no_content

**Comment by gaand** [comment]
Ah, rails defaults.

**Comment by tdyer** [comment]
Been working with Mike, problem disappeared?

**Comment by gaand** [comment]
I asked Mike to close if he's set or comment if not.
