### ISSUE TITLE
How to complete a Post request for multiple tables.

### ISSUE THREAD

**Issue by ajordon** [ga-wdi-boston/full-stack-project#191]
My ERD:
![image](https://cloud.githubusercontent.com/assets/6088950/13439581/2c30ba60-dfbc-11e5-83d2-7c61d8cf91a2.png)

When a new poll is created, my modal takes the `question` and  two `options`. Do I need two ajax posts for this or can I combine into one?

Schema:

```
create_table "options", force: :cascade do |t|
    t.text     "response"
    t.integer  "poll_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

create_table "polls", force: :cascade do |t|
    t.text     "question"
    t.date     "date_closed"
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
    t.integer  "created_by"
  end
```

**Comment by RealWeeks** [comment]
why not chain them?  Much like you (i think it was you, could have been someone else) did for tic tac toe.  How sign up was chained with sign in.

**Comment by ajordon** [comment]
I did not do that in my tic tac toe project but I guess the answer is two ajax posts.

**Comment by gaand** [comment]
If they need to all be saved together or not at all, then you'll want to send all the data in a single POST.

Then in the controller you can create the objects in a transaction.

**Comment by gaand** [comment]
#156 and #162 may be of use.

**Comment by jrhorn424** [comment]
@gaand I didn't see any references to implementation code in those issues. @ajordon, you may want to ask @apalmer0 for some advice about where to look for creating multiple things with a single form.

**Comment by gaand** [comment]
@ajordon I can help you tease out what's needed from those issues.  Talking with @ajordon may be quicker.

**Comment by RealWeeks** [comment]
Do they need to be saved together?

**Comment by ajordon** [comment]
Yes

**Comment by RealWeeks** [comment]
ok, just wanted clarification, looks like @gaand offered a 1-on-1

**Comment by ajordon** [comment]
-Updated polls_controller with option1 & option2(which include set_params)
-Altered HTML names to reflect changes
