### ISSUE TITLE
custom route question

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/full-stack-project#192]
I'd like to retrieve the single vote associated with a user for a given piece of art. I'd like to do this by defining a custom route such as arts/:art_id/votes/uservote. I've set my route up like this:
`get 'arts/:art_id/votes/with_user/:user_id' => 'arts#uservotesonart'`
My question now is, How do I write this action in the vote controller? I'm super confused. I understand it would be something like

```
def uservoteonart
@vote = Vote.where(art_id: @art.id, user_id: @current_user.id)
end
```

Am I on the right track here?

**Comment by gaand** [comment]
If this is for the logged in user you don't need to pass the `:user_id`.

Don't use `@current_user`, use the accessor `current_user`.  May I ask why you are doing that?

If this about the logged in user you want to start with `current_user` find the art then the vote.

**Comment by rchezrutt88** [comment]
How's this? 
route: `get 'arts/:art_id/votes/with_user' => 'votes#uservotesonart'`

```
  def uservoteonart
    @vote = @art.votes(user_id: current_user.id)
    render json: @vote
  end
```

**Comment by gaand** [comment]
Start with `current_user` for the query.

Please post the models for User, Art, and Vote.

**Comment by rchezrutt88** [comment]
```
class Vote < ActiveRecord::Base
  belongs_to :art, inverse_of: :votes
  belongs_to :user, inverse_of: :votes

  validates_uniqueness_of :user_id, scope: :art_id 
end
#
class User < ActiveRecord::Base
  include Authentication

  has_many :votes

end
class Art < ActiveRecord::Base
  has_many :votes, inverse_of: :art
end
```

**Comment by rchezrutt88** [comment]
@jrhorn424 I think your routing fix screwed something up.

**Comment by gaand** [comment]
Should a user have many arts (sp?) through votes?

**Comment by jrhorn424** [comment]
Stop fighting REST. I don't believe you need a custom controller action to accomplish what you're trying to do.

**Comment by jrhorn424** [comment]
If you create a `Vote` using `VotesController#create`, it is the responsibility of that action to scope by `current_user` and associate with a piece of art. 

That `create` action could be nested under `resources :arts` which is probably what you meant by:

> @jrhorn424 I think your routing fix screwed something up.

It actually fixed the problem you were running into, which is the same issue as this OP.

If you associate a vote with an art and a user when it is created, you can get both the art and the user from `GET /votes/:id`. No need for a custom route or custom action.

**Comment by rchezrutt88** [comment]
So would something like this be appropriate? 

```
  def show

    if params[:id] == 'user'
      @vote = @art.votes.where(user_id: current_user.id)
    end

    render json: @vote

  end
```

This way I can query a vote by id AND retrieve the vote associated with the current user and art if I make a get request to arts/art_id/votes/user?

**Comment by rchezrutt88** [comment]
Hey, I'm sorry, I'm still really frustrated. Not ready to close this issue.

**Comment by jrhorn424** [comment]
I thought we discussed `GET /votes/:id` for showing a single vote (unnested show)? 

What controller is your recent paste from? In any case, this is going to be a problem:

``` ruby
  if params[:id] == 'user'
```

`params[:id]` will be filled by the route. That is `:id` is something the router fills in on requests to `GET /foo/:id`.

**Comment by rchezrutt88** [comment]
The idea is that I want a separate paths for: returning ALL the votes on ALL the art, returning ALL the votes on ONE piece of art, and returning THE VOTE on ONE PIECE of art.

**Comment by rchezrutt88** [comment]
That is THE VOTE associated with the current user on ONE PIECE of art.

**Comment by GA-MEB** [comment]
> "The idea is that I want a separate paths for: returning ALL the votes on ALL the art, returning ALL the votes on ONE piece of art, and returning THE VOTE on ONE PIECE of art."

To get the first, an intuitive path might be `/votes`; for the second, you could use `/art/:art_id/votes`; for the third, `/art/:art_id/votes/:id`.

**Comment by rchezrutt88** [comment]
This works. I hate it and it sucks but I don’t care:

  def show

```
# XXX Returns array of length one. Elegant way of searching for singular element?
if params[:id] == 'user'
  @vote = @art.votes.where(user_id: current_user.id)
end

render json: @vote
```

  end

**Comment by rchezrutt88** [comment]
@MattB-GA-Boston 
So something like this (to return ALL the votes associated with an art piece)?

```
class ArtSerializer < ActiveModel::Serializer
  attributes
   :id,
   :author,
   :born_died,
   :title,
   :date,
   :technique,
   :location,
   :url,
   :form,
   :style,
   :school,
   :timeframe,
   :get_votes


  has_many :votes

  # TODO add serializer that returns all votes!

private

  def get_votes
    Vote.where(art_id: id)
  end


end
```

**Comment by GA-MEB** [comment]
> `# TODO add serializer that returns all votes!`

That part's not necessary - having the `has_many :votes` in your serializer is what adds the votes to your JSON.

You also no longer need `get_votes`.

**Comment by rchezrutt88** [comment]
This is a joke, right?

**Comment by rchezrutt88** [comment]
My sense of humor is not what it was eight hours ago.

**Comment by rchezrutt88** [comment]
Oh. Right. I obsoleted that TODO by adding the get_votes to the serializer.

**Comment by rchezrutt88** [comment]
Made that note while we were chatting.

**Comment by rchezrutt88** [comment]
So I didn't forget what we were talking about in the ten seconds it took me to walk from the conference room to where I'm sitting.

**Comment by jrhorn424** [comment]
I'm glad this is resolved. I'm going to write the note I should have written three hours ago.

> @MattB-GA-Boston To get the first, an intuitive path might be /votes; for the second, you could use /art/:art_id/votes; for the third, /art/:art_id/votes/:id.

This accomplishes your goal. When we spoke earlier, I was calling into question the wisdom of having a multiply nested route for your third requirement, since it is redundant. Allow me to explain:
1. To get all votes on all art, `GET /votes` is intuitive and accomplishes your first goal. It routes to the votes controller index action.
2. To get all votes for one piece of art, `GET /arts/:id/votes` routes to the votes controller index action. You can then have an if statement since the route for your first goal also routes to this action.
3. To get one vote for one piece of art, `GET /votes/:id` is RESTful, semantic, and sufficient. This is because the serializer should at least return something like `{ "vote": { "user_id": 1, "art_id": 1}, "id": 1 }`. There's your art right there. What would `GET /arts/1/votes/1` return different? Furthermore, you can customize the serializer to embed the entire art object if you wish, so the example becomes:
   
   ``` json
   {
     "vote": {
       "user_id": 1,
       "art": {
         "id": 1,
         "foo": "bar"
       }
     }
   }
   ```

**Comment by jrhorn424** [comment]
@apalmer0 Had a similar question in #186.
