### ISSUE TITLE
Deployed Site: seemingly random features do not work

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/full-stack-project#193]
Here is my deployed site: http://mfbrewster.github.io/diabetes-manager/
my front end repo: https://github.com/MFBrewster/diabetes-manager
and my back end repo: https://github.com/MFBrewster/diabetes-manager-api

The problem is that, even though locally every feature I have written for my site is working correctly, on the deployed site there are a bunch of really strange and apparently random errors. For example, I cannot sign in on an existing account on the hosted page, but I can sign up a new account. 

Once signed up, you're automatically logged in so you can test the rest of the features. The page links for change password, view medicines, and add medicine all work, but the page links for view doses and sign out do not work (both of them work locally).

I had similar issues with my tic-tac-toe game. Can you think of any thing which might be causing this?

**Comment by jrhorn424** [comment]
What was the output of `heroku logs`?

**Comment by gaand** [comment]
I'm seeing a repeating error in the chrome console when I load your deployed app.

**Comment by MFBrewster** [comment]
I think there were two separate problems here... (1) I had to go through the gh-pages push more methodically, and (2) I didn't take account of the fact that my database values (including user credentials) weren't being loaded along with my gh-pages.

**Comment by MFBrewster** [comment]
the app is working as it should for me now, I do not know why it would be giving AND a repeating error.

**Comment by jrhorn424** [comment]
@MFBrewster Please remove the script tag for livereload in your `<head>`. I can help you update your configuration so livereload still works without that script tag.

**Comment by jrhorn424** [comment]
That's what is causing the repeating error.

**Comment by RealWeeks** [comment]
@MFBrewster Did @jrhorn424 fix the issue?  Do you still need assistance with this?

**Comment by jrhorn424** [comment]
@MFBrewster To ask what @J-Weeks asked in a different way, do you still have errors other than the ones from the webpack dev server (WDS)?

**Comment by MFBrewster** [comment]
No, only the dev server error is persisting. Should I close?

**Comment by RealWeeks** [comment]
@MFBrewster yes.

**Comment by RealWeeks** [comment]
issue noted

**Comment by MFBrewster** [comment]
Thank you

**Comment by jrhorn424** [comment]
Speaking with Mike, we discovered a bug with the tooling. It's tracked at https://github.com/ga-wdi-boston/js-template/issues/29.
