### ISSUE TITLE
creating new instance doesn't save all data attributes (just one of two)

### ISSUE THREAD

**Issue by apalmer0** [ga-wdi-boston/full-stack-project#195]
I created a 'Bulletin' model that has 2 attributes: content and a gym_id. When I create a bulletin, only one attribute is saved.

**bulletins#create**

``` ruby
  def create
    @bulletin = Bulletin.new(bulletin_params)

    if @bulletin.save
      render json: @bulletin, status: :created
    else
      render json: @bulletin.errors, status: :unprocessable_entity
    end
  end
```

**bulletin_params**

``` ruby
  def bulletin_params
    params.require(:bulletin).permit(:content, :gym_id)
  end
  private :bulletin_params
```

**the form for actually creating the bulletin**

``` html
 <form id="new-bulletin">
        <input type="text" class="form-control" id="inputBulletinContent" placeholder="content" name="bulletin[content]" value="">
        <input type="hidden" class="form-control" id="inputBulletinGymId" name="bulletin[gym_id]" value="{{gymId}}">
        <div class="modal-footer">
          <button type="submit" name="submit" class="btn btn-success create-bulletin-button" data-gym-id="{{gymId}}">Create Bulletin</button>
        </div>
      </form>
```

**the error i get**

``` ruby
Started POST "/gyms/1/bulletins" for ::1 at 2016-03-01 16:28:41 -0500
Processing by BulletinsController#create as */*
  Parameters: {"gym_id"=>"1"}
  User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "6f4ac0b5de73dfccbcf902375c763764"]]
Completed 400 Bad Request in 5ms (ActiveRecord: 0.9ms)

ActionController::ParameterMissing (param is missing or the value is empty: bulletin):
  app/controllers/bulletins_controller.rb:42:in `bulletin_params'
  app/controllers/bulletins_controller.rb:14:in `create'
```

**Comment by jrhorn424** [comment]
> `ActionController::ParameterMissing (param is missing or the value is empty: bulletin)`

What data are you sending as part of the request? Can you share your AJAX?

**Comment by apalmer0** [comment]
``` js
  $('.content-body').on('click', 'button.create-bulletin-button', function(event) {
    event.preventDefault();
    console.log(event.target);
    let gymId = $(this)[0].dataset.gymId;
    var formData = new FormData(event.target);
    $.ajax({
      url: myApp.baseUrl + '/gyms/' + gymId + '/bulletins',
      headers: {
        Authorization: 'Token token=' + myApp.user.token,
      },
      method: 'POST',
      contentType: false,
      processData: false,
      data: formData
    }).done(function (data) {
      console.log(data);
      console.log('holy crap did that work????');
    }).fail(function (jqxhr) {
      console.error(jqxhr);
    });
  });
```

**Comment by jrhorn424** [comment]
Ah sweet! FormData. I need to inspect your form. 😄

**Comment by apalmer0** [comment]
here ya go

``` html
<script>console.log('new bulletin handlebars');</script>
<div class="story">
  <div class="row">
    <div class="story-header col-md-2">
      <img class="bulletin-thumbnail" src="assets/images/create.png">
    </div>
    <div class="story-body col-md-10">
      <form id="new-bulletin">
        <input type="text" class="form-control" id="inputBulletinContent" placeholder="content" name="bulletin[content]" value="">
        <input type="hidden" class="form-control" id="inputBulletinGymId" name="bulletin[gym_id]" value="{{gymId}}">
        <div class="modal-footer">
          <button type="submit" name="submit" class="btn btn-success create-bulletin-button" data-gym-id="{{gymId}}">Create Bulletin</button>
        </div>
      </form>
      <div class="story-expand">

      </div>
    </div>
  </div>
</div>

```

**Comment by jrhorn424** [comment]
Ah, phooey. I missed that in the OP. Thanks for not calling me out, but I kind of deserved it.

I edited your code blocks to add extensions so I could debug in color. I'm currently processing. 😄

**Comment by jrhorn424** [comment]
Ah-hah! What if you do this?

``` diff
- $('.content-body').on('click', /* ... */); // you're currently targeting the button in your delegation
+ $('.content-body').on('submit', /* ... */); // target the form in your event delegation
```

Do you understand the difference?

**Comment by apalmer0** [comment]
So this may be worthy of another issue - if I use `on('submit')`, the button just causes the page to reload

**Comment by jrhorn424** [comment]
Ok. To prevent the page from reloading,

``` diff
- <form id="new-bulletin">
+ <form id="new-bulletin" action="#">
```

You still have `preventDefault`, right?

**Comment by apalmer0** [comment]
I tried changing `on('click')` to `on('submit')` and adding `action="#"`, but the button goes back to reloading the page

**Comment by RealWeeks** [comment]
is that with the prevent default as well?

**Comment by apalmer0** [comment]
yup, still have that on every ajax call

**Comment by RealWeeks** [comment]
are you still here?

**Comment by gaand** [comment]
Try:

``` diff
- $('.content-body').on('click', ...
+ $('#new-bulletin').on('submit', ...
```

**Comment by apalmer0** [comment]
Unfortunately a new issue popped up - I think right after deploying to heroku - and now my app isn't working properly so I can't test this yet. it seems the server log is duplicating itself and data is not being returned properly. Happy to give any more details needed but not sure where to start. 

#198

**Comment by gaand** [comment]
Sorry, should have made this more clear:

``` diff
- $('.content-body').on('click', 'button.create-bulletin-button', function(event) {
+ $('#new-bulletin').on('submit', function(event) {
```

**Comment by apalmer0** [comment]
Sorry - this ends up refreshing the page again

**Comment by gaand** [comment]
I see now.  It's a handlebars template.

You can't add the event handler until after the template is rendered.

**Comment by apalmer0** [comment]
Nevermind, this wasn't actually the case.
~~I think part of this may be a result of my being lazy - I liked the way the buttons lined up on the bottom right of the modal so I reused some code from there. Specifically,~~

~~If I remove that div with the `modal-footer` class, the page doesn't automatically reload. Unfortunately it doesn't submit anything either, but I think it's closer?~~

**Comment by gaand** [comment]
So, it's not a handlebars template? I ask because:

``` html
<script>console.log('new bulletin handlebars');</script>
```

**Comment by gaand** [comment]
Does this line fomr the even handler run?

``` js
console.log(event.target);
```

If so, what's the output?

**Comment by apalmer0** [comment]
hmm... `console.log(event.target);` produces this:

`<button type="submit" name="submit" class="btn btn-success create-bulletin-button" data-gym-id="1">Create Bulletin</button>`

^ only when `$('.content-body').on('click', 'button.create-bulletin-button', function(event) {` is the event handler. When I use `$('#new-bulletin').on('submit', function(event) {`, it refreshes the page before it can console.log

**Comment by apalmer0** [comment]
And no, it is a handlebars template. That console.log was just for me to make sure that file was actually being loaded when i first created it.

**Comment by apalmer0** [comment]
So that explains why the gym_id is being saved - it's a data attribute I'm including in the button id for another reason... it's not actually coming from the form.

**Comment by gaand** [comment]
Yes.  And adding the submit handler doesn't work because you have to add it after the template had been rendered and added to the DOM.  Which is why you get the page reload.

**Comment by apalmer0** [comment]
I'm going to just take a new approach and use a modal like I've done elsewhere. I'd love to figure this out the way I was going for but I think this will actually get it working.
