### ISSUE TITLE
rails server log is duplicating every output and no longer runs properly

### ISSUE THREAD

**Issue by apalmer0** [ga-wdi-boston/full-stack-project#198]
Started happening basically right after deploying to heroku - I'm now getting the following outputs in my server logs, and any authenticated method isn't working any more

```
Started OPTIONS "/?[object%20FormData]" for ::1 at 2016-03-01 19:14:35 -0500
Started OPTIONS "/?[object%20FormData]" for ::1 at 2016-03-01 19:14:35 -0500

Started GET "/?[object%20FormData]" for ::1 at 2016-03-01 19:14:35 -0500
Started GET "/?[object%20FormData]" for ::1 at 2016-03-01 19:14:35 -0500
Processing by Rails::WelcomeController#index as */*
Processing by Rails::WelcomeController#index as */*
  Parameters: {"object FormData"=>nil}
  Parameters: {"object FormData"=>nil}
  Rendered /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/templates/rails/welcome/index.html.erb (0.1ms)
  Rendered /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/templates/rails/welcome/index.html.erb (0.1ms)
Completed 200 OK in 13ms (Views: 12.9ms | ActiveRecord: 0.0ms)
Completed 200 OK in 13ms (Views: 12.9ms | ActiveRecord: 0.0ms)
```

**Comment by gaand** [comment]
That's something that should be a POST or PATCH running as a GET.

**Comment by apalmer0** [comment]
I just removed all the changes we made to the Gemfile during Matt's "push to heroku" lesson and got it working again. Thoughts? Those changes were, specifically:

`gem 'rails-api'` turned back into: `gem 'rails-api', git: 'git@github.com:rails-api/rails-api.git'`
`gem 'active_model_serializers'` turned back into: `gem 'active_model_serializers', git: 'git@github.com:rails-api/active_model_serializers.git'`

and removing these guys:

```
gem 'rails_12factor'
gem 'dotenv-rails', :groups => [:development, :test]

```

When should they be removed from the gemfile? When should they be added?

**Comment by gaand** [comment]
The problem seemed to me to be something happening in the client, not the api, so I don't understand why those changes would make a difference.  

Changes to gems in rails don't change the method the client uses to submit requests.

I'm not sure which gems you're using, but pointing to gems on github is not usually what you want. If you have to do that you should look into specifying a tag.
