### ISSUE TITLE
Trying to use a Create Method via authentication on a table that is 2 join tables away from User

### ISSUE THREAD

**Issue by kelvinma** [ga-wdi-boston/full-stack-project#20]
Current Data structure:
User (has many) --> Weekly Menus (has many Recipes through Meals) --> Meals (belongs to weekly menus and recipes) --> Recipes (has many meals)

When logged in as User, when I try to create a Recipe via POST, I get a an error message that says undefined method "recipes" for User. I'm pretty sure that is because I have not set any "has_many, through" associations for Users and Recipes. I am not even sure that association is even necessary via how I am calling my data, so I'm wondering if there is a way around it. I do not want to allow recipe creation without authentication.

**Comment by GA-MEB** [comment]
Can you share the content of your RecipesController? My hunch is that the problem is in your `create` method.

**Comment by kelvinma** [comment]
I'm not very confident in my understanding of authentication implementation.

```
class RecipesController < OpenReadController
    before_action :set_recipe, only: [:update, :destroy]

 def index
    @recipes = Recipe.all

    render json: @recipes
  end

  # GET /recipes/1
  def show
    @recipe = Recipe.find(params[:id])

    render json: @recipe
  end

  # POST /recipes
  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      render json: @recipe, status: :created, location: @recipe
    else
      render json: @recipe.errors, status: :unprocessable_entity
    end
  end

  # PATCH /recipes/1
  def update
    if @recipe.update(recipe_params)
      head :no_content
    else
      render json: @recipe.errors, status: :unprocessable_entity
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy

    head :no_content
  end

  def set_recipe
    @recipe = current_user.recipes.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :which_meal, :style, :instructions)
  end

  private :set_recipe, :recipe_params
end
```

**Comment by gaand** [comment]
If your not using `has_many :recipes` the you can't create a recipe off off current_user.  

Since your controller inherits from `OpenReadController` the create action is authenticated.  So, I think you just want `Recipe.new`

**Comment by kelvinma** [comment]
So simple. Brilliant!

**Comment by gaand** [comment]
That also means you don't want `set_recipe` to use `current_user`.

**Comment by gaand** [comment]
If that solves your problem, please close the issue.  If not, comment again :-)

**Comment by kelvinma** [comment]
SUCCESS!
