### ISSUE TITLE
Serializer question

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/full-stack-project#203]
So let's say I want to return two arrays with every art object: An array of all the votes on the art object and the singular vote associated with the current_user and the art object. Can this be accomplished just in the serializer? Something like this: 

```
class ArtSerializer < ActiveModel::Serializer
  attributes :id, :author, :born_died, :title, :date, :technique, :location, :url, :form, :style, :school, :timeframe
  # :votes
  has_many :votes

private

  def my_vote
    Vote.where(art_id: id, user_id: current_user.id)
  end


end
```

...but then how do I return then result from my_vote with the rest of the attributes and the many votes?

**Comment by rchezrutt88** [comment]
@MattB-GA-Boston Sorry.

**Comment by GA-MEB** [comment]
> "Can this be accomplished just in the serializer? Something like this:"

You'd need to add `:my_vote` to the list of attributes, but yes.

> " how do I return then result from my_vote with the rest of the attributes and the many votes"

Does that possibly answer this question?

**Comment by rchezrutt88** [comment]
Huh. I did that. Yet still: 

```
NameError (undefined local variable or method `current_user' for #<ArtSerializer:0x007ffe3475c120>):
  app/serializers/art_serializer.rb:9:in `my_vote'
  app/controllers/arts_controller.rb:53:in `random'
```

Can the serializer not see the current_user?

**Comment by GA-MEB** [comment]
Shoot, I missed that. Yes, `current_user` is a method available to controllers, not serializers.

Let's sit down for this one.

**Comment by gaand** [comment]
Inside the `my_vote` method, you can use the AMS method `scope` which by default resolves to `current_user` from the controller.  Depending on the context, `current_user` may be `nil`.

If that provides a resolution, please close this issue.

**Comment by rchezrutt88** [comment]
> Depending on the context, current_user may be nil.

Can you elaborate? For instance if the controller calling the serializer inherits from OpenReadController rather than ProtectedController? @gaand

**Comment by gaand** [comment]
Yes.  OpenReadController does not guarantee that current user is set for `index` and `show`. If a valid token has been passed with the request, current_user will be set, nil otherwise.

If this answers your question, please close the issue.  Thanks.

**Comment by rchezrutt88** [comment]
@gaand Sweet. Thanks for the clarification. I set my ArtSerializer up like this and it appears to be functioning as intended! 

```
class ArtSerializer < ActiveModel::Serializer
  attributes :id, :author, :born_died, :title, :date, :technique, :location, :url, :form, :style, :school, :timeframe
  has_many :votes
  has_one :my_vote

  private

  def my_vote
    Vote.find_by(voteable_id: object.id, voter_id: scope.id)
  end

end
```
