### ISSUE TITLE
Constant error showing up in console after deployment

### ISSUE THREAD

**Issue by seatuna** [ga-wdi-boston/full-stack-project#204]
Everything works, but I'm getting this annoying error when I open Chrome's developer console.  Is this an indication of something terrible?

Not really urgent since my crud still works, but this will probably be super annoying during presentation...

![screen shot 2016-03-01 at 10 27 33 pm](https://cloud.githubusercontent.com/assets/16471076/13449870/572ffd52-dffd-11e5-9ba0-8e9d65d0c10d.png)

**Comment by jrhorn424** [comment]
This is a known issue. Thanks for reporting.

It's tracked at https://github.com/ga-wdi-boston/js-template/issues/29 and is related to part of the discussion in #193.

Ignore for now.

**Comment by seatuna** [comment]
Okie dokie!
