### ISSUE TITLE
Merge conflict

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/full-stack-project#206]
Hi, 

I have a merge conflict with my gh-pages and Master branch.  I think I merged training with gh-pages and then checkout Master branch and continued creating new branches from the master branch and finally merging all the feature branch into the master branch. Now If I try to merge master to gh-pages, I will get numerous merge conflict. 

CAn you give me advice how to proceed?  I need to add a few code, but I'm unsure what branch to put the code in because I'm worried there will be more merge conflicts. 
Below is my merge conflict with my branches. 
https://github.com/Knguyen21/menu-review_frontend/network

**Comment by RealWeeks** [comment]
Correct the merge conflict first. Then add more code.
