### ISSUE TITLE
undefined method `contacts' for nil:NilClass

### ISSUE THREAD

**Issue by rdelvallej32** [ga-wdi-boston/full-stack-project#208]
Hi,

I've been working on this issue for two days and unsure as to why the inheritance from my controller is not setting my current user. Essentially, I inherited the Contacts Controller, from OpenRead, which inherits from ProtectedController, which inherits from ApplicationController. Within Application Controller, it sets the current user and has an attr_reader called current_user. So, I used that current_user to apply in my Contacts Controller and Rails is not recognizing my set_contact. Is this an inheritance issue or am I being too restrictive with my before_action? Ideally, I want the current user to be the only person that can use the index, show , update and destroy actions. 

When I run requests I receive the undefined method `contacts' for nil:NilClass. It looks like it's not recognizing when I call current_user.

``` ruby

# Contacts Controller
class ContactsController < OpenReadController
  before_action :set_contact, only: [:index, :show, :update, :destroy]

  # GET /contacts
  def index
    @contacts = Contact.all

    render json: @contacts
  end

def set_contact
    @contact = current_user.contacts.find(params[:id]) 
  end
```

**Comment by laurenfazah** [comment]
Are you sure the undefined method `contacts` error is coming from the `set_contact` method's `current_user`?

**Comment by RDegnen** [comment]
try checking what type of variable current_user is in the Application Controller

**Comment by rdelvallej32** [comment]
okay, i'll take a look

**Comment by rdelvallej32** [comment]
So, I think I made progress? Its no longer calling the undefined method message any longer because I switched the inheritance from OpenReadController to ProtectedController. Now, I am receiving the HTTP Token: Access denied. However, when I sign-in as a user with the current session token, its giving me this huge error when I run a controller test to see what is going on:

expected `#<ActionController::TestResponse:0x007fbac39c8af8 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007fbac39b0688>, @stream=#<ActionDispatch::Response::Buffer:0x007fbac3900d00 @response=#<ActionController::TestResponse:0x007fbac39c8af8 ...>, @buf=["HTTP Token: Access denied.\n"], @closed=false>, @header={"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff", "WWW-Authenticate"=>"Token realm=\"Application\"", "Content-Type"=>"text/html; charset=utf-8"}, @status=401, @sending_file=false, @blank=false, @cv=#<MonitorMixin::ConditionVariable:0x007fbac39b05c0 @monitor=#<ActionController::TestResponse:0x007fbac39c8af8 ...>, @cond=#<Thread::ConditionVariable:0x007fbac39b0598>>, @committed=false, @sending=false, @sent=false, @content_type="text/html", @charset="utf-8", @cache_control={}, @etag=nil, @request=#<ActionController::TestRequest:0x007fbac3a01740 @env={"rack.version"=>[1, 3], "rack.input"=>#<StringIO:0x007fbac39a2380>, "rack.errors"=>#<StringIO:0x007fbac1648088>, "rack.multithread"=>true, "rack.multiprocess"=>true, "rack.run_once"=>false, "REQUEST_METHOD"=>"GET", "SERVER_NAME"=>"example.org", "SERVER_PORT"=>"80", "QUERY_STRING"=>"", "rack.url_scheme"=>"http", "HTTPS"=>"off", "SCRIPT_NAME"=>nil, "CONTENT_LENGTH"=>"0", "HTTP_HOST"=>"test.host", "REMOTE_ADDR"=>"0.0.0.0", "HTTP_USER_AGENT"=>"Rails Testing", "action_dispatch.routes"=>#<ActionDispatch::Routing::RouteSet:0x007fbac3de0bb8>, "action_dispatch.parameter_filter"=>[:password], "action_dispatch.redirect_filter"=>[], "action_dispatch.secret_token"=>nil, "action_dispatch.secret_key_base"=>"257c625ec97ae838d50b76717ac50de7d3d77bbc73dd88cf3bfec4e679e9e99f5e63a7824bee6752d7e1b7744209191c498c606cfcdc72a79788518d2a2f2b10", "action_dispatch.show_exceptions"=>false, "action_dispatch.show_detailed_exceptions"=>true, "action_dispatch.logger"=>#<ActiveSupport::Logger:0x007fbac1885e68 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007fbac1885df0 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x007fbac3c3bb00 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x007fbac1885da0 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<File:/Users/robertodelvallejr./wdi/projects/catch_up_api/log/test.log>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007fbac1885d78>>, @local_levels=#<ThreadSafe::Cache:0x007fbac1885cd8 @backend={}, @default_proc=nil>>, "action_dispatch.backtrace_cleaner"=>#<Rails::BacktraceCleaner:0x007fbac39e16c0 @filters=[#<Proc:0x007fbac39e15a8@/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/backtrace_cleaner.rb:14>, #<Proc:0x007fbac39e1580@/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/backtrace_cleaner.rb:15>, #<Proc:0x007fbac39e1558@/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/backtrace_cleaner.rb:16>, #<Proc:0x007fbac39e1120@/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/backtrace_cleaner.rb:29>], @silencers=[#<Proc:0x007fbac39e10f8@/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/backtrace_cleaner.rb:19>], @root="/Users/robertodelvallejr./wdi/projects/catch_up_api/">, "action_dispatch.key_generator"=>#<ActiveSupport::CachingKeyGenerator:0x007fbac39e0f68 @key_generator=#<ActiveSupport::KeyGenerator:0x007fbac39e0f90 @secret="257c625ec97ae838d50b76717ac50de7d3d77bbc73dd88cf3bfec4e679e9e99f5e63a7824bee6752d7e1b7744209191c498c606cfcdc72a79788518d2a2f2b10", @iterations=1000>, @cache_keys=#<ThreadSafe::Cache:0x007fbac39e0f40 @backend={"signed_token64"=>"\xF1\x12\xFA\x03V`\xBA\xDE\xD7\x9E\v\xB6\x8E\x9A\xC1\x02\xE9\x13-ub[\xA6\x9F\x91\x85\xD3\xF2\xBFD\xCCle>\b_$\x97+\xFB}4\x1EN\xB4\x82\x05\x00\x1F|\xB1D\xB62\x98\x87~\xB0\xEB\xD1\xCF\xDA\x97M"}, @default_proc=nil>>, "action_dispatch.http_auth_salt"=>"http authentication", "action_dispatch.signed_cookie_salt"=>"signed cookie", "action_dispatch.encrypted_cookie_salt"=>"encrypted cookie", "action_dispatch.encrypted_signed_cookie_salt"=>"signed encrypted cookie", "action_dispatch.cookies_serializer"=>nil, "action_dispatch.cookies_digest"=>nil, "rack.session"=>{}, "rack.session.options"=>{:key=>"rack.session", :path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :sidbits=>128, :cookie_only=>true, :secure_random=>SecureRandom, :id=>"9bbf43aabbd085765e87ef0f3205861d"}, "HTTP_AUTHORIZATION"=>"Token token=2138a10f4a849a74e5de74d4001007d1", "action_dispatch.request.query_parameters"=>{}, "action_dispatch.cookies"=>#<ActionDispatch::Cookies::CookieJar:0x007fbac39b0c50 @key_generator=#<ActiveSupport::CachingKeyGenerator:0x007fbac39e0f68 @key_generator=#<ActiveSupport::KeyGenerator:0x007fbac39e0f90 @secret="257c625ec97ae838d50b76717ac50de7d3d77bbc73dd88cf3bfec4e679e9e99f5e63a7824bee6752d7e1b7744209191c498c606cfcdc72a79788518d2a2f2b10", @iterations=1000>, @cache_keys=#<ThreadSafe::Cache:0x007fbac39e0f40 @backend={"signed_token64"=>"\xF1\x12\xFA\x03V`\xBA\xDE\xD7\x9E\v\xB6\x8E\x9A\xC1\x02\xE9\x13-ub[\xA6\x9F\x91\x85\xD3\xF2\xBFD\xCCle>\b_$\x97+\xFB}4\x1EN\xB4\x82\x05\x00\x1F|\xB1D\xB62\x98\x87~\xB0\xEB\xD1\xCF\xDA\x97M"}, @default_proc=nil>>, @set_cookies={}, @delete_cookies={}, @host="test.host", @secure=false, @options={:signed_cookie_salt=>"signed cookie", :encrypted_cookie_salt=>"encrypted cookie", :encrypted_signed_cookie_salt=>"signed encrypted cookie", :secret_token=>nil, :secret_key_base=>"257c625ec97ae838d50b76717ac50de7d3d77bbc73dd88cf3bfec4e679e9e99f5e63a7824bee6752d7e1b7744209191c498c606cfcdc72a79788518d2a2f2b10", :upgrade_legacy_signed_cookies=>false, :serializer=>nil, :digest=>nil}, @cookies={}, @committed=false>, "rack.request.cookie_hash"=>{}, "action_dispatch.request.path_parameters"=>{:format=>"json", :controller=>"contacts", :action=>"index"}, "action_dispatch.request.content_type"=>nil, "action_dispatch.request.request_parameters"=>{}, "action_dispatch.request.flash_hash"=>#<ActionDispatch::Flash::FlashHash:0x007fbac39a2308 @discard=#<Set: {}>, @flashes={}, @now=nil>, "PATH_INFO"=>"/contacts.json", "action_dispatch.request.parameters"=>{"format"=>"json", "controller"=>"contacts", "action"=>"index"}, "action_dispatch.request.formats"=>[#<Mime::Type:0x007fbac0a50960 @synonyms=["text/x-json", "application/jsonrequest"], @symbol=:json, @string="application/json", @hash=-2041574739715772101>]}, @filtered_parameters={"format"=>"json", "controller"=>"contacts", "action"=>"index"}, @filtered_env=nil, @filtered_path=nil, @protocol="http://", @port=80, @method=nil, @request_method="GET", @remote_ip=nil, @original_fullpath=nil, @fullpath="/contacts.json", @ip=nil, @uuid=nil, @formats=nil, @set_cookies={}, @cookies={}>>.successful?` to return true, got false

**Comment by rdelvallej32** [comment]
Is this error because I'm being too restrictive in my controller?

``` ruby

class ContactsController < ProtectedController
  before_action :set_contact, only: [:index, :show, :update, :destroy]
```

**Comment by laurenfazah** [comment]
Could I see what that test looks like?

**Comment by rdelvallej32** [comment]
Here is my controller rspec:

``` ruby

require 'rails_helper'

RSpec.describe ContactsController do
  def contact_params
    {
      first_name: 'Henry',
      last_name: 'Holmes',
      occupation: 'Professor',
      professional_relationship: 'Mentor',
      company: 'BU',
      last_contacted: '20120407',
      fact: 'Likes Pizza'
    }
  end

  def contact
    Contact.first
  end

  def user_params
    {
      email: 'alice@example.com',
      password: 'foobarbaz',
      password_confirmation: 'foobarbaz'
    }
  end

  def user
    User.first
  end

  before(:all) do
    User.create!(user_params)
    Contact.create!(contact_params)
  end

  after(:all) do
    Contact.delete_all
    User.delete_all
  end

  context 'when authenticated' do
     before(:each) do
       post :signup, { credentials: user_params }, format: :json
       post :signin, { credentials: user_params }, format: :json
     end
    before(:each) do
      request.env['HTTP_AUTHORIZATION'] = "Token token=#{user.token}"
    end

    describe 'GET index' do
      before(:each) do
        get :index, format: :json
      end

      it 'is successful' do
        expect(response).to be_successful
      end

      it 'renders a JSON response' do
        contact_response = JSON.parse(response.body)
        expect(contact_response).not_to be_nil
      end
    end

    describe 'GET show' do
      before(:each) do
        get :index, id: contact.id, format: :json
      end

      it 'is successful' do
        expect(response).to be_successful
      end

      it 'renders a JSON response' do
        contact_response = JSON.parse(response.body)
        expect(contact_response).not_to be_nil
      end
    end

    describe 'POST create' do
      before(:each) do
        post :create,
             { contact: contact_params }, format: :json
      end

      it 'is successful' do
        expect(response).to be_successful
      end

      it 'renders a JSON response' do
        contact_response = JSON.parse(response.body)

        expect(contact_response).not_to be_nil
      end
    end

    describe 'PATCH update' do
      def new_contact_params
        { occupation: 'Dean'
        }
      end

      before(:each) do
        patch :update,
              { id: contact.id, contact: new_contact_params },
              format: :json
      end

      it 'is successful' do
        expect(response).to be_successful
      end

      it 'renders a JSON response' do
        contact_response = JSON.parse(response.body)
        expect(contact_response).not_to be_nil
      end
    end

    describe 'DELETE destroy' do
      before(:each) do
        delete :destroy, id: contact.id, format: :json
      end

      it 'is successful' do
        expect(response).to be_success
      end

      it 'renders no response body' do
        expect(response.body).to be_empty
      end
    end
  end
end
```

**Comment by rdelvallej32** [comment]
Here is my request rspec:

The only test that I have passing is if when the user is not authenticating, they should be unsuccessful running any get requests.

``` ruby
require 'rails_helper'

RSpec.describe 'Contacts API' do # test for th articles api
  def contact_params
    {
      first_name: 'Henry',
      last_name: 'Holmes',
      occupation: 'Professor',
      professional_relationship: 'Mentor',
      company: 'BU',
      last_contacted: '20120407',
      fact: 'Likes Pizza'
    }
  end

  def contacts
    Contact.all
  end

  def contact
    Contact.first
  end

  def user_params
    {
      email: 'alice@example.com',
      password: 'foobarbaz',
      password_confirmation: 'foobarbaz'
    }
  end

  def user
    User.first
  end

  before(:all) do # before all the test, run method and then create a contact
    User.create!(user_params)
    Contact.create!(contact_params)
  end

  after(:all) do # after the test, run method to delete it
    User.delete_all
    Contact.delete_all
  end

  context 'when authenticated' do
    def headers
      {
        'HTTP_AUTHORIZATION' => "Token token=#{user.token}"
      }
    end

    before(:each) do
      post '/sign-up', credentials: user_params
      post '/sign-in', credentials: user_params

      @token = JSON.parse(response.body)['user']['token']
      @user_id = JSON.parse(response.body)['user']['id']
    end

    describe 'GET /contacts' do
      it 'lists all contacts' do
        get '/contacts', nil, headers

        p headers
        expect(response).to be_success

        contact_response = JSON.parse(response.body)
        p contact_response
        expect(contact_response.length).to eq(contacts.count)
        expect(contact_response['contacts'].first['first_name']).to eq(
          contacts.first.first_name)
      end
    end

    describe 'GET /contacts/:id' do
      it 'shows one contact' do
        # interpolate the contact method
        get "/contacts/#{contact.id}", headers

        expect(response).to be_success
        contact_response = JSON.parse(response.body)
        expect(contact_response['contacts']['id']).to eq[contact.id]
        expect(contact_response['first_name']).to eq(contact.first_name)
      end
    end

    describe 'POST /contacts' do
      it 'creates an contact' do
        post '/contacts', { contact: contact_params }, headers

        expect(response).to be_success
        contact_response = JSON.parse(response.body)
        expect(contact_response).not_to be_nil
        expect(
          contact_response['first_name']).to eq(contact_params[:first_name])
      end
    end

    describe 'PATCH /contacts/:id' do
      def contact_diff
        { first_name: 'Henry',
          last_name: 'Holmes',
          occupation: 'Dean',
          professional_relationship: 'Mentor',
          company: 'BC',
          last_contacted: '20130507',
          fact: 'Likes Pizza'
        }
      end

      it 'updates an contact' do
        patch "/contacts/#{contact.id}", { contact: contact_diff }, headers

        expect(response).to be_success
        contact_response = JSON.parse(response.body)
        expect(contact_response['id']).to eq(contact.id)
        expect(contact_response['company']).to eq(contact_diff[:company])
      end
    end

    describe 'DELETE /contacts/:id' do
      it 'deletes an contact and response body to be empty' do
        delete "/contacts/#{contact.id}", nil, headers

        expect(response).to be_success
        expect(response.body).to be_empty
      end
    end
  end

  context 'when not authenticated' do
    describe 'GET /contacts' do
      it 'is not successful' do
        get '/contacts'

        expect(response).not_to be_success
      end
    end

    describe 'GET /contacts/:id' do
      it 'is not successful' do
        get "/contacts/#{contact.id}"

        expect(response).not_to be_success
      end
    end
  end
end
```

**Comment by rdelvallej32** [comment]
Issue Resolved:  Issue stemmed from incorrect format for curl request
