### ISSUE TITLE
Questions on DB Structure

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/full-stack-project#211]
I'd like someone to walk through the finer points of my database structure before I go creating anything.

Here's a link to the basic structure: https://docs.google.com/spreadsheets/d/1kD-EuNJLmGi_r6k1i0l7eegLuruyJ5FzxWEHY7l9GVQ/edit?usp=sharing

In particular, I'd like to know about how to make a table that references itself (Sections have parent sections, or their parent section might be a Document).

**Comment by RDegnen** [comment]
Do you mean something like this?
http://stackoverflow.com/questions/1207504/how-can-rails-activerecord-table-refer-to-itself

**Comment by soynog** [comment]
Yeah. I guess I was hoping to have conversation about any possible pitfalls/things I should know before giving it a try.

**Comment by RDegnen** [comment]
I would direct a conversation like that to @gaand. I don't know much about the pitfalls of that

**Comment by RealWeeks** [comment]
@soynog This sounds like a reasonable idea, however I can't speak for the pitfalls having not done it before (my research would be no better than yours) @MattB-GA-Boston may have some idea, if @gaand  is currently occupied.

**Comment by GA-MEB** [comment]
@soynog I'm free to talk now if you want to come find me.

**Comment by GA-MEB** [comment]
@soynog Please mark closed when you get a chance!

**Comment by soynog** [comment]
Thanks Matt! I'll re-open if I have further questions.
