### ISSUE TITLE
Controller question

### ISSUE THREAD

**Issue by sjf125** [ga-wdi-boston/full-stack-project#213]
I used rails g scaffold instead of rails-api g scaffold - don't know if that is related...

All of my controllers were set up with 'before_action', but I notice in rails-bdd-iteration I notice that the controllers are set up with 'before_filter'.  For example:

Mine:

``` rb
before_action :set_comment, only: [:show, :update, :destroy]
```

Lauren's:

``` rb
before_filter :set_comment, only: [:show, :update, :destroy]
```

Is this ok?

**Comment by GA-MEB** [comment]
@sjf125 They're the same. `before_action` is just a new Rails 4 alias for the older `before_filter`.

`rails g scaffold` is fine.

**Comment by sjf125** [comment]
Thanks!
