### ISSUE TITLE
(Ownership)GET request returning has_many object with wrong user_id

### ISSUE THREAD

**Issue by philschoof** [ga-wdi-boston/full-stack-project#214]
I have a user table that has_many albums. I'm trying to get all albums with a associated user by sending a GET request to api + 'users/' + user_id + '/albums' with user_id 2, but it will only return albums with user_id 1. A user_id is set when sign-in is successful, and it console logs, but the get request isn't returning the right stuff.

**Comment by RDegnen** [comment]
Can you paste in the request your making

**Comment by philschoof** [comment]
``` js
let getAlbums = function(){
  console.log('get');
  $.ajax({
    method: "GET",
    url: app.api + 'users/' + ui.currentUser.id + '/albums',
    // method: 'GET',
    dataType: 'json',
    headers: {
      Authorization: "Token token=" + ui.currentUser.token
    }
  }).done(function(albums){
    console.log(albums);
    displayAlbums(albums);

  });
};
```

**Comment by philschoof** [comment]
how do i format that?

**Comment by RDegnen** [comment]
Just sandwich it between 3 back ticks. what is the value of `ui.currentUser.id`?

**Comment by philschoof** [comment]
It's set to the id of the user thats returned on sign-in

**Comment by laurenfazah** [comment]
So if you're logged in with user with id of 2, can you confirm that `ui.currentUser.id` is 2 and that albums are still showing for user 1?

**Comment by philschoof** [comment]
Yes - although I've been poking at it and it might just be returning all the albums. Would that be an adjustment I have to make to the controller?

**Comment by RealWeeks** [comment]
Sounds like no ownership. I'd look at the controller

**Comment by RealWeeks** [comment]
trying creating a an album that belongs to another user and see if it returns that one as well

**Comment by philschoof** [comment]
It does - user 2 is signed in and its returning albums that belong to users 1 and 3.
Should there be two 'index' controllers? One for all albums and another for all albums that belong to a user?

**Comment by RealWeeks** [comment]
you mean two index actions in the Albums controller? No

**Comment by laurenfazah** [comment]
You're hitting the `/users/:id/albums` endpoint, right? Is that mapped to `albums#index` in your AlbumsController? If so, can you paste that method.

**Comment by philschoof** [comment]
I'm not sure - is that in routes?

**Comment by philschoof** [comment]
Thanks guys
