### ISSUE TITLE
Questioning database structure

### ISSUE THREAD

**Issue by MichaelB167** [ga-wdi-boston/full-stack-project#216]
I've met with consultants several times to ensure that the scope/structure of my database was appropriate but going through testing I'm having second thoughts as to how its flow should be structured.  I'm doing a climbing training app where users input information about the gym they climbed at as well as information/what happened on routes where they fell.  The database is structured as such: each user has a one to many relationship with gyms and each gym has a one to many relationship with climbs http://i.imgur.com/XVvYTwi.jpg.  These are my relevant user stories:
- As a user, I want to be able to input information about which gym I climbed at and what happened on routes that I fell on so that I have a record I can refer to.
- As a user, I want to have the above information displayed in order to check my training progress.
- As a user, I want to see specifically what kind of routes/holds I fall on the most and have a total of each displayed along with a suggestion for how to improve at specific movements.

My end goal is to link users to climbs; can I do so by adding a direct migration reference from user to climbs or do I need to use the 'through' syntax from the rails model validation lesson?  My hesitation from doing the latter is that the relationship doesn't work in the inverse ie climbs don't have many users.

**Comment by MichaelB167** [comment]
fixed dead link

**Comment by RDegnen** [comment]
Yes a user can also have_many :climbs without having to go through gyms

**Comment by MichaelB167** [comment]
ok, ty Ross
