### ISSUE TITLE
Importing data from a CSV into my table

### ISSUE THREAD

**Issue by sjf125** [ga-wdi-boston/full-stack-project#219]
I'd like to import data from a CSV that has a list of country names and image file locations on wikipedia onto my 'flags' table, but I cannot as my schema requires a created_at and updated_at datetime entries which are not present in my CSV file.  Can I use rake db:populate to do this?

**Comment by laurenfazah** [comment]
Those should both be automatically set by a timestamp...have you attempted to populate the DB with your CSV yet? If so, could you post the error?

**Comment by sjf125** [comment]
```
~/wdi/projects/flags/flags-api (project)$ rake db:populate:all
rake aborted!
Don't know how to build task 'db:populate:all' (see --tasks)
```

**Comment by laurenfazah** [comment]
Ah, I assumed you were using an enumerable IO method (`CSV.foreach`...).

I believe `rake db:populate` is not a rake task within the API template repo.

**Comment by sjf125** [comment]
Is there a repo I can look at for how to do that?  I'm kind of at a loss.  I don't plan on having the flags change really at all once the project is up, I just need to get my data with the URLs in there.

**Comment by laurenfazah** [comment]
If you wanted to use it, you could port it over to your lib/tasks/db.rake file from a different project that used it, or implement an enum method, or batch edit your CSV and save each row as a seed within db/seeds.rb

**Comment by RDegnen** [comment]
if you look at the one-to-many or many-to-many lessons the `db:populate:all` task is a custom rake task that lives in `lib/tasks/db.rake` file. So you could copy it from there and modify it to your needs.

**Comment by sjf125** [comment]
Got it!  Thanks so much!  Went with editing the rake tasks file.
