### ISSUE TITLE
bulk load csv file using rails console 

### ISSUE THREAD

**Issue by HoldenMills** [ga-wdi-boston/full-stack-project#22]
I am trying to bulk load a csv file into my database.  I have run 'rails g task db parks' then updated the rake.db file using the rails-crud lesson as an example.  Then I ran 'rake -T db:populate'.  The terminal runs it successfully, but when I look at the database itself after running 'SELECT \* FROM parks' it shows that I have 0 rows.

**Comment by jrhorn424** [comment]
Can you please create a [gist](https://gist.github.com) with your files and a description of what commands you've run? Here's a good example of a gist: https://gist.github.com/jrhorn424/cc76cc9e4e8c9fe8ca49

When you're done, link to it here. Happy to talk to you at that point.

**Comment by jrhorn424** [comment]
I should've also pointed out, your description of the problem was good. Instead of saying I needed a "descriptiong of what commands you've run", I should've said "a description of the commands you've run, **and their output**". Sorry for any confusion!

**Comment by GA-MEB** [comment]
I think this one's been resolved. The issue wasn't with the rake task, it was with a migration/model - specifically, naming a column `type` caused the model to get confused. Renaming that column to `designation` and resetting the database fixed the problem.
