### ISSUE TITLE
Index action not firing with a curl request

### ISSUE THREAD

**Issue by rdelvallej32** [ga-wdi-boston/full-stack-project#221]
Hi,

My contacts index action is not firing when I send a Get Contacts request. I added a bind within the method and it is not firing and instead saying : {
  "error": {
    "message": "Not Found"
  }
}

My current_user is working across all the methods within the controller. 

``` ruby

  def index
    binding.pry
    @contacts = current_user.contacts
    render json: @contacts
  end
```

**Comment by rdelvallej32** [comment]
Also this is my curl request script:

TOKEN='BAhJIiU1Y2ExNWZmM2FjYzBkMjNkZDVjMTBkMDJkZTAwNzU4NAY6BkVG--d5fad93afaf24cd681e5c2e2750cfcd7dfcb2752'

curl --include --request GET http://localhost:3000/contacts \
--header "Authorization: Token token=$TOKEN" \

**Comment by RDegnen** [comment]
have you created any contacts yet for your current_user?

**Comment by RealWeeks** [comment]
is your rails server getting any errors?

**Comment by rdelvallej32** [comment]
No errors from the rails server, it completed the request with a 404 Not found and the user has around 6 contacts now in the database associated with their id

**Comment by GA-MEB** [comment]
@rdelvallej32 Can you paste in the output from running `SELECT * FROM contacts;` in Postgres?

**Comment by rdelvallej32** [comment]
Here it is:

atch-up-api_development=# select \* from contacts;
 id | first_name | last_name | occupation | professional_relationship | company | last_contacted |        fact        |         created_at         |         updated_at         | user_id 
----+------------+-----------+------------+---------------------------+---------+----------------+--------------------+----------------------------+----------------------------+---------
  3 | Kitty      | Holmes    | Professor  | Mentor                    | BU      | 2012-04-07     | Likes Pizza        | 2016-04-28 14:58:30.696342 | 2016-04-28 14:58:30.696342 |       2
  4 | Kitty      | Holmes    | Professor  | Mentor                    | BU      | 2012-04-07     | Likes Pizza        | 2016-04-28 14:59:06.448795 | 2016-04-28 14:59:06.448795 |       2
  5 | Kitty      | Holmes    | Professor  | Mentor                    | BU      | 2012-04-07     | Likes Pizza        | 2016-04-28 15:01:06.382656 | 2016-04-28 15:01:06.382656 |       2
  6 | Kitty      | Holmes    | Professor  | Mentor                    | BU      | 2012-04-07     | Likes Pizza        | 2016-04-28 15:01:17.143098 | 2016-04-28 15:01:17.143098 |       2
  7 | Kitty      | Holmes    | Professor  | Mentor                    | BU      | 2012-04-07     | Likes Pizza        | 2016-04-28 15:05:07.770265 | 2016-04-28 15:05:07.770265 |       2
  8 | Kitty      | Holmes    | Professor  | Mentor                    | BU      | 2012-04-07     | Likes Pizza        | 2016-04-28 15:12:48.894194 | 2016-04-28 15:12:48.894194 |       2
  1 | RoRo       | Married   | Scientist  | Former Boss               | BU      | 2013-04-07     | Doesnt Likes Pizza | 2016-04-28 14:40:57.309263 | 2016-04-28 15:29:43.866267 |       2
(7 rows)

**Comment by GA-MEB** [comment]
@rdelvallej32
Two more questions:
Are you logged in as User 2 when you are doing this?
What are your routes, currently?

**Comment by rdelvallej32** [comment]
Yes, I'm currently using user id: 2's token to authenticate and send the request. These are how my routes are set up currently : 

``` ruby
Rails.application.routes.draw do
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
  resources :contacts
  resources :examples, except: [:new, :edit]
end
```

**Comment by rdelvallej32** [comment]
Issue Resolved: Needed to delete :index out of before_action only:
