### ISSUE TITLE
Data structure question

### ISSUE THREAD

**Issue by natdjerf** [ga-wdi-boston/full-stack-project#222]
I've successfully posted all of my individual elements, but I think I may need to update the data structure. Essentially, the model is User will have many boards, and boards will have many cheeses, but there is direct relationship between the user and cheeses.
I was intending to use a csv file to load all of the cheeses in in advance, and therefore didn't anticipate the need for crud actions on the cheese, however, I have made a requirement for board_id on cheeses. 

In the database, they are structured as intended, and in the rails console I can see that the user owns the board and the board has cheese, but I don't know if that is an optimal way to structure it, or if I could eliminate the requirement of a board id and use the a patch request to add (an already existing) cheese to a board. 

Would someone be able to come take a look?

Models:

``` rb
class Board < ActiveRecord::Base
  belongs_to :user, inverse_of: :boards
  has_many :cheeses
end
class Cheese < ActiveRecord::Base
  belongs_to :board, inverse_of: :cheeses
end
```

Schema

``` rb
  create_table "boards", force: :cascade do |t|
    t.integer  "user_id",    null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string   "name",       null: false
  end

  add_index "boards", ["user_id"], name: "index_boards_on_user_id", using: :btree

  create_table "cheeses", force: :cascade do |t|
    t.string   "family",              null: false
    t.string   "name",              null: false
    t.string   "milk_type",         null: false
    t.string   "country_of_origin", null: false
    t.integer  "board_id",          null: false
    t.datetime "created_at",        null: false
    t.datetime "updated_at",        null: false
  end

  add_index "cheeses", ["board_id"], name: "index_cheeses_on_board_id", using: :btree
```

**Comment by RDegnen** [comment]
if you eliminated the board_id from the cheeses table than you would no longer be able to find the cheeses that belong to that board

**Comment by GA-MEB** [comment]
@natdjerf It sounds like Cheese is a variety of cheese, rather than a specific piece of cheese -- is that correct? Although a single Board might be associated with multiple Cheeses, any given variety of Cheese might also be associated with multiple different Boards. What does that tell you about their relationship?

**Comment by natdjerf** [comment]
@MattB-GA-Boston I'm not quite sure I follow- that the cheese is a many to many relationship / as in, cheese has many boards? I was hoping to do the csv upload and have only a select variety of cheeses I wanted to be available.. does that make sense?

**Comment by GA-MEB** [comment]
@natdjerf 
Yes, precisely. You want many Boards to associate with many Cheeses. Even if you don't want users to be able to create new Cheeses, at a minimum you need to have a table of Cheeses in your DB, and most likely you will also want a model to make it easy to manipulate Cheese resources (i.e. creating new Cheeses using data from a CSV file).

**Comment by GA-MEB** [comment]
@natdjerf Please close when you get a chance!
