### ISSUE TITLE
Why is current_user null in certain contexts?

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/full-stack-project#224]
I'm trying to ensure that a show action can only display a document owned by the current user. Using the current_user object to test this has worked for the index action. But for some reason when I try it on the show action I get an error because the object is null (and thus doesn't have an id).

Here is the offending code:

``` rb
  def user_documents
    Document.where('user_id = :user', user: current_user.id)
  end
```

Thanks!

**Comment by soynog** [comment]
P.S. this is in the controller for my Document object.

**Comment by laurenfazah** [comment]
If you're using `current_user` in a controller, the controller must inherit from ProtectedController rather than ApplicationController. ProtectedController authorizes the user before any actions whereas ApplicationController skips this.

**Comment by GA-MEB** [comment]
@soynog, to build on @laurenfazah 's comment: 
Your Rails app is "stateless" -- it doesn't keep track of who's logged in at any moment in time -- so the only way it can know the `current_user` is by looking at the token attached to the request (i.e. authenticating). Our vanilla  ApplicationController doesn't authenticate before its actions, but ProtectedController does.

**Comment by soynog** [comment]
So I already have before_action :authenticate at the top of my DocumentsController... which I think makes it the same as ProtectedController (though I'll change it so it actually inherits).

Again, checking current_user works fine in the context of the index action--just not when I try to show a specific document.

**Comment by laurenfazah** [comment]
Ah..check your routes (rake routes). Show is a member route, meaning it likely is not associated with the current user.

**Comment by soynog** [comment]
Hmm... so I have this. I don't understand--what about being a member route of documents determines whether or not it's associated with a user?

```
documents GET    /documents(.:format)           documents#index
document GET    /documents/:id(.:format)       documents#show
```

**Comment by laurenfazah** [comment]
Typically an `#index` route of a resource that belongs to User looks like `/users/:user_id/documents` and `#show` would be just `/documents/:doc_id`. However, yours look different, so we'll need to troubleshoot.

1) Does Documents in fact belong to User? Or am I just assuming
2) Are there any other routes given by `rake routes` that map to `documents#index` or `document#show`?

**Comment by soynog** [comment]
I was wondering about that. Should I set up the routes as /users/:user_id/documents? I wasn't sure if that was standard practice or not, and it's not the case for games in Antony's tic-tac-toe API so I figured not.

Currently Document _does_ belong to User. I'm missing inverse_of though--could that be an issue? I'll fix it regardless.

I just don't understand why it works for index and not for show... and it's otherwise authenticating properly.

Thanks Lauren!

**Comment by GA-MEB** [comment]
@laurenfazah @soynog 
There's actually no reason to do nested routes like that. The current user is totally determinable from the token, and does not need to be passed in through the URL.

Can you paste in the code for your DocumentsController?

**Comment by soynog** [comment]
Ha! Fixed it.

I never made User has_many Documents, just the other way around. Seems to be working now.

Thank you!!
