### ISSUE TITLE
Keep getting huge errors in tests and can't figure out why

### ISSUE THREAD

**Issue by sjf125** [ga-wdi-boston/full-stack-project#225]
Here is my test for my comments API, copied from the BDD training:

``` rb
describe 'DELETE /comments/:id' do
    it 'deletes an comment' do
      delete "/comments/#{comment.id}",
             comment: { id: comment.id },
             format: :json

      expect(response).to be_success
      expect(response.body).to be_empty
    end
  end
```

```
3) Comments API DELETE /comments/:id deletes an comment
     Failure/Error: expect(response).to be_success
       expected `#<ActionDispatch::TestResponse:0x007fd549d96b80 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007fd549d96b30>, @stream=#<ActionDispatch::Response::Buffer:0x007fd549d96ae0 @response=#<ActionDispatch::TestResponse:0x007fd549d96b80 ...>, @buf=["HTTP Token: Access denied.\n"], @closed=false>, @header={"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff", "WWW-Authenticate"=>"Token realm=\"Application\"", "Content-Type"=>"text/html; charset=utf-8", "Vary"=>"Origin", "Cache-Control"=>"no-cache", "X-Request-Id"=>"eb7046d8-d5ad-41fd-8d8d-d85ff1bec6e5", "X-Runtime"=>"0.002325", "Content-Length"=>"27"}, @status=401, @sending_file=false, @blank=false, @cv=#<MonitorMixin::ConditionVariable:0x007fd549d96ab8 @monitor=#<ActionDispatch::TestResponse:0x007fd549d96b80 ...>, @cond=#<Thread::ConditionVariable:0x007fd549d96a90>>, @committed=false, @sending=false, @sent=false, @content_type=#<Mime::Type:0x007fd54924afd8 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=1912809058582387419>, @charset="utf-8", @cache_control={:no_cache=>true}, @etag=nil>.success?` to return true, got false
```

The same huge errors occur for GET and PATCH as well. Any idea where I should be looking to fix this problem?

**Comment by RDegnen** [comment]
do your requests work outside of the tests?

**Comment by RealWeeks** [comment]
@sjf125 I'm not going to say don't test. But I would recommend getting your api up and running first before worrying about testing errors.

**Comment by laurenfazah** [comment]
Do these requests require token authorization? Check to see if you should be sending headers with these requests.

**Comment by sjf125** [comment]
No - I had my CommentController inherit from ProtectedController, so that you can't make comments without being logged in - but I'm not sure how to test the routes when you need a token.  Changing the inheritance from ProtectedController to ApplicationController makes the DELETE action pass the test, but the id for POST and PATCH are returning nil, and thus not passing the test.

**Comment by sjf125** [comment]
@J-weeks how do I know my API is up and running without knowing if it works?

**Comment by laurenfazah** [comment]
So when you're inheriting from ProtectedController, a token from the signed in user must be sent. Otherwise, ProtectedController doesn't know whom the current user is. Try as it was with headers sent.

**Comment by laurenfazah** [comment]
Also, just reread your error output and saw `@buf=["HTTP Token: Access denied.\n"],` so pretty sure that's the source of the issue.

**Comment by sjf125** [comment]
It is.  I just don't know how to get the token in along with the test

**Comment by laurenfazah** [comment]
Check out how it's done in rails-api-bdd-iteration/spec/requests/articles_spec.rb

**Comment by laurenfazah** [comment]
If that's not clear, I'm happy to break it down

**Comment by sjf125** [comment]
I just tried copying the content of rails-api-bdd-iteration/spec/requests/articles_spec.rb and changing all 'article' to 'comment' and having the params only be content, but it didn't work.  I am feeling really lost on what I should be doing, even aside from tests right now, and I'd really like to talk with someone and make sure I have the right idea of my routes and how my API should be working, before I spend much more time on the tests.
