### ISSUE TITLE
Huge error when trying to run rspec spec

### ISSUE THREAD

**Issue by V4Vince** [ga-wdi-boston/full-stack-project#229]
I'm getting a large error when trying to run rspec spec. I renamed `config/application.rb` to StoryTeller and `config/database.yml` to StoryTeller. I did not touch the spec file in the api template. The first line of the error says:

``` md
`rescue in connect': FATAL:  database "StoryTeller_test" does not exist (ActiveRecord::NoDatabaseError)
```

**Comment by RDegnen** [comment]
I would recommend not writing tests because it will just be a waste of time at this point

**Comment by V4Vince** [comment]
Ok, so I should just test it with curl then?

**Comment by laurenfazah** [comment]
Have you ran `rake db:create`? This could be indicative of a larger error, tests or not.

**Comment by V4Vince** [comment]
i didnt migrate. It works now, thanks!
