### ISSUE TITLE
Secrets.yml

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/full-stack-project#231]
My secrets.yml file seems to not be showing up in my config folder, however, it does exist. I can open it via the finder and it has my keys already created in them. I wanted to test my backend but I can't run curl requests while it's hidden. I have even tried deleting the file and creating a new one....SAME FUCKING ISSUE.

**Comment by laurenfazah** [comment]
1) Do you need a secrets.yml? 
2) Where is it not showing up? That file is "git ignored" meaning it won't be sent up to github.
