### ISSUE TITLE
Committing to the wrong repo

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/full-stack-project#232]
My commits for the backend have been going to the repo for my front end.  How do I change the repo they get sent to?  Do I have to delete the accidental commits to the front end repo?  Thanks!

**Comment by laurenfazah** [comment]
Run `git remote -v` in each repo from the command line. That'll show you which remotes you've added to each project. You likely added the wrong `origin` to the backend. If the wrong origin is in the repo you can delete it with `git remote rm origin`. Then go back to github and get the remote URL (from the same line that we copy to clone) and run `git remote add origin <remote URL>` in the respective repository with the correct URL for each.

**Comment by susandaiute** [comment]
Worked! Thanks Lauren!
