### ISSUE TITLE
Handlebars template. Passing variables / local storage

### ISSUE THREAD

**Issue by philschoof** [ga-wdi-boston/full-stack-project#236]
I'm trying to pull data from elements loaded in a handlebars template, but it throws an error saying that the element is undefined. I've been googling and can't find a solution. I'm guessing it's because the elements in the template load after the function is loaded. Is there a particular phrase or concept I should be googling?

**Comment by RealWeeks** [comment]
This is an issue Phil asked me about before the start of project time that I have not had time to address with him

**Comment by gaand** [comment]
@J-Weeks Please add a description of the issue.

@philschoof Please paste the error thrown.

**Comment by RealWeeks** [comment]
Phil could not figure out how to get a data-attribute attached to a handlebars template and use it after a modal pops up to attach it to an ajax request.

**Comment by philschoof** [comment]
Used local storage to retrieve and store data assigned to HTML element in handlebars template.
