### ISSUE TITLE
Making keyword queries using a get request

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/full-stack-project#237]
I want to be able to use keywords given by the user to query my foods database. For example, they would type "chicken" into a field and then a get request would return all the items in the foods table that contains "chicken" in the description. I've done some research and it looks like there are a few ways to do this. One is to do it by passing variables in the url of the get request, the other is to pass the keywords as data in the request and then use them to make the query on the backend. I am unsure what the best approach is here.

**Comment by gaand** [comment]
For two different questions, please open two different issues.

Copy and paste.  Thanks,

**Comment by laurenfazah** [comment]
Those are both viable options. A third could be using JS on the front end to scan your GET index results for a particular keyword. I personally would lean towards passing a keyword as data in your request to query on the backend or manipulating your data on the front end. @gaand perhaps you have more insight on a best approach.

**Comment by gaand** [comment]
For retrieving data, don't send a request body, add named query parameters.

**Comment by gaand** [comment]
@louarnos How did you handle this?
