### ISSUE TITLE
Using a patch to update items through a joined table.

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/full-stack-project#238]
In my database users have many meals. Meals have many foods through a meal_items joined table. I want to the user to be able to patch their meal.foods array once they have decided what food to add to a meal, and I am unsure on how to approach this. Any advice would be appreciated.

**Comment by gaand** [comment]
Question:
Is this a translation into english?

A user can add foods to a meal.

Suggestion:
The patch would go against the meals controller and you need to also send along the foods to add.

Similarly for deleting foods. I wouldn't do both at once (add and delete).

**Comment by louarnos** [comment]
Thats correct.

**Comment by gaand** [comment]
Sorry, two parts.  I edited my comment.  If it's unclear, please let me know.

**Comment by louarnos** [comment]
I guess I'm unsure how to push onto a meal's foods array through a patch.

**Comment by gaand** [comment]
First, how are you collecting the data from the user?  Will you have a meal and a list of foods?

**Comment by louarnos** [comment]
so the user will have a meal_id either through creating a new meal or recalling a previous meal by a get request. The user will then search for foods in the database and once selected, I'd store them on the front end and then pass them with the patch to the meal's foods array.

Does this make sense?

**Comment by GA-MEB** [comment]
@louarnos 
I'm finding this pretty confusing to follow. Meal and Food are two separate resources, yes? Then what "foods array" are you talking about? Do you mean the set of foods that are associated, through the `meal_items` table, with a particular Meal?

**Comment by RDegnen** [comment]
are you asking how to pass it to the meals food array?

**Comment by gaand** [comment]
Yes.  So, you'd be updating the meal by adding foods to it, perhaps by sending an array of foods to add?

**Comment by louarnos** [comment]
@RDegnen I want to essentially do what we did yesterday in rails console. Meals has foods through meal_items. I want to update this by patching to meals.

**Comment by louarnos** [comment]
@MattB-GA-Boston yes, thats correct.

**Comment by louarnos** [comment]
@gaand I'm just unsure how it expects the data. I've tried patching with the array in the data field and it doesn't like my formatting of the data.

**Comment by gaand** [comment]
Please show how the data is being sent(chrome network tab) and received (rails log).

**Comment by louarnos** [comment]
Ok, so I am getting a 200 now, but its not actually changing my array. This is my curl request: 

```
TOKEN='BAhJIiViZGVjNDE1ZWJlNmRhNzgyYjdkMmJlZTQwOTczMjY2MwY6BkVG--d1fde39b99e61e192bbc69ce6788fbceb3aa4fb5'
ID ='1'

curl --include --request PATCH http://localhost:3000/meals/$ID \
  --header "Authorization: Token token=$TOKEN" \
  --header "Content-Type: application/json" \
  --data '{
    "meal" : {
    "meal_type" : "test_1",
    "meal_items" : "[1,2,3,4,5]"
  }
}'

```

When I send this I get:

```
HTTP/1.1 200 OK 
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Vary: Origin
Etag: W/"c053745c60d70e0cf3466b4feb2e9f5a"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 66e2534f-adcb-40b4-9449-91f3b241c544
X-Runtime: 0.013176
Server: WEBrick/1.3.1 (Ruby/2.3.0/2015-12-25)
Date: Fri, 29 Apr 2016 16:05:15 GMT
Content-Length: 97
Connection: Keep-Alive

{"meal":{"id":1,"meal_type":"test_1","user":{"id":1,"email":"an@example.email"},"meal_items":[]}}~/wdi/projects/Fitness Tracker Project/rails-api-template-master (scaffolding)$ 
```

The meal_items array that is returned is still blank

**Comment by gaand** [comment]
This `"[1,2,3,4,5]"` is a string, not an array.

**Comment by louarnos** [comment]
I just tried: 

``` TOKEN='BAhJIiViZGVjNDE1ZWJlNmRhNzgyYjdkMmJlZTQwOTczMjY2MwY6BkVG--d1fde39b99e61e192bbc69ce6788fbceb3aa4fb5'
ID ='1'

curl --include --request PATCH http://localhost:3000/meals/$ID \
  --header "Authorization: Token token=$TOKEN" \
  --header "Content-Type: application/json" \
  --data '{
    "meal" : {
    "meal_items" : [1,2,3,4,5]
  }
}'
```

As well and it didn't update either. I would think it would throw and error if the type was wrong.

**Comment by louarnos** [comment]
I was calling the variable wrong... its working.
