### ISSUE TITLE
Logout request isn't clearing the token

### ISSUE THREAD

**Issue by baz1389** [ga-wdi-boston/full-stack-project#24]
My logout function seems to be working but after I logout and type user.token in the DOM console the token hasn't been cleared.

**Comment by gaand** [comment]
Nope.  But you can't use it anymore (assuming DELETE /logout/id worked).  If you want to clear it, you'll have to do so explicitly.

**Comment by baz1389** [comment]
Problem solved. 

To clear user.token on the front end you can write "user.token = null;" at the end of your logout function.
