### ISSUE TITLE
POST to database issue

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/full-stack-project#242]
Rescue is my primary database and what I'm trying to CREATE information to

when I submit my create form I see 

```
Object {rescues: Object}
jquery.js:9203 POST http://localhost:3000/sign-up send @ jquery.js:9203jQuery.extend.ajax @ jquery.js:8684signUp @ api.js:8(anonymous function) @ index.js:47jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
:8080/?#:1 XMLHttpRequest cannot load http://localhost:3000/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
ui.js:28 Object {readyState: 0, status: 0, statusText: "error"}failure @ ui.js:28fire @ jquery.js:3187self.fireWith @ jquery.js:3317done @ jquery.js:8787(anonymous function) @ jquery.js:9143
```

Unclear on why it's trying to post to sign up. 

below is the relevant html, and ajax request

``` html
<form id="new-rescue" role="form">
                <div class="form-group">

                    <label for="exampleInputEmail1">
                        Rescue Title
                    </label>
                    <input placeholder="Great tutorial on solving my Javascript problems" type="text" name="rescues[title]" class="form-control" id="inputRescueTitle" />
                </div>
                <div class="form-group">

                    <label for="inputRescueLink">
                        Rescue Link
                    </label>
                    <input  placeholder="www.solvemyjsproblems.net"class="form-control" type="text" name="rescues[link]"id="inputRescueLink" />
                </div>
        <div class="form-group">

                    <label for="inputTags">
                        Rescue Tags
                    </label>
                    <input  placeholder="problems, all, tutorial, cheatsheet, js, javascript" type="text" name="rescues[tag]" class="form-control" id="inputRescueTags" />
                </div>
                    <p class="help-block">
                        This was supposed to be help text, but you get it...right?
                    </p>
                <button type="submit" class="btn btn-default">
                    Submit
                </button>
            </form>
```

``` js
const newRescue = (success, failure, data) => {
  $.ajax({
    method: "POST",
    url: app.api +'users/' + ui.currentUser.id + '/rescues/',
    dataType: 'json',
    data,
    headers: {
      Authorization: "Token token=" + ui.currentUser.token
    },
  })
  .done(success)
  .fail(failure);

};
```

**Comment by RDegnen** [comment]
can you paste your event handler in

**Comment by RealWeeks** [comment]
put a debugger right below where you declare the newRescue function, does it hit it?

**Comment by BenGitsCode** [comment]
``` js
  $('#new-rescue').on('submit', function (event) {
    event.preventDefault();
    let data = getFormFields(this);
    authApi.signUp(authUi.success, authUi.failure, data);
    console.log(data);
  });
```

a debugger immediately above   event.preventDefault(); does fire

**Comment by RDegnen** [comment]
what is the value of data?

**Comment by BenGitsCode** [comment]
I'm unclear, when I type data into the console I get undefined?

**Comment by BenGitsCode** [comment]
``` sh
VM246:1 Uncaught ReferenceError: data is not defined(…)(anonymous function) @ VM246:1InjectedScript._evaluateOn @ VM144:145InjectedScript._evaluateAndWrap @ VM144:137InjectedScript.evaluate @ VM144:118
```

**Comment by gaand** [comment]
What does the console.log display when you click submit?

**Comment by BenGitsCode** [comment]
I'm unclear. I'm not seeing a log of data in the console, but when a put a debugger before or after the console.log it does fire.

**Comment by laurenfazah** [comment]
So when the debugger is after `console.log(data)`, what do you see for `data`?

**Comment by RDegnen** [comment]
if they debugger fires, then try seeing what data is while in your debugger

**Comment by BenGitsCode** [comment]
@laurenfazah it shows the correct data

New error:
```jquery.js:9203 XMLHttpRequest cannot load http://localhost:3000users/undefined/rescues/. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.send @ jquery.js:9203jQuery.extend.ajax @ jquery.js:8684newRescue @ api.js:57(anonymous function) @ index.js:47jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
ui.js:28 Object {readyState: 0, responseJSON: undefined, status: 0, statusText: "error"}

``````

```js
$('#new-rescue').on('submit', function (event) {
    event.preventDefault();
    let data = getFormFields(this); 
    authApi.newRescue(authUi.success, authUi.failure, data); // this originally had authApi.signUp
    console.log(data);
  });
``````

the wonders of copy and paste. 

the undefined in that error message looks to be the "  ui.currentUser.id " portion of the below snippet. Not sure why it's becoming undefined. 

``` js
const newRescue = (success, failure, data) => {
  $.ajax({
    method: "POST",
    url: app.api +'users/' + ui.currentUser.id + '/rescues/',
    dataType: 'json',
    data,
    headers: {
      Authorization: "Token token=" + ui.currentUser.token
    },
  })
  .done(success)
  .fail(failure);

};
```

**Comment by laurenfazah** [comment]
2 things.

1) Look closely at the endpoint it's hitting. `http://localhost:3000users/undefined/rescues/`
2) Can you verify that `currentUser.id` is being set after sign-in? (which should be set in your sign-in success function)

**Comment by Benjamski** [comment]
current user is coming up as not defined. So that's an issue.

**Comment by Benjamski** [comment]
currentUser.id is coming up as undefined, so that's an issue.

**Comment by laurenfazah** [comment]
@Benjamski I got an email saying you commented on my last post, but I'm not seeing the comment here. Beyond user id being undefined in the URL, do you notice a syntax error?

**Comment by BenGitsCode** [comment]
currentUser.id is coming up as undefined, so that's an issue.

so I looked at the routes displaying from rake routes and I'm not sure what I need to add. Obviously the current user is not being defined properly so that's the first issue to tackle.

but also do i need my rescues#create incorporated into my ajax request? I've tried changing it to

``` js
  url: app.api +'users/' + ui.currentUser.id + '/rescues/rescues#create',
  url: app.api +'users/' + ui.currentUser.id + '/rescues#create',
  url: app.api +'users/' + ui.currentUser.id + '/rescues/#create',
```

@laurenfazah sorry about that, I wanted to try the above before submitting my comment.

**Comment by laurenfazah** [comment]
Nope, the endpoint you had should be mapped to `rescues#create`, which you can verify with `rake routes`.

However, the syntax error I was hinting towards was a forgotten slash before `users` in the endpoint.

**Comment by laurenfazah** [comment]
So to diagnose why `currentUser` isn't being set properly, can you post your sign-in flow? The form, event handler, AJAX request, and whichever success/fail functions you're sending `.done()` and `.fail()`

**Comment by BenGitsCode** [comment]
ok here's that

``` js
const newRescue = (success, failure, data) => {
  $.ajax({
    method: "POST",
    url: app.api +'/users/' + ui.currentUser.id +'/rescues/',
    dataType: 'json',
    headers: {
      Authorization: "Token token=" + ui.currentUser.token
    },
    data: {
      "rescue": {
        "title": data.rescue.title,
        "url": data.rescue.url,
        "tag": data.rescue.tag,
      }
    }
  })
  .done(success)
  .fail(failure);
};
```

``` js
let currentUser = {
  token:'',
  id: undefined
};

const signInSuccess = (data) => {
  app.user = data.user;
  console.log(app);
  console.log("Sign in successful");
};

const signOutSuccess = () => {
  app.user = null;
  console.log(app);
  console.log("You signed OUT bro. Sweet!");
};

const success = (data) => {
  console.log(data);
};

const failure = (error) => {
  console.error(error);
};

module.exports = {
  failure,
  success,
  signOutSuccess,
  signInSuccess,
  app,
  currentUser
};
```

``` js
  $('#new-rescue').on('submit', function (event) {
    event.preventDefault();
    let data = getFormFields(this);
    authApi.newRescue(authUi.success, authUi.failure, data);
    console.log(data);
  });
```

``` html
  $('#new-rescue').on('submit', function (event) {
    event.preventDefault();
    let data = getFormFields(this);
    authApi.newRescue(authUi.success, authUi.failure, data);
    console.log(data);
  });
```

**Comment by laurenfazah** [comment]
Can you add your sign-in event handler? Looks like you posted `#new-rescue`'s twice instead.

**Comment by BenGitsCode** [comment]
My bad

``` js
  $('#sign-in').on('submit', function (event) {
    let data = getFormFields(this);
    event.preventDefault();
    authApi.signIn(authUi.signInSuccess, authUi.failure, data);
    console.log(data);
  });
```

**Comment by laurenfazah** [comment]
Okay so on sign-in, are you getting   

```
  console.log(app);
  console.log("Sign in successful");
```

printed to your console from `authUi.signInSuccess`?

**Comment by BenGitsCode** [comment]
<img width="457" alt="screen shot 2016-04-29 at 2 02 44 pm" src="https://cloud.githubusercontent.com/assets/16841950/14924993/1cbde4c4-0e13-11e6-9b07-75384f247c1e.png">

I know antony said no screenshots but I don't know how to make console code not look awful. But yes it is.

**Comment by BenGitsCode** [comment]
<img width="472" alt="screen shot 2016-04-29 at 2 14 15 pm" src="https://cloud.githubusercontent.com/assets/16841950/14925282/b8588aa0-0e14-11e6-8614-45c838d72dcc.png">

This is what I'm seeing now. It's understanding currentUser now, but if I type currentUser into the console I get uncaught type error, currentUser is undefined.

**Comment by laurenfazah** [comment]
Okay so I believe the issue you're getting from `currentUser` is that currentUser doesn't actually exist. You're setting `app.user = data.user`. Do me a favor and `console.log(app)` right before your AJAX call with `const newRescue`. Aka:

```
const newRescue = (success, failure, data) => {
  console.log(app)
  $.ajax({
    method: "POST",
    url: app.api +'users/' + ui.currentUser.id + '/rescues/',
    dataType: 'json',
    data,
    headers: {
      Authorization: "Token token=" + ui.currentUser.token
    },
  })
  .done(success)
  .fail(failure);

};
```

That's the user object you'll need to base your traversal to the current user's id with.

**Comment by BenGitsCode** [comment]
<img width="471" alt="screen shot 2016-04-29 at 2 51 24 pm" src="https://cloud.githubusercontent.com/assets/16841950/14926396/00037932-0e1a-11e6-9aee-ccdf34716353.png">

That's the result of the console.log You're talking about the last object it displays there?

**Comment by laurenfazah** [comment]
I'm saying you're trying to access `app.currentUser` but at no point to you create `app.currentUser`. On signin success, you're creating `app.user`

**Comment by BenGitsCode** [comment]
this is my sign in, isn't it creating currentUser?

``` js
const signInSuccess = (data) => {
  currentUser.token = data.user.token;
  currentUser.id = data.user.id;
  console.log(app);
  console.log("Sign in successful");
};
```

**Comment by laurenfazah** [comment]
Last time you posted the success function it looked like this:

```
const signInSuccess = (data) => {
  app.user = data.user;
  console.log(app);
  console.log("Sign in successful");
};
```

so I was basing off of that.

**Comment by laurenfazah** [comment]
This issue is getting a little too convoluted to diagnose indirectly. @RDegnen or @J-Weeks could you possibly self-assign to diagnose in person?

**Comment by BenGitsCode** [comment]
Guess they're busy. Thanks though @laurenfazah Roberto helped me diagnose the issue. It looks like my rescues controller not inheriting from ProtectedController was the core of the issue--after the current user was defined in the back end.

Roberto deserves a medal/financial compensation of some kind.
