### ISSUE TITLE
Can't get handlebars to work

### ISSUE THREAD

**Issue by sjf125** [ga-wdi-boston/full-stack-project#244]
I'm trying to get all of my flags to display on my page, but the img src is not getting passed in, nor is the name of the country showing up.  A sample flag:

``` json
{
"id": 3,
"location": "Asia",
"name": "Afghanistan",
"level": "country",
"imgurl": "'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Afghanistan.svg'"
},
```

Handlebars file:

``` js
{{#each flags}}
  <div class="jumbotron">
  <h2>{{this.name}}</h2>
  <img src="{{this.imgurl}}" class="img-responsive" alt="Image" />
  </div>
{{/each}}
```

index.js:

``` js
'use strict';

const displayFlags = function(flags){
  const template = require('./templates/flag-listing.handlebars');
  $('.content').append(template({flags}));
};

const getFlags = function(){
  $.ajax({
    url: "http://localhost:3000/flags",
    // method: 'GET',
    // dataType: 'json'
  }).done(function(flags){
    displayFlags(flags);
  });
};

$(document).ready(function(){
  getFlags();
});
```

I get a broken image link, with no country name, in my html here:

``` html
<div class="content">
  </div>
```

**Comment by laurenfazah** [comment]
Are you seeing the `<div class="jumbotron">` appended to `<div class="content">` when you inspect the page source?

**Comment by sjf125** [comment]
@laurenfazah I am

**Comment by sjf125** [comment]
The jumbotron outline is appearing

**Comment by sjf125** [comment]
This is how the html appears in the console on localhost:8080:

``` html
<div class="content">
 <div class="jumbotron">
  <h2></h2>
  <img src="" class="img-responsive" alt="Image">
  </div>
</div>
```

**Comment by laurenfazah** [comment]
Instead of `{{this.imgurl}}` try just `{{url}}`...let me know what that gives you.

**Comment by sjf125** [comment]
@laurenfazah  Same thing

``` html
<div class="content">
    <div class="jumbotron">
  <h2></h2>
  <img src="" class="img-responsive" alt="Image">
  </div>
</div>
```

**Comment by laurenfazah** [comment]
You might need to nest a `{{this}}` loop within `{{#each flags}}` like:

```
{{#each flags}}
{{#each this}}
  <div class="jumbotron">
  <h2>{{name}}</h2>
  <img src="{{imgurl}}" class="img-responsive" alt="Image" />
  </div>
{{/each}}
{{/each}}
```

Not positive that'll fix it though. @J-Weeks could you weigh in if not?

**Comment by RealWeeks** [comment]
yep. root key issue

**Comment by sjf125** [comment]
```
GET http://localhost:8080/'https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Liechtenstein.svg' 404 (Not Found)
```

**Comment by sjf125** [comment]
Names are appearing now, but localhost is getting prepended to the url path, and resulting in an error

**Comment by laurenfazah** [comment]
Could you console.log(flags) from your index.js? Is localhost prepended there too or only when rendered with handlebars?

**Comment by sjf125** [comment]
@laurenfazah Nope, only when rendered with handlebars - the URL is immutable as it is stored in the database

**Comment by laurenfazah** [comment]
Ok - @J-Weeks is thinking it's a webpack issue, @gaand should be in soon and can take a look at it.

**Comment by RealWeeks** [comment]
Im going to assign for now

**Comment by RealWeeks** [comment]
Looked for ways around this by such as splicing off the localhost, when in dev environment then removing line when deploying. Must be a better way or something I'm not noticing. @MattB-GA-Boston or @gaand any insight?

**Comment by gaand** [comment]
Helping in person.

**Comment by sjf125** [comment]
The URLs I had were wrapped in single quotes, and all data in a CSV is are strings by default, so when the data was passed to handlebars there were nested quotes which broke things.  I re-seeded the data without the quotes around the URLs, which fixed things.
