### ISSUE TITLE
Sign Up field not communicating with API

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/full-stack-project#246]
When I go to register/sign up a new user, something is happening but the form data is not being passed to the api.  I have multiple console logs that aren't firing.
I get this in the console:
`Navigated to http://localhost:8080/?credentials%5Bemail%5D=fake%40faked.fake&credentials%5Bpassword%5D=abc`

Index.js
`$('#register').on('submit', function (event) {
  console.log('clicked yo');
  event.preventDefault();
  let data = getFormFields(this);
  console.log(data);
  authApi.signUp(authUi.success, authUi.failure, data);
});`

Api.js
`const signUp = (success, failure, data) => {
  $.ajax({
    method: 'POST',
    url: app.api + '/sign-up',
    data,
  }).done(success)
  .fail(failure);
  console.log("signup fired");
};`

Register Modal
`<div class="modal fade sign up" id="signUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Register</h4>
        </div>
        <div class="modal-body">
          <form name="register" id="register">
            <div class="form-group">
              <label for="exampleInputEmailsignup">Email address</label>
              <input type="email" name="credentials[email]" value="an@example.email" class="form-control grabthis" id="exampleInputEmail1" placeholder="Email">
            </div>
            <div class="form-group">
              <label for="exampleInputPasswordSignUp">Password</label>
              <input type="password" name="credentials[password]" value="password" class="form-control" id="exampleInputPasswordSignUp" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </form>
        </div>
      </div>
    </div>
  </div>``

**Comment by susandaiute** [comment]
Formatted for easier reading:

Index.js

```
$('#register').on('submit', function (event) { 
console.log('clicked yo'); 
event.preventDefault(); 
let data = getFormFields(this); console.log(data); 
authApi.signUp(authUi.success, authUi.failure, data); });
```

Api.js

```
const signUp = (success, failure, data) => { 
$.ajax({ 
method: 'POST',
 url: app.api + '/sign-up', data,
 })
.done(success) 
.fail(failure); 
console.log("signup fired"); };
```

**Comment by susandaiute** [comment]
```
<div class="modal fade sign up" id="signUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Register</h4>
        </div>
        <div class="modal-body">
          <form name="register" id="register">
            <div class="form-group">
              <label for="exampleInputEmailsignup">Email address</label>
              <input type="email" name="credentials[email]" value="an@example.email" class="form-control grabthis" id="exampleInputEmail1" placeholder="Email">
            </div>
            <div class="form-group">
              <label for="exampleInputPasswordSignUp">Password</label>
              <input type="password" name="credentials[password]" value="password" class="form-control" id="exampleInputPasswordSignUp" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </form>
        </div>
      </div>
    </div>
  </div>
```

**Comment by laurenfazah** [comment]
What does your `console.log(data)` print to the console with the `#register` event handler?

Then in `signup()` in index.js, can you do the same `console.log(data)` before your AJAX call?

Let's see what those objects look like from the console.

**Comment by susandaiute** [comment]
Hi Lauren! It doesn't get far enough to console log anything which makes think it has to do with the button being linked to anything.

**Comment by susandaiute** [comment]
Also, hope you're feeling okay!

**Comment by RDegnen** [comment]
put a debugger in your event handler and see if that fires

**Comment by susandaiute** [comment]
I think I got it! The post request is sent when I click the register button and not the submit button inside the modal that pops up when you click register!

**Comment by susandaiute** [comment]
Ok, so it's firing correctly now, but I'm getting the error:

XMLHttpRequest cannot load http://localhost:3000/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.

Is this something to do with the routes?

**Comment by laurenfazah** [comment]
Is there an error in your rails server console?

**Comment by susandaiute** [comment]
Nope that was in the browser.  The rails console says:

Started POST "/sign-up" for ::1 at 2016-04-29 14:34:51 -0400
Processing by UsersController#signup as _/_
Completed 400 Bad Request in 0ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: credentials):
  app/controllers/users_controller.rb:63:in `user_creds'
  app/controllers/users_controller.rb:7:in`signup'

  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.6ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.7ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (43.5ms)

I'm wondering if that's because it might be expecting the 'confirm password' field which I don't have in my modal.

**Comment by laurenfazah** [comment]
Ok, so looks like it wants you to format the data object you're sending to `/sign-in` in your AJAX call.

Also, thanks, hope you're feeling better!

**Comment by laurenfazah** [comment]
In your UsersController, you can see that it's looking for an object to match this:

```
  def user_creds
    params.require(:credentials)
          .permit(:email, :password, :password_confirmation)
  end
```

with `credentials` as a root-key, and `email`, `password`, and `password-confirmation` as keys of a nested object

**Comment by susandaiute** [comment]
I deleted `:password_confirmation` from user_creds, but I'm still getting the same error.

**Comment by gaand** [comment]
I think you may not be preventing default in your submit handler, or a related problem.  

`http://localhost:8080/?credentials%5Bemail%5D=fake%40faked.fake&credentials%5Bpassword%5D=abc`

That indicates the browser is sending the request.

**Comment by susandaiute** [comment]
The event handler looks like this:

```
$('#submitpost').on('click', function (event) {
  event.preventDefault();
  let data = getFormFields(this);
  console.log(data);
  authApi.signUp(authUi.success, authUi.failure, data);
});
```

**Comment by laurenfazah** [comment]
Wait, why did you delete `password_confirmation`?

**Comment by susandaiute** [comment]
Rather than putting it in my modal...I thought it would be easier to just delete it from the credentials.  Is it a requirement?

**Comment by laurenfazah** [comment]
Yep, so when your UsersController is asking for this, you've gotta provide it. See if adding that clears it up.

Again, from UsersController:

```
  def user_creds
    params.require(:credentials)
          .permit(:email, :password, :password_confirmation)
  end
```

Also, make sure your data object is coming in with a root key of `credentials`

**Comment by RealWeeks** [comment]
Please see #243 for additional insight

**Comment by susandaiute** [comment]
How do I check to see if the root key I'm sending is `credentials`?

**Comment by laurenfazah** [comment]
That's where you'd want to console.log your data in your signup function that sends the AJAX request.

**Comment by susandaiute** [comment]
It looks like I'm getting an empty object.

**Comment by susandaiute** [comment]
I'm wondering if the problem isn't in GetFormFields then.

**Comment by RDegnen** [comment]
Ill assign myself

**Comment by susandaiute** [comment]
@RDegnen  I might have done this wrong. I changed 

``````
$('#submitPost').on('click', function (event) {
  event.preventDefault();
  let data = getFormFields(this);
  console.log(data);
  authApi.signUp(authUi.success, authUi.failure, data);
});
`` 
to  act on ```#registerForm``` and now when I click on any button in the form, it sends a POST request.
``````

**Comment by susandaiute** [comment]
should I not have changed `submitPost` and instead have changed `getFormFields(this)` to `getFormFields(#registerForm)`?

**Comment by RDegnen** [comment]
change `$(#submitPost).on('click', function (event))` to `$(#registerForm).on('submit', function (event))`

**Comment by susandaiute** [comment]
When I did that, the Post request gets sent whenever anything button in the form is clicked.

**Comment by RDegnen** [comment]
k ill come back

**Comment by susandaiute** [comment]
Should I wrap the button in it's own form?

**Comment by susandaiute** [comment]
Ok, so the problem was 
1) that I had the id set to the button's id and not the form's
2) that I had it set for .on('click') and not on.('submit).
3) that I totally didn't read what Ross wrote.

**Comment by susandaiute** [comment]
Solution:
`$(#registerForm).on('submit', function (event))`
