### ISSUE TITLE
Missing secret in config?

### ISSUE THREAD

**Issue by philschoof** [ga-wdi-boston/full-stack-project#249]
I've met all deliverables besides deploying to heroku, so I wanted to try it out today during instruction in case I ran into some weird problems like this one. I've pushed to heroku, restarted, and when I run heroku open I see this error 

Internal Server Error

Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml`
WEBrick/1.3.1 (Ruby/2.3.0/2015-12-25) at serene-spire-31706.herokuapp.com:443

I have keys for development and test, but not production. Should I run the secret command to get a key for production?

Thanks

**Comment by laurenfazah** [comment]
Yup.

**Comment by philschoof** [comment]
Ok I have the key now but I'm unsure of what to do next. I ran heroku rake db:migrate, git push heroku master, heroku restart, and when I heroku opened I got the same error.

**Comment by RealWeeks** [comment]
@laurenfazah there is a command you can run in your console to set heroku variables

**Comment by laurenfazah** [comment]
`heroku config:set secret_token=XXX secret_key_base=XXX`

**Comment by philschoof** [comment]
should I set those variables to the keys that are in my secrets.yml file?

**Comment by laurenfazah** [comment]
Try that - if not, `rake secret` for new ones, and if not, we may need to take a different approach.

**Comment by RealWeeks** [comment]
https://devcenter.heroku.com/articles/config-vars

**Comment by RealWeeks** [comment]
There are a few ways to do this @philschoof

**Comment by philschoof** [comment]
Is one better than another? 
@laurenfazah what does secret_token refer to in that command?

**Comment by laurenfazah** [comment]
Just one name of the two token keys you need to set up

**Comment by RealWeeks** [comment]
@philschoof they both do the same thing

**Comment by philschoof** [comment]
I'm going to try the link @J-Weeks posted.

**Comment by philschoof** [comment]
Ok I'm still pretty sideways on this and am now having other problems I should address. Should I close this and open another one if I need to later?

**Comment by laurenfazah** [comment]
Well what did you end up running and where did you run it?

**Comment by philschoof** [comment]
heroku config:set GITHUB_USERNAME=philschoof
which printed 

```
Setting GITHUB_USERNAME and restarting ⬢ serene-spire-31706... done, v7
GITHUB_USERNAME: philschoof
~/wdi/projects/second-project (master)$ heroku config
=== serene-spire-31706 Config Vars
DATABASE_URL:             postgres://kgguxlnlbwizqa:8cHQ86lNR51_9m1KWI20K2_bEb@ec2-54-204-41-70.compute-1.amazonaws.com:5432/d6nmmssb3c81uf
GITHUB_USERNAME:          philschoof
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:          58b6e34bd96dc313530a6c4922fea9e974caad0bbbe6f0828e218fcedbdc45774d2080ff9e3d20685ddc18f1d84523633842a49e3b86c29df7d2edc8e1881bd5
secret_key_base:          XXX
secret_token:             XXX
```

I don't know what values I'm supposed to be putting where if any.

**Comment by laurenfazah** [comment]
Looks like you made a start. You only needed to run the config command I first gave you and those XXXs should have been replaced with your actual secret tokens. Try running again with XXX replaced. My bad if that wasn't clear to replace those.

**Comment by philschoof** [comment]
I don't have anything called secret_token, and there are secret_base_keys for development, test, and production. What should go where?

**Comment by laurenfazah** [comment]
Let's roll back a bit before we stray too far from the original issue. Your original post had an error that said 

> Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in config/secrets.yml

So running `heroku config:set secret_token=<replace_with_rake_secret_result> secret_key_base=<replace_with_rake_secret_result>` on the command line within your back end repo should set those.

Otherwise it's saying you can add both `secret_token=<replace_with_rake_secret_result>` and  `<secret_key_base=<replace_with_rake_secret_result>` under a `production` key in config/secrets.yml

**Comment by gaand** [comment]
Please, no productions secrets in the repository

**Comment by gaand** [comment]
Please paste your `config/secrets.yml`

**Comment by philschoof** [comment]
```
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5637f0037616a2adc86065b4ea5c6e76c1204c51e6dd1401d4d1a79c543441f6fffec64f72af2390d84fa5f2583dd273e2fb743ab9907040225d7ab6f046eb1c

# Use different runs of `rake secret` for development and test
test:
  secret_key_base: 0a97e7c685847efd17b930b9278c1278460b9c4f9072a921be7f63bf9eb94c392e9c87512d10adb3eee64f53b6aeb9618161c491b86c76854210b67ca415f4c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
```

**Comment by RealWeeks** [comment]
@philschoof i think you followed the directions to literally

http://stackoverflow.com/questions/18556955/heroku-config-secret-key-base-error

**Comment by RealWeeks** [comment]
im going to explain this to phil

**Comment by RealWeeks** [comment]
The secrets.yml file was not being committed.  Had to do it with force `git add confit/secrets.yml -f` then run command to create secret_key_base and secret_token.  Something like `heroku config:set SECRET_TOKEN=$(rake secret)` and similar for secret_token

**Comment by jrhorn424** [comment]
This should be fixed in the near future by https://github.com/ga-wdi-boston/orientation/issues/166
