### ISSUE TITLE
CSV file

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/full-stack-project#252]
I would like to add data into my table. My table only has "Name" and "Ingredients." I'd like to load the data via a csv file. Looking for help on how to format what I type up. I don't have Excel so......yeap

**Comment by Jcornmanhomonoff** [comment]
Also, I don't want my ingredients to be a blob of text. Is there an easy way to format that? Ie: some kind of code that tells it at each comma make a line break...or something...?

If that's the case, I would obviously need to enter my Ingredients with commas, hence the question

**Comment by Jcornmanhomonoff** [comment]
Mostly my issue is with the list of ingredients and commas.

**Comment by gaand** [comment]
Should the ingredients be a separate table?  Possibly joined to the main table via a many-to-many relationship?

**Comment by Jcornmanhomonoff** [comment]
Made a joint table :(
