### ISSUE TITLE
How can I include a jQuery plugin

### ISSUE THREAD

**Issue by sjf125** [ga-wdi-boston/full-stack-project#253]
I want to use [Lazy Load](http://www.appelsiini.net/projects/lazyload) in my project, and it says I need to include the following in my html:

``` html
<script src="jquery.js"></script>
<script src="jquery.lazyload.js"></script>
```

I know we already have jQuery included in the...bundle?  But how would I go about including the Lazy Loader plugin?  Since I know that adding more <scripts> to our html won't work, and will get overridden by the bundle.

**Comment by gaand** [comment]
Have you searched the web with appropriate keywords?

**Comment by sjf125** [comment]
@gaand Yes, but I thought we couldn't insert additional script tags into out HTML because of WebPack?  I've found [this](http://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack) but I don't really understand it and I don't want to mess around with my webpack files at the risk of breaking other things.

**Comment by gaand** [comment]
I searched "webpack jquery lazyload" and the first result seemed like the right answer. No extra script tags required.

**Comment by sjf125** [comment]
Got it, thanks!

**Comment by gaand** [comment]
@sjf125 Don't leave us hanging, did you get it to work?

**Comment by sjf125** [comment]
I installed it via npm, and included the code listed [here](https://www.npmjs.com/package/jquery.lazyload.cjs), but it's not actually working.  I'm working on other things right now, but here is the code I have in my index.js file:

``` js
'use strict';

const events = require('./api/events.js');
var $ = require('jquery');
require('jquery.lazyload.cjs')($);

// On document ready
$(() => {
  events.addHandlers();
});

const displayFlags = function(flags){
  const flagsTemplate = require('./templates/flag-listing.handlebars');
  // const flagTemplate = require('./templates/flag.handlebars');
  $('.content').append(flagsTemplate({flags}));
  $('.flags').on("click", function(){
    localStorage.setItem('flagID',$(this).data("id"));
    let id = localStorage.getItem('flagID');
    // console.log(id);
    $('#flagModal').modal();
    getFlag(id);
  });
};

const getFlags = function(){
  $.ajax({
    url: "http://localhost:3000/flags",
    // method: 'GET',
    // dataType: 'json'
  }).done(function(data){
    displayFlags(data.flags);
  });
};

const displayFlag = function(flag){
  const display = require('./templates/flag.handlebars');
  $('.flagDisplay').empty();
  $('.flagName').val(function(){
    console.log(flag.name);
    return flag.name;
  });
  $('.flagDisplay').append(display({flag}));
  // $('.flags').on("click", function(){
  //   console.log(localStorage.getItem('flagID'));
  //   let id = localStorage.getItem('flagID');
  //   console.log(id);
  // });
};

const getFlag = function(id){
  console.log(id);
  $.ajax({
    url: "http://localhost:3000/flags/" + id,
    // method: 'GET',
    // dataType: 'json'
  }).done(function(data){
    displayFlag(data.flag);
  });
};

$(document).ready(function(){
  getFlags();
  $("img").lazyload({
    effect : "fadeIn"
  });
});

```

**Comment by sjf125** [comment]
I'll open this back up since it's not working yet.

**Comment by gaand** [comment]
Do you get any errors or does it just silently fail?

**Comment by RealWeeks** [comment]
`--save` and you may want to move it to your js manifest.

**Comment by sjf125** [comment]
Silently fails - all images are loaded, and there's no fadein effect.  I do get a linter error on `var $ = require('jquery');` saying it's a "Redefinition of $'

**Comment by gaand** [comment]
``` diff
  const events = require('./api/events.js');
- var $ = require('jquery');
  require('jquery.lazyload.cjs')($);
```

**Comment by sjf125** [comment]
I commented out that line but no difference.

**Comment by gaand** [comment]
Interesting.  I'll swing by at 11:30.

**Comment by sjf125** [comment]
I had the lazyload function run before the images loaded, so moving where the lazy load was called made it work:

``` js
const displayFlags = function(flags){
  const flagsTemplate = require('./templates/flag-listing.handlebars');
  // const flagTemplate = require('./templates/flag.handlebars');
  $('.content').append(flagsTemplate({flags}));
  $("img.flags").lazyload({
    effect : "fadeIn"
  });
  $('.flags').on("click", function(){
    localStorage.setItem('flagID',$(this).data("id"));
    let id = localStorage.getItem('flagID');
    $('#flagModal').modal();
    getFlag(id);
  });
};
```
