### ISSUE TITLE
Custom handlebar helper (multiple handlebars columns)

### ISSUE THREAD

**Issue by sjf125** [ga-wdi-boston/full-stack-project#254]
I'd like to arrange my flags in rows of 3 flags each, and I found a [custom helper function](https://funkjedi.com/technology/412-every-nth-item-in-handlebars/) that seems perfect.  However, I have no idea how to include it - do I save it somewhere in a script?  Here's the code I'd like to use:

``` js
<div class="container">
{{#grouped_each 3 books}}
    <div class="row">
    {{#each this }}
        <div class="span4 book" data-isbn="{{ isbn }}">
            <strong>{{ name }}</strong>
        </div>
    {{/each}}
    </div>
{{/grouped_each}}
</div>
```

``` js
Handlebars.registerHelper('grouped_each', function(every, context, options) {
    var out = "", subcontext = [], i;
    if (context && context.length > 0) {
        for (i = 0; i < context.length; i++) {
            if (i > 0 && i % every === 0) {
                out += options.fn(subcontext);
                subcontext = [];
            }
            subcontext.push(context[i]);
        }
        out += options.fn(subcontext);
    }
    return out;
});
```

**Comment by sjf125** [comment]
``` js
<div class="container">
  {{#grouped_each 3 flags}}
    <div class="row">
      {{#each this }}
        <div class="col-xs-4">
          <strong>{{name}}</strong>
          <img src={{imgurl}} class="img-responsive flags" />
        </div>
      {{/each}}
    </div>
  {{/grouped_each}}
</div>
```

**Comment by sjf125** [comment]
``` js
<ul>
  {{#each flags}}
    <li class="well" data-id={{id}}>
      <h2>{{name}}</h2>
      <img src={{imgurl}} class="img-responsive flags" alt="Image" />
    </li>
  {{/each}}
</ul>
```

**Comment by RealWeeks** [comment]
@sjf125 current webpack isn't configured to deal with handlebars helpers, it's a known issue. I'll add this to my webpack queue.

**Comment by sjf125** [comment]
Ah, bummer.  I'll close the issue, but let me know if there's any workarounds I can do to achieve a handlebars output in multiple columns.

**Comment by RealWeeks** [comment]
@sjf125 I reopened to discuss how to achieve handlebars output in multiple columns. Can you explain what your trying to achieve. If it's what I think it should be that difficult.

**Comment by sjf125** [comment]
@J-Weeks I want to have my flag names and images appear in a tiled gallery-like format like [this](http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_temp_store&stacked=h), or at least side-by-side in col-xs-6 or col-xs-4.

**Comment by RealWeeks** [comment]
I think a good solution to this would be to use partials.  One way to do this would be to "chunk" you flags into groups of three and feed them to the handlebars template, and let the css do the aligning for you.

**Comment by sjf125** [comment]
I used some pure CSS styling to organize the flags into a grid system, largely going off of [this](http://alijafarian.com/responsive-image-grids-using-css/).  Thanks!
