### ISSUE TITLE
How can I avoid circular dependencies on the front end?

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/full-stack-project#255]
This is an issue I ran into with tic-tac-toe as well. I find myself in the following pattern:
1. User clicks "Create New Document" button (events.js)
2. That action results in an ajax POST request (api.js)
3. Once the ajax call is successful, the UI is updated (ui.js)
4. Since there is a button associated with every document though, to successfully update the UI I must require (events.js), which creates the event handlers.

This results in a circular dependency which creates (often silent) errors. At least as far as I can tell that's the issue.

What's the best practice for dealing with this? Should I separate out all of my functions into separate files? Or merge them all together into one big module?

**Comment by soynog** [comment]
P.S. This is why I ended up with flow-control.js in my last project. Which I was told is bad practice (or maybe just the name was bad practice?). 

Point 7 in [this article](http://www.bitnative.com/2015/02/03/circular-dependencies-in-requirejs/) recommends making a 'business object'... which seems like more or less the approach I was going for with the 'flow-control' script.

**Comment by gaand** [comment]
I'm not sure I'm following. Please paste code snippets that show what your trying to accomplish for the flow you outlined. Please show just the requires and the relevant calls.

**Comment by soynog** [comment]
I think I've solved it using a master script that calls all the other scripts and passes them callback functions. Let's talk about it in more depth on Monday though, I'm curious if my solution is the right one.
