### ISSUE TITLE
Climb data saving with user reference but not gym reference

### ISSUE THREAD

**Issue by MichaelB167** [ga-wdi-boston/full-stack-project#256]
My database structure is the following: http://i.imgur.com/XVvYTwi.jpg.  I'm trying to create a show action that displays users' gyms and their climbs in each individual gym.  

Post actions are functioning and authenticated so that a user can input a gym that has their id attached and a climb that has their id attached, but the climbs aren't saving with a reference to gyms despite my having specified that relationship in my migrations.  

I could manually upload climb data with gym references attached but as the data for my app is user driven I'd like to avoid that.  I also don't think a join table makes sense as all the relationships in my database are one to many.  Do I need to perhaps create an additional action in my climb controller to specify that climbs are not only defined by the current user but also the current gym?

Climbs controller: 

```
# climbs controller
class ClimbsController < ProtectedController
  before_action :set_climb, only: [:update, :destroy]

  # GET /climbs
  # GET /climbs.json
  def index
    @climbs = current_user.climbs

    render json: @climbs
  end

  # GET /climbs/1
  # GET /climbs/1.json
  def show
    render json: Climb.find(params[:id])
  end

  # POST /climbs
  # POST /climbs.json
  def create
    @climb = current_user.climbs.build(climb_params)

    if @climb.save
      render json: @climb, status: :created, location: @climb_params
    else
      render json: @contact.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /climbs/1
  # PATCH/PUT /climbs/1.json
  def update
    @climb = Climb.find(params[:id])

    if @climb.update(climb_params)
      head :no_content
    else
      render json: @climb.errors, status: :unprocessable_entity
    end
  end

  # DELETE /climbs/1
  # DELETE /climbs/1.json
  def destroy
    @climb.destroy

    head :no_content
  end

  private

  def set_climb
    @climb = current_user.climbs.find(params[:id])
  end

  def climb_params
    params.require(:climb).permit(:route_type, :route_grade,
                                  :hold_type_of_fall, :fall_notes)
  end

  private :set_climb, :climb_params
end
```

**Comment by laurenfazah** [comment]
Could you post what your models look like?

**Comment by MichaelB167** [comment]
user: 

```
class User < ActiveRecord::Base
  include Authentication
  has_many :examples
  has_many :gyms, inverse_of: :user
  has_many :climbs, inverse_of: :user
end
```

gym:

```
class Gym < ActiveRecord::Base
  has_many :climbs, inverse_of: :gym
  belongs_to :user
end
```

climb:

```
class Climb < ActiveRecord::Base
  belongs_to :gym, inverse_of: :climbs
  belongs_to :user, inverse_of: :climbs
end
```

**Comment by MichaelB167** [comment]
just noticed climbs should be singular, fixing now

**Comment by MichaelB167** [comment]
^ crashed climb inputs, attempting to fix that

**Comment by MichaelB167** [comment]
never mind I think I'm confusing myself, climbs should be correct

**Comment by MichaelB167** [comment]
changed gym model to the following but still working on getting the gym reference id to save

```
class Gym < ActiveRecord::Base
  has_many :climbs, inverse_of: :gym
  belongs_to :user, inverse_of: :gyms
end
```

**Comment by gaand** [comment]
Are you providing the gym_id when creating a climb?

**Comment by MichaelB167** [comment]
I can do so by manually specifying it if I add a climb through the terminal as we have done in class, and I created a foreign key for gyms during my migrations so they should be related.  I don't think I am providing an id via creating a climb in the browser though.  Am I correct in thinking that my controller is the source of the problem?

**Comment by gaand** [comment]
Your controller needs to supply a gym_id when creating a climb and the client needs to send a gym_id when posting. A nested route might be appropriate.

**Comment by MichaelB167** [comment]
Ok.  I thought I had set up the route as nested but I'll go back through my notes and see if I can figure out what I'm missing, thank you Antony.

**Comment by gaand** [comment]
@MichaelB167  If you do have a nested route, before saving the new climb, set the gym_id from `params[:gym_id]`.

**Comment by MichaelB167** [comment]
I guess I'm unsure of what the syntax would look like.  As I understand it, my goal is to change the output of rake routes from 
`climbs GET    /climbs(.:format)              climbs#index` 
to `climbs GET    gyms/:id/climbs(.:format)              climbs#index`

Am I on the right track with something like
`@climb = Gym.find(params[:gym_id]).climbs.build(climb_params)`

**Comment by MichaelB167** [comment]
Still having trouble getting nest climbs to post.  Rake routes output is : 

```
    Prefix Verb   URI Pattern                        Controller#Action
  examples GET    /examples(.:format)                examples#index
           POST   /examples(.:format)                examples#create
   example GET    /examples/:id(.:format)            examples#show
           PATCH  /examples/:id(.:format)            examples#update
           PUT    /examples/:id(.:format)            examples#update
           DELETE /examples/:id(.:format)            examples#destroy
gym_climbs GET    /gyms/:gym_id/climbs(.:format)     climbs#index
           POST   /gyms/:gym_id/climbs(.:format)     climbs#create
 gym_climb GET    /gyms/:gym_id/climbs/:id(.:format) climbs#show
           PATCH  /gyms/:gym_id/climbs/:id(.:format) climbs#update
           PUT    /gyms/:gym_id/climbs/:id(.:format) climbs#update
           DELETE /gyms/:gym_id/climbs/:id(.:format) climbs#destroy
      gyms GET    /gyms(.:format)                    gyms#index
           POST   /gyms(.:format)                    gyms#create
       gym GET    /gyms/:id(.:format)                gyms#show
           PATCH  /gyms/:id(.:format)                gyms#update
           PUT    /gyms/:id(.:format)                gyms#update
           DELETE /gyms/:id(.:format)                gyms#destroy
   sign_up POST   /sign-up(.:format)                 users#signup
   sign_in POST   /sign-in(.:format)                 users#signin
           DELETE /sign-out/:id(.:format)            users#signout
           PATCH  /change-password/:id(.:format)     users#changepw
     users GET    /users(.:format)                   users#index
      user GET    /users/:id(.:format)               users#show
```

Relevant climbs controller sections are: 

```
def create
    @climb = current_user.gyms.find(params[:gym_id]).climbs.build(climb_params)

    if @climb.save
      render json: @climb, status: :created, location: @climb_params
    else
      render json: @contact.errors, status: :unprocessable_entity
    end
  end
```

and

```
def climb_params
    params.require(:climb).permit(:route_type, :route_grade,
                                  :hold_type_of_fall, :fall_notes, :gym_id)
  end
```

The curl script I'm testing with is:

```
curl --include --request POST http://localhost:3000/gyms/50/climbs \
    --header "Authorization: Token token=BAhJIiViNWQwYTNiYjlmM2MyZjg5ZTZhNDA4OTc3NTk2M2Y4NwY6BkVG--a2e73c49139e36b3db62e9ee49c25e1a75e11ac2" \
    --header "Content-Type: application/json" \
    --data '{
      "climbs": {
        "route_type": "Lead",
        "route_grade": "11",
        "hold_type_of_fall": "Crimp",
        "fall_notes": "Foot cut",
        "gym_id": "50"
      }
    }'
```

Getting 401 errors from ruby server despite having copied the token from signing in, is there maybe something wrong with my curl syntax?

**Comment by MichaelB167** [comment]
Testing through the browser with the following ajax function yields `Cannot read property 'id' of undefined` so maybe the problem is the gym id not being saved in the right place?

```
const createClimb = (success, failure, data) => {
  $.ajax({
    method: "POST",
    url: app.api + '/gyms/' + app.gyms.id + '/climbs',
    dataType: 'json',
    headers: {
      Authorization: 'Token token='+ app.user.token,
    },
    data,
  })
  .done(success)
  .fail(failure);
};
```

**Comment by gaand** [comment]
If you're getting a 401 on the curl command you're probably using an outdated token.

Please post the code that saves the gym in your app.

**Comment by MichaelB167** [comment]
@gaand Do you mean in the gym controller?

```
def create
    @gym = current_user.gyms.build(gym_params)

    if @gym.save
      render json: @gym, status: :created, location: @gym
    else
      render json: @contact.errors, status: :unprocessable_entity
    end
  end
```

createGym function:

```
const createGym = (success, failure, data) => {
  $.ajax({
    method: "POST",
    url: app.api + '/gyms',
    dataType: 'json',
    headers: {
      Authorization: 'Token token='+ app.user.token,
    },
    data,
  })
  .done(success)
  .fail(failure);
};
```

**Comment by MichaelB167** [comment]
tabling this until tomorrow and focusing on getting read to work properly.

**Comment by gaand** [comment]
@MichaelB167 I meant the code that saves to, I think, `app.gyms` since that's what you're trying to us to get the gym id.
