### ISSUE TITLE
Question: Creating New Branch to test new data migrations

### ISSUE THREAD

**Issue by rdelvallej32** [ga-wdi-boston/full-stack-project#257]
Hi,

I'm beginning the early process of setting up to add a third party api to my project. I created a separate branch that is not my master and would like to add new migration files to it, but I was wondering if this will affect my database? Or does my database technically change when I am in a new branch?

**Comment by gaand** [comment]
The database changes when you run the migrations. You should migrate to a version before those migrations before switching back to the master branch (unless you're ready to merge).

**Comment by rdelvallej32** [comment]
Okay thanks!
