### ISSUE TITLE
Join table- is an object created?

### ISSUE THREAD

**Issue by natdjerf** [ga-wdi-boston/full-stack-project#258]
I'm trying to get back an object on a join table in order to make a post. 

My database relationships are structured as follows:

``` rb
class Board < ActiveRecord::Base
  belongs_to :user, inverse_of: :boards
  has_many :cheese_additions
  has_many :cheeses, through: :cheese_additions
end

class Cheese < ActiveRecord::Base
  has_many :cheese_additions
  has_many :boards, through: :cheese_additions
end

class CheeseAddition < ActiveRecord::Base
  belongs_to :board, inverse_of: :cheese_additions
  belongs_to :cheese, inverse_of: :cheese_additions
end
```

where my cheese addition table holds only two items: board_id & cheese_id. When I submit a post request tor a board or user, I get back an object, but when I submit a post request for the cheese_addition, I don't. If I create an object from the form fields, I can't specify what type of object it is. I think it is because it's a join table rather than a standard table, but I'm not sure why/how to resolve. Should I be posting to cheese additions through board? 

I added the form fields in order to get back an object, but I would expect object{cheese_addition:Object}...

event handler:
(disregard the console logs, but I leave them there to show that I'm able to get the necessary information)

``` js
  $('.add-cheese-button').on('click', function (event) {
   event.preventDefault();
   console.log('Add to Board clicked.');
   let data = getFormFields(this);
   data.cheese_id = $(event.target).closest('div').data('id');
   console.log(data);
   data.board_id = app.board.id;
   console.log(data.board_id);
   console.log(data.cheese_id);
   cheeseApi.addToBoard(cheeseUi.addToBoardSuccess,cheeseUi.addToBoardFailure, data);
});

const addToBoard = (success, failure, data) => {
  $.ajax({
    method: 'POST',
    url: app.api + '/cheese_additions',
    headers:{
        Authorization: 'Token token=' + app.user.token,
    },
    data,
  }).done(success)
  .fail(failure);
};
```

console:

``` json
Object {user: Object}
user-events.js:17 Sign In clicked
user-ui.js:18 Object {user: Object}
cheese-events.js:44 Create Board clicked.
cheese-events.js:45 Object {board: Object}
cheese-ui.js:7 Object {id: 56, name: "attempt"}
cheese-ui.js:8 Object {id: 56, name: "attempt"}
cheese-events.js:62 Add to Board clicked.
cheese-events.js:67 Object {cheese_id: 2}
cheese-events.js:69 56
cheese-events.js:70 2
:3000/cheese_additions:1 POST http://localhost:3000/cheese_additions 
localhost/:1 XMLHttpRequest cannot load http://localhost:3000/cheese_additions. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
cheese-ui.js:20 Object {readyState: 0, status: 0, statusText: "error"}
```

my rails server is looking for cheese_params:
ActionController::ParameterMissing (param is missing or the value is empty: cheese_addition):
  app/controllers/cheese_additions_controller.rb:57:in `cheese_addition_params'

I'm able to get back the cheese_id & board_id by storing in a variable, but it's not coming back in the format I need to send a post request.

**Comment by natdjerf** [comment]
**Update. If I create a key value pair inside data, I am able to get it to work. I'm not sure this is the cleanest way, so please feel free to advise on a better approach.

``` js
$('.add-cheese-button').on('click', function (event) {
   event.preventDefault();
   console.log('Add to Board clicked.');
   let data = getFormFields(this);
   data.cheese_addition = {};
   data.cheese_addition.cheese_id = $(event.target).closest('div').data('id');
   data.cheese_addition.board_id = app.board.id;
   console.log(data);
   cheeseApi.addToBoard(cheeseUi.addToBoardSuccess,cheeseUi.addToBoardFailure, data);
});
```

**Comment by laurenfazah** [comment]
What is the `data` coming from the form fields before you add the `cheese_addition` object? Also, if this is working for now, I might suggest moving forward with it and come back to refactor it after you've got everything else up and running too.

**Comment by laurenfazah** [comment]
@natdjerf is this still a standing issue?

**Comment by natdjerf** [comment]
All set, closing!
