### ISSUE TITLE
Logout request makes my login jquery stop working.

### ISSUE THREAD

**Issue by LaurenGrant** [ga-wdi-boston/full-stack-project#26]
I wrote my jquery for logout in my ajax.js file and now that it is in the file, my login jquery will not work anymore. Not sure how if this is an issue of location in my file or what.

**Comment by GA-MEB** [comment]
Have you tested login behavior from Postman and/or `curl`?

**Comment by jrhorn424** [comment]
@MattB-GA-Boston I don't believe this is testable using `curl`. This is a frontend-only feature that deletes a token from a global object.

@LaurenGrant Come speak with me. I'm in classroom 1.

**Comment by GA-MEB** [comment]
Issue resolved! Typo in jQuery code - reversed `}` and `)`
