### ISSUE TITLE
AJAX POST request not recognizing function

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/full-stack-project#260]
I'm trying to make a POST request of an answer selected for a poll.  I'm getting back from my browser console that "checkAnswerOne is not a function".

```
const answerPoll = (success, failure, data) => {
  $.ajax({
    method: 'POST',
    url: app.api + '/answers',
    data,
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  }).done(success)
  .fail(failure);
};
```

```
$('#panelA').on('submit', function (event) {
  event.preventDefault();
  let data = checkAnswerOne();
  console.log(data);
  authApi.answerPoll(authUi.success, authUi.failure, data);
});
```

```
const checkAnswerOne = function () {
  answer = $("input[name=worms]:checked").val();
  console.log('this is answer' + answer);
  return answer;
};
```

**Comment by gaand** [comment]
Do you have linter errors?  You should getting that error. 

Is checkAnswerOne defined in the same file as the submit handler?  Is it defined before you use it?

**Comment by susandaiute** [comment]
Hi  Antony, checkAnswerOne is in a separate file.  I have it referenced with 
`const checkAnswerOne = require('./pollwork');`

**Comment by gaand** [comment]
Please post the `module.exports` from pollwork.js.

**Comment by susandaiute** [comment]
```
module.exports = {
  checkAnswerOne,
  checkAnswerTwo,
  checkAnswerThree,
};

```

**Comment by gaand** [comment]
You're not exporting a function, your exporting an object. So that explains the error message. You need to access the methods on that exported object.

**Comment by susandaiute** [comment]
I changed checkAnswerOne to:

```
const checkAnswerOne = function () {
  answer = $("input[name=worms]:checked");
  console.log('this is answer' + answer);
  return answer;
};
```

 and the event handler:

```
$('#panelA').on('submit', function (event) {
  event.preventDefault();
  let data = answer.id;
  console.log(data);
  authApi.answerPoll(authUi.success, authUi.failure, data);
});
```

and also changed the 'require'. 
I'm now getting that console.log('data') is undefined and an uncaught type error "Cannot read property 'token' of undefined" referring to:

```
const answerPoll = (success, failure, data) => {
  $.ajax({
    method: 'POST',
    url: app.api + '/answers',
    data,
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  }).done(success)
  .fail(failure);
};
```

**Comment by RealWeeks** [comment]
Try putting a debugger when you open answerPoll, what is app?

**Comment by susandaiute** [comment]
App is `Object {api: "http://localhost:3000"}`

**Comment by RealWeeks** [comment]
Do you store the user object on sign in?

**Comment by susandaiute** [comment]
This is a super basic question, but how do I even know if I'm doing that?  My brain is so dead. :(

**Comment by susandaiute** [comment]
I have this:

```
  def signin
    creds = user_creds
    if (user = User.authenticate creds[:email],
                                 creds[:password])
      render json: user, serializer: UserLoginSerializer, root: 'user'
    else
      head :unauthorized
    end
  end
```

**Comment by laurenfazah** [comment]
To find out if you're storing the user object on login, in your front-end repo, check out whatever function you're passing to sign in success (likely in the `ui.js` file if you're structured the same way as tic tac toe). Does the response data returned from success get saved anywhere?

**Comment by susandaiute** [comment]
I believe I am saving it, but I'm not sure.  I have:

```
const signInSuccess = (data) => {
  app.user = data.user;
  console.log(app);
};
```

**Comment by laurenfazah** [comment]
Looks right - so on sign in, do you get back that `console.log(app)` with a user object saved to it?

**Comment by susandaiute** [comment]
Yep.   `Object {api: "http://localhost:3000", user: Object}`

**Comment by laurenfazah** [comment]
Going to self assign

**Comment by susandaiute** [comment]
Summary: 

There was a typo in Questions Controller.  Also, it inherited from OpenReadController when it should have inherited from ProtectedController.

In addition, the QuestionsController looked like:
```class QuestionsController < ProtectedController
  before_action :set_question

``````
but needed ```only: [:show, :update, :destroy]``` after ``` :set_question```
``````
