### ISSUE TITLE
Major Git Remote Issues, two branches going to two repos

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/full-stack-project#262]
All of my commits are incredibly messed up.  Both the front end and back end repos have front end and back end branches.  Somehow, when I went to commit in the back end branch to the back end repo, when I typed in "git commit" the branch magically changed to the front end branch.....and then there's this stuff like ```error: Your local changes to the following files would be overwritten by checkout:
    back-end/app/controllers/answers_controller.rb
    back-end/app/controllers/questions_controller.rb
Please, commit your changes or stash them before you can switch branches.
error: Your local changes to the following files would be overwritten by checkout:
    back-end/config/routes.rb
Please, commit your changes or stash them before you can switch branches.
Aborting

```
which makes me think I have submodules...I don't even know.....and then when I checkout to a different branch a bunch of work is gone and everything is horrible.

I'm ready to just destroy both repos and start over.....
```

**Comment by susandaiute** [comment]
Omg...I messed up the back tick thing too

**Comment by BenGitsCode** [comment]
Have you been pushing your commits to github? If you have been, you can get a more visual record of your commits, and sort them by branches. You should be able to track down where things went awry.

https://github.com/susandaiute/PollPanda/commits/master

**Comment by RDegnen** [comment]
Did you initialize one Git repository in a directory that has both the front and back end directories in it? Or did you initialize a separate repo for each?

**Comment by susandaiute** [comment]
Yup. That's what I did.

**Comment by susandaiute** [comment]
Currently attempting this:

Move the folder:

mv .git thecorrectfolder/
Re-initialize the git repo:

cd thecorrectfolder/
git init
Re-add all the files, commit, and push:

git add .
git commit -am 'fixing things'
git push origin master
Done! Get yourself a beer.

From this page:http://stackoverflow.com/questions/1918111/my-git-repository-is-in-the-wrong-root-directory-can-i-move-it-instead-of

**Comment by laurenfazah** [comment]
How did this work out for you @susandaiute?

**Comment by susandaiute** [comment]
So I moved the git thing from the parent PollPanda directory down to the Front End subdirectory:

```
~/wdi/projects/pollpanda (pollwork)$ mv . git frontend
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/wdi/projects/pollpanda (pollwork)$ cd front-end/
~/wdi/projects/pollpanda/front-end (pollwork)$ git init
Initialized empty Git repository in /Users/susandaiute/wdi/projects/pollpanda/front-end/.git/
~/wdi/projects/pollpanda/front-end (master)$ git add .
~/wdi/projects/pollpanda/front-end (master)$ git remote -v
~/wdi/projects/pollpanda/front-end (master)$ git remote add origin git@github.com:susandaiute/PollPanda.git
~/wdi/projects/pollpanda/front-end (master)$ git remote -v
origin  git@github.com:susandaiute/PollPanda.git (fetch)
origin  git@github.com:susandaiute/PollPanda.git (push)
~/wdi/projects/pollpanda/front-end (master)$ git add .
~/wdi/projects/pollpanda/front-end (master)$ git commit -m "move git initialize"
[master (root-commit) d70c5cc] move git initialize
 31 files changed, 1243 insertions(+)
 create mode 100755 .editorconfig
 create mode 100755 .gitignore
 create mode 100755 .jscsrc
 create mode 100755 .jshintignore
 create mode 100755 .jshintrc
 create mode 100755 .remarkrc
 create mode 100755 Gruntfile.js
 create mode 100755 LICENSE
 create mode 100755 README.md
 create mode 100755 assets/scripts/answer.js
 create mode 100644 assets/scripts/api.js
 create mode 100644 assets/scripts/app-data.js
 create mode 100755 assets/scripts/index.js
 create mode 100644 assets/scripts/pollwork.js
 create mode 100644 assets/scripts/ui.js
 create mode 100755 assets/styles/index.scss
 create mode 100755 favicon.ico
 create mode 100755 forms.md
 create mode 100755 grunt/aliases.json
 create mode 100755 grunt/jasmine.json
 create mode 100755 grunt/jscs.json
 create mode 100755 grunt/jshint.json
 create mode 100755 grunt/jsonlint.json
 create mode 100755 grunt/paths.json
 create mode 100755 grunt/webpack-dev-server.js
 create mode 100755 grunt/webpack.js
 create mode 100755 index.html
 create mode 100755 index.js
 create mode 100755 lib/get-form-fields.js
 create mode 100755 package.json
 create mode 100755 spec/_all.js
```

and then when I did `git push origin master`, it resulted in:

```
o git@github.com:susandaiute/PollPanda.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:susandaiute/PollPanda.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

So then I did `git pull`

```
~/wdi/projects/pollpanda/front-end (master)$ git pull
warning: no common commits
remote: Counting objects: 294, done.
remote: Compressing objects: 100% (227/227), done.
remote: Total 294 (delta 95), reused 238 (delta 42), pack-reused 0
Receiving objects: 100% (294/294), 55.95 KiB | 0 bytes/s, done.
Resolving deltas: 100% (95/95), done.
From github.com:susandaiute/PollPanda
 * [new branch]      backend    -> origin/backend
 * [new branch]      html       -> origin/html
 * [new branch]      initialhtml -> origin/initialhtml
 * [new branch]      master     -> origin/master
 * [new branch]      pollwork   -> origin/pollwork
 * [new branch]      userwork   -> origin/userwork
There is no tracking information for the current branch.
Please specify which branch you want to rebase against.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master
```

and then tried `git pull master` and got:

```
~/wdi/projects/pollpanda/front-end (master)$ git pull master
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by laurenfazah** [comment]
Yikes okay. What state are you in locally?
- Is your app still working?
- Do you have two separate git repositories for both front and back end?
- If so, when you run `git remote -v` in both, can you paste what each lists?
- Also if so, what are your git repository URLs (the ones you paste if you were to clone)?

**Comment by laurenfazah** [comment]
If the answers to those are mostly negatives, would you be able to wait until the morning to detangle in person?

**Comment by susandaiute** [comment]
Omg yes, in person would be great. I think I might actually put this down for a brain break for an hour or so.  Thanks so much for the help Lauren!

**Comment by susandaiute** [comment]
Register and sign in are still working.  Update password and sign out no longer work.  I'm guessing this relates to my other open issue where user isn't being stored on sign in - no clue how that changed in between now and Friday.
There are two repositories, one for front end, the other for back end.
git remote -v for front end returns

```
origin  git@github.com:susandaiute/PollPanda.git (fetch)
origin  git@github.com:susandaiute/PollPanda.git (push)
```

which is my front end repo.

git remote -v for the back end returns the same thing, the front end repo.

The url for the front end repo is:    git@github.com:susandaiute/PollPanda.git
and the back end is:    git@github.com:susandaiute/SecondProjectBackEnd.git

**Comment by laurenfazah** [comment]
@susandaiute let me know when you're settled and I'll work through this with you.

**Comment by susandaiute** [comment]
Solution: created two new repos, destroyed the old ones, created two new directories in terminal, destroyed the old ones.  Currrently rising from the ashes like a beautiful phoenix.
