### ISSUE TITLE
Handlebars not displaying get request, unsure of how to test

### ISSUE THREAD

**Issue by MichaelB167** [ga-wdi-boston/full-stack-project#263]
I'm trying to display the result of a get request for all of the current user's climbs.  My corresponding curl request is successful and modals nested in my handlebars function that will eventually handle patch/delete requests for each climb are showing up but no data is populating.  Having just learned handlebars I'm unsure of how to go about testing the function or if this is even a viable way to structure it? 

initial sign in trigger

```
const signInSuccess = (data) => {
  app.user = data.user;
  console.log(data);
  climbApi.getClimbs(climbUi.getClimbsSuccess, climbUi.failure);
};
```

ajax

```
const getClimbs = (success, failure) => {
  $.ajax({
    method: 'GET',
    url: app.api + '/climbs',
    dataType: 'json',
    headers:{
      Authorization: 'Token token=' + app.user.token,
    },
  })
  .done(success)
  .fail(failure);
};
```

climb-ui

```
const getClimbsSuccess = (climbs) => {
  let showClimbs = require('../templates/show-climbs.handlebars');
  $('.content-display').html(showClimbs({climbs}));
};
```

handlebars 

```
{{#each climbs}}
  <div class="climb-list" data-id= {{id}}>
    Route Type: {{route_type}}<br/> Route Grade: {{route_grade}}<br/> Last Hold: {{hold_type_of_fall}}<br/> Fall Notes: {{fall_notes}}<br/>

    <div class=update-delete-modals>
      <button class="btn btn-primary btn-md update-climb" data-toggle="modal" data-target="#updateClimbModal" data-id= {{id}}>Update</button>
      <button type="button" class="btn btn-primary btn-md delete-climb" data-id= {{id}} id="delete-climb">Delete</button>
    </div>
  </div>
{{/each}}
```

**Comment by laurenfazah** [comment]
Hey Michael - so your template is loading, the data just isn't? Check out this issue to see how you'd need to nest an `{{#each this}}` loop within your `climbs` loop. https://github.com/ga-wdi-boston/full-stack-project/issues/244#issuecomment-215818696

**Comment by MichaelB167** [comment]
Thanks Lauren, I'll check that out.  Hope you're feeling better :)

**Comment by MichaelB167** [comment]
Hooray! Nesting {{#each this}} did the trick, they're displayed in a bizarre way but they're at least showing up haha.  TY again.

**Comment by gaand** [comment]
@MichaelB167 This may be an issue with root keys in JSON data and may not need nesting.  Please reopen if you'd like me to explain.

**Comment by MichaelB167** [comment]
@gaand Ok, get seems to work properly for now and I'm trying to finish satisfying the core requirements for CRUD (patch, delete) but once I satisfy those I'll definitely revisit this.
