### ISSUE TITLE
Model validation scope question

### ISSUE THREAD

**Issue by philschoof** [ga-wdi-boston/full-stack-project#264]
I'm trying to add some validation to my Album model, so that a user can't add the same album twice. Albums require a :title and an :author. I don't want to add uniqueness to them because I want the user to be able to have albums by the same artist with different titles, and albums with the same title by different artists. I initially added -

```
  validates :title, uniqueness: { scope: :artist }
  validates :artist, uniqueness: { scope: :title }
```
- but that threw an error when a signed-in user from adding an album that another user had added

```
POST http://localhost:3000/users/1/albums/ 422 (Unprocessable Entity)

Object {readyState: 4, responseText: "{"title":["has already been taken"],"artist":["has already been taken"]}", responseJSON: Object, status: 422, statusText: "Unprocessable Entity"}
```

I think I want something that does this 

```
 validates [:title, :artist], uniqueness: { scope: :user }
```

So that a user can't add the same album twice, but won't be stopped if another user has added that album.

**Comment by laurenfazah** [comment]
Hey Phil, have you tried something like this? http://stackoverflow.com/a/10910801/4141833

**Comment by philschoof** [comment]
It looks like that did it - heres my album model file for reference. Thanks!

```
class Album < ActiveRecord::Base
  belongs_to :user, inverse_of: :albums

  validates :title, presence: true
  validates :artist, presence: true

  validates :user, uniqueness: { scope: [:title, :artist] }
end
```
