### ISSUE TITLE
Adding 3rd Party API token to backend

### ISSUE THREAD

**Issue by rdelvallej32** [ga-wdi-boston/full-stack-project#266]
Hi, 

I would like to add my Account Token and SID to the backend, but concerned about where to place the information to keep it secure.

**Comment by RDegnen** [comment]
in your secrets file?

**Comment by rdelvallej32** [comment]
In the docs, it tells me to use this format within the secrets file :

twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

But I'm confused as to how it would know my account number or token from this format?

**Comment by RDegnen** [comment]
It's just like how you store your token for the user. You would use those variables that you set your key's to to access the account number/api key

**Comment by rdelvallej32** [comment]
Resolved: Created a env.yml file, added token and account id to it. Then added file path to GitIgnore file. Then created an environment_variables.rb file in the initializers folder
