### ISSUE TITLE
Join Table Issue

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/full-stack-project#267]
Having difficulty determining the order of my AJAX requests for ingredients.

**Comment by RDegnen** [comment]
what are you getting back from the server? an error? data that you don't expect?

**Comment by Jcornmanhomonoff** [comment]
I'm uncertain if I need to make two separate requests and multiple form fields or if I can do it all within the same request.

**Comment by RDegnen** [comment]
If your trying to get ingredients for a drink, then you would first need to find that drink and then get the ingredients from it

**Comment by Jcornmanhomonoff** [comment]
I'm trying to create a drink. I can successfully make the drink with a name but I'm not sure if I need to do a separate form and multiple requests to insert multiple ingredients.

**Comment by RDegnen** [comment]
Ah. You could also first find that drink and then push ingredients into their collection with a separate form, or do it all at once

**Comment by Jcornmanhomonoff** [comment]
How would one do it, if they were to do it all at once?

**Comment by Jcornmanhomonoff** [comment]
I shall attempt.

**Comment by Jcornmanhomonoff** [comment]
Attempting to send two ajax requests simultaneously. Not quite sure how to post at the same time.

**Comment by laurenfazah** [comment]
Is this for one post? Just make one AJAX request with one data object that you format as you'd need to from multiple form fields.

**Comment by Jcornmanhomonoff** [comment]
They're going to different URLs

**Comment by laurenfazah** [comment]
Are there two separate models? What is it that you're trying to post?

**Comment by gaand** [comment]
You probably don't want to send "simultaneous" AJAX requests.  The "asynchronous" part mean you can't know which will complete first.

**Comment by Jcornmanhomonoff** [comment]
Had to create another controller for ingredients and make a separate AJAX request

**Comment by gaand** [comment]
@Jcornmanhomonoff This could be handled in the drinks controller by passing along a list of ingredients when creating a drink.  Happy to talk about that if you want/have time.  Please reopen this issue in that case.
