### ISSUE TITLE
testing controllers 

### ISSUE THREAD

**Issue by leahphuong** [ga-wdi-boston/full-stack-project#27]
I'm having issues with testing my controllers on Postman

**Comment by jrhorn424** [comment]
What issue? Have you tried using `curl` instead? Can you take a screenshot? What url are you hitting? What route is used? What controller and action? What model?

**Comment by GA-MEB** [comment]
Empty params hash is failing strong params method during login.

**Comment by GA-MEB** [comment]
Issue with Postman - header was set up incorrectly.
