### ISSUE TITLE
Not entering either a success or failure handler for an ajax call

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/full-stack-project#275]
My get meal success handler automatically tries to automatically get the foods from the meal and display them on the screen. Here is the success handler for get meal:

``` bash
const getMealByIdSuccess = (data) => {
  currentMeal.local = data;
  console.log(data);
  getFoodItems.retrieveFood(data);
  console.log(currentMeal.local);
  console.log(data.meal);
};

```

This handler calls retrieveFood(), which is this:

``` bash
function retrieveFood(data) {
  debugger;
  for (let i = 0; i < data.meal.meal_items.length; i++) {
    api.getFoodById(ui.getFoodByIdSuccess, ui.getFoodByIdFailure, data.meal.meal_items[i].id);
  }
};
```

I've put debuggers in this statement, and I get into the for loop on both sides of the ajax call. I've also put debuggers in both the success handler and failure handler for getFoodById and never seem to enter them. No error shows in the console, the loop just ends without incident.

**Comment by laurenfazah** [comment]
It _could_ be that you're calling a function within a for loop. Might want to use `forEach` for this. Do you have linter errors from what you've got?

**Comment by louarnos** [comment]
just one for the debugger... I'll try a for each

**Comment by louarnos** [comment]
Ok, so the for each is getting me inside the handler... I'm wondering how I refer to the current item I'm iterating over... so I can replace data.meal.meal_items[i].id with something... I tried this.id

**Comment by RealWeeks** [comment]
have you googled this?  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

**Comment by laurenfazah** [comment]
`forEach` accepts `this` as a second argument

**Comment by louarnos** [comment]
Ive been reading through the documentation

**Comment by laurenfazah** [comment]
Look at how 

```
  array.forEach(function(entry) {
    this.sum += entry;
    ++this.count;
  }, this);
```

is passing `this` in (from the docs).

**Comment by louarnos** [comment]
if I'm understanding this correctly... do I need to add a prototype to my call back? like this is doing?

```
Counter.prototype.add = function(array) {
  array.forEach(function(entry) {
    this.sum += entry;
    ++this.count;
  }, this);
  // ^---- Note
```

**Comment by RealWeeks** [comment]
Nice job reading forward but no. I want to guide you further but the answer to this is a very googleable search away. Try some things first and if you can't figure it after a bit ask again.

**Comment by louarnos** [comment]
lol

**Comment by louarnos** [comment]
[This](http://stackoverflow.com/questions/25997290/js-foreach-item-in-array-current-value) is explained it. I didn't understand that you had to declare an anonymous function pass it the variables to make use of the three parameters.
