### ISSUE TITLE
Putting GET request content into a Bootstrap modal body

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/full-stack-project#276]
I have a button, "See My Questions", that display's the questions a user has submitted.  See My Questions opens a modal.  I would like the contents of the GET request to display in the modal's body, but I can't find anything on the internet that doesn't involve working with views.

**Comment by susandaiute** [comment]
This is not working:

```
const indexSuccess = function (data) {
  console.log(data);
  $(".getModalBody").append("<p>You Have Submitted: " + data.questions + "</p>");
};

```

**Comment by laurenfazah** [comment]
What is console.log(data) giving you? This could be a great place to use a handlebars partial to append if `data.questions` is an array of questions.

**Comment by susandaiute** [comment]
It's not console logging anything.  The rails server is giving me a 200 OK, but the browser console indicates that neither indexSuccess or failure are firing.

```
const index = (success, fail) => {
  $.ajax({
      method:'GET',
      url: app.api + '/questions',
      headers: {
        Authorization: 'Token token=' + app.user.token,
      }
  })
  .done(indexSuccess)
  .fail(fail);
};
```

**Comment by susandaiute** [comment]
I see a problem, I'm passing it success, not indexSuccess.

**Comment by susandaiute** [comment]
Everything is working now, I'm getting the right JSON back.  Back to my original question of getting it to display in the modal haha.  I'll look into Handlebars.

**Comment by susandaiute** [comment]
Yeah, not a fan of Handlebars.  Is there anyway to avoid it?

**Comment by laurenfazah** [comment]
Not unless you want to hardcode HTML for every new question you get uploaded to your database :)

Give it a try creating a simple partial for handlebars where you pass `data.questions` to the partial and have an `{{#each}}` loop in the partial listing out the questions. Should feel very similar to what we did in class during the handlebars lesson.

**Comment by susandaiute** [comment]
I have:

```
const displayQuestions = function(questions){
  let questionListingTemplate = require('./templates/question-listing.handlebars');
    $('.content').append(questionListingTemplate({
      questions: questions
    }));
};
```

```
const index = (indexSuccess, fail) => {
  $.ajax({
      method:'GET',
      url: app.api + '/questions',
      headers: {
        Authorization: 'Token token=' + app.user.token,
      }
  })
  .done(indexSuccess, displayQuestions)
  .fail(fail);
};

```

```
<!-- Begin Get Questions Modal -->
  <div class="modal fade get questions" id="getQuestions" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">My Questions</h4>
        </div>
        <div class="modal-body" id="getModalBody">
            <div class="content"></div>


            <button type="button" id="deleteButton" class="btn btn-danger">Delete All</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <!-- End Get Questions Modal -->
```

I'm not sure how to put displayQuestions into the click event other than:

```
$('#getQuestionsLink').on('click', function (event) {
  event.preventDefault();
  displayQuestions();
  authApi.index(authUi.indexSuccess, authUi.failure);
});
```

 but that returns that displayQuestions is not a function.  I  got this error before, and what I thought was a function was really an object.  I only needed the id of that, so I  was able to do object.id, but I'm not sure how to apply that here.

**Comment by susandaiute** [comment]
and the template is:

```
<div class = 'all-questions'>
 {{#each questions}}
 <div>
   <p>Question: {{this.title}}</p>
   <p>Answer 1: {{this.answer1}}</p>
   <p>Answer 2: {{this.answer2}}</p>
   <p>Answer 3: {{this.answer3}}</p>
 </div>
 {{/each}}
</div>
```

**Comment by laurenfazah** [comment]
Try appending the partial from your success function for this GET request

**Comment by susandaiute** [comment]
I...don't know what that means

**Comment by laurenfazah** [comment]
I'm coming to help

**Comment by susandaiute** [comment]
Summary: I had to call displayQuestions inside the indexSuccess function and pass it "data."
