### ISSUE TITLE
can't POST in curl

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/full-stack-project#28]
Just re-migrated "sites". 
I can do Site.new (with all attributes) in rails console. The table looks fine in rails db.

But when I try to create a new site in curl, I can't, and I get this error: 

ActionDispatch::ParamsParser::ParseError

Here's what I'm typing into the console, after logging in the user who will author the "site" and taking that token:

curl --request POST --header "Authorization: Token token=2f6ec10093655ee88450e15cba76de36" --header "Content-Type: application/json" -d '{
  "site": {
    "name":"Stairs",
    "description":"Short-range people watching",
    "category":"Seating",
    "address":"1801 Mass Ave",
    "neighborhood":"Porter Square",
    "scale:"medium",
    "coverage":"minimal",
    "busy":"somewhat"
  }
}'  http://localhost:3000/sites

Where else should I look for issues?

**Comment by gaand** [comment]
Trying to understand the parsing error.

**Comment by gaand** [comment]
Typo:  `"scale:` should be `"scale":`

**Comment by sarabrentmccoy** [comment]
Thanks.

**Comment by sarabrentmccoy** [comment]
Still having issues with an unknown attribute error user_id and I've tried a handful of things.

**Comment by sarabrentmccoy** [comment]
meaning, the error is "unknown attribute error"

**Comment by gaand** [comment]
It's about migrations or models and the whole class_name: thing.  Please meet me in classroom 1.

**Comment by sarabrentmccoy** [comment]
The issue was 

t.references :users 
where there should've been

t.references :user
