### ISSUE TITLE
Deploy Issue: Internal Server Error  Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml`

### ISSUE THREAD

**Issue by rdelvallej32** [ga-wdi-boston/full-stack-project#282]
Hi,

So, I referenced Phil's issue from Friday, but it wasn't clear as to how the issue was resolved. So far, I created a secret token and secret key base by running the command:

``` bash
 heroku config:set secret_token=<I included my rake secret token here> secret_key_base=<Included my rake secret token here>

```

It responded with a completion, but when I went to run heroku open, it gave me the same issue. Any ideas?

**Comment by gaand** [comment]
Please see #249.

**Comment by rdelvallej32** [comment]
I ran git commit config/secrets.yml -f, then the heroku config command to set the token and key base, but I'm still receiving the internal error after restarting heroku and opening it again

**Comment by RealWeeks** [comment]
going to assign this to explain

**Comment by rdelvallej32** [comment]
Solution: Needed to comment out in gitignore the config/secrets.yml file, then push to github and heroku. Then follow the heroku command line to generate the secret token( heroku config:set SECRET_TOKEN=$(rake secret) and secret key base token ( heroku config:set SECRET_KEY_BASE=$(rake secret)

**Comment by jrhorn424** [comment]
@rdelvallej32 had the correct fix at the time. For current cohorts, it may be an insufficient fix.

This should be fixed in the near future by ga-wdi-boston/orientation#166
