### ISSUE TITLE
deleteSuccess is firing, but DELETE request is not showing up in the rails server

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/full-stack-project#283]
I want to delete all of the questions a user has submitted.  I have a destroy_all method to do this.  The deleteSuccess function on the ajax call fires (as evidenced by a console log in the browser console), but there's no evidence of a delete happening in the rails server.

```
const deleteQuestions = (deleteSuccess, failure) => {
  $.ajax({
    method: 'DELETE',
    url: app.api + '/questions/' + app.user.id,
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  }).done(deleteSuccess)
  .fail(failure);
};

```

```
const deleteSuccess = () => {
  console.log('delete success');
  console.log(app);
};
```

```
$('#deleteButton').on('click', function (event) {
  event.preventDefault();
  authApi.index(authUi.deleteSuccess, authUi.failure);
});
```

```
class QuestionsController < ProtectedController
  before_action :set_question, only: [:show, :update, :destroy]
  before_action :set_question2, only: [:destroy_all]
```

```
  def destroy_all
    @question.destroy
    head :no_content
  end
```

```
  delete '/questions' => 'questions#destroy_all'
```

**Comment by susandaiute** [comment]
Also, when I go to check after the delete, the user's questions are all still there.

**Comment by susandaiute** [comment]
forgot to paste:

```
  def set_question2
    @question = current_user.questions
  end
```

**Comment by gaand** [comment]
Have a close look at this line:

``` js
authApi.index(authUi.deleteSuccess, authUi.failure);
```

**Comment by susandaiute** [comment]
It should be `authApi.updateQuestions(authUi.deleteSuccess, authUi.failure);`
I corrected that but now, upon trying to get the questions (a modal that pops up and then has the option to delete all questions) i'm getting `NoMethodError (undefined method `text' for #<Question:0x007fae8c69e640>):
  app/controllers/questions_controller.rb:11:in `index'`.  These errors are coming up since I created a questions serializer so that I could have id's for the questions in order to patch them.

```
class QuestionSerializer < ActiveModel::Serializer
  attributes :id, :text, :editable

  def editable
    scope == object.user
  end
end
```

**Comment by laurenfazah** [comment]
Is `text` an attribute of questions? It's looking for that and the error you're seeing is that it doesn't exist. If I remember correctly, you've got `subject`, `answer1`, `answer2` and `answer3` (or something close to that) as attributes. You can double check that in your `question_params` method in the QuestionsController.

**Comment by susandaiute** [comment]
I put those in and now when I go to get all of a user's submitted questions, it's returning the right object, but the handlebars display is no longer showing the variables.  Also, the delete request is now hitting the back end and getting a 404 error.

```
Started DELETE "/questions/12" for ::1 at 2016-05-02 22:10:40 -0400
Processing by QuestionsController#destroy as */*
  Parameters: {"id"=>"12"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "d7433fc39c76bd55956bda3b08946c55"]]
  Question Load (0.2ms)  SELECT  "questions".* FROM "questions" WHERE "questions"."user_id" = $1 AND "questions"."id" = $2 LIMIT 1  [["user_id", 12], ["id", 12]]
Completed 404 Not Found in 4ms (Views: 1.0ms | ActiveRecord: 0.4ms)
```

**Comment by laurenfazah** [comment]
What variables aren't the handlebars display showing? For what event?

And is this delete request you posted to delete a single question or all questions?

**Comment by gaand** [comment]
That probably means the question you're trying to delete wasn't created by the user associated with the token you're passing. So current_user doesn't own question 12.

**Comment by susandaiute** [comment]
The delete request is to delete all questions.

The handlebars won't display the any of the params: title, answer1, answer2, answer3

@gaand  I've only been working with one user so far who has created all of the questions.

**Comment by susandaiute** [comment]
Also, if you need to go to sleep, don't let me keep you up!!!!

**Comment by laurenfazah** [comment]
Just out of curiosity, is deleting all questions pertinent to the core functionality of your app? Are the other CRUD requirements for the project fulfilled? Depending on those, it might be worth timeboxing a delete all method before getting too tangled in it if other requirements are still hanging.

**Comment by laurenfazah** [comment]
Those are genuine, non-rhetorical questions :)

**Comment by susandaiute** [comment]
I have update left for CRUD actions and was going to use this to fulfill the delete requirement.  Do you think deleting one single question would be easier?  I think I had that earlier, but it wasn't showing up in the rails console.
I'm pretty well through update, just needs a bit more work tomorrow.

**Comment by laurenfazah** [comment]
Yeah, a one question delete is very straight-forward, and honestly, it looks like you've got your `destroy_all` method set up to delete only one question by ID, so you're not too far off by going down that route. Also, updating one question from there is almost a copy-paste

**Comment by susandaiute** [comment]
Awesome, I'll go back to that then.

**Comment by susandaiute** [comment]
I think I need to solve the handlebars problem, before I get back to working on Delete, otherwise, I can't see what I'm deleting.

**Comment by susandaiute** [comment]
Summary: We had to basically move everything related to delete into the ui file.  Oddly, it wouldn't reference functions in other files, possibly because of handlebars.
Result:

```
const displayQuestions = function(questions){
  let questionListingTemplate = require('./templates/question-listing.handlebars');
    $('.contentGet').append(questionListingTemplate({
      questions: questions
    }));
    const deleteQuestions = (deleteSuccess, failure, id) => {
      $.ajax({
        method: 'DELETE',
        url: app.api + '/questions/' + id,
        headers: {
          Authorization: 'Token token=' + app.user.token,
        },
      }).done(deleteSuccess)
      .fail(failure);
    };

    //added deletebutton event handler, taken from ui. because of handlebars
    $('.deleteButton').on('click', function (event) {
      event.preventDefault();
      let buttonid = $(this).data('id');
      deleteQuestions(deleteSuccess, failure, buttonid);
    });
};
```
