### ISSUE TITLE
PATCH trouble

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/full-stack-project#284]
Having trouble with my PATCH. I placed in a debugger and by the point the debugger hits, id is still undefined. Any help?

``` js
 $('#edit-drink').on('submit', function (event){
    event.preventDefault();
    let data = getFormFields(this);
    let id = $('.open-edit-drink').attr("data-current-drink-id"); //stores current drink id
    debugger
    console.log(data);
    // data.drinks.user_id = authUi.currentUser.id;
    authApi.editDrank(authUi.editDrankSuccess, authUi.failure, data);
    authApi.editIngredient(authUi.editIngredientSuccess, authUi.failure, data);
  });
```

**Comment by gaand** [comment]
I think you want to use `.data('current-drink-id');` but I dont know if that's the problem.

**Comment by laurenfazah** [comment]
I'll self assign to walk through what we spoke about this morning

**Comment by Jcornmanhomonoff** [comment]
Added click handler to container and am now trying to restrict it to events for buttons only.

**Comment by gaand** [comment]
@Jcornmanhomonoff 

``` js
$('.content').on('click', 'button', function(event) {
...
});
```

Will restrict to just button clicks in the content div (from http://api.jquery.com/on/).
