### ISSUE TITLE
Heroku routes

### ISSUE THREAD

**Issue by MichaelB167** [ga-wdi-boston/full-stack-project#285]
I decided to change the name of my heroku app not remembering that my routes would need to change as well.  Is it possible to roll back to the initially provided name?  If not can I use the same commands that I'd use to change git remotes and will I need to go through merging etc again?  What I did: 

```
Renaming fast-mountain-32612 to ClimbBuddy... !!!
 ▸    Name must start with a letter and can only contain lowercase letters,
 ▸    numbers, and dashes.
~/wdi/projects/climb-buddy-app/climb-buddy-back-end (master)$ climb-buddy
-bash: climb-buddy: command not found
~/wdi/projects/climb-buddy-app/climb-buddy-back-end (master)$ heroku apps:rename climb-buddy
Renaming fast-mountain-32612 to climb-buddy... done
https://climb-buddy.herokuapp.com/ | https://git.heroku.com/climb-buddy.git
Git remote heroku updated
 ▸    Don't forget to update git remotes for all other local checkouts of the app.
~/wdi/projects/climb-buddy-app/climb-buddy-back-end (master)$ heroku restart
Restarting dynos on ⬢ climb-buddy... done
~/wdi/projects/climb-buddy-app/climb-buddy-back-end (master)$ heroku open
~/wdi/projects/climb-buddy-app/climb-buddy-back-end (master)$ heroku open
~/wdi/projects/climb-buddy-app/climb-buddy-back-end (master)$ heroku open
~/wdi/projects/climb-buddy-app/climb-buddy-back-end (master)$ git remote -v
heroku  https://git.heroku.com/climb-buddy.git (fetch)
heroku  https://git.heroku.com/climb-buddy.git (push)
origin  git@github.com:MichaelB167/climb-buddy-back-end.git (fetch)
origin  git@github.com:MichaelB167/climb-buddy-back-end.git (push)
```

**Comment by RealWeeks** [comment]
the only thing that changes when you change the name is the beginning of the api url.  This should be an easy change on your front end.  I'm assuming you have some api object that points to "localhost:8080" or something.  Just update that name.

**Comment by MichaelB167** [comment]
Sorry I should've specified that the back end wasn't loading with 'heroku open' but thanks to heroku magic it seems to be now, checking functionality with the front end now.

**Comment by MichaelB167** [comment]
Working now, not sure why it wasn't loading before as I haven't changed anything but I'll take it.
