### ISSUE TITLE
Handlebars database sorting

### ISSUE THREAD

**Issue by sjf125** [ga-wdi-boston/full-stack-project#288]
When I edit a comment, it's position int he comment thread moves to the bottom, suggesting that handlebars is reading the database in order of updated-date.  Is there a way I can have handlebars/the database output in order of the original creation date/time?  The only things I've been able to find online so far invlove custom handlebars helpers, which we can't do.

**Comment by RealWeeks** [comment]
Is date created a column in your table? If you scaffolded it probably is.

**Comment by sjf125** [comment]
yeah, just as part of the activerecord scaffolding

**Comment by RealWeeks** [comment]
through your serializer expose that attribute and sort by created at on your front end... or your backend

**Comment by sjf125** [comment]
Thanks, working on something else right now, will let you know fi I can get it.

**Comment by sjf125** [comment]
So I would add created_at to the attributes of the comment serializer?  Would I have to sort via some JS, or is there a way to do it within handlebars or the backend?

**Comment by sjf125** [comment]
I think I got it, working on it now

**Comment by sjf125** [comment]
Nope, still need help - the ids are keys in objects in the array of comments, so I'm not sure how to sort by them.

**Comment by laurenfazah** [comment]
Are you getting `created_at` back with your comments? I'd suggest sorting them on that with javascript before sending them to your handlebars template.

**Comment by sjf125** [comment]
I am, but I could also acheive the same effect with the IDs since they are in order as well - I just don't know how to sort by them when the IDs and created_at attrs are stored in objects:

``` json
"comments": [
{
"id": 3,
"content": "Could do without the seal.",
"created_at": "2016-05-02T21:00:18.523Z",
"updated_at": "2016-05-02T21:00:18.523Z",
"user": {},
"flag": {}
},
{
"id": 4,
"content": "Yeah I'm the same user and I totally agree with the first comment.",
"created_at": "2016-05-02T22:01:54.634Z",
"updated_at": "2016-05-02T22:01:54.634Z",
"user": {},
"flag": {}
},
]
```

**Comment by RealWeeks** [comment]
I think you do know how to do this, and just need to think on it a bit more.  A google search here will yield some helpful code examples:

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=javascript+sort+id+in+object

**Comment by RealWeeks** [comment]
@sjf125 how is this going?

**Comment by sjf125** [comment]
Yeah I'm probably not going to implement comment sorting - if I have any extra time I'd rather try to implement a search instead.
