### ISSUE TITLE
Showing result of patch and delete

### ISSUE THREAD

**Issue by MichaelB167** [ga-wdi-boston/full-stack-project#293]
I have handlers for patch and delete (for climbs) that are working and added get requests to each so the new list of climbs should be displayed on a submit event.  Seemingly because Javascript is asynchronous, the get request in each function is firing first followed by the patch/delete.  I think this is the case because if I patch/delete twice, the first climb I changed updates or disappears depending on the action.  Reading jquery documentation suggests that .when and .then can be used in tandem to in effect make the function asynchronous but am I going about using them the right way?

```
$('.delete-climb-btn').on('click', function (event) {
      //get data, prevents default
      event.preventDefault();
      let id = $(this).attr("data-climb-id");
      $.when(authClimbApi.deleteClimb(authClimbUi.deleteClimbSuccess, authUi.failure, id)).then(authClimbApi.getClimbs(authClimbUi.getClimbsSuccess, authUi.failure));
  });
```

**Comment by MichaelB167** [comment]
just realized you have to pass .then a function

**Comment by MichaelB167** [comment]
still doing something wrong

```
$('.delete-climb-btn').on('click', function (event) {
      //get data, prevents default
      event.preventDefault();
      let id = $(this).attr("data-climb-id");
      $.when(authClimbApi.deleteClimb(authClimbUi.deleteClimbSuccess, authUi.failure, id)).then(function() {
        authClimbApi.getClimbs(authClimbUi.getClimbsSuccess, authUi.failure);});
  });
```

**Comment by laurenfazah** [comment]
Hey @MichaelB167 - try to take advantage of your success functions with update or delete and try updating your dom there

**Comment by MichaelB167** [comment]
Just got it doing that, TY Roberto and Lauren.
