### ISSUE TITLE
Project Requirements Check?

### ISSUE THREAD

**Issue by cuprous** [ga-wdi-boston/full-stack-project#295]
Hello,

I'd like to have someone take a look at the current state of my project to let me know if the requirements have been met, especially with respect to notifying the user that something has happened when an update action occurs.

Thanks.

**Comment by laurenfazah** [comment]
I can look over this with you.

**Comment by cuprous** [comment]
This is for anyone else that reads this.

Regarding notifying the user that something has happened without having to refresh:

I'm doing an update action to update the quantity of an entry in a join table. If the action is successful, a notification popups up that X has been updated to Y. If the ajax fails, a message saying something went wrong is displayed. This notification was enough to satisfy the requirement of letting the user know that the update has occurred without having to look in the developer tools.
