### ISSUE TITLE
I can authenticate a user, yet cannot post a new bike to my database

### ISSUE THREAD

**Issue by resource11** [ga-wdi-boston/full-stack-project#3]
So... I can successfully register and login a user through the backend _and_ the frontend through AJAX requests. I can successfully do GET requests to the backend and receive data to use in my frontend (i.e.,  populate a div with data collected from the backend).

I can successfully create a new bike from the backend using pry and using Postman using authentication. 

However. I cannot successfully create a _new_ bike POST from the front end. 

The error message I am receiving when I attempt to do an ajax POST request is:

POST http://localhost:3000/bikes 
localhost/:1 XMLHttpRequest cannot load http://localhost:3000/bikes. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access. The response had HTTP status code 500.

see attached image

<img width="1134" alt="screen shot 2015-11-10 at 9 07 11 am" src="https://cloud.githubusercontent.com/assets/11621935/11064327/90683c4a-878a-11e5-8641-8436c9b4100c.png">

I have googled, I have asked classmates, I've looked at my Rails backend to see if there's an issue.  I'm not sure if my bikes_controller.rb file is not set up correctly for creating a new bike.

**Comment by gaand** [comment]
What is the error that rails shows?  This will be in the terminal you ran `rails s`.

**Comment by resource11** [comment]
<img width="1420" alt="screen shot 2015-11-10 at 9 43 23 am" src="https://cloud.githubusercontent.com/assets/11621935/11065135/9dda2910-878f-11e5-9eaa-233825a67e58.png">

**Comment by gaand** [comment]
What does your create action look like for bikes? I.e. please post the code here.

**Comment by resource11** [comment]
# POST /bikes
  def create
    @bike = bikes.new(bike_params)
    @bike.save

```
if @bike.save
  render json: @bike, status: :created, location: @bike
else
  render json: @bike.errors, status: :unprocessable_entity
end
```

  end

**Comment by resource11** [comment]
def bike_params
    params.require(:bike).permit(:title, :description, :poster)
  end

  private :set_bike, :bike_params

**Comment by gaand** [comment]
How about the front end code?

**Comment by resource11** [comment]
<img width="795" alt="screen shot 2015-11-10 at 10 18 33 am" src="https://cloud.githubusercontent.com/assets/11621935/11066056/87e13acc-8794-11e5-8e9a-3472688be857.png">
<img width="860" alt="screen shot 2015-11-10 at 10 17 44 am" src="https://cloud.githubusercontent.com/assets/11621935/11066057/87e15868-8794-11e5-925e-3587a07cc385.png">
<img width="584" alt="screen shot 2015-11-10 at 10 18 03 am" src="https://cloud.githubusercontent.com/assets/11621935/11066058/87e51b10-8794-11e5-8b73-c671a7728fb5.png">
<img width="517" alt="screen shot 2015-11-10 at 10 18 52 am" src="https://cloud.githubusercontent.com/assets/11621935/11066059/87e506de-8794-11e5-8d74-aa0fe65c94dc.png">

**Comment by resource11** [comment]
<img width="860" alt="screen shot 2015-11-10 at 10 17 44 am" src="https://cloud.githubusercontent.com/assets/11621935/11066080/aa6f54e8-8794-11e5-8f90-80791a32b166.png">

<img width="584" alt="screen shot 2015-11-10 at 10 18 03 am" src="https://cloud.githubusercontent.com/assets/11621935/11066089/b3046ee0-8794-11e5-9521-c8733df7a0c5.png">

<img width="795" alt="screen shot 2015-11-10 at 10 18 33 am" src="https://cloud.githubusercontent.com/assets/11621935/11066093/b65967da-8794-11e5-9858-200f3e3d159e.png">

<img width="517" alt="screen shot 2015-11-10 at 10 18 52 am" src="https://cloud.githubusercontent.com/assets/11621935/11066100/b90e2e48-8794-11e5-8a44-9a131fc00237.png">

**Comment by resource11** [comment]
Solved! Needed to add a parameter to my ssme_api.createBike function and the createBikeCb function to pass in the data I was requesting. Also, made sure my AJAX request was actually stringifying the data I needed. Tests pass and I can now (finally) create a new bike from the front end. 

Thanks, Antony!
