### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by gotwilk890** [ga-wdi-boston/full-stack-project#30]
This is a 2 for one. Scott and I are having problems with a POST curl command

`curl --request POST --header "Authorization: Token token=be249dc0231396806f24c953cafae03a" --header "Content-Type: application/json" -d '{
  “guide": {
    “name”:"English"
   }
}'  http://localhost:3000/guides`

getting a parsing error and weve spent a good hour looking up whats wrong

`def create
    guide = current_user.guides.create(guide_params)
    if guide.save
      render json: guide, status: :created
    else
      render json: guide.error, status: :unprocessable_entity
    end`

`def guide_params
    params.require(:guide).permit(:name)
  end`

**Comment by gaand** [comment]
Please post the error message (preferably as text).

**Comment by gotwilk890** [comment]
DO NOT INCLUDE AUTHENTICATION IN MODELS THAT DON"T NEED IT.

lesson learned

**Comment by jrhorn424** [comment]
Heh :+1: 🍻
