### ISSUE TITLE
Fill form with table data not working

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/full-stack-project#301]
For some reason I can't quite get this feature working. I'm trying to automatically fill my edit input fields with the existing data but it's not happening. Every other part of the associated features seems to be working, the edit goes through fine but a blank input will delete the existing data.

``` html
  <label for="rescueTitle">
                      Edit Rescue Title
                    </label>
                    <input placeholder="Great tutorial on solving my Javascript problems" type="text" name="rescue[title]" class="form-control" id="inputRescueTitle">
                  </div>
                  <div class="form-group">

                    <label for="inputRescueLink">
                      Edit Rescue Link
                    </label>
                    <input  placeholder="www.solvemyjsproblems.net"class="form-control" type="text" name="rescue[url]"id="inputRescueLink">
                  </div>
                  <div class="form-group">

                    <label for="inputTags">
                      Edit Rescue Tags
                    </label>
                    <input  placeholder="problems, all, tutorial, cheatsheet, js, javascript" type="text" name="rescue[tag]" class="form-control" id="inputRescueTags">
                  </div>
```

``` js
$('#inputRescueTitle').val($(this).find('.rescues-title').text());
      $('#inputRescueLink').val($(this).find('.rescues-url').text());
      $('#inputRescueTags').val($(this).find('.rescues-tags').text());
      $('#edit-rescue-modal').modal('show');
```

**Comment by RealWeeks** [comment]
what do you mean by this "the edit goes through fine but a blank input will delete the existing data"

**Comment by RealWeeks** [comment]
Also what are you trying to do with that jquery?

**Comment by BenGitsCode** [comment]
so the i can edit the information but what I'm trying to do with the jquery is called on click of the edit modal, and fills the edit fields with the existing information. If I update title it will update title correctly, but also delete url and tags.

**Comment by laurenfazah** [comment]
Want to come to the dugout and I'll work through it with you?

**Comment by BenGitsCode** [comment]
on my way!

**Comment by laurenfazah** [comment]
Made some progress with setting up data attributes to pass correct IDs around, but event bubbling with the handlebars templates has complicated things.

**Comment by BenGitsCode** [comment]
@gaand are you available to take a look at this after announcements? Lauren thinks you'll be able to find the fix fast enough to make us both feel silly for trying this long.

**Comment by RealWeeks** [comment]
let me take a look

**Comment by RealWeeks** [comment]
MIC DROP. @Benjamski please write what we did to resolve the issue.

**Comment by BenGitsCode** [comment]
I'll do you one better @J-Weeks here's the commit showing the changes in my api.js file 

https://github.com/Benjamski/DevRescue-front-end/commit/546ab174f920482ec4123980109a89db88b03214
