### ISSUE TITLE
variable returns undefined after setting storyId

### ISSUE THREAD

**Issue by V4Vince** [ga-wdi-boston/full-stack-project#302]
I'm trying to set the clicked story's ID to a variable in a different file that's linked. But whenever I call the variable, it comes back as undefined. 

This finds the id of the clicked panel (which is set via js to be the story's Object ID) and sets it to `storyId` variable in userStatus file. 

``` js
$('.panel panel-title panel-default').on('click', function(event){
    event.preventDefault();
    userStatus.storyId = parseInt($(this).find("id"));
  });
```

I then call the variable `storyId` from the userStatus file (called storyData here) as an endpoint for the DELETE Ajax request. 

``` js
const deleteStory = (success, failure) => {
  $.ajax({
    method: 'DELETE',
    url: appURL.link + '/stories/' + storyData.storyId,
    headers: {
      Authorization: 'Token token=' + appURL.user.token,
    },
  }).done(success)
    .fail(failure);
};
```

It throws an error on the rails console as 404 id undefined.

**Comment by RealWeeks** [comment]
what is the value of storyId after deleteStory but before the ajax call

**Comment by GA-MEB** [comment]
@V4Vince 
To rephrase Jason's point, you should test the value of `storyData` between the start of the `deleteStory` function and when the AJAX request is made -- it might not be what you expect.

**Comment by V4Vince** [comment]
The storyId there returns undefined. I'm unsure why because I am listening to the click on `.panel-title` which comes before the deleteStory function. So the `storyId` variable should be set right before I call the deleteFunction. 

`userStatus.storyId = parseInt($(this).find("id"));`` is my syntax incorrect? 

``` js
$('.panel-title').on('click', function(event){
    debugger;
    event.preventDefault();
    userStatus.storyId = parseInt($(this).find("id"));
  });
```

```
Object {isThereUser: true, storyId: undefined, storyToken: undefined, allStories: Object}
allStories
:
Object
stories
:
Array[36]
```

**Comment by RealWeeks** [comment]
put a debugger after `userStatus.storyId = parseInt($(this).find("id"));`  what is the value of userStatus.storyId?  This should answer your question, and hopefully lead you to find the right solution.  Paste the value

**Comment by V4Vince** [comment]
hmm, my debugger isnt being hit so it seems like my click isn't firing. I'm not sure why because I checked the element within the console and my classes are correct... 

<img width="956" alt="screen shot 2016-05-03 at 4 34 52 pm" src="https://cloud.githubusercontent.com/assets/17656924/14997527/1d7554c8-114d-11e6-9188-ad0a5ef4fe85.png">

**Comment by RealWeeks** [comment]
I'm guessing you're using handlebars? Do you register the clicks before the handlebars template is compiled?

**Comment by RealWeeks** [comment]
If this is the case you need to register the clicks for .panel-title after the handlebars template has been compiled and the DOM has settled.

**Comment by V4Vince** [comment]
I'm not using handlebars. I used js for-loop to populate the stories in their own divs

``` js
const populateTitles = (data) => {
  for (let i = 0; i < data.stories.length; i++) {
    let storyTitle = data.stories[i].title;
    let storyBody = data.stories[i].body;
    let storyId = data.stories[i].id;
    let div1 = $('<div/>', {
      id: storyId,
      "class": 'panel panel-title panel-default',
      "data-toggle": 'modal',
      "data-target": '#read-story-on-click',
      text: storyTitle
    });
    let div2 = $('<div/>', {
      "class": 'panel panel-body panel-default',
      // "data-toggle": 'modal',
      // "data-target": '#read-story-on-click',
      text: storyBody
    });
    $('.story-holder').append(div1, div2);
  }
};
```

**Comment by RealWeeks** [comment]
Same still applies. Did you register the clicks after you finished altering the dom?

**Comment by V4Vince** [comment]
How do I know when the DOM is finished being altered? 

I'm pretty sure that I am because the titles are loaded first, only then am I able to click on them. If the titles aren't loaded then the they wont even be visible or clickable

**Comment by RealWeeks** [comment]
They would be visible.

I thought the click wasn't firing? what do you mean by "clickable"

**Comment by V4Vince** [comment]
I gave the divs a modal target so when clicking on them it will open a modal. I also wrote a function to listen for the clicks because I want to grab the story's id (which is the object's ID) as well

**Comment by RDegnen** [comment]
ill assign to this

**Comment by V4Vince** [comment]
the `panel-title` click function has to be placed inside of the `populateTitles` function after the for-loop.
