### ISSUE TITLE
Bootstrap Glyphicons don't display on Github Pages

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/full-stack-project#306]
Some of the glyphicons are replaced with empty boxes and other random characters. They are all displaying slightly differently.

They worked fine on localhost, and I added the meta tag <meta name="viewport" content="width=device-width, initial-scale=1"> to the HEAD of my index.html. It didn't help.

Any ideas?

**Comment by RDegnen** [comment]
are you getting any errors in the console?

**Comment by soynog** [comment]
I'm getting some 304 responses to GET requests which I didn't get before.

**Comment by soynog** [comment]
That's 304 Not Modified. On my index calls.

**Comment by RDegnen** [comment]
did you run grunt build before you deployed to Github pages?

**Comment by soynog** [comment]
Yes.

**Comment by soynog** [comment]
Though after I ran grunt build

**Comment by soynog** [comment]
Matt fixed it! See Roberto's issue #307.
