### ISSUE TITLE
Strange Get Issue on GH Pages

### ISSUE THREAD

**Issue by rdelvallej32** [ga-wdi-boston/full-stack-project#307]
I am having an issue on my GH Pages after deploying it. It is giving me the following message:

rdelvallej32.github.io/:1 GET http://rdelvallej32.github.io/catch_up_frontend/448c34a56d699c29117adc64c43affeb.woff2 
rdelvallej32.github.io/:1 GET http://rdelvallej32.github.io/catch_up_frontend/fa2772327f55d8198301fdb8bcfc8158.woff 
rdelvallej32.github.io/:1 GET http://rdelvallej32.github.io/catch_up_frontend/e18bbf611f2a2e43afc071aa2f4e1512.ttf 

I am not sure what these are exactly

**Comment by RealWeeks** [comment]
did you run grunt build?

**Comment by rdelvallej32** [comment]
yes i ran grunt build before the push to gh-pages

**Comment by RealWeeks** [comment]
hmm let me take a look

**Comment by rdelvallej32** [comment]
Issue: Glyphicons didn't load.
Solution: Remove .woff, .ttf, .woff2, .eot, .svg from Gitignore file.
