### ISSUE TITLE
Can't get my create or update to work

### ISSUE THREAD

**Issue by leahphuong** [ga-wdi-boston/full-stack-project#31]
```
class ItemsController < ApplicationController
  #GET /items
  def index
    #show all iems
    @items = Collection.find_by_id(params[:collection_id]).items.all

    render json: @items
  end

  #GET /items/1
  def show
    #show a particular item
    @item = Collection.find_by_id(params[:collection_id]).items.find(params[:id])

    render json: @item
  end

  #POST /items
  def create
    @item = Collection.find_by_id(params[:collection_id]).items.new(item_params)

    if @item.save
      render json: @item, status: :created,
        location: @item
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  #PATCH /items/1
  def update
    if @item.update(item_params)
      head :no_content
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end


  #DELETE items/1
  def destroy
    @item.destroy

    head :no_content
  end

  def set_item
    #look up items owned by current user
    # @item = Collection.find_by_id(params[:collection_id]).items.find(params[:id])
    @item = current_user.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :photo_url, :description)
  end

  private :set_item, :item_params
end
```

I have items resources nested within collections resources. 
A collection has many items.
Item belongs_to collections relationship.

**Comment by GA-MEB** [comment]
Where does `:collection_id` come from? Is it in your params hash?

**Comment by GA-MEB** [comment]
Also, could you paste the output of running `rake routes`?

**Comment by leahphuong** [comment]
because I have this:
resources :collections, except: [:new, :edit] do
    resources :items, except: [:new, :edit]
  end

in routes

**Comment by GA-MEB** [comment]
Can you please run `rake routes` in the console and paste the output here?

**Comment by leahphuong** [comment]
Prefix Verb   URI Pattern                                     Controller#Action
        register POST   /register(.:format)                             auth#register
           login PATCH  /login(.:format)                                auth#login
                 DELETE /logout/:id(.:format)                           auth#logout
           users GET    /users(.:format)                                users#index
                 POST   /users(.:format)                                users#create
            user GET    /users/:id(.:format)                            users#show
                 PATCH  /users/:id(.:format)                            users#update
                 PUT    /users/:id(.:format)                            users#update
                 DELETE /users/:id(.:format)                            users#destroy
           books GET    /books(.:format)                                books#index
                 POST   /books(.:format)                                books#create
            book GET    /books/:id(.:format)                            books#show
                 PATCH  /books/:id(.:format)                            books#update
                 PUT    /books/:id(.:format)                            books#update
                 DELETE /books/:id(.:format)                            books#destroy
collection_items GET    /collections/:collection_id/items(.:format)     items#index
                 POST   /collections/:collection_id/items(.:format)     items#create
 collection_item GET    /collections/:collection_id/items/:id(.:format) items#show
                 PATCH  /collections/:collection_id/items/:id(.:format) items#update
                 PUT    /collections/:collection_id/items/:id(.:format) items#update
                 DELETE /collections/:collection_id/items/:id(.:format) items#destroy
     collections GET    /collections(.:format)                          collections#index
                 POST   /collections(.:format)                          collections#create
      collection GET    /collections/:id(.:format)                      collections#show
                 PATCH  /collections/:id(.:format)                      collections#update
                 PUT    /collections/:id(.:format)                      collections#update
                 DELETE /collections/:id(.:format)                      collections#destroy
        profiles GET    /profiles(.:format)                             profiles#index
                 POST   /profiles(.:format)                             profiles#create
         profile GET    /profiles/:id(.:format)                         profiles#show
                 PATCH  /profiles/:id(.:format)                         profiles#update
                 PUT    /profiles/:id(.:format)                         profiles#update
                 DELETE /profiles/:id(.:format)                         profiles#destroy

**Comment by leahphuong** [comment]
```
Prefix Verb   URI Pattern                                     Controller#Action
        register POST   /register(.:format)                             auth#register
           login PATCH  /login(.:format)                                auth#login
                 DELETE /logout/:id(.:format)                           auth#logout
           users GET    /users(.:format)                                users#index
                 POST   /users(.:format)                                users#create
            user GET    /users/:id(.:format)                            users#show
                 PATCH  /users/:id(.:format)                            users#update
                 PUT    /users/:id(.:format)                            users#update
                 DELETE /users/:id(.:format)                            users#destroy
           books GET    /books(.:format)                                books#index
                 POST   /books(.:format)                                books#create
            book GET    /books/:id(.:format)                            books#show
                 PATCH  /books/:id(.:format)                            books#update
                 PUT    /books/:id(.:format)                            books#update
                 DELETE /books/:id(.:format)                            books#destroy
collection_items GET    /collections/:collection_id/items(.:format)     items#index
                 POST   /collections/:collection_id/items(.:format)     items#create
 collection_item GET    /collections/:collection_id/items/:id(.:format) items#show
                 PATCH  /collections/:collection_id/items/:id(.:format) items#update
                 PUT    /collections/:collection_id/items/:id(.:format) items#update
                 DELETE /collections/:collection_id/items/:id(.:format) items#destroy
     collections GET    /collections(.:format)                          collections#index
                 POST   /collections(.:format)                          collections#create
      collection GET    /collections/:id(.:format)                      collections#show
                 PATCH  /collections/:id(.:format)                      collections#update
                 PUT    /collections/:id(.:format)                      collections#update
                 DELETE /collections/:id(.:format)                      collections#destroy
        profiles GET    /profiles(.:format)                             profiles#index
                 POST   /profiles(.:format)                             profiles#create
         profile GET    /profiles/:id(.:format)                         profiles#show
                 PATCH  /profiles/:id(.:format)                         profiles#update
                 PUT    /profiles/:id(.:format)                         profiles#update
                 DELETE /profiles/:id(.:format)                         profiles#destroy
```

**Comment by GA-MEB** [comment]
OK. Your routes look fine.

**Comment by GA-MEB** [comment]
I notice that in your controller, you invoke a method called `find_by_id`. I'm not sure that method exists.
In ActiveRecord, when you want to look something up by its ID, you just use `find`.

**Comment by leahphuong** [comment]
It worked when i tested with Postman though

**Comment by GA-MEB** [comment]
It did? If so, then the problem is probably in your front-end, rather than in Rails.

**Comment by MattB-GA-Boston** [comment]
Actually, hold on.

**Comment by leahphuong** [comment]
I meant only Index/Show worked in Postman, not Create or Update

**Comment by GA-MEB** [comment]
I see. In that case, try testing create and update in Postman. If it doesn't work, then the issue is in Rails.

[EDIT]
Actually, it does look like there's something wrong with your `update` method.

```
def update
    if @item.update(item_params)  # Where is the value of @item being set?
      head :no_content
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end
```

**Comment by leahphuong** [comment]
NoMethodError in ItemsController#create
undefined method `item_url' for #ItemsController:0x007fb3188ab330              

```
if @item.save
  render json: @item, status: :created,
    location: @item
else
  render json: @item.errors, status: :unprocessable_entity
```

**Comment by GA-MEB** [comment]
That might be coming from the `location: @item`. Try leaving that out and see if it works.

**Comment by leahphuong** [comment]
I fixed it!! Update worked now! 
def update
    @item = Collection.find_by_id(params[:collection_id]).items.find(params[:id])
    if @item.update(item_params)
      head :no_content
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

**Comment by leahphuong** [comment]
I still have problem with Create. 

It threw this "NoMethodError in ItemsController#create
undefined method `item_url' for #ItemsController:0x007fb3188ab330"

 error at me but the item was still added when I tried to do Index/Show.

**Comment by leahphuong** [comment]
Yup! That was it, the location: @item.
I took it off and it WORKED!! YAYY!!

Thank you so much!!
