### ISSUE TITLE
using seeds.rb undefined method `text' for #<Item:0x007fc6b74c0e70>

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/full-stack-project#312]
I try to use the seed file to get data in my tables. I get this error: 

undefined method `text' for #Item:0x007fc6b74c0e70

I ran bundle exec db:seed 

and my seeds.rb file looks like that:

![screen shot 2016-06-23 at 11 18 31 am](https://cloud.githubusercontent.com/assets/13932794/16308883/af3b872e-3934-11e6-86f8-9203b77e3e92.png)

I also insert data with INSERT INTO ( bla,bla) VALUES (bla, bla) taht worked fine. Is this data going to be there permanent?

**Comment by berziiii** [comment]
Issue with validation in Item model. trying to validate 'text'. If resolved, please close @esthercordova
