### ISSUE TITLE
404 error when making POST request to create user profile

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/full-stack-project#313]
When I make a POST request to create a new user profile, I get a 404 message.

My other CRUD works (the template that we were given).

**Comment by andreasantarl** [comment]
Here's what my server says:

Started POST "/profiles" for ::1 at 2016-06-23 14:31:07 -0400
Processing by ProfilesController#create as _/_
  Parameters: {"first_name"=>"s", "last_name"=>"s", "submit"=>"Create your profile"}
  Profile Load (0.1ms)  SELECT  "profiles".\* FROM "profiles" WHERE "profiles"."id" = $1 LIMIT 1  [["id", nil]]
Completed 404 Not Found in 5ms (Views: 1.1ms | ActiveRecord: 1.0ms)

**Comment by berziiii** [comment]
- make sure your server is running :)
- check your routes `bundle exec rake db:routes` to see what path the POST => /profiles.
- Check your profiles controller to see what params you're allowing through.
- What is "submit" for your params?

**Comment by andreasantarl** [comment]
- Server is running
- I've made sure that I'm going through the correct routes by checking the db:routes

-submit is an HTML button, click handler in my JS

**Comment by andreasantarl** [comment]
```
params.require(:profile).permit(:first_name, :last_name)
```

**Comment by berziiii** [comment]
well something else is getting passed into your request because the request sent had

`Parameters: {"first_name"=>"s", "last_name"=>"s", "submit"=>"Create your profile"}`

I'd suggest debugging what information is available at the ajax request for Create New Profile by console log or debugger.

**Comment by andreasantarl** [comment]
That's what I want to get passed into the request.  I'm really lost because the console says that the data passed is first_name, last_name, and submit.

**Comment by payne-chris-r** [comment]
You want `submit` to be passed in params?

**Comment by andreasantarl** [comment]
The getFormField method is passing an object.

**Comment by andreasantarl** [comment]
All of the other fieldsets for the forms are not having submit passes in params.

**Comment by andreasantarl** [comment]
I don't understand what the problem is at all.  Can I get some facetime with one of you?

**Comment by payne-chris-r** [comment]
ANDREA SANTARI... COME ONNNN DOWWWN!! https://www.youtube.com/watch?v=13tnjh3dZw4

**Comment by payne-chris-r** [comment]
@andreasantarl can you post our resolution and close this when you get a chance?

**Comment by andreasantarl** [comment]
FIXED!!! Chris, you're the most wonderful helper EVER!!!!

**Comment by shireen-bean** [comment]
@andreasantarl  @payne-chris-r  Hi there, can someone post the solution to this issue, please? Thanks.
