### ISSUE TITLE
receiving "411 length required" error when sending curl POST to create to my Matches Table

### ISSUE THREAD

**Issue by mattb5** [ga-wdi-boston/full-stack-project#314]
sending the following curl request :

curl --include --request POST http://localhost:3000/matches
--header "Content-Type: application/json"
--header "Authorization: Token token="BAhJIiU4ZjM1ODc1MmJhNmQ2MDExMWMxOTkyYThjYmI4Y2ZjYQY6BkVG--d53ae9456d4fa76804d462e57e39fbc531911087" \
-- data '{
     "matches": {
         "opponent": "hello there",
         "user_id": 1
     }
}'     

to try to create a new row in my Matches table. 

have successfully seeded my matches table, now trying to add new match data to it.  

receiving this error in my terminal upon sending the curl request:

HTTP/1.1 411 Length Required 
Content-Type: text/html; charset=ISO-8859-1
Server: WEBrick/1.3.1 (Ruby/2.3.0/2015-12-25)
Date: Thu, 23 Jun 2016 19:57:39 GMT
Content-Length: 303
Connection: close

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Length Required</TITLE></HEAD>
  <BODY>
    <H1>Length Required</H1>
    WEBrick::HTTPStatus::LengthRequired
    <HR>
    <ADDRESS>
     WEBrick/1.3.1 (Ruby/2.3.0/2015-12-25) at
     localhost:3000
    </ADDRESS>
  </BODY>
</HTML>

**Comment by berziiii** [comment]
do you have a space after `--` and before `data`?

**Comment by berziiii** [comment]
make sure its `--data`

**Comment by mattb5** [comment]
fixed it but still getting same error

**Comment by mattb5** [comment]
this is returned in my rails server terminal when sending the curl request: 

[2016-06-23 16:16:32] ERROR WEBrick::HTTPStatus::LengthRequired

**Comment by mattb5** [comment]
good news is i just got a get request to work with this curl request : 

curl "http://localhost:3000/matches" \
     --include \
     --request GET \
     --header "Authorization: Token token"="BAhJIiU4ZjM1ODc1MmJhNmQ2MDExMWMxOTkyYThjYmI4Y2ZjYQY6BkVG--d53ae9456d4fa76804d462e57e39fbc531911087" \

**Comment by berziiii** [comment]
It may have been a space or forgot a `\` in the curl request. They can be frustrating! If resolved. Please close :)

**Comment by mattb5** [comment]
still can't get my post to work...  although i can get all matches and a single matches with '...matches/1'
