### ISSUE TITLE
keep getting 404 request

### ISSUE THREAD

**Issue by tina513** [ga-wdi-boston/full-stack-project#315]
When I send data by ajax request, I keep getting 
![screen shot 2016-06-23 at 4 34 20 pm](https://cloud.githubusercontent.com/assets/19153756/16319219/48cdac16-3960-11e6-8421-0973adb51580.png)

**Comment by tina513** [comment]
I am posting flight data into my backend database, but I couldn't send it back. I have already set up everything on the backend and I added "headers: {   Authorization: 'Token token=' + app.user.token,} " into my ajax request.

**Comment by berziiii** [comment]
Please share your ajax script. What does the rails server say?

**Comment by tina513** [comment]
![screen shot 2016-06-23 at 4 42 19 pm](https://cloud.githubusercontent.com/assets/19153756/16319456/5f94d8a6-3961-11e6-96c1-b3f499a4af20.png)

**Comment by tina513** [comment]
![screen shot 2016-06-23 at 4 43 44 pm](https://cloud.githubusercontent.com/assets/19153756/16319490/89e19d1a-3961-11e6-80d5-11115bf1cea7.png)

**Comment by tina513** [comment]
But I actually add route for that method on my route.rb file

**Comment by berziiii** [comment]
run `bundle exec rake routes` and look for the POST to `/users`. Does it exist?

**Comment by tina513** [comment]
yes. i restart my server. and error message changed to this.
![screen shot 2016-06-23 at 4 54 07 pm](https://cloud.githubusercontent.com/assets/19153756/16319895/0fc6dca0-3963-11e6-80d0-a6b28aaa19dd.png)
