### ISSUE TITLE
Rspec error. The instance creation is failing - it can't find the foreign key even though it is there

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/full-stack-project#316]
Error:

```
  ActiveRecord::InvalidForeignKey:
    PG::ForeignKeyViolation: ERROR:  insert or update on table "players" violates foreign key constraint "fk_rails_8880a915a5"
    **DETAIL:  Key (team_id)=(1) is not present in table "teams".**
    : INSERT INTO "players" ("surname", "given_name", "email", "phone_number", "captain", "team_id", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"
```

Is it looking for a team_id instead of just the team(id)?

**Comment by MishaHerscu** [comment]
The code causing the problem I think is this:

RSpec.describe PlayersController do
  def player_params
    {
      surname: 'Herscu',
      given_name: 'Misha',
      email: 'mishaherscu@gmail.com',
      phone_number: '413-320-6636',
      captain: 'yes',
      team_id: 1,
      user_id: 1
    }
  end

  def player
    Player.first
  end

  before(:all) do
    Player.create!(player_params)
  end

  after(:all) do
    Player.delete_all
  end

**Comment by MishaHerscu** [comment]
Specifically, it is because I am using foreign keys and I think rails doesn't interpret it how I expect. 

I am having some success doing things like just "user" instead of "user_id"

**Comment by MishaHerscu** [comment]
just "id" as the key works for one of them, but with 2 foreign keys, you need to have another way, because the first assignment to "id" gets overwritten by the second.

**Comment by MishaHerscu** [comment]
In our examples, we don't have any foreign keys in the object_params for the tests. I need to see an example of how to do that I think.

**Comment by MishaHerscu** [comment]
Lindsey has run into the same issue, potentially other people have as well.

**Comment by MishaHerscu** [comment]
I finally got it to work by using empty strings for those, but it is weird, and I still don't know if it is right.

**Comment by MishaHerscu** [comment]
Ah..

  def player_params
    {
      surname: 'Herscu',
      given_name: 'Misha',
      email: 'mishaherscu@gmail.com',
      phone_number: '413-320-6636',
      captain: 'yes',
      team_id: Team.first.id,
      user_id: User.first.id
    }
  end

instead of

  def player_params
    {
      surname: 'Herscu',
      given_name: 'Misha',
      email: 'mishaherscu@gmail.com',
      phone_number: '413-320-6636',
      captain: 'yes',
      team_id: 1, 
      user_id: 1
    }
  end

because id is at like 94 now because it only increments. I haven't nuke_paved in a while.

**Comment by MishaHerscu** [comment]
I have the test passing, but I may have a misunderstanding about how this works. I think it would be good to spend a few minutes talking to someone about this and how I got it to work in case it is working for a bad reason, and so that I can understand.

**Comment by payne-chris-r** [comment]
Misha, from your slack messages it sounded like you resolved this, is that correct? If so, can you comment on your resolution and close?

**Comment by MishaHerscu** [comment]
I will close this one for now, the auth issue is more important I think, and this should work once the auth is working. If it doesn't, I'll reopen this.
