### ISSUE TITLE
understanding current_user and authentication

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/full-stack-project#317]
I have been trying different things and reading the class docs from the template and looking online. I think I need to talk to someone for a bit to really get how to use this though. Can we find a time to talk?

**Comment by payne-chris-r** [comment]
@MishaHerscu did you figure this out? It sounds like you and Lindsey had it going. Can you post anything that might help others with your issues and close this?

**Comment by MishaHerscu** [comment]
I haven't been working with this yet, I am working on other things. I'll reopen this if I have trouble once I get back to working on this.
