### ISSUE TITLE
Rspec instance variables / instantiating objects

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/full-stack-project#318]
I just need to clarify, within Rspec, are you creating and destroying actual records in the database, or is create! (and destroy) in Rspec just making example data that only exists during the run of Rspec?

**Comment by MishaHerscu** [comment]
I think it is creating a temporary object in the test environment database, is that right? If you can confirm / send a reference link, I'll close this

**Comment by payne-chris-r** [comment]
RSpec uses the Test Environment for rails as far as I know. It won't effect your Development db, but it should actually make requests that hit your db once you get into the modelling tests. So, if you want to see that data you'll need to look in the Test db. That's also why we do delete all when we're done with our test running...

**Comment by MishaHerscu** [comment]
thanks
