### ISSUE TITLE
Rethinking data structure

### ISSUE THREAD

**Issue by RoobScoobs** [ga-wdi-boston/full-stack-project#319]
Hey guys, 

I'm thinking I need to restructure the way I set up my data. Currently, I have one table titled Workouts that has a MANY - to - 1 relationship with Users (many workouts belong to a single User). But I'm seeing a different way that might be better suited to the workout program I want users to follow. 

<img width="516" alt="screen shot 2016-06-24 at 9 41 50 am" src="https://cloud.githubusercontent.com/assets/16338632/16339319/0603bd4a-39f0-11e6-9ed4-b0dc3110df47.png">

Since I would only have three different types of workouts (Speed, Endurance & Recovery) I would like to display only three objects containing a collection of users' data. I'm not sure how to go about making the change though.

**Comment by berziiii** [comment]
If you want a workout to have many users and a user to have many workouts, you would need a many-to-many with some join table.

**Comment by RoobScoobs** [comment]
So far I have four entities: Users, Speed, Endurance and Recovery. In order to set up the relationship between Users and the types of workouts, do I need to scaffold another entity named Workout and add references to Users, Speed, Endurance and Recovery?

**Comment by RoobScoobs** [comment]
I think I'm going to simplify it to a One-to-Many relationship. In this case, Users have many Runs.
