### ISSUE TITLE
Can't understand 'Access-Control-Allow-Origin' error in..

### ISSUE THREAD

**Issue by dhuddell** [ga-wdi-boston/full-stack-project#32]
A create Profile request. Am able to use postman to write to the URL but cannot use my API to write, keep reaching this error.

**Comment by GA-MEB** [comment]
Sounds like a CORS error, although it might not be. Sometimes other errors masquerade as CORS errors.

**Comment by GA-MEB** [comment]
What does it say in the Rails console when you get that error?

**Comment by dhuddell** [comment]
```

  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (11.7ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (6.3ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (2.0ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (115.6ms)

```

**Comment by GA-MEB** [comment]
`.erb` files are used in Rails views. If you're seeing this, it means that you may not have called `render` inside your controller action. By default, Rails will try to render a View after each action, unless _otherwise interrupted_ by either `render` or `head`.

**Comment by GA-MEB** [comment]
@gaand There's something going on with the auth setup here. Can I tap you in?

**Comment by dhuddell** [comment]
I found that I needed to alter my controller with the following code when trying to create a profile(has_one):

```
  def create
    @weather_pair = current_user.profile.weather_pairs.build(weather_pair_params)
```

 and the later a weather_pair(has_many):

```
def create
    @profile = current_user.build_profile(profile_params)
```

Thanks to Matt and Antony for the swift assessment.
