### ISSUE TITLE
Do you filter your relationship data client side or server side?

### ISSUE THREAD

**Issue by mattb5** [ga-wdi-boston/full-stack-project#321]
My curl get requests are returning ALL of my "Matches" (relationship table) for all users.   Even when I curl with the authentication token header it still returns ALL of the match history. 

I want to filter for just the current user history.  Should I do this server side or client side?

I think I should do it server side (reduce the amount of JSON needing to be sent to client).  Not sure how to filter it though...

**Comment by berziiii** [comment]
This is where you have to identify the current_user and have the Matches.all retrieve the User.matches

**Comment by mattb5** [comment]
Ok.  Thanks :)
