### ISSUE TITLE
issue with background picture

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/full-stack-project#322]
was the problem solved with the background picture? Is there anything I need to do in particular?

I remember Misha had that problem in the tictactoe project... I tried using scss but that doesnt work then I used a extra main.css file but that also doesnt work...
I googled and ask classmates.

**Comment by payne-chris-r** [comment]
Esther, take a look here: https://github.com/ga-wdi-boston/game-project/issues/169
It might have something to do with WebPack, but make sure you have the right file path first!

**Comment by esthercordova** [comment]
I did change line 53 of webpack.js like Misha recommended:

```
`  test: /\.(ttf|eot|svg|jpg|png)(\?v=[0-9]\.[0-9]\.[0-9])?$/,`
```

but that didnt fix my problem.

Moved img to root directory and called it from there. Works for now.

**Comment by tina513** [comment]
If you have different type of image file, don't forget to add it inside first (), like test: /.(ttf|eot|svg|jpeg|jpg|png)(\?v=[0-9].[0-9].[0-9])?$/,`;
