### ISSUE TITLE
Problem pulling row ID in db for PATCH request

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/full-stack-project#323]
Trying to update user profiles.  My DB needs to find the row ID for that profile to update, but I can't figure out how to do it (keeps coming back as undefined).  Do I need a GET request first?  If so, what would be the event handler to trigger that? 

const updateProfile = (data) => {
  data.user_id = app.user.id;

  console.log ("App User data", app);
  // data.id = app.profiles;
  console.log("UpdateProfile Ajax data  ", data);
  return $.ajax({
    url: app.host + '/profiles/' + app.user.id,
    method: "PATCH",
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: {
      'profile': data
    }
  });
};

**Comment by payne-chris-r** [comment]
I'm holding this issue thread hostage until you post a resolution to your other one and close it.

**Comment by andreasantarl** [comment]
I gave you what you wanted.

**Comment by payne-chris-r** [comment]
First of all, this looks a little sdrawkcab to me: data.user_id = app.user.id;

**Comment by payne-chris-r** [comment]
(backwards)

**Comment by payne-chris-r** [comment]
You shouldn't need to do another GET. You should store current_user which will have the ID you need.

**Comment by andreasantarl** [comment]
It's not the user ID that I need, though.  It's the ID row in the profiles DB (foreign key is the user ID).

**Comment by andreasantarl** [comment]
Do you have two minutes for a face-to-face?

**Comment by payne-chris-r** [comment]
Yeah. Whe' dey at doe?

**Comment by andreasantarl** [comment]
2A

**Comment by payne-chris-r** [comment]
I just messaged you on slack, but come on down.

**Comment by andreasantarl** [comment]
Still not working.  Thoughts?  I can't figure it out.

**Comment by payne-chris-r** [comment]
Come back home young padawan.

**Comment by berziiii** [comment]
@andreasantarl CLOSE THE ISSUE! :)
