### ISSUE TITLE
Authentication in RSpec Testing

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/full-stack-project#324]
I think authentication is causing failures in all my tests because there is no user. I think the solution is to create and sign in a user in each of those tests, and submit the token for that session.

However, '/sign-in' is only an action on the user controller so it seems to be having a route issue.

I get this error:

GamesController POST new game is successful
     Failure/Error: post '/sign-in', { credentials: games_user_params }, format: :json

```
 RuntimeError:
   @routes is nil: make sure you set it in your test's setup method.
 # ./spec/controllers/games_spec.rb:22:in `block (2 levels) in <top (required)>'
```

Is the right solution something like what they did here?
http://stackoverflow.com/questions/10121835/how-do-i-simulate-a-login-with-rspec

**Comment by MishaHerscu** [comment]
This is still outstanding for me. I am hoping Jeff might have some time to look at it.

**Comment by jrhorn424** [comment]
@acobrelo Was this addressed? I'm sorry we didn't get a chance to address this yet in person. You may leave it open if you wish, but it will be closed by someone else in the next couple of weeks, when the next cohort starts this project.

**Comment by acobrelo** [comment]
@jrhorn424 I think you tagged me in the wrong thing, this is Misha's. I'm going to close the one I opened.
