### ISSUE TITLE
Seeding Table Question

### ISSUE THREAD

**Issue by acobrelo** [ga-wdi-boston/full-stack-project#325]
Context: I'm making an app that lets you enter responses to mood assessments to track changes over time. Each Entry has many Questions and vice versa. They're linked through a join table, Responses. Each Question belongs to an Assessment. 

My Questions table has the id, a brief version of the question, and then the id of the Assessment. 

I want to seed my database with all the questions for the first assessment. I can't find a good example in my notes on how to set this up. Would this be correct: 

In the seed.db file:

Assessment.create( purpose: 'depression', battery_name: 'Beck Depression Inventory' )

Question.create( [ 
      { question: 'are you sad', assessment_id: 1 },
      { question: 'crying more?', assessment_id: 1},
etc.... ])

Or, alternately, would it be possible to do the following and have the assessment_id automatically be 1 for all the questions I put in:

Assessment.create( purpose: 'depression', battery_name: 'Beck Depression Inventory' ).questions.create([
      { question: 'are you sad' },
      { question: 'crying more?'},
etc.... ])

Thanks in advance! Just want to make sure I'm doing this properly.

**Comment by berziiii** [comment]
If questions belong to assessments, you will need to have your examples.rb file in the db folder have 
`Question.create([
       { question: 'Blah', assessment_id: 1 },
       { question: 'Blah', assessment_id: 1 },
       etc...
])`

@acobrelo, please close since we spoke. Thank you!

**Comment by berziiii** [comment]
@acobrelo If this open? If not, please close. Thank!
