### ISSUE TITLE
Post across domains

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/full-stack-project#326]
I am having trouble with POST requests across domains. GET is fine, but I imagine PATCH and DELETE will also have trouble (haven't tried them yet). 

The request is: POST https://ironsidegoaltimate.herokuapp.com/games 

The error is:

XMLHttpRequest cannot load https://ironsidegoaltimate.herokuapp.com/games. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mishaherscu.github.io' is therefore not allowed access. The response had HTTP status code 400.

What is the Access-Control-Allow-Origin header? Do I actually have to add something else to the header?

Thanks

**Comment by berziiii** [comment]
You need your authentication token for the post, patch and delete.  Are you incorporating that into your Ajax request?

**Comment by MishaHerscu** [comment]
I just got it to work. I thought I had the token there, but I hadn't set the token yet. It is fine now.

**Comment by MishaHerscu** [comment]
Actually this now only works from localhost to localhost. I think I need to do something with CORS

**Comment by berziiii** [comment]
Please share your Ajax request code.

**Comment by payne-chris-r** [comment]
It definitely has something to do with CORS.

**Comment by MishaHerscu** [comment]
Okay here is the client code that I have now:

index.html has:

```
<form id="create-team">
       <input type="text" name="team-info[name]" placeholder="team name">
       <input type="submit" name="submit" value="Create!">
</form>
```

events file has:

`$('#create-team').on('submit', onCreateTeam);`

and also this:

```
const onCreateTeam = (event) => {
  event.preventDefault();
  $('#createTeamModal').modal('hide');
  let data = getFormFields(event.target);

  api.create(data)
  .done(ui.createTeamSuccess)
  .fail(ui.failure);
};
```

Then the API call is:

```
const create = function(data){
  return $.ajax({
    url: app.host + '/teams',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: data,
  });
};
```

finally, for now, the UI has:

```
const createTeamSuccess = (data) => {
  console.log(data);
};
```

The appropriate requires are also there and event handlers are also there.

The console just now running this was the following:
﻿

```
2016-06-27 00:52:09.440 :3000/teams:1 POST http://localhost:3000/teams 
2016-06-27 00:52:09.440 localhost/:1 XMLHttpRequest cannot load http://localhost:3000/teams. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
```

My GET requests are working fine, so I know the server at least exists etc.

**Comment by berziiii** [comment]
Put a debugger in the Ajax call right before you the 'return ajax' and see if you have the 'data' being passed correctly to the function for the call. Let's just check eve thing prior to moving forward.

**Comment by RDegnen** [comment]
What do your heroku logs look like when you make a POST request?

**Comment by MishaHerscu** [comment]
I am console logging in the ajax call and the data looks right. maybe someone else should check it though

**Comment by MishaHerscu** [comment]
omg Ross I think that just got me to the answer. i had been trying to insert a player with a team_id for a team that didn't exist....now it seems to be working.
