### ISSUE TITLE
API Verbs stop working when click on item that uses different verb

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/full-stack-project#328]
I'll click on a button that requires one verb, let's say GET.  Then I can click on another GET button, and it works well.  When I switch to a button with a different verb, let's say PATCH, I get an error message that  Cannot read property 'profile' OR 'id' of undefined.  No errors in the server.  I'm not sure how to fix this.

**Comment by payne-chris-r** [comment]
What is the use case? Are you trying to set a click handler on an element that doesn't exist yet?

**Comment by andreasantarl** [comment]
The elements exist.  I have a view workouts and create workouts.  if I click create, then I try to click view workouts, I get the error that it can't find the id of undefined .

**Comment by payne-chris-r** [comment]
Right, but do they exist when you try to ATTACH the click handler???

**Comment by RDegnen** [comment]
what is undefined supposed to be?

**Comment by andreasantarl** [comment]
It is supposed to be the user token.

**Comment by andreasantarl** [comment]
I'm using the same API call for two events.  On the second event, the app.user data is cleared.

**Comment by RDegnen** [comment]
I dont think the user token has an id property, but the user does. Is that what your trying to get?

**Comment by andreasantarl** [comment]
Punctuation.  Fucking punctuation.

**Comment by payne-chris-r** [comment]
Do we need to have a talk with you and Shireen?

**Comment by andreasantarl** [comment]
Watch yourself, Payne.
