### ISSUE TITLE
Signature Mix-Ins Unavailable

### ISSUE THREAD

**Issue by computingbets** [ga-wdi-boston/full-stack-project#329]
I checked how Bootstrap uses media queries in the link below, under responsive breakpoints, and it says to use syntax -
`@include media-breakpoint-up(sm) {
  .some-class {
    display: block;
  }
}`
From http://v4-alpha.getbootstrap.com/layout/overview/
When I use "@include media-breakpoint-up" i get an error saying "No mixin named media-breakpoint-up". So, I looked at https://github.com/shakacode/bootstrap-loader/issues/9 but I think the GH issue has to do with custom mix-ins. 
Do I need a new version of SCSS?

**Comment by RDegnen** [comment]
did you pass it a breakpoint? like sm lg etc.,

**Comment by computingbets** [comment]
yes - `@include media-breakpoint-up (sm){
  .question-one {
    margin-top: 159px;
  }`
Something worth mentioning is that this broke my scss but made the question-one responsive.

**Comment by RDegnen** [comment]
is it still throwing the error now that it's responsive? Or did it just break all the styles?

**Comment by computingbets** [comment]
Still an error. Broke styles. Is responsive.

**Comment by RDegnen** [comment]
did you forget a closing bracket? Or just not copy it in your question

**Comment by computingbets** [comment]
Forgot to copy

**Comment by RDegnen** [comment]
where are you?

**Comment by berziiii** [comment]
https://github.com/berziiii/html-css-sass/tree/solution/assets/styles. You need to define the breakpoint.scss mixin function. See this folder and how we created the function then used it.

**Comment by computingbets** [comment]
Okay, I applied the solution branch to my code and the magic ain't there. 
The breakpoint file is copied - 

```
$breakpoints: (
 'tiny':   (max-width:  300px),
 'small':  (min-width:  412px),
 'medium': (min-width:  992px),
 'large':  (min-width: 1200px)
);

@mixin breakpoint($name) {
 @if map-has-key($breakpoints, $name) {
   @media #{inspect(map-get($breakpoints, $name))} {
     @content;
   }
 } @else {
   @warn "Couldn't find a breakpoint named `#{$name}`.";
 }
}
```

and my version of breakpoint that I'm applying the mix-in to is - 

```
div.question-one {
  clear: left;
  @include breakpoint(small) {
    margin-top: 300px;
  }
  margin-top: 123px;
  position: relative;
  } 
```

I'm no longer getting errors.

**Comment by berziiii** [comment]
So is this solved? If so, please close. Thanks!
