### ISSUE TITLE
Need Help Login

### ISSUE THREAD

**Issue by pguzman26** [ga-wdi-boston/full-stack-project#33]
Need help using ajax to login to my server

**Comment by tdyer** [comment]
What did you try? Did you login successfully using curl, using the curl commands in the project2 readme?
Do you have a submit handler for login form submission?
For example, something like, $("#login').on('click, function(){... }). ?
Do you have some ajax code that isn't working? If so, copy it here.

**Comment by GA-MEB** [comment]
@gmankd, I second all of @tdyer's questions. Have you tested your API yet? If not, I suggest you hold off on messing with AJAX until you're sure that the API works.

**Comment by pguzman26** [comment]
I have tested my api with curt and postman. I am able to log in. I am getting an error with my routes.
The following is my ajax code.

'use strict';
var smart_grocery = {
  url: 'http://localhost:3000',

  ajax: function(config, cb) {
    $.ajax(config).done(function(data, textStatus, jqxhr) {
      cb(null, data);
    }).fail(function(jqxhr, status, error) {
      cb({jqxher: jqxhr, status: status, error: error});
    });
  },

//////////////////////////////////////////////////////////////////////////////////////////

  register: function register(credentials, callback) {
    this.ajax({
      method: 'POST',
      url: this.url + '/register',
      contentType: 'application/json',
      data: JSON.stringify(credentials),
      dataType: 'json'
    }, callback);
  },

  login: function login(credentials, callback) {
    this.ajax({
      method: 'POST',
      url: this.url + '/login',
      contentType: 'application/json',
      data: JSON.stringify(credentials),
      dataType: 'json'
    }, callback);
  },

  logout: function logout(id, token, callback) {
    this.ajax({
      method: 'DELETE',
      url: this.url + '/logout/' + user_id,
      headers: {
          Authorization: 'Token token=' + token
      },
      contentType: 'application/json',
      dataType: 'json'
    }, callback);
  },

//////////////////////////////////////////////////////////////////////////////////////////

createProfile: function createProfile(profile, user_id, token, callback) {
  this.ajax({
    method: 'POST',
    url: this.url + '/users/' + user_id + '/profile',
    headers: {
        Authorization: 'Token token=' + token
    },
    contentType: 'application/json',
    data: JSON.stringify(profile),
    dataType: 'json'
  }, callback);
},

updateProfile: function updateProfile(profile, user_id, token, callback) {
  this.ajax({
    method: 'PATCH',
    url: this.url + '/users/' + user_id + '/profile',
    headers: {
        Authorization: 'Token token=' + token
    },
    contentType: 'application/json',
    data: JSON.stringify(profile),
    dataType: 'json'
  }, callback);
},

readProfile: function readProfile(user_id, token, callback) {
  this.ajax({
    method: 'GET',
    url: this.url + '/users/' + user_id + '/profile',
    headers: {
      Authorization: 'Token token=' + token
    },
    dataType: 'json'

  }, callback);
},

//////////////////////////////////////////////////////////////////////////////////////////

  //Authenticated api actions
  listGames: function (token, callback) {
    this.ajax({
      method: 'GET',
      url: this.url + '/games',
      headers: {
        Authorization: 'Token token=' + token
      },
      dataType: 'json'
      }, callback);
  },

  createGame: function (token, callback) {
    this.ajax({
      method: 'POST',
      url: this.url + '/games',
      headers: {
        Authorization: 'Token token=' + token
      },
      contentType: 'application/json; charset=utf-8',
      data: JSON.stringify({}),
      dataType: 'json',
    }, callback);
  },

  showGame: function (id, token, callback) {
    this.ajax({
      method: 'GET',
      url: this.url + '/games/' + id,
      headers: {
        Authorization: 'Token token=' + token
      },
      dataType: 'json'
    }, callback);
  }
};

This is the error that I am getting from the back end.

o route matches [POST] "/"

Rails.root: /Users/pabloguzman/Projects/smart_grocery/smart_grocery_backend

Application Trace | Framework Trace | Full Trace

**Comment by gaand** [comment]
What code invokes these methods?  Please post that.  Thanks.

**Comment by pguzman26** [comment]
Rachel helped me solve. My login form was calling local host 3000 I removed that and entered the callback function on my registration 

(credentials, function(err, data){
  //     if (err) { console.error(err); });
      e.preventDefault();
      $('#login-form').hide();
    });

I am closing this issue.
