### ISSUE TITLE
requirements question

### ISSUE THREAD

**Issue by mattb5** [ga-wdi-boston/full-stack-project#330]
via a get request, the user successfully retrieves his tennis match history. 

for my delete crud action, i have the user input on website the number match that they want to delete.  IF the user input the wrong match number on website (a match number that user does not "own") it will still delete that row in the database -- even though the user doesn't "own" that match.

does this prevent me from passing requirements?

**Comment by berziiii** [comment]
Yes. You do not want to allow someone to delete someone else's items. IF you have a input field where they put the id, you have to check to see if the id of that item's user matches the id of the user logged in. But to have better UI and prevent this extra work, you should have handlebars loop through all items and return the ones that are for that user the  have a button to delete this specific item.

**Comment by mattb5** [comment]
ok.  working on this now.  thanks

**Comment by mattb5** [comment]
Brian - 

I think i fixed this problem.   the delete ajax requests always goes through (even when entering a number that's match ID that is not owned by the user) BUT it doesn't delete in the database because I have a condition to only delete if the match number is owned by current_user (current_user.matches.id).

could you possibly come by and check to make sure this meets requirements?  it will determine where I go from here.

Thanks<
Matt

**Comment by berziiii** [comment]
Yes that would work as long as you have something that prompts the user on the client side that the request failed and they need to check the number of their match and try again.

**Comment by mattb5** [comment]
ok.  thanks.  can i do it with an alert?  i think an alert is really fitting here - user can't miss it and it doesn't keep the message on the page.

**Comment by payne-chris-r** [comment]
Alerts are yucky. Don't use an alert.

**Comment by mattb5** [comment]
ok, thanks
