### ISSUE TITLE
Can't delete item that was just created

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/full-stack-project#332]
I'm trying to be able to create a new workout and then immediately delete the workout if the user wants to.  For workouts that were created in this session, I get an error that the id property of the workout cannot be found to be deleted. Otherwise, if a workout was already existing, I can delete it.

I also want to refresh the list of workouts when an item is deleted, and this only works for existing workouts- not for the new workouts that were added in a given session.

**Comment by payne-chris-r** [comment]
What have you done to try to resolve this?

**Comment by andreasantarl** [comment]
Console.log() to find out what data there is - i.e. what id the button has.

**Comment by RDegnen** [comment]
Can you post some code of the action and the ajax request?

**Comment by andreasantarl** [comment]
Event-------

``` js
const onDeleteWorkout = (event) => {
  event.preventDefault();
  let buttonId = $(event.target).attr('id');
  console.log("Delete button id: ", buttonId);
  api.deleteWorkout(buttonId)
  .done(ui.deleteWorkoutSuccess)
  .fail(ui.deleteWorkoutFailure);
  //event.onSeeWorkouts();
};
```

API ------ 

``` js
const deleteWorkout = (buttonId) => {
//  console.log("ButtonId: ", buttonId);
//  console.log("data in delete workouts: ", app.user.workouts[buttonId].id );
// console.log("App.user.workouts.buttonId:  ", app.user.workouts.buttonId);
  return $.ajax({
    url: app.host + '/workouts/' + app.user.workouts[buttonId].id,
    method: "DELETE",
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  });
};
```

UI ------------

``` js
const deleteWorkoutSuccess = (buttonId) => {
  console.log("Deleted!");
  app.user.workouts[buttonId].id = null;
};

const deleteWorkoutFailure = (error) => {
  console.error(error);
};
```

**Comment by payne-chris-r** [comment]
And the `console.log("ButtonId: ", buttonId);` returns the correct Button ID that you're wanting to delete? Are you creating these based on a INDEX to workouts/?

**Comment by RDegnen** [comment]
can you also post the error

**Comment by andreasantarl** [comment]
The button ID does return the correct ID and that indexes the workout.  I use that index to pull the ID of the database row for the workout.

Error message.
workouts_ui.js:50 Uncaught TypeError: Cannot set property 'id' of undefined

**Comment by RDegnen** [comment]
when you create a new workout, can you see if it is properly put into the array that you are deleting from?

**Comment by andreasantarl** [comment]
It isn't properly getting put into the array. Shouldn't that be happening automatically?

**Comment by RDegnen** [comment]
yea if you want to be able to delete it from the array than it should be put in there when you create it

**Comment by andreasantarl** [comment]
I don't know how to do that because I thought it would happen automatically.

**Comment by payne-chris-r** [comment]
Nothing happens automatically. Computers are dum.
