### ISSUE TITLE
date is always null

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/full-stack-project#333]
I created a new column in my table and gave it the datatype date. I seem not to be able to change it to anything. It always stays null. I'm using this html:

input type="date" name="dream-date" 

for creating a date picker. I don't know which code in which file I should send to give more information. I console.log everywhere and it's always null.

**Comment by payne-chris-r** [comment]
If you're console logging everywhere and it's always null, you should start at the beginning. Is the form actually pulling that data out?

**Comment by esthercordova** [comment]
I had a naming issue- too many different names for the same thing. Got it to work!
