### ISSUE TITLE
Join table of a table with itself

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/full-stack-project#334]
I have a table called "players" for all of the frisbee players. I want to make another table called "points" for every time someone scores. I think the fields on "points" should be:
1. id
2. game_id (foreign key to games table)
3. scoring_player_id (foreign key to player table)
4. assisting_player_id (another foreign key to player table)
5. created_at
6. updated_at

I think this is different from a self join. Is there a link you can send with an example of something like this?

Thanks

**Comment by MishaHerscu** [comment]
If there isn't an obvious way to do this the way I described, I could also just make the assisting_player_id not be a foreign key, and just have it be an integer that happens to be the user_id.

I also could make two separate tables for goals and assists. 

I also could make players have a "scorer" and an "assister" and then join those, but that is just making a lot more complexity

**Comment by payne-chris-r** [comment]
I've done a bit of googling. It's somewhat similar to this: http://stackoverflow.com/questions/2166613/multiple-foreign-keys-referencing-the-same-table-in-ror

**Comment by MishaHerscu** [comment]
thanks, i'll check it out. it got too late in the process though so i just did it the less nice way with two different tables
