### ISSUE TITLE
GitHub pages doesnt display any css

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/full-stack-project#336]
It doesnt show any css just html.

the link is: https://esthercordova.github.io/project-2-client/index.html

I ran grunt build. Don't know why that happens.

**Comment by RDegnen** [comment]
is there any error in your console?

**Comment by esthercordova** [comment]
![screen shot 2016-06-28 at 9 52 44 am](https://cloud.githubusercontent.com/assets/13932794/16418034/252f8644-3d16-11e6-8668-e26266d16292.png)

more than just one..

**Comment by RDegnen** [comment]
did you remember to unignore vendor.bundle and bundle files in your .gitignore file?

**Comment by esthercordova** [comment]
working on it

**Comment by berziiii** [comment]
I'm with Esther, Ill work with her.

**Comment by esthercordova** [comment]
I forgot to comment out the files Ross mentioned and now it works. Thanks.
