### ISSUE TITLE
can't push to master after changing the name of my github repository 

### ISSUE THREAD

**Issue by mattb5** [ga-wdi-boston/full-stack-project#337]
I changed the name of my git hub repository last night.

after merging to the master branch, i receive this error when trying to 'push origin master '

! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:mattb5/project2-rails-api.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

After trying to change the name of the repository back to original name, i still receive same error. 

Don't want to lose my work on github..

Thanks,
Matt

**Comment by mattb5** [comment]
One more piece of this puzzle is a few days ago, I did clone my repository into another folder in my computer to test it a few things out that I didn't want near my master branch...   I wonder if that's what this line is about : 

This is usually caused by another repository pushing
hint: to the same ref.

**Comment by RDegnen** [comment]
try removing your current origin with `git remote remove origin` and then run `git remote add origin <origin ssh>` and see if that fixes anything

**Comment by mattb5** [comment]
hey ross :) 

so this will remove the link between my local repo and the github repo and then we're adding that link back?  

and this is the  <origin ssh>?      git@github.com:mattb5/project2-rails-api.git

**Comment by RDegnen** [comment]
Yea it will remove the link and then add it back again. You get the ssh from clicking the green `clone or download` button on the topish right and copying that link.

**Comment by mattb5** [comment]
just removed link and added it back again but got the same error after trying to push to origin master again :

! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:mattb5/project2-rails-api.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by mattb5** [comment]
it's letting me push to my other branches, just not to master

**Comment by RDegnen** [comment]
k ill assign myself to this. where you at?

**Comment by mattb5** [comment]
classroom 4, thanks

**Comment by mattb5** [comment]
solution to this problem was that last night, i changed readme on github itself.  i had to first pull the updated readme to my local before I could push to master again. 

thanks ross.
