### ISSUE TITLE
Delete A Row From A Bootstrap Table

### ISSUE THREAD

**Issue by RoobScoobs** [ga-wdi-boston/full-stack-project#338]
Hey guys, 

I managed to render my data dynamically on a table in the front-end. 

<img width="596" alt="screen shot 2016-06-28 at 9 42 35 am" src="https://cloud.githubusercontent.com/assets/16338632/16417648/b6315b9c-3d14-11e6-91fc-3fe4373cc8a7.png">

I thought it would be really convenient for the user to be able to delete runs as they view them, so I wanted to attach a delete button at the end of each row. I'm stuck on how to move forward from here.

**Comment by RDegnen** [comment]
Are you rendering this table with a handlebars template and data from your backend or another way?

**Comment by RoobScoobs** [comment]
I used a for loop in javascript. Haven't dabbled with handlebars yet.

**Comment by RDegnen** [comment]
Ok, is each row populated with data from the database then? Because if it is then you could run a delete request for whatever data is in that specific row and then re-render the table

**Comment by RoobScoobs** [comment]
Each row is populated with data from the database, but still confused on how I would run a delete request.

**Comment by RDegnen** [comment]
I'll just write down here what I mentioned. When you put that x in, have a click handler that when you click on the x it fires the ajax DELETE request with the specific ID of whatever run you are trying to delete. If your still struggling then I'll come back and help out

**Comment by RoobScoobs** [comment]
Okay cool. I'm having some trouble actually getting the button to display since I only want each row that appears to have a delete button attached to it.

**Comment by RoobScoobs** [comment]
I tried inserting it into the for loop function as additional html but that didn't work.

**Comment by RoobScoobs** [comment]
Solution:

In order to render user data dynamically on the table I'm using a javascript for loop function which fires when a user clicks on a button to view all their runs.

``` js
const getRunsSuccess = function (data) {
  let viewRuns = data.runs;
  $('.display-runs').html("<table class='table table-hover'><tr id='row1'><th>Description</th><th>Total Miles</th><th>Total Time</th><th>Run Completion Date</th><th> </th</tr></table>");
  for (let i = 0; i < viewRuns.length; i++) {
    $('#row1').after("<tr><td>" + viewRuns[i]['description'] +
    "</td><td>"+viewRuns[i]['total_miles'] + "</td><td>" + viewRuns[i]['total_time'] +
    "</td><td>"+viewRuns[i]['completion_date'] + "</td><td>" +
    "<button type='button' data-id=" + viewRuns[i].id + " class='close' aria-label='Close'><span class='x' aria-hidden='true'>&times;</span></button>" +
    "</td></tr>");
  };
};

```

To make deleting each row easier, Ross helped me figure out the best way to do that which was dynamically adding a delete button. However, when deleting the row you need to ensure that the delete request has the correct ID. As the function iterates through each object, the corresponding ID `viewRuns[i].id` will be added to data-id.

Data-id allows us to store and access the id of that particular run. From here, we can add the click handler, however, because we're event binding on dynamically created elements, we need the following jquery: `$(staticAncestors).on(eventName, dynamicChild, function() {});`

Here is my example using the syntax noted above:

``` js

$(document).on('click', '.close', onDeleteRuns);

```

`onDeleteRuns` will call the following function:  

``` js

const onDeleteRuns = function (event) {
  event.preventDefault();
  let id = $(this).data("id");
  runsApi.deleteRuns(id)
  .done(runsUi.deleteRunsSuccess)
  .fail(runsUi.failure);
};

```
