### ISSUE TITLE
Glyphicons didn't load after deployment on gh-pages

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/full-stack-project#339]
Found the same problem in the closed issues: https://github.com/ga-wdi-boston/full-stack-project/issues/307

The solution was to remove .woff, .ttf, .woff2, .eot, .svg from Gitignore file. I don't have any of these in my gitignore file to begin with.

**Comment by esthercordova** [comment]
Could someone answer this?

**Comment by RDegnen** [comment]
can you post your .gitignore file

**Comment by esthercordova** [comment]
![screen shot 2016-06-28 at 11 22 20 am](https://cloud.githubusercontent.com/assets/13932794/16421359/b5fda2c6-3d22-11e6-954c-e165c3dd49ff.png)
![screen shot 2016-06-28 at 11 22 31 am](https://cloud.githubusercontent.com/assets/13932794/16421362/b79261ee-3d22-11e6-94c1-7376833b62d1.png)
![screen shot 2016-06-28 at 11 22 42 am](https://cloud.githubusercontent.com/assets/13932794/16421364/b9d15b5e-3d22-11e6-9330-1a0b8022a6ab.png)
![screen shot 2016-06-28 at 11 23 04 am](https://cloud.githubusercontent.com/assets/13932794/16421374/c0e3fca8-3d22-11e6-869a-1f60382ff83d.png)

**Comment by RDegnen** [comment]
all those files that you need to remove are right at the top starting with `*.woff2`

**Comment by esthercordova** [comment]
oopsi.. solved. Sorry. I used the find function in atom and it didnt come up. Thanks.
