### ISSUE TITLE
gh-pages doesnt want to communicate with Heroku, local server does

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/full-stack-project#341]
![screen shot 2016-06-28 at 10 56 54 am](https://cloud.githubusercontent.com/assets/13932794/16420441/55d44cf4-3d1f-11e6-9024-f815ac5635be.png)

Getting all kinds of errors when trying to use my app deployed on github pages instead of the localhost one. I changed the app.js to communicate with my API on Heroku. It works for localhost but not for github pages.

**Comment by Benjamski** [comment]
Have you tried changing the https to http?

**Comment by esthercordova** [comment]
changed the jquery source to https in index.html and waiting now for github pages to transfer the changes.

**Comment by RDegnen** [comment]
im pretty sure jquery is already included with the js-template. Is there a reason your using a google to get it?

**Comment by esthercordova** [comment]
Because it didnt work.I had the same issue with my first project that I had to import jquery even though it was supposed to be there.

**Comment by RDegnen** [comment]
I see, is the change you made working now?

**Comment by esthercordova** [comment]
the jquery error is gone but now I have this:

![screen shot 2016-06-28 at 11 24 20 am](https://cloud.githubusercontent.com/assets/13932794/16421432/eadee02c-3d22-11e6-9525-ff08ffe332f8.png)

**Comment by esthercordova** [comment]
worked with Ross. I had to drop my database. My schema file was not up-to-date since I used sql to add stuff to database.
