### ISSUE TITLE
Can not load image file for github page

### ISSUE THREAD

**Issue by tina513** [ga-wdi-boston/full-stack-project#342]
I couldn't load my background image on github page, and I keep getting 404 not found error. Please help~~~

**Comment by payne-chris-r** [comment]
Have you looked through other issues that are similar to this?

**Comment by tina513** [comment]
I checked. I have already did what Esther mentioned in her issue. But I still getting 404 not found error.

**Comment by RDegnen** [comment]
have you tried adjusting the file path in the inspector to see if the image loads?

**Comment by tina513** [comment]
Thank you guys~ Problem solved~ 
Reference: https://github.com/ga-wdi-boston/full-stack-project/issues/322
