### ISSUE TITLE
Seeing all user workouts when signed into user account

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/full-stack-project#344]
NO idea how to fix this.  I'm passing the AUTH token with each AJAX call and require authentication in ActiveREcord

**Comment by andreasantarl** [comment]
Also, my workout text fields are getting truncated.

**Comment by berziiii** [comment]
@andreasantarl please provide the solution and close. Thanks!

**Comment by jrhorn424** [comment]
This was an issue with not providing quotes around the output of handlebars inside an element attribute value. @andreasantarl Please close.
