### ISSUE TITLE
spec requirement question

### ISSUE THREAD

**Issue by mattb5** [ga-wdi-boston/full-stack-project#345]
the spec reads :

"Any actions which change data must be authenticated."

Does passing the user token in each user AJAX request CRUD action satisfy this requirement?

**Comment by payne-chris-r** [comment]
Do they break if you don't pass a user token?

**Comment by mattb5** [comment]
indeed they do :)

**Comment by mattb5** [comment]
solution: all crud ajax requests DO user token
