### ISSUE TITLE
PATCH Error

### ISSUE THREAD

**Issue by RoobScoobs** [ga-wdi-boston/full-stack-project#347]
Hey guys, 

While trying to send a patch request, I got this error in the console: 

XMLHttpRequest cannot load http://localhost:3000/runs/30. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.

Looking into the error I came across a bunch of different solutions that included adding `crossdomain: true`, passing `dataType: jsonp`, or `json: JSON.stringify`. 

Considering that I tested the backend using curl requests I don't think the issue is in the backend, but it might possibly be.

**Comment by RDegnen** [comment]
look at your server logs for the backend and see what they say when you make that request

**Comment by RoobScoobs** [comment]
ActionController::ParameterMissing (param is missing or the value is empty: run):

So do I have to permit the id that is being passed into the ajax call?

``` ruby
 def run_params
      params.require(:run).permit(:description, :total_miles, :total_time, :completion_date)
 end

```

**Comment by RoobScoobs** [comment]
Literally just had to change ONE character in my ajax function from `runs` to `run`: 

``` js
const updateRuns = function(description, total_miles, total_time, completion_date, id) {
  return $.ajax({
    url: app.host + '/runs/' + id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token='+ app.user.token,
    },
    data: {
      "run": {
        "description": description,
        "total_miles": total_miles,
        "total_time": total_time,
        "completion_date": completion_date
      }
    }
  });
};

```
