### ISSUE TITLE
One too many app.user.id's?

### ISSUE THREAD

**Issue by computingbets** [ga-wdi-boston/full-stack-project#348]
When I delete a playlist, which is stored in a join table that has user_id and song_id and retrieved through user_id, I cannot display a newly regenerated playlist. My delete playlist api uses the url + app.user.id. 
`const deletePlaylist = function () {
  return $.ajax({
    url: app.host + '/playlists/' + app.user.id,
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  });
};`

My display playlist api uses url + app.user.id.
`const displayPlaylist = function() {
  return $.ajax({
    //this needs to be changed
    //
    //
    url: app.host + '/playlists/' + app.user.id,
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  });
};`
 I think this is where the issue is bc when I try to make a new playlist after I delete one, the error says 
`:3000/playlists/2:1 GET http://localhost:3000/playlists/2 404 (Not Found)`
The 3000/playlists/2:1 appears as though it is making a request with double the user ids.

**Comment by payne-chris-r** [comment]
Why do you have a `//this needs to be changed comment` in there? Is that the one we left in there last week? Are you looking to get the same playlist you just deleted???

**Comment by computingbets** [comment]
I am not trying to get the same playlist that was deleted. I am trying to delete, then have another go and create a brand new playlist. However, the display playlist function does have the `//this needs to be changed`. I did change the playlist controller for GET.

**Comment by jrhorn424** [comment]
@logicmyth Was this addressed? Do you recall the resolution? Can this be closed? Thanks in advance!

**Comment by computingbets** [comment]
I vaguely recalled that I rewrote code that accounted for current user.
