### ISSUE TITLE
Heroku app not allowing sign in

### ISSUE THREAD

**Issue by acobrelo** [ga-wdi-boston/full-stack-project#349]
My client is deployed to gh-pages at  https://acobrelo.github.io/project-2-client/ 

Whenever I go to sign in or sign up, I get the following error: 

<img width="1158" alt="screen shot 2016-07-05 at 4 25 28 pm" src="https://cloud.githubusercontent.com/assets/19216945/16598688/21cc9df4-42cd-11e6-8425-337f748f7576.png">

{Hopefully attaching that pic worked, if not, I'll try and fix it}. Basically, the back end appears to be deployed just fine to Heroku, front end to gh-pages. I fixed the routing so it directs to the heroku app and not localhost. I sat down with Chris last week and we couldn't figure it out so I'm opening an issue.

I created the Heroku app early on though and it may have gotten messed up along the way somehow. Happy to start over and just push my server branch to a new Heroku app if need be. Thanks and let me know if you need more information.

**Comment by jrhorn424** [comment]
@acobrelo Was this addressed? Do you recall the resolution? Can this be closed? Thanks in advance!

**Comment by acobrelo** [comment]
Yes! Apologies! I think part of the issue was not migrating it properly and Chris helped me re-migrate and whatnot and then it worked. All set!
