### ISSUE TITLE
Need help setting up login on the Front end side

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/full-stack-project#35]
Just need a few minutes help to get me on the right track and oriented, please. My backend curl commands work just fine.

**Comment by gaand** [comment]
Okay.  Please let us know what you've done so far on the front end.  Do you have forms for register and login?  To you have event handlers for submit events?

**Comment by LaurisaNeuwirth** [comment]
I just started my index.html, app.js and style.css files. I want to confirm that I should list out the logic in the app.js file before I start coding. And I have my wireframes all finished for each page, I will work on my html/css today too. I just need a few minutes to make sure I am thinking in term sof separation of concerns as I progress.

**Comment by gaand** [comment]
Okay.  Please me me in classroom 3.

**Comment by gaand** [comment]
Walked through separation into app.js and api.js for user events versus network calls respectively.
