### ISSUE TITLE
.pause() is not a function

### ISSUE THREAD

**Issue by cdelsoin** [ga-wdi-boston/full-stack-project#351]
I current have my audio track and I'm trying to control it with jquery. I have no trouble using the jquery in the console to change the volume 

```
 $('#rain-track').prop('volume', 0.7);
 // to change the volume to 70% 
```

but when i try to use

```
$('#rain-track').pause()
```

i get back an error that says it is not a function

**Comment by gaand** [comment]
Please paste the the code for the DOM element with `id='#rain-track'`.

**Comment by cdelsoin** [comment]
```
      <form class="track-one">
        <p>Rain</p>
        <audio id="rain-track" class="audio-track" autoplay="autoplay" loop="loop" controls>
          <source src="assets/audio/rain.ogg" type="audio/ogg">
          <source src="assets/audio/rain.mp3" type="audio/mp3">
        </audio>
        <input class="rainSlider allSliders" data-track="rain" type="range" min="0" max="1" step="0.025" value="0.5">
      </form>
```

**Comment by gaand** [comment]
What is the type of `$('#rain-track')`?  

What type do you need to invoke `pause`?

**Comment by RealWeeks** [comment]
Google: http://stackoverflow.com/questions/4646998/play-pause-html-5-video-using-jquery

**Comment by RealWeeks** [comment]
@cdelsoin Please write what you did and close if this has been resolved.

**Comment by cdelsoin** [comment]
The solution was `$('#rain-track').get(0).pause()` as it said in the link that Jason posted. Thank you
