### ISSUE TITLE
Can't bundle exec rake db:nuke_pave

### ISSUE THREAD

**Issue by gabescarbrough** [ga-wdi-boston/full-stack-project#352]
I actually resolved this issue but wanted this up for anyone else who might run into it.

Also would like to know why this was happening.

Following with instructions for the Rails API Template I was not able to run:

``` rb
bundle exec rake db:nuke_pave
```

I was getting an error saying:

``` bash
rake aborted!
Dotenv::FormatError: Line "development:" doesn't match format
```

Noticing that it seemed to be a Dotenv issue, I deleted .env file I created (as per the instructions), and put my secrets in secrets.yml (as we have done in class).

Now I was able to nuke_pave and get my server running.

What was the issue here? What is the benefit of .env?

**Comment by gaand** [comment]
Colon not equals?

**Comment by gaand** [comment]
So, what did you put in your `.env` file?

**Comment by gaand** [comment]
So, Missing backticks had this, `SECRET_KEY_BASE_<DEVELOPMENT|TEST>` looking like this SECRET_KEY_BASE_<DEVELOPMENT|TEST> in the README.md.

**Comment by gabescarbrough** [comment]
That was it. I had the formatting of the keys the same as we had done them in the secrets.yml file. Once I changed it to `SECRET_KEY_BASE_<DEVELOPMENT|TEST>` it let me nuke_pave.
