### ISSUE TITLE
trouble installing dependencies

### ISSUE THREAD

**Issue by cdelsoin** [ga-wdi-boston/full-stack-project#353]
```
~/wdi/projects/audio-project/audio-project-api (master)$ bundle install
rbenv: version `2.3.1' is not installed (set by /Users/Cliff/wdi/projects/audio-project/audio-project-api/.ruby-version)
```

so i used 

```
rbenv install 2.3.1 && rbenv global 2.3.1 
```

i then had to `gem install rubocop`

after that i needed to rake secrets but i am getting this error

```
The `bundle' command exists in these Ruby versions:
  2.3.0
```

**Comment by cdelsoin** [comment]
The amount of roadblocks I keep hitting make me feel like something wrong is happening. If not, let me know and ill follow the errors to get everything working correctly

**Comment by gaand** [comment]
Please see #350

**Comment by cdelsoin** [comment]
![screen shot 2016-08-16 at 7 59 32 pm](https://cloud.githubusercontent.com/assets/20059077/17719944/2bdbabd8-63ec-11e6-8744-41280e6664d8.png)

....why

**Comment by gaand** [comment]
The above image is unrelated to this issue.  Please open a separate issue to seek assistance with the problem related to `uv_chdir`.

**Comment by cdelsoin** [comment]
Thank you
