### ISSUE TITLE
Questions about database tables

### ISSUE THREAD

**Issue by dvdpwll** [ga-wdi-boston/full-stack-project#354]
I have questions on the best way to save my map state to the database.

Initial idea: make a table named 'maps' and make a column named 'grid' that stored an int array. Every number would be associated with a certain image and when I get the array I would have a for loop and a switch that would insert an image onto the page.

Are there better ways of doing this?

**Comment by gaand** [comment]
Let's talk it over and explore the options and paths

**Comment by dvdpwll** [comment]
Thanks for the talk.
make an 'elements' table with columns 'object', 'terrain', 'other', 'order' and reference map. That way my database can store more information than one image and the database can return an array. Also active record doesn't like making a column an array.

**Comment by dvdpwll** [comment]
So I made my tables and tested it out, but when I look at it on localhost:3000 it looks very strange and I'm not sure I made it correctly.

```
{
    "elements": [
            {
                  "id": 1,
                  "object": {
                         "id": 1,
                         "map_id": 2,
                         "object": "rock",
                         "order": 1,
                         "created_at": "2016-08-17T15:08:43.976Z",
                        "updated_at": "2016-08-17T15:11:01.655Z"
                   },
                   "order": 1,
                   "map": {
                        "id": 2,
                        "name": "test"
                   }
            }
      ]
}
```

Is this how it's supposed to look?

Here is the model for Map

```
class Map < ActiveRecord::Base
  has_many :elements
end
```

Here is the model for Element

```
class Element < ActiveRecord::Base
  belongs_to :map
end
```

**Comment by gaand** [comment]
Please paste the code for your serializers.

**Comment by dvdpwll** [comment]
```
class MapSerializer < ActiveModel::Serializer
  attributes :id, :name
end
```

```
class ElementSerializer < ActiveModel::Serializer
  attributes :id, :object, :order
  has_one :map
end
```

**Comment by gaand** [comment]
This may help:

``` diff
 class ElementSerializer < ActiveModel::Serializer
   attributes :id, :object, :order
-  has_one :map
+  belongs_to :map
 end
```

**Comment by dvdpwll** [comment]
I changed the element serializer but it didn't change the json.

```
class ElementSerializer < ActiveModel::Serializer
  attributes :id, :object, :order
  belongs_to :map
end
```

**Comment by gaand** [comment]
In a serializer, `object` (or `:object`) refers to the thing being serialized.  So, different name.

**Comment by dvdpwll** [comment]
Yay! Change the name from object to thing fixes the json error.
Thanks!
