### ISSUE TITLE
localhost:3000 "PG::ConnectionBad"

### ISSUE THREAD

**Issue by jordanallain** [ga-wdi-boston/full-stack-project#355]
<img width="1270" alt="screen shot 2016-08-17 at 10 55 11 am" src="https://cloud.githubusercontent.com/assets/18097107/17741160/2176bcb4-6469-11e6-98d0-e21a18919b56.png">

**Comment by gaand** [comment]
Please paste the output of `tail /usr/local/var/postgres/server.log`.

**Comment by jordanallain** [comment]
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 269) running in data directory "/usr/local/var/postgres"?
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 269) running in data directory "/usr/local/var/postgres"?
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 269) running in data directory "/usr/local/var/postgres"?
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 269) running in data directory "/usr/local/var/postgres"?
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 269) running in data directory "/usr/local/var/postgres"?

**Comment by gaand** [comment]
postgres (or more likely your machine) failed to shutdown cleanly.  

Run `ps ax|grep postgres` and if that doesn't show PostgreSQL running
1. run brew services stop postgresql
2. delete postmaster.pid
3. run brew services start postgresql

**Comment by jordanallain** [comment]
i entered

``` sh
ps ax|grep postgres
```

and got 

``` sh
8771 s000  R+     0:00.00 grep postgres
```

**Comment by RealWeeks** [comment]
did you try `brew services restart postgres`

**Comment by jordanallain** [comment]
yes i tried that to no avail. 

i tried stopping postgres and deleting the postmaster.pid and got

``` sh
[~/wdi/projects/ballers-rails-template](master) delete postmaster.pid
-bash: delete: command not found
```

**Comment by gaand** [comment]
The file postmaster.pid is in /usr/local/var/postgres

**Comment by jordanallain** [comment]
navigated to /usr/local/var/postgres

stopped postgres
removed postmaster.pid
restarted postgres
stopped server
restarted server

problem appears to be solved. thank you!
