### ISSUE TITLE
Data undefined

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/full-stack-project#357]
I was able to create a new object, and it was successfully stored in the back end. However, I don't get my data object back in my console as I expected. I can't understand what is wrong.

It says, it can't read property done of undefined. 

``` events.js
const createJob = function(event) {

  event.preventDefault();

  let data = getFormFields(this);

    debugger;
    api.createJob(data)
    .done(ui.createJobsuccess)
    .fail(ui.failure);
};
```

``` api.js
const createJob = (data) => {
  $.ajax({
    method: "POST",
    url: app.api + '/jobs',
    data,
    headers: {
      Authorization: 'Token token=' + app.user.token
    },
  });

};
```

``` ui.js
// Create job
const createJobsuccess = (data) => {

    console(data);
};
```

<img width="691" alt="screen shot 2016-08-17 at 1 09 36 pm" src="https://cloud.githubusercontent.com/assets/19355037/17746129/c1e00594-647c-11e6-8e27-a77641c581cf.png">
<img width="319" alt="screen shot 2016-08-17 at 1 15 34 pm" src="https://cloud.githubusercontent.com/assets/19355037/17746134/c5ab6a38-647c-11e6-829a-d5f0462bd20d.png">

**Comment by RealWeeks** [comment]
Thing one, I really don't like the fact your using the same variable name for two functions `const createJob`

**Comment by RealWeeks** [comment]
Also, have you looked at your code for your previous project? How did you accomplish this in the past?

**Comment by gaand** [comment]
What are you requiring/exporting from the various files?

**Comment by NatasaPeic** [comment]
Name is fixed now. Thank you!

I have looked our previous project. We didn't pass any data last time. Now, I'm passing object. 

I'm requiring:

 events.js

```
const getFormFields = require(`../../../lib/get-form-fields`);

const api = require('./api');
const ui = require('./ui');
```

api.js

```
const app = require('../app');
```

ui.js

```

const app = require('../app');
```

And I'm exporting all the functions within the file.

**Comment by RealWeeks** [comment]
what are you exporting? please use code blocks instead of screenshots

**Comment by gaand** [comment]
Please don't paste images.  Paste the code in fenced code blocks.

**Comment by NatasaPeic** [comment]
Sorry for the pictures. 

Exporting:

events.js

``` js
const addHandlers = () => {


    $('#sign-up-modal-link').on('click', showSignUpModal);
    $('#sign-up').on('submit', onSignUp);
    $('#sign-up1').on('click', closeModalSignUp);

    $('#sign-in-modal-link').on('click', showSignInModal);
    $('#sign-in').on('submit', onSignIn);
    $('#sign-in1').on('click', closeModalSignIn);

    $('#change-password-modal-link').on('click', showChangePasswordModal);
    $('#change-password').on('submit', onChangePassword);
    $('#change-password1').on('click', closeModalChangePassword);




    $('#sign-out-modal-link').on('click', showSignOutModal);
    $('#sign-out').on('submit', onSignOut);
    $('#sign-out1').on('click', closeModalSignOut);

    $("#sign-out1").on('click', function () {
          $('#table').hide();
    });

    $('#create-job-modal-link').on('click', showCreateJobModal);
    $('#create-job').on('submit', createJob);
    $('#createJob1').on('click', closeCreateJobModal);



};


module.exports = {
  addHandlers,
};
```

api.js

``` js
module.exports = {
  signUp,
  signIn,
  changePassword,
  signOut,
  createJobs

};
```

ui.js

``` js

module.exports = {
  failure,
  success,
  signInSuccess,
  signOutSuccess,
  onSuccess,
  createJobsuccess

};

```

I edited this to show using langaguage indicators after the backticks. @gaand.

**Comment by RealWeeks** [comment]
createJob or createJobs? In the function you posted it says `createJob` in your exports it looks like you export `createJobs`

**Comment by NatasaPeic** [comment]
I have changed createJobs in my ui.js.

**Comment by RealWeeks** [comment]
In your UI.js, from reading your module.exports it looks like you only have a createJobssuccess, not a createJobs. Is this true?

**Comment by NatasaPeic** [comment]
My mistake. I changed it in api.js and not in us.js.

**Comment by NatasaPeic** [comment]
It seems to be working. Object is definitely stored. I will work now on showing it in the front end.

Thanks for help.
