### ISSUE TITLE
can't run rails c

### ISSUE THREAD

**Issue by EchoXin** [ga-wdi-boston/full-stack-project#358]
when running rails c, got this message:

~/wdi/projects/diary_api (master)$  rails c
There is a version mismatch between the spring client and the server.
You should restart the server and make sure to use the same version.

CLIENT: 1.6.4, SERVER: 1.7.2

I tried restart spring but doesn't work.

**Comment by gaand** [comment]
Is this the way we run the rails console in examples?

**Comment by EchoXin** [comment]
Yes

**Comment by EchoXin** [comment]
If I stop spring , then I can run rails c, seems problem solved.

**Comment by gaand** [comment]
Please see step 13 of https://github.com/ga-wdi-boston/rails-api-template#installation
