### ISSUE TITLE
user_id 'null' in Palettes table when POST request sent

### ISSUE THREAD

**Issue by gabescarbrough** [ga-wdi-boston/full-stack-project#360]
I've created my Palettes table and it has a many to one relationship with my User table. I am able to shovel a palette into a user's palettes in the Rails console, and this is reflected in the browser.

My basic CRUD actions have been created and tested with curl.

The thing confusing me is that when I send a POST request using curl, the user_id field is "null". 

I am sending the curl request after signing in via curl, and including the token so I thought it would see who the user was.

Looking back at the tic-tac-toe API, it appears that my formatting is correct but it seems I'm missing something.

PATCH request example:

``` sh
curl --include --request POST "http://localhost:3000/palettes" \
  --header "Authorization: Token token=BAhJIiU4MmY3MmM0ODA2ZmY3NGYzNmMwNmIxOGYwNTI3ODk2OAY6BkVG--963e8e7147d5ed706693436b6ccf51634734b140" \
  --header "Content-Type: application/json" \
  --data '{
    "palette": {
      "palette_name": "Signed in User w/ token",
      "color1": "hsl(2, 50%, 50%)",
      "color2": "hsl(50, 50%, 50%)",
      "color3": "hsl(20, 50%, 50%)",
      "color4": "hsl(50, 50%, 50%)",
      "color5": "hsl(20, 50%, 50%)"
    }
  }'
```

**Comment by gaand** [comment]
You want to use `current_user` who is the user whose token you sent.

**Comment by gabescarbrough** [comment]
I changed my create and set_palette methods based on the examples_controller.

``` rb
  def create
    @palette = current_user.palettes.build(palette_params)

    if @palette.save
      render json: @palette, status: :created, location: @palette
    else
      render json: @palette.errors, status: :unprocessable_entity
    end
  end
```

``` rb
    def set_palette
      @palette = current_user.palettes.find(params[:id])
    end
```

Now when I send a GET post requests I get the following 500 error on my Rails server saying that there is no method named 'palettes' on line 21.

Doesn't User have a .palettes do to the one-to-many relationship? I am able to do User.find_by_id(1).palettes in the Rails console for example.

```
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `palettes' for nil:NilClass):
  app/controllers/palettes_controller.rb:21:in `create'


  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.1ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.5ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (47.5ms)
```

**Comment by gaand** [comment]
Are you invoking `palettes` on an instance of `User`?  

And I assume you meant `POST` in the above.

**Comment by gabescarbrough** [comment]
Yes, I did mean `POST`.

I thought `current_user` was an instance of the current `User`. 

To be honest I'm reading through application_controller.rb and while it appears that `current_user` is defined in the `set_current_user` method, I'm not really sure what is going on there.

**Comment by gaand** [comment]
Look at `UsersController` and `ExamplesController` and what they inherit.

**Comment by gaand** [comment]
`before_action` is what makes things happen.

**Comment by gabescarbrough** [comment]
Works now.

Needed to change PalettesController to inherit from OpenReadContoller.

``` rb
class PalettesController < OpenReadController
```

**Comment by RealWeeks** [comment]
@gabescarbrough I'm reopening this so you can see it and be aware of the issue and so others can have this note when they search. `OpenReadController` !=`ProtectedController`. Use case may vary based on your intentions.

Once you see this feel free to re-close.
