### ISSUE TITLE
Getting a "GET http://localhost:8080/index.scss" error in my dev tools

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/full-stack-project#361]
I've been working on getting my front end set up for signing in and I have been getting a weird console notification:

![screen shot 2016-08-17 at 3 54 50 pm](https://cloud.githubusercontent.com/assets/19956362/17750978/04afdf14-6493-11e6-8cbb-495d0cfeda06.png)

I don't know why it's trying to GET http://localhost:8080/index.scss.  Everytime I try and create a new user it gives this alert:

![screen shot 2016-08-17 at 3 58 45 pm](https://cloud.githubusercontent.com/assets/19956362/17751106/90a8555a-6493-11e6-91e9-755589cd9142.png)

**Comment by gaand** [comment]
What files reference `index.scss`?

**Comment by gaand** [comment]
`ERR_SSL_PROTOCOL_ERROR` indicates that chrome is trying to use SSL but failing.

**Comment by jlmitch1989** [comment]
Well for the first part of the issue, I had some unnecessary code in my head tag within my HTML.  I thought it was neccessary for the font that I imported.  So that part is all set.  For the ERR_SSL_PROTOCOL_ERROR, I simple removed the 's' from HTTPS in my app.js folder.  Everything is working great now!
