### ISSUE TITLE
Issue with port 3000

### ISSUE THREAD

**Issue by natGalynker** [ga-wdi-boston/full-stack-project#362]
I went back to a previous commit that is on my master branch. At the time of commit the pets table I had made successful curl requests for all the crud actions. Now on any root off of 3000 I am faced with a white screen without any errors and the rails server isn't printing out any information. When I do a curl get request or post it gives me a 500 error.

**Comment by natGalynker** [comment]
I did this by checking out the files which I was working on. Before the rollback to a previous commit I was faced with the same white screen and thought that going back to a version which I knew was working would be the fix

**Comment by RealWeeks** [comment]
Please post in all relevant error messages, from the chrome console, the rails server and the grunt server.  Also make sure all other server instances are closed.

**Comment by natGalynker** [comment]
```
curl --include --request GET http://localhost:3000/pets --verbose
*   Trying ::1...
* Connected to localhost (::1) port 3000 (#0)
> GET /pets HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
HTTP/1.1 500 Internal Server Error
* no chunk, no close, no size. Assume close to signal end

< 
* Closing connection 0
```

**Comment by natGalynker** [comment]
I closed the terminal completely and reopened it, no other server instances running.

**Comment by RealWeeks** [comment]
No chrome console errors (if you've tried an ajax request) or rails server errors?

**Comment by natGalynker** [comment]
That is what I was working on when this happened. No errors in the console upon any ajax action. Blank page. No errors in the console. 500 error in the networks tab

**Comment by RealWeeks** [comment]
If there are no errors showing on your rails server then it's not hitting your API. Though, can you paste in whatever your rails server says, error or not. I'm worried you may be confusing your rails server for a terminal session.

**Comment by natGalynker** [comment]
My rails server doesn't print out anything. When I restarted the session after closing terminal it did not register any change. It stayed exactly the same. No errors, no updates, no 500 error. The curl and network tab of the debugger is the only tools registering any change .

**Comment by natGalynker** [comment]
```
Last login: Wed Aug 17 19:18:15 on ttys000
~ $ pwd
/Users/nataliagalynker
~ $ cd wdi
~/wdi $ cd projects
~/wdi/projects $ cd vets-rails-project
~/wdi/projects/vets-rails-project (master)$ atom .
~/wdi/projects/vets-rails-project (master)$ bundle exec rails server
=> Booting WEBrick
=> Rails 4.2.6 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2016-08-17 19:22:39] INFO  WEBrick 1.3.1
[2016-08-17 19:22:39] INFO  ruby 2.3.0 (2015-12-25) [x86_64-darwin15]
[2016-08-17 19:22:39] INFO  WEBrick::HTTPServer#start: pid=7370 port=3000
```

**Comment by RealWeeks** [comment]
so confirmed the request isn't hitting your api. Strange that curl isn't hitting your api either. I would think it's a problem with the request.

**Comment by natGalynker** [comment]
The point which I changed back to in my commit history was working earlier today. I was successfully using curl to test all the CRUD actions, also in PRY. The rails server was also being responsive so maybe this is not a code issue but a network one? Is that even possible given the nature of the errors?

**Comment by RealWeeks** [comment]
I would think something is blocking your port, maybe something else running on it... or a firewall?  It would be strange through, I don't think you changed any settings. Rolling back a commit shouldn't effect the network.  A rollback could cause errors in your api but there should at least be some error in the server log if it's hitting.

**Comment by RealWeeks** [comment]
Is it at all possible that there is another server instance running minimized somewhere?

**Comment by laurenfazah** [comment]
When `rails server` is running, are you able to go to localhost:3000 in your browser? Do you get the Rails welcome page?

**Comment by natGalynker** [comment]
Maybe there is a way to do a hard reset? No other Terminal sessions open. I did a hard quit when I initially shut down the terminal session, that did close 2 instances though. I can try and google if there is a way .  There were multiple terminal sessions open earlier today but those have all been closed

**Comment by laurenfazah** [comment]
But you're able to start your rails server, correct? When it's running, are you able to see the Rails welcome page on localhost:3000?

**Comment by natGalynker** [comment]
No, when I navigate there I encounter an blank screen as well. Without any errors outputting to any log except when I send a curl request

**Comment by laurenfazah** [comment]
Do you have any Rails linter errors?

**Comment by laurenfazah** [comment]
If linter errors are clear, maybe try this: http://stackoverflow.com/a/13395155/4141833

**Comment by natGalynker** [comment]
The only linter errors are from schema which I haven't touched since I migrated.

**Comment by laurenfazah** [comment]
What is the schema linter error?

**Comment by natGalynker** [comment]
It is complaining that lines are too long and that quotes are double not single, also: this line ActiveRecord::Schema.define(version: 20160816232221) do 
It wants every 3 integers to be separated by underscores?

**Comment by laurenfazah** [comment]
Oh that's fine, those are just warnings. I'd give this port change answer a try, but if it doesn't work, revert back to 3000 http://stackoverflow.com/a/13395155/4141833

**Comment by natGalynker** [comment]
What about killing the server? Would this work? kill -9 $(lsof -i tcp:3000 -t)

**Comment by laurenfazah** [comment]
I can't speak on that - I've never seen/used that command. Did you try loading your server on a different port? Seems like a safer bet first.

**Comment by natGalynker** [comment]
That did work! Does that mean that something else is running on 3000 that needs to be shut down?

**Comment by gaand** [comment]
It is likely that you have too many open windows.

**Comment by natGalynker** [comment]
When I came in this am I did a hard restart of my computer. I  am now able to go to 3000. When Jason asked if I had any sessions minimized I took that time to close anything I wasn't working on. I only have had the two atom sessions pertaining to the project open and the single instance of grunt server and rails. Is there an explanation here somewhere. If I had more processes than that and I restarted my computer I could understand that but would't closing those instances last night have taken care of that?

**Comment by gaand** [comment]
Closing a terminal usually ends the program running in it, but not always.  Having fewer windows/tabs open means it's easier to figure out what's running.

Shutting servers down - `control-c` is usually the way to go.

**Comment by RealWeeks** [comment]
@natGalynker Please close this issue if the problem has been resolved.

**Comment by natGalynker** [comment]
Yes issue is resolved, still unsure to the exact reason of how but I am back on track now!

**Comment by natGalynker** [comment]
I will keep a closer on on the amount of sessions open
