### ISSUE TITLE
can't create new diary

### ISSUE THREAD

**Issue by EchoXin** [ga-wdi-boston/full-stack-project#363]
here is the code to create a new diary

```
const create = (data) => {
  console.log(authApi.app.user.token);
  console.log(data);
  return $.ajax({
    url: app.api + '/diaries',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + authApi.app.user.token,
    },
    data,
   });
};
```

I got the same token with the user signing in, and the data {Object {title: "hi", content: "hi"}}, which is the same structure with the diary table. Here is the error:

POST http://localhost:3000/diaries 
localhost/:1 XMLHttpRequest cannot load http://localhost:3000/diaries. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.

**Comment by RealWeeks** [comment]
can you paste in the error from your rails server?

**Comment by EchoXin** [comment]
I checked the error in rails server and it shows the diary_prama is wrong, I changed the data type in that create function. It works now. Thank you so much!
