### ISSUE TITLE
Table structure uncertainty

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/full-stack-project#364]
Now that I'm actually starting to build up my tables, I'm starting to question whether or not my ideas line up with the structure.  For instance, I originally planned on only having two tables; the user table and a creation table.  
My creation table has 4 columns: 
title:text, 
picture:text, 
artist:text, 
and description:text.  

My planned ability for this application was to have 3 buttons:
Creations
Home
Artist

If you clicked the Creations button it would do GET#index action which would show all of the pictures of user's creations they posted.  If you click the Artist button it would show all of the users contact information(name, location, email, phone #) so that people can reach out to get work done by the artist.  

Now that I'm beginning to set things up, I feel like I may not have an effective map of how this will work or if it would work at all.  Jordan made a good suggestion of just adding a column to the users table called artist:boolean.  That way if the user is an artist it could be true.  Then maybe somehow I can grab all of the true values in the column and display all of those creations.  Is that possible?  I feel like I had it all planned out, in a way that would work but now I'm not sure that it will.

**Comment by gaand** [comment]
A boolean in users (or in a profiles table which maps to users) would allow the functionality I think you want to create.  Remember that controllers don't _have_ to map 1-to-1 to models, so you could create an artists controller (and serializer) to help get what you need.

**Comment by jlmitch1989** [comment]
I'm not sure I visually understand what you mean about the creating the controllers part.

**Comment by gaand** [comment]
You can have an artists controller that queries users with the flag artist set.

**Comment by jlmitch1989** [comment]
So You're saying that the controller can grab the true boolean from the artist column in users?

**Comment by gaand** [comment]
A controller can grab any data you tell it to.  So, you can grab just the users with property artist set to true and render the JSON for them.

I suggest you try it.  Add the boolean to users and use the rails console to query only users with it set to true.  Then you can create a controller to do the same, then a serializer to customize the JSON, etc.

**Comment by jlmitch1989** [comment]
Ok I will give it a shot, thank you.

**Comment by jlmitch1989** [comment]
I think I need a one on one.  I'm really not sure I'm doing this correctly and I if I spend anymore time on this I fear it'll be a waste.

**Comment by RealWeeks** [comment]
what have you tried so far?

**Comment by jlmitch1989** [comment]
Mostly trying to read about what I think may be going on, but I still haven't wrapped my head around it.  I'm just stuck, I don't fully understand what it is I need to do.

**Comment by gaand** [comment]
Have you added a boolean column to the users table called artist?

**Comment by jlmitch1989** [comment]
I have. I figured out how to call all of the users successfully with User.all in pry. But, all of the all of the rows in the Artist column come back 'nil'.  I'm guessing because I haven't fully setup a way to grab that information from the front end.  

That being said, I added yes or no check boxes to my signup modal asking "Are you an artist" for when people go to sign up.  I just don't have any clue on how to grab that information and use it.

**Comment by gaand** [comment]
Have you check to see what `getFormFields` fields returns for the form with checkbox?

**Comment by RealWeeks** [comment]
This may be useful: http://bfy.tw/7HVK

**Comment by jlmitch1989** [comment]
I've looked at it, but I have no idea what it says.

**Comment by gaand** [comment]
Well, what does it say?  I mean, what do you see if you console log it for instance? Or look at it in the chrome console?

**Comment by gaand** [comment]
Have you tried creating a user on the rails console with the artist attribute set to true?

**Comment by jlmitch1989** [comment]
I honestly don't even know where to begin with doing a "console.log" for it. I did look at it with the console but that's not giving me any clues to what I should do with it.  

Jason, I've been looking through the google search that you sent to me, nothing that I'm reading is giving me any clues as to where I should be going with this.  I know that I'm going to be using jQuery to set up an event, but I have no idea where or how I'm suppose to do that within the Sign up process.

**Comment by gaand** [comment]
Do you have a function that invokes `getFormFields`?  Do you save the value returned from that call?  If so, what does adding the console log below show when you click submit?

``` js
let data = getFormFields(this); // assuming this is in a submit handler
console.log("data:", data);
```

**Comment by jlmitch1989** [comment]
Its giving this back:
Object {credentials: Object, artist: "yes", submit: "Sign up!"}

But when I look back at all the users in pry, It still says 'nil' for the artist column.

**Comment by jlmitch1989** [comment]
I still need help. I'm really not grasping this at all.

**Comment by RealWeeks** [comment]
is artist a boolean on the api side?

**Comment by RealWeeks** [comment]
Josh, slow down.  Coding is a very slow process.  Putting debuggers in and experimenting and failing is all very much part of it.  Using the issue tracker is a way to slow your thoughts down and get to to focus on problem solving.

If on the api side artist is a boolean, then "yes" isn't a valid input.

**Comment by jlmitch1989** [comment]
Yes, artist is also the name for my input (name="artist")

**Comment by jlmitch1989** [comment]
The issue I'm having though is not even knowing where to put "debuggers" in. I'm really very lost in this whole process right now.

**Comment by jlmitch1989** [comment]
In a "process", there is generally progress.  I've been stuck in the same spot since the start of the day.

**Comment by RealWeeks** [comment]
debuggers are used to stop your code in process where the debugger is places so when you inspect it in your chrome console you have access to all the variables available in the same scope as the debugger.  

So the question really is what do you want to inspect?

I want to help but saying I'm lost, doesn't help me help you learn.  Focus on one small part of the problem and try to solve that, then ask a point specific question about that problem, what you tried, the results and what you think the issue is and where you want to get to.

**Comment by RealWeeks** [comment]
In your data object it looks like you have credentials, an artist and a submit. does this change based on is the box is checked or not?  Try it, test it.

**Comment by jlmitch1989** [comment]
But my concern is if what I'm doing is what I'm suppose to be doing in relation to my project.  I don't know if what I'm doing is even necessary for my project to work.

**Comment by RealWeeks** [comment]
Antony suggested this earlier, so who am I to question Antony `Have you added a boolean column to the users table called artist?`

The checkboxes are your call, there are a number of ways to do what you are trying to do.

**Comment by jlmitch1989** [comment]
This is what I get if I check the 'yes' box:
Object {credentials: Object, artist: "yes", submit: "Sign up!"}

This is what I get if I check the 'no' box:
Object {credentials: Object, artist: "no", submit: "Sign up!"}

**Comment by jlmitch1989** [comment]
Yes I have added the column. And I have done the check boxes.

**Comment by RealWeeks** [comment]
So it changes, nice! You know your checkboxes work and are being captured. What's next?

**Comment by jlmitch1989** [comment]
I need to make something that listens for it

**Comment by RealWeeks** [comment]
It depends, do you want to have some button that when you click it it captures the value of the form and then possibly sends it to your API?

**Comment by jlmitch1989** [comment]
Well It would only make since to do that because it is within the 'signup' modal, and there is already a submit button being used to pull the email and password info.  So I want to use that submit button.

**Comment by jlmitch1989** [comment]
I just don't understand how I capture the data.  Even after looking at the code for sign-up.  I'm not sure I understand what it is that I need to do in order to follow through with that.

**Comment by RealWeeks** [comment]
How did you capture the data in tic tac toe?  You solved this problem before, you can do it again.

**Comment by jlmitch1989** [comment]
The getFormFields?

**Comment by gaand** [comment]
Look at the name attributes of the input elements.

**Comment by jlmitch1989** [comment]
Like this?

``` html
<input type="radio" name="choice" value="A" checked>Yes<br>
<input type="radio" name="choice" value="B">No<br>
```

**Comment by jlmitch1989** [comment]
Actually without the 'checked at the end of the first one.

**Comment by gaand** [comment]
What are the values for the other inputs?

**Comment by jlmitch1989** [comment]
There are no values for the other input. This is what I have for my modal now:

``` html
<legend>Sign up!</legend>
                  <input type="text" name="credentials[email]" placeholder="e-mail">
                  <input type="password" name="credentials[password]" placeholder="password">
                  <input type="password" name="credentials[password_confirmation]" placeholder="password confirmation"><br>
                  <big>Are you an SFX artist?</big><br>
                  <input type="radio" name="credentials[choice]" value="A">Yes<br>
                  <input type="radio" name="credentials[choice]" value="B">No<br>
                  <input type="submit" name="submit" value="Sign up!">
                </fieldset>
```

**Comment by jlmitch1989** [comment]
I still haven't gotten anywhere with this.  I realize that I'm suppose to write some sort of javascript that sends the needed data over, but I don't have the slightest clue as to what I'm suppose to write.  I feel like I have gone through my tic-tac-toe code a thousand times.

**Comment by laurenfazah** [comment]
Checklist of things to think through:
1. Have you captured your form's submission?
2. Are you grabbing the data from the form submission and passing it to a function that will put that data through `getFormFields`?
3. Have you console.logged that data to see what it looks like?
4. Is then that data from `getFormFields` being passed to an AJAX request?

**Comment by jlmitch1989** [comment]
Well with the help of some amazing peers, I figured out that it was because my user controller params needed to be updated in order for me to send over the true or false values to my artist column.
