### ISSUE TITLE
Could use a hand with handlebars + event listeners

### ISSUE THREAD

**Issue by jordanallain** [ga-wdi-boston/full-stack-project#365]
I'm trying to use handlebars for directing people through the authentication process but I'm pretty sure I'm laying it out wrong. It seems like I have to keep turning on event listeners for the same buttons depending on how the user gets there. for instance after a user signs out the sign up and sign in buttons aren't working anymore.

At the moment I have all the functions in one file which I know is 'smelly' and should be broken up into separate files but I'm not sure how to do so without creating a circular dependency. Sorry if this is too general for an issue.

**Comment by RealWeeks** [comment]
Can you paste in an example of what you're trying to do, HTML and JS. let's narrow this down a bit.

**Comment by jordanallain** [comment]
okay sorry.

the page loads with these buttons displayed already in my index.html file

``` html
        <button class="sign-up-btn">Sign Up</button>
        <button class="sign-in-btn">Sign In</button>
```

when the page finishes loading these event listeners are activated for the sign up and sign in button to display the html for the forms associated with them.

``` js
$(() => {
  // event listener for the sign up button, fires showSignUp function
  $('.sign-up-btn').on('click', showSignUp);
  // event listener for the sign in button, fires showSignIn function
  $('.sign-in-btn').on('click', showSignIn);
});
```

these functions display the html for those forms

``` js
// when user selects sign up, this loads the html for sign up forms and turns on
// an event handler for the sign up submit button
const showSignUp = function(){
  let signUpTemplate = require('./templates/sign-up.handlebars');
  $('.content-change').html(signUpTemplate);
  $('.sign-up-form').on('submit', auth.onSignUp);
};

// when user selects sign in, this loads the html for the sign in forms and
// turns on an event handler for the sign in submit button
const showSignIn = function(){
    let signInTemplate = require('./templates/sign-in.handlebars');
    $('.content-change').html(signInTemplate);
    $('.sign-in-form').on('submit', auth.onSignIn);
};
```

those are in my index.js file. then it starts getting really dicey. at the moment everything else is in my events.js file and I had to lay out the functions in a certain way so that they weren't used before being defined. 

this makes it so after you sign up it takes you right to the sign in screen. i wanted to have signUpSuccess in a separate folder but it would need to be required by events.js for onSignUp to call it. However in the signUpSuccess function it would need events.js to be able to call onSignIn which would make it circular

``` js
// when sign up is successful the sign in form html is loaded and an 
// event listener is added to the sign in submit button
const signUpSuccess = () => {
  let signInTemplate = require('../templates/sign-in.handlebars');
  $('.content-change').html(signInTemplate);
  $('.sign-in-form').on('submit', onSignIn);
};

//prevents page from refreshing and calls a function from ./api
//the function it calls from ./api sends an ajax request to sign a new user up
const onSignUp = function (event) {
  let data = getFormFields(this);
  event.preventDefault();
  api.signUp(data)
    .done(signUpSuccess)
    .fail(ui.failure);
};
```

I was able to get it all working until I got to the last step which was sign out. I wanted to have the user be brought back to the landing page where sign up and sign in buttons would be activated again. however since they are all in the same file it creates this problem of calling functions before they are defined. Even if I did get it working this way I realize its really bad practice to have all these different functions residing in the same file I just can't seem to lay out the files in a way that won't create a conflict.

didn't want to post the entire events.js file but if that would make it easier to see i can do that.

**Comment by gaand** [comment]
You need more files and need to pass around objects or functions.

**Comment by RealWeeks** [comment]
This may seem like a pain now, but it will help you very much over the course of the project if you refactor to have more modular code now.  This will resolve a lot of your issues, both seen and unseen. ;)

**Comment by jordanallain** [comment]
yes i mean that was my plan all along maybe i just should not have used handlebars since they were only introduced to us the day i started the project.

**Comment by jordanallain** [comment]
okay well i broke everything up into separate files and it feels like it put me further away from having everything working.

now after signing up it takes you to sign in but the sign in submit button refreshes the page. it wasn't doing this previously. should i scrap the idea of handlebars i feel like i'm really behind now.

**Comment by RealWeeks** [comment]
You're not behind. It's only the first half of day 2.  Ultimately it's your choice, but I would recommend you keep at it.  Take a look at the solution branch for the `handlebars` lesson if you need to follow some code.

**Comment by RealWeeks** [comment]
@jordanallain any updates on this, what have you done, what errors are you getting now?

**Comment by jordanallain** [comment]
i created files and moved functions around.

event listener in index.js when document has loaded.

``` js
  $('.sign-up-btn').on('click', show.showSignUp);
```

function to show the html for the sign up form and applies an event listener for the submit button

``` js
const showSignUp = function(){
  let signUpTemplate = require('./templates/sign-up.handlebars');
  $('.content-change').html(signUpTemplate);
  $('.sign-up-form').on('submit', auth.onSignUp);
};
```

when they click submit this function runs that stops the page from refreshing and gets the data they entered.

``` js
const onSignUp = function (event) {
  event.preventDefault();
  let data = getFormFields(this);
  api.signUp(data)
    .done(ui.signUpSuccess)
    .fail(ui.failure);
};
```

ajax call for signing up

``` js
const signUp = (data) => {
  return $.ajax({
    url: app.api + 'sign-up',
    method: "POST",
    data,
  });
};
```

if sign up was successful this function loads the html for sign in forms and applies an event listener to the submit button on the sign in form

``` js
const signUpSuccess = () => {
  let signInTemplate = require('../templates/sign-in.handlebars');
  $('.content-change').html(signInTemplate);
  $('.sign-in-form').on('submit', auth.onSignIn);
};
```

this function is supposed to stop the page from refreshing when submit is pressed and grab the data but instead the page just refreshes

``` js
const onSignIn = function (event) {
  event.preventDefault();
  let data = getFormFields(this);
  api.signIn(data)
    .done(ui.signInSuccess)
    .fail(ui.failure);
};
```

this function is similar to signUpSuccess. when the page initially loads there is a sign in button that when pressed calls this function to load the sign in form and attach the submit click handler. it points to the function above that prevents default and grabs the data. it works when i access it first without signing up first.

``` js
const showSignIn = function(){
    let signInTemplate = require('./templates/sign-in.handlebars');
    $('.content-change').html(signInTemplate);
    $('.sign-in-form').on('submit', auth.onSignIn);
};
```

**Comment by gaand** [comment]
Do you get an errors in the console before clicking submit on sign in?

**Comment by jordanallain** [comment]
no

**Comment by gaand** [comment]
Okay.  I'll have a look.

**Comment by gaand** [comment]
Circular dependencies in require/export.  Leaving open for now.

**Comment by jordanallain** [comment]
still having the same issue where the sign in form's submit button is refreshing the page if you get to the sign in form after signing up. guess i didn't understand Antony's help as much as i had hoped.

after sign up is successful i am trying to trigger the sign in form which it does but like i mentioned the submit button is apparently not getting the event handler it should have. 

i tried this where 'show' is a variable containing the required file that 'showSignIn' resides

``` js
const signUpSuccess = () => {
  show.showSignIn();
};
```

but couldn't get it to work so i tried just using the code i got with Antony that loads initially with the page, but had the same issue.

``` js
const signUpSuccess = () => {
  show.showHome({
    onSignUp: auth.onSignUp,
    onSignIn: auth.onSignIn});
};
```

tried to emulate the showHome call by passing showSignIn this object

``` js
const signUpSuccess = () => {
  show.showSignIn({signIn: auth.onSignIn});
  };
```

then tried to access the value in the showSignIn function

``` js
const showSignIn = function(signIn){
    const signInTemplate = require('./templates/sign-in.handlebars');
    $('.content-change').html(signInTemplate);
    $('.sign-in-form').on('submit', signIn.signIn);
};
```

i realize the naming i've used is dumb but i've been working on this issue for 14 hours i guess so my brain is probably a puddle by now. will try to get some sleep and figure this out in the morning. not sure if i'm on the right track or not.

btw not sure if i'm looking at the right solution branch in the handlebars repo but didn't really see anything helpful in there. a lot of the code is commented out and i think one of the solution branches says "intentionally broke code to give to students" so it was kind of confusing.

**Comment by gaand** [comment]
What's the value of `auth.onSignIn` in `signUpSuccess`?  What's the value of `signIn.signIn` in `showSignIn`?

**Comment by jordanallain** [comment]
they are both undefined

**Comment by gaand** [comment]
If you just click the sign in button from home does that work?

**Comment by jordanallain** [comment]
if you go to the sign in form from home and click the submit button it is not working properly anymore. the page just refreshes. i must have changed something last night while my brain was mush because last time i tried to sign in from home it worked fine.

**Comment by jordanallain** [comment]
when i changed signIn.signIn back to just signIn in the second example the sign in form is working properly again from the home page.

``` js
const showSignIn = function(signIn){
    const signInTemplate = require('./templates/sign-in.handlebars');
    $('.content-change').html(signInTemplate);
    $('.sign-in-form').on('submit', signIn.signIn);
};
```

``` js
const showSignIn = function(signIn){
    const signInTemplate = require('./templates/sign-in.handlebars');
    $('.content-change').html(signInTemplate);
    $('.sign-in-form').on('submit', signIn);
};
```

**Comment by gaand** [comment]
Try this:

``` diff
 const signUpSuccess = () => {
-   show.showSignIn({signIn: auth.onSignIn});
+   show.showSignIn(auth.onSignIn);
 };
```

**Comment by jordanallain** [comment]
onSignIn is undefined

**Comment by gaand** [comment]
You most likely have a circular reference.  Let's see if we can find and fix it.

**Comment by gaand** [comment]
Teased out circular reference.

**Comment by gaand** [comment]
@jordanallain Have you resolved this issue?  If so, please comment and close.

**Comment by jordanallain** [comment]
still working on it sorry took a break to eat

**Comment by laurenfazah** [comment]
Never apologize for eating!

**Comment by gaand** [comment]
Eating is nothing to apologize for!

**Comment by jordanallain** [comment]
apologizing for not having been able to work it out yet

**Comment by laurenfazah** [comment]
Still, nothing to apologize for.

**Comment by jordanallain** [comment]
i just feel like after 2+ days and sitting down with Antony twice I should have a better grasp on what is going on here. i realize i'm close but without Antony helping me write what i have so far i would have not got to this point.

**Comment by gaand** [comment]
None of us can do this alone.  You set yourself a hard task for someone who's only been doing this for 6 weeks.  If you can move forward from where are (even if that requires some more help), it's less important how you got there.

**Comment by laurenfazah** [comment]
To add to Antony's comment, we have all felt that exact same way MANY times getting to the point we are at. This is not a unique feeling to you and you shouldn't put yourself down for having these feelings. 

I've found that when I try to maneuver understanding really difficult concepts, the first go (or first few goes) at it can be a matter of just getting it done with as much assistance as possible. Then, one day, you'll revisit or reflect upon that concept and a big "OH" moment of enlightenment will strike. 

If handlebars is that for you this project, so be it. Ask as many questions as you need to and try your best to not only keep a growth mindset, but don't think negatively of yourself for finding this difficult.

**Comment by jordanallain** [comment]
thank you. i didn't realize what i was setting myself up for with this but it would be a shame to abandon it now. can't help but feel like i'm not leaving myself much time for the back end. i haven't even thought about the actual logistics of the app or the seed data or the third party api or anything really because its been such a struggle to get through this authentication process.

**Comment by gaand** [comment]
Don't worry about 3rd party APIs.  Get a few players with a few attributes and some favorites from users and your most of the way to meeting expectations.

**Comment by jordanallain** [comment]
i changed the function that runs after sign in succeeds to this which makes the change password button open the change password form.

``` js
const showAfterSignedIn = function(changePassSignOut){
  const afterSignedInTemplate = require('./templates/after-signed-in.handlebars');
  $('.content-change').html(afterSignedInTemplate);
  $('.change-password-btn').on('click', function(){showChangePassword(changePassSignOut.onChangePassword);});
  $('.sign-out-btn').on('click', function(){showSignOut(changePassSignOut.onSignOut);});
};
```

it calls this function which i'm trying to pass in onChangePassword to but I must be doing it wrong because the change password submit button still prevents default

``` js
const showChangePassword = function(onChangePassword){
  const changePasswordTemplate = require('./templates/change-password.handlebars');
  $('.content-change').html(changePasswordTemplate);
  $('.change-password-form').on('submit', onChangePassword);
};
```

do i have to change the parameter to an object again? still struggling with this.

**Comment by laurenfazah** [comment]
I might be behind in understanding your code, but I'm not clear on what you're asking...

**Comment by jordanallain** [comment]
i'm trying to use handlebars to load the HTML for each form instead of using bootstrap.

when someone signs in successfully this function happens

``` js
const signInSuccess = (data, changePassword) => {
  app.user = data.user;
  show.showAfterSignedIn(changePassword);
};
```

then it loads the showAfterSignedIn HTML from the file assigned to 'show'. this shows a sign out and change password button and applies event listeners

``` js
const showAfterSignedIn = function(changePassSignOut){
  const afterSignedInTemplate = require('./templates/after-signed-in.handlebars');
  $('.content-change').html(afterSignedInTemplate);
  $('.change-password-btn').on('click', function(){showChangePassword(changePassSignOut.onChangePassword);});
  $('.sign-out-btn').on('click', function(){showSignOut(changePassSignOut.onSignOut);});
};
```

when you click the change password button it shows the change password form and i'm also trying to assign the event handler but i don't think its working because it doesn't prevent the page from refreshing which is the first line of the onChangePassword function

``` js
const showChangePassword = function(onChangePassword){
  const changePasswordTemplate = require('./templates/change-password.handlebars');
  $('.content-change').html(changePasswordTemplate);
  $('.change-password-form').on('submit', onChangePassword);
};
```

**Comment by gaand** [comment]
Please post the code that calls `signInSuccess`.

**Comment by jordanallain** [comment]
``` js
const onSignIn = function (event) {
  event.preventDefault();
  let data = getFormFields(this);
  api.signIn(data)
    .done(function(resp){ui.signInSuccess(resp, onChangePassword);})
    .fail(ui.failure);
};
```

**Comment by gaand** [comment]
As defined, `showAfterSignedIn` is expecting an argument that is an object (since you're referencing properties using the dot notation).  But it look like you may just be passing a function to it (`onChangePassword` via `signInSuccess`).

``` diff
 const onSignIn = function (event) {
   event.preventDefault();
   let data = getFormFields(this);
   api.signIn(data)
-    .done(function(resp){ui.signInSuccess(resp, onChangePassword);})
+    .done(function(resp){ui.signInSuccess(resp, {onChangePassword, onSignOut});})
     .fail(ui.failure);
 };
```

Can you see how the above should fix the issue?  Does it?

**Comment by jordanallain** [comment]
yes that makes sense i even mentioned a few comments ago that maybe i should try to change the parameter to an object. i thought i did try it after that but i must have either forgot to try it or put it in the wrong place.

i'm going to make this issue chain my epitaph.

hopefully i'll be able to close this tomorrow.

**Comment by jordanallain** [comment]
after wrestling with this for days i have decided to give in and go back to bootstrap like we have done previously. i would suggest not trying this route to anyone thinking about using handlebars in this fashion after just learning it.
