### ISSUE TITLE
require handlebars failed

### ISSUE THREAD

**Issue by EchoXin** [ga-wdi-boston/full-stack-project#366]
Here is the code in the index.js

```
let allDiary = require('./templates/all-diary.handlebars');

```

this is the error:

./assets/scripts/templates/all-diary.handlebars
Module build failed: Error: Partial 'partial' not found
    at tryExtension (/Users/xinying/wdi/projects/Diary-SPA-Project/node_modules/handlebars-loader/index.js:236:34)

**Comment by RealWeeks** [comment]
Can you go into the root your project directory and type `find assets/scripts` so we can see your file structure.  Please copy and paste the text in a snippet.

**Comment by EchoXin** [comment]
assets/scripts
assets/scripts/app.js
assets/scripts/auth
assets/scripts/auth/api.js
assets/scripts/auth/events.js
assets/scripts/auth/ui.js
assets/scripts/diary
assets/scripts/diary/api.js
assets/scripts/diary/events.js
assets/scripts/diary/ui.js
assets/scripts/example.js
assets/scripts/index.js
assets/scripts/templates
assets/scripts/templates/all-diary.handlebars
assets/scripts/templates/home.handlebars
assets/scripts/templates/sign-out.handlebars
assets/scripts/templates/sign-up.handlebars

**Comment by RealWeeks** [comment]
Can you paste in your handlebars template

**Comment by EchoXin** [comment]
it's an empty file

**Comment by RealWeeks** [comment]
so where is the partial from this coming from `Module build failed: Error: Partial 'partial' not found`.  Do you have any handlebars templates?

**Comment by EchoXin** [comment]
There are some comments like this:

```
<!-- {{> partial}} -->
<!-- Don't uncomment yet -->
```

I removed that and it works now. Thank you

-Updated to correct code blocks - @j-weeks
