### ISSUE TITLE
curl PATCH request 

### ISSUE THREAD

**Issue by natGalynker** [ga-wdi-boston/full-stack-project#367]
I have successfully done sign-up and sign-in POST requests for the user through curl for several users but I have been consistently getting an error on PATCH.

```Started PATCH "/change-password/3" for ::1 at 2016-08-18 11:11:18 -0400
Processing by UsersController#changepw as _/_
  Parameters: {"{\n    \"passwords\": {\n      \"old\": “vet123\",\n      \"new\": “change123\"\n    }\n  }"=>"[FILTERED]", "id"=>"3"}
  Rendered text template (0.0ms)
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 2ms (Views: 1.1ms | ActiveRecord: 0.0ms)

```
terminal prints out: 
```

 curl --include --request PATCH http://localhost:3000/change-password/3 \ --header "Authorization: Token token= df77a66b2983699519c47ee586eed010” \ --header "Content-Type: application/json” \  --data '{

> ```
> "passwords": {
>   "old": “vet123",
>   "new": “change123"
> }
> ```
> 
>   }'
> HTTP/1.1 401 Unauthorized 
> X-Frame-Options: SAMEORIGIN
> X-Xss-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> WWW-Authenticate: Token realm="Application"
> Content-Type: text/html; charset=utf-8
> Vary: Origin
> Cache-Control: no-cache
> X-Request-Id: 88944953-e65d-4b08-a64c-62e28cede44d
> X-Runtime: 0.017102
> Server: WEBrick/1.3.1 (Ruby/2.3.0/2015-12-25)
> Date: Thu, 18 Aug 2016 15:11:18 GMT
> Content-Length: 27
> Connection: Keep-Alive

HTTP Token: Access denied.
curl: (6) Could not resolve host:  --header
curl: (6) Could not resolve host: Authorization: Token token= df77a66b2983699519c47ee586eed010” \ --header Content-Type
curl: (6) Could not resolve host: application
curl: (6) Could not resolve host:  
~/wdi/projects/vets-rails-project (master)$ 

```

```

**Comment by gaand** [comment]
Are you running curl directly from the command line or from a script?

In the above, you don't seem to have the backticks in the right places, so it's hard to tell what arguments are actually being passed to curl.

**Comment by laurenfazah** [comment]
Also, judging by this, looks like you may have a formatting issue:

```
curl: (6) Could not resolve host: Authorization: Token token= df77a66b2983699519c47ee586eed010” \ --header Content-Type
```

**Comment by natGalynker** [comment]
Yes I, directly from the command line, this is what I sent as my request for each POST (sign-up, sign-in) and PATCH for change-password:

```
~/wdi/projects/vets-rails-project (master)$ curl --include --request POST http://localhost:3000/sign-up \
   --header "Content-Type: application/json" \
   --data '{
     "credentials": {
       "email": "blue@girl.com",
       "password": "vet123",
       "password_confirmation": "vet123"
     }
  }'

curl --include --request POST http://localhost:3000/sign-in \
     --header "Content-Type: application/json" \
     --data '{
       "credentials": {
         "email": "blue@girl.com",
         "password": "vet123"
       }
     }'

curl --include --request PATCH http://localhost:3000/change-password/3 \ --header "Authorization: Token token= df77a66b2983699519c47ee586eed010” \ --header "Content-Type: application/json” \  --data '{
     "passwords": {
       "old": “vet123",
       "new": “change123"
     }
   }'
```

I tried to reformat the patch, this happened:

```
HTTP/1.1 401 Unauthorized 
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
WWW-Authenticate: Token realm="Application"
Content-Type: text/html; charset=utf-8
Vary: Origin
Cache-Control: no-cache
X-Request-Id: 74efb86b-8b00-4674-a642-8c65f5ab67e9
X-Runtime: 0.032320
Server: WEBrick/1.3.1 (Ruby/2.3.0/2015-12-25)
Date: Thu, 18 Aug 2016 17:19:28 GMT
Content-Length: 27
Connection: Keep-Alive

HTTP Token: Access denied.
curl: (6) Could not resolve host: application
```

my reformat was:

```
curl --include --request PATCH http://localhost:3000/change-password/3 \
--header "Authorization: Token token= df77a66b2983699519c47ee586eed010” \
--header "Content-Type: application/json” \
--data '{
   "passwords": {
       "old": “vet123",
       "new": “change123"
 }
    }'
```

**Comment by RealWeeks** [comment]
trying creating a different user and changing their password. what happens then?

**Comment by laurenfazah** [comment]
I believe it's the space between your token and the equals sign. That's what I was trying to point at in my last comment.

**Comment by natGalynker** [comment]
```
curl --include --request PATCH http://localhost:3000/change-password/1 \
--header "Authorization: Token token = 171e45432be0718924446addfeae7624” \
--header "Content-Type: application/json” \
--data '{
   "passwords": {
       "old": “vet123",
       "new": “change123"
 }
    }'
```

During one of my rollbacks the database got cleared. I created a new user and signed in. Both the POST requests were successful. I posted the PATCH request which returned this error: 

```
HTTP/1.1 401 Unauthorized 
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
WWW-Authenticate: Token realm="Application"
Content-Type: text/html; charset=utf-8
Vary: Origin
Cache-Control: no-cache
X-Request-Id: c6f079e2-9e32-4cb0-8c04-eed760af52d2
X-Runtime: 0.003424
Server: WEBrick/1.3.1 (Ruby/2.3.0/2015-12-25)
Date: Thu, 18 Aug 2016 17:50:49 GMT
Content-Length: 27
Connection: Keep-Alive

HTTP Token: Access denied.
curl: (6) Could not resolve host: application
```

**Comment by laurenfazah** [comment]
Opposite...that space (and now those spaces) should not be there.

`Token token=171e45432be0718924446addfeae7624`

**Comment by natGalynker** [comment]
No dice. Same error returned

**Comment by gaand** [comment]
Are you sure the the old password and tokens are correct?

**Comment by RealWeeks** [comment]
After correcting with @laurenfazah and @gaand  advice test by again creating a new user and try changing their password to make sure that the token and passwords are correct.

**Comment by natGalynker** [comment]
I made sure the old password matched up with what I set up in the PATCH request. I navigated to the dababase with rake db to ensure I was in the correct directory and used the token associated with the new user I just created and signed in successfully. This is the return from the most recent PATCH attempt:

```
curl --include --request PATCH http://localhost:3000/change-password/3 \                                                           --header "Authorization: Token token=907989684d82f586ad7c2e7c46557e5e" \                                                                                                    --header "Content-Type: application/json"                                                                                                                                   --data '{              
    "passwords": {
      "old": "attempt123",
      "new": "test123"                      
    }
  }'
HTTP/1.1 401 Unauthorized 
....
HTTP Token: Access denied.
curl: (6) Could not resolve host:  
curl: (6) Could not resolve host:  
```

```
```

**Comment by RealWeeks** [comment]
The most recent or the first? If you sign in again you will be given another token.

**Comment by gaand** [comment]
The above is not a valid curl request.  You have improperly matched quotes.

**Comment by natGalynker** [comment]
Oh! That didn't translate properly. This is the curl request I just made:

```
curl --include --request PATCH http://localhost:3000/change-password/3 \                                                           --header "Authorization: Token token=907989684d82f586ad7c2e7c46557e5e" \                                                                                                    --header "Content-Type: application/json"                                                                                                                                   --data '{
    "passwords": {
      "old": "attempt123",
      "new": "test123"
    }              
  }'
```

The most recent. I created a user with a POST request, signed-in with a POST and this was my attempt at PATCH with changing password. Did not re-use the user information, all new instances.

**Comment by natGalynker** [comment]
It did it again,

``` bash
curl --include --request PATCH http://localhost:3000/change-password/3 \                                                          
--header "Authorization: Token token=907989684d82f586ad7c2e7c46557e5e" \  
--header "Content-Type: application/json"                                                                                                                                   --data '{
    "passwords": {
      "old": "attempt123",
      "new": "test123"
    }              
  }'
```

**Comment by natGalynker** [comment]
When I try to put it in fences, the --header Authorization and Content lines get deleted and when I don't do that the braces get altered

**Comment by RealWeeks** [comment]
weird, strange

**Comment by RealWeeks** [comment]
I fixed it for you.  Whatever you're writing it in and then pasting has some odd spacing and invisible characters. Try writing out your curl request in atom then pasting it in the the terminal or issues.

**Comment by natGalynker** [comment]
Is that what is effecting the curl request too?

I used atom to write it out this time and pasted it in from there.

I did not get the same could not resolve host errors:

Started PATCH "/change-password/3" for ::1 at 2016-08-18 15:16:57 -0400
Processing by UsersController#changepw as _/_
  Parameters: {"passwords"=>"[FILTERED]", "id"=>"3"}
  User Load (0.2ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "f"]]
  Rendered text template (0.0ms)
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.2ms | ActiveRecord: 0.2ms)

**Comment by RealWeeks** [comment]
Nice, ok. that looks like it was part of the problem.  I didn't look at the request to see if it was clean yet, but did you try to create a user again and then change the password

**Comment by natGalynker** [comment]
Same unauthorized error printed out. New user was created, used that user to sign in with the password with the sign-in POST request using curl. I just typed the following patch request out:

```
curl --include --request PATCH http://localhost:3000/change-password/4 \
  --header "Authentication: Token token=37e43b216e7388c66657d2235589c0f6" \
  --header "Content-Type: application/json" \
  --data '{
    "passwords": {
      "old": "shelter",
      "new": "clinic123"
    }
  }'
```

**Comment by laurenfazah** [comment]
Have you been working on other things besides this curl request? My opinion would be to timebox this and move onto other tasks for now.

**Comment by natGalynker** [comment]
Yes I have been. I have not been solely working on this curl request

**Comment by RealWeeks** [comment]
The error tells me that the request is being sent but you are not authorized, so either the ID is wrong, the token is wrong or the password is wrong.

**Comment by RealWeeks** [comment]
How are you getting your token?

**Comment by natGalynker** [comment]
After I create a user I use rake db to go to the database for the rails api. I then use SELECT \* FROM users to display the users and the user ID and token are listed there

**Comment by RealWeeks** [comment]
That's the problem. You have to get the token returned to you and use that in your change pw request.  You can't use the token stored in the db.

**Comment by natGalynker** [comment]
Thank you! That worked. The documentation on the rails template page had a much shorter token without the -- in the token. I was using that as a reference for the what I was looking for token-length wise.
