### ISSUE TITLE
ActiveModel::MissingAttributeError:

### ISSUE THREAD

**Issue by cdelsoin** [ga-wdi-boston/full-stack-project#369]
I've created a preset and joined it to the users table. When I attempt to shovel a preset into user 

`User.find(1).presets << Preset.find(1)`

I get 

`ActiveModel::MissingAttributeError: can't write unknown attribute`user_id` `

**Comment by gaand** [comment]
Have you pasted that error into google and looked at the results?

**Comment by cdelsoin** [comment]
i did but i guess ill look harder

**Comment by RealWeeks** [comment]
I think I may have found the answer: http://bfy.tw/7HUy

**Comment by RealWeeks** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7136645-136432832_2-s1-v1.png?transparent=1&width=246)  I hope you're feeling lucky

**Comment by cdelsoin** [comment]
Awesome! Thanks for the help
