### ISSUE TITLE
help with BootStrap

### ISSUE THREAD

**Issue by mkutter72** [ga-wdi-boston/full-stack-project#37]
I've done a quick check on the bootstrap document and it's not immediately evident how to accomplish the following:   I want to create a table that has rows of wines.   When want to be able to select a row then click a button to initiate further action on the item in the selected row

**Comment by GA-MEB** [comment]
@mkutter72 
Sorry for the slow response to this. To be clear, are you asking about how to make a table? Or are you asking how you indicate that a particular row in the table has been selected?

**Comment by gaand** [comment]
Or are you asking about handling an event on a table/list?
