### ISSUE TITLE
Displaying my images from my database

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/full-stack-project#370]
As you know, my app will have the ability to see images of work that SFX artist post.  I know that Lauren mentioned that embedding my images into the table might be easier.  I'm curious what you might think would be the best route for me.  

Should I be using a gem like paperclip to upload the image or will that be too complex?  I have been doing some reading on the matter, but I'm not sure which route is the safest for the amount of time that we have for this project.

**Comment by gaand** [comment]
Using paperclip would allow you to upload and then display images, but I think your should follow @laurenfazah 's suggestion to start and just enter urls from images already on the web.

**Comment by jlmitch1989** [comment]
ok

**Comment by gaand** [comment]
Once you've got that going, if you have time, or after presentations, we can look at using paperclip.

**Comment by RealWeeks** [comment]
@jlmitch1989 mind closing this until you're ready to get to it?

**Comment by jlmitch1989** [comment]
I actually already got it.  I used an image tag within my handlebars to change the url into an imbedded image.
