### ISSUE TITLE
Boostrap Modal Backdrop won't go away

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/full-stack-project#372]
After I click the sign-up button, the modal pops up and I sign up.  Once I click submit and exit the modal, a back drop is still hovering over my page, keeping me from being able to click anything on my page.  

I found something on stackoverflow that said try this:

``` js
$('.modal-backdrop').remove();
```

so I tried adding that here:

``` js
// Sign Up Modal Click Events
$(()=>{
  $('.sign-up').on('click', function(){
    // console.log('You clicked sign up');
    $('#sign-up-modal').modal('show');
    $('.save-sign-up').on('click', function(){
      // console.log('you clicked save sign out');
      $('#sign-up-modal').modal('hide');
      $('.modal-backdrop').remove();
    });
  });
});
```

I can't figure out why it won't go away, or why it's there to begin with.  None of the other modals do it.  Please help.

**Comment by jlmitch1989** [comment]
I added a z-index and that seems to work.  But now if I click the sign-up button and the modal pops up, then click the 'x' button to close it, it goes away.  And then click the sign up button again, the only thing that pops up is the top part of the modal with the 'x' button.

**Comment by laurenfazah** [comment]
I'd remove the `z-index` declaration.

Can you go back to after sign up when the modal backdrop is still there and right click/inspect the backdrop? What is the element (as the developer console shows you) that the entire backdrop is comprised of? Aka is it a `div` and what are its IDs and classes?

**Comment by laurenfazah** [comment]
Also, is this only happening with the sign up modal?

**Comment by RealWeeks** [comment]
This tends to be a problem with HTML formatting, but it's also a know bootstrap issue.  Check to make sure you tags are properly opened and closed.  Then play with the z-index

**Comment by jlmitch1989** [comment]
Like I said It works now after putting a z-index, 

"But now if I click the sign-up button and the modal pops up, then click the 'x' button to close it, it goes away. And then click the sign up button again, the only thing that pops up is the top part of the modal with the 'x' button."

**Comment by laurenfazah** [comment]
I really wouldn't play with `z-index` for this. It'll drop the backdrop to the background, which is why it looks like it's "working", but that z-index would still be applied when you click sign up again, hence why you're not seeing it again.

**Comment by laurenfazah** [comment]
It may look like it solved the issue, but it's really pushing you down another trail of frustrations.

**Comment by laurenfazah** [comment]
For troubleshooting, it would also be helpful to know if this is only happening for the sign up modal, or if it is happening with other modals you may have.

**Comment by RealWeeks** [comment]
when you do .remove() you are permanently removing a DOM element, this may cause some issues with bootstrap. You may want to think of another method.

**Comment by jlmitch1989** [comment]
Lauren, the sign-up modal is the only one doing this.  The others work just fine.

**Comment by laurenfazah** [comment]
Okay, so there must be some difference in either your HTML or jQuery with how you're handling the sign-up modal vs the others...

**Comment by jlmitch1989** [comment]
Well the jQuery for the modals are identical, and its identical to the tic-tac-toe game.

``` js
$(()=>{
  $('.sign-up').on('click', function(){
    // console.log('You clicked sign up');
    $('#sign-up-modal').modal('show');
    $('.save-sign-up').on('click', function(){
      // console.log('you clicked save sign out');
      $('#sign-up-modal').modal('hide');
    });
  });
});

// Sign In Modal Click Events
$(()=>{
  $('.sign-in').on('click', function(){
    // console.log('You clicked Sign In!');
    $('#sign-in-modal').modal('show');
    $('.save-sign-in').on('click', function(){
      // console.log('You clicked Submit');
      $('#sign-in-modal').modal('hide');
    });
  });
});
```

**Comment by jlmitch1989** [comment]
My HTML for my modals are all the same too, with the exception of the forms.

**Comment by laurenfazah** [comment]
Hmm....the IDs for the modals in their HTML are specific to each, though? Just want to make sure there aren't any repeated IDs in the markup

**Comment by jlmitch1989** [comment]
Like I said its identical with my tic-tac-toe modals, ID names and all.  I didn't have this issue at all with my tic-tac-toe game.  I've looked through it several times and i cant find any issues.

**Comment by RealWeeks** [comment]
Can you post the markup?

**Comment by jlmitch1989** [comment]
``` html
  <!-- START OF SIGN UP MODAL -->
      <div class="modal fade" id="sign-up-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-body">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <form id="sign-up">
                <fieldset>
                  <legend>Sign up!</legend>
                  <input type="text" name="credentials[email]" placeholder="e-mail">
                  <input type="password" name="credentials[password]" placeholder="password">
                  <input type="password" name="credentials[password_confirmation]" placeholder="password confirmation"><br>
                  Are you an SFX artist?<br>
                  <input type="radio" name="credentials[artist]" value="true">Yes<br>
                  <input type="radio" name="credentials[artist]" value="false">No<br>
                  <input type="submit" name="submit" value="Sign up!">
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
<!-- END OF SIGN UP MODAL -->
<!-- START OF SIGN IN MODAL -->
      <div class="modal fade" id="sign-in-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-body">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <form id="sign-in">
                <fieldset>
                  <legend>Sign in!</legend>
                  <input type="text" name="credentials[email]" placeholder="e-mail">
                  <input type="password" name="credentials[password]" placeholder="password">
                  <input type="submit" name="submit" value="Sign in!">
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
<!-- END OF SIGN IN MODAL -->

```

**Comment by RealWeeks** [comment]
Hmm, I may have to take a look on Monday.

**Comment by RealWeeks** [comment]
@jlmitch1989 Please write your solution and close this issue

**Comment by jlmitch1989** [comment]
The issue started because there was an incorrect ID name within the HTML.
