### ISSUE TITLE
Heroku Internal Server Error on deloyment

### ISSUE THREAD

**Issue by gabescarbrough** [ga-wdi-boston/full-stack-project#373]
Receiving the following error when I try to open up my API on Heroku in the browser:

```
Internal Server Error

Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml`
WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26) at enigmatic-journey-45830.herokuapp.com:443
```

Looks like a similar issue to #249 but my secrets are in `.env` not `config/secrets.yml` as per the instructions for the project.

Is the issue that `.env` isn't being committed? How should I remedy this?

**Comment by laurenfazah** [comment]
.env shouldn't be committed. Those hold development and test environment keys only. 

You'll want to configure heroku from the command line with `heroku config:set SECRET_KEY_BASE=$(rake secret)` for a new key in your production environment.

**Comment by laurenfazah** [comment]
Based on your error, you'll also want to `heroku config` a `SECRET_TOKEN` (in addition to `SECRET_KEY_BASE` also.

**Comment by gabescarbrough** [comment]
So run `heroku config:set SECRET_KEY_BASE=$(rake secret)` then `heroku config:set SECRET_TOKEN=$(rake secret)`? Just want to double check before I run anything since I haven't done this before.

**Comment by gaand** [comment]
I think the error message includes legacy info,  You should just need SECRET_KEY_BASE

**Comment by gaand** [comment]
In the root of your api repo:  `heroku config:set SECRET_KEY_BASE=$(bin/rake secret)`

**Comment by gabescarbrough** [comment]
Ran `heroku config:set SECRET_KEY_BASE=$(rake secret)` before Antony responded again and still received same error.

Ran `heroku config:set SECRET_KEY_BASE=$(bin/rake secret)` and still received same error.

Restarted both times to see if that helped but no dice.

**Comment by laurenfazah** [comment]
What is your output from running `heroku config`?

**Comment by gabescarbrough** [comment]
```
DATABASE_URL:             postgres://rmjimsusityngj:HY4ZDwzsz50qIdQ-iziF7gYmDY@ec2-23-23-192-249.compute-1.amazonaws.com:5432/d9n11mp9t9a93j
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:  *secret key_base here*
```

There is actually a secret key_base. Just didn't paste for obvious reasons.

**Comment by laurenfazah** [comment]
Hmm. So looks like it was set. Are you still getting the same error as before or has the error changed?

**Comment by gabescarbrough** [comment]
Same error.

**Comment by laurenfazah** [comment]
And when you said you restarted, was that with `heroku restart`?

**Comment by gabescarbrough** [comment]
Yes.

**Comment by laurenfazah** [comment]
@gaand any ideas?

**Comment by RealWeeks** [comment]
GUI.

**Comment by RealWeeks** [comment]
Heroku.com > <appname> > settings/config (whatever) > reveal secret keys > enter console generated key

**Comment by gabescarbrough** [comment]
Just looked in the GUI. Same key as was shown in the command line.

**Comment by gaand** [comment]
Let me have a look.

**Comment by gabescarbrough** [comment]
Had to force add my secrets file to GitHub.

``` sh
git add --force config/secrets.yml
git commit
git push origin master
git push heroku master
```

Edited by @gaand to add `sh` as fenced code block language and `--force` to as flag to `git add <...>` command.

**Comment by jrhorn424** [comment]
This should be fixed in the near future by ga-wdi-boston/orientation#166
