### ISSUE TITLE
POST AJAX not working

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/full-stack-project#374]
So I have Form field with the information needed to update my 'creations' table. 

![screen shot 2016-08-19 at 3 22 02 pm](https://cloud.githubusercontent.com/assets/19956362/17821653/bfab33d4-6620-11e6-9471-9d9a7dd5dc60.png)

Here is my ajax request:

``` js
  // ADD CREATION AJAX
  const addCreation = (data) => $.ajax({
    url: app.api + '/creations/',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data,
  });
```

This is what my console gives me.
![screen shot 2016-08-19 at 3 24 02 pm](https://cloud.githubusercontent.com/assets/19956362/17821731/258ec454-6621-11e6-9d97-f87f5deed516.png)

Here are my creation_params:

``` js
  def creation_params
      params.require(:creation).permit(:title, :picture, :artist_name, :description, :user_id)
    end
end
```

**Comment by laurenfazah** [comment]
In that AJAX request, are you sure `app.user.token` is set correctly?

**Comment by jlmitch1989** [comment]
I actually mistakenly put "user_id" in my params, thats no longer in there and I'm still getting the same error in my console

**Comment by jlmitch1989** [comment]
I mean it shouldn't be that much different from the tic-tac-toe games "create game".  So I would assume that it should work just fine.  But I'm not 100%

**Comment by laurenfazah** [comment]
Can you console.log it in your `addCreation` function to confirm?

**Comment by RealWeeks** [comment]
What does your rails server error say?

**Comment by jlmitch1989** [comment]
![screen shot 2016-08-19 at 3 36 42 pm](https://cloud.githubusercontent.com/assets/19956362/17822033/c358f780-6622-11e6-8739-785d81489ac1.png)

**Comment by RealWeeks** [comment]
looks like a param is missing.  Next please copy and paste text in code blocks instead of screen shots.

**Comment by RealWeeks** [comment]
Compare your strong params (the stuff in the bottom of your controller) to the params your trying to send to your API, what's missing?

**Comment by RealWeeks** [comment]
You have to read your errors. This is a very clear one.  Please be more meticulous in reading your errors.

**Comment by jlmitch1989** [comment]
My console:

```
data: Object {title: "burn victim", picture: "https://s-media-cache-ak0.pinimg.com/236x/a3/cf/05/a3cf0571990cb35f4a9e92b5d32167d3.jpg", artist_name: "Poop1", description: "makeup!"}
:3000/creations/:1 POST http://localhost:3000/creations/ 
:8080/#:1 XMLHttpRequest cannot load http://localhost:3000/creations/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
jquery.js:9175 XHR failed loading: POST "http://localhost:3000/creations/".send @ jquery.js:9175ajax @ jquery.js:8656addCreation @ api.js:36addMyCreation @ events.js:49dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
ui.js:20 Object {readyState: 0, status: 0, statusText: "error"}
```

My strong params:

``` rb
  def creation_params
      params.require(:creation).permit(:title, :picture, :artist_name, :description)
    end
```

**Comment by jlmitch1989** [comment]
I already knew that the error was pointing at my params.  Thats why I initially tried putting user_id a new param because I have been trying to figure out why it keeps giving me this error

**Comment by RealWeeks** [comment]
what param are you not passing? Hint: the rails server error is telling you which.

**Comment by jlmitch1989** [comment]
Everything in the params, is what I need to pass.  The rails server isn't telling me anything specific. I don't need 'creation' as a param. I tried it for the heck of it and it did the same thing.

**Comment by laurenfazah** [comment]
Is `creation` the root key of the data you're sending? This is to POST a new creation, yes? If so, I believe your rails server error is saying there is no root key of `creation`...

**Comment by jlmitch1989** [comment]
There are so many different definitions for root key online.  I'm not sure what you mean by this exactly.

**Comment by gaand** [comment]
When you create a new user, what do the parameters look like in the rails log?

**Comment by RealWeeks** [comment]
Remember tic-tac-toe, how did you have to send data then? You used a root key for that.

**Comment by laurenfazah** [comment]
Does this help?

```
data = {
  "root_key" : {
        "thing1": "value",
        "thing2": "value"
    }
}
```

**Comment by jlmitch1989** [comment]
But I do have a root key.  I even sent this curl request:

```
curl --include --request POST http://localhost:3000/creations \
  --header "Authorization: Token token=BAhJIiUzMzEyNzc2MWJjOTZmZTIyYTQ1MjJiMTU2ZGE5MmI0MgY6BkVG--e8ad78335c861dc08e96de43e23a926d3e5b8152" \
  --header "Content-Type: application/json" \
  --data '{
    “creation": {
      “title": “burn",
      “picture": “url.com”,
      “artist_name”: “poop”,
      “description”: “ciiiiiiii"
      "user-id": "1"
    }
}'

```

My server keeps giving me this error:

```
Started POST "/creations" for ::1 at 2016-08-20 16:50:48 -0400
Error occurred while parsing request parameters.
Contents:

{
    “creation": {
      “title": “burn",
      “picture": “url.com”,
      “artist_name”: “poop”,
      “description”: “ciiiiiiii"
      "user-id": "1"
    }
}

ActionDispatch::ParamsParser::ParseError (822: unexpected token at '{
    “creation": {
      “title": “burn",
      “picture": “url.com”,
      “artist_name”: “poop”,
      “description”: “ciiiiiiii"
      "user-id": "1"
    }
}'):

```

**Comment by RealWeeks** [comment]
There's the rot key! Looking at your error message from 2 days ago, you didn't have one.

The issue here is that you're not using valid characters.  Look closely at the quotes here, see how some of them are slanted and some of them are not.  The program you're writing them in and copying them out of has some formatting that it is adding.  Trying writing it in an atom file.

**Comment by jlmitch1989** [comment]
Even fixing those errors, it's still not working. I feel like I have tried everything to make this work.

**Comment by RealWeeks** [comment]
Are there new errors?

**Comment by jlmitch1989** [comment]
No its spitting out the same errors.

**Comment by RealWeeks** [comment]
post in the error message again, maybe there was a missed quote.  Try not to get frustrated, jumping from bug to bug is part of the coding process.

**Comment by jlmitch1989** [comment]
It's hard to not get frustrated after being stuck in the same spot for 3 days now.

This is the error from my chrome console:

```
data: Object {creations: Object}creations: Objectartist_name: "Poop1"description: "makeup"picture: "https://s-media-cache-ak0.pinimg.com/236x/a3/cf/05/a3cf0571990cb35f4a9e92b5d32167d3.jpg"title: "burn victim"__proto__: Object__proto__: Object
:3000/creations:1 POST http://localhost:3000/creations 
:8080/#:1 XMLHttpRequest cannot load http://localhost:3000/creations. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 500.
jquery.js:9175 XHR failed loading: POST "http://localhost:3000/creations".send @ jquery.js:9175ajax @ jquery.js:8656addCreation @ api.js:36addMyCreation @ events.js:48dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
ui.js:20 Object {readyState: 0, status: 0, statusText: "error"}failure @ ui.js:20fire @ jquery.js:3187fireWith @ jquery.js:3317done @ jquery.js:8759(anonymous function) @ jquery.js:9115
```

This is the error from my server:

```

Started POST "/creations" for ::1 at 2016-08-21 13:01:35 -0400
Processing by CreationsController#create as */*
  Parameters: {"creations"=>{"title"=>"burn victim", "picture"=>"https://s-media-cache-ak0.pinimg.com/236x/a3/cf/05/a3cf0571990cb35f4a9e92b5d32167d3.jpg", "artist_name"=>"Poop1", "description"=>"makeup"}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "db9cb19aaeb16201da268cc455394935"]]
Completed 500 Internal Server Error in 28ms (ActiveRecord: 13.9ms)

ActiveRecord::InverseOfAssociationNotFoundError (Could not find the inverse association for user (:creation in User)):
  app/controllers/creations_controller.rb:22:in `create'


```

**Comment by gaand** [comment]
Please post the code for the User and Creation models.

**Comment by jlmitch1989** [comment]
``` rb
# creation model
class Creation < ActiveRecord::Base
  belongs_to :user, inverse_of: :creation
end
```

``` rb
# User Model
class User < ActiveRecord::Base
  include Authentication
  has_many :creations, inverse_of: :user, foreign_key: 'user_id'
end
```

**Comment by gaand** [comment]
I think you're missing an `s`:

``` diff
 # creation model
 class Creation < ActiveRecord::Base
-  belongs_to :user, inverse_of: :creation
+  belongs_to :user, inverse_of: :creations
 end
```

**Comment by jlmitch1989** [comment]
Still getting the same errors after adding the 's' at the end of creation.

**Comment by gaand** [comment]
Did you restart the API?  Is it the same error from rails (ActiveRecord::InverseOfAssociationNotFoundError)?

**Comment by jlmitch1989** [comment]
I did restart the API, and it s giving this error from my rails server:

```
Started POST "/creations" for ::1 at 2016-08-21 14:30:12 -0400
Processing by CreationsController#create as */*
  Parameters: {"creations"=>{"title"=>"burn victim", "picture"=>"https://s-media-cache-ak0.pinimg.com/236x/a3/cf/05/a3cf0571990cb35f4a9e92b5d32167d3.jpg", "artist_name"=>"Poop1", "description"=>"Makeup!"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "f89d07f9cbb6c0079ce6ed01448f41cf"]]
Completed 400 Bad Request in 32ms (ActiveRecord: 1.3ms)

ActionController::ParameterMissing (param is missing or the value is empty: creation):
  app/controllers/creations_controller.rb:58:in `creation_params'
  app/controllers/creations_controller.rb:22:in `create'


```

**Comment by jlmitch1989** [comment]
So now it's giving me the error that I had before when y'all said I didn't have a root key.  So apparently I don't know what the heck is going on.

**Comment by gaand** [comment]
The data you sent:

```
Parameters: {"creations"=>{"title"=>"burn victim", "picture"=>"https://s-media-cache-ak0.pinimg.com/236x/a3/cf/05/a3cf0571990cb35f4a9e92b5d32167d3.jpg", "artist_name"=>"Poop1", "description"=>"Makeup!"}}
```

The error reported:

```
ActionController::ParameterMissing (param is missing or the value is empty: creation):
```

Plural keys are for arrays of data.  You're trying to create one thing so the key should be singular.

**Comment by jlmitch1989** [comment]
Wow. That worked. I could scream right now. Thank you.

**Comment by RealWeeks** [comment]
@jlmitch1989 Please close this issue since it's been solved.
