### ISSUE TITLE
Pushing to Heroku

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/full-stack-project#375]
I set my secret keys in my secrets.yml by mistake. I also have them in .env. 

I pushed it on the Github.

Should I remove them from secrets.yml, and push it again on Github before proceeding with Herouku?

**Comment by NatasaPeic** [comment]
Jason confirmed that I could proceed with Heroku this time. I deployed my api.

**Comment by RealWeeks** [comment]
Still unresolved @gaand how would you like to handle removing secrets?

**Comment by NatasaPeic** [comment]
True. Keys are pushed to Github. I thought that secret.yml file will be ignored by gitignore. I had the same issue as Gabe, and had to force my keys to Heroku.

**Comment by gaand** [comment]
Because they are not production secrets, I would just revert the secrets file to use the environment.

The keys should be stored in the `.env` file (development and test) or `heroku config:set <...>` (production), not in `config/secrets.yml`.

You did need to force add `config/secrets.yml` to git, just not the secrets themselves.

**Comment by NatasaPeic** [comment]
I forced config/secrets.yml just like that.

I have keys in .env file. And I had them in secrets.yml as well. 

If I revert my last commit, do I need to delete keys from secret.yml and push again?

**Comment by gaand** [comment]
Don't revert a commit unless the only change is to remove the red lines and adds the green lines in `config/secrets.yml`:

``` diff
 development:
-   secret_key_base: e2b4b449ad82e6cfdaafa21376e5268dcfed45b147abb1e578f7100619bd4b301e18af8fe58d9d9542276b1c83a858b20d3441506c339516c636a6f872777152
+   secret_key_base: <%= ENV['SECRET_KEY_BASE_DEVELOPMENT'] %>

 # Use different runs of `rake secret` for development and test
 test:
-  secret_key_base: 1be3de9a17e300a795d6c2a0719f68bcdc4d6c43be9e8700a973bb6939e04322a2501df6c8e1e6f75acdb0deb4bcbb9fc001880a331bb58039c22da42cc70dae
+  secret_key_base: <%= ENV['SECRET_KEY_BASE_TEST'] %>
```

The above is the change you want to make to `config/secrets.yml`.

**Comment by NatasaPeic** [comment]
Yes. That would be only change. I can remove keys and replace them like above. 

Thank you.
