### ISSUE TITLE
Can't sign in or sign up after I deployed my front end.

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/full-stack-project#379]
I wouldn't know where to look, but I can't sign in or sign up once my app is deployed. Everything works like it should locally.

**Comment by gaand** [comment]
What errors do you get when you try to sign up?  In the chrome console or in the heroku logs?

**Comment by NatasaPeic** [comment]
This is what I get for sign-up: 

```
/job-search-app-front-end/#:1 XMLHttpRequest cannot load https://thawing-spire-40526.herokuapp.com//sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://natasapeic.github.io' is therefore not allowed access.
2016-08-21 00:18:56.016 vendor.bundle.js:9285 XHR failed loading: POST "https://thawing-spire-40526.herokuapp.com//sign-up".send @ vendor.bundle.js:9285ajax @ vendor.bundle.js:8766signUp @ no-conflict.js:13onSignUp @ no-conflict.js:13dispatch @ vendor.bundle.js:4847elemData.handle @ vendor.bundle.js:4659
2016-08-21 00:18:56.018 no-conflict.js:13 Object {readyState: 0, status: 0, statusText: "error"}
```

**Comment by NatasaPeic** [comment]
This is what I get for sign in. (This email/password combination works locally)

```
/job-search-app-front-end/#:1 XMLHttpRequest cannot load https://thawing-spire-40526.herokuapp.com//sign-in. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://natasapeic.github.io' is therefore not allowed access.
2016-08-21 08:30:13.952 vendor.bundle.js:9285 XHR failed loading: POST "https://thawing-spire-40526.herokuapp.com//sign-in".send @ vendor.bundle.js:9285ajax @ vendor.bundle.js:8766signIn @ no-conflict.js:13onSignIn @ no-conflict.js:13dispatch @ vendor.bundle.js:4847elemData.handle @ vendor.bundle.js:4659
2016-08-21 08:30:13.953 no-conflict.js:13 Wrong Password!
```

**Comment by RealWeeks** [comment]
Please copy and paste in code blocks, do not use screenshots.

Look closely at the URL, what's wrong with it?

**Comment by NatasaPeic** [comment]
I can see #.

**Comment by NatasaPeic** [comment]
```js

const app = {
  api:  'https://thawing-spire-40526.herokuapp.com',
};

module.exports = app;

```

I had a slash at the end of url. I fixed that, redeployed again, but it still redirects me to another resource.

**Comment by gaand** [comment]
Did you set follow step 11 here https://github.com/ga-wdi-boston/rails-api-template/#installation ?

**Comment by NatasaPeic** [comment]
No. I just set it.

It this correct?

config/application.rb

``` rb
# Cross-Origin Resource Sharing
    config.middleware.use Rack::Cors do
      allow do
        origins ENV['CLIENT_ORIGIN'] || 'https://natasapeic.github.io'
        resource '*',
                 headers: :any,
                 methods: [:options, :get,
                           :post, :patch, :put, :delete]
      end
    end
  end
end
```

**Comment by RealWeeks** [comment]
You know the next question is going to be: did you test it out?

**Comment by NatasaPeic** [comment]
Yes. 30 seconds after I changed it. I still get the same errors.

**Comment by laurenfazah** [comment]
What does `heroku config` from the command line of your API repo print out? Do you see `CLIENT_ORIGIN` set there?

**Comment by gaand** [comment]
You should not change `config/application.rb`  You should set CLIENT_ORIGIN in the environment of you deployed api via heroku config:set 

With the change you made you won't be able to test your api locally

**Comment by NatasaPeic** [comment]
Would I run this in my terminal? Just want to double check.

heroku config:set CLIENT_ORIGIN=https://natasapeic.github.io

**Comment by NatasaPeic** [comment]
@laurenfazah 

It isn't set...

```
~/wdi/projects/project2/rails-api-template-master (master)$ heroku config
=== thawing-spire-40526 Config Vars
DATABASE_URL:             postgres://acedmbdhdkfgkt:exTB_85_9erl9Du3Y3_zwBSXS2@ec2-54-235-78-240.compute-1.amazonaws.com:5432/d4baf74l0089je
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:          ***
~/wdi/projects/project2/rails-api-template-master (master)$ 
```

**Comment by gaand** [comment]
Try it, then check.

Also, revert the change to `config/application.rb`

**Comment by NatasaPeic** [comment]
I reverted changes. And run the command in terminal. Now CLIENT_ORIGIN is set, but app is still not working. I pushed changes to Github too.

```
~/wdi/projects/project2/rails-api-template-master (master)$ heroku config
=== thawing-spire-40526 Config Vars
CLIENT_ORIGIN:            https://natasapeic.github.io
DATABASE_URL:             postgres://acedmbdhdkfgkt:exTB_85_9erl9Du3Y3_zwBSXS2@ec2-54-235-78-240.compute-1.amazonaws.com:5432/d4baf74l0089je
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:          ***
~/wdi/projects/project2/rails-api-template-master (master)$ 
```

**Comment by laurenfazah** [comment]
`https://natasapeic.github.io` - is that what your project is set to? Or is the project at a different URL?

**Comment by NatasaPeic** [comment]
I followed step 11.

`In order to make requests from your deployed client application, you will need to set CLIENT_ORIGIN in the environment of the production API (e.g. https://<github-username>.github.io).`

**Comment by NatasaPeic** [comment]
I will set it again with my URL.

**Comment by NatasaPeic** [comment]
Set it. Not working still.

```
~/wdi/projects/project2/rails-api-template-master (master)$ heroku config
=== thawing-spire-40526 Config Vars
CLIENT_ORIGIN:            https://natasapeic.github.io/job-search-app-front-end/
DATABASE_URL:             postgres://acedmbdhdkfgkt:exTB_85_9erl9Du3Y3_zwBSXS2@ec2-54-235-78-240.compute-1.amazonaws.com:5432/d4baf74l0089je
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:          000dc39450b69c3480a8f1786387c4db631084906b5f459434289c09184e5de948dc712dd611cd29dab3906ed32e5637c009e64a0682b5afcce800b2475760fe
~/wdi/projects/project2/rails-api-template-master (master)$ 
```

**Comment by laurenfazah** [comment]
Is the error the same?

**Comment by NatasaPeic** [comment]
The same errors.

**Comment by gaand** [comment]
CLIENT_ORIGIN without a path is correct.

Did you restart your api server after setting the environment variable?

**Comment by NatasaPeic** [comment]
No. I will restart it now and revert changes.

**Comment by NatasaPeic** [comment]
Reverted changes. 

```

~/wdi/projects/project2/rails-api-template-master (master)$ heroku config
=== thawing-spire-40526 Config Vars
CLIENT_ORIGIN:            https://natasapeic.github.io
DATABASE_URL:             postgres://acedmbdhdkfgkt:exTB_85_9erl9Du3Y3_zwBSXS2@ec2-54-235-78-240.compute-1.amazonaws.com:5432/d4baf74l0089je
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:          000dc39450b69c3480a8f1786387c4db631084906b5f459434289c09184e5de948dc712dd611cd29dab3906ed32e5637c009e64a0682b5afcce800b2475760fe
~/wdi/projects/project2/rails-api-template-master (master)$ 
```

Run in terminal:

```
 heroku restart

 heroku open
```

Still not working.

**Comment by RealWeeks** [comment]
Give it up to 30 minutes, sometimes it take a while for heroku to reflect new changes. This probably isn't it, but best to be safe.

**Comment by NatasaPeic** [comment]
Ok. One more detail. I used rails template Antony shared on the very first day we started learning Rails. I believe some other people used that template too. That is why I had CLIENT_URL in my application.rb instead of CLIENT_ORIGIN. I changed it to CLIENT_ORIGIN, committed again, pushed too. Restarted Heroku again.

Does that have anything to do with errors I'm getting?

**Comment by gaand** [comment]
When I load your front end I get these messages:

```
Mixed Content: The page at 'https://natasapeic.github.io/job-search-app-front-end/' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/inpGl4E.png'. This content should also be served over HTTPS.
natasapeic.github.io/:482 Mixed Content: The page at 'https://natasapeic.github.io/job-search-app-front-end/' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/qqnj5wI.png'. This content should also be served over HTTPS.
natasapeic.github.io/:488 Mixed Content: The page at 'https://natasapeic.github.io/job-search-app-front-end/' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/2G6XD0s.png'. This content should also be served over HTTPS.
https://natasapeic.github.io/job-search-app-front-end/bootstrap.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
natasapeic.github.io/:1 Mixed Content: The page at 'https://natasapeic.github.io/job-search-app-front-end/' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/A2sFs1E.jpg'. This content should also be served over HTTPS.
natasapeic.github.io/:1 Mixed Content: The page at 'https://natasapeic.github.io/job-search-app-front-end/' was loaded over HTTPS, but requested an insecure favicon 'http://i.imgur.com/5LKtdmr.png'. This content should also be served over HTTPS.
https://natasapeic.github.io/job-search-app-front-end/bootstrap.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

It does not appear you are using the template as designed.

This may be unrelated to your issue signing up.

Have you signed up on the deployed api using curl?

**Comment by NatasaPeic** [comment]
Ok. I will try to fix that. Thank you.

**Comment by gaand** [comment]
I just checked the network tab after trying to sign up and it succeeded (but I got the error in the console).  

So it's likely that the problem isn't with the api on signup, but with the deployed code.

**Comment by gaand** [comment]
When I tried to sign in that was successful on the api as well, but the front end got an error.

Would you please post the code that handles sign up?  Thanks.

**Comment by NatasaPeic** [comment]
events.js

``` js
// Sign up
const onSignUp = function (event) {
  event.preventDefault();
  let data = getFormFields(this);

   api.signUp(data)
   .done(ui.onSuccess)
   .fail(ui.failure);
};

const showSignUpModal = function showSignUpModal(){
  $('#sign-up-modal').modal('show');
};

const closeModalSignUp = function closeModalSignUp() {
    $('#sign-up-modal').modal('hide');
};


const addHandlers = () => {


    $('#sign-up-modal-link').on('click', showSignUpModal);
    $('#sign-up').on('submit', onSignUp);
    $('#sign-up1').on('click', closeModalSignUp);

}
```

api.js

``` js
const signUp = (data) => $.ajax({
    url: app.api + '/sign-up',
    method: 'POST',
    data,
   });

```

**Comment by NatasaPeic** [comment]
I will fix the template part now. Problem with loading files like images and bootstrap.min etc. Not sure if I can replce it all, so it all works again.

**Comment by gaand** [comment]
The template already includes bootstrap, so you shouldn't need to load that.

For the imgur files, just change the scheme to https.

**Comment by NatasaPeic** [comment]
I have separate css folder that handles my styling. That is why it is failing to load those css files. Not sure how to handle that other than to copy everything in css folder this js-template provided and to reference it it my html. I did that, but my styling now looks completely off.

**Comment by gaand** [comment]
I'm still seeing an extra slash in the url of the deployed client.  I don't think this is the issue, but I'm concerned that what's deployed and what you think is deployed may not match.

**Comment by NatasaPeic** [comment]
True. Not sure where that slash is coming from. I can set my CLIENT_ORIGIN again with that slash. Restart and try again.

**Comment by gaand** [comment]
Use `assets/styles/index.scss` to import them.  Put the files in  `assets/styles/` or a subdirectory of that.

**Comment by gaand** [comment]
This is on the url set in the client app you deploy to github pages.

**Comment by NatasaPeic** [comment]
This is so very confusing. Now I can't do anything locally either. I pushed my changes to heroku.

I can sign in on my live app, but I get errors.

```

vendor.bundle.js:9285 XHR finished loading: POST "https://thawing-spire-40526.herokuapp.com/sign-in".send @ vendor.bundle.js:9285ajax @ vendor.bundle.js:8766signIn @ no-conflict.js:13onSignIn @ no-conflict.js:13dispatch @ vendor.bundle.js:4847elemData.handle @ vendor.bundle.js:4659
2016-08-21 14:09:27.340 no-conflict.js:13 Object {id: 5, email: "peic.natasa@gmail.com", token: "BAhJIiVmYjg2Y2QyNDBlNTI4NmViNDJhMTk0M2FlZmI0NDlmZAY6BkVG--b43395dfe06f56cbf247f9db8b5fe0e838408e87"}
2016-08-21 14:09:27.345 no-conflict.js:13 User is signed in!
2016-08-21 14:09:27.423 vendor.bundle.js:9285 XHR finished loading: POST "https://thawing-spire-40526.herokuapp.com/sign-in".send @ vendor.bundle.js:9285ajax @ vendor.bundle.js:8766signIn @ no-conflict.js:13onSignIn @ no-conflict.js:13dispatch @ vendor.bundle.js:4847elemData.handle @ vendor.bundle.js:4659
2016-08-21 14:09:27.424 no-conflict.js:13 Object {id: 5, email: "peic.natasa@gmail.com", token: "BAhJIiU5ZTI2YmE4Njk1MzY1YmMwZTczMzNiMjlhNDk0ZWM2YgY6BkVG--6af28fc7b1d2b21b8f26b861416afd064c0752b9"}
2016-08-21 14:09:27.425 no-conflict.js:13 User is signed in!
2016-08-21 14:09:27.471 thawing-spire-40526.herokuapp.com/jobs:1 GET https://thawing-spire-40526.herokuapp.com/jobs 401 (Unauthorized)
2016-08-21 14:09:27.472 vendor.bundle.js:9285 XHR finished loading: GET "https://thawing-spire-40526.herokuapp.com/jobs".send @ vendor.bundle.js:9285ajax @ vendor.bundle.js:8766getJobs @ no-conflict.js:13signInSuccess @ no-conflict.js:13fire @ vendor.bundle.js:3297fireWith @ vendor.bundle.js:3427done @ vendor.bundle.js:8867(anonymous function) @ vendor.bundle.js:9233
2016-08-21 14:09:27.472 no-conflict.js:13 Object {readyState: 4, responseText: "HTTP Token: Access denied.↵", status: 401, statusText: "Unauthorized"}failure @ no-conflict.js:13fire @ vendor.bundle.js:3297fireWith @ vendor.bundle.js:3427done @ vendor.bundle.js:8869(anonymous function) @ vendor.bundle.js:9233
2016-08-21 14:09:27.672 vendor.bundle.js:9285 XHR finished loading: GET "https://thawing-spire-40526.herokuapp.com/jobs".send @ vendor.bundle.js:9285ajax @ vendor.bundle.js:8766getJobs @ no-conflict.js:13signInSuccess @ no-conflict.js:13fire @ vendor.bundle.js:3297fireWith @ vendor.bundle.js:3427done @ vendor.bundle.js:8867(anonymous function) @ vendor.bundle.js:9233
2016-08-21 14:09:27.683 no-conflict.js:13 [Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object]
```

**Comment by gaand** [comment]
I think at least part of the problem is the same event being handle twice.

Also, I think you may have an asynch bug, getting jobs before the token is available.

**Comment by NatasaPeic** [comment]
If sign up was successful, I'm sending GET request to show all jobs. Token should be available.

What event are you referring to?

**Comment by gaand** [comment]
On the deployed app when I sign in, the network tab in chrome shows two `POST`s to `/sign-in` followed by two `GET`s to `/jobs` the first of which fails (401 Unauthorized).  I think the first get may run before the token is stored.

In any case, I don't think you intend for the sign in network request, or the get for jobs, to run twice, but they do.

**Comment by NatasaPeic** [comment]
I fixed images and bootstrap files.

I don't understand now why I can't do anything locally? I get now the same errors locally, but some different ones in live application.

Two GET requests are confusing. This is what should be happening...

If sign in was successful, signInSuccess will be fired. 

events.js

``` js
// Sign in
const showSignInModal = function showSignInModal(){
  $('#sign-in-modal').modal('show');
};

const closeModalSignIn = function closeModalSignIn() {
    $('#sign-in-modal').modal('hide');
};


const onSignIn = function (event) {

  let data = getFormFields(this);
  event.preventDefault();


  api.signIn(data)
   .done(ui.signInSuccess)
   .fail(ui.failureSignIn);
}
```

signInSucces will fire another AJAX (GET) to show all the content on the front end and pass function showJobsSuccess that is stored also within ui.js. That function calls displayJobs that uses handlebars. 

ui.js

``` js
// Sign in
const signInSuccess = (data) => {
  app.user = data.user;
  console.log(app.user);
  console.log("User is signed in!");

    $('#sign-in-job-modal').modal('hide');
    $(".modal-backdrop").hide();

    $('#sign-in-modal-link').hide();
      $('#c-job-modal-link, #table').show();


  // reset form fields
  $('#sign-in' ).each(function(){
  this.reset();
});
  // fire ajax if sign in was successful to show jobs on the front end
  api.getJobs(showJobsSuccess, failure);

};
```

This is also within ui.js

``` js
// GET request, show data on the front end
const showJobsSuccess = (data) => {

  app.jobs = data.jobs;

  displayJobs(data);
  console.log(app.jobs);
};

```

``` js
// handlebars
let displayJobs = function(jobs){
  // debugger;
  let jobListingTemplate = require('../template/jobs.handlebars');

  // remove all the content table
   $('.table').empty();
  // append content from GET request using handlebars
  $('.table').append(jobListingTemplate({

  // debugger;
    jobs
  }));
};
```

This all worked locally without any issues. Now after I pushed changes to heroku, it doesn't work locally either.

Really not sure what to do next...

**Comment by NatasaPeic** [comment]
This is what I have in application.rb. Reverted all. But still not able to do locally anything after pushing to heroku. 

``` js
# Cross-Origin Resource Sharing
    config.middleware.use Rack::Cors do
      allow do
        origins ENV['CLIENT_ORIGIN'] || 'http://localhost:8080'
        resource '*',
                 headers: :any,
                 methods: [:options, :get,
                           :post, :patch, :put, :delete]
      end
    end
```

**Comment by gaand** [comment]
When you're testing locally, is the client accessing the correct api url?

Is it possible that even handlers are being added twice?

**Comment by NatasaPeic** [comment]
Yes. I have localhost:3000 set as my api locally.

I can sign in locally, but getting errors. I'm so confused. I'm going through my code now... Shouldn't be called twice.

**Comment by NatasaPeic** [comment]
On document ready, I have this:

index.js

``` js

const authEvents = require('./auth/events.js');


// on document ready
$(() => {
  authEvents.addHandlers();


 $('#createJob, #updateJob, #deleteJob, #change-password-modal-link, #change-password-modal-link, #sign-out-modal-link, .content, #create-job-modal-link, #update-job-modal-link, #sign-in-modal-link, #delete-job-modal-link, #update-job-modal-link, #c-job-modal-link, #table').hide();


});
```

It fires all handlers in events.js.

**Comment by gaand** [comment]
Try putting a debugger in `authEvents.addHandlers();` and then hard reload to see if addHandlers runs twice.

**Comment by NatasaPeic** [comment]
I got really confused with local/live application. So, I needed to focus on either one at the time

**Issue #1** -- Requests loading twice.
**Solution** 
When Antony wrote that I wasn't using template as designed, I was going through my code and I thought I forgot to add `<scripts>` for bundle.js and vendor.js. So, I added them again, and that caused my requests to be loaded twice. 

**Issue #2** -- I used old template with CLIENT_URL in config/application.rb
**Solution** 
Changed it to CLIENT_ORIGIN in the same file.

**Issue  #3** -- My show method in job controller loaded jobs that don't belong to the current user.
**Solution** 

``` js
def show
      # render json: @job
    render json: Job.find(params[:id])
  end
```

**Issue #4** -- Adding, committing, and pushing to Heroku is needed every time we make changes. I made my changes for the show method as well as CLIENT_ORIGIN.
**Solution**
`git push heroku master`

Once I was ready to work on my live application, I changed api.js in the front end to point to heroku, add, commit, deploy front end again. 

That would be all.

Thank you Antony, Lauren and Jason for help.
