### ISSUE TITLE
Parameters error when creating property from browser/javascript. Works with curl. Details below. Cannot resolve.

### ISSUE THREAD

**Issue by bbarbersox** [ga-wdi-boston/full-stack-project#38]
Error when PropertiesController invoked from Browser

Started POST "/properties" for ::1 at 2015-11-11 09:55:22 -0500
Processing by PropertiesController#create as HTML
Parameters: {"{\"property\":{\"no\":\"12\",\"street\":\"Fuller Street\",\"city\":\"Sheldon\",\"state\":\"NH\",\"zip\":\"34876\",\"house_mgmt_co\":\"Holsten Holdings\",\"manager\":\"Matt Savrest\",\"user_id\":3}}"=>nil}
User Load (1.5ms) SELECT "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1 [["token", "4cc8af9ed51fe85dd117c0d615a2621a"]]
Completed 400 Bad Request in 5ms (ActiveRecord: 1.5ms)

ActionController::ParameterMissing (param is missing or the value is empty: property):
app/controllers/properties_controller.rb:48:in property_params' app/controllers/properties_controller.rb:18:increate'

Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.5ms)
Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.8ms)
Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (43.6ms)

Successful completion when add property invoked via curl
Started POST "/properties" for ::1 at 2015-11-11 10:07:22 -0500
Processing by PropertiesController#create as /
Parameters: {"property"=>{"no"=>"56", "street"=>"Weston Drive", "city"=>"Ashton", "state"=>"KY"}}
User Load (0.2ms) SELECT "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1 ["token", "4cc8af9ed51fe85dd117c0d615a2621a"] BEGIN
SQL (1.0ms) INSERT INTO "properties" ("no", "street", "city", "state", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id" ["no", "56"], ["street", "Weston Drive"], ["city", "Ashton"], ["state", "KY"], ["user_id", 3], ["created_at", "2015-11-11 15:07:22.955276"], ["updated_at", "2015-11-11 15:07:22.955276"] COMMIT
Completed 201 Created in 17ms (Views: 1.8ms | ActiveRecord: 2.4ms)

**Comment by srhoulam** [comment]
Bill, please paste your code to make the AJAX request.

**Comment by bbarbersox** [comment]
addProperty: function (formdata, token, callback) {
    debugger;
    console.log('got to add property function');
    console.log(formdata);
    this.ajax({
      method: 'POST',
      url: this.ttt + '/properties',
      headers: {
        Authorization: 'Token token=' + token
      },
      data: JSON.stringify(formdata),
      dataType: 'json'
    }, callback);
  },
};  

$('.addProperty').on('submit', function(e) {
    debugger;

```
var property = {
    "no":"",
    "street":"", // game.cell.index,
    "city":"", // game.cell.value
    "state":"",
    "zip":"",
    "house_mgmt_co":"",
    "manager":"",
    "user_id":0
};

// dataForServer = $('#propertyFormDiv').serializeArray();

property.no = $(".addProperty input[id=streetNo]").val();
property.street = $(".addProperty input[id=street]").val();
property.city = $(".addProperty input[id=city]").val();
property.state = $(".addProperty input[id=state]").val();
property.zip = $(".addProperty input[id=zipcode]").val();
property.house_mgmt_co = $(".addProperty input[id=propertyMgmtCo]").val();
property.manager = $(".addProperty input[id=manager]").val();
property.user_id = 3;

// var property = wrap('property', form2object(this));
// var data = wrap('game', wrap('cell', form2object(this))); -- from tic tac toe
// var formdata = wrap('formdata', form2object(this));
// var cb = function cb(error, data) {
//   if (error) {
//     callback(error);
//     return;
//   }
console.log('got to add property function', property);
e.preventDefault();
tttapi.addProperty(property, token, callback);
```

  });

**Comment by srhoulam** [comment]
Your back-end is expecting your `properties` object to be wrapped in another object as the value of the `property` attribute. Ben had the same issue, see here for an example: https://github.com/ga-wdi-boston/rails-project-full-stack-app/issues/36

**Comment by srhoulam** [comment]
You can ask further questions here if necessary or close it if your issue is resolved.

**Comment by bbarbersox** [comment]
Antony,
Modified property table as Ben did with his word table.  Error looks worse as it is seeming to duplicate the property object set to server.

 $('.addProperty').on('submit', function(e) {
    debugger;

```
var property = {
  property : {
    "no":"",
    "street":"",
    "city":"",
    "state":"",
    "zip":"",
    "house_mgmt_co":"",
    "manager":"",
    "user_id":0
  }
};

property.no = $(".addProperty input[id=streetNo]").val();
property.street = $(".addProperty input[id=street]").val();
property.city = $(".addProperty input[id=city]").val();
property.state = $(".addProperty input[id=state]").val();
property.zip = $(".addProperty input[id=zipcode]").val();
property.house_mgmt_co = $(".addProperty input[id=propertyMgmtCo]").val();
property.manager = $(".addProperty input[id=manager]").val();
property.user_id = 3;

console.log('got to add property function', property);
e.preventDefault();
tttapi.addProperty(property, token, callback);
```

  });

  addProperty: function (formdata, token, callback) {
    debugger;
    console.log('got to add property function');
    console.log(formdata);
    this.ajax({
      method: 'POST',
      url: this.ttt + '/properties',
      headers: {
        Authorization: 'Token token=' + token
      },
      data: JSON.stringify(formdata),
      dataType: 'json'
    }, callback);
  },
};

Started OPTIONS "/properties" for ::1 at 2015-11-11 11:27:00 -0500

Started POST "/properties" for ::1 at 2015-11-11 11:27:07 -0500
Processing by PropertiesController#create as HTML
  Parameters: {"{\"property\":{\"no\":\"\",\"street\":\"\",\"city\":\"\",\"state\":\"\",\"zip\":\"\",\"house_mgmt_co\":\"\",\"manager\":\"\",\"user_id\":0},\"no\":\"12\",\"street\":\"Fuller Street\",\"city\":\"Sheldon\",\"state\":\"NH\",\"zip\":\"34876\",\"house_mgmt_co\":\"Holsten Holdings\",\"manager\":\"Trish Williams\",\"user_id\":3}"=>nil}
  User Load (0.4ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "cb7a27e6631bda0f8883c518b5b6ab4b"]]
Completed 400 Bad Request in 3ms (ActiveRecord: 0.4ms)

ActionController::ParameterMissing (param is missing or the value is empty: property):
  app/controllers/properties_controller.rb:48:in `property_params'
  app/controllers/properties_controller.rb:18:in`create'

  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.5ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.8ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (42.4ms)

**Comment by srhoulam** [comment]
Try adding `contentType : 'application/json'` to the options hash for your call to `tttapi.ajax` (inside `tttapi.addProperty` as `this.ajax`).

**Comment by bbarbersox** [comment]
Saad,
When I add that line (see below) the create request completes without an error (see below) yet the record that is written is all nulls (except userid).  The property object seems to be duplicated on the rails server.  Progress but still not correctly creating a new property.
Bill

addProperty: function (formdata, token, callback) {
    debugger;
    console.log('got to add property function');
    console.log(formdata);
    this.ajax({
      method: 'POST',
      url: this.ttt + '/properties',
      headers: {
        Authorization: 'Token token=' + token
      },
      contentType : 'application/json',
      data: JSON.stringify(formdata),
      dataType: 'json'
    }, callback);
  },
};

Started OPTIONS "/properties" for ::1 at 2015-11-11 12:02:10 -0500

Started POST "/properties" for ::1 at 2015-11-11 12:02:25 -0500
Processing by PropertiesController#create as HTML
  Parameters: {"property"=>{"no"=>"", "street"=>"", "city"=>"", "state"=>"", "zip"=>"", "house_mgmt_co"=>"", "manager"=>"", "user_id"=>0}, "no"=>"12", "street"=>"Fuller Street", "city"=>"Sheldon", "state"=>"NH", "zip"=>"34876", "house_mgmt_co"=>"", "manager"=>"", "user_id"=>3}
  User Load (0.7ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "bbc9b27984fa725aa7993eb7c520855a"]](0.2ms)  BEGIN
  SQL (1.3ms)  INSERT INTO "properties" ("no", "street", "city", "state", "house_mgmt_co", "manager", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["no", ""], ["street", ""], ["city", ""], ["state", ""], ["house_mgmt_co", ""], ["manager", ""], ["user_id", 3], ["created_at", "2015-11-11 17:02:25.123305"], ["updated_at", "2015-11-11 17:02:25.123305"]](0.3ms)  COMMIT
Completed 201 Created in 39ms (Views: 3.5ms | ActiveRecord: 7.8ms)

Started GET "/properties" for ::1 at 2015-11-11 12:08:44 -0500
Processing by PropertiesController#index as HTML
  Property Load (0.3ms)  SELECT "properties".\* FROM "properties"
Completed 200 OK in 12ms (Views: 11.7ms | ActiveRecord: 0.3ms)

**Comment by bbarbersox** [comment]
Saad,
Got it working.  Changed the name of the table from property to dataForServer (see below) and that write the correct form data onto the server.  Six hours later and many errors resolved to get to that point.  Thanks alot!!!! You were a GREAT help.  Hope you are feeling better.
Bill

var dataForServer = {
      property : {
        "no":"",
        "street":"",
        "city":"",
        "state":"",
        "zip":"",
        "house_mgmt_co":"",
        "manager":"",
        "user_id":0
      // }
   }
  };

Rails Server output
Started OPTIONS "/properties" for ::1 at 2015-11-11 12:28:34 -0500

Started POST "/properties" for ::1 at 2015-11-11 12:30:12 -0500
Processing by PropertiesController#create as HTML
  Parameters: {"property"=>{"no"=>"33", "street"=>"Lucky Street", "city"=>"Memphis", "state"=>"TN", "zip"=>"72301", "house_mgmt_co"=>"Watercreek Village", "manager"=>"Will Chandler", "user_id"=>3}}
  User Load (0.3ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "fb57b0306ecb7ebd5b28e670a4f3ec66"]](0.7ms)  BEGIN
  SQL (0.9ms)  INSERT INTO "properties" ("no", "street", "city", "state", "zip", "house_mgmt_co", "manager", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["no", "33"], ["street", "Lucky Street"], ["city", "Memphis"], ["state", "TN"], ["zip", 72301], ["house_mgmt_co", "Watercreek Village"], ["manager", "Will Chandler"], ["user_id", 3], ["created_at", "2015-11-11 17:30:12.549326"], ["updated_at", "2015-11-11 17:30:12.549326"]](1.3ms)  COMMIT
Completed 201 Created in 12ms (Views: 2.2ms | ActiveRecord: 3.2ms)

Started GET "/properties" for ::1 at 2015-11-11 12:32:21 -0500
Processing by PropertiesController#index as HTML
  Property Load (0.4ms)  SELECT "properties".\* FROM "properties"
Completed 200 OK in 11ms (Views: 10.6ms | ActiveRecord: 0.4ms)

**Comment by bbarbersox** [comment]
Saad was great with resolving this issue(s).

**Comment by srhoulam** [comment]
I'm happy to help, Bill. I'm much better-rested today, thanks for asking.
