### ISSUE TITLE
Issue with CORS 

### ISSUE THREAD

**Issue by cdelsoin** [ga-wdi-boston/full-stack-project#380]
So I previously has an issue with CORS. I added an extension to chrome to solve it but it seems to only work sometimes. I've done a lot of reading on how to solve this CORS problem but I'm more confused than when I began.

I seem to run into a couple of roadblocks depending on the situation. currently the error that I'm getting in my rails server is `ActionController::RoutingError (No route matches [OPTIONS] "/presets"):`

**Comment by cdelsoin** [comment]
the error that i get in my console `XMLHttpRequest cannot load http://localhost:3000/presets/. Response for preflight has invalid HTTP status code 404`

**Comment by laurenfazah** [comment]
What is the request you're making?

**Comment by gaand** [comment]
What are the routes for presets?

**Comment by cdelsoin** [comment]
i get this error when i try to POST my presets. which was working fine the last time i was attempting (by fine i mean i was successfully posting but still having the null issue explained in my other open issue). Like I said before I was having an issue with CORS before but it went away and now has come back 
came back.

**Comment by cdelsoin** [comment]
resources :presets, except: [:new, :edit]

**Comment by laurenfazah** [comment]
You're on Chrome, right? I don't think you should be having actual CORS issues (even if that's what the messages are indicating), unless some of your app's configuration has strayed from what we've taught. Antony can weigh in otherwise. 

I'm thinking it's something with the request you're making (the way it's formatting and whether or not correct token is there). Could you post the code for your POST request?

**Comment by gaand** [comment]
Is this against the deployed api?

**Comment by cdelsoin** [comment]
no i havent deployed yet and yes i am using chrome

**Comment by cdelsoin** [comment]
events.js

```
const onSavePreset = function onSavePreset(getRain, getFire, getThunder, getCrickets, getBirds, getCoffee, getWaves, getBowl) {
  getRain = $(".rainSlider").prop('value');
  getFire = $(".fireSlider").prop('value');
  getThunder = $(".thunderSlider").prop('value');
  getCrickets = $(".cricketsSlider").prop('value');
  getBirds = $(".birdsSlider").prop('value');
  getCoffee = $(".coffeeSlider").prop('value');
  getWaves  = $(".wavesSlider").prop('value');
  getBowl = $(".bowlSlider").prop('value');
  let getName = $('.save-input').prop('value');
  // let getName = getFormFields(this);
  event.preventDefault();
  api.savePreset(getName, getRain, getFire, getThunder, getCrickets, getBirds, getCoffee, getWaves, getBowl)
    .done(ui.success)
    .fail(ui.failure);
};

```

api.js

```
const savePreset = function (getName, getRain, getFire, getThunder, getCrickets, getBirds, getCoffee, getWaves, getBowl){
  return $.ajax ({
    url: app.api + '/presets/',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + app.user.token
    },
    data: {
      "preset": {
        "name": getName,
        "rain": getRain,
        "fire": getFire,
        "thunder": getThunder,
        "crickets": getCrickets,
        "birds": getBirds,
        "coffee": getCoffee,
        "waves": getWaves,
        "bowl": getBowl
      }
    }
  });
};

```

**Comment by laurenfazah** [comment]
Can you put a debugger after the `data` object and inspect this function in the browser by making a POST request? What do those variables pass in as? Is `app.user.token` defined if you hover over it?

**Comment by gaand** [comment]
Is there a reason t not use getFormFields?

**Comment by cdelsoin** [comment]
i put a debugger in but i error out before the debugger is hit. the first is without the CORS extension turned on and the second is with the extension

```
XMLHttpRequest cannot load http://localhost:3000/presets/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 500.
2016-08-21 21:44:14.017 jquery.js:9175 XHR failed loading: POST "http://localhost:3000/presets/".send @ jquery.js:9175ajax @ jquery.js:8656savePreset @ api.js:56onSavePreset @ events.js:96dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
```

```
XMLHttpRequest cannot load http://localhost:3000/presets/. Response for preflight has invalid HTTP status code 404
```

**Comment by cdelsoin** [comment]
i think i used jquery just to see if i could and left it there. i believe the both worked for me

**Comment by laurenfazah** [comment]
What was the internal server error from the first error (in your rails console)?

**Comment by cdelsoin** [comment]
```
Started OPTIONS "/presets/" for ::1 at 2016-08-21 21:52:03 -0400


Started POST "/presets/" for ::1 at 2016-08-21 21:52:03 -0400
Processing by PresetsController#create as */*
  Parameters: {"preset"=>{"name"=>"ksflkn", "rain"=>"0.5", "fire"=>"0.5", "thunder"=>"0.5", "crickets"=>"0.5", "birds"=>"0.5", "coffee"=>"0.5", "waves"=>"0.5", "bowl"=>"0.5"}}
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `presets' for nil:NilClass
Did you mean?  present?):
  app/controllers/presets_controller.rb:22:in `create'


  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.4ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.9ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.2ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (62.8ms)


```

**Comment by laurenfazah** [comment]
What is here?   app/controllers/presets_controller.rb:22:in `create'

Can you post your `create` method in the PresetsController?

**Comment by cdelsoin** [comment]
```
 def create
    # @preset = Preset.new(preset_params)
    @preset = current_user.presets.build(preset_params)

    if @preset.save
      render json: @preset, status: :created, location: @preset
    else
      render json: @preset.errors, status: :unprocessable_entity
    end
  end
```

i just realize i changed @preset in presets_controller.rb to `@preset = current_user.presets.build(preset_params)`  in create and set_params to match examples_controller.rb to see if it would help.. i just changed them back to `@preset = Preset.new(preset_params)` and now my post is going through and i having my original problem of everything returning null from the other issue i have posted.

![screen shot 2016-08-21 at 10 44 36 pm](https://cloud.githubusercontent.com/assets/20059077/17842428/ecb80664-67f0-11e6-9e26-b1631ed993ff.png)

```
Started OPTIONS "/presets/" for ::1 at 2016-08-21 22:16:28 -0400


Started POST "/presets/" for ::1 at 2016-08-21 22:16:28 -0400
Processing by PresetsController#create as */*
  Parameters: {"preset"=>{"name"=>"adasd", "rain"=>"0.5", "fire"=>"0.5", "thunder"=>"0.5", "crickets"=>"0.5", "birds"=>"0.5", "coffee"=>"0.5", "waves"=>"0.5", "bowl"=>"0.5"}}
   (0.2ms)  BEGIN
  SQL (78.0ms)  INSERT INTO "presets" ("created_at", "updated_at") VALUES ($1, $2) RETURNING "id"  [["created_at", "2016-08-22 02:16:28.690073"], ["updated_at", "2016-08-22 02:16:28.690073"]]
   (1.0ms)  COMMIT
[active_model_serializers] Rendered PresetSerializer with ActiveModelSerializers::Adapter::Json (6.57ms)
Completed 201 Created in 105ms (Views: 10.0ms | ActiveRecord: 80.1ms)


```

 it seems like created a second issue trying to solve the first one 

i guess i can close this issue?

**Comment by laurenfazah** [comment]
Yes I'd close this and continue in #378
