### ISSUE TITLE
app broken after deploy

### ISSUE THREAD

**Issue by EchoXin** [ga-wdi-boston/full-stack-project#381]
working locally both on api and js, here is the error from the console:
jquery.js:9175 POST https://localhost:3000/sign-in net::ERR_SSL_PROTOCOL_ERROR

and here is the error from rails serve:
[2016-08-21 21:41:03] INFO  WEBrick 1.3.1
[2016-08-21 21:41:03] INFO  ruby 2.3.0 (2015-12-25) [x86_64-darwin15]
[2016-08-21 21:41:03] INFO  WEBrick::HTTPServer#start: pid=37061 port=3000
[2016-08-21 21:41:20] ERROR bad URI `?\x13?'.
[2016-08-21 21:41:20] ERROR bad Request-Line`\x16\x03\x01\x00?\x01\x00\x00?\x03\x02\x01ǨQ(\x06\v?I???B|?}?p\x16?\x01΄39[?|?{?e\x00\x00\x10?\t?\x13?'.

**Comment by gaand** [comment]
What is the url for the deployed api?

The one in the error message points to localhost (which caused the SSL Protocol Error)).

**Comment by EchoXin** [comment]
https://salty-mesa-93438.herokuapp.com   this is deployed api, I am working locally now for test

**Comment by gaand** [comment]
When local you must use `http` as the scheme.

When deployed use `https`.

**Comment by EchoXin** [comment]
I can work locally now, but still got an error when I use deployed api, here is the error from console:

Request cannot load https://salty-mesa-93438.herokuapp.com/sign-in. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'https://echoxin.github.io' is therefore not allowed access. 
The response had HTTP status code 500.

**Comment by EchoXin** [comment]
I update the ruby version to 2.3.1, and it works well locally but get a new error on deployed api: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://echoxin.github.io' is therefore not allowed access. The response had HTTP status code 401.

**Comment by EchoXin** [comment]
and the deployed api also works well on the local page.

**Comment by RealWeeks** [comment]
That seems like a good error to me.  401 means unauthorized, what this tells me is that it is hitting your back end but something is wrong with your email address, password or token.

**Comment by EchoXin** [comment]
I change the client url to client origin in the config/application.rb, now everything is fine.
