### ISSUE TITLE
third party api doesn't work on gh page

### ISSUE THREAD

**Issue by EchoXin** [ga-wdi-boston/full-stack-project#384]
I have a weather data  from a third party api, it works well locally, but i can't post that data to the diary table on gh page, here is the warning:

Content: The page at 'https://echoxin.github.io/Diary-SPA-Project/#' was loaded over HTTPS, but requested an insecure image 'http://openweathermap.org/img/w/.png'. This content should also be served over HTTPS.

img/w/.png, the w should be replaced by the  weather data, but seems I can't get that data from the weather api.

**Comment by laurenfazah** [comment]
Are you able to serve "http://openweathermap.org/img/w/.png" as "https://openweathermap.org/img/w/.png"? (http vs https)

**Comment by EchoXin** [comment]
if I change to https, the page can't open, the problem is I can't request get data from this api http://api.openweathermap.org/data/2.5/forecast/city?q=Boston&APPID=f1c0d3b7cb3bd30991614b391a2ddf52

and even didn't get an error for the get request in console.

here is the code to get data from that api

```
const createWeather = function (){
   return $.ajax({
    url: app.weatherApi,
    method: 'GET',
    async: false
  })
  .done(function(data){
    weatherColumn = data.list[1].weather[0].icon;
    console.log(weatherColumn);
  });

};

```

**Comment by laurenfazah** [comment]
This is an issue with your browser not wanting to load HTTP from your deployed site: https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content?hl=en

It looks like to use HTTPS with this API, you'd need to pay: https://openweathermap.desk.com/customer/portal/questions/8166727-http-to-https

You _might_ want to consider a different weather API that can load over HTTPS...

**Comment by EchoXin** [comment]
I see, thank you so much

**Comment by EchoXin** [comment]
is there any way to ask a get request from a http api in github page?

**Comment by laurenfazah** [comment]
Not in Chrome at least. It's not GitHub that's the problem.

**Comment by gaand** [comment]
You could proxy your request through your API.

**Comment by laurenfazah** [comment]
Look into http://ruby-doc.org/stdlib-2.3.1/libdoc/net/http/rdoc/Net/HTTP.html for `GET`. 

You could create a custom controller method with a matching custom route and have your API make the request.

**Comment by gaand** [comment]
This also might help https://github.com/axsuul/rails-reverse-proxy but the docs are slight.

**Comment by EchoXin** [comment]
Problem solved. I merge the third party api to the app api and install http gem. Thank you so much for Antony and Lauren's help!
