### ISSUE TITLE
Best way to avoid duplicates in join table?

### ISSUE THREAD

**Issue by jordanallain** [ga-wdi-boston/full-stack-project#385]
right now i have my users table and my players table. then i have the join table that has columns for id, user_id, and player_id. i was wondering what the best method would be to make sure that the user doesn't add the same player to their favorites more than once. i read about uniq constraints but wasn't sure if that would work because the same user_id can be added multiple times as well as the same player_id.

i also thought that when getting all favorite players associated with a user i could filter out the duplicates but i thought it would be better practice to not create duplicates in the first place.

i could go the route of turning off the button to add the player after a user has added them but then i would have to go about turning the button back on if the user deleted them from their favorites which i was trying to avoid.

**Comment by gaand** [comment]
You could use `validates` with the `scope` options.  See http://guides.rubyonrails.org/active_record_validations.html#uniqueness

You probably also want to create a unique index across the columns as an optimization.

**Comment by jordanallain** [comment]
changed my model and it appears to be functioning correctly. i believe i already had a unique id on the favorites column because i scaffolded it. closing this thank you, if this appears incorrect let me know.

``` js
class Favorite < ActiveRecord::Base
  belongs_to :user, inverse_of: :favorites
  belongs_to :player, inverse_of: :favorites

  validates_uniqueness_of :user_id, scope: :player_id
end
```
