### ISSUE TITLE
How to have a form appear if value in my User table is true

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/full-stack-project#387]
I'm having an issue with trying to make a form appear based off of my radio check boxes.  I have it set up that when you sign up, you can select whether or not you are a SFX artist; yes = true, and no = false.  If the user selects yes when they sign up, every time they sign in, I want the form to pop up so they can post their work.    

``` js
// Sign In Modal Click Events
$(()=>{
  $('#creation-form').hide();
  $('.sign-in').on('click', function(){
    // console.log('You clicked Sign In!');
    $('#sign-in-modal').modal('show');
    $('.save-sign-in').on('click', function(){
      // console.log('You clicked Submit');
      // $('#sign-in-modal').modal('hide');
    });
  });
});
```

The top jQuery is the one I used to hide the form initially.

``` js
// stores user data
const signInSuccess = (data) => {
  app.user = data.user;
  console.log(app);
  if (data.artist === true) {
    $('#creation-form').show();
  }
};
```

Above is what I have tried so far to get it to show.  I guess I'm uncertain how to use the boolean data of the artist column I added to the user table.  I can't figure out how to use that data to bring the form forward one those that are artist sign in.

**Comment by jlmitch1989** [comment]
The form successfully hides, I just can't get it to show up when I want it to.

**Comment by laurenfazah** [comment]
So is the form supposed to show up based on the radio button or based on the user data coming back from the API (that was determined by the radio button)?

**Comment by RealWeeks** [comment]
When the document is ready the first thing you do is hide the element.  Why not show it when you want it to appear instead of hiding it at first then showing it?

Am I understanding the question correctly?

**Comment by RealWeeks** [comment]
Either way put a debugger where your console.log is and check the value of data.artist.

**Comment by jlmitch1989** [comment]
@laurenfazah, I mean I guess either could work, but right now I have my user table collecting the boolean data, so I guess based off of the API?

@J-Weeks, I don't want it to show until someone who claims to be an artist signs in.

**Comment by laurenfazah** [comment]
I guess more what I mean is when/where is this form supposed to show up? After what user action?

**Comment by RealWeeks** [comment]
Have you tested this out? Can you clarify the issue a bit more.

**Comment by jlmitch1989** [comment]
Ok so now I've just realized apparently my database isn't actually collecting this information, when I thought it was. So i guess this is more of a question about why isn't my database taking this information in.

**Comment by jlmitch1989** [comment]
Problem solved!  Needed to add :artist into my login serializer as well.
