### ISSUE TITLE
Heroku access control origin

### ISSUE THREAD

**Issue by dvdpwll** [ga-wdi-boston/full-stack-project#388]
I had an issue where even though the front end and back end work fine locally, when deploying the front end and back end I get an access control origin error on the chrome console when I try to sign up/sign in. But when I check the heroku database an account was made correctly and it return 200.

This is b/c I had not set the CLIENT_ORIGIN to github. Run this code to fix:

```
heroku config:set CLIENT_ORIGIN=https://(USERNAME).github.io
```

additionally if in the rails template, file application.rb, the CLIENT_ORIGIN is instead CLIENT_URL then run this:

```
heroku config:set CLIENT_URL=https://(USERNAME).github.io
```

**Comment by gaand** [comment]
I asked @dvdpwll to open this for those who grabbed the template before the change from `URL` to `ORIGIN`.

I am closing since this should no longer be an issue.
