### ISSUE TITLE
How to GET data from two related tables, in one controller

### ISSUE THREAD

**Issue by cwcrane** [ga-wdi-boston/full-stack-project#39]
I have a books table and a ratings table. A book has_one rating, and a rating belongs_to book. 

When I make a GET request to http://localhost:3000/books I would like to get data back on the books as well as their ratings. I am not sure how to structure the books controller to do this?

I tried making a an instance variable @rating to hold book.rating, and then rendering this in json, ...didn't work.

**Comment by GA-MEB** [comment]
@cwcrane To confirm, what you want is to be able to request `/books` and get information about both books _and_ ratings, all at once?

**Comment by gaand** [comment]
Serializers are (a big) part of the solution.

**Comment by cwcrane** [comment]
Yes correct Matt. I'll try working on the books serializer. Would love to pick one of your brains about the params hash at some point too...

Thank you

**Comment by gaand** [comment]
This is worth the first ten minutes or so: http://railscasts.com/episodes/409-active-model-serializers
Credit to Rachel for posting this is forum.

**Comment by gaand** [comment]
Chris is looking at the railscast and docs and will add a comment if he needs additional assistance.

**Comment by cwcrane** [comment]
I added :rating to my books serializer and am now receiving ratings back on my book GET requests. Thanks!
