### ISSUE TITLE
Issues getting the values of an array

### ISSUE THREAD

**Issue by natGalynker** [ga-wdi-boston/full-stack-project#391]
I am am successfully getting the GET requests. I am now having issues with getting the actual value of the arrays of that request. I have been playing around with this for a while and chaining in various ways, both using handlebars and not. The arrays however are being incredibly stubborn. I would really love some help with this!

**Comment by gaand** [comment]
Without seeing the code you're using or the results/errors you're seeing, it isn't really possible to help.

**Comment by natGalynker** [comment]
Sorry this didn't send:

currently the request is  

```
    const showPetsSuccess = (data) =>  {
     const displayPets = require('../templates/pets-display.handlebars');
      console.log(data);
    $('.pet-display-append').html(displayPets({
    pets:data.pets
  }));
```

```
const onShowPets = function onShowPets() {
event.preventDefault();
api.showPets()
.done(ui.showPetsSuccess)
.fail(ui.failure);
};
```

```
{{#each pets.pets}}

    <h1><large>: {{pet.name}}</large></h1>
    <h1><large>: {{pet.owner_name}}</large></h1>
    <h2><small>: {{pet.born_on}}</small></h2>
    <h3><small>: {{pet.gender}}</small></h3>
    <h3><small>: {{pet.breed}}</small></h3>
    <h1><small>: {{pet.rabes_date_on}}</small></h1>
    <h1><small>: {{pet.only_pet}}</small></h1>

  {{/each}}
```

```
const showPets = function () {
  return $.ajax({
    url: app.api + '/pets',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + app.user.token
    },
  });

};
```

**Comment by gaand** [comment]
I think your handlebars syntax is incorrect.

I searched for "handlebars each" and found this http://handlebarsjs.com/builtin_helpers.html

**Comment by natGalynker** [comment]
No errors. This is the results from the rails sever also 

```
Started GET "/pets" for ::1 at 2016-08-22 20:44:17 -0400
Processing by PetsController#index as */*
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "c41b059a797512276aacdf8087f22431"]]
  Pet Load (0.5ms)  SELECT "pets".* FROM "pets" WHERE "pets"."user_id" = $1  [["user_id", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Json (2.54ms)
Completed 200 OK in 13ms (Views: 6.3ms | ActiveRecord: 0.8ms)
```

dev console output:

```
jquery.js:9175 XHR finished loading: GET "http://localhost:3000/pets".send @ jquery.js:9175ajax @ jquery.js:8656showPets @ api.js:61onShowPets @ events.js:52dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
2016-08-22 21:11:19.457 jquery.js:9175 XHR finished loading: GET "http://localhost:3000/pets".
```

**Comment by laurenfazah** [comment]
I believe Antony was referring to the `{{each}}` in your handlebars template itself.

Here's an example from the link he shared:

```
  {{#each people}}
    <li>{{this}}</li>
  {{/each}}
```

**Comment by natGalynker** [comment]
I was in the process of updating it: 

```

<h1 class = "pet_list">

{{#each pets}}
    <h2><large>: {{this.name}}</large></h2>
    <h2><large>: {{this.owner_name}}</large></h2>
    <h2><small>: {{this.born_on}}</small></h2>
    <h2><small>: {{this.gender}}</small></h2>
    <h2><small>: {{this.breed}}</small></h2>
    <h2><small>: {{this.rabes_date_on}}</small></h2>
    <h2><small>: {{this.only_pet}}</small></h2>
  {{/each}}
```

I was using the example which Jason did in class to go off of,

After the adjustment above when I launched in the browser there was still no change.
In either the console or the screen itself to what I am appending to

**Comment by laurenfazah** [comment]
Does your `console.log(data)` logging data in `const showPetsSuccess`?

**Comment by natGalynker** [comment]
console.log(data) has been returning the following result:

```
jquery.js:9175 XHR finished loading: GET "http://localhost:3000/pets".send @ jquery.js:9175ajax @ jquery.js:8656showPets @ api.js:61onShowPets @ events.js:52(anonymous function) @ index.js:25dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
2016-08-22 21:28:53.554 ui.js:71 Object {pets: Array[4]}pets: Array[4]0: Objectborn_on: "2007-04-20"breed: "black cat"declawed: trueferal: truegender: "female"id: 1name: "Minx"neutered: trueonly_pet: trueowner_name: "Kel"rabes_shot_date: "2016-04-05"__proto__: Object1: Object2: Object3: Objectlength: 4__proto__: Array[0]__proto__: Object
```

**Comment by natGalynker** [comment]
It returns an array. I have been having issues with getting access to those keys/values within the get to manipulate to display that information to the user.

**Comment by natGalynker** [comment]
I tried to Chain them: data.pets.name but that was not successful.

**Comment by laurenfazah** [comment]
You're sending `data.pets` to the template, right? So for each item in the `{{each}}`, you've already traversed that far into the object, so each `data.pets` === `this`, just like you had it before. This wasn't showing anything in your browser's view?

``` html

{{#each pets}}
    <h2><large>: {{this.name}}</large></h2>
    <h2><large>: {{this.owner_name}}</large></h2>
    <h2><small>: {{this.born_on}}</small></h2>
    <h2><small>: {{this.gender}}</small></h2>
    <h2><small>: {{this.breed}}</small></h2>
    <h2><small>: {{this.rabes_date_on}}</small></h2>
    <h2><small>: {{this.only_pet}}</small></h2>
  {{/each}}
```

**Comment by natGalynker** [comment]
Correct.  That is why I was attempting to target each key value of the Pet object, but I am not sure what I am doing wrong here. I have linked the template, I have a click handler to fire the handlebars template when fired, the data is there since when I console log it it is being returned as four arrays.

**Comment by laurenfazah** [comment]
Is the list showing at all without data?

You can determine that by either seeing the `:`s you have after the `<small>` and `<large>` tags, or by inspecting where they should be in the browser, and seeing if you see the `<h2>`s for each pet from the template...

**Comment by natGalynker** [comment]
Got! It. Thank you something you just said clicked with me. I had altered the element I was appending to, which is why it wasn't showing I. I fixed this and it is appearing loud and clear. Thank you so much!  One more to go!
