### ISSUE TITLE
I'm having serious issues after deploying front and back end.

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/full-stack-project#392]
I don't even know where to begin.  For starters, all of the images I used for the styling of my webpage, including my custom font isn't working.  Its saying this in my console: 

```
jlmitch1989.github.io/:131 GET https://jlmitch1989.github.io/assets/eye-hand.jpg 404 (Not Found)
jlmitch1989.github.io/:1 GET https://jlmitch1989.github.io/assets/spooky-wallpaper.jpg 404 (Not Found)
jlmitch1989.github.io/:1 GET https://jlmitch1989.github.io/assets/styles/youmurdererbb_reg-webfont.woff2 
jlmitch1989.github.io/:1 GET https://jlmitch1989.github.io/assets/styles/youmurdererbb_reg-webfont.woff 
```

After trying to sign up I get this error in my console:

```
Mixed Content: The page at 'https://jlmitch1989.github.io/monster-me-frontend/#' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://monsterme.herokuapp.com//sign-up/'. This content should also be served over HTTPS.
/monster-me-frontend/#:1 XMLHttpRequest cannot load http://monsterme.herokuapp.com//sign-up/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://jlmitch1989.github.io' is therefore not allowed access.
vendor.bundle.js:9285 XHR failed loading: POST "http://monsterme.herokuapp.com//sign-up/".send @ vendor.bundle.js:9285ajax @ vendor.bundle.js:8766signUp @ no-conflict.js:13onSignUp @ no-conflict.js:13dispatch @ vendor.bundle.js:4847elemData.handle @ vendor.bundle.js:4659
no-conflict.js:13 Object {readyState: 0, status: 0, statusText: "error"}
```

I don't understand what the heck is going on.  It was working perfectly before i deployed.

**Comment by laurenfazah** [comment]
A few issues. Let's attach in order of priority. 

First, your api should be worked with HTTPS:

``` diff
- http://monsterme.herokuapp.com/
+ https://monsterme.herokuapp.com/
```

Second, check out your endpoint with this error:

`http://monsterme.herokuapp.com//sign-up/`

Notice any extra `/`s?

**Comment by jlmitch1989** [comment]
Well how do I fix it? My app.js file has the "HTTPS".

**Comment by laurenfazah** [comment]
Your `.woff` and `.woff2` need to be commented out from your `.gitignore` for those two errors.

For the two error load images. Are there other images loading on your site? Or are those the only two and they aren't loading.

```
jlmitch1989.github.io/:131 GET https://jlmitch1989.github.io/assets/eye-hand.jpg 404 (Not Found)
jlmitch1989.github.io/:1 GET https://jlmitch1989.github.io/assets/spooky-wallpaper.jpg 404 (Not Found)
```

**Comment by laurenfazah** [comment]
Well in that case, maybe the HTTPS error is from the invalid endpoint.

**Comment by jlmitch1989** [comment]
Can I comment them out and then add/commit then push to gh-pages? Or do I have to do more than that?

Well I can't sign in to see if the images I imbedded for creations are working, so for now it's just those two images.

How do I fix an invalid endpoint?

**Comment by laurenfazah** [comment]
By invalid endpoint, I mean nothing more than a syntax error.

Again, here is the sign-up endpoint you have:

`http://monsterme.herokuapp.com//sign-up/`

See a syntactic difference between that and:

`http://monsterme.herokuapp.com/sign-up/`?

(Hint: It's the double slash between your api url and the `sign-up` endpoint.)

**Comment by jlmitch1989** [comment]
Yes, I see it now.  I have an extra slash before sign-up.  So if I comment out the .woff and .woff2, and I remove the extra slash from the api url in the app.js file.  All I need to do is save it, add/commit it, the push to gh-pages?

**Comment by laurenfazah** [comment]
> Can I comment them out and then add/commit then push to gh-pages? Or do I have to do more than that?

Yup. You can follow this solution if you want: https://github.com/ga-wdi-boston/full-stack-project/issues/307#issuecomment-216691645

**Comment by jlmitch1989** [comment]
I just did all of those things and i'm still getting the same issues for my pictures and fonts.

**Comment by gaand** [comment]
GitHub pages sometimes takes a few minutes.

Did you hard reload the front end (open the dev tools in chrome and click and hold the reload button)?

**Comment by jlmitch1989** [comment]
This is what my console is showing me when I try and sign-up.

```
vendor.bundle.js:9285 Mixed Content: The page at 'https://jlmitch1989.github.io/monster-me-frontend/#' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://monsterme.herokuapp.com//sign-up/'. This request has been blocked; the content must be served over HTTPS.send @ vendor.bundle.js:9285ajax @ vendor.bundle.js:8766signUp @ no-conflict.js:13onSignUp @ no-conflict.js:13dispatch @ vendor.bundle.js:4847elemData.handle @ vendor.bundle.js:4659
vendor.bundle.js:9285 XMLHttpRequest cannot load http://monsterme.herokuapp.com//sign-up/. Failed to start loading.send @ vendor.bundle.js:9285ajax @ vendor.bundle.js:8766signUp @ no-conflict.js:13onSignUp @ no-conflict.js:13dispatch @ vendor.bundle.js:4847elemData.handle @ vendor.bundle.js:4659
no-conflict.js:13 Object {readyState: 0, status: 0, statusText: "error"}
```

**Comment by laurenfazah** [comment]
It looks like the same sign-up endpoint issue as before. Did you check that it was fixed locally?

**Comment by jlmitch1989** [comment]
Yes I did, and it's still giving the same errors

**Comment by laurenfazah** [comment]
Check slack
