### ISSUE TITLE
[Rails] Categories not showing up on Games, even though they have a has_many/belongs_to relationship?

### ISSUE THREAD

**Issue by tuckyeah** [ga-wdi-boston/full-stack-project#394]
So I'm setting up a Game model (and associated controller/route) that will, theoretically, hold about 5 Categories (which is it's own separate model).

However, I'm running into an issue where I'm not able to get any categories to show up at all, it just returns an empty array when I go to look at the Game.first.categories (or anything similar)

![image](https://cloud.githubusercontent.com/assets/8702511/18966284/a3f3fa74-864e-11e6-8d83-ecb4e980fe8f.png)

I'm pretty sure I have the relationships set up correctly, so I'm not sure what step I'm missing here?

Here's my code, labeled appropriately.

**Category Model**

``` [Rails]
class Category < ActiveRecord::Base
  has_many :clues, -> { order(value: :asc) } # orders the clues based on their dollar amount
  belongs_to :game
end
```

**Game Model**

``` [Rails]
class Game < ActiveRecord::Base
  has_many :categories, dependent: :destroy
  belongs_to :user
end
```

**Games Controller**

``` [Rails]
class GamesController < ApplicationController
  def index
    @games = Game.first # i realize this won't show all games, it's just for testing
    render json: @games.categories
  end
end
```

**Games Table in Schema**

``` [Rails]
  create_table "games", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
  end

  add_index "games", ["user_id"], name: "index_games_on_user_id", using: :btree
```

**Categories table in Schema**

``` [Rails]
  create_table "categories", force: :cascade do |t|
    t.string   "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "game_id"
  end

  add_index "categories", ["game_id"], name: "index_categories_on_game_id", using: :btree
```

And finally,
**Game serializer**

``` [Rails]
class GameSerializer < ActiveModel::Serializer
  attributes :id, :categories
end
```

I'm hoping it's something silly like I misspelled something, or otherwise skipped a small step... I do create a new game in my Examples file, so I know that one exists... I'm just not sure why Categories isn't showing up!

Any suggestions are incredibly welcome!!!

**Comment by payne-chris-r** [comment]
Try doing your `index` the way we showed you with Game.all. I think your issue is you're just rendering one and thats why it looks weird. Follow convention always*!

*unless you have a really really good reason to not.

**Comment by berziiii** [comment]
Have you seeded any categories?

**Comment by tuckyeah** [comment]
I do have categories seeded - if you go to /categories they show up correctly (with their associated clues! so I know that relationship works)

I just tried doing Game.all and returning that, and I still get an empty 'categories' array... 

![image](https://cloud.githubusercontent.com/assets/8702511/18966797/9a2563dc-8650-11e6-8881-1fcc840435d4.png)

Proof that my /categories/ works:
![image](https://cloud.githubusercontent.com/assets/8702511/18966803/a57fd88e-8650-11e6-8015-c4e129a56941.png)

**Comment by payne-chris-r** [comment]
Is there a reason you're only rendering categories in your games#index? 

```
class GamesController < ApplicationController
  def index
    @games = Game.first # i realize this won't show all games, it's just for testing
    render json: @games.categories
  end
end
```

**Comment by tuckyeah** [comment]
@payne-chris-r I just wanted to see if I could get any categories to show up... I changed the code back to how a 'standard' index function should look and I'm still getting an empty array for categories (but the Game object looks right, see the image I posted above)

```
class GamesController < ApplicationController
  def index
    @games = Game.all 
    render json: @games
  end
end
```

**Comment by tuckyeah** [comment]
Talked with Chris - my issue is that my Game has categories, but my Categories don't have a game ID assigned to them (yet). I'm going to work on making sure that when we create a game, it picks five categories and then adds the correct game id to those categories.

 I'll close this for now, but likely reopen when I get stuck again :)

**Comment by jrhorn424** [comment]
Neat issue and solution. That must have been a pain to debug. Good work!
