### ISSUE TITLE
I am getting an error from Git Hub when I try to set up front end repo

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/full-stack-project#396]
I followed the same steps I followed for the back end. From the very first time I used the command 
git remote add origin git@github.com:rosmith76/browser-template-LiveMusicCalendar.git
I got the error fatal: remote origin already exists.
I deleted the repo, and started over. I got the same message.

**Comment by berziiii** [comment]
are you nested in the api repository?

**Comment by rosmith76** [comment]
i don't think so

browser path ~/wdi/projects/LiveMusicCalendar/browser-template-LiveMusicCalendar (master)$

api pathc ~/wdi/projects/LiveMusicCalendar/rails-api-template-LiveMusicCalendar (initial_backend_setup)$

**Comment by berziiii** [comment]
type `git remote -v` in terminal and share the output; in the repository you're having the issue in.

**Comment by rosmith76** [comment]
I destroyed the original, and started over. I got everything set up on GH

**Comment by jrhorn424** [comment]
> I destroyed the original, and started over

For future folks reading this thread, I do not advocate this solution to any problem.
