### ISSUE TITLE
A little confused about many-to-many relationship in my app

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#397]
The model I set up for the "This Book Sucks" app has users connected to books in a many-to-many relationship through another table called to_read_lists. It seems that with a join table it's implicit that each end of the relationship has a one-to-many relationship with to_read_lists. However, it makes more sense that the user would have only a one-to-one relationship with the to_read_lists. I think I am missing something, and I would like to show someone my code to make sure that I'm still on the right track in setting this up.

**Comment by berziiii** [comment]
Please share the code here. Also, if you could describe further the relationships and models you're working with, that would be a big help.

**Comment by julie1013** [comment]
The app I am making is called "This Book Sucks". The idea is that voracious readers with huge to-read lists who are looking to whittle down their lists to something manageable come to this app and read scathing reviews. Then the user decides based upon the review whether or not they want to remove the book from their to-read list. 

User has many books, and book has many users. This mutual relationship is established through to-read-list. But is it not implicit that the user has many to-read lists? The user should only have one. Of course, books have many to-read-lists.

User also has many reviews, and books have many reviews.

Relevant code:

``` ruby
class Book < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :to_read_lists
  has_many :to_read_lists, dependent: :destroy
end
```

``` ruby
class Review < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end
```

``` ruby
class ToReadList < ActiveRecord::Base
  belongs_to :user, inverse_of: :to_read_lists
  belongs_to :book, inverse_of: :to_read_lists
end
```

``` ruby
class User < ActiveRecord::Base
  include Authentication
  has_many :reviews
  has_many :books, through: :to_read_lists
  has_many :to_read_lists, dependent: :destroy
end
```

``` ruby
class ToReadListSerializer < ActiveModel::Serializer
  attributes :id
  has_one :user
  has_one :book
end
```

``` ruby
class UserSerializer < ActiveModel::Serializer
  attributes :id, :email, :books
end
```

Also, should there be a serializer for Books?

Thanks!

**Comment by payne-chris-r** [comment]
I think the problem you're having is with naming. I don't think your `to_read_lists` should be called that. I think it should just be called `to_read`. The list is created when a user wants to view all the books that they haven't axed/removed yet...
A user has many books through to_read (I think we can still think of an even better name), and a single book has many users through to_read. Unless I'm missing something and each user will have multiple lists that they are tracking, I think the word 'lists' at the end of `to_read_lists` is tripping you up (and rightfully so).

**Comment by julie1013** [comment]
"...lists" is tripping me up a bit, but the join table automatically pluralized it! What do you think would be a better name? 

Also, should there be a serializer for Books?

**Comment by payne-chris-r** [comment]
Can you post an ERD?
I'm confused where reviews are coming in. Don't users also have many books through reviews and vice versa as well as to_read??

**Comment by payne-chris-r** [comment]
Yeah, the table should definitely be plural, but your model (and ERD) should stay singular to keep your head straight. That's why I want you to remove the word `lists` though, because unless each `to_read_list` has many books, you don't want the word `lists` in there.

**Comment by payne-chris-r** [comment]
And you should only have a serializer for Books when you need a serializer for Books. You should also only serialize out attributes of books when you need those attributes of books. #privatebydefault

**Comment by julie1013** [comment]
I'm still trying to figure out how I would get the back end to grab the reviews and store them on the server.

Of course `to_read_list` has many books...

I took a picture of the ERD I drew, but it doesn't appear that I can attach it here.

**Comment by payne-chris-r** [comment]
I can't continue helping until I see the ERD so I better understand.
In my mind Users have many books through `to_read`, and vice-versa, Users also have many books through `reviews`, and vice-versa. Each `to_read` only belongs to one user and one book, and the same is true for a review. If you're saying that `to_read_list` has many books than I don't know what your model looks like.

**Comment by julie1013** [comment]
Should I email it to you?

**Comment by payne-chris-r** [comment]
Sure

**Comment by payne-chris-r** [comment]
chris.payne@ga.co

**Comment by julie1013** [comment]
Done.

**Comment by payne-chris-r** [comment]
![many-to-many](https://cloud.githubusercontent.com/assets/12667121/19001626/f13e242c-86fc-11e6-9d7c-a870edf673ab.jpg)

**Comment by payne-chris-r** [comment]
Ok. This is exactly how I expected it to look. I think you want to remove the word 'lists' from your join. It's confusing you (and me for that matter). It isn't a table full of lists it's a table full of `to_read` records that make up a list when you query that table.

**Comment by julie1013** [comment]
OK, but does it also mean that a user has many to_reads? Or is it different since it's a join table?

**Comment by payne-chris-r** [comment]
What about `books_to_read` or `approved_books` or something along those lines? `qualified_books`?

**Comment by julie1013** [comment]
OK, but it's still a single table. Doesn't that make it ...has many books to readS?

**Comment by payne-chris-r** [comment]
Use `approved_books` or `qualified_books` or make up a new (better) name that's similar to those.

**Comment by julie1013** [comment]
OK. Do I have to remigrate to do that or can I change it manually?

**Comment by payne-chris-r** [comment]
I'm not sure what you mean by 'change it manually', but you'll want to add a migration that deletes your current join and creates a new one, or renames your current join to what we've discussed.

**Comment by julie1013** [comment]
I meant changing the name of the join table. Anyway, thanks!
