### ISSUE TITLE
Localhost 3000 issue

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/full-stack-project#398]
I have set my secret keys in .env file. I am getting the following error when I try to access localhost 3000. The .env file is in my main folder. When I spin up the server there are no errors
Internal Server Error

Missing `secret_token` and `secret_key_base` for 'development' environment, set these values in `config/secrets.yml`
WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26) at localhost:3000

I have tried adding new keys, quitting out of atom

Any other suggestions?

**Comment by berziiii** [comment]
Can you please provide your `.env` code and your `secrets.yml` code? Thanks

**Comment by rosmith76** [comment]
.env

``` .rb
SECRET_KEY_BASE_DEVELOPMENT=67ca2dbd6b811a1664c360456bbba1b08b5a5aa3459b4e5a70ee1f8e715d562aafd71f003199de4ff289d42cf6166ee551bda7ed965ad165e31197188e1d7262
SECRET_KEY_BASE_TEST=cdfb9ce63b26f7eb56b2996333efc9d4c03dc4d48084f94cda1939e8444ab429746c70b100c2a82f4c93a1627c8b3d22a6fe0e48b0029cc62fb74e1c5bf3e2aa
```

I don't have a secrets.yml file

**Comment by berziiii** [comment]
The `secrets.yml` file should have something that links the development stage to `ENV[Secret_Key_Base_Development]`. Go look at the secrets.yml file in the clinic code along and copy the entire content over to a new `config/secrets.yml` file.

**Comment by rosmith76** [comment]
I am going to nuke it and start over

**Comment by rosmith76** [comment]
I destroyed the original, and started over. It works now

**Comment by jrhorn424** [comment]
Do you mean you nuked your git repository or delete your project folder?

Both are extreme responses when copying an example `config/secrets.yml` from another app would have worked.

**Comment by rosmith76** [comment]
I deleted the project folder and the git repository. Then I started over. I realized I made a few mistakes when setting everything up. From where I was in the process it made more sense to me to start over rather than try to fix the mess I had created.
