### ISSUE TITLE
Post request

### ISSUE THREAD

**Issue by NickBoyadjian** [ga-wdi-boston/full-stack-project#399]
For my project I have users, events, and attendees tables. I'm using the attendees table as a join table to link users to events, and events to users. What I want to do is have a user click on an event which will then put them on the attendees list. My attendees table has two columns, user_id and event_id. When i click on an event after I have logged in, i'm getting an error which says, "Cannot read property 'done' of undefined", and then "XMLHttpRequest cannot load http://localhost:3000/attendees. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400."

So the message is saying no header is present, however i do have a header:

``` js
const attend = function(event_id) {
  console.log("in api.js")
  let data = {
    user_id: 1, event_id: 2
  };

  $.ajax({
  url: app.host + '/attendees',
  method: 'POST',
  headers: {
    Authorization: 'Token token=' + app.user.token,
  },
  data: data
})
};
```

**Comment by berziiii** [comment]
I'm assuming this is in your `api.js` file. If so, you need to access the `user_id` as well as `event_id`. Then you're data object is not structured correctly. You need to name the object you're storing as `data` like your api expects.

**Comment by payne-chris-r** [comment]
Check your rails server. My guess is you have a "Bad Request" meaning you're not sending rails enough data or you're sending the wrong data. Either way, Brian seems to be onto something that your data object might not be structured the way your API is expecting it...

**Comment by NickBoyadjian** [comment]
Okay, I changed the data to: 

``` js
  let attendee = {
    "attendee": {
      "user": {
        "id": 1
      },
      "event": {
        "id": 2
      }
    }
  };
```

at this point i am able to see a post however the id values are nil.

**Comment by berziiii** [comment]
What are the params that your `attendee` controller accepts?
 Should be `user_id` and `event_id`...

Not a user object with an `id` but a `user_id`. Same with `event`.

**Comment by payne-chris-r** [comment]
Have you tried a curl request?

**Comment by NickBoyadjian** [comment]
Got it working, I had to format it the way Brian said. Thanks

**Comment by berziiii** [comment]
Please close with correct data structure example @NickBoyadjian. Thanks.

**Comment by NickBoyadjian** [comment]
``` js
let attendee = {
    "attendee": {
      "user_id": app.user.id,
      "event_id": event_id
    }
  };
```
