### ISSUE TITLE
Heroku issue and counter cache question

### ISSUE THREAD

**Issue by eshimel** [ga-wdi-boston/full-stack-project#4]
I haven't been able to get my backend to work in heroku.  most recently the message is that the page doesn't exist.  I've gone through the readme steps three times on my own,  made sure all my branches are up to date, and tried to trouble-shoot from console error messages, though I am not getting any this time.  
Also, I'm trying to figure out if using a counter in my db will be helpful for my program, but I'm a little unclear from the rails api documentation and other sources that I have looked at, if it is necessary or if I am using it correctly.

Thanks!

**Comment by gaand** [comment]
Helping.
