### ISSUE TITLE
Need help with data model

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/full-stack-project#40]
Creating beers at the same time, where beers are linked to establishment.  Need a few minutes to figure out how to link them in the data structure.

**Comment by GA-MEB** [comment]
@jcmeyer10 
Can you explain what you mean? Is it that you want to create multiple beers in a single request?

**Comment by jcmeyer10** [comment]
I would like to be able to link them to a location at the time of the creation, does that make sense?

**Comment by jcmeyer10** [comment]
I have a join table but want to make sure it makes sense based on what I am trying to accomplish

**Comment by GA-MEB** [comment]
I see. So you want to associate a beer with a particular establishment when you create it. Where is the information about the establishment being provided? In other words, how does the BeersController know which establishment you're talking about?

**Comment by jcmeyer10** [comment]
I feel like I am reading this wrong but it's being provided in a form where you create a location (sorry for going back and forth but location is how I have it labeled in my api) you have a form for a beer with one submit button.  I don't know how they should talk to one another.  Is there a way to say if location.save === true then beer.save?

**Comment by GA-MEB** [comment]
So you make a request to create a location, and then make a request to create a beer, and the beer that you create gets associated with the location you just created?

**Comment by jcmeyer10** [comment]
Ugh, this feels like a two step process again.

On Wed, Nov 11, 2015 at 11:42 AM, Matt Brendzel notifications@github.com
wrote:

> So you make a create location request, and then make a create beer
> request, and the beer that you create gets associated with the location you
> just created?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-wdi-boston/rails-project-full-stack-app/issues/40#issuecomment-155839112
> .

## 

Regards,
Jeff Meyer

857-206-3572

**Comment by jcmeyer10** [comment]
Can I use a shovel?  location.beers << beer

On Wed, Nov 11, 2015 at 11:56 AM, Jeff Meyer jcmeyer10@gmail.com wrote:

> Ugh, this feels like a two step process again.
> 
> On Wed, Nov 11, 2015 at 11:42 AM, Matt Brendzel notifications@github.com
> wrote:
> 
> > So you make a create location request, and then make a create beer
> > request, and the beer that you create gets associated with the location you
> > just created?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ga-wdi-boston/rails-project-full-stack-app/issues/40#issuecomment-155839112
> > .
> 
> ## 
> 
> Regards,
> Jeff Meyer
> 
> 857-206-3572

## 

Regards,
Jeff Meyer

857-206-3572

**Comment by GA-MEB** [comment]
The issue is that they're two separate requests, on two separate controllers (LocationsController and BeersController). Come see me in CR1 and we'll talk through it.

**Comment by GA-MEB** [comment]
The solution here is to save data on the front-end, where you're making both requests.
