### ISSUE TITLE
Heroku bundler version warning can be safely ignored

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/full-stack-project#400]
Reported by @wmcb91.

> Not breaking anything yet but it is odd.  When I push to heroku the first lines of interest are these.
> 
> ```
> remote: Building source:
> remote: 
> remote: -----> Ruby app detected
> remote: -----> Compiling Ruby/Rails
> remote: -----> Using Ruby version: ruby-2.3.1
> remote: -----> Installing dependencies using bundler 1.11.2
> remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
> remote:        Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
> ```
> 
> I ran install bundler and got
> 
> ```
> Successfully installed bundler-1.13.1
> ```
> 
> then I ran a bundle install incase it would update anything else and in the output there is a line confirming
> 
> `Using bundler 1.13.1`
> 
> I made a small change and committed so I could push to heroku again and got the same
> 
> ```
> remote:        Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
> ```
> 
> message.  Weird, but again it doesn’t seem to be breaking anything.

**Comment by jrhorn424** [comment]
@wmcb91 After updating and running `bundle install`, did the `Gemfile.lock` change? (`git status`)

**Comment by wmcb91** [comment]
Yes, the Gemfile.lock's last two lines are now
 `184   BUNDLED WITH `<br>`185   1.13.1`

**Comment by berziiii** [comment]
Still open @wmcb91?

**Comment by wmcb91** [comment]
According to [this stackoverflow thread](http://stackoverflow.com/questions/37375215/how-to-solve-the-update-bundler-warning-in-rails-when-deploying-to-heroku), it seems like the language used by Heroku does not provide a solution that will get rid of the warning since Heroku is limited to bundler version 1.11.2.

**Comment by jrhorn424** [comment]
Thanks @wmcb91
