### ISSUE TITLE
What is the meaning to the limit # in schema.rb file

### ISSUE THREAD

**Issue by JaimeGaribaldo7** [ga-wdi-boston/full-stack-project#402]
I’m making migrations to add columns and their datatypes BUT I got a weird result. This is what it looks like in my schema.rb file

```
 create_table "pokemons", force: :cascade do |t|
    t.datetime "created_at",           null: false
    t.datetime "updated_at",           null: false
    t.string   "name"
    t.integer  "number",     limit: 2

```

I'm asking about the last section where it says "t.integer 'number', limit: 2"
I'm having issues understanding what the LIMIT: 2 Means?

**Comment by JaimeGaribaldo7** [comment]
I found this link very useful https://ariejan.net/2009/08/20/once-and-for-all-rails-migrations-integer-limit-option/

The LIMIT corresponds to the Bytes for the numbers you are using.
I was using the datatype `:smallint`, so my limit was set to 2.

**Comment by jrhorn424** [comment]
Thanks so much for reporting @JaimeGaribaldo7!

**Comment by laurenallegra** [comment]
Thanks for posting your solution, @JaimeGaribaldo7 ! This was really helpful for me to, too!
