### ISSUE TITLE
User Stories Wizard ERD

### ISSUE THREAD

**Issue by viohlet** [ga-wdi-boston/full-stack-project#403]
Hi,

I am building an app that helps developers to store their user stories. And I am having problems with the values of my ERD. My ERD right now:

One to many rel.
-User (email, password)
-Projects (title, add, update, remove)

One to many rel.
-Projects (title, add, update, remove)
-User Stories (role, action, goal, add, update, remove)

So: user has many projects but projects belong to one user only. A project can have many user-stories but user-stories have only one project (or project title).

Problem: I will have options to delete, update, and add user-stories and the same actions for projects.

Doubt: Should I reconsider:

One to many rel.
-User (email, password)
-User Stories (role, action, goal, add, update, remove, project-title)

Should I skip being able to add/remove/update project-titles and have them affect all user-stories inside those project-titles? Am I attempting to nest too much? I'd like to keep it simple.

Thanks for your guidance,
Violeta

**Comment by berziiii** [comment]
In talking with Violeta, this ERD is correct and makes sense for what she wants.

`user` has_many `projects`
`project` belongs_to `user`
`project` has_many `user_stories`
`user_story` belongs_to `project`

**Comment by berziiii** [comment]
Please add any additional information about the table structures and close @viohlet

**Comment by payne-chris-r** [comment]
What irony...

**Comment by viohlet** [comment]
Thanks for your guidance, Brian!
