### ISSUE TITLE
changing table name

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#404]
I wanted to change join table name from `to_read_list` to `qualified_books`

I got an error when I ran `rake db:migrate`:

This is my code from the generated migrate file:

``` ruby
class RenameToReadListToQualifiedBooks < ActiveRecord::Migration
  def change
    rename_table :to_read_list, :qualified_books
  end
end
```

```
PG::UndefinedTable: ERROR:  relation "to_read_list" does not exist
: ALTER TABLE "to_read_list" RENAME TO "qualified_books"
/Users/julieesris/WDI_Fall_2016/projects/book-sucks/book-sucks-backend/db/migrate/20160930184821_rename_to_read_list_to_qualified_books.rb:4:in `change'
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "to_read_list" does not exist
: ALTER TABLE "to_read_list" RENAME TO "qualified_books"
/Users/julieesris/WDI_Fall_2016/projects/book-sucks/book-sucks-backend/db/migrate/20160930184821_rename_to_read_list_to_qualified_books.rb:4:in `change'
PG::UndefinedTable: ERROR:  relation "to_read_list" does not exist
/Users/julieesris/WDI_Fall_2016/projects/book-sucks/book-sucks-backend/db/migrate/20160930184821_rename_to_read_list_to_qualified_books.rb:4:in `change'
```

**Comment by payne-chris-r** [comment]
So it's saying `to_read_list` does not exist. Why might it not exist?

**Comment by julie1013** [comment]
Damned if I know. That's what I named it, and that's what I see in my files. I pluralized it, adding an s to all instances of List/list in the file and file name. It says it migrated, but I see no evidence in my files that the name has changed.

**Comment by julie1013** [comment]
Or do I have to manually rename everything? Doesn't that defeat the point of the migration?

**Comment by payne-chris-r** [comment]
Slow down. Have you checked to see if it exists in your database?

**Comment by julie1013** [comment]
It looks like it made the changes in schema

**Comment by payne-chris-r** [comment]
Can you post the code in your schema.rb file here?

**Comment by julie1013** [comment]
Thanks, but Brian actually helped me with manually changing the names outside the schema. The schema was fine.

**Comment by berziiii** [comment]
When changing names, be sure everything that corresponds with that name changes or DOESN't change. aka, don't have a migration names `CreateX` and in the migration file, `y_table` as the name of the table being created.

**Comment by payne-chris-r** [comment]
Was it that you had created `to_read_lists` and you were trying to rename `to_read_list`?!?

**Comment by julie1013** [comment]
Yeah. I hadn't realized it needed to be plural
