### ISSUE TITLE
Scaffold command

### ISSUE THREAD

**Issue by viohlet** [ga-wdi-boston/full-stack-project#405]
Hi, when scaffolding my one-to-many relationship

user has_many projects
project belongs_to user
project has_many user_stories
user_story belongs_to project

Problem:
I am having doubts about the strings. 

For my Projects table: bundle exec rails g scaffold Projects title:string
Should I have added here anything about my user id?

For my User_stories table: bundle exec rails g scaffold User_stories role: string action:string goal:string project:references
is "project:reference" necessary if this is a one-to-many relationship only?

**Comment by berziiii** [comment]
Yes it is. And for scaffolding `Projects` you needs a `user:references` if a project belongs to a user.

**Comment by viohlet** [comment]
Thank you, Brian!

**Comment by jrhorn424** [comment]
Great issue, thanks @viohlet!
