### ISSUE TITLE
Table with incorrect attributes

### ISSUE THREAD

**Issue by BMorse09** [ga-wdi-boston/full-stack-project#406]
I scaffolded a table, but I realized the attributes I gave it are incorrect. I have not assigned any values to the attributes yet. Should I alter the attributes manually, or go in and remove all the files associated with the table and then re-create it in the terminal with the correct attributes?

**Comment by berziiii** [comment]
@BMorse09, please provide solution from last night on how we rolled back and altered the migrations to get the tables set up correctly. Thanks.

**Comment by BMorse09** [comment]
We used rake db:rollback to set back the migrations one step, then inputted the correct table attributes and values in Atom. Once those were right, we re-ran db:nuke_pave to set the table up correctly.
