### ISSUE TITLE
[Heroku] "Application Error" After Re-deploying

### ISSUE THREAD

**Issue by jenboyd** [ga-wdi-boston/full-stack-project#407]
I successfully deployed my app to Heroku and was able to see the tables I created.

I had initially commented out the Create, Update, and Destroy functions in my Trips Controller. (I don't want the trips to be able to be modified by the users). I then realized I probably want that function so that I can test the deployed database, so I added them back in. After redeploying to Heroku I am getting this error in the browser.

![screen shot 2016-09-30 at 4 43 44 pm](https://cloud.githubusercontent.com/assets/19177290/19006436/73910018-872d-11e6-813d-4939b1042336.png)

I'm thinking I missed a step somewhere, below is what I did when deploying:
- commit changes on working branch
- `git checkout master`
- `git merge <working branch>`
- `git push origin master`
- `git push heroku master`
- `heroku run rake db:migrate`
- `heroku restart`
- `heroku open`

Here is what the log looks like on Heroku:

-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.3.1
-----> Installing dependencies using bundler 1.11.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Using rake 11.2.2
       Using i18n 0.7.0
       Using json 1.8.3
       Using minitest 5.9.0
       Using thread_safe 0.3.5
       Using builder 3.2.2
       Using erubis 2.7.0
       Using mini_portile2 2.1.0
       Using pkg-config 1.1.7
       Using rack 1.6.4
       Using mime-types-data 3.2016.0521
       Using thor 0.19.1
       Using arel 6.0.3
       Using bcrypt 3.1.11
       Using concurrent-ruby 1.0.2
       Using pg 0.18.4
       Using rack-cors 0.4.0
       Using bundler 1.11.2
       Using rails_serve_static_assets 0.0.5
       Using rails_stdout_logging 0.0.5
       Using jsonapi 0.1.1.beta2
       Using tzinfo 1.2.2
       Using mime-types 3.1
       Using nokogiri 1.6.8
       Using rack-test 0.6.3
       Using sprockets 3.7.0
       Using rails_12factor 0.0.3
       Using activesupport 4.2.7.1
       Using mail 2.6.4
       Using rails-deprecated_sanitizer 1.0.3
       Using globalid 0.3.7
       Using activemodel 4.2.7.1
       Using loofah 2.0.3
       Using rails-dom-testing 1.0.7
       Using activerecord 4.2.7.1
       Using activejob 4.2.7.1
       Using rails-html-sanitizer 1.0.3
       Using actionview 4.2.7.1
       Using actionpack 4.2.7.1
       Using actionmailer 4.2.7.1
       Using railties 4.2.7.1
       Using sprockets-rails 3.1.1
       Using active_model_serializers 0.10.2
       Using rails-api 0.4.0
       Using rails 4.2.7.1
       Bundle complete! 16 Gemfile dependencies, 45 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Bundle completed (0.32s)
       Cleaning up the bundler cache.
       Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
###### WARNING:

```
   No Procfile detected, using the default web server.
   We recommend explicitly declaring how to boot your server process via a Procfile.
   https://devcenter.heroku.com/articles/ruby-default-web-server
```

-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> console, rake, web, worker
-----> Compressing...
       Done: 26.6M
-----> Launching...
       Released v8
       https://boston-day-trips.herokuapp.com/ deployed to Heroku

**Comment by jenboyd** [comment]
Solution: 

I ran `heroku run rails console` which gave me the following error

![screen shot 2016-09-30 at 6 01 46 pm](https://cloud.githubusercontent.com/assets/19177290/19008262/00f5f332-8738-11e6-906e-433087b1cf5b.png)

Once I fixed the syntax error, I redeployed and everything seems to be working

**Comment by jrhorn424** [comment]
Great issue! Good job debugging, @jenboyd.
