### ISSUE TITLE
several errors when pushing master branch to heroku

### ISSUE THREAD

**Issue by knoddin** [ga-wdi-boston/full-stack-project#409]
I am unable to successfully push to heroku from my master branch and am coming across several errors. The last error listed is:

``` sh
# edited by @jrhorn424 - please format your error logs using a fenced code block
error: failed to push some refs to 'https://git.heroku.com/rocky-dawn-18013.git'

many, many lines above that, there are errors that read:

remote:        Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote: sh: 2: Syntax error: Unterminated quoted string
remote: sh: 2: Syntax error: Unterminated quoted string
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     LoadError: cannot load such file -- CSV
```

I am unclear what is wrong, except that it can't load my CSV file. Should I relocate it? It's currently in a "data" folder that I created in the root of my repo.

**Comment by payne-chris-r** [comment]
Did you make sure you've closed all your quotes? Looks like it's complaining about missing a quote. If you think it's a specific file you can try pushing without it first to eliminate other potential issues. I think you're probably missing a close quote in your gemfile though.

**Comment by jrhorn424** [comment]
To run your linter outside of your editor, go into your project and run `rubocop`.

https://github.com/bbatsov/rubocop

The linter will catch both style and syntax errors, so don't ignore it wholesale. Read each one and fix it. If you don't know how to fix it, show us the code and we can advise. With the current rubocop configuration, there may be **rare** cases that you can ignore, but I won't know until I see the code.

**Comment by jrhorn424** [comment]
Please format your errors. It's polite. I've done this one for you.

**Comment by jrhorn424** [comment]
> I am unclear what is wrong, except that it can't load my CSV file. Should I relocate it? It's currently in a "data" folder that I created in the root of my repo.

That's not your only error. I'd fix what @payne-chris-r suggested and try again. Let us know if anything changes by telling us what you fixed (pasting the code would help), and also pasting the new error message if any.

**Comment by knoddin** [comment]
Thank you. I ran rubocop in terminal and I am getting notices regarding a missing frozen string literal in my gemfile, however I have not touched my gem file. I have read that running this command can help ignore them, but I am not comfortable doing that unless you think that is a fix: 

```
bundle exec rubocop --auto-correct --only FrozenStringLiteralComment
```

The errors still indicate that it can't load my CSV file. Is it possible that requiring the CSV file in the rake file was not a good idea? Here is my db.rake file code:

```
require 'CSV'

namespace :db do
  desc 'Load example data from db/examples.rb'
  task examples: :environment do
    require_relative '../../db/examples'
  end

  desc 'Fill the weeks table with week data'
  task weeks: :environment do
    Week.transaction do
      CSV.foreach(Rails.root + 'data/weeks.csv',
                  headers: true) do |row|
        week = row.to_hash
        next if Week.exists? week
        Week.create!(week)
      end
    end
  end

  unless Rails.env == 'production'
    desc 'Drop and setup the development database with examples'
    task nuke_pave:
      %w(environment db:drop db:create db:migrate db:seed db:examples db:weeks) do
      puts "Nuke and pave of #{Rails.env} complete."
    end
  end
end

```

I know how to force files (if that is a good option), but how do I exclude them?

**Comment by jrhorn424** [comment]
Thanks for running rubocop!

> The errors still indicate that it can't load my CSV file.

I would debug what `Rails.root + 'data/weeks.csv'` returns.

Also, can you confirm that you fixed the syntax error that was reported by heroku?

> Is it possible that requiring the CSV file in the rake file was not a good idea? 

You may have hit upon something there. I don't know if it's a bad idea, but it definitely breaks convention.

If this is data that is required for you app to function, then I would include it in `db/seeds.rb`. If it is data that is sample data to play with, include it in `db/examples.rb`. Don't manipulate it directly in a rake task.

**Comment by jrhorn424** [comment]
@knoddin Any updates for this issue?

**Comment by knoddin** [comment]
Not yet - I tried moving the CSV import to my seed.rb file and the data didn't import. Still working on it.

**Comment by jrhorn424** [comment]
Did it still have all the `rake` junk in it? See my diff and comments over at #418. There are a few other common mistakes there you might want to avoid as well.

**Comment by knoddin** [comment]
I was able to import the CSV successfully using the seed.db file instead of the db.rake file (thanks for the help, Jaime!). Now trying to import.

**Comment by knoddin** [comment]
Correct code in seed file:

``` rb
require 'CSV'
Week.transaction do
  CSV.foreach('data/weeks.csv', headers: true, header_converters: -> (h) { h.downcase.to_sym }) do |week|
   p week
   Week.create(start_date: week[:start_date], end_date: week[:end_date].to_s)
 end
end
```

**Comment by knoddin** [comment]
I was able to push everything to heroku, but am unable to rake my seed data in heroku because of the CSV file. I am again getting this error:

```
Running rake db:seed on ⬢ rocky-dawn-18013... up, run.5443 (Free)
  ActiveRecord::SchemaMigration Load (0.9ms)  SELECT "schema_migrations".* FROM "schema_migrations"
rake aborted!
LoadError: cannot load such file -- CSV
```

**Comment by payne-chris-r** [comment]
My guess is your file path may be incorrect. Did you see the rails root piece Jaime had in his code? Do some research on that...

**Comment by knoddin** [comment]
corrected it so my code looks like this 

``` rb
require 'CSV'
Week.transaction do
  CSV.foreach(Rails.root + 'data/weeks.csv', headers: true, header_converters: -> (h) { h.downcase.to_sym }) do |week|
   p week
   Week.create(start_date: week[:start_date], end_date: week[:end_date].to_s)
 end
end
```

but I am receiving the same error when I do heroku run rake db:seed

**Comment by jrhorn424** [comment]
@knoddin Can you look at Jaime's most recent comment? I think you need to convert the CSV row into something else before you do `Week.create`.

**Comment by knoddin** [comment]
I made my 'csv' extension (in require 'csv' line in the seed file) lowercase. Heroku will not read it as an extension if it is uppercase. It worked for me! Thank you!

Source: [http://stackoverflow.com/questions/14481490/ruby-not-loading-csv-from-stdlib](url)
