### ISSUE TITLE
File read error.  'readAsText' on 'FileReader': The object is already busy reading Blobs.

### ISSUE THREAD

**Issue by DanielJRaine** [ga-wdi-boston/full-stack-project#411]
I have added a file upload to my app.  It can successfully console.log the file, but when I try to read the file with a FileReader, it generates the error

```
Uncaught DOMException: Failed to execute 'readAsText' on 'FileReader': The object is already busy reading Blobs.
    at Error (native)
    at eval (eval at evaluate (unknown source), <anonymous>:1:20)
    at HTMLButtonElement.onFileUpload (http://localhost:8080/bundle.js:637:4)
    at HTMLButtonElement.dispatch (http://localhost:8080/vendor.bundle.js:4847:28)
    at HTMLButtonElement.elemData.handle (http://localhost:8080/vendor.bundle.js:4659:29)
```

The code that I wrote in my events.js file looks like the following

```
const onFileUpload = (event) => {
  let selectedFile = $('#file-input-upload').get(0).files[0];
  let fileReader = new FileReader();
  console.log(fileReader.readAsText(selectedFile));
  debugger;
};

const addHandlers = () => {
  $('#file-button-upload').on('click', onFileUpload);
};
```

Thoughts?  Blobs?

**Comment by DanielJRaine** [comment]
It turns out that reading files takes time, so you need to set an event listener to wait until the instance of FileReader has finished reading the file, at which point it will emit an event.  To catch the event, use the FileReader.onload method and pass it an event, as described below...

```const onFileUpload = (event) => {
  event.preventDefault();
  let selectedFile = $('#file-input-upload').get(0).files[0];
  let fileReader = new FileReader();

  fileReader.readAsText(selectedFile);
  fileReader.onload = function(event) {
    console.log(event.target.result);
  };
};

```
> output:
X: 3
T: MacArthur Road
R: reel
M: 4/4
L: 1/8
K: Emaj
|: B2 Gc Bcef | g2 (3ggg fece | ~f3 g fece | a2 ga gfec |
B2 Gc Bcef | g2 (3ggg fece | f3 g fecA | Bcef e4 :|
|: be (3eee bec'e | beeg fece | ~f3 g fece | a2 ga gfec |
[1 be (3eee bec'e | beeg fece | ~f3 g fecA | Bcef e4 :|
[2 B2 Gc Bcef | g2 (3ggg fece | f3 g fecA | Bcef e4 |]
```

**Comment by jrhorn424** [comment]
Congratulations on debugging this. When I saw your message on slack I thought it would... non-straight-forward.

You're running into async issues. We give async a full treatment in the next unit. Really impressive to deal with this on your own with what we've given you so far. Good work!
