### ISSUE TITLE
Button not firing

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#413]
I added some buttons dynamically to a master list that the user sees upon login. 

``` js
const showMasterList = function (){
  let masterList = $('#master-ordered-list');
  for (let i = 0; i < masterList.length; i++){
    $('li').append('<form>'+
      '<input type=submit value="Add to your list" id=add-to-my-to-read-list class=add-to-my-to-read-list-button>' + '</form>');
  }
};
```

It's called in index.js

``` js
$('#add-to-my-to-read-list').on('submit', events.onAddToMyToReadList);
```

However, it doesn't get any further than that. When I click it, the page refreshes. And yes, there's event.preventDefault();

``` js
const onAddToMyToReadList = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.addToMyToReadList(data)
    .done(ui.onAddToMyToReadListSuccess)
    .fail(ui.onError);
  };
```

I inspected and made sure that the button indeed had the correct ID-- and it does. And yet when it's firing it doesn't even seem to hit `onAddToMyToReadList`

I've double, triple, and quadruple checked to make sure that the IDs are matched. The only thing I can think of is that since I added the buttons dynamically that there was this issue.

**Comment by berziiii** [comment]
If a button is added dyamically, after the initial page is loaded, there is a good chance that the button 'doesn't' exist when the event handler is attached. IF this is the case, you may need to look into attaching the event handler after your create the html for the `showMasterList`.

**Comment by julie1013** [comment]
That's it, thanks! I put the parent element (li) in and then targeted the form (button)  after submit.

``` js
$('li').on('submit', 'form', events.onAddToMyToReadList);
```

**Comment by berziiii** [comment]
Also, a much better issue, @julie1013. Thank you for following process!

**Comment by julie1013** [comment]
A "much better issue"? Ummm oK o_O

**Comment by jrhorn424** [comment]
Yep, great issue. Much improved. Thanks @julie1013!
