### ISSUE TITLE
[HTML/JS] Attempting to dynamically add form fields, multiple AJAX requests from single form

### ISSUE THREAD

**Issue by abeers** [ga-wdi-boston/full-stack-project#416]
## Problem

In my recipe app, I have a form that creates a new recipe based on attributes given in the form. The logic works fine as far as adding a single ingredient and instruction (and assigning relationships to recipes).

``` html
      <form id="add-new-recipe">
        <fieldset>
          <legend>Add a recipe!</legend>
          <input type="text" name="recipe[name]" placeholder="Name of Recipe">
          <input type="number" name="recipe[time]" placeholder="Number of Minutes to Make">
          <input type="text" name="ingredient[name]" placeholder="Name of Ingredient">
          <input type="number" name="recipeingredient[quantity]" placeholder="Quantity">
          <input type="text" name="ingredient[units]" placeholder="Units">
          <input type="text" name="instruction[step]" placeholder="Instruction">
          <input type="text" name="instruction[step]" placeholder="Instruction">
          <input type="submit" name="submit" value="Add recipe!">
        </fieldset>
      </form>
```

I've found resources online to help with dynamically adding form fields, but before I implement that, I want to make sure I can get data from those form fields.

I've just added that second 'instruction' input to test out `getFormFields`. I understand what it's doing (the second input overrides the first input), but I'm wondering how to get both pieces of data instead of just one.
## Ideas
- Make a custom getFormFields
  I can try to write a different getFormFields that can recognize duplicate names and handle them the way I want them to be handled. This feels a little complicated, but I might be able to do it.
- Make nested forms and use getFormFields on all of them
  If I have something like this:

``` html
      <form id="add-new-recipe">
        <fieldset>
          <legend>Add a recipe!</legend>
          <input type="text" name="recipe[name]" placeholder="Name of Recipe">
          <input type="number" name="recipe[time]" placeholder="Number of Minutes to Make">
          <input type="text" name="ingredient[name]" placeholder="Name of Ingredient">
          <input type="number" name="recipeingredient[quantity]" placeholder="Quantity">
          <input type="text" name="ingredient[units]" placeholder="Units">
          <form class="instruction-form"
            <input type="text" name="instruction[step]" placeholder="Instruction">
          </form>
          <form class="instruction-form"
            <input type="text" name="instruction[step]" placeholder="Instruction">
          </form>
          <input type="submit" name="submit" value="Add recipe!">
        </fieldset>
      </form>
```

I can then do something like:

``` js
      $('.instruction-form').forEach(getFormFields(form));  //Not going for 100% syntax here
```

and I can then use that data to have separate instructions. However, I don't know how the `getFormFields` that is handling the 'add-new-recipe' form will handle the sub-forms.

**Comment by jrhorn424** [comment]
How about firing multiple get requests in serial? So, listen to the submit event of the out form, then have the handler fire a function that makes all your requests using the data you need from each subsection? So each ajax request will have a single line of `let data = getFormFields(/* not (only) event.target*/)`.

**Comment by abeers** [comment]
I think I understand. I'll try to write it in the next hour or so and report back. Thanks!

**Comment by abeers** [comment]
## Possible Solution:

I don't know if I did it the way you said or used best practices, but this works:

``` html
      <form id="add-new-recipe">
        <fieldset>
          <legend>Add a recipe!</legend>
          <input type="text" name="recipe[name]" placeholder="Name of Recipe">
          <input type="number" name="recipe[time]" placeholder="Number of Minutes to Make">
          <input type="text" name="ingredient[name]" placeholder="Name of Ingredient">
          <input type="number" name="recipeingredient[quantity]" placeholder="Quantity">
          <input type="text" name="ingredient[units]" placeholder="Units">
          <form>
          </form>
          <form class='instruction-form'>
            <input type="text" name="instruction[step]" placeholder="Instruction">
          </form>
          <form class='instruction-form'>
            <input type="text" name="instruction[step]" placeholder="Instruction">
          </form>

          <input type="submit" name="submit" value="Add recipe!">
        </fieldset>
      </form>
```

I need that empty form for some reason. If I don't have it, jQuery thinks the first 'instructions-form' is part of the outer form. The linter also hates that I have nested forms.

``` js
  let instructionForms = $('.instruction-form');

  recipeApi.addRecipe(recipeData)
    .done(function (recipeResult) {
        //other stuff to add ingredients
              for (let i = 0; i < instructionForms.length; i++) {
                let instructionData = getFormFields(instructionForms[i]);
                instructionData.instruction.recipe_id = recipeResult.recipe.id;
                api.addInstruction(instructionData)
                  .done(console.log('Success!'))
                  .fail(ui.failure);
                }
            })

     .fail(ui.failure);
};
```

I also don't love having a `for` loop in my api calls, but it does seem necessary to process each instruction. If you think there's a better way to do this, let me know, otherwise I'll continue with this.

**Comment by jrhorn424** [comment]
There's a better way, perhaps. Unnest your forms. Have a form at the end that only contains a submit.

These are sibling nodes, so your loop that is kicked off by the last form has to know what other form `id`s to look for, but I think that's ok, especially since it will let you use `getFormFields` as you expect, and satisfy your linter.

**Comment by jrhorn424** [comment]
Hey @abeers Do you want to keep this open for a few more weeks to discuss anything, or should it be closed?

**Comment by abeers** [comment]
My bad. I am currently still using the nested forms, but I plan to refactor them out into separate forms, targeting them once the submit button is clicked.
