### ISSUE TITLE
Requesting a 1-on-1 regarding handlebars as well as GitHub

### ISSUE THREAD

**Issue by BMorse09** [ga-wdi-boston/full-stack-project#417]
Having trouble getting the proper data to display on my frontend using handlebars. Also having some GitHub issues that I need to fix before deploying.

**Comment by berziiii** [comment]
Can you provide code that you have for when you successfully get data back from the request, the handlebars template and anything else that you use in this process?

**Comment by BMorse09** [comment]
I fixed the initial problem I was having. However, I now need my data to be displayed more neatly, preferably in a table, and I have no idea how to do it (this is necessary for functionality, not just for style). But foremost, I would like to solve those aforementioned GitHub issues, which I do not trust myself to troubleshoot.

**Comment by payne-chris-r** [comment]
Please make separate issues for your two problems.

**Comment by jrhorn424** [comment]
Thanks @BMorse09.

**Comment by jrhorn424** [comment]
I think the reason this fell off our radar is that I assumed when you closed the issue, you'd be making two other issues since you were having two problems.

@payne-chris-r?

**Comment by payne-chris-r** [comment]
Yes. Please make two issues like I asked previously. 
Something like: "`Handlebars not rendering correctly.`" and "`[GitHub] <explanation of your issue>`"

**Comment by jrhorn424** [comment]
From @BMorse09 via Slack:

> To be clear, I would like the 1-on-1 to be solely about my GitHub problems.

cc @payne-chris-r

**Comment by payne-chris-r** [comment]
Are you all set on this now @BMorse09 ? Can you please close?
