### ISSUE TITLE
Problem inserting csv file data into table

### ISSUE THREAD

**Issue by JaimeGaribaldo7** [ga-wdi-boston/full-stack-project#418]
I made a Data directory and created a Csv file that I want to add into one of my tables. I'm having trouble remembering how to insert this data to the table. I have gone through the repositories where we worked on with Doctors/Patients, Ingredients/Recipes, and Library/Books but i cant find where we did this. I have a feeling it has to do with the bulk load file we created but I cant remember which steps to take in order to do this. If I do have to create a script file where i bulk load the data, should I run: 
`bundle exec rails db`
 or

`bundle exec rails console`

when I'm running the scripts?

**Comment by payne-chris-r** [comment]
https://github.com/ga-wdi-boston/ruby-enumerable-io

**Comment by JaimeGaribaldo7** [comment]
Tried adjusting my data but nothing is happening, this is what my seeds.rb file looks like: 

```
require 'CSV'
namespace :db do
  desc 'Fill the pokemons table with pokemons data'
  task pokemons: :environment do
    Pokemon.transaction do
      CSV.foreach(Rails.root + 'data/pokemon.csv', headers: true) do |row|
        pokemon = row.to_hash
        pokemon.each do |hs|
          Pokemon.create([{ name: hs[:name], number: hs[:number], pokemontype:
            hs[:pokemontype] }])
        end
      end
    end
  end
end
```

**Comment by jrhorn424** [comment]
That's not `seeds.rb`. That's a Rake task. Please move all of that code into `db/seeds.rb` and test it by running `rake db:seed`.

**Comment by jrhorn424** [comment]
How large is the seed file (how many rows)?

**Comment by JaimeGaribaldo7** [comment]
Jeff, thats where it is.. In my seeds.rb file inside of the db directory.

My csv file is about 150 rows.
the seeds.rb file is 15 rows.

I didnt specify that it was in db, that was my mistake.

**Comment by jrhorn424** [comment]
There shouldn't be anything like `namespace` or `task` in a seed file. I think you've copied something from a rake task and pasted it into `db/seeds.rb`.

**Comment by JaimeGaribaldo7** [comment]
I dont know what a my db/seeds.rb should look like. That code is what I've seen other people do?

**Comment by jrhorn424** [comment]
> I dont know what a my db/seeds.rb should look like. That code is what I've seen other people do?

Other people are wrong.

Do this:

``` diff
require 'CSV'
- namespace :db do
-  desc 'Fill the pokemons table with pokemons data'
-  task pokemons: :environment do
    Pokemon.transaction do
      CSV.foreach(Rails.root + 'data/pokemon.csv', headers: true) do |row|
        pokemon = row.to_hash
        pokemon.each do |hs|
          Pokemon.create([{ name: hs[:name], number: hs[:number], pokemontype:
            hs[:pokemontype] }])
        end
      end
    end
-  end
- end
```

**Comment by JaimeGaribaldo7** [comment]
When i ran the command with db:seed, the terminal gave me this output: 

```
rake aborted!
TypeError: no implicit conversion of Symbol into Integer
/Users/jaimegaribaldo/wdi/projects/Project-2/rails-api-template-master/db/seeds.rb:11:in `[]'
/Users/jaimegaribaldo/wdi/projects/Project-2/rails-api-template-master/db/seeds.rb:11:in `block (3 levels) in <top (required)>'
/Users/jaimegaribaldo/wdi/projects/Project-2/rails-api-template-master/db/seeds.rb:10:in `each'
/Users/jaimegaribaldo/wdi/projects/Project-2/rails-api-template-master/db/seeds.rb:10:in `block (2 levels) in <top (required)>'
/Users/jaimegaribaldo/wdi/projects/Project-2/rails-api-template-master/db/seeds.rb:8:in `block in <top (required)>'
/Users/jaimegaribaldo/wdi/projects/Project-2/rails-api-template-master/db/seeds.rb:7:in `<top (required)>'
/usr/local/var/rbenv/versions/2.3.1/bin/bundle:23:in `load'
/usr/local/var/rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

**Comment by payne-chris-r** [comment]
Can you copy a line from the CSV and your schema code for the pokemons table below? My guess is you're storing pokemon # in the db as integer, but trying to create it as a string or something like that...

**Comment by JaimeGaribaldo7** [comment]
Here's the section for my pokemon table inside the schema file

```
  create_table "pokemons", force: :cascade do |t|
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
    t.integer  "number"
    t.string   "name"
    t.string   "pokemontype"
  end
```

**Comment by JaimeGaribaldo7** [comment]
I should run a migration to change the number datatype into a string?

**Comment by payne-chris-r** [comment]
Can you paste a line from the CSV into this issue so I can see what it looks like?

**Comment by jrhorn424** [comment]
> I should run a migration to change the number datatype into a string?

No.

Everything in your CSV is a string. Can you change this part:

``` rb
Pokemon.create([{ name: hs[:name], number: hs[:number], pokemontype: hs[:pokemontype] }])
```

So that number isn't a string?

**Comment by JaimeGaribaldo7** [comment]
Here's the first line from the CSV file and the data for it

```
id,name,number,pokemontype
1,bulbasaur,1,grass/poison
```

**Comment by jrhorn424** [comment]
What happens if you `puts` each row before you call `Pokemon.create`? Paste the output here.

**Comment by JaimeGaribaldo7** [comment]
This is the result in my rails console when I insert a puts for pokemon

```
   (0.2ms)  BEGIN
{"id"=>"1", "name"=>"bulbasaur", "number"=>"1", "pokemontype"=>"grass/poison"}
   (0.2ms)  ROLLBACK
TypeError: no implicit conversion of Symbol into Integer
from (pry):7:in `[]'
```

**Comment by jrhorn424** [comment]
How do you access a hash with string keys?

**Comment by JaimeGaribaldo7** [comment]
pokemon[0] ?

**Comment by payne-chris-r** [comment]
http://lmgtfy.com/?q=How+do+you+access+a+hash+with+string+keys%3F

**Comment by jrhorn424** [comment]
You're using hashes incorrectly. Please change this line:

``` rb
Pokemon.create([{ name: hs[:name], number: hs[:number], pokemontype: hs[:pokemontype] }])
```

**Comment by jrhorn424** [comment]
Or, you can change this line (there's an optional argument that will help solve the problem for you if you can find it in the docs):

``` rb
CSV.foreach(Rails.root + 'data/pokemon.csv', headers: true) do |row|
```

**Comment by JaimeGaribaldo7** [comment]
This would be found in the ruby docs here http://ruby-doc.org/core-2.3.1/ right?

**Comment by JaimeGaribaldo7** [comment]
I still can't find the problem.
I tried `Pokemon.create(name: hs[:name], number: hs[:number], pokemontype: hs[:pokemontype])` but I'm getting the same result about No implicit conversion of Symbol to integer.
Is this the only way to load in my csv file?

**Comment by payne-chris-r** [comment]
Here's the code from class:

``` ruby
CSV.foreach('data/pets.csv',
                headers: true,
                header_converters: -> (h) { h.downcase.to_sym }) do |pet|
      p pet
      @pets << Pet.new(pet.to_hash)
end
```

and you're doing:

``` ruby
Pokemon.transaction do
      CSV.foreach(Rails.root + 'data/pokemon.csv', headers: true) do |row|
        pokemon = row.to_hash
        pokemon.each do |hs|
          Pokemon.create([{ name: hs[:name], number: hs[:number], pokemontype:
            hs[:pokemontype] }])
      end
   end
end
```

What's the difference?

**Comment by jrhorn424** [comment]
```
[1] (pry) main: 0> string_keys = { 'name': 'Jaime' }
=> {
    :name => "Jaime"
}
[2] (pry) main: 0> puts string_keys
{:name=>"Jaime"}
=> nil
[3] (pry) main: 0> string_keys['name']
=> nil
[4] (pry) main: 0> string_keys[:name]
=> "Jaime"
[5] (pry) main: 0>
[6] (pry) main: 0> symbol_keys = { name: 'Jaime' }
=> {
    :name => "Jaime"
}
[7] (pry) main: 0> puts symbol_keys
{:name=>"Jaime"}
=> nil
[8] (pry) main: 0> symbol_keys[:name]
=> "Jaime"
[9] (pry) main: 0> symbol_keys['name']
=> nil
```

**Comment by JaimeGaribaldo7** [comment]
I modified my db/seeds.rb file to look like this now:

```
require 'CSV'
Pokemon.transaction do
  CSV.foreach('data/pokemon.csv', headers: true, header_converters: -> (h) { h.downcase.to_sym }) do |pokemon|
    p pokemon
    @pokemons << Pokemon.new(pokemon.to_hash)
    Pokemon.create(id: hs[:id], name: hs[:name], number: hs[:number].to_s, pokemontype: hs[:pokemontype])
  end
end
```

I ran the command
`bundle exec rake db:seed`
and i got this output:

```
#<CSV::Row id:"1" name:"bulbasaur" number:"1" pokemontype:"grass/poison">
rake aborted!
NoMethodError: undefined method `<<' for nil:NilClass
/Users/jaimegaribaldo/wdi/projects/Project-2/rails-api-template-master/db/seeds.rb:10:in `block (2 levels) in <top (required)>'
/Users/jaimegaribaldo/wdi/projects/Project-2/rails-api-template-master/db/seeds.rb:8:in `block in <top (required)>'
/Users/jaimegaribaldo/wdi/projects/Project-2/rails-api-template-master/db/seeds.rb:7:in `<top (required)>'
/usr/local/var/rbenv/versions/2.3.1/bin/bundle:23:in `load'
/usr/local/var/rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

**Comment by jrhorn424** [comment]
You're trying to shovel into an array you haven't created.

**Comment by jrhorn424** [comment]
Delete this line: `@pokemons << Pokemon.new(pokemon.to_hash)`.

What are you trying to do? Explain each line of the code to me.

**Comment by JaimeGaribaldo7** [comment]
I DID IT. 

So, as i was preparing myself to explain each line i realized that this:

```
@pokemons << Pokemon.new(pokemon.to_hash)
```

 wasnt necessary.

This is my code right now:

```
require 'CSV'
Pokemon.transaction do
  CSV.foreach('data/pokemon.csv', headers: true, header_converters: -> (h) { h.downcase.to_sym }) do |pokemon|
    p pokemon
    Pokemon.create(id: pokemon[:id], name: pokemon[:name], number: pokemon[:number].to_s, pokemontype: pokemon[:pokemontype])
  end
end
```

```
hs
```

i also changes this ^ HS that i was using before each symbol. I set it to match the "pokemon" i replaced 

 `do |pokemon|` 

up above it in the foreach parameter.

**Comment by jrhorn424** [comment]
AWESOME! Great work, @JaimeGaribaldo7!
