### ISSUE TITLE
AJAX POST request not working.

### ISSUE THREAD

**Issue by knoddin** [ga-wdi-boston/full-stack-project#419]
I have looked at a few other issues regarding AJAX posts and have formatted my data in a similar way in hopes of solving my problem. No luck yet.

I am trying to create a new reservation(join table) from my users and a set list of available weeks(already have IDs associated with them). I am receiving error 422: unprocessable entity when attempting to post a new reservation to my reservations table. 

Here is my js code:

``` js
const onSaveRes = function(week_id){
  let reservation = {
    "reservation": {
      "user_id": app.user.id,
      "week_id": week_id
    }
  };
  return $.ajax({
    url: app.host + '/reservations',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: reservation
  });
    };
```

My events.js code:

``` js
const saveRes = function() {
  event.preventDefault();
  let data = {};
    api.onSaveRes(data)
    .done(ui.saveResSuccess)
    .fail(ui.failure);
};
```

and my ui.js code

``` js
const saveResSuccess = function() {
return week_id;
};
```

When I look into the error, it appears that week is empty, and in my controller I list it as being allowed, so I am assuming that something is wrong with my JS. I just can't seem to see where. Additionally, when making the POST, I am getting the following error in the rails console:

```
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.08ms)
Completed 422 Unprocessable Entity in 5ms (Views: 0.5ms | ActiveRecord: 0.5ms)

```

Here is my Reservation Serializer:

``` rb
class ReservationSerializer < ActiveModel::Serializer
  attributes :id
  has_many :users
  has_many :weeks
end
```

I am unclear on how to proceed - whether it's an issue with my JS, my serializer, both, or neither!

**Comment by payne-chris-r** [comment]
Have you tried a curl request?

Also, fix your formatting ;-)

**Comment by jrhorn424** [comment]
Look at the signature.

> `const onSaveRes = function(week_id){`

What are you passing?

> `let data = {};`
> `api.onSaveRes(data)`

**Comment by jrhorn424** [comment]
Also, after you do your `curl` request, let us know both the command and the output.

**Comment by knoddin** [comment]
The curl request is not working (it did before I started inheriting from the protected controller!). The output appears to be my project in the terminal...and the rails console has the following error, which I am now realizing may be similar to Violeta's issue:

```
[active_model_serializers] Rendered ReservationSerializer with ActiveModelSerializers::Adapter::Json (6.13ms)
Completed 500 Internal Server Error in 68ms (ActiveRecord: 15.8ms)

NoMethodError (undefined method `users' for #<Reservation:0x007ff96ebb31d0>
Did you mean?  user
               user=):
  app/controllers/reservations_controller.rb:24:in `create'

```

I am not sure why it is looking for a users method? Do I need to pass in user_id if the id is automatically going to be the current user? I think I confused myself with table generating. Here's what my Reservation controller looks like:

```
class ReservationsController < ProtectedController
  before_action :set_reservation, only: [:show, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    render json: @reservations
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    render json: @reservation
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = current_user.reservations.build(reservation_params)

    if @reservation.save
      render json: @reservation, status: :created, location: @reservation
    else
      render json: @reservation.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    if @reservation.update(reservation_params)
      head :no_content
    else
      render json: @reservation.errors, status: :unprocessable_entity
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy

    head :no_content
  end

  private

    def set_reservation
      @reservation = current_user.reservations.find(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit(:user_id, :week_id)
    end
end
```

**Comment by jrhorn424** [comment]
The error is saying there's something up with your `ReservationSerializer`. Can you copy that here?

**Comment by jrhorn424** [comment]
Should a reservation `has_many` or `belong_to` `:user`?

If it's a `belongs_to`, then your serializer is doing exactly what you tell it to do (try to find multiple users):

> ``` rb
> class ReservationSerializer < ActiveModel::Serializer
>  attributes :id
>  has_many :users
>  has_many :weeks
> end
> ```

**Comment by knoddin** [comment]
```
class ReservationSerializer < ActiveModel::Serializer
  attributes :id
  has_many :users
  has_many :weeks
end
```

**Comment by knoddin** [comment]
I think I switched that with having multiple users in mind - I will switch back to belongs_to.

**Comment by knoddin** [comment]
Success (with the curl request!). I shouldn't have changed the serializer to has_many for either users or weeks, since each reservation will only have one user and one week.

**Comment by knoddin** [comment]
I am now able to post, however I am having trouble passing the week_id to the api, perhaps because of my separation of concerns. I have a lot going on in my ui.js file, which I don't think is ideal, but I couldn't get the click handler working elsewhere. I want to be able to pass week_id to the API, but it is getting lost between there and ui.js.

ui

``` js
const onListClick = function() {
  week_id = $(this).attr('data-id');
  $('.reservation').text(app.weeks[week_id].start_date + ' to ' + app.weeks[week_id].end_date);
  console.log(week_id);
};
```

events.js

``` js
const saveRes = function() {
  event.preventDefault();
    api.onSaveRes()
    .done(ui.saveResSuccess)
    .fail(ui.failure);
};
```

When the reservation posts (with 201) it says the week object is null.

**Comment by knoddin** [comment]
Here also is my update ajax, which I reformatted to be structured correctly:

``` js
const onSaveRes = function(week_id){
  let reservation = {
    "reservation": {
          "user_id": app.user.id,
          "week_id": week_id
        }
  };
  return $.ajax({
    url: app.host + '/reservations',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data:
    {
      reservation,
  }
});
};
```

**Comment by jrhorn424** [comment]
@knoddin Cool. Let's fix this second issue, and if you run into another one, open a different issue?

This issue is well-done. Thanks. It's making it very easy to help.

> ``` js
>   week_id = $(this).attr('data-id'); // we don't ever use `this` for handlers. we usually use something else...
> ```

Inside `onListClick`, is `console.log(week_id);` logging what you expect it to? What is it logging?

You aren't passing anything to `onSaveRes`, which is why `week_id` is null on the server.

> ``` js
> api.onSaveRes() // this is the call in events.js
> // ...
> const onSaveRes = function(week_id){ // but this is the signature where you've defined it
> ```

**Comment by jrhorn424** [comment]
This is related to my previous comment:

> Look at the signature.
> 
> > ``` js
> > const onSaveRes = function(week_id){
> > ```
> 
> What are you passing?
> 
> > ``` js
> > let data = {};
> > api.onSaveRes(data)
> > ```

In both cases you aren't passing what you expect to the function. Add "check function signature when calling a method" to your list of debugging strategies.

**Comment by knoddin** [comment]
So I know I want to pass in week_id like this 

```
api.onSaveRes(week_id)
```

My problem is passing that value from the ui file to the events file. I have tried redefining it in the events file or requiring it from ui.js but it doesn't seem to work that way. 

Inside onListClick, is console.log(week_id), and that is logging what I want it to.

**Comment by jrhorn424** [comment]
Maybe whatever is firing `onListClick` could also fire `onSaveRes`?

**Comment by jrhorn424** [comment]
``` js
$('.something').on('click' /*or 'submit'*/, fooFunction);
$('.something').on('click' /*or 'submit'*/, barFunction);
```

**Comment by knoddin** [comment]
Thanks for the suggestions with the click handler - I added a new one for saving the reservation, and converted the data id to an integer so that it could be passed to my reservation table. Working code below:

``` events.js
const saveRes = function() {
  event.preventDefault();
  let week_id = ($('.selection').attr('data-id')) * 1;
  console.log(week_id);
    api.onSaveRes(week_id)
    .done(ui.saveResSuccess)
    .fail(ui.failure);
};

const addHandlers = () => {
  $("#sign-in").on('submit', viewWeeks);
  $("#my-res").on('click', viewRes);
  $('#save-res').on('click', saveRes);
  $('#del-res').on('click', deleteRes);
};
```

``` api.js
const onSaveRes = function(week_id){
  return $.ajax({
    url: app.host + '/reservations',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data:
    {
      "reservation": {
        "user_id": app.user.id,
        "week_id": week_id
        },
  }
});
};
```

Thanks, Jeff!

**Comment by jrhorn424** [comment]
Awesome! Glad that helped!
