### ISSUE TITLE
Review of user event logic please (real quick)

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/full-stack-project#42]
I have all of it done, I just need advice on whether to put a "Create Topic" on each honey's profile listing or as a stand alone button.

**Comment by GA-MEB** [comment]
Do you show more than one Honey per page? If not, it shouldn't matter, but if so, you need to figure out how your app will know which Honey the Topic is being attached to.

**Comment by LaurisaNeuwirth** [comment]
Yes I display a list of my honeys on the Home page. Can I show it to you and you can advise me on the smartest way to do it please?

**Comment by GA-MEB** [comment]
Sure. I'm in CR1.

**Comment by LaurisaNeuwirth** [comment]
I will be right there
just saw this, I was looking for an email

**Comment by GA-MEB** [comment]
Closing this issue for now - it's a matter of design choices.
