### ISSUE TITLE
Multi-line strings/template literals in Handlebars not working.

### ISSUE THREAD

**Issue by DanielJRaine** [ga-wdi-boston/full-stack-project#420]
Handlebars does not recognize backtics and cannot use them to create multi-line strings.  As such, I cannot find a way for a multiline string to be used within Handlebars.  When the multiline string gets into my template file, as soon as it hits a line-break, things blow up.  

Help.

**Comment by payne-chris-r** [comment]
Can you post your code?

**Comment by DanielJRaine** [comment]
Solved the issue.  Talked to students from WDI '13, and found out you can't use <script> tags within Handlebars.  So after banging my head against the wall for a couple hours with Handlebars, I decided to say fuck it and switch to templating with Lodash, which actually allows you to use logic within your template.  Now it works.

**Comment by jrhorn424** [comment]
I looked at @DanielJRaine's code. What he was trying to accomplished can be accomplished with a Handlebars custom helper. He went with `lodash` templates instead.
