### ISSUE TITLE
Heroku Install Problem Heroku toolbelt already installed

### ISSUE THREAD

**Issue by JaimeGaribaldo7** [ga-wdi-boston/full-stack-project#421]
This is the command I ran

`brew install heroku`

This were the error messages:

Warning: heroku-toolbelt already installed, it's just not migrated
You can migrate formula with `brew migrate heroku`
Or you can force install it with `brew install heroku --force`

Warning: You are using a pre-release version of Xcode.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

**Comment by payne-chris-r** [comment]
Is this the first time you're deploying? Did you follow the template? This is a computer that may or may not have heroku already installed, correct?

**Comment by JaimeGaribaldo7** [comment]
Hey Chris,

That is the first time I try deploying. I followed the template, but when I
got to the part where i have to install Heroku, It gave me the two errors
about xcode and Heroku. Yes, this is the same computer that has a few
programs already installed into it. It gives me two options for what
commands to run but im not sure which one to use. Also, i dont know what it
means by, "you are using a pre-released version of xcode." So  idk what to
do about that either.

**Comment by payne-chris-r** [comment]
You need to update xcode. 
http://stackoverflow.com/questions/15417619/how-do-you-update-xcode-on-osx-to-the-latest-version

**Comment by JaimeGaribaldo7** [comment]
In the app store it tell me xcode doesn't need to be updated. I ran the command softwareupdate --list in the terminal and it also wont show there either.

**Comment by jrhorn424** [comment]
What happens when you follow the instructions presented in the error?

> `brew migrate heroku`

**Comment by JaimeGaribaldo7** [comment]
This is the output for brew migrate heroku

```
==> Migrating heroku-toolbelt to heroku
==> Unlinking heroku-toolbelt
Moving to: /usr/local/Cellar/heroku
==> Linking heroku
```

**Comment by jrhorn424** [comment]
Cool. In the future, you won't ever have to install heroku toolbelt again if you follow the guide again.

Try following the rest of the guide and let us know what happens.

**Comment by JaimeGaribaldo7** [comment]
Okay, got it.
Now it gave me an error when I ran 

```
git push heroku master
```

this is what i got back:

```
Username for 'https://git.heroku.com': Jaime Hernandez
Password for 'https://Jaime Hernandez@git.heroku.com': 
remote: !   WARNING:
remote: !   Do not authenticate with username and password using git.
remote: !   Run `heroku login` to update your credentials, then retry the git command.
remote: !   See documentation for details: https://devcenter.heroku.com/articles/http-git#authentication
fatal: Authentication failed for 'https://git.heroku.com/dry-mesa-20099.git/' 
```

**Comment by jrhorn424** [comment]
Did you try doing what it said?

**Comment by JaimeGaribaldo7** [comment]
Yes, & I've been following the guide up until where it asks me to use git push heroku master. Now i have the error above. I need a username that i never created?

**Comment by jrhorn424** [comment]
Sorry, to be clear, you did this?

> Run `heroku login`

**Comment by JaimeGaribaldo7** [comment]
Yes, I ran

```
 heroku login
```

then:

```
heroku create
```

Now I'm running

```
git push heroku master
```

**Comment by JaimeGaribaldo7** [comment]
Now I'm running
```
git push heroku master
```

**Comment by jrhorn424** [comment]
When you run `git push heroku master`, it still asks you to login?

**Comment by JaimeGaribaldo7** [comment]
Yes It's still asking me to log in

**Comment by jrhorn424** [comment]
Did you log in using your heroku account information? If this doesn't work, paste the output of `git remote -v` into this issue. Thanks!

**Comment by JaimeGaribaldo7** [comment]
Here's the output for `git remote -v`

```
heroku  https://git.heroku.com/dry-mesa-20099.git (fetch)
heroku  https://git.heroku.com/dry-mesa-20099.git (push)
origin  git@github.com:JaimeGaribaldo7/rails-api-template-2.git (fetch)
origin  git@github.com:JaimeGaribaldo7/rails-api-template-2.git (push)
```

**Comment by JaimeGaribaldo7** [comment]
When I try to input the username and password I have on Heroku, It still tells me this:

```
Username for 'https://git.heroku.com': Jaime Hernandez
Password for 'https://Jaime Hernandez@git.heroku.com': 
remote: !   WARNING:
remote: !   Do not authenticate with username and password using git.
remote: !   Run `heroku login` to update your credentials, then retry the git command.
remote: !   See documentation for details: https://devcenter.heroku.com/articles/http-git#authentication
fatal: Authentication failed for 'https://git.heroku.com/dry-mesa-20099.git/' 
```

**Comment by jrhorn424** [comment]
It's telling you so because you're using the `https` version of heroku. I don't know how that happened. It should be an ssh url. @payne-chris-r will have a solution for you.

**Comment by payne-chris-r** [comment]
Here's the section from the deployment guide. It looks like you have the wrong url type... 
https://github.com/ga-wdi-boston/rails-deployment-heroku-guide

Create a New Heroku App

Go to the root of your repo and run heroku create. This will create an autogenerated name for your app, and add a new remote repository to your repo called heroku. View your remotes by typing git remote -v. You should see something like:

```
    heroku  git@heroku.com:agile-badlands-7658.git (fetch)
    heroku  git@heroku.com:agile-badlands-7658.git (push)
    origin  git@github.com:tdyer/wdi_4_rails_hw_tdd_hacker_news.git (fetch)
    origin  git@github.com:tdyer/wdi_4_rails_hw_tdd_hacker_news.git (push)
```

**Comment by JaimeGaribaldo7** [comment]
It's still giving me the same output, here's what happened when i ran `heroku create`  again

```
~/wdi/projects/Project-2/rails-api-template-master (main)$ heroku create
Creating app... done, ⬢ hidden-mesa-55890
https://hidden-mesa-55890.herokuapp.com/ | https://git.heroku.com/hidden-mesa-55890.git
~/wdi/projects/Project-2/rails-api-template-master (main)$ git remote -v
heroku  https://git.heroku.com/dry-mesa-20099.git (fetch)
heroku  https://git.heroku.com/dry-mesa-20099.git (push)
origin  git@github.com:JaimeGaribaldo7/rails-api-template-2.git (fetch)
origin  git@github.com:JaimeGaribaldo7/rails-api-template-2.git (push)
~/wdi/projects/Project-2/rails-api-template-master (main)$ 
```

**Comment by payne-chris-r** [comment]
Try running this:
`git config --global url.ssh://git@heroku.com/.insteadOf https://git.heroku.com/`

**Comment by JaimeGaribaldo7** [comment]
After running 
I didn't get an output from the terminal then i ran this `git remote -v`
and i got  this result:

```
heroku  ssh://git@heroku.com/dry-mesa-20099.git (fetch)
heroku  ssh://git@heroku.com/dry-mesa-20099.git (push)
origin  git@github.com:JaimeGaribaldo7/rails-api-template-2.git (fetch)
```

**Comment by JaimeGaribaldo7** [comment]
Then I ran `git push heroku master`
and it gave me this output

```
The authenticity of host 'heroku.com (50.19.85.154)' can't be established.
RSA key fingerprint is SHA256:8tF0wX2WquK45aGKs/Bh1dKmBXH08vxUe0VCJJWOA/o.
Are you sure you want to continue connecting (yes/no)?
```

**Comment by payne-chris-r** [comment]
Awesome. Were you able to login with `heroku login`?

**Comment by jrhorn424** [comment]
> Are you sure you want to continue connecting (yes/no)?

Did you try typing 'yes'?

**Comment by JaimeGaribaldo7** [comment]
Yes I was able to log in with `heroku login`

afterwards I tried typing yes into into the result from `git push heroku master` and it gave me this result:

```
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'heroku.com,50.19.85.132' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
~/wdi/projects/Project-2/rails-api-template
```

**Comment by payne-chris-r** [comment]
Yeah, I'm getting the same thing. Hang 10.

**Comment by JaimeGaribaldo7** [comment]
Hanging 10

**Comment by jrhorn424** [comment]
From anywhere in the terminal:

```
cat ~/.ssh/id_rsa.pub | pbcopy
```

Then go to your Heroku account, click Add a New SSH Key, and paste into the box.

**Comment by payne-chris-r** [comment]
You need to put it here on heroku.com:
<img width="554" alt="screen shot 2016-10-04 at 11 55 48 am" src="https://cloud.githubusercontent.com/assets/12667121/19081777/8da6150c-8a29-11e6-9603-5d0240b6130b.png">

**Comment by JaimeGaribaldo7** [comment]
What exactly am i pasting into that section?
when i ran

```
cat ~/.ssh/id_rsa.pub | pbcopy
```

nothing happened

**Comment by payne-chris-r** [comment]
After you run that command you have something in your clipboard. Just go to the section and hit `command + v`. It should paste a string of mess into the field.

**Comment by JaimeGaribaldo7** [comment]
Am I okay to keep the previous Key? Now I have two keys.

**Comment by JaimeGaribaldo7** [comment]
I completed all of the steps and the deployed app looks like i wants new secret keys?

**Comment by payne-chris-r** [comment]
What's the error message?

**Comment by JaimeGaribaldo7** [comment]
In the deployed app it tells me this

Internal Server Error

Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml`
WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26) at dry-mesa-20099.herokuapp.com:443

**Comment by payne-chris-r** [comment]
Have you tried doing what it says?

**Comment by jrhorn424** [comment]
Your original issue was:

> Heroku Install Problem Heroku toolbelt already installed

We've solved that issue, and an additional one of authentication with Heroku. Now we have:

> ```
> Missing secret_token and secret_key_base for 'production' environment, set these values in config/secrets.yml
> WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26) at dry-mesa-20099.herokuapp.com:443
> ```

This is a new issue. Please close and open a new issue @JaimeGaribaldo7.

**Comment by jrhorn424** [comment]
I also suggest looking at closed issues.

**Comment by jrhorn424** [comment]
For example #231 #249 #376

**Comment by JaimeGaribaldo7** [comment]
I already had my secrets and everything done. I'm really confused now. I don't know what is going on.

**Comment by jrhorn424** [comment]
> This is a new issue. Please close and open a new issue @JaimeGaribaldo7.
