### ISSUE TITLE
[JS/Handlebars] Trying to refresh a list after deleting a single item

### ISSUE THREAD

**Issue by styletabtech** [ga-wdi-boston/full-stack-project#423]
**Intro:** I got my delete working to delete a list name from a list of list names (when I get all of my lists). I wasn't sure how to clear the html of the recently deleted list name, so I thought it would be nice to just have the entire list refresh so that the recently deleted list name would disappear. I sort of got the refresh working by calling my getMyLists function inside of .done in my onDeleteList function. 

**Problem:** When I click the 'my lists' button on the front end, I can delete the first list name in the list and the list will refresh properly for 2 times and then it gets stuck (i.e. i hit delete on the next item in the list and it doesn't delete). Additionally, when I click delete on a list name that's at the bottom of the list, it seems to be deleting the list name currently at the top of the list and the refresh also doesn't fire.

I'm unsure if I should first be clearing the html and then calling the getNewList function again? I wasn't able to find any previous issues related to this. I'm stumped. 

**event handlers**

```

const addHandlers = () => {

  // for getting all lists
  $('#my-lists-button').on('click', getMyLists);

  // deleting a list
  $('.content').on('click', onDeleteList);

};
```

**events.js**

```
// for getting all lists

const getMyLists = function () {
  event.preventDefault();
    api.getAllLists()
      .done(ui.myListsSuccess)
      .fail(ui.failure);
};

// for deleting a given list

const onDeleteList = function (event) {
  event.preventDefault();
  let listID = $('.delete-list').attr('id');
  console.log('listID is', listID);
  api.destroyList(listID)
    .done(getMyLists())  <---where I'm trying to refresh
    .fail(ui.failure);
};

```

**api.js**

```
// get all lists

const getAllLists = () => {
  return $.ajax({
    url: app.host + '/lists',
    method: "GET",
    headers: {
      Authorization: 'Token token=' + app.user.token,
  }});
};

// delete a list

const destroyList = (listID) => {
return $.ajax ({
    url: app.host + '/lists/' + listID,
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  });
};

```

**ui.js**

```
// for getting all lists

const myListsSuccess = (data) => {
  console.log('list success data is', data);
  let lists = data;
  // console.log(data);
  $(".content").html(showAllListsTemplate(lists));
};

// for deleting a list (don't currently have this running since I don't call it on .done)

const deleteListSuccess = () => {
  console.log('successful delete');
//  $('.delete-list').html('');
  // app.user.lists[list].id = null;
  //let deletedList = data.list;
//  $('.content').html('');
 };

```

**handlebars**

```
<h1>My Lists:</h1>

{{#each lists}}

<h2> {{title}}
<button id={{id}} class="btn delete-list">DELETE</button> </h2>
<table>
  <thead>
    <th>DATE</th>
    <th>TASK</th>
    <th>PRIORITY</th>
    <th>DUE</th>
  </thead>
  <tbody>
    <tr>
      <td>
        {{this.date}}
      </td>
    <td>
        {{this.task}}
    </td>
    <td>
      {{this.priority}}
    </td>
    <td>
      {{this.due}}
    </td>
  </tr>
  </tbody>
</table>

{{/each}}
```

**Comment by jrhorn424** [comment]
This is a great issue, thanks @styletab.

I think this might have to do with `id`s getting out of sync somewhere. I'll keep digging. But for now...

> I'm unsure if I should first be clearing the html and then calling the getNewList function again?

You've noted a great debugging step. Can you try it and post your updated code? Let me know whether that works or not?

**Comment by jrhorn424** [comment]
Oh! I see.

It's definitely an async issue. It might be something else as well.

``` diff
-    .done(getMyLists())  <---where I'm trying to refresh
+    .done(getMyLists)
```

**Comment by styletabtech** [comment]
Ok here's my updated code for clearing the HTML (also fixed the extra parens you called out). Implementing this seemed to resolve the issue of refresh getting 'stuck' however the top names are still being deleted if I click a name on the bottom of the list. (is that the async issue?)

**events**

```
const onDeleteList = function (event) {
  event.preventDefault();
  let listID = $('.delete-list').attr('id');
  console.log('listID is', listID);
  api.destroyList(listID)
    .done(ui.clearMyLists)
      .done(getMyLists)
      .fail(ui.failure);
};
```

**ui**

```
const clearMyLists = () => {
  console.log('clearMyLists is running');
  $(".content").html("");
};
```

**Comment by styletabtech** [comment]
@abeers helped me figure this out! (shocker) 

**Solution:** In my onDeleteList function my jquery was looking for the class name rather than the target that was being clicked. So when the I clicked delete on any list name (no matter it's location in the list) it was looking for and deleting the first item that had that class.  

**Wrong code:**

```
const onDeleteList = function (event) {
  event.preventDefault();
  let listID = $(delete-list).attr('id'); <---- this is the problem
  console.log('listID is', listID);
  api.destroyList(listID)
    .done(ui.clearMyLists)
      .done(getMyLists)
      .fail(ui.failure);
};
```

**Correct code:** 

```
const onDeleteList = function (event) {
  event.preventDefault();
  let listID = $(event.target).attr('id');
  console.log('listID is', listID);
  api.destroyList(listID)
    .done(ui.clearMyLists)
      .done(getMyLists)
      .fail(ui.failure);
};
```

**Comment by jrhorn424** [comment]
Good job, @abeers. 🦄
