### ISSUE TITLE
[Handlebars / JS] Trying Pass Id through multiple functions

### ISSUE THREAD

**Issue by jenboyd** [ga-wdi-boston/full-stack-project#424]
I am working on trying to add the "edit comment" feature from a list of all comments. Currently, Users can click an "edit" button on a specific comment that is generated by a handlebars template. The event handler for this "click" fires the getSingleComment function. This function replaces the list of all comments with the single comment the user selected. It also shows a form that I have in my HTML (it's display:none on page load). Users should be able to submit the form and make a patch request to that comment. I am having trouble passing the data-id that I have on that comment to the patch request. Is this possible or do I need to rethink the way I am laying out my app?

I am getting the error below :

![screen shot 2016-10-03 at 4 56 02 pm](https://cloud.githubusercontent.com/assets/19177290/19053791/70979070-898a-11e6-97de-bdea43d4284b.png)

Below is my code for the patch request:

HTML

```
          <form id="edit-comment">
            <fieldset>
              <input type="text" class="comment-input" name="comment[comments]" 
                    placeholder="type here">
              <input type="text" class="comment-trip-id" name="comment[trip_id]" 
                    placeholder="Trip ID">
              <input type="submit" class="add-margin" name="submit" value="Submit">
            </fieldset>
          </form>
```

Events

```
 $('#edit-comment').on('submit', onEditComment);


const onEditComment = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  console.log(data);
  api.updateComment(data)
    .done (ui.updateCommentSuccess)
    .fail (ui.failure);
};
```

API

```
const updateComment = function (data) {
  return $.ajax({
      method: 'PATCH',
      url: app.host + '/comments/' + data.id,
      headers: {
      Authorization: 'Token token=' + app.user.token,
      },
      data: data,
    });
  };
```

UI

```
const updateCommentSuccess = (data) => {
  console.log(data);
};
```

**Comment by jrhorn424** [comment]
Probably not a great idea to have to manually input a trip id. You should JavaScript should take care of that in some way.

> ```
>              <input type="text" class="comment-trip-id" name="comment[trip_id]" 
>                    placeholder="Trip ID">
> ```

For the following piece of code:

> ```
> const updateComment = function (data) {
>   return $.ajax({
>      method: 'PATCH',
>      url: app.host + '/comments/' + data.id,
>      headers: {
>      Authorization: 'Token token=' + app.user.token,
>      },
>      data: data,
>    });
>  };
> ```

`id` should be a comment id, correct? Well, data comes from `getFormFields` so if you have an input (probably hidden) with `name='id'` then you could expect `id` to be defined on the object that gets returned from `getFormFields`. I don't see anything like that in your form. You could also store the `id` as a `data-id` on the form element itself (HTML) and use `$('#edit-comment').data('id')` to retrieve it instead of passing it in.

``` diff
- url: app.host + '/comments/' + data.id
+ url: app.host + '/comments/' + $('#edit-comment').data('id')
```

**Comment by jenboyd** [comment]
Thanks @jrhorn424 

I was able to use place a data-id on the comment I click on and call it using :

`url: app.host + '/comments/' + $('.comment-to-edit').data('id'),`

My complete code is below:

Handlebars Template (Loads after getSingleComment function runs)

```
<div class="comment-to-edit" data-id={{comment.id}}>
  <h4>{{comment.trip.name}}</h4>
  <p>"{{comment.comments}}"</p>
</div>
```

HTML (Loads after getSingleComment function runs)

```
       <form id="edit-comment">
            <fieldset>
              <input type="text" class="comment-input" name="comment[comments]" 
                    placeholder="type here">
              <input type="text" class="comment-trip-id" name="comment[trip_id]" 
                    placeholder="Trip ID">
              <input type="submit" class="add-margin" name="submit" value="Submit">
            </fieldset>
          </form>

```

Events 

```
const onEditComment = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.updateComment(data)
    .done (ui.updateCommentSuccess)
    .fail (ui.failure);
};

const addHandlers = () => {
  $('#edit-comment').on('submit', onEditComment);
};
```

API

```
const updateComment = function (data) {
  return $.ajax({
      method: 'PATCH',
      url: app.host + '/comments/' + $('.comment-to-edit').data('id'),
      headers: {
      Authorization: 'Token token=' + app.user.token,
      },
      data: data,
    });
  };
```

**Comment by jrhorn424** [comment]
@jenboyd Glad to hear it.

Mind elaborating on why this works?

> ``` js
>  url: app.host + '/comments/' + $('.comment-to-edit').data('id'),
> ```

IIUC, this works because there's only one comment edit form open at a time?

**Comment by styletabtech** [comment]
I'm running into a similar issue to Jen. I've tried the above steps and discussed it with Jen as well and I haven't been able to find a solution. 

**Problem**: I have a dynamically displayed edit button on a list name. When I click the edit button, I run a function to have a form show. When I click submit on the form it runs the patch request. The functions are running, however I can't retrieve my list object id from the form button that gets clicked on to update a list name. I get the following error that the id is undefined

agenda-api-3000.herokuapp.com/lists/undefined:1 PATCH https://agenda-api-3000.herokuapp.com/lists/undefined 404 (Not Found)

I've tried the following variations with Handlebars and my PATCH ajax request 

HB

```
<h1>My Lists:</h1>

{{#each lists}}

<h2> {{title}}
  <button type="click" class="btn edit-list" data-id={{id}}>EDIT</button>

// other variations
  <button type="click" class="btn edit-list" data-id={{this.id}}>EDIT</button>
  <button id={{this.id}} class="btn edit-list" >EDIT</button>
<button type="click" class="btn edit-list" data-id={{lists.id}}>EDIT</button>

```

API

```
const updateListTitle = (data) => {
  console.log('update ajax data', data);
  return $.ajax({
    method: 'PATCH',
    url: app.host + '/lists/' + $('#update-list-form').data('id'),
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: {
      list: {
        'title': data.list.title
      }
    }
  });
};
// other variations of url:
url: app.host + '/lists/' + data.list.id,
url: app.host + '/lists/' + data,
```

HTML

```
        <form id="update-list-form" class="form-container hide">
          <label>List Title</label>
          <input name="list[title]" type="text">
          <input type="submit" class="btn btn-primary submit" id="update-list-submit" value="UPDATE LIST">
        </form>
```

Events

```
  $('#edit-content').on('click', '.edit-list', getUpdateList); <-- runs function to show the form
 $('#update-list-form').on('submit', onUpdateList);

const getUpdateList = function (event) {
  console.log('getupdatelist is running');
  event.preventDefault();
  ui.proceedToUpdateList(event);
};

const onUpdateList = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  console.log('updateList data', data);
    api.updateListTitle(data)
      .done(ui.updateListSuccess)
      .fail(ui.failure);
};
```

**Comment by styletabtech** [comment]
**Update**: I tried wrapping a div around my handlebars html:

```
<h1>My Lists:</h1>

{{#each lists}}

<div class="list-name-wrapper" data-id={{lists.id}}>
<h2> {{title}}
  <button id={{this.id}} class="btn edit-list">EDIT</button>
<button id={{this.id}} class="btn delete-list">DELETE</button> </h2>
<table>
  <thead>
    <th>DATE</th>
    <th>TASK</th>
    <th>PRIORITY</th>
    <th>DUE</th>
  </thead>
  <tbody>
    <tr>
      <td>
        {{this.date}}
      </td>
    <td>
        {{this.task}}
    </td>
    <td>
      {{this.priority}}
    </td>
    <td>
      {{this.due}}
    </td>
  </tr>
  </tbody>
</table>
</div>
{{/each}}

```

After doing that I'm receiving the following error: 

PATCH http://localhost:3000/lists/ 404 (Not Found)
2016-10-03 21:53:59.944 localhost/:1 XMLHttpRequest cannot load http://localhost:3000/lists/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.
2016-10-03 21:53:59.944 jquery.js:9175 XHR failed loading: PATCH "http://localhost:3000/lists/".send @ jquery.js:9175ajax @ jquery.js:8656updateListTitle @ api.js:40onUpdateList @ events.js:46dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549

My server log says the following: 

```
Started PATCH "/lists/" for ::1 at 2016-10-03 21:53:59 -0400

ActionController::RoutingError (No route matches [PATCH] "/lists"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

```

I'm confused because my curl requests are successful and my list serializer has the id included:

```
class ListSerializer < ActiveModel::Serializer
  attributes :id, :title
  belongs_to :user
  has_many :items
end
```

**Comment by styletabtech** [comment]
Another update! I changed the div to say the following and success!! All set @jenboyd you can close this, thanks for reopening it for me. 

```
<h1>My Lists:</h1>

{{#each lists}}

<div class="list-name-wrapper" data-id={{id}}>
```

**Comment by jrhorn424** [comment]
Great work, devs. Good to see teamwork! :+1: :100:

**Comment by jenboyd** [comment]
@jrhorn424, the code below works for me because there is only one form on my "edit comment view". The view initially does a get request for the comment the user clicked on. It shows the comment the user wants to edit and provides the form to do so. Pulling the id from the result of the get request, '.comment-to-edit', gives me the id to perform the patch request. 

```
url: app.host + '/comments/' + $('.comment-to-edit').data('id')
```
