### ISSUE TITLE
more fun with dynamically created buttons

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#425]
So earlier I was having an issue in which dynamically created buttons weren't firing properly. This was an easy fix, because at the time I just had this button:

``` js
$('.master-list ol').on('submit', 'li', events.onAddToMyToReadList);
```

This was generated dynamically along with the book titles. Now I've added another button (with one more to come) that is a child of that same li, so I need a way to differentiate them. I've tried differentiating them by class name:

``` js
$('.master-list ol').on('submit', 'li.add-to-my-to-read-list-button', events.onAddToMyToReadList);
 $('.master-list ol').on('submit', 'li.read-button', events.onReadReviews);
```

No dice. And what I tried was in my Google results!

**Comment by julie1013** [comment]
Also tried this:

``` js
  $('.master-list ol').on('submit', 'li form.add-to-my-to-read-list-button', events.onAddToMyToReadList);
  $('.master-list ol').on('submit', 'li form.read-button', events.onReadReviews);
```

**Comment by jrhorn424** [comment]
Two questions:
1. Are `li.add-to-my-to-read-list-button` and `li.read-button` forms or submit buttons? If they're submit buttons, you should listen to `click`, not `submit`. If they're forms, you should listen to `submit`. You should wrap each button in a form, change `.read-button` to an id instead of a class, and move it to the form, then listen for submit as you are now. The lesson here is that forms fire submit events, not buttons.
2. Why scope it by `li`? Once these are forms, delegate to `#read` or `#add-to-my-list` instead.

**Comment by julie1013** [comment]
They are submits, sorry. I actually did try this with ID (each element has a class and an ID, the ID being for jQuery purposes). They are dynamically created (one for each element on the master list), so I can't target them directly; I have to target the parent element.

**Comment by jrhorn424** [comment]
I might be confused, or what I said earlier may have been confusing, or not read slowly enough.

In any case, I'm not asking you to target them directly. I'm asking you to target the generated forms with `id`s.

Change so your (generated) HTML looks something like this:

``` html
<form id="read">
  <input type="submit" value="Mark as read">
</form>
```

``` diff
-  $('.master-list ol').on('submit', 'li form.read-button', events.onReadReviews);
+  $('.master-list ol').on('submit', '#read', events.onReadReviews);
// or maybe
+  $('.master-list ol').on('submit', 'li #read', events.onReadReviews);
```

**Comment by julie1013** [comment]
Unfortunately, none of these works. It still isn't firing properly (ie it's not even hitting events.on[insert rest here]

**Comment by julie1013** [comment]
Ah, yes, the second of those suggestions works. Thanks!
