### ISSUE TITLE
Heroku login command not found

### ISSUE THREAD

**Issue by hantungy** [ga-wdi-boston/full-stack-project#426]
So I just installed Heroku on the command line by running `brew install heroku`, but I'm not getting a prompt when I run `heroku login`. It gives me a `heroku:  command not found error`. I tried running `brew install heroku` again and it gives me a `Warning: heroku-3.43.12 already installed`.

**Comment by jrhorn424** [comment]
What else does it say? Post the full output when you run `brew install heroku` again.

Also do a `brew info heroku`. What does it say? Paste the output here as well.

**Comment by hantungy** [comment]
The output is just 

```
Warning: heroku-3.43.12 already installed
```

when I ran `brew install heroku` again. This is what `brew info heroku` output looks like: 

```
heroku: stable 3.43.12, HEAD
Everything you need to get started with Heroku
https://toolbelt.heroku.com/standalone
/home/hantungy/.linuxbrew/Cellar/heroku/3.43.12 (992 files, 6.7M) *
  Built from source on 2016-10-03 at 19:57:09
From: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/heroku.rb
```

**Comment by jrhorn424** [comment]
Please format your response correctly. As noted in Project 1, the three backticks require a new line in order for it to be a fenced code block. I've edited your comment. If you'd like to see how I changed it, you can click the edit button to see what fenced blocks look like. You can also use the preview tab before submitting a comment to see how it will look after submission.

Additionally, inline code snippets only require a single backtick.

**Comment by jrhorn424** [comment]
I can't reproduce. This is what I see:

<img width="650" alt="jeffh__heroku_login" src="https://cloud.githubusercontent.com/assets/388761/19062400/f1cad606-89c7-11e6-8ae0-344c34dfff30.png">

Please try the following:
1. `brew uninstall --force heroku`
2. `brew update`
3. `brew install heroku`
4. `heroku login`

**Comment by jrhorn424** [comment]
If the last step doesn't work, try restarting your terminal. If that doesn't work, one of us will probably need to look at your shell setup `.bashrc` and  `.bash_profile`.

**Comment by hantungy** [comment]
I tried those commands just now and it's still outputting:

`heroku: command not found`

**Comment by berziiii** [comment]
try `sudo <command>` for every command.

So in this case, `sudo heroku login` then `sudo ...` etc.

**Comment by payne-chris-r** [comment]
I think this is resolved now. @hantungy can you close if so?

**Comment by berziiii** [comment]
@hantungy please close with solution. Thank you.

**Comment by jrhorn424** [comment]
Every time you disregard process, we each feel disrespected.

**Comment by hantungy** [comment]
Sorry, I totally forgot. So my problem was that I was installing the mac version of heroku on Linux. The correct command was:

`wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh`

**Comment by jrhorn424** [comment]
Thanks for posting the solution!
