### ISSUE TITLE
When I save a form the page refreshes

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/full-stack-project#429]
I have an add event form. When I hit save the page refreshes. I have event prevent default. There is no request sent to server. 

``` .html
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#add-events-button">Add New Show</button>

    <div class="modal fade" id="add-events-button" tabindex="-1"role="dialog" aria-labelledby="addEventsModalLabel">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <form id="add-event">
           <fieldset>
             <legend>Add Show</legend>
             <input type= "text" name= "band" placeholder="Band Name">
             <input type= "text" name= "venue" placeholder="Venue Name">
             <input type= "date" name= "date" placeholder="Show Date yyyy-mm-dd">
             <input type= "text" name= "setlist" placeholder="Setlist">
             <input type="submit" name="submit" value="Save!">
           </fieldset>
         </form>
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal"
             aria-label="Close"><span aria-hidden="true">&times;</span></button>
         </div>
       </div>
     </div>
   </div>
```

API

``` .js
const addEvents = (data) => {
  return $.ajax({
    url: app.host + '/events/',
    method: 'POST',
    data: data,
  });
};


module.exports = {
  addEvents,
};
```

Events.js

``` .js
const onAddEvents = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.addEvents(data)
    .done(ui.addEventsSuccess)
    .fail(ui.failure);
};

const addHandlers = () => {
$('#add-events').on('submit', onAddEvents);
$('#add-events').on('submit', function(){
    $('#add-events').hide();
  });
};
```

 UI

``` .js
const addEventsSuccess = (data) => {
  app.user = data.user;
};
module.exports = {
  failure,
  success,
  addEventsSuccess,
};
```

**Comment by payne-chris-r** [comment]
Start at the beginning. What should happen when the button is clicked?

**Comment by berziiii** [comment]
Like Chris said, look at what happens when the `form` is submitted and how that matches up with the id on the event handler...

Also, be sure to have your `name="band"` match what your API wants...think of object name with attribute name.

**Comment by rosmith76** [comment]
When the button is pressed the data "band" "venue" "date" "setlist" should be posted to the event table. 
I updated the event handler, but it is still happening

``` .js
const addHandlers = () => {
  $('#add-events-button').on('submit', onAddEvents);
```

**Comment by payne-chris-r** [comment]
That's like 20 steps ahead of where I'm at. Start at the beginning. What should happen when the button is clicked? What's the **very first step**?

**Comment by rosmith76** [comment]
Since there seemed to be no response at all to the js functions I moved them to a my auth files. I am now getting an error massage, and the page is no longer refreshing. This will give me something to work with. 
I looked at the require links in my index.js file, and I don't see where the disconnect was. The files were linked the same way my others were.

**Comment by jrhorn424** [comment]
I wish you had persisted with this instead of moving things around.

The problem is you weren't targeting the right thing. First, let's have a look at your `addHandlers` function:

``` js
const addHandlers = () => {
  $('#add-events-button').on('submit', onAddEvents);
//           ^                 ^ ---------- buttons don't fire submit events, forms do
//           |------------ this is a button
```

Now let's look at your HTML: 

``` html
 <div class="modal fade" id="add-events-button" tabindex="-1"role="dialog" aria-labelledby="addEventsModalLabel">
<!--                                     ^______ this element isn't a button, it's a div                       -->
<!--                                             but it is what your handler above targets (divs don't submit) -->

     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <form id="add-event"><!-- this is what you should be targeting -->
```

To summarize:

```
$('#add-events-button').on('submit', onAddEvents);
<form id="add-event">
```

This is what @payne-chris-r and @berziiii were attempting to get you to see.

**Comment by rosmith76** [comment]
@jrhorn424  that was how I originally had it. I am back to the original code, and the page refreshes when I submit the form.

``` .js
const addHandlers = () => {
$('#add-events').on('submit', onAddEvents);
```

**Comment by jrhorn424** [comment]
Did you make any other changes that you haven't updated here?

**Comment by rosmith76** [comment]
The API is a little different

``` .js
const addEvents = (data) => {
  return $.ajax({
    url: app.host + '/events/' + app.user.id,
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: data,
  });
};
```

**Comment by jrhorn424** [comment]
Ok. I'm a bit confused as to why you'd give the `events` resource a user ID:

> ```
>     url: app.host + '/events/' + app.user.id,
> ```

Let's sit and debug why the page is refreshing.

**Comment by rosmith76** [comment]
I saw that and fixed it earlier

``` .js
url: app.host + '/events/' + app.events.id,
```

**Comment by jrhorn424** [comment]
Ok, cool. Thanks for fixing that.

> Let's sit and debug why the page is refreshing.

**Comment by rosmith76** [comment]
Spelling is hard....
Spelling error was causing the issue.
