### ISSUE TITLE
Question about dynamically displayed buttons

### ISSUE THREAD

**Issue by styletabtech** [ga-wdi-boston/full-stack-project#430]
To preface this, **my buttons are working** how I want them to right now, I just don't quite understand why and feel that I might have them setup incorrectly, so I'd like to get more clarity around best practices for this. I've looked at issue #425 but I'm still not totally following.

**Intro:** I have two buttons, edit and delete, that become displayed when a list name is created. When you click on the edit button (it's an actual button) it shows a form to update the list name. My submit button on that form then fires the edit functions. For my delete button, there is no form and that button itself fires the functions.

Here's how I have my event handlers set up:

```
  // for updating a list title

  $('#edit-content').on('click', '.edit-list', getUpdateList);
 $('#update-list-form').on('submit', onUpdateList);

  // deleting a list
  $('.content').on('click', '.delete-list', onDeleteList);

```

HTML

```
  <div class='content-wrapper'>
          <div id='edit-content' class='content'>
          <div class='edit-content'></div>
          <div class='delete-content'></div>

          </div>
      </div>
```

Handlebars

```
<div class="list-name-wrapper" data-id={{id}}>
  <h2>{{this.title}}
  <button id={{this.id}} class="btn edit-list">EDIT</button>
  <button id={{this.id}} class="btn delete-list">DELETE</button></h2>
```

In an attempt to split up these handlers I tried targeting edit button (to get the form) to the div class `edit-content`, and targeting the delete button to the div class `delete-content`, but that didn't work. I guess I'm just confused as to why I can target two separate events to the same div. Plus I'm hoping to eventually add and "add" button to be displayed alongside these, so I don't feel that this setup will support that.

**Comment by berziiii** [comment]
It may be a naming issue. 

You can also have one button that targets a `class.on('click',...)`  and attaches a handler but then you target the specific event through `this`.

**Comment by jrhorn424** [comment]
I'm going to quote a few things from #425.

> ... If they're submit buttons, you should listen to click, not submit. If they're forms, you should listen to submit. You should wrap each button in a form, change classes to ids, and move it to the form, then listen for submit. The lesson here is that forms fire submit events, not buttons. [paraphrased]
> 
> ``` html
> <form id="myForm" data-id="1">
>   <input type="submit" value="Do the thing">
> </form>
> ```

**Comment by jrhorn424** [comment]
> and attaches a handler but then you target the specific event through this

Please use `event.target` instead of `this`.

**Comment by jrhorn424** [comment]
@styletab Wrapping each button in a form might help alleviate some of the confusion you note here:

>  I guess I'm just confused as to why I can target two separate events to the same div.

After changing to using forms, if you still want to fire two events on the same form, you can use a technique like that mentioned in #416 or #419.

**Comment by styletabtech** [comment]
Thanks @berziiii @jrhorn424. I'm still working through this. I've encountered another issue that is related to this topic so I'm trying to process and test out what you guys elaborated on and will report back soon with an update.

**Comment by jrhorn424** [comment]
@styletab Any updates?

**Comment by styletabtech** [comment]
Hey @jrhorn424 yes apologies for the delay. I thought I had this figured out and now it's broken again. le sigh.

At the moment when I click on my edit button. I can use my form and submit to edit the list title, however it's updating the wrong list title. I can't seem to figure out how to get the id of the list I want to edit to be passed through to my function that fires the patch. My buttons have id's and they match my list titles ids. I think I need to get the button id of the list I click on, but after numerous attempts I haven't had much luck. 

Here's my updated code:

Handlers: 

```
$('#edit-content').on('click', '.edit-list-all-view', function () {
  $('#editTitleModal').modal('show');
});

 $('#update-list-form').on('submit', onUpdateListAllView);

 $('#update-list-form').on('submit', function(){
   $('#editTitleModal').modal('hide');

   });
```

Events

```
const onUpdateListAllView = function (event) {
  event.preventDefault();
  let updateListId = $('.update-button').data('id');
  console.log('targeted list id is', updateListId);
  $("#listIdUpdateTitle").val(updateListId);
  let data = getFormFields(event.target);
  console.log('updateList data', data);
    api.updateListTitle(data)
      .done(ui.clearMyLists)
        .done(getMyLists)
        .fail(ui.failure);
};

// not currently using the below but an example of something I was trying to do to get the button id.
const clickEditOnList = function (event) {
  event.preventDefault();
  let list_id = $(event.target).attr('id');
  console.log('listID is', list_id);
    ui.proceedToUpdateList(list_id);

};
```

API

```
const updateListTitle = (data) => {
console.log('update ajax data', data);
  return $.ajax({
    url: app.host + '/lists/' + data.list.list_id,
    //$('.list-name-wrapper').data('id')
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + app.user.token,
        },
    data: {
      list: {
        'title': data.list.title
      }
    }
  });
  };
```

Handlebars

```
<h1 class="list-title">My Lists</h1>

{{#each lists}}

<div class="list-name-wrapper" data-id={{id}}>
{{> all-lists}}

{{/each}}
</div>

// all-lists
  <h2>
    <button id={{id}} class="btn view-single-list">{{this.title}}</button>
    <!-- <button id={{id}} class="btn add-item-all-view">ADD</button> -->
    <button id={{id}} class="btn edit-list-all-view update-button" data-id={{id}}>EDIT</button>
    <button id={{id}} class="btn delete-list">DELETE</button>
  </h2>

```

**Comment by berziiii** [comment]
When you console log `data` from event.target on get form fields, is the ID of the list item correct there? 

What is `$("#listIdUpdateTitle")`? It's an ID so I'm curious to know if once it's set, it doesn't like you reassigning the value.

Additional thought, It appears you're getting the data-id on the `.update-button` but I don't think the form you're submitting has the ID on it. You also don't appear to be passing the ID of the button you clicked through to the API call. ( different from form being submitted) check to make sure that `data.list.list_id` matches the id of the buttons data-id.

**Comment by jrhorn424** [comment]
@berziiii Good points. I believe some of these were discussed this evening with @abeers.

@styletab Mind updating this when you get a moment? Thanks. An english description of the problem you were trying to solve and your working approach might be enough. If in doubt, feel free to post code. Thanks!

**Comment by payne-chris-r** [comment]
Closing this since there was no response. @styletabtech if you remember, an explanation would still be awesome!
