### ISSUE TITLE
Trying to bring user's books to front-end

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#431]
Now that the Sisyphean ordeal of accessing the user's books on the backend is complete, bringing it to the frontend is the new Sisyphean ordeal!

Because getting it to automatically populate the to-read list upon login is a bit difficult (I think there might be issues of circular dependencies), I want to bring the list forward with a button, at least for now. I know that I need to pass in the user's id to get the books.

On clicking the 'submit' in the form, this fires:

``` js
const onShowMyToReadList = function (event){
    event.preventDefault();
    let data = getFormFields(event.target);
    api.showMyToReadList(data)
    .done(ui.onPopulateMyListSuccess)
    .fail(ui.onError);
  };
```

then this:

``` js
const showMyToReadList = function(data){
  let userID = data.users.id;
  return $.ajax({
    url: app.host + '/users/' + userID + '/books',
  });
};
```

then this:

``` js
const onShowMyToReadListSuccess = function (data){
  let id;
  for(let i = 0; i < data.length; i++){
    id = parseFloat(data[i].id);
    $('#to-read-list').append('<li id=' + id + '>' +
    '<span class=title>' + data[i].title +'</span>' + ' , by ' +
    '<span class=author>' +  data[i].author + '</span>');
  }
};
```

It's clear that it's not snagging the user id. I'm not even sure HOW to do it. Googling for the time being...

**Comment by jrhorn424** [comment]
> I know that I need to pass in the user's id to get the books

You actually don't need to pass the user's ID. If the user ID you want to pass is the same as the currently logged in user, you can just use `current_user` on the backend.

The way this works is by taking the Token with the request and finding the matching user in the database. That user then become `current_user`. So if your `BooksController` inherits from `ProtectedController`, and you pass a Token with your request, you can change the `index` action to only render `current_user.books` as mentioned in #408.

> It's clear that it's not snagging the user id.

How is it clear?

**Comment by julie1013** [comment]
Well it was clear in that data was coming back undefined...

IN any event, doing your suggestion will make life more... interesting... Because that means to get the master list of books I'll now need to authenticate. I have it set so that it grabs them on page load but are then hidden until signin. That means I'll have to call `events.onShowMasterList();` upon successfully signing in... which will result in a circular dependency.

**Comment by jrhorn424** [comment]
> Because that means to get the master list of books I'll now need to authenticate.

That's true. You can usually `skip_before_action :authenticate, only: [:the_thing_to_skip]`, but you've got logic in `index` where one branch needs `current_user` and the other branch doesn't.

> That means I'll have to call events.onShowMasterList(); upon successfully signing in... which will result in a circular dependency.

I'm not certain it will. I'd have to see all the code to be sure. Can you give it a shot?

**Comment by julie1013** [comment]
I'll give the other stuff you told me a shot, but the diagram reveals that calling the event in UI results in circular dependency, as events already depends on ui.

**Comment by julie1013** [comment]
Actually, I'm not clear on the first part of that. What do you mean by branches?

**Comment by jrhorn424** [comment]
``` rb
if condition
  # first branch of code
else
  # second branch of code
end
```

**Comment by julie1013** [comment]
OK... but it sounds to me like you're saying I can't do that because of the conditional statements already present?

**Comment by jrhorn424** [comment]
No, I'm saying you can't do `skip_before_action :authenticate, only: [:the_thing_to_skip]` because of the conditional.

If I'm doing a poor job communicating, please tell me how I might improve.

**Comment by julie1013** [comment]
No, that is what I meant. So I'm not sure how to handle the issue at this point.

**Comment by jrhorn424** [comment]
> > That means I'll have to call events.onShowMasterList(); upon successfully signing in... which will result in a circular dependency.
> 
> I'm not certain it will. I'd have to see all the code to be sure. Can you give it a shot?

**Comment by julie1013** [comment]
Well, for that what I had in mind was calling events.onShowMasterList at onSignInSuccess. That's in ui, upon which events has a dependency. Tried it just now for the hell of it. Said `events.onShowMasterList()` is not a function. Circular dependency.

**Comment by jrhorn424** [comment]
> Tried it just now for the hell of it. Said events.onShowMasterList() is not a function. Circular dependency.

Cool, thanks for trying that.

> Well it was clear in that data was coming back undefined...

What's your AJAX code?

How does that compare to a curl request? Does the curl request work and the AJAX fail?

Have you looked at your server log?

**Comment by julie1013** [comment]
Well, the curl request is this: 
`curl --include --request GET http://localhost:3000/users/1/books`

And that works. But obviously it's different when I want it to pass in the ID of the user who is logged in. As I've said, the issue now is how to reroute the `events.onShowMasterList()` function to avoid a circular dependency, which I'd have to do in order to set it so that books inherits from a protected class.

**Comment by julie1013** [comment]
Used `app.user.id` to access the user ID.
