### ISSUE TITLE
[Rails] Question about validations?

### ISSUE THREAD

**Issue by tuckyeah** [ga-wdi-boston/full-stack-project#432]
So after some super helpful modelling advice from some stranger on StackOverflow, I've refactored my Game model to include a helper function that will populate the 'GameClues' model (which will hold the game's clues, and serve as the interim between the Game and the Clues)

I'm able to successfully populate these GameClues, so that's great, but I'm still not able to make sure that they have the right number of categories/clues. I figure this has something to do with validations, but I'm not sure how.

Based on Mr. StackOverflow's advice, he suggested using some custom validations to make sure that we have the right number of clues per category, as well as each one having a unique value/dollar amount... however, when I try to implement these validations in my game class, it breaks my helper builder function!

```
class Game < ActiveRecord::Base
  has_one :response
  belongs_to :user
  has_many :game_clues

  def self.create_for(user_id)
    user = User.find(user_id)
    # num_cats = num_categories.to_i
    this_game = user.games.new
    [100, 200, 400, 800, 1000].each do |points|
      Category.where(id: Category.pluck(:id).sample(5)).map do |cat|
        if cat.clues.where(value: points).length > 1
          offset_num = cat.clues.where(value: points).length
          clue = cat.clues.where(value: points).offset(rand(offset_num)).first
        else
          clue = cat.clues.where(value: points).first
        end
        this_game.game_clues.create(clue: clue) unless clue.nil?
      end
    end
  end

  validates :game_clues, length: { minimum: 5 }
  validate :must_have_clues_from_5_categories
  validate :must_have_proper_range_of_points

   protected

   def must_have_clues_from_5_categories
     if game_clues.pluck(:category_id).uniq.length < 5
       errors.add(:game_clues, :invalid)
     end
   end

   def must_have_proper_range_of_points
     if game_clues.pluck(:points).uniq.length < 5
       errors.add(:game_clues, :invalid)
     end
   end
end
```

Because of these validations, my new game isn't able to be created and then my builder function can't run because `ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved`

I'm imagining there's a for-loop or a do-while loop involved somewhere in here, but I'm not sure where it would go? Any suggestions?

Thanks!

**Comment by payne-chris-r** [comment]
I think you need to return true/false from validations. I'm not sure if `errors.add` is "truthy" or "falsy" but I think it's trying to validate based on those methods, not seeing something that it considers "true" and saying valdation => false, so don't create the thing. I could be wrong, you're wandering into uncharted territory for me, but I love that you're trying it.

**Comment by jrhorn424** [comment]
@payne-chris-r I believe that lines like this:

``` rb
       errors.add(:game_clues, :invalid)
```

Do what you're expecting. The validations don't have to return `true` or `false`.

When we call `.valid?` on a record, what rails actually does is something like `errors.empty?`. So adding something to the errors is fine.

@tuckyeah I believe there needs to be some sort of validation on the other model as well.

@payne-chris-r Can provide a SO link we were looking at earlier today with a small example in the answer that's trying to do something similar.

**Comment by payne-chris-r** [comment]
http://stackoverflow.com/questions/5577562/maximum-number-of-associated-records

**Comment by payne-chris-r** [comment]
Take a look at this too: http://api.rubyonrails.org/classes/ActiveModel/Validator.html

**Comment by tuckyeah** [comment]
@jrhorn424 can you elaborate a little more on what might need to be in the other model? I'm trying the 'validates_assocation: game' on the GameClues model as we speak, but it doesn't seem to be working. 

I can't populate the game's clues unless the Game instance is saved, and I don't want to save the game until the clues are appropriately populated... hmmmm...

**Comment by jrhorn424** [comment]
@tuckyeah I hate to ask this, but do you mind outsourcing back to StackOverflow? I'm bit pulled in different directions at the moment, and I think I may be the only one that has used custom validators in the past.

If you're really nice, maybe @gaand can help? 😉

**Comment by tuckyeah** [comment]
Not a problem! I'll close this for now - the app works well enough even if it's not perfectly populated :) 

Thanks!!

**Comment by gaand** [comment]
@tuckyeah This message says it all:  `ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved`

Some annotated code from `create_for`:

``` ruby
 # new does not save game
this_game = user.games.new
# tries to create, new then save, a clue
# but the game hasn't been saved
this_game.game_clues.create(clue: clue) unless clue.nil?
```

A game `id` doesn't exist until a new game is saved, so a game clue can't be created with that as the `game_id`.

I believe ActiveRecord handles this correctly if you build the parent and children and then save the parent (see `autosave: true`).

**Comment by jrhorn424** [comment]
Aw. I'm sad. I hope you get to return to this before you present.

Keep in mind, you can be defensive (Google: defensive coding) and write your examples script such that these guarantees are made.

For the scope of this one week iteration, you could make the argument that you really only need validations when accepting user input, like if a user were creating categories and games. Since you're making them both, you can also script up the `game_clues`.

It might be neat to add a column to `games` to see if a User has played it yet. So create a bunch of `Game`, `GameClue`, and `Clue`, have a `played` column on `games`, and show a list when you start your app. When I click a game, I can play that game.

This approach would only work for one, known user right now. That's the downside.

**Comment by tuckyeah** [comment]
Okay I swear I'm moving along but I really want to figure this out and it's driving me nuts because I feel like I'm super close.

Here's what my Game model looks like now - I adjusted the 'create_for' method to only save after we've made a bunch of game_clues, but my problem is that it looks like it's saving no matter what... It'll say that it can save and everything has passed and it's valid while the number of game_clues in the instance is anywhere from 5 - 10....

```
class Game < ActiveRecord::Base
  include ActiveModel::Validations
  after_create :create_response
  has_one :response
  belongs_to :user
  has_many :clues, through: :game_clues
  has_many :game_clues
  accepts_nested_attributes_for :game_clues
  validates :game_clues, length: { is: 5 }, on: :save

  def create_response
    build_response(game_id: id, user_id: user_id)
  end

  def self.create_for(params)
    user = User.find(params[:user_id])
    num_cats = params[:num_categories].to_i
    this_game = user.games.new
    Category.where(id: Category.pluck(:id).sample(num_cats)).map do |cat|
      [100, 200, 400, 800, 1000].each do |points|
        if cat.clues.where(value: points).length > 1
          offset_num = cat.clues.where(value: points).length
          clue = cat.clues.where(value: points).offset(rand(offset_num)).first
        else
          clue = cat.clues.where(value: points).first
        end
        this_game.game_clues.new(clue: clue) unless clue.nil?
      end
    end
    this_game.save if this_game.valid? # i've tried this a hundred ways
                                       # but it keeps returning true no matter what.

#    this_game.update_attributes(num_clues: this_game.game_clues.length)
 #   this_game
  end
end
```

**Comment by payne-chris-r** [comment]
Let's chat about this tomorrow after presentations? I've been doing some research on custom validations, and I might be able to help if we give ourselves some time to talk it out. I'm happy to do a 1-1 sometime in the next week to discuss if you'd rather not do it tomorrow, just let me know!

**Comment by jrhorn424** [comment]
@tuckyeah Out of curiosity have you done anything else with validations? I know you discussed with @payne-chris-r and I changing your modeling approach to accommodate easier validations. If you have any planning collateral (pictures, notes, etc.) would you mind linking them here? We'll keep this issue open for another six weeks or so, and we can revisit this when you like.

**Comment by payne-chris-r** [comment]
I think we covered (at least basically) what a custom validation is, and where it should exist. Not sure if @tuckyeah got it working the way he wanted just yet, but we made a lot of progress.

**Comment by tuckyeah** [comment]
Yes we did a lot of work here, and it was super helpful!

I haven't had a chance to implement or play around with it yet, so I'm not totally confident saying I'm confident on custom validations haha, but let me at least compile my notes and diagrams and link them here ASAP. 

I'll shoot to get that done in the next day or so and then, when I do successfully implement some custom validations, I'll post those solutions here as well.

**Comment by payne-chris-r** [comment]
@tuckyeah did you ever figure this out? I'm closing the issue, but I know we talked about doing this "during week 13." Let me know if you want eyes on it!
