### ISSUE TITLE
Error when deploying front-end / CLIENT_ORIGIN and mixed content error

### ISSUE THREAD

**Issue by viohlet** [ga-wdi-boston/full-stack-project#434]
Hi,

I am getting the following error in the console when I try to log-in or sign-up:

```
vendor.bundle.js:9285 Mixed Content: The page at 'https://viohlet.github.io/project2-client/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:3000/sign-up'. This request has been blocked; the content must be served over HTTPS.
```

I got this after getting a GET issue and solving it by deleting some file on .gitignore as per this solution: https://github.com/ga-wdi-boston/full-stack-project/issues/307 

I added my heroku link in app.js but error is the same.

Thanks for your guidance!

**Comment by berziiii** [comment]
Is your client still pointed to localhost? If so, that won't work. You need the client to be pointing to deployed app.

**Comment by viohlet** [comment]
Hi Brian- Thanks! My api's client_origin is pointing to my github page. Will try to change it to the deployed app.

**Comment by berziiii** [comment]
@viohlet please provide solution to your issue that I helped with. Thanks.

**Comment by viohlet** [comment]
Thank you for helping me, @berziiii !

Solution: 
Go to your Heroku dash and then to settings, and add CLIENT_ORIGIN and <your github pages link> on the site (don't forget to take out the "/" at the end!).

**Comment by DanielJRaine** [comment]
From your Heroku dash, there is actually no direct way to access a settings option.  
You can either click on your user icon and go to Account Settings, or you can click on an app and then click on Settings in the navbar on the top of the page. 
Even then, within your app Settings, there is no place that has "CLIENT_ORIGIN."  You have to add it in one of the blanks in your CONFIG vars.

**Comment by jrhorn424** [comment]
@DanielJRaine 

<img width="1280" alt="boiling-eyrie-35804_ _heroku-git___heroku" src="https://cloud.githubusercontent.com/assets/388761/19091794/063a187e-8a52-11e6-8ab3-47109bebb8a2.png">
<img width="1280" alt="boiling-eyrie-35804_ _settings___heroku" src="https://cloud.githubusercontent.com/assets/388761/19091799/0c0f83d8-8a52-11e6-8fb8-83a62d895b2b.png">
<img width="1280" alt="boiling-eyrie-35804_ _settings___heroku" src="https://cloud.githubusercontent.com/assets/388761/19091807/167eb1e0-8a52-11e6-9b18-d9ae7261500c.png">

**Comment by DanielJRaine** [comment]
After looking at this issue https://github.com/ga-wdi-boston/rails-api-template/issues/20 I tried using CLIENT_URL as a config var instead of CLIENT_ORIGIN and set it to 'https://danieljraine.github.io"

So far it has been working fine, though I'm not sure what the difference is between CLIENT_ORIGIN and CLIENT_URL.

**Comment by jrhorn424** [comment]
I can't be sure right now (I'll have to dig into your code later) but is it possible you have an out-dated version of the rails-template?

**Comment by jrhorn424** [comment]
Current master says it should be `CLIENT_ORIGIN`, and the last change was made August 25th.

See https://github.com/ga-wdi-boston/rails-api-template/blob/master/config/application.rb#L44
