### ISSUE TITLE
Another fun error

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#435]
When I load my page, I get this error:

```
client?cd17:68./spec/example.spec.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/julieesris/WDI_Fall_2016/projects/book-sucks/book-sucks-frontend/spec/example.spec.js'
    at Error (native)
 @ ./spec spec\.js$
```

Not sure what caused it or why it's even looking for this (non-existent) file.

**Comment by jrhorn424** [comment]
Because you deleted `assets/scripts/example.js`. That's fine. Delete the offending file `spec/example.spec.js`. The restart your grunt server, or if you're looking at a deployed client, rebuild and push.

**Comment by julie1013** [comment]
This was just on the local server. And I don't have `spec/example.spec.js` Just `-all.js`

**Comment by julie1013** [comment]
Oh wait, I see what you mean. In any case, running `grunt serve` doesn't change anything. I don't understand why this would suddenly happen now when I deleted example.js days ago.

**Comment by julie1013** [comment]
Now I'm getting this when I try to do `grunt serve`
`Fatal error: listen EADDRINUSE 127.0.0.1:8080`

**Comment by payne-chris-r** [comment]
That's a new issue. Please follow the process for opening issues.

**Comment by julie1013** [comment]
OK, restarting terminal seemed to fix the problem, and now there's another mystery issue. New issue coming...
