### ISSUE TITLE
Deployed api still needs secrets?

### ISSUE THREAD

**Issue by JaimeGaribaldo7** [ga-wdi-boston/full-stack-project#437]
After deploying my api I got this error message:

```
Internal Server Error

Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml`
WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26) at dry-mesa-20099.herokuapp.com:443
```

I already had that done for the development and test secrets. Do i need to make another secret for production?

**Comment by jrhorn424** [comment]
Yes. See #434 and various other issues I mentioned before.

**Comment by payne-chris-r** [comment]
Is this resolved @JaimeGaribaldo7 ?

**Comment by JaimeGaribaldo7** [comment]
I'm having a different issue
