### ISSUE TITLE
Regarding params and .require on a Create Method

### ISSUE THREAD

**Issue by bullhead242** [ga-wdi-boston/full-stack-project#438]
Hi! I'm having difficulty creating a new instance of the class Visit, which is, effecitvely the join between my "users" and "shops." A user has many visits, each visit belongs to a user and has one shop.  I am able to create a new visit using a curl request

```
  curl --include --request POST http://localhost:3000/visits \
    --header "Content-Type: application/json" \
    --data '{
      "visit": {
        "user_id": "1",
        "shop_id": "1"
      }
    }'
```

While this is successful, running a function clicked by a button, which is designed to create a visit with the `user_id` and `shop_id` defined by the click data and the value of the boolean `like` to `true` returns the following:

```
ActionController::ParameterMissing (param is missing or the value is empty: visit):
  app/controllers/visits_controller.rb:57:in `visit_params'
  app/controllers/visits_controller.rb:21:in `create'
```

The function which sends the POST is as follows, and returns the expected values for the named variables: 

```
function addEventHandlersToLikeButtons(event) {
  $('.like-button').click(function(event){
    const selectedShopId = event.target.parentElement.dataset.shop;
    const theyLikedIt = true;
    api.createVisit({user_id: app.user.id, shop_id: selectedShopId, like: theyLikedIt})
      .done(function(data) {
        console.log(data);
      })
      .fail();
  });
}
```

What I'm gathering is that the server is not receiving a value for `:visit` which was expected to create a new instance. Mostly, I'm confused as to why the curl request can succeed

**Comment by jrhorn424** [comment]
Can you look at `app/controllers/visits_controller.rb:57:in 'visit_params'` and paste what that method definition here? Thanks.

**Comment by jrhorn424** [comment]
> Mostly, I'm confused as to why the curl request can succeed

Are you sure it is succeeding? Please paste the curl command that is succeeding.

**Comment by bullhead242** [comment]
From `app/controllers/visits_controller.rb:57` :

```
  def visit_params
      params.require(:visit).permit(:user_id, :shop_id, :like)
    end
```

I've updated the original issue with the curl which returns a `201 Created`, i had originally posted the function twice by accident.

**Comment by payne-chris-r** [comment]
Thank you. The error message is telling you everything you need to know: 
`ParameterMissing (param is missing or the value is empty: visit):`
Try logging the `data` before the request gets sent and take a look at what it looks like.

**Comment by payne-chris-r** [comment]
@bullhead242 did you figure this out?

**Comment by bullhead242** [comment]
@payne-chris-r 

nope. 

right now, `app.user.id` is returning the object of everything after the comma inside that function. trying to figure out how to remove the values from being nested inside that object.

**Comment by payne-chris-r** [comment]
Ok. Please pull data into its own object before you send it:

``` js
let data = {user_id: app.user.id, shop_id: selectedShopId, like: theyLikedIt}
api.someFunction(data)
```

instead of 

``` js
api.someFunction({user_id: app.user.id, shop_id: selectedShopId, like: theyLikedIt})
```

**Comment by bullhead242** [comment]
i'm working on separating the individual definitions within that far-too-complicated portion of the function into a few variables and passing them to the AJAX call separately right now. If i run into anything else, I'll post here.

**Comment by payne-chris-r** [comment]
Cool. Thanks.

**Comment by jrhorn424** [comment]
@bullhead242 The error is still here:

```
let data = {user_id: app.user.id, shop_id: selectedShopId, like: theyLikedIt}
```

You'll need to adjust that data object to in the right format. Compare to the data you sent in your `curl` request to see what you need to do.

**Comment by bullhead242** [comment]
Got it. Took at lot of messing with the syntax to properly format the JSON to be read by the controller on the back end. Working code for the main function is:

```
const createVisit = (userId, selectedShopId, theyLikedIt) => {
  debugger;
  return $.ajax({
    url: app.host + '/visits',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + app.user.token,
              },
    data: { visit: {"user_id": userId, "shop_id": selectedShopId, "like": theyLikedIt}
            }
  });
};
```

Thanks @payne-chris-r and @jrhorn424 for your help
