### ISSUE TITLE
Margins are different when deployed

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#439]
Margins are different on one of my elements when deployed vs. when it's on the local server. Is this normal?

**Comment by berziiii** [comment]
I don't know. Not enough here.

**Comment by julie1013** [comment]
On local server the top margin of an element were -1088. Deployed they are -577 to be in the same place.

**Comment by jrhorn424** [comment]
What have you tried to debug?

**Comment by julie1013** [comment]
Not sure how I would debug-- it's not dynamically added and it's just HTML.

**Comment by berziiii** [comment]
https://developers.google.com/web/tools/chrome-devtools/. You can start there for debugging margin issues from local to deployed and cross reference the differences.
