### ISSUE TITLE
Trying to run index controller method tied to user_id

### ISSUE THREAD

**Issue by kelvinma** [ga-wdi-boston/full-stack-project#44]
This is the code in my WeeklyMenusController < OpenReadController:

```
  def index
    @weeklymenus = WeeklyMenu.where(user_id: current_user)

    render json: @weeklymenus
  end
```

My current_user has an ID of 5, and I'm trying to get my GET request to return all WeeklyMenus associated with User_ID 5.

Query does not return any ActiveRecord objects with user_id: 5.

**Comment by GA-MEB** [comment]
Rhetorical question : What type of data is `current_user`?

**Comment by kelvinma** [comment]
Ah, thanks. It's an activerecord object. Plugging in current_user.id to get me the user_id integer is throwing me internal server errors (500) now.

I think I can figure it out from here... (maybe?)

**Comment by GA-MEB** [comment]
What's the terminal output from the Rails server?

**Comment by kelvinma** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

It's referencing this part of my code:

```
  var indexMenus = function(error, data) {
    if (error) {
      console.error(error);
      return;
    }
      var menuHTML = menuTemplate({weekly_menus: data.weekly_menus});
      $('#allMenus').html(menuHTML);
  };
```

**Comment by GA-MEB** [comment]
Actually, I mean the terminal window that's running the Rails server. Can you paste that output here?

**Comment by kelvinma** [comment]
```
NoMethodError (undefined method `id' for nil:NilClass):
  app/controllers/weekly_menus_controller.rb:5:in `index'
```

Referencing this code in my Controller:

```
  def index
# THIS LINE    @weeklymenus = WeeklyMenu.where(user_id: current_user.id) 

    render json: @weeklymenus
  end
```

**Comment by gaand** [comment]
What does WeeklyMenuController inherit from?

**Comment by kelvinma** [comment]
OpenReadController

**Comment by gaand** [comment]
Okay.  Then the index action doesn't require authentication.  But that means `current_user` may not be set.  It will be set if you send a valid token in the headers.

**Comment by kelvinma** [comment]
I thought I was doing with my API call via the client side. Is this a line I need to add in my controller?

**Comment by kelvinma** [comment]
Figured it out. It was an issue with where I was storing my token on the front end.
