### ISSUE TITLE
Submitting review

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#440]
Trying something simple with letting someone submit a review.

I have this:

``` js
$('.master-list ol').on('click', 'li #write', function(event){
    event.preventDefault();
    $('#review-form').show();
    $('#write-review-here').on('submit', events.onSubmitReview);
  });
```

which calls this:

``` js
const onSubmitReview = function (event){
    event.preventDefault();
    let data = getFormFields(event.target);
    api.submitReview(data)
      .done(ui.onSubmitReviewSuccess)
      .fail(ui.onError);
  };
```

which calls this:

``` js
const submitReview = function(data){
  return  $.ajax({
    url: app.host + '/reviews',
    method: "POST",
    data: data,
  });
};
```

And then this:

``` js
const onSubmitReviewSuccess = function(data){
  console.log(data);
};
```

I have these errors:

```
http://localhost:3000/reviews Failed to load resource: the server responded with a status of 400 (Bad Request)
```

```
2016-10-04 15:20:03.677 (index):1 XMLHttpRequest cannot load http://localhost:3000/reviews. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
```

It hangs up at the ajax call.

**Comment by payne-chris-r** [comment]
Are you making this request from your deployed front end?

**Comment by julie1013** [comment]
No, this is on the local server.

**Comment by jrhorn424** [comment]
Then you have to look at your rails server logs. What does it say? (Just the most recent failing request is fine, the log usually separates them by a newline or two).

**Comment by julie1013** [comment]
OK, it looks like it's missing a parameter and won't fire unless all of them are there. So it needs the USER ID (which would mean reviews inherits from protected class), the book ID (which I'll have to pass in), and it needs a review title. I guess at this point my question is how to do that. I guess I'll have to find/make a field form that takes more than one text area and letting the backend know where the different text areas match up.. whoo boy.

**Comment by jrhorn424** [comment]
> USER ID (which would mean reviews inherits from protected class)

No, needing user id means it needs to be provided in the JSON you send with the object. If you inherit from `ProtectedController` and do `current_user.something.build(...)`, then `current_user` would be providing it for you. Since you're not inheriting from `ProtectedController`, try getting it to work by send the user id.

Go ahead and make that change (send user id). Before I can continue debugging, I need you to paste your error log so I can see what's up.

**Comment by julie1013** [comment]
Done. Error:

``````
:3000/users/1/reviews/review-form:1 POST http://localhost:3000/users/1/reviews/review-form 
2016-10-04 17:30:07.429 ?Title=&body=sadfsfsa:1 XMLHttpRequest cannot load http://localhost:3000/users/1/reviews/review-form. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.```
``````

**Comment by payne-chris-r** [comment]
What is this ? `http://localhost:3000/users/1/reviews/review-form`

**Comment by julie1013** [comment]
I was wondering about that myself. I don't know how it got there. Since that was an ID was it interpreting that as part of the data it was passing?

**Comment by payne-chris-r** [comment]
I'm confused. Is that the URL you were trying to hit?

**Comment by julie1013** [comment]
I wanted the endpoint to be reviews. So it can add to reviews.

**Comment by payne-chris-r** [comment]
That's what I thought. Please fix and report back

**Comment by julie1013** [comment]
I'm not even sure HOW that's happening. Here's the code I have

``` js
  const onSubmitReview = function (event){
    let bookID = $(this).parent().attr('id');
    event.preventDefault();
    let data = getFormFields(event.target);
    api.submitReview(data, bookID)
      .done(ui.onSubmitReviewSuccess)
      .fail(ui.onError);
  };
```

``` js
const submitReview = function(data, bookID){
  let id = app.user.id;
  return  $.ajax({
    url: app.host + '/users/' + id + '/reviews/' + bookID,
    method: "POST",
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: data,
  });
};
```

**Comment by payne-chris-r** [comment]
``` js
console.log("BookID is ", bookID);
```

**Comment by julie1013** [comment]
Hmm this is going to make life interesting. I have it set so that you press a button from within the list item (which has an ID assigned to the book) to generate the form. Give me a few minutes to think about how to get that.

**Comment by julie1013** [comment]
More than a few minutes... Was working on something else.

**Comment by julie1013** [comment]
OK, it seems that I have to somehow target the `li`. However, `li` isn't an ancestor or descendent. `.find()` and `.closest()` seem to only target those things. I guess I'll have to capture the ID when someone clicks the button in the `li` that opens the form field?

**Comment by julie1013** [comment]
`let bookID = $(this).closest('li').attr('id');`

This snags book ID from original click that reveals the form. Now I need to pass it into the submission form.

**Comment by julie1013** [comment]
Obviously I need to capture the data in the form fields (`title`, `body`), but I also need to figure out a way to submit the captured `bookID` as an argument when making my ajax call to the backend.

**Comment by payne-chris-r** [comment]
`console.log("data is ", data)` before the ajax call gets sent. What type of 'thing' is it? How would you add something to it?

**Comment by julie1013** [comment]
![screen shot 2016-10-06 at 10 22 29 am](https://cloud.githubusercontent.com/assets/14143334/19156156/f12bdaf4-8bae-11e6-8145-1b044737f885.png)

**Comment by julie1013** [comment]
OK, so it's an object, and it looks like by virtue of the type of form field it is, it captures `title` and `body` as I want it to. Obviously, there's still the matter of setting the bookID. I can capture it like this, and I'm trying to pass it this way:

``` js
$('.master-list ol').on('click', 'li #write', function(event){
    event.preventDefault();
    let bookID = $(this).closest('li').attr('id');
    $('#review-form').show();
    $('#review-form').on('submit', bookID, events.onSubmitReview);
  });
```

But I am not sure how to pass `bookID` into `events.onSubmitReview`. 
I don't think the way I did it above works.

**Comment by julie1013** [comment]
Closing the issue for now, as instructors have deemed it beyond the scope of this project in order to meet requirements.
