### ISSUE TITLE
Disappearing to-read list

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#444]
``` js
  const onShowMyToReadList = function (event){
    event.preventDefault();
    api.showMyToReadList()
    .done(ui.onShowMyToReadListSuccess)
    .fail(ui.onError);
  };
```

fires this:

``` js
const showMyToReadList = function(){
  let id = app.user.id;
  return $.ajax({
    url: app.host + '/users/' + id + '/books',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  });
};
```

and this:

``` js
const onShowMyToReadListSuccess = function (data){
  let bookID;
  for(let i = 0; i < data.length; i++){
    bookID = parseFloat(data[i].id);
    $('#to-read-list').append('<li id=' + bookID + '>' +
    '<span class=title>' + data[i].title +'</span>' + ' , by ' +
    '<span class=author>' +  data[i].author + '</span>');
  }
};
```

Debugging indicates that the to-read-list, on the page at the time that the event fires, disappears after the ajax request is fired. Why, I'm not sure. Still searching...

**Comment by julie1013** [comment]
Debugger stops here:
`let id = app.user.id;`
It says `bundle.js:272 Uncaught TypeError: Cannot read property 'id' of undefined`

The bundle turned the code around so that it says `app.users.id`, yes, with the extra "s"! Why? Damned if I know. The bigger mystery is why it even tried running the success function after that!

**Comment by jrhorn424** [comment]
Search your entire project for `app.users.id`. I suspect there's a line somewhere that says `app.users.id =` instead of `app.user.id =`.

The bundler will not add an extra `s`. If it does, and we can prove it, I'll be really surprised.

**Comment by julie1013** [comment]
Just searched for it using the search function for the full project. Nothing found!

**Comment by jrhorn424** [comment]
Show me what the bundle did, and show me the source code.

**Comment by julie1013** [comment]
Strangely enough, it's NOT doing that anymore and it's not throwing me that error. But the to-read list is still disappearing after the ajax call! I can't imagine what's causing this; code is still the same as what I posted above.

**Comment by jrhorn424** [comment]
> Debugging indicates that the to-read-list, on the page at the time that the event fires, disappears after the ajax request is fired.

Please confirm whether or not the browser is refreshing.

**Comment by julie1013** [comment]
It's not. Everything else that only shows during the logged in state is still there.

**Comment by payne-chris-r** [comment]
Where does `onShowMyToReadListSuccess` run? Is there anything around it that would remove that div/html element from the page? What are all the functions that run in between the event handler and your element(s) disappearing? I'd look there.

**Comment by payne-chris-r** [comment]
Also doing a search through the entire project for the `class` or `id` that the disappearing HTML element has might lead you to where you want.

**Comment by julie1013** [comment]
I've posted all the functions associated with this event. 
I finally realized that I probably need to put `ol` in so it says  `$('#to-read-list ol')` . But the result is still the same.

**Comment by payne-chris-r** [comment]
Try appending something to a different div. See if the div in question still disappears.

``` js
$('#some-other-div').append('<li id=' + bookID + '>' +
    '<span class=title>' + data[i].title +'</span>' + ' , by ' +
    '<span class=author>' +  data[i].author + '</span>');
```

**Comment by julie1013** [comment]
It still disappears even when I try that. :(

**Comment by julie1013** [comment]
Targeted the ol (which I gave an ID) directly. It worked.
