### ISSUE TITLE
Don't understand the routes needed when deploying / Summary of client-api combinations and notes on configuration

### ISSUE THREAD

**Issue by JaimeGaribaldo7** [ga-wdi-boston/full-stack-project#445]
Requesting a 1 on 1 for help with when to use local host 8080,  3000, or my rails deployed app, or client deployed app.

**Comment by jrhorn424** [comment]
Shouldn't need 8080 or 3000 when deployed.

**Comment by jrhorn424** [comment]
From @payne-chris-r 
1. Requests from localhost:8080 to Heroku should work fine while you're testing your API deployment.
2. Requests from localhost:8080 to localhost:3000 should work fine while you're developing.
3. Requests from GitHub to Heroku should work fine as long as you've set your Heroku client config variable to point to your GitHub domain.
4. Requests from GitHub to localhost:3000 **will never** work.
5. When GitHub makes request to your API, the client app host property must begin with `https` not `http`. When Heroku responds, the client config variable should also begin with `https` and not include a trailing slash.

**Comment by jrhorn424** [comment]
![slack for ios upload-11](https://cloud.githubusercontent.com/assets/388761/19094946/11ae7df8-8a61-11e6-960f-dbfada4ff2fd.jpg)

**Comment by jrhorn424** [comment]
![slack for ios upload-12](https://cloud.githubusercontent.com/assets/388761/19094955/1b86ede2-8a61-11e6-984c-61dcb59c8e16.jpg)

**Comment by payne-chris-r** [comment]
@JaimeGaribaldo7 did you figure it out?

**Comment by JaimeGaribaldo7** [comment]
This helped a lot yes!
