### ISSUE TITLE
Returning reviews

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#446]
Similar to what the instructors helped me with this morning in getting all of the reader's books, I wanted to get all the reader's reviews. However, `http://localhost:3000/users/1/reviews/`
just shows me 1, 2, and 3. I have to do `http://localhost:3000/users/1/reviews/1` , for example, if I want to see any content. Is this to be expected since reviews are longer than just a few lines?

Relevant code:

In reviewers controller:

``` ruby
def index
    user = params[:user_id]
    @reviews = if user
                 Review.where(user: user).pluck(:id)
               else
                 Review.all
               end
    render json: @reviews
  end
```

In routes:

``` ruby
  resources :users, only: [:index, :show, :signup, :signout, :changepw] do
    resources :books, :reviews
  end
```

**Comment by payne-chris-r** [comment]
Why is your `resources :books, :reviews` in a do/end inside `:users`?

**Comment by julie1013** [comment]
My brother told me that this is a way to specify resources as being under users

**Comment by jrhorn424** [comment]
> Why is your resources :books, :reviews in a do/end inside :users?

That was @payne-chris-r's way of suggesting that maybe it's not the right choice.

> ```
> Review.where(user: user).pluck(:id)
> ```

This only returns ids, not a review object. You probably meant `Review.where(user: user)`. But you shouldn't do that either.

If you're trying to read the `current_user`'s reviews, you can do that with flat routes (unnest them), and then use `current_user.reviews` in your controller instead of the above line. In order for that to work, you'll need to inherit from `ProtectedController`.

Please get `current_user` to work where it makes sense. The proper response to circular dependencies on the front-end is to fix the dependencies, not to change your API.

**Comment by julie1013** [comment]
I figured that's what he was saying, but I also wanted to provide an explanation. I guess I give my brother too much credit? Should I not have it?

Why shouldn't I do this? `Review.where(user: user)` It gives me what I ask for in the browser.

**Comment by jrhorn424** [comment]
> I guess I give my brother too much credit? Should I not have it?

Nah, it isn't that. He just doesn't know our auth since we've hand-rolled it for WDI.

> Why shouldn't I do this? Review.where(user: user) It gives me what I ask for in the browser.

Then is the issue closed?

**Comment by julie1013** [comment]
I mean, I don't know. I meant when I type `http://localhost:3000/users/1/reviews/` in the browser it gives me what I'm looking for. I thought maybe you were anticipating something I wouldn't necessarily be aware of.

**Comment by jrhorn424** [comment]
> Why shouldn't I do this? Review.where(user: user) It gives me what I ask for in the browser.

You don't necessarily have to change this, but if you aren't using `current_user` anywhere, I'm not sure users are owning data. For example, can a different user delete a review than the one who posted it?

If the destroy action in the `ReviewsController` looks like `@review.destroy`, then you aren't protecting user data. Please note, if you are not protecting user data, that would be a separate issue. Let's focus on your original issue, which I'm unsure is resolved or not:

> Returning reviews

**Comment by jrhorn424** [comment]
I can't know @julie1013 whether this issue is closed. If the thing that originally prompted you to open this issue is no longer happening, the issue is done.

**Comment by julie1013** [comment]
Well, yeah, this particular issue is closed. Let's see what happens.
