### ISSUE TITLE
Can pass specific ID when trying to delete an event

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/full-stack-project#447]
Curl request works.

console log error

``` .html
jquery.js:9175 OPTIONS http://localhost:3000/events/[object%20Object] send @ jquery.js:9175ajax @ jquery.js:8656deleteEvent @ api.js:44onDeleteEvent @ events.js:45dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
2016-10-04 19:35:17.220 localhost/:1 XMLHttpRequest cannot load http://localhost:3000/events/[object%20Object]. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
2016-10-04 19:35:17.220 jquery.js:9175 XHR failed loading: DELETE "http://localhost:3000/events/[object%20Object]".send @ jquery.js:9175ajax @ jquery.js:8656deleteEvent @ api.js:44onDeleteEvent @ events.js:45dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
2016-10-04 19:35:17.221 ui.js:13 Object {readyState: 0, status: 0, statusText: "error"}
```

I know this link "http://localhost:3000/events/". needs an ID to work. I can't figure that part out. 

HTML

``` .html
   <div class="modal fade" id="delete-events-button" tabindex="-1"role="dialog" aria-labelledby="deleteEventsModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form id="delete-event">
          <fieldset>
            <legend>Delete Show</legend>
            <input type= "text" name= "event_id" placeholder="Event ID#">
            <input type="submit" name="submit" value="Delete">
          </fieldset>
        </form>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"
            aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
      </div>
    </div>
  </div>
```

UI

``` .js
const deleteEventSuccess = (data) => {
  console.log (data);
};
```

API

``` .js
const deleteEvent = (data) => {
  return $.ajax({
    url: app.host + '/events/' + data,
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  });
};
```

events

``` .js
const onDeleteEvent =(data) => {
  event.preventDefault();
  api.deleteEvent(data)
    .done(ui.deleteEventSuccess)
    .fail(ui.failure);
};
```

**Comment by berziiii** [comment]
What is `data` being passed to the events function? Are you sure it's what you think it is?

**Comment by rosmith76** [comment]
i thought that it would be the ID. I can see that I was wrong. I also tried event.target with no success either

**Comment by payne-chris-r** [comment]
Javascript is interpretting this line: `url: app.host + '/events/' + data,`
as this: `http://localhost:3000/events/[object%20Object]`
Do me a favor, open `node` in your terminal and run this line: `'string' + {}`

**Comment by rosmith76** [comment]
String + object in node produces 'string[object Object]'
If I change the code to use data as an object i get this string as part of the error.
"http://localhost:3000/events/[object%20Object]"
I am still not sure how to pass the data from the form into that object.

**Comment by jrhorn424** [comment]
Choose a property instead of the whole object.

**Comment by rosmith76** [comment]
I think I am on the right track with this, but it still doesn't work

``` .js
const getID =  function (event){
  event.preventDefault();
  let id = $(event.target).attr("event-id");
  $(".delete-event").attr("event-id", id);
};

const onDeleteEvent =(event) => {
  event.preventDefault();
  let id =$(event.target).attr("event-id");
  api.deleteEvent(id)
    .done(ui.deleteEventSuccess)
    .fail(ui.failure);
};
```

**Comment by payne-chris-r** [comment]
Is this strictly a `getID`???

```
const getID =  function (event){
  event.preventDefault();
  let id = $(event.target).attr("event-id");
  $(".delete-event").attr("event-id", id);
};
```

You need to separate your concerns better.

**Comment by payne-chris-r** [comment]
Also, can you try logging `data` like I've shown below? This is the single greatest technique I know of for debugging api/ajax calls and making sure the data you're sending is what you expect.

``` js
const deleteEvent = (data) => {
  console.log("data is ", data);
  return $.ajax({
    url: app.host + '/events/' + data,
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  });
};
```

**Comment by rosmith76** [comment]
@jrhorn424  I made some edits based on the conversation we had. I changed the event code to this

``` .js
const onDeleteEvent =(event) => {
  event.preventDefault();
  let data = getFormFields(event.target);
  let id =$(data.data-id).event('data-id');
  api.deleteEvent(id)
    .done(ui.deleteEventSuccess)
    .fail(ui.failure);
};
```

I am now getting an error that "event" isn't a function. I tried data and attr in place of events, and I get this again "http://localhost:3000/events/[object%20Object]"

**Comment by payne-chris-r** [comment]
On what line? Which line do you think it's blowing up?

**Comment by rosmith76** [comment]
here or maybe the (event) on line 1. I have also tried data there

``` .js
  let id =$(data.data-id).event('data-id');
```

**Comment by gaand** [comment]
This line:

```
  let id =$(data.data-id).event('data-id');
```

is parsed as: get the value of the key `data` from the object stored in the variable `data` and subtract the value in the variable `id`.  because of JavaScript parsing rules, this throws a `ReferenceError` and at that point the parsing stops.

I think you probably want to retrieve a data attribute from a DOM element in `event.target`.  

Is that a form?  What does it look like in html?

**Comment by rosmith76** [comment]
I do want to retrieve the data in the DOM element. It's the ID of the item I am trying to delete. 
The HTML is still the same as it was posted above. Here it is again. 

``` .html
   <div class="modal fade" id="delete-events-button" tabindex="-1"role="dialog" aria-labelledby="deleteEventsModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form id="delete-event">
          <fieldset>
            <legend>Delete Show</legend>
            <input type= "text" name= "[event]id" placeholder="Event ID#">
            <input type="submit" name="submit" value="Delete">
          </fieldset>
        </form>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"
            aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
      </div>
    </div>
  </div>
```

**Comment by rosmith76** [comment]
here is the HTML button

``` .html
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#delete-events-button">Remove Show</button>
```

**Comment by gaand** [comment]
First, compare the following two lines:

``` html
<input type= "text" name= "[event]id" placeholder="Event ID#">
<input type="text" name="credentials[email]" value="">
```

Do you see the problem?

The  POJO (Plan Old JavaScript Object) that getFormFields returns for a form containing the second line above allows me to find out what the user typed in as an e-mail address using:

``` js
let data = getFormFields(event.target);
let email = data.credentials.email;
```

You might want to add a `console.log(data);` to make sure you're actually getting the data you want.  That would also help you see how to extract that data from the object `getFormFields` returns.

**Comment by rosmith76** [comment]
@gaand Thanks Antony! I changed the code to 

``` .html
<input type= "text" name= "[event]id" placeholder="Event ID#" value="">
```

When I console log data I am getting the object I am looking for. What I don't get is that I didn't use value="" on any other authentication functions, and they all work the way they should??
Either way I am now getting the results I am looking for. Now I just need to figure out my next error stating that this isn't a function

``` .js
  let id =$(data.data-id).event('data-id');
``
```

**Comment by rosmith76** [comment]
When I used the code as it's written above, the console log gives me this object.

``` .js
Object {id: "7", submit: "Delete"}
id
:
"7"
submit
:
"Delete"
__proto__
:
Object
```

I have tried rewriting this code several different ways, and I can't get the 7 out of this object.
I have tried
code 

``` .js
let id =$(data.event.id);
```

error message
Cannot read property 'id' of undefined

code 

``` .js
let id =$(event.data.id);
```

error message
Cannot read property 'id' of undefined

code

``` .js
let id =$(data.data.id);
```

error message
Cannot read property 'id' of undefined

code 

``` .js
let id =$(data.data.id).event.data.id;
```

error message
Cannot read property 'id' of undefined

code 

``` .js
let id =$(data.id);
```

error 
XMLHttpRequest cannot load http://localhost:3000/events/[object%20Object].

**Comment by gaand** [comment]
Two problems (the missing `value=""` wasn't what I was trying to get you to see.

One, the name you're giving the input:

``` diff
-<input type= "text" name= "[event]id" placeholder="Event ID#" value="">
+<input type="text" name="event[id]" placeholder="Event ID#" value="">
```

Two, when you wrap anything in `$(` and `)`,  you get back a jQuery object, but you just want the `id`.
So, after making the previous change:

``` diff
-let id =$(data.event.id);
+let id = data.event.id;
```

**Comment by rosmith76** [comment]
With the above changes I still get the same result.
error message
Cannot read property 'id' of undefined

**Comment by payne-chris-r** [comment]
Can you log what `data` is now?

**Comment by rosmith76** [comment]
It hasn't changed.

``` .html
Object {event: Object, submit: "Delete"}
event
:
Object
id
:
"7"
__proto__
:
Object
submit
:
"Delete"
__proto__
:
Object
```

**Comment by gaand** [comment]
That is different from what you posted previously.  

Please post the current code for `onDeleteEvent`.

**Comment by payne-chris-r** [comment]
Doesn't the object now include a new object with a key "event"?

**Comment by rosmith76** [comment]
``` .js
const onDeleteEvent =(event) => {
  event.preventDefault();
  let data = getFormFields(event.target);
  console.log(data);
  let id =event.data.id;
  api.deleteEvent(id)
    .done(ui.deleteEventSuccess)
    .fail(ui.failure);
};
```

**Comment by gaand** [comment]
Order matters.  You have to read what you type carefully.

This is not the correction I suggested above:

``` js
let id =event.data.id;
```

Please compare that to what I suggested and see if you can figure out what's wrong.

**Comment by rosmith76** [comment]
I would have sworn that I wrote that the same way. After looking at this code for so long I could not see the difference. Thanks for working through this with me. 
Final correct code

``` .js
const onDeleteEvent =(event) => {
  event.preventDefault();
  let data = getFormFields(event.target);
  console.log(data);
  let id = data.event.id;
  api.deleteEvent(id)
    .done(ui.deleteEventSuccess)
    .fail(ui.failure);
};
```
