### ISSUE TITLE
Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by hantungy** [ga-wdi-boston/full-stack-project#449]
I have two branches with fully working code, one for the API and one for the Client. It works perfectly fine when I run those two branches together. But it stops working when I merge them to master and run it. It gives me a error in the console when I try to run a function:

`Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR`

**Comment by berziiii** [comment]
Solved. You cannot have `https://localhost:3000` or `https://localhost:8080` as your urls. They cannot be secure.

**Comment by hantungy** [comment]
thx Brian!!
