### ISSUE TITLE
Patch request for /profiles controller 

### ISSUE THREAD

**Issue by dhuddell** [ga-wdi-boston/full-stack-project#45]
My patch request in my profiles controller is wrong. Server response involves:

```
Started PATCH "/profiles/?user_id=1" for ::1 at 2015-11-11 12:24:14 -0500
ActionController::RoutingError (No route matches [PATCH] "/profiles"):
```

Controller looks like this: 

```
# PATCH /profiles/1
  def update
    if @profile.update(update_params)
      head :no_content
    else
      render json: @profile.errors, status: :unprocessable_entity
    end
  end
```

referencing this:

```
  def update_params
    params.require(:profile).permit(:nickname, :zip_code, :user_id)
  end
```

**Comment by gaand** [comment]
What's in `config/routes.rb`?  What's the output of `rake routes`?

**Comment by dhuddell** [comment]
I got some help from Jeff before he left and we restructured my profiles to be nested inside of users
ie `..url/users/[user_id]/profile` so I need to move forward to seeing how to work my controllers so that I can reach the route.

**Comment by gaand** [comment]
Do actions with profiles ever need anything other than `current_user`?  If not, then nesting probably isn't necessary.

**Comment by dhuddell** [comment]
I believe his reasoning was that I was querying for the id when I could just use the user_id in the path for the profile (now singular)

**Comment by gaand** [comment]
Yes.  I'm asking if that id is always the id of `current_user`.  If it is, then you don't need it in the query at all.

**Comment by dhuddell** [comment]
Resolved.
