### ISSUE TITLE
Issue when I try to push

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#451]
I got this error message when pushing my front end:

```
~/WDI_Fall_2016/projects/book-sucks/book-sucks-frontend (booksucks)$ git push origin booksucks
To github.com:julie1013/booksucks-front-end.git
 ! [rejected]        booksucks -> booksucks (fetch first)
error: failed to push some refs to 'git@github.com:julie1013/booksucks-front-end.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~/WDI_Fall_2016/projects/book-sucks/book-sucks-frontend (booksucks)$ git push origin booksucks
To github.com:julie1013/booksucks-front-end.git
 ! [rejected]        booksucks -> booksucks (fetch first)
error: failed to push some refs to 'git@github.com:julie1013/booksucks-front-end.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~/WDI_Fall_2016/projects/book-sucks/book-sucks-frontend (booksucks)$ 
```

Not sure what this means...

**Comment by payne-chris-r** [comment]
You're about to find out...

**Comment by payne-chris-r** [comment]
Add the screenshot we took next time you get a chance.

**Comment by julie1013** [comment]
![screen shot 2016-10-06 at 10 22 29 am](https://cloud.githubusercontent.com/assets/14143334/19156170/fd352486-8bae-11e6-861d-e2c1dc4b0a0a.png)

**Comment by julie1013** [comment]
This is a screenshot but I was having issues specifically pushing frontend.

**Comment by payne-chris-r** [comment]
Please stop working on this during Brian's lecture. Check this next break.

**Comment by payne-chris-r** [comment]
Your front end should not have a `heroku` branch. It should have a `gh-pages` branch. Let's fix this during the next break.

**Comment by julie1013** [comment]
I know. I only realized that last week when I asked you about it. But for a bit I was able to deploy. In any case, I'm still not sure why I couldn't push this time. I wasn't trying to push to heroku.

**Comment by julie1013** [comment]
Must have accidentally pushed `master` instead of `booksucks` to `booksucks`. Created a new branch `booksucksfront` and merged from `booksucks`. I'll be working from `booksucksfront` now.
