### ISSUE TITLE
Trouble deploying my backend

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#455]
I got this error when trying to deploy my backend to Heroku:

```
To github.com:julie1013/booksucks-api.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:julie1013/booksucks-api.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

Is this related to the issue I was having the other day with my frontend, @payne-chris-r ?

**Comment by payne-chris-r** [comment]
What was the command you tried to run?

**Comment by julie1013** [comment]
`git push`

**Comment by payne-chris-r** [comment]
Is that it? What branch are you pushing? What remote are you pushing to?

**Comment by julie1013** [comment]
Sorry, `git push origin master` from master

```
error: failed to push some refs to 'git@github.com:julie1013/booksucks-api.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by payne-chris-r** [comment]
The title of this issue suggests you're trying to push to heroku.
The command you ran is trying to push to github (I assume).
`git push origin master` will push to your master branch on whatever git believes `origin` is (typically github). If you're not sure, type `git remote -v`

**Comment by julie1013** [comment]
Oh, I see. I saw `git push` on there and thought it was telling me to do that. I realize upon second reading that it was breaking down what happens on `git push heroku master` 

My bad!

**Comment by payne-chris-r** [comment]
Another reason we tell you to go slow ;-). Especially with `git`!!!

**Comment by julie1013** [comment]
Yeah, well, you need to go slower too... how many times can you take a day off to go to Six Flags just so you can barrel along at 90 MPH on a roller coaster? ;)
