### ISSUE TITLE
jquery.js:4996 Uncaught TypeError: Cannot create property 'guid' on string 

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#456]
I get this error when adding the click handler for `#removeNote`:

`jquery.js:4996 Uncaught TypeError: Cannot create property 'guid' on string`

This is the click handler:

`$('#to-read-list-div ol').on('submit', 'li #removeNote', events.onRemoveNote);`

This is the loop that sets up this field:

``` js
const onShowMyToReadListSuccess = function (data){
  $('#to-read-list').children(':not("h4")').remove();
  let qualifiedBookID;
  for(let i = 0; i < data.length; i++){
    if (data[i].notes === null){
      data[i].notes = "Your note here!";
      $('#removeNote').hide();
      $('#addNote').show();
    }
    qualifiedBookID = data[i].id;
    $('#to-read-list').append('<li data-id=' + qualifiedBookID + '>' +
    '<span class=title>' + data[i].book.title +'</span>' + ' , by ' +
    '<span class=author>' +  data[i].book.author + '</span>'+ '<p id="noteSpace">Notes:</p>' +
    data[i].notes +
    '<form id=remove-from-my-to-read-list class=remove-from-my-to-read-list-button>' +
    '<input type=submit value="Remove" >' + '</form>' +
    '<form id="addNote" class="notes-field">' + '<input type=submit value="Write a note?">' +
    '<input name="notes"' + 'input type="text"'+ 'value="">' + '</form>' +
    '<form id="removeNote" class="notes-field">' + '<input type=submit value="Remove Note">' +
    '</form>' + '</li>');
    if (data[i].notes !== "Your note here!"){
      $('#removeNote').show();
      $('#addNote').hide();
    }
  }
};
```

Tried targeting the button (field; it's a submit event) in other ways, but none of them seem to work. But I'm guessing the problem is in the way I'm targeting the button.

**Comment by julie1013** [comment]
`$('#to-read-list-div ol li').on('submit', '#removeNote', events.onRemoveNote);`

This fixed it

**Comment by jrhorn424** [comment]
This is an incredibly complicated traversal. You should really be targeting forms directly for submit events.

**Comment by julie1013** [comment]
Yeah, but if I'm creating a list, shouldn't I be adding it dynamically?

**Comment by jrhorn424** [comment]
Yes, you have a point. I was mistaken where emphasis added:

> You should really be **targeting forms directly** for submit events. 

Great catch!!

I'll take this opportunity to be more explicit:

``` diff
-$('#to-read-list-div ol li').on('submit', '#removeNote', events.onRemoveNote);
+$('body').on('submit', '#removeNote', events.onRemoveNote);
```

This isn't _great_, but its OK for an app this size. More generally, you could find a closer parent than body, but not be so specific with your selector. Would something like this work, assuming nothing else changed?

```
$('#to-read-list-div').on('submit', '#removeNote', events.onRemoveNote);
```

Also, it's usually not a great idea to add HTML element names to your IDs or class names, in this case:

``` diff
- #to-read-list-div
+ #to-read-list
```

**Comment by julie1013** [comment]
Nope, that doesn't target the form button!

**Comment by jrhorn424** [comment]
> Nope, that doesn't target the form button!

You mean it doesn't target the form? That's odd. Do you have multiple `#to-read-list` elements on the page? IDs have to be unique within the DOM.

**Comment by julie1013** [comment]
Yep, I've made that change, setting up click handlers within the loop and adding the index number to the end of the id name.
