### ISSUE TITLE
Resolving git merge conflicts

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#458]
Merged from `booksucksfront` to `master`. Now trying to merge `master` to `gh-pages`. There's a conflict between `master` and `gh-pages`. Whatever's on `master` is what I want. How do I resolve it? I'm asking directly because I know I'm playing with fire.

**Comment by jrhorn424** [comment]
> I'm asking directly because I know I'm playing with fire.

Good. :smile:

While you're in a bad merge state, can you paste the output of `git status` here?

**Comment by julie1013** [comment]
```
git merge master
Auto-merging index.html
CONFLICT (content): Merge conflict in index.html
Auto-merging assets/styles/main.scss
CONFLICT (content): Merge conflict in assets/styles/main.scss
Auto-merging assets/scripts/ui.js
CONFLICT (content): Merge conflict in assets/scripts/ui.js
Auto-merging assets/scripts/site-api.js
CONFLICT (content): Merge conflict in assets/scripts/site-api.js
Auto-merging assets/scripts/index.js
CONFLICT (content): Merge conflict in assets/scripts/index.js
Auto-merging assets/scripts/events.js
CONFLICT (content): Merge conflict in assets/scripts/events.js
Removing assets/scripts/backendtoread.js
Removing assets/scripts/addbackendui.js
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by jrhorn424** [comment]
As long as you're sure `master` is what you want, you can do this:

```
git checkout gh-pages # if you're on a different branch
git merge -X theirs master 
```

Pay attention to the output and do a `git status` afterword. Then visually inspect the files and make sure they are the ones you want.

**Comment by julie1013** [comment]
All set!
