### ISSUE TITLE
Cannot create profile after logging in with curl.

### ISSUE THREAD

**Issue by kaylal12** [ga-wdi-boston/full-stack-project#46]
I log in with a user and take the token i receive from the server.
When trying to create a profile with that token, I receive "HTTP Token Access Denied".

The controller looks like this:

```
def create
    @profile = current_user.create_profile(profile_params)

    if @profile.save
      render json: @profile, status: :created, location: @profile
    else
      render json: @profile.errors, status: :unprocessable_entity
    end
  end
```

This works if I try to create a profile within the rails console, so i'm not sure what i'm missing.

**Comment by gaand** [comment]
The problem precedes this code.  How are you invoking the create action for the profile controller?  curl, postman, JavaScript?

**Comment by srhoulam** [comment]
Are you setting an authorization header containing your token in your request?

Please paste the `curl` call or your front-end code to make the ajax request.

**Comment by kaylal12** [comment]
I have been using curl.

To login i use:

```
curl --request POST --header "Content-Type: application/json" -d '{
  "credentials": {
    "email": "abc@abc.com",
    "password": "abc"
  }
}' http://localhost:3000/login
```

which works and gives me 

```
User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "abc@abc.com"]]
  SQL (7.5ms)  UPDATE "users" SET "token" = '732ce0d9ac8cd31fedd435f4ce23cac5', "updated_at" = '2015-11-11 18:24:00.070783' WHERE "users"."id" = $1  [["id", 2]]
```

Taking the token given, i use

```
curl --request POST --header "Authentication Token token=732ce0d9ac8cd31fedd435f4ce23cac5" --header "Content-Type: application/json" -d '{
  "profile": {
    "first_name": "hello",
    "last_name": "goodbye",
    "description": "test profile"
  }
}' http://localhost:3000/profiles
```

which then gives me "HTTP Token: Access denied."

**Comment by srhoulam** [comment]
Kayla, change `--header "Authentication Token token=732ce0d9ac8cd31fedd435f4ce23cac5"` to `--header "Authorization: Token token=732ce0d9ac8cd31fedd435f4ce23cac5"`

**Comment by kaylal12** [comment]
Thank you!
