### ISSUE TITLE
Removing a note

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#464]
Users can write notes for the books on their to-read list. I also want a way for them to be able to remove the notes or, more specifically, return it to its default setting (notes, a column in `qualified_books` has a default setting of "Your note shows here!" Obviously, the method would be PATCH, not DELETE. But I'm not sure how to target that with a curl request let alone do it through the ajax request. Is this an issue that I'd have to address through routes and controller?

**Comment by julie1013** [comment]
More specifically, I have this route:

``` ruby
patch '/qualified_books/:id' => 'qualified_books#update_notes'
```

And this controller:

``` ruby
def update_notes
    @qualified_book = QualifiedBook.find(params[:id])
    if @qualified_book.update(qualified_book_params)
      render json: @qualified_book
    else
      render json: @qualified_book.errors, status: :unprocessable_entity
    end
  end
```

**Comment by julie1013** [comment]
This works:

``` js
const onRemoveNote = function(event){
  event.preventDefault();
  let qualifiedBookID = $(this).parents().attr('id');
  console.log(qualifiedBookID);
  let params = {notes: "Your note shows here!"};
  api.removeNote(params, qualifiedBookID)
  .done(uiAddNote.onRemoveNoteSuccess)
  .fail(uiAddNote.onError);
};
```

``` js
const removeNote = function(params, qualifiedBookID){
  return $.ajax({
    url: app.host + '/qualified_books/' + qualifiedBookID,
    method: 'PATCH',
    data: {
      qualified_book : params
    },
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
  });
};
```

**Comment by jrhorn424** [comment]
Specifically, the original code (not posted) wasn't working since the function call parameters and the function definition parameters for `removeNote` were reversed.
