### ISSUE TITLE
Issue with deployed client not working with deployed api

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/full-stack-project#466]
I get the same error no matter what action I try. Sign up, in, update etc. 
error

```
rosmith76.github.io/:1 XMLHttpRequest cannot load https://shrouded-taiga-89115.herokuapp.com/sign-up/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://rosmith76.github.io' is therefore not allowed access. The response had HTTP status code 400.
```

app.js

``` .js
const app = {
  // host: 'http://localhost:3000'
  host: 'https://shrouded-taiga-89115.herokuapp.com'
};
```

application.rb

``` .rb
    config.middleware.use Rack::Cors do
      allow do
        origins ENV['CLIENT_ORIGIN'] || 'https://rosmith76.github.io/browser-LiveMusicCalendar/'
        # rosmith76.github.io/
        resource '*',
                 headers: :any,
                 methods: [:options, :get,
                           :post, :patch, :put, :delete]
      end
    end
  end
end
```

**Comment by payne-chris-r** [comment]
Have you looked through other issues? Almost every deployment issue can be resolved by either re-doing the deployment guide or looking through old issues.

**Comment by payne-chris-r** [comment]
I'm not trying to brush you off, I'm just giving you options until I have time to take a real look. Does curl work to your deployed back end?

**Comment by berziiii** [comment]
Definitely follow chris on looking at closed issues and deployment guide again. 

But also set a var config in your Heroku settings that is a key of CLIENT_ORIGIN and the value is your deployed API.  Find it by log into the Heroku website, not through terminal > settings > config vars > enter new variable.

**Comment by berziiii** [comment]
Correction. Your deployed client URL - no API in Heroku config vars

**Comment by rosmith76** [comment]
I updated client origin and made a change to application rb

``` .rb
    config.middleware.use Rack::Cors do
      allow do
        origins ENV['CLIENT_ORIGIN'] || 'https://rosmith76.github.io/'
        # rosmith76.github.io/
        resource '*',
                 headers: :any,
                 methods: [:options, :get,
                           :post, :patch, :put, :delete]
      end
    end
  end
end
```

**Comment by berziiii** [comment]
That is not what it is supposed to be but more importantly, did you add a `CLIENT_ORIGIN` to the heroku > settings > config vars?

**Comment by berziiii** [comment]
![image](https://cloud.githubusercontent.com/assets/8379295/19357432/ab505834-913f-11e6-883b-b5e519f6cfa7.png)

![image](https://cloud.githubusercontent.com/assets/8379295/19357439/b4437c82-913f-11e6-9886-b527a2fe5aae.png)

![image](https://cloud.githubusercontent.com/assets/8379295/19357451/c15d4aa6-913f-11e6-8998-8079d135b8b8.png)

![image](https://cloud.githubusercontent.com/assets/8379295/19357454/c40cb11a-913f-11e6-9c4c-30c46b9416de.png)

**Comment by rosmith76** [comment]
Yes. I updated client origin.

**Comment by berziiii** [comment]
Update? Working?

**Comment by rosmith76** [comment]
No. Still not working

**Comment by berziiii** [comment]
Please show the url you have in the client origin on heroku.

**Comment by rosmith76** [comment]
https://rosmith76.github.io/browser-LiveMusicCalendar/

**Comment by jrhorn424** [comment]
@rosmith76 Please update with solution and note any details regarding the format of the URL.

**Comment by rosmith76** [comment]
The link in application.rb was incorrect. I changed it to

``` .js
    config.middleware.use Rack::Cors do
      allow do
        origins ENV['CLIENT_ORIGIN'] || 'https://localhost:8080/'
        # rosmith76.github.io/
        resource '*',
                 headers: :any,
                 methods: [:options, :get,
                           :post, :patch, :put, :delete]
      end
    end
  end
end
```

CLIENT_ORIGIN link on Heroku page was also updated to 
https://rosmith76.github.io/

**Comment by jrhorn424** [comment]
Not exactly.

> CLIENT_ORIGIN link on Heroku page was also updated to  https://rosmith76.github.io/

But it should be `https://rosmith76.github.io` (note, no trailing slash). Should be the same thing here:

``` diff
-         origins ENV['CLIENT_ORIGIN'] || 'https://localhost:8080/'
+         origins ENV['CLIENT_ORIGIN'] || 'https://localhost:8080'
```
