### ISSUE TITLE
Curl register request failing

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/full-stack-project#47]
Here is my curl request:

curl --include --request POST --header "Content-Type: application/json" -d '{
  "credentials": {
    "email": "ab@example.email",
    "password": "an example password",
    "password_confirmation": "an example password"
  }
}' http://localhost:3000/register

Here is the error:
Started POST "/register" for ::1 at 2015-11-11 13:19:55 -0500
Processing by AuthController#register as _/_
  Parameters: {"credentials"=>{"email"=>"ab@example.email", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}
   (0.2ms)  BEGIN
  User Exists (0.5ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = 'ab@example.email' LIMIT 1
  SQL (1.7ms)  INSERT INTO "users" ("email", "password_digest", "created_at", "updated_at", "token") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["email", "ab@example.email"], ["password_digest", "$2a$10$ci6ZIs0XYsXeeYlJOH0zQ.ump8PE3HQWBnKSkE66SUPQdiht3W/wy"], ["created_at", "2015-11-11 18:19:55.375057"], ["updated_at", "2015-11-11 18:19:55.375057"], ["token", "a8157740c31ed7324cbb1250bf069076"]]
PG::NotNullViolation: ERROR:  null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (12, ab@example.email, a8157740c31ed7324cbb1250bf069076, $2a$10$ci6ZIs0XYsXeeYlJOH0zQ.ump8PE3HQWBnKSkE66SUPQdiht3W/wy, 2015-11-11 18:19:55.375057, 2015-11-11 18:19:55.375057, null, null).
: INSERT INTO "users" ("email", "password_digest", "created_at", "updated_at", "token") VALUES ($1, $2, $3, $4, $5) RETURNING "id"
   (0.2ms)  ROLLBACK
Completed 500 Internal Server Error in 97ms (ActiveRecord: 2.6ms)

**Comment by LaurisaNeuwirth** [comment]
I need to remove the not_null constraint on a column in my users table. I tried 

change_column :users, :name, :string, :null => false

and got back an error: NoMethodError: undefined method `change_column' for main:Object

**Comment by GA-MEB** [comment]
If you added the `not_null` constraint in your migration, then that's where you'll need to remove it. 
Run `rake db:rollback` until your `CreateUsers` migration has been rolled back, change the migration file, and then run `rake db:migrate`.

**Comment by GA-MEB** [comment]
Out of curiosity, can you also paste in the part of your `schema.rb` file that contains the `users` table?

**Comment by LaurisaNeuwirth** [comment]
Sure, here is the user table from the schema files:

create_table "users", force: :cascade do |t|
    t.string   "email",           null: false
    t.string   "token",           null: false
    t.string   "password_digest", null: false
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.string   "name",            null: false
    t.string   "hive"
  end

**Comment by LaurisaNeuwirth** [comment]
Matt I am worried to run db:rollback over & over bc I had fixed things earlier and dont want them un-fixed. Can I see you in person for this please?

**Comment by LaurisaNeuwirth** [comment]
I tried solving this with Saad and he said I need some help

**Comment by srhoulam** [comment]
The original issue is resolved. Please open a new issue for anything else that comes up.

**Comment by LaurisaNeuwirth** [comment]
The workaround for this issue requires customization for the register submit form and I need some help to finish that part, so I am re-opening this.
