### ISSUE TITLE
Project API - ERD and CRUD review/help

### ISSUE THREAD

**Issue by kibs86** [ga-wdi-boston/full-stack-project#471]
I'm having trouble coming up with a way to incorporate update into my game and also have a couple of questions regarding my ERD before I start doing any work building out my API.

**Comment by neugierige** [comment]
Is your ERD in a format that you can post here? What do you currently have for the other CRUD methods?

**Comment by gaand** [comment]
Links to existing material will definitely help to focus any discussion.

**Comment by kibs86** [comment]
My current CRUD methods are:
Create
1. When a user guesses a word correctly, it creates an entry in my completed_words join table.
2. I was thinking about allowing users to add (create) their own words

Retrieve
1. When a user chooses a difficulty, it will GET a word from that difficulty tier for them to unscramble.
2. Future enhancement: allowing users to get a count of levels completed within each difficulty tier

Update - TBD
1. I was thinking if a user could create a word then they could update it as well, but I'm not really sure what purpose that would serve.  Maybe if they misspelled it or something?  I was hoping to find something that added a bit more to the game functionality.  If I modified the auth API to allow a user to setup a username and update their email would that count?

Delete
1. Allowing a user to reset their game state (delete all of their completed words)

My ERD options can be seen here: https://www.lucidchart.com/invitations/accept/9f4dfced-5b25-44ae-8709-9977224c42aa

I've pretty much ruled out option 3, but I'm not sure whether I should go with option 1 or 2.  Option 2 would be better if I'm allowing users to create their own words.  I'd like to at some point have each word be a level so users can choose any of their uncompleted levels to play.  If all words are in one table it will be harder to do that.

**Comment by neugierige** [comment]
Kara, the ERD diagrams are not visible without a login. Can you post a screenshot or a jpeg?

**Comment by neugierige** [comment]
regarding the CRUD methods, I do believe that changing password was a PATCH

**Comment by kibs86** [comment]
ERD - Option 1
![erd - option 1](https://cloud.githubusercontent.com/assets/16957330/20681011/9379d394-b56f-11e6-8a91-d951f74a4b04.jpeg)

ERD - Option 2
![erd - option 2](https://cloud.githubusercontent.com/assets/16957330/20681012/953c39d8-b56f-11e6-9106-877092204b5f.jpeg)

I've attached my ERD jpegs.  Sorry about that!

Changing password is a PATCH, but it's given to us as part of the template.  Since I need at least one other to meet the project requirements I was curious if I could add to the auth API and add an additional PATCH there if I can't find a way to implement one as part of my game API.

**Comment by gaand** [comment]
@neugierige CRUD is required on something other than user.

@kibs86 Perhaps the creator could update the word difficulty?

**Comment by kibs86** [comment]
Right now, when they select a difficulty it just triggers a GET to grab a word from that difficulty tier.  When they either successfully unscramble or reach max turns, they're routed back to the choose difficulty screen to play again.  For now I guess I could just give them the ability to update any of the words they create themselves in case they typo it or something.  In the future, I'd like to connect to a dictionary API to do a check that a word a user creates is an actual dictionary word, but it's not in my initial scope.

**Comment by gaand** [comment]
I meant an admin type could update the difficulty.  Or maybe some other property of the words.  

Where do the words come from?  Loaded at the start?  Crowd sourced? Someone with special permissions?

**Comment by kibs86** [comment]
Oh ok, that's a good idea!  I'll look at what I could implement for admin functionality.  I was just going to load words at the start.  Just a few for testing purposes while I'm building everything and then bulk load a bunch for each difficulty tier.

**Comment by kibs86** [comment]
Closing this issue.  I'm going to think about what I may be able to implement for admin functionality to fulfill the update requirement.  Thank you for the help!
