### ISSUE TITLE
Trouble Showing Backend Data on the Front End

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/full-stack-project#473]
Can't seem to get data to show on my front end. I am trying to show a chore which gets put into the backed in an object. I use a for in loop to access the data and then put it into a div it but for some reason, only the the last key value pair shows up. Here is my code:

`let showData = function(data){
  for(let i in data) {
  $('.chore').text( i + ": " + data[i]);
  }
};`

**Comment by raq929** [comment]
Can you explain more about what you're trying to do?
Also, what file is this in? Where is data defined?

**Comment by akradin** [comment]
Yup! so, my app is designed to assign chores to a group of people. I haven't gotten the group part set up, but that is irrelevant. In the spirit of small problems first, I just want to display the data that is input on the front end (which is where data is defined) on the user facing site.

This is in my  event.js file so when you create a chore, this function runs. Here is the other part of the function
``` onCreateChore = function (event) {
  event.preventDefault();
  let data = getFormFields(this);
  api.createChore(data)
    .then(ui.success)
    .catch(ui.failure);
  console.log(data);
  showData(data);
};
```

Update: I checked my object and it is not populating correctly.
I have my `chore_params` in the backend formatted properly but I still can't figure out why it is not working.
I know that the back end is working because it works in rails console and via curl request. I also have the HTML formatted properly when it accepts data.

**Comment by payne-chris-r** [comment]
Throw a `console.log("Data is ", data);` right after `let data = getFormFields(this)`. 
What is it? 
What does your rails server say? Maybe something like `required parameter is missing or invalid: chore`?

**Comment by akradin** [comment]
Rails server seems to be okay. When I do a `console.log` I get `data is [object Object]`

**Comment by payne-chris-r** [comment]
Please post the output for both the rails server and your updated code with the logs.

**Comment by akradin** [comment]
Code from the rails server:
```Started POST "/chores" for ::1 at 2016-11-28 20:50:25 -0500
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by ChoresController#create as */*
  Parameters: {"chore"=>{"name"=>"1", "due_date"=>"", "difficulty"=>""}}
   (0.2ms)  BEGIN
  SQL (13.6ms)  INSERT INTO "chores" ("name", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["name", "1"], ["created_at", "2016-11-29 01:50:25.578090"], ["updated_at", "2016-11-29 01:50:25.578090"]]
   (190.0ms)  COMMIT
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Chore (0.52ms)
Completed 201 Created in 238ms (Views: 7.9ms | ActiveRecord: 207.7ms)
```

Updated code:
```js
const onCreateChore = function (event) {
  event.preventDefault();
  let data = getFormFields(this);
  console.log("data is" + data)
  api.createChore(data)
    .then(ui.success)
    .catch(ui.failure);
  console.log(data);
};

const addHandlers = () => {
$('.chore-submit').on('submit', onCreateChore);
};
```

the second `console.log`  shows the object with all of the added data:
```
chore-events.js:15 
Object
chore
:
Object
difficulty
:
"2"
due_date
:
"2016-12-02"
name
:
"sweep"
```

Unsure of how best to show console messages from chrome on here

**Comment by gaand** [comment]
Please post the form markup.

**Comment by payne-chris-r** [comment]
Can you just post a screenshot? Typically screenshots aren't that helpful, but I think with logs it'll work.

**Comment by akradin** [comment]
Yup
<img width="416" alt="screen shot 2016-11-28 at 10 12 21 pm" src="https://cloud.githubusercontent.com/assets/22475825/20695132/d2b02e12-b5b7-11e6-84fb-f4f10b1e9d3f.png">

**Comment by payne-chris-r** [comment]
Can you post the curl request that IS working and the rails output for that as well? Rails isn't receiving any of the information properly, but your object looks sound. After you've done that, please post the `createChore` function from your `api` file.

**Comment by akradin** [comment]
curl request:
```sh
curl --include --request POST http://localhost:4741/chores \
  --header "Content-Type: application/json" \
  --data '{
    "chore": {
      "name": "rake",
      "due_date": "2016-11-30",
      "difficulty": 5,
      "assigned_to": "ralph"
    }
  }'
```

`createChore` function:
```js
const config = require('../config.js');

const createChore = (data) =>
  $.ajax({
    url: config.host + '/chores',
    method: 'POST',
    data,
  });
```

**Comment by payne-chris-r** [comment]
Rails output?

**Comment by akradin** [comment]
Rails Output after curl request:
```sh
Started POST "/chores" for ::1 at 2016-11-29 08:40:26 -0500
Processing by ChoresController#create as */*
  Parameters: {"chore"=>{"name"=>"rake", "due_date"=>"2016-11-30", "difficulty"=>5}}
   (0.1ms)  BEGIN
  SQL (23.6ms)  INSERT INTO "chores" ("name", "due_date", "difficulty", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "rake"], ["due_date", "2016-11-30"], ["difficulty", 5], ["created_at", "2016-11-29 13:40:26.137968"], ["updated_at", "2016-11-29 13:40:26.137968"]]
   (0.8ms)  COMMIT
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Chore (0.46ms)
Completed 201 Created in 43ms (Views: 4.6ms | ActiveRecord: 31.4ms)
```

Per request, also made curl request for GET method:
```sh
curl --include --request GET http://localhost:4741/chores \
  --header "Content-Type: application/json"
```

Rails output for this:
```sh
Started GET "/chores" for ::1 at 2016-11-29 08:53:30 -0500
Processing by ChoresController#index as */*
  Chore Load (0.6ms)  SELECT "chores".* FROM "chores"
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with Chore::ActiveRecord_Relation (8.58ms)
Completed 200 OK in 11ms (Views: 10.4ms | ActiveRecord: 0.6ms)
```

**Comment by raq929** [comment]
It looks like you are successfully creating a Chore both with your request and through curl. I'm not quite clear on what the problem is. Is the new chore not showing up in your list of chores?

**Comment by payne-chris-r** [comment]
Sorry, I realize it can be confusing to know what to look for initially. When we're debugging issues with rails we really want to see a) what the curl request returned in terminal in addition to b) what the rails API processed (so both terminal window outputs). Here we would expect that curl request to return a json object that's full of chores, but I can't be certain that's the case without knowing what the returned json was.
Can you paste the output in the terminal window from that curl request please?

**Comment by neugierige** [comment]
Is your `showData` still the same as what you initially posted? Looks like you're trying to convert the entire object to text. Have you tried specifying a particular property, like `name`?

**Comment by akradin** [comment]
Rachel, everything is working when I add a chore to the back end. I want the user to be able to see this, though. I am trying to get the data to show on the front end.

Lu, I have tried this. If I pass in data.name, it will run the loop on the name portion of the chore and return the key value pair of the last number and last letter of the chore name. 

Chris, here is the curl requests return in terminal
```sh
[{"id":1,"name":"rake","due_date":"2016-11-30","difficulty":5,"created_at":"2016-11-24T17:35:14.786Z","updated_at":"2016-11-24T17:35:14.786Z"},{"id":3,"name":"Dishes","due_date":"2016-12-02","difficulty":1,"created_at":"2016-11-26T19:47:58.019Z","updated_at":"2016-11-26T19:47:58.019Z"},{"id":4,"name":"Dishes","due_date":"2016-12-02","difficulty":1,"created_at":"2016-11-26T19:50:23.134Z","updated_at":"2016-11-26T19:50:23.134Z"},{"id":5,"name":"TEST","due_date":"2016-12-02","difficulty":1,"created_at":"2016-11-28T02:15:01.681Z","updated_at":"2016-11-28T02:15:01.681Z"},{"id":6,"name":"test","due_date":"2016-12-02","difficulty":1,"created_at":"2016-11-28T02:15:31.867Z","updated_at":"2016-11-28T02:15:31.867Z"},{"id":7,"name":"testing","due_date":"2016-01-12","difficulty":1,"created_at":"2016-11-28T21:16:43.375Z","updated_at":"2016-11-28T21:16:43.375Z"},{"id":8,"name":"tesgin","due_date":"2016-01-12","difficulty":2,"created_at":"2016-11-28T21:17:45.774Z","updated_at":"2016-11-28T21:17:45.774Z"},{"id":9,"name":"testin","due_date":"2016-01-12","difficulty":1,"created_at":"2016-11-28T21:22:41.619Z","updated_at":"2016-11-28T21:22:41.619Z"},{"id":10,"name":"","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:23:18.116Z","updated_at":"2016-11-28T21:23:18.116Z"},{"id":11,"name":"test","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:23:35.891Z","updated_at":"2016-11-28T21:23:35.891Z"},{"id":12,"name":"test","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:24:58.371Z","updated_at":"2016-11-28T21:24:58.371Z"},{"id":13,"name":"test","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:25:12.212Z","updated_at":"2016-11-28T21:25:12.212Z"},{"id":14,"name":"test","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:25:27.699Z","updated_at":"2016-11-28T21:25:27.699Z"},{"id":15,"name":"please","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:26:24.864Z","updated_at":"2016-11-28T21:26:24.864Z"},{"id":16,"name":"please","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:27:14.751Z","updated_at":"2016-11-28T21:27:14.751Z"},{"id":17,"name":"test","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:31:28.977Z","updated_at":"2016-11-28T21:31:28.977Z"},{"id":18,"name":"","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:31:50.017Z","updated_at":"2016-11-28T21:31:50.017Z"},{"id":19,"name":"test","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:35:57.865Z","updated_at":"2016-11-28T21:35:57.865Z"},{"id":20,"name":"update","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:36:39.347Z","updated_at":"2016-11-28T21:36:39.347Z"},{"id":21,"name":"1","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:39:05.648Z","updated_at":"2016-11-28T21:39:05.648Z"},{"id":22,"name":"test","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:39:54.874Z","updated_at":"2016-11-28T21:39:54.874Z"},{"id":23,"name":"chore 1","due_date":"2016-12-02","difficulty":16,"created_at":"2016-11-28T21:40:31.171Z","updated_at":"2016-11-28T21:40:31.171Z"},{"id":24,"name":"12","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:41:03.353Z","updated_at":"2016-11-28T21:41:03.353Z"},{"id":25,"name":"1","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:41:13.112Z","updated_at":"2016-11-28T21:41:13.112Z"},{"id":26,"name":"what","due_date":null,"difficulty":0,"created_at":"2016-11-28T21:41:34.407Z","updated_at":"2016-11-28T21:41:34.407Z"},{"id":27,"name":"test","due_date":null,"difficulty":null,"created_at":"2016-11-28T21:42:29.996Z","updated_at":"2016-11-28T21:42:29.996Z"},{"id":28,"name":"test","due_date":null,"difficulty":0,"created_at":"2016-11-28T22:02:23.657Z","updated_at":"2016-11-28T22:02:23.657Z"},{"id":29,"name":"test","due_date":null,"difficulty":0,"created_at":"2016-11-28T22:05:03.975Z","updated_at":"2016-11-28T22:05:03.975Z"},{"id":30,"name":"test","due_date":null,"difficulty":null,"created_at":"2016-11-28T22:07:34.461Z","updated_at":"2016-11-28T22:07:34.461Z"},{"id":31,"name":"poop","due_date":null,"difficulty":1,"created_at":"2016-11-28T22:11:46.190Z","updated_at":"2016-11-28T22:11:46.190Z"},{"id":32,"name":"","due_date":null,"difficulty":null,"created_at":"2016-11-28T22:12:37.351Z","updated_at":"2016-11-28T22:12:37.351Z"},{"id":33,"name":"suck","due_date":null,"difficulty":2,"created_at":"2016-11-28T22:12:52.736Z","updated_at":"2016-11-28T22:12:52.736Z"},{"id":34,"name":"pupp","due_date":null,"difficulty":9,"created_at":"2016-11-28T22:13:49.492Z","updated_at":"2016-11-28T22:13:49.492Z"},{"id":35,"name":"molly","due_date":null,"difficulty":1,"created_at":"2016-11-28T22:14:12.920Z","updated_at":"2016-11-28T22:14:12.920Z"},{"id":36,"name":"1","due_date":null,"difficulty":null,"created_at":"2016-11-29T01:50:25.578Z","updated_at":"2016-11-29T01:50:25.578Z"},{"id":37,"name":"rake","due_date":"2016-11-30","difficulty":5,"created_at":"2016-11-29T13:40:26.137Z","updated_at":"2016-11-29T13:40:26.137Z"},{"id":38,"name":"test","due_date":null,"difficulty":null,"created_at":"2016-11-29T13:41:13.477Z","updated_at":"2016-11-29T13:41:13.477Z"},{"id":39,"name":"test","due_date":null,"difficulty":3,"created_at":"2016-11-29T13:41:44.757Z","updated_at":"2016-11-29T13:41:44.757Z"},{"id":40,"name":"test","due_date":null,"difficulty":3,"created_at":"2016-11-29T13:41:53.386Z","updated_at":"2016-11-29T13:41:53.386Z"}]
```

**Comment by gaand** [comment]
Are you using the rails-API-template?

**Comment by akradin** [comment]
Yup

**Comment by gaand** [comment]
Your JSON doesn't have a root key. Did you create a serializer?

**Comment by raq929** [comment]
Ok, so you're successfully getting the data from the server to the front end, and the only problem right now is displaying it in HTML, correct?
The correct data is successfully getting passed to showData?

**Comment by akradin** [comment]
Antony, I do now. 
Rachel, yes. I can see all data in an object in Chrome console, just not in the HTML

**Comment by gaand** [comment]
The data is only correct if it has a root key `"chores"`.

**Comment by payne-chris-r** [comment]
I suggest making this do less until you know exactly what you're getting back. I don't think it's doing what you think it's doing.

```js
let showData = function(data){ 
  for(let i in data) { 
    $('.chore').text( i + ": " + data[i]); 
  } 
};
```

**Comment by raq929** [comment]
Agreed. What is the exact data you're looking at in showData? 
Can you get showData to insert 'hello world' into the html? 
Once you're sure it can print dummy text, move on to working with your data.

**Comment by akradin** [comment]
I mean, I just want to show the entire object. If I change the content of the div I am targeting with 
`$('.chore').text(data);`
The div content just changes to `[object Object]`

If I change it to `data.chore` or `data.name` I get nothing. I understand why `showData` is not working. 

Honestly kind of just at a loss as to what to do next. Can I set up a one-to-one?

**Comment by neugierige** [comment]
I agree with Rachel. Get some string, any string to show in your HTML with your function first.

**Comment by raq929** [comment]
So, if the content is changing to [object Object], that's success getting text into HTML.
Next you need to look at what the data is. It clearly doesn't have a 'chore' or 'name' key, so what does it have?
Console.log it inside showData and take a look.

**Comment by raq929** [comment]
Any luck with this?

**Comment by akradin** [comment]
Tried a couple of different things to no avail. Not really sure what else to try. I also abandoned the for in loop all together. Somone suggested using jQuery's each method which got me close, but still not quite. 
```
    $.each(data, function(key, value) {
        console.log(key, value);
    });
```
this shows exactly what I want in the console, i.e, all of hte chore paramaters but when I do this:
```
    $.each(data, function(key, value) {
        $('.chore').text(key, value);
    });
```
it just returns "chore" in the html. So not sure what to do next

**Comment by raq929** [comment]
Ok, I think you need to take a step back. What happens when you just `console.log(data)`. What does that object look like?

**Comment by akradin** [comment]
Like the image I posted above
<img width="416" alt="screen shot 2016-11-28 at 10 12 21 pm" src="https://cloud.githubusercontent.com/assets/22475825/20718828/0296992a-b628-11e6-85c2-091769e3a9b2.png">

**Comment by payne-chris-r** [comment]
So what's the difference between `console.log` and `.text`?

**Comment by akradin** [comment]
Uh, they return different things. `console.log` shows me everything and `.text` only shows me the object that contains everything. So, I need to get into that object, but I do not know how.

**Comment by neugierige** [comment]
You have the keys. You can use the keys to get values...

**Comment by akradin** [comment]
yeah that works
`data.chore.name`
`data.chore.due_date`
etc
thanks
