### ISSUE TITLE
Trying to set up rails-api-template

### ISSUE THREAD

**Issue by RpRoderick** [ga-wdi-boston/full-stack-project#474]
The instructions on rails-api-template are not entirely clear, specifically steps 11 and 12.  Where do the SECRET_KEY_BASE(s) go on heroku?  Not sure I want to post pics of my heroku settings page....I  have followed the steps up until that point (https://github.com/ga-wdi-boston/rails-api-template)
and discussed with a few people, but we are a little confused as to the correct placement.  Thanks!

**Comment by payne-chris-r** [comment]
They are referring to this: https://github.com/ga-wdi-boston/rails-heroku-setup-guide

**Comment by RpRoderick** [comment]
So, I may have done this correctly...The commands in rails-api-setup guide (heroku config:set SECRET_TOKEN=$(rake secret)) are a little confusing.  These commands only work when you specify an app with -app [APP NAME]  ?? is that correct?  so the actual commands would be heroku config:set --app [MY APP NAME] SECRET_TOKEN=$(rake secret that i generated?).  When I do these commands, they go through on terminal as a success, but I'm wondering what SECRET TOKEN actually is?  If you look on the rails-api-template and the heroku setup guide, some of the instructions seem to overlap.  You set up secret keys on .env and then you set up secret keys on heroku?  I'm assuming that you set up the same key on both? and that secret TOKEN is just another rake secret that you've generated?  If that is the case, I believe I've done it correctly, although when I ran the command heroku config:set --app [myappname] SECRET_KEY_BASE=$(rake secret i generated) it erased my key from the Heroku settings on the website itself.  ??  So...hard to tell if I did it correctly until I try and deploy.

**Comment by gaand** [comment]
Did you set up the repository as a heroku app?

**Comment by raq929** [comment]
your secret keys on heroku (for production) should be different from your secret keys for development and test.

**Comment by RpRoderick** [comment]
I followed the steps in rails-heroku-setup, which included heroku create, which gave me my app name.  However, when I type in git remote -v I'm looking at my git remotes, not my heroku remotes.  I may be misunderstanding the use of heroku.

**Comment by RpRoderick** [comment]
Ok, so I should simply generate a new secret key for the heroku settings page?

**Comment by raq929** [comment]
Where in your directories did you run heroku create? What did the console print out when you did it?

**Comment by BenGitsCode** [comment]
If you're using the the heroku Web UI to do anything, you're not following the guide.

**Comment by RpRoderick** [comment]
Hmm, that was yesterday...I believe that I ran it in my project folder, I should have taken a screenshot.  I believe that it printed out a success message and then I viewed remotes and it looked like it was supposed to:
 heroku  git@heroku.com:agile-badlands-7658.git (fetch)
    heroku  git@heroku.com:agile-badlands-7658.git (push)
    origin  git@github.com:tdyer/wdi_4_rails_hw_tdd_hacker_news.git (fetch)
    origin  git@github.com:tdyer/wdi_4_rails_hw_tdd_hacker_news.git (push)

After that, I figured out after how to run the commands config:set (these commands gave me an error when running them as described in instructions - see screenshot below.)

**Comment by RpRoderick** [comment]
<img width="657" alt="screen shot 2016-11-29 at 11 18 30 am" src="https://cloud.githubusercontent.com/assets/22726092/20718121/be5cc812-b625-11e6-95bf-bfac991879f1.png">

**Comment by RpRoderick** [comment]
This is just an example, as no rake secret is entered in, but this was the gist of the message

**Comment by payne-chris-r** [comment]
`heroku config:set SECRET...` not `heroku config: set SECRET...`. You have a space in your command.

**Comment by raq929** [comment]
Is this resolved? Please comment and close it if it is. :)
