### ISSUE TITLE
Unable to Add Reference Column To Table

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/full-stack-project#475]
I am trying to my Chores table to have a Reference to users so Chores are assigned to user ID.
I ran this rails command:
`bundle exec rails g migration AddAssignmentToChores assigned_to:references`

I then checked my migration file which looked like this:
```class AddAssignmentToChores < ActiveRecord::Migration
  def change
    add_reference :chores, :assigned_to, index: true, foreign_key: true
  end
end
```

Comparing this to the one to many code-along this appear to be what I **should** be getting but when I try to migrate to verify in my data base rake aborts and I get the following error message:
```ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "assigned_tos" does not exist
: ALTER TABLE "chores" ADD CONSTRAINT "fk_rails_6cb5c93091"
FOREIGN KEY ("assigned_to_id")
  REFERENCES "assigned_tos" ("id")
```

I did some further research online. It seems like I have everything set up properly. I also searched my entire project for `assigned_tos` and found nothing, so I am unsure of why pluralization is happening here.

Let me know if you need more info.

**Comment by payne-chris-r** [comment]
Alex, is the point of your app to be able to assign other users to a chore? Is that what `assigned_to` is supposed to be a user id?? If so, I think you want to `AddUserRefToChores`. Not `assigned_to`. When naming foreign keys you're much better off naming them `<table-name>_id`. Also, in the future, please post the full error. Let me know if that helps.

**Comment by akradin** [comment]
The point of the app is so chores get assigned to users. The ultimate goal would be to sum the difficulties (which are integers) of a users total chores using Ruby's count method or javscript/jquery and whichever user has the lowest number, gets the next chore. 

With that said, I think it could work that way. Simply, A user has many chores. so I think we are on the same wave length. Your markup got a little wonky though. Not sure what naming convention you are trying to convey but I deleted the old migration and did `AddUserRefToChores user_id:references`. Still getting errors. Here is the error message in full with the command I typed in:
```
~/wdi/projects/chore-tracker/rails-api-template-master (rails-setup)$ bundle exec rails g migration AddUserRefToChores user_id:references
Running via Spring preloader in process 9908
      invoke  active_record
      create    db/migrate/20161129015802_add_user_ref_to_chores.rb
~/wdi/projects/chore-tracker/rails-api-template-master (rails-setup)$ bundle exec rake db:migrate
== 20161129015802 AddUserRefToChores: migrating ===============================
-- add_reference(:chores, :user_id, {:index=>true, :foreign_key=>true})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "user_ids" does not exist
: ALTER TABLE "chores" ADD CONSTRAINT "fk_rails_c3299eb182"
FOREIGN KEY ("user_id_id")
  REFERENCES "user_ids" ("id")
/Users/AlexKradin/wdi/projects/chore-tracker/rails-api-template-master/db/migrate/20161129015802_add_user_ref_to_chores.rb:3:in `change'
/Users/AlexKradin/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/AlexKradin/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "user_ids" does not exist
: ALTER TABLE "chores" ADD CONSTRAINT "fk_rails_c3299eb182"
FOREIGN KEY ("user_id_id")
  REFERENCES "user_ids" ("id")
/Users/AlexKradin/wdi/projects/chore-tracker/rails-api-template-master/db/migrate/20161129015802_add_user_ref_to_chores.rb:3:in `change'
/Users/AlexKradin/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/AlexKradin/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
PG::UndefinedTable: ERROR:  relation "user_ids" does not exist
/Users/AlexKradin/wdi/projects/chore-tracker/rails-api-template-master/db/migrate/20161129015802_add_user_ref_to_chores.rb:3:in `change'
/Users/AlexKradin/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/AlexKradin/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by payne-chris-r** [comment]
Fixed markup. My b

**Comment by payne-chris-r** [comment]
What is the line from the `rails-api-...` lesson you're trying to emulate?
This one? 
```bash
rails g migration `AddAuthorToBooks author:references
```

**Comment by payne-chris-r** [comment]
Here's the migration from the `one-to-many` lesson:
```ruby
class AddAuthorRefToBooks < ActiveRecord::Migration
  def change
    add_reference :books, :author, index: true, foreign_key: true
  end
end
```

**Comment by akradin** [comment]
Yup, and mine looks similar. It just has  the information regarding my project.

```rb
class AddUserRefToChores < ActiveRecord::Migration
  def change
    add_reference :chores, :user_id, index: true, foreign_key: true
  end
end
```

**Comment by gaand** [comment]
`author:references` versus `user_id:references`

**Comment by akradin** [comment]
So it should just be `user:references`

Got it, thanks
