### ISSUE TITLE
Need help with Heroku

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/full-stack-project#476]
I cannot for the life of me get heroku working. I keep getting things like "app does not exist", and "'heroku' does not appear to be a git repository". I'm very confused and could use some help.

**Comment by gaand** [comment]
What have you tried?

Did you create a heroku app?

What generates  the git error?

**Comment by treep78** [comment]
following the rails-api-template instructions I executed 
```
heroku config:set CLIENT_ORIGIN https://treep78.github.io
``` 
which gives the error 
```
▸Error: No app specified
 ▸    Usage: heroku config:set --app APP
 ▸    We don't know which app to run this on.
 ▸    Run this command from inside an app folder or specify which app to use with --app APP
 ▸    
 ▸    https://devcenter.heroku.com/articles/using-the-cli#app-commands
```
so then I went back the the heroku setup guide and when I reach 
```git push heroku master``` 
I get the error 
```
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by raq929** [comment]
I would look at the heroku guide repo that Ben gave out.

**Comment by treep78** [comment]
that's what I was using

**Comment by raq929** [comment]
Ok. You said you were using rails-api-template instructions, so I was confused.
I would try doing what the error tells you to do: `heroku config:set --app APP`

**Comment by gaand** [comment]
This? https://github.com/ga-wdi-boston/rails-heroku-setup-guide

**Comment by neugierige** [comment]
@treep78 are you sure you did `heroku create` in your rails-api repo?

**Comment by treep78** [comment]
Yes, that's what I tried using. and running ```heroku config:set --app APP``` gives the error
```
 ▸    Usage: heroku config:set KEY1=VALUE1 [KEY2=VALUE2 ...]
 ▸    Must specify KEY and VALUE to set.
```

which I have tried to set every which way I can think of but nothing works.

**Comment by treep78** [comment]
I've accidentally created about 5 different heroku apps and none of them seem to be working

**Comment by raq929** [comment]
What do you get when you type `git remote -v`?

**Comment by neugierige** [comment]
what do you mean by "[not] working"?

**Comment by treep78** [comment]
the remote gives me 
```
origin	git@github.com:treep78/full-stack-project.git (fetch)
origin	git@github.com:treep78/full-stack-project.git (push)
```
I'm guessing that should somehow be the link to my heroku app instead, but I can't get that far in the heroku setup

**Comment by payne-chris-r** [comment]
Try starting over with the heroku deployment guide and be extremely methodical. Don't skip a step, don't brush over something you think you've done.

**Comment by treep78** [comment]
do I need to nuke anything or can I just start from the beginning?

**Comment by treep78** [comment]
I tried starting over, but when I run ```git remote -v``` it doesn't show any heroku remotes, just the origins

**Comment by raq929** [comment]
Ok. Are you in the root of your repository? What happened when you ran `heroku create`?

**Comment by treep78** [comment]
When I heroku create it creates a heroku app
```
Creating app... done, ⬢ guarded-fortress-68667
https://guarded-fortress-68667.herokuapp.com/ | https://git.heroku.com/guarded-fortress-68667.git
```

**Comment by neugierige** [comment]
ok, now navigate into your `rails-api-template` folder, or whatever you called it, and then run `git remote -v`

I think the issue here is what folder you are operating in. Be very attentive to that! Your project repo should be a git repo, and it should have heroku app.

**Comment by treep78** [comment]
I've gotten it linked with 
```
heroku git:remote -a guarded-fortress-68667
```
I just need to check if that's fixed it

**Comment by treep78** [comment]
So now I have new error when I try to execute 
```
git push heroku master
```
the error is
```
Counting objects: 190, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (155/155), done.
Writing objects: 100% (190/190), 75.45 KiB | 0 bytes/s, done.
Total 190 (delta 45), reused 45 (delta 18)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote:  !     No default language could be detected for this app.
remote: 			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
remote: 			See https://devcenter.heroku.com/articles/buildpacks
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to guarded-fortress-68667.
remote: 
To https://git.heroku.com/guarded-fortress-68667.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/guarded-fortress-68667.git'
```

**Comment by treep78** [comment]
I was able to use 
```
 heroku buildpacks:set heroku/ruby
```
to set a build pack, but I have new, but similar, errors
```
~/wdi/projects/full-stack-project/back-end (master)$ git push heroku master
Counting objects: 190, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (155/155), done.
Writing objects: 100% (190/190), 75.45 KiB | 0 bytes/s, done.
Total 190 (delta 45), reused 45 (delta 18)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Failed to detect set buildpack https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/ruby.tgz
remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to guarded-fortress-68667.
remote: 
To https://git.heroku.com/guarded-fortress-68667.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/guarded-fortress-68667.git'
```

**Comment by treep78** [comment]
I've reviewed https://devcenter.heroku.com/articles/buildpacks#detection-failure but the error there does not match the parameters I'm getting.

**Comment by raq929** [comment]
What is in your repo right now?

**Comment by treep78** [comment]
Like what is everything in my repo? To folders, front-end and back-end which have my front and back end in them. The back end is where I put the back end template and vise vera. I have both successfully deployed and running locally.

**Comment by raq929** [comment]
Ah. I think that's your problem. You should have two separate repos, one for front end, and one for backend. Heroku won't know what to do unless it's looking at the root of your rails app.

**Comment by raq929** [comment]
How's this going?

**Comment by treep78** [comment]
Haven't been home long. I'll see if I can get it a bit later.

**Comment by treep78** [comment]
That helped, but it still aborts. I says it can't compile my rails app. It says to make sure I can ```bundle exec rake -P``` which I checked and I can. Other than that I can't see where to go from here.
```
remote: -----> Detecting rake tasks
remote: sh: 2: Syntax error: Unterminated quoted string
remote: sh: 2: Syntax error: Unterminated quoted string
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     LoadError: cannot load such file -- rspec/core/rake_task
```
```

remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to mysterious-temple-83611.
remote: 
To https://git.heroku.com/mysterious-temple-83611.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/mysterious-temple-83611.git'
```

**Comment by raq929** [comment]
Can you do `heroku run bundle exec rake -P`?

**Comment by treep78** [comment]
```
~/wdi/projects/full-stack-project/back-end (master)$ heroku run bundle exec rake -P
Running bundle exec rake -P on ⬢ mysterious-temple-83611... up, run.8820 (Free)
bash: bundle: command not found
```

**Comment by treep78** [comment]
heroku run bundle install?

**Comment by treep78** [comment]
guess not

**Comment by payne-chris-r** [comment]
Come find me. Let's fix this once and for all.

**Comment by payne-chris-r** [comment]
This is not resolved yet. The error I think is here: `remote: sh: 2: Syntax error: Unterminated quoted string`
I'm not sure where the unterminated quoted string resides, but it's certainly annoying. @gaand proposed that it may be in some sort of config file (.gitignore, heroki configuration, etc). There also might be an issue with the heroku settings as well ON `heroku.com`.
The last potential issue is that @treep78 is using a `hackintosh` (a pc running Mac OSX) and there is a chance that the ruby build is wacky because of that. @raq929 found some issues with deploying to heroku from a windows machine, and I'm wondering if this may be the cause as well...

**Comment by gaand** [comment]
I'm happy to take a look tomorrow.

**Comment by treep78** [comment]
Issue resolved by update to the rails-api-template
