### ISSUE TITLE
Project starting issues

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/full-stack-project#477]
Can someone sit with me for a quick 10min to help me get started. I followed the instructions on the api template repo but I'm not sure where to start or how to link my front end and back end. I moved the template into my projects folder but I'm not sure how to change the name. And also should I create a new repo within projects for my front end? Should I copy my set up from my tic tac toe project?

**Comment by gaand** [comment]
Have you followed the directions here?

https://github.com/ga-wdi-boston/rails-heroku-setup-guide

You should have two repositories.  One for your API, one for your client.

**Comment by Sphilippe7** [comment]
ok thanks. Sorry, I forgot about that repo.
