### ISSUE TITLE
Heroku setup

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/full-stack-project#478]
I'm following the instructions listed but not seeing the correct messages in my console. I'm getting an error when trying to run ```git remote -v```

**Comment by neugierige** [comment]
what is the error?

**Comment by Sphilippe7** [comment]
it said fatal. So then I went into my rails api template repo and did it but I did not get the same response as what is shown in the example. All I see is "creating app..... done". In the guide is says I'm supposed to get back:

    heroku  git@heroku.com:agile-badlands-7658.git (fetch)
    heroku  git@heroku.com:agile-badlands-7658.git (push)
    origin  git@github.com:tdyer/wdi_4_rails_hw_tdd_hacker_news.git (fetch)
    origin  git@github.com:tdyer/wdi_4_rails_hw_tdd_hacker_news.git (push)
```

**Comment by neugierige** [comment]
1. Please paste the exact error you are getting. 
2. Did you run these 3 steps exactly:
- [ ]  Run `heroku create` in the command line in the root of your Rails API to create a new (blank) app on Heroku.
- [ ]  Push your latest code to Heroku (`git push heroku master`)
- [ ]  Tell Heroku to run your migration files (`heroku run rake db:migrate`). If you have any other rake tasks that need to run (e.g. rake db:seed), run those with heroku run as well.

**Comment by Sphilippe7** [comment]
![screen shot 2016-11-29 at 11 39 53 am](https://cloud.githubusercontent.com/assets/9563419/20719004/9818e53e-b628-11e6-87be-f3d9638dd004.png)

**Comment by neugierige** [comment]
I see that you ran `heroku create` in your wdi folder. Is that folder a git repo? No, it is not.

**Comment by neugierige** [comment]
remember, the instructions say "Run heroku create in the command line in the root of your Rails API to create a new (blank) app on Heroku." That would be the `rails-api-template` folder. But you did `cd ..` before creating the Heroku app.

**Comment by Sphilippe7** [comment]
If you look in the middle of my command line, I tried it in the rails-api-template already and got the same response @neugierige

**Comment by neugierige** [comment]
yes, that's true. So did you try the `git remote -v` command in the rails-api-template repo?

**Comment by Sphilippe7** [comment]
yes and I received "not a git repository". It is also in the screenshot that I posted

**Comment by neugierige** [comment]
Ok, so it's not a git repository. Do you know how to make it into a git repository? 

How did you create this directory in the first place? Did you fork and clone?

**Comment by neugierige** [comment]
I don't see you running that command from the `rails-api-template` folder... where do you see that? 

That error appears twice in your screen shot, once from the `wdi` folder, and once from the `wdi/projects` folder

**Comment by Sphilippe7** [comment]
Yea it shows rails-api-template (master). You should see it in the middle of the terminal

**Comment by Sphilippe7** [comment]
Never posted the ```git remote -v``` inside of the rails template. I made the mistake of running it outside of it. Thank you @neugierige
