### ISSUE TITLE
ERD and Tables Help

### ISSUE THREAD

**Issue by kmg1434** [ga-wdi-boston/full-stack-project#479]
Quick Project Description: Educational Ear Training Game App, user plays through a sequence of ear training exercises, progress is tracked along the way. Exercises are re-playable.

My ERD and tables seem to behave a bit differently than most others and I'm having a bit of trouble setting them up. Here's what I thought was obvious and what I started with:

**[ User ]** -has many-<**[ Games ]**-has many-<**[Levels]**-has many-<**[Prompts]**

Users will own Games, and be able to CRUD Games. Each Game has multiple Levels that a user plays in an ordered sequence, and each Level has a set number of Prompts for the user to respond to. 

Part of my issue is that every User will be playing the same "Game", or else it wouldn't really be fair to the Users, since hopefully they will be able to compare their statistics with other Users (look at leaderboards and such) when the app is complete. Every Game has the same Levels, and every Level has a specific set of Prompts. My main concern is that every User is navigating the same "tree", but with different statistics (wins, losses, correct guess ratio, etc) and the table layout and columns are puzzling me. If I could do a brief 1:1 with someone to help me out it'd be a huge help. Thank you.

**Comment by raq929** [comment]
Oh, I love this idea! 
So it sounds like your CRUD will be similar to tic-tac-toe's CRUD, with games. Take a look at that API and see if it clarifies things for you. If it doesn't, can you explain more about what is confusing to you about the table/column layout?

**Comment by neugierige** [comment]
I think you may be confusing some terminology here. The overarching `Game` that you have designed has these level and prompts. But users are playing a single session of the game - do I have that right? 

Can you also share your current thinking for each table's columns?

**Comment by kmg1434** [comment]
@raq929 :
What's confusing me the most is the extra layer. In tic tac toe, every game is identical. For me, I have maybe 5 different Levels with increasing difficulty. I'm not sure if I have one table for every Level, or one really long table of Levels where each User owns 5 of them. I'm just not 

@neugierige 
Yes, the overarching Game has multiple Levels, every Level has multiple Prompts. A User does play a single "session" of the Game, but I'm not exactly sure what that means.

Table Ideas:
USERS: user_id, username(text), password(text)
GAMES: game_id, user_id, five different level columns???
LEVELS: level_id, complete(boolean), win_loss_ratio(double), something to do with prompts?
PROMTS: prompt_id, completed(boolean), ???, ???

I'm not sure I understand the length of these tables. Will I have a whole separate Levels table for every Game? Or will I have 1 enormous Levels table with repeating Prompts over and over? That doesn't seem right. Same thing goes for Prompts table; will I have a huge table with every Prompt for every Level for every User in one table?

**Comment by raq929** [comment]
I thought that in your case, users are playing the same game? Or are users making their own levels and prompts that they can then share with other users?

I think you had it right in your original post. Users have many games, Games have many levels, levels have many prompts.

**Comment by neugierige** [comment]
I think your `GAME` table should have ONE column for difficulty level (i.e. a number between 1 through 5). 

I'm assuming that each level will not be exhaustive of your prompts? If so, I agree that your `PROMPT` and `LEVEL` tables can have a one-to-many relationship.

**Comment by kmg1434** [comment]
So I just went over this whole thing with Johnathan and I think we've got it covered. 

Users is going to be many-to-many with Games through a join table called Started_Games or something similar. 

USERS: user_id, username, password, win_loss_ratio
STARTED_GAMES(join table): started_games_id, user_id, game_id
GAMES: game_id, Level 1(bool), Level_2(bool), Level_3(bool), etc

I don't think I have any need to store the Prompts in the back end. I do want to store some statistics about how many attempts a user has pass/failed but I can just throw that number in the Users table since every user will only have one "master batting average".

CRUD will now be done on the Started_Games table. 

If no one comments on this issue by the end of Outcomes I'll close it.

**Comment by neugierige** [comment]
I'm not sure I agree that this would be the best solution. In the organization you described above, what would go inside the `GAMES` table? As in, what are the each individual rows inside the table?

**Comment by payne-chris-r** [comment]
Yeah, I agree with Lu that this may not be the best solution. I will probably work, but you may be making it more complex than it needs to be. I think `games` IS your join table. You have:
GAMES: game_id, user_id, five different level columns???
When I see `five different level columns???` I immediately want to push this to a `has_many` relationship where each user has many `games`, and the `games` table consists of `id`, `user_id`, `level_id`. The problem is this isn't a `game` the way we think of it. It's more like `user_levels`. My question for you that will help me give you more advice on the matter is this:
Should a user have MANY games? Should I be able to see how many new games I've played? Stats for each of those games? How fast I answer the questions? Or are they just playing the same game over and over again for practice? Can you give us some user stories around replay-ability of the game?

**Comment by kmg1434** [comment]
@neugierige 
I'm surprised I didn't see that logic flaw... I honestly don't even know what would go in the rows of the Games table at this point...

@payne-chris-r 
**Should a user have MANY games?**
Honestly... I don't know. I said yes originally so that it would satisfy CRUD, specifically the Delete action verb. I was thinking that a user could erase their record and kind of "start a new game from scratch on Level 1".

**Should I be able to see how many new games I've played?**
Yeah, sure, that should be easy. It could be cool to look back at your history and say "oh look i got a perfect score on this game attempt on every Level!" Just realized that this is a weird version of a user story, but it's a user story.

**Should I be able to see Stats for each of those games?**
I was originally thinking only a total "master batting average" being stored. Meaning how many prompts the user got correct out of the total amount of prompts they were asked over the history of the entire game... or even over all of their games?

**How fast I answer the questions?**
This was exactly a stretch goal I had, implementing some sort of timer. I don't think I'm going to worry about this yet. I'm still working on my ERD.

**Or are they just playing the same game over and over again for practice? Can you give us some user stories around replay-ability of the game?**
This app is supposed to be a linear educational game. As a user, I want to start a new game, start on level 1 and try over and over again until I complete level 1. Now level 2 is "unlocked" and I attempt the prompts from that level, etc. 

As a user, I want to be able to replay any level that I have completed, PLUS the FIRST level that I have not completed. This is very much parallel to most classic Nintendo or platformer games. The purpose for re-playing levels is for practice and to try and get a better score (ratio).

As a user, I want to be able to view a leaderboard, say Top 25 scores (win/loss ratio, fastest time would be cool, maybe some other stats) of all players.

Ok, if my Games table IS my join table. Is it joining Users to... Levels? Five different Levels? That might make sense. I'll try drawing it out.

**Comment by kmg1434** [comment]
@neugierige 
What was supposed to go in the Games rows was a user_id and a pass/fail boolean for each level, so one row would look like: 1, true, true, false, false, false if user number 1 had passed the first two levels. I'm not sure this makes sense, but it's what I had in mind, I had just forgotten.

**Comment by neugierige** [comment]
can a game be multiple levels at the same time? If you have a column for each level _per game_, that suggests that a game can be levels 1 AND 2, or that someone can play level 4 without levels 1, 2, 3. I don't think you want that. I think you want one column, with a single value for what the level is.

Why do you necessarily need a join table? Like the tic-tac-toe game, users can have many games. The one potential many-to-many relationship I see is between `level` and `prompt` - a level has many prompts, and a prompt can belong to more than 1 level - if that's what you want. If each prompt is unique to a level, then it would again be one-to-many.

**Comment by raq929** [comment]
(I would break up those user stories into much smaller components before tackling them. But the give us a good idea of where you're going.)
I would encourage you to de-scope a little at this point. Is there a way to do CRUD on the first user story, and leave the others as stretch goals? ie, I can wipe my game away to start over(D), and otherwise, I can create a game(R), update it's status(U), and log back in to see where I was (R).

I would start with allowing a user to have one game. Games have levels, and maybe a boolean field for each level like `level_one_complete?`. 
That way, you can display levels based on their completeness for that user. It's probably not the most elegant solution, but it might get the job done.

**Comment by neugierige** [comment]
To be clear, I imagine that `GAME` is a table where the data is created by users, `PROMPT` has stuff you created that we are "getting," and each `LEVEL` object is comprised of prompts, and can either be created ad hoc (randomly, as a game is created), or pre-determined by you.

**Comment by kmg1434** [comment]
@neugierige 
**can a game be multiple levels at the same time?**
A Game HAS multiple levels, I don't know what you mean by asking if "it can be multiple levels". 
I'm also not going to worry about "unlocking levels" at this point. I'm no where close to there yet, so I don't thing the order or accessibility of the Levels matters at this point.

**Why do you necessarily need a join table?** I don't think I do, I originally didn't, I've gone back and forth now and I didn't mean to imply that I thought either way.

There is certainly a many-to-many relationship between Levels and Prompts but I'm not sure I even need a Prompts table in the back end at all, unless I wanted to go deep into statistics (not a requirement).

@raq929 
**Is there a way to do CRUD on the first user story, and leave the others as stretch goals?**
I believe I can do CRUD on Game, but I no longer even know what a Game is anymore. Is it just a join table now? I've written out about 5 different ERDs but none of them seem complete.

**I would start with allowing a user to have one game. Games have levels, and maybe a boolean field for each level like level_one_complete?**
This is exactly what I had! Chris thought it was a bad idea though? And that this should introduce a has_many relationship with a Levels table that holds the booleans?

Could I please "pen and paper" this out with someone? I'm almost more lost than I was when I opened the issue.

**Comment by neugierige** [comment]
I'd be happy to chat at 4pm if you'd like. Sometimes things do get messy before they clean up...

**Comment by kmg1434** [comment]
Okay, I think we're kicked out of the lounge, where should we meet?

**Comment by kmg1434** [comment]
So I think I figured this all out. Most of my confusion was coming from the difference between the data held in a table and the data held in an object in the front end. I am much much more familiar with the latter. Anyways, here are my tables and columns now:

Users: id, username(text), password(text),email(text)
Games: id, level_id, user_id
Levels: id, prompt1(bool), prompt2(bool), prompt3(bool), prompt4, etc

These prompt booleans will be true if the user responded to them correctly.

Users have many Games, and can CRUD on Games, which is effectively a join-table between Users and Levels. Every row in Games will refer to ONE level_id. If there are 5 total levels, a user will need at least 5 rows in Games to complete the progress in the app.

**Comment by kmg1434** [comment]
So I might have misunderstood my own ERD. I still have the same 3 tables with the same columns BUT:

If Games is a join table between Users and Levels I would say "A User has many Levels THROUGH Games" and "A Level has many Users through Games". This means that my CRUD is all going to be on Levels and NOT Games, since Games is a join table? 

**[Users]**-<**[Games]**-**[Levels]** is what I had but I think I need:
**[Users]**-<**[Games]**>-**[Levels]**

So when a User starts to play the app they are going to pick a Level they wish to play, which will be referenced through Games. Am I right in thinking that CRUD will be on Levels and not Games?

**Comment by neugierige** [comment]
I think you want Game as your join table. The user should not have a direct relationship with levels. Level is a property of a Game, not a User. And a User should not be able to access a Level without a Game, right? 

It's like the Loans between Books and Borrowers - a Book does not and should not know about a Borrower unless there is a Loan.

**Comment by kmg1434** [comment]
Yes this is exactly what I was thinking in my head, maybe I didn't explain it well enough above. That's what I meant by "A User has many Levels through Games" and "A Level has many Users through Games". 

I'm confused as to whether or not I'll be CRUDing on Games or Levels.

**Comment by neugierige** [comment]
So in the comparison with Books and Loans, Borrowers is functionality equivalent to your Users. Borrowers only know about Loans, they can't perform any changes on Books. 

If your User is able to CRUD on Levels...they would be able to change the existence of Levels (via create/delete), and the content of what's in them (via update). And because all your users are interacting with the same content, one user could then alter another user's experience.  Is that what you want?

A User's Games, on the other hand, belong to that user, and they can perform changes on them as they like. A Game object will have information about what level it is, but it has no effect on the actual Level itself.

**Comment by kmg1434** [comment]
After a quick satisfying chat with Lu (who has had a lot of patients with me, thank you so much!) I am totally erasing my Levels table. NEW ERD:

**[Users]**-has_many-**[Games]**

Users Table Columns: id, email, password
Games Table Columns: id, user_id, level(integer), score(double)

Score will just be (correct answers) / (number of prompts in the level), so it'll be a ratio calculated in the front end, and sent to the Games table on an Update AJAX request. If there are other stats I want to store later I can always add a column to the games table and change my Update AJAX request json format.
