### ISSUE TITLE
git push does not work for many branches

### ISSUE THREAD

**Issue by HoldenMills** [ga-wdi-boston/full-stack-project#48]
I have been making many commits, but I forgot to push. When I run git push -u origin database it says origin is not a database.

**Comment by HoldenMills** [comment]
git push -u origin controller
error: src refspec controller does not match any.
error: failed to push some refs to 'origin'

**Comment by srhoulam** [comment]
You do not have a remote repo to push to. This is remedied by creating an empty repo on github and running the following command from your local repo:

``` bash
git remote add origin <ssh link for github repo>
```

**Comment by HoldenMills** [comment]
-bash: syntax error near unexpected token `newline'
