### ISSUE TITLE
Trouble Visualizing Workflow

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/full-stack-project#480]
I feel like I keep pigeon holing myself. No matter what I work on I feel like it isn't working

**Comment by neugierige** [comment]
how would you like your workflow to be?

**Comment by raq929** [comment]
That's a frustrating feeling. Do you have user stories and acceptance criteria? 
I often find when I'm stuck, breaking my user stories or acceptance criteria into smaller steps helps a lot.
