### ISSUE TITLE
Heroku or No Heroku

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/full-stack-project#481]
So I spent a better part of today trying to get Heroku to work before finally getting it before lunch. While struggling with it, I asked Suja to help me just create two repo's with my project folder. She helped me clone both the browser template and the rails api template for the front and back ends. Everything is fine and within the right place. Can't I just work through them and get further in my project then come back to this heroku process? Do I actually NEED heroku?

**Comment by neugierige** [comment]
Do you remember when you did the game project, and we told you how important it was to deploy it? And to make sure that deployment worked? I think this is the equivalent. It's much better to get heroku working 1st, rather than to do this (and run into the same problems) last minute.

**Comment by BenGitsCode** [comment]
You NEED heroku to deploy your application, and it needs to be deployed for presenting.

As Lu said, it's highly encouraged to get deployed at least a few times before the final hour—that said, you can develop locally and test locally, and take a break from heroku in the meantime if you've spent too much time on it. BUT, be sure to come back to it soon. 

The issue tracker will only fill with helpful deployment experiences to learn from as time passes.

**Comment by Sphilippe7** [comment]
Yes you are right @neugierige

**Comment by Sphilippe7** [comment]
Ok I think I will do that. I just felt that I was spending too much time on it instead of my actual project code @BenGitsCode

**Comment by Sphilippe7** [comment]
Thank you
