### ISSUE TITLE
trouble with getFormFields - form comes back undefined

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/full-stack-project#484]
here's the code I'm using to call getFormFields

```js
const createMed = (e) => {
  e.preventDefault();
  debugger;
  let data = getFormFields(this);
  api.create(data)
  .then(ui.createMedSuccess)
  .catch(ui.failure);
};

const addMedHandlers = () => {
  $('#show-meds-btn').on('click', indexMeds);
  $('.create-med-form').on('submit', createMed);
};
```

the getFormFields(this) call throws an error, saying that the variable 'form' is undefined, but when I make the same call in the console at the debugger above, it brings back the object I was expecting. Any idea why the data isnt reaching getFormFields? From what I can tell, it looks identical to the auth getFormFields calls which are working correctly...

**Comment by neugierige** [comment]
where is the variable `form` defined? can you share that code?

**Comment by ioncrash** [comment]
it's part of the getFormFields function which we were given. Here's the snippet that's throwing the error:

```
const getFormFields = (form) => {
  let target = {};

  let elements = form.elements || [];
  for (let i = 0; i < elements.length; i++) {
    let e = elements[i];
    if (!e.hasAttribute('name')) {
      continue;
    }
```

**Comment by raq929** [comment]
What is `this` referring to in your code? If you look at code from your last project, what does it usually refer to when you use `getFormFields`?

**Comment by ioncrash** [comment]
As I understand it, `this` refers to the html form element that I'm clicking `submit` on. If I call `this` in the debugger right before that getFormFields call, it returns the html for the modal form. And it looks like getFormFields goes through that html and pulls the user data into an Object. Seems to do similar things for both auth functions (which are working), and med functions (which aren't working).

**Comment by ioncrash** [comment]
well, I don't know why, but it seems to have helped to switch from the arrow function `createMed` to the long-hand:

```
const createMed = function(e) {
  e.preventDefault();
  let data = getFormFields(this);
  api.create(data)
  .then(ui.createMedSuccess)
  .catch(ui.failure);
};
```

Would be interested to know why it doesn't like the arrow function, but hey! It works now! Thank you!

**Comment by raq929** [comment]
Because the arrow function doesn't create it's own scope. So `this` doesn't point to the same thing when you use an arrow function.
