### ISSUE TITLE
Not Sure How to get PATCH working from front end

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/full-stack-project#485]
Sort of the same story as earlier. I have total CRUD functionality using curl requests and rails console when it comes to updating data, but I am not sure how to process this on the front end. I know it needs to be through an ajax call but I don't know how to append the applicable chore id onto the chore URL

**Comment by raq929** [comment]
I would take a look at the working code from your tic-tac-toe project. How did you append the correct id there? 
(Are you storing the chore id when you make a get request?)
Take it one step at a time.

**Comment by akradin** [comment]
I looked at that code for reference and it makes sense in that context. When the user clicks on the board, the board is updated. There is only one thing that can happen. 

Maybe I am making it more complicated but instead of clicking on a cell, now you have a whole list of chores to chose from so it cant be just `store.id` because there are multiple ids. I guess ideally the user would be able to input the ID of the chore they want to change. But I don't know how to make that happen either

**Comment by payne-chris-r** [comment]
How do users input data for signing in?

**Comment by akradin** [comment]
Via a form and a submit button. I have both. I think it is just the ajax call I am struggling with

**Comment by raq929** [comment]
I think you should find a way to store the id of your chores, so that you can get the id again when someone clicks on one. Look into the data-* attribute in HTML.

**Comment by neugierige** [comment]
wait, why can't you get a specific id from the chore that the user clicks on? if each chore is its own div or row, isn't that very similar to the boxes in tic-tac-toe?

**Comment by akradin** [comment]
The chores aren't clickable, good idea though. Maybe that is my solution.

**Comment by akradin** [comment]
Actually, now that I mention it. Since deploying to heroku now when I submit a chore it no longer shows up in the html at all. So everything is falling apart. 

I am going to focus on getting CRUD actions to happen before getting to see them. 

Rachel, I looked into data-* and I don't understand how it works. It seems like the in this instance it would be `data-id` but I am not sure how it is relevant to what I am trying to do

**Comment by akradin** [comment]
To be honest, I think I have confused myself into oblivion and I am 99%  certain I will get no more work done tonight. I would really appreciate being able to talk to someone in person about this.

**Comment by raq929** [comment]
Things break when you deploy sometimes. That's OK. That's why we tell you to deploy early.
I think you're right, data-id is a good idea. You can use that to store the id in the html, and then you can use jQuery to get it out again when you need to send it to the server.

**Comment by raq929** [comment]
If you start feeling like everything is going wrong, it's a good time to take a break.

**Comment by akradin** [comment]
Alright, so I took the T home and feel a bit better. Don't we set data attributes to a specific value? Or are they set on creation. For example, I create a chore and that chore then has a the data-id attribute that is set to its id on creation, then I could do data.id in my ajax call. I just dont see how I would make that happen. Maybe I am totally misunderstanding how they work

**Comment by payne-chris-r** [comment]
The best thing you've said all day:
'I am going to focus on getting CRUD actions to happen before getting to see them.'
Try hard coding things. Remember one step at a time. Make sure that little change works. Move on.

**Comment by raq929** [comment]
I think the last section of this documentation (the .data(key)) part is the most helpful. 
https://api.jquery.com/data/
I second what Chris said about one step at a time. And if the step seems overwhelming, make it smaller. Hard code an id in your api call first. If that works, then you can worry about how to get the data.

**Comment by raq929** [comment]
What have you tried so far to get this working? Can you post some code/errors?

**Comment by akradin** [comment]
All I have really tried so far is manually putting the ID of whatever chore I would update into the AJAX call. For example:
```js
const updateChore = (data) =>
  $.ajax({
      url: config.host + '/chores/' + 1,
      method: 'PATCH',
      data,
    });
```

And this works. When I update the first chore in the front end, the changes are put in place. I guess Ideally the user would be able to put in that ID as well

**Comment by raq929** [comment]
Awesome! So, you have a lot working: a click handler, an api call, etc. All you need now is a way to store data and get it back when you need it.
Why don't you try using the data-* html element and see what you can do with it. (You can hard-code the id in at first, and then switch to putting it in when you load the data.)
Does that make sense?

**Comment by akradin** [comment]
Uhh sort of? So for simplicity's sake (and definitely not the user's sake) you can see the ID of the chore. So I just have it now so you input the ID and then the edit to the chore is made. the code looks like this 

```html
      <form class="chore-update">

        <input type="text" placeholder="chore id" name="chore[chore_id]">
        <input type="text" placeholder="chore" name="chore[name]">
        <input type="text" placeholder="due date" name="chore[due_date]">
        <input type="text" placeholder="Difficulty, 1-5" name="chore[difficulty]">
        <input type="submit" value="Update" id="chore-update">
      </form>
```

and `updateChore` function:
```js
const onUpdateChore = function (event) {
  event.preventDefault();
  let data = getFormFields(this);
  api.updateChore(data)
    .then(ui.updateSuccess)
    .catch(ui.failure);
```

and the AJAX call:
```js
const updateChore = (data) =>
  $.ajax({
      url: config.host + '/chores/' + data.chore.chore_id,
      method: 'PATCH',
      data,
    });
```
