### ISSUE TITLE
index method still showing all data, not just that of current user

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/full-stack-project#487]
alright, I'll bite -- how the heck does current_user work? I'm pretty sure I accurately copied and adapted examplesController into my medsController (it inherits from ProtectedController), and I tried messing around with user_serializer and user_login_serializer based on some stuff google said, but it doesn't seem to help... feel like I'm just thrashing around in the dark here, trying random commands. 

Is anyone available for a one-on-one tomorrow?

**Comment by raq929** [comment]
So, from looking at the ApplicationController (which ProtectedController inherits from), it looks like the set_current_user function checks if a user is authenticated, and sets the variable @current_user to the authenticated user. There's an attr_reader in there that means there's a getter for current_user on any instance of the ApplicationController class.
So, any classes that inherit from the ApplicationController (which is likely all of your controllers) have access to the current user.  

What is it that you're trying to do?

**Comment by ioncrash** [comment]
um, well I was trying to get it so that my meds#index would only return the meds owned by the current user... I was trying to add some code to the meds_serializer to make this happen, or some kind of special built in rails thingy... and then I solved it by adding some ruby to the index method like so:

```
def index
    @meds = Med.where(:user_id => current_user.id)

    render json: @meds
  end
```

don't overthink things, I guess :D
