### ISSUE TITLE
JS - not loading document ready function

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/full-stack-project#488]
I have been trying to get sign in of auth to work( no auth currently working), upon putting debuggers in multiple places, and finally tracing all the way back to the document ready as in here, the debugger doesn't show. SO there's no way that my sign in functions can work.
Here is the code in index.js 
```js
$(() => {
  debugger;
  authEvents.addHandlers();


});
```

**Comment by BenGitsCode** [comment]
Can I see the `<head>` of your html?

**Comment by raq929** [comment]
Yeah, check out the solution to #483

**Comment by jbuzzanco** [comment]
resolved. didn't have the js files in the correct path. webpack hated that. server wasn't updating upon changes. so put the js files in scripts folder instead of one step back.
