### ISSUE TITLE
CSS being overridden by dependencies.js/bundle.js

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/full-stack-project#489]
If I load both dependicies/bundle and my CSS my app displays only part of the CSS. How do I get them to coexist peacefully?

**Comment by raq929** [comment]
Is it your css or bootstrap css?

**Comment by gaand** [comment]
You want to use `styles/index.scss` to load your css.

**Comment by kiraamaa** [comment]
Bootstrap CSS... Adding the reference 
```
<link href="assets/styles/css/bootstrap.min.css" rel="stylesheet">
``` 
didn't change anything

**Comment by raq929** [comment]
Right, you need to require your bootstrap css in `styles/index.css`

**Comment by kiraamaa** [comment]
Do I use an actual require statement?

This is inside my index.scss file right now:
```
$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import '~bootstrap-sass/assets/stylesheets/bootstrap';
```

**Comment by raq929** [comment]
No, import should work. What happens with that? Is there an error?
Also, have you uncommented all the things in the html that we commented out when we were trying to figure out your click handler?

**Comment by kiraamaa** [comment]
There isn't an error with import, that part has no issues. I did uncomment everything out so that the app shows all my Bootstrap edits IF and only if the links to dependencies and bundle are commented out.

**Comment by raq929** [comment]
So, did you edit the bootstrap css, or just the HTML? 
Can you post all of the links in your html, as well as your whole `styles/index.scss` file?

**Comment by kiraamaa** [comment]
I'm not sure what you mean. I didn't edit the Bootstrap CSS at all, and only added the link to the Boostrap CSS into the head of my HTML. The Bootstrap CSS looks good when dependencies and bundle are not linked in my HTML, and my HTML looks the same regardless. 

``` html
<!-- Bootstrap core CSS -->
   <link href="assets/styles/index.scss" rel="stylesheet">
   <link href="assets/styles/css/bootstrap.min.css" rel="stylesheet">


   <!-- Custom Google Web Font -->
   <link href="assets/styles/font-awesome/css/font-awesome.min.css" rel="stylesheet">
   <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
 <link href='http://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>


   <!-- Custom CSS-->
   <link href="assets/styles/css/general.css" rel="stylesheet">

  <!-- Owl-Carousel -->
 <link href="assets/styles/css/custom.css" rel="stylesheet">
 <link href="assets/styles/css/owl.carousel.css" rel="stylesheet">
 <link href="assets/styles/css/owl.theme.css" rel="stylesheet">
 <link href="assets/styles/css/style.css" rel="stylesheet">
 <link href="assets/styles/css/animate.css" rel="stylesheet">

 <!-- Magnific Popup core CSS file -->
 <link rel="stylesheet" href="assets/styles/css/magnific-popup.css">

 <script src="assets/styles/js/modernizr-2.8.3.min.js"></script>  <!-- Modernizr /-->
 <!--[if IE 9]>
   <script src="js/PIE_IE9.js"></script>
 <![endif]-->
 <!--[if lt IE 9]>
   <script src="js/PIE_IE678.js"></script>
 <![endif]-->

 <!--[if lt IE 9]>
   <script src="js/html5shiv.js"></script>
 <![endif]-->
 <script src="dependencies.js" type="text/javascript" charset="utf-8" defer></script>
 <script src="bundle.js" type="text/javascript" charset="utf-8" defer></script>
```

**Comment by kiraamaa** [comment]
This is my entire ``` styles/index.scss``` file:
``` scss
$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import '~bootstrap-sass/assets/stylesheets/bootstrap';
```

**Comment by raq929** [comment]
@gaand do you have any input on this?

**Comment by gaand** [comment]
Yes.

**Comment by gaand** [comment]
The template in question includes all of bootstrap and you probably only want the parts that were added by the author.

**Comment by kiraamaa** [comment]
Discussed with Antony, will attempt to cobble together custom css/find a node module that corresponds to my Bootstrap template if I have the time at the end.
