### ISSUE TITLE
Curious how to test my join table

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/full-stack-project#49]
Modeled it after the many through movies controller to set my join table controller but curious

```
class BeersController < OpenReadController
before_action :set_beer, only: [:update, :destroy]

  # GET /beers
  def index
    @beer_choices = Location.beer_choices

    render json: @beer_choices
  end

  # GET /beers/1
  def show
    @beer_choices = Location.find(params[:id])

    render json: @beer_choices
  end

  # POST /beers
  def create
    @beer = current_user.beers_choices.new(beer_choices_params)
    @beer_choices.save

    if @beer_choices.save
      render json: @beer_choices, status: :created, location: @beer_choices
    else
      render json: @beer_choices.errors, status: :unprocessable_entity
    end
  end

  # PATCH /beers/1
  def update
    if @beer_choices.update(beer_choices_params)
      head :no_content
    else
      render json: @beer_choices.errors, status: :unprocessable_entity
    end
  end

  # DELETE /beers/1
  def destroy
    @beer_choices.destroy

    head :no_content
  end

  def set_beer_choices
    @beer_choices = current_user.location.find(params[:id])
  end

  def beer_params
    params.require(:beer_choices).permit(:location_id, :beer_id)
  end

  private :set_beer_choices, :beer_params_choices
end

end
```

**Comment by jcmeyer10** [comment]
This feels like it's the right response:

[10] pry(main)> l1 = Location.first
  Location Load (0.5ms)  SELECT  "locations".\* FROM "locations"  ORDER BY "locations"."id" ASC LIMIT 1
=> #<Location:0x007ffa8bd4d388
 id: 1,
 name: "Location_0",
 street_num: 0,
 street: "Elm",
 city: "Boston",
 state: "MA",
 created_at: Wed, 11 Nov 2015 16:02:09 UTC +00:00,
 updated_at: Wed, 11 Nov 2015 16:02:09 UTC +00:00,
 user_id: nil>
[11] pry(main)> l1.beers.all
  Beer Load (0.5ms)  SELECT "beers".\* FROM "beers" INNER JOIN "beer_choices" ON "beers"."id" = "beer_choices"."beer_id" WHERE "beer_choices"."location_id" = $1  [["location_id", 1]]
=> [#<Beer:0x007ffa8bcb5e70
  id: 1,
  name: "Boston Lager",
  brewery: "Sam Adams",
  style: "Vienna Lager",
  created_at: Wed, 11 Nov 2015 16:02:09 UTC +00:00,
  updated_at: Wed, 11 Nov 2015 16:02:09 UTC +00:00,
  user_id: nil>,
 #<Beer:0x007ffa8bcb5b50
  id: 7,
  name: "Grolsh",
  brewery: nil,
  style: nil,
  created_at: Wed, 11 Nov 2015 16:02:09 UTC +00:00,
  updated_at: Wed, 11 Nov 2015 16:02:09 UTC +00:00,
  user_id: nil>,
 #<Beer:0x007ffa8bcb5808
  id: 8,
  name: "Heineken",
  brewery: nil,
  style: nil,
  created_at: Wed, 11 Nov 2015 16:02:09 UTC +00:00,
:

**Comment by GA-MEB** [comment]
When you manipulate the models in `rails c`, do the tables show the expected result when you look at them in `rails db`?

**Comment by jcmeyer10** [comment]
No :(

**Comment by GA-MEB** [comment]
Missing migration files to link the different tables, `beers`, `beer_choices`, `locations`.
