### ISSUE TITLE
Table problem

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/full-stack-project#490]
I made the mistake of only adding Month, rating, and category to my model. I tried to go back and enter in title because I need to have the title of my games and got a conflict message

**Comment by Sphilippe7** [comment]
in my console

**Comment by neugierige** [comment]
Can you share the conflict message?

As a general rule, always include the error itself.

**Comment by Sphilippe7** [comment]
conflict db/migrate/20161130152646_create_games.rb
Another migration is already named create_games: /Users/stanleyphilippe/wdi/projects/full-stack-project/YOG-Back-End/db/migrate/20161130151713_create_games.rb. Use --force to replace this migration or --skip to ignore conflicted file.

**Comment by neugierige** [comment]
ok, so you have already run a migration called "create_games," which means it can't run another migration for creating a games table. But what you are trying to accomplish is to add a column into your table, not to create a new table, right?

**Comment by Sphilippe7** [comment]
yes.

**Comment by neugierige** [comment]
https://lmgtfy.com/?q=rails+add+column+to+table

**Comment by Sphilippe7** [comment]
lol thanks @neugierige
