### ISSUE TITLE
Connecting back end and front end

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/full-stack-project#492]
I'm a little confused as to where do I go from here after I've created a simple api to start out with. I want to connect the api to my front end and see if things work on my page through the console. How do I go about doing this?

**Comment by neugierige** [comment]
I believe it was Alex who asked this question in class last week, during the Rails many-to-many talk. 

Think back to your tic-tac-toe project. In that project, we had an API that was available for your use. You connected that API to your front-end. Do you remember how you did that? Take a look at that project again.

**Comment by Sphilippe7** [comment]
Oh Ok I'll refer back to the project.
