### ISSUE TITLE
Re-Clicking Modals

### ISSUE THREAD

**Issue by kmg1434** [ga-wdi-boston/full-stack-project#494]
My auth currently is fully functioning from front to back, but I'm having some HTML/Bootstrap issues with the modals.

"As a user, I wish to be able to Sign In, then Sign Out, then Sign In again" is the story I'm working on, I suppose.

Any SECOND time a modal is called, it shows up for a fraction of a second, then disappears, and my whole webpage is greyed out so I cannot click anything. 

Here's the relevant chunk of my auth/ui.js file:
```
const hideModals = () => {
  $('#sign-up-modal').modal('hide');
  $('#sign-in-modal').modal('hide');
  $('#sign-out-modal').modal('hide');
  $('#change-password-modal').modal('hide');
  $('.modal-backdrop').remove();
};

const signInSuccess = (data) => {
  vault.user = data.user; 
  hideModals();
};
```

signInSuccess() is called by my onSignIn() function in auth/events.js which is the same old jazz:
```
const onSignIn = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.signIn(data)
  .then(ui.signInSuccess)
  .catch(ui.failure);
};
```

index.html Sign In Modal:
```
      <!-- Sign In Modal -->
      <div class="modal fade" id="sign-in-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="sign-in-label">Sign In</h4>
            </div>
            <div class="modal-body">

                <!-- Form Fields -->
                <form class="sign-in-form">
                  <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" name="credentials[email]" class="form-control" id="email-input" placeholder="Email">
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="credentials[password]" class="form-control" id="password-input" placeholder="Password">
                  </div>
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
          </div>
        </div>
      </div>

      <!-- Sign Out Modal -->
      <div class="modal fade" id="sign-out-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="sign-out-label">Are you sure you wish to sign out?</h4>
            </div>
            <div class="modal-body">

                <!-- Form Fields -->
                <form class="sign-out-form">
                  <button type="submit" class="btn btn-primary">Yes</button>
                  <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                </form>
            </div>
          </div>
        </div>
      </div>
```

I think part of my issue is that I am never calling ```$('sign-in-modal').modal('show');``` anywhere, but this functionality seems already written into bootstrap, since I didn't do a .modal('show') in my tic-tac-toe app either and all of those modals worked just fine.

**Comment by raq929** [comment]
Is there an error in the console?
What happens if you use jQuery's `.hide` method instead of `.modal`?

**Comment by kmg1434** [comment]
@raq929 
There is no error in the console, my whole screen is just grayed out like the background of a modal... but the modal only flashes for a second.

**What happens if you use jQuery's .hide method instead of .modal?**

So I switched my auth/ui.js to:
```
const hideModals = () => {
  $('#sign-up-modal').hide();
  $('#sign-in-modal').hide();
  $('#sign-out-modal').hide();
  $('#change-password-modal').hide();
  $('.modal-backdrop').remove();
};
```
And now it only works every OTHER time I click the "Sign In" button... better than before, but not great, I'd say that's a user facing bug.

**Comment by raq929** [comment]
🐛 
What is '.modal-backdrop'?

**Comment by raq929** [comment]
This doesn't seem like it would be relevant, but all these modals have `aria-labelledby='myModalLabel'`. Does changing those make any difference?
Also, did you use similar modals in your tic-tac-toe project? How are these different?

**Comment by kmg1434** [comment]
**What is '.modal-backdrop'?**
It's quite literally the backdrop of the modal. It's the greyed out overlay I'm talking about that doesn't let you click on anything until it is gone. Since I can't get it to go away, my app is frozen.

**Also, did you use similar modals in your tic-tac-toe project? How are these different?**
I am using the exact same modals that are fully functional in my tic-tac-toe project. For whatever reason the backdrop wouldn't go away after I clicked submit, just the modal would go away, leaving me with a frozen interface.

Changing and removing ```aria-labelledby='myModalLabel'``` seemingly did nothing.

**Comment by raq929** [comment]
I can come take a look at it around 3. Keep working on other things until then, with double-clicking. =/

**Comment by kmg1434** [comment]
I'm just working on backend stuff in the meantime. I'll be in the same spot at 3, thanks.

**Comment by BenGitsCode** [comment]
I would look at the bootstrap button [documentation](http://getbootstrap.com/css/#buttons) and this [stackoverflow](http://stackoverflow.com/questions/23443579/how-to-stop-buttons-from-staying-depressed-with-bootstrap-3) may help as well.

**Comment by raq929** [comment]
What's your status on this @kmg1434?

**Comment by kmg1434** [comment]
No luck. I have a temporary solution that will let me keep writing code elsewhere but I still have to double click all of my buttons:

```
const hideModals = () => {
  $('#sign-up-modal').hide();
  $('#sign-in-modal').hide();
  $('#sign-out-modal').hide();
  $('#change-password-modal').hide();
  $('.modal-backdrop').remove();
};
```

This is certainly a user facing bug, but I'm going to move on to other issues I'm having with back end deployment.

**Comment by raq929** [comment]
I think we also discovered that the buttons are not losing focus after a click - they remain highlighted as if the user were still clicking on them.

**Comment by kmg1434** [comment]
Yes, this is correct, I have found no way to remove focus on the buttons yet.

**Comment by neugierige** [comment]
@kmg1434 have you seen this?/is this relevant? 
http://stackoverflow.com/questions/3861307/jqueryui-button-remains-pressed-after-opening-ui-dialog-with-it-in-firefox

**Comment by kmg1434** [comment]
@neugierige 
I had not seen that specific thread, but many of those suggested solutions I had seen elsewhere and tried to no avail. I hadn't seen this one before though:

```
button.click(function() {
    button.removeClass("ui-state-focus ui-state-hover");
}
```

So I'll try that when I have the time and report back. For now I'll be working on my backend functionality which is much more important to me at the moment.

**Comment by payne-chris-r** [comment]
Any update @kmg1434 ?

**Comment by kmg1434** [comment]
Nope, haven't touched it since I'm not done with CRUD yet. Got my U and D to do and then a ton of front end logic. Sorry but this issue might be open for a long time.

**Comment by payne-chris-r** [comment]
That's totally fine. Just making sure you aren't thrashing on it. Keep up the work to meet requirements, then come find this issue.

**Comment by kmg1434** [comment]
So I am at the point where my nav buttons only work on the odd numbered clicks (1, 3, 5, etc) but there are no other modal issues. Is this considered a user-facing bug? It was not mentioned in my "does not meet requirements" email. I have no idea how to fix this.

**Comment by kmg1434** [comment]
Ok, now that I've removed the Bootstrap template 

```$('<modal name>').modal('hide');```

works for everything! woo!
