### ISSUE TITLE
jQuery Datepicker Not working

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/full-stack-project#496]
I would like to be able to use jQuery Datepicker (https://jqueryui.com/datepicker/) but it appears to not play nice with `dependencies.js` and `bundle.js`. There are some articles online on how to potentially fix this, and while I am okay with breaking my own code, I am not really sure how these two files work.

**Comment by neugierige** [comment]
what is the error you are getting?

**Comment by raq929** [comment]
I think this is a stretch goal that you should work on after your requirements have been met.

**Comment by akradin** [comment]
👍
