### ISSUE TITLE
ERD-could someone see if it is represented correctly for this approach

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/full-stack-project#497]
was wondering if someone could take a look at my erd as it is recommended in the full-stack project repo to see if I am representing tables and such correctly and just to see if my approach to create these entities is reasonable.

**Comment by neugierige** [comment]
Have you written/drawn it out? could you post an image/link to image of your ERD?

**Comment by jbuzzanco** [comment]
Yes I just updated my representation on paper. I will take a picture and post it.

**Comment by jbuzzanco** [comment]
http://imgur.com/0ggIydA

**Comment by neugierige** [comment]
I'm not sure what is meant by those arrows between Users and Quotes, but I'm guessing that `Quote` is the resource that your users can CRUD on? 

What are your user stories? What are the main functionalities of your app?

**Comment by jbuzzanco** [comment]
Here are some of my user stories
- as a user, I want to read and look at other people’s quotes
- as a user, I want to be able to post a quote.
- as a user, I want to be able to delete a quote.

- as a user, I want to be able to vote for ones that I like best
- as a user, I want to be able to click a plus button to state my opinion on something.
- as a user, when I like something, my opinion will add to the likes on that particular content

**Comment by jbuzzanco** [comment]
So a user has many quotes, a quote has one author (the user).
Maybe I should just start with having users being able to see other quotes and post/delete their quotes, and that would meet requirements I believe. THen once that is accomplished i could have a third table, likes. So user---likes---quotes. Kind of like the meeting point between doctors and patients is appointments?

**Comment by neugierige** [comment]
I like how you're thinking, Joel.

You should absolutely just start with users and quotes, and have users be able to CRUD on them. And the `likes` join table sounds like a good plan!

**Comment by jbuzzanco** [comment]
Ok 😃  
To approach this data structure would it make sense to generate two different scaffolds with the appropriate attributes associated or is that not really the right direction? trying to follow this api we did in class , although near the end it says to recommend using scaffolding instead of doing it by hand https://github.com/ga-wdi-boston/rails-api-library-demo#a-note-on-best-practices.

**Comment by neugierige** [comment]
Yes, you can and should use scaffold for your resources. However, have you looked at what's included in the rails api template?

**Comment by jbuzzanco** [comment]
Ok cool 😃 .
Yes, well there are controllers , models and serializers but not specific to quotes. Is what you are leading towards is that there are already user models, controllers and serializers . Just not exactly tailored to my project, and that I could modify these files?

**Comment by neugierige** [comment]
🎉 

(Yes, but with caution. Make a branch.)

**Comment by jbuzzanco** [comment]
also I was looking at ruby on rails docs to try and follow their guides. At step 6 it talks about migration commands. But it goes into erb in 6.2. DO you think it is a good idea to follow this explicitly. http://guides.rubyonrails.org/v3.2.8/getting_started.html

**Comment by jbuzzanco** [comment]
should I put this part above in a separate issue?
