### ISSUE TITLE
API Troubles

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/full-stack-project#499]
having a really hard time connecting the API and getting things to work. The user modals seem to work just fine but when I hit submit on the side of platform modals, it does not work. I did not get an error, it seems to just reload the page.
![screen shot 2016-11-30 at 2 31 33 pm](https://cloud.githubusercontent.com/assets/9563419/20767841/bd4aaa40-b709-11e6-8b5e-ac38049c49d7.png)

**Comment by neugierige** [comment]
so what's your code for sending a request to your API?

**Comment by Sphilippe7** [comment]
```'use strict';

const getFormFields = require(`../../../lib/get-form-fields`);
const api = require('./api');
const ui = require('./ui');


const getinfo = function (event) {
  event.preventDefault();
  console.log('chose month');
  // api.getinfo()
  //   .then(ui.success)
  //   .catch(ui.failure);
};


const addHandlers = () => {
  $('.select-month-form').on('submit', getinfo);
};

module.exports = {
  addHandlers,
};
```

**Comment by neugierige** [comment]
what is `api.getinfo()`? and why is it commented out?

**Comment by Sphilippe7** [comment]
I was trying to write it identical to my other events file but when I realized that modal problem I had, I commented it out to see what was the problem.

**Comment by neugierige** [comment]
so what is `api.getinfo()`? please share the code

**Comment by Sphilippe7** [comment]
well "get info" was the rout I was going to try and give the model a function. After clicking month, you get a window that ask you to type in the month of your search. After typing in a month and hitting submit, it reloads the page

**Comment by Sphilippe7** [comment]
no luck after checking over my html

**Comment by neugierige** [comment]
let me take a look

**Comment by Sphilippe7** [comment]
I made progress. My page does not reload anymore but I get an error. What I did was change my index.js file. The portion that contains "On Document ready" did not have the folder which contains the events.js file for my game folder. (which I called YOG)
![screen shot 2016-11-30 at 4 50 11 pm](https://cloud.githubusercontent.com/assets/9563419/20772828/178d9586-b71d-11e6-8ab3-dbb02be0700f.png)

**Comment by Sphilippe7** [comment]
So now my error is this: 
![screen shot 2016-11-30 at 4 50 45 pm](https://cloud.githubusercontent.com/assets/9563419/20772853/3bfdb07c-b71d-11e6-946e-da336e6ed607.png)

**Comment by raq929** [comment]
So, looks like you're trying to send a request to 'games/:some-game-id'. Is that what you want?

**Comment by raq929** [comment]
Do you have a working CURL request that does what you're trying to do? That's the first step, before hooking up the front end.

**Comment by Sphilippe7** [comment]
ok. I'm going to try and do that now, I just got home so sorry for the late reponse @raq929
