### ISSUE TITLE
Why are certain DOM elements are showing, when they should be hidden?

### ISSUE THREAD

**Issue by cwcrane** [ga-wdi-boston/full-stack-project#5]
I am having trouble controlling what is hidden and what is showing in my app. I have a ux.js file for controlling the state of the page view and determine which elects are hidden. But for some reason certain elects are not hiding when they should be. 

I have tried changing the order in which I load my scripts. And I have tried putting a couple js functions in a $(document).ready wrapper. But ca't figure it out. 

Thanks!

**Comment by srhoulam** [comment]
Solved by putting call to a DOM-manipulating function inside the callback to a `$(document).ready` call.

**Comment by srhoulam** [comment]
Chris also needed some guidance in separating his front-end concerns. All done now.
