### ISSUE TITLE
adding search/query functionality in a controller

### ISSUE THREAD

**Issue by baz1389** [ga-wdi-boston/full-stack-project#50]
I'm entering a word into a searchbar and based on what word I enter I'm trying to have my database update the frontend where a previously created word, definition, and sample sentence have been stored.

**Comment by MattB-GA-Boston** [comment]
To be clear, `search` works from the API, just not from the front end.

**Comment by GA-MEB** [comment]
`search` is not present as a default CRUD action. You need to create a controller action for it, and a route that points to that controller action.

**Comment by baz1389** [comment]
I think I am on the right track, but my query returns all the words that have already been created, not just what I wanted to search for

**Comment by baz1389** [comment]
```
Started GET "/words/?name=apple" for ::1 at 2015-11-11 15:26:44 -0500
Processing by WordsController#index as */*
  Parameters: {"name"=>"apple"}
Completed 200 OK in 4ms (Views: 0.8ms | ActiveRecord: 1.0ms)


Started GET "/words/?word=apple" for ::1 at 2015-11-11 15:26:52 -0500
Processing by WordsController#index as */*
  Parameters: {"word"=>"apple"}
Completed 200 OK in 1ms (Views: 0.7ms | ActiveRecord: 0.0ms)Started GET "/words/?name=apple" for ::1 at 2015-11-11 15:26:44 -0500
Processing by WordsController#index as */*
  Parameters: {"name"=>"apple"}
Completed 200 OK in 4ms (Views: 0.8ms | ActiveRecord: 1.0ms)


Started GET "/words/?word=apple" for ::1 at 2015-11-11 15:26:52 -0500
Processing by WordsController#index as */*
  Parameters: {"word"=>"apple"}
Completed 200 OK in 1ms (Views: 0.7ms | ActiveRecord: 0.0ms)
```

**Comment by baz1389** [comment]
```
Started GET "/words/?name=apple" for ::1 at 2015-11-11 15:26:44 -0500
Processing by WordsController#index as */*
  Parameters: {"name"=>"apple"}
Completed 200 OK in 4ms (Views: 0.8ms | ActiveRecord: 1.0ms)


Started GET "/words/?word=apple" for ::1 at 2015-11-11 15:26:52 -0500
Processing by WordsController#index as */*
  Parameters: {"word"=>"apple"}
Completed 200 OK in 1ms (Views: 0.7ms | ActiveRecord: 0.0ms)
```

**Comment by MattB-GA-Boston** [comment]
Probably an issue with your controller method. Try running the commands from `rails c` and see if you can get them to work.

**Comment by baz1389** [comment]
Those errors were from curl commands so I can't run it in rails c.

Words.where(name: "some_word"), however, does work in rails c (but I think that inherently comes with the console functionality).

**Comment by GA-MEB** [comment]
@baz1389 
I'm re-reading your console output, and I think the issue is that a GET request at `/words` is being interpreted by your routes as `words#index`, irrespective of the query parameter.

I think you need to either (a) come up with a separate route for `search`, distinct from `index`, or (b) re-write `index` so that it knows to use `.where` when given a query string.

**Comment by baz1389** [comment]
Are either of these on the right track?

```
def index
    if params[:word] then
      @word = Word.where(word: params[:word])
        elsif params[:name] then
          @word = Word.where(name: params[:name])
        else
          @word = Word.all
        end
      end
    end
    render json: @words
  end
```

```
def search
    if params[:query].present?
      @words = Word.where(name:, params[:query].downcase)
    else
      @words = Word.none
    end
    render json: @words
  end
```

**Comment by gaand** [comment]
Your index action above has too many `end`s.  Have you tried running it?

**Comment by baz1389** [comment]
```
curl http://localhost:3000/words/?name=apple
```

I ran this curl command based on what Mike posted yesterday and the CLI returned my entire HTML document

**Comment by baz1389** [comment]
Problem solved.

```
def index
    if params[:name]
      @words = Word.where(name: params[:name])
    else
      @words = Word.all
    end

    render json: @words
end
```

I was overcomplicating things in my head -__-
