### ISSUE TITLE
'Method Undefined' In controller.

### ISSUE THREAD

**Issue by rickdean** [ga-wdi-boston/full-stack-project#500]
I am attempting to address the 'current user' requirements.  I am receiving the following status return when attempting a post request.

`Started POST "/shows" for ::1 at 2016-11-30 14:43:01 -0500
Processing by ShowsController#create as */*
  Parameters: {"show"=>{"title"=>"", "genre"=>"", "description"=>"", "release_date"=>"", "episodes"=>"", "rss"=>"", "site"=>"", "voice_artist_string"=>""}, "submit"=>""}
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "f03f1bc906dac0270da402be2904852e"]]
Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.1ms)

NoMethodError (undefined method `show' for #<User:0x007f8f54ab34a8>):
  app/controllers/shows_controller.rb:21:in `create'`

Line 21 (the culprit) - looks like this (the rest of mycontroller is also based on the example controller)

`  def create
    @show = current_user.shows.build(show_params)
    if @show.save
      render json: @show, status: :created, location: @show
    else
      render json: @show.errors, status: :unprocessable_entity
    end
  end`

I've also updated updated my show.rb as follows:

`class Show < ActiveRecord::Base
    belongs_to :user
    validates :user, presence: true
  end
`

Any thoughts?  I've been working to figure this one out for awhile.

**Comment by raq929** [comment]
It looks like your conroller is looking for called `show` which doesn't exist.

Did you create a migration after adding the relationship? And migrate?
Can you use three backticks when posting code? I'm having trouble reading this.

**Comment by rickdean** [comment]
Thank you.  Yes - it's definitely a problem with 'show'.  I have run migrations consistently. Does the order of things in the controller itself matter?  I don't think it's the problem as I am mirroring the order of the examples file but it's a thought.    My controller code looks like this.....

```rb
class ShowsController < ProtectedController
  before_action :set_show, only: [:show, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.where("user_id=#{current_user.id}").reverse

    render json: @shows
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
    render json: @show
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = current_user.shows.build(show_params)
    if @show.save
      render json: @show, status: :created, location: @show
    else
      render json: @show.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    # @show = Show.find(params[:id])
    # render json: @show
    if @show.update(show_params)
      head :no_content
    else
      render json: @show.errors, status: :unprocessable_entity
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    if @show.destroy
      head :no_content
    else
      render json:  @show.errors, status: :unprocessable_entity
    end
  end

  private

  def set_show
    @show = current_user.shows.find(params[:id])
  end

  def show_params
    params.require(:show).permit(:title, :genre, :description, :release_date, :episodes, :rss, :site, :voice_artist_string)
  end
end

```

**Comment by raq929** [comment]
Can you post the migration that created the relationship? 
Also, check issue #493

**Comment by rickdean** [comment]
Thank you.  I have been watching Alex's thread as well.

the migration is....

```rb
class Fk < ActiveRecord::Migration
  def change
    add_foreign_key :shows, :users
  end
end
```

**Comment by raq929** [comment]
I think you should rollback that migration, and try to have your migration look more like the solution branch on `rails-api-one-to-many`. 
Your command to generate the migration should look something like: https://github.com/ga-wdi-boston/rails-api-one-to-many#demo-modify-books-migration

**Comment by rickdean** [comment]
Hi!  I actually was attempting to do just that before gettjng your message.  When I attempt to run the command I receive the message that 'user_id' column already exists.  This makes sense since I created it.  But I cannot seem to drop the column (it has an index and a foreign key).  Whenever I try to rollback the migrations that created the column or try to delete it I receive this message

```rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "user_id" of relation "shows" already exists
: ALTER TABLE "shows" ADD "user_id" integer```

It then references all migrations which previously created it and the index and foreign key.  Any ideas without having to drop the table and recreate it?

**Comment by gaand** [comment]
Does adding a foreign key add a column? I think there may be other migrations to look through.

**Comment by rickdean** [comment]
True.  I performed three steps.  Add column - add index- then the foreign.  While trying to reverse them I hit the 'rake aborted' message.  I probably am not understanding how these rollbacks work.  I attempted to target each migration for rollback but each time I hit the rake aborted.  For example -

```
~/wdi/projects/show-api (response)$ rake db:rollback 20161130150458
== 20161130160508 AddIndexToShows: reverting ==================================
-- remove_index(:shows, {:column=>:user_id})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Index name 'index_shows_on_user_id' on table 'shows' does not exist

ArgumentError: Index name 'index_shows_on_user_id' on table 'shows' does not exist

Tasks: TOP => db:rollback
(See full trace by running task with --trace)
```
20161130150458 was the migration I used to add the column.

**Comment by gaand** [comment]
You probably have an ordering related problem.  

You could reset, or if you'd like to puzzle it out, I'd be happy to assist tomorrow.

**Comment by rickdean** [comment]
Sounds good.  Thank you Antony.  We can take a look together tomorrow.  I appreciate it.

**Comment by rickdean** [comment]
With Rachel's help I reversed the three migrations that were in the way of rollback.
-add user_id column 
-add index to user_id
-add foreign key to user_id

To do this we ran 'bundle exec rails d migration' on each (i.e bundle exec rails d migration addForeignKey)

We then ran 'rails g migration AddUserToShows user:references' to create the proper reference per 
https://github.com/ga-wdi-boston/rails-api-one-to-many#demo-modify-books-migration
