### ISSUE TITLE
Ruby | Following migration guides

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/full-stack-project#502]
Was wondering if it was appropriate for this project to look at ruby on rails docs to try and follow their guides step by step for migrations. 

For example, at step 6 it talks about migration commands. But it goes into erb in step 6.2. Do you think it is a good idea to follow these guides step by-step?http://guides.rubyonrails.org/v3.2.8/getting_started.html

**Comment by payne-chris-r** [comment]
No. That guide is telling you how to build a rails app from scratch ([including views](http://guides.rubyonrails.org/v3.2.8/getting_started.html#adding-a-link)). Please use our `rails-api-template` as a starting point, and follow the commands outlined in that repo to get started.

**Comment by payne-chris-r** [comment]
For your reference, this is where you should be starting: https://github.com/ga-wdi-boston/rails-api-template

**Comment by jbuzzanco** [comment]
Okay 🆒 
 I have the rails-api-template. Just haven't done the heroku part in this. However, the commands in the repo do not really talk about scaffolding. Just really getting the rails server up and running from what I understand.
So for scaffolding say a quotes table, would it be a good idea to follow some rails documentation?

**Comment by payne-chris-r** [comment]
I believe it's covered in one of our `rails-api-...` talks. Maybe the `rails-api-many-to-many` one? This is fine to run though:
`rails generate scaffold Post name:string title:string content:text`

**Comment by jbuzzanco** [comment]
Cool. Ya was just looking for some sort of written documentation to follow. I'll try and use that as a guide https://github.com/ga-wdi-boston/rails-api-many-to-many/
