### ISSUE TITLE
Unable to completely drop a table

### ISSUE THREAD

**Issue by sujkid** [ga-wdi-boston/full-stack-project#505]
So i had a table that I messed up, so I decided to drop it.. the table is gone, but the files are still in my folder. Now when i create a different table, I get an error during migration.

rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "requests" does not exist

Is it ok to manually delete the migration files from the previous table from the project folder?

The previous table is gone from the database and the schema. The only remains are the mess-ups that i made that are in the form of migration files.

**Comment by raq929** [comment]
You can use `bundle exec rails d migration <name of migration>`.

**Comment by neugierige** [comment]
@sujkid resolved?

**Comment by sujkid** [comment]
no, still working on it

**Comment by sujkid** [comment]
I deleted some migrations from the folder(via terminal) and bundle exec rake db:drop, create, migrate.
