### ISSUE TITLE
Need help with seeds

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/full-stack-project#509]
I lost the information I created in my create games table so Ben advised that I use seeds. Now I'm getting a lot of warnings when I try to enter in the info. I'm not sure if it is just a linter error or it will cause my code to not store that info into my table.

![screen shot 2016-12-01 at 10 27 22 am](https://cloud.githubusercontent.com/assets/9563419/20799643/c4460b80-b7b0-11e6-945d-c175c0593b4e.png)

**Comment by raq929** [comment]
Try it! `bundle exec rake db:seed`
If you get an error, post the error.

**Comment by Sphilippe7** [comment]
Worked! So should I just disregard the warnings?

**Comment by Sphilippe7** [comment]
and do I have to run that after every save?

**Comment by neugierige** [comment]
No. `bundle exec rake db:seed` is run once. 

Your Linter warning look seem to all be related to formatting, so you're probably ok.

**Comment by Sphilippe7** [comment]
ok thank you @neugierige
