### ISSUE TITLE
Can I talk through my project's serializers with someone?  

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/full-stack-project#51]
On a user's profile, I'd like to have a list of sites that user has authored, preferably with a count of each site's upvotes (which were cast by other users). I'd also like to list sites similarly (with upvote count) when I search by the attribute :neighborhood. How do serializers help me do this? 

I'd listen to that railscast Rachel posted, but I don't have headphones...

I know somewhere I put something like this (for the user question) but what else am I missing...?
user.as_json(include: {:sites  {include: {votes: {only: ...?} }, only: :name, :neighborhood} } )

**Comment by sarabrentmccoy** [comment]
Feel like this might be a bigger-picture, app-logic question...

**Comment by GA-MEB** [comment]
I have headphones! But I can also explain serializers. Come find me in the dugout.

**Comment by jrhorn424** [comment]
I don't believe you need to type `as_json` when you're using serializers.

**Comment by GA-MEB** [comment]
@gaand @jrhorn424 
Need some additional support. Something's broken with `has_many: ... , through: ...`

**Comment by sarabrentmccoy** [comment]
undefined method `relation_delegate_class' for Sites:Module

**Comment by sarabrentmccoy** [comment]
That's the error I get when I try to call User.first.sites, etc. 
User.first.my_sites works.

Here are my models: 

class Site < ActiveRecord::Base
  belongs_to :user
  has_many :votes
  has_many :users, through: :votes 
end

class User < ActiveRecord::Base
  include Authentication
  has_many :my_sites, class_name: 'Site'
  has_many :votes
  has_many :sites, through: :votes
end

class Vote < ActiveRecord::Base
  belongs_to :users
  belongs_to :sites
end

**Comment by gaand** [comment]
We found and corrected a pluralization issue.
