### ISSUE TITLE
Conceptual issues

### ISSUE THREAD

**Issue by matthewgsommers** [ga-wdi-boston/full-stack-project#511]
At this point I need to make a decision in regards to my tables, their data and how they will be joined and would appreciate some assistance. I originally intended on the following tables:
1. User (self explanatory: sign up / sign in / sign out / change password)
2. Picture (would contain information about the picture in focus with columns:  title/artist/location/url/description/etc). This would satisfy my GET, POST (upload picture), and DELETE (delete a picture & its info).
3. Battle (would contain the id of both pictures and a battle_id). This was originally intended to satisfy the PATCH requirement by associating the winning picture of the battle with the user. 

However, at this point I feel as if the battle aspect is more of a reach given our timeframe. So I'd like to talk through potentially removing the battle aspect and replacing the battle decision (PATCH) with comments.

**Comment by neugierige** [comment]
I agree that you should figure out the CRUD methods for Picture. Did you have a particular concern about doing a PATCH on the pictures themselves?

By the way, the Picture table should probably have a reference to the user table, to indicate which user it belongs. It sounds like multiple users cannot have a same picture?

**Comment by matthewgsommers** [comment]
My PATCH shouldnt be too difficult, I just need to figure out the correct direction. I'm not sure if I should have a comments table or if it should be a column of the pictures table. 

So the second comment is where I'm getting a bit stuck. The app is supposed to be a gallery, so I made the assumption that users should not have to be logged in to view the images so technically the auto-populated images and their data wouldnt belong to anyone. I'd like the images that users upload to also be viewable to an unauthorized user, but unauthorized users wouldnt be able to POST / PATCH / DELETE any images.

**Comment by neugierige** [comment]
Yes, the Pictures in the gallery are visible to anyone. That is definitely doable. In fact, Chris addressed this in class last week (I believe). Don't worry about it for now, we'll cross that bridge when we get to it!

**Comment by payne-chris-r** [comment]
Why not just PATCH on pictures?
```Picture (would contain information about the picture in focus with columns: title/artist/location/url/description/etc```
Why not just update who the artist is, or the title, etc? This would satisfy your update requirement.

**Comment by raq929** [comment]
What's the status of this?

**Comment by neugierige** [comment]
@callmelife ok to close??
