### ISSUE TITLE
Placing dependancies.js & bundle.js in head of bootstrap template  breaks certain styles/js

### ISSUE THREAD

**Issue by akadane87** [ga-wdi-boston/full-stack-project#512]
I'm using this bootstrap template: https://startbootstrap.com/template-overviews/agency/

Styles and Js working fine until I placed these in the head:
```
<script src="dependencies.js" type="text/javascript" charset="utf-8" defer></script>
 <script src="bundle.js" type="text/javascript" charset="utf-8" defer></script>
```

Not all of the stylings break but some do. Also the additional bootstrap dropdown menu I've placed in with my auth functions won't show. I've used a hacky jQuery work around to test my auth (which works) but worried it's going to cause more problems later

Lastly I tried putting "bundle.js" above "dependencies.js" which throws this error:
```
bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined(…)
```
Not sure what's happening in my webpack here...

**Comment by raq929** [comment]
Yep, that template hasn't been updated with the changes we made in browser-template in project 1.
You'll have to go through the steps here: https://github.com/ga-wdi-boston/game-project/issues/355
to get it working.

**Comment by gaand** [comment]
If you've added `link` or `script` tags to `index.html` then you will run into problems.

Incorporating a bootstrap template into the browser template can't be done by adding link and script tags.

**Comment by raq929** [comment]
@akadane87 What's your status with this?

**Comment by akadane87** [comment]
@raq929 So my template had already reflected those changes when I started. 
@gaand I'm a bit confused on what you mean. I'm currently using an index.html file from a bootstrap template within our browser-template. I've since added the 2 <script> links to that html which seems to be semi-breaking things. Sorry if I'm not being clear enough or if this is repetitive.

**Comment by gaand** [comment]
Our template loads all of bootstrap by default.  When you load it again (probably a different version) and other JavaScript (a different version of jQuery), that breaks things.

**Comment by akadane87** [comment]
Is there a list of steps I could take to swap the browser-template's js/bootstrap/jquery libraries for the template's one? Or is the solution to get rid of the template and start over?

**Comment by gaand** [comment]
If the template relies on customizations to the bootstrap files, starting over might be the way to go.

If not, you might be able to extract the customizations added on top of bootstrap and load those using `assets/styles/index.scss`.

**Comment by akadane87** [comment]
Hoping I can get a 1:1 to attempt syncing libraries, but it sounds like I need to delete everything. Solution: Don't use 3rd party bootstrap templates in conjunction with GA browser-template

**Comment by gaand** [comment]
I'd be happy to have a look with you about how it might be accomplished, but it should probably wait until you feel that you're meeting requirements.
