### ISSUE TITLE
Issue with update after enabling current_user

### ISSUE THREAD

**Issue by kibs86** [ga-wdi-boston/full-stack-project#513]
I tried to enable current_user for update by looking at the example controller, but whenever I try to update, I get a 404.  The update was working fine before doing the current_user check.

**Rails request details from terminal:**
```
Started PATCH "/words/1" for ::1 at 2016-12-01 12:00:39 -0500
Processing by WordsController#update as */*
  Parameters: {"word"=>{"word"=>"hello", "difficulty"=>"medium"}, "id"=>"1"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "a5d2c0c12d2908b568d103f3c0a9d5d2"]]
  Word Load (0.2ms)  SELECT  "words".* FROM "words" INNER JOIN "completed_words" ON "words"."id" = "completed_words"."word_id" WHERE "completed_words"."user_id" = $1 AND "words"."id" = $2 LIMIT 1  [["user_id", 2], ["id", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.06ms)
Completed 404 Not Found in 8ms (Views: 1.0ms | ActiveRecord: 1.0ms)
```

**Controller action for update** (including before_action)
```rb
before_action :set_word, only: [:show, :update, :destroy]

def set_word
    @word = current_user.words.find(params[:id])
  end

def update
    if @word.update(word_params)
      # head :no_content
      render json: base_query
    else
      render json: @word.errors, status: :unprocessable_entity
    end
  end
```

**Comment by payne-chris-r** [comment]
Does `words/1` belong to the `current_user`? i.e. does the record in the `words` table have a `user_id: 3` (or whatever the `current_user`'s id is)?

**Comment by kibs86** [comment]
No, I think that's actually the problem.  I do have a join table, but it's to keep track of words that the user has played and successfully unscrambled.  It doesn't keep track of words that the user has created.  In the words table, I have a column for the user's email which I've added manually for the first few I've bulk loaded, but I plan on building into the create action once I get that working.  Should I do a manual check of current_user.email in my Words table instead of copying the example?  Or can I simultaneously have a many to many relationship between Users and Words through Completed Words and a 1 to many between Users and Words for one's they've created?

That might be a terrible explanation so I can draw it out as well if that would be helpful.

**Comment by gaand** [comment]
Is the action intended for `words` or `completed_words`?

**Comment by kibs86** [comment]
This update action is intended for ```words```.

**Comment by payne-chris-r** [comment]
You can. But take it one thing at a time. I think the steps are:
1) create a bunch of words (through seed/example data)
2) make sure you can get all words, make sure you can get 1 word
3) create a `completed_words` table that has `user_id`, `word_id`, and whether or not the user got it right?, or the user's response?.
4) a) build out `create` routes and actions for `words`
b) build out `update` routes and actions for `words`
c) build out `destroy` routes and actions for `words`
5) figure out user ownership of `words` <-- what happens to your seed/example data at this point? How do you handle words that aren't owned?
6) how do users interact with a game now that they own words. Do *their* words come up as options in the game? Do they not? etc.

**Comment by gaand** [comment]
Create an admin user who owns all the words?

**Comment by payne-chris-r** [comment]
![image](https://cloud.githubusercontent.com/assets/12667121/20805580/43eaa332-b7c5-11e6-924a-f896fb9ca1fd.jpeg)

**Comment by kibs86** [comment]
Thank you both!

@payne-chris-r per our conversation I've dropped the ```creator``` column from ```words``` and I'm generating the reference to ```users```.  How do I get a custom column name called ```owner_id``` instead of the default of ```user_id```?

**Migration File**
```
class AddUserRefToWords < ActiveRecord::Migration
  def change
    add_reference :words, :user_id, index: true, foreign_key: true
  end
end
```

**Comment by gaand** [comment]
http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_reference

**Comment by payne-chris-r** [comment]
Hey Kara,
I think you also might want to take a look at this:
http://stackoverflow.com/questions/1163032/rails-has-many-with-alias-name
The example in it is:
`has_many :jobs, foreign_key: "user_id", class_name: "Task"`
Which would allow you do make user.words be the completed_words, but user.owned_words be the words that the user has created...

**Comment by kibs86** [comment]
I created an ```owner_id``` column that's a foreign key to ```user_id``` in the ```users``` table.  I also kept the ```has_many```, but removed the ```through: :completed_words``` piece.  When I run update now, I'm getting this error:

From Rails logs in terminal:
```
Started PATCH "/words/1" for ::1 at 2016-12-01 14:27:57 -0500
Processing by WordsController#update as */*
  Parameters: {"word"=>{"word"=>"hello", "difficulty"=>"medium"}, "id"=>"1"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "0fd71f38b88e73dd3992da20c8768bbc"]]
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.2ms)

ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column words.user_id does not exist
LINE 1: SELECT  "words".* FROM "words" WHERE "words"."user_id" = $1 ...
                                             ^
HINT:  Perhaps you meant to reference the column "words.owner_id".
: SELECT  "words".* FROM "words" WHERE "words"."user_id" = $1 AND "words"."id" = $2 LIMIT 1):
  app/controllers/words_controller.rb:101:in `set_word'
```

My ```update``` and ```set_word``` methods look like this:
```
def update
    if @word.update(word_params)
      # head :no_content
      render json: base_query
    else
      render json: @word.errors, status: :unprocessable_entity
    end
  end

def set_word
    @word = current_user.words.find(params[:id])
  end
```

Is there a way within set_word to have it match params[:id] to the owner_id column?  The foreign key is setup.  Otherwise, maybe I should have kept my owner_id column as user_id?

**Comment by gaand** [comment]
Please post your words model.

**Comment by gaand** [comment]
Also, don't you want both, a `has_many` and a `has_many, through:`?

**Comment by kibs86** [comment]
Words Model:
```
class Word < ActiveRecord::Base
  # has_many :users, through: :completed_words
  has_many :users
  has_many :completed_words, dependent: :destroy
  # belongs_to :user
  # validates :user, presence: true
end
```

Maybe I do need both.  I was thinking at one point that I needed both a ```belongs_to``` and a ```has_many``` since the ```User``` to ```Word``` relationship is 1 to many outside of the completed words functionality.

**Comment by kibs86** [comment]
Also, further clarification.  I tested my ```GET``` and ```CREATE``` for ```completed_words``` and that's still working.  So basically, playing the game is still working and update is closer.  It just doesn't seem to like that the columns aren't named the same.

**Comment by gaand** [comment]
Let's chat briefly.

**Comment by kibs86** [comment]
I think I finally got it using the advice from both of you.  Thank you very much!!

**Resolution:**
1. Dropped the ```creator``` column from ```words``` table
2. Created a new ```owner_id``` column using the process of create column, create foreign key, create index
3. Updated User model and Word model
4. Updated Create action

User Model:
```
class User < ActiveRecord::Base
  include Authentication
  has_many :examples
  has_many :words, through: :completed_words
  has_many :owned_words, foreign_key: 'owner_id', class_name: 'Word'
  has_many :completed_words, dependent: :destroy
end
```

Word model:
```
class Word < ActiveRecord::Base
  has_many :users, through: :completed_words
  belongs_to :owner
  has_many :completed_words, dependent: :destroy
  # validates :user, presence: true
end
```

Create action:
```
def create
    @word = current_user.owned_words.build(word_params)
    @word.owner_id = current_user.id

    if @word.save
      render json: @word, status: :created, location: @word
    else
      render json: @word.errors, status: :unprocessable_entity
    end
  end
```

**Comment by payne-chris-r** [comment]
Did your chat with @gaand get you where you need to be @kibs86 ? I think you DO want a has_many and a has_many_through, but see my comment so you can give it a different alias...

**Comment by payne-chris-r** [comment]
Ignore last comment. Thanks for posting your solution @kibs86.
