### ISSUE TITLE
Looking for help with rails validation

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/full-stack-project#514]
Since there are quite a bit of forms in my app that only accept certain kinds of data, I want to set up validation.
I am reading the Ruby docs (http://guides.rubyonrails.org/active_record_validations) and following the steps and starting small with just validating name for chore, but the changes aren't taking effect. I am not sure if there is anything I need to do on my front end to make the changes happen. 
I also read some of the older issues  but it looks like people were using them in a more in-depth manner than me and I couldn't simplify them
Here is all I have for code:

```rb
class Chore < ActiveRecord::Base
  validates :name, presence: true
end
```

**Comment by payne-chris-r** [comment]
Can you embellish on what you mean by "I want to set up validation"? Do you not want a chore not to be created unless there is a name for that chore?

**Comment by akradin** [comment]
Exactly. I want the entire form, which contains name, chore, and difficulty, to have to be filled out and use the correct data types before being able to be submitted

**Comment by payne-chris-r** [comment]
The code you have written basically says:
Before you create a Chore, make sure that Chore has a name. Otherwise, barf.

**Comment by raq929** [comment]
That sounds like front-end validation that you're talking about. Have you met requirements? I think this is an awesome stretch goal, but I would wait until the basic requirements are met.
If yes, I'm happy to meet with you about it.

**Comment by gaand** [comment]
Do you get an error from the rails server when you try to create a chore?

**Comment by gaand** [comment]
Front end validations are good, but are insufficient.  The API must also validate.

As @raq929 says, this may be a stretch goal.

**Comment by payne-chris-r** [comment]
I think your question is about `not sure if there is anything I need to do on my front end`, and my answer is no, except for now you need to make sure that when you POST to `/chores`, your chore has a `name`.

**Comment by akradin** [comment]
Okay so lets say a user wants to add a chore. They add the name, and it will work fine because the data type is text, but lets say they put in text in the date field which requires date format. Rails will allow that to happen, you can still make a chore but when you look at it, it will say Date: null.

Isn't that a user facing bug, thus making my project not meet requirements

**Comment by raq929** [comment]
Ah, OK. That's backend validation, then. It happens AFTER the form is submitted, but BEFORE the object is created in the database.
Have you looked at Rails documentation about validation? 
http://guides.rubyonrails.org/active_record_validations.html

**Comment by gaand** [comment]
http://guides.rubyonrails.org/active_record_validations.html#format ?

Also, you can check to see if it can be coerced to a date.

**Comment by akradin** [comment]
Yeah, I am trying to follow the guide step by step but it doesn't seem like the changes are actually happening.

**Comment by payne-chris-r** [comment]
My steps would be as follows:
1) Test the code you have written works (meaning you try to create a chore without a name, and watch it barf)
2) Do the same thing for `date` (i.e. presence true). 
3) Repeat 1) for your new addition.
4)  Take a look at the link @gaand just posted and see if you can figure out how to make a data type be a `date`

**Comment by akradin** [comment]
Yeah Chris, just tried it and no barfing is happening

**Comment by gaand** [comment]
Have you restarted your API after the change?  It should reload, but make sure that's not the problem.

**Comment by akradin** [comment]
Interesting, I restarted the API and when I load my app in the browser it shows:
```sh
{
"status": "500",
"error": "Internal Server Error"
}
```

**Comment by akradin** [comment]
So maybe that is the issue, not really sure how to troubleshoot heroku though...

**Comment by gaand** [comment]
Are you not developing the API locally?

**Comment by akradin** [comment]
I was, I didn't realize this was an issue until I was testing to see if I met requirements, I could go back onto my local server if that would make figuring this out easier

**Comment by gaand** [comment]
When adding new features, you need to test locally and get them working there before trying them on the deployed API.

**Comment by akradin** [comment]
Okay, back in local mode and getting a 500 error when the name field is left blank. 
```sh
Started POST "/chores" for ::1 at 2016-12-01 13:48:01 -0500
Processing by ChoresController#create as */*
  Parameters: {"chore"=>{"name"=>"", "due_date"=>"", "difficulty"=>""}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "e7ba65e9efb277cada544814e1002646"]]
   (0.1ms)  BEGIN
   (0.2ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.15ms)
Completed 500 Internal Server Error in 15ms (Views: 4.0ms | ActiveRecord: 0.5ms)
```

I am assuming this is what I want?

**Comment by payne-chris-r** [comment]
Try it with a `name` and nothing else and find out!

**Comment by akradin** [comment]
WARNING, GOING TO ATTACH A SCREEN SHOT. 
If you look at the screen shot it is showing more of an in depth error message than the server. So the solution is to work on the API locally and then push changes after.
<img width="426" alt="screen shot 2016-12-01 at 1 54 10 pm" src="https://cloud.githubusercontent.com/assets/22475825/20807645/c69034d4-b7cd-11e6-9444-b55cb8ec8a99.png">

**Comment by payne-chris-r** [comment]
Or google "What error should I receive if a rails validation doesn't work?"

**Comment by payne-chris-r** [comment]
YAYYYY

**Comment by payne-chris-r** [comment]
Also, just so you know. "can't be blank" is the `default` message. You can customize it as well if you want. ;-)

**Comment by akradin** [comment]
sounds like something I should mess with once I meet requirements ;) ;)
