### ISSUE TITLE
Any Idea what http Token Access denied means when trying to look on localhost?

### ISSUE THREAD

**Issue by RpRoderick** [ga-wdi-boston/full-stack-project#516]
<img width="273" alt="screen shot 2016-12-01 at 12 20 03 pm" src="https://cloud.githubusercontent.com/assets/22726092/20804382/ae4b32c8-b7c0-11e6-9d29-b20919a48ccc.png">

**Comment by gaand** [comment]
It means you're trying to access a resources that can only be accessed if your request includes a valid token.  This was something you had to do with the game project API.

**Comment by RpRoderick** [comment]
ok, thank you.  I guess what I'm not understanding is why simply going to local rails host/users would return this, since I'm only trying to see the data of users? As in the Json listing of created users (temp data).  Do I need to give the temp data (User.create) a token?  That doesn't make sense to me since I'm trying to see a list of many users which I've created. I believe I'm missing something here...

**Comment by gaand** [comment]
Does the users controller authenticate the index action?

**Comment by RpRoderick** [comment]
Ok, that fixed it.  For anyone who doesn't quite know what that means, I'll post before and after pics below.  Thanks!

**Comment by RpRoderick** [comment]
Before:

<img width="838" alt="screen shot 2016-12-01 at 1 03 32 pm" src="https://cloud.githubusercontent.com/assets/22726092/20805906/ada80b4c-b7c6-11e6-99bc-1f3c5b312841.png">

**Comment by RpRoderick** [comment]
After:

<img width="765" alt="screen shot 2016-12-01 at 1 03 52 pm" src="https://cloud.githubusercontent.com/assets/22726092/20805914/b6845f4a-b7c6-11e6-8b30-ad05fc4c6533.png">

**Comment by gaand** [comment]
@RpRoderick 

Please post code snippets rather than images.

Also, is there a reasons that listing all of the users is something anyone should be able to do?

**Comment by RpRoderick** [comment]
Yes, I could see where you would not want to have anyone list out all users and info.  I'll take out the :index before I deploy final, but I wanted to be able to see my data here to verify my steps.  I'm also viewing in pry, but it lists everything.  Mostly for verification purposes.  And I will post code next time.  Thanks again.
