### ISSUE TITLE
Rails| Migration now displaying error

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/full-stack-project#517]
I had my rails server displaying the list of quotes correctly but now there an error saying migrations are pending. But when I run bundle exec rake db:migrate It shows that there is already a migration, which I ran earlier: ActiveRecord::DuplicateMigrationNameError: . Not sure why migrations are pending when there is already a migration.
Edit: Also when I do rake db:rollback, it won't let me as there are multiple migrations it claims. 
```
ActiveRecord::DuplicateMigrationNameError: 

Multiple migrations have the name CreateQuotes

```

**Comment by raq929** [comment]
Is there an error when you run `bundle exec rake db:migrate`?

**Comment by jbuzzanco** [comment]
Yes 
when I run bundle exec rake db:migrate It shows that there is already a migration, which I ran earlier: `ActiveRecord::DuplicateMigrationNameError: ` is the error

**Comment by raq929** [comment]
It looks like you have more than one migration with the same name.
This may be related to #261.

**Comment by jbuzzanco** [comment]
I did try to rollback `bundle exec rake db:rollback`
It does not allow as there are multiple migrations

**Comment by jbuzzanco** [comment]
Resolved. There was literally another migration file that I didn't need in my folder that I deleted, so now it works as there is only one migration file for quotes.
