### ISSUE TITLE
I need help with Handlebars

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/full-stack-project#519]
I'm trying to find a way to show my index from the API onto my front end. I heard many people speak of handlebars so I decided to look it up in the repo. I saw the examples but not quite sure how to incorporate it into my html. Mostly because I do not understand it too well.

**Comment by neugierige** [comment]
Stanley, please review this again: https://github.com/ga-wdi-boston/project-issue-tracker-guide#before-you-create-a-new-issue-ie-due-diligence

We would be much more able to help you if you had an actual error from some code that you tried.

**Comment by Sphilippe7** [comment]
ok I'll provide an error once I read over the documentation again

**Comment by neugierige** [comment]
Reading the documentation is always good to do, but most importantly, just TRY something! If it doesn't work, read the error, try to find the solution in the documentation, then try something else.
