### ISSUE TITLE
need help customizing the 

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/full-stack-project#52]
The workaround to solve the issue of the name required to be not_null during registration requires customization for the register submit form and I need some help to finish that part, so I am re-opening this by creating this new issue.

**Comment by LaurisaNeuwirth** [comment]
I need to write a callback function for the registration submit. I also do not understand if the name entered during registration has any other ramifications.

**Comment by srhoulam** [comment]
Laurisa, start by writing a function. Paste it here once you've done so.

**Comment by LaurisaNeuwirth** [comment]
callback_submit = function callback(error, data) {
    if (error) {
      console.error(error);
      $('#result').val('status: ' + error.status + ', error: ' +error.error);
      return;
    }
  };

**Comment by LaurisaNeuwirth** [comment]
It works. Please close this issue.
