### ISSUE TITLE
Handlebars| Style gets messed up upon implementing files

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/full-stack-project#520]
So I am trying to implement what we went over in class for the handlebars repository, and editing according to my project.
The style is gone upon adding handlebars but comes back when I delete the files, and am not sure why. 
The html implemented from handlebars is showing up on the page load, however the functionality of it is not working.

**Comment by raq929** [comment]
Is there an error in the console? 
Also please post code with your issue. It helps us answer issues much faster if you post the code initially without us having to ask. In this case, please post your HTML and your handlebars file.

**Comment by jbuzzanco** [comment]
Ok ya there is just a lot of different files but I'll try and post what is relevant. Was just trying to follow along with the handlebars repo 😃 
index.html
```
<!-- handlebars -->
  <div class="container-fluid">
    <button id="getQuotesButton" class="btn btn-default">Get Quotes!</button>
    <button id="clearQuotesButton" class="btn btn-default">Clear Quotes!</button>
    <div id="content" class="content">
    </div>
  </div>
  <!-- handlebars end -->
```
quote-listing.handlebars
```
{{#each quotes as |quote|}}

  <h1> <small>Quote: {{quote.author}}</small></h1>
  <div>
    {{#if quote.author}}
      {{book.author}}
    {{else}}
      Unknown author.
    {{/if}}
  </div>
  <div>
    {{#if quote.quoteText}}
      {{book.quoteText}}
    {{else}}
      Unknown quoteText.
    {{/if}}
  </div>

{{/each}}
```
ui.js
```
'use strict';

const showQuotesTemplate = require('../templates/quote-listing.handlebars');
};


const getQuotesSuccess = (quotes) => {
  $('#content').append(showQuotesTemplate(quotes);
    console.log(quotes);

};


module.exports = {
  showQuotesTemplate,
  getQuotesSuccess,
  getTitlesSuccess,
  clearBooks,
  failure,
};
```
events.js
```
'use strict';

const api = require('./api.js');
const ui = require('./ui.js');

const onGetQuotes = (event) => {
  event.preventDefault();
  api.getBooks()
    .then(ui.getQuotesSuccess)
    .catch(ui.failure);
};

const addHandlers = () => {
  $('#getQuotesButton').on('click', onGetQuotes);
  // $('#clearBooksButton').on('click', onClearBooks);
};

module.exports = {
  addHandlers,
};
```
api.js
```
'use strict';

const app = require('../app.js');

let getQuotes = function(){
  return $.ajax({
    url: app.host + "/quotes", // "http://book-json.herokuapp.com/books"
    method: 'GET',
    // dataType: 'json'
  });
};


module.exports = {
  getQuotes,
};
```

**Comment by raq929** [comment]
Ok. What is the functionality that isn't working?

**Comment by jbuzzanco** [comment]
The `    <button id="getQuotesButton" class="btn btn-default">Get Quotes!</button>`

**Comment by raq929** [comment]
What happens when you click the button? 
Can you also post your index.js file?

**Comment by jbuzzanco** [comment]
Nothing happens in the console on clicking the button.

index.js
```

// user require with a reference to bundle the file and use it in this file
// var example = require('./example');

// use require without a reference to ensure a file is bundled
'use strict';

const authEvents = require('./auth/events.js');
const quoteEvents = require('./quotes/events.js');

// On document ready
$('document').ready(function() {
  authEvents.addHandlers();
  quoteEvents.addHandlers();

});
```

**Comment by jbuzzanco** [comment]
There is a fair chance it's a path issue as I look in the console on page load and it gives this error: `events.js:4Uncaught Error: Cannot find module "./ui.js"
`

**Comment by jbuzzanco** [comment]
However I am not sure why it is not finding `ui.js` as it is actually in the same directory.

**Comment by raq929** [comment]
Do you have any linter errors?

**Comment by jbuzzanco** [comment]
No errors, just warnings in index.html for having an empty span.

**Comment by jbuzzanco** [comment]
resolved. path was correct. Just needed to add an extra closing bracket )
