### ISSUE TITLE
Ruby gem help

### ISSUE THREAD

**Issue by rickdean** [ga-wdi-boston/full-stack-project#521]
When someone has a moment - I am trying to test a ruby gem that, when used, turns null form values into 'nil' values (so as not to overwrite a field with an empty string upon submission).  I've installed the gem but when I attempt to follow the documentation I receive this error..

```
NoMethodError (undefined method `nilify_blanks' for ActiveRecord::Base:Class):
```
I found the gem here: https://github.com/rubiety/nilify_blanks

It may not do what I want it to do but I have as yet been unable to get it to work.  I've tried doing this in my show.rb model...

```
class Show < ActiveRecord::Base.nilify_blanks
      belongs_to :user
      validates :user, presence: true
end
```

**Comment by gaand** [comment]
Did you update your Gemfile?

**Comment by gaand** [comment]
Also, after looking that over I'm not sure it does what you intend.

I think it will overwrite fields with `nil` rather than `''` which seems equally unwanted.

**Comment by rickdean** [comment]
Thank you.  I believe I missed a step.  Running update again (in case I had not).
