### ISSUE TITLE
Question as to the best way to store data that doesn't really need its own table 

### ISSUE THREAD

**Issue by Naki21** [ga-wdi-boston/full-stack-project#523]
So in my project I'm using a gem which in turn makes calls to the Giphy api via methods. The gem itself is included as a Module in a FighterController. Right now the only way I am allowing users to generate gifs if to use a GET which renders the gif in the browser by using its url (one of the values sent back from the gipfy api hash). When a user selects a Gif they want to keep as a "fighter" I have been planning on posting to a separate "join" table called Barracks. So in reality I wouldn't ever be creating fighters just calling and referencing them if I even need to. My question really boils down to is are controllers required to have models?  I don't want to include (or know if its possible) the Giphy gem on the user side because can also be used to get-by-id and return many gifs via search which I wish to use in other situations. 

Is there a better way to do (or think about) this issue? Should I consider caching all calls? How could that work using a gem instead of direct calls to a third party api?

Barracks table: :user_id(int) :giphy_id(string)

Sample output from Giphy Gem (Giphy.random)
```{
"data": {
"type": "gif",
"id": "x3aCxKS5ZRLWM",
"url": "http://giphy.com/gifs/casper-the-friendly-ghost-count-chocula-x3aCxKS5ZRLWM",
"image_original_url": "http://media0.giphy.com/media/x3aCxKS5ZRLWM/giphy.gif",
"image_url": "http://media0.giphy.com/media/x3aCxKS5ZRLWM/giphy.gif",
"image_mp4_url": "http://media0.giphy.com/media/x3aCxKS5ZRLWM/giphy.mp4",
"image_frames": "8",
"image_width": "480",
"image_height": "372",
"fixed_height_downsampled_url": "http://media0.giphy.com/media/x3aCxKS5ZRLWM/200_d.gif",
"fixed_height_downsampled_width": "258",
"fixed_height_downsampled_height": "200",
"fixed_width_downsampled_url": "http://media0.giphy.com/media/x3aCxKS5ZRLWM/200w_d.gif",
"fixed_width_downsampled_width": "200",
"fixed_width_downsampled_height": "155",
"fixed_height_small_url": "http://media0.giphy.com/media/x3aCxKS5ZRLWM/100.gif",
"fixed_height_small_still_url": "http://media0.giphy.com/media/x3aCxKS5ZRLWM/100_s.gif",
"fixed_height_small_width": "129",
"fixed_height_small_height": "100",
"fixed_width_small_url": "http://media0.giphy.com/media/x3aCxKS5ZRLWM/100w.gif",
"fixed_width_small_still_url": "http://media0.giphy.com/media/x3aCxKS5ZRLWM/100w_s.gif",
"fixed_width_small_width": "100",
"fixed_width_small_height": "78",
"username": "",
"caption": ""
}
}```

**Comment by raq929** [comment]
I think you just need a barracks controller, which will store the giphy url.

**Comment by Naki21** [comment]
Thats what it does. It stores the giphy_id which is a string and then I can use that to call back the hash if I need it

**Comment by Naki21** [comment]
It has been determined I never really had a problem
