### ISSUE TITLE
Is there a way to issue a request to delete_all?

### ISSUE THREAD

**Issue by kibs86** [ga-wdi-boston/full-stack-project#532]
Is there a way to issue a call to delete all of a certain type of resource?  For example, if I wanted to give users a way to reset their game state by deleting all of their completed words.  I think within my ```delete``` controller action it would look something like:

```
CompletedWord.where(user_id: current_user.id).destroy_all
```

But when I issue the ajax call, it's expecting me to define an ID for a specific completed word.  Is there a way to call ```DELETE``` against ```/completed_word``` instead of ```/completed_word/:id```?

**Comment by raq929** [comment]
You could define a different route, and have it route to delete (or to a new controller method.)
Like `completed_word/delete_all` or something.
Alternately, you can change your delete method to not require an id, and always delete all words.

**Comment by kibs86** [comment]
Ah ok, perfect thank you!

Resolution: Going to look at creating a new route to the existing delete controller method.
