### ISSUE TITLE
Requirement clarification on CRUD

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/full-stack-project#533]
> Create at least 4 RESTful routes for handling GET, POST, PUT/PATCH, and DELETE requests

To meet the PATCH requirement, I added a new field to the provided user model and wrote a corresponding controller method. I wanted to make sure this was sufficient to meet requirements as while it's associated with the existing user it's separate from the pre-built auth functions.

**Comment by payne-chris-r** [comment]
What is the field you're updating on user?

**Comment by coffeeisamazing** [comment]
I added a date field called meeting_date.

**Comment by coffeeisamazing** [comment]
```ruby
  # PATCH '/user/:id'
  def update
    @user = User.find(params[:id])
    @user.meeting_date = user_details[:meeting_date]
    @user.save
    head :no_content
  end
```

**Comment by neugierige** [comment]
assigning @payne-chris-r to this issue

**Comment by coffeeisamazing** [comment]
Discussed that ideally meeting_date would not be on the user table.
Will add another patch to my user_location table.
