### ISSUE TITLE
Having trouble updating and/or deleting games

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/full-stack-project#536]
I get the same error for both which is 404. I had trouble with my update game so I decided not to stick on it any longer and move over to the delete function. I looked at the back end server and it does not list what the problem is so I'm assuming it is my front end code? I mean it does show the bad request but does not say what the problem is. Maybe I am reading it wrong

![screen shot 2016-12-02 at 11 05 45 am](https://cloud.githubusercontent.com/assets/9563419/20840763/501c1612-b87f-11e6-86b2-801b2200f1d2.png)

**Comment by payne-chris-r** [comment]
404 isn't bad request, 404 is not found. Are you using `current_user`? Can you show me your controller action?

**Comment by neugierige** [comment]
are you getting this response from a curl request?

**Comment by payne-chris-r** [comment]
Nevermind. Do you see the line `Parameters{"id"=>":id"}` in your rails output?

**Comment by Sphilippe7** [comment]
yes. And the other ben recommended I change my api so now it looks like this:

```
const deletegame = (id) =>
$.ajax({
  url: api.host + '/games/' + id,
  method: 'DELETE',
  headers: {
    Authorization: 'Token token=' + api.user.token,
  },
});
```

**Comment by Sphilippe7** [comment]
nvm, I changed it back. It made the error worst

**Comment by Sphilippe7** [comment]
```
const deletegame = () =>
$.ajax({
  url: api.host + '/games/:id',
  method: 'DELETE',
  headers: {
    Authorization: 'Token token=' + api.user.token,
  },
});
```

**Comment by neugierige** [comment]
what do you mean by "made the error worse"? can you show us what it said?

**Comment by Sphilippe7** [comment]
@raq929 advised it was not "worst" so I set it as the first api that i posted

**Comment by Sphilippe7** [comment]
this is my destroy/delete method in my back end:

```
def destroy
    @game.destroy

    head :no_content
  end
```

**Comment by Sphilippe7** [comment]
This is the error I see in my console now:

![screen shot 2016-12-02 at 11 37 46 am](https://cloud.githubusercontent.com/assets/9563419/20841983/d3af2aba-b883-11e6-8ef8-4a8d1ab3f87f.png)

**Comment by Sphilippe7** [comment]
I'm still working on it and trying to figure it out but I want to know why it would be the first api while the route is listed like this @raq929 :

![screen shot 2016-12-02 at 11 46 04 am](https://cloud.githubusercontent.com/assets/9563419/20842285/120f19e0-b885-11e6-86ef-b0a180c11967.png)

**Comment by raq929** [comment]
Great! It looks like you're passing an object to your ajax call as `id` instead of a number.

**Comment by payne-chris-r** [comment]
You want the one we 👍 'd

**Comment by payne-chris-r** [comment]
Are we doing PATCH or DELETE? Focus on one and the other becomes easier.

**Comment by neugierige** [comment]
recall that the `:some_var` is Ruby syntax, because the colon indicates that it's a symbol, which does not exist in JS

**Comment by Sphilippe7** [comment]
The issue was with my ajax call. I was not getting an id so I had to change that in my events file. my events file now looks like this:

```
const deleteGame = function (event) {
  event.preventDefault();
  console.log(event.target);
  let id = $(event.target).data('id');
  api.deletegame(id)
    .then(ui.deletegameSuccess)
    .catch(ui.failure);
    $('#MonthModal').modal('hide');
    $('#CategoryModal').modal('hide');
    $('#RatingModal').modal('hide');
};
```

Also, I made edit and delete to appear as buttons under the list of items. To make things a lot simpler
