### ISSUE TITLE
Id-ing my dynamically created buttons.

### ISSUE THREAD

**Issue by sujkid** [ga-wdi-boston/full-stack-project#538]
I have this dynamically created table that list all my resources.
Against each of my resource, I have an Edit button and a Delete links.
I am successfully able to delete, 'coz I have an id for my Delete  link.
I cannot realize how to ID my edit link, so right now I am hard coding the id of the item I want to edit.
I want each Edit button to have their own unique ID. Since clicking the EDIT link opens a modal in my case, this.id will not work( I am not assigning any id to my edit link at all because I have no idea how to)

**Comment by raq929** [comment]
How did you get an ID in your delete link?

**Comment by sujkid** [comment]
the delete link is the same as my resource id. ideally i would like edit also to have the same id, but i guess you cannot have two buttons with the same id?

**Comment by raq929** [comment]
OH, it's the ID of the button? That's not the best way to resolve it, I think. I would use html's
data-* instead. https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes
You can use jQuery's `.data()` method to get the data out.

**Comment by gaand** [comment]
If you need event handlers for dynamically created buttons, it's usually better to attach the handler to a parent element into which the dynamically created element is rendered.

**Comment by sujkid** [comment]
I am not using a ul or li, they are displaying on a dynamically created table with run time created rows..
But my table does have both class and id..
Are you suggesting that I attach the edit button click handlers to the table?
Right now, I am trying to declare a global variable (like store, which we used for auth), so i can access it like from other functions.

**Comment by gaand** [comment]
Yes.  See the information about delegated events for http://api.jquery.com/on/

**Comment by sujkid** [comment]
Managed to get an id for my edit button, using the documentation that Antony included(example at the end of the page), and Rachel's help in understanding the documentation. Thanks!
