### ISSUE TITLE
linter error with 'function called before it was defined'

### ISSUE THREAD

**Issue by sujkid** [ga-wdi-boston/full-stack-project#539]
I have a particular function that calls another functin, that calls another function, that calls the first function. Doing that gives me a 

<firstfunction> was called before it was defined error in the linter.

If I move it into any other file, i would have a circular dependency..

Any way to approach this issue?

**Comment by sujkid** [comment]
edit: it's a warning, not an error

**Comment by BenGitsCode** [comment]
Sure wish I could see the relevant code ; )

Are you exporting and requiring the error-inducing function?

**Comment by sujkid** [comment]
This is my UI file...

```
js
```

const onDeleteItemsSuccess = function(data) {
  // debugger;
  console.log(data);
  api.viewItems()
  .then(onViewItemsSuccess)
  .catch(failure);
};

const onDeleteItems = function(event) {
  debugger;
  let data = this.id;
  event.preventDefault();
  api.deleteItems(data)
    .then(onDeleteItemsSuccess)
    .catch(failure);
};

const addHandlers = function() {
  $('.del-items').on('click', onDeleteItems);
  $('.edit-item-form').on('submit', update.onUpdateItems);
};

const onViewItemsSuccess = function(data) {
  delete_table();
  debugger;
.
.
.
addHandlers();
}

**Comment by sujkid** [comment]
So my top function calls the very bottom function, but I cannot rearrange these, with the way my code is now

**Comment by sujkid** [comment]
Resolved by moving the addHandler function to entry file.
