### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by atsundwn** [ga-wdi-boston/full-stack-project#54]
I can't seem to resolve this CORS issue.  Everything works in Postman, but when I try to do stuff through front-end.

**Comment by MattB-GA-Boston** [comment]
CORS issue.

**Comment by GA-MEB** [comment]
Please paste in output from the terminal where the server is running.

**Comment by srhoulam** [comment]
Are you accessing your front-end by navigating to localhost:5000 or have you opened the files from disk?

**Comment by GA-MEB** [comment]
Not a CORS issue - data was being stringified when it should not have been.
