### ISSUE TITLE
Not sure about my data structures anymore? 

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/full-stack-project#546]
I have three (?) tables: users, cheeses, and cheeseplates. I have it set up such that cheeseplates is a join tables between users and cheeseplates. I cannot delete a cheese if it has been added to a cheeseplate, and Peter indicated that it might be because there needs to be another join tables between cheese and cheeseplate ? 

What do I change to make it possible to delete a cheese from an existing cheese plate?

**Comment by neugierige** [comment]
I think you made a typo here?

> I have it set up such that cheeseplates is a join tables between users and cheeseplates.

so...where `cheeses` in relation to these?

**Comment by kiraamaa** [comment]
I had a one-on-one with Rachel and I'm adding CRUD for cheeseplates so that users can own cheeseplates and create/edit/delete them as necessary.
