### ISSUE TITLE
I need to rename my models and migrations

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/full-stack-project#55]
models and migrations are confused about who is the join table and what needs to be referenced :(

**Comment by GA-MEB** [comment]
Fixed.

**Comment by jcmeyer10** [comment]
How does this look?  I am trying to get taps through Locations just like we tried to get Reviews through Movies.

class TapsController < OpenReadController
before_action :set_beer, only: [:update, :destroy]

  # GET /beers
  def index
    @taps = @location.taps

```
render json: @tap
```

  end

  # GET /beers/1
  def show
    @tap = location.taps.find(params[:id])

```
render json: @tap
```

  end

  # POST /beers
  def create
    @beer = current_user.taps.new(tap_params)
    @tap.save

```
if @tap.save
  render json: @tap, status: :created, location: @tap
else
  render json: @tap.errors, status: :unprocessable_entity
end
```

  end

  # PATCH /beers/1
  def update
    if @tap.update(tap_params)
      head :no_content
    else
      render json: @tap.errors, status: :unprocessable_entity
    end
  end

  # DELETE /beers/1
  def destroy
    @tap.destroy

```
head :no_content
```

  end

  def set_tap
    @tap = current_user.location.find(params[:id])
  end

  def beer_params
    params.require(:tap).permit(:location_id, :beer_id)
  end

  private :set_tap, :beer_params_choices
end

end
