### ISSUE TITLE
Handlebars Issue

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/full-stack-project#554]
I am having trouble displaying the data on the front-end from my "Create Lib" Success. I want an empty library to be displayed with the appropriate "Library name" (which a user inputs on Create) showing at the top. 

UI:
```js
const createLibSuccess = (data) => {
  $('.show-library').html(createLibrary(data));
  console.log(data);
};
```

HANDLEBARS:

```handlebars
{{#each libraries as |library|}}
<li>
  <h3>{{library.name}}</h3>
  <h4>{{fundraiser.name}}</h4>
  <h5>{{fundraiser.description}}</h4>
  <h5>{{fundraiser.url}}</h4>
  <h5>{{fundraiser.city}}</h4>
<ul>
    <li button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#deleteFromLib" id="deleteFromlib">Delete from Library</li>
</ul>
</li>

{{/each}}
```

HTML:
```html
  <div class="container-fluid">
    <ul class="show-library">
    </ul>
  </div>
```

**Comment by raq929** [comment]
Can you get createLibrarySuccess to console.log something? Can you get it to add 'hello' to the html?
If yes, please post your `showLibrary` function.

**Comment by raq929** [comment]
Sorry, I mean createLibrary.

**Comment by payne-chris-r** [comment]
I also really like putting something OTHER than variables in my handlebars templates for sanity check... at least until I know they're working. 

Something like this:
```html
{{#each libraries as |library|}}
<li>
  <h3>THIS IS WORKING</h3>
  <h3>{{library.name}}</h3>
  <h4>{{fundraiser.name}}</h4>
  <h5>{{fundraiser.description}}</h4>
  <h5>{{fundraiser.url}}</h4>
  <h5>{{fundraiser.city}}</h4>
<ul>
    <li button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#deleteFromLib" id="deleteFromlib">Delete from Library</li>
</ul>
</li>

{{/each}}
```

**Comment by jdaly04** [comment]
I'm not sure I understand what you mean, @raq929, by your question about getting 'hello' added to the html... When I put just a console.log('hello') within my createLib success function, it does console log the 'hello'...but I don't think that's what you meant.

Also, I tried changing the h3 tag per @payne-chris-r 's suggestion, but that didn't change anything either.

Here's my createLib API call:
```js 
  const createLib = (data) =>
   $.ajax({
     url: config.host + '/libraries',
     method: 'POST',
     headers: {
       Authorization: 'Token token=' + store.user.token,
     },
     data,
   });
```

EVENT HANDLER:
```js
const onCreateLib = function(event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.createLib(data) // NEEDS TO BE UPDATED.
    .then(ui.createLibSuccess)  //getAllSuccess needs to be updated
    .catch(ui.failure);
};
```

UI:
```js
const onCreateLib = function(event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.createLib(data) // NEEDS TO BE UPDATED.
    .then(ui.createLibSuccess)  //getAllSuccess needs to be updated
    .catch(ui.failure);
};
```

**Comment by jdaly04** [comment]
I put the wrong function above for UI. Here's the correct one:
```js
const createLibSuccess = (data) => {
  console.log('hello');
  $('.show-library').html(createLibrary(data));
  console.log(data);
};
```

**Comment by gaand** [comment]
Please post the code for the function named `createLibrary`.  It looks like it's what you use to render the handlebars template.

**Comment by jdaly04** [comment]
So I have createLibrary at the top, set to the handlebars template: 

```js
const createLibrary = require('../templates/libraries.handlebars');
```

**Comment by raq929** [comment]
What happens when you run the code?

**Comment by jdaly04** [comment]
I get a new Library object in the console, but nothing gets rendered in the browser.

**Comment by raq929** [comment]
And you get the 'hello'?
Can you post the object you see in the console?

**Comment by jdaly04** [comment]
```
jquery.js:9536 XHR finished loading: POST "http://localhost:4741/libraries".send @ jquery.js:9536ajax @ jquery.js:9143createLib @ api.js:17onCreateLib @ events.js:21dispatch @ jquery.js:5201elemData.handle @ jquery.js:5009
2016-12-04 00:02:28.525 ui.js:18 Objectlibrary: Objectid: 43name: "thththt"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()__proto__: Object
```

**Comment by jdaly04** [comment]
So it has a library id, and a name, and it's created in the database, but I can't get it to render in the browser so that then when someone updates their library with a new fundraiser it shows up in the library on the front-end.

**Comment by raq929** [comment]
OK. But no hello, and no log of the library itself.

**Comment by raq929** [comment]
Ah. This looks like code to create a new library, not to add a fundraiser to a library.

**Comment by raq929** [comment]
Do you want it to show up in your list of libraries?

**Comment by raq929** [comment]
I think you are expecting data from your controller that it isn't giving you. Take a look at what it returns. What do you expect/want it to return?

**Comment by jdaly04** [comment]
Yeah, right now I'm just trying to get a new library, with no fundraisers, to show up so that ultimately when someone does add fundraisers, those would also show up in the library. As of now, my four CRUD actions just happen in the console (besides my GET to show all fundraisers). 

So, I'm trying to take it one at a time, and now get the "CREATE" to render in the browser so PATCH and DELETE can subsequently function properly on the front-end.

**Comment by jdaly04** [comment]
I want it to return the Library Name, and I want it to somehow show an empty table with nothing in it. 

It seems like the name is coming back but not getting rendered with handlebars.

**Comment by BenGitsCode** [comment]
Can you show us what you're actually returning now, and the controller code responsible for it?

**Comment by jdaly04** [comment]
```
jquery.js:9536 XHR finished loading: POST "http://localhost:4741/libraries".send @ jquery.js:9536ajax @ jquery.js:9143createLib @ api.js:17onCreateLib @ events.js:21dispatch @ jquery.js:5201elemData.handle @ jquery.js:5009
2016-12-04 10:32:33.384 ui.js:17 hello
2016-12-04 10:32:33.387 ui.js:19 Objectlibrary: Object__proto__: Object
```
CONTROLLER CODE: 
```ruby
class LibrariesController < OpenReadController
  before_action :set_library, only: [:show, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all

    render json: @libraries
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
    render json: @library
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    if @library.save
      render json: @library, status: :created
    else
      render json: @library.errors, status: :unprocessable_entity
    end
  end


def library_params
    params.require(:library).permit(:name)
  end
end
```

**Comment by raq929** [comment]
Cool. So, you're returning a library, but your template is expecting a list of libraries to iterate through with it's `#each`.

**Comment by jdaly04** [comment]
Interesting...so I want it to just show one?

**Comment by raq929** [comment]
That sounds like what you're saying. Your handlebars template is expecting
an array. If the data you're passing it is not an array, then you will
either need to change the template or change the data.

**Comment by jdaly04** [comment]
Yeah, I'm not finding any helpful resources to change the template to do what I want it to do.

**Comment by raq929** [comment]
Is this issue resolved?

**Comment by jdaly04** [comment]
No, I messed up Patch and Delete so am working on those. 

_ _ _ _
c: 203-218-4923
e: julia.m.daly@gmail.com

**Comment by raq929** [comment]
OK. I would simply remove the each on your template for this issue.

**Comment by jdaly04** [comment]
That did not work. 

Here's what I have in the handlebars:

```
{{libraries as |library|}}
<li>
  <h3>{{THIS IS WORKING}}</h3>
  <h4>{{library.name}}</h4>
<ul>
    <li button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#deleteFromLib" id="deleteFromlib">Delete from Library</li>
</ul>
</li>

```

**Comment by raq929** [comment]
Take out the first line.
This is assuming that the data object you get back from the server looks like:
{ 'library' : something }

**Comment by jdaly04** [comment]
Antony saved the day! As well as Rachel! I now got it to work. My Handlebars template now looks like this:
```handlebars
<li>
  <h3>Your Libraries</h3>
  <h4>{{library.name}}</h4>
  <h4>{{library.id}}</h4>
  <ul>
    <li button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#deleteFromLib" id="deleteFromlib">Delete Library
    </li>
  </ul>
</li>
```
That fixed the problem!
