### ISSUE TITLE
Handlebars| DELETE Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/full-stack-project#555]
Been trying to follow along with handlebars repo and previous functions to try and get delete working. However am getting error that I do not understand in the console 
```
events.js:39 Uncaught TypeError: Cannot read property 'then' of undefined
```
line 39 is the second line in this snippet below
```
const deleteQuote = function () {
  event.preventDefault()
  .then(ui.success)
  .catch(ui.failure);
};
```
Been trying to follow along with signout api as well to create this delete function.
Why is this error happening?

**Comment by gaand** [comment]
`preventDefault` doesn't return a `Promise`. Are you missing a call to an API function that uses `$.ajax`?

**Comment by jbuzzanco** [comment]
OK. So I looked up `preventDefault` and `Promise`, don't really know what I'm missing here. The API for it is 
```
let destroy = () => {
  return $.ajax({
    url: app.host + '/quotes/' + store.user.id,
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
  });
};

module.exports = {
  getQuotes,
  create,
  update,
  destroy
};
```

**Comment by raq929** [comment]
There's no API call in your click handler.

**Comment by jbuzzanco** [comment]
resolved. put `    url: app.host + '/quotes/' + id,
` for the api and for event 
```

const deleteQuote = function () {
  console.log('deleteQuote fired');
  event.preventDefault();
  api.destroy($(this).attr('data-id'))
  .then(ui.success)
  .then(api.getQuotes)
  .then(ui.getQuotesSuccess)
  .catch(ui.failure);
};
```
