### ISSUE TITLE
JS| Update stuck on modal

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/full-stack-project#557]
Everything is working except update is not closing out of the modal. It is doing the post request. Just not closing out. No errors show up in the console or linter that I can find.
Here is relevant code. events.js
```
const updateQuote = function(event) {
  console.log('updateQuote fired');
  event.preventDefault();
  let quoteData = getFormFields(event.target);
  let quoteId = $(this).attr('data-id');
  api.update(quoteData, quoteId)
  .then(ui.createQuoteSuccess)
  .then(api.getQuotes)
  .then(ui.getQuotesSuccess)
  .catch(ui.failure);
};

const addHandlers = () => {
  $('#getQuotesButton').on('click', onGetQuotes);
  $('#create-quote').on('submit', createQuote);
  $(document).on('submit','.update-quote-form', updateQuote);
  $(document).on('click','.delete-button', deleteQuote);
  // $('#clearBooksButton').on('click', onClearBooks);
};

module.exports = {
  addHandlers,
};
```

api
```
const update = function(data, id) {
  return $.ajax({
    url: app.host + '/quotes/' + id,
    method: 'PATCH',
    data,
    headers: {
      Authorization: 'Token token=' + store.user.token,
    },
  });
};

```

**Comment by payne-chris-r** [comment]
What does `createQuoteSuccess` do? Do you maybe want a `updateQuoteSuccess` handler?
```js
const updateQuote = function(event) {
  console.log('updateQuote fired');
  event.preventDefault();
  let quoteData = getFormFields(event.target);
  let quoteId = $(this).attr('data-id');
  api.update(quoteData, quoteId)
  .then(ui.createQuoteSuccess)
```

**Comment by jbuzzanco** [comment]
I don't believe it is defined, I'm not really sure.

Here is what I tried to change.
```

const updateQuote = function(event) {
  console.log('updateQuote fired');
  event.preventDefault();
  let quoteData = getFormFields(event.target);
  let quoteId = $(this).attr('data-id');
  api.update(quoteData, quoteId)
  .then(ui.updateQuoteSuccess)
  .then(api.getQuotes)
  .then(ui.getQuotesSuccess)
  .catch(ui.failure);
};
```

**Comment by payne-chris-r** [comment]
Is `ui.updateQuoteSuccess` a function? Is it defined?

**Comment by jbuzzanco** [comment]
No its not defined. But neither is `createQuotesSuccess` and `createQuotes` is working

**Comment by payne-chris-r** [comment]
What does `is working` mean?

**Comment by jbuzzanco** [comment]
It is creating a new quote

**Comment by jbuzzanco** [comment]
So I tried to define createQuoteSuccess
cannot get back a id because id is undefined in the console
`TypeError: Cannot read property 'id' of undefined`
here is what i tried
```
const createQuoteSuccess = (quotes) => {
  $('#content').html(showQuotesTemplate(quotes.id, "cool"));
    console.log(quotes);

};
```
I know that I am probably defining it wrong then 😅

**Comment by BenGitsCode** [comment]
Where are you defining quotes. Is it being exported into the file containing the above?

**Comment by BenGitsCode** [comment]
Where are you defining quotes. Is it being exported into the file containing the above code? (did not mean to close this. disacknowledge the closing.)

**Comment by jbuzzanco** [comment]
I think quotes is a url

**Comment by jbuzzanco** [comment]
Quotes is an object

**Comment by payne-chris-r** [comment]
Update: @jbuzzanco has determined `createQuoteSuccess` isn't running at all. He is going to investigate and return back with more...

**Comment by jbuzzanco** [comment]
`  .then(ui.updateQuoteSuccess)
`
is how it is getting called and it is getting exported here.

```
module.exports = {
  showQuotesTemplate,
  getQuotesSuccess,
  createQuoteSuccess,
  updateQuoteSuccess

};
```

**Comment by jbuzzanco** [comment]
`console.log` is running so `updateQuoteSuccess` is running now. just not closing the modal

**Comment by jbuzzanco** [comment]
It is getting the requests that are necessary

**Comment by raq929** [comment]
So, you want updateQuoteSuccess to close the update modal? 
What does updateQuoteSuccess look like now? (i.e. what code are you running in order to close the modal.)

**Comment by jbuzzanco** [comment]
I have tried a lot of different things to close the modal from looking at similar issues on StackOverflow, nothing seems to do hide, remove, removeClass for this. For example:
```
$('#updateModal').modal('close');
  $('.modal-backdrop').remove();
$('body').removeClass('modal-open');
```

**Comment by jbuzzanco** [comment]
For the record, playing around with it, just having `  $('body').removeClass('modal-open');
` in updateQuoteSuccess, allows me to scroll, but wont allow to click on the page or interact as it is still in the modal--the page is grayed out a bit, but can scroll. 💫 . So ya. I'll keep toying, and am open to other things to try 👍

**Comment by jbuzzanco** [comment]
got it to close somehow by running this code exactly. 

```
const updateQuoteSuccess = (quotes) => {
  $('#content').html(showQuotesTemplate(quotes, "cool"));
  api.getQuotes();
  $('#updateModal').modal('hide');
  $('body').removeClass('modal-open');
  $('.modal-backdrop').remove();


  console.log('quotes is', quotes);

};
```
http://stackoverflow.com/questions/11519660/twitter-bootstrap-modal-backdrop-doesnt-disappear
