### ISSUE TITLE
Group Needs Pizza

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/full-stack-project#559]
So was wondering what the group wants in pizza toppings? 🍕 
Issue was supposed to be opened because an instructor who shall remain unnamed asked to open an issue on the pizza toppings.

**Comment by payne-chris-r** [comment]
Reginas.

**Comment by BenGitsCode** [comment]
Please post the names of the pizzas you're trying to receive from the request.

**Comment by payne-chris-r** [comment]
```js
api.getPizzas(order)
  .then(eatMyselfSilly)
  .catch(getMad)
```

**Comment by sujkid** [comment]
We know who that consultant is! Anchovies in his pizza for making you open an issue

**Comment by payne-chris-r** [comment]
Reginas screwed up the order. Run `.catch`

**Comment by BenGitsCode** [comment]
`rm -rf reginas/`

**Comment by payne-chris-r** [comment]
![image](https://cloud.githubusercontent.com/assets/12667121/20868592/43a644a2-ba2d-11e6-9bc7-fa3fc9c40c41.jpeg)

**Comment by payne-chris-r** [comment]
Pizza was gud
