### ISSUE TITLE
Looking for help understanding how to use another site's API

### ISSUE THREAD

**Issue by cwcrane** [ga-wdi-boston/full-stack-project#56]
I am able to get a response using a curl command to the site's API. But it is giving me back xml, and I am not able to understand from the API documentation, how I should be formatting my HTTP requests. Thanks

**Comment by srhoulam** [comment]
Chris, can you link the API docs here?

**Comment by cwcrane** [comment]
https://www.goodreads.com/api/index

**Comment by srhoulam** [comment]
The API doc tells you the following:
- the URL (the path),
- the method,
- the expected parameters (what to put in the body)

for each endpoint.

Can you point to something that is unclear?

**Comment by gaand** [comment]
Have a look at https://github.com/jnunemaker/httparty
