### ISSUE TITLE
PATCH not working - cannot read id of undefined

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/full-stack-project#560]
I'm circling back to the same issue I faced when I first started tackling my CRUD actions, which is that I have to hard-code the id of the object I want to patch in order for the API call to go through. I don't know how to abstract the id of each cheeseplate whose name I want to alter. 

My update cheeseplate name form is being generated via Handlebars, and I tried using a data attribute to call the form from handlebars in my events.js file to no avail.

Here's my code:

api.js
```js
const updateCheeseplate = (data) =>
$.ajax({
  // url: 'https://hidden-lowlands-96809.herokuapp.com/cheeses/1',
  url: app.host + '/cheeseplates/' + data.cheese.id,
  method: 'PATCH',
  // headers: {
  //   Authorization: 'Token token=' + app.user.token,
  // },
  data,
});
```

events.js
```js
const onUpdateCheeseplate = function (event) {
  event.preventDefault();
  // let id = $(this).data().cheeseId;
  // let id = event.target.getAttribute("data-cheeseplate-id");
  // console.log(id);
  let data = getFormFields(event.target);
  api.updateCheeseplate(data)
    .then(ui.updateCheeseplateSuccess)
    .catch(ui.failure);
};

const addHandlers = () => {
  $('.get-all').on('click', onGetAllCheeses);
  $('.create-plate-form').on('submit', onCreateCheeseplate);
  $('.newest-plates').on('submit', '.update-cheeseplate-form', onUpdateCheeseplate);
  $('.newest-plates').on('click', '.delete-cheeseplate-button', onDeleteCheeseplate);
  $('.get-plates').on('click', onGetAllCheeseplates);
 };
```

ui.js
```js
const updateCheeseplateSuccess = (data) => {
  console.log(data);
  $('.newest-plates').html(getCheeseplates(data));
};
```

handlebars 
```js
{{#each cheeseplates as |cheeseplate|}}
<div class="newest-plates">
  <ul class="list-group">
    <li class="list-group-item">
      <p>{{cheeseplate.name}}</p>
      <button type="button" class="delete-cheeseplate-button" data-cheeseplate-id="{{cheeseplate.id}}">Delete Cheeseplate</button>
    </li>
    <li>
      <div class="change-name-of-cheeseplate text-center">
        <p class="lead"> Change the name of this cheese.</p>
          <form class="update-cheeseplate-form">
            <input type="text" class="cheeseplate-name" name="cheeseplate[name]" data-cheeseplate-id="{{cheeseplate.id}}" placeholder="New name">
            <button type="submit" class="change-cheeseplate-button btn btn-default">Submit</button>
          </form>
      </div>
    </li>
  </ul>
</div>
{{/each}}
```

**Comment by raq929** [comment]
Ok, I see where you're setting the cheeseplate ID in the template, but I don't see how you're getting it out. 
getFormFields won't grab that cheeseplate-id attribute for you. 
Look into jQuery's .data method: http://api.jquery.com/jQuery.data/
I would pass the data as one object, and the id as it's own thing to your AJAX call. ie, the api call should take two arguements, data and id.

**Comment by raq929** [comment]
#544 may be helpful for an example.

**Comment by raq929** [comment]
Also, a gotcha with the data attribute, I'm not sure what it will do with that second `-` in `data-cheeseplate-id`. It may turn it into `data-cheeseplateid`, so inspect your html to be sure of what it looks like. (I know it does weird things with capitalization, I'm not sure about dashes.)

**Comment by kiraamaa** [comment]
I was able to solve it by adding another input field for id, and then just using `let data = getFormFields(event.target);` to grab the id and the new name to be patched.
