### ISSUE TITLE
Current User

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/full-stack-project#561]
I thought I had everything working correctly but I checked now and seen that my current user does not work. Now when I try to add a game it gives me an error. 

![screen shot 2016-12-04 at 6 16 22 pm](https://cloud.githubusercontent.com/assets/9563419/20870029/c8e3a7de-ba4d-11e6-92c8-8014a70c67d8.png)

**Comment by gaand** [comment]
What does the server show?

**Comment by Sphilippe7** [comment]
![screen shot 2016-12-04 at 5 54 51 pm](https://cloud.githubusercontent.com/assets/9563419/20870134/53448086-ba50-11e6-8b27-3dad9ecc84f5.png)

**Comment by Sphilippe7** [comment]
@gaand

**Comment by gaand** [comment]
It would be easier if you copied and pasted the test rather than an image.

That message says there isn't a `games` method on `User`.  Please post the user model.

**Comment by Sphilippe7** [comment]
This is what I have in my user model:

```
# frozen_string_literal: true
class User < ActiveRecord::Base
  include Authentication
  has_many :examples
end
```

**Comment by Sphilippe7** [comment]
and this is what is in my games controller:

```
class GamesController < ApplicationController
  before_action :authenticate
  before_action :set_game, only: [:show, :update, :destroy]
  def index
    @games = Game.all

    render json: @games
  end

  def show
    render json: Game.find(params[:id])
  end

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:title, :month, :category, :rating, :platform)
  end

  def create
    @game = current_user.games.build(game_params)

    if @game.save
      render json: @game, status: :created
    else
      render json: @game.errors, status: :unprocessable_entity
    end
  end

  def update
    if @game.update(game_params)
      head :no_content
    else
      render json: @game.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @game.destroy

    head :no_content
  end

  private :set_game, :game_params
end
```

**Comment by gaand** [comment]
This line is probably causing the error:

```ruby
    @game = current_user.games.build(game_params)
```

Because your user model doesn't have

```ruby
has_many :games
```

so rails doesn't know how to build a new game and attach it to the current user.

**Comment by Sphilippe7** [comment]
I put that line in to see if it would work and still got the same error. I also took out the lines and got the same error.

**Comment by gaand** [comment]
Which line?  What did you change?  Did you restart you server when you made the change?  Did you get the same error or a different error?  Did the games migration add a user reference?  Does the games model `belong_to :user`?

**Comment by Sphilippe7** [comment]
my user model is now 

```
# frozen_string_literal: true
class User < ActiveRecord::Base
  include Authentication
  has_many :games
end
```

**Comment by Sphilippe7** [comment]
and my games controller is the same one I posted earlier

**Comment by Sphilippe7** [comment]
same error as the pic above

**Comment by gaand** [comment]
What's the scheme for games?  What does `\d games` show in `bin/rails dbconsole`?

**Comment by Sphilippe7** [comment]
This is what I'm getting now

![screen shot 2016-12-04 at 9 06 38 pm](https://cloud.githubusercontent.com/assets/9563419/20871613/9822059c-ba65-11e6-9188-a2095e56964e.png)

**Comment by gaand** [comment]
The games schema doesn't have a reference to the users table, so games can't be owned by users.

```sh
bin/rails dbconsole # this is where I wanted you to enter `\d games`
bin/rails console # this is what's in the image above
```

You need to add a user reference to games:

```sh
bin/rails generate migration AddUserRefToGames user:reference
bin/rake db:migrate
```

**Comment by Sphilippe7** [comment]
added those and it worked right on time for presentations! Thank you @gaand
