### ISSUE TITLE
heroku/webpack| bootstrap icons arent loading on deployment

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/full-stack-project#563]
I have icons that aren't loading on the deployed gh-pages. 
I believe that this error may have something to do with it. It is pointing to a file I never touched and so leads me to believe there is a chance it is a webpack issue.

_here is the error_
```
/browser-template/e18bbf611f2a2e43afc071aa2f4e1512.ttf:1 GET https://jbuzzanco.github.io/browser-template/e18bbf611f2a2e43afc071aa2f4e1512.ttf 
```

**Comment by neugierige** [comment]
Hi Joel, I don't believe that this is actually the error statement. Are you looking at the backend server in your Terminal? Do you see a statement with the word "error" in it?

**Comment by jbuzzanco** [comment]
Well, it is not an error in the terminal, it is an error in the console. I couldn't look at the terminal to see the error because the I am not hosting it locally, I am hosting it with heroku.

**Comment by jbuzzanco** [comment]
![screen shot 2016-12-06 at 5 19 08 pm](https://cloud.githubusercontent.com/assets/13890937/20946317/352dc90c-bbd8-11e6-8cdf-e0d01198e3f0.png)
![screen shot 2016-12-06 at 5 21 07 pm](https://cloud.githubusercontent.com/assets/13890937/20946377/72f9b14c-bbd8-11e6-825d-70d3593f2005.png)
@gaand if you look at the icons, you can notice a difference. I believe it is because webpack doesn't know where to find them on the deployed site. The first img is a screenshot of the deployed site, the second img is a screenshot of the local site. Do you know why these icons aren't loading?

here is some code of what is showing the buttons
```
<button data-id="{{quote.id}}" class="delete-button btn-danger btn large material-icons">Remove
          <span class="glyphicon glyphicon-trash"></span>
  </button>
```

**Comment by neugierige** [comment]
to clarify, the 1st image is from the app that's deployed, and 2nd image is from the app running locally

**Comment by jbuzzanco** [comment]
resolved. spoke with @gaand, told me to `git add --force` files that were requested in the `GET` request for these icons. Now icons are working. Thanks Antony 😄
