### ISSUE TITLE
POST: 500 Internal Server Error

### ISSUE THREAD

**Issue by matthewgsommers** [ga-wdi-boston/full-stack-project#564]
Hello everyone!

Already attempted solutions: I was working in a study group on Saturday and despite our best efforts, I was unable to find a solution. I've also been reviewing the issue tracker but I cannot place what is going wrong; I think my error is something very specific (you will see below due to the errors occurring on local host vs the deployed version.) 

The way my app should work: My app is an art gallery. Users should be able to sign in and POST an image and data about that image (artist, title, description, location, date photographed). After POSTing, users should be able to view the image and the image's information with a GET, each time the GET button is clicked it should display the next image that was POSTed. Users should be able to comment on the picture for PATCH. Users should be able to DELETE a picture and it's relevant information. Note: POST is required before GET because there is no seed data. 

When I run the app locally, I'm able to GET / POST / PATCH / DELETE to all work (however, I'm having some issues with data ownership at this point as well - I'm able to GET images that other users have uploaded, but not PATCH / DELETE; so that is a contributing factor as well.)

When I attempt to run the app on heroku, I cannot get past the POSTing issue. I know that the backend is running (see links below for back / front), but there must be some form of miscommunication between the back and the front. 

I admittedly did some thrashing this morning and at lunch in an effort to get everything up and running but it clearly did not work and most likely added to my level of confusion, so I'm going to list everything I can think of that could be contributing to this error. 

CONSOLE ERROR MESSAGE: "graffiti-gallery.herokuapp.com//battles/:1 POST https://graffiti-gallery.herokuapp.com//battles/ 500 (Internal Server Error)."

Running Frontend: https://callmelife.github.io/Graffitit-Frontend/
Running Backend: https://graffiti-gallery.herokuapp.com/battles

Remotes on Backend: 
heroku	https://git.heroku.com/graffiti-gallery.git (fetch)
heroku	https://git.heroku.com/graffiti-gallery.git (push)
origin	git@github.com:callmelife/Graffitit-Backend.git (fetch)
origin	git@github.com:callmelife/Graffitit-Backend.git (push)
upstream	git@github.com:ga-wdi-boston/rails-api-template.git (fetch)
upstream	git@github.com:ga-wdi-boston/rails-api-template.git (push)

Remotes on Frontend: 
origin	git@github.com:callmelife/Graffitit-Frontend.git (fetch)
origin	git@github.com:callmelife/Graffitit-Frontend.git (push)

FRONT END CODE: 
**AJAX call in api.js (exported):**
```
const uploadPicture = function(data) {
  return $.ajax({
    url: app.host + '/battles/',
    method: 'POST',
    headers: {
        Authorization: 'Token token=' + app.user.token,
      },
      data,
  });
};

```
**TRIGGERING EVENT in events.js (exported):** 
```
const onUploadPicture = function (event) {
  event.preventDefault();
  let battle = getFormFields(event.target).battle;
  api.uploadPicture({battle})
  .then(ui.uploadPictureSuccess)
  .catch(ui.failure);
  $('.get-picture-button').show();
  $('.delete-btn').show();
};
```

**EXPORTED ADD HANDLER in events.js:** 
```
const addHandlers = () => {
  api.getPicture().then(data => app.items = data);
  // api.uploadPicture().then(data => app.game.id = data.game.id);
  $('#get-picture-form').on('submit', onGetPicture);
  $('#upload-picture-form').on('submit', onUploadPicture);
  $('#delete-btn-form').on('submit', onDeletePicture);
  $(document).on('submit', '#comment-form', onCommentPicture);
};
```

**UI  in ui.js (exported):**
```
const uploadPictureSuccess = (data) => {
  app.items.push(data);
  console.log('Upload is working');
};
```

**HOST INFO in app.js**
```
module.exports = {
  host: 'https://graffiti-gallery.herokuapp.com',
    // host: 'http://localhost:4741',
};
```

BACKEND:
**CREATE action in battles_controller.rb **
```
def create
    p current_user
    @battle = current_user.battles.build(battle_params)
    if @battle.save
      render json: @battle, status: :created
    else
      render json: @battle.errors, status: :unprocessable_entity
    end
  end
```

**USER Model from user.rb**
```
class User < ActiveRecord::Base
  include Authentication
  has_many :battles
end
```

**BATTLE Model from battle.rb**
```
class Battle < ActiveRecord::Base
  belongs_to :user
  #validates :text, :user, presence: true
end
```

**ROUTES info from routes.rb**

```
 Rails.application.routes.draw do
   resources :examples, except: [:new, :edit]
   post '/sign-up' => 'users#signup'
   post '/sign-in' => 'users#signin'
   delete '/sign-out/:id' => 'users#signout'
   patch '/change-password/:id' => 'users#changepw'
   resources :users, only: [:index, :show, :create, :destroy, :update]
   resources :battles
 end

```
Please let me know if I should post any additional information prior to class tomorrow.

**Comment by matthewgsommers** [comment]
Also, when trying to push to gh-pages, I'm receiving the following error: 

~/wdi/graffiti-gladiator-project/browser-template (gh-pages)$ git push origin gh-pages
To git@github.com:callmelife/Graffitit-Frontend.git
 ! [rejected]        gh-pages -> gh-pages (non-fast-forward)
error: failed to push some refs to 'git@github.com:callmelife/Graffitit-Frontend.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I've been Googling "git pull ..." commands and am still attempting to make it work on my end, but I'm a bit confused on how the remote can be ahead of the current branch? 

EDIT: I ran 'git pull origin gh-pages' and received the following response; the short version is that I still cant push to origin gh-pages:

From github.com:callmelife/Graffitit-Frontend
 * branch            gh-pages   -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: Hopefully deploying correctly now.
Using index info to reconstruct a base tree...
.git/rebase-apply/patch:580: trailing whitespace.
	/*
.git/rebase-apply/patch:581: trailing whitespace.
		MIT License http://www.opensource.org/licenses/mit-license.php
.git/rebase-apply/patch:582: trailing whitespace.
		Author Tobias Koppers @sokra
.git/rebase-apply/patch:583: trailing whitespace.
	*/
.git/rebase-apply/patch:584: trailing whitespace.
	// css base code, injected by the css-loader
warning: squelched 291 whitespace errors
warning: 296 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging bundle.js
CONFLICT (add/add): Merge conflict in bundle.js
error: Failed to merge in the changes.
Patch failed at 0001 Hopefully deploying correctly now.
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

**Comment by raq929** [comment]
Can you open a separate issue about the git problem? 
Also, this issue is great, thanks for posting all those things. I'm curious about what the server output is when you attempt to post from the front-end.

**Comment by matthewgsommers** [comment]
This issue isnt relevant anymore, thanks all!
