### ISSUE TITLE
GH Pages Error Message

### ISSUE THREAD

**Issue by rickdean** [ga-wdi-boston/full-stack-project#565]
I've had no issues deploying to GH Pages until this afternoon.  When I deploy my updates (a simple version number update in my index.html) and then try to login to test my app I receive the following console log errors.

```
dependencies.js:9646 Mixed Content: The page at 'https://rickdean.github.io/audio_drama/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:4741/sign-in'. This request has been blocked; the content must be served over HTTPS.
```
and

```
dependencies.js:9646 XMLHttpRequest cannot load http://localhost:4741/sign-in. Failed to start loading.
```

**Comment by raq929** [comment]
If you do what it wants and change `http` to `https`, does it work? 
This may be because you're talking to localhost and not to your heroku app. If when you did it before the api endpoint was your heroku app, and that was https, you wouldn't get this error.

**Comment by rickdean** [comment]
And of course you nailed it.  Thank you Rachel.  Just updated and repushed to GH-Pages.  It took a little while to fully update but the error is now gone.
