### ISSUE TITLE
1-1 Request

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/full-stack-project#566]
I'd like to request a 1-1 to discuss the delete problem found in my submission.

**Comment by raq929** [comment]
Yes, we can definitely do this. @gaand might have time? 
Can you post the code that is creating the race condition? (We might be able to help debug sooner that way, and also for the benefit of future people who have this problem.)

The culprit code is likely in your click handler for creating user's locations. 
Yay race conditions! 🎉

**Comment by coffeeisamazing** [comment]
Sorry, should've updated the ticket. Meeting with @payne-chris-r today or tomorrow. He is familiar with the issue. I'll be sure to post the final outcome back here.

**Comment by payne-chris-r** [comment]
I think we're good on this one now, right @coffeeisamazing ?

**Comment by coffeeisamazing** [comment]
Yes, I'll close now. The root cause was a problem with the logic in my controller - I was returning a different users' location record, so when they went to delete they got a not found as the ID doesn't exist for that user (due to current_user).
