### ISSUE TITLE
Git| No change when go to previous commit

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/full-stack-project#567]
I was trying to add something and then messed up. So wanted to go to a previous commit. Followed along with this
http://stackoverflow.com/questions/4114095/how-to-revert-git-repository-to-a-previous-commit
so `git log`

copy the characters from previous commit
then `git checkout 50db47d1a639022`
it says I am in detatched head. So I open the project with `grunt serve` but it is still the same place as where I was at before. But it still is the same, and I know because I updated the navbar in the latest changes I made and they are still there in the latest commit. Anyone know why going back isn't actually working?

**Comment by raq929** [comment]
Not sure why it's not working, but I have some ideas for figuring it out. 
First checkout back to your head by doing `git checkout <whateveryourbranchwas>
First, maybe the last commit wasn't what you think it was? Check out your commit messages from the log. 
You can use `git show jlkjlerj` to show you what commit `jlkjlerj` changed.
You can also use the commit hash (that's the big letter/number string that you see with each commit on the log) to see the diff between two commits.
So, you can do `git diff a23jkjfn lksfd343` to see what changed between commit `a23jkjfn` and commit `lksfd343`.
(You only need about 6 characters from a commit - that's usually unique enough for git to know which one you're talking about.)
Try figuring it out using some of these techniques and let us know how it goes.

**Comment by jbuzzanco** [comment]
Okay. I tried these, and went back to multiple commits. As well as different branch names (which I remember to have different features).  It seems that my differerent branches and commits are in the same point in the development process, even though I remember them to be at different points.

**Comment by raq929** [comment]
I'm not sure from this comment what you tried.
Can you be more specific about that?
What is the problem you're having now?

**Comment by jbuzzanco** [comment]
Ok. Sorry if it was unclear. Basically tried `git log` then copied the string from the commit that I wanted to go back to, then `git checkout <that string>`
Also tried to `git checkout feature` (to a earlier branch that wasn't up to date with what I was working on), but it seemed to be at the same point as well. 
I found out what was wrong, which is what made me want to go back to a commit in the first place, so I am just going to close this issue if that's okay.
