### ISSUE TITLE
Using a migration to add a column to parks table

### ISSUE THREAD

**Issue by HoldenMills** [ga-wdi-boston/full-stack-project#57]
I am trying to add a token model and password_digest model (from Antony's project2 api).  I created a new migration;

```
class AddAuthenticationToUsers < ActiveRecord::Migration
  def change
    add_column :token, null: false, index: {unique: true } :string
    add_column :password_digest, null: false, :string
  end
end
```

when I run 'rake db:migrate', It gives me the error message;

rake aborted!
SyntaxError: /Users/Photon/WDI/project2/nps_app/db/migrate/20151111204645_add_authentication_to_users.rb:3: syntax error, unexpected ':', expecting keyword_end
    add_column :token, null: false, index: {unique: true } :string
                                                            ^
/Users/Photon/WDI/project2/nps_app/db/migrate/20151111204645_add_authentication_to_users.rb:4: syntax error, unexpected ':', expecting keyword_end
    add_column :password_digest, null: false :string
                                              ^

```
```

**Comment by GA-MEB** [comment]
Not the right syntax for `add_column`. Should be
`add_column :table_name, :column_name, :column_type, ... (other_options)`
