### ISSUE TITLE
Trouble finalizing data structures - Rails 

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/full-stack-project#570]
I think I've finally structured my data properly with tables for users, cheeseplates, cheeses_on_plates, and cheeses. Each user has many cheeseplates, which have many cheeses through cheeses_on_plates. Cheeses have many cheeseplates through cheeses_on_plates as well. 

What I'm now struggling with is testing how/if my structures work. I'm unable to create a curl request to create a cheeses_on_plate, and I'm now (expectedly) getting a 500 server error on my front end when I try to issue an index call to see all cheeseplates. How do I begin to solve this? What do you need to see to understand the underlying problems?

**Comment by gaand** [comment]
I would not have a controller for cheeses on plates  Just plates.  Index action for the list of a users plates. Show for one plate and it's cheeses (through cheeses on plates). Create makes a new plate. Update adds or removes a cheese from a plate (through cheeses on plates). 

I hope that helps.

**Comment by neugierige** [comment]
When it comes to testing data models and the associations, I find it easiest to do this in the rails console. I assume that your goal is to verify that cheeseplates are indeed owned by a user, and that existing cheese objects can be added to your cheeseplate. 

I would try to simulate the sequence of CRUD actions that you would want your app to perform. For example, you could start with assigning a user object to a variable, create a cheeseplate for the user, assign a cheese object to a variable, then add a cheese to that specific cheeseplate via cheese_on_plate. Then check the cheese_on_plate model to verify that it has been added, and that that object has references to the correct plate and cheese ids. And also check that that specific plate now includes that specific cheese (i.e. `silky_plate.cheeses`).

**Comment by kiraamaa** [comment]
Okay so thus far I have:
1.  assigned a user object to a variable
2. created a cheeseplate for the user
3. assigned a cheese object to a variable

I don't know how to add a cheese to that specific cheeseplate via cheese_on_plate, or how to check the cheese_on_plate model to verify that it has been added, and that that object has references to the correct plate and cheese ids.

**Comment by kiraamaa** [comment]
@gaand are you sure I don't need a cheese_on_plates controller? I'm very confused as to how I would show or update a plate using just plates.

**Comment by neugierige** [comment]
can you share the code you used to accomplish 1-3? 

remember, to parallel the book/borrower/loan analogy: 
`book == cheese`
`borrower == cheeseplate`
`loan == cheese_on_plate`

In class, we did `Loan.all` to see all the loans, and `borrower.loans` to see an array of loans on that borrower.

**Comment by gaand** [comment]
I'll have a look.

**Comment by gaand** [comment]
Went over having patch/update to cheese plate as add or remove cheese on plate.

**Comment by kiraamaa** [comment]
Still having trouble getting action to work. I have forms set up on each cheese plate such that a user can enter in a cheese id and a cheese plate id and ostensibly add the cheese to the cheese plate. However, the ids of both are returning as undefined, and I'm getting this message on my back end server:
```
Started PATCH "/cheeseplates/20" for ::1 at 2016-12-09 16:22:49 -0500
Processing by CheeseplatesController#update as */*
  Parameters: {"id"=>"20"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "82cd8146ecb135937ec5280dcefe60c9"]]
  Cheeseplate Load (0.3ms)  SELECT  "cheeseplates".* FROM "cheeseplates" WHERE "cheeseplates"."user_id" = $1 AND "cheeseplates"."id" = $2 LIMIT 1  [["user_id", 1], ["id", 20]]
Completed 400 Bad Request in 7ms (ActiveRecord: 0.5ms)

ActionController::ParameterMissing (param is missing or the value is empty: cheese):
  app/controllers/cheeseplates_controller.rb:13:in `edit_plate_params'
  app/controllers/cheeseplates_controller.rb:38:in `update'


  Rendered /Users/kiraamaa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (8.4ms)
  Rendered /Users/kiraamaa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (5.1ms)
  Rendered /Users/kiraamaa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (8.8ms)
  Rendered /Users/kiraamaa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (89.1ms)
```

**Comment by kiraamaa** [comment]
``` ruby
def edit_plate_params
    params.require(:cheese).permit(:id, :cheese, :add, :remove)
  end

  def update
    if edit_plate_params[:add]
      @cheeseplate.cheeses_on_plates.build(edit_plate_params[:id])
    elsif edit_plate_params[:remove]
      cheese_on_plate = @cheeseplate.cheeses_on_plates.find(edit_plate_params[:id])
      @cheeseplate.cheeses_on_plates.delete(cheese_on_plate)
    else

    end

    if @cheeseplate.save
      head :no_content
    else
      render json: @cheeseplate.errors, status: :unprocessable_entity
    end
  end
```

**Comment by gaand** [comment]
What does you're form look like?

**Comment by raq929** [comment]
What's your status on this, @kiraamaa ?

**Comment by gaand** [comment]
I should have commented on Friday that we worked through using the `has_many :cheeses, through: cheeses_on_plates` relationship to update the `cheesplate`.

**Comment by kiraamaa** [comment]
So sorry; just realized I never closed this. I resolved my issues by adding 
```
def update
    if params[:add]
      cheese = Cheese.find(edit_plate_params[:id])
      @cheeseplate.cheeses.push(cheese)
    elsif params[:remove]
      cheese = @cheeseplate.cheeses.find(edit_plate_params[:id])
      @cheeseplate.cheeses.delete(cheese)
    else
      render json: @cheeseplate.errors, status: :unprocessable_entity
    end
```
I can now add a cheese to a cheese plate using cheese ID.
