### ISSUE TITLE
Heroku Problem

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/full-stack-project#575]
Instructions are:
1 Go to the root of your repo and run ```heroku create```
2 View your remotes by typing ```git remote -v```
3 what you should see is:
```    
    heroku  git@heroku.com:agile-badlands-7658.git (fetch)
    heroku  git@heroku.com:agile-badlands-7658.git (push)
    origin  git@github.com:tdyer/wdi_4_rails_hw_tdd_hacker_news.git (fetch)
    origin  git@github.com:tdyer/wdi_4_rails_hw_tdd_hacker_news.git (push)
``` 

I have followed the steps and I am not getting the response  the repo says I am suppose to get as only get back half of step 3:

```
$ heroku create
Creating app... done, ⬢ mighty-coast-17672
https://mighty-coast-17672.herokuapp.com/ | https://git.heroku.com/mighty-coast-17672.git
~/wdi/projects/daily-boulders-rails-api (master)
$  git remote -v
heroku	https://git.heroku.com/frozen-coast-36495.git (fetch)
heroku	https://git.heroku.com/frozen-coast-36495.git (push)
~/wdi/projects/daily-boulders-rails-api (master)
$
```

**Comment by BenGitsCode** [comment]
It looks like you don't have an origin remote? Is that what you mean by the other half?

**Comment by doremaxime** [comment]
yes

**Comment by doremaxime** [comment]
It now works. There is a step not mentioned in the rails-heroku-setup-guide repo which is to start a new repo in github, follow the steps to new repo in github, and then continue the rails-heroku-setup-guide instructions.
