### ISSUE TITLE
lost with user resource

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/full-stack-project#577]
One of my resources is **user**. i believe I have to create a table, controller, model, etc.. for user. However, in the template, that is already created but differently. 
I see my user table being with the following columns: **id**, **first_name**, **last_name**, and **email**. However there is a user_serializer that has the attributes of **id** and **email** already.. 
I am very confused as to what we are suppose to create/overwrite if anything for users. 
so do i create another index.sh, controller, model, etc..? but if so, how to differentiate between the two sets?

**Comment by jrhorn424** [comment]
> I am very confused as to what we are suppose to create/overwrite if anything for users.

You should not be scaffolding `User` for anything. You should edit the `User` resource if necessary.

However, `User` should be strictly reserved for authentication concerns. If collecting names is absolutely necessary, it should be done as part of a different resource, `Profile` or some such.

Other good generic names:

- `Person`
- `Biography`
- `Address` (if you're only storing addresses)

**Comment by doremaxime** [comment]
In class with Chris we had some **user** resources (fatih, mario, and myself) so is there a user resource for the rails API and a user resource for the Auth API?
If it is only one **user** resource for both and I edit it for the rails api, won't it affect the other?
collecting names is not necessary.

**Comment by raq929** [comment]
I'm not sure I understand this question. Did you get it answered? If yes, please post what you learned. 
You only have one api... what Jeff is saying is that users can have a profile that has a one-to-one relationship with user, where you add that extra info, so it doesn't affect auth. I would consider it a stretch goal.

**Comment by doremaxime** [comment]
No I did not get answered. 
I don't see how I would make a relation between my **climb** resource and **user** resource without affecting the **user** resource. Isn't the **user** resource only for the auth? 
Basically, as a user, I want to be able to create a climb. So the user needs to have a relation with climb.

**Comment by raq929** [comment]
You can have relationships between the use and other resources without
making major changes to the model. If you look at the examples model and
the user model, they have a relationship. I'd also take a look at the
examples controller to see how examples are built. Note which controller
examples inherits from.

**Comment by doremaxime** [comment]
Ok, so we can't scaffold the user, but we have to make the {create, index, show, update, delete}.sh right?

**Comment by raq929** [comment]
I see you reopened. What's up?

**Comment by doremaxime** [comment]
Ok, so we can't scaffold the user, but we have to make the {create, index, show, update, delete}.sh right?

**Comment by raq929** [comment]
Nope. Users are created by sign-up. They already have an index method, I believe, and possibly a show. There's curl scripts in `rails-api-template`. If you give more specifics about what you're trying to do I might be able to help more.

**Comment by doremaxime** [comment]
Sorry i'm not getting this. 
So as a user, I want to be able to create climbs

**Comment by raq929** [comment]
Is this answered in #586? 
If no, I'm not quite sure what you're asking here.

**Comment by doremaxime** [comment]
to me they are two different things but they could be the same to someone who gets it. we can just close this issue and maybe i'll get it later with #586.
