### ISSUE TITLE
Request 1-on-1

### ISSUE THREAD

**Issue by newayliu1** [ga-wdi-boston/full-stack-project#578]
I  came up a new ERD for my project. I would like to have a 1-on-1.

**Comment by bernardlee** [comment]
I think that there are talks all day today.  If the talks finish early, then I can meet with you.

**Comment by raq929** [comment]
Please post your new ERD, and tell us a bit about what you want to discuss. We can meet tomorrow morning.

**Comment by MicFin** [comment]
@newayliu1  Has this 1on1 happened yet?
