### ISSUE TITLE
1-1 

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/full-stack-project#579]
hey guys, do any of you have time for a 1-1 today? I have wireframe and user stories but I have questions about what exact things to define in my table vs what I need for create or update

**Comment by bernardlee** [comment]
I think that there are talks all day today.  If the talks finish early, then I can meet with you.

**Comment by ggabrakadabra** [comment]
what about after class?

**Comment by bernardlee** [comment]
I've some time after class.

**Comment by MicFin** [comment]
@ggwilliams has this 1on1 happened yet?
