### ISSUE TITLE
Weird issue on update

### ISSUE THREAD

**Issue by gotwilk890** [ga-wdi-boston/full-stack-project#58]
When I update my table it DOES update and then throws a 500 internal server error right after. I then realized that the row that was updated is sent to the end of my table and my tables ID column is all out of order. Any ideas would be appreciated.

**Comment by GA-MEB** [comment]
What's your schema? What models do you have?

**Comment by gotwilk890** [comment]
SCHEMA
```ActiveRecord::Schema.define(version: 20151110165435) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "guides", force: :cascade do |t|
    t.string   "name",       null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
  end

  add_index "guides", ["name"], name: "index_guides_on_name", unique: true, using: :btree
  add_index "guides", ["user_id"], name: "index_guides_on_user_id", using: :btree

  create_table "questions", force: :cascade do |t|
    t.text     "question",   null: false
    t.string   "answer",     null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "guide_id"
  end

  add_index "questions", ["guide_id"], name: "index_questions_on_guide_id", using: :btree

  create_table "users", force: :cascade do |t|
    t.string   "email",           null: false
    t.string   "token",           null: false
    t.string   "password_digest", null: false
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
  end

  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["token"], name: "index_users_on_token", unique: true, using: :btree

  add_foreign_key "guides", "users"
  add_foreign_key "questions", "guides"
end```

**Comment by gotwilk890** [comment]
models are user, guides, and questions

**Comment by gotwilk890** [comment]
When I try to PATCH(update) guides it updates and then shoots an error and throws whatever row I updated to the end of my table

ex.
I update row 1

it gets updated and sent down to the end of my table.

ids now read

2,3,4,1

**Comment by GA-MEB** [comment]
Sure. In your table, it always lists in order of most recently updated.

[EDIT] Thought it was always, but I guess it's not guaranteed.

**Comment by GA-MEB** [comment]
OK, let's backtrack a bit. 
1. Have you looked over the databases using `rails db`? Is their structure correct?
2. Have you successfully performed CRUD on all three tables in `rails c` using the models?
3. Does your API work successfully with `curl`/Postman?

**Comment by gotwilk890** [comment]
Good to know about the order thing!

1.yes
2.yes
3.sort of, it does the update and saves it but the server shoots out a 500 error right after

**Comment by gaand** [comment]
The order of rows is only guaranteed when you explicitly order them.

**Comment by gaand** [comment]
What's the error?  What does it show in the terminal where you ran `rails s`?

**Comment by gotwilk890** [comment]
Completed 500 Internal Server Error

**Comment by gaand** [comment]
Is that all it says? No other info?

**Comment by GA-MEB** [comment]
Are you using a serializer with that request?

**Comment by gotwilk890** [comment]
I am not. Could that be the cause of it? 

Im trying to dig deeper into the error on chrome console for you guys.

**Comment by gotwilk890** [comment]
Ya only thing it shoots out is "Internal server error"

**Comment by gotwilk890** [comment]
This is what my server says. Should I just ignore it seeing that it does update my row like its supposed to?

`Started PATCH "/guides/1" for ::1 at 2015-11-11 17:41:24 -0500
Processing by GuidesController#update as HTML
  Parameters: {"guide"=>{"name"=>"HISTORY"}, "id"=>"1"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "79e2dc7083e289f20e2d17399ea7941a"]]
  Guide Load (19.4ms)  SELECT  "guides".* FROM "guides" WHERE "guides"."user_id" = $1 AND "guides"."id" = $2 LIMIT 1  [["user_id", 1], ["id", 1]]
   (0.2ms)  BEGIN
  SQL (0.8ms)  UPDATE "guides" SET "name" = $1, "updated_at" = $2 WHERE "guides"."id" = $3  [["name", "HISTORY"], ["updated_at", "2015-11-11 22:41:24.447933"], ["id", 1]]
   (0.6ms)  COMMIT
Completed 500 Internal Server Error in 60ms (Views: 1.8ms | ActiveRecord: 21.4ms)`

**Comment by gaand** [comment]
Does update call `head` or `render`?  If not, that's the problem.

**Comment by gotwilk890** [comment]
it does unfortunately 

```class GuidesController < ApplicationController

  #GET /guides
  def index
    render json: current_user.guides
  end
  #POST /guides
  def create
    guide = current_user.guides.create(guide_params)
    if guide.save
      render json: guide, status: :created
    else
      render json: guide.errors, status: :unprocessable_entity
    end
  end

  #PATCH /guides/id
  def update
    guide = current_user.guides.find(params[:id])
    if guide.update_attributes(guide_params)
      render json: guide, status: :updated
    else
      render json: guide.errors, status: :unprocessable_entity
    end
  end

  #DELETE /guides/id
  def destroy
    current_user.guides.find(params[:id]).destroy
    head :no_content
  end

private

  def guide_params
    params.require(:guide).permit(:name)
  end
end```

**Comment by gaand** [comment]
What are you routes for guides?

**Comment by gotwilk890** [comment]
Rails.application.routes.draw do
  post '/register' => 'auth#register'
  # patch '/confirm' => 'auth#confirm'
  post '/login' => 'auth#login'
  delete '/logout/:id' => 'auth#logout'

  resources :users, except: [:new, :edit]
  resources :guides, except: [:new, :edit]
  resources :questions, except: [:new, :edit]
end

**Comment by gaand** [comment]
I won't be in until later and I think this might require active debugging.  Are you able to work on other aspects of your project?

**Comment by gotwilk890** [comment]
Ya everything works it just likes to throw that error after it works

**Comment by gaand** [comment]
Okay.  I'm happy to help debug once I'm in.  If it becomes pressing you should ask someone who's there.

**Comment by gotwilk890** [comment]
Thanks Antony

**Comment by GA-MEB** [comment]
@gotwilk890 I'm free right now and can help with this. Should I come find you?

**Comment by gotwilk890** [comment]
Issue was that upon completion I was sending a status code that did not exist.

after changing the status code to an actual status code the 500 error disappeared.

Mystery solved gang
