### ISSUE TITLE
Is it possible to reset/revert to the original repository?

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#582]
I did a scaffold, but I want to have less attributes than I originally set up to keep it simple. Can I go back to the blank API template?

**Comment by BenGitsCode** [comment]
What have you tried? For instance, this is a good start. http://bit.ly/2lQW4oO

**Comment by raq929** [comment]
How is this going, Alex? Please close if it's no longer an issue.

**Comment by BenGitsCode** [comment]
Any updates here Alex?

**Comment by alexkarasik** [comment]
Sorry, I just deleted the extra parameters in my files manually. I still need to look up how to properly do this, but I did what needed to be done.
