### ISSUE TITLE
1 on 1

### ISSUE THREAD

**Issue by cshea93** [ga-wdi-boston/full-stack-project#583]
If the schedule is not already full, I would love to have my one on one tomorrow afternoon at some point!

Let me know. Thanks.

**Comment by bernardlee** [comment]
Do you have the required materials (wireframes, user stories, ERDs, etc.) ready?

**Comment by MicFin** [comment]
@cpstrillvt93 has this 1on1 happened yet?

**Comment by cshea93** [comment]
I do have them ready. I am giving them a look over right now to try and get a better visualization of what I have to do. Can we meet in a bit?

**Comment by MicFin** [comment]
10:15 in the kitchen

**Comment by cshea93** [comment]
sounds good !

**Comment by cshea93** [comment]
For my 1 on 1, Mike and I walked through my ERD's and user stories. Instead of having a Shows table to pull from, like I had originally planned, the user will now just add his/her own shows to the show table. This should help cut down on the number of user stories and relationships I have to develop to meet requirements. My next move is to get my authorization forms in order. After that I will get a dummy client for adding/showing shows on the webpage. Will check in for a 1on1 again after I complete those steps.
