### ISSUE TITLE
ruby Array#first method returning an array

### ISSUE THREAD

**Issue by samordonez** [ga-wdi-boston/full-stack-project#585]
I am trying to write some tests for my api resources, specifically in this case the Book resource. I have already tested this resource fairly thoroughly with curl scripts, so all of the tests, if written correctly, should probably pass. My question is that when it gets to the following test:

```
it 'renders a JSON response' do
  books_collection = JSON.parse(response.body)
  expect(books_collection).not_to be_nil
  expect(books_collection.first['title']).to eq(book.title)
end
```

Through some `puts` magic I discovered that `books_collection.first` seems to be returning an array that looks something like `[books, <the actual book object>]` when in theory it should be just return the book object in question as per the [ruby docs](https://ruby-doc.org/core-2.2.0/Array.html#method-i-first).

Am I missing something about how the `#first` method works or is my api actually returning things in the wrong format? For reference, the index action is written thus:

```
# GET /books
def index
  @books = Book.all

  render json: @books
end
```

Edit for clarity:
A test is failing that should in theory be passing. I don't know rspec well enough to be sure if the problem is with how I wrote the test or with the api itself. The error I am getting is
```
2) Books GET index renders a JSON response
     Failure/Error: expect(books_collection.first['title']).to eq(book.title)
     
     TypeError:
       no implicit conversion of String into Integer
     # ./spec/requests/books_spec.rb:38:in `[]'
     # ./spec/requests/books_spec.rb:38:in `block (3 levels) in <top (required)>
```

**Comment by MicFin** [comment]
Is there an error that is coming up or a failing test that you think should pass?  What caused you to need to `puts` to inspect the collection?

**Comment by samordonez** [comment]
Yes, a test is failing that should in theory be passing. I don't know rspec well enough to be sure if the problem is with how I wrote the test or with the api itself. The error I am getting is
```
2) Books GET index renders a JSON response
     Failure/Error: expect(books_collection.first['title']).to eq(book.title)
     
     TypeError:
       no implicit conversion of String into Integer
     # ./spec/requests/books_spec.rb:38:in `[]'
     # ./spec/requests/books_spec.rb:38:in `block (3 levels) in <top (required)>
```
I wasn't sure why it would need to be converting strings into integers which is why I added `puts` statements to see what it was actually returning. Apparently `books_collection.first['title']` is not a thing that exists. What I just now realized it that because `books_collection.first` is an array, it is trying to convert 'title' into an index number.

**Comment by raq929** [comment]
I suspect your serializer is returning something like: `{ books: [] } ` instead of `[]`. So you'll need to look at `response.body['books']` or some such.

**Comment by raq929** [comment]
Other things that might be going wrong, are you sure you created a book in your test setup?

**Comment by raq929** [comment]
Also, I'd encourage you to timebox the testing. If you've tested with curl, that's probably OK, and you can come back to add more testing later. Testing is awesome, and can help you get exceeds, but make sure you have time to the requirements, and you can come back to the tests.

**Comment by samordonez** [comment]
I definitely created a book, since I can get the information I'm looking for out of the book I am comparing against. `response.body['books']` is failing with a JSON.parse error
```
 2) Books GET index renders a JSON response
     Failure/Error: books_collection = JSON.parse(response.body['books'])
     
     JSON::ParserError:
       784: unexpected token at 'books'
     # ./spec/requests/books_spec.rb:34:in `block (3 levels) in <top (required)>
```
but that makes sense. When I change the parse line to
````
books_collection = JSON.parse(response.body)['books']
```
it works.
