### ISSUE TITLE
Migration issue. Validation failed: User must exist

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/full-stack-project#586]
I have been stuck for a couple hours on create a relationship.
Goal: user to have many climbs and climbs to belong to a user.

My models:
```
class User < ApplicationRecord
  include Authentication

  has_many :examples
  has_many :climbs
end


class Climb < ApplicationRecord
  belongs_to :user

  validates :date, presence: true
  validates :grade, presence: true
end
```

20170217141649_add_user_to_climbs:
```
class AddUserToClimbs < ActiveRecord::Migration[5.0]
  def change
    add_reference :climbs, :user, index: true, foreign_key: true
  end
end
```

When I run **rake db:nuke_pave** I get the following error:
```
Dropped database 'daily-boulders-api_development'
Dropped database 'daily-boulders-api_test'
Created database 'daily-boulders-api_development'
Created database 'daily-boulders-api_test'
== 1 CreateUsers: migrating ===================================================
-- create_table(:users, {})
   -> 0.0418s
== 1 CreateUsers: migrated (0.0420s) ==========================================

== 2 CreateExamples: migrating ================================================
-- create_table(:examples, {})
   -> 0.0434s
== 2 CreateExamples: migrated (0.0436s) =======================================

== 20170215205556 CreateClimbs: migrating =====================================
-- create_table(:climbs)
   -> 0.0198s
== 20170215205556 CreateClimbs: migrated (0.0200s) ============================

== 20170217141649 AddUserToClimbs: migrating ==================================
-- add_reference(:climbs, :user, {:index=>true, :foreign_key=>true})
   -> 0.0291s
== 20170217141649 AddUserToClimbs: migrated (0.0293s) =========================

rake aborted!
ActiveRecord::RecordInvalid: Validation failed: User must exist
/Users/MD/wdi/projects/daily-boulders-rails-api/db/examples.rb:25:in `block in <top (required)>'
/Users/MD/wdi/projects/daily-boulders-rails-api/db/examples.rb:21:in `each'
/Users/MD/wdi/projects/daily-boulders-rails-api/db/examples.rb:21:in `<top (required)>'
/Users/MD/wdi/projects/daily-boulders-rails-api/lib/tasks/db.rake:5:in `require_relative'
/Users/MD/wdi/projects/daily-boulders-rails-api/lib/tasks/db.rake:5:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:nuke_pave => db:examples
(See full trace by running task with --trace)
```

I ran **db:examples** as indicated at the end of the message plus to make sure that I do have so fill in data to develop with but I am getting the same error message.

**Comment by raq929** [comment]
Are you seeding data? It looks like you might be trying to create climbs without giving them user ID. 
Can you post the examples.rb file?

**Comment by doremaxime** [comment]
```
%w(antony jeff matt jason).each do |name|
  email = "#{name}@#{name}.com"
  next if User.exists? email: email
  User.create!(email: email,
               password: 'abc123',
               password_confirmation: nil)
end

%w(V2 V8 V9 V4).each do |climb|
  # date = '2017-02-10'
  # grade = climb
  next if Climb.exists? grade: climb
  Climb.create!(date: '2017-02-10',
                grade: climb)
end
```

**Comment by doremaxime** [comment]
I get the same error with: 
```
$ bin/rake db:drop db:create db:migrate db:seed db:examples

```

When i do them one at a time i only get the error when it do the last one (examples)

**Comment by raq929** [comment]
Awesome. Your migration worked just fine, or you wold have had an error on `db:migrate`. It's just that you're trying to create some climbs without assigning a user to them, which you've made invalid. I you've created some example users, so I would find one them and use them to create the climb. 

I would do it similarly to the way the examples controller creates examples:
```ruby
user = User.first # or last, or whatever you want
user.climbs.build(climb_params)
```
You'll have to set the params, of course.

**Comment by ggabrakadabra** [comment]
Or couldn't you just add user_id to the params in your controller?

  def climb_params
    params.require(:climb).permit(:title, :user_id)
  end

**Comment by raq929** [comment]
The problem with that is that it opens you up to malicious users changing the climb's user id. So it's not best practices (and could lead to big trouble if your app was, say, about bank accounts).

You can use user id in your examples file in the way that Gabby is suggesting, though.

**Comment by doremaxime** [comment]
I currently have:
```
  def create
    @climb = Climb.new(climb_params)

    if @climb.save
      render json: @climb, status: :created
    else
      render json: @climb.errors, status: :unprocessable_entity
    end
  end
```
and
```
  def set_climb
    @climb = Climb.find(params[:id])
  end
  private :set_climb
```
is that what you both recommended i do?

**Comment by raq929** [comment]
You'll need to do it the way that the examples controller does, using `current_user` and `build` rather than `create`.

**Comment by raq929** [comment]
But the controller is a separate issue.
This issue is about seed data, so let's concentrate on that for now.

**Comment by doremaxime** [comment]
So you mean that the climb in examples.rb is faulty?

**Comment by raq929** [comment]
Yep. You can fix it with the code I posted above.

**Comment by doremaxime** [comment]
but i thought the code below went in the controller no?
```user = User.first # or last, or whatever you want
user.climbs.build(climb_params)
```


So do you mean something like this in examples.rb:
```
%w(V2 V8 V9 V4).each do |climb|
  user = User.first
  next if Climb.exists? grade: climb
  user.climbs.build(date: '2017-02-10',
                    grade: climb,
                    user_id: user)
end
```

**Comment by raq929** [comment]
If you do `user.climbs.build`, you don't need the user_id field. 
If you do it with `Climb.create`, you will need it.

**Comment by doremaxime** [comment]
ok, I made it work by scrapping the loop because i couldn't make it and replaced it with:
```
Climb.create!(date: '2010-01-01', grade: 'V1', user_id: 1)
Climb.create!(date: '2019-09-09', grade: 'V9', user_id: 2)
Climb.create!(date: '2017-02-10', grade: 'V0', user_id: 3)
Climb.create!(date: '2018-08-08', grade: 'V8', user_id: 4)
```

i believes it worked because they all showed when doing **Climb.all** in **bin/rails console**

nuke_pave now completes
