### ISSUE TITLE
scaffold

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/full-stack-project#587]
I created a scaffold for a comments table. I tested each script on this table to make sure it works (index, create, destroy, show, update) But now I want to make it a join table. In the many to many repo, we have a command
```rb
rails g scaffold loan borrower:references book:references date:datetime
```

so I want to run this command,

```
rails g scaffold comments movie:references user:references date:datetime
```
but what does this mean for the other comments table? Or should I make a new table called review and then run 

```rb
rails g scaffold reviews movie:references user:references date:datetime 
```

and then just forget about the last comments table I made? Or if I run the scaffold comments command, will it make the connections for me and then can I run 
bin/rails db:drop db:create db:mirgrate db:seed db:examples?

Or can I just run 
```rb
bin/rails generate model comments user:references movie:references?
```

**Comment by raq929** [comment]
Cool. I'm not entirely sure what you're trying to do. 
You have a movies table and a users table, and you want to join them via either comments or reviews, yes? 
I would pick either comments or reviews for this project.
If comments, yeah, I would get rid of the table you generated (there's a rails command that does the opposite of generate; I don't remember it off the top of my head, but it's googleable.)
and then you can do `rails g scaffold comments movie:references user:references date:datetime`.

Let me know if you need clarification!

**Comment by ggabrakadabra** [comment]
so if I wanted to undo my previous scaffold, stackoverflow says run 

```rb
rails destroy scaffold MyFoo
```

so for me to destroy my old scaffold I need to run 

```rb
bin/rails destroy scaffold comments comment:string
```
and then run 

```rb
rails g scaffold comments movie:references user:references date:datetime.
```
to create my join table?

**Comment by MicFin** [comment]
@ggwilliams I want to teach you how to write code examples in Github comments.  I am coming to see you.
