### ISSUE TITLE
1-on-1 - Project planning, ERD & Wireframes

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/full-stack-project#588]
I would like to schedule a 1-on-1 today to review some questions I have on the tables for my models and my wireframes before I get started on my making my API.

![bookie_nook - erd](https://cloud.githubusercontent.com/assets/24688275/23070825/59717254-f4fa-11e6-8fb6-0ea0da78991f.png)

**Comment by raq929** [comment]
Cool. What are your questions? 
I would start this with _just_ one join table: choose either reviews or myBooks and do that. If you have extra time, add the other table.

**Comment by AshlenPrice** [comment]
OK here are all the questions I have written down as I have been planning.

- Data, I have had a hard time finding a .csv database of books, might you know where I can find one? 
- Once I have one would you recommend I  add a csv to my project if I want to have pre-populated data?
- Should I model my relationships differently based on what you see? 
- Can we review the CRUD Actions on my table based on the user stories? I want to make sure I have them right.
- Should I join the profile table to books instead of it being the user table?
-  How to add multiple reviews to 1 book? 
- is there another way of a user having favorites/personal book list other than making a join table? 
- Does a personal book list need to have additional information?

Also do my wireframes too ambitious
![img_0494 jpg](https://cloud.githubusercontent.com/assets/24688275/23074417/a8b28054-f506-11e6-9f43-9282fd5d0d4c.jpeg)
?

**Comment by raq929** [comment]
OK, come find me, I'm in classroom 6

**Comment by raq929** [comment]
Please update and close!

**Comment by AshlenPrice** [comment]
Thanks for helping me de-scope and prioritize my tables! 
![img_0499 jpg](https://cloud.githubusercontent.com/assets/24688275/23079586/8dbb39d4-f51b-11e6-8e7b-b03fc514ddce.jpeg)
