### ISSUE TITLE
Error making update/create requests in rspec tests

### ISSUE THREAD

**Issue by samordonez** [ga-wdi-boston/full-stack-project#589]
When making my request tests for my api, I copied over the rspec tests we had written yesterday in the rails-bdd lesson. Initially none of the tests were even properly making requests, I was getting a whole bunch of errors that looked like this:
```
2) Books PATCH update is successful
     Failure/Error:
       patch :update, params: { id: book.id, book: book_diff },
                      format: :json
     
     ArgumentError:
       unknown keyword: format
     # ./spec/requests/books_spec.rb:83:in `block (3 levels) in <top (required)>'
```

For index, show and destroy I was able to change the requests themselves from this format
```
before(:each) do
  post :create, params: { book: new_book }, format: :json
end
```
to a format like this
```
before(:each) { get "/books/#{book.id}" }
```
and they subsequently worked. However I am not sure how to change the update and create requests, which require me to send data alongside the request, into that format, or why I even need to for the tests to work. The original format worked in the lesson yesterday so I don't understand why it is failing now with what looks like an error in the routing.

edit: [link to my actual repository and relevant branch](https://github.com/Sofistication/reading-list-api/tree/book-crud)

**Comment by bernardlee** [comment]
Do you have an up-to-date branch of your repository that I can look at?

**Comment by raq929** [comment]
Yeah, I'm actually confused about why `format: :json` was working during our lesson yesterday. You should just take it off your tests.  I think it's a holdover from a previous version of Rails/Rspec.

**Comment by samordonez** [comment]
I'll commit my most recent changes in a second. I did take the `format: :json` part off and it was still failing, I only added it back in today to see what would happen.

**Comment by samordonez** [comment]
All changes have been pushed to the `book-crud` branch

edit: [the actual repo](https://github.com/Sofistication/reading-list-api/tree/book-crud)

**Comment by raq929** [comment]
Link to the repo?

**Comment by samordonez** [comment]
I changed the offending line to 
```
before(:each) do
  patch "/books/#{book.id}", params: { book: book_diff }
end
```
and it worked. Turns out I copied over code from the wrong rspec file.

**Comment by raq929** [comment]
Sweet. Please close the issue!

**Comment by samordonez** [comment]
Oops, meant to do that with that comment.
