### ISSUE TITLE
handlebar and managing different forms in my front end

### ISSUE THREAD

**Issue by gracenjambi** [ga-wdi-boston/full-stack-project#59]
I am looking to add different forms that will help in adding data to the backend. I think handlebars is the right way to handle this but I need guidance.

I have tried following the tutorial and I have been working on this for about an hour, then I thought it best to discuss out loud what I am trying to do, so that I can come up with the most efficient way to handle these actions in my front end, which will populate the information added to the back end.

**Comment by GA-MEB** [comment]
Are you trying to use Handlebars to create the forms? How does it fit in?

**Comment by gracenjambi** [comment]
I am using handle bars to dynamically add information. Say if it is equipment i am trying to make equipments be added and stored in a table where you can add or delete rows depending on whether you need the equipments.

**Comment by GA-MEB** [comment]
Handlebars is explicitly for the purpose of generating HTML. It doesn't sound like that's the problem you're trying to solve. Can you be more precise?

**Comment by srhoulam** [comment]
``` js
// document is ready
// global variable `templates` exists and contains an object
// global variable `views` exists and contains an object

templates.garden = Handlebars.compile($("#garden-template").html());
templates.crop = Handlebars.compile($("#crop-template").html());
// now we can do, e.g.:
// templates.garden({
//     name : "Hanging Garden of Babylon"
// });

views.crop = $("my-crop");


// example of usage with ajax
// to display data retrieved from the back-end
$.ajax({
    method : "GET",
    url : "http://localhost:3000/crops",
    dataType : "json"
}).done(function(data) {
    views.crop.html(templates.crop(data));
});

```
