### ISSUE TITLE
scaffold created has_one 

### ISSUE THREAD

**Issue by cob0910** [ga-wdi-boston/full-stack-project#590]
I did a scaffold for my table and instead of putting the referenced table as an attribute it put it as a has_one:

```
class IdeaSerializer < ActiveModel::Serializer
  attributes :id, :title, :where, :price, :notes, :status
  has_one :giftee
end
```

As compared to what we did in class which looks like this, doctors is an attribute and we had to define doctors

```
class PatientSerializer < ActiveModel::Serializer
  attributes :id, :name, :diagnosis, :born_on, :doctors

  def doctors
    object.doctors.pluck(:id)
  end
end
```

I am trying to find out what/why has_one was generated here instead of the attribute/def way but cannot figure out if they are used for different situations or just alternatives that would both work?

**Comment by cob0910** [comment]
Here is my terminal entry from when I did the scaffold

```
[10:22:12] ~/wdi/projects/gift-list/rails-api-template:(relationships)$ rails g scaffold idea giftee:references title:string where:string price:float notes:string status:integer
Running via Spring preloader in process 40744
Expected string default value for '--serializer'; got true (boolean)
      invoke  active_record
      create    db/migrate/20170217152242_create_ideas.rb
      create    app/models/idea.rb
      invoke    rspec
      create      spec/models/idea_spec.rb
      invoke  resource_route
       route    resources :ideas
      invoke  serializer
      create    app/serializers/idea_serializer.rb
      invoke  scaffold_controller
      create    app/controllers/ideas_controller.rb
      invoke    rspec
      create      spec/controllers/ideas_controller_spec.rb
      create      spec/routing/ideas_routing_spec.rb
      invoke      rspec
      create        spec/requests/ideas_spec.rb
```

**Comment by MicFin** [comment]
Can you post the `db/migrate/20170217152242_create_ideas.rb`?

**Comment by cob0910** [comment]
```
class CreateIdeas < ActiveRecord::Migration[5.0]
  def change
    create_table :ideas do |t|
      t.references :giftee, foreign_key: true
      t.string :title
      t.string :where
      t.float :price
      t.string :notes
      t.integer :status

      t.timestamps
    end
  end
end
```

**Comment by raq929** [comment]
I suspect this serializer will return the idea with a field `giftee` that is the whole giftee object. What we did for doctors is just return the doctor's id. I'd try creating some ideas (either in Rails console or as seed data) and doing a curl request to see if you're getting the info you want.

**Comment by cob0910** [comment]
thanks for helping!

**Comment by cob0910** [comment]
so I think I understand what you are saying Rachel

I think the way we did it in class is how I want my tables to interact too so it looks like I need to redo my table and use giftee_id:integer instead of of giftee:references

```
[09:47:07] ~/wdi/training/rails-api-clinic-code-along:(training)$ bin/rails generate scaffold appointments date:date time:timestamp doctor_id:integer patient_id:integer
```

**Comment by raq929** [comment]
Serializers have nothing to do with how your tables look, they just determine how your data is sent to the person making the HTTP request. So I'd try it and see if it's what you want.
