### ISSUE TITLE
Changing GitHub Repo and redirecting remote to new repo address

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/full-stack-project#592]
Hey, 
So I changed my Github repo name for my API, and I googled how to do that. I used this [link](https://help.github.com/articles/renaming-a-repository/). 
I followed those steps and I changed the name locally. I checked out to my master branch before doing the `$ git remote set-url origin new_url` command. My question is when I redirected the remote repo to the new one does it also take all the branches created too?

**Comment by raq929** [comment]
You'll have to push the branches to the new url.

**Comment by BenGitsCode** [comment]
It will take all of the branches you push to it. 

A git remote is just a pointer. When you change it or add a different one, it's just pointing your push to a different location. 

Is this resolved?

**Comment by AshlenPrice** [comment]
Awesome Thanks everyone!
