### ISSUE TITLE
Ownership set up question 

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/full-stack-project#593]
Just want to double check-- If I'm trying to make it so each user has_one athlete, the command to create the migration would be
`bin/rails generate migration AddUserIdToAthletes user:references` ?
Where each athlete is linked to one user ID? or is the other way around recommended?

**Comment by MicFin** [comment]
You want to identify what the two way relationship is.

If you want the relationship to be `Athlete belongs_to User` and `User has_one Athlete` then you would want to do:

```
bin/rails generate migration AddUserToAthletes user:references
``` 

Which will generate the following migration:

```rb
class AddUserToAthletes < ActiveRecord::Migration
  def change
    add_reference :athletes, :user, index: true
  end
end
```

That migration adds a `user_id` column to the `Athletes` table.

Then you will need to set the `belongs_to` in the `Athlete.rb` and `has_one` in the `User.rb`.

Read this :)  It's great info on has_one and belongs_to.
http://requiremind.com/differences-between-has-one-and-belongs-to-in-ruby-on-rails/

**Comment by raq929** [comment]
How is this going, Lauren?

**Comment by laurpaik-zz** [comment]
much better! I'll file another issue if I have another question!

**Comment by laurpaik-zz** [comment]
@dsweetser
