### ISSUE TITLE
change_column_null -Recommended method?

### ISSUE THREAD

**Issue by s0phi4** [ga-wdi-boston/full-stack-project#595]
I created my table called resources, and I created an instance of the model to test it. It worked fine. I went to look at the schema and realized that I forgot to add null:false in my columns. I do not want to drop my table and I saw this is a solution for my issue
**change_column_null :table_name, :column_name, false**
I have googled this solution and some people do not recommend it because it makes an irreversible migration. 

Do you recommend the above approach?

**Comment by raq929** [comment]
Why don't you want to drop your table? That seems like the easiest solution.

**Comment by s0phi4** [comment]
I could modify my last migration by adding null: false to the columns and then go to the terminal and run 'bin/rails db:nuke_pave '

**Comment by raq929** [comment]
Yeah, I think that's an easier option.

**Comment by raq929** [comment]
Yen, did that work for you? If yes, please let us know and close the issue. If not, please update.

**Comment by s0phi4** [comment]
`bin/rails db:nuke_pave` worked!  :)

Thanks!
