### ISSUE TITLE
Can't open atom through terminal...?

### ISSUE THREAD

**Issue by cshea93** [ga-wdi-boston/full-stack-project#596]
I am suddenly unable to open a directory using the atom . command in terminal....any insight?

**Comment by bernardlee** [comment]
What's the error that you're getting?

**Comment by cshea93** [comment]
command not found

**Comment by bernardlee** [comment]
Be sure to close the issue once it has been resolved.

**Comment by cshea93** [comment]
Reinstalled atom. Seemed to fix the problem. Still not 100% sure why problem occurred.
