### ISSUE TITLE
request 1 on 1 - populating data

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/full-stack-project#598]
I have my trail tests done  and would like some guidance about how we are populating the data and how the schema works.

**Comment by Soboscott** [comment]
I also would like to ask a few questions about the Heroku website and the servers we will be using

**Comment by raq929** [comment]
These are two different issues.  Please open a separate issue for Heroku, and tell us what questions you want to ask. (This makes it easier for people with future issues to find info that's relevant to them.)

What do you want to know about populating data?

The schema is generated by rails. It will automatically update when you change your tables. DO NOT EDIT IT MANUALLY.

**Comment by Soboscott** [comment]
Ok ,
I have the trails and users samples in the seed.rb and am having trouble with the migration command bin/rails db migrate seeds.rb examples.rb ...that's not right i'm looking at the rubyonrails.org/command_line.html but I am stuck

**Comment by raq929** [comment]
Please put your commands in backtics.

I think the commands here are what you're looking for? https://github.com/ga-wdi-boston/rails-api#creating-a-blog-api

**Comment by MicFin** [comment]
@Soboscott what is that status of this?

**Comment by Soboscott** [comment]
I think I have the trails db created and migrated but am not sure which file to test with the sh...

**Comment by MicFin** [comment]
Take a look at the solutions from the BDD demo.

Curl script for a resource 
https://github.com/ga-wdi-boston/rails-api-bdd/blob/solution/scripts/get-examples.sh

Requests tests for a resource
https://github.com/ga-wdi-boston/rails-api-bdd/blob/solution/spec/requests/articles_spec.rb

Routing tests for a resource
https://github.com/ga-wdi-boston/rails-api-bdd/blob/solution/spec/routing/articles_spec.rb

Controller tests for a resource
https://github.com/ga-wdi-boston/rails-api-bdd/blob/solution/spec/controllers/articles_spec.rb

Model tests for a resource
https://github.com/ga-wdi-boston/rails-api-bdd/blob/solution/spec/models/article_spec.rb

**Comment by Soboscott** [comment]
so do I need to create a new get_trails.sh?

**Comment by Soboscott** [comment]
when I run the test I get this error:
when we did the bdd repo we didn't go over GET #new
```Failures:

  1) TrailsController GET #new assigns a new trail as @trail
     Failure/Error: get :new, params: {}, session: valid_session
     
     ActionController::UrlGenerationError:
       No route matches {:action=>"new", :controller=>"trails"}
     # ./spec/controllers/trails_controller_spec.rb:57:in `block (3 levels) in <top (required)>'

  2) TrailsController routing routes to #new
     Failure/Error: expect(get: '/trails/new').to route_to('trails#new')
     
       The recognized options <{"controller"=>"trails", "action"=>"show", "id"=>"new"}> did not match <{"controller"=>"trails", "action"=>"new"}>, difference:.
       --- expected
       +++ actual
       @@ -1 +1 @@
       -{"controller"=>"trails", "action"=>"new"}
       +{"controller"=>"trails", "action"=>"show", "id"=>"new"}
     # ./spec/routing/trails_routing_spec.rb:11:in `block (3 levels) in <top (required)>'```

**Comment by BenGitsCode** [comment]
Please format your code snippets in block format per https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by BenGitsCode** [comment]
Is this issue about populating data or sending a GET request?
