### ISSUE TITLE
OpenReadController causing tests to fail

### ISSUE THREAD

**Issue by samordonez** [ga-wdi-boston/full-stack-project#599]
This is admittedly another issue where I'm unsure if the problem is my code or my tests. Similar to what was discussed in #586 I need users to own books they have created. I have changed my books controller to inherit from OpenReadController and made the relevant adjustments in code (namely the use of current_user).

Now my tests do not appear to be authenticating properly, I am getting a ton of errors that look like this
```
1) BooksController GET #index assigns all books as @books
     Failure/Error: book = Book.create! valid_attributes
     
     ActiveRecord::RecordInvalid:
       Validation failed: User must exist, User can't be blank
     # ./spec/controllers/books_controller_spec.rb:61:in `block (3 levels) in <top (required)>'
```

From what I understand, this is due to Rails not finding the correct user, but I don't understadn why this is happening. Based on the users files, I am making the requests like this
```
before(:each) do
  patch "/books/#{book.id}", params: { book: book_diff }, headers: headers
end
```
where further up in the test file I have
```
  def headers
    {
      'HTTP_AUTHORIZATION' => "Token token=#{@token}"
    }
  end

  def user_params
    {
      email: 'alice@example.com',
      password: 'foobarbaz',
      password_confirmation: 'foobarbaz'
    }
  end

  def book_params
    {
      title: '1984',
      author: 'George Orwell',
      published_in: 1949
    }
  end

  def book
    Book.first
  end

  before(:all) do
    post '/sign-up', params: { credentials: user_params }
    post '/sign-in', params: { credentials: user_params }
    @token = JSON.parse(response.body)['user']['token']

    Book.create!(book_params)
  end
```

**Comment by raq929** [comment]
Are you sure the token is being set correctly?

**Comment by samordonez** [comment]
I'm incredibly unsure about that, but there's actually something I can do to test that.

**Comment by samordonez** [comment]
It appears that the token is in fact not being set correctly, but I'm unsure where I need to move it in order for it to set correctly. I have tried doing the sign-up sign-in inside the headers function and that still does not work. I also moved the headers function to be after the user_params to no avail.

**Comment by raq929** [comment]
Issue #135 might help?

**Comment by samordonez** [comment]
That is helpful except that I am unsure what file they're referring to that gave the person the solution...

**Comment by gaand** [comment]
Have you tried accessing the action via `curl`?

**Comment by samordonez** [comment]
I think I have actually figured it out, I was not storing the user information in a place where all of the things that needed to access it could do so, and I needed to pass the whole user object when creating a sample book, since I was not using a request to create it.
