### ISSUE TITLE
Unknown attribute error

### ISSUE THREAD

**Issue by novakw267** [ga-wdi-boston/full-stack-project#601]
I am getting ActiveModel::UnknownAttributeError (unknown attribute 'title' for BlogTemplate.):
  
app/controllers/blog_templates_controller.rb:21:in `create'

so I want straight to that code to check for spelling errors or anything not matching up appropriately and I can't find a reason for this error everything seems in place. 

controller
```
def create
  line 21  @blog_template = BlogTemplate.new(blog_template_params)

    if @blog_template.save
      render json: @blog_template, status: :created, location: @blog_template
    else
      render json: @blog_template.errors, status: :unprocessable_entity
    end
  end

  def blog_template_params
    params.require(:blog_template).permit(:title, :subject, :body)
  end
end
```
model 
```
# frozen_string_literal: true

# :nodoc:
class BlogTemplate < ApplicationRecord
  validates :title, presence: true
  validates :subject, presence: true
  validates :body, presence: true
end
```
create.sh
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/blog_templates"
curl "${API}${URL_PATH}" \
  --include \
  --request POST\
  --header "Content-Type: application/json" \
  --data '{
    "blog_template": {
      "title": "'"${title}"'",
      "subject": "'"${subject}"'",
      "body": "'"${body}"'"
    }
  }'
```
routes 
```
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :blog_templates, except: [:new, :edit]
  resources :profiles
  resources :profiles, except: [:new, :edit]
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end
```
my create template
```
# frozen_string_literal: true

class CreateBlogTemplates < ActiveRecord::Migration[5.0]
  def change
    create_table :blog_templates do |t|
      t.string :title, null: false
      t.string :subject, null: false
      t.text :body, null: false

      t.timestamps null: false
    end
  end
end
``` 
So I know I am probably missing something small. However I had two other students look over this code as well and we couldn't find the error. 

command line  code
```
title='metal rules' subject='Reasons list' body='Reasons coming soon keep on waiting!' sh scripts/blog_templates/create.sh
``` 
I apologize for the long post but I didn't know which parts would be useful to figure this out.

**Comment by raq929** [comment]
DO NOT APOLOGIZE FOR THIS POST. It is a _great_ issue that includes all the relevant code. Thank you!

**Comment by raq929** [comment]
Can you make a blog template from the rails console?

**Comment by gaand** [comment]
Have you run `\d blog_template` from `bin/rails dbconsole`.

**Comment by novakw267** [comment]
Thank you, Rachel was able to figure out that title is a protected ruby template. So the table was not recording what I was trying to put into it. After we changed title to something different it was able to receive data.

**Comment by raq929** [comment]
Ruby symbol, not ruby template. And probably it's a rails thing, not a ruby thing. 😄

**Comment by jrhorn424** [comment]
Title is not a reserved word (https://reservedwords.herokuapp.com/words?utf8=✓&q%5Bword_or_notes_cont%5D=title). Can you provide a link? @raq929
