### ISSUE TITLE
Moved repository on git push?

### ISSUE THREAD

**Issue by jwaskow** [ga-wdi-boston/full-stack-project#606]
I originally named my api repo 'animal-sighting-logbook', then realized that the name wasn't specific enough because I needed to have my front end repo as well.  So, I renamed the api repo to 'animal-sighting-logbook-api' on github.  When I make a commit and push, I get this message in the terminal:

```
$ git push origin post_table
Counting objects: 14, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (14/14), done.
Writing objects: 100% (14/14), 1.63 KiB | 0 bytes/s, done.
Total 14 (delta 10), reused 0 (delta 0)
remote: Resolving deltas: 100% (10/10), completed with 10 local objects.
remote: This repository moved. Please use the new location:
remote:   https://github.com/jwaskow/animal-sighting-logbook-api.git
git staTo https://github.com/jwaskow/animal-sighting-logbook.git
   82cc203..999e290  post_table -> post_table
```

As far as I can tell, the 'animal-sighting-logbook-api' repo on github gets correctly updated with the commits and changes from the push.  Should I do anything about the `Please use the new location:
remote:   https://github.com/jwaskow/animal-sighting-logbook-api.git` part of the message, even though it seems everything is pushing correctly?

**Comment by MicFin** [comment]
Check this out
https://help.github.com/articles/changing-a-remote-s-url/

**Comment by raq929** [comment]
Yeah, you should do what it says.

**Comment by jwaskow** [comment]
Thanks! I changed it, closing issue.
