### ISSUE TITLE
trying to use handlebars for deleting a list

### ISSUE THREAD

**Issue by moshiko1988** [ga-wdi-boston/full-stack-project#608]
i am creating a todo list app and im trying to reuse the handlebar code that we practice in class to create a delete  button for every list that im creating.
im not really sure if im doing it in the right way.

this is what i have so far in the handlebar file : 

```handlebars
{{#each lists as |list|}}


   <ul data-id="{{list.id}}">
     <li> <small>Title: {{list.title}}</small></li>
     {{#if list.description}}
        <li>{{list.description}}</li>
     {{else}}
        <li>No description.</li>
      {{/if}}
      <li><button id="destroy-book"type="button" name="button">Remove</button></li>
   </ul>

{{/each}}

```

and this is what i have in the ui.js file : 

```ui.js
const onCreateSuccess = function (data) {
  console.log(data);
  console.log('List was successfully created.');
  let showListsHtml = showListTemplate({ lists: data.lists });
$('.content').append(showListsHtml);
};
```

if i could get a direction of how to start. thanks

**Comment by moshiko1988** [comment]
also - i manage creating a list and removing a list by double click on it. the problem is that when i create a list i have the create button attached to it so it POST the request but when i delete im not sure where to pass the id of the delete button.

i prefer to use the double click to remove a list rather then create a delete button on handlebar.
if you could look at my code first and help me decide how to approach it:


```index.js
$(document).ready(
      function(){
          $('#create-book > button').click(
              function(){
                  let toAdd = $('#create-book > div > input[type="text"]').val();
                   $('ol').append('<li>' + toAdd + '</li>');
              });
  });



        $(document).on('dblclick','li', function(){
          $(this).toggleClass('strike').fadeOut('slow');
        });

});```

**Comment by raq929** [comment]
I'm confused about your handlebars file because I don't see any html in it. You can put the list Id in a data attribute on the html of your button.

**Comment by BenGitsCode** [comment]
I'm jumping in late and on my phone while on the T so please excuse any
typos , but the first thing that jumps to my mind is that's cool that you
prefer a double click, but would a user? Because I en you click on anything
on site and receive none

—
*Ben Adamski | Developer in Residence*
General Assembly Boston | 125 Summer Street, Boston MA 02210
ben.adamski@generalassemb.ly | xxx-xxx-xxxx |

Gain access to our grads. https://profiles.generalassemb.ly/

**Comment by MicFin** [comment]
@moshiko1988 please go back and style the code in your comments with the proper format shown [here](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting) so instead of appearing like this 


`$(document).ready(
      function(){
          $('#create-book > button').click(
              function(){
                  let toAdd = $('#create-book > div > input[type="text"]').val();
                   $('ol').append('<li>' + toAdd + '</li>');
              });
  });



        $(document).on('dblclick','li', function(){
          $(this).toggleClass('strike').fadeOut('slow');
        });

});
`

It appears like this


```js
$(document).ready(function(){
    $('#create-book > button').click(function(){
        let toAdd = $('#create-book > div > input[type="text"]').val();
        $('ol').append('<li>' + toAdd + '</li>');
    });
});

$(document).on('dblclick','li', function(){
    $(this).toggleClass('strike').fadeOut('slow');
});
```

**Comment by moshiko1988** [comment]
@MicFin thanks. i was wondering why its not working well .

**Comment by MicFin** [comment]
In your handlebars template you are looping through lists and creating a `ul` and eventually `button` to delete for every list.  That button gets created multiple times if there are multiple lists.

```js
{{#each lists as |list|}}


   <ul data-id="{{list.id}}">
     <li> <small>Title: {{list.title}}</small></li>
     {{#if list.description}}
        <li>{{list.description}}</li>
     {{else}}
        <li>No description.</li>
      {{/if}}
      <li><button id="destroy-book" type="button" name="button">Remove</button></li>
   </ul>

{{/each}}
```

Every button inside the loop is being given the same ID.  In HTML only 1 element can have an ID of a specific name.
```html
<li><button id="destroy-book" type="button" name="button">Remove</button></li>
```

Please review the Handlebars repo and specifically how we added IDs to elements.  Also, consider using a Class instead of an ID if you want every `button` have the same click event applied.

https://github.com/ga-wdi-boston/handlebars/blob/solution/assets/scripts/templates/book-listing.handlebars

**Comment by raq929** [comment]
Issue #623 may help as well.

**Comment by raq929** [comment]
What's your status with this issue?

**Comment by moshiko1988** [comment]
@raq929 im trying to go back to the original code that i had and making the handlebars work.
sill working on it

**Comment by raq929** [comment]
If you post what you're working on now, and what the current problem is, we'd be happy to help you figure it out.

**Comment by moshiko1988** [comment]
@raq929 i have been looking at the issue #623 and i am having the same problem of showing the lists on the page.

```ui.js

const showListTemplate = require('../templates/listing.handlebars');

const getListSuccess = (data) => {
  console.log(data);
  let showListHtml = showListTemplate({ lists: data.lists });
  $('.content').append(showListHtml);

};
 ```
handlebars
``` handlebars

{{#each notes as |list|}}

  <ul data-id="{{list.id}}">
    <li><h1 data-id="{{list.id}}"> <small>note: {{note.list}}</li>
  <li><button type="button" name="button">Remove</button></li>
  </ul>

{{/each}}
```

```html
    <div id="content" class="content">
    </div> 
```

i added content into the div to check that its showing and i get the table of the lists on console but it dosnt show on the page

**Comment by raq929** [comment]
On this line: `let showListHtml = showListTemplate({ lists: data.lists });`
You are passing your template data as `lists`.
But in your template: `{{#each notes as |list|}}` you are expecting `notes`. Those have to be the same things.
Also, it looks like you are mixing up note and list within the template.

But again, I would take this step by step.
1. Comment out what you have. 
1. Make sure you can display a template with just a div and some text in it.
1. Make sure you can send data to the template. Display just `{{ lists }}` (Or notes, whichever you decide to call it.)
1. Uncomment your for loop, but not the things in it. Put in your div and text and be sure that prints for each item you have.
1. Uncomment what you have in the loop.

**Comment by moshiko1988** [comment]
thanks it worked.

```handlebars


{{#each lists as |list|}}

  <ul data-id="{{list.id}}">
    <li><h1 data-id="{{list.id}}">{{list.note}}</li>
  <li><button type="button" name="button">Remove</button></li>
  </ul>

{{/each}}
```

```ui.js

const showListTemplate = require('../templates/listing.handlebars');

const getListSuccess = (data) => {
  console.log(data);
  let showListHtml = showListTemplate({ lists: data.lists });
  $('.content').append(showListHtml);

};
```
