### ISSUE TITLE
development.log

### ISSUE THREAD

**Issue by novakw267** [ga-wdi-boston/full-stack-project#609]
My development.log is trying to get me to commit it to my repo??? Is there a way to get it to not come up when I do git status or do I just have to not commit it?

**Comment by bernardlee** [comment]
This shouldn't be happening since `rails-api-template-master` comes with a `.gitignore` file with `/log` as an entry.  Did you modify or remove `.gitignore`?

**Comment by BenGitsCode** [comment]
Bernard is right. Run 'cat .gitignore'and paste the output here.

**Comment by raq929** [comment]
I suspect you used finder to copy the temple instead on using the command line, and therefore didn't copy the hidden files, like the linter config and the . gitignore. You'll need to copy those files into your repo.

**Comment by BenGitsCode** [comment]
Please review the instructions.

**Comment by novakw267** [comment]
This is the response when I ran cat.gitignore. I did follow the instructions because it says to rename the file and move into the new project and then git init. Which is what I did. You're correct I did not use the command line, I literally took the entire unzipped file rails-api-template and moved it into my projects folder and renamed it. Does unzipping it create hidden files outside of the main folder of rails-api-template when you unzip it? Not trying to be rude or anything I am legit curious because I didn't know that if it did. 
```
### macOS ###
*.DS_Store
.AppleDouble
.LSOverride

# Icon must end with two \r
Icon
# Thumbnails
._*
# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent
# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk


### Linux ###
*~

# temporary files which can be created if a process still has a handle open of a deleted file
.fuse_hidden*

# KDE directory preferences
.directory

# Linux trash folder which might appear on any partition or disk
.Trash-*

# .nfs files are created when an open file is removed but is still being accessed
.nfs*

# End of https://www.gitignore.io/api/macos,linux

# Created by https://www.gitignore.io/api/ruby

### Ruby ###
*.gem
*.rbc
/.config
/coverage/
/InstalledFiles
/pkg/
/spec/reports/
/spec/examples.txt
/test/tmp/
/test/version_tmp/
/tmp/

# Used by dotenv library to load environment variables.
# .env

## Specific to RubyMotion:
.dat*
.repl_history
build/
*.bridgesupport
build-iPhoneOS/
build-iPhoneSimulator/

## Specific to RubyMotion (use of CocoaPods):
#
# We recommend against adding the Pods directory to your .gitignore. However
# you should judge for yourself, the pros and cons are mentioned at:
# https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control
#
# vendor/Pods/

## Documentation cache and generated files:
/.yardoc/
/_yardoc/
/doc/
/rdoc/

## Environment normalization:
/.bundle/
/vendor/bundle
/lib/bundler/man/

# for a library or gem, you might want to ignore these files since the code is
# intended to run in multiple environments; otherwise, check them in:
# Gemfile.lock
# .ruby-version
# .ruby-gemset

# unless supporting rvm < 1.11.0 or doing something fancy, ignore this:
.rvmrc

# End of https://www.gitignore.io/api/ruby

# Created by https://www.gitignore.io/api/rails

### Rails ###
*.rbc
capybara-*.html
.rspec
/log
/tmp
/db/*.sqlite3
/db/*.sqlite3-journal
/public/system
/coverage/
/spec/tmp
**.orig
rerun.txt
pickle-email-*.html

# TODO Comment out this rule if you are OK with secrets being uploaded to the repo
# config/initializers/secret_token.rb

# Only include if you have production secrets in this file, which is no longer a Rails default
# config/secrets.yml

# dotenv
# TODO Comment out this rule if environment variables can be committed
.env

## Environment normalization:
/.bundle
/vendor/bundle

# these should all be checked in to normalize the environment:
# Gemfile.lock, .ruby-version, .ruby-gemset

# unless supporting rvm < 1.11.0 or doing something fancy, ignore this:
.rvmrc

# if using bower-rails ignore default bower_components path bower.json files
/vendor/assets/bower_components
*.bowerrc # shouldn't be an issue in rails-api repositories
bower.json # same

# Ignore pow environment settings
.powenv

# Ignore Byebug command history file.
.byebug_history

# End of https://www.gitignore.io/api/rails
```

**Comment by bernardlee** [comment]
What is the output when you run `ls -A` in the directory?

**Comment by novakw267** [comment]
.gitignore	CONTRIBUTING.md	README.md	config		public
..		.remarkrc	Gemfile		Rakefile	config.ru	scripts
.editorconfig	.rspec		Gemfile.lock	STYLE.md	db		spec
.env		.rubocop.yml	LICENSE		app		lib		tmp
.git		.ruby-version	Procfile	bin		log

so .gitignore seems to be there but I don't know if that is what you're looking for

**Comment by novakw267** [comment]
Oh wait hold on, nevermind ignore that last comment before that bernard I ran that in the wrong command line. I had my clinic-api open, I got "cat: .gitignore: No such file or directory" which Means I definitely do not have the .gitignore.

**Comment by bernardlee** [comment]
You can create it manually and paste the contents from [rails-api-template-master/.gitignore](https://raw.githubusercontent.com/ga-wdi-boston/rails-api-template/master/.gitignore).

**Comment by novakw267** [comment]
So just to clarify all I do is make a .gitignore file in my main directory and copy that page you linked into it?

**Comment by bernardlee** [comment]
That and any other files that you might be missing.

**Comment by novakw267** [comment]
I copied the other files over that I was missing, and it is still requesting that I commit my development.log. It seemed like I was missing 
```
 .editorconfig
  .remarkrc
 .rubocop.yml
 .ruby-version
.respec
```
in addition to the .gitignore

**Comment by bernardlee** [comment]
Run `ls -A` and paste the output.

**Comment by novakw267** [comment]
```
.		.git		.ruby-version	Procfile	bin		log
..		.gitignore	CONTRIBUTING.md	README.md	config		public
.DS_Store	.remarkrc	Gemfile		Rakefile	config.ru	scripts
.editorconfig	.rspec		Gemfile.lock	STYLE.md	db		spec
.env		.rubocop.yml	LICENSE		app		lib		tmp
``` 
this is what I received.

**Comment by bernardlee** [comment]
Now run `git status` and paste the output.

**Comment by novakw267** [comment]
```
$ git status
On branch join_table
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   log/development.log
	modified:   tmp/pids/server.pid

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by bernardlee** [comment]
`git reset` and then `git status`.

**Comment by novakw267** [comment]
```
$ git status
On branch join_table
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   log/development.log
	modified:   tmp/pids/server.pid

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by bernardlee** [comment]
`git rm --cached -- log/development.log tmp/pids/server.pid`
`git status`

**Comment by novakw267** [comment]
```
$ git rm --cached -- log/development.log tmp/pids/server.pid
rm 'log/development.log'
rm 'tmp/pids/server.pid'
~/wdi/projects/forum-project-backend (join_table)
$ git status
On branch join_table
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	deleted:    log/development.log
	deleted:    tmp/pids/server.pid
```

**Comment by bernardlee** [comment]
Commit and write a good subject line and message body.

**Comment by bernardlee** [comment]
Your `.env` file is in your remote repository as well.

**Comment by novakw267** [comment]
That seemed to have worked, I ran another couple of commands to try and build some new data in the development.log and then ran git status and it did not come up in the que. So I think that last bit solved the issue, does that sound about right?

**Comment by novakw267** [comment]
Oh, it hadn't updated with your last comment.  Should I run the previous line again for that file?
Or can I just delete the file from my repo?

**Comment by raq929** [comment]
You need your `.env` file with secrets for your app to run. I would delete it using `git rm .env`, commit that deletion, then recreate it with NEW SECRETS. It **should not appear** when you type `git status` because it should be in the `.gitignore.` 

Your original have been compromised since they were committed to your repo, and anyone can go back in your commit history and find them. (Which means they could steal people's passwords much more easily, among other things.)
