### ISSUE TITLE
PATCH/update coming back undefined

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/full-stack-project#610]
My PATCH/update works in my rails api however it is currently coming back as **undefined** in the front end. 
I expect to get back a **204** so that when i do an index i would confirm the change.
I believe the solution lies in the API with the **data** being passed. I do not think it is the **data.climb.id** that creates this issue as if it were wrong it should get back a different issue.

Events:
```
const onUpdate = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.update(data)
    .then(ui.updateSuccess)
    .catch(ui.updateFailure)
    ;
};

const addHandlers = () => {
  $('.update-climb').on('submit', onUpdate);
};

module.exports = {
  onUpdate,
  addHandlers,
};
```

API:
```
const update = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/climbs/' + data.climb.id,
    method: 'PATCH',
    data,
  });
};
```

UI:
```
const updateSuccess = (data) => {
  console.log(data);
};

const updateFailure = (data) => {
  console.log(data);
};
```

HTML:
```
      <form class="update-climb">
        <fieldset>
          <legend>update Climb</legend>
          <input type="text" name="climb[id]" placeholder="id">
          <input type="text" name="climb[date]" placeholder="date: e.g. 2000-12-20">
          <input type="text" name="climb[grade]" placeholder="gade: e.g. V3">
          <input type="submit" name="submit" value="update Climb">
        </fieldset>
      </form>
```

**Comment by doremaxime** [comment]
News!
It is actually updating the data! Even though it is coming back as undefined.
when i hit index again i see the data has changed.
Not sure why that is.... i'll leave the issue up in case someone puts a reason. i'll close if there is nothing  by the late am tomorrow.

**Comment by raq929** [comment]
Sweet! Update just sends a success status with no content, so that's why your data is undefined.
