### ISSUE TITLE
CREATE works in rails console but not in terminal

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/full-stack-project#611]
I am able to create an instance of the resource **climb** in the **bin/rails console** but when I try to do it with a terminal command I am getting an error and therefore not in the browser either.
I expect my command to create a climb. 
I believe the solution may lie in the command, which I may be making a mistake in.

create.sh:
```
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/climbs"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "climb": {
      "date": "'"${DATE}"'",
      "grade": "'"${GRADE}"'"
      }
    }' # \
  # --header "Authorization: Token token=$TOKEN"

echo
```

controller:
```
  # POST /climbs
  def create
    @climb = current_user.climbs.build(climb_params)

    if @climb.save
      render json: @climb, status: :created
    else
      render json: @climb.errors, status: :unprocessable_entity
    end
  end

  def set_climb
    @climb = current_user.climbs.find(params[:id])
  end
  private :set_climb

  def climb_params
    params.require(:climb).permit(:date, :grade, :id, :user_id)
  end
  private :climb_params
```

model:
```
class Climb < ApplicationRecord
  belongs_to :user

  validates :date, presence: true
  validates :grade, presence: true
end
```

command I have tried (also restarted server):
```
DATE="1111-11-11" GRADE="V1" sh scripts/climbs/create.sh
DATE="1111-11-11" GRADE="V1" USER_ID="1" sh scripts/climbs/create.sh
ID=5 DATE="1111-11-11" GRADE="V1" USER_ID="1" sh scripts/climbs/create.sh
ID=5 DATE="1111-11-11" GRADE="V1" USER_ID=1 sh scripts/climbs/create.sh
```

Error message in terminal:
```
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
X-Request-Id: 829201d6-905f-43fd-b0c2-aa5e7d7739a9
X-Runtime: 0.246300
Vary: Origin
Content-Length: 11481

{"status":500,"error":"Internal Server Error","exception":"#\u003cNoMethodError: undefined method `climbs' for nil:NilClass\u003e"
```
I did not paste the entire error message as it is quite long but can if it is actually needed.

Because the error message indicates that **undefined method climbs** I have tried setting the create in the controller to     **@climb = current_user.climbs.build(climb_params)** but then the error message is **undefined method climb**. This leads me to believe that the issue lies somewhere else...

**Comment by bernardlee** [comment]
Which class does `ClimbsController` inherit from?

I think that you might have to uncomment the line `# --header "Authorization: Token token=$TOKEN"` from `create.sh`.

Try signing in with with `sign-in.sh`, copying the `token` that you get back, and then sending that as an additional argument with `create.sh`.

**Comment by raq929** [comment]
The error message is actually undefined method `climbs`. I suspect that you have not set the `has_many` relationship on the user model.

Also, you should *remove user_id* from the climb's permitted params. This is a serious security bug that would allow users to 'steal' other user's climbs. Your app will get the authenticated user to create a climb, and users should under no circumstances have control of that. (If you introduced this bug to, say, a financial services app, you would get fired. So it's important.)

Nice issue!

**Comment by doremaxime** [comment]
The ```ClimbsController``` inherits from ```ApplicationController```

Yes, I had put has_many in the user model:
```
# frozen_string_literal: true
class User < ApplicationRecord
  include Authentication

  has_many :examples
  has_many :climbs
end
```

I thought i needed _user_id_ in order to test to see that the climb i am creating is having the user_id rightfully set to the climb. 
If I take that out, how will users create a climb and have their id being set to the climb?

**Comment by bernardlee** [comment]
Since you're going to let your users perform CRUD operations on `Climb`, set `ClimbsController` to inherit from `ProtectedController`.  I think that this will allow you to test `create` with the method that I described without having `user_id` in the permitted parameters.

**Comment by doremaxime** [comment]
I see! but how does one test it in the terminal when you need to send a token as well / be signed in? Because that would just tell me that the access is denied then.

**Comment by bernardlee** [comment]
From looking at the source code, I believe that sending a token with `create.sh` will automatically set `current_user` to the one with the matching token.

**Comment by doremaxime** [comment]
I'm not sure I know how to do that.
Here is what I tried:
```
TOKEN="BAhJIiVhNTY0OGJiMWNhYzUyZTA5ZWUwOGUxOGE5NzU0ZDk0YQY6BkVG65e122d3fd22ca1d335019c5f9686ed9603fabeb" ID=5 DATE="1111-11-11" GRADE="V1" sh scripts/climbs/create.sh 
```
and
```
ID=5 DATE="1111-11-11" GRADE="V1" TOKEN="BAhJIiVhNTY0OGJiMWNhYzUyZTA5ZWUwOGUxOGE5NzU0ZDk0YQY6BkVG65e122d3fd22ca1d335019c5f9686ed9603fabeb" sh scripts/climbs/create.sh 
```
but I am being denied access.

**Comment by doremaxime** [comment]
I took that token from signing in the browser.

**Comment by bernardlee** [comment]
I have to head out now, but push up an updated branch of your repository at some point and I'll take a look tomorrow.

**Comment by bernardlee** [comment]
I just tried the process that I explained and it worked for me.  Did you uncomment out the lines disabling the `header` option in `create.sh` before trying it again?  Also, you don't need to pass `ID` in when using running the script since `climbs` has a primary key and it will automatically be created and incremented for you.
```
🦃 [09:36:54] ~/work/github/doremaxime/daily-boulders-api:(feature)$ EMAIL=bl@bl.com PASSWORD=bl sh scripts/sign-up.sh
HTTP/1.1 201 Created
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"6e92e06105978baa87dfcf81ffa9dc85"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: b0c956ef-9f8e-4209-88bb-fda80e69dbb2
X-Runtime: 0.358703
Vary: Origin
Transfer-Encoding: chunked

{"user":{"id":5,"email":"bl@bl.com"}}
🐆 [09:36:55] ~/work/github/doremaxime/daily-boulders-api:(feature)$ EMAIL=bl@bl.com PASSWORD=bl sh scripts/sign-in.sh
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"3469c01148a916bf54d966c1f6042736"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: d7c6d217-c9b3-4c02-b2bd-821bc4cb81a9
X-Runtime: 0.092619
Vary: Origin
Transfer-Encoding: chunked

{"user":{"id":5,"email":"bl@bl.com","token":"BAhJIiUxNDVmMDY2YTk4YWQ3NGEzMjI1YzkwNWRjMmY1NDdiYQY6BkVG--5966d3c21d999c60589a7039c94f411af01ffc7e"}}
🦋 [09:37:06] ~/work/github/doremaxime/daily-boulders-api:(feature)$ DATE=2017-02-18 GRADE=V17 TOKEN=BAhJIiUxNDVmMDY2YTk4YWQ3NGEzMjI1YzkwNWRjMmY1NDdiYQY6BkVG--5966d3c21d999c60589a7039c94f411af01ffc7e sh scripts/climbs/create.sh
HTTP/1.1 201 Created
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"6df767967d159608d423f25b5a65c883"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 63b2df96-effb-4aee-bebb-4981dd4a8cb0
X-Runtime: 0.036263
Vary: Origin
Transfer-Encoding: chunked

{"climb":{"id":5,"date":"2017-02-18","grade":"V17"}}
🐔 [09:37:24] ~/work/github/doremaxime/daily-boulders-api:(feature)$ 
```

**Comment by doremaxime** [comment]
Ah ok, my terminal command wasn't correct. 
yes, I've uncommented the auth header in the curl.
Thank you!
