### ISSUE TITLE
Create 'Athlete' at the same time as user sign up?

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/full-stack-project#612]
If I'm linking my user to my 'athlete', would it make sense to have them both get created with the sign up button? So onSignUp and onCreateAthlete would happen with the same submit button?
If yes I'm assuming I'd need a whole sign up form to also require information for athlete (like given name, surname, and date of birth)?

**Comment by bernardlee** [comment]
Before you think about doing this, go into `app/controllers` and read the comments for `application_controller.rb`, `open_read_controller.rb`, and `protected_controller.rb`.  Check your custom controllers afterward.

**Comment by laurpaik-zz** [comment]
will do! I'll reopen this after I read them if I have other related questions.

**Comment by laurpaik-zz** [comment]
So then should I have my athlete class inherit from protected controller since it has a one to one relationship with the user?

**Comment by bernardlee** [comment]
Do you have an updated branch of your repository?

**Comment by laurpaik-zz** [comment]
I tried turning athlete to an openread controller to see what it would do... [here ](https://github.com/laurpaik/WorkIt-API/tree/openread) ... if you look at the other branches, 'workouts' is the branch where I made the relationship between "athletes" and "workouts" through "logs", and 'userlink' is where I made the athletes link to the user... 'openread' is a branch off of 'userlink'.

**Comment by laurpaik-zz** [comment]
Now I don't have authorization to create anything other than a user, even if I add the token in

**Comment by raq929** [comment]
As a reminder, the controllers `OpenReadController` and `ProtectedController` do not have anything to do with relationships between tables. They simply determine which actions need authentication. 
How are you trying to create things? Can you post that code please?

**Comment by laurpaik-zz** [comment]
```sh
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/athletes"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "athlete": {
      "given_name": "'"${GIVEN_NAME}"'",
      "surname": "'"${SURNAME}"'",
      "date_of_birth": "'"${DOB}"'"
    }
  }'
```
AthleteController:
```rb
# frozen_string_literal: true

class AthletesController < OpenReadController
  before_action :set_athlete, only: [:update, :destroy]

  # GET /athletes
  def index
    @athletes = Athlete.all

    render json: @athletes
  end

  # GET /athletes/1
  def show
    render json: Athlete.find(params[:id])
  end

  # POST /athletes
  def create
    @athlete = current_user.athletes.build(athlete_params)

    if @athlete.save
      render json: @athlete, status: :created
    else
      render json: @athlete.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /athletes/1
  def update
    if @athlete.update(athlete_params)
      head :no_content
    else
      render json: @athlete.errors, status: :unprocessable_entity
    end
  end

  # DELETE /athletes/1
  def destroy
    @athlete.destroy
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_athlete
    @athlete = current_user.athletes.find(params[:id])
  end
  private :set_athlete

  # Only allow a trusted parameter "white list" through.
  def athlete_params
    params.require(:athlete).permit(:given_name, :surname,
                                    :date_of_birth)
  end
  private :athlete_params
end
```

I tried this, with and without the token:
```node
TOKEN="<token>" GIVEN_NAME='la' SURNAME='pa' DOB='1993-01-16' sh scripts/athletes/create.sh 
```
I think without the token I got this:
```
NoMethodError (undefined method `password_digest' for #<Athlete:0x007f86b6349d30>
Did you mean?  password):
  
app/controllers/athletes_controller.rb:22:in `create'
Started POST "/athletes" for 127.0.0.1 at 2017-02-18 12:13:18 -0500
Processing by AthletesController#create as */*
  Parameters: {"athlete"=>{"given_name"=>"la", "surname"=>"pa", "date_of_birth"=>"1993-01-16"}}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "797453e5660ce49523d66e5452fe3254"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 20ms (ActiveRecord: 2.7ms)
```

and with the token I got this:
```
NoMethodError (undefined method `athletes' for #<User:0x007f86bc99b408>
Did you mean?  athlete
               athlete=):
  
app/controllers/athletes_controller.rb:20:in `create'
Started POST "/athletes" for 127.0.0.1 at 2017-02-18 12:13:41 -0500
Processing by AthletesController#create as */*
  Parameters: {"athlete"=>{"given_name"=>"la", "surname"=>"pa", "date_of_birth"=>"1993-01-16"}}
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 0ms (Views: 0.1ms | ActiveRecord: 0.0ms)
```

**Comment by laurpaik-zz** [comment]
I am going to open a different issue that's more appropriately named because I'm realizing this thread has two issues in it.
