### ISSUE TITLE
heroku problems

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/full-stack-project#615]
I followed the directions in the API and Heroku repos, I have a heroku site : 
https://serene-basin-28916.herokuapp.com/
and have a user name and password, but I don't see anything on the site.
I can see the project on my heroku dashboard.
my assets/scripts/config.js is:

```'use strict';

const config = {
  apiOrigins: {
    production: 'https://serene-basin-28916.herokuapp.com/',
  },
};

module.exports = config;
```

**Comment by MicFin** [comment]
Review and go through these steps.  Do you hit any errors along the way?

> **Troubleshooting**
> 
> These are the commands required for deploying to heroku with rails. If your heroku deployment isn't working as expected, review these steps carefully.
> 
> ```
> heroku create
> git push heroku master
> heroku run rake db:migrate
> heroku run rake db:seed
> heroku config:set SECRET_KEY_BASE=$(rake secret)
> heroku config:set SECRET_TOKEN=$(rake secret)
> heroku config:set CLIENT_ORIGIN=https://yourgithubname.github.io
> heroku apps:rename newname (optional)
> heroku restart
> heroku open
> ```
https://github.com/ga-wdi-boston/rails-heroku-setup-guide#troubleshooting

**Comment by Soboscott** [comment]
I followed all the steps again and now have several personal apps on Heroku, but I still get this when i try to look at my page:
![image](https://cloud.githubusercontent.com/assets/24324239/23097044/380c3244-f5f8-11e6-97fc-7d491fbd0707.png)

**Comment by MicFin** [comment]
Referencing back to https://github.com/ga-wdi-boston/rails-heroku-setup-guide#check-your-work.

![heroku error page](https://cloud.githubusercontent.com/assets/388761/13259005/93c9fdf6-da23-11e5-9c90-19c59580944a.png)

That's normal, unless you have defined a root route.

**Comment by Soboscott** [comment]
I looked for solutions and read a lot of sites, many were directing me to look at the route.rb file.  this is my config/routes.rb file I don't know what is wrong with it.

```# frozen_string_literal: true
Rails.application.routes.draw do
  resources :trails
  resources :posts
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end

```

**Comment by MicFin** [comment]
What is the response for `git branch` and `git branch -a`?

**Comment by Soboscott** [comment]
from which directory?

**Comment by MicFin** [comment]
Anywhere in your project with the `routes.rb` that you just shared.

**Comment by Soboscott** [comment]
```~/wdi/projects/rails-heroku-setup-guide/ruby-getting-started (master)
$ git branch -a
* master
  remotes/heroku/master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/schneems/puma
~/wdi/projects/rails-heroku-setup-guide/ruby-getting-started (master)
$ 

```

from my project directory
```

~/wdi/projects/trail-rater (inprogress)
$ git branch -a
* inprogress
  master
  models
  remotes/origin/HEAD -> origin/master
  remotes/origin/inprogress
  remotes/origin/master
~/wdi/projects/trail-rater (inprogress)

```

**Comment by MicFin** [comment]
Checkout into the `heroku/master` branch and then look at your routes.  Are they the same?

**Comment by Soboscott** [comment]
very different
```
Rails.application.routes.draw do
  resources :widgets

  # The priority is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"

  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

```

**Comment by Soboscott** [comment]
so, do I Put root 'welcome#index' some were in my route.rb or use the in the heroku/master???

**Comment by MicFin** [comment]
What happens when you run 
`git status`?
`git push heroku master`?

**Comment by Soboscott** [comment]
I get 
```
$ git status
HEAD detached at heroku/master
nothing to commit, working tree clean
~/wdi/projects/rails-heroku-setup-guide/ruby-getting-started 
$ git push heroku/master
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push heroku/master HEAD:<name-of-remote-branch>

~/wdi/projects/rails-heroku-setup-guide/ruby-getting-started 
$ 

```

**Comment by Soboscott** [comment]
do I merge it with my project???
I'm confused.

**Comment by raq929** [comment]
You checked out to heroku/master instead of pushing it. You'll need to check out to a branch in order to push. 

In reference to your earlier questions, your rails app doesn't have a `/` route, so navigating to `https://serene-basin-28916.herokuapp.com/` won't get you much. I'd try navigating to `https://serene-basin-28916.herokuapp.com/trails` or testing with curl to check that your deployment worked correctly.

**Comment by Soboscott** [comment]
welp, gonna try to figure it out on my own.

**Comment by raq929** [comment]
Hi Scott, I commented on this yesterday, and I've was expecting to hear from you about where you are with it. I can't offer more help if I don't know that my comment didn't help you. 
I'm happy to help more if you update me about where you're at with this.
