### ISSUE TITLE
2 auth in 1

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/full-stack-project#616]
I am trying to combine sign-up with sign-in so that if a user signs-up, he will automatically be signed-in. I have never tried this before but I don't think there is too much to it and that only the events.js needs to be modified.

Current events code which allows a user to sign up, and then sign-in:
```
const onSignUp = function (event) {
  event.preventDefault();

  let data = getFormFields(event.target);

  api.signUp(data)
  .then(ui.signUpSuccess)
  .catch(ui.signUpFailure);
};

const onSignIn = function (event) {
  event.preventDefault();

  let data = getFormFields(event.target);

  api.signIn(data)
  .then((response) => {
    store.user = response.user;
    return store.user;
  })
    .then(ui.signInSuccess)
    .catch(ui.signInFailure);
};
```

What I have tried is to have the sign in be called when the sign-up is successful:
```
const onSignUp = function (event) {
  event.preventDefault();

  let data = getFormFields(event.target);

  api.signUp(data)
  .then(onSignIn())       // <= HERE
  .catch(ui.signUpFailure);
};
```

It does indeed call the **onSignIn** function.
However, the browser console stops when it reaches the ``` event.preventDefault();``` of the onSignIn function. when I comment it out so that it can go past that line, the **event.target** of the **onSignIn** function stops the browser as the **event** parameter is undefined. This makes sense as **onSignIn** is triggered by a click event.
I am beginning to wonder if I should make a second sign-in function in events.js which would pass the data from the **onSignUp** to that new function instead of passing an event...
Please let me know what direction I should take of if I am even on the right path.

**Comment by MicFin** [comment]
I would recommend not combining Sign Up and Sign In until you have already met all the requirements for the project and are trying to earn Exceed Expectations.

**Comment by doremaxime** [comment]
As far as I can tell I have meet the requirements. Although the development section of my README is 'to be continued'...

**Comment by MicFin** [comment]
Complete the README, it's a requirement.  Is you site fully deployed?  If you completed the requirements and your site is fully deployed on Heroku then share the link with the consultants in slack so we can review it for you and you can move on to Sign Up/Sign In and other areas that could push your project to Exceed Requirements.

Also, style your code in Github comments using this syntax so that is color coded correctly https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

Instead of 
```
const onSignUp = function (event) {
  event.preventDefault();

  let data = getFormFields(event.target);

  api.signUp(data)
  .then(onSignIn())       // <= HERE
  .catch(ui.signUpFailure);
};
```

We can have 
```js
const onSignUp = function (event) {
  event.preventDefault();

  let data = getFormFields(event.target);

  api.signUp(data)
  .then(onSignIn())       // <= HERE
  .catch(ui.signUpFailure);
};
````

**Comment by MicFin** [comment]
You are passing a function as an argument to `.then()` and when you pass a *Callback Function* as an argument to another function you do not execute the function like you did with `onSignIn()`.  You pass the function name `onSignIn` so that it can be called back to when the API is successful.
```js
const onSignUp = function (event) {
  event.preventDefault();

  let data = getFormFields(event.target);

  api.signUp(data)
  .then(onSignIn) // <= pass .then() a function name onSignIn not execute function onSignIn()
  .catch(ui.signUpFailure);
};
```

**Comment by doremaxime** [comment]
I just did something that messed up my handlebars for index so i'll get the 2 auth in 1 when i deploy after i fix the handlebars. i'll reopen the issue then.
