### ISSUE TITLE
API patch / delete

### ISSUE THREAD

**Issue by moshiko1988** [ga-wdi-boston/full-stack-project#620]
i am currently trying to make the patch work by clicking on the checkbox of a list.
in my backend i have a column of 'completed' and its boolean default false 

when i create a new list it works with the server and when i delete and patch it does nothing

``` api.js

const patch = function(id, data, checkbox){
  return $.ajax({
    url: config.apiOrigin + '/lists/' + id,
    method: 'PATCH',
    data: {
      "list":{
        "completed": checkbox
      }
    },
  });
};

const destroy = function(id){
  return $.ajax({
    url: config.apiOrigin + '/lists/' + id,
    method: 'DELETE',
  });
};
```

this is my javascript file

```index.js 
$(document).ready(function () {

  $('#list-items').html(localStorage.getItem('listItems'));

  $('.add-items').submit(function(event)
  {
    event.preventDefault();

    let item = $('#todo-list-item').val();

    if(item)
    {
      $('#list-items').append("<li><input class='checkbox' type='checkbox'/>" + item + "<a class='remove'>x</a><hr></li>");

      localStorage.setItem('listItems', $('#list-items').html());

      $('#todo-list-item').val("");
    }

  });

  $(document).on('change', '.checkbox', function()
  {
    if($(this).attr('checked'))
    {
      $(this).removeAttr('checked');
    }
    else
    {
      $(this).attr('checked', 'checked');
    }

    $(this).parent().toggleClass('completed');

    localStorage.setItem('listItems', $('#list-items').html());
  });

  $(document).on('click', '.remove', function()
  {
    $(this).parent().remove();

    localStorage.setItem('listItems', $('#list-items').html());
  });

}); 
```
i know i need to change the data when the checkbox is click it will send data back but im not sure what to do

**Comment by MicFin** [comment]
Why are you saving in in local storage?  It seems like you are using local storage as your API instead of your own.

**Comment by moshiko1988** [comment]
when i used localStorage it worked and sent the data
when i changed it to the setAPIOrigin it gave me an error  the page did work

**Comment by MicFin** [comment]
Please show the code that caused the error and the error.

**Comment by moshiko1988** [comment]
`Uncaught TypeError: setAPIOrigin.getItem is not a function
    at HTMLDocument.<anonymous> (index.js:57)
`

i changed all of the local storage to this at first

```index.js
  $('#list-items').html(setAPIOrigin.getItem('listItems'));
```

**Comment by MicFin** [comment]
That is not how you have been making API calls on click events.  Why are you using `.getItem()`?  Is there a blog that used this code that you are referencing?

**Comment by raq929** [comment]
You should be making API calls to get your data instead of using localStorage. Setting new items in localStorage does not save them to the database and will not meet requirements.

Also, you should not be setting click handlers on the whole document. They must be set on an HTML element. You should be separating your concerns in a similar way to the way auth is separated - separate files for `events`, `api` and `ui`. Having only one javascript file will likely make it more difficult for you to debug.

**Comment by raq929** [comment]
Where are you with this, Moshe? If it's resolved, please let us know what you did to fix it. If not, please let us know what you've tried and where you're at now.

**Comment by moshiko1988** [comment]
@raq929 
so i changed it to handlebars but i have a new issue.
i generate a delete button on evert list that i show and i gave this delete button an id
when i click on it nothing is happening:

```events.js
const onDeleteList = function(event){
  event.preventDefault();

  let data = getFormFields(event.target);
  api.destroy(data.list.id)
    .then(ui.onDeleteSuccess)
    .catch(ui.onError);
};

const addHandlers = () => {
  $('#remove-list').on('click', onDeleteList);

};
```
```handlebars

{{#each lists as |list|}}

  <table class="table" data-id="{{id}}">
    <td><h3 data-id="{{list.id}}">ID: {{id}}  </td>
      <td><h3 data-id="{{list.id}}">Note: {{note}}</h3></td>
  <td><button type="button" name="button" id="remove-list">Remove</button></td>
</table>

{{/each}}
```

**Comment by MicFin** [comment]
The click event is being assigned to `#remove-list` but EVERY button is getting that ID in the loop.  You should use class if you want them all to have the same selector.  Only 1 element on the page can have an attribute ID of specific value `id="remove-list"` can only occur once on the page, not multiple times due to a loop.
```html
<button type="button" name="button" id="remove-list">Remove</button>
```

**Comment by moshiko1988** [comment]
solved it 

```event.js

const onDeleteList = function(event){
  event.preventDefault();
let id = event.target.dataset.id;
  // let data = getFormFields(event.target);
  api.destroy(id)
    .then(ui.onDeleteSuccess)
    .catch(ui.onError);
};
```
```js
<button type="button" name="button" class="remove-list">Remove</button>
```
