### ISSUE TITLE
ActiveRecord::AssociationTypeMismatch

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#621]
After putting this in my console:
``` rb 
$ MOVIE_ID=1 USER_ID=1 MOVIE="Grizzly Man" USER="Alex" STARS=5 sh scripts/reviews/create.sh
```
I am getting a 500 request error. 
My server is telling me: 
```rb
Processing by ReviewsController#create as */*
  Parameters: {"review"=>{"movie_id"=>"1", "user_id"=>"1", "movie"=>"Grizzly Man", "user"=>"Alex", "stars"=>"5"}}
Completed 500 Internal Server Error in 45ms (ActiveRecord: 4.1ms)
ActiveRecord::AssociationTypeMismatch (Movie(#70234088161860) expected, got String(#70234048733280)):
app/controllers/reviews_controller.rb:19:in `create'
```

This is line 19 of the controller, so it is saying it is in my params: 
```rb
 @review = Review.new(review_params)
```

Here is my controller:
``` rb
# frozen_string_literal: true
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :update, :destroy]

  # GET /reviews
  def index
    @reviews = Review.all

    render json: @reviews
  end

  # GET /reviews/1
  def show
    render json: @review
  end

  # POST /reviews
  def create
    @review = Review.new(review_params)

    if @review.save
      render json: @review, status: :created
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /reviews/1
  def update
    if @review.update(review_params)
      render json: @review
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end

  # DELETE /reviews/1
  def destroy
    @review.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def review_params
    params.require(:review).permit(:movie_id, :user_id, :movie, :user, :stars)
  end
end
```

My model:
``` rb
# frozen_string_literal: true
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  validates :movie_id, presence: true
  validates :user_id, presence: true
  validates :stars, presence: true
  validates :user, presence: true
  validates :movie, presence: true
end
```

Serializer: 
``` rb
# frozen_string_literal: true
class ReviewSerializer < ActiveModel::Serializer
  attributes :id, :stars, :movie_id, :user_id, :movie, :user
end
```
Migration:
``` rb
# frozen_string_literal: true
class CreateReviews < ActiveRecord::Migration[5.0]
  def change
    create_table :reviews do |t|
      t.integer :stars, null: false
      t.integer :movie_id, null: false
      t.integer :user_id, null: false
      t.string :movie, null: false
      t.string :user, null: false

      t.references :movie, index: true, foreign_key: true, null: false
      t.references :user, index: true, foreign_key: true, null: false
      t.timestamps null: false
    end
  end
end
```

my create:
``` rb
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/reviews"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "review": {
      "movie_id":"'"${MOVIE_ID}"'",
      "user_id": "'"${USER_ID}"'",
      "movie": "'"${MOVIE}"'",
      "user": "'"${USER}"'",
      "stars": "'"${STARS}"'"
    }
  }'

  echo
```
Also, I want to make sure that I am  doing this the right way in general. I have a User who is able to have many reviews and I have a list of movies, which are able to have many reviews. Movies and Users are linked by Reviews, so Reviews will be my join table. 

 I have not done anything for users yet (and I believe I don't have to), so I am not really sure where that ID would be coming from, I just know I need one. I believe all the ID's and my star variable should be integers because they are just being represented by numbers.

**Comment by alexkarasik** [comment]
I am not sure if it makes a difference, but I rearranged every file, so they go in order of movie_id, user_id, movie, user, stars
Still getting the same error though

**Comment by MicFin** [comment]
I do not see why `Reviews` would have a `user` column and a `stars` column when it already has a `movie_id` and `user_id` and a `belongs_to` relationship to match.

**Comment by raq929** [comment]
You *must remove* the user ID from the allowed params. Users should be set by the controller (see the create example in the ExamplesController to see how to do this). Allowing users to set the user_id from the front end is a *serious* security bug, and if you were to do it on, say, a bank website, you would be fired. (And possibly owe some people a lot of money.)

Moving on... I suspect you're sending the IDs and the rating as strings, but the database wants integers, so they are failing validation. You can send them as integers or coerce them to integers on the backend.  You can figure this out for sure by printing out their type in your controller; when you make the request, you can look at the server log and see the printout.

**Comment by alexkarasik** [comment]
Are you saying that you think those should go in movies or that you don't think they are necessary at all? I want each user to be able to give each movie 1-5 stars, so I thought it would make sense for them to go in reviews.

**Comment by alexkarasik** [comment]
Ok, so I think I have my controller working properly then and it is attached through the model, so I don't need the users to be connected as attributes in any way. 
Perhaps getting rid of the user id's will solve this problem

**Comment by raq929** [comment]
You will need to change your `create` method to look like the one in `ExamplesControler` as well.

**Comment by raq929** [comment]
What's your status, Alex? Has this been resolved? If yes, please update and close. If not, please let us know where you're at.

**Comment by alexkarasik** [comment]
I've been working on front end stuff this morning. I will get back to this now.

**Comment by alexkarasik** [comment]
Everything looks the same, except for this line in my review controller:
    @review = Review.new(review_params)
but I believe that is what I want. I want a new Review with the permitted params.

**Comment by gaand** [comment]
Reviews are not owned and I suspect they need to be.  Please compare your controller with the example as @raq929 suggested.

**Comment by alexkarasik** [comment]
Are you saying it should be movie.Review.new(review_params)?
I am not really sure what you mean about ownership. I thought that is what is happening in the model.

**Comment by alexkarasik** [comment]
Reviews are owner by a user, but also a movie... so do I need 2?

**Comment by gaand** [comment]
Have you looked at `ExamplesController` :question:

**Comment by alexkarasik** [comment]
Yes. It is not clear to me what you are speaking about when you mention ownership in the create method. My method looks almost the same as the example controller now.

**Comment by alexkarasik** [comment]
``` rb
  def create
    @example = current_user.examples.build(example_params)

    if @example.save
      render json: @example, status: :created
    else
      render json: @example.errors, status: :unprocessable_entity
    end
  end
```


```rb
  def create
    @review = Review.new(review_params)

    if @review.save
      render json: @review, status: :created
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
```

**Comment by gaand** [comment]
The first line of your create action looks quite different from the first line of the example create action.

**Comment by alexkarasik** [comment]
so I am thinking that line should be:

@review = User.Review.new(review_params)

because Reviews belong to users

**Comment by raq929** [comment]
I'm a bit frustrated, because both Antony and I have asked you to look at the `ExamplesController` and model your create action on it. It doesn't seem like you've done that.

Here's the create action from the `app/controllers/examples.rb`
```ruby
 def create
    @example = current_user.examples.build(example_params)

    if @example.save
      render json: @example, status: :created
    else
      render json: @example.errors, status: :unprocessable_entity
    end
  end
```

**Comment by raq929** [comment]
Your controller will have to inherit from `OpenReadController` or `ProtectedController` for this to work, I think.

**Comment by raq929** [comment]
Look at this line: `@example = current_user.examples.build(example_params)`
That's still very different from what you've got. You're not using `current_user` at all.
What happens when you try the code you're proposing? You need to try code out to see how it fails instead of asking for us to approve it. You'll get more information that way, and you'll be better able to debug things in the future.

**Comment by alexkarasik** [comment]
I've been looking at the examples controller for a long time and posted those lines already in my previous comments. I know this is where the issue is, but this problem is new to me, so I am not sure about what the syntax should be and want to be clear about what I am doing. 
I don't really understand what is happening in those 2 controller files. Should I be adding Reviews to them? I asked about them to some of my classmates and they said they didn't have to touch them. I am feeling in over my head at the moment.

**Comment by MicFin** [comment]
@alexkarasik did you solve this?

**Comment by alexkarasik** [comment]
I wasn't making myself clear so I tried to rephrase it start again in a new issue where it was answered, but I am not sure what I was supposed to have changed in the other 2 mentioned controller files.
