### ISSUE TITLE
Can't handle the bars

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/full-stack-project#623]
I am trying/expect to display the index data from the backend in the browser using handlebars.
No error occurs, but nothing is displayed either (the data does show in the browser console though).
Once the index button is clicked it gets all the climbs of the user and goes to **ui.indexSuccess**.

ui:
```
const showClimbsHandlerbars = require('../templates/helpers/climb-listing.handlebars');

const indexSuccess = (data) => {
  console.table(data.climbs);
  let showClimbsHtml = showClimbsHandlerbars({ climb: data.climbs });
  $('.view').append(showClimbsHtml);
};
```

climb-listing.handlebars:
```
{{#each climbs as |climb|}}

  <ul data-id="{{climb.id}}">
    <li><h1 data-id="{{climb.id}}"> <small>date: {{climb.date}}, grade: {{climb.grade}}</small></h1></li>
  </ul>

{{/each}}
```

html:
```
      <div class="view">
      </div>
```

**Comment by raq929** [comment]
(I have such a soft spot for puns in issue names.)

As debugging steps (and as methodical steps for building handlebars templates), here's what I would do. Comment out what you've got in the handlebars template. Then:
1. Put in a div with some text in it, and see if that appears.
2. If it does, put in `{{ climbs }}` and be sure that you have the data you want.
3. Uncomment the `each` loop. (Or write it, if you haven't already.)

If the text in step 1 does not appear:
1. Double check that the file name is spelled correctly. Then check one more time.
If the data in step 2 does not appear:
1. Double check that the data you're sending to the template has the same name as the data your template expects.

Writing no. 2 on that second list makes me pretty sure that your error is that you use `climb` in your `ui` file but `climbs` in your handlebars template.

**Comment by doremaxime** [comment]
1st instructions step 1&2:
updated html:
```
      <div class="view">max {{ climbs }}
      </div>
```
Result:
![screen shot 2017-02-18 at 8 03 49 pm](https://cloud.githubusercontent.com/assets/24608045/23098156/7b9bcea8-f615-11e6-9ea0-291490e905e3.png)

1st instructions step 1&2:
I am confused as my each loop in the climb-listing.handlebars is not commented. Either way i tried to comment it out and the result was the same.

2nd instructions step 1:
Can't see any typos
![screen shot 2017-02-18 at 8 09 41 pm](https://cloud.githubusercontent.com/assets/24608045/23098193/539cf124-f616-11e6-8a1f-cb49c1017344.png)

2nd instructions step 2: I am not sending any data, I am only receiving since it's an index action and it is being received well as it is showing in the browser console.

**Comment by raq929** [comment]
In my instructions, I say to comment out the loop before following the steps.

Sorry for being unclear about sending data. I meant when you send data to your template on this line:
`let showClimbsHtml = showClimbsHandlerbars({ climb: data.climbs });`

I suspect
```diff
- { climb: data.climbs }
+ { climbs: data.climbs }
``` 
will solve your problem.

**Comment by doremaxime** [comment]
It worked! thank you!


Updated code that works:
ui:
```
const showClimbsHandlerbars = require('../templates/helpers/climb-listing.handlebars');

const indexSuccess = (data) => {
  let showClimbsHtml = showClimbsHandlerbars({ climbs: data.climbs });
  $('.view').append(showClimbsHtml);
};
```
