### ISSUE TITLE
[Rails] Inherit ProtectedController to a table 

### ISSUE THREAD

**Issue by newayliu1** [ga-wdi-boston/full-stack-project#625]
I have a table which has many-to-many relationship with user table. I am trying to inherit ProtectedController and trying write the index method by using current_user. 

```ruby
  # GET /products
  def index
    @products = current_user.inventories.product.all

    render json: @products
  end
```

I run the code to get all products. 
```
TOKEN="BAhJIiU3NjgyNmY0N2I3OTBiMzhkNDEwYjkzMTVjZWRhNWNhMgY6BkVG--71c46a0075488f2fadf8ae0ddccc0543ac9030c5" sh scripts/products/index.sh 
```
But, the server said NoMethodError

```
NoMethodError (undefined method `product' for #<Inventory::ActiveRecord_Associations_CollectionProxy:0x007ffd90b342d8>):
  
app/controllers/products_controller.rb:7:in `index'
```

I am not sure how to write a protected controller for another main entity table in many-to-many relationship.

**Comment by gaand** [comment]
Please post your models, user, inventory, and product.

**Comment by raq929** [comment]
I would also recommend testing your relationships via the rails console to ensure they're working correctly before you test via curl. With `rails console` you can experiment and iterate quickly to find the right answer.

**Comment by newayliu1** [comment]
User model
```
# frozen_string_literal: true
class User < ApplicationRecord
  include Authentication
  has_many :inventories
end
```
Product model
```
# frozen_string_literal: true
class Product < ApplicationRecord
  has_many :inventories
  validates :name, presence: true
end
```
Inventories Model
```# frozen_string_literal: true
class Inventory < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :price, :section, presence: true
end
```

**Comment by gaand** [comment]
Should a user have many products through inventories?

**Comment by newayliu1** [comment]
yes

**Comment by raq929** [comment]
That relationship needs to be on your user model, then.

**Comment by raq929** [comment]
Has this been resolved? If yes, please close. If not, let us know where you're at so we can help.

**Comment by newayliu1** [comment]
Haven't. I would like to have an 1 on 1 to talk about it

**Comment by newayliu1** [comment]
The relationship between product and user is many to many. Inventories table is the joint table between them. What relationship do i still need to add?

**Comment by raq929** [comment]
You need to add a `has_many` relationship in the model. Please review `rails_api_many_to_many` and let us know what you've tried, and then we can set up a 1:1.

**Comment by MicFin** [comment]
@newayliu1 did you have your 1on1 with @raq929 yet?

**Comment by newayliu1** [comment]
I figured it out. I forgot add the following relationship in model. 
``` ruby
has_many :users, through :inventories
```

Thank you so much.
