### ISSUE TITLE
vendor.js and application.js not loading on frontend

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/full-stack-project#627]
My frontend will not deploy properly. 
https://ggwilliams.github.io/gabs-scary-movies-frontend/

when I run grunt deploy, it loads properly and doesn't give me errors so I'm not sure why this is happening. And everything works fine on localhost.

**Comment by ggabrakadabra** [comment]
this is my config file. the apikeys are for a 3rd party api and I don't think that should mess with anything.

```rb
'use strict';

const config = {
  apiOrigins: {
    // production: 'https://gabs-scary-movies.herokuapp.com/',
    development: 'http://localhost:4741/'
  },
};

const v3ApiKey = "e18ddcf3507daa19535e7842e7a62270";
const v4ApiKey = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlMThkZGNmMzUwN2RhYTE5NTM1ZTc4NDJlN2E2MjI3MCIsInN1YiI6IjU4YThlYzA1YzNhMzY4NjQ1MDAwNDAwNyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.sIkFhkjis7UQhQTF6SPsxMtVMxbfv82E_PbWOS7gO_w";

module.exports = {
config,
v3ApiKey,
v4ApiKey};
```

**Comment by gaand** [comment]
You shouldn't be storing your API keys in the config file of your front end (or in any file stored on github). Depending on how you're using them, they probably belong in your API (via `heroku config:set` and `.env`).

Given what you're exporting from the config file, I'm surprised your client works locally.  The only thing that should be exported is the config object.

Once you've fixed that, you probably need to make this change:

```diff
 const config = {
   apiOrigins: {
-    // production: 'https://gabs-scary-movies.herokuapp.com/',
+    production: 'https://gabs-scary-movies.herokuapp.com/',
     development: 'http://localhost:4741/'
   },
 };
```

I'm not sure how you're using the API keys, so I'm not sure how to advise you on that.

**Comment by raq929** [comment]
The deployed site runs in the production environment, so that's why you have to uncomment the production origin. You shouldn't need to comment it out to run locally, so if you're having problems running locally with it uncommented, we should work on resolving those.

**Comment by ggabrakadabra** [comment]
I uncommented out the production, tried to grunt deploy again and got this

```rb
grunt deploy
Running "shell:git-is-clean" (shell) task
On branch master
Your branch is ahead of 'origin/master' by 4 commits.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    index-sign-in.html

no changes added to commit (use "git add" and/or "git commit -a")
Warning: Command failed: test -z "$(git status --porcelain)"  || (git status && false)
 Use --force to continue.

Aborted due to warnings.


Execution Time (2017-02-19 12:13:53 UTC-5)
loading tasks       1.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 98%
shell:git-is-clean  29ms  ▇ 2%
Total 1.6s


```

**Comment by ggabrakadabra** [comment]
I'm using the api key to set my url so that the third party api works properly, which is does. It's a free api so I don't know why I wouldn't be able to have it stored in my config file.
Once my frontend deploys properly, I'll have to change the url from the 3rd party api from http://localhost to https://gabs-scary-movies.herokuapp.com/ but my frontend won't deploy so I haven't done this.

**Comment by ggwilliams** [comment]
Also, my project runs locally with the production uncommented, so that isn't an issue.

**Comment by ggabrakadabra** [comment]
so to set my api, I should run heroku config:set v3ApiKey = "e18ddcf3507daa19535e7842e7a62270";
on the backend? and then it should be able to be accessed on the front end?

**Comment by gaand** [comment]
`Aborted due to warnings.` means the deploy didn't happen.

**Comment by ggabrakadabra** [comment]
But why is it aborting?

**Comment by gaand** [comment]
Because you have uncommitted changes.

**Comment by ggabrakadabra** [comment]
the deleted page?

**Comment by ggabrakadabra** [comment]
now it lets me grunt deploy but vendor.js and application.js still don't load on the page

**Comment by gaand** [comment]
Please post a link to your gh-pages branch on GitHub.

**Comment by ggabrakadabra** [comment]
https://github.com/ggwilliams/gabs-scary-movies-frontend/tree/gh-pages

**Comment by gaand** [comment]
That seems correct. I'm on my iPhone so I can't check the details.

**Comment by ggabrakadabra** [comment]
I'm just going to keep working form localhost and if I still can't get it to work I'll show you on tuesday.

**Comment by gaand** [comment]
When you go to settings on github, what branch is selected in the Source drop down under GitHub Pages?

**Comment by ggabrakadabra** [comment]
it says master branch. should i change that to gh-pages?

**Comment by gaand** [comment]
Yes.  That is almost certainly the problem.

**Comment by ggabrakadabra** [comment]
That was absolutely the problem. I didn't see that you had commented back until now. Thank you.
