### ISSUE TITLE
Handlebars show action

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/full-stack-project#628]
A sort of continuation of issue: Can't handle the bars #623 which is about displaying index data onto the browser.

I am attempting to do the same thing but for displaying a climb (singular - show action).
I would think that the code is the same (or very similar).
Goal: display 1 climb using an ID.
Issue: UI is not displaying properly and no data on browser but data is showing in browser console, which means that the data is successfully being retrieved.

show-climb.handlebars:
```javascript
{{#each climbs as |climb|}}

  <ul data-id="{{climb.id}}">
    <li><h1 data-id="{{climb.id}}"> <small>id: {{climb.id}}, date: {{climb.date}}, grade: {{climb.grade}}</small></h1></li>
  </ul>

{{/each}}
```
(I have also tried commenting out the first and last line of this, so no **each**, and still no result.)

ui:
```javascript
const showClimbsHandlerbars = require('../templates/helpers/show-climb.handlebars');

const showSuccess = (data) => {
  console.log(data.climb);
  let showClimbHtml = showClimbsHandlerbars({ climbs: data.climb });
  $('.view').html(showClimbHtml);
};
```
The index action version has an ```s``` at the end of the last **climb** in ```showClimbsHandlerbars({ climbs: data.climb });``` but it wasn't working for the show action so i took it off which makes sense since there is only one instance. Currently, without the ```s``` this is what displays:
![screen shot 2017-02-19 at 1 52 53 pm](https://cloud.githubusercontent.com/assets/24608045/23105275/cd7a3dbe-f6aa-11e6-9678-cb965ad03c6e.png)
Why there are 3 lines and no data I don't understand as only 1 climb is being retrieved and confirmed by the browser console. Same thing displays when the **each** lines are commented out in **show-climb.handlebars**

html:
```html
      <div class="view">
      </div>
```

**Comment by MicFin** [comment]
**ui.js** the object you are passing has a singular `climb` as the value of `climbs` plural
```js
let showClimbHtml = showClimbsHandlerbars({ climbs: data.climb });
```

**show-climb.handlebars** you are looping through `climbs` as if it is an array of multiple climbs but as shown above, its value is a singular `climb`.
```js
{{#each climbs as |climb|}}
  <ul data-id="{{climb.id}}">
    <li><h1 data-id="{{climb.id}}"> <small>id: {{climb.id}}, date: {{climb.date}}, grade: {{climb.grade}}</small></h1></li>
  </ul>
{{/each}}
```
You are following the pattern of your `index` page which is a good start but on your `show` page you are interacting with just a single resource.

**Comment by doremaxime** [comment]
right, so i commented out the **each** and **/each**  in **show-climb.handlebars**
such as: 
```javascript
  <ul data-id="{{climb.id}}">
    <li><h1 data-id="{{climb.id}}"> <small>id: {{climb.id}}, date: {{climb.date}}, grade: {{climb.grade}}</small></h1></li>
  </ul>
```

and in ui i tried: 
```javascript
let showClimbHtml = showClimbsHandlerbars({ climbs: data.climb });
```
and
```javascript
let showClimbHtml = showClimbsHandlerbars({ climb: data.climb });
```
but neither works. 
Please let me know if I don't understand because I originally thought i understood haha

**Comment by MicFin** [comment]
If you `{{log climb}}` in `show-climb.handlebars` what do you get?
What is the error that you get with? 
```js
// ui.js
let showClimbHtml = showClimbsHandlerbars({ climb: data.climb });

// show-climb.handlebars
<ul data-id="{{climb.id}}">
    <li><h1 data-id="{{climb.id}}"> <small>id: {{climb.id}}, date: {{climb.date}}, grade: {{climb.grade}}</small></h1></li>
</ul>
```

**Comment by raq929** [comment]
Hehe, I was going to say something similar but one step back; what's the result of console.log(data)? 
Is this an index or a show? If it's show, you're not going to want the loop.
Basically I think the data you think you have and the data you have are probably in slightly different formats, so if we look at what you've got, we might be able to figure it out.

**Comment by doremaxime** [comment]
McFin: where are you saying to put ```{{log climb}}```? I tried doing:
```javasrcipt
let showClimbHtml = showClimbsHandlerbars({{log climb}});
```
but the linter won't let me. 
I also put it in the .view div but doesn't work either.


So with 
```javasrcipt
let showClimbHtml = showClimbsHandlerbars({ climbs: data.climb });

<ul data-id="{{climb.id}}">
    <li><h1 data-id="{{climb.id}}"> <small>id: {{climb.id}}, date: {{climb.date}}, grade: {{climb.grade}}</small></h1></li>
</ul>
```
I get this:
![screen shot 2017-02-19 at 3 02 08 pm](https://cloud.githubusercontent.com/assets/24608045/23105964/b00d8c7c-f6b4-11e6-822f-2b01bef803f3.png)
![screen shot 2017-02-19 at 3 02 37 pm](https://cloud.githubusercontent.com/assets/24608045/23105966/b49d7324-f6b4-11e6-9c68-e97b3ad651a9.png)





And with:
```javasrcipt
let showClimbHtml = showClimbsHandlerbars({ climb: data.climb });

<ul data-id="{{climb.id}}">
    <li><h1 data-id="{{climb.id}}"> <small>id: {{climb.id}}, date: {{climb.date}}, grade: {{climb.grade}}</small></h1></li>
</ul>
```
I get:
![screen shot 2017-02-19 at 3 05 56 pm](https://cloud.githubusercontent.com/assets/24608045/23105997/00dd5bf0-f6b5-11e6-9d90-55fe0c802919.png)
![screen shot 2017-02-19 at 3 06 07 pm](https://cloud.githubusercontent.com/assets/24608045/23105996/00dd6bcc-f6b5-11e6-93ae-f6139e1fa340.png)

the difference in the javascript is the **s** in **{ climb: data.climb }**

**Comment by doremaxime** [comment]
the code to log the data in the console is:
```javascript
  console.log(data.climb);
```

**Comment by raq929** [comment]
Ok. It looks like you're only trying to display one climb here. 

So. I would use `let showClimbHtml = showClimbsHandlerbars({ climb: data.climb });`
And ditch the loop. 

What happens if you put just {{climb}} in your template? (With the above code in your file). What about {{id}}?
I was looking at the documentation and I'm not quite sure how it will work, so it's time to experiment.
http://handlebarsjs.com/

**Comment by doremaxime** [comment]
Wasn't sure exactly what you meant so with no loop and:
```javascript
let showClimbHtml = showClimbsHandlerbars({ climb: data.climb });
```

I tried the following:
```javascript
  <ul data-id="{{climb.id}}">
{{id}}
  </ul>
```

```javascript
  <ul data-id="{{climb.id}}">
{{climb}}
  </ul>
```

```javascript
  <ul data-id="{{climb}}">
{{climb}}
  </ul>
```

```javascript
{{id}}
```

```javascript
{{climb}}
```

```javascript
{{climb.id}}
```

Each time nothing display at all  unless I have the **s**:
```javascript
let showClimbHtml = showClimbsHandlerbars({ climbs: data.climb });
```

**Comment by doremaxime** [comment]
Development!

If I have 
```{{climb}}``` in the handlerbars and

```javascript
let showClimbHtml = showClimbsHandlerbars({ climbs: data.climb });
```

Then it displays:
![screen shot 2017-02-19 at 5 26 50 pm](https://cloud.githubusercontent.com/assets/24608045/23107306/a8196fb8-f6c8-11e6-9a5f-84a2b7910a38.png)

But that is the only thing in the handlers that gets the data through.
I have tried 
```javascript
id: {{climb.id}}, date: {{climb.date}}, grade: {{climb.grade}}
{{climb}}
{{id}}
{{grade}}
{{date}}
```
and it just displays:
![screen shot 2017-02-19 at 5 29 29 pm](https://cloud.githubusercontent.com/assets/24608045/23107321/ff0705ba-f6c8-11e6-8d86-d70397ac6589.png)
eventhough it has **{{climb}}** inside!  wat?

**Comment by raq929** [comment]
I'm confused about what's going on. Please paste your whole handlebars file. Actually, why don't you push a branch and I'll take a look. (Please tell me the names of the relevant files as well. 
Can you try Mike's `{{log climb}}`? It goes in the handlebars file.

**Comment by doremaxime** [comment]
https://github.com/doremaxime/daily-boulders

Yes I tried {{log climb}} which works similarly to {{climb}}.

**Comment by MicFin** [comment]
What do you get in console AND as an error with...

**ui.js**
```js
const showClimbsHandlerbars = require('../templates/helpers/show-climb.handlebars');

const showSuccess = (data) => {
  console.log("In UI.js ", data.climb);
  let showClimbHtml = showClimbsHandlerbars({ climb: data.climb });
  $('.view').html(showClimbHtml);
};
```

**show-climb.handlebars**
```js
{{ log climb }}
<ul data-id="{{climb.id}}">
    <li><h1 data-id="{{climb.id}}"> <small>id: {{climb.id}}, date: {{climb.date}}, grade: {{climb.grade}}</small></h1></li>
</ul>

```

**Comment by doremaxime** [comment]
No errors, I get:
![screen shot 2017-02-19 at 7 51 25 pm](https://cloud.githubusercontent.com/assets/24608045/23108551/e1ca6e92-f6dc-11e6-8cd3-1ff5827e4a3c.png)


![screen shot 2017-02-19 at 7 51 31 pm](https://cloud.githubusercontent.com/assets/24608045/23108550/e1c97bae-f6dc-11e6-9ae3-c3fb0bb61348.png)

**Comment by raq929** [comment]
I have sad sad news for you. Well, good news. Sort of. Your comments are HTML comments not Handlebars comments, so your code is running as if uncommented. So... you get to try all your debugging again with actual handlebars comments. Or just deleting the code. Which is honestly what I would do at this point. You can always get back to it because it's committed.

**Comment by raq929** [comment]
I would tell you more but I'm having trouble with my setup and I can't run the server.

**Comment by MicFin** [comment]
It does not look like your log is logging with the changes I suggested.  Please double check these.
```js
console.log("In UI.js ", data.climb);  // says IN US.js
let showClimbHtml = showClimbsHandlerbars({ climb: data.climb }); // SINGULAR climb
```

**Comment by doremaxime** [comment]
oh ma gaaaaad!!! thanks rachel! i'll try now

**Comment by doremaxime** [comment]
mike: confirmation of your last code:
![screen shot 2017-02-19 at 8 09 36 pm](https://cloud.githubusercontent.com/assets/24608045/23108730/7b6786f0-f6df-11e6-97f6-bef37e92d353.png)
it shows twice because i had another console.log(data.climb)

**Comment by raq929** [comment]
OK. So you have the right data. That's good. What's the status of the template?

**Comment by doremaxime** [comment]
I've tried a whole bunch of of combinations and nothing yet

**Comment by raq929** [comment]
OK. I think it should be singular climb in the js. 
Then put {{log climb}} in the handlebars file and delete everything else. Except maybe a `<p>Hello</p>` to let you know it's running. What happens then?
`let showClimbHtml = showClimbsHandlerbars({ climb: data.climb });` <= This in your js file.

**Comment by doremaxime** [comment]
It displays:
```
Hello
```

but if i put just {{climb}} instead, it displays:
```
[object Object]
Hello
```

**Comment by raq929** [comment]
Yay!
That's good. It's getting your data.
Now try `{{climb.id}}`.  Keep the `hello` div as your control.

**Comment by doremaxime** [comment]
YAAYYYYY!!! it all works!
This worked:
```html
{{climb.id}}
<p>Hello</p>
```

So i tried:
```html
<p>{{climb.id}}, date: {{climb.date}}, grade: {{climb.grade}}
<p>Hello</p>
```
and it worked!!!!!! YAAYYY 
RACHEL IS AWASOME!! AND MIKE TOO!!

**Comment by raq929** [comment]
Please close the issue! 🎈  🎊 🎈

**Comment by raq929** [comment]
Oh! The fact that you had HTML instead of handlebars comments means you may have missed a part of installfest where we made handlebars comments the default. You don't have to fix it now, but you may want to.
