### ISSUE TITLE
Two issues: 1. cannot create favorite_bikes. 2. Bike creation through frontend not updating correctly unless a browser refresh

### ISSUE THREAD

**Issue by resource11** [ga-wdi-boston/full-stack-project#63]
So... for 1: cannot create favorite_bikes through the front-end

I _can_ create a favorite bike through curl, through Postman, and through pry. However, I get an error when trying to create from the frontend. I ran into a similar issue with creating a new bike and solved that, so I'm not sure if the issue is the same (the error is the same), or if it's something else. I'm 90% sure it's a frontend issue. However. Considering the issue that's happening with #2, I'm wondering if my Serializer files and favorite_bikes_controller.rb file are contributing to the problem.

<img width="1375" alt="screen shot 2015-11-12 at 1 58 37 am" src="https://cloud.githubusercontent.com/assets/11621935/11112449/3acfd4b6-88e1-11e5-83ea-1e51f7e3b2c6.png">

**\* Update on #1: got a different error, now. Better error, IMO. Looks like my form is wrapping my data and ordering it incorrectly.

<img width="1403" alt="screen shot 2015-11-12 at 9 16 07 am" src="https://cloud.githubusercontent.com/assets/11621935/11120555/843b41de-891e-11e5-9be2-9b41d895ad92.png">

The correct order is _supposed_ to be:

"favorite_bike": {
    "favorite": true,
    "user_id": 2,
    "bike_id": 3
  }

issue #2. I can successfully create a new bike on the frontend, however, the data returned initially shows up as undefined and only shows up correctly if the browser is refreshed. This issue is new (I didn't have the data showing up as undefined after receiving the HTTP response earlier in the day). 

*\* Update on #2: I tested changing to different feature branches in my backend repo. From what I can tell, whatever I did with my serializers is causing the issue (changing to the branch where I didn't have my serializers set up allowed my frontend to reflect a bike creation correctly on the frontend).

**Comment by gaand** [comment]
Please paste the text of the code for the serializer, the action, and the JavaScript that invokes the action.

**Comment by resource11** [comment]
ISSUE 1 solved. Stand by for data for issue 2

**Comment by resource11** [comment]
The serializer:

class UserSerializer < ActiveModel::Serializer
  attributes :id, :email, :current_user
  has_many :bikes, :favorite_bikes, :favorites

  def current_user
    scope == object
  end
end

The submit action:

  // create new bike handler
  $('#bike').on('submit', function(e) {
    var bike = wrap('bike', form2object(this));

```
// test to see if the session.token is recognized
console.log(session.token);

// test to see if bike was created from wrap function
console.log(bike);

ssme_api.createBike(session.token, bike, createBikeCb);
e.preventDefault();
```

  });

the ssme_api.createBike() 

var ssme_api = {
  url: 'http://localhost:3000',

  createBike: function (token, bike, callback) {
    this.ajax({
      method: 'POST',
      url: this.url + '/bikes',
      headers: {
        Authorization: 'Token token=' + token
      },
      contentType: 'application/json',
      data: JSON.stringify(bike),
      dataType: 'json'
    }, callback);
  }

}

The callback function:

// createBike callback
var createBikeCb = function (error, bike) {
  if (error) {
    console.error(error);
    $(".user-messages").html("<strong>Error! Bike create fail!</strong>");
    return;
  }

  // console.log test
  console.log('data is ' + bike);

  var $newBike = $('#new-bike');
  var bikes = bike.title;

  // add the new bike to the current_user's bike bucket
  var $userBikeList = $('#user-bikes');
  $userBikeList.append('<div id=' + bike.id + ' class="bike-posts"><h3>' + bike.title + '</h3><p>' + bike.description +'</p><p> bike id: '+ bike.id +'</p><p> user id: '+ bike.user_id +'</p><button class="delete-bike">Delete this listing</button></div>');

  // add the new bike to the 'all bikes for sale' bucker
  var $bikeList = $('#all-bikes');
  $bikeList.append('<div id=' + bike.id + ' class="bike-posts"><h3>' + bike.title + '</h3><p>' + bike.description +'</p><p> bike id: '+ bike.id +'</p><p> user id: '+ bike.user_id +'</p><button class="favorite-bike">Favorite this bike</button></div>');

  // console.log for testing
  console.log('bikes are ', bikes);
  bike.bikeId = bike.title;
  console.log('My new bike is ', bike.bikeId);

};
// end of createBike submit handler

**Comment by gaand** [comment]
Please paste the code from the create action in BikesController.

**Comment by resource11** [comment]
```
  # POST /bikes
  def create
    @bike = current_user.bikes.new(bike_params)
    @bike.save

    if @bike.save
      render json: @bike, status: :created, location: @bike
    else
      render json: @bike.errors, status: :unprocessable_entity
    end
  end
```

**Comment by gaand** [comment]
It looks like you're calling save twice.  Which unfortunately isn't the problem.

This may require an in person consultation.

**Comment by resource11** [comment]
OK.

**Comment by GA-MEB** [comment]
This was JS problem - changing the serializer meant that the callback handler needed to change its references.
