### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#630]
Trying to ask a question I was asking before more succinctly now.

This is my create method now:
``` rb
  def create
    @review = current_user.reviews.build(review_params)

    if @review.save
      render json: @review, status: :created
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
```

I was not aware before that we should keep the syntax from the create in the example controller so closely to how it appears. When I try to add a review, this is the error I am not getting in my terminal:

NoMethodError (undefined method `reviews' for nil:NilClass):
  
app/controllers/reviews_controller.rb:19:in `create'

Line 19 is that 1st line in create, but it seems to be following the synax from the example_controller create now.  I believe reviews is supposed to be plural, but it is not being recognized.

**Comment by raq929** [comment]
This error means that current_user is nil. You either made a request without logging in and getting a token, or your controller does not inherit from `OpenReadController` or `ProtectedController`.

**Comment by alexkarasik** [comment]
I see. So I can not run the tests for reviews until I have properly done the sign-up/sign-in stuff for the front end?
I have a follow up question. Yesterday, Mike said he didn't see why I needed a user_id parameters for reviews, but my review table is the join table for the movies and users, so I think I need movie_id and user_id as the foreign keys for it to work. Is this right?

**Comment by raq929** [comment]
No, absolutely not. You should sign in via curl request and use the token from that for your other requests.  You should be able to test your entire backend before setting up the front end.
The user_id is set by doing `current_user.reviews.build`. You **must not** allow `user_id` as a param, as it is a **serious** security flaw and you will not meet expectations if you have it. (There is no ownership if I can change who owns something via a curl request.)
You will need the `movie_id` as a param.

**Comment by raq929** [comment]
Related to #607 and #360

**Comment by alexkarasik** [comment]
Ok, sorry, I remember that conversation now that you mention it. The confusion I was having before was regarding what current_user.reviews.build was doing exactly and now it makes a bit more sense. 
I am working on getting my server running to test my front end stuff now. I've done the html, but am a little confused on how to check the front-end with the back-end. I think I need both of the servers running together. 
Thanks

**Comment by raq929** [comment]
If this issue is resolved, please close it.

**Comment by MicFin** [comment]
Re-read what I said, it's not what you said above.
https://github.com/ga-wdi-boston/full-stack-project/issues/621#issuecomment-280882810
