### ISSUE TITLE
Have not been pushing my front end branch properly to my github

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#631]
Sorry to have 2 issues at once, but I just went to check my brach for the front end work I've been pushing on github and that branch wasn't even in my repo! I am not sure where my commits have been going. 
In the terminal, I have been adding commits from here:
~/Documents/wdi/project2/movieReview-client (client)

**Comment by raq929** [comment]
You should have two separate repos, one backend and one front end. 
I'm having trouble grokking what your problem is. 
What happens when you type `git status`?

**Comment by alexkarasik** [comment]
My apologies. I think I made a spelling error when I tried to push last time.
