### ISSUE TITLE
not recognizing store.athlete

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/full-stack-project#633]
Hi, I am trying to get it so my athlete stores upon creation so that I can use store.athlete when I'm creating a log, but I don't think it's recognizing the storage.
Here is my onCreateAthlete function where I thought I was telling it to store the athlete:
```js
const onCreateAthlete = function (event) {
  event.preventDefault();

  let data = getFormFields(event.target);
  api.create(data)
    .then((response) => {
      store.athlete = response.athlete;
    })
    .then(ui.onCreateSuccess)
    .catch(ui.onError);
};
```
my create log function:
```js
const create = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/logs',
    method: 'POST',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data: {
      data,
      athlete_id: store.athlete.id,
    }
  });
};
```
(^ That's where it tells me it doesn't recognize store.athlete)
Just for fun, here's my form to show that it is recognizing the other two parameters:
```html
      <form class='create-log' id="post-log">
        <fieldset>
          <div class="form-group">
            <input type="date" name="log[date_completed]" placeholder="Date">
            <input type="text" name="log[workout_id]" placeholder="Workout ID">
          </div>
          <button type="submit" class="btn btn-default">Create Log</button>
      </fieldset>
      </form>
```
Should I just add another form to have the user input their own athlete id? I feel like that's unnecessary/ not user friendly though.

**Comment by raq929** [comment]
Nooooo. You should never allow users to do that. (This is what I was talking about on the project channel.) You will need to set this up on the back end. 

Take a look at the create method in `ExamplesController` to see how.

**Comment by raq929** [comment]
Related: https://github.com/ga-wdi-boston/full-stack-project/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20ExamplesController

**Comment by laurpaik-zz** [comment]
Does this mean I won't be able to do store.athlete at all then? My controllers:
for Log:
```rb
  def create
    @log = current_user.logs.build(log_params)

    if @log.save
      render json: @log, status: :created
    else
      render json: @log.errors, status: :unprocessable_entity
    end
  end
```
For Athlete:
```rb
  def create
    @athlete = current_user.build_athlete(athlete_params)

    if @athlete.save
      render json: @athlete, status: :created
    else
      render json: @athlete.errors, status: :unprocessable_entity
    end
  end
```

**Comment by laurpaik-zz** [comment]
log params:
```rb
  def log_params
    params.require(:log).permit(:date_completed, :workout_id, :athlete_id)
  end
```
athlete params:
```rb
  def athlete_params
    params.require(:athlete).permit(:given_name, :surname,
                                    :date_of_birth)
  end
```

**Comment by laurpaik-zz** [comment]
I didn't want to do store.user.id because hypothetically the user id and the athlete id might not be the same number... But the person updating their log would need their athlete id in order to make the join table work.

**Comment by raq929** [comment]
Oh, I'm sorry, I think I misunderstood the question. Well, the first part of the question.
Cool. In your create log function, what do you get from `console.log(store.athlete.id)`?
When you say it doesn't recognize it, what do you mean?

**Comment by laurpaik-zz** [comment]
[This](https://goo.gl/photos/r7f8a1D51mMqXEqG7) --sorry, couldn't copy paste this time

**Comment by laurpaik-zz** [comment]
So I guess my create athlete event isn't doing what I want, but I'm not sure what else to do to store things other than the user
```js
const store = require('../store');

const onCreateAthlete = function (event) {
  event.preventDefault();

  let data = getFormFields(event.target);
  api.create(data)
    .then((response) => {
      store.athlete = response.athlete;
    })
    .then(ui.onCreateSuccess)
    .catch(ui.onError);
};
```

**Comment by raq929** [comment]
What happens if you do
```
.then((response) => {
      store.athlete = response.athlete;
      console.log(store.athlete)
    })
```

Also, just double-checking, you did import the store in your other file, correct?

**Comment by laurpaik-zz** [comment]
To be fair, I'm not even sure if this formatting is legit.. I was trying to say that the create function would get some of the data from getFormFields and the last parameter would be fulfilled with what I wanted `store.athlete.id` to mean:
```js
const create = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/logs',
    method: 'POST',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data: {
      data,
      athlete_id: store.athlete.id,
    }
  });
};

```

**Comment by raq929** [comment]
I think you likely need to add athlete.id to the data object you're getting passed, instead of adding it as a separate field in the data AJAX data object. But that's moot if athlete.id is undefined.

**Comment by raq929** [comment]
Wait, I want to back up a minute. Can I, as a user, create a log for an athlete that's not me?

**Comment by laurpaik-zz** [comment]
^to the most recent comment: In Terminal, I was not able to.

**Comment by raq929** [comment]
Right. In my mind, I shouldn't be able to make logs for other people. So I think `athlete_id` Does have to be the same as `user_id`, in which case, we don't have to worry about how to pass it, because the controller looks up the user based on the token and takes care of it for you.

**Comment by laurpaik-zz** [comment]
[console.log after creating a new athlete](https://goo.gl/photos/hrJZNWEio9CSSCXH9)
[new error after I try to get "Jason" to create a log](https://goo.gl/photos/pFXM6ZrTYMNm8Bpy7)
Server error:
```Started POST "/athletes" for 127.0.0.1 at 2017-02-19 20:44:57 -0500
Processing by AthletesController#create as */*
  Parameters: {"athlete"=>{"given_name"=>"Jason", "surname"=>"Paik", "date_of_birth"=>"1987-03-20"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "f08df9f3e2a4b50ba1d4e90ef56a23b8"], ["LIMIT", 1]]
  Athlete Load (0.2ms)  SELECT  "athletes".* FROM "athletes" WHERE "athletes"."user_id" = $1 LIMIT $2  [["user_id", 16], ["LIMIT", 1]]
   (0.1ms)  BEGIN
  SQL (0.3ms)  INSERT INTO "athletes" ("given_name", "surname", "date_of_birth", "created_at", "updated_at", "user_id") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["given_name", "Jason"], ["surname", "Paik"], ["date_of_birth", Fri, 20 Mar 1987], ["created_at", 2017-02-20 01:44:57 UTC], ["updated_at", 2017-02-20 01:44:57 UTC], ["user_id", 16]]
   (1.0ms)  COMMIT
[active_model_serializers]    (0.3ms)  SELECT "workouts"."id" FROM "workouts" INNER JOIN "logs" ON "workouts"."id" = "logs"."workout_id" WHERE "logs"."athlete_id" = $1  [["athlete_id", 16]]
[active_model_serializers] Rendered AthleteSerializer with ActiveModelSerializers::Adapter::Json (13.14ms)
Completed 201 Created in 26ms (Views: 11.6ms | ActiveRecord: 4.9ms)


Started POST "/logs" for 127.0.0.1 at 2017-02-19 20:47:00 -0500
Processing by LogsController#create as */*
  Parameters: {"data"=>{"log"=>{"date_completed"=>"2017-02-19", "workout_id"=>"1"}}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "f08df9f3e2a4b50ba1d4e90ef56a23b8"], ["LIMIT", 1]]
Completed 400 Bad Request in 3ms (ActiveRecord: 0.2ms)


  
ActionController::ParameterMissing (param is missing or the value is empty: log):
  
app/controllers/logs_controller.rb:53:in `log_params'
app/controllers/logs_controller.rb:20:in `create'
```
This is after I took out the weird line in log api:
```js
const create = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/logs',
    method: 'POST',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data: {
      data,
    }
  });
};
```

**Comment by laurpaik-zz** [comment]
Wait, but hypothetically if two users make accounts back to back and the second user finishes their athlete profile before the first user, would the ids not be different?

**Comment by laurpaik-zz** [comment]
(btw we are getting kicked out of District Hall... I'll look at this again when I get home)

**Comment by raq929** [comment]
The profile should be made at the same time as the user is created, I think, and then them 'creating' it is really just an edit. 
@gaand may be able to tell you more about best practices here.

**Comment by laurpaik-zz** [comment]
Are you saying I need a form for email, password/confirmation, given_name, surname, dob and have one sign-up button to submit all of it? Because if so I run into the issue of not being authorized to make an athlete profile... I tried changing my controller so that the create function is
```rb
  def create
    @athlete = Athlete.new(athlete_params)

    if @athlete.save
      render json: @athlete, status: :created
    else
      render json: @athlete.errors, status: :unprocessable_entity
    end
  end
``` 
instead of
```rb
  def create
    @athlete = current_user.build_athlete(athlete_params)

    if @athlete.save
      render json: @athlete, status: :created
    else
      render json: @athlete.errors, status: :unprocessable_entity
    end
  end
```
but I'm still unauthorized.

**Comment by raq929** [comment]
The second `create` is closer, but unlikely to work. It should be more like what's in the `ExamplesController`. I recommend experimenting in rails console to find what works here. However, you're not even getting to this function, because you're not authorized.

Being unauthorized is because you are not properly sending the token, and is independent of whether this create function works. (You should be testing this with curl, and once it works, do it from the front end.)

So, I want you to keep two forms the way it is now. But when the user is created, an (empty) profile should be created for them. They can then fill it out on the subsequent form.

**Comment by laurpaik-zz** [comment]
Okay, I'll play around with that. I may request a 1 on 1 tomorrow depending on how that goes though.
