### ISSUE TITLE
requesting a one on one for help with deployment

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/full-stack-project#635]
I still can't get the front end with heroku to work.  I have gone through the set up over again and have several heroku projects on my dashboard but am still not seeing my site.  Could somebody please help me Tuesday???

**Comment by raq929** [comment]
What do you mean by 'not seeing your site'? In the issue you closed (#615), I mentioned that you won't actually see anything at the root of a rails API.
What happens when you make curl requests to your deployed site?

**Comment by raq929** [comment]
The front end should be deployed using gitHub pages, the same way we deployed tic-tac-toe.

**Comment by raq929** [comment]
We can help on Tuesday, but I'd like you to try making curl requests first to your deployed site first.

**Comment by raq929** [comment]
Also, where you were on 615 was in a detached head state in git. I suggested you checkout to a branch. Did you do that?

**Comment by Soboscott** [comment]
I did not deploy to the front end on the first project... I failed that one.
so I'm not sure where to even look for the font end deployment site for this one.
I was very confused in what you meant about checkout to a branch, the detached head is in a different directory form my project.

**Comment by raq929** [comment]
OK. Let's focus on one step at a time, then. We'll start with the back end deployment.
What happens when you type `git status` in your back end repo?

**Comment by Soboscott** [comment]
this is what I get:

```

~/wdi/projects/trail-rater (inprogress)
$ git status
On branch inprogress
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   browser-template/assets/scripts/config.js
	modified:   browser-template/assets/styles/style.css
	modified:   browser-template/index.html
	modified:   spec/controllers/trails_controller_spec.rb
	modified:   spec/models/trail_spec.rb

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	bower_components/

no changes added to commit (use "git add" and/or "git commit -a")
~/wdi/projects/trail-rater (inprogress)
$ 


```

**Comment by raq929** [comment]
Cool. You're not in detached head state, so that's good! 
What's the result of `git remote -v`?

**Comment by Soboscott** [comment]
```

$ git remote -v
heroku	https://git.heroku.com/trail-rater.git (fetch)
heroku	https://git.heroku.com/trail-rater.git (push)
origin	git@github.com:Soboscott/trail-rater.git (fetch)
origin	git@github.com:Soboscott/trail-rater.git (push)
~/wdi/projects/trail-rater (inprogress)
$ 
```

**Comment by raq929** [comment]
Great! What happens on `git push heroku master`?
You may have to commit or stash your local changes before it allows you to push.

**Comment by Soboscott** [comment]
```

$ git push heroku master
Everything up-to-date
~/wdi/projects/trail-rater (inprogress)
$ 

```

**Comment by raq929** [comment]
Neat. What's the url for your heroku app?
As a check, what's on your master branch? Just the template, or have you made more commits?

**Comment by Soboscott** [comment]
The URL is: https://dashboard.heroku.com/apps/trail-rater
and on my master branch is just the template. all changes and commits have been in the inprogress branch.

**Comment by raq929** [comment]
That's the dashboard, which I can't see because I can't log in as you. I meant the weird url they generate for you `https://dancing-octopus` or some such.

**Comment by Soboscott** [comment]
it's : https://serene-basin-28916.herokuapp.com/

**Comment by raq929** [comment]
Could it be a different one? You said you made several ones, and since your heroku remote is `trail-rater` not `serene-basin`, I'm thinking that this possibly isn't the right one.

**Comment by Soboscott** [comment]
I have:
https://aqueous-oasis-85771.herokuapp.com/
https://damp-citadel-44524.herokuapp.com/
https://intense-stream-79331.herokuapp.com/
https://trail-rater.herokuapp.com/

**Comment by raq929** [comment]
Looks like the last one,  `https://trail-rater.herokuapp.com/` is all set to go. I'd double check it by signing up and signing in via curl request, but from what I can see, it's pushed and working. 

I navigated to `https://trail-rater.herokuapp.com/users`, a route that I know exists on the template, and got an `Unauthorized` error, which is what I would expect to get.

**Comment by raq929** [comment]
You can deploy the front end using `grunt deploy`. You'll have to add the production url `https://trail-rater.herokuapp.com/` to the config file.

**Comment by Soboscott** [comment]
I get this error:
```
$ grunt deploy
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
~/wdi/projects/trail-rater (inprogress)
$ 
```

**Comment by bernardlee** [comment]
You need to be in the front end directory.

**Comment by Soboscott** [comment]
THANK YOU!

**Comment by jrhorn424** [comment]
The status posted earlier:

```
~/wdi/projects/trail-rater (inprogress)
$ git status
On branch inprogress
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   browser-template/assets/scripts/config.js
	modified:   browser-template/assets/styles/style.css
	modified:   browser-template/index.html
	modified:   spec/controllers/trails_controller_spec.rb
	modified:   spec/models/trail_spec.rb
```

Suggests that the client is embedded in the API repository under the directory `browser-template`.
