### ISSUE TITLE
404 Not found for Sign -up/Server not receiving any info

### ISSUE THREAD

**Issue by s0phi4** [ga-wdi-boston/full-stack-project#637]
I am trying to test my auth for sign -up and I get the below error.
abstract-xhr.js:132 XHR finished loading: GET "http://localhost:7165/sockjs-node/info?t=1487607648446".
AbstractXHRObject._start @ abstract-xhr.js:132
(anonymous) @ abstract-xhr.js:21
2017-02-20 11:21:08.964 jquery.js:9536 POST http://localhost:7165/undefined/sign-up 404 (Not Found)
send @ jquery.js:9536
ajax @ jquery.js:9143
signUp @ api.js:7
onSignUp @ events.js:11
dispatch @ jquery.js:5201
elemData.handle @ jquery.js:5009
2017-02-20 11:21:08.964 jquery.js:9536 XHR finished loading: POST "http://localhost:7165/undefined/sign-up".
send @ jquery.js:9536
ajax @ jquery.js:9143
signUp @ api.js:7
onSignUp @ events.js:11
dispatch @ jquery.js:5201
elemData.handle @ jquery.js:5009
2017-02-20 11:21:08.968 ui.js:14 Object {readyState: 4, responseText: "Cannot POST /undefined/sign-up↵", status: 404, statusText: "Not Found"}

My code looks as follows and link to my repo is here 
Front end  https://github.com/yenpraja610/yenproject_front/tree/front_work
Back end   https://github.com/yenpraja610/yenproject

api_file
const config = require('../config');
const store = require('../store');

const signUp = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data,
  });
};

ui file
const successSignUp = (data) => {
  config.user = data.user;
  $('#exampleModalUp').modal('hide');
  $('.signup-clean').val('');
  $('.message').text('');
  console.log(data);
};

const failureSignUp = (data) => {
  console.log(data);
  $('.message').text('Nope, you used this account already, try with a different account!');
};

events file
const onSignUp = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.signUp(data)
    .then(ui.successSignUp)
    .catch(ui.failureSignUp);
};

**Comment by bernardlee** [comment]
There are several problems here and the root of this, from what I've seen so far, stems from `assets/scripts/index.js`.

**Comment by raq929** [comment]
Please format your issue so that we can read it. Mike posted guidelines in the project channel, and they can also be found at `ga-wdi-bos/project-issue-tracking-guide`

**Comment by s0phi4** [comment]
@bernardlee You are an angel!!! Problem solved! I looked every ui, api, events file except index.js
Thank you!!!
