### ISSUE TITLE
can not get server running

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#638]
I want to test my auth functionality, but I am getting an error that grunt is not installed. 
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started

So I enter this:
npm install -g grunt-cli

but it still doesn't seem to be working. I thought grunt was included already so I am not sure why I am having this issue.

**Comment by bernardlee** [comment]
Did you run `npm install` in the front end directory?

**Comment by alexkarasik** [comment]
No I did not. I forgot to do that. thank you.
