### ISSUE TITLE
User examples are not running properly 

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#639]
When I go into pry to test my users, I type User.all
and get the following error: 
NameError: uninitialized constant Users
from (pry):1:in `__pry__

I am not sure if you want me to post all my code from the User files, because I have not touched them and they are in the same state as they were given to us. 
I checked my files against Max's and they are the same as well.

**Comment by bernardlee** [comment]
Did you run `pry` or `bin/rails console`?

**Comment by alexkarasik** [comment]
yes

**Comment by alexkarasik** [comment]
I have an empty array when I do that:
[1] pry(main)> User.all
  User Load (0.9ms)  SELECT "users".* FROM "users"
=> []

**Comment by bernardlee** [comment]
I meant, "Which command did you run?" when you got that error.  Did you run `pry` for your initial post post and then `bin/rails console` after I responded?  `User.all` is returning an empty array because there aren't any `User` records (no rows in the `users` table).

**Comment by alexkarasik** [comment]
Sorry, I am a bit confused. I just run bin/rails console and then I am in pry. Then I enter User.all. I am not sure what I am missing to get the examples to display.

**Comment by bernardlee** [comment]
Are you referring to "examples" as in records being created via `db/examples.rb` or instances of the `Example` model that `User`s own?

**Comment by alexkarasik** [comment]
I just want the users examples in db/examples.rb to run to make sure users is working properly.

**Comment by bernardlee** [comment]
What does `db/examples.rb` look like?

**Comment by alexkarasik** [comment]
This is all that is not commented out in that file:

%w(antony jeff matt jason).each do |name|
  email = "#{name}@#{name}.com"
  next if User.exists? email: email
  User.create!(email: email,
               password: 'abc123',
               password_confirmation: nil)
end

**Comment by bernardlee** [comment]
What have you tried doing to load the example data?

**Comment by alexkarasik** [comment]
I don't understand your question, sorry

**Comment by bernardlee** [comment]
What are you doing (or what have you tried doing) to get the example data into the database?

**Comment by alexkarasik** [comment]
EMAIL='jeff' PASSWORD='abc123' sh scripts/sign-in.sh

**Comment by bernardlee** [comment]
That's a terminal command to execute a shell script to test signing in.  That has nothing to do with `db/examples.rb`, which is what we've been discussing.

**Comment by alexkarasik** [comment]
I guess I don't know what the command to do that is. When I was running the shell command before,  I am getting this error: 
ActiveRecord::PendingMigrationError (

Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=development

):

I am running this command, but nothing is changing.

**Comment by raq929** [comment]
You need to exit the shell, and then run the migrations.

**Comment by alexkarasik** [comment]
When I do, this is the error I am getting:

-- add_reference(:reviews, :user, {:foreign_key=>true})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "user_id" of relation "reviews" already exists
: ALTER TABLE "reviews" ADD "user_id" integer

What happened was I did a migration for user_id's because I thought I needed one... so I think I need to delete it, because that was unneccesary.

**Comment by raq929** [comment]
Seems like it! Try it and see what happens.

**Comment by alexkarasik** [comment]
Ok, I deleted it and am now I am getting a 400 error when I try to run this command: 
$ EMAIL='jeff' PASSWORD='abc123' sh scripts/sign-in.sh

which is better, but I am not sure about the command that bernard was speaking about regarding moving the example data into the database

**Comment by bernardlee** [comment]
Review this repository: [Rails API Overview](https://github.com/ga-wdi-boston/rails-api).

**Comment by alexkarasik** [comment]
bin/rake db:examples is what I did last and I think that was correct

**Comment by alexkarasik** [comment]
but when I try to run the scripts, they still do not work, but I am not sure if that means I am getting ahead of myself.

**Comment by raq929** [comment]
If you type `bin/rails console`
And then in the rails  console, `User.all` do you see a list of users?

**Comment by raq929** [comment]
If yes, then you have the users, and you're not running the curl request correctly. If no, then something went wrong with `bin/rake db:examples

**Comment by alexkarasik** [comment]
Definitely making progress, because now I have this: 
``` rb
[1] pry(main)> User.all
  User Load (0.7ms)  SELECT "users".* FROM "users"
=> [#<User:0x007f95343874a0
  id: 1,
  email: "antony@antony.com",
  token: "39a6d16ce4014e5491c738be03b2cbdc",
  password_digest:
   "$2a$10$nfFOiViyqlr7OUwlNHhoQew5IxKgVzzC.Md5.u5r5JLyjp68PAyuS",
  created_at: Mon, 20 Feb 2017 19:46:11 UTC +00:00,
  updated_at: Mon, 20 Feb 2017 19:46:11 UTC +00:00>,
 #<User:0x007f953435d358
  id: 2,
  email: "jeff@jeff.com",
  token: "90b9edbfc368a19d63c9c33e2e981ec1",
  password_digest:
   "$2a$10$uvSz.C.J9TBBDlStwvKma.Kst43yQ9n.P4oHsYFuZTJKIdDNyh9Vm":
```
I am happy about this, but know it is not completely right... there are supposed to be 4 users in the example and only 2 are coming up and jeff is not giving my the created_at or updated_at info either.

**Comment by alexkarasik** [comment]
Oh gosh, so sorry, but when I keep pressing enter, the rest of the info is there. I don't know why it cut some of it off when displaying, but I think I am good and can close this issue now. Thanks.
