### ISSUE TITLE
Help with seed data for Heroku deployment

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/full-stack-project#64]
So, I'm using data for my app that was given to me by the Sacred Harp organization, which means I have two issues.
1) This data is not mine, and I probably shouldn't commit it. So I don't know how to get it to heroku. I have done some testing on heroku with dummy data, but I'd like to get the actual data up. 
2) I have a LOT of data. It took about 40 minutes to import it to my database. Right now I'm using a lot of #find_or_create_by, and there has to be a faster way, so I'm looking for advice on how to optimize my data loading.

**Comment by gaand** [comment]
Are you wrapping that in a transaction?  If not, that will likely speed things up a lot.

What format is the data?

**Comment by raq929** [comment]
The data is JSON. I am not clear about how transactions work. I tried to use them in a different (similar!) part of the project, but it did not seem to work (ie, it created the singing, but did not rollback when subsequent creates failed.) I read about nested transactions in the rails docs, but I didn't really get it. 

So, I'm passing an array of singings to the script, and it takes the first singing, creates a singing, then creates 'callers' if they don't exist, then creates 'calls' using the caller and singing IDs, and song IDs. It gets the songs IDs from the json as well, but they are marked up, and it has to remove the markup and create a song or find it as appropriate.
 Then moves on to the next singing.

**Comment by gaand** [comment]
I suggest this in your script (unless you've already tried it):

``` rb
Singing.transaction do
  # all find or creates go here
end
```

**Comment by raq929** [comment]
I tried that in a similar script (for loading one singing instead of many). It created the singing, but when it failed to create the calls, I got an error, but it did not rollback the singing creation. Which I think means it's not working right?

**Comment by gaand** [comment]
As we discussed, that is quite strange.  Please share the code that didn't work (low priority).
