### ISSUE TITLE
Think I am using the wrong attributes for reviews

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#644]
I have movie_id, movie and review as my attributes for my Review table:
``` rb
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/reviews"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "review": {
      "movie_id":"'"${MOVIE_ID}"'",
      "movie": "'"${MOVIE}"'",
      "review": "'"${REVIEW}"'"
    }
  }'

  echo
```
but now I don't think I need a movie_id or even a movie. Because I created a migration file, AddReviewsToMovies, I believe that my single-to-many relationship of movies to many reviews should be covered... so I am thinking that the only attribute I need for reviews now may just be REVIEW. Is my thinking correct?

**Comment by alexkarasik** [comment]
After a discussion with a peer, my relationships are fine, but I will be taking out the movie title and just having the id, since they are linked together. I will be filing a new issue as my problem has now changed and I feel like this one is resolved.

**Comment by jrhorn424** [comment]
> After a discussion with a peer

@MicFin said as much here: https://github.com/ga-wdi-boston/full-stack-project/issues/621#issuecomment-280882810
