### ISSUE TITLE
Modal not hiding properly

### ISSUE THREAD

**Issue by samordonez** [ga-wdi-boston/full-stack-project#645]
I am trying to do something which is perhaps too complicated: I am using a modal to allow users to update books, and once that book has been updated, I want to hide the modal and replace the html element for the book with new information obtained by a show request for the same book. The issue I am having is that the html updates properly and the modal itself goes away, but not the grey filter on the window that prevents the user from clicking anything.

I am using handlebars to add the individual list elements, my template look like this:
```
<ul data-id="{{book.id}}">
  <li> <h4>Title: {{book.title}}</h4></li>
  <li>Author: {{book.author}}</li>
  <li>Published In: {{book.published_in}}</li>
  {{#if book.description}}
    <li>{{book.description}}</li>
  {{else}}
    <li>No description.</li>
  {{/if}}
  {{> update-book-modal book=book}}
</ul>
```
Where the `update-book-modal` partial creates a standard bootstrap modal with an id of `updateBookModal-<id>` and the corresponding button to bring up the modal

The handlers for the update book forms are added like this:
```
  // add event handlers to update books
  $('.updateBookForm').on('submit', function (event) {
    event.preventDefault();
    let data = getFormFields(event.target);
    let bookId = event.target.dataset.book;
    // $('#updateBookModal-' + bookId).modal('hide');
    api.updateBook(data, bookId)
      .then(function () {
        $('#updateBookModal-' + bookId).modal('hide');
      })
      .then(function () {
        // $('.updateModal').modal('hide');
        api.showBook(bookId)
          .then(onUpdateSuccess)
          .catch(onFailure);
      })
      .catch(onFailure);
  });
```

and the onUpdateSuccess function looks like this:
```
const onUpdateSuccess = function(data) {
  let updatedBookHtml = listEntry({ book: data.book });
  $("ul[data-id='" + data.book.id +"']").replaceWith(updatedBookHtml);
};
```

I am aware that I may have issues with the newly created update buttons not having event handlers, but that is not something I can even address until this is fixed. In case I have missed any relevant info, the most up to date version of the code, with the error present, can be found here: https://github.com/Sofistication/book-next/tree/update-books

**Comment by samordonez** [comment]
I am going to try something based on https://github.com/ga-wdi-boston/full-stack-project/issues/634 I will update this once I have.

**Comment by samordonez** [comment]
adding the setTimeout as suggested in the above issue helped, shoutout to @wilsonkaya for pointing me to that issue.

**Comment by samordonez** [comment]
Small update: `setTimeout` was not actually what solved this issue, I only thought it was. It seems that having the modal be hidden in a `.then` followed by a second `.then` to make the api show call is actually what solved this.

Event handler added like this:
```
// add event handlers to update books
  $('.updateBookForm').on('submit', function (event) {
    event.preventDefault();
    let data = getFormFields(event.target);
    let bookId = event.target.dataset.book;
    api.updateBook(data, bookId)
      .then(function () {
        $('#updateBookModal-' + bookId).modal('hide');
      })
      .then(function () {
        api.showBook(bookId)
          .then(onUpdateSuccess)
          .catch(onFailure);
      })
      .catch(onFailure);
  });
```

and onUpdateSuccess being (note that the setTimeout is commented out)
```
const onUpdateSuccess = function(data) {
  let updatedBookHtml = listEntry({ book: data.book });
  // setTimeout( function () {
    $("ul[data-book='" + data.book.id +"']").replaceWith(updatedBookHtml);
  // }, 1475);
};
```
works. I'm not sure why this wasn't working previously, I think in trying to debug I was commenting and uncommenting various things and causing more problems.

**Comment by jrhorn424** [comment]
http://getbootstrap.com/javascript/#modals-methods

**Comment by jrhorn424** [comment]
https://github.com/ga-wdi-boston/full-stack-project/issues/636#issuecomment-281119805
