### ISSUE TITLE
HTTP Token: Access denied.

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#646]
I have verified that my users are now working correctly. I successfully signed up and signed in. 
This is the token I was given:
```js
{"user":{"id":6,"email":"NAH@NAH","token":"BAhJIiVkYjkzM2ZjM2MxYWJlM2NhOTlmM2Q1ZDgzMDExZDUxMAY6BkVG--ca3ec04a3c0b1455642301406090d9402cf2622f"}}
```
And this is the next command I put in: 
```js
$ TOKEN="BAhJIiVkYjkzM2ZjM2MxYWJlM2NhOTlmM2Q1ZDgzMDExZDUxMAY6BkVG--ca3ec04a3c0b1455642301406090d9402cf2622f" MOVIE_ID=1 REVIEW="It's good" sh scripts/reviews/create.sh
```
and that is when I get the error I posted in the title and a 401 error, but as far as I can tell, my token and order in making the call are correct.

**Comment by bernardlee** [comment]
You're missing something very important in `scripts/reviews/create.sh`.  The 401 response that you got will point you in the right direction.

**Comment by alexkarasik** [comment]
I saw what you were referencing was that I was not including this line:
```js
  --header "Authorization: Token token=$TOKEN" \
```
So I added it, but now I am getting a new 500 error:
```js
NoMethodError (undefined method `review_entry' for #<Review:0x007fb56bde3578>
Did you mean?  review_id):
```
I am not sure if you want me to post the old error, but I know where this error is coming from. It was recommended to me to not have a parameter named "review" in my Review module. So now, my parameters are a bit different from when i created them. I now have: 
``` rb
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/reviews"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "review": {
      "movie_id": "'"${MOVIE_ID}"'",
      "reviewentry": "'"${REVIEW_ENTRY}"'"
    }
  }'

  echo
```

So I went back and changed them all, but I am not sure if I should touch anything in my schema, where I do not have this old attribute, but the old "review" instead.

**Comment by raq929** [comment]
You should **never** edit your schema file. That file is auto-generated by rails and should never be edited by hand.

The new error is a problem with your controller. Please post your controller's `create` method, the `review_params` method, and your schema for the review table. 
How did you change the names of the attributes? If you didn't use a migration, that's likely the problem here.

**Comment by alexkarasik** [comment]
I didn't use migration and I am nit sure exactly how to write it and get rid of the old one, so I don't want to create a bigger problem for myself than I already have. Here is the code you asked for. The schema still has the old movie and review params.

``` rb
  def create
    @review = current_user.reviews.build(review_params)

    if @review.save
      render json: @review, status: :created
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
```
```rb
  def review_params
    params.require(:review).permit(:movie_id, :review_entry)
  end

  private :review_params
```
``` rb
  create_table "reviews", force: :cascade do |t|
    t.integer  "movie_id",   null: false
    t.string   "movie",      null: false
    t.string   "review",     null: false
    t.integer  "user_id",    null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "review_id"
    t.index ["movie_id"], name: "index_reviews_on_movie_id", using: :btree
    t.index ["review_id"], name: "index_reviews_on_review_id", using: :btree
    t.index ["user_id"], name: "index_reviews_on_user_id", using: :btree
  end
```

**Comment by bernardlee** [comment]
Is `reviews` your join table?  If so, then why does it have `movie` and `review` columns?

**Comment by alexkarasik** [comment]
That is my issue. I am trying to get rid of those and replace them with movie_id and review_entry columns.

**Comment by bernardlee** [comment]
Refer to section 2.1 in [Active Record Migrations](http://guides.rubyonrails.org/active_record_migrations.html#creating-a-standalone-migration) on how to write a migration to remove columns.

**Comment by raq929** [comment]
OK, so we fixed this issue in a one on one. Please post what we did and close the issue. (New problems that are related should be a new issue.) Thanks!

**Comment by alexkarasik** [comment]
I created some Users to my database and then we dropped the unneccessary columns and changed their names by using this migration: bin/rails generate migration FixReviewColumnName
