### ISSUE TITLE
1 on 1 request tomorrow

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#647]
I am having a few issues with my join table and would like to do a one on one tomorrow. Thanks

**Comment by raq929** [comment]
Please give us more information about your issue here. What are you trying to do? What is going wrong? What have you tried?

**Comment by alexkarasik** [comment]
I have an issue in the queue, but I think in this case talking and showing the situation in person would be more effective. I want to change the name of an attribute in my join table and I want to make sure I do it the right way and that variable name is in many different files. I do not want to cause bigger problems. 
My attributes used to be MOVIE, MOVIE_ID and REVIEW but now they are just MOVIE_ID and REVIEW_ENTRY.
```rb
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/reviews"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "review": {
      "movie_id": "'"${MOVIE_ID}"'",
      "review_entry": "'"${REVIEW_ENTRY}"'"
    }
  }'

  echo
```

**Comment by alexkarasik** [comment]
Is there a time we can meet soon? I am not sure how to proceed.

**Comment by raq929** [comment]
Let's meet now.
