### ISSUE TITLE
div hide/show side-effect

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/full-stack-project#648]
Goal: have the index action called when successful create action.
Both actions currently work independently and when I sign in all divs (including the create button) show/hide properly when signing in/out.

Issue:
If I call the index function in **createSuccess** and require it as such:
```javascript
const crudEvents = require('./events.js');     // <== HERE

const createSuccess = () => {
  $('#createClimbModalLabel').text('Create Climb');
  $('#createClimbModal').modal('hide');
  crudEvents.onIndexAnShow();       //  <== HERE
};
```
events.js is a sibling file (same parent).

events.js:
```javascript
const onIndexAnShow = function () {
    api.index()
    .then(ui.indexSuccess)
    .catch(ui.indexFailure);
};

module.exports = {
  onIndexAnShow,
};
```

Then, when I sign in, on the whole view only the create modal button appears and no other divs.
Without those 2 lines, all the divs display properly.
I am confused because the 2 lines that are added are not related to appearances. Neither has a climb been created successfully/error...WAT?

Everything should display correctly and when I create a climb, the index should be called to display the updated index of all the climbs.

**Comment by raq929** [comment]
I wonder if you have a circular dependency here. What file is `createSuccess` in? 
If you look at the network tab, are the requests you're expecting being made?

**Comment by doremaxime** [comment]
Circular dependency you say ay?
```createSuccess``` is in ```assets/scripts/crud/ui.js```.
Without the 2 lines in the first comment the create action logs in the console, but not for the index when create is successful.
As for the network tab (which I am now finding about), this is what shows up after a climb is successful:
![screen shot 2017-02-20 at 11 23 27 pm](https://cloud.githubusercontent.com/assets/24608045/23150728/bfdb783e-f7c3-11e6-8fe7-3bb61c9beb01.png)
Not sure what it all means... for now!

**Comment by raq929** [comment]
The network tab is confirming what you told me. A climb is created, (the 201) at the bottom, but there's no get request made afterwards.
It does look like you're making three get requests before the post... Is it possible that this request is made?

But because of the visual thing, I think something else is going on as well. Let's meet this morning and I'll take a look.

**Comment by doremaxime** [comment]
Ok, 1-1 would be great!

**Comment by doremaxime** [comment]
What time can you schedule?

**Comment by raq929** [comment]
Come by at 10:15? I'm in classroom 6.

**Comment by jrhorn424** [comment]
FWIW, two of the logged requests with status 200 are initiated by the same code, but the one in the middle is likely an OPTIONS request with a status of 200.

I know @raq929 accepted your 1on1 request, but I'd like for you to also post your `ui.indexSuccess` and `ui.indexFailure` code, please.

**Comment by doremaxime** [comment]
Thank you Jeff!

ui.indexSuccess:
```javascript
const indexSuccess = (data) => {
  console.table(data.climbs);
  $('.update-delete-container').css('display', 'unset');
  $('.index').css('display', 'unset');
  // $('.index').text('');

  let indexClimbsHtml = indexClimbsHandlerbars({ climbs: data.climbs });
  $('.table-striped').html(indexClimbsHtml);

  resetTitles();
};
```

ui.indexFailure:
```javascript
const indexFailure = (data) => {
  console.log(data);
  $('#index-show-title').text("you haven't logged any yet! get to work!");
  resetTitles();
};
```

**Comment by raq929** [comment]
We resolved this in a 1:1. Please update with the code we used and close. Thanks!

**Comment by doremaxime** [comment]
Solution:
Forget those 2 lines of code mentioned originally. There was a circular dependency so the the requiring of the file was messing all the display.

Instead (and very simply), just called the function in a  ```.then``` of the other function:
```javascript
const onCreate = function (event) {
  event.preventDefault();

  let data = getFormFields(event.target);

  api.create(data)
    .then(ui.createSuccess)
    .then(onIndexAnShow) // <=== HERE I call the function when create is successful!
    .catch(ui.createFailure)
    ;
};
````
