### ISSUE TITLE
Adding foreign keys when scaffolding resource

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/full-stack-project#649]
Is there a way to add a foreign key at the beginning when you scaffold a new resource?

I tried looking this up but the results only show adding the foreign keys to the table with this format
(that's an example)

```ruby
rails g migration add_category_id_to_expenses category_id:integer
rake db:migrate
```

**Comment by AshlenPrice** [comment]
I think I may have found a solution .... I tried the second answer with 5 votes [here](http://stackoverflow.com/questions/26800569/ruby-on-rails-scaffold-need-to-include-foreign-keys). Can someone just give a glance over just in case you may have additional input.

**Comment by bernardlee** [comment]
Check near the end of section 2.1 in [Active Record Migrations](http://guides.rubyonrails.org/active_record_migrations.html#creating-a-standalone-migration).

**Comment by raq929** [comment]
You should always use `references` over `integer` so that rails and postgres know that the integer isn't just any integer, it's a reference to another table.

**Comment by AshlenPrice** [comment]
Thanks, I tried this method
```rails generate scaffold Reader name:string grade:string user:references```
