### ISSUE TITLE
Adding additional scripts

### ISSUE THREAD

**Issue by ddobson** [ga-wdi-boston/full-stack-project#650]
I just integrated a [bootstrap theme](http://demos.creative-tim.com/material-kit/index.html) into my project. I was able to add the SCSS styles without much trouble but I am unsure how to proceed to get the scripts for animation working. In the index.html file there is a comment saying that scripts should not be added unless we know what we are doing. I know we're using Webpack to bundle the JS and I am not sure if I should configure these scripts with that and if so, how I would go about it. Any direction you can give me?

**Comment by raq929** [comment]
Integrating a bootstrap theme is often asking for trouble. They often use a different version of jQuery than we do, which is going to cause problems. I would recommend instead figuring out which parts of the theme you want in your project, and integrating them yourself. 
The bootstrap documentation is fairly thorough: http://getbootstrap.com/2.3.2/components.html

**Comment by raq929** [comment]
In 015, people who tried to integrate themes ended up having to abandon them. 😢

**Comment by MicFin** [comment]
@raq929 is giving good advice.  If integrating this theme is part of your `Exceeds Requirements` goals then share the folder/file structure here and we can discuss the best way to implement.  If it is not part of your goal to `Exceed Requirements` then I would not waste time on integrating the template.

**Comment by ddobson** [comment]
Okay, well I'm very close to completing requirements. I'll focus on finishing that today and reopen this issue tomorrow if I have time.

**Comment by raq929** [comment]
Cool. Incorporating bootstrap is a goal, not incorporating a bootstrap theme. I'd work on figuring out how to get the things you want working without grabbing a pre-made theme. You'll learn more about how bootstrap works and be better able to understand those themes later.

**Comment by raq929** [comment]
Also, THANK YOU for reading that comment and asking before adding the script. 😄

**Comment by ddobson** [comment]
I am requirement complete! Is it possible to set up some time today to look into adding the JS I need for my theme's animations?

**Comment by MicFin** [comment]
You are set to meet with @gaand at 4pm.

**Comment by raq929** [comment]
While you wait: http://getbootstrap.com/javascript/

**Comment by jrhorn424** [comment]
@ddobson We had a slight miscommunication. I'll meet with you at 4pm, not @gaand. Thanks! 😄

**Comment by raq929** [comment]
Dale, was this issue resolved? If so, please post how you resolved it and close.

**Comment by ddobson** [comment]
Jeff helped me get the form animations going by installing with npm and loading in Webpack. Resolving!
