### ISSUE TITLE
422 Unprocessable Entity (User Must Exist)

### ISSUE THREAD

**Issue by spwisner** [ga-wdi-boston/full-stack-project#651]
For this portion of the project, a user needs to be able to create multiple students.  I think the error could be the token (the input and output token in the error do not match - also, after signing out and signing in the token is the same).  When I try to run a curl request for create, I keep getting an error:

![image](https://cloud.githubusercontent.com/assets/13546265/23169406/a4ef4d10-f819-11e6-88fe-7afc07f88fc6.png)

![image](https://cloud.githubusercontent.com/assets/13546265/23169428/b6c9a13e-f819-11e6-9a9c-0441b8704243.png)

Here is the associated code:

Student Controller
```rb
# frozen_string_literal: true

class StudentsController < OpenReadController
  before_action :set_student, only: [:show, :update, :destroy]
  # GET /students
  def index
    @students = Student.all
    render json: @students
  end

  # GET /students/1
  def show
    render json: @student
  end

  # DELETE /students/1
  def destroy
    @student.destroy
    head :no_content
  end

  # PATCH/PUT /students/1
  def update
    if @student.update(student_params)
      render json: @student
      # head :no_content
    else
      render json: @student.errors, status: :unprocessable_entity
    end
  end

  # POST /students
  def create
    # @student = current_user.build_student(student_params)

    @student = Student.new(student_params)

    if @student.save
      render json: @student, status: :created
    else
      render json: @student.errors, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    # @student = Student.find(params[:id])
    @student = Student.where(id: params[:id], user: cuerrent_user).take
  end

  # Only allow a trusted parameter "white list" through.
  def student_params
    params.require(:student).permit(:first_name, :last_name, :born_on,
                   :school, :teacher, :grade)
  end

  # Archived student-params before fail under update
  # def student_params
  #   params.require(:student).permit(:first_name, :last_name, :born_on,
  #                                   :school, :teacher, :grade)
  # end
end
```

Student Model
```rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :observations, inverse_of: :student, dependent: :destroy
  validates :first_name, :last_name, :born_on,
            :school, :teacher, :grade, presence: true
end
```

Student Serializer

```rb
# frozen_string_literal: true

class StudentSerializer < ActiveModel::Serializer
  attributes :id, :first_name, :last_name, :born_on, :school, :teacher, :grade,
             :editable

  def editable
    scope == object.user
  end
end
```

CREATE CURL REQUEST
```rb
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/students"
curl "${API}${URL_PATH}" \
  --include \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "student": {
      "first_name": "'"${FIRST_NAME}"'",
      "last_name": "'"${LAST_NAME}"'",
      "born_on": "'"${BORN_ON}"'",
      "school": "'"${SCHOOL}"'",
      "teacher": "'"${TEACHER}"'",
      "grade": "'"${GRADE}"'"
    }
  }'
```

**Comment by MicFin** [comment]
Is your CURL request missing anything?

```rb
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/examples"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "example": {
      "text": "'"${TEXT}"'"
    }
  }'

echo
```
https://github.com/ga-wdi-boston/rails-api-bdd/blob/solution/scripts/create-example.sh

**Comment by MicFin** [comment]
Use `binding.pry` in ruby like you use `debugger` in javascript.

```rb 
# POST /students
  def create
    # add binding.pry here and see what the following return to help you debug: 
    # params
    # student_params
    # @student = current_user.build_student(student_params) and then @student.save
    # @student = Student.new(student_params) and then @student.save
    binding.pry
    @student = Student.new(student_params)

    if @student.save
      render json: @student, status: :created
    else
      render json: @student.errors, status: :unprocessable_entity
    end
  end

**Comment by raq929** [comment]
Yeah, figure out what the token you have there is. It may simply be a question of you not setting it correctly in your request, so it's using an old one.

**Comment by spwisner** [comment]
I made a mistake when posting code before - the curl request did include the post.  

When trying binding.pry with 
```rb
@student = Student.new(student_params) 
# I received the same error ({user: must exist})
```

When trying binding.pry with 
```rb
@student = current_user.build_student(student_params)
# NoMethodError (undefined method `build_student' for #<User:0x007fadae2300d8>).
```

What do I do if it is the token?  I logged out and logged in again and used the new token with a new create curl request.  Why wouldn't it process the new token?

Thanks,
Steve

**Comment by MicFin** [comment]
What did you get with `binding.pry` and checking `params` and `student_params`?
Please share your `user.rb`.

**Comment by spwisner** [comment]
I don't think I understand binding.pry

Here is my input for the controller
![image](https://cloud.githubusercontent.com/assets/13546265/23172822/1e9bb40e-f825-11e6-81c4-579178280dfe.png)

![image](https://cloud.githubusercontent.com/assets/13546265/23172838/2d1a77ea-f825-11e6-9a98-2a023a627cf3.png)

Here is the output
![image](https://cloud.githubusercontent.com/assets/13546265/23172875/4e47861a-f825-11e6-9872-b6564ea3d79b.png)

![image](https://cloud.githubusercontent.com/assets/13546265/23172905/68b80196-f825-11e6-91d2-a8d13207b9d9.png)

This doesn't really tell me anything (at least i don't think).  Am I misusing it?  

For instance, when you ask for binding.pry with params do you want this in the controller:

![image](https://cloud.githubusercontent.com/assets/13546265/23172958/99708d3a-f825-11e6-901e-632bcf67637f.png)

Or, do you want params to be part of the @students?  

Further explanation in terms of what i need to do would be helpful.  Thanks.

**Comment by MicFin** [comment]
I am coming over to show you how to use `binding.pry` properly.

**Comment by spwisner** [comment]
For Rachel:

In terms of the token, this is the information in the Rails console related to the user creating the student:

![image](https://cloud.githubusercontent.com/assets/13546265/23173355/e95c4798-f826-11e6-9de0-59de9e129ec1.png)

Note the token provided in this instance.

Next, after signing-in, I get a much longer token
![image](https://cloud.githubusercontent.com/assets/13546265/23173445/2a602476-f827-11e6-86e0-c8b8b99ddfef.png)

Next, when creating the student, I entered: 
![image](https://cloud.githubusercontent.com/assets/13546265/23173569/9436ec2c-f827-11e6-84c6-a8fbc874c57d.png)

**Comment by spwisner** [comment]
Mike helped me with solution to this problem:

The problem was that users have a one to many relationship with students.  Therefore, in my students controller, I ****could not**** use the `@student = current_user.build_student(student_params)`.  Instead, I had to use: `@student = current_user.students.build(student_params)`.  For details, view stackoverflow: http://stackoverflow.com/questions/1993615/has-many-build-method-rails

Students Controller:

```rb
  def create

    @student = current_user.students.build(student_params)

    if @student.save
      render json: @student, status: :created
    else
      render json: @student.errors, status: :unprocessable_entity
    end
  end
```

**Comment by jrhorn424** [comment]
Good work. The token is actually the same. What you see inside Rails is the unencrypted token, what you see in the JSON response is an encrypted token.
