### ISSUE TITLE
Issue: Not having any issues

### ISSUE THREAD

**Issue by dsweetser** [ga-wdi-boston/full-stack-project#654]
Hey Team!

I'm very confused by the fact that I haven't been stuck enough to file any issues.  Should I be worried about this?  I have an ugly app but it seems to be fully CRUD'ing my Sessions table like it should with ownership.

My app is located here: https://dsweetser.github.io/HMM-Front/ 

Repos are here: https://github.com/dsweetser/HMM-Front
and here: https://github.com/dsweetser/HMM-API

Thanks for your help!
Dan

**Comment by MicFin** [comment]
Trying to Sign Up I received `Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Comment by dsweetser** [comment]
Interesting! My hero! Thanks so much for finding that!
