### ISSUE TITLE
request 1-1

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/full-stack-project#657]
I know I am not fully done with my project
I've managed to create, show, delete, update for comments.
But I really want to start figuring out how to add movies from my api. I know that in order to avoid having 'dirty data' I have to specify which aspects of the movies I want to save to my database. 

Basically, I just need someone to tell me what I need to do next and whether I still have a lot more to do before I can start this. I'm kind of stuck.

**Comment by raq929** [comment]
OK, so, have you met requirements? As in, you have full crud, back and front end on one resource, with user ownership, and no bugs?
If you don't have that, then I'd say work on that. If you do, then you can move on. I wouldn't save any movie data to your database except it's id (From the third party API.)

**Comment by ggabrakadabra** [comment]
ok so I definitely have stuff to work on. But I will be back.
