### ISSUE TITLE
 Unable to autoload constant REVIEW

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#658]
I am trying to add a review to the first of 3 movies currently in my database with the following command: 

REVIEW.create(movie_id:"1", review_entry:"It's good")

This is the full error I am getting: 

LoadError: Unable to autoload constant REVIEW, expected /Users/alexkarasik/Documents/wdi/project2/movie-review/app/models/review.rb to define it
from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:512:in `load_missing_constant'

I believe this error is saying that there is a problem with my Review model, but I don't see anywhere I am making a mistake:
``` rb
# frozen_string_literal: true
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  validates :movie_id, presence: true
  validates :review_entry, presence: true
end
```

**Comment by raq929** [comment]
Why do you have `REVIEW` in all caps?

**Comment by alexkarasik** [comment]
Because I was not being careful enough. That was it, thanks.
