### ISSUE TITLE
NoMethodError: undefined method `reviews'

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#659]
I have signed up and signed in and am trying to create a review for a movie. 
This was my last command: 

$ TOKEN="BAhJIiU2NGY1ZWNjOTI4MzU5Y2Q4N2UwNDIwNGJmNDk4NzFlMgY6BkVG--dd26e77a4a4776971ae39634d0fce319a136784" MOVIE_ID=1 REVIEW_ENTRY="It's good" scripts/reviews/create.sh 

When I enter this to look at it: $ ID=1 sh scripts/reviews/show.sh 

I get a 500 error that starts off like this:
{"status":500,"error":"Internal Server Error","exception":"#\u003cNoMethodError: undefined method `reviews' for nil:NilClass\u003e","traces":{"Application Trace":[{"id":0,"trace":"app/controllers/reviews_controller.rb:44:in `set_review'"}],

and here is my server error:
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms)

  
NoMethodError (undefined method `reviews' for nil:NilClass):
  
app/controllers/reviews_controller.rb:44:in `set_review'

Here is the line in my controls it is referring to:
```rb
  def set_review
    @review = current_user.reviews.find(params[:id])
  end
  private :set_review
```

**Comment by raq929** [comment]
You are probably missing the relationship on your model. Compare to the `examples` model (and the `user` model).

**Comment by jrhorn424** [comment]
Please do check your models, as @raq929 suggests.

However, I'd like to draw your attention to the line you pasted. (Thanks very much for including it and formatting it, BTW! please format your error messages too next time). 

See how the method `reviews` is being called on the `current_user`, but the error message says it's being called on `nil`? That means `current_user` is `nil`. That means the wrong token is likely being sent. Try signing in again, and repeating the request with the new token.

**Comment by alexkarasik** [comment]
My User model:
``` rb
# frozen_string_literal: true
class User < ApplicationRecord
  include Authentication
  has_many :examples
  has_many :reviews
end
```

So I believe Users should have movies through reviews... so I think I should add the line 
has_many :movies through: :reviews

**Comment by alexkarasik** [comment]
Ah, sorry Jeff, just saw your comment now. I will try to sign-in again!

**Comment by alexkarasik** [comment]
This was my last script command:
``` rb 
$ TOKEN="BAhJIiUyOWU5NzVkNTUxNWExOGU2YTkyMzI4MzM3MGNmMzQzMwY6BkVG--9df5501c2735df0a8035b27c34691b824d9bbf7b" MOVIE_ID=1 REVIEW_ENTRY="It's good" sh scripts/reviews/create.sh 
```
And it worked!

```rb
{"review":{"id":1,"movie_id":1,"review_entry":"It's good"}}
```
So that's great, but when I go back to that first movie that I believe I just wrote a review for with:

``` rbyet 
$ ID=1 sh scripts/movies/show.sh
```

I get just my movie info that I previosuly put in, but my understanding is that the REVIEW_ENTRY should be displaying as well and its not:

```rb 
{"movie":{"id":1,"title":"GM","length":100,"rating":"R","description":"Bear eats a dude"}}
```

I have not changed my User model yet and I am pretty sure that is still where the issue is, so should I include that line I suggested earlier:
has_many :movies through: :reviews

**Comment by jrhorn424** [comment]
Which layer determines what JSON gets sent back?

**Comment by jrhorn424** [comment]
Also, pretty sure this a new issue.

**Comment by jrhorn424** [comment]
> so should I include that line I suggested earlier... ?

I will no longer answer issues that have the following words in them:

-   Should I...?
-   Is it OK to...?
-   Will the gods sacrifice a kitten if... ?

I will grant exceptions for `rm` and `git`.

The answer is always: try it.

**Comment by alexkarasik** [comment]
Ok, I think you're right. I will close this issue and start a new one. to restate the solution to my issue: I was not prooperly signed-in with the token to be able to create a new review

**Comment by jrhorn424** [comment]
Thanks!
