### ISSUE TITLE
On save update-Page is signing out user and refreshing and not saving update. -one on one please

### ISSUE THREAD

**Issue by s0phi4** [ga-wdi-boston/full-stack-project#660]
I have a modal form in my handle bars file to submit updates and when I click on save, it refreshes the page and signs out the user.
I believe I have to add 
```// const resourceTemplate = require('../templates/resource.handlebars');``` to my js file but how do I load it on document ready? if there are no methods to call like the way we do with   authEvents.addHandlers();

**Comment by raq929** [comment]
That means when you're clicking save, `error.preventDefault()` is not running. Either you don't have a click handler set on the button, or your click handler is not preventing default. 
I would try going through the steps in #529 to ensure that your click handler is set properly.

**Comment by jrhorn424** [comment]
I believe @raq929 meant `event.preventDefault()` and I'd wager a dollar that she's right.

**Comment by s0phi4** [comment]
I went through the steps and still same result 

HTML
```html
<button type="button" class="btn btn-primary btn pull-right update" data-toggle="modal" data-target="#exampleModalUpdate" data-whatever="@getbootstrap"><span class="glyphicon glyphicon-pencil"></span></button>
          <div class="modal fade" id="exampleModalUpdate" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content saveNewLink">
                <div class="modal-header">
                  <form id="update-info">
                    <fieldset>
                      <h4 class="modal-title" id="exampleModalLabel">Update!</h4>
                      <label>
                          Name
                          <input type = "name" name ="resource[name]" class="clean-change">
                        </label>
                      <label>
                          URL
                          <input type ="url" name ="resource[url]" class="clean-change">
                        </label>
                      <input type="submit" class="btn btn-primary uInfo" name="submit" value="Save">
                      <div id="messageUpdate"></div>
                    </fieldset>
                  </form>
                </div>
              </div>
            </div>
          </div>
```
Events
```javascript
const onUpdateLink = function (event) {
   event.preventDefault();
   let data = getFormFields(event.target);
   api_link.updateLink(data)
   .then(ui_link.success)
   .then(() => {
     $("#messageUpdate").text("Name and URL updated!");
   })
   .catch(ui_link.failure);
};
```

```$('#update-info').on('submit', onUpdateLink);```

**Comment by s0phi4** [comment]
Since change password and update do the same request, I am comparing them and if they look exactly same why is change password working but not update... Since the update modal is in handlebars, I think I need to add the handlebar file in my js under document ready but I do not know how to call it when there is no method to call...  
Still not sure if that will be the solution...

**Comment by raq929** [comment]
If you put `console.log("HELLO")` in your click handler `onUpdateLink`, does it console.log?
If no, you have not set the click handler correctly.

Also, if you created this in handlebars, you've got two issues. If you created it in a loop, you've got multiple elements with the same ID. This is **not OK**.
Second, if you set the clickHandler on your element before handlebars created the element, the click handler is not set. Scroll down to the very bottom of the documentation here for a solution to that issue:
http://api.jquery.com/on/

**Comment by s0phi4** [comment]
It does not console.log :(

**Comment by s0phi4** [comment]
I changed my click handler to the below 
```$('.resourcesTable').on('submit', '#update-info',onUpdateLink);```
still same refresh and sign out happening

**Comment by raq929** [comment]
Again, you'll need to change the ID to something else. If multiple elements that ID, it won't be sure what to target. Try changing it to a class for now. If that doesn't work, come see me, I'm near front lines.

**Comment by s0phi4** [comment]
Issue solved- 

PLEASE PLEASE MAKE SURE YOU HAVE 

```event.preventDefault();```

ON YOUR EVENTS---
And 

1. If you have a modal in your handlebars file, make sure you append your {{table.id}} to your id names
EX: id="exampleModalUpdate-{{table.id}}"

2. Your click handlers need to reference the div you created in your html file for the handlebars
Ex: $('.div').on('click','.class', onDeleteLink);

3. If you have a span for an icon in your button make sure it follows this format
Ex: ```<span data-id="{{table.id}}" class="glyphicon glyphicon-trash"></span>```
