### ISSUE TITLE
Reviews not getting attached to Movies

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#662]
Picking up from the direction of my last issue now. So I am trying to attach my Reviews to my Movies.
This was the last question placed to me by Jeff: "Which layer determines what JSON gets sent back?"
I don't totally understand the question I think. I am not sure what is meant by layer. 

I thought there was an issue with my User model, so I added has_many :movies through: :reviews
to this: 

```rb
# frozen_string_literal: true
class User < ApplicationRecord
  include Authentication
  has_many :examples
  has_many :reviews
end
```
but that was not right.

**Comment by jrhorn424** [comment]
Current ERDs, user stories, and wireframes? If you have old ones that's fine. I'm trying to diagnose whether this is a modeling issue, or something else.

> Jeff: "Which layer determines what JSON gets sent back?" I don't totally understand the question I think. I am not sure what is meant by layer.

By layer, I meant which of these: "M", "V", or "C"?

**Comment by alexkarasik** [comment]
That would be the controller. 
I think my understanding has been off for some of the back-end. When I was calling "show" on movies, I have been thinking that after I add a review to a specific movie_id that the review_entry for that movie should now be part of the data for that movie. 
How would I check that the review_entry is properly attached to the right movie?

**Comment by raq929** [comment]
I'd go into `rails_console` and look at a movie and it's reviews.

**Comment by alexkarasik** [comment]
I attached the reviews to the movies by adding them to the serialzier , so I think I am good on this now.
