### ISSUE TITLE
Handlebars and event targeting

### ISSUE THREAD

**Issue by jwaskow** [ga-wdi-boston/full-stack-project#663]
I'm having trouble getting my click handler to target the correct item in a handlebars loop/list.  I can delete an item and it successfully deletes on the backend, but the front end does not get updated until I get the index again.  I'd like for the UI to remove the deleted item once it is deleted.  I went through the solution branch to the handlebars repo and tried the code: 
```
$("#content").on("click", 'button', function (e) {
  e.preventDefault();
  $(e.target).parent().parent().remove();
});
```
But I could not get this to work.  

I researched this extensively, tried many variations of `event.target` and `attr('data-id')`, read through the handlebars repo & solution branch, and read through previous handlebars issues, and I still can't seem to figure it out.  

**Handlebars**
```
{{#each posts as |post|}}

 <!-- Developers, why are we using data-id and not just id? -->
  <h1 class="postData" data-id="{{post.id}}"> <small>Animal Type: {{post.animal_type}}</small></h1>
  <div>
    <ul>
    <li>
      I saw this animal at: {{post.location}}
  </li>
  <li>
      The date I saw this animal was: {{post.date_seen}}
  </li>
  <li>
      Here's a description of this animal: {{post.description}}
  </li>
  <li>
  <p>Post ID: {{post.id}}</p>
</li>
<li>
  <button id="updatePost" data-id="{{post.id}}">Update</button>
</li>
<li>
  <button id="removePost" data-id="{{post.id}}">Delete</button>
</li>
  </ul>

{{/each}}
```

HTML for handlebars to load to: `<div id="entry-container"></div>`

**Click handler and Event**
```
  $('#entry-container').on('click', '#removePost', onRemovePost);


const onRemovePost = (event) => {
  event.preventDefault();
  let id = event.target.getAttribute('data-id');
  console.log(id);
  logApi.destroy(id)
    .then(logUi.removePostSuccess)
    .catch(logUi.failure);
};
```

**UI event**
```
const removePostSuccess = (event) => {
  $(event.target).parent.parent.remove();
};
```

**API destroy (again, i believe this is working correctly)**
```
const destroy = function (id) {
  return $.ajax({
    url: config.apiOrigin + '/posts/' + id,
    method: 'DELETE',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
  });
};
```

Additionally, I'd like for my update to automatically load the ID of the post being updated.  When a user clicks update, I'd like for them to update the content without having to manually enter the ID of the post being updated.  I believe I can do this if I can figure out how to properly the ID of the item in handlebars with my click handler.  However, I'll take it one step at a time and work on removing a deleted item first.

**Comment by raq929** [comment]
I would use the jQuery `data` method.
`$(event.target).data("id")`

**Comment by raq929** [comment]
BUT FIRST. Be sure your click handler is attached to your div. 
Put in a console.log("HELLO") with no other code (except preventDefault) in your handler. If that runs, your click handler is set, and you can try the above method.

**Comment by jwaskow** [comment]
The click handler is attached correctly, I have other console logs that show, and the script to delete the item runs correctly when the button is clicked (like if i click get index after I click to delete an item, that item is no longer on the index).  Also I have tried the data method, it returns the same error as my other attempts: `Cannot read property 'remove' of undefined`.

**Comment by jwaskow** [comment]
I'm trying to get the item to visually disappear when the delete button is clicked.  It gets deleted from the back end fine, but I'd like the user to know that the delete was successful (and not just give them a message that it was successful).  I thought we did removing items from handlebars in class, but I tried everything in the repo and I can't figure it out.

**Comment by raq929** [comment]
Ah. I wouldn't bother removing the item using handlebars. I'd just make another GET request to the API (you have a `then` that has your deleteSuccess then have another `then` to make the new API call) and do whatever you did with the first GET request to redisplay the table. Then you're SURE that your data on the frontend is up-to-date with the server's data.
I did this with Yen in #660 - If her solution doesn't include the part we did about this, ask her to update it please! 😄

**Comment by bernardlee** [comment]
`onRemovePost()` calls your API with this promise chain:
```javascript
logApi.destroy(id)
    .then(logUi.removePostSuccess)
    .catch(logUi.failure);
```
The return value from `logApi.destroy(id)` gets passed into `.then(logUi.removePostSuccess)`, which gets passed into `logUi.removePostSuccess()`.  `removePostSuccess()` expects a DOM event object as an argument.

**Comment by jwaskow** [comment]
I fixed it!

My remove event is now:
```
const onRemovePost = (event) => {
  event.preventDefault();
  let id = event.target.getAttribute('data-id');
  console.log(id);
  logApi.destroy(id)
    .then(logUi.removePostSuccess)
    .then(logApi.getIndex)
    .then(logUi.indexSuccess)
    .catch(logUi.failure);
};
```

I also made the same change to create, so after a user creates a new post it gets added to the list.

**Comment by jrhorn424** [comment]
Good resolution.

If you want to grab the `data-id` with jQuery instead, you can do this:

```diff
-  let id = event.target.getAttribute('data-id');
+  let id = $(event.target).data('id');
```
