### ISSUE TITLE
One on One Request

### ISSUE THREAD

**Issue by zchenbonterra** [ga-wdi-boston/full-stack-project#665]
I am not sure how to define my problem, but to simply put it, I need help! I am trying to do a quiz app and for some reason its taking double clicks to start the game. And even when the player gets the question wrong, they will still take the spot as soon as the other player answers their question right. Please advise!

Update:
Can I use click handlers inside another click handler??

**Comment by raq929** [comment]
This sounds like two different issues.
I'm going to ask questions about the first one first. 
Are you using a pre-made Bootstrap template?
Please post your HTML and your click handler for the button that starts the game.

Please open a second issue about your other problem.

**Comment by zchenbonterra** [comment]
Yes, please see below for html and codes.
``` html
  <h3></h3>
  <div class="answers">
    <ul>
      <li>
        <div type="button" class="ans-cells" id="ans1"></div>
      </li>
      <li>
        <div type="button" class="ans-cells" id="ans2"></div>
      </li>
      <li>
        <div type="button" class="ans-cells" id='ans3'></div>
      </li>
      <li>
        <div type="button" class="ans-cells" id='ans4'></div>
      </li>
    </ul>
  </div>



  <div class="gameboard">
  </div>
```

``` javascript
const rightAnswer = function() {
  api.getQuestion()
    .then((response) => {
      gameStore.problem = response.question.problem;
      gameStore.correct = response.question.correct;
      gameStore.wrongOne = response.question.wrongOne;
      gameStore.wrongTwo = response.question.wrongTwo;
      gameStore.wrongThree = response.question.wrongThree;
      return gameStore;
    });
  let answers = [gameStore.correct, gameStore.wrongOne, gameStore.wrongTwo, gameStore.wrongThree];
  answers.sort(() => 0.5 - Math.random());
  for (let i = 0; i < 4; i++) {
    $(`#ans${i+1}`).text(answers[i]);
  }
  return answers;
};

// Reset function to reset board
const reset = function() {
  for (let i = 0; i < gridSize; i++) {
    board[i] = '';
    $('#' + i).text('');
  }


  $('.cells').on('click', (event) => {
    event.preventDefault();
    let id = parseInt(event.target.id);
    let textSelected = $(event.target);
    rightAnswer();
    $('h3').text((gameStore.problem));
    $('h2').text('');

    $('.answers').on('click', (event) => {
      event.preventDefault();
      if ($(event.target).text() === gameStore.correct) {
        if (textSelected.text() === "") {
          selectSpace(parseInt(id));
          textSelected.text(currentPlayer);
          $('h2').text('Correct!');
        }
      } else {
        changingTurns();
        $('h2').text('Wrong!');
      }
    });

    if (winConditions() === true) {
      $('h4').text(`Winner is ${currentPlayer}`);
      $('.cells').unbind('click');
    }
  });
};

```

**Comment by raq929** [comment]
So, do you start the game by clicking on the board?

**Comment by zchenbonterra** [comment]
By clicking the start button, and it takes two clicks to start on the board. The problem is that even if the player answers the question incorrectly, they still get the space after the other player gets the question correct.

**Comment by bernardlee** [comment]
I see a couple of possible problems here.

1. `rightAnswer()` returns an array, but it gets called in the callback for `.cells`'s click handler without being assigned to anything.
2. `reset()` attaches a click handler to `.cells`.  I assume that this function will be called multiple times if the user decides to reset the game.  Click handlers don't overwrite one another.

**Comment by raq929** [comment]
I don't see a start button in the html you posted, or a click handler for the start button. 
Bernard is answering your second issue. Please open a second issue to address that. 
This issue is ONLY about the start button. Please post the code that is relevant to the start button.

**Comment by zchenbonterra** [comment]
I got it working! Basically, I just need to break the reset function into smaller pieces instead of having everything inside.
