### ISSUE TITLE
404 on my PATCH for Reviews

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#666]
This was my command for UPDATE:
```rb
$ TOKEN="BAhJIiU4NTc5MjlmYmI1YWFhYjJlM2NjYmM0ZGRkMGI4MThkMgY6BkVG--4630633856ee5466488f746384c2be994b591102" MOVIE_ID=1 REVIEW_ENTRY="It's bad" sh scripts/reviews/update.sh 
```

This is the error my server is giving me:
```rb
Started PATCH "/reviews/" for 127.0.0.1 at 2017-02-21 15:10:39 -0500
  
ActionController::RoutingError (No route matches [PATCH] "/reviews"):
```

So there is an issue with patch in my router, but I do not see what:
```rb
  def update
    if @review.update(review_params)
      head :no_content
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
```

**Comment by raq929** [comment]
Yep, there's no route for PATCH to `reviews`. You'll need to send the request to `reviews/:some_review_id`.

**Comment by alexkarasik** [comment]
I was not rendering the JSON in the controller:  
```rb
def update
    if @review.update(review_params)
      render json: @reviews
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
```

**Comment by jrhorn424** [comment]
> I was not rendering the JSON in the controller:

You shouldn't be. The controller action **should** look like this:

```ruby
def update
  if @review.update(review_params)
    head :no_content
  else
    render json: @review.errors, status: :unprocessable_entity
  end
end
```

You already have the data in your client. You got it from the update form. You should either re-use that data, or make a new GET request (preferred) to update anything that needs updating.

Finally, your solution has nothing to do with your original problem.

This:

> I was not rendering the JSON in the controller:

Does not fix:

> 404 on my PATCH for Reviews
> ...
> ```
> ActionController::RoutingError (No route matches [PATCH] "/reviews"):
> ```
