### ISSUE TITLE
Help defining Handlebars helper

### ISSUE THREAD

**Issue by ddobson** [ga-wdi-boston/full-stack-project#668]
I am trying to define a Handlebars helper but it is not working. My goal is to pre-select an `<option>` element based on the value of a variable.

I have added the following helper in `assets/scripts/templates/helpers/`:

```
'use strict';

require('handlebars');

Handlebars.registerHelper("select", function(value, options) {
  return options.fn(this)
    .split('\n')
    .map(function(v) {
      const t = 'value="' + value + '"';
      return !RegExp(t).test(v) ? v : v.replace(t, t + ' selected="selected"');
    })
    .join('\n');
});
```

I have tried with and without requiring the handlebars module. In both cases the linter tells me that `Handlebars` is not defined. 

In my template file I am calling the helper like this  (look at the `{{#select}}` bit):

```
<div class="row ingredient-wrapper">
  <hr>
  <div class="form-group">
    <div class="col-xs-6 col-md-2">
      <input name="recipe[recipe_ingredients_attributes][][quantity]" type="number" class="form-control form-inline ingredient-field" placeholder="Qty" value="{{quantity}}">
    </div>
    <div class="col-xs-6 col-md-2">
      <select name="recipe[recipe_ingredients_attributes][][ingredient_attributes][unit]" class="form-control form-inline ingredient-field">
        {{#select unit}}
          <option value="oz">oz</option>
          <option value="gal">gal</option>
          <option value="lbs">lbs</option>
          <option value="tsp">tsp</option>
          <option value="tbs">tbs</option>
        {{/select}}
      </select>
    </div>
    <div class="col-xs-10 col-md-7">
      <input name="recipe[recipe_ingredients_attributes][][ingredient_attributes][name]" type="text" class="form-control form-inline ingredient-field" placeholder="Ingredient" value="{{name}}">
    </div>
    <div class="col-xs-2 col-md-1">
      <button class="btn btn-danger btn-fab btn-fab-mini btn-round pull-right destroy-ingredient-btn">
        <i class="material-icons">remove</i>
      </button>
    </div>
  </div>
</div>

```

The above code is a partial which I call like this:

```
      <label for="ingredients">Ingredients</label>
      {{#each recipe.ingredients}}
        {{>edit-ingredient-form}}
      {{/each}}
```

If I try to render this template without the helper everything works fine, including the other ingredient variables. If I include the helper function `{{#select }}`nothing is rendered. Can you point me in the right direction?

**Comment by raq929** [comment]
I think taking a look at this branch of the handlebars repo might help.
https://github.com/ga-wdi-boston/browser-template/tree/hbs-helpers/assets/scripts/templates/helpers

**Comment by ddobson** [comment]
I have tried modifying to the following and renaming the helper file to `select.js` but it's still not working. I am still not getting any errors but the edit form will not load. 

```
'use strict';

module.exports = function(value, options) {
  return options.fn(this)
    .split('\n')
    .map(function(v) {
      const t = 'value="' + value + '"';
      return !RegExp(t).test(v) ? v : v.replace(t, t + ' selected="selected"');
    })
    .join('\n');
};
```

**Comment by jrhorn424** [comment]
Use breakpoints to determine what `options` is when the helper is attempting to be rendered, and then consider what it should be.

Can you describe what you're trying to do with the helper, and what resources you used to construct the helper function?

**Comment by jrhorn424** [comment]
> Use breakpoints to determine what options is when the helper is attempting to be rendered, and then consider what it should be.

That wasn't clear enough. I'd also like to know what `options` is and what you think it should be. :smile:

**Comment by ddobson** [comment]
Can you explain what you mean by "breakpoints"? As I understand it, `options` contains the elements within the block. In this case, a list of `<option>` elements.

**Comment by ddobson** [comment]
Also, using console logs I can see that the reason the page never updates is because handlebars never finishes rendering the template html.

**Comment by raq929** [comment]
#254 or #454 might also help. (I'm really sad this isn't issue 654).

**Comment by raq929** [comment]
What's your status on this?

**Comment by ddobson** [comment]
I got it! I found a similar helper function online and exported it in the style of the example.

```
'use strict';

module.exports = function(value, options) {
  let $el = $('<select />').html(options.fn(this));
  $el.find('[value="' + value + '"]').attr({
    'selected': 'selected'
  });
  return $el.html();
};
```
