### ISSUE TITLE
*No changes in code* data.user.token returning 'undefined'

### ISSUE THREAD

**Issue by kelvinma** [ga-wdi-boston/full-stack-project#67]
Between last night, when my code was working, and this morning, with no changes made in between, my login AJAX call is no longer functional. 

Returns following JSON upon successful login:

```
{id: 5, email: "me@kelvinma.com", current_user: false, token: "aa6953dd424cb1a8b5d73ed31d523cb3"}
```

Cannot proceed with project until this issue is resolved. 

Rage is building.

**Comment by gaand** [comment]
What you pasted is the value of data?  If some it looks like the serializer isn't running.

**Comment by kelvinma** [comment]
I'll dive in and see what's going on, but I did not make any changes to the serializers last night.

**Comment by gaand** [comment]
Please console.log the value of data before you try to get the token and paste what's shown here.

**Comment by kelvinma** [comment]
That's what I pasted.

**Comment by gaand** [comment]
Okay.  Then something changed about your serializer setup.  By default, active_model_serializers adds a `root` key, e.g. `{ user: {id: 5, email: "me@kelvinma.com", current_user: false, token: "aa6953dd424cb1a8b5d73ed31d523cb3"} }'.

As a work around you should be able to access the token as `data.token`, but figuring out what happened to your serializers is important.  If getting the token that way works, see if the root keys are missing from other requests.

Oh, what do you get back if you invoke login using `curl`?

**Comment by kelvinma** [comment]
curl is getting me parser errors from the server console

**Comment by kelvinma** [comment]
curl gives me back the same object without the 'user' root:

```
{"id":5,"email":"me@kelvinma.com","current_user":false,"token":"f8734f461ae448070f973be0a6367292"}
```

**Comment by kelvinma** [comment]
I can do the workaround with data.token and load the page without errors, but I am unable to run my other authenticated actions off my saved token.

**Comment by gaand** [comment]
Is the error "401 Unauthorized" or something else?

**Comment by kelvinma** [comment]
There are no errors on the server side. I can get the data back just fine. It appears that none of my serializers are functional anymore. I have done a bundle install to try to reinitialize any gems that may have gone buggy. No success. 

I'm at a complete standstill, as I was at a point where all of the features I was building on required authentication, now I can't even get my log in to authenticate properly.

**Comment by kelvinma** [comment]
FYI, I also went back to the commits that I had from last night when everything was working properly, and I am getting the same error.

**Comment by gaand** [comment]
I think you should seek help from someone there for debugging.  I'll be in this afternoon but you shouldn't wait.  My apologies, but I don't yet understand why you're having this problem.

**Comment by kelvinma** [comment]
PROBLEM SOLVED:

I was calling the rails-api serializer gem from their github. They updated it after I had installed it, and it was creating problems.
