### ISSUE TITLE
sorting lists issue

### ISSUE THREAD

**Issue by moshiko1988** [ga-wdi-boston/full-stack-project#672]
so im having an issue when i edit one of the lists, after the patch it moves the item to the end of the table.
is there a way to edit a list and keep it on the same order? 

```events.js
const onPatchList = function(event){
  event.preventDefault();
  console.log(event.target);
  let id = event.target.dataset.id;
  let data = getFormFields(event.target);
  api.patch(id, data)
    .then(ui.onPatchSuccess)
    .then(onGetList)
    .catch(ui.onError);
    onGetList();

```

**Comment by raq929** [comment]
I would consider ordering the list on the back-end.

**Comment by raq929** [comment]
Also, unless you're sure you've met requirements, I think this can wait until you have.

**Comment by bernardlee** [comment]
Correct me if I'm remembering wrong, but I think that @gaand once said that databases retrieve data in the most efficient way possible, not necessarily in a particular order unless you tell it to sort by some field when you write the query.  Assuming that this is the case, you'll have to sort your data on the back end before rendering it to the front end or sort it on the front end after receiving it but before putting it to use elsewhere.

**Comment by moshiko1988** [comment]
issue solved. 
changed the list controller to 
``` ruby
   @lists = current_user.lists.order(:id)
```
from 
```ruby
   @lists = current_user.lists.all
```
