### ISSUE TITLE
After updating table in modal, screen is lock and I can't click anything

### ISSUE THREAD

**Issue by s0phi4** [ga-wdi-boston/full-stack-project#673]
Hello!
I have a modal that is used to update data in my table. After I click save, in the console log I get 200 and the change is made on the screen but the screen is locked and doesn't allow me to perform other actions. (Like delete or update another row or clink on any button)
My approach: Looking at Set Time Out but saw that it is not the best solution.

This is my code for the events
```
const onUpdateLink = function (event) {
  console.log("HELLO");
   event.preventDefault();
   let data = getFormFields(event.target);
  let id = $(event.target).data('id');
   console.log(id);
   api_link.updateLink(data,id)
   .then(ui_link.success)
   .then(onGetLinks)
  //    $("#messageUpdate").text("Name and URL updated!");
  //  })

   .catch(ui_link.failure);
};```

**Comment by raq929** [comment]
We're going to take a look at this tomorrow morning.

**Comment by raq929** [comment]
Meanwhile, here's the boostrap documentation: http://getbootstrap.com/javascript/#modals-usage

**Comment by raq929** [comment]
Put it in a `then`. 😄

**Comment by s0phi4** [comment]
So I tried this new code and didn't work (New code has an added .then with hide modal)
```
const onUpdateLink = function (event) {
  console.log("HELLO");
   event.preventDefault();
   let data = getFormFields(event.target);
   let id = $(event.target).data('id');
   console.log(id);
   api_link.updateLink(data,id)
   .then(ui_link.success)
   .then($('#exampleModalUpdate').modal('hide'))
   .then(onGetLinks)
   .catch(ui_link.failure);
};
```
We can look at it tomorrow with less tired eyes :) and mind :)

**Comment by raq929** [comment]
What is `#exampleModalUpdate`?  Is that in your html? 
What is the error? 
Regardless, I doubt it'll work unless you wrap it in a function.
```js
.then(() => { $('#exampleModalUpdate').modal('hide') })
```
And yes, we can look at it tomorrow.

**Comment by s0phi4** [comment]
Problem solved!
In order to update and close the modal

Steps: 
1. Make sure to append the variable {{table.id}} to all your ids in your modal
See handlebars example below

``` 
<div class="modal fade updateRowTable" id="exampleModalUpdate-{{resource.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content saveNewLink">
                <div class="modal-header">
                  <form data-id="{{resource.id}}" class="update-info">
                    <fieldset>
                      <h4 class="modal-title" id="exampleModalLabel-{{resource.id}}">Update!</h4>
                      <label>
                          Name
                          <input type = "name" name ="resource[name]" class="clean-change">
                        </label>
                      <label>
                          URL
                          <input type ="url" name ="resource[url]" class="clean-change">
                        </label>
                      <input type="submit" class="btn btn-primary uInfo" name="submit" value="Save">
                      <div id="messageUpdate-{{resource.id}}"></div>
                    </fieldset>
                  </form>
                </div>
              </div>
            </div>
          </div>
```
2. Add a hide method to the modal as seen below and position it as shown below

```
const onUpdateLink = function (event) {
  console.log("HELLO");
   event.preventDefault();
   let data = getFormFields(event.target);
   let id = $(event.target).data('id');
   $(`#exampleModalUpdate-${id}`).modal('hide');
   console.log(id);
      api_link.updateLink(data, id)
   .then(ui_link.success)
   .then(onGetLinks)
   .catch(ui_link.failure);
};
```

**Comment by s0phi4** [comment]
Thank you @raq929 @jrhorn424

**Comment by jrhorn424** [comment]
I'd prefer this to be a part of the promise chain. If you'd like to try that, I can help you debug it.

**Comment by s0phi4** [comment]
I closed the incognito window I was working on and opened a new one, all the functions work except the update. 

- No error on the console
- It patches
- and I get the info updated
- screen then locks the user out 

refreshed the page again

- Update worked once and user was not locked out

Try new update

- screen locks user from clicking

**Comment by MicFin** [comment]
Still having modal issues?

**Comment by s0phi4** [comment]
YESSSS

**Comment by s0phi4** [comment]
I am getting the screen of darkness

**Comment by s0phi4** [comment]
And tried 4 solutions already

**Comment by MicFin** [comment]
Come to the kitchen for a 1on1

**Comment by s0phi4** [comment]
Give me 5 min please

**Comment by jrhorn424** [comment]
Please close the modal in a `then`. This is a race condition. @MicFin If I'm wrong, I owe you a beverage.

**Comment by jrhorn424** [comment]
> I'd prefer this to be a part of the promise chain. If you'd like to try that, I can help you debug it.

Let me know if you have any problems with my suggestion @yenpraja610.

**Comment by raq929** [comment]
How's this going? Is it resolved?

**Comment by s0phi4** [comment]
Issue resolved!
So the solution is this:

- Delete fade class in the modal
-Add a .then to the event file like this

```
const onUpdateLink = function (event) {
   event.preventDefault();
   let data = getFormFields(event.target);
   let id = $(event.target).data('id');
    api_link.updateLink(data, id)
      .then(() => {
        ui_link.onUpdateSuccess(id);
      } )
      .then(onGetLinks)
      .catch(ui_link.failure);
};
```

Thanks @jrhorn424  @MicFin  @raq929
