### ISSUE TITLE
1 on 1 request

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#675]
I have some questions on how to use handlebars in what I have and the deployment process and would like to prepare how to articulate my presentation a bit more if possible.

**Comment by raq929** [comment]
Hi Alex, please let us know what you've tried for using handlebars and deployment and what your problems are so we can focus on specifics.

**Comment by jrhorn424** [comment]
> I have some questions on how to use handlebars

Great! What are they?

Once you've posted your questions, and a little more context as @raq929 suggested, I'm happy to meet with you for a bit!

**Comment by alexkarasik** [comment]
I am going to work on articulating my question and a few others for the next hour or so if that is ok.

**Comment by raq929** [comment]
Your articulation doesn't have to be perfect. Throw them out here, and we can help you refine them. 😄

**Comment by jrhorn424** [comment]
> Your articulation doesn't have to be perfect. Throw them out here, and we can help you refine them.

Please do so. I want to help. I just want to know what I'm going to be helping with so we can use our time together effectively.

**Comment by alexkarasik** [comment]
I am having a 400 error I can not figure out at the moment. I would also like to go through what I have left to do and make sure my understanding of the way the front end and back end are working together is correct.

**Comment by jrhorn424** [comment]
> I would also like to go through what I have left to do and make sure my understanding of the way the front end and back end are working together is correct.

We can talk about that. Let's meet at 3:45 or 4:30.

(If anyone else is free before then, I'm happy to let them help)

**Comment by alexkarasik** [comment]
With some help, I fixed the 400 error on the addReview button, but I am still getting a 404 error on the update and delete buttons. The problem last time was that I had a click handler on my add-review button, so I switched it to a 'submit' handler:
```rb
  $('#create-review').on('submit', onCreateReview);
```
I thought that was the issue with the other buttons, but it is not. I changed those event handlers to submits:
```rb
  $('#change-review').on('submit', onPatchReview);
  $('#delete-review').on('submit', onDeleteReview);
```
But the same error is still occurring for those two.

Here are the HTML fields:
```rb
  <form id="change-review">
                  <fieldset>
                    <legend class="change-review">Update Review</legend>
                    <input type="number" name="review[movie_id]" placeholder="Movie ID">
                    <input type="text" name="review[review_entry]" placeholder="Review">
                    <input id="update-review" type="submit" value="Update Review">
                  </fieldset>
                </form>

                <form id="delete-review">
                  <fieldset>
                    <legend class="delete-review">Delete Review</legend>
                    <input type="number" name="reviews[movie_id]" placeholder="Movie ID">
                    <input id="delete-reviews" type="submit" value="Delete Review">
                  </fieldset>
                </form>
```

**Comment by jrhorn424** [comment]
This is a separate issue. Please open it (the same post is fine), and add a few additional details:

- The error as it appears in your API server log
- your AJAX call definitions
- your success and failure handlers for what isn't working

**Comment by jrhorn424** [comment]
Why'd you close this? You tried to introduce a new issue, which was not correct, but you still didn't have your 1on1... so I'm confused?

Do you still need it?

>We can talk about that. Let's meet at 3:45 or 4:30.
>
>(If anyone else is free before then, I'm happy to let them help)

**Comment by alexkarasik** [comment]
I'm sorry, I did not see that part of what you wrote. I would still like to do a 1 on 1 as soon as possible.

**Comment by alexkarasik** [comment]
My situation at the moment is that I don't think I have included enough attributes for my reviews to be able for a user to easily idenitify what they want to edit or delete. I am also getting an error when I try to delete: Cannot read property 'id' of undefined. 
I am not sure if I should open up a new issue for that, but I think it is the only requirement I am missing at the moment and I want to make sure I am right.

**Comment by BenGitsCode** [comment]
☝️ This assignment was meant to be me not Alex. I added and removed myself so that between this comment and that thread that it's clear what happened.

**Comment by alexkarasik** [comment]
A productive one on one has occurred for me, so I will close this now. Thanks
