### ISSUE TITLE
422 Unprocessable Entity

### ISSUE THREAD

**Issue by zchenbonterra** [ga-wdi-boston/full-stack-project#677]
Hi All,
I am getting the 422 unprocessable entity error message with the code provided below. Please advise what I need to do in order to make the status code back into 204.

Server message:
Started POST "/games/" for 127.0.0.1 at 2017-02-22 09:18:23 -0500
Processing by GamesController#create as */*
  Parameters: {"game"=>{"playerOneWon"=>"false", "playerTwoWon"=>"false", "over"=>"false"}}
   (0.3ms)  BEGIN
   (0.2ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.29ms)
Completed 422 Unprocessable Entity in 11ms (Views: 0.8ms | ActiveRecord: 0.5ms)

``` ruby
# game model
class Game < ApplicationRecord
  belongs_to :user

  validates :playerOneWon, presence: true
  validates :playerTwoWon, presence: true
  validates :over, presence: true
end

# game serializer
class GameSerializer < ActiveModel::Serializer
  attributes :id, :playerOneWon, :playerTwoWon, :over
end
```
``` javascript
const createBoard = function () {
  return $.ajax({
    url: config.apiOrigin + '/games/',
    method: "POST",
    headers: {
      Authorization: `Token token=${store.user.token}`
    },
    data: {
      'game': {
        'playerOneWon': false,
        'playerTwoWon': false,
        'over': false,
      }
    }
  });
};

  api.createBoard()
    .then((response) => {
      store.game = response.game;
      return store;
    });

**Comment by bernardlee** [comment]
What do `GamesController#create` and `GamesController#games_params` look like?  Does creating a game using a cURL script work?

**Comment by zchenbonterra** [comment]
Please see below for curl script and game controller. And Yes, the curl script does work.

``` sh

#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/games"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "game": {
      "playerOneWon": false,
      "playerTwoWon": false,
      "over": false
    }
  }'

echo

```

``` ruby
# frozen_string_literal: true
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :update, :destroy]

  def index
    render json: Game.all
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      render json: @game, status: :created
    else
      render json: @game.errors, status: :unprocessable_entity
    end
  end

  def show
    render json: @game
  end

  def update
    @game.update(game_params)
    head :no_content
  end

  def destroy
    @game.destroy
    head :no_content
  end

  def set_game
    @game = Game.find(params[:id])
  end
  private :set_game

  def game_params
    params.require(:game).permit(:playerOneWon, :playerTwoWon, :over)
  end
  private :game_params
end

**Comment by raq929** [comment]
We met and found that the curl request is not actually working, after adding the user relationship. Zhu is going to use the `create` method from the `ExamplesController` as a model for updating his `create` method.

**Comment by zchenbonterra** [comment]
Please see below for the schema, curl script for the game table, and error message from the sh. If you can please let me know how or why the system is only taking in true and not false, that would be great.

HTTP/1.1 422 Unprocessable Entity
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: ddce516d-8fff-4225-b14c-ecb3b0f6a422
X-Runtime: 0.008467
Vary: Origin
Transfer-Encoding: chunked

{"playerOneWon":["can't be blank"],"playerTwoWon":["can't be blank"]}
~/Desktop/connect_five_api (master)

```
  create_table "games", force: :cascade do |t|
    t.boolean  "playerOneWon", null: false
    t.boolean  "playerTwoWon", null: false
    t.boolean  "over",         null: false
    t.datetime "created_at",   null: false
    t.datetime "updated_at",   null: false
    t.integer  "user_id"
    t.index ["user_id"], name: "index_games_on_user_id", using: :btree
  end

```

``` sh

#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/games"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "game": {
      "playerOneWon": false,
      "playerTwoWon": false,
      "over": true
    }
  }'

echo

```

**Comment by bernardlee** [comment]
Can you paste the model for `Game`?

**Comment by zchenbonterra** [comment]
```
# frozen_string_literal: true
class Game < ApplicationRecord
  belongs_to :user

  validates :playerOneWon, presence: true
  validates :playerTwoWon, presence: true
  validates :over, presence: true
end
```

**Comment by bernardlee** [comment]
What's the status on this?

**Comment by bernardlee** [comment]
The reason for the error message `{"playerOneWon":["can't be blank"],"playerTwoWon":["can't be blank"]}` is because of the model's validations.  `presence: true` tests if a field is `nil` or `false`.  Since `false` is being passed in, the validation fails because it thinks it's not present.  Check [section 2.9 of Active Record Validations](http://guides.rubyonrails.org/active_record_validations.html#presence) to see how boolean validation can be done.

**Comment by zchenbonterra** [comment]
Thanks! I took out the validations in the game model and it is working now

**Comment by bernardlee** [comment]
Did you take them out completely?

**Comment by zchenbonterra** [comment]
I did

**Comment by zchenbonterra** [comment]
```
# frozen_string_literal: true
class Game < ApplicationRecord
  belongs_to :user
end
```

**Comment by bernardlee** [comment]
Why?  The link that I posted shows you how to validate booleans.

**Comment by zchenbonterra** [comment]
Oh I did that base on your comment. Let me take a look at the docu.
