### ISSUE TITLE
Request 1 -on -1

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/full-stack-project#679]
I would like to go over some questions I have on my getReviews and showReviews function as well as a quick check on what else I need to do to complete requirements.
I'm having issues with my get request for reviews on both the index and the show functions. I can CRUD on the back end.

onShowReviews - pauses in my debugger and it says and gives me a ``` Authorization: `Token token=${store.user.token}```` not defined.

onGetreviews does a get request bust it doesn't return anything. 

Questions that I have are:
- My JSON book data has some strange spacing in it and I want to know how to fix it.
- My reviews aren't populating and I want to know If I need to add the FK review to show the data.
- Do I have most of what I need to meet requirements?
-How can I display reviews of books in the same handle bars template.

**Comment by jrhorn424** [comment]
> onShowReviews - pauses in my debugger and it says and gives me a ``` Authorization: `Token token=${store.user.token}```` not defined.

That's an fair start to a new issue.

> onGetreviews does a get request bust it doesn't return anything.

That's an fair start to a new issue.

> My JSON book data has some strange spacing in it and I want to know how to fix it.

That's an fair start to a new issue.

> My reviews aren't populating and I want to know If I need to add the FK review to show the data.

That's an fair start to a new issue.

> How can I display reviews of books in the same handle bars template.

That's an fair start to a new issue.

> Do I have most of what I need to meet requirements?

I'll gladly meet with you for a 1on1 once these other issues are resolved. I can tell you from your description of the issues that they must be fixed before I can confidently say you meet requirements.

**Comment by AshlenPrice** [comment]
@jrhorn424 I have actually knocked out 2 of these issues. I am working on opening the other issues.

**Comment by AshlenPrice** [comment]
I would like some help planning/identifying what additional things I need to do. I feel that I've done a good job at outlining the things that I need to up to today... But feeling stuck with what to prioritize (hope that makes sense).

**Comment by raq929** [comment]
Come on by classroom 6!

**Comment by AshlenPrice** [comment]
Thank you for the time and help!
