### ISSUE TITLE
Look over my API README?

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/full-stack-project#681]
[Would someone be willing to look over this and let me know if I'm missing anything important?](https://github.com/laurpaik/WorkIt-API/tree/master)

**Comment by raq929** [comment]
I don't have time to check that you included every route, but it looks really nice! 
If you want to be super spiffy, add curl requests for each request the same way they're put in for the auth routes.

**Comment by jrhorn424** [comment]
Awesome! For super extra cool points, you could add:

- What you learned from working on this.
- What technologies you used for building the API.
- What your process was like.
- What you struggled with and how you grew.
- Anything you'd like to do in future iterations.

These points should be focused on the API and similar points (focused on the client) should be in the client README. For the API repo, these points should come before the endpoint documentation. :+1:

**Comment by raq929** [comment]
You get cool points not just for us, but for employers. Yay!

**Comment by laurpaik-zz** [comment]
Thank you!
