### ISSUE TITLE
Show Review  Form not allowing me to enter ID

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/full-stack-project#683]
The form on my client HTML does not allow me to enter data. I have looked for typos, I can't find, I have made sure that the functions are right they are sending and getting data.
I have no idea what else to try. I have tried re-writing the form and having someone else look at it.
```html
  <form class='show' id="show-review">
      <fieldset>
        <div class="form-group">
          <input type="text" name="review[id]" placeholder="ID">
        </div>
        <button type="submit" class="btn btn-default btn-lg">Show Review</button>
      </fieldset>
    </form>
```

My functions 
api.js
```js
  <form class='show' id="show-review">
      <fieldset>
        <div class="form-group">
          <input type="text" name="review[id]" placeholder="ID">
        </div>
        <button type="submit" class="btn btn-default btn-lg">Show Review</button>
      </fieldset>
    </form>
```
Events.js
``` js
const onShowReview = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  console.log(data);
  let id = data.review.id;
    api.showReview(id)
    .then(ui.onSuccess)
    .catch(ui.onError);
};
```
ui.js
``` js
const onSuccess = function (data) {
console.table(data);
    let getReviewsHtml = getReviewsHandlebars({ reviews: data.reviews });
    $('#global-reviews').html(getReviewsHtml);
  };
```

**Comment by raq929** [comment]
What do you mean by 'does not allow me to enter data'? Can you enter things into the form fields?

**Comment by raq929** [comment]
If yes, please follow these steps to set your handler: https://github.com/ga-wdi-boston/full-stack-project/issues/529#issuecomment-264361193

If no, come see me in classroom 6.

**Comment by AshlenPrice** [comment]
Thansk @raq929 I have updated the form and I can now type in it but my review data isn't showing up in the handlebars table.

**Comment by jrhorn424** [comment]
In `api.js` above, you've pasted your markup again, not whatever the contents of `api.js` are.

**Comment by raq929** [comment]
Can you post the handlebars file?

**Comment by AshlenPrice** [comment]
``` handlebars.js
<thead>
  <tr>
    <th>ID</th>
    <th>Reviews</th>
    <th>Book title</th>
    <!-- <th></th> -->
  </tr>
</thead>
<tbody>
  {{#each reviews as |review|}}
 <tr data-id="{{review.id}}">
    <th scope="row">{{review.id}}</th>
    <td>{{review.review_content}}</td>
    <td>{{review.book.id}}</td>
  </tr>
  {{/each}}
</tbody>
```

**Comment by jrhorn424** [comment]
I had to re-learn this lesson tonight. Could you post the output of `grunt nag`, please? I honestly can't see anything wrong with your OP, though I'm not sure how that particular handlebars file is relevant.

**Comment by AshlenPrice** [comment]
![image](https://cloud.githubusercontent.com/assets/24688275/23241158/8fa82144-f93f-11e6-93c8-5a8ab1eb74bc.png)

I'm currently not working on this trying to finish my project to an acceptable point.  But it's my next thing to do!

**Comment by MicFin** [comment]
@AshlenPrice are you going to pursue this or should it closed?

**Comment by MicFin** [comment]
@AshlenPrice said she has ice boxed this issue until after she resubmits, this is not critical for her resubmittal.
