### ISSUE TITLE
Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#684]
This is the console error I am getting for this part of my event file:

```rb
const onGetMovies = function (event) {
  event.preventDefault();
  api.showMovies()
  .then(function (response){
    // $('.movie-entries').empty();
    console.log(response);
      for (let i = 0; i <= response.movies.length; i++){
        let movieTitle = `<div>Movie Title: ${response.movies[i].title}</div>`;
      //  let review_entry = `<div> Review: ${response.reviews[i].note}</div>`;
        $('.movie-results').append(`<div>${movieTitle}</div>`);
      }
  })
    .catch(ui.onError);
  };
```

In any event, I want to learn to do this with a handler after anyway, but I also don't understand why I am getting this error, because my titles are displaying on my page now, so I am not sure what this error even means.

**Comment by bernardlee** [comment]
You're probably seeing that error because `response.movies[i]` is undefined for some value of `i`.  Check your loop conditions.

**Comment by raq929** [comment]
Or there's a movie in your database that doesn't have a title. Perhaps from before you added validations.

**Comment by raq929** [comment]
I take it back, Bernard is right. 😛

**Comment by alexkarasik** [comment]
I did not need that = in the <=.
