### ISSUE TITLE
My JSON book data has some strange spacing in it and I want to know how to fix it.

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/full-stack-project#685]
This is what my JSON looks like with the strange spacing. I'm not sure what this issue is nor how to fix it. I think it stems from the spacing in the seed data but I had to style it that way because the linter was nagging that the lines were too long.

![image](https://cloud.githubusercontent.com/assets/24688275/23221929/56df56de-f8f4-11e6-8bc7-2cc0494ccfd0.png)
This is what my seed data look like-
``` ruby

Book.create([
              { title: 'Stepping on the Cracks',
                author: 'Mary Downing Hahn',
                grade_level: '5th',
                description: 'The story of a conscientious objector
                              being sheltered during World War II.' },

              { title: 'Wayside School Is Falling Down',
                author: 'Louis Sachar',
                grade_level: '4th',
                description: 'One of several hilarious books about wacky Wayside
                            School.' },

              { title: 'The Very Hungry Caterpillar',
                author: 'Eric Carle',
                grade_level: 'Pre-K',
                description: 'The tale of a ravenous caterpillar who eats his
                              way through the week.' },
              { title: 'Goodnight Moon',
                author: 'Margaret Wise Brown',
                grade_level: 'Pre-K',
                description: 'The classic bedtime book' },

              { title: 'The Cat in the Hat',
                author: 'Dr. Seuss',
                grade_level: '1st',
                description: 'A silly tongue-twisting story, about a cat in a
                              hat.' }
            ])
```

**Comment by raq929** [comment]
Is the strange spacing making your app look strange? If no, I don't think it's a problem.

**Comment by AshlenPrice** [comment]
It's not giving me any issues on my front end so I guess I won't worry about it now. I will close this for now and re-open if it becomes an issue

**Comment by bernardlee** [comment]
It's not strange spacing but exactly what you set the strings to.  For example, the description of the first book is "The story of a conscientious objector" followed by a line break, followed by several spaces, and finally followed by "being sheltered during World War II."  Look up how to write multiline strings in Ruby.  If you still need help, then please update this thread.

**Comment by jrhorn424** [comment]
@bernardlee Is correct. Ruby is working as expected. If you want the spacing gone, we have to change the syntax you're using.

@raq929 Is also correct. This should not be a priority.

**Comment by jrhorn424** [comment]
I'd use the `[].join` trick mentioned [here](https://www.commandercoriander.net/blog/2014/11/09/a-multiline-string-cheatsheet-for-ruby/) but instead of joining on a newline, I'd join on a space.

**Comment by AshlenPrice** [comment]
Awesome Thanks for the feedback I will add it to my list of things to fix when I'm done

**Comment by MicFin** [comment]
@AshlenPrice how is this issue going?

**Comment by MicFin** [comment]
@AshlenPrice said she has ice boxed this issue until after she resubmits, this is not critical for her resubmittal.
