### ISSUE TITLE
How to make Admin account?

### ISSUE THREAD

**Issue by zchenbonterra** [ga-wdi-boston/full-stack-project#686]
I like to make an admin account. How should I approach this?

**Comment by raq929** [comment]
I would add an attribute to users `isAdmin` (a boolean) and check for it. Likely in a function that is used called in the `before_action`.

**Comment by jrhorn424** [comment]
>I would add an attribute to users `isAdmin`

Our convention on the API is to make a column called `admin`. Rails will provide a predicate method called `admin?` for the associated model. 

`isAdmin` is a fine name for a predicate method on the client.

**Comment by raq929** [comment]
How's this going? If it's resolved, please close the issue. If not, can you update us on how it's going?

**Comment by zchenbonterra** [comment]
Thanks for quick reply. I was trying to do it earlier, but with time limit issue, I will have to add in this feature later on in the future. The comments were useful and I think I will know how to approach this when I start adding in this feature.
