### ISSUE TITLE
How do I make a search bar that searches by attributes other than id?

### ISSUE THREAD

**Issue by lbreguet** [ga-wdi-boston/full-stack-project#687]
I have a search bar in my app that can only search data by the id. How do I make it so it searches by another attribute of the table?

**Comment by raq929** [comment]
How are you searching by ID? I think you'd need to sent the param and the search term to the back end, and your controller can search by that.  Take a look at the ActiveRecord documentation and play around in `rails console` to figure out how to search the way you want, then move on to sending the correct data from the frontend.

**Comment by jrhorn424** [comment]
Yep! @raq929 is putting you on the right track. You'll need to do something with `params` and some sort of query method to find something in ActiveRecord.

Congratulations on choosing a hard problem to tackle. Have you met requirements otherwise?

**Comment by lbreguet** [comment]
Thank you for the help. And I am meeting requirements.

**Comment by samordonez** [comment]
I'm trying to do this as well and found a gem https://github.com/plataformatec/has_scope that seems to be made for this. Should I mess around with it try to do it via params? (which I have an idea of how to go about doing, but the gem seems like an easier way)

**Comment by samordonez** [comment]
I have a solution that works but makes rubocop angry. I changed my index action to the following:

```ruby
  # GET /books
  def index
    if search_params
      @books = Book.where(search_params)
    else
      @books = Book.all
    end

    render json: @books
  end
```
and further down in the controller
```ruby
  def search_params
    params.permit(:title, :author)
  end
  private :search_params
```

the part that angers rubocop is the `if search_params`, it tells me to `Use the return of the conditional for variable assignment and comparison`

**Comment by samordonez** [comment]
Rubocop is no longer about to arrest me:

```ruby
  # GET /books
  def index
    @books = if search_params
               Book.where(search_params)
             else
               Book.all
             end

    render json: @books
  end
```

**Comment by lbreguet** [comment]
Thanks Sam!!!
