### ISSUE TITLE
Un expected tInteger 

### ISSUE THREAD

**Issue by wilsonkaya** [ga-wdi-boston/full-stack-project#688]
The format of my toke is ```twilio_token:4384034hds395dk37``` both my linter and my api is given 

```syntax error, unexpected tINTEGER, expecting tSTRING_CONTENT or tSTRING_DBEG or tSTRING_DVAR or tSTRING_END```

How can I prevent this ?

**Comment by raq929** [comment]
You are giving it an integer and it's expecting a string. I would send it a string.

**Comment by raq929** [comment]
Actually, that may not be it. Check your linter for the syntax error, it will probably tell you what to do.

**Comment by raq929** [comment]
Post the code if you can't find it, please.

**Comment by wilsonkaya** [comment]
expecting tSTRING_CONTENT or tSTRING_DVAR or tSTRING_END

**Comment by raq929** [comment]
That's the error, please post the code that's generating the error.

**Comment by wilsonkaya** [comment]
I have converted to string and it worked thanks
