### ISSUE TITLE
How can I display reviews of books in the same book handlebars template?

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/full-stack-project#689]
I've made handlebars to show all the books when a user is not logged in. I want to be able to show the review content for the books that have reviews on it.
I have tried t display the data in the console and it shows up as a separate array that I dig about 2 layers in. I'm not sure how to actually show the data on the pg. 

Here is what my UI looks like.
![image](https://cloud.githubusercontent.com/assets/24688275/23223869/3b845370-f8fa-11e6-9a57-a83abb470220.png)

This is what my handlebars looks like
```handlebars.js
<div class="table-responsive">
  <table class="table table-hover">
<thead>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Author</th>
    <th>Grade Level</th>
    <th>Description</th>
    <th>Reviews</th>
  </tr>
</thead>
<tbody>
{{#each books as |book|}}
  <tr data-id="{{book.id}}">
    <th scope="row">{{book.id}}</th>
    <td>{{book.title}}</td>
    <td>{{book.author}}</td>
    <td>{{book.grade_level}}</td>
    <td>{{book.description}}</td>
    <td>{{book.reviews}}</td>
  </tr>
  {{/each}}
</tbody>

  </table>
</div>
```

``` handlebars.js
const getBooksSuccess = (data) => {
  console.table(data.books);

  let showBooksHtml = showBooksTemplate({ books: data.books });
$('.bookslist').append(showBooksHtml);
};
```

**Comment by bernardlee** [comment]
`book.reviews` is an array.  What can you do when you need to traverse an array?

**Comment by jrhorn424** [comment]
You're asking how to display the reviews. You're already doing for `books` exactly what you need to do for `reviews` as well.

**Comment by AshlenPrice** [comment]
Fixed it by doing 
``` js
<td>{{#each reviews as |review|}}
      {{review.review_content}}
      {{/each}}
    </td>
```

Thanks!
