### ISSUE TITLE
Trying to get click functions and ajax to work together

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/full-stack-project#69]
My CURL commands work.  In Rails C I can make the controllers and models and routes work together  Now it's getting something to display on the page or at least getting something from the backend.

Here is a sample AJAX call for getting my data to display on load

  new_location: function (token, id, callback) {
    this.ajax({
      method: 'POST',
      url: this.url + '/locations',
      headers: {
        Authorization: 'Token token=' + token
      },
      contentType: 'application/json; charset=utf-8',
      data: JSON.stringify(location),
      dataType: 'json'

```
}, callback);
```

  },

Here is my click function to post a new location

  $('#submit-loc').on('submit', function(e) {
      var location = wrap('location', form2object(this));
      on_tap_api.new_location(new_location, callback);
      e.preventDefault();
    });

It just takes me back to the top of the page without doing anything.

**Comment by gaand** [comment]
It looks like you got an argument/parameter mismatch
`new_location: function (token, id, callback) {`
verus
`on_tap_api.new_location(new_location, callback);`

**Comment by srhoulam** [comment]
Yep, I'm working with Jeff to correct various API methods and calls made to them.

**Comment by srhoulam** [comment]
Various issues from misnamed parameters, accessing the front-end as a file on disk, and calling api methods incorrectly have been resolved for adding new locations to his application. Jeff will now work on doing the same for adding new beers.

**Comment by jcmeyer10** [comment]
I changed everything to refer to Adding a Beer, making sure none of the trappings of the previous effort were there.  Right now when I click the submit button on new beer it just gives me back a location object instead of a Beer object.  There are no errors or anything and I have hard restarted my browser but it just wants to give me a location object.  Troubleshooting now but am curious.  Should I restart server?
