### ISSUE TITLE
Show Reviews button not displaying my reviews

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#690]
I am not getting an error in my console, but I have nothing displaying when I click my 'show reviews' button. 
Here is the event:
```rb
const onGetReviews = function (event) {
  event.preventDefault();
  api.showReviews()
  .then(function (response){
    $('.review-results').empty();
    console.log(response);
      for (let i = 0; i < response.reviews.length; i++){
        let movieId = `<div>Movie ID: ${response.reviews[i].movie_id}</div>`;
        let review_entry = `<div> Review: ${response.reviews[i].review_entry}</div>`;
        $('.review-results').append(`<div>${movieId}${review_entry}</div>`);
      }
  })
    .catch(ui.onError);
  };
  }

};
```
My handler:
```rb
  $('#show-reviews').on('click', onGetReviews);
```
The HTML:
```RB
  <button id="show-reviews">Show Reviews</button>
                <div class="review-results"></div>
```

**Comment by bernardlee** [comment]
Right click on your show reviews button, Inspect, and then check the Event Listeners tab in the Developer Tools.  Expand "click" and check if your handler is in the list.

**Comment by alexkarasik** [comment]
It says no event listeners, and I am not sure why...

**Comment by raq929** [comment]
Please follow the instructions here for creating click handlers: https://github.com/ga-wdi-boston/full-stack-project/issues/529#issuecomment-264361193

**Comment by alexkarasik** [comment]
I didn't have my reviews eventHandlers attached in the index.js file.
