### ISSUE TITLE
problems with my front end html

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/full-stack-project#694]
I'm not sure what I did, but my web site is not showing the html in my index.html.  It is showing an earlier version and I am afraid I might really have made a mess of it.
I know this is a badly worded question, but I don't know how else to explain it

**Comment by BenGitsCode** [comment]
What earlier version?

Is it possible you have:
- unsaved changes in atom?
- uncommitted changes?

Did it ever show those changes?

**Comment by Soboscott** [comment]
I can't find the earlier version, and I have committed since 
```
git status
On branch inprogress
nothing to commit, working tree clean
~/wdi/projects/trail-rater (inprogress)
$ 
```
when I was making changes to the html it was working before, I don't know what happened.

**Comment by Soboscott** [comment]
I tried looking in the inspector to find the source file but still could not find where it is Pulling the file from.

**Comment by BenGitsCode** [comment]
Are you looking for these changes on your local or deployed app?

**Comment by Soboscott** [comment]
local

**Comment by BenGitsCode** [comment]
Are you using private mode? If not, try pasting that link into an incognito window. (Open with CMD+SHIFT+N)

It's possible your browsers is caching your previous versions.

**Comment by Soboscott** [comment]
opened in an incognito window same result

**Comment by Soboscott** [comment]
i shut down the grunt server and restarted it same result

**Comment by BenGitsCode** [comment]
I can take a closer look at this, where are you now?

**Comment by Soboscott** [comment]
room 5

**Comment by jrhorn424** [comment]
@BenGitsCode @Soboscott I'm curious what the resolution was.

**Comment by Soboscott** [comment]
I had nested repos

**Comment by BenGitsCode** [comment]
@jrhorn424 

```
Some-parent-directory
api-repo
├── .git
   └── client-repo
    └── .git
```

Directory structure looked like this. we essentially `mv client-repo ../some-parent directory` so that he now has separate client and api repos there, not nested. 

Because of this, all of his client commits before today were made in the `api-repo` .git object and not in the client repo, which contained only the browser-template commits.
