### ISSUE TITLE
request 1 on 1 

### ISSUE THREAD

**Issue by K0iram** [ga-wdi-boston/full-stack-project#695]
I fixed my previous problem I posted about my post function getting stuck in a loop ( #691 ) but now I'm having a problem where the patch function is not firing on my click event. 

my click handlers looks like this

```
const addHandlers = () => {
  $('#create-meal').on('submit', onCreateMeal);
  $('#show-meals').on('click', onGetMeals);
  $('.meal-show').on('click', '.meal-delete', onRemoveMeal);
  $('.meal-show').on('click', '.meal-edit', openEditModal);
  $('form.edit-meal').on('submit', onUpdateMeal);
};
```

**Comment by K0iram** [comment]
actually just figured it out when i printed those on the screen.

**Comment by jrhorn424** [comment]
Good work!
