### ISSUE TITLE
Can't get book title & information onto the review table

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/full-stack-project#696]
I'm trying to show data from my books table like book title/author on my reviews table. I have tried adding validations and constraints in my api, as well as adding the book attributes like ```:title``` to my reviews serializer. 

Each of those attempts result in  a  bad request error or internal server error. 
Do I need to add a migration to ```AddBookTittleToReviews```?

**Comment by bernardlee** [comment]
How are you retrieving your reviews?

**Comment by jrhorn424** [comment]
> Do I need to add a migration to AddBookTittleToReviews?

No. Aren't you already storing that in a `books` table? Plus, you have a misspelling there.

Please post:

- The script or command that is generating the error
- The error you are getting (browser console or terminal, as well as API server if needed)
- Your models
- Your schema
- Your serializers

If you've pushed a recent branch, it might be quicker just to drop a link to it.

**Comment by AshlenPrice** [comment]
[This](https://github.com/AshlenPrice/bookienook-api/tree/fixes) my most updated branch I just pushed. I undid all the changes I can re-do them so that you can see what I tried. Give me a few minutes.

**Comment by jrhorn424** [comment]
Ok, paste links to the commits you want me to see.

**Comment by AshlenPrice** [comment]
I didn't commit those changes. I want someone to look at my relationships to make sure they are right to achieve what I want to achieve.

**Comment by raq929** [comment]
Your relationships are OK. (I looked at this during our 1:1.) This can be fixed through the serializer.

**Comment by bernardlee** [comment]
Take a look at the Associations section in the [Active Model Serializers documentation](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/serializers.md).

**Comment by jrhorn424** [comment]
@AshlenPrice Any update? Just curious. Not priority for tonight, but soon please.

**Comment by bernardlee** [comment]
Hint: try adding an association from a model into its serializer and observe how the output changes.

**Comment by MicFin** [comment]
@AshlenPrice how are you doing with this issue?

**Comment by MicFin** [comment]
@AshlenPrice said she has ice boxed this issue until after she resubmits, this is not critical for her resubmittal.
