### ISSUE TITLE
Page is refreshing

### ISSUE THREAD

**Issue by novakw267** [ga-wdi-boston/full-stack-project#698]
I feel silly I can't figure this out. Everytime I click on the button referenced in the click handler at the bottom of the page, it refreshes the page. I ran a console.log and was able to show that this page of code is loaning on the page, and the problem is clicking the button at least from what I can tell??

```js
'use strict';
const getFormFields = require(`../../../lib/get-form-fields.js`);

const api = require('./api');
const ui = require('./ui');

const store = require('../store');

const onCreateProfile = function(event) {
  event.preventDefault();
  console.log('lol');

  let data = getFormFields(event.target);

  api.profiles(data);

  console.log('lol')
    .then(ui.createProfileSuccess)
    .catch(ui.failure);
};

const test = function() {
  console.log('working?');
};
// const addHandlers = () => {
//   $('#sign-up').on('submit', onSignUp);
//   $('#sign-in').on('submit', onSignIn);
//   $('#change-password').on('submit', onChangePassword);
//   $('#sign-out').on('submit', onSignOut);
// };

const profHandlers = () => {
    $('#create').on('submit', onCreateProfile);
    $('#create_profile').on('click', test);

};

module.exports = {
 profHandlers,
 test,
};
```

**Comment by raq929** [comment]
Yep, the default for clicking a button is to refresh the page. Which means you're not preventing default. Which means this click handler is not set properly. I assume your `console.log()` is not logging anything?
Can you post the HTML that this click handler is set on?

**Comment by novakw267** [comment]
So I added 'test' in the index.js
```
$(() => {
  authEvents.addHandlers();
  profEvents.profHandlers();
  profEvents.test();
});
```
 to see if the events page is getting loaded it is, the click handler is attached to this in the html
```
<input type="submit" name="submit" value="Create Profile" id="create" class="hidden">
```
which on signup and sign in I have that class hidden removed from the button to appear. Not sure what else would be helpful in determining where its not connecting.

**Comment by raq929** [comment]
Is the create profile button part of a form? Does anything else in your html have that ID? (I would search your html for create to double check.)

**Comment by novakw267** [comment]
It is part of a form,
```
  <form id="create_profile" class="hidden">
    <fieldset>
      <legend>Create Profile!</legend>
    <label>
                Profile Name
                <input type="text" name="profiles[USERNAME]" id="username" class="hidden">
              </label>
    <label>
                Favorite Genre
                <input type="text" name="profiles[FAVORITE_GENRE]" id="favorite_genre" class="hidden">
              </label>
    <label>
                Favorite Band
                <input type="text" name="profiles[FAVORITE_BAND]" id="favorite_band" class="hidden">
              </label>
    <input type="submit" name="submit" value="Create Profile" id="create" class="hidden">
  </fieldset>
  </form>
``` 
I know I am having issues with the path to my profile data in my back end, but I am not even getting to the 404 error I was getting before.

**Comment by novakw267** [comment]
I figured it out I needed to call to the form id and not the id of the button itself.
