### ISSUE TITLE
implementing Antony's API

### ISSUE THREAD

**Issue by HoldenMills** [ga-wdi-boston/full-stack-project#70]
Instead of cloning the project2-api (as I should have done) I made my own and copied from the project-api into my ps_app.  I'm assuming the best fix would be to re-clone the project2-api and copy my ps_app into it, but I would like help making sure I do that right.

**Comment by GA-MEB** [comment]
What's going wrong with the one you built yourself? It's inadvisable to start from scratch at this point unless absolutely necessary.

**Comment by HoldenMills** [comment]
I'm running into Authentication issues.  After sending a post request to the local host I get this;

ActionController::InvalidAuthenticityToken

**Comment by HoldenMills** [comment]
when I ran a curl request into my terminal; 
curl --include --request POST --header "Content-Type: application/json" -d '{

>   "credentials": {
>     "email": "abc@email.com",
>     "password": "a",
>     "password_confirmation": "a"
>   }
> }' http://localhost:3000/register

I got this;

HTTP/1.1 422 Unprocessable Entity 
Content-Type: text/html; charset=utf-8
Content-Length: 86302
X-Request-Id: c268f290-103b-48f0-966f-28f85b644dc4
X-Runtime: 0.349286
Server: WEBrick/1.3.1 (Ruby/2.2.3/2015-08-18)
Date: Thu, 12 Nov 2015 15:15:50 GMT
Connection: Keep-Alive

I know I need a token to login, but I can't get it.

**Comment by srhoulam** [comment]
It looks like Holden's register route requires an authorization token.

**Comment by gaand** [comment]
There should be a `skip_before_action :authenticate, only: [:login, :register]` in the auth controller to remove that requirement.
