### ISSUE TITLE
trigger one function on one click and then on second page trigger two functions with the same button 

### ISSUE THREAD

**Issue by s0phi4** [ga-wdi-boston/full-stack-project#702]
I have a form with a save button and a see your resources button on my home page. A user is able to save and once save is clicked it also displays the table.
I want the table to be displayed when see your resources is clicked and keep the form and have the user save but clisk on save and see the new update on the table. 
All  functions are working properly and the buttons as well but the see your resources button is like useless!
```
const onCreateLink = function (event) {
  event.preventDefault();

  let data = getFormFields(event.target);
  console.log(data);

  api_link.createLink(data)
 .then(ui_link.success)
 .then(onGetLinks)
 .catch(ui_link.failure);
 };
```

**Comment by s0phi4** [comment]
So on this click event on the home page I want the info to be saved 
and on second page having the same form and button I want the info saved and the index to run also.
```
$('#linksForm').on('submit', onCreateLink);
```

What the save button is doing now on the home page is saving and showing the updated table

**Comment by jrhorn424** [comment]
@yenpraja610 May I see all of your handlers registrations? (anything with `.on`)

**Comment by jrhorn424** [comment]
@yenpraja610 Clarified her requirements and expectations. We resolved the issue of having a "useless button" to fetch a list by making the list auto-populate after sign-in. Yen exported and used a function she had already written to fetch and populate the table in the sign-in success handler.

**Comment by jrhorn424** [comment]
@yenpraja610 Is this closable?

**Comment by s0phi4** [comment]
Yes Sir! @jrhorn424
