### ISSUE TITLE
Deployed project but no data shows up in books

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/full-stack-project#703]
Hey I deployed my project to test to make sure everything was working but when I check out books you can read I get an empty table. 
I've pushed all my things to master, and Heroku master not sure what to do.
[Here is my link]( https://ashlenprice.github.io/bookienook/)

**Comment by raq929** [comment]
Your database on Heroku is new, so it doesn't have any data in it. 
You can create examples or run whatever file you create your books in using `heroku run bin/rake db:examples`. (Substitute the other file if your books are not in examples.)

**Comment by AshlenPrice** [comment]
Oh Awesome! Thanks that was the case.

**Comment by jrhorn424** [comment]
The database on your machine is not controlled by git, and an entirely separate database is securely created for you on heroku.
