### ISSUE TITLE
Front End Not Updating

### ISSUE THREAD

**Issue by ladypinetree** [ga-wdi-boston/full-stack-project#705]
I deployed my master about an hour ago and it seems that my front-end is only receiving error messages.
https://ladypineapple.github.io/pollBrowser/
The front end throws error messages on sign in, sign up, or search.
<img width="702" alt="screen shot 2017-02-22 at 7 44 41 pm" src="https://cloud.githubusercontent.com/assets/24965469/23239843/9392ac1e-f937-11e6-85c2-6efb4e43631b.png">

When I check the network I get 200s
<img width="663" alt="screen shot 2017-02-22 at 7 45 00 pm" src="https://cloud.githubusercontent.com/assets/24965469/23239848/973e1b14-f937-11e6-980f-932dc18abf4b.png">

Please let me know what other info I can provide.

**Comment by raq929** [comment]
You missed a step in the deployment.
`heroku config:set CLIENT_ORIGIN=https://yourgithubname.github.io`

(You need to change `yourgithubname` to your actual gitHub name.)

**Comment by ladypinetree** [comment]
Even better, I set the client config to https://yourgithubname.github.io

Apparently my brain slows dramatically after 12 hours.

**Comment by jrhorn424** [comment]
> Apparently my brain slows dramatically after 12 hours.

Been there. Lived that life. Living it now.
