### ISSUE TITLE
How to revert changes made to master

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#708]
I was working in the master branch by accident and want to undo the changes. I know exactly where they are and they are only in one file, but I think I just want to go back a commit. 
This was what came up when I did a git log:
```rb
~/Documents/wdi/project2/movieReview-client (master)
$ git log
commit 8257012c41535171993d703806f4ec2dd96feb2e
Author: kinkorea <alexkarasik89@gmail.com>
Date:   Thu Feb 23 09:22:23 2017 -0500

    Added in movie form field

commit a0771e67d8a2c8445ea7e309fea2ec82b9fa0855
Author: kinkorea <alexkarasik89@gmail.com>
Date:   Wed Feb 22 21:13:02 2017 -0500

    Changed the config
```

So I believe all I want to do is 
```rb
git reset a0771e67d8a2c8445ea7e309fea2ec82b9fa0855
```

But I want to make sure it is the right thing before I do it. I had to make a change to the config file in order for the deploy on heroku to work, so I think I am fine with that previous commit to master and just want to be safe.

**Comment by raq929** [comment]
I would create a branch, and try it on that branch. If it gets you to where you want to be, then you did it right! If not, you can go back to your other branch where all commits are still there.

**Comment by MicFin** [comment]
@alexkarasik What is the status on this?

**Comment by alexkarasik** [comment]
Taken care of in the 1 on 1, thanks guys
