### ISSUE TITLE
one on one request

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#709]
I want to meet with someone to discuss what went wrong with my project and what I think needs to be done for it next. I want to add a database of movies that users can add reviews to and have their user names attached to their reviews and am not sure how to do that. I want to add in handlebars and make sure I understand them and what they are doing better than I currently do before adding them in.

**Comment by raq929** [comment]
I will try to make sure you get some 1:1 time on Wednesday when we have workshop time.
