### ISSUE TITLE
One of One Request

### ISSUE THREAD

**Issue by spwisner** [ga-wdi-boston/full-stack-project#712]
After meeting with Jeff today, I mentioned that I made the mistake of creating a new repo for the project (because of starting over).  He informed me that this is not allowed (I should have known this from the instructions) and that I will need to transfer over my new repo to the original.  The complication involves the commits I made with the new repo.  I do not know how to transfer the commits over to the original repo (otherwise it will only register as a single commit).

I would greatly appreciate it if someone would be willing to meet with me to make the transfer and to briefly go over my new project.  Thank you.

**Comment by MicFin** [comment]
Is this still an active issue?

**Comment by spwisner** [comment]
I never found out how to merge my new repo to the original with all of my new commits.  Therefore, I will have to just replace it, which will only count as one commit.

**Comment by MicFin** [comment]
You still have the 2nd repo that you can use to show you met the commits per day requirement, please push it to github and include it as part of the README explaining what happened.
