### ISSUE TITLE
Displaying dates other than default

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/full-stack-project#713]
Currently, when indexing my resource, the date displays as **2016-03-04** and is ordered descending.
Goal: date displays as **Mar 4** and ordered descending.

I believe it would be in the back end (resource controller) to send the data in such a format but am unsure how to do so. 

I have found the following documentation with more formats than I thought existed: [http://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html](url)
One that seemed promising for the year is:
**:discard_year - Set to true if you don't want to show a year select. This includes the year as a hidden field instead of showing a select field.**

One that seemed promising for the month is:
**:use_short_month - Set to true if you want to use abbreviated month names instead of full month names (e.g. “Feb” instead of “February”).**

For the day, I also need to find a way to discard a double digit display if it is a single digit day, i.e: 4 instead of 04.

So would it be something like this?
```ruby
  def index
    @climbs = current_user.climbs.all.order(date: :desc, :discard_year :true, :use_short_month :true)

    render json: @climbs
  end
```
I am also confused regarding the colons.

current controller:
```ruby
  def index
    @climbs = current_user.climbs.all.order(date: :desc)

    render json: @climbs
  end
```

**Comment by MicFin** [comment]
**.order()**

Let's start with the `.order()` method and the arguments we pass to it.  The documentation is
[here](http://apidock.com/rails/ActiveRecord/QueryMethods/order).
```rb
User.order(:name)
=> SELECT "users".* FROM "users" ORDER BY "users"."name" ASC

User.order(email: :desc)
=> SELECT "users".* FROM "users" ORDER BY "users"."email" DESC

User.order(:name, email: :desc)
=> SELECT "users".* FROM "users" ORDER BY "users"."name" ASC, "users"."email" DESC

User.order('name')
=> SELECT "users".* FROM "users" ORDER BY name

User.order('name DESC')
=> SELECT "users".* FROM "users" ORDER BY name DESC

User.order('name DESC, email')
=> SELECT "users".* FROM "users" ORDER BY name DESC, email
```

The `.order()` method can accept a few patterns of parameters.  
In your code you use:
```rb
@climbs = current_user.climbs.all.order(date: :desc)
```
So you are ordering based on the `date:` column and the order you want them in is `:desc` descending order. `:desc` and `:asc` are symbols that Rails know.   

**Dates**

Dates can be challenging in programming.  Generally we like to have our server API use the date in the format you originally have `2016-03-04`.  That is ideal for sorting and storing.  On our client side, we often want to display the date in a more human readable form.  

*Client Side*
Once your client side application, receives a date from the server API and needs to display it, we can use the Javascript `Date()` library to write javascript that formats our `2016-03-04`.

```js

const monthNames = ["Jan", "Feb", "Mar", 
"Apr", "May", "June", "Jul", "Aug", "Sep", 
"Oct", "Nov", "Dec"];

const dateFromAPI = "2016-03-04";

let d = new Date(dateFromAPI); // turns string into a Date object
let curr_date = d.getDate(); // gets us the 1-31 value of a day
let curr_month = d.getMonth(); // gets us the 1-12 value of a month

let formattedDate = monthNames[curr_month] + " " + curr_date ;
```

Or we could use a Date library in JS that someone else already built like:
https://momentjs.com/
http://www.mattkruse.com/javascript/date/source.html 

*Server Side*
Ruby on Rails does provide us with methods to format dates before the API sends the data back to the client.  In this scenario you would write a method on your Serializer model for that resource that formats the date.

```rb
class ClimbSerializer < ActiveModel::Serializer
  attributes :date 

  def date
    object.date.strftime("%b %e")
  end
end
```
https://stackoverflow.com/questions/22255476/rails-formatting-date

Is formatting the date on the front end part of your requirements to resubmit?
If not, I would save formatting the date for AFTER your resubmit and BEFORE the Meet and Hire.

**Comment by doremaxime** [comment]
I do not have to resubmit, just making it better.
Thank you for explaining that I could do on either the server side or the client!
At first I thought it would be more complex to do it on the client side because I imagined all that code being in the handlebars (seeing as that's where my dates were being generated) but I now know better. 
Seeing as we were playing with serializers today and that I didn't use it on my project, I will have the date format set on the server side.
Thank you!
