### ISSUE TITLE
Getting a message to display with an empty database...

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#716]
I have been working on getting a message to display when my database is empty and it has not been working... 
This is the event that gets triggered by clicking a "show movies" button:
```js
const onGetMovies = function (event) {
  event.preventDefault();
  api.showMovies()
  .then((response) => {
     store.movies = response.movies;
     return store;
   })
  .then(ui.onSuccess)
  .catch(ui.onError);
  };
```
This is my ui success function:
```js
const onSuccess = function (data) {

  if (data) {
    console.log(data);
  } 
  let showMovies = movieHandlebars({ movies: data.movies});
  $('.movie-results').empty().append(showMovies);
  if (store.movies.length === 0) {
    $('.message').text("no movies");
  }
};
```

and this is my html section where they get displayed:
```html
      <button id="show-movies">Show Movies</button>
          <div class="movie-results"></div>
```

I think that is all the useful info...

**Comment by MicFin** [comment]
On this line you are using `data.movies` to reference all of the movies

```js
let showMovies = movieHandlebars({ movies: data.movies});
```
Yet in your condition you are using `store.movies` to reference all of the movies.

```js
if (store.movies.length === 0) {
```
**1.  What is `store.movies` and what is `data.movies`?**

To add the `no movies` text to the page you are using
```js
 $('.message').text("no movies");
```

In this case you are adding the string`no movies` as the text of the HTML elements with the `message` class.  But, in your HTML there is no `message` class from what you've shared.  

**2. Is there an HTML element with the class `message`?**

**Comment by alexkarasik** [comment]
I have a div with a .message class up above and I know that is working because it is working for all of the other messages.
I am going to check this for reviews now instead because that database is empty and has the exact same format, but this is still not working:
```js
const onSuccess = function (data) {
    //  debugger;
      if (data) {
        console.log(data);
      }
      let showResults = reviewHandlebars({ reviews: data.reviews});
      $('.review-results').empty().append(showResults);
      if (data.reviews.length === 0) {
        $('.message').text("no reviews");
      }
    };
```
```js
const onGetReviews = function (event) {
  event.preventDefault();
  api.showReviews()
  .then((response) => {
     store.reviews = response.reviews;
     return store;
   })
  .then(ui.onSuccess)
  .catch(ui.onError);
};
```

**Comment by MicFin** [comment]
Can you explain more about what is going wrong?
What are you seeing on the page?  
If you inspect the page, what HTML is there that shouldn't be or isn't there that should be? 
Are there any errors in the console?

Here you append the template to elements with the `review-results` class.  
```js
let showResults = reviewHandlebars({ reviews: data.reviews});
$('.review-results').empty().append(showResults);
```

Should that happen if there are no reviews?

**Comment by alexkarasik** [comment]
There are no errors in the console, it just displays array[0] if I try to get the reviews when there are none.
That shouldn't happen if there are no reviews. Perhaps I should include it as the else part of an if statment that starts with accounting for the length of reviews being 0.
I haven't slept well in awhile and need to go to bed now, but please let me know tomorrow. I am scared of failing right now over this but I need sleep.
Thanks.

**Comment by alexkarasik** [comment]
I woke up a little while ago and I am trying to check my local host host, but I am not getting a connection error and not sure why. When I click anything in the conolse, I get a message of ERR_CONNCECTION-REFUSED

**Comment by alexkarasik** [comment]
I got it figured out. I don't know why it wasn't changing my message before but tis working now.
