### ISSUE TITLE
CORS - Call is rejected by outside API

### ISSUE THREAD

**Issue by dhuddell** [ga-wdi-boston/full-stack-project#72]
Making a GET request to foreign API. **IF I CAN FIGURE THIS OUT ON MY OWN, JUST SAY GO, OTHERWISE I'LL WAIT TO TALK TO SOMEONE**

Error: 

```
XMLHttpRequest cannot load https://api.forecast.io/forecast/0d2fae036c63eb41ba914a58600cb1ef/42.3991718,-71.1240559. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access.
script.js:188 Object {jqxher: Object, status: "error", error: ""}
```

API code:

```
get_weather: function get_weather(latlng, callback) {
    this.ajax({
      method: 'GET',
      url: 'https://api.forecast.io/forecast/0d2fae036c63eb41ba914a58600cb1ef/' + latlng,
      contentType: 'application/json'
    }, callback);
  },
```

I've found a tutorial, but I also have other things to be working on, so dig in or work on other things?

**Comment by srhoulam** [comment]
Dan, come to the dugout. This sounds like a quick one.

**Comment by srhoulam** [comment]
Dan was having CORS errors when making AJAX requests at an API that did not set CORS headers. I instructed him to make HTTP requests at this API from his back-end instead, where CORS is irrelevant.
