### ISSUE TITLE
Database not clearing

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#721]
On my deployed site, I know the message works when either my movie or review database is empty to let the user know, but I have run db:nuke_pave a number of times now and the the data is still there.

**Comment by gaand** [comment]
I don't think db:nuke_pave can run successfully against heroku.

Some of the options listed here might help: `heroku pg --help`

**Comment by alexkarasik** [comment]
I am getting a 500 error from my server now and I have not seen this before.

**Comment by MicFin** [comment]
Have you done your migrations for your Heroku environment or just your local environment? 
https://stackoverflow.com/questions/4820549/how-to-empty-db-in-heroku

**Comment by alexkarasik** [comment]
i just created a new deployment on heroku and its working now. thanks
