### ISSUE TITLE
[requirements] - Front End

### ISSUE THREAD

**Issue by aprilsourz** [ga-wdi-boston/full-stack-project#723]
Are there any other requirements for the front end of this project other than the following?

It effectively makes use of all the required features of the API.
Which are: Authentication(sign up, sign in, sign out, change password) and create, read, update, and delete data in a SQL database.

In other words, I can do whatever I want, as long as I build an API that does these things and a front end that makes use of them.

**Comment by tvcrawley** [comment]
As long as you are satisfying the [**deliverables**](https://github.com/ga-wdi-boston/full-stack-project) section, you "can do whatever [you] want".

**Comment by danman01** [comment]
@arlofeirman can we close this issue out?

**Comment by aprilsourz** [comment]
Thanks

**Comment by Jcornmanhomonoff** [comment]
@arlofeirman would you mind closing please?! 👍
