### ISSUE TITLE
I think I messed up my remote git repos

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/full-stack-project#725]
I want to do a test deploy to make sure I have set up heroku and the other 2 repos correctly. 

When I try to grunt deploy from my full-stack-client repo I get the following error:

error: failed to push some refs to 'https://github.com/awoodrum87/angies-other-list-client'.

I am able to ```git push origin master``` with no errors.  I also think it is because my local repo and my github repo have different names, but I have not had success creating a github repo with the same name and trying to push to that either.

**Comment by tvcrawley** [comment]
What is the entire error message?

**Comment by awoodrum87** [comment]
To https://github.com/awoodrum87/angies-other-list-client
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/awoodrum87/angies-other-list-client'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Warning: Command failed: git push origin master
To https://github.com/awoodrum87/angies-other-list-client
 ```! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/awoodrum87/angies-other-list-client'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
 Use --force to continue.

Aborted due to warnings.```

**Comment by tvcrawley** [comment]
This output is very helpful! It looks like git is providing a helpful suggestion to solve your problem. Have you tried it yet?

**Comment by tvcrawley** [comment]
Update?

**Comment by awoodrum87** [comment]
I have verified that no other repos are pushing to angies-other-list-client.
I have nothing in the remote repo, so I don't have work remotely that needs pulled to my local repo.

Link to repo: https://github.com/awoodrum87/angies-other-list-client

**Comment by awoodrum87** [comment]
I also have this issue with my angies-other-list-api

**Comment by tvcrawley** [comment]
What is the output when you type `git remote -v`?

**Comment by awoodrum87** [comment]
<img width="763" alt="screen shot 2017-04-27 at 11 12 17 am" src="https://cloud.githubusercontent.com/assets/25780850/25490358/9a486ab4-2b3a-11e7-84d4-2858ddd5b6df.png">
<img width="660" alt="screen shot 2017-04-27 at 11 12 45 am" src="https://cloud.githubusercontent.com/assets/25780850/25490359/9a48946c-2b3a-11e7-9b9c-eedc33250da7.png">

**Comment by awoodrum87** [comment]
We isolated the issue to the README file where what was local was different from the remote and it was causing merge conflicts. This was resolved by reconciling the readme file and committing again. 
thanks @tvlangley!
