### ISSUE TITLE
Having trouble with CURL to HEROKU

### ISSUE THREAD

**Issue by sjruby** [ga-wdi-boston/full-stack-project#726]
I'm fairly sure I got my heroku app launched, when I look at the guide I'm getting to the last step successfully with root URL: https://tiler-wdi-p2.herokuapp.com/

I updated the URL in the curl request, the sign-up I'm trying to run is below

```sh
curl --include --request POST https://tiler-wdi-p2.herokuapp.com/sign-up \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "an@example.email",
      "password": "an example password",
      "password_confirmation": "an example password"
    }
  }'
```

The response I get from the server is "TTP/1.1 500 Internal Server Error" which makes me think that I didn't set up something correctly with Heroku.  I ran bin/rake routes to confirm that the /sign-up POST route does exist on my API already.  Tried googling some HEROKU 500 errors but wasn't able to diagnose the problem.

**Comment by sjruby** [comment]
One other thing I did was double check the Heroku set up, I do have all the keys/origins I think I'm supposed to, when I ran heroku config this is my result:

=== tiler-wdi-p2 Config Vars
CLIENT_ORIGIN:            https://sjruby.github.io
DATABASE_URL:             postgres://izjsxwvzdxhmbx:933cae336328fc5a80a5aa9195bd7685d05e0d216c5bb28ce7519b1beabd8b6c@ec2-54-221-244-196.compute-1.amazonaws.com:5432/d9ko4l4n11818i
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_LOG_TO_STDOUT:      enabled
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:          479cf293a8cdd75fdbbb6b86ab1d3581689bf9e9a48b6d3f98576a6d40073c72eb2f856aeae0cd1564876c7e83776ae019a8ad81fba0028473b99f39d40e06bf
SECRET_TOKEN:             7dfab11fa28599d1d3decdaf36eebbc12c5a3388444126af80b8f5af15471657ff5701cf266a3669e7209237c41b183ada7fdf52547b97c5a878e1efd9269c78

**Comment by benjimelito** [comment]
When you say "launched", do you mean deployed? When I go to the url you provided, I'm not currently getting anything

**Comment by sjruby** [comment]
Totally, I don't expect there to be anything.  It is deployed to git, b/c when I run git push heroku master the response is Everything up-to-date.  I have not put any content on the page, I'm trying to run a curl script off the heroku server before trying to login on the front end.

**Comment by sjruby** [comment]
I tried going through some of the steps again and I'm still getting the CURL error of HTTP 500.  Can I please get some one-one time for this b/c I am struggling to make progress on the backend without heroku running.

**Comment by tvcrawley** [comment]
Double check your curl request. Is it of the same format as `scripts/sign-up.sh` or (if this file has been modified) the others in the `scripts` folder?

**Comment by sjruby** [comment]
I'll look at the CURL request but it's the one I used TIC-TAC-TOE one I used with a changed URL.  I know I'm not using the variable format but I didn't think that should change anything.  I will try to mess with that, but would rather not waste time trying to  make a CURL request take variable when I've copied code that I know works in another environment. What will be different if I do that?  I'm working on it now just wondering.

**Comment by jordanallain** [comment]
have you run heroku migrations and restarted the heroku app?

**Comment by sjruby** [comment]
Just reran those commands and reopend heroku and it worked.  Here's my updated CURL script it's still bombing with the 500 error.

```sh
EMAIL=ava@bob.com
PASSWORD=hannah
API="${API_ORIGIN:-https://tiler-wdi-p2.herokuapp.com}"
URL_PATH="/sign-up"

curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "'"${EMAIL}"'",
      "password": "'"${PASSWORD}"'",
      "password_confirmation": "'"${PASSWORD}"'"
    }
  }'
``

**Comment by jordanallain** [comment]
I'm confused about this line

`API="${API_ORIGIN:-https://tiler-wdi-p2.herokuapp.com}"`

does your terminal know what API_ORIGIN is?

**Comment by sjruby** [comment]
Took it out and it still bombs, can I please just get some 5 minutes on this, I'm sure I'm just missing something really obvious and don't want to keep thrashing on this issue.

**Comment by BenGitsCode** [comment]
Was this issue resolved? It closed without a resolution as I was commenting on it.

**Comment by sjruby** [comment]
Yeah it was solved, I don't know why or what I did but just thrashed at it and now its working.

**Comment by EricLScace** [comment]
I am having exactly this same issue. Unfortunately this thread doesn't have a resolution.
