### ISSUE TITLE
Direction After Creating Repos, Database, and Tables

### ISSUE THREAD

**Issue by andyjzhong** [ga-wdi-boston/full-stack-project#727]
Greetings --

I was wondering if one of the consultants can help provide some direction as far as next steps. I was able to successfully create repos for both my client and API using the templates provided. I also was able to scaffold a 'cars' table with valid columns in my API. I'm pretty sure my next step is to establish relationships between my users and their cars but I'm nervous about making changes. I decided to keep my ERD as simple as possible for the time being with a one-to-many relationship using Users which have_many Cars.

I can work on adding in forms for user sign-up and sign-in, etc. similar to the way I did for the game project in the meantime. I will also try to review our training material on one-to-many relationships as I wait to hear back -- just wanted to put this out there as early as possible.

Please let me know if you need any additional info.

Thanks!

**Comment by benjimelito** [comment]
Hey Andy, it sounds to me like you have a pretty good idea of your next step, what changes are you nervous about making specifically? Keep in mind that you can always check out a new branch and make changes without affecting `master`!

**Comment by andyjzhong** [comment]
Thanks, Ben! As I was writing back I think I answered my own question! I was unsure of how to actually CHECK whether I'm doing things correctly, but then I remembered I could just view the rails serve through localhost and see whether my cars objects were created. I think what I'm going to do next is create files within my db/migrate folder similar to what we did in class and also run curl requests to see if these are running as intended. 

Does this sound like a good approach? Thanks!

**Comment by benjimelito** [comment]
I think you're on the right track for sure 👍

**Comment by andyjzhong** [comment]
Thank you! :)

**Comment by tvlangley** [comment]
@andyjzhong If you have no further concerns on this topic, please close this issue.
