### ISSUE TITLE
Token Authentication for Creating Users

### ISSUE THREAD

**Issue by jscohen** [ga-wdi-boston/full-stack-project#728]
I am trying to begin my process by creating a new user on the back end.  I am using the user_controller object from the API template that we went over this morning.  I am posting in the following CURL script:

curl --include --request POST http://localhost:4741/users \
    --header "Content-Type: application/json" \
    --data '{
    "user": {
    "email": "Jon Cohen",
    "password": "j",
    "password_confirmation": "j"
  }
}'

I get the reply: 
HTTP/1.1 401 Unauthorized
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
WWW-Authenticate: Token realm="Application"
Content-Type: text/plain; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 26d4cab0-ec96-4ea6-b9dc-f3eb42f0788b
X-Runtime: 0.004847
Vary: Origin
Transfer-Encoding: chunked

HTTP Token: Access denied.

I believe that this has something to do with the authentication or token.  However, I'm just trying to create a user, so I don't have a token.  On the front end process, which I am using the tic tac toe API for, a token is not created during the sign up.

I looked at my CreateUsers migration and it seems to require a token: 

'''
class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :email, null: false, index: { unique: true }
      t.string :token, null: false, index: { unique: true }
      t.string :password_digest, null: false
      t.timestamps null: false
    end
  end
end
'''

I am just not sure how to create a token to test my user creation in this scenario.

Thank you in advance.

**Comment by jscohen** [comment]
Please disregard, I solved this issue.

**Comment by benjimelito** [comment]
That's great, please remember to update with your solution and close the issue!

**Comment by tvcrawley** [comment]
@jscohen ☝️ please update and close!

**Comment by jscohen** [comment]
So I had a user validation test that looked for the token and gave the error, but the token is actually not required to create a user so I removed it.  Closing now.
