### ISSUE TITLE
Need help with migration

### ISSUE THREAD

**Issue by octater** [ga-wdi-boston/full-stack-project#732]
I created a table using bin/rails generate scaffold games.  I updated the routes and did some curl commands against the table.  Now I realize, I had a column defined incorrectly.  I wanted to delete the scaffold associated with this games table.

I have ran the following:
  598  bin/rails destroy migration 20170427154104_create_games
  599  bin/rails db:rollback
  600  bin/rails destroy migration 20170427154104_create_games
  601  bin/rails db:migrate
  602  bin/rails destroy migration 20170427154104_create_games

but after each one, the table was still on the database.

```RB
class CreateGames < ActiveRecord::Migration[5.0]
  def change
    create_table :games do |t|
      t.string :player_id
      t.string :game_status
      t.string :letters_played, default: ["", "", "", "", "", ""], array: true

      t.timestamps
    end
  end
end
```

**Comment by octater** [comment]
I am not that far along, if it is easier to nuke everything, that is fine.  I did already push the tables to  heroku.

**Comment by tvcrawley** [comment]
There's no need to nuke the table if a column is wrong. A migration can be run to correct the column.

**Comment by payne-chris-r** [comment]
db:migrate adds the migration, db:rollback takes the last migration and "undoes" it. If you run `db:rollback` after you've deleted the migration I'm not sure how it handles it--but I don't think good things happen. 
The order _should be_ `bin/rails generate migration...` -> check it -> `db:migrate` -> `db:rollback` -> `delete migration` -> `generate` -> etc.

**Comment by payne-chris-r** [comment]
Did you mean to keep destroying the migration? It looks like you have that command multiple times. What does your table look like? What do you want it to look like?

**Comment by octater** [comment]
the table looks at follows:
    create_table :games do |t|
      t.string :player_id
      t.string :game_status
      t.string :letters_played, default: ["", "", "", "", "", ""], array: true

      t.timestamps

I would like to have the letters_played changed from a array to just an integer for now

**Comment by payne-chris-r** [comment]
I mean, what does your sql table look like? Can you create a migration that changes `letters_played` type to `integer` instead?

**Comment by octater** [comment]
Let me try running a migration that just changes the column type.  I was afraid that the commands I ran before may have messed up something.  I will update this thread after I try a couple migrations.

Thanksk

**Comment by payne-chris-r** [comment]
You'll be alright. There's almost nothing you can do that we can't undo. It may come to blowing it up and starting over, but that should never be the first thought, especially with migrations. Let us know how it goes.

**Comment by octater** [comment]
I was able to alter the column on the table.  Thanks all
