### ISSUE TITLE
Can't Create Cars, tho.

### ISSUE THREAD

**Issue by andyjzhong** [ga-wdi-boston/full-stack-project#733]
Been at this for a bit and I still can't seem to get my curl request working for creating a car for my user. Each time I run the curl request below, I receive a 401 Unauthorized error (also shown below). I feel like it has something to do with user access so I tried creating a user and signing in first.  I successfully created a user and signed in but when I ran the curl request to create the car I still get this error. What am I missing? 

Please let me know if you need additional info.

Thank you!

Curl Request for Creating Cars

```sh
curl --include --request POST http://localhost:4741/cars \
  --header "Content-Type: application/json" \
  --data '{
    "car": {
      "user_id": "1",
      "make": "Mazda",
      "model": "Mazda6",
      "year": "2016",
      "color": "white"
    }
  }'
```

Error Message in Terminal:

HTTP/1.1 401 Unauthorized
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
WWW-Authenticate: Token realm="Application"
Content-Type: text/plain; charset=utf-8
Cache-Control: no-cache
X-Request-Id: f921eae2-1075-4c7d-b278-5f743e0389d7
X-Runtime: 0.018201
Vary: Origin
Transfer-Encoding: chunked

HTTP Token: Access denied.

**Comment by tvcrawley** [comment]
What is the rails server output?

**Comment by andyjzhong** [comment]
Hi Toni -- Here's what is showing in my rails server: 

Started POST "/cars" for 127.0.0.1 at 2017-04-27 13:57:18 -0400
Processing by CarsController#create as */*
  Parameters: {"car"=>{"user_id"=>"1", "make"=>"Mazda", "model"=>"Mazda6", "year"=>"2016", "color"=>"white"}}
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 0ms (Views: 0.1ms | ActiveRecord: 0.0ms)

**Comment by tvcrawley** [comment]
Could you post in the `CarsController` code?

**Comment by andyjzhong** [comment]
Sure thing! Please see below:

```rb
class CarsController < ProtectedController
  before_action :set_car, only: [:show, :update, :destroy]

  # GET /cars
  def index
    @cars = Car.all

    render json: @cars
  end

  # GET /cars/1
  def show
    render json: @car
  end

  # POST /cars
  def create
    @car = Car.new(car_params)

    if @car.save
      render json: @car, status: :created, location: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cars/1
  def update
    if @car.update(car_params)
      render json: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end

  # DELETE /cars/1
  def destroy
    @car.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def car_params
      params.require(:car).permit(:make, :model, :year, :color)
    end
end
```

**Comment by danman01** [comment]
@andyjzhong how are you authenticating that a user can be associated with a car? ApplicationController? It looks like there's some missing token at some point, or some authentication error, so I'm thinking how the signed in user needs to tell the application, "Hey I'm signed in, let me create a car with my user id!"

**Comment by andyjzhong** [comment]
Thanks Danny -- I'm still noodling your comment. I'm guessing it has something to do with maybe passing in a token in my curl request -- I think I've seen that in my notes somewhere before. Thinking back to the game project -- I do recall require a token in order to create a game. But let me know if I'm just completely off. :)

**Comment by jordanallain** [comment]
i like where you're heading @andyjzhong

**Comment by danman01** [comment]
That sounds like the right track to investigate @andyjzhong. Also if you have access to your rails server locally, you can load your rails environment and database with `bin/rails console` and take a look at your classes, try creating the same thing you are doing with your curl request, just to see if there's anything you can identify at that console level.

**Comment by andyjzhong** [comment]
I tried passing in the curl request below with the updated token line and I'm still getting the same error -- I'll try your suggestion next, Danny to look in bin/rails console.

```sh
curl --include --request POST http://localhost:4741/cars \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \
  --data '{
    "car": {
      "user_id": "1",
      "make": "Mazda",
      "model": "Mazda6",
      "year": "2016",
      "color": "white"
    }
  }'
```

**Comment by andyjzhong** [comment]
Waiiiit... Do I need to create a Token column within my cars table? Kind of grasping for straws at the moment. :\

<img width="964" alt="screen shot 2017-04-27 at 2 46 37 pm" src="https://cloud.githubusercontent.com/assets/26101294/25499098/5eb81d5a-2b58-11e7-84d7-79932ce7e91d.png">

**Comment by jordanallain** [comment]
No you don't need a token in your table. Do you  remember how you implemented the token in tic tac toe? it could be a good reminder.

**Comment by payne-chris-r** [comment]
Run a curl script for `sign-in` => should return a TOKEN.
Copy that TOKEN and use it for the subsequent curl request for when you create a car. Make sure it's the same token that you just got from the sign in!
I don't think you're sending a valid token. The curl req you posted above looks good, but you need to pass TOKEN=lksejflksejfoesufjsiuevseuofjseofijklrjfse in front of the curl script so that it can fill in `$TOKEN` with that as a command-line-variable

**Comment by payne-chris-r** [comment]
If your cars controller is inheriting from protected you need to send a *valid* token for *every* request that routes to that controller.

**Comment by andyjzhong** [comment]
I just tried running my curl script with a token passed in from one of my created users and I received a 500 error which I think stems from my other issue log regarding heroku. I'm getting the message below about running migrate but I've already run db:migrate using both bin/rails db:migrate and the heroku migrate command.

Unfortunately I've been stuck on these two issues for 3 hours now and don't feel like I've made any progress. Any chance I can meet with someone on this? Thanks.

{"status":500,"error":"Internal Server Error","exception":"#\u003cActiveRecord::PendingMigrationError: \n\nMigrations are pending. To resolve this issue, run:\n\n        bin/rails db:migrate RAILS_ENV=development\n\n\u003e"

**Comment by jordanallain** [comment]
did you close the other issue before resolving it?

**Comment by andyjzhong** [comment]
Hi Jordan -- No I got some help from Danny and Toni yesterday and we just ended up blowing away my first heroku setup and redoing it from scratch after making a quick change to my Cars model. I'm going to make another attempt at Chris' suggestion this morning for this issue.

**Comment by andyjzhong** [comment]
I had a slight diversion because I wasn't exactly sure how to generate user tokens without actually developing my sign-in functionality. Now that it's all set up (I can sign up, sign in, change password, sign out), I was able to grab a token and attempt Chris' suggestion above to pass in the token first in front of my curl script. Below is the script I attempted, which is still generating the same error.

I think what I'm going to do is just start developing the forms for creating cars on my client side similar to the way I'm handling users, but it's still unclear to me whether I would be able to make cars unique to the current user.

```
$ TOKEN='BAhJIiUwZTFhMGQwZTA5ZDNjYThjYzZkYmM2MDkzNDIxMjY5ZgY6BkVG--917fe0fe4d48c64cbfdeeab5f01d4d01de75cc3f' curl --include --request POST http://localhost:4741/cars \
>   --header "Content-Type: application/json" \
>   --header "Authorization: Token token=${TOKEN}" \
>   --data '{
>     "car": {
>       "user_id": "1",
>       "make": "Mazda",
>       "model": "Mazda6",
>       "year": "2016",
>       "color": "white"
>     }
>   }'
HTTP/1.1 401 Unauthorized
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
WWW-Authenticate: Token realm="Application"
Content-Type: text/plain; charset=utf-8
Cache-Control: no-cache
X-Request-Id: d2476869-6230-427d-a9f5-f071f5e7c951
X-Runtime: 0.003335
Vary: Origin
Transfer-Encoding: chunked

HTTP Token: Access denied.
```

**Comment by danman01** [comment]
@andyjzhong I think that's a good strategy -- put a pin in the token auth issue and go on to creating car forms. 

But to look closer at your POST, if the access is denied due to the token, then something is wrong with the token or how it is being passed or sent to authentication. If you've gone through signing in, grabbing the token, and including it, which it looks like you did, then also verify in your rails server log that the correct token was passed in, and that the params look to be what you expect.

**Comment by andyjzhong** [comment]
Ok -- placing a pin in this for now and will come back to this when I'm done creating my car form. Thanks for everyone's help so far.
