### ISSUE TITLE
status: 400, error: "Bad Request" when trying to submit new item to my issues db

### ISSUE THREAD

**Issue by jonifallon** [ga-wdi-boston/full-stack-project#737]
I have 2 tables, users and issues.  I'm trying to build the form that will allow a user to add a new issue to the issues db table.  I'm getting a 400 bad request error.

Repo URLs:

https://github.com/jonifallon/issues_client
https://github.com/jonifallon/issues_api

Html form:
`Html form:

     <form id="create-issue">

       <div class="productfield">
         <label class="fb-text-label">Application or Service</label>
         <input type="text" required="false" placeholder="Insert product name" class="form-control" name="issues[product]" id="text-product" aria-required="false"></div>

      <div class="descriptionfield"><label class="fb-textarea-label">Description<span class="fb-required"> *</span><span class="tooltip-element" tooltip="Include any known error messages">?</span></label>
           <textarea type="textarea" required="true" placeholder="Describe symptoms and/or error messages a user might encounter." class="form-control" name="issues[description]" id="textarea-description" aria-required="true"></textarea></div>

      <div class="notesfield"><label class="fb-textarea-label">Notes</label><textarea type="textarea" placeholder="Provide any known workarounds, restoration ETA, etc." class="form-control" name="issues[notes]" id="textarea-notes"></textarea></div>

      <div class="create-issue"><button type="button" class="btn btn-success" name="button-newsubmit" style="success" id="newissue">Submit</button></div>
    </form>

Browser console error when I submit the form:

	.	.	{status: 400, error: "Bad Request",…}
	.	error : "Bad Request" exception : "#<ActionController::ParameterMissing: param is missing or the value is empty: issue>" status : 400 traces : {Application Trace: [{id: 1, trace: "app/controllers/issues_controller.rb:49:in `issue_params'"},…],…}
	.	Application Trace : [{id: 1, trace: "app/controllers/issues_controller.rb:49:in `issue_params'"},…] Framework Trace : [,…] Full Trace : [,…] `

My Routes

# frozen_string_literal: true
Rails.application.routes.draw do
  resources :issues, except: [:new, :edit]
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/create-issue' => 'issues#create'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end

My issues Controller

class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :update, :destroy]

  # GET /issues
  def index
    @issues = Issue.all

    render json: @issues
  end

  # GET /issues/1
  def show
    render json: @issue
  end

  # POST /issues
  def create
    @issue = Issue.new(issue_params)

    if @issue.save
      render json: @issue, status: :created, location: @issue
    else
      render json: @issue.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /issues/1
  def update
    if @issue.update(issue_params)
      render json: @issue
    else
      render json: @issue.errors, status: :unprocessable_entity
    end
  end

  # DELETE /issues/1
  def destroy
    @issue.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def issue_params
      params.require(:issue).permit(:product, :description, :notes)
    end
end

**Comment by Jcornmanhomonoff** [comment]
It looks like you may want to revisit the error you're receiving from the browser to see what you're _missing_

**Comment by Jcornmanhomonoff** [comment]
@jonifallon status check ?

**Comment by danman01** [comment]
@jonifallon here's the error: `error : "Bad Request" exception : "#<ActionController::ParameterMissing: param is missing or the value is empty: issue>`

Double check the params that are coming in from your form submission, and how you are handling them in your controller. Also remember to check out how Rails does param permitting and whitelisting, near the bottom of the controller.

**Comment by jonifallon** [comment]
I made some changes to the form on index.html as well as the event handler.  Now I'm receiving the following error when trying to submit a new 'issue' via the form:

422 (Unprocessable Entity)
* {user: ["must exist", "can't be blank”]}

I'm authenticated when I submit the form.

The server log looks like this, where I can see the params pass, but not my user ID (not sure if I should see that or not)?

Started POST "/issues" for 127.0.0.1 at 2017-04-27 15:56:49 -0400
Processing by IssuesController#create as */*
  Parameters: {"issue"=>{"product"=>"product field", "description"=>"description field", "notes"=>"notes field"}}
   (0.2ms)  BEGIN
   (0.2ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.14ms)
* Completed 422 Unprocessable Entity in 22ms (Views: 4.0ms | ActiveRecord: 5.0ms) 

I did look at the bottom of the issues controller, and I'm passing everything it needs:

  def issue_params
      params.require(:issue).permit(:product, :description, :notes)
    end

Please help.

**Comment by jonifallon** [comment]
...and I can't find anything wrong with the serializer:

class IssueSerializer < ActiveModel::Serializer
  attributes :id, :product, :description, :notes
end

**Comment by jonifallon** [comment]
Resolved by editing my controller by adding the current_user... reference under def create.  

  def create
    @issue = current_user.issues.build(issue_params)
