### ISSUE TITLE
Commits and work flow

### ISSUE THREAD

**Issue by antleo1995** [ga-wdi-boston/full-stack-project#738]
Trying to figure out the best way to handle some of my commits without pushing all my changes immediately to master. Would it be best to do a bare bones feature and then push to master, or i was thinking of creating a new branch and merging what i have to that branch - i.e. i finished my recipe submit form and about to start on a recipe get feature. 

Additionally, I am not sure if I should build out all my CRUD stuff before getting the authenticated user feature working. by that i mean only an authenticated user being able to create a recipe and such.

**Comment by jordanallain** [comment]
It's best to only merge code into master when you know it is working correctly.

When you create a new branch it has everything from the branch you made it off of, you shouldn't need to merge anything into it.

If you have two feature branches and you merge one into master, then you would want to get those changes into the other feature branch before trying to merge that feature into master.

Does that answer any of your questions?

**Comment by BenGitsCode** [comment]
I think these are two issues @antleo1995 but they're both great things to be thinking critically about!

Feel free to open a second issue with your "additionally" bit (in fact, that might be even better in the slack forum where you can get feedback from your fellow developers on what approaches are working/not working well for them.

Do you feel better about your git workflow after the above comment?

**Comment by antleo1995** [comment]
More or less. What about best practice for the CRUD and auth stuff - get CRUD first?

**Comment by antleo1995** [comment]
I think that helps on the git question. Closing thread,.
