### ISSUE TITLE
Heroku Error

### ISSUE THREAD

**Issue by andyjzhong** [ga-wdi-boston/full-stack-project#739]
Alright -- Continuing to lead the league in issue logs.

I tried following the Rails Heroku Setup Guide and thought I followed every direction but I'm receiving an Application error below. In my terminal I'm getting a Pending Migrations error, so i tried running bin/rails db:migrate RAILS_ENV=development like it asked me to. Still no gots. I'm afraid to do anything else while this issue is up in case it messes up any of my api files.

Halp?

<img width="669" alt="screen shot 2017-04-27 at 3 13 03 pm" src="https://cloud.githubusercontent.com/assets/26101294/25500288/7656287c-2b5c-11e7-9089-f57528a09ddc.png">
<img width="966" alt="screen shot 2017-04-27 at 3 12 12 pm" src="https://cloud.githubusercontent.com/assets/26101294/25500295/7b0ab0fe-2b5c-11e7-839b-d6af329df17b.png">

**Comment by samguergen** [comment]
Are you sure you want to run the migration in a development env if you are using heroku? 
There is a special command to run your migration on heroku. Try looking it up in the Heroku docs.

**Comment by BenGitsCode** [comment]
Please use code fences and not screenshots.  https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by andyjzhong** [comment]
Ok - I ran the "heroku run rake db:migrate" command within my rails api and I'm still getting this error. Do I need to create brand new secrets after doing this?

**Comment by samguergen** [comment]
did you make sure to push your changes to heroku after running this command?

**Comment by jordanallain** [comment]
also restarting your heroku app

**Comment by andyjzhong** [comment]
After I ran my heroku run rake db:migrate, I ran git push heroku master. Then I restarted my heroku by running "heroku restart" and "heroku open." Still have the same error. Thanks for the help so far -- I def appreciate it.

**Comment by samguergen** [comment]
have you tried running bin/rails db:migrate by itself? close and reopening the terminal window after stopping the server? Made sure there were no syntax errors in your migrations, and that they work locally?

**Comment by andyjzhong** [comment]
When I ran my bin/rails db:migrate command by themselves -- I got the error below that says my tables already exist........?

$ bin/rails db:migrate
== 30 CreateCars: migrating ===================================================
-- create_table(:cars)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "cars" already exists
: CREATE TABLE "cars" ("id" serial primary key, "user_id" integer NOT NULL, "make" character varying, "model" character varying, "year" integer, "color" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
/Users/andy/wdi/projects/full-stack-project-directory/full-stack-project-api/db/migrate/030_create_cars.rb:3:in `change'
/Users/andy/wdi/projects/full-stack-project-directory/full-stack-project-api/bin/rails:9:in `require'
/Users/andy/wdi/projects/full-stack-project-directory/full-stack-project-api/bin/rails:9:in `<top (required)>'
/Users/andy/wdi/projects/full-stack-project-directory/full-stack-project-api/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "cars" already exists
: CREATE TABLE "cars" ("id" serial primary key, "user_id" integer NOT NULL, "make" character varying, "model" character varying, "year" integer, "color" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
/Users/andy/wdi/projects/full-stack-project-directory/full-stack-project-api/db/migrate/030_create_cars.rb:3:in `change'
/Users/andy/wdi/projects/full-stack-project-directory/full-stack-project-api/bin/rails:9:in `require'
/Users/andy/wdi/projects/full-stack-project-directory/full-stack-project-api/bin/rails:9:in `<top (required)>'
/Users/andy/wdi/projects/full-stack-project-directory/full-stack-project-api/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
PG::DuplicateTable: ERROR:  relation "cars" already exists
/Users/andy/wdi/projects/full-stack-project-directory/full-stack-project-api/db/migrate/030_create_cars.rb:3:in `change'
/Users/andy/wdi/projects/full-stack-project-directory/full-stack-project-api/bin/rails:9:in `require'
/Users/andy/wdi/projects/full-stack-project-directory/full-stack-project-api/bin/rails:9:in `<top (required)>'
/Users/andy/wdi/projects/full-stack-project-directory/full-stack-project-api/bin/spring:15:in `<top (required)>'

**Comment by andyjzhong** [comment]
I'm not sure if it has anything to do with me having renamed my migrate file for cars.

db/migrate/030_create_cars.rb (whereas before I changed it to 030, it was an auto-generated timestamp.

**Comment by andyjzhong** [comment]
Thanks Toni and Danny -- I had an error in my Cars model where it was keying off ActiveRecord instead of ApplicationRecord. I went through the Heroku guide once more after and it seemed to work for me. Thank you!
