### ISSUE TITLE
Search function works with ajax request. Struggling with calling the data to update HTML

### ISSUE THREAD

**Issue by baz1389** [ga-wdi-boston/full-stack-project#74]
I am able to search for a specific word with my searchWord Ajax method. The DOM displays the following:

```
Object {words: Array[1]}
words: Array[1]
0: Object
created_at: "2015-11-11T15:26:34.019Z"
definition: "the usually round, red, green, or yellow, edible fruit of a small tree."
id: 4
name: "apple"
sample_sentence: "This is a shiny red apple"
updated_at: "2015-11-11T21:01:30.622Z"
user_id: 15
__proto__: Object
length: 1
__proto__: Array[0]
__proto__: Object
```

Ajax Method:

```
searchWord: function (name, token, callback) {
    this.ajax({
      method: 'GET',
      url: this.mwb + '/words' + '?name=' + name,
      headers: {
        Authorization: 'Token token=' + token
      },
      dataType: 'json'
    }, callback);
  }
```

jquery:

```
$('#search').on('submit', function(e) {
    var token = user.token;
    var name = form2object(this).word;
    mwbapi.searchWord(name, token, function(err, data) {
      if (err) {
        console.error(err);
        return;
      }
      console.log(data);
    });
    e.preventDefault();

  });
```

My problem is that I'm not quite sure how to call the information that is returned from the ajax request to update the word, definition, and sentence in my HTML.

**Comment by tdyer** [comment]
The info returned from the server, via the ajax request, will be the data in the anonymous function passed to mwbapi.search.

$('#search').on('submit', function(e) {
    var token = user.token;
    var name = form2object(this).word;
    mwbapi.searchWord(name, token, function(err, data) {
      if (err) {
        console.error(err);
        return;
      }

```
 // data contains the results of the search request!!
  console.log(data);

// Use this data when you build and display the HTML in the page.
});
e.preventDefault();
```

  });

**Comment by baz1389** [comment]
So will I need to add data as an argument into my searchWord method too?

**Comment by tdyer** [comment]
Nope, come see me in the dugout.

**Comment by tdyer** [comment]
OK, Ben understands that he needs to use the data returned from the server to build HTML and put it on his page.
