### ISSUE TITLE
Workflow - CRUD v authenticated user

### ISSUE THREAD

**Issue by antleo1995** [ga-wdi-boston/full-stack-project#740]
Trying to decide should I work on getting CRUD working first - or add authenticated user to the CRUD process as I go.

**Comment by BenGitsCode** [comment]
What's factoring in either side of the decision? What sounds like it makes the most sense to you?

**Comment by antleo1995** [comment]
Most comfortable with the basic CRUD functions, but was afraid I might code myself into a corner as I am not very familiar. Seemed easy enough but just trying not to waste time.

**Comment by antleo1995** [comment]
I already have a working post function.

**Comment by antleo1995** [comment]
Moving on....
