### ISSUE TITLE
how do I write curl and ajax query parameters

### ISSUE THREAD

**Issue by gastevend** [ga-wdi-boston/full-stack-project#741]
Hey guys,

I have been thrashing a little bit here. 

I have a table in my database called user_songs which is my join table which joins users and songs through it. 

On this table I have three columns including the primary id key. Id, user_id, and song_id.

One of my states in the UI is to show all of the songs that belong to the user requesting them. so what i am trying to do is query the user_songs table where a user_id is foo. I am trying to create my curl requests to get the correct response back from the table but i cant seem to figure out how to pass parameters on a get request.

It makes sense to me to pass data on POST and PATCH request as you are using that data to update the table row. I tried to pass an JSON object with the data option set to the parameters I think would work but that is still bringing back the whole table. 

After googling curl and ajax parameters and looking at the game project api README. I also tried to pass parameters straight to the url of the get request with a /?param but that also is pulling everything back.

i also cant pass a /:id into the url of the get request because that would just bring back the primary user_songs id and not the specific users id.

also realize i could probably get all and then filter on the front end but that seems kind of wasteful

**Comment by jordanallain** [comment]
one thing at a time. lets get a curl to your url working and worry about ajax later.

what does your curl request look like?

what is the response? is it an error?

**Comment by gastevend** [comment]
No errors. response is 200 ok with the whole table coming back

curl requests i have tried:
```sh
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/user_songs"
curl "${API}${URL_PATH}" \
  --include \
  --request GET
  --data '{
    "user_songs": {
      "user_id": "1"
    }
  }'

# also (tried this format because this is how my response is formatted coming back

--data '{
    "user_songs": {
      "user": {
        "id": "1"
      }
    }
  }'
```
```sh
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/user_songs/?user_id=1"  # also "/user_songs?user_id=1" and "/user_songs[user_id=1]"
curl "${API}${URL_PATH}" \
  --include \
  --request GET
```

**Comment by jordanallain** [comment]
You might want to check back to previous GET requests you made. How did you do a GET request for retrieving user stats in tic tac toe?

**Comment by gastevend** [comment]
I got all and filtered on the front end :'(

**Comment by jordanallain** [comment]
So if you want to handle it on the back end, do you have a route set up with an action that defines what happens when that route is hit?

**Comment by gastevend** [comment]
Oh like a manual nonRESTFUL route?

**Comment by jordanallain** [comment]
It can still follow RESTful guidelines, but it still needs a route

**Comment by jordanallain** [comment]
Updates @gastevend ?

**Comment by gastevend** [comment]
Sorry about that. solution to my issue at a high level was to write a custom route specifically for looking for a users songs and in the controller using the current_user variable to retrieve their songs from the user_songs table. I pass the user_table the users token in the get request and let current_user do the rest
