### ISSUE TITLE
I am in GitHub hell.. please help with a quick face-to-face

### ISSUE THREAD

**Issue by octater** [ga-wdi-boston/full-stack-project#742]
I had a merge conflict and that didn't seem to be correct.  I followed the recommended steps but now when I got to  https://github.com/octater/hangman-rails-api, is says that my working branch is 2 commits behind master.  Before I get too along, I would like a quick 1-to-1 to review my git commands and repository.

Here are the steps I am doing

  545  git status
  546  git add ****
  573  git status
  574  git commit
  575  git status
  576  git push origin working
  577  git checkout master
  578  git merge working
  579  git push origin master
  581  git push heroku master
  586  heroku run rake db:migrate
  587  heroku run rake db:seed
  588  heroku restart
  584  heroku open

**Comment by BenGitsCode** [comment]
Let's git it on Terry.

**Comment by octater** [comment]
Thanks so much Ben for your help.   The issue was that I did a commit before fixing the merge conflict, not good.  I was able to fix the merge conflict and now GitHub looks good.
