### ISSUE TITLE
Editable method in my serializer is not working

### ISSUE THREAD

**Issue by jim-moody** [ga-wdi-boston/full-stack-project#743]
I am trying to take advantage of the "editable" method that I saw in the Examples serializer so I can determine if I should show/hide an Edit/Delete button in my client, but it does not appear to be working correctly.

When I sign in with a user and create a new message, it does return editable=true which is correct.

But then if I refresh the page and sign in with that user again, all the messages in the database come back with editable=false which is incorrect because at least one of them belongs to that user.

Serializer:
```ruby
class LineSerializer < ActiveModel::Serializer
  attributes :id, :text, :editable

  def editable
    scope == object.user
  end
end
```

Response from API on POST:
```js
Object {id: 30, text: "new line 2", editable: true}
```

Response from API on INDEX after logging in with same user that created above message:
```js
Object {id: 30, text: "new line 2", editable: false}
```

**Comment by sdavidson140** [comment]
where are you setting the value of editable?

**Comment by jim-moody** [comment]
I figured out the issue...

I wasn't passing the token into my `index` api call

Before:
```js
const listLines = () => {
  return $.ajax({
    url: config.apiOrigin + '/lines',
    method: 'GET'
  })
}
```

After:
```js
const listLines = () => {
  const token = store.user && store.user.token || ''
  return $.ajax({
    url: config.apiOrigin + '/lines',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + token
    }
  })
}
```
