### ISSUE TITLE
Unable to successfully PATCH 

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/full-stack-project#744]
Hi,
I am having some trouble deciphering where my error is when doing a patch curl request. 

The curl requests:
```
curl --include --request PATCH http://localhost:4741/reviews/1 \
  --header "Content-Type: application/json" \
  --data '{
    "reviews": {
      "review_date": "2017-04-27",
      "review_text": "John Smith is a great tipper"
    }
  }'

  API="${API_ORIGIN:-http://localhost:4741}"
  URL_PATH="/reviews"
  curl "${API}${URL_PATH}/${ID}" \
    --include \
    --request PATCH \
    --header "Content-Type: application/json" \
    --data '{
      "reviews": {
        "review_date": "27-04-2017",
        "review_text": "John Smith is great tipper"
      }
    }'
```
The error I get is:
![screen shot 2017-04-27 at 4 25 21 pm](https://cloud.githubusercontent.com/assets/25780850/25503013/ce113566-2b66-11e7-873b-37c4d70e51b3.png)

The code that the error is referencing:

```  def update
    if @review.update(review_params)
      head :no_content
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end

  def review_params
    params.require(:review).permit(:review_date, :review_text)
  end
```

I have reviewed all of the code from the labs and code alongs and my reviews code is the same as what I have in my patients and doctors, I really can't figure out why the params is not being not being passed to the update method.

Thanks!

ps. all of my other curl requests are working.

**Comment by scottyscripts** [comment]
make sure the params you are sending are the ones that are being required in your controller

**Comment by awoodrum87** [comment]
@sdavidson140 not sure what you mean..

**Comment by scottyscripts** [comment]
take a closer look at your error message. especially the last two lines

**Comment by scottyscripts** [comment]
and look at the params that you are requiring in your controller

**Comment by awoodrum87** [comment]
i've looked closely at both for a while now. still not making the connection. this is modeled verbatim (minus the review vs doctor/patient) from my lab and code along code and that works.

**Comment by lisamsmith100** [comment]
I'm having a similar issue.  my curl requests are great.  my ajax not so much. I'm watching this.

**Comment by awoodrum87** [comment]
the issue was in my curl request. I require review (singular) in the controller and was passing reviews plural in my curl request. Here is the cool request that works:

```  API="${API_ORIGIN:-http://localhost:4741}"
  URL_PATH="/reviews"
  curl "${API}${URL_PATH}/${ID}" \
    --include \
    --request PATCH \
    --header "Content-Type: application/json" \
    --data '{
      "reviews": {
        "review_date": "27-04-2017",
        "review_text": "John Smith is great tipper"
      }
    }'
```
