### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by MattKwonDo** [ga-wdi-boston/full-stack-project#746]
I am getting a 401 Unauthorized error when I try to run the users script from the command line, which seems like it has to do with my token, but not sure how to resolve it. 

In my .env file I have three tokens:
SECRET_KEY_BASE_TEST
SECRET_KEY_BASE_DEVELOPMENT
SECRET_TOKEN

The contents of the users script:
``` sh
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/users"
curl "${API}${URL_PATH}" \
  --include \
  --request GET \
  --header "Authorization: Token token=$TOKEN"

echo
```

the error from server:
```
Started GET "/users" for 127.0.0.1 at 2017-04-27 17:41:44 -0400
Processing by UsersController#index as */*
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 0ms (Views: 0.1ms | ActiveRecord: 0.0ms)
```

the response in terminal
```
HTTP/1.1 401 Unauthorized
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
WWW-Authenticate: Token realm="Application"
Content-Type: text/plain; charset=utf-8
Cache-Control: no-cache
X-Request-Id: dd92d6a3-12d7-42b4-a262-8d6a28382c65
X-Runtime: 0.004049
Vary: Origin
Transfer-Encoding: chunked

HTTP Token: Access denied.
```

Thanks!

**Comment by jordanallain** [comment]
Is there a reason you are trying to get all the users?

**Comment by MattKwonDo** [comment]
just to make sure I can get them

**Comment by jordanallain** [comment]
is it part of the functionality of your app that other users should be able to look at a list of all the users?

**Comment by MattKwonDo** [comment]
no. ok, sounds like I don't need to do that. but should I be able to?

**Comment by jordanallain** [comment]
i believe you would have edit the users controller in the api for you to be able to.

**Comment by MattKwonDo** [comment]
Ok, thanks!
