### ISSUE TITLE
Question on migration file

### ISSUE THREAD

**Issue by lisamsmith100** [ga-wdi-boston/full-stack-project#749]
Hi,
I have a question(s) re: migration files.  Been staring at it a bit already and need an answer to questions.

I had written down instructions to re-migrate and did so and retrospectively did not need to so I have an empty migration file.  

Question(s): Is there any harm in this or do I need to take any action to prevent it from having adverse effects on my migration file add_user_to_entries.rb?

Here is the entry.rb
```rb
# frozen_string_literal: true

class CreateEntries < ActiveRecord::Migration[5.0]
  def change
    create_table :entries do |t|
      t.string :title
      t.string :backstory
      t.string :stopper
      t.string :status
      t.timestamp :date_added
      t.boolean :deleted_flag

      t.timestamps
    end
  end
end

```
here is the useless migration file
```rb
# frozen_string_literal: true

class Entry < ActiveRecord::Migration[5.0]
  def change
  end
end
```

and lastly here is my migration file adding the user_id to entries
```rb
# frozen_string_literal: true

class AddUserToEntries < ActiveRecord::Migration[5.0]
  def change
    add_reference :entries, :user, foreign_key: true
  end
end

```
Thank you.

**Comment by scottyscripts** [comment]
is there already a migration for Entry? What is creating that table in the database when you migrate?

**Comment by lisamsmith100** [comment]
I scaffolded already but thought I had to do a second generate migration based on my notes from demo.  Can I update that second empty migration file?
Thanks.

**Comment by scottyscripts** [comment]
Is there another migration file besides the empty one for Entry? If not, you can update that file then migrate again to update your schema

**Comment by lisamsmith100** [comment]
Hello Scott,

The migration files I have are

001_create_users.rb
002_create_examples.rb
20170427145333_create_entries.rb
20170427152910_entry.rb
and
20170428024913_add_user_to_entries.rb

So are my next steps to…

Copy the code in create_entries.rb
Paste into entry.rb
Then generate migration for entry
Then db:migrate again
Then generate migration for add_user_to_entries.rb,
Then db:migrate?

Thank you for the clarification.

**Comment by scottyscripts** [comment]
If you already have the code in create_entries to create the entries table, and the empty file currently does nothing, do you even still need the empty one?

**Comment by lisamsmith100** [comment]
I don’t think I need it.  I’d like to delete it.  OK to proceed with deleting?
Thanks!

**Comment by scottyscripts** [comment]
I think you're right that you don't need it!

**Comment by lisamsmith100** [comment]
If it's not going to conflict with any other migrations or files, I'll leave it as is and ignore it (but not delete).  Thank you!

**Comment by scottyscripts** [comment]
Probably best to get rid of it now while it's still fresh and so it won't cause any conflicts down the road!

**Comment by lisamsmith100** [comment]
The migration file was useless and so I ran the following command in the shell.  Closing this issue.
```sh
bin/rails destroy migration Entry
```
