### ISSUE TITLE
Git Happens

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/full-stack-project#752]
From my full-stack-project-api:
I can add, commit, and push from my feature branch.
When I checkout my master and try to merge my feature with master I get:
fatal: refusing to merge unrelated histories. 

From my full-stack-project-client:
I cannot merge to master because there is a merge conflict in the readme

Toni and I worked on this yesterday and we got both of my repos to push from master, so I am unsure why there is still a disconnect from feature and master. We reconciled the differences in the readme in both repos

**Comment by jordanallain** [comment]
if you had branched off of master previously the histories might not line up now. you may have commits on the master branch that aren't there on your feature branch.

**Comment by awoodrum87** [comment]
and now when I try to checkout out my feature in my client directory I get this error:
$ git checkout feature
README.md: needs merge
assets/scripts/config.js: needs merge
assets/scripts/index.js: needs merge
index.html: needs merge
error: you need to resolve your current index first
~/wdi/projects/full-stack-client (master)

**Comment by awoodrum87** [comment]
I ran `git merge --abort` and was able to checkout to my feature branch, but I still have merge conflicts when I try to merge them.

**Comment by awoodrum87** [comment]
I have followed these instructions (which is basically what Toni and I did yesterday), specifically the Competing line change merge conflicts section: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/
and got the following errors and messages: 
<img width="685" alt="screen shot 2017-04-28 at 10 08 31 am" src="https://cloud.githubusercontent.com/assets/25780850/25532253/c3d3299e-2bfa-11e7-80a0-aee889a91f94.png">

**Comment by awoodrum87** [comment]
Thanks @jordanallain and @sdavidson140 
We resolved this by using commands to force everything on my feature branch to be on the master and remote and now we seem to be golden. :D

**Comment by awoodrum87** [comment]
so, i am getting the same errors as I was last week. Can I get some help getting my git on track? I would like to deploy and am unable to because of the merge issues.

**Comment by awoodrum87** [comment]
more deets:
when I `git push origin feature` from my full stack client repo I get the following error
```~/wdi/projects/full-stack-client (feature)
$ git push origin feature
To https://github.com/awoodrum87/angies-other-list-client
 ! [rejected]        feature -> feature (non-fast-forward)
error: failed to push some refs to 'https://github.com/awoodrum87/angies-other-list-client'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
```

I can push from my full stack api repo (feature branch), but cannot merge to master.

**Comment by scottyscripts** [comment]
take a look at the last line of that error message you got when pushing. Have you tried to pull before pushing?

**Comment by tvcrawley** [comment]
update?

**Comment by awoodrum87** [comment]
I want to follow these directions to not annihilate my local repo (i have a TON of code)
http://stackoverflow.com/questions/19216411/how-do-i-pull-files-from-remote-without-overwriting-local-files
when I run `git stash` I get `no local changes to save` I assume because I have committed (?).
I just want to make sure I don't mess up what I have locally because I have tons of code.

**Comment by awoodrum87** [comment]
I have tried the pull, then tried to resolve readme conflicts. :/
```
~/wdi/projects/full-stack-client (feature)
$ git pull https://github.com/awoodrum87/angies-other-list-client feature
From https://github.com/awoodrum87/angies-other-list-client
 * branch            feature    -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: Initial commit
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
error: Failed to merge in the changes.
Patch failed at 0001 Initial commit
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

~/wdi/projects/full-stack-client 
$ atom README.md
~/wdi/projects/full-stack-client 
$ git rebase --continue
README.md: needs merge
You must edit all merge conflicts and then
mark them as resolved using git add
~/wdi/projects/full-stack-client 
$ git add README.md 
~/wdi/projects/full-stack-client 
$ git rebase --continue
Applying: Initial commit
Applying: commiting for a test deploy
Using index info to reconstruct a base tree...
M	README.md
Falling back to patching base and 3-way merge...
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
error: Failed to merge in the changes.
Patch failed at 0002 commiting for a test deploy
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

~/wdi/projects/full-stack-client 
$ git commit README.md 
[detached HEAD 6455cca] PLEASE PLEASE COMMIT
 1 file changed, 12 insertions(+)
~/wdi/projects/full-stack-client 
$ git rebase --continue
Applying: commiting for a test deploy
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

~/wdi/projects/full-stack-client 
$ git push origin feature
To https://github.com/awoodrum87/angies-other-list-client
 ! [rejected]        feature -> feature (non-fast-forward)
error: failed to push some refs to 'https://github.com/awoodrum87/angies-other-list-client'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~/wdi/projects/full-stack-client 
$ 
```

**Comment by awoodrum87** [comment]
many thanks to @tvlangley for the assistance (again).
My remote head appeared to be many commits behind causing merge conflicts. We seem to have all of the branches reconciled and able to deploy.
