### ISSUE TITLE
I have a CRUD machine. Now what?

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/full-stack-project#753]
Here is my ERD:
![img_20170424_182214](https://cloud.githubusercontent.com/assets/25780850/25531721/affa5250-2bf8-11e7-887d-968b9943f895.jpg)

I am having trouble, conceptually, with the next steps. I have created my DBs and have working curl requests to my users and reviews (yay!). I wireframed my application to have a 'create reviewer profile' hence the reviewers table. What I don't understand moving forward is, when a user logs in, then creates a profile, do the references automatically get created in the DB? when the user logs in, will he need to then login again to his reviewer profile to make a review? I am starting to think that dropping the join table reviewers and just having a one to many users to reviews may be easiest. But I know the correct way to do it is through the reviewers table. HALLPPP

**Comment by scottyscripts** [comment]
We have to define references between foreign keys in our migrations. If you defined these references, then when a user creates a profile, these tables will be linked by user id. 
There is no right or wrong way of doing this! Looking at your ERD though, I don't see the benefit a user would get from creating a reviewer profile. The only thing their profile has that the user doesn't have is an industry. If that is the case, you need to ask yourself if users really NEED a reviewer profile.

**Comment by awoodrum87** [comment]
ok, so here is my next question. The users table was predefined for us, can i modify that? I want industry to be in there

**Comment by scottyscripts** [comment]
You can absolutely modify it! You can run a migration to add a column(s) to the user table.

**Comment by awoodrum87** [comment]
Thanks @sdavidson140 ! I'm going to have a think and make some decisions.

**Comment by awoodrum87** [comment]
Hey @sdavidson140 ,

I have decided to modify my users table (complete) and drop the reviewers table. I want to do a drop table migration. Is this the best way to do this? I haven't added any data to that table, but I did create it via a migration and thus all the subsequent code exists. I used this overstack issue: http://stackoverflow.com/questions/4020131/rails-db-migration-how-to-drop-a-table to create this code:
```
class DropReviewersTable < ActiveRecord::Migration[5.0]
  def change
    drop_table :reviewers do |t|
      t.string :username, null: false
      t.string :industry
      t.datetime :created_at, null: false
      t.datetime :updated_at, null: false
    end
  end
end
```

should I just run this and see if it works? I really don't want to get myself in a position where I have to start over with my database work.

**Comment by awoodrum87** [comment]
I got impatient and tried it anyway. Got this error. 

```
$ rake db:migrate
== 20170428152000 DropReviewersTable: migrating ===============================
-- drop_table(:reviewers)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DependentObjectsStillExist: ERROR:  cannot drop table reviewers because other objects depend on it
DETAIL:  constraint fk_rails_007031d9cb on table reviews depends on table reviewers
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
: DROP TABLE "reviewers"
/Users/angelawoodrum/wdi/projects/full-stack-api/db/migrate/20170428152000_drop_reviewers_table.rb:3:in `change'
ActiveRecord::StatementInvalid: PG::DependentObjectsStillExist: ERROR:  cannot drop table reviewers because other objects depend on it
DETAIL:  constraint fk_rails_007031d9cb on table reviews depends on table reviewers
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
: DROP TABLE "reviewers"
/Users/angelawoodrum/wdi/projects/full-stack-api/db/migrate/20170428152000_drop_reviewers_table.rb:3:in `change'
PG::DependentObjectsStillExist: ERROR:  cannot drop table reviewers because other objects depend on it
DETAIL:  constraint fk_rails_007031d9cb on table reviews depends on table reviewers
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
/Users/angelawoodrum/wdi/projects/full-stack-api/db/migrate/20170428152000_drop_reviewers_table.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by scottyscripts** [comment]
@awoodrum87 You need to rollback you db if you already ran the migration

**Comment by awoodrum87** [comment]
@sdavidson140 and I took my code back to where it was yesterday and dropped the db and ran the migrations again. Now it is in the working state I need to move forward.

**Comment by awoodrum87** [comment]
OK @payne-chris-r , I've worked through some of what you gave me to think on
1. What gets returned on sign-on?
A. the user object specifically the user_id, email, and token
Conclusion: I need the user_id in my reviewers table. That is how I will tie the review, to the reviewer, to the user. I added a reference to the user id in rails and ran all the commands and now the schema is updated and that is good. 

2. How do I get the reviewer based on that what is returned in the user object?
A. the user_id!

3. Can I modify the sign in serializer to make my life easier. 
A. maybe? The sign in serializer only shows the email, id, and token, rather than all the data the user has associated with such as password and the datetime fields. rather than modify it, use it as a model form my reviewers serializer??

4. How do I see a user's ...reviews. 
A. I'm kind of spinning my wheels on this one. I know I see the reviews (of User 1) by working backwards through my ERD review_id (in reviews table)<user_id(reference in the reviewers table)

**Comment by payne-chris-r** [comment]
Can you post the sign-in serializer code?

**Comment by awoodrum87** [comment]
yep. here you go,
```
class UserLoginSerializer < ActiveModel::Serializer
  attributes :id, :email, :token

  def token
    Rails.application.message_verifier(:signed_token).generate(object.token)
  end
end
```

**Comment by payne-chris-r** [comment]
```diff
class UserLoginSerializer < ActiveModel::Serializer
-  attributes :id, :email, :token
+  attributes :id, :email, :token, :profile_id
  def token
    Rails.application.message_verifier(:signed_token).generate(object.token)
  end
end
```

**Comment by payne-chris-r** [comment]
Updates @awoodrum87 ?

**Comment by awoodrum87** [comment]
Apologies, @payne-chris-r 
Per our discussions yesterday, I am going to close this. I have my DB setup with the users -reviewers > reviews and am going to move forward with that.

**Comment by awoodrum87** [comment]
I'm soooo close I can taste it. I cannot create a review from my UI. I am able to do it via a curl request. 
I get the 500 undefined method error, telling me my current_user is nil (or empty). I don't understand why it is empty. I have followed Issue #771  pretty closely and it isn't getting where I need to be. 

here is the relevant code:

review model:
```
class Review < ApplicationRecord
  belongs_to :reviewer, foreign_key: 'reviewer_id'
  validates :reviewer
end
```
create method in the controller (where the undefined or nil current_user resides)
```
  def create
    @review = current_user.reviews.build(review_params)
    # @review = Review.new(review_params)

    if @review.save
      render json: @review, status: :created
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
```
review serializer:
```
class ReviewSerializer < ActiveModel::Serializer
  attributes :id, :review_date, :review_text, :reviewer
end
```

**Comment by payne-chris-r** [comment]
I haven't even read this yet, but working at 3:30am is prrrrobably a bad idea...

**Comment by awoodrum87** [comment]
Ha. Good looking out! It wasn't planned, I just couldn't sleep so I decided to take a peek at my code :)

**Comment by payne-chris-r** [comment]
I'm confused.
RE: "I cannot create a review from my UI. I am able to do it via a curl request." typically means that we should be looking in the client, not in the API. However, getting a 500, `undefined method 'reveiws'`from the api sounds like you're right that the api IS the problem. Can you confirm that the curl request is working (if it in fact is) and post that curl request here?

**Comment by awoodrum87** [comment]
apparently I lied. My curl request no longer works. 👎 I get the 500 error

**Comment by payne-chris-r** [comment]
I didn't think so. ☹️

**Comment by payne-chris-r** [comment]
So what does `500, undefined method 'reviews'` mean? What is the full error?

**Comment by awoodrum87** [comment]
The error is:
```{"status":500,"error":"Internal Server Error","exception":"#\u003cNoMethodError: undefined method `reviews' for nil:NilClass\u003e","traces":{"Application Trace":[{"id":0,"trace":"app/controllers/reviews_controller.rb:18:in `create'"}]```

line 18 that is working is the line `@review = current_user.reviews.build(review_params)` in the following function:
```
  def create
    @review = current_user.reviews.build(review_params)
    # @review = Review.new(review_params)

    if @review.save
      render json: @review, status: :created
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
```

I've gathered that it reads current_user as nil, but I don't understand why. the reviewers to reviews is a 1:many relationship.

**Comment by payne-chris-r** [comment]
Yeah, you're getting ahead of yourself though. If current user isn't defined, why isn't it defined? How do we set current_user? What needs to be sent with the request in order to establish which user is the `current_user`?

**Comment by awoodrum87** [comment]
I seem to have gotten this to work. I was having trouble chaining everything together so that I could get the reviewer_id associated with current_user. I remedied this by fixing the reviewers model to:

```
class Reviewer < ApplicationRecord
  belongs_to :user
  has_many :reviews
end
```

and then fixing the create method in reviews controller to:
```
def create
    @review = current_user.reviewer.reviews.build(review_params)
    if @review.save
      render json: @review, status: :created
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
```
thanks for the breadcrumbs! it took a while but I pieced it together.
