### ISSUE TITLE
Client repo stuck in gh-pages branch

### ISSUE THREAD

**Issue by rrdaniels85** [ga-wdi-boston/full-stack-project#755]
I was deploying from my master branch and something went wrong with the deploy (I think it may not have completed) and now I am stuck in my gh-pages branch of the client repo. It doesn't let me checkout the master again because during the incomplete deploy a bunch of files were somehow created. I was hoping for some guidance on how to proceed as I am cautious about messing with anything involving the gh-pages branch.

**Comment by payne-chris-r** [comment]
Can you post the output from your terminal?

**Comment by rrdaniels85** [comment]
I also should add that before the deploy got hung for like 5 minutes and wouldn't proceed so I control C ^ out and then the following occurred:    [9] ./lib/get-form-fields.js 960 bytes {0} [built]
       cjs require ../../../lib/get-form-fields [8] ./assets/scripts/auth/events.js 3:20-59
       cjs require ../../../lib/get-form-fields [13] ./assets/scripts/goals/events.js 3:20-59
  [10] ./assets/scripts/auth/api.js 1.08 kB {0} [built]
       cjs require ./api [8] ./assets/scripts/auth/events.js 5:10-26
  [11] ./assets/scripts/store.js 55 bytes {0} [built]
       cjs require ../store [10] ./assets/scripts/auth/api.js 4:12-31
       cjs require ../store.js [12] ./assets/scripts/auth/ui.js 3:12-34
       cjs require ../store [14] ./assets/scripts/goals/api.js 4:12-31
       cjs require ../store.js [15] ./assets/scripts/goals/ui.js 3:12-34
  [12] ./assets/scripts/auth/ui.js 1.16 kB {0} [built]
       cjs require ./ui [8] ./assets/scripts/auth/events.js 6:9-24
  [13] ./assets/scripts/goals/events.js 1.53 kB {0} [built]
       cjs require ./goals/events.js [1] ./assets/scripts/index.js 17:17-45
  [14] ./assets/scripts/goals/api.js 1.08 kB {0} [built]
       cjs require ./api [13] ./assets/scripts/goals/events.js 5:10-26
  [15] ./assets/scripts/goals/ui.js 1.48 kB {0} [built]
       cjs require ./ui [13] ./assets/scripts/goals/events.js 6:9-24
  [16] ./assets/scripts/templates/goal-listing.handlebars 5.69 kB {0} [built]
       cjs require ../templates/goal-listing.handlebars [15] ./assets/scripts/goals/ui.js 4:24-71
  [17] ./~/handlebars/runtime.js 167 bytes {0} [built]
       cjs require /Users/rrdaniels/wdi/projects/bucketlist-client/node_modules/handlebars/runtime.js [16] ./assets/scripts/templates/goal-listing.handlebars 1:17-110
  [18] ./~/handlebars/dist/cjs/handlebars.runtime.js 4.59 kB {0} [built]
       cjs require ./dist/cjs/handlebars.runtime [17] ./~/handlebars/runtime.js 3:17-57
  [19] ./~/handlebars/dist/cjs/handlebars/base.js 8.38 kB {0} [built]
       cjs require ./handlebars/base [18] ./~/handlebars/dist/cjs/handlebars.runtime.js 12:22-50
       cjs require ./base [34] ./~/handlebars/dist/cjs/handlebars/runtime.js 26:12-29
  [20] ./~/handlebars/dist/cjs/handlebars/utils.js 10.2 kB {0} [built]
       cjs require ./handlebars/utils [18] ./~/handlebars/dist/cjs/handlebars.runtime.js 27:23-52
       cjs require ./utils [19] ./~/handlebars/dist/cjs/handlebars/base.js 9:13-31
       cjs require ../utils [23] ./~/handlebars/dist/cjs/handlebars/helpers/block-helper-missing.js 5:13-32
       cjs require ../utils [24] ./~/handlebars/dist/cjs/handlebars/helpers/each.js 8:13-32
       cjs require ../utils [26] ./~/handlebars/dist/cjs/handlebars/helpers/if.js 5:13-32
       cjs require ../utils [29] ./~/handlebars/dist/cjs/handlebars/helpers/with.js 5:13-32
       cjs require ../utils [31] ./~/handlebars/dist/cjs/handlebars/decorators/inline.js 5:13-32
       cjs require ./utils [32] ./~/handlebars/dist/cjs/handlebars/logger.js 5:13-31
       cjs require ./utils [34] ./~/handlebars/dist/cjs/handlebars/runtime.js 18:13-31
  [21] ./~/handlebars/dist/cjs/handlebars/exception.js 4.58 kB {0} [built]
       cjs require ./handlebars/exception [18] ./~/handlebars/dist/cjs/handlebars.runtime.js 23:27-60
       cjs require ./exception [19] ./~/handlebars/dist/cjs/handlebars/base.js 11:17-39
       cjs require ../exception [24] ./~/handlebars/dist/cjs/handlebars/helpers/each.js 10:17-40
       cjs require ../exception [25] ./~/handlebars/dist/cjs/handlebars/helpers/helper-missing.js 8:17-40
       cjs require ./exception [34] ./~/handlebars/dist/cjs/handlebars/runtime.js 22:17-39
  [22] ./~/handlebars/dist/cjs/handlebars/helpers.js 2.91 kB {0} [built]
       cjs require ./helpers [19] ./~/handlebars/dist/cjs/handlebars/base.js 15:15-35
  [23] ./~/handlebars/dist/cjs/handlebars/helpers/block-helper-missing.js 3.77 kB {0} [built]
       cjs require ./helpers/block-helper-missing [22] ./~/handlebars/dist/cjs/handlebars/helpers.js 9:33-74
  [24] ./~/handlebars/dist/cjs/handlebars/helpers/each.js 8.1 kB {0} [built]
       cjs require ./helpers/each [22] ./~/handlebars/dist/cjs/handlebars/helpers.js 13:19-44
  [25] ./~/handlebars/dist/cjs/handlebars/helpers/helper-missing.js 1.98 kB {0} [built]
       cjs require ./helpers/helper-missing [22] ./~/handlebars/dist/cjs/handlebars/helpers.js 17:28-63
  [26] ./~/handlebars/dist/cjs/handlebars/helpers/if.js 3.33 kB {0} [built]
       cjs require ./helpers/if [22] ./~/handlebars/dist/cjs/handlebars/helpers.js 21:17-40
  [27] ./~/handlebars/dist/cjs/handlebars/helpers/log.js 2.5 kB {0} [built]
       cjs require ./helpers/log [22] ./~/handlebars/dist/cjs/handlebars/helpers.js 25:18-42
  [28] ./~/handlebars/dist/cjs/handlebars/helpers/lookup.js 846 bytes {0} [built]
       cjs require ./helpers/lookup [22] ./~/handlebars/dist/cjs/handlebars/helpers.js 29:21-48
  [29] ./~/handlebars/dist/cjs/handlebars/helpers/with.js 3 kB {0} [built]
       cjs require ./helpers/with [22] ./~/handlebars/dist/cjs/handlebars/helpers.js 33:19-44
  [30] ./~/handlebars/dist/cjs/handlebars/decorators.js 990 bytes {0} [built]
       cjs require ./decorators [19] ./~/handlebars/dist/cjs/handlebars/base.js 17:18-41
  [31] ./~/handlebars/dist/cjs/handlebars/decorators/inline.js 2.68 kB {0} [built]
       cjs require ./decorators/inline [30] ./~/handlebars/dist/cjs/handlebars/decorators.js 9:24-54
  [32] ./~/handlebars/dist/cjs/handlebars/logger.js 3.83 kB {0} [built]
       cjs require ./logger [19] ./~/handlebars/dist/cjs/handlebars/base.js 19:14-33
  [33] ./~/handlebars/dist/cjs/handlebars/safe-string.js 1.15 kB {0} [built]
       cjs require ./handlebars/safe-string [18] ./~/handlebars/dist/cjs/handlebars.runtime.js 19:28-63
  [34] ./~/handlebars/dist/cjs/handlebars/runtime.js 33.6 kB {0} [built]
       cjs require ./handlebars/runtime [18] ./~/handlebars/dist/cjs/handlebars.runtime.js 31:25-56
  [35] ./~/handlebars/dist/cjs/handlebars/no-conflict.js 1.57 kB {0} [built]
       cjs require ./handlebars/no-conflict [18] ./~/handlebars/dist/cjs/handlebars.runtime.js 35:28-63
  [36] ./assets/styles/index.scss 1.03 kB {0} [built]
       cjs require ./assets/styles/index.scss [0] ./index.js 12:0-37
  [37] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 158 kB {0} [built]
       cjs require !!../../node_modules/css-loader/index.js!../../node_modules/sass-loader/index.js!./index.scss [36] ./assets/styles/index.scss 4:14-118
  [38] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
       cjs require ../../node_modules/css-loader/lib/css-base.js [37] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 1:27-83
  [39] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot 82 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot [37] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4172-4253
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot [37] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4276-4357
  [40] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2 84 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2 [37] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4409-4492
  [41] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff 83 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff [37] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4525-4607
  [42] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf 82 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf [37] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4639-4720
  [43] ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.svg 82 bytes {0} [built]
       cjs require bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.svg [37] ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4756-4837
  [44] ./~/style-loader/addStyles.js 6.91 kB {0} [built]
       cjs require !../../node_modules/style-loader/addStyles.js [36] ./assets/styles/index.scss 7:13-69
  [45] ./spec spec\.js$ 182 bytes {1} [built]
       require.context ./ [0] ./spec/_all.js 6:10-50
  [46] ./spec/example.spec.js 173 bytes {1} [optional] [built]
       context element ./example.spec.js [45] ./spec spec\.js$
  [47] ./~/bootstrap-sass/assets/javascripts/bootstrap.js 69.7 kB {2} [built]
       single entry bootstrap-sass [0] multi vendor

Running "shell:deploy-publish" (shell) task
.nojekyll { dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 4710257,
  size: 0,
  blocks: 0,
  atime: 2017-04-28T15:10:11.000Z,
  mtime: 2017-04-28T15:10:11.000Z,
  ctime: 2017-04-28T15:10:11.000Z,
  birthtime: 2017-04-28T15:10:11.000Z }
[gh-pages (root-commit) 3bddb36] deploy task
 11 files changed, 15451 insertions(+)
 create mode 100644 .nojekyll
 create mode 100755 favicon.ico
 create mode 100755 index.html
 create mode 100644 public/448c34a56d699c29117adc64c43affeb.woff2
 create mode 100644 public/89889688147bd7575d6327160d64e760.svg
 create mode 100644 public/application.js
 create mode 100644 public/e18bbf611f2a2e43afc071aa2f4e1512.ttf
 create mode 100644 public/f4769f9bdb7466be65088239c12046d1.eot
 create mode 100644 public/fa2772327f55d8198301fdb8bcfc8158.woff
 create mode 100644 public/specs.js
 create mode 100644 public/vendor.js
^C

Execution Time (2017-04-28 11:10:06 UTC-4)
webpack:build             2.2s  ▇ 2%
webpack:build             1.2s  ▇ 1%
shell:deploy-publish  1m 39.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 95%
Total 1m 44.5s

~/wdi/projects/bucketlist-client (gh-pages)
$ git checkout master
error: The following untracked working tree files would be overwritten by checkout:
	.editorconfig
	.eslintrc.json
	.gitignore
	.jscsrc
	.jshintignore
	.jshintrc
	.remarkrc
	.scss-lint.yml
	CONTRIBUTING.md
	Gruntfile.js
	LICENSE
	README.md
	STYLE.md
	assets/scripts/.eslintrc.json
	assets/scripts/auth/api.js
	assets/scripts/auth/events.js
	assets/scripts/auth/ui.js
	assets/scripts/config.js
	assets/scripts/example.js
	assets/scripts/goals/api.js
	assets/scripts/goals/events.js
	assets/scripts/goals/ui.js
	assets/scripts/index.js
	assets/scripts/store.js
	assets/scripts/templates/goal-listing.handlebars
	assets/scripts/templates/helpers/.keep
	assets/styles/index.scss
	forms.md
	grunt/aliases.json
	grunt/eslint.json
	grunt/jasmine.json
	grunt/jsonlint.json
	grunt/paths.json
	grunt/shell.js
	grunt/webpack-dev-server.js
	grunt/webpack.js
	index.js
	lib/add-nested-value.js
	lib/get-form-fields.js
	lib/parse-nested-query.js
	lib/set-api-origin.js
	package.json
	spec/.eslintrc.json
	spec/_all.js
	spec/example.spec.js
Please move or remove them before you switch branches.
Aborting
~/wdi/projects/bucketlist-client (gh-pages)
$ grunt deploy
Running "shell:git-is-clean" (shell) task
On branch gh-pages
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.editorconfig
	.eslintrc.json
	.gitignore
	.jscsrc
	.jshintignore
	.jshintrc
	.remarkrc
	.scss-lint.yml
	CONTRIBUTING.md
	Gruntfile.js
	LICENSE
	README.md
	STYLE.md
	assets/
	forms.md
	grunt/
	index.js
	lib/
	package.json
	spec/

nothing added to commit but untracked files present (use "git add" to track)
Warning: Command failed: test -z "$(git status --porcelain)"  || (git status && false)
 Use --force to continue.

Aborted due to warnings.


Execution Time (2017-04-28 11:12:12 UTC-4)
loading tasks       956ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 97%
shell:git-is-clean   28ms  ▇▇ 3%
Total 984ms

~/wdi/projects/bucketlist-client (gh-pages)
$ cd ..
~/wdi/projects 
$ cd bucketlist-client/
~/wdi/projects/bucketlist-client (gh-pages)
$ git checkout master
error: The following untracked working tree files would be overwritten by checkout:
	.editorconfig
	.eslintrc.json
	.gitignore
	.jscsrc
	.jshintignore
	.jshintrc
	.remarkrc
	.scss-lint.yml
	CONTRIBUTING.md
	Gruntfile.js
	LICENSE
	README.md
	STYLE.md
	assets/scripts/.eslintrc.json
	assets/scripts/auth/api.js
	assets/scripts/auth/events.js
	assets/scripts/auth/ui.js
	assets/scripts/config.js
	assets/scripts/example.js
	assets/scripts/goals/api.js
	assets/scripts/goals/events.js
	assets/scripts/goals/ui.js
	assets/scripts/index.js
	assets/scripts/store.js
	assets/scripts/templates/goal-listing.handlebars
	assets/scripts/templates/helpers/.keep
	assets/styles/index.scss
	forms.md
	grunt/aliases.json
	grunt/eslint.json
	grunt/jasmine.json
	grunt/jsonlint.json
	grunt/paths.json
	grunt/shell.js
	grunt/webpack-dev-server.js
	grunt/webpack.js
	index.js
	lib/add-nested-value.js
	lib/get-form-fields.js
	lib/parse-nested-query.js
	lib/set-api-origin.js
	package.json
	spec/.eslintrc.json
	spec/_all.js
	spec/example.spec.js
Please move or remove them before you switch branches.
Aborting
~/wdi/projects/bucketlist-client (gh-pages)
$

**Comment by rrdaniels85** [comment]
I should mention that during the deploy it got hung up for like 5 minutes and wouldn't proceed so I control C ^ out and then this occurred (Not sure if that's what caused this): 


  [47] ./~/bootstrap-sass/assets/javascripts/bootstrap.js 69.7 kB {2} [built]
       single entry bootstrap-sass [0] multi vendor

Running "shell:deploy-publish" (shell) task
.nojekyll { dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 4710257,
  size: 0,
  blocks: 0,
  atime: 2017-04-28T15:10:11.000Z,
  mtime: 2017-04-28T15:10:11.000Z,
  ctime: 2017-04-28T15:10:11.000Z,
  birthtime: 2017-04-28T15:10:11.000Z }
[gh-pages (root-commit) 3bddb36] deploy task
 11 files changed, 15451 insertions(+)
 create mode 100644 .nojekyll
 create mode 100755 favicon.ico
 create mode 100755 index.html
 create mode 100644 public/448c34a56d699c29117adc64c43affeb.woff2
 create mode 100644 public/89889688147bd7575d6327160d64e760.svg
 create mode 100644 public/application.js
 create mode 100644 public/e18bbf611f2a2e43afc071aa2f4e1512.ttf
 create mode 100644 public/f4769f9bdb7466be65088239c12046d1.eot
 create mode 100644 public/fa2772327f55d8198301fdb8bcfc8158.woff
 create mode 100644 public/specs.js
 create mode 100644 public/vendor.js
^C

Execution Time (2017-04-28 11:10:06 UTC-4)
webpack:build             2.2s  ▇ 2%
webpack:build             1.2s  ▇ 1%
shell:deploy-publish  1m 39.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 95%
Total 1m 44.5s

~/wdi/projects/bucketlist-client (gh-pages)
$ git checkout master
error: The following untracked working tree files would be overwritten by checkout:
	.editorconfig
	.eslintrc.json
	.gitignore
	.jscsrc
	.jshintignore
	.jshintrc
	.remarkrc
	.scss-lint.yml
	CONTRIBUTING.md
	Gruntfile.js
	LICENSE
	README.md
	STYLE.md
	assets/scripts/.eslintrc.json
	assets/scripts/auth/api.js
	assets/scripts/auth/events.js
	assets/scripts/auth/ui.js
	assets/scripts/config.js
	assets/scripts/example.js
	assets/scripts/goals/api.js
	assets/scripts/goals/events.js
	assets/scripts/goals/ui.js
	assets/scripts/index.js
	assets/scripts/store.js
	assets/scripts/templates/goal-listing.handlebars
	assets/scripts/templates/helpers/.keep
	assets/styles/index.scss
	forms.md
	grunt/aliases.json
	grunt/eslint.json
	grunt/jasmine.json
	grunt/jsonlint.json
	grunt/paths.json
	grunt/shell.js
	grunt/webpack-dev-server.js
	grunt/webpack.js
	index.js
	lib/add-nested-value.js
	lib/get-form-fields.js
	lib/parse-nested-query.js
	lib/set-api-origin.js
	package.json
	spec/.eslintrc.json
	spec/_all.js
	spec/example.spec.js
Please move or remove them before you switch branches.
Aborting
~/wdi/projects/bucketlist-client (gh-pages)
$ grunt deploy
Running "shell:git-is-clean" (shell) task
On branch gh-pages
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.editorconfig
	.eslintrc.json
	.gitignore
	.jscsrc
	.jshintignore
	.jshintrc
	.remarkrc
	.scss-lint.yml
	CONTRIBUTING.md
	Gruntfile.js
	LICENSE
	README.md
	STYLE.md
	assets/
	forms.md
	grunt/
	index.js
	lib/
	package.json
	spec/

nothing added to commit but untracked files present (use "git add" to track)
Warning: Command failed: test -z "$(git status --porcelain)"  || (git status && false)
 Use --force to continue.

Aborted due to warnings.


Execution Time (2017-04-28 11:12:12 UTC-4)
loading tasks       956ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 97%
shell:git-is-clean   28ms  ▇▇ 3%
Total 984ms

~/wdi/projects/bucketlist-client (gh-pages)
$ cd ..
~/wdi/projects 
$ cd bucketlist-client/
~/wdi/projects/bucketlist-client (gh-pages)
$ git checkout master
error: The following untracked working tree files would be overwritten by checkout:
	.editorconfig
	.eslintrc.json
	.gitignore
	.jscsrc
	.jshintignore
	.jshintrc
	.remarkrc
	.scss-lint.yml
	CONTRIBUTING.md
	Gruntfile.js
	LICENSE
	README.md
	STYLE.md
	assets/scripts/.eslintrc.json
	assets/scripts/auth/api.js
	assets/scripts/auth/events.js
	assets/scripts/auth/ui.js
	assets/scripts/config.js
	assets/scripts/example.js
	assets/scripts/goals/api.js
	assets/scripts/goals/events.js
	assets/scripts/goals/ui.js
	assets/scripts/index.js
	assets/scripts/store.js
	assets/scripts/templates/goal-listing.handlebars
	assets/scripts/templates/helpers/.keep
	assets/styles/index.scss
	forms.md
	grunt/aliases.json
	grunt/eslint.json
	grunt/jasmine.json
	grunt/jsonlint.json
	grunt/paths.json
	grunt/shell.js
	grunt/webpack-dev-server.js
	grunt/webpack.js
	index.js
	lib/add-nested-value.js
	lib/get-form-fields.js
	lib/parse-nested-query.js
	lib/set-api-origin.js
	package.json
	spec/.eslintrc.json
	spec/_all.js
	spec/example.spec.js
Please move or remove them before you switch branches.
Aborting
~/wdi/projects/bucketlist-client (gh-pages)
$

**Comment by rrdaniels85** [comment]
Thanks for the help Chris

**Comment by payne-chris-r** [comment]
git was stuck somewhere between git checkout -b gh-pages and build I think? Not sure what exactly happened here, but the deploy task barfed at some point and gave us a dirty git staging area. We ended up doing a `git checkout master --force` and running `grunt deploy` again. We didn't like it, but it seemed better than `rm -rf ./` or something else with potential to be extremely destructive.

**Comment by danman01** [comment]
Deedee and I were encountering similar barfing of the grunt deploy task: https://github.com/ga-wdi-boston/browser-template/issues/102

For some reason, this was happening, even though we had node_modules in .gitignore:
>While running the grunt deploy during script line 16 -
>`command: 'test -z "$(git status --porcelain)" || (git status && false)'`
>is adding node modules to `gh-pages` branch. When we get to the last command -
>`git checkout master` - grunt deploy aborts because of conflict with master branch.

Thus causing the final `git checkout master` to fail, which happened in this current issue too...things deployed fine, just had a dirty git staging area leftover from gh-pages.
