### ISSUE TITLE
Handlebars - single item

### ISSUE THREAD

**Issue by antleo1995** [ga-wdi-boston/full-stack-project#756]
I am able to loop through a collection and put it on page but when trying to place a single item in a div I am unable to do so. The hang up is setting a variable I believe

Below is the working code i am attempting to mimic for a single item
```html
<ul>

  {{#each recipes as |recipe|}}
   <!-- Developers, why are we using data-id and not just id? -->
  <li class='recipe{recipe.id}}'>
    <h1> <small>Recipe Name: {{recipe.title}}</small></h1>
    <div>
  <ul class=“recipes”>

     <li>{{recipe.ingredient_list}}</li>
     <li>{{recipe.directions}}</li>
     <li>{{recipe.prep_time}}</li>

  </ul>
    </div>
  <hr>
  </li>
  {{/each}}

</ul>
```
Here's the code for a single recipe
```html
{{#each recipes as |recipe|}}
  <li class='recipe{recipe.id}}'>
    <h1> <small>Recipe Name: {{recipe.title}}</small></h1>
    <div>
     <ul class=“recipes”>

     <li>{{recipe.ingredient_list}}</li>
     <li>{{recipe.directions}}</li>
     <li>{{recipe.prep_time}}</li>

  </ul>
    </div>
  <hr>
  </li>
{{/each}}
```

Just displays a blank entry for every recipe owned by the user.

**Comment by jordanallain** [comment]
`<li class='recipe{recipe.id}}'>`

This line looks like it is missing something.

**Comment by antleo1995** [comment]
I spoke with Danny. He helped me figure it. 
```html
    <h1> <small>Recipe Name: {{recipe.title}}</small></h1>
    <div>
     <ul class=“recipes”>

     <li>{{recipe.ingredient_list}}</li>
     <li>{{recipe.directions}}</li>
     <li>{{recipe.prep_time}}</li>

    </ul>
  </div>
  <hr>
```

The above code worked. I just needed to make a simple call to the object passed in. I tried that previously but must've had something else incorrect. It is now working as intended.
