### ISSUE TITLE
Still Can't Create Cars -- Permission Denied

### ISSUE THREAD

**Issue by andyjzhong** [ga-wdi-boston/full-stack-project#757]
This is a continuation from Issue #733

Previously, I was trying to get my curl request for creating new cars to work, but was running into a 401 Unauthorized error every time I entered a curl request. I have tried passing in the token of my current user along with my curl request to no avail.

I took a break from running curl requests to actually develop my form for creating cars in my client. When I try to click my Create Car button, my onCreateCars function RUNS, but returns a 422: Unprocessable Entity error. I click into this error through Google Chrome's Inspect and it returns the following:
```
{user: ["must exist", "can't be blank"]}
user
:
["must exist", "can't be blank"]
```
I wonder if this has anything to do with the code in my cars model (shown below)?
```rb
class Car < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'

  validates :user, presence: true
end
```
Please let me know if you require more detail -- would love to sit with someone to discuss this if possible. Thanks!

**Comment by andyjzhong** [comment]
This is what is showing in my rails server:

Started POST "/cars/" for 127.0.0.1 at 2017-04-28 12:09:25 -0400
Processing by CarsController#create as */*
  Parameters: {"car"=>{"make"=>"1", "model"=>"1", "year"=>"1", "color"=>"1"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "7201adb90e6f277765ad0ceac826a340"], ["LIMIT", 1]]
   (0.2ms)  BEGIN
   (0.1ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.09ms)
Completed 422 Unprocessable Entity in 21ms (Views: 3.2ms | ActiveRecord: 6.4ms)

**Comment by jordanallain** [comment]
please post the cars controller

**Comment by andyjzhong** [comment]
Hi Jordan --

```rb
class CarsController < ProtectedController
  before_action :set_car, only: [:show, :update, :destroy]

  # GET /cars
  def index
    @cars = Car.all

    render json: @cars
  end

  # GET /cars/1
  def show
    render json: @car
  end

  # POST /cars
  def create
    @car = Car.new(car_params)

    if @car.save
      render json: @car, status: :created, location: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cars/1
  def update
    if @car.update(car_params)
      render json: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end

  # DELETE /cars/1
  def destroy
    @car.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def car_params
      params.require(:car).permit(:make, :model, :year, :color)
    end
end
```

**Comment by scottyscripts** [comment]
The validation in your model is making sure that you have a `user` field when creating a new car. Is this intended? See if you can create in rails console.

**Comment by payne-chris-r** [comment]
Typically this is the wrong approach:
`I took a break from running curl requests to actually develop my form for creating cars in my client.`
Focus on one thing at a time. Please work with the curl request, make sure that's working, then move onto your client.

**Comment by payne-chris-r** [comment]
Post the curl request, and post the output here

**Comment by andyjzhong** [comment]
Hi Scott -- I would like each user to only be able to create and update his/her own car, which is why I thought having the user present would be necessary. I am thankfully able to create new users and sign in, etc. But when I log in and try to create cars, it's still coming up with that 422 error.

Chris -- Thanks for the tough love. Just wanted to get a small victory and feel like I was making progress but I understand your feedback. Here's the curl script I tried running to pass in 

```
USER_ID=1 TOKEN="BAhJIiU3ODcxZTVkMmY5OTIyMzE3ODM3ZjNhYTU4MmUzMzI3NAY6BkVG--8a64294e89337e8034b8d2b5bf2578e18aa3a780" MAKE=Hello MODEL=Hello YEAR=2020 COLOR=Blue scripts/cars-scripts/create_cars.sh 
```

create_cars.sh:
```
  API="${API_ORIGIN:-http://localhost:4741}"
  URL_PATH="/cars"
  curl "${API}${URL_PATH}" \
    --include \
    --request POST \
    --header "Content-Type: application/json" \
    --header "Authorization: Token token=$TOKEN" \
    --data '{
      "car": {
        "make": "'"${MAKE}"'",
        "model": "'"${MODEL}"'",
        "year": "'"${YEAR}"'",
        "color": "'"${COLOR}"'"
      }
    }'

  echo
```
The error returned below:
```
-bash: scripts/cars-scripts/create_cars.sh: Permission denied
```

**Comment by scottyscripts** [comment]
Try to create a new car in your Rails console, and let me know what happens. This will help us determine if the error is in your logic or request.

**Comment by andyjzhong** [comment]
Thanks, Scott -- Here's what happens when I try to create a car within my console:

It looks like it tries to create the object but then doesn't like something so it rolls back. Am I not providing it with the right parameters?

```
bin/rails console
Running via Spring preloader in process 19960
Loading development environment (Rails 5.0.1)
No entry for terminal type "s/andy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/console_helper.rb";
using dumb terminal settings.
[1] pry(main)> Car.create({make: "make"})               
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
=> #<Car:0x007ff68abc4930
 id: nil,
 user_id: nil,
 make: "make",
 model: nil,
 year: nil,
 color: nil,
 created_at: nil,
 updated_at: nil>
[2] pry(main)> 
```

**Comment by scottyscripts** [comment]
@andyjzhong can i see your migration file for car

**Comment by andyjzhong** [comment]
Migration file for car:
```
class CreateCars < ActiveRecord::Migration[5.0]
  def change
    create_table :cars do |t|
      # Adds a user_id column to the cars table.
      t.references :user, null: false
      t.string :make
      t.string :model
      t.integer :year
      t.string :color

      t.timestamps
    end
  end
end
```

Is the t.references :user, null: false line creating this issue?

**Comment by danman01** [comment]
@andyjzhong yes, that means it wants a user id or it won't persist to the DB. Tip: in the console, after generating an ActiveRecord error on an object (by calling `save`, `create` or `valid?`), type `.errors?` (i.e. `car.errors?`) to see more detailed error output.

**Comment by payne-chris-r** [comment]
See all these things Rails is expecting that it's not getting?
```
 id: nil,
 user_id: nil,
 make: "make",
 model: nil,
 year: nil,
 color: nil,
 created_at: nil,
 updated_at: nil
```
Some of those values are required, some aren't, some are provided by SQL. Can you look at your migration and tell us which ones come from where, and which ones are required in order to make that request?

**Comment by payne-chris-r** [comment]
I'll come find you as soon as I get a minute. If you can answer my last question you'll be right as rain in no time.

**Comment by andyjzhong** [comment]
Required values is User ID
Not Required: Make, Model, Year, Color
Provided: Created/Updated and ID

I need to specify the User ID. And I think I know where to do that. Let's discuss.

**Comment by payne-chris-r** [comment]
Booyah.

**Comment by andyjzhong** [comment]
Thanks, Chris! I managed to get this working by making sure I passed in the current_user.id.

Within my Cars Controller, I had to add in the line below, which allows me to create a new car AND build an association between the new car and current user.

```rb
@car = current_user.cars.build(car_params)
```

```rb
  def create
    # @car = Car.new(car_params)
    # Array of current user's car objects

    # Build method allows you to create a new car and also build an association between user and new car.
      # @car = Car.new(car_params)
      # @car.user_id = current_user.id
    @car = current_user.cars.build(car_params)

    if @car.save
      render json: @car, status: :created, location: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end
```
