### ISSUE TITLE
Question about Handlebars Event Handlers

### ISSUE THREAD

**Issue by sjruby** [ga-wdi-boston/full-stack-project#758]
We reviewed in class how to add click handlers to HTML rendered by Handlebars, I figured a way out on the internet that's different(I couldn't find my notes and the StackOverflow answer I found dosn't match memory).  The approach I'm using works, but just wanted to get some feedback if there is a problem with the approach below:

```js
$(document).on('click','.list_of_boards',boardActions.onGetBoard)
```
Thanks!

**Comment by scottyscripts** [comment]
You just need to be sure that the element with class `list_of_boards` is rendered when the DOM is loaded. If it is working you should be good!

**Comment by sjruby** [comment]
Thanks!
