### ISSUE TITLE
Problem reading Error Messages

### ISSUE THREAD

**Issue by sjruby** [ga-wdi-boston/full-stack-project#759]
I have a patch request that works locally and then bombs on Heroku.  The HTTP code I'm getting back is 400 BAD request, I'm thrashing figuring out how to add like the response body or some the details on the BAD request so I can correct it.   I've messed around with the response ui.failure logic here's what I have for the failure:

```js
 const failure = function (response) {

  $message.append(response.content)
}
```

here is the controller that I'm calling, I think I must be missing something in there to tell it to return the errors but have been thrashing at it for a while:

```rb
  # GET /doctors/1
  def show
    render json: @board
  end
```

**Comment by jordanallain** [comment]
have you looked at your heroku logs?

**Comment by danman01** [comment]
Also @sjruby could you post your entire error message, and also the Rails server output?

**Comment by sjruby** [comment]
once you know how to get the error message problems are easy to fix!  Thanks!

**Comment by danman01** [comment]
@sjruby what did it turn out to be? And, could you close this when it's resolved?

**Comment by sjruby** [comment]
Sorry about that meant to close it, it was that I had a require for a class required in the params that I wasn't actually passing.  I just removed the class, b/c I did not actually need it and it started working.  I think as I was testing the front end I probably made the same change to params on the backend but never deployed/saved the change.
