### ISSUE TITLE
Ahhhh  Some of my routes don't work on the back end anymore!

### ISSUE THREAD

**Issue by eshimel** [ga-wdi-boston/full-stack-project#76]
So I tested my routes on postman the day before yesterday, and I either missed the fact that I am missing critical indexes or I did something wacky to make them go away.  I need some guidance before my head explodes.

Thanks!

**Comment by tdyer** [comment]
What is the URL for the failing route? 
- Use curl to submit a request to this URL and check the server log.
- Try to decipher the error message, if one, in the server log.
- If you can't understand the error message add it to this issue..

**Comment by gaand** [comment]
What's the output of `rake routes`?

**Comment by eshimel** [comment]
Issue with my routes, had :index in exception, preventing it from doing its thing...don't do this!
