### ISSUE TITLE
Rails changes to support current_user hitting HTTP/1.1 404 Not Found when doing a create

### ISSUE THREAD

**Issue by donpowers** [ga-wdi-boston/full-stack-project#760]
This is the response from the curl request:

HTTP/1.1 404 Not Found
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 6f35ba31-5e16-457a-baac-f8ecaac64f9c
X-Runtime: 0.052628
Vary: Origin
Transfer-Encoding: chunked

{"error":{"message":"Not Found"}}~/wdi/projects/bee-mgt-api (userSecurity)

This is what was in the Rails window:

Started POST "/hives" for 127.0.0.1 at 2017-04-28 13:39:24 -0400
Processing by HivesController#create as */*
  Parameters: {"hive"=>{"hive_name"=>"Hive Seven", "queen_type"=>"Russian", "brood_supers"=>2, "honey_supers"=>2, "hive_location"=>"Amesbury, NH"}}
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "256692cea47730760a9496538cec4d37"], ["LIMIT", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.1ms)
Completed 404 Not Found in 36ms (Views: 4.9ms | ActiveRecord: 5.6ms)

My controller file
```rb
class HivesController < ProtectedController
  def index
    @hives = Hive.all

    render json: @hives
  end

  def show
    render json: current_user.hives.find(params[:id])
  end

  def update
    # @hive = Hive.find(params[:id])
    @hive = current_user.hives.find(params[:id])
    if @hive.update(hive_params)
      head :no_content
    else
      render json: @hive.errors, status: :unprocessable_entity
    end
  end

  def create
    # will need to update this to support current_user model
    set_hive
    @hive = current_user.hives.build(hive_params)
    puts "Insde create is hive: #{@hive}"
    if @hive.save
      render json: @hive, status: :created
    else
      render json: @hive.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @hive = Hive.find(params[:id])
    @hive.destroy

    head :no_content
  end

  def set_hive
    @hive = current_user.hives.find(params[:id])
  end

  def hive_params
    params.require(:hive).permit(:hive_name, :queen_type, :brood_supers,
                                 :honey_supers, :hive_location)
  end
  private :hive_params
end
```

**Comment by jordanallain** [comment]
can you post the curl request?

**Comment by donpowers** [comment]
Here is the curl request:
```
curl --include --request POST http://localhost:4741/hives \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=BAhJIiUyNTY2OTJjZWE0NzczMDc2MGE5NDk2NTM4Y2VjNGQzNwY6BkVG--5f6502f04d68be2fc70c10d7a5b45bea4fbaf5b7" \
  --data '{
    "hive": {
      "hive_name": "Hive Seven",
      "queen_type": "Russian",
      "brood_supers": 2,
      "honey_supers": 2,
      "hive_location": "Amesbury, NH"
    }
  }'
```

**Comment by tvcrawley** [comment]
Can you post the entire error from the terminal after pasting the curl request?

**Comment by donpowers** [comment]
The entire error was posted above...here it is again....

HTTP/1.1 404 Not Found
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 6f35ba31-5e16-457a-baac-f8ecaac64f9c
X-Runtime: 0.052628
Vary: Origin
Transfer-Encoding: chunked

{"error":{"message":"Not Found"}}~/wdi/projects/bee-mgt-api (userSecurity)
$ HTTP/1.1 404 Not Found

**Comment by donpowers** [comment]
Before updating to the current_user it was working with this 

  @hive = Hive.new(hive_params)

switch to use this since it was how the 'examples' did it.  Not sure what the difference between
new and build

    @hive = current_user.hives.build(hive_params)

**Comment by tvcrawley** [comment]
Can you post your Hive Model?

**Comment by donpowers** [comment]
is this what you are looking for?

class Hive < ApplicationRecord
  belongs_to :user
end

**Comment by tvcrawley** [comment]
Ok, can you also post the User Model?

**Comment by donpowers** [comment]
class User < ApplicationRecord
  include Authentication
  has_many :hives
end

**Comment by donpowers** [comment]
In the HivesController class I was making a call to 'set_hive'. 

 def set_hive
    @hive = current_user.hives.find(params[:id])
 end

This call returned 404 since the id at this point was not valid for the 'current_user'.  It also was not the correct thing to do when doing a create, since I was not trying to retrieve anything from the current user.
