### ISSUE TITLE
No able to access array within an object returned from API

### ISSUE THREAD

**Issue by deeforte** [ga-wdi-boston/full-stack-project#761]
I'm able to get an object from the API but not able to get at the array within the object to pass to my function that will iterate the array.

This is probably something simple, but I've thrashed on it too long.

currentYarns requires store

When my code in main.js is like this:
yarnEvents.getUserYarns()
yarnDisplay = currentYarns
console.log('yarnDisplay', yarnDisplay)
console.log('currentYarns', currentYarns)

Both yarnDisplay and currentYarns show as the objects in the console.
{
"yarns": [
{
"id": 1,
"name": "mountain mohair",
"quantity": null,
"yards": null,
"color": null,
"project": null,
"user": {
"id": 2,
"email": "deeforte@email.com"
}
},
{
"id": 2,
"name": "mountain mohair",
"quantity": 3,
"yards": 250,
"color": "gray",
"project": "sweater",
"user": {
"id": 2,
"email": "deeforte@email.com"
}
},
{
"id": 3,
"name": "shetlan",
"quantity": 3,
"yards": 250,
"color": "gray",
"project": "shawl",
"user": {
"id": 2,
"email": "deeforte@email.com"
}
}
]
}

When i try to get yarnDisplay to be the array the array by
yarnDisplay = currentYarn.yarns
currentYarn returns the object to the console, but yarnDisplay is undefined.

I've been thrashing on this for hours.   I've tried googling how to access array within object.  I've referred back to the game project where this approach worked.  
Did I setup my database incorrectly?

Help would be very much appreciated.   Thanks.

**Comment by jordanallain** [comment]
`console.log('currentYarns', currentYarns)`

`yarnDisplay = currentYarn.yarns`

is this right? the variable names look different to me.

**Comment by deeforte** [comment]
No...sorry.
yarnDisplay = currentYarns.yarns returns undefined.

**Comment by deeforte** [comment]
yarnEvents.getUserYarns()
yarnDisplay = currentYarns.yarns
console.log('yarnDisplay', yarnDisplay)
console.log('currentYarns', currentYarns)

yarnDisplay returns undefined to console.

**Comment by tvcrawley** [comment]
You've tried accessing the array using dot notation. Have you tried the other option on accessing object values?

**Comment by deeforte** [comment]
hint please.  maybe the repo that we discussed.   I did think of that and went back to look at js training repos and could not find it.

**Comment by tvcrawley** [comment]
Hint: google `js access array in object` there should be an informative stackoverflow post for the first link

**Comment by deeforte** [comment]
yarnDisplay = currentYarns['yarns']
console.log('yarnDisplay', yarnDisplay)

yarnDisplay is still undefined in console.log

**Comment by deeforte** [comment]
Thank you Jordan and Toni.
