### ISSUE TITLE
Need assistance with rails generate

### ISSUE THREAD

**Issue by rlarsonil71** [ga-wdi-boston/full-stack-project#762]
Issue Description:
I reduced complexity by starting with CRUD using one new favorite_players table.
I followed the https://github.com/ga-wdi-boston/rails-api-single-resource repo instructions following what was done for the `books` table **without** a relationship.
I did the following to create a new controller and model:
 - bin/rails generate controller favorite_players
 - bin/rails generate model favorite_player player_name:string ... etc.

Note that I did NOT do a `bin/rails generate **scaffold** favorite_player player_name:string ...etc`.

All CURL CRUD scripts worked fine. 

I am now adding the relationship code to the `users` table.  One user has many favorite_players.
I notice that I have some files missing as expected since I did not do the full scaffold.

A full scaffold example from the https://github.com/ga-wdi-boston/rails-api-one-to-many repo is:
~/wdi/training/rails-api-library-demo (tutorial)$ bin/rails generate scaffold
author given_name:string family_name:string
Running via Spring preloader in process 17246
Expected string default value for '--serializer'; got true (boolean)
      invoke  active_record
      create    db/migrate/20170419183303_create_authors.rb
      create    app/models/author.rb
      invoke    rspec
      create      spec/models/author_spec.rb
      invoke  resource_route
       route    resources :authors
      **invoke  serializer
      create    app/serializers/author_serializer.rb**
      invoke  scaffold_controller
      create    app/controllers/authors_controller.rb
      invoke    rspec
      create      spec/controllers/authors_controller_spec.rb
      **create      spec/routing/authors_routing_spec.rb**
      invoke      rspec
      **create        spec/requests/authors_spec.rb**

I am missing the associated BOLD files above in my api repo (all other files exist in my repo):
 - app/serializers/favorite_player_serializer.rb
 - spec/routing/favorite_players_routing_spec.rb
 - spec/requests/favorite_players_spec.rb

I am pretty sure I need to run the following command to create the new serializer:
$ bin/rails generate serializer favorite_player

I am not sure how to create the other 2 files above 
(spec/routing/favorite_players_routing_spec.rb AND spec/requests/favorite_players_spec.rb).

QUESTION:
How do I create those 2 missing files (without doing a scaffold)?

I know a bin/rails generate scaffold will break my file structure.  I am trying to prevent extra and incorrect files in my api repo.

Once I figure this out, I know that I need to the following:
 $ bin/rails generate migration AddFavoritePlayerToUsers favorite_player:references

since I already updated the code with Rails Relationships and has_many and belongs_to MacroMethods in the 2 models.

I did try the following but am not getting it:
$ rails generate -h
Running via Spring preloader in process 59718
Expected string default value for '--serializer'; got true (boolean)
Usage: rails generate GENERATOR [args] [options]

General options:
  -h, [--help]     # Print generator's options and usage
  -p, [--pretend]  # Run but do not make any changes
  -f, [--force]    # Overwrite files that already exist
  -s, [--skip]     # Skip files that already exist
  -q, [--quiet]    # Suppress status output

Please choose a generator below.

Expected string default value for '--helper'; got false (boolean)
Expected string default value for '--assets'; got false (boolean)
Rails:
  channel
  controller
  generator
  integration_test
  job
  mailer
  migration
  model
  resource
  scaffold
  scaffold_controller
  serializer
  task

ActiveRecord:
  active_record:migration
  active_record:model

Rspec:
  rspec:controller
  rspec:feature
  rspec:helper
  rspec:install
  rspec:integration
  rspec:job
  rspec:mailer
  rspec:model
  rspec:observer
  rspec:request
  rspec:scaffold
  rspec:view

TestUnit:
  test_unit:controller
  test_unit:generator
  test_unit:helper
  test_unit:integration
  test_unit:job
  test_unit:mailer
  test_unit:model
  test_unit:plugin
  test_unit:scaffold

Let me know if you need further information.
Thanks!

**Comment by jordanallain** [comment]
the other two files that would have been created are spec files for testing. do you plan on needing those?

**Comment by rlarsonil71** [comment]
Hey Jordan - Ok thanks.. that's right.  I will do rails BRD testing time permitting so I will skip these 2 spec files for now.

I will just do the following then to create the serializer:
$ bin/rails generate serializer favorite_player

and the following to create the new migration with the foreign key:
$ bin/rails generate migration AddFavoritePlayerToUsers favorite_player:references

Thanks!

**Comment by tvcrawley** [comment]
Sounds like a good plan!

**Comment by rlarsonil71** [comment]
Thanks!  On to more FUN!  :-) .  Closing issue.
