### ISSUE TITLE
Update CRUD

### ISSUE THREAD

**Issue by antleo1995** [ga-wdi-boston/full-stack-project#763]
I have hit a pretty big stopping point. A few things have me stuck - biggest thing is how i am going to possibly bypass validation on update. When I create, I am validating all fields except the prep_time column. When a user updates the record I am uncertain if this validation happens again since it is in my model which look as follows: 

```
class Recipe < ApplicationRecord
  belongs_to :user
  validates :title, :ingredient_list, :directions, presence: true
end
```

I have some other issues but I think I can work around them. As I worked through my problem, I found this to be my biggest issue I cannot solve. Is there a way for me to only validate on create but allow a user to update any field they want, in other words, can they update a single field - where might i check?

**Comment by jordanallain** [comment]
have you tried updating a recipe with a curl request to see if it would work?

**Comment by antleo1995** [comment]
I was actually going to do that - sort of

Gonna try just a form with the id provided and see what happens...but a curl might be faster. ;)

Leaving this open for now. Will update you with my results.

**Comment by antleo1995** [comment]
Nifty shifty! So much automagic.....

Seems it will update fine still. Whew! Moving on and closing thread. Thanks!

💃
