### ISSUE TITLE
curl request returns an error that I cannot figure out

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/full-stack-project#764]
The curl request is:
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/reviewers"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token="BAhJIiUwNzcyMjU2Mjk5MjI2ZmIzMzRiYWQ4YzI1ZDVmOTgxZQY6BkVG--326a122db81548c0daede62ab61f6c6cf92dfa84"" \
  --data '{
    "reviewer": {
      "username": "'"Pocahontas"'",
      "industry": "'"Wilderness"'"
    }
  }'
```
The error is: 
undefined method `reviewers' for nil:NilClass\u003e","traces":{"Application Trace":[{"id":0,"trace":"app/controllers/reviewers_controller.rb:46:in `set_reviewer'"}]

My code at the referenced location in the error is
```def set_reviewer
      @reviewer = current_user.reviewers.find(params[:id])
    end
```

I have also tried:
```
def set_reviewer
      @reviewer = current_user.user.reviewers.find(params[:id])
    end

def set_reviewer
      @reviewer = current_user.users.reviewers.find(params[:id])
    end

def set_reviewer
      @reviewer = current_user.Reviewers.find(params[:id])
    end

def set_reviewer
      @reviewer = current_user.r=Reviewer.find(params[:id])
    end
```

**Comment by danman01** [comment]
Hey @awoodrum87 - so `undefined method reviewers' for nil:NilClass` is coming back for which file and line #? From there, you can see that one of your objects is not what you think it is. That object does not have the method `reviewers` available to it.

Also, you are trying multiple ways of setting the reviewer - have any of them worked as you expect? What do you expect, and what results are you getting in the `@reviewer` instance variable?

**Comment by awoodrum87** [comment]
hey dan, i didn't inspect the generated code close enough and I didn't update the model. :)

It works now. Thank you!

**Comment by danman01** [comment]
Excellent!

**Comment by danman01** [comment]
@awoodrum87 please close this issue if it's resolved. Thanks!

**Comment by awoodrum87** [comment]
so i retested curl requests to another db and now it doesn't work
I created a reviews DB yesterday with a 1:1 relationship from users
then I modified and added a reviewers table. once I got the reviewers curl requests working, i decided to test the reviews table again with this curl request:
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/reviews"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=BAhJIiU5MTBiZjljYTg3NzAwOTBjZWIzZTRkODFlYzMyZGJhZgY6BkVG--6b6c7bf878090ab3e0f071c5dbc7ac5e75075804" \
  --data '{
    "review": {
      "review_date": "'"28-04-2017"'",
      "review_text": "'"Daisy eats all of her then complains so she gets free food"'"
    }
  }'
```

and I got the following error:
```HTTP/1.1 422 Unprocessable Entity
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 7c9c975d-dc33-4a90-adcc-96be7e055bd2
X-Runtime: 0.040924
Vary: Origin
Transfer-Encoding: chunked

{"reviewers":["must exist"]}
```

I don't understand what needs changed to make the viewer exist in this curl request.

**Comment by payne-chris-r** [comment]
Is this resolved now @awoodrum87 ?

**Comment by awoodrum87** [comment]
@tvlangley and I got these curl requests working. PLURAL VS SINGULAR MATTERS.
