### ISSUE TITLE
Adding a calculated field to existing table

### ISSUE THREAD

**Issue by naributler** [ga-wdi-boston/full-stack-project#765]
I'm trying to add a field that calculates the days to expiration for perishable food items. Here's what I have so far, and it would be great to know if I'm on the right path.

I generated a migration using this command: 
`rails generate migration AddComputedDaysToExp2 days_to_exp:interval`

I added a field called `days_to_exp` to the `items` table: 
```
class AddComputedDaysToExp2 < ActiveRecord::Migration[5.0]
  def change
    add_column :items, :days_to_exp, :interval
  end
end
```
I migrated to update the database:
`bin/rails db:migrate`

This does generate a column called "days_to_exp" in the `items` table. 
The `items` table now has the following columns: 
- id
- food_name
- purchase_date
- exp_date
- store_name
- quantity
- purchased
- created_at
- updated_at 
- user_id
- days_to_exp (type: interval)

Now, I'd like to populate the days_to_exp column. Here's the formula I'd like to use: 
**days_to_exp = exp_date - todays_date**

In SQL, I can update the table using the following code: 
```
UPDATE items
/* Age is a psql function that subtracts from the current date and returns that difference as an interval (10 days, 1 mon 3 days) */
/* The age function returns a negative number when calculating against a future date. Therefore, I multiplied by -1 to make these numbers positive.*/
SET days_to_exp = age(exp_date)*-1;
```
This worked, and all of my existing records now have populated values for the days_to_exp variable. 

My next step is to translate this SQL into Ruby on Rails. I tested some functions in pry, and found that this sequence of Ruby statements should work: 
```
now = Time.now.utc.to_date
exp_dte = '2017-05-03'.to_date
days_to_exp = (exp_dte - now).to_i
```

I'm not sure **where** to do this calculation so that it will happen in the background every time someone adds a new food item. Should this kind of code go into my Item model? I've seen a method called [update](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update) which seems promising. Am I on the right track here, or completely off base? 

Thank you!

**Comment by tvcrawley** [comment]
Sounds like you want this to happen every time a food item is added...or `create`d

**Comment by naributler** [comment]
Ohh...so does this kind of logic need to go in the controller, not the model?

**Comment by naributler** [comment]
When I looked at this [stackoverflow article](http://stackoverflow.com/questions/28168202/rails-how-do-i-make-a-calculation-using-form-input-variables-in-the-create-acti), it seemed like these changes were happening in the model?

**Comment by tvcrawley** [comment]
In this case, you could but it in the model or in the view.
Interesting article: https://richonrails.com/articles/rails-presenters

**Comment by naributler** [comment]
Thank you! I'll give that article a read.

**Comment by naributler** [comment]
After talking with @payne-chris-r yesterday afternoon, I'm trying to define this variable in the serializer, not the database. I've dropped the column called days_to_exp and migrated to update the database. Now, I'm trying to write a method in the serializer that will calculate this field. Here's what I have so far: 

```rb
class ItemSerializer < ActiveModel::Serializer
  attributes :id, :food_name, :purchase_date, :exp_date, :store_name, :quantity,
             :purchased, :days_to_exp

  def days_to_exp
    today = Time.now.utc.to_date
    exp_dte = :exp_date
    (exp_dte - today).to_i
  end
end
```

This code results in `NoMethodError (undefined method `-' for :exp_date:Symbol):`, so my next step is to solve this error.

**Comment by naributler** [comment]
Update - I made a typo and needed to remove the `:`. New code: 
```rb
class ItemSerializer < ActiveModel::Serializer
  attributes :id, :food_name, :purchase_date, :exp_date, :store_name, :quantity,
             :purchased, :days_to_exp

  def days_to_exp
    today = Time.now.utc.to_date
    exp_dte = exp_date
    (exp_dte - today).to_i
  end
end
```
New error to debug: NameError (undefined local variable or method `exp_date' for #<ItemSerializer:0x007f8f656e3b78>

**Comment by payne-chris-r** [comment]
Is exp_date a value in the table?

**Comment by payne-chris-r** [comment]
Which line is erroring?

**Comment by naributler** [comment]
Yes, exp_date is a value in the table. Here's a list of the table columns: 
<img width="692" alt="screen shot 2017-04-29 at 2 52 29 pm" 
src="https://cloud.githubusercontent.com/assets/20606223/25557991/8766bccc-2ceb-11e7-9be1-1c73f26a5468.png">

Here's the entire error: 
```
NameError (undefined local variable or method `exp_date' for #<ItemSerializer:0x007f8f63be2248>
Did you mean?  exp_dte):

app/serializers/item_serializer.rb:9:in `days_to_exp'
app/controllers/items_controller.rb:33:in `create'
```
Looks like it's erroring on `exp_dte = exp_date`.

**Comment by naributler** [comment]
I also tried this: 
```rb
class ItemSerializer < ActiveModel::Serializer
  attributes :id, :food_name, :purchase_date, :exp_date, :store_name, :quantity,
             :purchased, :days_to_exp

  def days_to_exp
    today = Time.now.utc.to_date
    # exp_dte = exp_date
    # (exp_dte - today).to_i
    exp_date - today
  end
end
```
But it returned the same error: 
```
NameError (undefined local variable or method `exp_date' for #<ItemSerializer:0x007f8f661730e8>):

app/serializers/item_serializer.rb:11:in `days_to_exp'
app/controllers/items_controller.rb:33:in `create'
```

**Comment by naributler** [comment]
Also, I posted this question on stackoverflow: http://stackoverflow.com/questions/43696814/ruby-nomethoderror-when-subtracting-dates

I tried one of the suggestions from there (changing `attributes` to `attr_accessor`), but it did not work.

**Comment by payne-chris-r** [comment]
Yeah, I think you want attributes. The issue is `attributes :exp_date` != `exp_date`

**Comment by payne-chris-r** [comment]
Ruby doesn't know what `exp_date` is. I think you need to say something like `object.exp_date`

**Comment by payne-chris-r** [comment]
You need to somehow get the attribute `exp_date` that belongs to the `Item`. `attributes :id, :food_name, :etc,...` is doing something _similar_ to `attr_accessor :foo`, but you definitely don't have access to the naked `exp_date` here.

**Comment by naributler** [comment]
That worked!!!!!! Thank you so much, @payne-chris-r!! Here's the final code: 
```rb
class ItemSerializer < ActiveModel::Serializer
  attributes :id, :food_name, :purchase_date, :exp_date, :store_name, :quantity,
             :purchased, :days_to_exp

  def days_to_exp
    today = Time.now.utc.to_date
    # exp_dte = exp_date
    # (exp_dte - today).to_i
    (object.exp_date - today).to_i
  end
end
```
It makes sense that we wouldn't just be able to automatically access attributes from `Item`. `object.exp_date` did the trick. Thank you!!

**Comment by payne-chris-r** [comment]
Boomsauce.
