### ISSUE TITLE
Need assistance with recreating table

### ISSUE THREAD

**Issue by rlarsonil71** [ga-wdi-boston/full-stack-project#766]
Issue Description:
I reduced complexity by starting with CRUD using one new favorite_players table.
I followed the https://github.com/ga-wdi-boston/rails-api-single-resource repo instructions following what was done for the books table without a relationship.

After getting CURL CRUD scripts to work, I dropped the favorite_players table in sql to wipe away all test data as I thought I needed to do this before adding the relationship to the users table.

I am thinking that I shouldn't have done the drop table but just delete data on the table instead.

I am trying to recreate the favorite_players table.  I have the old migration file to create the favorite_players table (from when I created it using the https://github.com/ga-wdi-boston/rails-api-single-resource repo instructions but a `$ bin/rails db:migrate` does not return anything and no favorite_players table is created.

The following is my old migration file:
```
# frozen_string_literal: true

class CreateFavoritePlayers < ActiveRecord::Migration[5.0]
  def change
    create_table :favorite_players do |t|
      t.string :player_name
      t.string :team_name
      t.string :sport
      t.string :position
      t.integer :player_number

      t.timestamps
    end
  end
end
```

How do I recreate the favorite_players table?

Once this favorite_players table is recreated, I can do the following to create a new migration with the foreign key:
$ bin/rails generate migration AddFavoritePlayerToUsers favorite_player:references

Let me know if you need more information.

Thanks!

**Comment by rlarsonil71** [comment]
I think I am going to do the following:
 - db rollback using the old migration file
 - update the migration file with the favorite_player reference

**Comment by rlarsonil71** [comment]
I need to recreate the favorite_players table in SQL so I am trying the following so that I can then do the db rollback using the old migration file:

```
CREATE TABLE favorite_players(
  id SERIAL PRIMARY KEY,
  player_name TEXT,
  team_name TEXT,
  sport TEXT,
  position TEXT,
  player_number INTEGER,
  timestamps
);
```
I tried to make the fields strings but SQL is not allowing strings so I am trying TEXT.

Can someone please assist so that I recover and move on?   Thanks!

**Comment by rlarsonil71** [comment]
I need to sit with someone to get me back on track.  Thanks!

**Comment by payne-chris-r** [comment]
DON'T WRITE YOUR OWN SQL! COME FIND ME!

**Comment by rlarsonil71** [comment]
YES, POINT TAKEN!   I sat with Jordan and Danny and I am now good by doing a rollback.

Thanks @jordanallain and @danman01 !!  

On to more FUN!  :-)
