### ISSUE TITLE
Javascript - Unable to access function from events module.

### ISSUE THREAD

**Issue by alzateja** [ga-wdi-boston/full-stack-project#767]
I am unable to access my "events" functions in my "UI" Javascript. 
In my ui.js I have :
 const albumEvents = require('./events.js')

and a function that says 

const clearAlbums = () => {
  albumEvents.test
  console.log('Album clear sucess')
  $('.content').empty()
}

in the events file, I have  a test function

const test = () => {
  console.log("123213")
}

and an exported function.
module.exports = {
  addHandlers,
  onViewAlbumDetail,
  test
}

**Comment by jordanallain** [comment]
the files aren't requiring each other are they?

**Comment by danman01** [comment]
Hey @alzateja, make sure to format code with "`". What error message are you receiving / how do you know it's not working? And, are you following an example we worked with in the past that did work?

**Comment by alzateja** [comment]
Hi guys.  Jim just helped me with the issue.  You can can't have api.js reference events.js. If events.js references api.js already reference each other.  It is some sort of circular reference issue.
