### ISSUE TITLE
Unpermitted parameters

### ISSUE THREAD

**Issue by antleo1995** [ga-wdi-boston/full-stack-project#769]
I am attempting to create an update form for my recipe. On this form, I am including the ID so i can update the correct recipe based on what is passed in. However, I am getting:
Unpermitted parameter: id
   (0.1ms)  BEGIN
   (0.2ms)  ROLLBACK

My understanding was whitelisting ignored anything else but apparently I am missing something. Curl works for updates, but not my form since it has an ID with the data passed in. 
HTML form
```html
<div class='recipe-form-div'>
    <h1>Update Recipe</h1>
    <form id='recipe-update-form'>
      <input type="text" name='recipe[id]' id="recipe-id-input" placeholder="Recipe ID">
      <input type="text" name='recipe[title]' id="recipe-title-input" placeholder="Recipe Name">
      <input type="text" name='recipe[ingredient_list]' id="recipe-ingredients-input" placeholder="Recipe ingredients">
      <input type="text" name='recipe[directions]' id="recipe-directions-input" placeholder="Recipe directions">
      <input type="text" name='recipe[prep_time]' id="recipe-preptime-input" placeholder="Recipe prep time">
      <input type='submit' name='submit' value='Update'>
    </form>
  </div>
```
Model whitelist
```ruby
  def recipe_params
    params.require(:recipe).permit(:title, :ingredient_list, :directions,
                                   :prep_time)
  end
```
Patch portion of controller
```ruby
  def update
    if @recipe.update(recipe_params)
      render json: @recipe
    else
      render json: @recipe.errors, status: :unprocessable_entity
    end
  end
```

**Comment by antleo1995** [comment]
Is there a way to explicitly ignore this parameter?

**Comment by jrhorn424** [comment]
> ```
>       <input type="text" name='recipe[id]' id="recipe-id-input" placeholder="Recipe ID">
> ```

**Comment by antleo1995** [comment]
I don't follow

**Comment by antleo1995** [comment]
I am still using to to pass to my api call to get to the right place - so if you mean to remove it then it breaks my functionality. I can find another way to pass it but I thought whitelisting ignored any other parameters.

**Comment by antleo1995** [comment]
```
const updateRecipe = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/recipes/' + data.recipe.id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```

**Comment by antleo1995** [comment]
I could really use some direct guidance here, been thrashing for well over thirty minutes and this is the final layer of my crud.

**Comment by jrhorn424** [comment]
The data object you're sending to the API has an ID, no?

**Comment by jrhorn424** [comment]
If you fixed this issue, please tell us how and close. I'll ping others for assistance as well if you need it.

**Comment by antleo1995** [comment]
I'm doing it a different way. This is now a moot point.

**Comment by payne-chris-r** [comment]
Are you still here @antleo1995 ?

**Comment by payne-chris-r** [comment]
If you want to chat about it and/or resolve it, I'm happy to help.

**Comment by antleo1995** [comment]
Appreciate you reaching out. My new method is to populate a form with the data that comes back from the record into text fields so a user only need to edit the one they want and submit the form. This alleviates a tertiary issue - once i eliminated the ID from the form submission the update was still failing unless all fields were filled in. The end goal is to have it so a user can update a single field if they so choose - such as prep time and leave the rest as is. I have the form populating as expected so i just need to get my submit button working. Currently it's refreshing my page so i made a typo somewhere most likely. 

Here is my new form for reference:

```html
    <h1> <small>Recipe Name: {{recipe.title}}</small></h1>
    <h2> <small>Recpe ID: {{recipe.id}}</small></h2>
    <div>
    <form class'recipe-form-{{recipe.id}}'>
     <ul class=“recipes”>

       <li class='ingredient_list{{recipe.id}}'>
         <input type="text" name='recipe[title]' id="recipe-title-upate" value="{{recipe.title}}">
       </li>
       <li class='ingredient_list{{recipe.id}}'>
         <input type="text" name='recipe[ingredient_list]' id="recipe-ingredients-upate" value="{{recipe.ingredient_list}}">
       </li>
       <li>
         <input type="text" name='recipe[directions]' id="recipe-directions-update" value="{{recipe.directions}}">
       </li>
       {{#if recipe.prep_time}}
       <li class='ingredient_list{{recipe.id}}'>
         <input type="text" name='recipe[prep_time]' id="recipe-preptime-input" value="{{recipe.prep_time}}">
       </li>
       {{else}}
       {{/if}}

       <input type="button" class='delete' id='{{recipe.id}}' value='delete'>
       <input type="submit" class='update' id='{{recipe.id}}' value='update'>

     </ul>
   </form>
  </div>
  </div>
```
