### ISSUE TITLE
Cannot Call POST more than once - No token id after first successful POST

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/full-stack-project#772]
When I click on the 'ADD Chore' button on my front end, it only works once in inserting a new row in the chores table. If I click the button again to add another chore, the attached picture shows the error message and location of the failure. For some reason, the token seems to be getting wiped out and I can't determine why despite more console.logs than actual code.

As an aside, this token doesn't get removed when I repeatedly click a Delete Chore. It successfully deletes the chore in the table and the token is remembered each time as I see it in the server log.

Any suggestions here as to what I'm missing to hold onto that token when I want to add a second item to the chore table.

Thanks

![screen shot 2017-04-29 at 2 26 45 pm](https://cloud.githubusercontent.com/assets/26227953/25557886/02114878-2ce9-11e7-9ae5-3ef1f9044889.png)

CHORE EVENT:

``` const onCreateChore = function (event) {
  event.preventDefault()
  const data = getFormFields(this)
  api.createChore(data)
  .then(function (data) {
    ui.createChoreSuccess(data)
  })
  .catch(ui.createChoreFailure)
} ```


==========
CHORE API:
==========
``` const createChore = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/chores',
    method: 'POST',
    data: data,
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
} ```


=================
CHORE CONTROLLER:
=================
``` class ChoresController < ProtectedController
  before_action :set_chore, only: [:show, :update, :destroy]

  # GET /chores
  def index
    @chores = current_user.chores.all

    render json: @chores
  end

  # POST /chores
  def create
    @chore = current_user.chores.build(chore_params)

    if @chore.save
      render json: @chore, status: :created, location: @chore
    else
      render json: @chore.errors, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chore
      @chore = current_user.chores.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def chore_params
      params.require(:chore).permit(:task, :priority, :due_on)
    end
end
 ```

**Comment by glasneed** [comment]
Here is the output of the server log showing a successful sign in and the insert of one chore. But once I hit the button a second time, the above error occurs:

``` Started POST "/chores" for 127.0.0.1 at 2017-04-29 14:55:23 -0400
Processing by ChoresController#create as */*
  Parameters: {"chore"=>{"task"=>"Some blasted chore", "due_on"=>"2017-05-02", "priority"=>"1"}, "submit"=>"Add Chore"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "e2d73f536135f351850063d7fc300daa"], ["LIMIT", 1]]
   (0.1ms)  BEGIN
  SQL (0.7ms)  INSERT INTO "chores" ("task", "priority", "due_on", "created_at", "updated_at", "user_id") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["task", "Some blasted chore"], ["priority", 1], ["due_on", Tue, 02 May 2017], ["created_at", 2017-04-29 18:55:23 UTC], ["updated_at", 2017-04-29 18:55:23 UTC], ["user_id", 2]]
   (1.9ms)  COMMIT
[active_model_serializers] Rendered ChoreSerializer with ActiveModelSerializers::Adapter::Json (0.25ms)
Completed 201 Created in 35ms (Views: 2.2ms | ActiveRecord: 7.2ms) ```

**Comment by glasneed** [comment]
Here is the ROUTES.rb if needed:

``` # frozen_string_literal: true
Rails.application.routes.draw do

  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
  resources :chores, except: [:new, :edit]
end```

**Comment by payne-chris-r** [comment]
It looks like the error is with the token, not with the api, but just to absolutely rule it out, can you do two identical `curl` requests one after the next? If those work, then we know we can focus on the client.

**Comment by payne-chris-r** [comment]
If those duplicate curl requests work, then you can focus on the error at hand. What happens after the ajax request is sent? What's the code in `ui.createChoreSuccess(data)`? Do you ever wipe `store.user`? If it "can't read property 'token' of undefined" what piece is it choking on?

**Comment by glasneed** [comment]
Sent two duplicate CURL requests and both worked with "201 Created". Validate they were successfully insert into the DB.  Here is one sample curl. I pasted in the token from the sign in page and used it in both CURL requests.  

Checking the createChoreSuccess next...

``` curl --include --request POST http://localhost:4741/chores \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=BAhJIiVjZTVjODcxZmVmNTNmMTM2NmRkNTQ3Y2QyYzg3OWY4NAY6BkVG--ff83c1aa2f52ca1f9e8b663c486814f09de96ede" \
  --data '{
    "chore": {
      "task": "Cut the grass",
      "priority": 2,
      "due_on": "2017-07-22"
    }
  }' ```

**Comment by conorjennings** [comment]
Sorry here is the complete CURL as first line missing...

``` curl --include --request POST http://localhost:4741/chores \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=BAhJIiVjZTVjODcxZmVmNTNmMTM2NmRkNTQ3Y2QyYzg3OWY4NAY6BkVG--ff83c1aa2f52ca1f9e8b663c486814f09de96ede" \
  --data '{
    "chore": {
      "task": "Cut the grass",
      "priority": 2,
      "due_on": "2017-07-22"
    }
  }' ```

**Comment by payne-chris-r** [comment]
Awesome, so let's walk through the code on the client. You can rule out the possibility of something funky going on in any stage of your API for this specific issue.

**Comment by payne-chris-r** [comment]
Do you ever modify `store.user`? After you create one, can you do anything? Is it JUST creating another one that doesn't work?

**Comment by glasneed** [comment]
Here is the code for createChoreSuccess 
``` const createChoreSuccess = (data) => {
  store.user = data.user
  console.log('Add Chore Success: ', data)
} ```

And yes, I can create only the first chore, but that it. It then hoses the token and none of the other buttons then work such as GET Chores or DELETE a chore. They all stop once I enter only the first successful chore.

I'll check if I ever modify store.user next..

**Comment by glasneed** [comment]
I wasn't using that store.user anywhere else in my chores project. So I just turned it off in createChoreSuccess and tested it out and the front end is working fine now after multiple inserts. I then tested a delete after doing a few inserts and it worked too. 

Thanks Chris for pointing me in the right direction here.

Now if I could only figure out how to use those 3 back ticks correctly when pasting code!


``` const createChoreSuccess = (data) => {
  // store.user = data.user
  console.log('Add Chore Success: ', data)
} ```

**Comment by payne-chris-r** [comment]
\```js
someJavascript
\```

**Comment by glasneed** [comment]
Thanks. Closing this issue now. Enjoy rest of the weekend..

**Comment by payne-chris-r** [comment]
What WAS this line doing?
```js
store.user = data.user
```
Why does it break everything? What gets passed to `createChoreSuccess`? What is `data`?

**Comment by glasneed** [comment]
I was passing in the following variables inside 'data' object that were used to insert into my chore table. None of them contained the data.user. As such I'm guessing that is why I was voiding out the user in this step after the first successful insert into the chore table when, in fact, I did not need to do that step as it is part of the authentication logic (which is more than likely where I copied it fro).

<img width="523" alt="screen shot 2017-04-29 at 6 12 38 pm" src="https://cloud.githubusercontent.com/assets/26227953/25559423/bc19abb6-2d07-11e7-9ead-1aa251bf26ff.png">

**Comment by payne-chris-r** [comment]
That's exactly right. The object (referred to as `data` in your code) passed back from the ajax request to POST a new chore is what you've `console.log`d above. 

Does it have a key called .user?
What happens when you try to access `object.keyThatDoesntExist`? 
What does it return? 
Can you assign that to something else?
What's the value of `store.user` once you're done with that line?

**Comment by glasneed** [comment]
Nope, there is no key. The value of store.user after that code was run the first time is:

 **store.user:  undefined**

which then explains why I can no longer do inserts, reads, deletes as the session user was set to undefined.

**Comment by payne-chris-r** [comment]
👍 👍 👍 👍

**Comment by glasneed** [comment]
Cheers Chris! Appreciate the help.. Closing ticket now.
