### ISSUE TITLE
Help with cURL script  - Return data with a filter condition other than ID

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/full-stack-project#773]
Hi -
So I've googled this one and gotten nowhere. I am stuck on how to write a cURL request that essentially implements this sample SQL command:

SELECT * from chores WHERE month = 10

The 2 examples of cURL requests below that implement a GET request that I've seen so far is one that just returns everything from a table and the other one returns data for one ID. 

But how do I filter data coming back in a cURL that wants to use something **other than ID** such as month number. This would give you back 1:N rows for the passed in month value.

Thanks

```  curl --include --request GET http://localhost:4741/chores \
    --header "Content-Type: application/json" \
    --header "Authorization: Token token=BAhJIiVhZDdhZDc2ZjBmOTM3MmZkYTE5NjY3ODA3M2ZiNmZjZgY6BkVG--799a86682426200bfb24708e583a310dfa61b78a" \
    --data "priority=1"

# GET ONE ITEM BACK FOR id 28
    curl --include --request GET http://localhost:4741/chores/28 \
      --header "Content-Type: application/json" \
      --header "Authorization: Token token=BAhJIiVhZDdhZDc2ZjBmOTM3MmZkYTE5NjY3ODA3M2ZiNmZjZgY6BkVG--799a86682426200bfb24708e583a310dfa61b78a" \

```

**Comment by payne-chris-r** [comment]
Where does a curl request go? What's the first "stop" in a request to a rails server?

**Comment by glasneed** [comment]
I believe it's first stop is at the controller. I understand that when I call the above curl request for ID of 28 on chores table, it is been passed here where ID is been specified in the params macro:

```  
  # GET /chores/1
  def show
    render json: current_user.chores.find(params[:id])
  end
  end 
```

So this takes care of invoking a curl script where ID is passed in. 

But what I don't follow is how write a curl script if I wanted to pass in a '10' for month attribute?  I can't just write it with /10 as that would pick up an ID of 10. And if I wrote another show method with **current_user.chores.find(params[:month])** I still don't get how it knows which one I'm trying to pass into the curl request.

If I'm not making sense, maybe we can just discuss tomorrow morning.

Thank you

**Comment by payne-chris-r** [comment]
The first step is the router. Ther router is what tells us that /books/3 routes to BooksController#show and passes a params hash where
```ruby
{
  id: 3
}
```
If you to pass more than that, you probably want to take a look at "query params"

**Comment by payne-chris-r** [comment]
Have you ever seen something like this?
https://www.google.com/search?q=foo

**Comment by glasneed** [comment]
That's exactly the type of URL I was thinking of with the question mark and vrious parameter(s) attached to it. Its strange how you don't have to do that when just passing in an ID by itself.

Either way, I'd like to implement something that allows me to pass data parameters from my front end that ends up in the WHERE clause of a SQL statement. However, as much as I'd like to learn how to do this, I may have to shelf it in order  to ensure I make the MVP components for this project and double back after the fact. It is something I do want to learn. If I get MVP working and tested, then I'll come back to this one as its nagging me...and slowing me down too :)

**Comment by payne-chris-r** [comment]
Holler if/when you do.

**Comment by glasneed** [comment]
OK, thanks Chris

**Comment by danman01** [comment]
Hi @conorjennings - were you able to implement what you wanted? If so can you close out the issue? Thanks!

**Comment by glasneed** [comment]
Hi Danny -
I was not able to implement it. I decided to put it on the back burner for now until I complete all the MVP requirements. If I have time tomorrow I’d like to see if I could implement this. So can I leave it open for now as I know I will have more questions on how to do this if I get the time. Or if you’d like to meet in the caf for 5 minutes to discuss and point me in the right direction, thats fine too.

Thank you

**Comment by danman01** [comment]
@conorjennings let's meet and figure it out, then you can move on. I think you're pretty close. I'm in the cafe now if you want to come by.

**Comment by danman01** [comment]
If you are all set, please close this issue. Thanks!

**Comment by glasneed** [comment]
Danny - Thank you for your advice on this. I'll close the ticket and post my approach if I get to it before the deadline.
