### ISSUE TITLE
Help Wanted: Issue with Authentication in Deployed App

### ISSUE THREAD

**Issue by lisamsmith100** [ga-wdi-boston/full-stack-project#774]
Hi,

When signing up and into my deployed app, I'm receiving an error.  I am not having an issue with authentication in my localhost.

Here's what I'm seeing in the console:

"No 'Access-Control-Allow-Origin' header is present on the requested resource"

https://lisamsmith100.github.io/hnd-client/
https://hnd-api.herokuapp.com/

When I googled this problem, I'm seeing a lot of information about CORS but I'm not sure what it means.

Can someone point me to a viable easy to understand source so that I can troubleshoot this?

Is there a short answer so I can continue verifying the rest of my authentication so I can focus on my working out the list items?

I think I get the gist that the api template and browser template have a conflict somewhere but I don't understand where to look.

Appreciate any help on this so I can keep trucking.

Thank you.

**Comment by lisamsmith100** [comment]
Here is a screen shot of deployed app:
![image](https://cloud.githubusercontent.com/assets/26127720/25567537/c96167b2-2dbd-11e7-8338-4816c03b7dcd.png)

**Comment by jordanallain** [comment]
Can you run `heroku config` in the terminal from the API's repo and paste in the results?

**Comment by lisamsmith100** [comment]
yes

**Comment by lisamsmith100** [comment]
```sh
$ heroku config
=== hnd-api Config Vars
CLIENT_ORIGIN:            git@github.com:lisamsmith100.github.io
DATABASE_URL:             postgres://muhnazohsekgix:f137c8b4bb733216cacd7279cd6c7e9650d4e330ce5004649c74cac6cad82337@ec2-54-243-107-66.compute-1.amazonaws.com:5432/der71791jrls8i
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_LOG_TO_STDOUT:      enabled
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:          8a2a1ac6a34d6c2f94a0a2feb9962255aa01defe4d3694625252bb638cd1bdafd512bf9d863ff4ace579240d014f86e28900d3efdea0e7c87b6290288b69214a
SECRET_TOKEN:             1faf18ec33c09239281215d3de226b9b054d7f2ce71b2dcb3e39e3974160a1d2357d9fac11e74c7bfd2c6128ce9d50667e5a5d8cf4da36c4bada2373ce0eb20c
~/wdi/projects/hnd-api (railsfeature)
$ 
```

**Comment by lisamsmith100** [comment]
I found a trailing comma in my config file.  will see if that did any good.

**Comment by payne-chris-r** [comment]
I would also remove that last comment

**Comment by payne-chris-r** [comment]
As a general rule of thumb you don't want to post tokens or sekrit keys to the internet. Esp for deployed things.

**Comment by BenGitsCode** [comment]
Develop in private mode. May even be the cause of the issue, but even if not it's a better practice.

**Comment by lisamsmith100** [comment]
Will switch the other mode and continue investigating how to correct security.

**Comment by lisamsmith100** [comment]
I switched to incognito mode but that didn't solve the issue.
All of the curl requests seems to work so I think it's something with the submit event or api file.  Investigating that file unless there's something else more specific I should review?

**Comment by lisamsmith100** [comment]
I'm still receiving an error but I have a pinpointed and possibly related question.

The url shows a double forward slash in the url

https://hnd-api.herokuapp.com//sign-in/

It works in the localhost so I'd be inclined not to make the update, push, merge, deploy.  I'll see if it causes error in localhost and then if not, give that a shot.

My config file is
```js
'use strict'

const config = {
  apiOrigins: {
    production: 'https://hnd-api.herokuapp.com/'
  }
}

module.exports = config
```
and my api file is

```js

'use strict'

const app = require('../app.js')
const config = require('../config')
const store = require('../store')
// const getFormFields = require('../../../lib/get-form-fields.js');

// authApi.signUp(authUi.success, authUi.failure, data);

const showEntries = function (data) {
  console.log('called showEntries in the entry/api.js')
  return $.ajax({
    url: config.apiOrigin + '/entries/',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

const addEntry = function (data) {
  console.log('called addEntry in the entry/api.js')
  console.log('data is' + data)
  return $.ajax({
    url: config.apiOrigin + '/entries/',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

const showOneEntry = function (data) {
  console.log('called showOneEntry in the entry/api.js')
  console.log('data is' + data)
  return $.ajax({
    url: config.apiOrigin + '/entries/',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

const updateEntry = function (data) {
  console.log('called addEntry in the entry/api.js')
  console.log('data is' + data)
  return $.ajax({
    url: config.apiOrigin + '/entries/',
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

const hideEntry = function (data) {
  console.log('called hideEntry in the entry/api.js')
  console.log('data is' + data)
  return $.ajax({
    url: config.apiOrigin + '/entries/',
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

const deleteEntry = function (data) {
  console.log('called deleteEntry in the entry/api.js')
  console.log('data is' + data)
  return $.ajax({
    url: config.apiOrigin + '/entries/',
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}

module.exports = {
  showEntries,
  addEntry,
  showOneEntry,
  updateEntry,
  hideEntry,
  deleteEntry
}

```

**Comment by lisamsmith100** [comment]
removing the additional / was not the solution.  Still searching.  The websites brought up a term "CORS".  Is there an edit to the application I should be making instead?

**Comment by payne-chris-r** [comment]
Take a look at this and see if it helps https://github.com/ga-wdi-boston/full-stack-project/issues/626

**Comment by lisamsmith100** [comment]
I reviewed the files, which matched, except I don't have "accounts," I have "entries" instead.  I continued and followed her steps, which are the same steps I have ben.
I have been pushing and deploying after each piece of functionality and I am still getting the error.  I will let this issue settle a bit and pick up in 30 minutes.

**Comment by lisamsmith100** [comment]
I am still not finding the solution.  Will try again tomorrow.

**Comment by jim-moody** [comment]
Did you run this command when setting up the API?

`heroku config:set CLIENT_ORIGIN=https://yourgithubname.github.io`

If you don't remember, you can check in your heroku dashboard under settings.

And then click "Reveal Config Vars" and check to see if you have something like this:

<img width="829" alt="screen shot 2017-04-30 at 10 33 18 pm" src="https://cloud.githubusercontent.com/assets/26190589/25570664/4919e164-2df5-11e7-88a0-34018de69583.png">

**Comment by lisamsmith100** [comment]
I think so, we were pretty diligent in running through each step, but I’ll give it another go.
Thanks!

**Comment by lisamsmith100** [comment]
The issue is resolved.  This error was cleared by re-running the command Jim Moody suggested as follows:
```sh
heroku config:set CLIENT_ORIGIN=https://lisamsmith100.github.io
```

I was using the following, causing the error:

```sh
heroku config:set CLIENT_ORIGIN=https://lisamsmith100.github.io/hnd-client/
```

Thank you, Jim.

**Comment by donpowers** [comment]
I had the same error Lisa had.  My error was resolved when I updated **config.js(the production line)** and did a **grunt build**, then a **grunt deploy.**

Thanks Lisa and Angela for your assistance!
