### ISSUE TITLE
Requirements questions - change prompts success needed?

### ISSUE THREAD

**Issue by Ryaong792** [ga-wdi-boston/full-stack-project#775]
I am making a todo list app.
When I add a List or task do I need to have a prompt stating it created successfully? I have it to where it auto auto populate when or if you have it pulled up on the front end.  I would think that since it shows the item added I would not need a prompt but I wanted to be safe and ask if that would be consider a user facing bug or working as design.

Thanks,

Ryan

**Comment by payne-chris-r** [comment]
That sounds fine.

**Comment by Ryaong792** [comment]
donka
