### ISSUE TITLE
Trouble saving game and phrase object locally like player object

### ISSUE THREAD

**Issue by octater** [ga-wdi-boston/full-stack-project#778]
I can create a game and looks like all 3 objects are saved locally.  When I go to play the game, only the player object seems to be populated.  Here are some screen shots of the local objects after the create new game.

<img width="388" alt="screen shot 2017-05-01 at 9 18 07 am" src="https://cloud.githubusercontent.com/assets/26232064/25580493/6c2e681e-2e4f-11e7-8f2f-32c82eb244a7.png

<img width="1120" alt="screen shot 2017-05-01 at 9 17 21 am" src="https://cloud.githubusercontent.com/assets/26232064/25580513/9205c1fe-2e4f-11e7-8572-f6735a93fedf.png">

<img width="606" alt="screen shot 2017-05-01 at 9 17 43 am" src="https://cloud.githubusercontent.com/assets/26232064/25580512/8cbf030e-2e4f-11e7-8ebd-9d87cd2f8375.png">

<img width="364" alt="screen shot 2017-05-01 at 9 18 00 am" src="https://cloud.githubusercontent.com/assets/26232064/25580503/85384866-2e4f-11e7-9061-7ed7d672bc3e.png">
">
 when I get to my gameplay.js, I require them all
```js
const game = require('./game.js')
const player1 = require('./player1.js')
const gamePhrase = require('./gamePhrase.js')

but when displaying, only player1 has data

  console.log('here is the gamePhrase ', gamePhrase)
  console.log('here is the game ', game)
  console.log('here is the user ', player1)
  debugger

**Comment by jordanallain** [comment]
need some context here. what are the resources other than users? what is the ERD between your resources?

**Comment by octater** [comment]
hey Jordan, can we chat about this?  5 minutes tops

**Comment by jordanallain** [comment]
terry i'm not even sure what it is you are trying to do or what your app is. please provide some more information.

**Comment by octater** [comment]
my app is a hangman game.  I have a user object, a game object and a phrase object.  I have a player1.js defined to keep my signed-in user.  I am trying to do the same thing with the phrase that was generated and the game that was built.  I have both a phrase.js and game.js.  these both seem to have data after the create game. But when I try to use either phrase or game within the game logic, both are empty, but player1 still has data.

**Comment by jordanallain** [comment]
So there is Users, Phrases and Games? What is the relationships between these resources? Do Users have many Games and Games have one Phrase?

**Comment by octater** [comment]
correct.  I randomly read a row from the phrase table and associate that id to the games table as a foreign key.  I want to keep a copy of the phrase, like player1, so when I build the board, i don't have to read the database for the phrase associated with the id in games

**Comment by jordanallain** [comment]
Can you post the function(s) that GET the random Phrase and POST it to the Games table?

**Comment by octater** [comment]
Hey Jordan,  I need to leave this open for a bit longer.  I am finishing up something else and will get back to this shortly.

Thanks

**Comment by octater** [comment]
Closing this issue.  my console log statement was the issue
