### ISSUE TITLE
having issue pulling the data-ID for LIST on handlebars

### ISSUE THREAD

**Issue by Ryaong792** [ga-wdi-boston/full-stack-project#779]
Issue:
 1. need to be able to pull data-id from List.  Please see handlebars:

Action:
1. To delete a TASK from LIST.  

Table relations:
User to many Lis
List to many list.

```
{{#each list}}
    <a data-id="{{this.id}}" data-name="{{this.name}}" class='list{{this.id}} toggle'><p>
      {{this.name}}
      <i class="material-icons add_task" name:"button">note_add</i>
      <i class="material-icons update" name:"button">mode_edit</i>
      <i class="material-icons delete" name:"button">delete</i>
</p>
      </a>
<ul class="inner">
  {{#each this.tasks}}
      <li data-id="{{this.id}}"><p>{{this.name}}
        <i class="material-icons delete_task" name:"button">delete</i>
      </p>
      </li>
      {{/each}}
    </ul>
{{/each}}
```
The way I'm finding the data-ID is thought my event JS

```
const deleteTask = function () {
  event.preventDefault()
  console.log($(this))
  console.log($(this).closest('li').data('id'))
  todoapi.deleteTask($(this).closest('a').data('id'), $(this).closest('li').data('id'))
    .then(todoui.deleteTaskSuccess)
    .catch(todoui.deleteTaskFailure)
  $(this).closest('li').hide()
}
```
the man problem is that I'm only able to pull the data-id for task (see closest li) but when I try to pull
the data-id from the list (see <a data=id) it returns undefined.  I have confirmed via console.log does not pull data but only the Task section works.  On the rails API it shows that the ID=0 since its not passing anything.  

This code should work since my Delete list works and when I used another handlebar with the same thing it works ok.  I just don't understand why the its not pulling the info.

Been stuck on this most yesterday.  Please help.

**Comment by jordanallain** [comment]
have you tried to just console.log the $(this).closest('a') in that function to see what it is grabbing?

**Comment by Ryaong792** [comment]
undefined on console log

**Comment by Ryaong792** [comment]
when I do the ($(this)) on console.log to see where this was showing it does not find it in the DOM

**Comment by jordanallain** [comment]
not sure what you mean by your last comment. you tried console.logging $(this) and it was undefined?

**Comment by Ryaong792** [comment]
2017-05-01 10:06:15.529
events.js:27 
[i.material-icons.delete_task]
0
:
i.material-icons.delete_task
length
:
1
__proto__
:
Object(0)

**Comment by Ryaong792** [comment]
that's what the console for $(this) shows

**Comment by jordanallain** [comment]
okay so you may need to try traversing the DOM in a way other than `$(this).closest('a')` there are lots of different jQuery methods for traversing have you tried any other ones?

**Comment by Ryaong792** [comment]
yes I tried the attribution and parent etc.  I think I tired most out there but still getting undefined.  Been working on this most of yesterday

**Comment by jordanallain** [comment]
so you are trying to use the data-id from an anchor tag with a delete button? have you tried just storing it on the button instead of the anchor tag?

**Comment by samguergen** [comment]
have you tried using: {{#each this.list}} ?

**Comment by Ryaong792** [comment]
I have not will try that

**Comment by Ryaong792** [comment]
Not sure how to write that in JS do I just do a {{#each this.list}.data('id')?

**Comment by Ryaong792** [comment]
I would like to request someone to see me after lunch if possible if this is not resolved by then.

**Comment by jordanallain** [comment]
did you try my suggestion?

**Comment by Ryaong792** [comment]
No I'm not sure how to do that.  that's why I was doing it this way

**Comment by Ryaong792** [comment]
Issue resolved.
FIX: added the following to the delete task js.
```
todoapi.deleteTask($(this).data('id'), $(this).closest('li').data('id'))
```
and on my handlebars got the list ID by adding it to the button:
```
<i class="material-icons delete_task" data-id="{{this.list_id}}" name="button">delete</I>
```
closing
