### ISSUE TITLE
error when registering

### ISSUE THREAD

**Issue by gracenjambi** [ga-wdi-boston/full-stack-project#78]
Whenever I try and Login I see that the Server has acknowledged and I am able to log in however I am not able to register. Please see below:

script.js:29 click
script.js:43 {
    "user": {
        "id": 1,
        "email": "grace@example.com",
        "current_user": false,
        "token": "765ebce141dde9f3a2007dd9cae293f7",
        "gardens": [
            {
                "id": 2,
                "name": "garden_#{i}_#{name}",
                "kind": "box",
                "crops": []
            },
            {
                "id": 3,
                "name": "garden_#{i}_#{name}",
                "kind": "box",
                "crops": []
            },
            {
                "id": 4,
                "name": "garden_#{i}_#{name}",
                "kind": "box",
                "crops": []
            }
        ]
    }
}
script.js:89 click
script.js:110 Uncaught TypeError: farmAPI.addGarden is not a function

**Comment by gracenjambi** [comment]
This is the error on the server. So the POST is starting its an Active Record issue.
Started OPTIONS "/register" for 127.0.0.1 at 2015-11-12 14:24:25 -0500

Started POST "/register" for 127.0.0.1 at 2015-11-12 14:24:25 -0500
Processing by AuthController#register as HTML
  Parameters: {"credentials"=>{}}
Completed 400 Bad Request in 0ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: credentials):
  app/controllers/auth_controller.rb:37:in `credentials'
  app/controllers/auth_controller.rb:17:in`register'

  Rendered /home/grace/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.9ms)
  Rendered /home/grace/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.4ms)
  Rendered /home/grace/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.6ms)
  Rendered /home/grace/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (15.1ms)

**Comment by GA-MEB** [comment]
Based on reading your error message, it doesn't look like you've sent any data from your front end in making the POST request for `register`. Have you tested the `register` action using `curl` or Postman? Can you confirm that it's working on the back end?

**Comment by gracenjambi** [comment]
I have now confirmed it works. The server is giving me an error with the user controller. I tried changing it and it affected my login which works

So I left it alone.

**Comment by MattB-GA-Boston** [comment]
Back-end issue.

**Comment by GA-MEB** [comment]
Back end wasn't working. Grace is currently testing the API with Postman.
