### ISSUE TITLE
Deploying my site is breaking it

### ISSUE THREAD

**Issue by antleo1995** [ga-wdi-boston/full-stack-project#780]
For whatever reason my get request URLs are all jacked up. Sign in works fine, and everything works fine locally, but viewing the requests looks like this:
recipe-card-backend.herokuapp.com/recipes:1 GET https://recipe-card-backend.herokuapp.com/recipes 500 (Internal Server Error)

recipe-card-backend.herokuapp.com/recipes/:1 POST 

I am guess it's the colon, but I have no idea why it is breaking on deployment. 

Here is my create api call:
``` javascript
const addRecipe = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/recipes',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```

**Comment by samguergen** [comment]
Have you tried console.logging the result of config.apiOrigin, to make sure that it is not set to localhost when you deploy?

**Comment by antleo1995** [comment]
If you look at the error message it clear this is not the case. Sign in works but not anything related to my recipe stuff. I am going to check and make sure my database is migrated properly.

**Comment by jordanallain** [comment]
you were seeing this in the console? 

`recipe-card-backend.herokuapp.com/recipes:1`

if so that looks like its missing a slash where the colon is.

**Comment by antleo1995** [comment]
I tried adding that. And it does not have it in the sign up stuff. Not sure why its adding a colon but that is not any difference in my code. Works on the local copy just like that.

**Comment by jordanallain** [comment]
is it just get requests or all requests other than authentication actions?

**Comment by antleo1995** [comment]
Requests other than auth - here's what the logs say:
".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "65423c70940052c4985cd0d6a84ace87"], ["LIMIT", 1]]
2017-05-01T14:16:36.106398+00:00 app[web.1]: [5457f2e7-e490-4d3d-a803-d5b142ab0ee4] Completed 500 Internal Server Error in 5ms (ActiveRecord: 1.3ms)
2017-05-01T14:16:36.106894+00:00 app[web.1]: [5457f2e7-e490-4d3d-a803-d5b142ab0ee4]   
2017-05-01T14:16:36.106935+00:00 app[web.1]: [5457f2e7-e490-4d3d-a803-d5b142ab0ee4] ActiveModel::UnknownAttributeError (unknown attribute 'user_id' for Recipe.):

Not sure why it is giving me that since it does work locally and I don't know what would change. I did try another db migrate to no avail.

**Comment by antleo1995** [comment]
I have psql configured to see what's on my prod DB and that field is there.

**Comment by jordanallain** [comment]
did you do a db migrate or a heroku migrate?

**Comment by antleo1995** [comment]
yup that's what i mean when i say i ran it. sorry, should have specified

**Comment by antleo1995** [comment]
Ended up having to add user_id to my recipe params. Will test further but seems happy now.
