### ISSUE TITLE
Exceeds Discussion

### ISSUE THREAD

**Issue by cpm5041** [ga-wdi-boston/full-stack-project#781]
I would like to request a discussion for what it would mean to exceed expectations on this full stack project.

**Comment by samguergen** [comment]
Can you meet me in the lounge in 5min?

**Comment by payne-chris-r** [comment]
@cpm5041 I think we should talk.

**Comment by payne-chris-r** [comment]
Leave this open until I can sit with you.

**Comment by cpm5041** [comment]
I spoke with Sam and Chris and will work towards exceeding based on their feedback. Thank you!
