### ISSUE TITLE
Server Response question

### ISSUE THREAD

**Issue by MattKwonDo** [ga-wdi-boston/full-stack-project#784]
in my app if a user clicks the button to create a new item but doesn't enter any text, the server will send back a 422 (Unprocessable Entity) message. The message only shows in the console, it is not rendered in the browser. Is this considered a bug or error that would prevent me from meeting requirements? or is this expected behavior?

**Comment by tvcrawley** [comment]
Question: If the user expects an action to happen and it fails, how would the user know they did something wrong?

**Comment by MattKwonDo** [comment]
If i included feedback in the browser, they would. If I did that, but still allow them to try to create a blank new item and get the 422 message back, is that considered a bug/error?

**Comment by tvcrawley** [comment]
Logically, you wouldn't want an item with no data created. If the user has feedback, then it would no longer be a user facing bug; however, you could potentially have a ton of empty objects in your database. 😥 

While this wouldn't prevent you from meeting requirements, I'd suggest to 
**revisit this once you feel your app does meet requirements**. 

For now, you can consider this a low priority issue.

**Comment by danman01** [comment]
Sounds like you want to validate that there is input before making the server request. Ideally, you don't want to send incorrect things to your server and rely on your api to catch them, but sometimes it's not possible to prevent. If you have the time, check out how you can validate input in a form field using javascript / jQuery.

**Comment by MattKwonDo** [comment]
will do, thanks!
