### ISSUE TITLE
Parsing and finding specific value from API Response

### ISSUE THREAD

**Issue by jscohen** [ga-wdi-boston/full-stack-project#785]
Hello all,

I'm trying to integrate a third party API that lets me grab song lyrics into my project.  I've made a successful API call for a specific track in Ruby, however the response I am getting is a wall of crazy text: 
```sh
{"message"=>{"header"=>{"status_code"=>200, "execute_time"=>0.011421918869019, "available"=>13}, "body"=>{"track_list"=>[{"track"=>{"track_id"=>86790678
```

There's a lot more, but all I need here is the track ID, which I will use to get lyrics.  I'm having trouble grabbing that value from this hash.  I did the following:

'''
response = (above text)

key = response.has_key?("track_id")

p key
'''

This returns false.  I'm not sure why it doesn't see the track_id key.  Could it be because of the [] right before track?

Thanks,

 - Jon

**Comment by jscohen** [comment]
Also, I am parsing this as a JSON hash so I also tried iterating through it recursively, but I still can't get the key:

```ruby
def ihash(hash)
  hash.each_pair do |k, v|
    if k == 'track_id'
      p k
      break
    elsif v == 'track_id'
      p v
      break
    elsif v.is_a?(Hash)
      ihash(v)
      if v.has_key?("track_id")
        p v
      end
    end
  end
end
```

**Comment by payne-chris-r** [comment]
It's probably because the response's top level is `track_list`, not `track_id`. I'm not sure `has_key?` drills down any further than once...

**Comment by BenGitsCode** [comment]
Firstly, you have single quotes instead of back ticks for your code fences. Change them to back ticks the ones above tab, and add the type of file next to the first set of backticks e.g. (```ruby) I edited the first one, please edit the rest to match.

I think Chris might be right, can you make those edits as well?

**Comment by scottyscripts** [comment]
maybe first get the selector you need to obtain `track_list` from the hash then iterating over that array.

**Comment by jscohen** [comment]
So I was able to resolve this issue, although not in an elegant way.

The iteration is as follows:

```ruby
  def trackhash(hash)
    hash.each_pair do |k, v|
      v.each do |key, value|
        if key == 'body'
          value.each do |key1, value1|
            value1.each do |i|
              i.each do |key2, value2|
                value2.each do |key3, value3|
                  if key3 == 'track_id'
                    return value3
                  end
                end
              end
            end
          end
        end
      end
    end
  end
```

**Comment by jscohen** [comment]
Thanks everyone for the help!
