### ISSUE TITLE
ajax requests: login

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/full-stack-project#79]
error is XMLHttpRequest cannot load http://localhost:3000/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 400.

Tried to establish through 5000 server, keeps throwing this error.

login: function (credentials, callback) {
    this.ajax({
      method: 'POST',
      // url: 'http://httpbin.org/post',
      url: this.url + '/login',
      contentType: 'application/json; charset=utf-8',
      data: JSON.stringify(credentials),
      dataType: 'json'
    }, callback);
  },

  $('#login').on('submit', function(event) {
    event.preventDefault();

```
var credentials = ('credentials', form2object(this))
proj_twoapi.login(function(err, data){
  debugger;
  if (err) {
    console.log(err)
  } else {
  $("#login").hide();
  $("#logout").show();
  token = data.user.token;
  id = data.user.id;
  }
});
```

  });

**Comment by srhoulam** [comment]
Your submit handler is very incorrect starting here:

`var login = $(this).done(function(data){`

The object returned by using the jQuery function (`$`) does not have a `done` method. What were you actually trying to do?

**Comment by sarabrentmccoy** [comment]
Edited above code.

**Comment by srhoulam** [comment]
Are there any error messages you can share?

**Comment by sarabrentmccoy** [comment]
error is XMLHttpRequest cannot load http://localhost:3000/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 400.

**Comment by sarabrentmccoy** [comment]
I've tried restarting the server.

**Comment by gaand** [comment]
Does the server produce error output?

**Comment by sarabrentmccoy** [comment]
ActionController::ParameterMissing (param is missing or the value is empty: credentials):
  app/controllers/auth_controller.rb:38:in `credentials'
  app/controllers/auth_controller.rb:7:in`login'

**Comment by srhoulam** [comment]
Sarabrent, that means you're running your front-end by opening it as a file in the browser. This will prohibit you from making cross-origin AJAX requests. You need to go into your front-end directory and run `rubys`. You can then access your front-end by navigating to `localhost:5000`.

**Comment by sarabrentmccoy** [comment]
Ok, running rubys, accessing from localhost:5000, have closed opened front-end file in browser, still getting same error in console 

XMLHttpRequest cannot load http://localhost:3000/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access. The response had HTTP status code 400.

**Comment by gaand** [comment]
Did you use my `project2-api` repo to create your api?

**Comment by sarabrentmccoy** [comment]
Yes

**Comment by srhoulam** [comment]
She was missing the `wrap` function and not passing credentials to her login function. All is well now.
