### ISSUE TITLE
Async ajax request not executing promise function

### ISSUE THREAD

**Issue by angmas** [ga-wdi-boston/full-stack-project#790]
Description: My ajax POST promise is not being executed. I think this has to do with circular requires happening between the files. If this is the case, I would like some direction on best practices for handling this.

Steps to recreate:
1. Sign In as email: a, password: a
2. Click on New Note
3. Fill out some fields and click on Save button
4. Look at console messages

Expected Result: 
XHR finished loading: POST "http://localhost:4741/notes".
createNoteSuccess ran:  {Object}

Actual:
XHR finished loading: POST "http://localhost:4741/notes". 
(no console message from the createNoteSuccess promise .

Additional details:
1. Code flow diagram below. Blue lines are when files are required by another file. Black lines are the calls.
[code flow2.pdf](https://github.com/ga-wdi-boston/full-stack-project/files/970649/code.flow2.pdf)

2. console log snapshot from local host execution:
<img width="1474" alt="screen shot 2017-05-02 at 9 29 59 am" src="https://cloud.githubusercontent.com/assets/26231241/25620124/5a2cb6bc-2f1b-11e7-91da-02c3ee08be49.png">

3. note/events.js code next to note/ui.js code
<img width="1262" alt="screen shot 2017-05-02 at 9 31 35 am" src="https://cloud.githubusercontent.com/assets/26231241/25620454/6e592610-2f1c-11e7-942e-9cfbaefe2fcf.png">

**Comment by angmas** [comment]
updated code flow diagram - added a an arrow showing navPage being required by note/ui.js. I am guessing the problem has to do with all of the circular requiring.

**Comment by danman01** [comment]
This is the best issue I've seen. Thank you for the details! 

I'm looking into the jquery ajax docs: http://api.jquery.com/jquery.ajax/ to see what else we could try here...one initial thing I would do is use the debugger within the chrome dev tools as opposed to console logs, but both get to the same result, telling you if your code enters a certain function.

Did it work at some point, and then stop working?

**Comment by angmas** [comment]
Any help would be appreciated. I am taking a break from this for now to focus on getting my delete and update calls coded.

**Comment by danman01** [comment]
Could you post your api functions?

It looks like we can use a few more jqXHR functions that are available to us on the jquery ajax object: `done(), .fail(), .always()` and maybe try `beforeSend`  option to see what's going on in and around the ajax request. More: http://api.jquery.com/jquery.ajax/#jqXHR

**Comment by angmas** [comment]
I'm not sure I understand what you mean by post. Do you mean you want to see my api calls (see below from my repo).
[https://github.com/angmas/my-note-client/tree/master/assets/scripts/note](url). I'll read up on those other functions you mentioned above and play with them after I get done with my delete function.

Thanks!

**Comment by danman01** [comment]
Took a look at your api.js file and that all seems fine. When you get back to debugging this, I would start with using the chrome devtools debugger to verify the flow of code and the objects are what you expect.

**Comment by scottyscripts** [comment]
Do you mean to pass `ui.createFailure` or `ui.createNoteFailure` to the .catch method. Try to log something in that .catch function to make sure that isn't executing instead.

**Comment by payne-chris-r** [comment]
Is there a link I should be able to recreate your steps? Can you post your entire events.js and ui.js files?

**Comment by payne-chris-r** [comment]
The issue is that createNoteSuccess isn't running?

**Comment by payne-chris-r** [comment]
Are you getting something like `createNoteSuccess is not a function`?

**Comment by angmas** [comment]
nope, just no response at all. I think it has to do with requires I am doing across all of it (see my diagram above). my repo is here: [https://github.com/angmas/my-note-client](url).

I'll figure it out eventually-- worst case scenario is I'll make the user click on buttons to initiated some actions instead of "chaining" async calls. I don't want anyone to spend too much time looking into this when others in the class need more help. I really appeciate your time! 

I'll keep this open for now so that I can post my solution when I get to it later tonight.

**Comment by angmas** [comment]
Ok, I spent some time to rethink the code flow. What I implements seems to have fixed my problem. I am closing this issue.

I drew up the following plan and then followed it. The list of functions are not complete 
[New structure.pdf](https://github.com/ga-wdi-boston/full-stack-project/files/973844/New.structure.pdf)
and they may not be name 100% correct, but I think you will get the gist of what I did. I essentially consolidated the two events.js files (auth and note), consolidated my UI code to one file.

Thanks, everyone, for your time!

**Comment by angmas** [comment]
Even though I resolved my issue, Chris P. mentioned that he (or anyone?) can share some code organizational tips that could improve upon my solutions. I am definitely interested learning those. This is the reason for why I reopened this issue.

**Comment by angmas** [comment]
Closing issue. Chris whiteboarded the promise chain for my events file. 

Thanks, Chris!
