### ISSUE TITLE
Need help getting data-id from handlebars out to form outside of handlebars

### ISSUE THREAD

**Issue by Ryaong792** [ga-wdi-boston/full-stack-project#792]
I'm attempting to add and update form outside of the handlebars but unsure how to get the data-id over from the handlebars when created. As of right now I'm using a prompt to change the name of the list.  But I want to move it to form that I created in my HTML body.

```
{{#each list}}
    <a data-id="{{this.id}}" data-name="{{this.name}}" class='list{{this.id}} mdl-cell mdl-cell--1-col mdl-navigation__link toggle
    animated flipInY'><p>
      {{this.name}}
      <i class="material-icons delete" name="button">delete</i>
      <i class="material-icons update" name="button">mode_edit</i>
      <i class="material-icons add_task" name="button">note_add</i>
    </p>
  </a>

<ul class="inner">
  {{#each this.tasks}}
      <li class="li-table" data-id="{{this.id}}"><p>{{this.name}}
        <i class="material-icons delete_task" data-id="{{this.list_id}}" name="button">delete</i>
        <i class="material-icons update_task" name="button">mode_edit</i>
      </p>
      </li>
      {{/each}}
    </ul>
{{/each}}
```

This is the form I was thinking of using for all the update on list.

```
<dialog class="mdl-dialog dialog4"><i class="material-icons close_ul" name:"button">close</i>
  <p>
  <h3 class="mdl-dialog__title">Update List</h3></p>
  <div class="mdl-dialog__content Update_list form-list">
    <form class="update">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" name="list[name]" id="update-list">
        <label class="mdl-textfield__label" for="update_list">Name...</label>
      </div>
      <button class="mdl-button mdl-js-button mdl-button--primary create-button" type="submit" name="submit">Create
      </button>
    </form>
  </div>
</dialog>
```

I want to put the data-id=   to the button class but not sure how can I get the ID of the list from handlebars to an outside form.   Unless prompts are legal to use then I can close this :) otherwise will need help getting the form attach.

**Comment by danman01** [comment]
The list is simply data that is coming from your javascript and injected into the handlebars template. so, if you really want to get access to the list, but want it outside of handlebars, you can use javascript to access the data stored within `list`

I'm not sure that answers your question though. If you post some screenshots of your before form and what you hope to have after your changes, that may help.

I would not use prompts (asking the user for the list id right?) because we can do better than that! It's not illegal per se though...

**Comment by Ryaong792** [comment]
the prompt I had them do is just input in the change name.  what I'm trying to do is have them update the name of the list they want to edit.  As of right now I have them click on the update icon, prompt shows up.  they input their change name and it updates my list.  Now I want to use a nicer form outside of the handlebars and with it update the data but how can the form determine what list they want to update to change its name.

**Comment by Ryaong792** [comment]
I mean I guess if I have to, I could take the data-id from the handlebars of the task created.
create a function to addClass with that data id as the input to the form, then do the search for that class form to get then  id class to input for the data for the request but I rather have a clean way then what I'm thinking lol

**Comment by jordanallain** [comment]
you can store the ID temporarily like how we use the store to save user data or game data in tic tac toe.

**Comment by Ryaong792** [comment]
but with handles bars creating or updating the list will the store data still be there?

**Comment by jordanallain** [comment]
the data should be there unless you delete or over write it.

**Comment by Ryaong792** [comment]
Will play around with it and will get back with you guys.

**Comment by Ryaong792** [comment]
I'm going to work on this tonight I'm pretty burnt on it and will fix up my other items first.  Just need to step away from the problem for now.

**Comment by Ryaong792** [comment]
Will leave it as is for now Will work on other bugs I need to resolved first by the morning.
