### ISSUE TITLE
Best practices for pulling images from other websites

### ISSUE THREAD

**Issue by naributler** [ga-wdi-boston/full-stack-project#793]
I curious whether there are any best practices/protocols for pulling background images from other websites. Should we give credit to the source website in a visible way on our app?

**Comment by BenGitsCode** [comment]
This always a tough one, where are the images you want to use? Are they copyrighted? Who owns them?

**Comment by BenGitsCode** [comment]
This may be helpful

![](https://i.kinja-img.com/gawker-media/image/upload/qxptplnxqtrhme965gal.jpg)

**Comment by naributler** [comment]
Thanks, Ben! I used one of the food images from this website: http://bojongourmet.com/2016/06/ricotta-and-roasted-beet-tart-with-beet-greens-pesto-gluten-free/

I found the website via Pinterest. Since each of these photos has a Pinterest tag, it seems like the creater intended for these images to be publicly viewed. Seems like it's alright to redistribute these images for personal purposes.

**Comment by BenGitsCode** [comment]
I think that's a fair assessment 👏  I always try to credit ownership somewhere, even if its license permits use.

Most websites like that (recipes, dieting etc) tend to do their own photography and put a lot of work into it—but I bet they care more about their recipes and other material than their images being used for non-commercial use like this, but assumptions are dangerous. 

Just in case (just to be nice, if anything) I would include some attribution either in a small footer or in your README, or both. 

I find people are always more understanding when you credit them

**Comment by naributler** [comment]
Sounds great! I'll include a credit in my README. Thank you! :)
