### ISSUE TITLE
Invoke a function inside another function 

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/full-stack-project#795]
I am trying to call another function (onGetChores) inside a function (onDeleteChore). Basically, I just want to fire off the onGetChores method that does a SELECT * for the entire table after I do a DELETE function. 

I've tried both onGetChores and this.onGetChores and it does not call that function on the last liine of the code below after a successful delete has occurred.  Both functions reside in the same JS script.

This onDeleteChore function is invoked in my handler as follows:

``` $('#delete-chore').on('submit', onDeleteChore) ```

``` const onDeleteChore = function (event) {
  event.preventDefault()
  const data = getFormFields(this)
  api.deleteChore(data)
  .then(function (data) {
    ui.deleteChoreSuccess(data)
  })
  .catch(ui.deleteChoreFailure)
  console.log('>>>About to call get chores inside onDeleteChore')
  onGetChores
} ```

Thanks

**Comment by jordanallain** [comment]
does it show your console log?

`console.log('>>>About to call get chores inside onDeleteChore')`

**Comment by glasneed** [comment]
Yes, it shows the console.log: 
``` console.log('>>>About to call get chores inside onDeleteChore')```

 I also have a console.log at the beginning of onGetChores and it does not get outputted to the console. 

``` const onGetChores = (event) => {
  event.preventDefault()
  console.log('>>>Now calling onGetChores  function')
  api.getChores()
    .then(ui.getChoresSuccess)
    .catch(ui.failure)
} 
```

**Comment by danman01** [comment]
With javascript, when you define a function, it is defined within a certain scope. If you do not have access to that function inside another, make sure it is in the correct scope. You can place a debugger on the line above your call to onGetChores, and see if you have access to that function. 

So, what file is `onGetChores` defined in, what is its scope, and what file and function are you calling `onGetChores` from, and what is its scope?

**Comment by glasneed** [comment]
Danny -
``` onGetChores ``` is defined in the same JS file as ``` onDeleteChores ```

RE "You can place a debugger on the line above your call to onGetChores, and see if you have access to that function"
I believe thats what I showed above in my comments where I can see the console.log of :  ``` console.log('>>>About to call get chores inside onDeleteChore') ```
However, I never make it to the second console.log inside ``` onGetChores ``` as follows:  

``` 
const onGetChores = (event) => {
  event.preventDefault()
  console.log('>>>Now calling onGetChores  function')
  api.getChores()
    .then(ui.getChoresSuccess)
    .catch(ui.failure)
} .  ```

Can we meet to discuss as I'd like to close this last issue before I start into deployment and documentation.

Thank you

**Comment by danman01** [comment]
Sure, coming to find you now to see if we can figure it out.

**Comment by glasneed** [comment]
To close this item, Danny helped me figure out that I was only passing the reference variable of the function rather than actually invoking the function itself using ```  onGetChores() ```
I also had an issue with the ``` event.preventDefault() ``` which was preventing my page from been displayed correctly. 
Here was the final solution: 
```
const onDeleteChore = function (event) {
  event.preventDefault()
  const data = getFormFields(this)
  api.deleteChore(data)
  .then(function (data) {
    ui.deleteChoreSuccess(data)
    onGetChoresApi()
  })
  .catch(ui.deleteChoreFailure)
}

const onGetChoresApi = () => {
  api.getChores()
    .then(ui.getChoresSuccess)
    .catch(ui.failure)
}
```

Thank you again for your assistance with this..
