### ISSUE TITLE
Last Hurdle to completion: handlebars buttons (1 of 2)

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/full-stack-project#796]
Hi, I have 2 roadblocks until I am done! They are related to handlebars. I will create 2 issues and make references to the other. 

1 of 2:  Get the reviews of just the current reviewer
[2 of 2: update/delete individual reviews from buttons within handlebars](https://github.com/ga-wdi-boston/full-stack-project/issues/797)

I am able to push a button and get all reviews created. I am unable to just the reviews of the user that is logged in. 

The getReviews in my api file looks like this and it works. :
```
const getReviews = () => {
  return $.ajax({
    url: config.apiOrigin + '/reviews/',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```

I understand that I need the reviews that belong to the current reviewer that belong to the current user. Some of my troubleshooting efforts include:
1. Updating my serializers, which currently look like this (and work for all of my other crud actions):
```
class ReviewerSerializer < ActiveModel::Serializer
  attributes :id, :username, :industry, :user
end
```
```class ReviewSerializer < ActiveModel::Serializer
  attributes :id, :review_date, :review_text, :reviewer
end
```
I attempted to add :review to the reviewers serializer, to make the review data available in the reviewers object. This not only didn't work, it broke other CRUD actions. 

2. modifying the above API call to include the reviewer_id in the authorization. I was never able to make that work.

**Comment by jordanallain** [comment]
so do you want to change the index method so that it only returns current user's reviews? or do you want another method that handles only the current user's reviews?

**Comment by awoodrum87** [comment]
Well, I like the 'get all reviews' functionality. So I guess I want the index to work how it does now, with another method that handles only the current user's reviews?

**Comment by jordanallain** [comment]
any ideas for how to go about that?

**Comment by awoodrum87** [comment]
not a clue. the following code does not work:

from reviews_controller:
```
  def index
    @reviews = current_user.reviewer.reviews.all

    render json: @reviews
    # @reviews = Review.all
    # render json: @reviews
  end
```
I thought changing this would return just the reviews of the current user. I have also tried:
`@reviews=current_user.reviews.all`

It did not work either

**Comment by jordanallain** [comment]
how are the relationships set up between users, reviewers, and reviews?

**Comment by awoodrum87** [comment]
users |---| reviewers |----< reviews
(users have a 1:1 with reviewers. reviewers have a 1:many with reviews)

**Comment by jordanallain** [comment]
so it sounds like you need to find all the reviews that are associated with a specific reviewer id, does that sound accurate?

**Comment by awoodrum87** [comment]
yes

**Comment by jordanallain** [comment]
so the route will need the id of the reviewer in the ajax request. any thoughts on how to proceed with this?

**Comment by awoodrum87** [comment]
yes i know that. 
I have tried adding store.review.id to the end of the route below. (in create review success data.review is set to store.review)

```
const getReviews = () => {
  return $.ajax({
    url: config.apiOrigin + '/reviews/',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```

**Comment by scottyscripts** [comment]
In our controller, how would we get the reviewer_id based upon the current_user's id? 
once we do that we can select from reviews where reviewer_id is ___

**Comment by scottyscripts** [comment]
Can you post the code from your models that define relationships between these entities?

**Comment by awoodrum87** [comment]
I actually just got this under control!

so I created a custom in my back end code:
routes: `get '/your-reviews'=> 'reviews#your_reviews'`

code in reviews_controller:
```
  def your_reviews
    @yourreviews = current_user.reviews
    render json: @yourreviews
  end
```

modified code in api call (in client repo)
```
const getReviews = () => {
  return $.ajax({
    url: config.apiOrigin + '/your-reviews',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}
```

**Comment by awoodrum87** [comment]
BOOM!
Thanks @jordanallain and Steve Duvall for the assistance!
