### ISSUE TITLE
Last Hurdle to completion: handlebars buttons (2 of 2)

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/full-stack-project#797]
Hi, I have 2 roadblocks until I am done! They are related to handlebars. I will create 2 issues and make references to the other. 

[1 of 2:  Get the reviews of just the current reviewer](https://github.com/ga-wdi-boston/full-stack-project/issues/796)
2 of 2: update/delete individual reviews from buttons within handlebars

I am able to use handlebars to show reviews, along with delete and update buttons for each review. I want to be able to click the delete button and delete the review and click the update button and render a modal with the form to update the review. At one point, I was able to click on the button and get a console log message that the click was successful but I broke that functionality and have not been able to get back there. This is similar to [Issue 777](https://github.com/ga-wdi-boston/full-stack-project/issues/777), but I was unable to fix my code based on that issue. 

my handlebars code:
```
{{#each reviews as |review|}}
<div id='review-actions'>
<ul>
  <!-- <li> <h1 data-id="{{review.id}}"> </h1></li> -->
  <li><small>Date: {{review.review_date}} </small></li>
  <li> <small> Review: {{review.review_text}}</small></li>
  <p> <input type="submit" data-id="{{review.id}}" id='ind-del-review' class="btn btn-danger" value="Delete Review"> </p>
  <p> <input type="submit" data-id="{{review.id}}" id='ind-up-review' class="btn btn-danger" value="Update Review"> </p>
</ul>
</div>
{{/each}}
```

events code (for delete, the update is the same except it says update):
```
const onDeleteReview = function (event) {
  event.preventDefault()
  console.log('delete review is heard')
  // api.deleteReview()
  //   .then(ui.deleteReviewSuccess)
  //   .catch(ui.deleteReviewFailure)
}
```
```
$('#review-events').on('click', '#ind-del-review', onDeleteReview)
```

**Comment by awoodrum87** [comment]
Update:
I found this [stackoverflow](http://stackoverflow.com/questions/17605296/document-onclick-not-working) and updated my events code to this, still not hearing the click:
```
  $('document').on('submit', '#ind-del-review', onDeleteReview)
```

**Comment by jordanallain** [comment]
when are you setting up the event listener? is it on page load? remember, you can't set up an event listener on an html element if it hasn't been rendered in the DOM yet.

**Comment by awoodrum87** [comment]
I have the click registering using the following event listener code:
(needed to use the div class, not the document)
`$('.content').on('submit', '#ind-del-review', onDeleteReview)`

**Comment by jordanallain** [comment]
okay, does that work?

**Comment by awoodrum87** [comment]
yes my clicks are heard using this. I need to resolve my other issue before I  can move on and am working on that.

**Comment by awoodrum87** [comment]
ok. so my buttons were working. or I should say I could console log a message to verify the click event is registering. NOW, when I click buttons it just resets my app. but my function specifies to do the prevent default. 

the html for the button:
```<input data-id="{{review.id}}" type="submit" name="submit" id="up-rev-submit" value="Update This Review">```

the event handler:
```$('document').on('submit', '.update-review', onUpdateReview)```

the  update review function:
```
const onUpdateReview = function (event) {
  event.preventDefault()
  console.log('update review is heard')
  api.updateReview()
    .then(ui.updateReviewSuccess)
    .catch(ui.updateReviewFailure)
}
```

All of this combined just refreshes my application

**Comment by scottyscripts** [comment]
try removing type="submit" on that input. This may make your app think that it's submitting an HTML form, thus refreshing the page. This could be overriding the `preventDefault`

**Comment by danman01** [comment]
`$('.content').on('submit', '#ind-del-review', onDeleteReview)`

vs

`$('document').on('submit', '.update-review', onUpdateReview)`

It looks like you had success with targeting the `#ind-del-review` within the `.content` div, as opposed to using `document` earlier?

**Comment by awoodrum87** [comment]
thanks @danman01 , I found the document approach in some documentation. but i returned it to my old code and that worked so that's what i'm going to roll with.

**Comment by danman01** [comment]
Great! And remember to close this issue if it is resolved.
