### ISSUE TITLE
Making one (very annoying) button disappear after sign in - all others disappear fine!

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/full-stack-project#799]
So when I sign in successfully, I turn off a bunch of menu items such as Sign Up. However no matter what I tried, I can't get rid of it. I tried two approaches.

 The first one I've used on several other menu items with no issues at all.

1. ```  $('.sign-up-menu').hide()  ```
2. Tried applying a css class to it as follows and it had no impact.
```
CSS:
.hide-sign-up-menu { display: none; };

.
.
$('.sign-up-menu').addClass('hide-sign-up-menu')
```

All other menu items show and hide perfectly fine, but not this one ? 

Any suggestions appreciated.

**Comment by scottyscripts** [comment]
Is there another class/id on the button? What does html look like for said button? Are you able to do $('.sign-up-menu').hide() in the developer console to hide the element?

**Comment by danman01** [comment]
@conorjennings can you open the chrome dev tools, inspect the element that is not hiding, and are you able to hide it from the devtools by adding a css property to it? More: https://developers.google.com/web/tools/chrome-devtools/inspect-styles/

If you can get that working, then you should be able to affect the visibility of the element using css.

Also, in the chrome dev console, you can type the JS you expect to hide it, and it should hide...if not, something is wrong with how you are targeting the element.

**Comment by glasneed** [comment]
I just met with Ryan and he pointed out my issue with some nifty debugging skills. **Thanks Ryan!!**

I had the following bug where I was calling the show method by mistake on the sign-up-menu

``` 
const onHideSignIn = function () {
  $('.sign-in-section').hide()
  //$('.sign-up-menu').show()
}

```

**Comment by glasneed** [comment]
Thanks Danny and Scott as well for feedback...

**Ryan - It works perfectly now. Thank you again!!**
