### ISSUE TITLE
having trouble deleting collections

### ISSUE THREAD

**Issue by mkutter72** [ga-wdi-boston/full-stack-project#8]
def destroy
    @messages = User.find(params[:id]).messages
    @messages.destroy

```
head :no_content
```

  end

not sure where to go from here, @messages = User.find(params[:id]).messages gets the messages I want to destroy

**Comment by gaand** [comment]
Does searching for activerecord has_many destroy help?

**Comment by gaand** [comment]
I don't know your use case, but should you use `current_user.messages`?

**Comment by gaand** [comment]
Resolved: `current_user.messages.destroy current_user.messages`
