### ISSUE TITLE
ProfilesController update/destroy method not working

### ISSUE THREAD

**Issue by leahphuong** [ga-wdi-boston/full-stack-project#80]
class ProfilesController < ApplicationController
  def index
    @profiles = current_user.profile

```
render json: @profiles
```

  end

  def show
    @profile = current_user.profile
    render json: @profile
  end

  def create
    @profile = current_user.profile = Profile.create(profile_params)

```
if @profile.save
  render json: @profile, status: :created,
    location: @profile
else
  render json: @profile.errors, status: :unprocessable_entity
end
```

  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      head :no_content
    else
      render json: @profile.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @profile = current_user.profile
    @profile.destroy

```
head :no_content
```

  end

  private
  def profile_params
    params.require(:profile).permit(:surname, :given_name)
  end
end

**Comment by tdyer** [comment]
Please look at the server log to understand what may be breaking when you attempt to update a profile.
If you don't understand the server log entry then paste it here.

**Comment by leahphuong** [comment]
I remove the profile id because i always create/modify the profile for the current user. work now!!

**Comment by tdyer** [comment]
And you changed the routes to not include the profile id as it wasn't needed. Good.
