### ISSUE TITLE
Handlebars - List template works but single object template does not work

### ISSUE THREAD

**Issue by rlarsonil71** [ga-wdi-boston/full-stack-project#800]
Issue Description:
I am able use a handlebars list template to loop through a list and display the list on a page but when I am try to place a single item using a separate handlebars template I am unable to do so.  I have the correct object passed to the single item handlebars template.  I believe the issue is how my object handlebars template is accessing the object.

Below is working code for the handlebars list template and call:

**assets/scripts/player/ui.js**
```
const indexPlayerSuccess = (ajaxResponse) => {
  console.log('player/ui.js (indexPlayerSuccess) ran!  Response is :', ajaxResponse)

  // Hide the SHOW FAVORITE PLAYERS modal from displaying to the user
  $('#myIndexPlayerModal').modal('hide')

  // Clear modal body text in SHOW FAVORITE PLAYERS modal
  $('#index-player').trigger('reset')

  // Clear favorite players content
  $('.content').empty()

  // Build handlebars HTML showing my favorite players for current user
  const showMyFavoritePlayersHtml = showMyFavoritePlayersTemplate({ favorite_players: ajaxResponse.favorite_players })
  $('.content').append(showMyFavoritePlayersHtml)
}
```

**assets/scripts/templates/favorite_player-listing.handlebars**
```
{{#each favorite_players as |player|}}

  <!-- {{> partial}} -->

  <h2><small>Player: {{player.player_name}}</small></h2>

  <ul><data-id="{{player.id}}">

  <li><button data-id="{{player.id}}" class="show-more-button jeter-test" id="{{player.id}}">Show More</button></li>
  <li><button data-id="{{player.id}}" class="remove-button" id="{{player.id}}">Remove</button></li>
  </ul>

{{/each}}
```

Below is code i am attempting to mimic for a single item:

**assets/scripts/player/ui.js**
```
const showMorePlayerSuccess = (ajaxResponse) => {
  console.log('player/ui.js (showMorePlayerSuccess) ran!  Response is :', ajaxResponse)
  console.log('player/ui.js (showMorePlayerSuccess) ran!  Favorite Player is :', ajaxResponse.favorite_player)
  console.log('player/ui.js (showMorePlayerSuccess) ran!  Player Name is :', ajaxResponse.favorite_player.player_name)
  console.log('player/ui.js (showMorePlayerSuccess) ran!  Team Name is :', ajaxResponse.favorite_player.team_name)
  console.log('player/ui.js (showMorePlayerSuccess) ran!  Sport is :', ajaxResponse.favorite_player.sport)
  console.log('player/ui.js (showMorePlayerSuccess) ran!  Position is :', ajaxResponse.favorite_player.position)
  console.log('player/ui.js (showMorePlayerSuccess) ran!  Player Number is :', ajaxResponse.favorite_player.player_number)

  // Clear favorite players content
  $('.content').empty()

  // Build handlebars HTML showing more data about selected favorite player
  //  for current user
  const showMoreMyFavoritePlayerHtml = showMoreFavoritePlayerTemplate({ favorite_player: ajaxResponse.favorite_player })
  $('.content').append(showMoreMyFavoritePlayerHtml)
}
```

**assets/scripts/templates/favorite_player-more-data-listing.handlebars**
```
<h2><small>Player: {{favorite_player.player_name}}</small></h2>

<ul><data-id="{{favorite_player.id}}">

    <h3><small>Team: {{favorite_player.team_name}}</small></h3>
    <h3><small>Sport: {{favorite_player.sport}}</small></h3>
    <h3><small>Position: {{favorite_player.position}}</small></h3>
    <h3><small>Player Number: {{favorite_player.player_number}}</small></h3>
</ul>
```

Console.log shows the following output:
```

2017-05-02 13:49:38.347 ui.js:80 player/ui.js (indexPlayerSuccess) ran!  Response is : Object {favorite_players: Array(8)}favorite_players: Array(8)0: Object1: Object2: Object3: Object4: Object5: Object6: Object7: Objectlength: 8__proto__: Array(0)__proto__: Object
2017-05-02 13:49:41.914 index.js:46 scripts/index.js (ODR - show-more-button) ran!  ID is : 1
2017-05-02 13:49:41.914 events.js:36 player/events.js (onShowMorePlayer) - (data is  1
2017-05-02 13:49:41.914 api.js:48 player/api.js (showMorePlayer) - (data is  1
2017-05-02 13:49:41.928 jquery.js:9566 XHR finished loading: GET "http://localhost:4741/my-favorite-players/1".
2017-05-02 13:49:41.930 ui.js:108 player/ui.js (showMorePlayerSuccess) ran!  Response is : Object {favorite_player: Object}
2017-05-02 13:49:41.930 ui.js:109 player/ui.js (showMorePlayerSuccess) ran!  Favorite Player is : Object {id: 1, player_name: "Derek Jeter", team_name: "New York Yankees", sport: "baseball", position: "Shortstop"…}
2017-05-02 13:49:41.930 ui.js:110 player/ui.js (showMorePlayerSuccess) ran!  Player Name is : Derek Jeter
2017-05-02 13:49:41.931 ui.js:111 player/ui.js (showMorePlayerSuccess) ran!  Team Name is : New York Yankees
2017-05-02 13:49:41.931 ui.js:112 player/ui.js (showMorePlayerSuccess) ran!  Sport is : baseball
2017-05-02 13:49:41.931 ui.js:113 player/ui.js (showMorePlayerSuccess) ran!  Position is : Shortstop
2017-05-02 13:49:41.931 ui.js:114 player/ui.js (showMorePlayerSuccess) ran!  Player Number is : 2
```

I saw a similar closed issue 756 and the showMoreFavoritePlayerTemplate still returns nothing.

Let me know if you need further information!    Thanks!

**Comment by scottyscripts** [comment]
Apologies for the wait. I am looking into this issue now. Will have feedback soon

**Comment by benjimelito** [comment]
I'm wondering if this might have something to do with your naming? I'm seeing this line `showMoreMyFavoritePlayerHtml = showMoreFavoritePlayerTemplate` and wondering if you forgot a "My" in the template name?

**Comment by benjimelito** [comment]
Would you mind posting where you are requiring the handlebars template?

**Comment by scottyscripts** [comment]
can you also push your most recent code to github?

**Comment by scottyscripts** [comment]
can you confirm that you define `const showMoreFavoritePlayerTemplate = require('../templates/favorite_player-more-data-listing.handlebars')` in your file?

**Comment by rlarsonil71** [comment]
Reviewing responses now...  thanks!

**Comment by rlarsonil71** [comment]
Here are the handlebars template definitions in assets/scripts/ui.js:

**assets/scripts/ui.js**
```
const store = require('../store')
const api = require('./api')
const showMyFavoritePlayersTemplate = require('../templates/favorite_player-listing.handlebars')
const showMoreFavoritePlayerTemplate = require('../templates/favorite_player-more-data-listing.handlebars')
```

**Comment by rlarsonil71** [comment]
No linter errors occur so definition naming is consistent.

**Comment by rlarsonil71** [comment]
Working on committing and uploading a branch to my github repo so you guys can take a look...  Thanks!

**Comment by rlarsonil71** [comment]
Ok... here is a link to my github repo with the latest client code (current branch is show_player_handlebars):

https://github.com/rlarsonil71/food-wine-rails-client/commits/show_player_handlebars

**Comment by rlarsonil71** [comment]
Here is a link to my github repo with the latest API code (current branch is master) in case you need it to research this issue:

https://github.com/rlarsonil71/food-wine-rails-api/commits/master

Thanks!

**Comment by scottyscripts** [comment]
@rlarsonil71 is the HTML from the template being rendered, just without the data?

**Comment by rlarsonil71** [comment]
The div is not being rendered from the template.

**Comment by rlarsonil71** [comment]
Issue is resolved.  Scott and Ben cloned my repo and Scott sat down with me and had me try a couple things.  

Resolution:
I had the following comment in the assets/scripts/templates/favorite_player-more-data-listing.handlebars file from the handlebars training repo:

```
  <!-- Developers, why are we using data-id and not just id? -->
  <!-- <h1 data-id="{{book.id}}"> <small>Title: {{book.title}}</small></h1> -->
```

I removed these comments and the single data object successfully rendered from the showMoreFavoritePlayerTemplate (assets/scripts/templates/favorite_player-more-data-listing.handlebars file).

** There must be a escape control character in the above comment that handlebars doesn't like skipping the rest of the template file. ***

Thanks @benjimelito and @sdavidson140 !
