### ISSUE TITLE
Issue with string manipulation in API calls

### ISSUE THREAD

**Issue by jscohen** [ga-wdi-boston/full-stack-project#801]
I am using a third party api to pass strings to an API to translate and I am running into a couple of issues.

I am storing the original text and the translated text in a resource called lyric, like so:

The .text is the original song lyrics, while .translation is the translated lyrics.

```ruby
  # POST /lyrics
  def create
    @lyric = Lyric.new(lyric_params)

    artist = lyric_params[:artist]
    title = lyric_params[:title]

    song_text = get_full_lyrics(artist, title)

    @lyric.text = song_text

    @lyric.translation = translate(song_text)
    if @lyric.save
      render json: @lyric, status: :created, location: @lyric
    else
      render json: @lyric.errors, status: :unprocessable_entity
    end
  end
```

The methods called are in another file, and the original text is scrubbed to be only in ASCII like so:

```ruby

def translate(lyrics)
  lyrics.split('').each do |i|
    if i == ' '
      lyrics.sub!(i, '%20')
    elsif i == 'ù'
      lyrics.sub!(i, '%0249')
    elsif i == 'Ù'
      lyrics.sub!(i, '%0217')
    elsif i == 'À'
      lyrics.sub!(i, '%0192')
    elsif i == 'à'
      lyrics.sub!(i, '%0224')
    elsif i == 'è'
      lyrics.sub!(i, '%0232')
    elsif i == 'È'
      lyrics.sub!(i, '%0200')
    elsif i == 'ò'
      lyrics.sub!(i, '%0242')
    elsif i == "\'"
      lyrics.sub!(i, '%27')
    elsif i == 'ì'
      lyrics.sub!(i, '%0236')
    elsif i == 'Ì'
      lyrics.sub!(i, '%0204')
    end
  end
  trans = translations(lyrics)
  trans
end
```

However, it is doing a few unexpected things.  This function is not only changing the local string I need to pass to the translation API, it is also changing the value in @lyrics.text to include all these characters.  I'm not sure how these things are related, but I want to keep the original text as it is.

**Comment by scottyscripts** [comment]
Just for clarification, you are just trying to modify `lyrics` or in this case `song_text` so you can pass that updated value to `def translations` right?

**Comment by scottyscripts** [comment]
also what is `def translations` doing?

**Comment by scottyscripts** [comment]
Since you are passing `song_text` as an argument to `translate` and calling `.sub!` you are modifying `song_text` in place. Perhaps pass in a copy of `song_text` to `def translate`

**Comment by jscohen** [comment]
Yes, I am trying to modify song_text to pass to the translate function.  The translate function makes a call to a third party API and returns song_text in English (it is originally in Italian).  That is why I am using the special character modification.  How can I make a copy of song_text?  By creating a new variable?

**Comment by jscohen** [comment]
We resolved this issue by cloning the lyrics object into a local variable for the translate function.
