### ISSUE TITLE
Request Assistance - Strange Behavior B/W Branches & Deployed

### ISSUE THREAD

**Issue by lisamsmith100** [ga-wdi-boston/full-stack-project#803]
Hi,
I'm not sure why, but my app is exhibiting strange behavior after things have been fixed.  For my client side, I have a strange feeling that my master branch is not my master branch at all and I've been reverting my changes and want to take a look at this if someone has a couple minutes.  I'm wanting to wrap up my requirements and make some additional finishing touches but the testing is not going well with that confusion.  I have reviewed my repo website, my repo in terminal and am getting confused.  
The issue is that the changes I have been making do not appear to be implemented and I'm afraid that I'm going to break it even more at this late hour.  

Some of the errors I had already fixed are showing again.  Can someone help, please?

**Comment by scottyscripts** [comment]
Have you been pushing local changes to Github? This could cause differences in looking at your remote branch and locally

**Comment by scottyscripts** [comment]
What do you mean when you say that you've been reverting changes? Did you go back to an earlier commit on your branch?

**Comment by lisamsmith100** [comment]
In my client, my commands have been

git commit
git push origin wkgbranch
git checkout master
git merge wkgbranch
git push origin master
grunt build
grunt deploy

I didn’t think I was reverting by going to earlier branch, but after committing changes through re-deploying, I’m not seeing the fixes in prod and I’m not seeing the fixes in my wkgbranch.

I recall there may have been a weird event but it was early and we discussed briefly on Tuesday but were not able to see any hangups.  Is there a chance that my wkgbranch is the effective master branch?  I’m not sure how to tell.  But given the code was working on a particular branch, I’d like to go back to it but unsure of the commands and afraid to make it worse.

The branch that was working correctly was 1 parent 5d71af5<https://github.com/lisamsmith100/hnd-client/commit/5d71af5b95d2f88f280194e9821860b3456c8b03> commit 49e99d2f8636f20b333ccb7917b2fcfb16439792


Thanks,

Lisa

**Comment by scottyscripts** [comment]
The immediate issue isn't whether master is actually master, we'll get to that. If your code for either of those branches isn't appearing on github, is there a chance that those pushes didn't work? try a `git push origin wkgbranch` check the terminal for any errors.

**Comment by danman01** [comment]
Also, if you run `git log` in the master branch, and `git log` in the wkgbranch, are they different? Do you notice the same commits are present in your repo on github?

**Comment by lisamsmith100** [comment]
I’ll take a look at both.  Thanks!  I am reviewing files again and making the updates.  I’m in wkgbranch.  I’ll re commit push origin wkgbranch.

**Comment by scottyscripts** [comment]
Awesome. let me know how that goes. pay attention after running the `git push` and look for any errors

**Comment by lisamsmith100** [comment]
I’ve been watching for errors when pushing to origin.  I’m seeing 5/5 or 3/3 or 8/8 so I think it’s working.  Comparing the git logs next…

**Comment by lisamsmith100** [comment]
It looks OK except for the last couple.  The commit I want to revert to is

commit ebfaf62b3c9ae753981b96015c930260ae669f9c

Is that the best solution since functionality was working?

Thanks for advice. 


![image](https://cloud.githubusercontent.com/assets/26127720/25636021/146a2316-2f4e-11e7-85ec-8decc07a353d.png)

**Comment by lisamsmith100** [comment]
To revert to past commit, I'm seeing that I need to follow these next steps:

git checkout 49e99d2f8636f20b333ccb7917b2fcfb16439792
git push origin 49e99d2f8636f20b333ccb7917b2fcfb16439792
git checkout master
git merge 49e99d2f8636f20b333ccb7917b2fcfb16439792
git push origin master
grunt build
grunt deploy

are these the correct steps to take?

Thank you again.

**Comment by lisamsmith100** [comment]
@sdavidson140 or @danman01 ,
I tried to push again and am seeing the following after conflicts resolution:
```sh
$ git commit
[master b026b7b] Merge branch 'wkgbranch'
~/wdi/projects/hnd-client (master)
$ git status
On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
~/wdi/projects/hnd-client (master)
$ 

```

**Comment by danman01** [comment]
Is this the commit you want to checkout: `ebfaf62b3c9ae753981b96015c930260ae669f9c` and do you want to checkout to this commit because it's where your project works and the newer stuff does not work?

If so, you will need to run `git checkout ebfaf62b3c9ae753981b96015c930260ae669f9c` and then `git branch myNewBranch`. 

From there you can `git push origin myNewBranch`, but really I don't think you would want to do that. What you are trying to do is move master back to that working commit, correct?

If that is correct, you have a few options:
`reset --hard`
`reset --soft `
`revert `

Read more here: http://stackoverflow.com/questions/4114095/how-to-revert-git-repository-to-a-previous-commit

I hope these git commands don't frighten you! Just read about them and try them out. Ask us if you would like to verify a command is correct. If you are really unsure, copy your current branch to a new branch to experiment on. Branches are plentiful and cheap.

**Comment by lisamsmith100** [comment]
I still haven't found a solution to my issue.  Going to keep trying things.

**Comment by lisamsmith100** [comment]
I mulled on this more and, given time constraints, I will continue working with the master branch and a new branch resolving the problems I had earlier with reverting back.  Closing this issue.
