### ISSUE TITLE
Is my syntax for jquery correct?

### ISSUE THREAD

**Issue by jonifallon** [ga-wdi-boston/full-stack-project#804]
I want to update an item in the 'issues' db.  I have a function that is intended to pre-populate the fields in my update form, but it's not pulling in the data.  Can you tell me if the **syntax** I have in the function is correct?     $('#text-product').val(data.issue.product)

Html
```
<form id="update-issue">
                      <h3>Update an Issue</h3>
                    <div class="productfield">
                      <label>Application or Service</label>
                      <input type="text" required="true" placeholder="Insert product name" class="form-control" name="issue[product]" id="text-product" aria-required="false">
                    </div>
                    
                    <div class="descriptionfield">
                      <label>Description</label>
                    <textarea type="textarea" required="true" placeholder="Describe symptoms and/or error messages a user might encounter." class="form-control" name="issue[description]" id="textarea-description" aria-required="true"></textarea>
                   </div>

                   <div class="notesfield">
                     <label>Notes</label>
                     <textarea type="textarea" required="false" placeholder="Provide any known workarounds, restoration ETA, etc." class="form-control" name="issue[notes]" id="textarea-notes"></textarea>
                   </div>
                   <div><button type="submit" style="success" id="updatedissuesubmit">Submit</button></div>
                  </form>

```

Function to populate the form using query

```
const onGetIssueForUpdateSuccess = function (data) {
  console.table(data)
  console.log('inside onGetIssueForUpdateSuccess ui.js', data)
  $('#text-product').val(data.issue.product)
}
```

**Comment by jonifallon** [comment]
This is my table:

issues_db_development=# \d issues
                                 Table "public.issues"
   Column    |       Type        |                      Modifiers                      
-------------+-------------------+-----------------------------------------------------
 id          | integer           | not null default nextval('issues_id_seq'::regclass)
 user_id     | integer           | not null
 product     | character varying | 
 description | character varying | 
 notes       | character varying | 
Indexes:
    "issues_pkey" PRIMARY KEY, btree (id)
    "index_issues_on_user_id" btree (user_id)

**Comment by scottyscripts** [comment]
That syntax does appear to be correct. Is the console.log for data working? Where are you invoking `onGetIssueForUpdateSuccess`. Is this currently being invoked?

**Comment by jonifallon** [comment]
Yes the console.log is working.  Yes I'm invoking onGetIssueForUpdateSuccess.  It's being invoked from 

```
const populateUpdateIssueForm = function (event) {
  // populate the create-issue form on the index page
  event.preventDefault()
  hideThings()
  showThings()
  // captures the issue ID input by the user
  const issue = $('#updateissuetextbox').val()
  api.showIssue(issue)
      .then(ui.onGetIssueForUpdateSuccess)
      // .catch(ui.onGetIssueFailure)
  $('#update-issue').show()
  console.log('inside populateUpdateIssueForm')
}
```

**Comment by danman01** [comment]
Does your javascript work in the chrome console? Open up devtools, run your javascript:
`$('#text-product').val(data.issue.product)`
(substituting what you need to use for `data.issue.product`) and see if that works as expected. 

And, does `data.issue.product` contain what you think it does? How can you find out?

**Comment by jonifallon** [comment]
Sorry - I'm not sure what I need to substitute for data.issue.product.  If someone could sit with me for a few minutes I'd appreciate it.  i'd love to finish this today.  Thank you!

**Comment by scottyscripts** [comment]
Issue at hand resolved. Issue had to do with duplicate id names

**Comment by jonifallon** [comment]
I have since also resolved the issue with passing data/id.  Closing this issue.
