### ISSUE TITLE
Handlebars Formatting Issue

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/full-stack-project#805]
I need some assistance with formatting the output returned from a handlebars query.  The data is accurate but it prints out as is there is a new line feed after each word.

Thank You

**Comment by jordanallain** [comment]
more data please

**Comment by glasneed** [comment]
Met with Chris M on this one and helped me solve the issue. I switched out a class in my handlebar file from using 

``` <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12"> ```
to using 
``` <div class = 'container'> ```
and the output is formatted better now.

**Thanks Chris!**
