### ISSUE TITLE
Rails issue with data returning from group by and count

### ISSUE THREAD

**Issue by octater** [ga-wdi-boston/full-stack-project#806]
my       @games = Game.all returns:
{"games":[{"id":117,"user_id":13,"game_status":2,"letters_played":7,"phrase_id":9},{"id":118,"user_id":13,"game_status":1,"letters_played":7,"phrase_id":8},{"id":119,"user_id":13,"game_status":0,"letters_played":6,"phrase_id":7},{"id":113,"user_id":14,"game_status":1,"letters_played":9,"phrase_id":6},{"id":120,"user_id":14,"game_status":0,"letters_played":7,"phrase_id":14},{"id":121,"user_id":14,"game_status":2,"letters_played":7,"phrase_id":11},{"id":122,"user_id":13,"game_status":0,"letters_played":0,"phrase_id":4},{"id":123,"user_id":14,"game_status":0,"letters_played":0,"phrase_id":10},{"id":124,"user_id":14,"game_status":0,"letters_played":0,"phrase_id":15},{"id":125,"user_id":13,"game_status":0,"letters_played":0,"phrase_id":12},{"id":126,"user_id":13,"game_status":0,"letters_played":0,"phrase_id":12},{"id":127,"user_id":13,"game_status":0,"letters_played":0,"phrase_id":7},{"id":128,"user_id":13,"game_status":2,"letters_played":10,"phrase_id":11}]}

but when I do a  @games = Game.group('games.phrase_id').order('games.phrase_id asc').count
it returns: 
{"4":1,"6":1,"7":2,"8":1,"9":1,"10":1,"11":2,"12":2,"14":1,"15":1}

how can I get it to return in the same format as Game.all??

**Comment by jordanallain** [comment]
`@games = Game.group('games.phrase_id').order('games.phrase_id asc').count`

what is this line setting @games to?

**Comment by danman01** [comment]
If you drill down to get the value of the "games" key, you get an array. From there, you can call the array methods `sort_by` and `count` to work with your data on the array of hashes. Here's a discussion on how to sort an array of hashes: http://stackoverflow.com/questions/5483889/how-to-sort-an-array-of-hashes-in-ruby

**Comment by octater** [comment]
closing this ticket due to out of time to implement.  Thanks guys for your input
