### ISSUE TITLE
Unable to get button in handlebars to register click event

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#807]
I have a form inside my handlebars template that will submit updates for an item.
When I click the submit button nothing happens. It's supposed to submit the form items and call the API for a patch request. I think I don't have the event handler constructed correctly - would like a second set of eyes to verify.

index.html where the div gets modified and where the item form is displayed:
```html
  <div class="item-list col-sm-12" id="item-list">
  </div>
```

form in handlebar: 
```html
    <form id="update-item" class="tr">
        <span class="td"><input type="text" name="item_name" placeholder="{{item.item_name}}"></span>
        <span class="td"><input type="text" name="purchase_date" placeholder="{{item.purchase_date}}"></span>
        <span class="td"><input type="text" name="expiry_date" placeholder="{{item.expiry_date}}"></span>
        <span class="td"><input type="text" name="price" placeholder="{{item.price}}"></span>
        <span class="td"><input type="text" name="category" placeholder="{{item.category}}"></span>
        <span class="td"><input type="text" name="quantity" placeholder="{{item.quantity}}"></span>
        <span class="td"><input type="submit" name="submit" value="Save Changes"></span>
    </form>
```

event.js - this is where I'm getting tripped up:
```js
const addAuthHandlers = () => {
  $('#item-list').on('click', '#update-item', function () {
    onUpdateItem
  })
}
```

here is the function for onUpdateItem, it's not reaching the debugger:
```js
const onUpdateItem = function (event) {
  event.preventDefault()
  const data = getFormFields(this)
  debugger
  api.updateItem(data)
    .then(ui.updateItemSuccess)
    .catch(ui.updateItemFailure)
}
```

**Comment by ghost** [comment]
Realized that I'm not submitting the form. Revised the handler - still not able to call the function:
```js
  $('#update-item').on('submit', function (event) {
    onUpdateItem
```

**Comment by benjimelito** [comment]
Are you making sure that the form has been appended to the DOM before you attach the click-handler?

**Comment by benjimelito** [comment]
Would you mind posting where you are appending the form to the DOM?

**Comment by ghost** [comment]
I guess I'm not appending the form to the DOM. Not exactly sure how - would this be it?

```js
$('document').on('click', '#item-list', function(event) {
     $('#update-item').on('submit', onUpdateItem)
  })
```

**Comment by jordanallain** [comment]
the handlebars is rendering the HTML, so you want to set the listener after the handlebar is called.

**Comment by naributler** [comment]
I ran into this issue as well! This statement worked for me:
```
$(document).on('click', '.move-to-grocery-list', updateQuantity)
```

**Comment by ghost** [comment]
Thanks @narichasavanorkejoyce, @jordanallain, @benjimelito, the following worked for me:
```js
$(document).on('submit', '#update-item', onUpdateItem)
```
