### ISSUE TITLE
Most images are not loading on deployed site

### ISSUE THREAD

**Issue by buffalo0707** [ga-wdi-boston/full-stack-project#808]
Most of the images on my site are not displaying when viewing the deployed site. The images display OK in my local environment.

When the issues load, a console error is thrown like:
```
forest.png:1 GET https://buffalo0707.github.io/PixlMonstr-Client/assets/images/forest.png 404 (Not Found)
```
Site URL: [https://buffalo0707.github.io/PixlMonstr-Client/#/public/assets/images](https://buffalo0707.github.io/PixlMonstr-Client/#/public/assets/images)

Steps taken so far:
-Confirmed there are no capital letters in any of the filepaths I am using
-Confirmd the files are all pushed to GitHub and appear in the correct location in the GitHub repo
-Confirmed that no files start with underscore
-Reviewed closed issues for this project and for game project. For game project, we used imgur as a workaround. However, in my case, I need the full filename in order to dynamically generate filepaths to determine which image to display in a given scenario

**Comment by benjimelito** [comment]
How long has it been since you deployed your app? I know that sometimes there can be a lag when uploading images to a deployed app

**Comment by buffalo0707** [comment]
It's been about 25 minutes. I'll give it a little more time and see what happens.

**Comment by buffalo0707** [comment]
Still not working. The rest of the changes that were included in my last deploy are available in the deployed site.

**Comment by danman01** [comment]
This image works fine: https://buffalo0707.github.io/PixlMonstr-Client/public/01c12f27129cd1286dfcb755b4f55c48.jpg

Where is it stored in relation to the images that are not working?

**Comment by buffalo0707** [comment]
It is stored in the same location as all of the other images which are not working.

This image is applied as a background-image property in my index.scss file. Here is my code:
```css
  background-image: url('../images/cave.jpg');
```

I noticed in Chrome inspector window that the url has changed in the deployed site. Here is the code that shows in inspector:

```css
background-image: url(public/01c12f27129cd1286dfcb755b4f55c48.jpg);
```
Are image files renamed when deployed?

**Comment by jordanallain** [comment]
i think that is a webpack thing. so that working one is a relative path and it looks like the non working one was an absolute path. maybe changing them all to relative paths? are there any non-relative paths that are not functioning?

**Comment by buffalo0707** [comment]
Thanks, I'll give it a show now.

**Comment by buffalo0707** [comment]
No good. I think in the interest of time, I'm going to have to approach this a different way using imgur. Oh well.

Thanks.
