### ISSUE TITLE
low priority - Images sideways in README.md file

### ISSUE THREAD

**Issue by mkutter72** [ga-wdi-boston/full-stack-project#81]
My wireframe images are rotated 90 degrees when I view my README.md file

**Comment by tdyer** [comment]
Mike, whats the markup look like? Also open the image in the preview app, or the browser, and look at the orientation of the image.

**Comment by mkutter72** [comment]
when I click on the image file listed in github it is sideways,  if I then click on the raw button it looks find.
I saw this on project one 
https://github.com/mkutter72/TicTacToe/blob/gh-pages/WireFrame1.jpg

**Comment by GA-MEB** [comment]
@mkutter72 
It might be that the underlying file is sideways, and OS X and Chrome are just smart enough to know to right-end it, while GitHub isn't. Do you have GIMP on your machine? If so, you could try opening the image in GIMP, and see if it's upright or on its side.

**Comment by tdyer** [comment]
Mike, closing this out as it's only an issue in your README.
