### ISSUE TITLE
Update form from handlebars not working properly

### ISSUE THREAD

**Issue by rlarsonil71** [ga-wdi-boston/full-stack-project#811]
Issue Description:
I am trying to use a handlebars update template which adds an update player form to the screen.  The form renders on the screen as well as an Update Player button.  

Once I click the Update Player button, the page refreshes even though I added a call to event.preventDefault() in the button event handler callback.

I have tried to make changes to the assets/scripts/templates/favorite_player-update-listing.handlebars file as well as the assets/scripts/player/events.js files.

Below is my update handlebars file:
**assets/scripts/templates/favorite_player-update-listing.handlebars**
```
<!-- Update Player input form -->
<h2><small>Player: {{favorite_player.player_name}}</small></h2>
<div data-id="{{favorite_player.id}}" id="updateForm{{favorite_player.id}}" class='form-group updateDiv text-left'>
  <form data-id="{{favorite_player.id}}" id="updatePlayerForm" class='text-left form-group updateForm'>
    <input type="text" name="player_info[team_name]" id='update-player-team-name' value="{{favorite_player.team_name}}" placeholder="Team Name"><br>
    <input type="text" name="player_info[sport]" id='update-player-sport' value="{{favorite_player.sport}}" placeholder="Sport"><br>
    <input type="text" name="player_info[position]" id='update-player-position' value="{{favorite_player.position}}" placeholder="Position"><br>
    <input type="text" name="player_info[player_number]" id='update-player-player-number' value="{{favorite_player.player_number}}" placeholder="Player Number"><br>
    <br>
    <input type="submit" name="submit" id="save-id" data-id="{{favorite_player.id}}" class="save-update-button" value='Update Player'>
  </form>
  <br>
</div>
```

Below is code from the events.js file:
**assets/scripts/player/events.js**
```
const onSaveUpdatedPlayer = function (id, event) {
  event.preventDefault()
  console.log('player/events.js (onSaveUpdatedPlayer) - ID: ', id)

  console.log('THIS: ', this)

  const data = getFormFields(this)
  console.log('player/events.js (onSaveUpdatedPlayer) - Data is: ', data)

  api.updatePlayer(id, data)
    .then(ui.updatePlayerSuccess)
    .catch(ui.updatePlayerFailure)
}

const onUpdatePlayer = function (id) {
  event.preventDefault()
  console.log('player/events.js (onUpdatePlayer)')

  console.log('player/events.js (onUpdatePlayer) - Favorite Player is: ', store.favorite_player)
  console.log('player/events.js (onUpdatePlayer) - ID is: ', id)

  // Clear favorite players content
  $('.content').empty()

  // Build handlebars HTML showing UPDATE FORM to have current user update data
  //  about selected favorite player

  const showUpdateMyFavoritePlayerHtml = showUpdateMyFavoritePlayerTemplate({ favorite_player: store.favorite_player })
  $('.content').html(showUpdateMyFavoritePlayerHtml)

  $(document).on('submit', '#save-id', function (event) {
    event.preventDefault()
    console.log('scripts/index.js (ODR - save-update-button) ran!  ID is :', this.id)
    onSaveUpdatedPlayer(this.id, event)
  })
}
```

No linter errors.

Workflow to Recreate:
1. Sign up
2. Sign in
3. Create player
4. Create 2nd player
5. Click Show My Favorite Players button
6. List of 2 players is shown each showing a Show More button and a Remove button.
7. For one of the 2 players, click its Show More button.
8. An update form is rendered with an Update Player button.
9. Once the Update Player button is clicked (to submit the form), the page refreshes.

NOTE at one point, the console.log showed from the following commands to getFormFields:

```
console.log('THIS: ', this)
const data = getFormFields(this)
```

THIS: <handlers>

I noticed that in my Create Player form that `this` is the <form div>.

In this case, this is incorrect so getFormFields method doesn't work.

Let me know if you need any more information.  Thanks!

**Comment by rlarsonil71** [comment]
I am in the process of uploading my latest client code to my github and will update this issue with the link shortly.

**Comment by rlarsonil71** [comment]
Here is a link to my github repo with the latest client code (current branch is show_player_handlebars):

https://github.com/rlarsonil71/food-wine-rails-client/commits/show_player_handlebars

**Comment by rlarsonil71** [comment]
Here is a link to my github repo with the latest API code (current branch is master) in case you need it to research this issue:

https://github.com/rlarsonil71/food-wine-rails-api/commits/master

Thanks!

**Comment by rlarsonil71** [comment]
Walking back from GA to get some food and will be online in 30 minutes.  Thanks!

**Comment by jordanallain** [comment]
is this the event listener that isn't working?

```js
$(document).on('submit', '#save-id', function (event) {
    event.preventDefault()
    console.log('scripts/index.js (ODR - save-update-button) ran!  ID is :', this.id)
    onSaveUpdatedPlayer(this.id, event)
  })
}
```
if so what are you targeting with that?

**Comment by awoodrum87** [comment]
ron, I was having the same issue. I was unable to use the $(document) approach.

I ultimately used: `$('.content').on('submit', '#ind-del-review', onDeleteReview)`
.content is an empty div in my html where the handlebars renders
#ind-del-review is the id of the button
onDeleteReview is the function I run when I submit* the button

*note, my button type is a submit, not button, therefore it's submit rather than click. see the code for my botton: `<p> <input type="submit" data-id="{{review.id}}" id='ind-del-review' class="btn btn-danger" value="Delete Review"> </p>`

If this doesn't work, let me know.

**Comment by rlarsonil71** [comment]
@jordanallain Yes, that is the event handler that isn't working.   

I tried adding the event handler after the call to create the update player form using the Update Handlebars form instead of at 'On Document Ready' in the scripts/index.js file (thinking that the button wouldn't be in the DOM until the Update Handlebars template adds it to the DOM).

**Comment by rlarsonil71** [comment]
@awoodrum87 Thanks Angie!  I will try that in a few minutes after a break and will let you know.

**Comment by jordanallain** [comment]
but what is the id you are using to target? is that the right one?

**Comment by rlarsonil71** [comment]
Hey Jordan.... #save-id is the id I am using to target.  It is the id in the last line of the form within my update handlebars file **(assets/scripts/templates/favorite_player-update-listing.handlebars)** 

This id is the same as the id used in the event handler code snip that you added above.

```
    <input type="submit" name="submit" id="save-id" data-id="{{favorite_player.id}}" class="save-update-button" value='Update Player'>
```

See the snip from this update handlebars file at the top of this issue for the entire file.

**Comment by jordanallain** [comment]
is that what you are trying to capture the submit of?

**Comment by jordanallain** [comment]
what have you done previously with submit buttons nested in forms?

**Comment by rlarsonil71** [comment]
Yes, @jordanallain that is the submit button (id=#save-id) that is called at steps 8 and 9 below:

1. Sign up
2. Sign in
3. Create player
4. Create 2nd player
5. Click Show My Favorite Players button
6. List of 2 players is shown each showing a Show More button and a Remove button.
7. For one of the 2 players, click its Show More button.
8. An update form is rendered with an Update Player button (id=#save-id) so that the user can update any of the player's data fields.
9. Once the user enters updated data AND the Update Player button (id=#save-id) is clicked (to submit the form), the page incorrectly refreshes.

**Comment by rlarsonil71** [comment]
I have a Create New Player form that works just fine with a submit button attached to the form.  

The only difference that I can see is that the Create New Player button is inside a modal on the navbar and is defined in index.html AND the update form with the Update Player button (id=#save-id) is inside the update handlebars template.

**Comment by rlarsonil71** [comment]
@awoodrum87 - Angie, I tried your suggestion and the page still incorrectly refreshes when I run step 9 above.

```
  $('content').on('submit', '#save-id', function (event) {
    event.preventDefault()
    console.log('scripts/index.js (ODR - save-update-button) ran!  ID is :', this.id)
    onSaveUpdatedPlayer(this.id, event)
  })
```

**Comment by awoodrum87** [comment]
if that is your code is content a class? if so it should be `$('.content')` (your code snip does not have the period before content)

**Comment by jordanallain** [comment]
ron in your event listener for the create new player form, what element are you targeting for the submit of?

**Comment by rlarsonil71** [comment]
@awoodrum87 - Good catch.  Content is a class and I added the period.

```
  // Clear favorite players content
  $('.content').empty()

  // Build handlebars HTML showing UPDATE FORM to have current user update data
  //  about selected favorite player

  const showUpdateMyFavoritePlayerHtml = showUpdateMyFavoritePlayerTemplate({ favorite_player: store.favorite_player })
  $('.content').html(showUpdateMyFavoritePlayerHtml)

  $('.content').on('submit', '#save-id', function (event) {
    event.preventDefault()
    console.log('player/events.js (save-id) ran!  ID is :', this.id)
    onSaveUpdatedPlayer(this.id, event)
  })
```

The page still incorrectly refreshes when I run step 9 above.

**Comment by awoodrum87** [comment]
yikes! I'm out of ideas. Apologies. I'll be at GA before class. A fresh brain might help :)

**Comment by rlarsonil71** [comment]
@jordanallain The following code is for the WORKING create new player form all located in the index.html file as it is a modal button in a navbar:

```
<!-- Button trigger select-create-player modal -->
<button type="button" id="select-create-player" class="btn btn-success btn-md" data-target="#myCreatePlayerModal">
         Create New Player
</button>
```

```
  <!-- MODAL - CREATE-PLAYER -->
  <div class="modal fade" id="myCreatePlayerModal" tabindex="-1" role="dialog" aria-labelledby="myCreatePlayerModalLabel">
    <div class="modal-dialog modal-md" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myCreatePlayerModalLabel">Create New Favorite Player</h4>
        </div>

        <!-- MODAL BODY -->
        <div class="modal-body">
          <form id="create-player">
              <input type="text" name="player_info[player_name]" id="create-player-player-name" placeholder="Player Name">  Player Name<br>
              <input type="text" name="player_info[team_name]" id="create-player-team-name" placeholder="Team Name">  Team Name<br>
              <input type="text" name="player_info[sport]" id="create-player-sport" placeholder="Sport">  Sport<br>
              <input type="text" name="player_info[position]" id="create-player-position" placeholder="Position">  Position<br>
              <input type="text" name="player_info[player_number]" id="create-player-player-number" placeholder="Player Number">  Player Number<br><br>
              <input type="submit" name="submit" value="Create New Player">
          </form>
        </div>
        <!-- MODAL BODY -->

        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> -->
          <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
        </div>

      </div>
    </div>
  </div>
```

```
  <div id="content" class="content">
  </div>
```

**assets/scripts/players/events.js**
```
const addHandlers = () => {
  // Set up event handler to CREATE NEW PLAYER modal
  $('#create-player').on('submit', onCreatePlayer)
```

**Comment by jordanallain** [comment]
okay can you answer the question i asked?

**Comment by jordanallain** [comment]
now look at what you are targeting in that event listener and compare it to the one that isn't working

**Comment by rlarsonil71** [comment]
Yup... I just edited the comment above and pasted it above from assets/scripts/players/events.js.   I am targeting the #create-player id.

**Comment by jordanallain** [comment]
```
<form id="create-player">
$('#create-player').on('submit', onCreatePlayer)
```

```
<input type="submit" name="submit" id="save-id" data-id="{{favorite_player.id}}" class="save-update-button" value='Update Player'>
$(document).on('submit', '#save-id', function (event) {
```

**Comment by jordanallain** [comment]
in one of those you are targeting a `<form>` and in one you are targeting an `<input>`

**Comment by rlarsonil71** [comment]
Aaah... needed some coffee for that one.  Thanks!  I understand now what you were asking.  

I changed the target from the 'save-id' ID on the ```<input>``` to the 'updatePlayerForm' ID on the ```<form>``` and the page no longer refreshes.

```
<!-- Update Player input form -->
<h2><small>Player: {{favorite_player.player_name}}</small></h2>
<div data-id="{{favorite_player.id}}" id="updateForm{{favorite_player.id}}" class='form-group updateDiv text-left'>
  <form data-id="{{favorite_player.id}}" id="updatePlayerForm" class='text-left form-group updateForm'>
    <input type="text" name="player_info[team_name]" id='update-player-team-name' value="{{favorite_player.team_name}}" placeholder="Team Name"> Team Name<br>
    <input type="text" name="player_info[sport]" id='update-player-sport' value="{{favorite_player.sport}}" placeholder="Sport"> Sport<br>
    <input type="text" name="player_info[position]" id='update-player-position' value="{{favorite_player.position}}" placeholder="Position"> Position<br>
    <input type="text" name="player_info[player_number]" id='update-player-player-number' value="{{favorite_player.player_number}}" placeholder="Player Number"> Player Number<br>
    <br>
    <input type="submit" id='save-id' data-id="{{favorite_player.id}}" class="btn btn-success save-update-button" value='Update Player'>
  </form>
  <br>
</div>
```

```
  // $('.content').on('submit', '#save-id', function (event) {
  $('.content').on('submit', '#updatePlayerForm', function (event) {
    event.preventDefault()
    console.log('player/events.js (onUpdatePlayer) ran!  ID is :', id)
    onSaveUpdatedPlayer(id)
  })
```

**Comment by rlarsonil71** [comment]
Thanks!  I am now getting an undefined this when sending it to:

```
const data = getFormFields(this)
```

**console.log**
```
events.js:66 player/events.js (onUpdatePlayer) - Favorite Player is:  Object {id: 21, player_name: "Nomar Garciaparra", team_name: "Red Sox", sport: "baseball", position: "Shortstop"…}
2017-05-03 00:11:50.909 events.js:67 player/events.js (onUpdatePlayer) - ID is:  21
2017-05-03 00:12:04.997 events.js:87 player/events.js (onUpdatePlayer) ran!  ID is : 21
2017-05-03 00:12:04.997 events.js:50 player/events.js (onSaveUpdatedPlayer) - ID:  21
2017-05-03 00:12:04.998 events.js:52 THIS:  **undefined**
```

```
  $('.content').on('submit', '#updatePlayerForm', function (event) {
    event.preventDefault()
    console.log('player/events.js (onUpdatePlayer) ran!  ID is :', id)
    onSaveUpdatedPlayer(event, id)
  })
```

```
const onSaveUpdatedPlayer = function (event, id) {
  event.preventDefault()
  console.log('player/events.js (onSaveUpdatedPlayer) - ID: ', id)

  console.log('THIS: ', this)

  const data = getFormFields(this)
  console.log('player/events.js (onSaveUpdatedPlayer) - Data is: ', data)

  api.updatePlayer(id, data)
    .then(ui.updatePlayerSuccess)
    .catch(ui.updatePlayerFailure)
}
```

**Comment by rlarsonil71** [comment]
Comparing getFormFields(this) that works in onCreatePlayer with getFormFields(this) that has an undefined this in onSaveUpdatedPlayer.

```
const onCreatePlayer = function (event) {
  event.preventDefault()
  console.log('player/events.js (onCreatePlayer) ran!')

  console.log('THIS: ', this)

  const data = getFormFields(this)
  api.createPlayer(data)
    .then(ui.createPlayerSuccess)
    .catch(ui.createPlayerFailure)
}
```

```
events.js:21 THIS:  **<form id=​"create-player">​…​</form>​**
2017-05-03 00:19:41.280 api.js:7 player/api.js (createPlayer) - (data is  Object {player_info: Object, submit: "Create New Player"}
2017-05-03 00:19:41.305 jquery.js:9566 XHR finished loading: POST "http://localhost:4741/favorite_players/".
send @ jquery.js:9566
ajax @ jquery.js:9173
createPlayer @ api.js:10
onCreatePlayer @ events.js:24
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014
2017-05-03 00:19:41.306 ui.js:12 player/ui.js (createPlayerSuccess) ran!  Response is : Object {favorite_player: Object}
```

**Comment by rlarsonil71** [comment]
I figured out the getFormFields(this) where ```this``` = undefined issue.

I changed the following code:
```
  $('.content').on('submit', '#updatePlayerForm', function (event) {
    event.preventDefault()
    console.log('player/events.js (onUpdatePlayer) ran!  ID is :', id)
    onSaveUpdatedPlayer(event, id)
  })
```
to: 

```
  $('.content').on('submit', '#updatePlayerForm', onSaveUpdatedPlayer)
```
and getFormFields(this) now works as ```this``` is now the update form.

**Comment by rlarsonil71** [comment]
Thanks @jordanallain and @gastevend !!
