### ISSUE TITLE
Data not passing correctly on Heroku deployment

### ISSUE THREAD

**Issue by jonifallon** [ga-wdi-boston/full-stack-project#812]
https://jonifallon.github.io/issues_client/
https://shrouded-beach-65904.herokuapp.com/ 
https://github.com/jonifallon/issues_api
https://github.com/jonifallon/issues_client

Everything is functioning fine locally (http://localhost:7165/), but in the deployed version on Heroku (https://jonifallon.github.io/issues_client/), I'm seeing this behavior:

It fails when I request to update an issue that I created.  It tells me the issue id isn’t valid, which should only happen if I wasn’t the original creator.  I'm seeing "onGetIssueForUpdateFailure ui.js TypeError: Cannot read property 'product' of undefined" in the console.  

I can create new issues, but the content I entered into the form fields never populates - it’s creating an object with all fields empty except the ID.

```
no-conflict.js:13 create issue success ran.  data is: Object {issue: Object}
21:52:31.482 no-conflict.js:13 you are in the createissueSuccess function on ui.js Object {id: 9, product: "", description: "", notes: ""}
21:52:39.196 vendor.js:9678 XHR finished loading: GET "https://shrouded-beach-65904.herokuapp.com/issues".
send @ vendor.js:9678
ajax @ vendor.js:9285
index @ no-conflict.js:13
onIndex @ no-conflict.js:13
dispatch @ vendor.js:5318
elemData.handle @ vendor.js:5126
21:52:39.198 no-conflict.js:13 (index)idproductdescriptionnotes02"aaaaa""a""a"13""""""24""""""35""""""47""""""59""""""
```
There is one item in the db that I believe I created earlier today (2), and that issue correctly contains the data in each field.  Anything I'm creating now does not.  

I did a heroku restart but that did not resolve the issues.  What else can I try?

**Comment by jonifallon** [comment]
And I have deployed all updates on both the client and api side.  Heroku should have the latest code since I followed these steps after committing:

git checkout master
git merge my-feature # merge your working code
git push # update GitHub
git push heroku master # update heroku

**Comment by jonifallon** [comment]
I'll plan to work on this further tomorrow morning.

**Comment by jordanallain** [comment]
do you have any migrations that haven't been run?

**Comment by jonifallon** [comment]
No, everything is up to date.

**Comment by jordanallain** [comment]
can you post the functions and which files they should be in?

**Comment by jonifallon** [comment]
This is resolved.  When trying again this morning, my local was also passing empty objects upon creation.  I rolled back my events.js file and index.html file since I had made late changes on each, and now things are back to normal.  I will dig deeper to see what functionality/code, if any, I need to restore - but things are looking good!
