### ISSUE TITLE
No Access Control Allow Origin Problem

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/full-stack-project#813]
I opened an issue here -- 
https://git.generalassemb.ly/ga-wdi-boston/full-stack-project/issues/723

Lots of details over there, let me know if you want me to respecify here.

**Comment by benjimelito** [comment]
This type of error happens when you make a request from a different domain than the resources are hosted on. On what domain is your backend hosted?

**Comment by benjimelito** [comment]
It is possible that this issue can be fixed by including a `'Access-Control-Allow-Origin' header on your backend routes, but I think you should be able to resolve it without doing this.

**Comment by Maggicorp** [comment]
What do you mean? My heroku address is  
https://advice-app-maggicorp.herokuapp.com/
but the back end repo is called https://github.com/Maggicorp/advice_back_end

**Comment by Maggicorp** [comment]
I finally got it work deploy properly. The problem was that I had to start and restart grunt server.
