### ISSUE TITLE
current_user not accessible

### ISSUE THREAD

**Issue by pjliddy** [ga-wdi-boston/full-stack-project#814]
Encountering an issue where current_user is nil when being accessed from the list item controller.

It appears the user needs to be authenticated before user ID can be accessed by controller and/or test methods.

**Comment by benjimelito** [comment]
Are you making a curl request to sign up and sign in a user?

**Comment by jordanallain** [comment]
you can look in the application controller to see how current user is set

**Comment by danman01** [comment]
@pjliddy what did you find out / can this be resolved?

**Comment by MicFin** [comment]
@pjliddy Please share your working Controller file with the change mentioned below so we can see the full solution.

**Comment by pjliddy** [comment]
Here's a controller for a auto-generated item class:

You need to call the `set_current_user` method inherited from ApplicationController before the class will know that current_user has a value.

This solution manually calls the local `validate_user` method before it's needed in index, create, update, destroy, and set_item. `set_current_user` in ApplicationController should probably be called when users sign in.

``` ruby
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: %i[show update destroy]
  before_action :validate_user, only: %i[index create update destroy set_item]

  # GET /items
  def index
    # filter by user_id
    # @items = Item.all
    @items = current_user.items

    render json: @items
  end

  # GET /items/1
  def show
    render json: @item
  end

  # POST /items
  def create
    # get current user_ID from application_controller
    @item = current_user.items.build(item_params)

    if @item.save
      render json: @item, status: :created, location: @item
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      render json: @item
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    # @item = Item.find(params[:id])
    validate_user
    @item = current_user.items.find(params[:id])
  end

  def validate_user
    set_current_user
  end

  # Only allow a trusted parameter "white list" through.
  def item_params
    params.require(:item).permit(:title, :body)
  end
end
```

**Comment by MicFin** [comment]
Additionally, here's some more information about the 5 controllers that come with the `rails-api-template`.  Click the link to view the code of each one.

1. [application_controller](https://github.com/ga-wdi-boston/rails-api-template/blob/master/app/controllers/application_controller.rb)
    - defines methods `set_current_user` and `authenticate`
2.  [protected_controller](https://github.com/ga-wdi-boston/rails-api-template/blob/master/app/controllers/protected_controller.rb)
    - inherits from `application_controller` 
    - calls `authenticate` before every action
    - _inherit from this if you want a controller to `authenticate` every action_
3.  [users_controller](https://github.com/ga-wdi-boston/rails-api-template/blob/master/app/controllers/users_controller.rb)
    - inherits from `protected_controller`
    - overrides `before_action` to not `authenticate` on `sign_up` or `sign_in`
    - handles `user` resource actions
4.  [open_read_controller](https://github.com/ga-wdi-boston/rails-api-template/blob/master/app/controllers/open_read_controller.rb)
    - inherits from `protected_controller`
    - overrides `before_action` to not `authenticate` the `index` or `show` methods
    - overrides `before_action` to `set_current_user` for `index` and `show` methods
    - _inherit from this if you want a controller to allow unauthenticated `index` and `show` actions_
5.  [examples_controller](https://github.com/ga-wdi-boston/rails-api-template/blob/master/app/controllers/examples_controller.rb)
    - inherits from `open_read_controller`
    - handles `example` resource actions
