### ISSUE TITLE
Issue when deploying to GitHub pages

### ISSUE THREAD

**Issue by joebelmonte** [ga-wdi-boston/full-stack-project#816]
Hi, 

When I type "grunt deploy" on my master branch, it fails.  The warning says there are thousands of node files in the node_models/ folder that haven't been tracked in my gh-pages branch.  I have tried deleting that branch and re-trying.  I'm not sure what's causing these untracked files to show up in that branch.  My master branch says it's clean before running the grunt deploy command.  I can run grunt serve successfully...

[Screen Shot 2017-05-04 at 3.00.48 PM.png.pdf](https://github.com/ga-wdi-boston/full-stack-project/files/977273/Screen.Shot.2017-05-04.at.3.00.48.PM.png.pdf)

**Comment by jordanallain** [comment]
what were the steps you took before running `grunt deploy`?

**Comment by joebelmonte** [comment]
I wrote some basic html and got my user authentication working locally on a "working branch."  I merged the working branch into the master.  Pushed both branches to GitHub.  

On GitHub, I went to "settings" for the repo and set up GitHub pages for the master branch.  

When I go to the link (https://joebelmonte.github.io/project_2_front_end/) it looks like just the html loaded and nothing else....

**Comment by jordanallain** [comment]
`On GitHub, I went to "settings" for the repo and set up GitHub pages for the master branch.`

what do you mean by that? were you following the instructions for this part?

**Comment by joebelmonte** [comment]
This is the page https://github.com/joebelmonte/project_2_front_end/settings

Here's a screen shot in case that doesn't come through...

[Screen Shot 2017-05-04 at 3.51.14 PM.png.pdf](https://github.com/ga-wdi-boston/full-stack-project/files/977394/Screen.Shot.2017-05-04.at.3.51.14.PM.png.pdf)

For instructions, I googled and found instructions which directed me to this setting....

**Comment by jordanallain** [comment]
that was not necessary and you may have to undo what you changed.

**Comment by joebelmonte** [comment]
OK, I created an entirely new repo (both local and on git hub) and re-downloaded the browser template.  I didn't make any modifications to it.  I tried to grunt deploy and got the same error...

**Comment by jordanallain** [comment]
did you `git init` in the local repo and `git remote add <ssh-of-remote-repo>` ?

**Comment by joebelmonte** [comment]
yes

**Comment by joebelmonte** [comment]
Do you happen to have a copy of the instructions?  Maybe I am missing something, but I've not tried it twice  on completely new repos and gotten the same problem both times.  I've spent about 2 hours on this  and not gotten anywhere.  I apologize for asking for the instructions - I recall they were given to us for the last project, but I cannot seem to locate them.  I have 100+ repos on my GitHub at this point and can't find the one that contains the link - I've looked a couple of times with no luck.  I'm thinking that it may have been in a repo that I didn't fork, in which case I think it will be tough to find.  I tried the search feature on GitHub but it didn't seem that useful and there are too many repos on WDI for me to search one by one...

**Comment by jordanallain** [comment]
[deploying front end](https://git.generalassemb.ly/ga-wdi-boston/gh-pages-deployment-guide)

[deploying back end](https://git.generalassemb.ly/ga-wdi-boston/rails-heroku-setup-guide)

is that what you wanted? or the template instructions?

**Comment by jordanallain** [comment]
[browser template set up](https://git.generalassemb.ly/ga-wdi-boston/browser-template)

[rails api template set up](https://git.generalassemb.ly/ga-wdi-boston/rails-api-template)

**Comment by joebelmonte** [comment]
The deploying front end was what I was looking for - thank you for sending it.  Unfortunately I have been doing what it says.  Not sure what's going on here.  This took me 5 minutes for tic tac toe.

**Comment by joebelmonte** [comment]
I've got it working now.  For future reference, I think the issue was that when I downloaded the browser template, I should have renamed the folder but instead I moved its contents into a folder I had already set up with the name I wanted.  I'm guessing the copy/paste missed some hidden files.
