### ISSUE TITLE
New but similar error - 500 error

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/full-stack-project#817]
When I try to post to my deployed site and send a post request I get a 500 error
```
maggicorp.github.io/:1 XMLHttpRequest cannot load https://advice-app-maggicorp.herokuapp.com/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://maggicorp.github.io' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by jordanallain** [comment]
did you try with CURL? or is this through an AJAX request?

**Comment by Maggicorp** [comment]
The curl requests have no errors and return a 200 messages.  This is through ajax

**Comment by jordanallain** [comment]
can you post the ajax ?

**Comment by Maggicorp** [comment]
yes, it works locally
```
const signUp = (data) => {
  console.log('reached api sign up')
  console.log(data)
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data
  })
}
```

**Comment by jordanallain** [comment]
where is it grabbing this from `maggicorp.github.io/:1` ?

**Comment by Maggicorp** [comment]
Yes, it seems that is somehow configured wrong.  How and where would it set that?

**Comment by Maggicorp** [comment]
It is being called from https://maggicorp.github.io/front-end-full-stack/

**Comment by Maggicorp** [comment]
On heroku the client origin is set to https://Maggicorp.github.io
is that not right? I that it wasn't supposed to include the local repo

**Comment by jordanallain** [comment]
it should end at `io` that is correct but it looks like it is trying to use an id or something on the end of the url. did you change everywhere that it says `browser-template` to be your project name?

**Comment by Maggicorp** [comment]
What do you mean by project name? The project has a lot of names.

**Comment by jordanallain** [comment]
sorry i meant in the back end not the front end, theres a step to replace `rails-api-template` and `RailsApiTemplate`

**Comment by Maggicorp** [comment]
I think that was the problem.  Would it be possible for someone to come look at it with me.  I think the set up was wrong and I am trying to go back and fix it

**Comment by Maggicorp** [comment]
Heroku didn't let me use my original name idea because that was taken so I had to make up another and they didn't match

**Comment by Maggicorp** [comment]
I changed it to  adviceappmaggicorp
but now I need to reconfigured the origin.

**Comment by Maggicorp** [comment]
I ran 
``` heroku apps:rename adviceappmaggicorp ``` which should I have changed the configuration but it just returned couldn't find that app.

**Comment by Maggicorp** [comment]
tried it again and it still couldn't find the app name even though I can see that it exsists and is changed on the heroku dashboard

**Comment by jordanallain** [comment]
you can always set up a new app on heroku if you feel like you messed up on the set up steps, may be quicker than resolving this.

**Comment by Maggicorp** [comment]
I could do that, but how do I disconnect this one? It seems like I should just be able to udpate the name?

**Comment by jordanallain** [comment]
what do you mean by disconnect?

**Comment by Maggicorp** [comment]
Still getting errors.  It seems like they are cors errors.  I can sign up and in but i get 400 errors when I try to change my password or sign out.  
```
maggicorp.github.io/:1 XMLHttpRequest cannot load https://vast-coast-80096.herokuapp.com/sign-out/5. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://maggicorp.github.io' is therefore not allowed access. The response had HTTP status code 404.
```
  I put this code into the controlller.rb file to make sign up and sign in work
```
before_filter :allow_cors_requests

  def allow_cors_requests
    headers["Access-Control-Allow-Origin"] = "*"
    headers["Access-Control-Allow-Methods"] = %w{GET POST PUT DELETE}.join(",")
    headers["Access-Control-Allow-Headers"] = %w{Origin Accept Content-Type X-Requested-With X-CSRF-Token}.join(",")
    head(:ok) if request.request_method == "OPTIONS"
    # or, render text: ''
```

**Comment by Maggicorp** [comment]
I would love some one one one help.  This seems like a browers security issues and I'm not sure how to get around this.

**Comment by BenGitsCode** [comment]
I think this may be solved by deleting your heroku app and creating a new one

**Comment by BenGitsCode** [comment]
What's the output of `heroku config` and `heroku info`?

**Comment by Maggicorp** [comment]
I did that already. 
heroku config
```
=== vast-coast-80096 Config Vars
DATABASE_URL:             postgres://jxisqpsntffmjr:ea8f533fe5e23dc83ed66bb1edc1f98fb6fe1ee93d1f623c35e798e30b410b12@ec2-54-235-120-39.compute-1.amazonaws.com:5432/d19bjpklmucvok
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_LOG_TO_STDOUT:      enabled
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:          4feeb5311ca26012021e5284666ed88ccd3885ba7a738a43381ec448dcf6cbe0c5969f60357801c5cdbd1c47f5f10ad023cc64628673cbef4d965bc5191cfa37
```

**Comment by Maggicorp** [comment]
heroku info says 
```
=== vast-coast-80096
Addons:         heroku-postgresql:hobby-dev
Auto Cert Mgmt: false
Dynos:          web: 1
Git URL:        https://git.heroku.com/vast-coast-80096.git
Owner:          mvjcasey@gmail.com
Region:         us
Repo Size:      82 KB
Slug Size:      26 MB
Stack:          cedar-14
Web URL:        https://vast-coast-80096.herokuapp.com/
```

**Comment by BenGitsCode** [comment]
I don't see that in this issue but thank you for posting.

It lookslike you may have missed steps in the heroku deployment guide. Your configuration is incomplete.

**Comment by BenGitsCode** [comment]
[typo edit] cross-reference this issue with the heroku section of the deployment guide. Do you see what's missing?

**Comment by Maggicorp** [comment]
we changed the config origin but I am still getting errors.  Is that what you saw that was missing?

**Comment by Maggicorp** [comment]
fixed for the moment **finger crossed**. Not sure why exactly, I made a few changes, but it might have been setting the origin.
