### ISSUE TITLE
Point of clarification localhost vs. CURL

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/full-stack-project#818]
So when I run the curl request for index, I am given a 200 status code and returned a json manifestation of all movies associated with my current user. However, when I go to `http://localhost:4741/movies/` to check, I am seeing a 500 NoMethodError. 

I am inclined to disregard this, as my curl requests are manifesting appropriately, and that this is likely the result of the localhost not being cognizant of an active user. Is this inclination/the logic behind this inclination accurate?

**Comment by MicFin** [comment]
Your back end API is not set up to send back HTML so you can not visit it at the URL directly.  It is only set up to respond with JSON from AJAX requests
