### ISSUE TITLE
Seeding DB with CSV file, created character varying data types in pgres columns

### ISSUE THREAD

**Issue by mangoceylon** [ga-wdi-boston/full-stack-project#819]
I have this in my seeds.rb file in order to provide data to my db:
```require 'csv'

csv_text = File.read(Rails.root.join('db', 'data', 'ingredients.csv'))
csv = CSV.parse(csv_text, :headers => true, :encoding => 'ISO-8859-1')
csv.each do |row|
  t = Ingredient.new
  t.name = row['name']
  t.measurement = row['measurement']
end
```

It resulted in creating columns that have "character varying" type. I think I need to add something to make the columns strings when they are loaded, something like:

```t.name = string.row['name']```

But I'm not sure of the syntax and google wasn't helping much.

Would the character varying inputs would even be an issue in this case? These columns are not going to allow create/patch/delete only GET so I don't care about users uploading insanely long data or anything here.

**Comment by jordanallain** [comment]
can you post the output you were seeing?

**Comment by MicFin** [comment]
Also share the CSV

**Comment by mangoceylon** [comment]
The csv is the same one from the cookbook SQL lessons, header row is:
ingredient, measurement,
avocado, grams,
celery, pounds, etc.

Here is the database that shows the value types. Again, only will be getting from this db so there won't be any issues with accepting data into it, but not sure if this data type will cause an issue otherwise:

<img width="795" alt="screen shot 2017-05-05 at 9 12 26 am" src="https://cloud.githubusercontent.com/assets/26262143/25746831/28387970-3173-11e7-9c88-b48e1b4bae5b.png">

**Comment by MicFin** [comment]
That is ok https://pmatsinopoulos.github.io/blog/2014/06/11/using-string-column-type-for-migrations/

**Comment by mangoceylon** [comment]
Ok so this script isn't actually loading the data, I'm left with a DB with no rows. So there seems to be an issue somewhere with loading the csv syntax wise.

**Comment by mangoceylon** [comment]
I have a workaround that seems fine, which is just manually loading the data each time I initialize the application, but if the right way to seed from a csv comes to mind I'm open to it!

**Comment by tvcrawley** [comment]
Have you looked at the [`rails-api-library-demo db/examples.rb`](https://github.com/ga-wdi-boston/rails-api-library-demo/blob/017/training/db/examples.rb)? Data is being loaded from a csv there.

**Comment by mangoceylon** [comment]
That should do it thanks!
