### ISSUE TITLE
In creating a new honey I am getting error

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/full-stack-project#82]
error: POST http://localhost:3000/honeys 401 (Unauthorized)

**Comment by gaand** [comment]
Are you setting the Authorization header in your request?

**Comment by LaurisaNeuwirth** [comment]
I think so:

honeyAPI.logout = function (token, id, callback) {
    this.ajax({
      method: 'DELETE',
      url: this.server + '/logout/' + id,
      headers: {
        Authorization: 'Token token=' + token
      },
      dataType: 'json'
    }, callback);
  };

**Comment by LaurisaNeuwirth** [comment]
i forgot to send this code snippet sorry

**Comment by gaand** [comment]
No worries.  Please send the code that calls this method.

**Comment by LaurisaNeuwirth** [comment]
here is my error on the 3000 server, yes I will send the code too

Started POST "/honeys" for ::1 at 2015-11-12 14:24:06 -0500
Processing by HoneysController#create as HTML
  Parameters: {"honey"=>{"name"=>"Steve"}}
  User Load (1.1ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "undefined"]]
  Rendered text template (0.2ms)
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 17ms (Views: 4.0ms | ActiveRecord: 1.1ms)

**Comment by LaurisaNeuwirth** [comment]
$('#add_your_honey').on('submit', function(e) {

```
 e.preventDefault();
 var token = $('.token').val();
 var new_honey = wrap('honey', form2object(this));
 honeyAPI.new_honey(token, new_honey, function(err, honeyData) {
   if(err) {
     // do something with the error
     return;
   } else{
     console.log(honeyData);
   }
 });
```

   });   // end of add_you_ho

**Comment by gaand** [comment]
The JavaScript you sent is for logout.  What's the code for new_honey?

**Comment by LaurisaNeuwirth** [comment]
$('#add_your_honey').on('submit', function(e) {

```
 e.preventDefault();
 var token = $('.token').val();
 var new_honey = wrap('honey', form2object(this));
 honeyAPI.new_honey(token, new_honey, function(err, honeyData) {
   if(err) {
     // do something with the error
     return;
   } else{
     console.log(honeyData);
   }
 });
```

   });

**Comment by LaurisaNeuwirth** [comment]
here is the ajax

honeyAPI.new_honey = function (token, new_honey, callback) {
   this.ajax({
     method: 'POST',
     url: honeyAPI.server + '/honeys',
     headers: {
       authorization: 'Token token=' + token
     },
     contentType: 'application/json; charset=utf-8',
     data: JSON.stringify(new_honey),
     dataType: 'json'

   }, callback);
 };

**Comment by gaand** [comment]
I'm not sure it's case sensitive, but authorization is capitalized.  Check that and if it doesn't work please meet me in classroom 1.

**Comment by gaand** [comment]
Sorry, **should be capitalized**

**Comment by gaand** [comment]
Got token from app object.
