### ISSUE TITLE
500 error, null value in collumn...

### ISSUE THREAD

**Issue by Anddrew914** [ga-wdi-boston/full-stack-project#821]
I'm trying to write the curl request for my first item in my new table. I'm getting this error. 
{"status":500,"error":"Internal Server Error","exception":"#\u003cActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column \"instrument_type\" violates not-null constraint\nDETAIL:  Failing row contains (1, null, null, 60.00, null, null, 2017-05-04 23:09:05.962589, 2017-05-04 23:09:05.962589).

And this is my curl request. 
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/instruments"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=8a9d5dfe68f51d16e2f11e6c4028f23b" \
  --data '{
    "instrument": {
      "instrument_type": "Stradivarius",
      "price": "60.00"
    }
  }'

echo

So the type column does have data going in as far as I can tell. Let me know if you need any more info.

**Comment by jordanallain** [comment]
what does the instrument_type column accept?

**Comment by Anddrew914** [comment]
A string. I think it's related to this issue. https://github.com/ga-wdi-boston/full-stack-project/issues/550  I first created the column as just "type" and ran a migration. I was told that "type" is a reserved word so I had to change the column name. I reverted migration and renamed the  column but only in the migration file then reran the migration which I think screwed up my route naming convention. Now I"m going to revert again, destroy scaffold, rescaffold with the correct names and see if that fixes it. I'll report back.

**Comment by Anddrew914** [comment]
Nope, that didn't do it. Really thought it would. Here's the error again 
```
{"status":500,"error":"Internal Server Error","exception":"#\u003cActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column \"instrument_type\" violates not-null constraint\nDETAIL:  Failing row contains (1, null, null, 60.00, null, 2017-05-05 00:17:21.689633, 2017-05-05 00:17:21.689633)
```
and here's the curl request again.
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/instruments"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=8a9d5dfe68f51d16e2f11e6c4028f23b" \
  --data '{
    "instrument": {
      "instrument_type": "Stradivarius",
      "price": "60.00"
    }
  }'

echo
```
and, curiously, my controller params still looks like this, I have a hunch it's the issue.     def 
```
instrument_params
      params.require(:instrument).permit(:instrument, :maker, :price, :details)
    end
end
```

**Comment by jordanallain** [comment]
hmm, you most likely want :instrument_type to be a permitted param i would think

**Comment by Anddrew914** [comment]
Yeah I've tried changing it manually.  I also redid the scaffolding command twice and that is how the controller sets it as a default.

**Comment by MicFin** [comment]
What's your schema look like?

**Comment by MicFin** [comment]
Does this:
```rb
def instrument_params
  params.require(:instrument).permit(:instrument, :maker, :price, :details)
end`
```
Match this?

```
--data '{
    "instrument": {
      "instrument_type": "Stradivarius",
      "price": "60.00"
    }
  }'
```

**Comment by Anddrew914** [comment]
```
create_table "instruments", force: :cascade do |t|
    t.string   "instrument_type",                         null: false
    t.string   "maker"
    t.decimal  "price",           precision: 8, scale: 2, null: false
    t.text     "details"
    t.datetime "created_at",                              null: false
    t.datetime "updated_at",                              null: false
  end
```
This is my schema.

**Comment by MicFin** [comment]
What does this line do?
```rb
t.string   "instrument_type",                         null: false
```
What does this line do?
```rb
params.require(:instrument).permit(:instrument, :maker, :price, :details)
```

**Comment by Anddrew914** [comment]
When I change the controllers to look like 
```
params.require(:instrument_type).permit(:instrument_type, :maker, :price, :details)

or

params.require(:instrument).permit(:instrument_type, :maker, :price, :details)

```
I get 

```
{"status":400,"error":"Bad Request","exception":"#\u003cActionController::ParameterMissing: param is missing or the value is empty: instrument_type\u003e"

and

{"status":500,"error":"Internal Server Error","exception":"#\u003cActiveModel::UnknownAttributeError: unknown attribute 'instrument_type' for Instrument.\
```
respectively.

**Comment by MicFin** [comment]
Have you restarted your server?

**Comment by Anddrew914** [comment]
I have not. Should I revert, destroy scaffold, restart server, scaffold and
migrate?

**Comment by MicFin** [comment]
I would start with just restarting the server

**Comment by MicFin** [comment]
Does the ID of your last migration match the ID at the top of your schema?  
- Is so, then the schema looks good so you don't need to do any migrations.

Your controller doesn't need to be re-scaffolded, but you do need to fix the `instrument_params` method.
```rb
def instrument_params
  params.require(:instrument).permit(:instrument, :maker, :price, :details)
end`
```
The first part `params.require(:instrument)` means that the hash in the request must have a `instrument` key.  As yours does here:  
```
--data '{
    "instrument": {
```
The second part `.permit(:instrument, :maker, :price, :details)` means that the `instrument` hash may only have the following keys `instrument`, `maker`, `price`, `details`.  You sent the following keys:
```
--data '{
    "instrument": {
      "instrument_type": "Stradivarius",
      "price": "60.00"
    }
```

When you changed the `instrument_params` to
```rb
params.require(:instrument_type).permit(:instrument_type, :maker, :price, :details)
```
 then you got a 
```js
{"status":400,"error":"Bad Request","exception":"#\u003cActionController::ParameterMissing: param is missing or the value is empty: instrument_type\u003e"
``` 
because it required a `instrument_type` key first and you sent `instrument`.  

When you changed the `instrument_params` to
```rb
params.require(:instrument).permit(:instrument_type, :maker, :price, :details)
```
 then you got a 
```js
{"status":500,"error":"Internal Server Error","exception":"#\u003cActiveModel::UnknownAttributeError: unknown attribute 'instrument_type' for Instrument.\
``` 
because...well I'm not sure but that sounds it has to do with the database but that message `unknown attribute 'instrument_type' for Instrument` doesn't seem to be an issue with the schema.
```rb
create_table "instruments", force: :cascade do |t|
    t.string   "instrument_type",                         null: false
```
1.  Did you restart your server since your last migration?
2.  What's the model look like?
3.  Was this the curl request data that caused that? 
```
--data '{
    "instrument": {
      "instrument_type": "Stradivarius",
      "price": "60.00"
    }
  }'
```

**Comment by Anddrew914** [comment]
Restarting the server and renaming the controller worked. Any idea why the controller wouldn't generate properly and why restarting the server was necessary to make it all work?
