### ISSUE TITLE
post curl request error

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/full-stack-project#823]
I am trying to run my create advice curl script and it is returning a 500 error. The curl script says (aside, I am passing a token in, passing the token like this worked for my index curl request so I don't think that is where the problem is.)
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/advices"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
    --header "Authorization: Token token=9160e1769f9f1d5a0134865c7e29191b" \
  --data '{
    "advice": {
      "idea": "'"Help a buddy out"'"
    }
  }'

echo
```
The error says
```
NoMethodError (undefined method `advices' for nil:NilClass):
  
app/controllers/advices_controller.rb:18:in `create'
Started POST "/advices" for 127.0.0.1 at 2017-05-04 23:44:16 -0400
Processing by AdvicesController#create as */*
  Parameters: {"advice"=>{"idea"=>"Help a buddy out"}}
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms)
NoMethodError (undefined method `advices' for nil:NilClass):
app/controllers/advices_controller.rb:18:in `create'
```
The advices controller defines create here
```
def create
    @advice = current_user.advices.build(advice_params)

    if @advice.save
      render json: @advice, status: :created, location: @advice
    else
      render json: @advice.errors, status: :unprocessable_entity
    end
  end
```
and the route to it is
```
  resources :advices, except: [:new, :edit]
```

**Comment by Maggicorp** [comment]
Hey, this curl request still doesn't work, but my ajax request works so I am not too worried about it.

**Comment by danman01** [comment]
Note that `index` is a read action and `create` is a create, as you know, so you may have different permissions for the various actions. If you dig into the error, what is the object that is `nil` that should have the method `advices`, but does not? Also, how does your ajax request differ from curl?

**Comment by danman01** [comment]
@Maggicorp can we close this issue if it's not a concern, or would you like to get it working?

**Comment by Maggicorp** [comment]
That makes sense, thanks.
