### ISSUE TITLE
migrating issue

### ISSUE THREAD

**Issue by eliottenos** [ga-wdi-boston/full-stack-project#824]
I generated scaffold with ```bin/rails generate scaffold location title:string body:text user:references``` but now unable to ```bin/rake db:create``` or ```bin/rake db:migrate```

Terminal says the returns the following:
```
rails aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
/Users/eliottenos/Documents/eliott-rails-api/bin/rails:9:in `require'
/Users/eliottenos/Documents/eliott-rails-api/bin/rails:9:in `<top (required)>'
/Users/eliottenos/Documents/eliott-rails-api/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by tvcrawley** [comment]
Have you carefully read the error message? Looks like it is providing some useful information.

**Comment by eliottenos** [comment]
Not connecting to the server for some reason.  I get the same error in console during authentication process also...
```
PG::ConnectionBad (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

**Comment by tvcrawley** [comment]
Right, mainly this part: `Is the server running locally`

**Comment by danman01** [comment]
So this is a postgresql server not running error. Try to tackle it on your own by going through the steps in `brew info postgresql`, specifically at the very bottom of the output to start / restart the postgresql server. If you feel uncomfortable mucking around with that stuff / think you may mess up your system settings, feel free to confirm here or on slack what command you are going to run.

`ps aux | grep postgresql` should report a process is running when your server is started correctly.

(these commands are run from the terminal)

**Comment by eliottenos** [comment]
followed the steps to remove and reinstall but still getting the same error
```ps aux | grep postgresql``` is showing

```
44631 100.0  0.0  2432804    776 s001  S+   10:24am   0:00.00 grep postgresql
```

**Comment by eliottenos** [comment]
Solved!

had to remove this file ```postmaster.pid``` and now working fine

**Comment by danman01** [comment]
Nice work!
