### ISSUE TITLE
How to properly build an object for CURL submission

### ISSUE THREAD

**Issue by Anddrew914** [ga-wdi-boston/full-stack-project#829]
I'm trying to submit my first violin to my form via my webpage. I wrote a curl request that worked so now I"m trying to figure out how to get my forms to submit in that same form. Here's a correct Curl submission
```
  Parameters: {"instrument"=>{"instrument_type"=>"Stradivarius", "price"=>"60.00"}}
   (0.1ms)  BEGIN
  SQL (34.1ms)  INSERT INTO "instruments" ("instrument_type", "price", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["instrument_type", "Stradivarius"], ["price", #<BigDecimal:7fa305b934a8,'0.6E2',9(18)>], ["created_at", 2017-05-05 12:56:33 UTC], ["updated_at", 2017-05-05 12:56:33 UTC]]
```

That was done with curl. 

Here's my current webpage submission
```
Started POST "/instruments/" for 127.0.0.1 at 2017-05-05 11:22:03 -0400
Processing by InstrumentsController#create as */*
  Parameters: {"instrument_type"=>"Guarneri", "price"=>"70.00", "submit"=>"Submit"}
Completed 400 Bad Request in 0ms (ActiveRecord: 0.0ms)
```

So it looks like I need to add "instruments" to my params and also get rid of the "submit" part. Step one for me is adding :"instruments". I tried manually adding that to

```
const onAddInstrument = function (event) {
  console.log('events')
  event.preventDefault()
  const data = "instruments" + getFormFields(event.target) # I added ["instruments" + ] here

  api.addInstrument(data)
    .then(ui.addInstrumentSuccess)
    .catch(ui.addInstrumentFailure)
}
```
but that get's me an error in my server like so
```
Started POST "/instruments/" for 127.0.0.1 at 2017-05-05 11:27:10 -0400
Processing by InstrumentsController#create as */*
  Parameters: {"instruments"=>{"object Object"=>nil}}
Unpermitted parameter: object Object
```

do I need to dig into getFormFields here and edit how it turns form info into data?

**Comment by tvcrawley** [comment]
How were you able to accomplish this before? What could help solve this problem? Have you compared this to previously written code?...Maybe to your game project?

**Comment by Anddrew914** [comment]
Yeah i've been digging through old files and the internet. I've never had to modify the results of get form fields before.

**Comment by jrhorn424** [comment]
> Started POST "/instruments/" for 127.0.0.1 at 2017-05-05 11:22:03 -0400

Look at the resource name.

> Processing by InstrumentsController#create as */*
>  Parameters: {"instrument_type"=>"Guarneri", "price"=>"70.00", "submit"=>"Submit"}

Look at your root key in that JSON. (BTW, you build JSON, not objects, to submit via `curl`. I'm not just being a pedant.)

Finally, look at your strong params. Then answer @tvlangley's questions one by one.

**Comment by Anddrew914** [comment]
Okay, so it turns out I was indeed misunderstanding how get form fields was working. I needed to change how I was structuring my HTML forms to get the right object built for the request. Now that I have that I'm getting a new error 

```
Started POST "/instruments/" for 127.0.0.1 at 2017-05-05 14:11:42 -0400
Processing by InstrumentsController#create as */*
  Parameters: {"instrument"=>{"instrument_type"=>"guarneri", "price"=>"70.00"}}
   (0.2ms)  BEGIN
   (0.1ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.1ms)
Completed 422 Unprocessable Entity in 22ms (Views: 0.8ms | ActiveRecord: 4.7ms)

```

compared to my working curl request
```
 Parameters: {"instrument"=>{"instrument_type"=>"Stradivarius", "price"=>"60.00"}}
   (0.1ms)  BEGIN
  SQL (34.1ms)  INSERT INTO "instruments" ("instrument_type", "price", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["instrument_type", "Stradivarius"], ["price", #<BigDecimal:7fa305b934a8,'0.6E2',9(18)>], ["created_at", 2017-05-05 12:56:33 UTC], ["updated_at", 2017-05-05 12:56:33 UTC]]
```
 the object seems to be constructed properly. 
I have nuked and paved my DB but that didn't help

**Comment by Anddrew914** [comment]
This might need to be a new issue or it might be a continuation of the last one, I'm not sure.

**Comment by danman01** [comment]
@Anddrew914 could you close this one, and open a new issue and put this in:

```
Started POST "/instruments/" for 127.0.0.1 at 2017-05-05 14:11:42 -0400
Processing by InstrumentsController#create as */*
  Parameters: {"instrument"=>{"instrument_type"=>"guarneri", "price"=>"70.00"}}
   (0.2ms)  BEGIN
   (0.1ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.1ms)
Completed 422 Unprocessable Entity in 22ms (Views: 0.8ms | ActiveRecord: 4.7ms)
```

As well as the output from your rails server showing that incoming reuqest and resulting error
