### ISSUE TITLE
help debugging PATCH request

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/full-stack-project#83]
I'm getting {"message":"Not Found"} when I PATCH requests in postman. I don't see anything in my controller that would return a message, much less this one. I am sure that I am requesting a patch for an existing id number.

**Comment by gaand** [comment]
Please post the code from the update action.

**Comment by gaand** [comment]
Sorry, I should have said, that message comes from my code.

**Comment by raq929** [comment]
The message I get back is {"message":"Not Found"} 
 I don't think it's getting to the controller, because if it were, it would be complaining about multiple render json: 
But the route is definitely there, so I don't know what's up. 

The code in the controller is:

```
def update
    singing = Singing.find(singing_params[:id])
    render json: singing_params
    singing.update(singing_params)
    if singing.save
      render json: singing
    else
      render json: singing.errors, status: :unprocessable_entity
    end
  end
```

I'm pretty frustrated at this point, and I'd really appreciate some in-person help on this issue and the heroku deployment issue. I have not gotten any in-person attention this project week, and a few minutes would mean a lot to me.

**Comment by raq929** [comment]
I've tested multiple other things that use singings_params, so I'm pretty sure that's not the issue.

**Comment by gaand** [comment]
Please post the output of `rake routes`.

**Comment by raq929** [comment]
caller_calls GET    /callers/:caller_id/calls(.:format)       calls#index
  caller_call GET    /callers/:caller_id/calls/:id(.:format)   calls#show
      callers GET    /callers(.:format)                        callers#index
       caller GET    /callers/:id(.:format)                    callers#show
singing_calls GET    /singings/:singing_id/calls(.:format)     calls#index
 singing_call GET    /singings/:singing_id/calls/:id(.:format) calls#show
     singings GET    /singings(.:format)                       singings#index
              POST   /singings(.:format)                       singings#create
  new_singing GET    /singings/new(.:format)                   singings#new
 edit_singing GET    /singings/:id/edit(.:format)              singings#edit
      singing GET    /singings/:id(.:format)                   singings#show
              PATCH  /singings/:id(.:format)                   singings#update
              PUT    /singings/:id(.:format)                   singings#update
              DELETE /singings/:id(.:format)                   singings#destroy
   song_calls GET    /songs/:song_id/calls(.:format)           calls#index
    song_call GET    /songs/:song_id/calls/:id(.:format)       calls#show
        songs GET    /songs(.:format)                          songs#index
         song GET    /songs/:id(.:format)                      songs#show
     register POST   /register(.:format)                       auth#register
      confirm PATCH  /confirm(.:format)                        auth#confirm
        login POST   /login(.:format)                          auth#login
              DELETE /logout/:id(.:format)                     auth#logout
        users GET    /users(.:format)                          users#index
              POST   /users(.:format)                          users#create
         user GET    /users/:id(.:format)                      users#show
              PATCH  /users/:id(.:format)                      users#update
              PUT    /users/:id(.:format)                      users#update
              DELETE /users/:id(.:format)                      users#destroy

**Comment by gaand** [comment]
Please meet me in classroom 1.

**Comment by gaand** [comment]
First we'll look at what rails sends to the terminal.

**Comment by gaand** [comment]
Replaced using strong params with `params[:id]`.
