### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by pjliddy** [ga-wdi-boston/full-stack-project#830]
I'm at a stable point and would like to have a consultant review where my project is before I move on to the next pieces.

Deployed project: https://pjliddy.github.io/snippet-list-client
Client repo: https://github.com/pjliddy/snippet-list-client
API repo: https://github.com/pjliddy/snippet-list-api

I've got a backlog of items on my immediate to-do list: https://trello.com/b/pW91c8HS/snippet-list

**Comment by jordanallain** [comment]
what is the stable point you are at? are you able to CRUD your resource?

**Comment by pjliddy** [comment]
I can crud my resources and have a functioning UI for all the responses.

**Comment by jordanallain** [comment]
Everything looks to be functioning properly as far as i can tell. You've got a ton of console.logs to get rid of but I'm sure you were gonna get around to that. Did you have some particular features in mind that you wanted to meet and chat about?

**Comment by pjliddy** [comment]
I'd like to implement another table for tagging or categorization using TDD.

Also, I want to implement a JS code coloring library that allows it to be implemented as an API but I think it's as a node.js api. I could use a second set of eyes on it (https://highlightjs.org/)

**Comment by jrhorn424** [comment]
Did you have specific questions other than:

>  but I think it's as a node.js api

?

**Comment by pjliddy** [comment]
If it's going to be a local JS implementation vs. something hosted and accessed via REST, should I use it for my project or should I find something that uses REST? The JS version has better features, but technically the implementation would be a 3rd party JS library, not a 3rd party API.

**Comment by jrhorn424** [comment]
"3rd party API" refers to a RESTful service you do not control.

"API" typically means a RESTful service you do control. Sometimes called "1st party API".

"API" also means "description of how to use a library, including documented public methods, their signatures and return values".

You should include highlight.js if you wish. It's a pretty neat library. But the way you would use it is to style elements that contain code that you render from your own server.

**Comment by pjliddy** [comment]
I left out one link. There's documentation for an API based on highlight.js (Highlight.js exports a few functions as methods of the `hljs` object.

http://highlightjs.readthedocs.io/en/latest/api.html

I think it can be build to run locally as an api:

http://highlightjs.readthedocs.io/en/latest/building-testing.html

**Comment by jordanallain** [comment]
You should be able to install it with npm and require the module or specific methods you want.

**Comment by jordanallain** [comment]
@pjliddy can this be closed?
