### ISSUE TITLE
debugger is breaking my code

### ISSUE THREAD

**Issue by rowlandhill** [ga-wdi-boston/full-stack-project#831]
Hi!  I'm trying to check an error in my code with debugger, but I'm getting a linter error when I try to use it.  Please see below for code and picture of linter error (linter error is `'Unexpected 'debugger' statement. (no debugger)`:

```js
const onUpdateRecipe = function (event) {
  // console.log(data)
  const data = getFormFields(event.target)
  event.preventDefault()
  api.updateRecipe(data)
    .then(ui.recipeStateSuccess)
    .catch(ui.recipeStateFailure)
  debugger
}
```

[here is a picture of the linter error](http://imgur.com/jShjOUJ)

Is there a way for me to use debugger?  What do I need to change in Atom?

Thanks!

**Comment by danman01** [comment]
Alternatively, you can open the chrome dev tools inspector, and use the chrome debugger.
The location of your files in the sources tab of the inspector is a little opaque: 

sources tab   -> 
   webpack    -> 
      .               -> 
        your file -> 
            click on line number to add debugger

More: https://developers.google.com/web/tools/chrome-devtools/javascript/

**Comment by danman01** [comment]
Any luck debugging?

**Comment by jordanallain** [comment]
linter will complain about the debugger, its a good way to remember to take it out before deploying.

**Comment by rowlandhill** [comment]
I was able to add it in chrome, using the instructions you provided.  Thanks, @danman01 !

@jordanallain is there a way to change linter to allow debugger?  Adding debugger in is breaking my code and not allowing me to run anything :/

**Comment by jordanallain** [comment]
it shouldn't be stopping you from running things, what do you mean by that last sentence?

**Comment by rowlandhill** [comment]
When I add debugger to a function, it breaks the function.  After I add debugger, I go back to localhost, but the entire page is broken and my console gives me an error pointing to debugger.  If I remove debugger, my page loads.

**Comment by MicFin** [comment]
I just don't think you can put debugger specifically where you did.
```js
const onUpdateRecipe = function (event) {
  // console.log(data)
  const data = getFormFields(event.target)
  event.preventDefault()
 debugger 
 api.updateRecipe(data)
    .then(ui.recipeStateSuccess)
    .catch(ui.recipeStateFailure)
}
```
Try that.  If you want to see what goes on inside the `ui.recipeStateSuccess` then add a debugger in that methods definition.

**Comment by rowlandhill** [comment]
Success!  Thank you!  I don't know why it wasn't working before when I placed it below `event.preventDefault()` but it's working now.

Thanks!
