### ISSUE TITLE
Is it safe to manually delete old migration files?

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/full-stack-project#832]
Is it safe to manually delete old create_tablename migration files, along with its corresponding models and controllers? I reverted back to version 2 of the database, but my old migration files are still there (xxxxxxxx_create_words, xxxxxxx_create_authors, and xxxxxxx_add_author_to_words). I'd like to delete all migration files and files I worked on so that I could work on a clean slate (original template at version 2).

I found solutions online to run ```rails destroy``` commands (http://stackoverflow.com/questions/7105373/removing-a-model-in-rails-reverse-of-rails-g-model-title) but I'd prefer deleting them manually if possible.

**Comment by danman01** [comment]
You can delete the migration files manually, if you have rolled back to a previous state and do not want to re-run the files. To keep everything in the `rails` world, you do have the destroy command available as you discovered. But manually deleting should be fine. 

Alternatively, you could keep the migrations, then create another migration to drop the database table to preserve the history of what your schema has endured. I would personally go the manual deletion route after migrating back, like you have down, if I don't need / care about that history. ***If you are working with a team, you should absolutely create a migration to drop the table, as other users of the team will then be able to run that migration to drop the table.***

**Comment by nriser** [comment]
@danman01 Thank you for your reply. Great, I'll delete the migration files. So I'm assuming it's fine to delete the corresponding models and controller files as well?

**Comment by danman01** [comment]
Yes, if you no longer need them, you can delete them. Just because there's no database table doesn't necessarily mean you don't want / can't make use of a controller / model, but in your case I believe you don't want the related scaffolding for that resource.

**Comment by nriser** [comment]
@danman01 great, thank you! I'll delete those files too.
