### ISSUE TITLE
Receiving net:: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Pouk91** [ga-wdi-boston/full-stack-project#833]
When i try to sign up i receiving the following error in the console. I am not sure what's causing this, but its causing my api to fail
jquery.js:9566 POST http://localhost:4741//sign-up net::ERR_CONNECTION_REFUSED

```html
  <form id="sign-up">
    <fieldset>
      <input type="text" name="credentials[email]" value="email">
      <input type="password" name="credentials[password]" value="password">
      <input type="password" name="credentials[pasword_confirmation]" value="password_confirmation">
      <input type="submit" name="submit" value="Sign up!">
    </fieldset>
  </form>

```

```js
const signUp = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data: data
  })
}
```

```js
const onSignUp = function (event) {
  const data = getFormFields(this)
  event.preventDefault()
  // console.log(data, 'hi')
  api.signUp(data)
    .then(ui.signUpSuccess)
    .catch(ui.signUpFailure)
}

const addHandlers = () => {
  $('#sign-up').on('submit', onSignUp)
}
```

```js
const signUpSuccess = (data) => {
  console.log('Success')
}
const signUpFailure = (data) => {
  console.log('fail')
}
```

**Comment by danman01** [comment]
Could you post the error output from the rails server log (any more additional info than what you posted?)

From what I can tell, your localhost server is refusing the connection...but why?

**Comment by Pouk91** [comment]
I ran the bin/rails server it solved that issue but now i am receiving a 500 error
```
jquery.js:9566 POST http://localhost:4741//sign-up 500 (Internal Server Error)
```

UPDATE: Migrated my db in heroku and started to receive the error again

**Comment by danman01** [comment]
Can you close this issue if it's resolved, and open a new one for a 500 error?

Which error does this refer to? 
>UPDATE: Migrated my db in heroku and started to receive the error again

**Comment by Pouk91** [comment]
Sorry Danny, i turned off my bin/rails server now I'm receiving the 500 internal error again closing the issues.
