### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/full-stack-project#835]
I have an error on my [deployed site](https://awoodrum87.github.io/angies-other-list-client/index.html) that I cannot resolve. 

The error in my console when I attempt any authorization CRUD is: 
```
index.html:1 XMLHttpRequest cannot load https://angies-other-list.herokuapp.com//sign-up/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://awoodrum87.github.io' is therefore not allowed access.
```
I have done some Googling and found t[his stackoverflow](http://stackoverflow.com/questions/20035101/no-access-control-allow-origin-header-is-present-on-the-requested-resource) which led to [this article](https://www.html5rocks.com/en/tutorials/cors/), but I still am unclear about what this error is, so I don't know how to start resolving it.

**Comment by jordanallain** [comment]
do you have the CLIENT_ORIGIN set in your heroku app?

**Comment by awoodrum87** [comment]
yep! I did it when I set up my heroku app, and just did it again:
```
heroku config:set CLIENT_ORIGIN=https://awoodrum87.github.io/angies-other-list-client/index.html
Setting CLIENT_ORIGIN and restarting ⬢ angies-other-list... done, v11
CLIENT_ORIGIN: https://awoodrum87.github.io/angies-other-list-client/index.html
~/wdi/projects/full-stack-api (master)
$ heroku restart
Restarting dynos on ⬢ angies-other-list... done
~/wdi/projects/full-stack-api (master)
$ heroku open

```

**Comment by jordanallain** [comment]
the CLIENT_ORIGIN should end at `io`

**Comment by awoodrum87** [comment]
it works!!!!
THANK YOU SO MUCH YOU ARE THE BEST
