### ISSUE TITLE
Issue with linking form fields to patch request

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/full-stack-project#836]
This is sort of links to a problem I was having earlier, but was able to resolve:

https://github.com/ga-wdi-boston/gh-pages-deployment-guide/issues/18 (I opened the issue in the wrong repo -_-)

Now, I am having a similar problem where patch requests to my server throw the following error:

```
ActionController::ParameterMissing (param is missing or the value is empty: movie):
app/controllers/movies_controller.rb:53:in movie_params'
app/controllers/movies_controller.rb:32:in update'
```

my Ajax request:
```js
const update = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/movies/' + data.id, // now its a 400 error
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```

and my event which calls the AJAX request
```js
const onUpdate = function (event) {
  event.preventDefault()
  let data = getFormFields(event.target)
  data = data.movie
  api.update(data)
    .then(ui.updateSuccess)
    .catch(ui.updateFailure)
}
```

and the form which calls the event
```html
<form class="update">
      <fieldset>
         <input type="integer" name="movie[id]" placeholder="Select ID">
         <input type="text" name="movie[title]" placeholder="Change Title">
         <input type="submit" name="submit" value="Update Movie">
       </fieldset>
    </form>
```

I was able to resolve the problem with POST by sending it a movie object with a title string taken from the form. I attempted to emulate this, but I have definitely messed up in my attempt to pass two different things to the API.

**Comment by jordanallain** [comment]
have you console.logged or debugger'd your function to see what that data object is?

**Comment by d00medman** [comment]
yeah, I placed console logs at the following points:

`let data = getFormFields(event.target)
  console.log(data)
  data = data.movie
  console.log(data)
  console.log(data.id)`

When I input ID 4 (a valid ID) and an updated title of "gabagool", the following are printed

`Object {movie: Object, submit: "Update Movie"}` (data)
`Object {id: "4", title: "gabagool"}` (data.movie)
`4` (data.id)

**Comment by jordanallain** [comment]
so be mindful of how the data needs to be structured in the request. it has to be an object with the key movie, that points to another object.

**Comment by d00medman** [comment]
I'm not entirely sure I follow. It looks like my data variable is an object with a kay movie which points to another object. Is this what it is supposed to be or what it is not supposed to be?

**Comment by danman01** [comment]
Take a look, using `binding.pry`, in your rails controller at the location of this error to further explore what params you are receiving from your ajax call:
```
ActionController::ParameterMissing (param is missing or the value is empty: movie): app/controllers/movies_controller.rb:53:in movie_params' app/controllers/movies_controller.rb:32:in update'
```

**Comment by MicFin** [comment]
What does the `data` object look like after this?
```js
let data = getFormFields(event.target)
data = data.movie
console.log("data after calling .movie", data) // what is this?
```
Does it have a hash key called `movie`?  Because it should.  
What does the `MoviesController` require in `set_movie`?  
Does it require a `movie` key?
The error `param is missing or the value is empty: movie` makes me think maybe it expects a `movie` key in the `data` that you send to the API but your current `data` object doesn't have it.

**Comment by d00medman** [comment]
After calling data.movie, I get
`Object {id: "4", title: "gabagool"}` 
So basically, since data is being set to data.movie, it renders my controller incapable of accepting the data, hence the 400 error.

**Comment by d00medman** [comment]
However, when I comment out the line 

`data = data.movie`

a 404 error is thrown instead.

I think I may need to pass in two arguments to my api parameter, one which allows it to properly build the URL and one which is passed through as data.

**Comment by d00medman** [comment]
This worked. Final code was the following:

my event:
`const onUpdate = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  const targ = data.movie
  api.update(data, targ)
    .then(ui.updateSuccess)
    .catch(ui.updateFailure)
}`

my API call:
`const update = (data, targ) => {
  return $.ajax({
    url: config.apiOrigin + '/movies/' + targ.id, // now its a 400 error
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}'

There is the very real prospect that all of this becomes moot when I refactor my update function in my handlebars build.
