### ISSUE TITLE
1 on 1 Request - Help w/ db:migrate Message

### ISSUE THREAD

**Issue by kellye2010** [ga-wdi-boston/full-stack-project#837]
I am receiving a message after running 'bin/rails db:migrate' that I am not sure how to read. WHere should I look to check for why my migrate is aborting and not running?
![screen shot 2017-05-05 at 1 19 53 pm](https://cloud.githubusercontent.com/assets/4691419/25756790/0ca10e2a-3196-11e7-83bc-3503246a87aa.png)

**Comment by tvcrawley** [comment]
Have you read the error message carefully? It maybe giving you a hint on how to resolve this problem.

**Comment by kellye2010** [comment]
Added 's' to the end of references in my migration files where necessary.
Thanks!
