### ISSUE TITLE
How to render returned information on the page

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/full-stack-project#838]
So I am attempting to have my index function render the raw JSON objects on the page. Thus far, on index success, my code looks like this

`const indexSuccess = (response) => {
  console.log(response)
  const movies = response.movies
  console.log(movies)
  $('.display').text(movies)
}`

However, in practice, this gives me the following:

[object Object],[object Object],[object Object],[object Object],[object Object]

I had this problem in my tic tac toe game before deciding to eschew this kind of functionality, but it is now a pretty vital stepping stone for properly displaying my returned data. Any advice on how to parse something useful from the response variable?

**Comment by jordanallain** [comment]
handlebars

**Comment by danman01** [comment]
Try googling for "javascript [object Object]" and variations on that, and see what you can find out.

**Comment by d00medman** [comment]
Hmm, sounds like this sort of thing is better off just done with handlebars, rather than some unwieldy in-between step. Will deal with this once I begin handlebar implementation.
