### ISSUE TITLE
422 Unprocessable Entity

### ISSUE THREAD

**Issue by Anddrew914** [ga-wdi-boston/full-stack-project#839]
EDIT. For me, the solution was to make my controller set to OpenReadController. You'll need to make your controller look like the example controller provided. Hope this helps some future students!

I'm getting this error when trying to post a new instrument to my new table. I've run a nuke on the DB so it's now empty, but still I can't get the webpage forms to POST items. 
```
Started POST "/instruments/" for 127.0.0.1 at 2017-05-05 14:11:42 -0400
Processing by InstrumentsController#create as */*
  Parameters: {"instrument"=>{"instrument_type"=>"guarneri", "price"=>"70.00"}}
   (0.2ms)  BEGIN
   (0.1ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.1ms)
Completed 422 Unprocessable Entity in 22ms (Views: 0.8ms | ActiveRecord: 4.7ms)
```
compared to my working curl request

```
Parameters: {"instrument"=>{"instrument_type"=>"Stradivarius", "price"=>"60.00"}}
   (0.1ms)  BEGIN
  SQL (34.1ms)  INSERT INTO "instruments" ("instrument_type", "price", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["instrument_type", "Stradivarius"], ["price", #<BigDecimal:7fa305b934a8,'0.6E2',9(18)>], ["created_at", 2017-05-05 12:56:33 UTC], ["updated_at", 2017-05-05 12:56:33 UTC]]
```

**Comment by danman01** [comment]
Can you place a `binding.pry` in the code before `create` or `save` is called (these methods are triggering the database rollback), and report back if that object is `valid?` and if there are active record `errors` on that object?

**Comment by Anddrew914** [comment]
=> #<Instrument:0x007fccb0a51cc8
 id: nil,
 instrument_type: "guarneri",
 maker: nil,
 price: #<BigDecimal:7fccb0a094f0,'0.7E2',9(18)>,
 details: nil,
 created_at: nil,
 updated_at: nil>
[5] pry(#<InstrumentsController>)> 

I'm guessing BigDecimal is the problem here?

**Comment by jordanallain** [comment]
`id: nil` seems like an issue

**Comment by tvcrawley** [comment]
What does the form you're submitting this data with look like?

**Comment by Anddrew914** [comment]
```
  <form id="add-instrument">
  <fieldset>
    <legend>Create instrument</legend>
    <input name="instrument[instrument_type]" type="text" value="Instrument type" onFocus="this.select()">
    <input name="instrument[price]" type="number" step="any" placeholder="Price" onFocus="this.select()">
    <!-- <input name="maker" type="text" value="Maker" onFocus="this.select()"> -->
    <!-- <br>
    <textarea name="details "style="margin: 10px 0;"rows="4" cols="50" onFocus="this.select()">
      Instrument details
    </textarea>
    <br> -->
    <input type="submit" class="btn btn-default" value="Submit">
  </fieldset>
</form>
```

**Comment by danman01** [comment]
Within your `binding.pry` can you call `valid?` on the object, and then call `errors` to get the active record errors? If it's not yet saved, it won't have an ID.

**Comment by Anddrew914** [comment]
```
[4] pry(#<InstrumentsController>)> violin=Instrument.new(instrument_params)
=> #<Instrument:0x007ffa762a1048
 id: nil,
 instrument_type: "guarneri",
 maker: nil,
 price: 70.0,
 created_at: nil,
 updated_at: nil>
[5] pry(#<InstrumentsController>)> violin.valid?
=> false
[6] pry(#<InstrumentsController>)> violin.errors
=> #<ActiveModel::Errors:0x007ffa76c78918
 @base=
  #<Instrument:0x007ffa762a1048
   id: nil,
   instrument_type: "guarneri",
   maker: nil,
   price: 70.0,
   created_at: nil,
   updated_at: nil>,
 @details={:user=>[{:error=>:blank}]},
 @messages={:user=>["must exist"]}>
```

**Comment by MicFin** [comment]
Items to check for consistent attribute names and validation rules.
1.  Schema table and columns
2.  Model validation rules
3.  Controller `set_resource` method that has `.require` and `permit`
4.  Data being sent by CURL request
5.  Data being sent by AJAX
Feel free to post them all if you dont see any discrepancies on your own.

**Comment by Anddrew914** [comment]
I can create the object in pry but not save it for some reason. Can I get a one on one before the day is up? I've been trying to do this one thing since like 10 and don't want to have to go into the whole weekend with nothing to go on.

**Comment by tvcrawley** [comment]
Have you identified which file(s) may be the culprit? If not, like Mike said, feel free to post all files listed above.

**Comment by MicFin** [comment]
If you share the:
>1.  Schema
>2.  Model
>3.  Controller
>4.  Ajax/Curl that is making the request

I bet we can troubleshoot it with you.

**Comment by Anddrew914** [comment]
Controller
```rb

  def instrument_params
      params.require(:instrument).permit(:instrument_type, :price,)
    end
```

model
```rb
class Instrument < ApplicationRecord
  belongs_to :user
end
```
serializer
```rb
class InstrumentSerializer < ActiveModel::Serializer
  attributes :id, :instrument_type, :price,
end
```
migrate
```rb
class CreateInstruments < ActiveRecord::Migration[5.0]
  def change
    create_table :instruments do |t|
      t.string :instrument_type, null: false
      t.float :price

      t.timestamps
    end
  end
end
```
schema
```rb
  create_table "instruments", force: :cascade do |t|
    t.string   "instrument_type", null: false
    t.float    "price"
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
  end
```
Request log
```
Started POST "/instruments/" for 127.0.0.1 at 2017-05-05 16:08:48 -0400
Processing by InstrumentsController#create as */*
  Parameters: {"instrument"=>{"instrument_type"=>"violin", "price"=>"34"}}
   (0.1ms)  BEGIN
   (0.2ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.09ms)
Completed 422 Unprocessable Entity in 32ms (Views: 4.1ms | ActiveRecord: 5.4ms)
```

**Comment by tvcrawley** [comment]
Can you post the entire `InstrumentsController`?

**Comment by Anddrew914** [comment]
```rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :update, :destroy]

  # GET /instruments
  def index
    @instruments = Instrument.all

    render json: @instruments
  end

  # GET /instruments/1
  def show
    render json: @instrument
  end

  # POST /instruments
  def create
    @instrument = Instrument.new(instrument_params)
    if @instrument.save
      render json: @instrument, status: :created, location: @instrument
    else
      render json: @instrument.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /instruments/1
  def update
    if @instrument.update(instrument_params)
      render json: @instrument
    else
      render json: @instrument.errors, status: :unprocessable_entity
    end
  end

  # DELETE /instruments/1
  def destroy
    @instrument.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def instrument_params
      params.require(:instrument).permit(:instrument_type, :price,)
    end
end
```

**Comment by MicFin** [comment]
`params.require(:instrument).permit(:instrument_type, :price,)`
 I wonder if that extra comma after `:price` is making rails think it should expect a 3rd attribute?

**Comment by MicFin** [comment]
The next step to debug, is to `binding.pry` and test your data
```rb
def create
    binding.pry # what is params?  what is instrument_params?
    @instrument = Instrument.new(instrument_params)
    binding.pry # what is @instrument?  Can you do @instrument.save, what happens?
    if @instrument.save
      render json: @instrument, status: :created, location: @instrument
    else
      render json: @instrument.errors, status: :unprocessable_entity
    end
  end
```

**Comment by Anddrew914** [comment]
I've done that before and will do it again  but when I did it last time I was able to create a new instrument with the correct name and price by doing violin=Instrument.new(instrument_params)
then when I tried to save it I got "false" as a reponse

**Comment by MicFin** [comment]
It sounds like you `params` that you are sending over do not match what your database or model validations expect.  This should show you:

instruments_controller.rb
```rb
def create
    binding.pry # what is params?  what is instrument_params?
```

**Comment by Anddrew914** [comment]
Where do I put that?

**Comment by danman01** [comment]
@Anddrew914 you output the result of `.errors` a while back...what was the validation error that came back? What are you missing when you create an instrument? What's a different way to create something that includes that missing attribute?

Read the output of `.errors` line for line and make note of anything that sounds like a validation error
