### ISSUE TITLE
Having trouble connecting two data sets when POSTing

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/full-stack-project#84]
I can create a Beer and a Location but for some reason they are not connecting, thus not making a new Tap (location_id + beer_id).  I understand how to do that in Rails C, but the implementation into code has me puzzled.

I don't know how to turn

```
loca= Location.first
loca.beers.create!(name:"". brewery:"", style:"")
```

into a function.

This is my function to add a beer 

```
$('#add-beer').on('submit', function(e) {
      e.preventDefault();
      var token = $('.token').val();
      var new_beer = wrap('beer', form2object(this));
      on_tap_api.new_beer(token, new_beer, function(err, beerData) {
        if(err) {
          // do something with the error
          return;
        } else{
          console.log(beerData);
        }
      });
    });
```

and this is my AJAX call

```
new_beer: function (token, new_beer, callback) {
    this.ajax({
      method: 'POST',
      url: this.url + '/beers',
      headers: {
        Authorization: 'Token token=' + token
      },
      contentType: 'application/json; charset=utf-8',
      data: JSON.stringify(new_beer),
      dataType: 'json'

    }, callback);
  },
```

**Comment by GA-MEB** [comment]
Have you tested the API with Postman / `curl`? Can you create new Taps from there? It's important to confirm that this isn't a back-end issue.

**Comment by jcmeyer10** [comment]
Started POST "/taps" for ::1 at 2015-11-12 15:40:18 -0500
Processing by TapsController#create as _/_
  Parameters: {"tap"=>{"location_id"=>"1"}}
  User Load (0.2ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "cf686e40f6eb4e2a98c720a4ef257bc3"]]
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.2ms)

NoMethodError (undefined method `save' for nil:NilClass):
  app/controllers/taps_controller.rb:19:in`create'

**Comment by gaand** [comment]
Please post the code for the TapsController create action

**Comment by jcmeyer10** [comment]
class TapsController < OpenReadController
before_action :set_beer, only: [:update, :destroy]

  # GET /taps
  def index
    render json: Tap.all
  end

  # GET /taps/1
  def show
    @tap = Tap.find(params[:id])

```
render json: @tap
```

  end

  # POST /taps
  def create
    @beer = Tap.new(tap_params)
    @tap.save

```
if @tap.save
  render json: @tap, status: :created, location: @tap
else
  render json: @tap.errors, status: :unprocessable_entity
end
```

  end

  # PATCH /taps/1
  def update
    if @tap.update(tap_params)
      head :no_content
    else
      render json: @tap.errors, status: :unprocessable_entity
    end
  end

  # DELETE /taps/1
  def destroy
    @tap.destroy

```
head :no_content
```

  end

  def set_tap
    @tap = current_user.location.find(params[:id])
  end

  def tap_params
    params.require(:tap).permit(:location_id, :beer_id)
  end

  private :set_tap, :tap_params
end

**Comment by gaand** [comment]
You're assigning `@beer` as the new tap then trying to save `@tap`

**Comment by jcmeyer10** [comment]
This might be stupid but def create
    @tap = Location.beers.new(tap_params)
    @tap.save

```
if @tap.save
  render json: @tap, status: :created, location: @tap
else
  render json: @tap.errors, status: :unprocessable_entity
end
```

  end

**Comment by gaand** [comment]
If I understand correctly, to create a tap you need a beer and a location.  If you have both of those ids for both of those things it should be straight forward to create a tap with `Tap.create(location_id: lid, beer_id: bid)`.  Are you sending those things in the request from the front end (values to put in for `lid` and `bid`)?

**Comment by jcmeyer10** [comment]
Not in any form.  The forms are put in separately, ie I can create a location independent of beer.  So I have no way of connecting the two as it stands right now.

**Comment by gaand** [comment]
Okay.  So what we need is a way for users to connect new beers to existing locations or new locations to existing beers or existing to existing.

**Comment by gaand** [comment]
Please come to classroom 1.

**Comment by gaand** [comment]
I should have removed myself when I left for the day.
