### ISSUE TITLE
Need Checkpoint

### ISSUE THREAD

**Issue by kellye2010** [ga-wdi-boston/full-stack-project#841]
I am kind of stuck and need to ensure that I am on the right path.

**Comment by danman01** [comment]
Can you elaborate:
1. where do you want to be?
1. what's stopping you from getting there?
1. are you encountering a certain bug or unable to figure out some logic in your app?

**Comment by tvcrawley** [comment]
What have you accomplished on your list for today? Are you stuck on a particular task?

**Comment by kellye2010** [comment]
So far I have generated all of the tables for my database, along with their relations. I feel like there is something I am missing for my routes, but I am not quite sure.  I know they need more actions, but I dont want to get ahead of myself adding them if that's not the step I need to be on yet.

**Comment by kellye2010** [comment]
There is some logic I need help with, but I will put in another issue for that.

**Comment by danman01** [comment]
Are you following your user stories? Which ones have you accomplished, and which user story are you working on currently?

**Comment by tvcrawley** [comment]
There are routes already in your routes file. What is the setup of the routes that look somewhat like the resource(s) you just scaffolded?

**Comment by kellye2010** [comment]
Each resource only contains 'only: [:index, :show]', so I will add the controller actions of my user stories to each resource.

**Comment by kellye2010** [comment]
Completed routes.
Thank you!
