### ISSUE TITLE
DB Relations

### ISSUE THREAD

**Issue by kellye2010** [ga-wdi-boston/full-stack-project#842]
I need some help with my database relation logic. Can someone please provide feedback on my database relations, specifically my playlist_songs to songs relationship.
![screen shot 2017-05-05 at 3 02 43 pm](https://cloud.githubusercontent.com/assets/4691419/25760460/e0acb436-31a4-11e7-8951-05dcd36b8c26.png)

**Comment by danman01** [comment]
That looks great! Are you able to actually create these relationships in your rails app and create the tables in your db with these attributes?

**Comment by tvcrawley** [comment]
I second Danny. This is awesome! I would suggest making Users and Playlists work first before adding Playlist Songs, Songs, & Artists. #BabySteps #IncrementalProgress

**Comment by kellye2010** [comment]
Will work with making just Users and Playlist work first.
Thanks!

**Comment by tvcrawley** [comment]
@kellye2010 Sounds like you're at a good point, can you close this?
