### ISSUE TITLE
Adding columns after migrating

### ISSUE THREAD

**Issue by eliottenos** [ga-wdi-boston/full-stack-project#844]
I have tried to add columns after migrating but have inadvertently added them as their own class it seems.  How do I reverse this and add them correctly?
I ran...
```
rails generate migration add_Zipcode_to_Location Zipcode:integer
```
and then
```
rake db:migrate
```

**Comment by tvcrawley** [comment]
Have you tried googling `rails how to undo migration`?

**Comment by tvcrawley** [comment]
Have you found the command to undo a migrate?

**Comment by eliottenos** [comment]
ran command ```rake db:rollback STEP=2``` to rollback to correct migration
