### ISSUE TITLE
500 Error after deploying - migrating one specific file to Heroku?

### ISSUE THREAD

**Issue by xiangcatherine** [ga-wdi-boston/full-stack-project#846]
My POST request is successful locally, but receiving a 500 Internal Server Error when deployed. 

In my heroku logs, the specific problem is this:

<img width="536" alt="screen shot 2017-05-05 at 4 20 08 pm" src="https://cloud.githubusercontent.com/assets/26419914/25762943/c29a9b34-31ae-11e7-964a-8533345f696f.png">

I think the problem is that I didn't run
```heroku run rake db:migrate```
after creating user references in my babies table (although I did migrate locally).

I tried running that command again now, but it keeps saying that relation 'babies' already exists:
<img width="546" alt="screen shot 2017-05-05 at 4 24 27 pm" src="https://cloud.githubusercontent.com/assets/26419914/25763058/698aa448-31af-11e7-8ae4-ea6072694558.png">
Which is why I think I need to run one specific migration. I tried searching online, and I've tried something like this:
```heroku run rake --trace db:migrate VERSION=20170505180044```
but that returns the same error.

Any guidance you can give? 

Thanks for the help!

**Comment by xiangcatherine** [comment]
I'm guessing I can also do a rollback, but unsure!

**Comment by MicFin** [comment]
What does the migration file look like that adds babies?

**Comment by xiangcatherine** [comment]
I have 3 migration files: 

creating Babies table
```
class CreateBabies < ActiveRecord::Migration[5.0]
  def change
    create_table :babies do |t|
      t.integer :age
      t.string :size

      t.timestamps
    end
  end
end
```
Add user to babies
```
class AddUserToBabies < ActiveRecord::Migration[5.0]
  def change
    add_reference :babies, :user, foreign_key: true
  end
end
```
Remove size from babies
```
class RemoveSizeFromBabies < ActiveRecord::Migration[5.0]
  def change
    remove_column :babies, :size, :string
  end
end

```
I think it's the last two that I didn't migrate to heroku

**Comment by xiangcatherine** [comment]
I dropped my heroku database and re-migrated. All is working now!
