### ISSUE TITLE
 param is missing or the value is empty: recipes... missing file in gems directory?

### ISSUE THREAD

**Issue by rowlandhill** [ga-wdi-boston/full-stack-project#847]
I'm trying to create a new recipe, but I receive this error when I fill my inputs and run my code:

```terminal
Started POST "/recipes/" for 127.0.0.1 at 2017-05-05 16:29:35 -0400
Processing by RecipesController#create as */*
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "c7eff7b8cf6022a6219d773c433e66c0"], ["LIMIT", 1]]

From: /Users/rowlandhill/wdi/projects/list-project/list-project-api/app/controllers/recipes_controller.rb @ line 22 RecipesController#create:

    18: def create
    19:   require 'pry'
    20:   binding.pry
    21:   # @recipe = Recipe.new(recipe_params)
 => 22:   @recipe = current_user.recipes.build(recipe_params)
    23: 
    24:   if @recipe.save
    25:     render json: @recipe, status: :created, location: @recipe
    26:   else
    27:     render json: @recipe.errors, status: :unprocessable_entity
    28:   end
    29: end

[1] pry(#<RecipesController>)> recipe_params
ActionController::ParameterMissing: param is missing or the value is empty: recipes
from /Users/rowlandhill/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.1/lib/action_controller/metal/strong_parameters.rb:310:in `require'
```

Here is my html (I am not passing any ingredients in at this time, just recipe):

```html
<div class="container-fluid">
    <form id="new-recipe">unhides everything below
        <input class="btn btn-default" type="submit" name="submit" value="new recipe">
    </form>
    <form id="recipe-container" class="form-group">
      <div class="form-group">
        <input class="form-control" type="text" name="recipe[name]" id="recipe-name" placeholder="name">
      </div>
    <div class="form-group">
      <input class="form-control" type="text" name="ingredients[quantity]" id="quantity" placeholder="quantity">
    </div>
    <div class="form-group">
      <input class="form-control" type="text" name="ingredients[name]" id="ingredients" placeholder="ingredient">
    </div>
    <button type="submit" class="btn btn-default" id="appendIngredients">+</button>
    <div class="form-group">
      <p>add description</p>
    <textarea class="form-control" name="recipe[description]" rows="7"></textarea>
    </div>
    <div class="form-group">
      <input class="form-control" name="recipe[servings]" type="text" value="" placeholder="servings">
    </div>
    <button type="submit" class="btn btn-default" id="createRecipe">add</button>
  </form>
</div>
```

Here is the code in my recipes_controller:

at the top:

```ruby
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :update, :destroy]
  before_action :validate_user
```

the create method:

```ruby
# POST /recipes
  def create
    require 'pry'
    binding.pry
    # @recipe = Recipe.new(recipe_params)
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      render json: @recipe, status: :created, location: @recipe
    else
      render json: @recipe.errors, status: :unprocessable_entity
    end
  end
```

and this is my code at the bottom:

```ruby
private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = current_user.recipes.find(params[:id])
    end

    def validate_user
      set_current_user
    end

    # Only allow a trusted parameter "white list" through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :servings)
    end
end
```

and this is my script:

```js
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/recipes"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "recipe": {
      "name": "'"${STRING}"'",
      "description": "'"${TEXT}"'",
      "servings": "'"${INTEGER}"'"
    }
  }'
```
I'm not really sure where to go after this.  I looked at other forms we've used, but I haven't found anything that points me in the right direction.   My app knows who the current_user is, but for some reason the params are not being filled.  Could it be something in my front-end not passing the right info through?  I'm not sure where to look :/

(current user)
```terminal
current_user
=> #<User:0x007ffb1639e798
 id: 3,
 email: "lp",
 token: "b65623025a0c35d96809f4c2109275c0",
 password_digest: "$2a$10$iQzuKAYrX1lfOC.MtawSMuDEycMo7RY/9CXwK.Z0OQQqBUKqL.QHO",
 created_at: Thu, 04 May 2017 19:37:12 UTC +00:00,
 updated_at: Fri, 05 May 2017 20:39:07 UTC +00:00>
```

Thanks!

**Comment by rowlandhill** [comment]
I was successfully able to create a recipe running my code through the browser.  I looked at the example schema and saw a user_id, so I ran a migration to add_user_to_recipes, then added the user_id to the recipe_params, ran my code and received the "Completed 201 Created" message.

However, while a recipe was created, the ingredients I entered into the input fields were not added to the ingredients table... Do I need to create a user_id for ingredients as well?  I'm not getting any errors when I run my code, but ingredients are not showing in my database, while the recipe attributes are.

**Comment by MicFin** [comment]
If the relationship is `Recipe has_many Ingredients` and you are trying to send both the `recipe` data and its associated `ingredients` and their data to all get created by the `recipes_controller` then you are creating a Nested Model and will need to:
- set up a nested form
- allow your models to accept nested attributes
- permit your controller to accept nested attributes

This article is a nice tutorial on how to do so.
https://rubyplus.com/articles/3681-Complex-Forms-in-Rails-5

Another option, would be to create just the recipe first and then adding the ingredients after.

**Comment by rowlandhill** [comment]
Thanks, Mike!  I followed the tutorial and am allowing my models to accept nested attributes:

```ruby
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :ingredients, inverse_of: :recipe, dependent: :destroy

  accepts_nested_attributes_for :ingredients
end
```

```ruby
class Ingredient < ApplicationRecord
  belongs_to :recipe, inverse_of: :ingredients, dependent: :destroy
end
```
but I'm a little hazy on what I need to do to allow my controller to accept nested attributes.  Is it something along the lines of:

```ruby
@ingredients = @recipe.ingredients
```

Do I need to do anything to my Ingredients controller?  I'm still getting an error:

```terminal
oMethodError (undefined method `ingredients' for #<User:0x007fbda45ec310>
Did you mean?  increment):
  
app/controllers/ingredients_controller.rb:21:in `create'
```
In order to set up a nested form, does that mean I need to re-write my index.html file in ruby?  That's the sense I'm getting from the tutorial you sent over - I've been doing a little research, and it doesn't look like nested forms are possible with HTML.

**Comment by MicFin** [comment]
Look at Step 13 in the tutorial.  The `recipe_controller.rb` needs to allow `ingredients_attributes` and specify its attributes in the `permit`.  There's also a video https://rubyplus.com/episodes/11-Movie-Review-Rails-5-App-Part-3.

**Comment by MicFin** [comment]
Your error says, `app/controllers/ingredients_controller.rb:21:in 'create'`.
Why are you making a request to the `ingredients_controller`?  You should only need to make a request to the `recipes_controller` action `create` if you are doing it with Nested Models.

**Comment by rowlandhill** [comment]
I have a `createIngredient` AJAX call, so that's probably why the `ingredients_controller` is being called.  Since I'm creating a Nested Model, is `createIngredient` no longer necessary because it's nested in `Recipe`?

```js
const createIngredient = (data) => {
  console.log('createIngredient data is', data)
  return $.ajax({
    url: config.apiOrigin + '/ingredients/',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```

**Comment by MicFin** [comment]
Yes, if set up correctly that would be the goal.  Your `recipes_controller` action for `create` should be able to create both the recipe and it's ingredients.

However, I think the simpler route is to just handle creating a recipe and then creating it's ingredients after.  Please keep in mind that Nested Models will be more challenging of a path.  

If you use AJAX promises correctly then you should still be able to have the user experience of making them both at the first time but have the `POST /recipes` AJAX call go first and then the `POST /ingredients` AJAX calls should only fire after the `POST /recipes` AJAX call finishes so you can send it's ID with it.

**Comment by rowlandhill** [comment]
Understood.  I'll create the recipe and then have the ingredients go after.  It sounds like I can just have the `createIngredient` function fire on `createRecipeSuccess` or something like that.  

Thank you for your help, Mike!  Do you mind if I keep this open until after I try this out?

**Comment by rowlandhill** [comment]
Well, it wasn't as simple as just having the `createIngredient` function fire on `createRecipeSuccess` haha

When I did that, `createIngredient` never fired at all.  

It's passing the Ingredient data into the Recipe, though, because in the Google chrome console, it looks like it's creating an object with BOTH recipe and ingredient inside:

```console
Object {recipe: Object, ingredients: Object, submit: ""}
ingredients: Object
name: "kopkopkop"
quantity: "12"
__proto__: Object
recipe: Object
description: "kopkopkop"
name: "jiojio"
servings: "2"
```

I have a feeling that the reason it's bundling them together like that is because I have everything in one form-group in my index.html file, but when I separate them, the Ingredient data is never passed through (my html):

```html
<form id="createRecipe" class="form-group">
      <div class="form-group">
        <input class="form-control" type="text" name="recipe[name]" id="recipe-name" placeholder="name">
      </div>
    <div class="form-group">
      <input class="form-control" type="text" name="ingredient[quantity]" id="quantity" placeholder="quantity">
    </div>
    <div class="form-group">
      <input class="form-control" type="text" name="ingredient[name]" id="ingredients" placeholder="ingredient">
    </div>
    <button type="submit" class="btn btn-default" id="appendIngredients">+</button>
    <div class="form-group">
      <p>add description</p>
    <textarea class="form-control" name="recipe[description]" rows="7"></textarea>
    </div>
    <div class="form-group">
      <input class="form-control" name="recipe[servings]" type="text" value="" placeholder="servings">
    </div>
    <button type="submit" class="btn btn-default" name="submit">add</button>
    </form>
    <form id="new-recipe">unhides everything below
        <input class="btn btn-default" type="submit" name="submit" value="new recipe">
    </form>
```

I'm not sure how to separate ingredients and recipes so they can pass through correctly, without forcing the user to create the recipe and then add ingredients afterwards - not an ideal user experience.

When I added it after `onCreateRecipe` in `addHandlers`, it runs `createIngredient` first, even though it's listed further down the page than `createRecipe` everywhere in my code:

```js
$('#createRecipe').on('submit', onCreateRecipe, onCreateIngredient)
```

Here's the error that shows `createIngredient` running first:

```terminal
Started POST "/ingredients/" for 127.0.0.1 at 2017-05-06 23:42:08 -0400
Processing by IngredientsController#create as */*
  Parameters: {"recipe"=>{"name"=>"huihui", "description"=>"huihui", "servings"=>"2"}, "ingredients"=>{"quantity"=>"12", "name"=>"gyugyu"}, "submit"=>""}
  User Load (1.5ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "34a1a43ee9dae45c9e0e4203c2910745"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 32ms (ActiveRecord: 1.5ms)


  
NoMethodError (undefined method `ingredients' for #<User:0x007ff85c85f078>
Did you mean?  increment):
  
app/controllers/ingredients_controller.rb:21:in `create'
```

Here is my code for create in my `ingredients_controller` (line 21 is `@ingredient = current_user.ingredients.build(ingredient_params)`:

```ruby
# POST /ingredients
  def create
    # require 'pry'
    # binding.pry
    @ingredient = current_user.ingredients.build(ingredient_params)

    if @ingredient.save
      render json: @ingredient, status: :created, location: @ingredient
    else
      render json: @ingredient.errors, status: :unprocessable_entity
    end
  end
```

and at the bottom:

```ruby
private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = current_user.ingredients.find(params[:id])
    end

    def validate_user
      set_current_user
    end

    # Only allow a trusted parameter "white list" through.
    def ingredient_params
      params.require(:ingredient).permit(:quantity, :name, :id, :recipe_id)
    end
end
```

I'm kind of at a loss as to what I should be doing in order to create both of these at the same time.  Do both of them need `current_user`?  Should they each have their own form-class in my HTML? Or can both recipe and ingredient be nested within the same form-class?  I'm not sure how to make sure the correct data is being pulled for the right AJAX call when doing them both at the same time.

**Comment by rowlandhill** [comment]
Closing issue for now.  Will continue working on just the Recipes table.
