### ISSUE TITLE
Having trouble getting an id number to pass through an AJAX request

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/full-stack-project#849]
I have been working on my handlebars templates. The goal of these templates is to have each listed item drawn from the API be connected to a delete button, which removes the item from both the list and the database. However, I cannot seem to get a valid id out of my submit buttons, causing me constant 404 errors.

I have jury rigged a solution where you input which id you want to delete underneath that item's id in the list. My goal to strip this down to a single button which passes the correct id through the AJAX request. How would I go about finding said ID?

the destroy method in its current state
```js
const destroy = (event) => {
  event.preventDefault()
  let data = getFormFields(event.target)
  data = data.movie
  api.destroy(data.id)
    .then(destroySuccess(event))
    .catch(destroyFailure)
}
```

The handlebars template which creates the delete buttons
```handlebars
{{#each movies as |movie|}}
  <ul data-id="{{movie.id}}">
  <h5>
    {{movie.title}}
  </h5>
  <h6>
    id: {{movie.id}}
  </h6>
  <form class="destroy">
    <fieldset>
      <input type="integer" name="movie[id]" placeholder="Delete movie by ID">
      <input type="submit" name="submit" value="Submit ID">
    </fieldset>
  </form>
  </ul>
{{/each}}
```

**Comment by aprilsourz** [comment]
You can get the the data-is out of the ul element and pass it to api destroy. You can do this with the .parents and .attr jquery methods.

**Comment by aprilsourz** [comment]
I think the code for that might be in the solution branch for the handlebars training.

**Comment by jordanallain** [comment]
You could also store the ID on the button itself as a data attribute. Then you don't need to traverse the DOM to get it.

**Comment by d00medman** [comment]
This solved the problem. I placed a data id with the value `data-id="{{movie.id}}"` in the header of my form, then used `const targ = $(event.target).attr('data-id')` to pull the data-id, then pass it through the delete function.
