### ISSUE TITLE
I'd like 20 minutes to hash out a few problems

### ISSUE THREAD

**Issue by eshimel** [ga-wdi-boston/full-stack-project#85]
Backend:
I'm still not sure how to implement the counting logic on the backend, I've looked it into serializers and changing the controllers, but want to make sure I understand how they can work before I go anymore.

Frontend:
I'm trying have data update whenever the login/registration is loaded, thought that onload was the way to go, but don't think so now.  Then I though .ajaxComplete, but its pre ajax completing.

I am also having a curl issue,

**Comment by GA-MEB** [comment]
Let's chat for a couple mins and tease this into separate issues.

**Comment by eshimel** [comment]
got login and registration up and running, adjusted controllers, still would like to chat
