### ISSUE TITLE
Heroku first login attempt,  No Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by Anddrew914** [ga-wdi-boston/full-stack-project#850]
When I try to login on my deployed site this is what I get. 

XMLHttpRequest cannot load https://ga-wdi-boston.herokuapp.com/sign-in. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://anddrew914.github.io' is therefore not allowed access. The response had HTTP status code 401.

I get this same issue when trying to sign up. 

My heroku config in case it helps
$ heroku config
=== luthier-api Config Vars
CLIENT_ORIGIN:            https://anddrew914.github.io
DATABASE_URL:             postgres://bqjzkyhcksnigh:4a436963cdfe03ce67776d70ccfcb4ae61c5a41fb07acf658d6b8bd406d2b32c@ec2-23-23-222-147.compute-1.amazonaws.com:5432/d6mgtbji1g31p5
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_LOG_TO_STDOUT:      enabled
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:          9523dbac5ed8d4e03a39ae3dcede6415b1cf9b124e15ca498e1fa79158c4d3eb96f88e7cb3009f218458ccf4fb9c92d8549dc047efed28f17e24aa59fb0fee31
SECRET_TOKEN:             49189a1f0c416c535e4794e9a5dec2e0d5fcd32006f074ee680bf50071513721008fb25976c395574d26380fd687bdcb0365d37ca633e6e777abd8a6bd313195

These keys and tokens are not the same as my local. Is that an issue?

**Comment by MicFin** [comment]
Take a look at these and see if they help:
https://github.com/ga-wdi-boston/full-stack-project/issues/835
https://github.com/ga-wdi-boston/full-stack-project/issues/518

**Comment by Anddrew914** [comment]
Woo! My host in config.js in my front end repo wasn't set properly as in link 518. Also as a bonus for future students remember to add commit and redeploy or your changes won't show any effect. I also had to remember to migrate afterwards to actually set up the tables. The command heroku logs, run from the project terminal, was useful for showing error messages similar to the rails server we run locally.
