### ISSUE TITLE
Need to remove empty strings from getformfields

### ISSUE THREAD

**Issue by joebelmonte** [ga-wdi-boston/full-stack-project#851]
Hi, I'm working on a db that tracks movies, and each movie has multiple attributes (title, year released, mpaa rating, length, etc.).

For the patch, I'm leveraging the getformfields function with 1 field for each attribute.  The user can fill out 1 or more fields and then click "update."  

The fields that the user fills out are being successfully used to update the movie's record.  Unfortunately, any field that the user doesn't fill out is being sent to the API as a blank string and therefore wiping out the pre-existing data.  Obviously, this is not desirable behavior.  I want it to patch only fields that the user actually updated.

My thinking is to try to modify the getformfields function to exclude these empty strings.  From looking at that file, it looks like that function returns a variable called "target" which is an object with the keys/values of the form fields.  I've been trying to delete the empty key/value pairs before they are sent to the api.  I've tried several variations on the code below, which I've put at the bottom of the getformfields file:

```js
  const removeEmpty = (obj) => {
    Object.keys(obj).forEach((k) => (!obj[k] && obj[k] === '') && delete obj[k])
    return obj
  }

  removeEmpty(target)
```

This works fine when I try an example in repl.it but not in my app unfortunately.  When I run the above code, I get a 400 error (bad request).  When I examine the console logs, it doesn't even look like the function did anything (which begs a further question of why it failed...)

I've spent about an hour on this running various permutations with no luck - either it fails entirely or the patch is successful but with the original behavior of wiping out data for fields that weren't filled out.

 Does it look like I'm on the right track?  Any suggestions would be appreciated.

Thanks,

Joe

Thanks,

Joe

**Comment by MicFin** [comment]
Look into: 
`update_attributes` 
- https://cbabhusal.wordpress.com/2014/10/08/different-between-update-update_columns-update_column-update_attributes-assign_attributes/

`update_attribute` 
- https://stackoverflow.com/questions/14824939/updating-a-single-attribute-in-rails
- https://stackoverflow.com/questions/6089903/rails-is-there-a-way-to-update-a-single-attribute

Also see,
https://stackoverflow.com/questions/1531047/update-attributes-unless-blank

Another strategy would be to have the form field default to the value in the database so if they don't change it, it will remain the same and not submit an empty string.

**Comment by joebelmonte** [comment]
I think I've got it working - thanks, Mike!!

For future reference, the solution that I've implemented can be found in the final link above.  

Specifically, I've updated my movie_params in the movie controller with the .reject below:

```rb
    def movie_params
      params.require(:movie).permit(:name, :year_released, :mpaa_rating, :user_rating, :length, :ownership_status, :ownership_type, :last_viewing, :times_watched, :id).reject { |_, v| v.blank? }
    end
end
```

Doesn't appear to have broken anything else so far.  Fingers crossed...
