### ISSUE TITLE
[jQuery] - Click event will not work with function required from another JS file.

### ISSUE THREAD

**Issue by aprilsourz** [ga-wdi-boston/full-stack-project#854]
Here is the code that attaches the click handlers. In handler-helper.js, this is the entire file.

```js
const {
  onItemDestroy,
  openEditForm
} = require('./events.js')

const createItemHandlers = () => {
  $('.item-destroy').off('click', onItemDestroy)
  $('.item-edit').off('click', openEditForm)
  $('.item-destroy').on('click', onItemDestroy)
  $('.item-edit').on('click', openEditForm)
}

module.exports = {
  createItemHandlers
}
```

These are the functions being attached, which are in events.js

```js
const onItemDestroy = (event) => {
  event.preventDefault()
  const destroyId = getIdFromElement(event)

  api.itemDestroy(destroyId)
    .then(ui.itemDestroySuccess)
    .catch(ui.itemDestroyFailure)
}
```

```js
const openEditForm = (event) => {
  editFormSwap(event)
  editItemHandlers()
}
```
This is where createItemHandlers is being called.

```js
const itemIndexSuccess = (data) => {
  console.log(data.items)
  const allItemsHtml = showAllItems({ items: data.items })
  $('#current-list').html(allItemsHtml)
  createItemHandlers()
}
```

I have used console logs to eliminate some of the possibilities. createItemHandlers is definitely being invoked. When I put a function in the same file as createItemHandlers, the click event will trigger it.

```js
const onItemDestroy = () => { console.log('foo') }
const openEditForm = () => { console.log('bar') }
const createItemHandlers = () => {
  $('.item-destroy').off('click', onItemDestroy)
  $('.item-edit').off('click', openEditForm)
  $('.item-destroy').on('click', onItemDestroy)
  $('.item-edit').on('click', openEditForm)
}

module.exports = {
  createItemHandlers
}
```

I think the problem is that the .on method won't attach a function required from another file. I ran into this issue while refactoring. The only solution I've found is to put everything in the same file. That got really messy. Is there a way to attach a function required from another file to a click event?

**Comment by MicFin** [comment]
This looks odd to me
```js
const {
  onItemDestroy,
  openEditForm
} = require('./events.js')
```
Will you describe what that is doing?

**Comment by aprilsourz** [comment]
Yeah totally. Thats slightly different syntax for require which lets me use onItemDestroy and openEditForm without putting events. before it. 

```js
const {
  onItemDestroy,
  openEditForm
} = require('./events.js')

openEditForm()
onItemDestroy()
```
is the same as

```js
const events = require('./events.js')

events.onItemDestroy()
events.openEditForm()
```

**Comment by aprilsourz** [comment]
Also I'm requiring events.js in handler-helper.js and handler.helper.js in events.js. Does a cause a circular dependency which would break it?

**Comment by aprilsourz** [comment]
I haven't found a solution to this yet. I still have to keep the .on, and the function its binding to the element in the same file. I restructured the content of my files in a different way which is fairly modular. I'm going to close the issue, it doesn't seem worth investigating further.

Thanks.
