### ISSUE TITLE
Testing app behavior that depends on current time

### ISSUE THREAD

**Issue by xiangcatherine** [ga-wdi-boston/full-stack-project#856]
My app is a pregnancy tracker, and I have it so that when the user next signs in, the age of the baby is updated based on a calculation (using the created_at value) in the Baby model, like so:

```ruby
class Baby < ApplicationRecord
  belongs_to :user

  validates :age, presence: true

  def current_age
    created_date = created_at.to_date
    current_date = Date.today

    days = (current_date - created_date).round
    weeks = (days / 7.0).round

    age + weeks
  end
end
```

I think it's functioning, but is there a good way to test this? I tried changing the date of my computer -- but that's not working (I think because Rails has it's own date/ time system?).

Thank you!

**Comment by MicFin** [comment]
I would test it by going into `bin/rails console` and creating a new Baby then trying to use the method.  It would probably look similar to:
```rb
@baby_mike = Baby.new(31) # pass in whatever else is needed to create a baby
@baby_mike.current_age # does it work?
```

However, I do not think it is ideal to store `age` as a column in the database.  It is a more common pattern to store `birth_date`.  There is a datatype called `Date` that you should probably be saving their birth date as.  

Here is an example of someone else needing to change their DB column to `date`. 
https://stackoverflow.com/questions/2799774/rails-migration-for-change-column

Here is an example of someone else writing a method to change their `date` to an `age`.
https://stackoverflow.com/questions/819263/get-persons-age-in-ruby
And another...https://stackoverflow.com/questions/35803160/ruby-age-method-using-date-of-birth-including-months ;)

**Comment by xiangcatherine** [comment]
Thanks Mike, will look into this! 

Although my concern is that since the user is a pregnant mother, she might start using the app at any time (e.g. week 24). So to me it doesn't fully make sense to use birth_date?  Will think about it more.
