### ISSUE TITLE
Guidance on altering a table using db:migrate

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/full-stack-project#857]
I have to alter a table to have NOT NULL for it's 3 fields. I already have two earlier DB migrate scripts that created the table and then added a FK constraint. The code for both of these 2 scripts is below.
```
class CreateChores < ActiveRecord::Migration[5.0]
  def change
    create_table :chores do |t|
      t.string :task
      t.integer :priority
      t.date :due_on

      t.timestamps
    end
  end
end
```

```
class AddUserToChores < ActiveRecord::Migration[5.0]
  def change
    add_reference :chores, :user, index: true, foreign_key: true
  end
end
```
What I am unclear of now is how to do a simple table alter using Active Record? Can I duplicate the first script and give it a unique name and just add in the ``` null: false ``` value as shown below? 

If not, I don't understand how to do a TABLE ALTER command as I've only created a table in db:migrate to date.

This is what I want the new table create to look like. But unsure if I create a second create table script or if there is some way to do an alter table migration script. 

```
class CreateChores < ActiveRecord::Migration[5.0]
  def change
    create_table :chores do |t|
      t.string :task, null: false
      t.integer :priority, null: false
      t.date :due_on, null: false

      t.timestamps
    end
  end
end
```

**Comment by prankmode** [comment]
i just did this - basically, first create an empty migration by doing something like 
```rails generate migration <some name like add-null-blahblahblah>```
and then edit the migration file and use the 
```change_column_null```

google all that to check all the syntax, etc

**Comment by glasneed** [comment]
Thank you for this input! I'll definitely google your suggestion above and check out that ```change_column_null``` field.

**Comment by glasneed** [comment]
Closing this issue after discussing approaches with Danny. In the end, I took the option of using "presence" in the routes.rb file which required no database migration.

 http://guides.rubyonrails.org/active_record_validations.html#presence
