### ISSUE TITLE
TDD testing and authentication

### ISSUE THREAD

**Issue by pjliddy** [ga-wdi-boston/full-stack-project#858]
If we are going to implement automated testing for TDD on Rails controllers based on the ProtectedController class, is it possible to do with the tools we have already been exposed to in class? 

I've been researching it for several hours and it looks like most solutions use some combination of Factory Girl and/or Devise to automate authentication for any tests on our custom tables. It would be great to get some guidance on what kinds of things to look for if we've got to research this from scratch.

**Comment by MicFin** [comment]
Devise is a Rails Gem that sets up authentication and registration for you.  It builds the User model, Controllers, Routes, etc etc.  You dont need that.

Factory Girl IS USEFUL.   But you dont need it.  However, I would recommend utilizing if it seems within the scope of what you can do within the project time.

https://robots.thoughtbot.com/how-we-test-rails-applications
https://thoughtbot.com/upcase/test-driven-rails-resources/rspec.pdf
https://thoughtbot.com/upcase/test-driven-rails-resources/rspec_acceptance.pdf
https://code.tutsplus.com/articles/factory-girl-101--cms-25087
https://semaphoreci.com/community/tutorials/working-effectively-with-data-factories-using-factorygirl
