### ISSUE TITLE
POST 404 Error

### ISSUE THREAD

**Issue by JLisaW** [ga-wdi-boston/full-stack-project#860]
I keep getting a POST 404 error when I try to create a task item.  I looked through all my code but I can't seem to find the issue.  I'm not sure where else to look. 

Started POST "/tasks" for 127.0.0.1 at 2017-05-07 23:15:59 -0400
Processing by TasksController#create as */*
  Task Load (9.8ms)  SELECT  "tasks".* FROM "tasks" WHERE "tasks"."id" = $1 LIMIT $2  [["id", nil], ["LIMIT", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (5.29ms)
Completed 404 Not Found in 139ms (Views: 32.3ms | ActiveRecord: 81.0ms)

api.js
```javascript
const createTask = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/tasks',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```
events.js
```javascript
const onCreateTask = function (event) {
  event.preventDefault()
  api.createTask()
      .then(ui.createTaskSuccess)
.then(() => {
        api.viewTasks()
        .then(ui.viewTasksSuccess)
        .catch(ui.viewTasksError)
      })
      .catch(ui.createTaskError)
}

const onViewTasks = function (event) {
  event.preventDefault()
  api.viewTasks()
  .then(ui.viewTasksSuccess)
  .catch(ui.viewTasksError)
}
```

create task function
```javascript
function createTask () {
  const taskItem = document.getElementById('taskList').value
  const task = document.createTextNode(taskItem)
  const newTask = document.createElement('li')
  newTask.appendChild(task)
  document.getElementById('createTask').appendChild(newTask)
}
```

**Comment by tvcrawley** [comment]
Looks like this is an api problem. Have you looked at the error message from the rails server (or Heroku logs)?

**Comment by BenGitsCode** [comment]
Have you tested this action with curl requests?

**Comment by BenGitsCode** [comment]
Any updates here @JLisaW ?

**Comment by JLisaW** [comment]
This is the last commit where my request was working.  

https://github.com/JLisaW/task_project/commit/c8688b3a4342fdf4b30f8b5996b7f5477f7b9b35

After this commit, I've been seeing a 500 error.

**Comment by tvcrawley** [comment]
What is the message stemming from the error in the rails server?

**Comment by JLisaW** [comment]
I keep getting 

NoMethodError (undefined method `items' for nil:NilClass):

**Comment by tvcrawley** [comment]
So it looks like `items` is not accessible. Can you post the file associated with this error?

**Comment by JLisaW** [comment]
```rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :update, :destroy]
  

  # GET /tasks
  def index
    # @tasks = Task.all
    @tasks = current_user.tasks

    render json: @tasks
  end

  # GET /tasks/1
  def show
    render json: @task
  end

  # POST /tasks
  def create
    # @task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)

    if @task.save
      render json: @task, status: :created, location: @task
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      render json: @task
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      # @task = Task.find(params[:id])
      @task = current_user.tasks.find(params[:id])
    end

    def validate_user
      set_current_user
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:user_id, :description)
    end
end
```

**Comment by tvcrawley** [comment]
The create method looks fine. I'm going to direct you to [this issue](#814). Scroll down to Mike's response. Let me know if you need further help after reading it.

**Comment by BenGitsCode** [comment]
@tvlangley That's this issue 🙃 Did you mean [this](https://github.com/ga-wdi-boston/full-stack-project/issues/848) one?

**Comment by mangoceylon** [comment]
I think she meant [this one](https://github.com/ga-wdi-boston/full-stack-project/issues/814)

**Comment by BenGitsCode** [comment]
Any updates @JLisaW Did those issues provide any help?

**Comment by JLisaW** [comment]
no update on the the rails side but now my post is sort of working.  my store.user is coming up as undefined for some reason

**Comment by JLisaW** [comment]
Found the issue, in my HTML I put "tasks" instead of "task"

```html
  <h1>Task</h1>
    <form id="createTask">
        <input id="taskList" type="text" name="task[description]">
        <button type="submit">New Task</button>
    </form>
<ol id="task">
```
