### ISSUE TITLE
catching a specific server error?

### ISSUE THREAD

**Issue by awoodrum87** [ga-wdi-boston/full-stack-project#861]
My goal is to catch 500 and 422 errors and give the user specific errors for those circumstances. I have done a ton of research, but can't figure out what I'm doing wrong. 

I've tried leaving off the URL, taking the 'reviews' part off the url. 

some research I've conducted:
[read the documentation](http://api.jquery.com/jquery.ajax/)
[stackoverflow](http://stackoverflow.com/questions/13639225/how-to-capture-the-500-error-message-using-jquery)

```
$.ajax({
    url: "http://localhost:4741/reviews",
    statusCode: {
        500: function() {
            console.log('500 ')
        }
    }
})
```

```
$.ajax({
    url: "http://localhost:4741/reviews",
    statusCode: {
        500: function() {
            console.log('500 ')
        }
       422:function(){
           console.log('422')
    }
})
```

**Comment by jordanallain** [comment]
have you tried putting in a conditional in the failure function that checks the status code on the response?

**Comment by awoodrum87** [comment]
```
const createReviewFailure = (error) => {
  console.error(error)
  console.log('does fail sequence make it this far?')
  $.ajax({
    statusCode: {
      500: function () {
        console.log('500 error caught')
      }
    }
  })
}
```

**Comment by jordanallain** [comment]
maybe i'm misunderstanding what you're trying to do. i thought you wanted to give a specific error depending on the status code. in that code it looks like you're trying to make another ajax call. 

the `error` that this function receives should have a status code in it so i was saying you could make a conditional statement that checked the status code and gave back a specific message.

**Comment by awoodrum87** [comment]
i've previously tried an `if statusCode` function, didn't go well, but i'll try again

**Comment by jordanallain** [comment]
use the debugger/console.logs to make sure you're checking the correct part of your data.

**Comment by awoodrum87** [comment]
so [this documentation](http://api.jquery.com/jquery.ajax/) leads me to believe my original approach is correct. I did, however, try a few things. an if statement does not work at all. 

```
const createReviewFailure = (statusCode) => {
  // console.log('status code is', statusCode.reponseText) // returns undefined
  console.log('status code is', statusCode) // returns a massive object
  console.error(statusCode)
  console.log('does fail sequence make it this far?')

  // $.ajax({
  //   statusCode: {
  //     500: function () {
  //       console.log('500 error')
  //     }
  //   }
  // })

  if (statusCode === '500') {
    console.log('500 error')
  } else if (statusCode === '422') {
    console.log('422 error')
  }
}
```

**Comment by jordanallain** [comment]
the request response is going to be a large object, you will have to use dot notation to find the status code.

**Comment by awoodrum87** [comment]
yeah, I tried that (see line of the createReviewFailure function. I keep getting undefined. I have tried:
`console.log('status code is', statusCode.reponseText)`
`console.log('status code is', object.reponseText)`
`console.log('status code is', statusCode.Object.reponseText)`

The object looks like this:
<img width="475" alt="screen shot 2017-05-09 at 1 25 03 pm" src="https://cloud.githubusercontent.com/assets/25780850/25863776/15ce0ebc-34bb-11e7-8200-0f6ddad889a4.png">
<img width="359" alt="screen shot 2017-05-09 at 1 25 19 pm" src="https://cloud.githubusercontent.com/assets/25780850/25863775/1598fb96-34bb-11e7-890f-6839cbfbf8f9.png">

**Comment by jordanallain** [comment]
did you try statusCode.status?

**Comment by awoodrum87** [comment]
oh damnit. no i didn't but it works like a charm many many thanks.
