### ISSUE TITLE
Issue posting to API

### ISSUE THREAD

**Issue by mangoceylon** [ga-wdi-boston/full-stack-project#863]
I'm experiencing a similar issue to [this one](https://github.com/ga-wdi-boston/full-stack-project/issues/860)

I'm sending a POST to my API and receiving a 404 error:
<img width="701" alt="screen shot 2017-05-08 at 11 46 46 am" src="https://cloud.githubusercontent.com/assets/26262143/25812395/23f44bf0-33e4-11e7-82dc-e062924b62a4.png">

I could use a pointer in the right direction as to how I am formatting my POST request, because it seems like I might be doing something wrong.

I've read through previous issues and have tried a lot of different combinations of how I'm sending the data, but I could use another set of eyes.

**Comment by tvcrawley** [comment]
What is the error when running this request with a curl script?

**Comment by mangoceylon** [comment]
I've rewritten the curl script a few times and I keep getting: command not found.

If I copy paste an existing working curl script it still gives me a command not found.

**Comment by BenGitsCode** [comment]
How are you running the curl request?

Try running the curl script file from the command line.

**Comment by mangoceylon** [comment]
<img width="696" alt="screen shot 2017-05-08 at 12 03 57 pm" src="https://cloud.githubusercontent.com/assets/26262143/25813125/712d9e1a-33e6-11e7-9ff9-ec454c01f9d2.png">
<img width="696" alt="screen shot 2017-05-08 at 12 02 51 pm" src="https://cloud.githubusercontent.com/assets/26262143/25813129/747c224e-33e6-11e7-9702-503a0a9d963f.png">

**Comment by jordanallain** [comment]
Prefer pasting in the code over snapshots. it is saying id: nil, that is probably a problem. any idea where that is coming from?

**Comment by mangoceylon** [comment]
Yea so my issue seems to be I am querying WHERE inventories.id, but I want to be doing WHERE user.id.

So I'm trying to figure out how to change that.

**Comment by mangoceylon** [comment]
I'm now getting a 422 unprocessable entity

**Comment by BenGitsCode** [comment]
Now getting 422 after what? What changed?

**Comment by BenGitsCode** [comment]
Can you post the relevant controller code?

**Comment by mangoceylon** [comment]
```
  def create
    @inventory = current_user.inventories.build(inventory_params)

    if @inventory.save
      render json: @inventory, status: :created, location: @inventory
    else
      render json: @inventory.errors, status: :unprocessable_entity
    end
  end
```

Back to 404 error

**Comment by mangoceylon** [comment]
I think if I could get the query from the model to be pointed at the correct resource then this would be fixed, I'm just not sure how to do that, but continuing to try different combos and testing different things.

**Comment by jordanallain** [comment]
what is the relationship here. its between user and inventory correct?

**Comment by mangoceylon** [comment]
I'm trying to use a join table between both of them.

**Comment by jordanallain** [comment]
what is the join table?

**Comment by mangoceylon** [comment]
The join table has keys for user_id, ingredient_id, and amount

<img width="334" alt="screen shot 2017-05-08 at 3 31 36 pm" src="https://cloud.githubusercontent.com/assets/26262143/25821542/82e7792e-3403-11e7-9b4c-c0da8be82588.png">

**Comment by payne-chris-r** [comment]
<img width="303" alt="screen shot 2017-05-08 at 3 34 43 pm" src="https://cloud.githubusercontent.com/assets/12667121/25821670/07ca7a92-3404-11e7-9ca6-b2d1b5dc7795.png">
🔨 🔨 🔨 😜

**Comment by mangoceylon** [comment]
```ruby
class Inventory < ApplicationRecord
  has_many :user
  has_many :ingredient

  validates :user, presence: true
  validates :ingredient, presence: true
  validates :amount, presence: true
end

```

**Comment by mangoceylon** [comment]
```
Column     |            Type             |                        Modifiers                         
---------------+-----------------------------+----------------------------------------------------------
 id            | integer                     | not null default nextval('inventories_id_seq'::regclass)
 user_id       | integer                     | 
 ingredient_id | integer                     | 
 amount        | integer                     | 
 created_at    | timestamp without time zone | not null
 updated_at    | timestamp without time zone | not null
Indexes:
    "inventories_pkey" PRIMARY KEY, btree (id)
    "index_inventories_on_ingredient_id" btree (ingredient_id)
    "index_inventories_on_user_id" btree (user_id)
Foreign-key constraints:
    "fk_rails_6642cbdd87" FOREIGN KEY (user_id) REFERENCES users(id)
    "fk_rails_7806091f24" FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
```

**Comment by payne-chris-r** [comment]
```diff
class Inventory < ApplicationRecord
-  has_many :user
+  has_many :users
-  has_many :ingredient
+  has_many :ingredients

  validates :user, presence: true
  validates :ingredient, presence: true
  validates :amount, presence: true
end

```

**Comment by jordanallain** [comment]
what about in the User and Ingredient models?

**Comment by mangoceylon** [comment]
That gives a 500:

```
NoMethodError (undefined method `inventories' for #<User:0x007fa2368a28b8>):
```

**Comment by mangoceylon** [comment]
```
class Ingredient < ApplicationRecord
  has_many :users, through: :inventories
end
```

```
class User < ApplicationRecord
  include Authentication
  has_many :ingredients, through: :inventories
end
```

**Comment by jordanallain** [comment]
I believe your Inventory model should `belong_to` user and ingredient, not `has_many`

**Comment by mangoceylon** [comment]
Made those changes and tried a few other things and I'm still on the original issue.

```
Started GET "/inventories/" for 127.0.0.1 at 2017-05-08 15:55:15 -0400
Processing by InventoriesController#index as */*
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "70f4b69efa18f0b13c0f85a4123fadf0"], ["LIMIT", 1]]
  Inventory Load (0.2ms)  SELECT  "inventories".* FROM "inventories" WHERE "inventories"."id" = $1 LIMIT $2  [["id", nil], ["LIMIT", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.11ms)
Completed 404 Not Found in 16ms (Views: 5.3ms | ActiveRecord: 2.7ms)
```

I feel like the:

``` 
WHERE "inventories"."id" =$1
```


should be

```
WHERE "user_id" = $1
```

But I'm not sure what to do to make that happen.

**Comment by jordanallain** [comment]
what are the inventory_params in the inventories controller?

**Comment by jordanallain** [comment]
also

```
  validates :user, presence: true
  validates :ingredient, presence: true
  validates :amount, presence: true
```
are you sure you want to be validating `:user` and not `:user_id` in your inventory model?

**Comment by mangoceylon** [comment]
```
def inventory_params
      params.require(:inventory).permit(:ingredient_id, :amount)
    end
```

Here is what I'm sending it:

```
const inventoryLoad = {
      inventory: {
        ingredient_id: ingredientId,
        amount: amount
      }
    }
```

**Comment by mangoceylon** [comment]
Changing it from ```user``` to ```user_id``` made no obvious differences.

**Comment by mangoceylon** [comment]
Same issue persists.

**Comment by mangoceylon** [comment]
Was not assigning relationships correctly in the User and Ingredient model.

Was creating a has_many through the join table, but didn't have a relationship with the join table directly.

Thanks Toni!
