### ISSUE TITLE
Sorting Data from the database

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/full-stack-project#867]
I am trying to get some data from my database and sort if to figure out which advice gets the most yes votes and I am not sure where to start.  I was able to sort the data on the javascript end to do things like count total data and total votes but this seems like it could maybe be done on the back end and then returned as a different route or method. Any suggestions on which way to go with this? The data I am working with is from a table called take_advices which belongs to both user and advice and returns 0 or 1 in the :yes_or_no, as well as the user and the advice id, whenever anyones votes on the advice.   Below is an example of one take_advices object.   What I want is the ability to sort based on advice id number, then reduce the resulting yes_or_no array a sum and order them so I know which advice has the most yes votes and which has the least.  This is the sort of sorting that we did with jeff on the database sql level but I'm not sure how best to apply that here.   
```
 #<TakeAdvice:0x007faec540b9f8
  id: 160,
  yes_or_no: 1,
  advice_id: 253,
  created_at: Mon, 08 May 2017 15:19:37 UTC +00:00,
  updated_at: Mon, 08 May 2017 15:19:37 UTC +00:00,
  user_id: nil>,
```

**Comment by MicFin** [comment]
There are methods we can use.

.order (rails, activerecord query)
https://apidock.com/rails/ActiveRecord/QueryMethods/order

.group (rails, activerecord query)
https://apidock.com/rails/ActiveRecord/QueryMethods/group

.sort (ruby arrays)
http://agelber.com/blog/ruby-sort-vs-sort-by

More advice:
https://stackoverflow.com/questions/9857888/best-way-to-implement-sort-asc-or-desc-in-rails

**Comment by jordanallain** [comment]
yeah sounds like you want a SQL query that groups by and orders by certain columns

**Comment by tvcrawley** [comment]
Update? Was Mike's suggestions helpful?

**Comment by tvcrawley** [comment]
@Maggicorp ☝️

**Comment by Maggicorp** [comment]
I looked at this but didn't wind up doing it.
