### ISSUE TITLE
Issue with string interpolation on API post request

### ISSUE THREAD

**Issue by joebelmonte** [ga-wdi-boston/full-stack-project#869]
Hi, I'm trying to do a post request where I couldn't use get-form-fields since I'm trying to add data from a 3rd party API.  

The function that posts the data is called addNewMovieFromOMDb and I'm passing it an object that represents a single movie.  I should be able to type movie.name and have it put in the actual name of the movie, however when I use the code below it posts but the name in the database is "${movie.name}".  

```js
const addNewMovieFromOMDb = (movie) => {
  console.log('in addNewMovie and data is ', movie)
  return $.ajax({
    url: config.apiOrigin + '/movies',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: {
        "movie": {
          "name": "${movie.name}",
          "year_released": "",
          "mpaa_rating": "",
          "user_rating": "",
          "length": "",
          "ownership_status": "",
          "ownership_type": "",
          "last_viewing": "",
          "times_watched": "",
        }
      }
  })
}
```

I've tried using " ' "${movie.name}" ' " since I have seen that work in other places but that says "parsing error: Unexpected token $ (Fatal)".

Any suggestions?

**Comment by jordanallain** [comment]
In JavaScript, you need to use back ticks to do string interpolation. Double quotes is for ruby.

**Comment by joebelmonte** [comment]
I think I was able to figure it out - closing for now.

**Comment by joebelmonte** [comment]
Thanks, Jordan!
