### ISSUE TITLE
Help with being able to add delete update show items from my backend to my front end.

### ISSUE THREAD

**Issue by pguzman26** [ga-wdi-boston/full-stack-project#87]
This is what I have so far....

listGroceries: function (token, callback) {
    this.ajax({
      method: 'GET',
      url: this.url + '/groceries',
      headers: {
        Authorization: 'Token token=' + token
      },
      dataType: 'json'
    }, callback);
  },

  createGroceries: function (token, callback) {
    this.ajax({
      method: 'POST',
      url: this.url + '/groceries',
      headers: {
        Authorization: 'Token token=' + token
      },
      contentType: 'application/json; charset=utf-8',
      data: JSON.stringify({}),
      dataType: 'json',
    }, callback);

**Comment by gaand** [comment]
Do you have event handlers that invoke those methods?
