### ISSUE TITLE
Images not deploying

### ISSUE THREAD

**Issue by xiangcatherine** [ga-wdi-boston/full-stack-project#876]
I use quite a few images for my app (36), and while they work locally, they show as broken links when deployed. 

```javascript
const getImgBasedOnAge = (response) => {
  const week = response['baby']['age']
  const imgSource = ("assets/images/week" + week + ".PNG")
  $('.baby-size-img').css('display', 'block')
  $('.baby-size-img').attr('src', imgSource)
}
```
Above is the code I have for getting the image, which works fine. I searched online - some found that making the ending uppercase (.PNG) helped, but I'm still having issues. I could switch to hosting on something like imgur or cloudinary, but that means I would have to write much more code than above, since the names wouldn't be as clean.

Thank you!

**Comment by jordanallain** [comment]
there are a few closed issues dealing with similar problems. did you use relative or absolute paths?

**Comment by xiangcatherine** [comment]
Relative path e.g. assets/images/week9.png
I saw some places that using a raw github link works -- will try that now, since that's still a bit better than using imgur?

**Comment by jordanallain** [comment]
make sure you include the ./ or ../ to begin the url

**Comment by xiangcatherine** [comment]
OK just tried using a raw github link, and it works! 
Thanks Jordan :)
