### ISSUE TITLE
third party api over http returning error #30

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/full-stack-project#878]
The third party api I am using, this - http://api.adviceslip.com/#object-slip-example, does not work in the deployed version because it has been blocked for not being over https. The error message says -
```
vendor.js:9678 Mixed Content: The page at 'https://maggicorp.github.io/front-end-full-stack/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.adviceslip.com/advice'. This request has been blocked; the content must be served over HTTPS.
```
Is there any way around this?

**Comment by jordanallain** [comment]
try adding the `s` in after `http`

**Comment by Maggicorp** [comment]
I tried that it doesn't work.  I did a lot of googling and pretty much everything says you should either add the s, and if that doesn't work you can disable the mixed content blocker locally.  Is it cool if I disable the blocker on my chrome for the presentation? I couldn't find any other ways around it.  Is that final presentation kosher?

**Comment by jordanallain** [comment]
are you using a key to access the API?

**Comment by Maggicorp** [comment]
I am not using a key.  Here is how I access it.  It works locally 
```
const showExampleAdvice = () => {
  console.log('at show example advice')
  return $.ajax({
    url: 'http://api.adviceslip.com/advice',
    method: 'GET'
    // headers: {
    //   Authorization: 'Token token=' + store.user.token
    // }
  })
}
```

**Comment by jordanallain** [comment]
it may need a key to be passed in as a header im not sure. often third party api's will work locally without one.

**Comment by Maggicorp** [comment]
what type of key?  The documentation is pretty sparse and doesn't say anything about a key
http://api.adviceslip.com/#object-slip-example.  If I disable the chrome mixed content blocker shield it works.   I disabled it by doing this
```
Click the shield icon in the far right of the address bar.
In the pop-up window, click Load anyway or Load unsafe script (depending on your Chrome version).
```

**Comment by Maggicorp** [comment]
*Sorry, accidental close.

**Comment by BenGitsCode** [comment]
Where did you change an `http` to `https` I don't think you changed the right url.

**Comment by Maggicorp** [comment]
I did that.  changing it from http to https does not work for this api.  The url doesn't work when you do that and the api ajax call doesn't working doing that.

**Comment by BenGitsCode** [comment]
Have you tried passing in a header on the ajax request per Jordan's suggestion?

**Comment by Maggicorp** [comment]
I didn't know what header to pass.  He mentioned a key and I asked what he meant by a key. I still am unsure.  It currently doesn't have a header.

**Comment by Maggicorp** [comment]
The only header I have passed for other ones it the token.  But since it isn't my api I don't think I should pass it a random token.   I could pass this header, but I don't think that would change what I am trying to change.  
```
--header "Content-Type: application/json" 
```
I could also pass an access control origin header, but I am pretty sure we have coded that in to be always passed anyway.

**Comment by Maggicorp** [comment]
@BenGitsCode  I don't think this works with the https, https://www.programmableweb.com/api/advice-slip

**Comment by BenGitsCode** [comment]
That's what it's looking like. Are you just using the API to provide the example advice?

**Comment by Maggicorp** [comment]
Yes

**Comment by BenGitsCode** [comment]
If that's all you use it for then maybe table this for now, and provide some of your own seed data? If this API integration isn't essential for your project I'd put it aside for now.

Does the rest of your project meet requirements?

**Comment by Maggicorp** [comment]
Yes, the rest of my project meets requirements.  It is sort of the only thing I am still working on.  Any suggestions for an https advice or suggestions or inspiration api I could use instead?

**Comment by BenGitsCode** [comment]
Ah okay, that's good then. @MicFin do you have any thoughts? I don't know of any such APIs, I'd just make my own examples if they exist just to be examples.

**Comment by Maggicorp** [comment]
I changed it to this new api.  They are design advice and quotes, so a little more off topic, but here it is https://quotesondesign.com/api-v4-0/

**Comment by Maggicorp** [comment]
I have to see if it deploys but the documentation says it is https friendly

**Comment by Maggicorp** [comment]
They are like design quotes, so it makes way less sense...    :(
Moving forward, this one is having a access control origin error so I changed the request to include this header.
```
const showExampleAdvice = () => {
  return $.ajax({
    url: 'https://quotesondesign.com/wp-json/posts?filter[orderby]=rand&filter[posts_per_page]=1',
    // url: 'http://api.adviceslip.com/advice',
    method: 'GET',
    header: 'Access-Control-Allow-Origin: https://quotesondesign.com'})
}
```

**Comment by BenGitsCode** [comment]
That worked?

If so, that's great! Even if it's not quite the one you'd rather use, it shows a good ability to pivot and make sacrifices if necessary.

**Comment by Maggicorp** [comment]
That works.  I now have some inspirational advice about design displaying from a third party api.  I hope that is a good work around.  Let me know.
