### ISSUE TITLE
Mixed content when deploying to heroku

### ISSUE THREAD

**Issue by JLisaW** [ga-wdi-boston/full-stack-project#879]
i'm getting this error when i try to log into my deployed site.  i'm not really sure where to look to fix this issue.  

![image](https://cloud.githubusercontent.com/assets/26361086/25834478/29877864-3446-11e7-8fcf-46f42c2ddba0.png)

**Comment by jordanallain** [comment]
try adding `s` after the `http` in your API url

**Comment by JLisaW** [comment]
that didn't work, i'm getting the same error

**Comment by BenGitsCode** [comment]
Are you developing in private/incognito mode?

**Comment by JLisaW** [comment]
now i'm getting a 401 unauthorized error.  

![image](https://cloud.githubusercontent.com/assets/26361086/25854338/a3816718-349d-11e7-800a-bda8ede79c61.png)

**Comment by BenGitsCode** [comment]
Is that a user you've used on your deployed database before? does signing up a new user work?

**Comment by JLisaW** [comment]
my sign up isn't working anymore, i ran the curl script and it gave me a 201 created but my browser keeps refreshing even though I have event.preventDefault 

events.js
```javascript
const onSignUp = function (event) {
  event.preventDefault(event)
  const data = getFormFields(this)
  console.log('sign up success')
  api.signUp(data)
    .then(ui.signUpSuccess)
    .then(() => {
      api.signIn(data)
       .then(ui.signInSuccess)
       .catch(ui.signInFailure)
    })
   .catch(ui.signUpFailure)
}
```
api
```javascript
const signUp = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data
  })
}
```

**Comment by JLisaW** [comment]
it works now, thanks!
