### ISSUE TITLE
POST error when creating site

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/full-stack-project#88]
When I try to create a new site from the front end (after successfully logging in), I'm getting what seems like same error message as Laurisa was:
(console error)
POST http://localhost:3000/sites 401 (Unauthorized)  

(server error)
Started POST "/sites" for ::1 at 2015-11-12 15:45:13 -0500
Processing by SitesController#create as HTML
  Parameters: {"site"=>{"name"=>"asdf", "description"=>"asdf", "address"=>"asdf", "neighborhood"=>"asdf", "scale"=>"asdf", "coverage"=>"asdf", "busy"=>"asdf"}}
  User Load (1.1ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "undefined"]]
  Rendered text template (0.1ms)
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 11ms (Views: 1.1ms | ActiveRecord: 1.1ms)

createSite: function (token, new_site, callback) {
    this.ajax({
      method: 'POST',
      url: this.url + '/sites',
      headers: {
        Authorization: 'Token token=' + token
      },
      contentType: 'application/json; charset=utf-8',
      data: JSON.stringify(new_site),
      dataType: 'json',
    }, callback);
  },  

$('#new-site').on('submit', function(e) {
    e.preventDefault();

```
var token = $('.token').val();
var new_site = wrap('site', form2object(this));
proj_twoapi.createSite(token, new_site, function(err, data) {
  if(err) {
    console.log(err)
  } else{
    console.log(data);
  }
});
```

  });

**Comment by GA-MEB** [comment]
This looks like a problem with your controller's `create` method. Have you tested your controllers' methods in Postman?

Also, can you post the contents of that `create` method below?

**Comment by sarabrentmccoy** [comment]
Have only tested create in curl and it worked and was associated with the logged-in user.

**Comment by gaand** [comment]
This is probably about where you are (or aren't) saving the token.
Do you have an input element with a class of token? 
You probably need to store the token when you login is successful.  I suggest storing the user object returned as having the user's id is necessary for logout.

**Comment by sarabrentmccoy** [comment]
Min helped me out. I needed to declare var token outside of everything.
