### ISSUE TITLE
Delete button won't work - problem with event.currentTarget? or glyphicon?

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/full-stack-project#880]
I have a flashcard app that lists all flashcards created on a page when you click on 'view all cards' through the GET index request. Each card has a unique ID number displayed above and a **'delete (trash glyphicon)'** button below that pings the api with a DELETE request, deletes (from the database) its respective card, and hides the card (the rest of the undeleted cards scoot inward).

However, when I remove the text 'Delete' in order to **only use bootstrap trash glyphicon as a button** to delete its respective card, I get a 404 (not found) error that tells me the flashcard id is undefined. 

rails error:
```
Started DELETE "/flashcards/undefined" for 127.0.0.1 at 2017-05-09 09:14:37 -0400
Processing by FlashcardsController#destroy as */*
  Parameters: {"id"=>"undefined"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "7b1ab12fb55bd56a2eb4714dae506c28"], ["LIMIT", 1]]
  Flashcard Load (3.0ms)  SELECT  "flashcards".* FROM "flashcards" WHERE "flashcards"."user_id" = $1 AND "flashcards"."id" = $2 LIMIT $3  [["user_id", 2], ["id", 0], ["LIMIT", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.46ms)
Completed 404 Not Found in 20ms (Views: 3.3ms | ActiveRecord: 3.2ms)
```

handlebar file:
(point of interest: button#delete-flashcard)
```html
<div id="card-response" class="card-response">

  {{#each flashcards as |flashcard|}}

    <div id="card-container" class="card-container" data-id="{{flashcard.id}}">
      <div class="card-id" id="card-id">
        Card ID: {{flashcard.id}}
      </div>

      <div id="flip-container" class="flip-container" ontouchstart="this.classList.toggle('hover')">

        <div class="flipper">
          <div id="flip-front" class="flip-front card">
            <p id="flip-front-text" class="flip-front-text">
              {{flashcard.word}}
            </p>
          </div>

          <div id="flip-back" class="flip-back card">
            <p id="flip-back-text" class="flip-back-text">
              {{flashcard.definition}}
            </p>
          </div>
        </div>
      </div>

      <audio controls
      src="http://api.voicerss.org/?key=cb75676b142f4d9ea40f9082ad50731b&hl=ja-jp&src={{flashcard.word}}" class="word-audio" id="word-audio">
      Your browser does not support the <code>audio</code> element.
      </audio>

      <button id="delete-flashcard" class="delete-flashcard" data-id="{{flashcard.id}}">
        <span class="glyphicon glyphicon-trash"></span>       
      </button>

    </div>
  {{/each}}

</div>
```

specifically, this works:
```html
      <button id="delete-flashcard" class="delete-flashcard" data-id="{{flashcard.id}}">
        <span class="glyphicon glyphicon-trash"></span>
       Delete
      </button>
```
but this won't: 
```html
      <button id="delete-flashcard" class="delete-flashcard" data-id="{{flashcard.id}}">
        <span class="glyphicon glyphicon-trash"></span>
       
      </button>
```
<br>
<br>

ui.js:
(point of interest: $(event.currentTarget).parent().remove() in onDeleteFlashcard function)
```js
const onDeleteFlashcard = function (event) {
  event.preventDefault()
  createDataObject($(event.target).data('id'))
  $(event.target).prop('disabled', true)
  console.log('$(this).parent() ', $(this).parent())
  console.log('$(event.target).parent() is ', $(event.target).parent())
  console.log('$(event.currentTarget).parent() is', $(event.currentTarget).parent())

  $(event.currentTarget).parent().remove()
  if ($('.card-response').children().length === 0) {
    $('#content-status-message').text('You have no cards. Create a new card.')
  }
}

const createDataObject = function (flashcardId) {
  const data = {
    flashcard: {
      id: flashcardId
    }
  }

  event.preventDefault()
  api.deleteFlashcard(data)
    .then(ui.getFlashcardsSuccess)
    .catch(ui.getFlashcardsFailure)
}
```
I use  ```$(event.currentTarget).parent().remove()``` to traverse from the button (button.card-container) to the parent (div.card-response) to target the parent of the button. When the 'Delete' text is present in handlebar, this works. When the 'Delete' text is not present, it won't work.

I've tried using ```this```, ```event.target```, and ```event.currentTarget``` to target the parent of the button, but as you can see below, only ```this``` and ```event.currentTarget``` seem to target the parent (which seems like using either ```this``` or ```event.currentTarget``` will make the delete work). Yet, when the delete button is clicked, I get a 404 not found error that says the flashcard id is undefined.

console.logs when it works:
<img width="770" alt="screen shot 2017-05-09 at 9 13 02 am" src="https://cloud.githubusercontent.com/assets/16979795/25852583/d61a48bc-3497-11e7-93e2-4484114bb07b.png">

console.log when it doesn't work: 
<img width="716" alt="screen shot 2017-05-09 at 9 14 43 am" src="https://cloud.githubusercontent.com/assets/16979795/25852626/feb946f6-3497-11e7-9f11-e5f70fc94d13.png">

Is the problem with the span tag (that has the glyphicon class) or the event.currentTarget/this?

**Comment by gaand** [comment]
That does this function do:

```js
const createDataObject = function (flashcardId) {
  const data = {
    flashcard: {
      id: flashcardId
    }
  }
```

**Comment by nriser** [comment]
@gaand Thank you for your response.

The ```onDeleteFlashcard``` function calls the ```createDataObject``` function, and passes in the data-id number of the delete button (which corresponds to its respective flashcard). Then in ```createDataObject```, I use the id number response from the server and contain it in a flashcard data object that I create (```const data```). That data object is then sent to the API ```(api.deleteFlashcard(data))``` in order to delete the flashcard through the DELETE action. 

I apologize in advance if my explanation is insufficient.

**Comment by MicFin** [comment]
Great job troubleshooting.  You seem very close to solving the issue.

`Parameters: {"id"=>"undefined"}` - you identified the meaningful part of the error

`$(event.target).data('id')` - This is where you are getting the ID from the DOM 

Does the `$(event.target)` element have a `data-id` attribute?

**Comment by nriser** [comment]
@MicFin 

Thank you for response. Your last sentence was a great hint. I added the data-id attribute to the nested span tag too, and it works now! 

```
      <button id="delete-flashcard" class="delete-flashcard" data-id="{{flashcard.id}}">
        <span class="glyphicon glyphicon-trash" data-id="{{flashcard.id}}"></span>

      </button>
```

Although, I can't comprehend why event.currentTarget will not work without the span tag with data-id attribute. As show in the console, event.currentTarget refers to the button, not span, and event.currentTarget.parent() refers to the container element that I want .remove(). Theoretically, shouldn't it work using event.currentTarget with or without the span tag?

![](https://cloud.githubusercontent.com/assets/16979795/25852626/feb946f6-3497-11e7-9f11-e5f70fc94d13.png)

**Comment by tvcrawley** [comment]
@nriser Is this issue resolved?

**Comment by nriser** [comment]
@tvlangley I'm waiting for a response to my last question: 'Theoretically, shouldn't it work using event.currentTarget with or without the span tag?'

**Comment by scottyscripts** [comment]
@nriser take a look at event bubbling and the difference between `event.target` and `event.currentTarget`

**Comment by MicFin** [comment]
^ Yes, what he said

**Comment by nriser** [comment]
Thank you! Will look into it.
