### ISSUE TITLE
How to load jQuery file from package.json into html?

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/full-stack-project#881]
I'm implementing the parallax effect (included in the project exceeds site) and the direction says:

https://github.com/pixelcog/parallax.js/
```
Download package or install with Bower and include parallax.min.js in your document after including jQuery.

$ bower i --save parallax.js

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="/path/to/parallax.min.js"></script>
```
... and when I do the second option of adding the two script tags to my head tag, the parallax scrolling effect works.

```html
<head>
  <title>KIOKU</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Do not add `link` tags unless you know what you are doing -->
  <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">

  <!-- Do not add `script` tags unless you know what you are doing -->
  <script src="public/vendor.js" type="text/javascript" charset="utf-8" defer></script>
  <script src="public/application.js" type="text/javascript" charset="utf-8" defer></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="parallax.js-1.4.2/parallax.js"></script>
</head>
```

However, my understanding is that the jQuery library is already loaded in our template (thus we're able to use jQuery in our javascript files) through the package.json file. I believe I'd be writing redundant code by adding the google-hosted tag below:

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
```

I've tried NOT adding the above script tag in my head, but the parallax effect will no longer work.

```html
<head>
  <title>KIOKU</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Do not add `link` tags unless you know what you are doing -->
  <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">

  <!-- Do not add `script` tags unless you know what you are doing -->
  <script src="public/vendor.js" type="text/javascript" charset="utf-8" defer></script>
  <script src="public/application.js" type="text/javascript" charset="utf-8" defer></script>
  <script src="parallax.js-1.4.2/parallax.js"></script>
</head>
```

How can I load the jQuery that exists in package.json?

**Comment by jordanallain** [comment]
In the browser template it instructs you not to add any script tags so definitely won't work if you have those in there.

**Comment by jordanallain** [comment]
i would look at this page, i believe this is the package you were referring to

https://www.npmjs.com/package/parallax-js

**Comment by nriser** [comment]
@jordanallain thank you for your reply.

Actually, it does work when I enter the script tags. Can I keep doing it the way I am?

**Comment by jordanallain** [comment]
it may work now but it won't when you deploy

**Comment by nriser** [comment]
@jordanallain I see! I'll check it out, thank you!
