### ISSUE TITLE
Can Not Read, Update, or Destroy

### ISSUE THREAD

**Issue by kellye2010** [ga-wdi-boston/full-stack-project#885]
Upon successfully logging in, I am able to create an item, but I am not able to successfully read, update or destroy any items. In my GET/read for all playlists, I receive a 200 message, but I am not receiving the data that is expected. My remaining CRUD actions (update and destroy) are just not able to update or destroy any of my items that have been created.
![screen shot 2017-05-09 at 12 19 32 pm](https://cloud.githubusercontent.com/assets/4691419/25861261/2f29e7ae-34b2-11e7-8b35-fe668e5795d0.png)
![screen shot 2017-05-09 at 12 22 04 pm](https://cloud.githubusercontent.com/assets/4691419/25861322/62ddc19c-34b2-11e7-98bc-48435308b9e7.png)
![screen shot 2017-05-09 at 12 20 10 pm](https://cloud.githubusercontent.com/assets/4691419/25861325/6683b2ac-34b2-11e7-9f2b-0ee03aa96876.png)
![screen shot 2017-05-09 at 12 20 44 pm](https://cloud.githubusercontent.com/assets/4691419/25861330/69e14ef0-34b2-11e7-8f98-19bc5ce3eacf.png)
![screen shot 2017-05-09 at 12 20 57 pm](https://cloud.githubusercontent.com/assets/4691419/25861334/6d23223c-34b2-11e7-8de4-b02748408681.png)
![screen shot 2017-05-09 at 12 22 23 pm](https://cloud.githubusercontent.com/assets/4691419/25861338/6f68f59e-34b2-11e7-8486-a152857960ca.png)

**Comment by tvcrawley** [comment]
Looks like there's a lot of `unauthorized` messages occurring. Are the `current_user`s items able to get (for an individual item) and update?

**Comment by tvcrawley** [comment]
Can you post the ajax requests and playlists controller?

**Comment by kellye2010** [comment]
Playlists controller and AJAX requests below:
![screen shot 2017-05-09 at 12 53 53 pm](https://cloud.githubusercontent.com/assets/4691419/25862649/c981d3ee-34b6-11e7-816e-4494a34475ba.png)
![screen shot 2017-05-09 at 11 40 55 am](https://cloud.githubusercontent.com/assets/4691419/25862651/cba23b64-34b6-11e7-975f-eab988b9a28f.png)
![screen shot 2017-05-09 at 12 56 14 pm](https://cloud.githubusercontent.com/assets/4691419/25862714/1514aee4-34b7-11e7-9611-e0aa81f99fec.png)
![screen shot 2017-05-09 at 12 56 34 pm](https://cloud.githubusercontent.com/assets/4691419/25862715/15172908-34b7-11e7-96a0-6d37b968c843.png)

**Comment by tvcrawley** [comment]
Can you post this again but the code and not screenshots?

**Comment by kellye2010** [comment]
AJAX Requests:
`'use strict'
const config = require('../config.js')
const store = require('../store.js')
// const app = require('../app.js')

const createPlaylist = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/playlists',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

const indexPlaylists = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/playlists',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.token
    },
    data
  })
}

// const showPlaylists = (data) => {
//   return $.ajax({
//     url: config.apiOrigin + '/playlists/',
//     method: 'GET',
//     headers: {
//       Authorization: 'Token token=' + store.user.token
//     },
//     data
//   })
// }

const showPlaylist = function (id) {
  return $.ajax({
    url: config.apiOrigin + '/playlists/' + id,
    method: 'GET',
    Authorization: 'Token token=' + store.user.token
  },
)
}

const updatePlaylist = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/playlists/' + data.playlist.id,
    method: 'PATCH',
    data
  })
}

const destroyPlaylist = function (id) {
  return $.ajax({
    url: config.apiOrigin + '/playlists/' + id,
    method: 'DELETE'
  })
}

module.exports = {
  createPlaylist,
  indexPlaylists,
  showPlaylist,
  // showPlaylists,
  updatePlaylist,
  destroyPlaylist
}
`

Controller:
`class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :update, :destroy]
  before_action :authenticate, only: [:show, :create, :update, :destroy]

  # GET /playlists
  def index
    @playlists = Playlist.all

    render json: @playlists
  end

  # GET /playlists/1
  def show
    @playlist = Playlist.find(params[:id])
    @playlist = current_user.playlists.build(playlist_params)
    render json: @playlist
  end

  # POST /playlists
  def create
    # @playlist = Playlist.new(playlist_params)
    @playlist = current_user.playlists.build(playlist_params)
    if @playlist.save
      render json: @playlist, status: :created, location: @playlist
    else
      render json: @playlist.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /playlists/1
  def update
    # @playlist = Playlist.find(params[:id])
    if @playlist.update(playlist_params)
      render json: @playlist
    else
      render json: @playlist.errors, status: :unprocessable_entity
    end
  end

  # DELETE /playlists/1
  def destroy
    # @playlist = Playlist.find(params[:id])
    # @playlist = current_user.playlists.build(playlist_params)
    @playlist.destroy
    head :no_content
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def playlist_params
      params.require(:playlist).permit(:title, :user_id)
    end
end
`

**Comment by scottyscripts** [comment]
Take a look at how you are sending token in `indexPlaylists` function. You are getting the value of `token` in a different way here, than everywhere else. Verify that token is being sent with your requests.

**Comment by kellye2010** [comment]
I started out with using store.user.token for the authentication in my indexPlaylist function, but the problem I get is that it is creating an array of the "example text" I used in my rails-api for each object created.

**Comment by jordanallain** [comment]
@kellye2010 is this issue still persisting?
