### ISSUE TITLE
Using Paperclip Gem

### ISSUE THREAD

**Issue by xiangcatherine** [ga-wdi-boston/full-stack-project#886]
I want to build a function where mothers can upload photos of their bump, and I have found [this](https://github.com/ga-wdi-boston/rails-paperclip) WDI lesson on the Ruby gem Paperclip very helpful.

But I am having trouble sending the image from the client to the API. In the above link, there is this code:

```javascript
$(document).ready(function(){

  $('#submit').on('click', function(e){
    e.preventDefault();
    // creates a new instance of the FileReader object prototype
    var reader = new FileReader();

    //setting a function to be executed every time the reader successfully completes a read operation
    reader.onload = function(event){
      // once the data url has been loaded, make the ajax request with the result set as the value to key 'poster'
      $.ajax({
        url: 'http://localhost:3000/movies',
        method: 'POST',
        data: { movie: {
          title: $('#title').val(),
          director: $('#director').val(),
          poster: event.target.result
        } }
      }).done(function(response){

      }).fail(function(response){
        console.error('Whoops!');
      })
    };

    // read the first file of the file input
    $fileInput = $('#poster');
    reader.readAsDataURL($fileInput[0].files[0]);

  });
});
```
I think I understand most of it, but the part I'm having trouble with is 
```
$fileInput = $('#poster');
reader.readAsDataURL($fileInput[0].files[0]);
```

Specifically, what is $fileInput?

Any guidance on this would be helpful!

**Comment by scottyscripts** [comment]
In this particular lesson, `$('#poster')` is the selector for `<input type="file" id="poster"/>`

You would want to use a selector to target your `<input type="file" />` element

**Comment by scottyscripts** [comment]
Check out this link on MDN also https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL

**Comment by MicFin** [comment]
I love that you are undertaking this challenge.  The AWS part to make it work on production may pose to be outside of the scope of what you're going to have time for.

**Comment by jordanallain** [comment]
as a work around you could include instructions for your users to upload a picture to imgur, and then just use the URL of the image to display it on your page

**Comment by xiangcatherine** [comment]
Great, thank you!

**Comment by xiangcatherine** [comment]
Will keep digging through this - might not be able to complete it by tomorrow, but definitely a thing I want to do afterwards! :)
