### ISSUE TITLE
UI - Displaying indexed items

### ISSUE THREAD

**Issue by kellye2010** [ga-wdi-boston/full-stack-project#887]
When running a GET action to display a list of indexed items, I do not know how to make these indexed items appear in the UI. What documentations should I reference to find out how to do this??

**Comment by benjimelito** [comment]
When you say that you are unable to get these items to display in the UI, do you mean that you are unable to get them to display on the page?

**Comment by benjimelito** [comment]
And also when you say indexed items, are you saying that you want the items to be displayed with their indexes on the page?

**Comment by kellye2010** [comment]
Hi Ben,
Yes I do mean that I am not able to get the items to display on the page. I want to be able to display them in a list format

**Comment by benjimelito** [comment]
Ok gotcha. Are you planning on using handlebars to do this (not a requirement)?

**Comment by kellye2010** [comment]
I do plan on using handlebars. I need it to meet exceeds (unless its "bonus" and not "exceeds") but from my understanding, it's cleaner to use handlebars.

**Comment by benjimelito** [comment]
I think that using handlebars alone is simply a bonus, and you will need
more for an exceeds. That being said, I would start by looking at the
handlebars lesson, and trying to apply it to your project. Feel free to
reply here if you have questions about it.

**Comment by benjimelito** [comment]
How is this going Kelly?

**Comment by kellye2010** [comment]
resolved
