### ISSUE TITLE
Question about README requirements.

### ISSUE THREAD

**Issue by aprilsourz** [ga-wdi-boston/full-stack-project#888]
Hello. 

Does the Readme in the repository for my back end need to have anything other than a link to the front end repo?

Are the requirements for the README in the front end repository the same as for the Tic Tac Toe project? Other than needing a link to my back end repository?

**Comment by tvcrawley** [comment]
According to the requirements, that is all however, someone going to your api repo  would have no context whatsoever on what's going on. 

[API readme example](https://github.com/ga-wdi-boston/game-project-api)

**Comment by aprilsourz** [comment]
Ok thanks, I'll put something helpful in there. 

Are the requirements for the README in the front end repository the same as for the Tic Tac Toe project? Other than needing a link to my back end repository?

**Comment by BenGitsCode** [comment]
Yes. You can review the readme requirements [here](https://github.com/ga-wdi-boston/full-stack-project#deliverables)

**Comment by aprilsourz** [comment]
thanks
