### ISSUE TITLE
How to save the json object returned by an AJAX query

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/full-stack-project#889]
Title sort of says it all. I'm trying to save the result of a GET request to pass through another function, but cannot seem to make the result of the request stick. 

Code in question
```js
return ui.isMovie(api.omdbGet(input))
```
I am trying to pass the JSON object created by the AJAX query of omdbGet(input), but the value passed to isMovie() is the following:

```js
Object {readyState: 1, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}
```
How would I solve this problem?

**Comment by benjimelito** [comment]
I believe you are encountering an issue with asynchronus code. Assuming that `api.omdbGet` is an AJAX request, it is being passed into `ui.isMovie` before it has finished executing. Try to look up using `.then()` statements to fix this, but if you have questions let me know.

**Comment by d00medman** [comment]
so when I run the following code
 ```js 
api.omdbGet(input).then(ui.isMovie)
```
the result is [object Object]. However, the method isMovie is supposed to return a boolean value

```js
const isMovie = (response) => {
  console.log(response)
  console.log(response.Response)
  if (response.Response === 'False') {
    return false
  }
  return true
}
```

The logic of isMovie works properly, but I am wondering why it is not returning its result.

**Comment by benjimelito** [comment]
I don't think that syntax for `.then()` is 100% correct. You still need to somehow pass the result of the returned AJAX call to `ui.isMovie`. Try something like this:
```
api.omdbGet(input)
.then(function(ajaxResult){
ui.isMovie(ajaxResult)
}
```

**Comment by d00medman** [comment]
Alright, I think I can see my problem. my issue is that I am making this AJAX call in the same method as another ajax call

```js
const onCreate = function (event) {
  event.preventDefault()
  const data = getFormFields(this)
  const exists = isRealMovie(data.movie.title)
  console.log('exists: ' + exists)
  if (ui.validate(data.movie.title) === true && exists === true) {
    api.create(data)
      .then(ui.createSuccess)
      .catch(ui.createFailure)
  } else if (exists === true) {
    ui.createFailure()
  } else {
    ui.createFailure()
  }
}
```

Despite the fact that the AJAX call appears to be working, I'm guessing the fact that I'm calling the omdbGet in the same code block as the onCreate is the source of my problem. How would I go about getting these functions to fire in the correct order?

**Comment by jordanallain** [comment]
you could change the success function that gets called, you know that function won't be invoked unless the call has returned successfully.

**Comment by jordanallain** [comment]
@d00medman can this be closed now?
