### ISSUE TITLE
Token is undefined when I redirected to a new page

### ISSUE THREAD

**Issue by leahphuong** [ga-wdi-boston/full-stack-project#89]
$('#AddNewItem').click(function(e) {
    e.preventDefault();
    console.log(token);
    window.location.href = '/addAnItem.html?token=' + token;
  });

I tried to declare the token as global variable but it didn't work =(

**Comment by GA-MEB** [comment]
Where do you define `token`?

**Comment by leahphuong** [comment]
on line 1 of my js file.

**Comment by srhoulam** [comment]
Leah, you have two options:
- Make a single-page app so you never have this problem of losing all your variables when you navigate to another page.
- Use [LocalStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to store and retrieve the token across pages.

**Comment by GA-MEB** [comment]
Oh geez, I didn't even notice that. Yeah, Leah - why are you using `window.location.href`? Are you trying to load a separate page?

**Comment by srhoulam** [comment]
Leah is now using local storage to store and retrieve her token, and no longer passing it across pages in the query string.
