### ISSUE TITLE
Unmet Requirement Clarification

### ISSUE THREAD

**Issue by andyjzhong** [ga-wdi-boston/full-stack-project#890]
Greetings --

I was wondering if I could get some clarification on the following unmet requirements I had for Project 2:

1. Any actions which change data must be authenticated, and the data must be "owned" by the user performing the change.
2. Other users can delete and update resource
3. Unauthenticated users can create resource

Based on the code in my Cars Controller however, I believe I have addressed each of these items, so I'm looking for some feedback for how I can satisfy these requirements if unmet.

I believe the following code in my Car Controller addresses the first two requirements of making sure only the current user can update/delete their own cars.
```
class CarsController < ProtectedController
  before_action :set_car, only: [:show, :update, :destroy]

... (code in between) ...

    # Use callbacks to share common setup or constraints between actions.
    def set_car
      # @car = Car.find(params[:id])
      @car = current_user.cars.find(params[:id])
    end
```

Also, in relation to requirement #3, I believe the following code addresses allowing ONLY current users to create their OWN cars:
```
# POST /cars
  def create
    # @car = Car.new(car_params)
    # Array of current user's car objects

    # Build method allows you to create a new car and also build an association between user and new car.
      # @car = Car.new(car_params)
      # @car.user_id = current_user.id
    @car = current_user.cars.build(car_params)

    if @car.save
      render json: @car, status: :created, location: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end
```

@payne-chris-r  mentioned to place my entire Car Controller below, which I believe had addressed each of these issues. The only resources I have as part of my project are Cars and Users.

Feel free to correct me if I'm wrong, but I just wanted to make sure I'm not trying to fix something that isn't broken.

Thanks!
Andy

```
class CarsController < ProtectedController
  before_action :set_car, only: [:show, :update, :destroy]

  # GET /cars
  def index
    @cars = current_user.cars

    render json: @cars
  end

  # GET /cars/1
  def show
    render json: @car
  end

  # POST /cars
  def create
    # @car = Car.new(car_params)
    # Array of current user's car objects

    # Build method allows you to create a new car and also build an association between user and new car.
      # @car = Car.new(car_params)
      # @car.user_id = current_user.id
    @car = current_user.cars.build(car_params)

    if @car.save
      render json: @car, status: :created, location: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cars/1
  def update
    if @car.update(car_params)
      render json: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end

  # DELETE /cars/1
  def destroy
    @car.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      # @car = Car.find(params[:id])
      @car = current_user.cars.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def car_params
      params.require(:car).permit(:make, :model, :year, :color)
    end
end
```

**Comment by tvcrawley** [comment]
Have you tried running curl scripts against your api to see if:
- **only** the current user is able to update & delete cars?  
- someone who is not signed in **cannot** create cars?

**Comment by andyjzhong** [comment]
Yes -- I was able to successfully run my curl scripts against my API and I was unable to replicate the issues suggested by the 3 unmet requirements. 

For #3, I tried to create a new car without passing it a current user token and it **did not** allow me to create a car using my curl script. Once I successfully logged in and passed it the current user's token, I was able to create my cars.

For #1 and #2, I logged in as User A and tried to update and delete User B's cars using my curl scripts. I was presented with a NOT FOUND error in my server. Once I logged into User B's account and passed it the correct token using my curl scripts, I was able to successfully update and delete User B's cars.

Please let me know if you require more detail -- I'm happy to share the curl scripts I tried.

Based on my findings, it seems that my code was working appropriately for these 3 requirements -- but like I've mentioned before, I would just like confirmation/clarification in case I'm misunderstanding my Project 2 feedback so I can better understand what exactly I need to fix.

Thanks!
