### ISSUE TITLE
Local App Not Working - Yesterday It Worked - No Changes Since Then

### ISSUE THREAD

**Issue by lisamsmith100** [ga-wdi-boston/full-stack-project#891]
My local app worked yesterday.  It is not working today (cannot log in).  I didn't change it yesterday or last night.  I want assistance if possible.  I'm getting in my own way and don't know why.
Would someone have a minute to discuss this with me?

**Comment by lisamsmith100** [comment]
It's probably something really obvious... but it was working yesterday...


![image](https://cloud.githubusercontent.com/assets/26127720/25871276/ef734d44-34d4-11e7-8b31-a0313541b865.png)


Browser:
```sh

$ grunt server
Running "webpack-dev-server:start" (webpack-dev-server) task
webpack-dev-server on port 7165  
 67% 125/131 build moduleswebpack: wait until bundle finished: /public/vendor.js
webpack: wait until bundle finished: /public/application.js
Version: webpack 1.15.0     
                                 Asset     Size  Chunks             Chunk Names
                        application.js   298 kB       0  [emitted]  application
  f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]  
 fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]  
  e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]  
  89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]  
  afa0884dbb5d1cd1cb341d06ff45597e.jpg   1.9 MB          [emitted]  
448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]  
                              specs.js  1.38 kB       1  [emitted]  specs
                             vendor.js   597 kB       2  [emitted]  vendor
                    application.js.map   369 kB       0  [emitted]  application
                          specs.js.map  1.92 kB       1  [emitted]  specs
                         vendor.js.map   723 kB       2  [emitted]  vendor
webpack: Compiled successfully.


```


Rails:
```sh
Use Ctrl-C to stop
Killed: 9
~/wdi/projects/hnd-api (resub)
$ bin/rails server
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://localhost:4741
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.7.0 (ruby 2.3.1-p112), codename: Snowy Sagebrush
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:4741
Use Ctrl-C to stop
```

**Comment by jrhorn424** [comment]
Show me the definition of your `signUp` AJAX request, as well as your API host configuration, please and thank you.

**Comment by lisamsmith100** [comment]
From my auth/api.js

```js
'use strict'

const config = require('../config')
const store = require('../store')

const signUp = function (data) {
  // console.log('signup data is ', data)
  return $.ajax({
    url: config.apiOrigin + '/sign-up/',
    method: 'POST',
    data
  })
}

```

From my templates/config.js
```js
'use strict'

const config = {
  apiOrigins: {
    development: 'http://localhost:7165',
    production: 'https://hnd-api.herokuapp.com/'
  }
}

module.exports = config
```

**Comment by lisamsmith100** [comment]
I tried to update my Model file to remove the validation for title and then remigrated but it was not working before that... so I don't think that is the issue.

**Comment by scottyscripts** [comment]
Take a look at the `url` you are POSTing to in your AJAX request. What is the value of `config.apiOrigin`?

**Comment by lisamsmith100** [comment]
I updated to this:
```js
'use strict'

const config = {
  apiOrigin: {
    development: 'http://localhost:7165',
    production: 'https://hnd-api.herokuapp.com/'
  }
}

module.exports = config
```
Still not able, but looking into it.  I think I was just going to update the index.html to make the project pass, but i feel like i should remove the title validation in my model and re-migrate.

**Comment by lisamsmith100** [comment]
but maybe I need not do that... and just add the user-message.

**Comment by lisamsmith100** [comment]
I figured out the issue.  I reverted my config file to 
```js
'use strict'

const config = {
  apiOrigins: {
    // development: 'http://localhost:7165',
    production: 'https://hnd-api.herokuapp.com/'
  }
}

module.exports = config

```
I saw others had the development in there but mine works without.  
I totally panicked and should not have.  Thanks for the question, @sdavidson140 .  Took me a while to thrash on it and was hoping to avoid thrashing but with interest of getting it wrapped up, really wanted to figure it out.

**Comment by jrhorn424** [comment]
> => Rails 5.0.1 application starting in development on http://localhost:4741

Now look at your `config` once again.

**Comment by jrhorn424** [comment]
Ah, didn't refresh the page before posting. Good work!

**Comment by lisamsmith100** [comment]
Thanks!
