### ISSUE TITLE
Third Party API

### ISSUE THREAD

**Issue by eliottenos** [ga-wdi-boston/full-stack-project#898]
Im trying to send data to the third party api and the docs have suggested the following API call
```js
$('#weather').click(function() {
const zipCode=" ";
$.ajax({ url : "http://api.wunderground.com/api/d118b6ec8394c5fc/geolookup/forecast/q/US/"+zipCode +".json",
dataType : "jsonp",
success : console.log(parsed_json)
}
```

The syntax is causing a fatal error though and im struggling to fix this in accordance with docs?  Any suggestions?  zipCode to send the inputed zipcode from #weather id.  The url is the provided one from api and ```d118b6ec8394c5fc``` is my key

**Comment by benjimelito** [comment]
What is the fatal error that you are getting?

**Comment by eliottenos** [comment]
It says ```module.exports``` below is unexpected? And if I try and close out the above with (} it says that they are unexpected tokens

**Comment by prankmode** [comment]
Do you think it's weird that you are constructing a URL with a space in it?  Is zipCode a space?

**Comment by benjimelito** [comment]
I think the issue might have something to do with closing out all your parens and curlies...pay attention to those

**Comment by eliottenos** [comment]
ok changed around the api caller as syntax was all messed up.
now I have my html
```html
<h3>Check Weather</h3>
        <form class='locations' id='weather'>
        <div class="form-group">
          <input type="number" name="location[zipcode]" id="zipcode" placeholder="Zipcode">
        </div>
        <input type="submit" name="submit" value="Submit">
      </form>
```
which calls an event...
```js
$('#weather').on('submit', onWeather)
const onWeather = function (event) {
  const data = getFormFields(this)
  event.preventDefault()
  api.weather(data)
    .then(ui.weatherSuccess)
    .catch(ui.weatherFailure)
}
```
which calls ui.js
```js
const weatherSuccess = (data) => {
  console.log(data)
  $('.auth').text('weather')
}
```
and my api.js
```js
const weather = (data) => {
  return $.ajax({
    url : 'http://api.wunderground.com/api/d118b6ec8394c5fc/geolookup/forecast/q/US/'+ data.zipCode +.'json',
    method: 'GET',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: data
  })
}
```

**Comment by eliottenos** [comment]
Getting this back in console?

![screen shot 2017-05-17 at 17 25 25](https://cloud.githubusercontent.com/assets/26254104/26176978/fb9ad608-3b25-11e7-82c4-30342344ff92.png)

**Comment by jordanallain** [comment]
Check out that URL, something in it is `undefined`

**Comment by eliottenos** [comment]
docs say should be sent in this format?
```http://api.wunderground.com/api/d118b6ec8394c5fc/conditions/q/CA/San_Francisco.json```

**Comment by jordanallain** [comment]
It's data.zipCode that is undefined so maybe put a debugger in there to see what data is and if it has a zipCode in it.

**Comment by benjimelito** [comment]
Status?

**Comment by jordanallain** [comment]
@eliottenos ?

**Comment by BenGitsCode** [comment]
Bump^
