### ISSUE TITLE
having trouble with my login ajax request

### ISSUE THREAD

**Issue by baz1389** [ga-wdi-boston/full-stack-project#9]
At the end of my login.on() method I have a console.log("You logged in")  and $('.login-block').hide(); to display that I did, in fact, log in. I put debuggers in between every line of my code to see how each line is working. Going through each line piecemeal, everything seems to be working. However, once I exit the .on() method the website seems to refresh and the console doesn't display anything and the html isn't hidden. No error messages are being displayed either.

**Comment by srhoulam** [comment]
Helped Ben get his authentication sorted out on the front end.
