### ISSUE TITLE
Update functionality

### ISSUE THREAD

**Issue by baz1389** [ga-wdi-boston/full-stack-project#90]
Pretty lost as how to get the update method to work. Having trouble calling the id of the element I am trying to change so that what changes is registered to the correct piece of data.

**Comment by gaand** [comment]
client or api?
Conventionally, the id goes in the url.  The updated attributes in the body of the request (the `data` key in the ajax config object).

**Comment by baz1389** [comment]
Client side. I have this so far:

```
updateWord: function (id, data, token, callback) {
    this.ajax({
      method: 'PATCH',
      url: this.mwb + '/words/' + id,
      headers: {
        Authorization: 'Token token=' + token
      },
      contentType: 'application/json; charset=utf-8',
      data: JSON.stringify(data),
      dataType: 'json'
    }, callback);
  }
```

```
 $('#buttonUpdate').on('click', function(e) {
    e.preventDefault();
    $('.col-lg-12').hide();
    $('#createNew').show();
    var id =
    var token = user.token;
    mwbapi.updateWord(id, data, token, function(err, data) {
      if (err) {
        console.error(err);
        return;
      }
      console.log(data);
    });
    e.preventDefault();

    // var updateWord = $('#word').text();
    // var updateDefinition = $('#definition').text();
    // var updateSentence = $('#sentence').text();
    // $('#exampleWordInput').text(updateWord);
    // debugger;
  });
```

**Comment by gaand** [comment]
Are you saving the words in a list of some kind?  You probably need to store the word id in the items in that list so you can grab them for the update.

**Comment by baz1389** [comment]
I mean, when a word is created it has the the id that is automatically assigned to it (which can be accessed with the index route). I am able to search/query a word by the word name (but no other parameter) if that helps at all.

**Comment by gaand** [comment]
I mean you need the id on the front end if your going to update that record on the backend.

**Comment by baz1389** [comment]
I guess I'm not quite sure how to do that then.

I looked at my logout function since that is the only other method that calls an id (albeit a different id), but I don't think I can call the word_id like I did user.id
