### ISSUE TITLE
rails api .env file question

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/full-stack-project#900]
I want to git to ignore the .env file. Tried googling and looking at git documentation with no luck. What is the syntax for git ignore filename?

**Comment by BenGitsCode** [comment]
What have you tried googling?

**Comment by BenGitsCode** [comment]
For instance, that last sentence miiiight be perfect ;)

**Comment by MarcyNash** [comment]
I have been googling 'What is the syntax for git ignore filename' :-)  I keep ending up in the gitignore documentation which tells me to set a pattern in the gitignore file. I did this a while ago and don't think I had to edit the gitignore file.

**Comment by BenGitsCode** [comment]
How do you know that git isn't ignoring your `.env`? Is it being tracked by git?

**Comment by MarcyNash** [comment]
Edited .gitignore file and uncommented. I thought there was a command line syntax, but don't really have the time now to find it (or not find it as the case may be :)
