### ISSUE TITLE
Help With Rails Authentication

### ISSUE THREAD

**Issue by constaac** [ga-wdi-boston/full-stack-project#901]
I currently have two tables for my project: Users and Players. There is a one-to-many relationship between them, with users having many players. I don't want other users to be able to modify players that aren't associated with their user account. I set up the players controller to inherit from ProtectedController, and now every CRUD action requires an authentication token which is okay.

Tokens don't seem to be specific to a user, so I'm trying to figure out how to use current_user in the players controller. I can't figure out a way to put/console log what current user is, but I assume its a hash of the user entry). 

I'm struggling with incorporating current_user into the players controller so that a user may only modify players with that user's id. I logged in with "user 1", got a key, and then used the key to create a player attached to "User 2". I'm also able to update and delete that player with the wrong account. 

I added "include Authorization" to my players model, just as it is in the User model.

I am thinking I need to make if statements for the beginning of the player actions along these lines: 
 if User.find(player_params[:id]) is equal to current_player[:id]

I see current user being defined in the application controller, which I am basically inheriting from, but I don't understand how it is being defined exactly - and really how I can use it in this situation.

Any help would be greatly appreciated!

**Comment by constaac** [comment]
Player Controller:

```
class PlayersController < ProtectedController
  before_action :set_player, only: [:show, :update, :destroy]

  # GET /players
  def index
    @players = Player.all

    render json: @players
  end

  # GET /players/1
  def show
    render json: @player
  end

  # POST /players
  def create
    @player = Player.new(create_player_params)

    if @player.save
      render json: @player, status: :created, location: @player
    else
      render json: @player.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /players/1
  def update
    if @player.update(player_params)
      render json: @player
    else
      render json: @player.errors, status: :unprocessable_entity
    end
  end

  # DELETE /players/1
  def destroy
    @player.destroy
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def player_params
      params.require(:player).permit(:name, :vpip, :pfr, :"3b", :f3b, :number_hands, :user_id)
    end

    def create_player_params
      params.require(:player).permit(:name, :user_id)
    end
end
```

**Comment by danman01** [comment]
>I added "include Authorization" to my players model, just as it is in the User model.

You don't need this, as Authorization model is only for the User class so it has methods to authenticate. 

>I am thinking I need to make if statements for the beginning of the player actions along these lines:
if User.find(player_params[:id]) is equal to current_player[:id]

This is along the correct path of verifying the user who is signed in (`current_user`) is the one who owns the player. So when a player is created, they have a `user_id` associated with them. The `current_user` object is created from the `ApplicationController`, and that oject has as `user_id`. If the `current_user.id` matches that of the player which you're working with, then you know that current_user is the owner of that player.

Take a look at how `ExamplesController` sets the current example, and how it uses `current_user` when setting up the `@example` in the before_filter.

**Comment by constaac** [comment]
I've got it working so that update and such won't work on a player that doesn't belong to a user, but index is still returning all users. I had to inherit from OpenReadController instead, and fix the set player method to:
```
def set_player
      @player = current_user.players.find(params[:id])
end
```
I figure I need to use 
```@players = Player.where()```
but I can't figure out how to retrieve the id of the current user.

**Comment by constaac** [comment]
Got it! It was simply, current_user.id.
