### ISSUE TITLE
500 error for POST ('create') curl request.

### ISSUE THREAD

**Issue by RoryEnright** [ga-wdi-boston/full-stack-project#902]
curls for sign-up and sign-in are working, I thought I would try creating a reminder, getting a 500 back.  belongs_to is undefined? 

{"status":500,"error":"Internal Server Error","exception":"#\u003cNoMethodError: undefined method `belongs_to' for Reminder:Class\u003e","traces":{"Application Trace":[{"id":0,"trace":"app/models/reminder.rb:3:in `\u003cclass:Reminder\u003e'"},{"id":1,"trace":"app/models/reminder.rb:2:in `\u003ctop (required)\u003e'"},{"id":33,"trace":"app/controllers/reminders_controller.rb:46:in `set_reminder'"}],"Framework Trace":[{"id":2,"trace":"activesupport (5.0.1) lib/active_support/dependencies.rb:477:in `load'"},{"id":3,"trace":"activesupport (5.0.1) lib/active_support/dependencies.rb:477:in `block in load_file'"},{"id":4,"trace":"activesupport (5.0.1) lib/active_support/dependencies.rb:662:in `new_constants_in'"},{"id":5,"trace":"activesupport (5.0.1) lib/active_support/dependencies.rb:476:in `load_file'"},{"id":6,"t, etc, etc

I've tried messing around with class inheritence, validation, belongs_to
controller:
```rb
class RemindersController < OpenReadController
  before_action :set_reminder, only: [:show, :update, :destroy, :create]

  # GET /reminders
  def index
    @reminders = Reminder.all

    render json: @reminders
  end

  # GET /reminders/1
  def show
    render json: Reminder.find(params[:id])
  end

  # POST /reminders
  def create
    @reminder = current_user.reminders.build(reminder_params)

    if @reminder.save
      render json: @reminder, status: :created, location: @reminder
    else
      render json: @reminder.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /reminders/1
  def update
    if @reminder.update(reminder_params)
      head :no_content
      # render json: @reminder
    else
      render json: @reminder.errors, status: :unprocessable_entity
    end
  end

  # DELETE /reminders/1
  def destroy
    @reminder.destroy

    head :no_content
  end

  def set_reminder
    @reminder = current_user.reminders.find(params[:id])
  end
  #  Use callbacks to share common setup or constraints between actions.
  #  Only allow a trusted parameter "white list" through.

  def reminder_params
    params.require(:reminder).permit(:content, :day, :when)
  end

  private :set_reminder, :reminder_params
end
```
Model
```rb
# frozen_string_literal: true
class Reminder < OpenReadController
  belongs_to :user, inverse_of: :reminders
  validates :content, :day, :when, :user, presence: true
end
```
Curl
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/reminders"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=BAhJIiVjMjBmZDA2N2MwZWM3OTFiNTI1OWM5YzYyZmQ1ZGIzNgY6BkVG--dea90fe7842f5b10b81df8584ae6459ddc000dee" \  (token is updated whenever I sign-in)
  --data '{
    "reminder": {
      "content": "This is a test",
      "day": "2017-06-08",
      "when": "12:00"
    }
  }'
```
Schema for create Reminders table
```  create_table "reminders", force: :cascade do |t|
    t.string   "content",    null: false
    t.date     "day"
    t.time     "when"
    t.integer  "user_id",    null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_reminders_on_user_id", using: :btree
  end
```
routes
```
Rails.application.routes.draw do
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
  resources :reminders
end
```

**Comment by jordanallain** [comment]
do you have any pending migrations? have you compared how you set up the relationship to how we did it during the lesson?

**Comment by RoryEnright** [comment]
No pending migrations.  Switched the model to inherit from ApplicationRecord.  Now I'm receiving a 404 not found when running my create CURL script. I've tried closing and restarting the server a few times.

HTTP/1.1 404 Not Found
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: ba880f89-31da-4adc-a261-6fa2c8816324
X-Runtime: 0.003174
Vary: Origin
Transfer-Encoding: chunked

**Comment by jordanallain** [comment]
is your server giving you any errors?

**Comment by RoryEnright** [comment]
Started POST "/reminders" for 127.0.0.1 at 2017-06-09 09:44:57 -0400
Processing by RemindersController#create as */*
  Parameters: {"reminder"=>{"content"=>"This is a test", "day"=>"2017-06-08", "when"=>"12:00"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "c91afdb52f167d862b2d1bc94452d8ab"], ["LIMIT", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.06ms)
Completed 404 Not Found in 2ms (Views: 0.3ms | ActiveRecord: 0.3ms)

**Comment by jordanallain** [comment]
can you post your reminder serializer?

**Comment by RoryEnright** [comment]
class ReminderSerializer < ActiveModel::Serializer
  attributes :id, :content, :day, :when, :editable

  def editable
    scope == object.user
  end
end

**Comment by jordanallain** [comment]
```
# frozen_string_literal: true
class Reminder < OpenReadController
  belongs_to :user, inverse_of: :reminders
  validates :content, :day, :when, :user, presence: true
end
```
why did you add this line?
  `validates :content, :day, :when, :user, presence: true`

**Comment by jordanallain** [comment]
hold up...check out this line

` before_action :set_reminder, only: [:show, :update, :destroy, :create]`

anything in there seem wrong to you?

**Comment by jordanallain** [comment]
compare that line from your controller to the examples controller

**Comment by RoryEnright** [comment]
Yup, that was the issue.    Switched it to ```before_action :set_reminder, only: [:update, :destroy]```

the line ```validates :content, :day, :when, :user, presence: true``` is also included in the example model, thought it was something we had to include.

**Comment by jordanallain** [comment]
Nice, @RoryEnright can you close this now?
