### ISSUE TITLE
Unable to add new beer via ajax call

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/full-stack-project#904]
I'm unable to post a new beer via an ajax call that is populate with data from a client side form. 

The user enters all the required data to create a new form except for the user_id. I am attempting to supply the user_id in the ajax call (it's stored in store for the user's login). This may be the wrong approach, perhaps there's another way for the back-end to know the current user's id?

What I've been trying is to store the data from the form fields before making the ajax call, then include that stored data in the call, along with the user_id. 

This is the code for the ajax call, and a screenshot showing where I've console logged data and store just before the call is made.

```js
const addBeer = function (data) {
  store.newBeer = data
  console.log('store.newBeer is', store.newBeer)
  console.log('data is', data)
  return $.ajax({
    url: config.apiOrigin + '/beers',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.userToken
    },
    data: {
      'beer': {
        'name': store.newBeer.beer.name,
        'brand': store.newBeer.beer.brand,
        'style': store.newBeer.beer.style,
        'alc': store.newBeer.beer.alc,
        'price': store.newBeer.beer.price,
        'user_id': store.id}
    }
  })
  // .then((response) => {
  // })
}
```
<img width="1145" alt="screen shot 2017-06-08 at 10 49 00 pm" src="https://git.generalassemb.ly/storage/user/6318/files/4d367d9a-4c9d-11e7-9a10-95aad0080f91">

**Comment by jordanallain** [comment]
rails will know the id of the signed in user if you use current_user like how i showed you in the examples controller

**Comment by artpylon** [comment]
Ah yes, updated my beers controller based on examples file, removed the user_id from the request, and now it works:

```rb
  def create
    @beer = current_user.beers.build(beer_params)

    if @beer.save
      render json: @beer, status: :created, location: @beer
    else
      render json: @beer.errors, status: :unprocessable_entity
    end
  end
```
