### ISSUE TITLE
api create function is not working 

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/full-stack-project#905]
my curl scripts are also not working

''{"status":500,"error":"Internal Server Error","exception":"#\u003cNoMethodError: undefined method `cars' for #\u003cUser:0x007fc330efc8b0\u003e\u003e","traces":{"Application Trace":[{"id":1,"trace":"app/controllers/cars_controller.rb:19:in `create'"}],"Framework Trace":[{"id":0,"trace":"activemodel (5.0.1) lib/active_model/attribute_methods.rb:433:in `method_missing'"},{"id":2,"trace":"actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'"},{"id":3,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'"},{"id":4,"trace":"actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'"},{"id":5,"trace":"actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'"},{"id":6,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'"},{"id":7,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'"},{"id":8,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'"},{"id":9,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'"},{"id":10,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'"},{"id":11,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":12,"trace":"actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'"},{"id":13,"trace":"actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'"},{"id":14,"trace":"actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'"},{"id":15,"trace":"activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'"},{"id":16,"trace":"activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'"},{"id":17,"trace":"activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'"},{"id":18,"trace":"actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'"},{"id":19,"trace":"actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'"},{"id":20,"trace":"activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'"},{"id":21,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'"},{"id":22,"trace":"actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'"},{"id":23,"trace":"actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'"},{"id":24,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'"},{"id":25,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'"},{"id":26,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'"},{"id":27,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'"},{"id":28,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'"},{"id":29,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'"},{"id":30,"trace":"rack (2.0.1) lib/rack/etag.rb:25:in `call'"},{"id":31,"trace":"rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'"},{"id":32,"trace":"rack (2.0.1) lib/rack/head.rb:12:in `call'"},{"id":33,"trace":"activerecord (5.0.1) lib/active_record/migration.rb:553:in `call'"},{"id":34,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'"},{"id":35,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'"},{"id":36,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'"},{"id":37,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":38,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'"},{"id":39,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":40,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"},{"id":41,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'"},{"id":42,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":43,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'"},{"id":44,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'"},{"id":45,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'"},{"id":46,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'"},{"id":47,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'"},{"id":48,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'"},{"id":49,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'"},{"id":50,"trace":"rack (2.0.1) lib/rack/runtime.rb:22:in `call'"},{"id":51,"trace":"activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"},{"id":52,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":53,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'"},{"id":54,"trace":"rack (2.0.1) lib/rack/sendfile.rb:111:in `call'"},{"id":55,"trace":"rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'"},{"id":56,"trace":"railties (5.0.1) lib/rails/engine.rb:522:in `call'"},{"id":57,"trace":"puma (3.7.0) lib/puma/configuration.rb:226:in `call'"},{"id":58,"trace":"puma (3.7.0) lib/puma/server.rb:578:in `handle_request'"},{"id":59,"trace":"puma (3.7.0) lib/puma/server.rb:415:in `process_client'"},{"id":60,"trace":"puma (3.7.0) lib/puma/server.rb:275:in `block in run'"},{"id":61,"trace":"puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'"}],"Full Trace":[{"id":0,"trace":"activemodel (5.0.1) lib/active_model/attribute_methods.rb:433:in `method_missing'"},{"id":1,"trace":"app/controllers/cars_controller.rb:19:in `create'"},{"id":2,"trace":"actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'"},{"id":3,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'"},{"id":4,"trace":"actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'"},{"id":5,"trace":"actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'"},{"id":6,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'"},{"id":7,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'"},{"id":8,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'"},{"id":9,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'"},{"id":10,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'"},{"id":11,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":12,"trace":"actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'"},{"id":13,"trace":"actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'"},{"id":14,"trace":"actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'"},{"id":15,"trace":"activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'"},{"id":16,"trace":"activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'"},{"id":17,"trace":"activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'"},{"id":18,"trace":"actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'"},{"id":19,"trace":"actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'"},{"id":20,"trace":"activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'"},{"id":21,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'"},{"id":22,"trace":"actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'"},{"id":23,"trace":"actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'"},{"id":24,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'"},{"id":25,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'"},{"id":26,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'"},{"id":27,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'"},{"id":28,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'"},{"id":29,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'"},{"id":30,"trace":"rack (2.0.1) lib/rack/etag.rb:25:in `call'"},{"id":31,"trace":"rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'"},{"id":32,"trace":"rack (2.0.1) lib/rack/head.rb:12:in `call'"},{"id":33,"trace":"activerecord (5.0.1) lib/active_record/migration.rb:553:in `call'"},{"id":34,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'"},{"id":35,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'"},{"id":36,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'"},{"id":37,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":38,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'"},{"id":39,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":40,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"},{"id":41,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'"},{"id":42,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":43,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'"},{"id":44,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'"},{"id":45,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'"},{"id":46,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'"},{"id":47,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'"},{"id":48,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'"},{"id":49,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'"},{"id":50,"trace":"rack (2.0.1) lib/rack/runtime.rb:22:in `call'"},{"id":51,"trace":"activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"},{"id":52,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":53,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'"},{"id":54,"trace":"rack (2.0.1) lib/rack/sendfile.rb:111:in `call'"},{"id":55,"trace":"rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'"},{"id":56,"trace":"railties (5.0.1) lib/rails/engine.rb:522:in `call'"},{"id":57,"trace":"puma (3.7.0) lib/puma/configuration.rb:226:in `call'"},{"id":58,"trace":"puma (3.7.0) lib/puma/server.rb:578:in `handle_request'"},{"id":59,"trace":"puma (3.7.0) lib/puma/server.rb:415:in `process_client'"},{"id":60,"trace":"puma (3.7.0) lib/puma/server.rb:275:in `block in run'"},{"id":61,"trace":"puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'"}]}}

**Comment by jordanallain** [comment]
can you paste in the curl script you are trying to run?

**Comment by isharma-sharma** [comment]
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/cars"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Authorization: Token token=$TOKEN" \
  --header "Content-Type: application/json" \
  --data '{
    "car": {
      "model": "mercury",
      "color": "red",
      "lcp": "up80",
      "repair": "change"
    }
  }'

**Comment by jordanallain** [comment]
do you have a route and controller action set up to handle this?

**Comment by isharma-sharma** [comment]
this is my controller

````
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/cars"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Authorization: Token token=$TOKEN" \
  --header "Content-Type: application/json" \
  --data '{
    "car": {
      "model": "mercury",
      "color": "red",
      "lcp": "up80",
      "repair": "change"
    }
  }'

**Comment by isharma-sharma** [comment]
sorry

```


class CarsController < OpenReadController
  before_action :set_car, only: [:update, :destroy]

  # GET /cars
  def index
    @current_user_id = current_user.id
    @car = Car.where(user_id: @current_user_id)

    render json: @cars
  end

  # GET /cars/1
  def show
    render json: @car
  end

  # POST /cars
  def create
    @car = current_user.cars.build(car_params)

    if @car.save
      render json: @car, status: :created, location: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cars/1
  def update
    if @car.update(car_params)
      render json: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end

  # DELETE /cars/1
  def destroy
    @car.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def car_params
      params.require(:car).permit(:user_id, :model, :color, :lcp, :repair)
    end
end

**Comment by isharma-sharma** [comment]
my route is
```
  resources :cars,  except: [:new, :edit]
```

my models car.rb
````
class Car < ApplicationRecord
  belongs_to :user
  validates :text, :user, presence: true
end
````

**Comment by jordanallain** [comment]
i would remove the :user_id from the car_params method because you are not passing it in in the request

**Comment by isharma-sharma** [comment]
i did that still not working

**Comment by jordanallain** [comment]
when you run the script, is there any output on your server logs?

**Comment by isharma-sharma** [comment]
output of server
`````
Started POST "/cars" for 127.0.0.1 at 2017-06-09 10:59:14 -0400
Processing by CarsController#create as */*
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "d3de555cd1072a79db0aa12db61370f1"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 7ms (ActiveRecord: 0.5ms)


  
NoMethodError (undefined method `cars' for #<User:0x007fc331893748>):
  
app/controllers/cars_controller.rb:19:in `create

**Comment by jordanallain** [comment]
do you have the relationship set up in your models?

**Comment by isharma-sharma** [comment]
class Car < ApplicationRecord
  belongs_to :user
  validates :text, :user, presence: true
end

# frozen_string_literal: true
class User < ApplicationRecord
  include Authentication
  has_many :examples
  has_many :cars
end
 i just set up my User model now the error is 400 error
```
  
ActionController::ParameterMissing (param is missing or the value is empty: car):
  
app/controllers/cars_controller.rb:50:in `car_params'
app/controllers/cars_controller.rb:19:in `create'

**Comment by isharma-sharma** [comment]
then i added the :user_id still the same error

**Comment by isharma-sharma** [comment]
how much more time i have to work on the same create function

**Comment by jordanallain** [comment]
added :user_id to what? if you changed something can you paste the new version of your code and the new error?

**Comment by isharma-sharma** [comment]
error 
````
ActionController::ParameterMissing (param is missing or the value is empty: car):
  
app/controllers/cars_controller.rb:50:in `car_params'
app/controllers/cars_controller.rb:19:in `create'

'```
and the car controller
````
class CarsController < OpenReadController
  before_action :set_car, only: [:update, :destroy]

  # GET /cars
  def index
    @current_user_id = current_user.id
    @car = Car.where(user_id: @current_user_id)

    render json: @cars
  end

  # GET /cars/1
  def show
    render json: @car
  end

  # POST /cars
  def create
    @car = current_user.cars.build(car_params)

    if @car.save
      render json: @car, status: :created, location: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cars/1
  def update
    if @car.update(car_params)
      render json: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end

  # DELETE /cars/1
  def destroy
    @car.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = current_user.cars.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def car_params
      params.require(:car).permit(:user_id,:model, :color, :lcp, :repair)
    end
end

**Comment by jordanallain** [comment]
why do you have `@CAR` sometimes and `@car` other times?

**Comment by isharma-sharma** [comment]
i didnt get you

**Comment by isharma-sharma** [comment]
it is @car 
```
class CarsController < OpenReadController
  before_action :set_car, only: [:update, :destroy]

  # GET /cars
  def index
    @current_user_id = current_user.id
    @car = Car.where(user_id: @current_user_id)

    render json: @cars
  end

  # GET /cars/1
  def show
    render json: @car
  end

  # POST /cars
  def create
    @car = current_user.cars.build(car_params)

    if @car.save
      render json: @car, status: :created, location: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cars/1
  def update
    if @car.update(car_params)
      render json: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end

  # DELETE /cars/1
  def destroy
    @car.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = current_user.cars.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def car_params
      params.require(:car).permit(:user_id,:model, :color, :lcp, :repair)
    end
end

**Comment by isharma-sharma** [comment]
it is @car small c

**Comment by isharma-sharma** [comment]
i dont know why its coming in capital

**Comment by jordanallain** [comment]
oh okay must be a weird thing about Github markdown...lets meet in the kitchen for a 1on1

**Comment by isharma-sharma** [comment]
ok

**Comment by jordanallain** [comment]
looks like it was a combination of things being right/wrong in multiple places so fixing one thing but not changing the old thing back was confusing the issue.

we realized that we were using an outdated token in the curl script as well as accidentally commenting out the data we were trying to send in the ajax request.
