### ISSUE TITLE
Unique Entries by user_id

### ISSUE THREAD

**Issue by constaac** [ga-wdi-boston/full-stack-project#906]
Currently, I have two tables - users and players - where users has many players. Player names are not unique, and can have multiple entries with the same name. I know how to make the name column unique, but issues arise when the entire column is unique by name. If user a makes a player named bob, no other users can make a player named bob. 

I can't find the documentation to make the column name unique, but only by user_id. Any guidance here would be appreciated!

I have a feeling it has to do with putting a validates helper in the player method - something like:
```validates_uniqueness_of :name, :scope => :user_id```

**Comment by jordanallain** [comment]
check out `validates_uniqueness_of`, and combining it with `scope:`

**Comment by constaac** [comment]
I edited my post once I found that, but hadn't tried it.

It works! Thanks
