### ISSUE TITLE
Sign-up reloading

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#907]
Hi,
Trying to get sign-up to work and it just reloads.  i have event.preventdefault() in the code but its still reloads.
```js
const onSignUp = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  event.preventDefault()
  api.signUp(data)
    .then(ui.signUpSuccess)
    .catch(ui.fail)
}
```

**Comment by jordanallain** [comment]
do you have an event handler set up for the button?

**Comment by ghost** [comment]
Yes,
```
const addHandlers = () => {
  $('#sign-up').on('submit', onSignUp)
```js

**Comment by ghost** [comment]
Think problem is index.js will try to fix and report back

**Comment by jordanallain** [comment]
are you calling addHandlers in the document ready function?

**Comment by ghost** [comment]
"Fixed" it, problem was index.js was not set up properly with authEvents
