### ISSUE TITLE
heroku error?

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#908]
Getting this error on sign-up

XMLHttpRequest cannot load https://safe-tundra-54607.herokuapp.com/sign-up/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:7165' is therefore not allowed access.

Don't know where to fix issue

**Comment by lisawilliams** [comment]
You're trying to send requests to your Heroku instance from your localhost server. 
You need to send them from rothenbg.github.io/your-front-end-repo

**Comment by lisawilliams** [comment]
I made a checklist of how I start, run & push changes to my local app and my public app here: 
https://github.com/lisawilliams/auto-mom-front/blob/master/checklist.md#starting-local--public-apps--pushing-changes-to-them

**Comment by ghost** [comment]
Where do we edit that?

**Comment by jordanallain** [comment]
do you have the deployed API url in your client repo?

**Comment by ghost** [comment]
Client repo as in the back-end?

**Comment by jordanallain** [comment]
no 

client = front end

**Comment by ghost** [comment]
sorry, yes
```
const config = {
  apiOrigins: {
    development: 'https://safe-tundra-54607.herokuapp.com',
    production: 'https://ga-wdi-boston.herokuapp.com'
  }
```js

**Comment by scottyscripts** [comment]
@rothenbg Your deployed heroku app will be the url you use in production. Where are you going to send requests when you are doing development? Based on both of these, what will your new values be for `development` and `production`?

**Comment by ghost** [comment]
So change development to the localhost and make production the heroku?

**Comment by ghost** [comment]
So I changed the configs and got a 404 error
```
jquery.js:9566 POST http://localhost:7165/sign-up/ 404 (Not Found)
```
curl is 
```
curl "https://localhost:7165/sign-up/" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    \"credentials\": {
         \"email\": \"${EMAIL}\",
         \"password\": \"${PASSWORD}\",
         \"password_confirmation\": \"${PASSWORD}\"
       }
  }'
``` js
api is 
```

const signUp = function (data) {
  return $.ajax({
    url: config.apiOrigin.development + '/sign-up/',
    method: 'POST',
    data
  })
}
```js

**Comment by ghost** [comment]
so removed the '.development' in the api and got a different error:

jquery.js:9566 POST https://localhost:7165/sign-up/ net::ERR_CONNECTION_CLOSED

**Comment by scottyscripts** [comment]
Is your rails server running? Is it serving at `:7165`?

**Comment by ghost** [comment]
its serving at :4741

**Comment by ghost** [comment]
Issue solved, had wrong localhost server
