### ISSUE TITLE
Handlebar issue

### ISSUE THREAD

**Issue by gotwilk890** [ga-wdi-boston/full-stack-project#91]
Dissected problem comes out that I have a parsing error. Wondering if I could have someone take a look at it as to what I'm doing wrong.

**Comment by GA-MEB** [comment]
I'm sorry, I don't understand. What is the error? Your Handlebars template isn't compiling properly?

**Comment by gotwilk890** [comment]
could be that. Its saying that I have a parsing error and chrome console stops in the handlebars CDN

**Comment by gaand** [comment]
Post the template code here inside a pair of triple back-ticks please.

**Comment by gotwilk890** [comment]
```
<script id="guide-show" type="text/x-handlebars-template">
  {{#each guides}}
  <div class="col-md-6 col-sm-12 col-xs-12 icon-box">
    <div class="col-md-2 col-sm-2 col-xs-12">
      <div class="iconing">
        <i class="glyphicon glyphicon-pencil"></i>
      </div>
    </div>
    <div class="col-md-9 col-md-offset-1 col-sm-10 col-xs-12 icon-text-box">
                <h4>{{name}}</h4>
    </div>
  </div>
</script> 
```

**Comment by GA-MEB** [comment]
You didn't close your `{{#each}}`. It needs to end in `{{/each}}`

**Comment by gotwilk890** [comment]
You're a saint!!
