### ISSUE TITLE
Submitting form refreshes page, prevent default is in place

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/full-stack-project#910]
I have an update beer form that is appended to a list of the user's beers with handlebars when they click update beer button. 

When the user submits the update beer form, the page refreshes. 

I am setting a click handler on the update beer form after it is appended to the page in the ui function. 

 This click handlers calls the onUpdateBeer function in my events.js file, this function contains the event.preventDefault method. 

Open  update beer form
```js
const openBeerForm = function (event) {
  let updateBeerFormHtml = beerFormTemplate()
  $(event.target).append(updateBeerFormHtml)
  $('#updateBeer').on('submit', events.onUpdateBeer)
}
```
update beer form in handlebars
```handlebars

<form id="updateBeer" data-id="{{beer.id}}">
  <fieldset>

    <label>Name</label>
    <input type="text" name="[beer][name]" placeholder="Name">

    <label>Brand</label>
    <input type="text" name="[beer][brand]" placeholder="Brand">

    <label>Style</label>
    <input type="text" name="[beer][style]" placeholder="Style">

    <label>Alc Content</label>
    <input type="number" name="[beer][alc]" placeholder="Alc Content">

    <label>Price</label>
    <input type="number" name="[beer][price]" placeholder="Price">

    <input type="submit" class="button" name="submit" value="Update Beer">
  </fieldset>
</form>
```

updateBeer function:

```js
const onUpdateBeer = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  api.updateBeer(data)
    .then(ui.updateBeerSuccess)
    .catch(ui.updateBeerFailure)
}
```
<img width="850" alt="screen shot 2017-06-09 at 11 29 20 am" src="https://git.generalassemb.ly/storage/user/6318/files/ee2553ca-4d06-11e7-80c3-33e04060d5ab">

**Comment by scottyscripts** [comment]
If you put a console.log in onUpdateBeer does it log in the console? Is this function being invoked?

**Comment by artpylon** [comment]
I moved the onUpdateBeer function into the ui file and now I have new error with the corresponding update ajax call, so I fixed it!
