### ISSUE TITLE
Problems with serializer/multiple migrations

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/full-stack-project#912]
OK, I just generated and ran a migration: 
`rails generate migration AddUserToChore user:belongs_to`

When I go to http://localhost:4741/chores, I get the following error: 

```
// 20170609124220
// http://localhost:4741/chores

{
  "status": 500,
  "error": "Internal Server Error",
  "exception": "#<ActiveRecord::PendingMigrationError: \n\nMigrations are pending. To resolve this issue, run:\n\n        bin/rails db:migrate RAILS_ENV=development\n\n>",
```

Since it says migrations pending, I run the following at the command line: 

`bin/rails db:migrate`

Now I have two migration files called AddUserToChore, and when I try to rollback, I get the following error: 

```
$ bin/rake db:rollback
Running via Spring preloader in process 72719
rake aborted!
ActiveRecord::DuplicateMigrationNameError: 

Multiple migrations have the name AddUserToChore.

-e:1:in `<main>'
Tasks: TOP => db:rollback
(See full trace by running task with --trace)
```

**Comment by danman01** [comment]
You could just delete one, if they both have the same code, and one hasn't been ran. Go into your `db/migrations` folder, and take a look at the files there. No harm in deleting migrations if you do not want to run them. If they have already ran, you will want to either rollback the migration or create a new migration which makes the changes you need.

**Comment by lisawilliams** [comment]
I just checked the schema_migrations table and I did run it, unfortunately. 

When I do bin/rake db:rollback, I get the following error. I can't roll back because both the migrations have the same name. 

```
$ bin/rake db:rollback
Running via Spring preloader in process 73529
rake aborted!
ActiveRecord::DuplicateMigrationNameError: 

Multiple migrations have the name AddUserToChore.

-e:1:in `<main>'
Tasks: TOP => db:rollback
(See full trace by running task with --trace)
~/wdi/projects/auto-mom/auto-mom-back (development)

```

**Comment by jordanallain** [comment]
are both migrations the same?

**Comment by lisawilliams** [comment]
Yes! I just checked.  The only thing that is different is the timestamp.

**Comment by lisawilliams** [comment]
And I checked the database this migration affects, and there are no changes. This migration adds a foreign key to the 'chores' table to have a place to put a user ID.

**Comment by lisawilliams** [comment]
There's still only one user_id column, no new unexpected columns, records, or tables.

**Comment by scottyscripts** [comment]
@lisawilliams How is this issue going? Status update for today?

**Comment by danman01** [comment]
@lisawilliams can this issue be closed? Thanks!

**Comment by lisawilliams** [comment]
Oh hey! Yes, I can close this.  
Here's what fixed it:  I generated two migration files, then after deleting one, Rails was looking for the one I deleted. So we had to do some Git machinations to get the old file back in place. Once we did that, it worked.
