### ISSUE TITLE
ActiveRecord find_or_create_by!() generates a linter error

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/full-stack-project#917]
The following generates a `unexpected end of input, expecting ')'` linter error starting at `symbol…` line:
`manu = Manufacturer.find_or_create_by!(
  name: 'Linotype',
  symbol: 'Δ'
)`

But this generates no linter error:
`  mat = Matrix.find_or_create_by!(
    code_prefix: row['prefix'],
    code_suffix: row['suffix']
  )`

http://api.rubyonrails.org/classes/ActiveRecord/Base.html says that dynamic attribute-based finders of this form should be correct; e.g.,
`Person.find_by(user_name: user_name, password: password)`
 So, what's wrong here?

**Comment by EricLScace** [comment]
Despite the linter error, the code executes successfully. So WTF‽

**Comment by MicFin** [comment]
Maybe it doesn't like Δ ?

**Comment by scottyscripts** [comment]
Does it throw an error if you use another character for `symbol`? Is it finding the correct / creating the entry with expected values?

Sometimes the linter doesn't know what to do, it's true...if this is working fine and no longer an issue, go ahead and close it please.

**Comment by danman01** [comment]
@EricLScace can this issue be closed? Thanks!

**Comment by EricLScace** [comment]
It appears to be fussiness over Unicode character sets. A Greek upper-case delta works. A math symbol of "increment" does not work. Not a show-stopper.
