### ISSUE TITLE
Need help finishing an on-click function for my honey list

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/full-stack-project#92]
Heres what I have so far:

```
$('.honey-content').on('click', function(e) {
    var $li = $(e.target);
    var id = $li.data('honey-id');
    console.log(id);
    $(".honey-content").append('<li data-honey-id="'+honey.id+'">' + honey.name + "</li>");
  }); 
```

**Comment by GA-MEB** [comment]
Is the `console.log` working correctly? Are you seeing the right id?

**Comment by GA-MEB** [comment]
Also, do you mean to be using `append()`, and not `html()`? In other words, are you adding on to the existing content of the `<li>`, or are you overwriting it?

**Comment by LaurisaNeuwirth** [comment]
I just want to add the new Honey to the list.

**Comment by LaurisaNeuwirth** [comment]
I just need to talk it through I think.

**Comment by gaand** [comment]
Please meet me in classroom 1.

**Comment by gaand** [comment]
I should have removed myself when I left for the day.
