### ISSUE TITLE
Handlebars: Add Event Handlers

### ISSUE THREAD

**Issue by slammyde7113** [ga-wdi-boston/full-stack-project#920]
SO I feel like I'm about to ask a question with a simple answer but It almost midnight and I'm tired.

After I append a button to the DOM using Handlebars, my button doesn't seem to work. I put a debugger in my code and I found out that the event connected to the button isn't being triggered. How do I attach an event handler to a newly added button when I use Handlebars?

**Comment by danman01** [comment]
Did you figure this out? It's all about adding the event handler when the element is actually available to the code adding the handling. If the element is not yet created / rendered, it may not have that click handler attached.

**Comment by slammyde7113** [comment]
all set. I added the handler as I was creating the element. thank you!
