### ISSUE TITLE
join tables with rails

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#922]
How do you join tables with rails? I have my has_many/belongs_to statements as well as an AddPeopleToCars statement with the foreign key.  I looked in the one-to-many repo but there is no Join table section.

**Comment by ghost** [comment]
Checked the schema and it shows
```t.integer  "people_id"```ruby
Does this mean the tables are joined?

**Comment by ghost** [comment]
Should clarify this is under "cars" table

**Comment by danman01** [comment]
What are you trying to accomplish by joining tables? Accessing a certain resource that belongs_to / has_many of another resource?

**Comment by danman01** [comment]
If you truly want to issue an SQL join statement, there is a way to do that: http://guides.rubyonrails.org/v3.2/active_record_querying.html#joining-tables

**Comment by ghost** [comment]
Ok, thank you I think the issue is resolved so I am closing it

**Comment by danman01** [comment]
Great, care to share what you found?
