### ISSUE TITLE
i m getting error on my localhost 4741 and the same on the heroku

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/full-stack-project#927]
````
{
"status": 500,
"error": "Internal Server Error"
}

**Comment by lisawilliams** [comment]
I also have this issue when I navigate to 

http://localhost:7165/chores/

error: `Cannot GET /chores/`

All my requests are working in my app tho so that's pretty confusing! :D

**Comment by danman01** [comment]
@isharma-sharma What url are you trying to access / what action in your application generates the 500 error?

@lisawilliams yours works fine locally but not deployed? Is the database up to date and did you push to heroku correctly? Does `heroku logs` tell you anything useful?

**Comment by lisawilliams** [comment]
@danman01 I'm actually getting that error locally -- yet everything works fine! ¯\_(ツ)_/¯ File under: Mysteries Of Code.

**Comment by isharma-sharma** [comment]
http://localhost:4741/cars

https://car-booking.herokuapp.com/cars

i deployed last night and also push heroku correctly  by this command
``
git push heroku master

**Comment by danman01** [comment]
can you paste those things you just told me? and format code blocks with three back tics ```

**Comment by isharma-sharma** [comment]
https://car-booking.herokuapp.com/cars

error
`````
{
"status": 500,
"error": "Internal Server Error"
}

http://localhost:4741/cars
error
````
{
"status": 500,
"error": "Internal Server Error",
"exception": "#<NoMethodError: undefined method `cars' for nil:NilClass>",
"traces": {
"Application Trace": [
{
"id": 0,
"trace": "app/controllers/cars_controller.rb:8:in `index'"
}
],
"Framework Trace": [
{
"id": 1,
"trace": "actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'"
},
{
"id": 2,
"trace": "actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'"
},
{
"id": 3,
"trace": "actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'"
},

**Comment by isharma-sharma** [comment]
and the thing iam getting in the console 
````
<!-----
2jquery.js:3860 jQuery.Deferred exception: Cannot read property 'cars' of undefined TypeError: Cannot read property 'cars' of undefined
    at http://localhost:7165/public/application.js:1728:28
    at mightThrow (http://localhost:7165/public/vendor.js:11500:30)
    at process (http://localhost:7165/public/vendor.js:11568:13) undefined
<---->

**Comment by danman01** [comment]
Ok this is something we can work with...just seeing the 500 error is very hard to debug, but when we get a file and line number and nicer error message, then that is helpful.

Which file and line in your rails app is the error coming from? What is the specific error (exception) your rails app is giving? And once you find that, what is the code in your app that generates that error?

**Comment by isharma-sharma** [comment]
i tried it again no error ion console

but on my rail server i m getting 
````
NoMethodError (undefined method `cars' for nil:NilClass):
```
is this the issue by which i . m getting 500 internal server error

**Comment by isharma-sharma** [comment]
Started GET "/cars" for 127.0.0.1 at 2017-06-12 11:21:10 -0400
Processing by CarsController#index as HTML
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)


  
NoMethodError (undefined method `cars' for nil:NilClass):
