### ISSUE TITLE
422 unprocessible entity

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#929]
Trying to create a car in the database from the front end and get a 422 unprocessible entity error.  The rails server directs me as such
```
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.11ms)
```
Serializer in Rails looks like

**Comment by ghost** [comment]
Serializer in Rails looks like
```
class CarSerializer < ActiveModel::Serializer
  attributes :id, :brand, :model
end
```rb

**Comment by danman01** [comment]
Where are you getting the 422 error, from the rails server console? Could you post  the error that the server is giving you Hopefully it will include a file and line number.

Also which piece of your code is responsible for calling the serializer? Could you post that as well?

**Comment by ghost** [comment]
Yes, 422 error is from rails.  Entire server says
```
Started POST "/cars/" for 127.0.0.1 at 2017-06-12 12:43:12 -0400
Processing by CarsController#create as */*
  Parameters: {"car"=>{"brand"=>"Lamborghini", "model"=>"Aventador"}, "submit"=>"Upload!"}
   (1.6ms)  BEGIN
   (0.2ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.16ms)
Completed 422 Unprocessable Entity in 44ms (Views: 4.8ms | ActiveRecord: 11.2ms)
```
Doesn't mention a line number

**Comment by ghost** [comment]
Here is the code for the controller
```
def create
    @car = Car.new(car_params)

    if @car.save
      render json: @car, status: :created, location: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end
```
ruby

**Comment by danman01** [comment]
So it looks like you are getting to your error condition of the `if / else`

Try using `binding.pry` after you set up `@car`, and investigate your `car_params`. Does `@car` look ok? if you call `.valid?` on car, does that come back as true? If not, call `.errors` to see any Active Record errors on the object. Can you manually save it via the `pry` repl? Is the problem with turning `@car` into JSON for your serializer?

**Comment by ghost** [comment]
Tried Car.save and it returns false, that is why it is failing.  I don't know much beyond that.

**Comment by ghost** [comment]
If I just do car.save by itself I get a NoMethodError ,

NoMethodError: undefined method `save' for Car (call 'Car.connection' to establish a connection):Class
from /Users/geoffreyrothenberg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/dynamic_matchers.rb:21:in `method_missing'

**Comment by danman01** [comment]
Alright, try using the instance variable instead of the class: `@car.save` and then, `@car.errors` to see what errors ActiveRecord has placed on your car object. Alternatively, just calling `.valid?` on an object (like `@car.valid?`) will return true / false and also put those errors on the object, so you can then do `@car.errors`

**Comment by ghost** [comment]
I am getting
```NoMethodError: undefined method `save' for nil:NilClass```
@car itself returns nil as a value.  Is this normal?

**Comment by danman01** [comment]
when you say **`@CAR`** are you reffering to `@car`?

**Comment by danman01** [comment]
If so, does this return nil as well? `Car.new(car_params)`

And, does `car_params` return the attributes you are expecting?

**Comment by ghost** [comment]
No, I get:
```NameError: undefined local variable or method `car_params' for main:Object```

**Comment by danman01** [comment]
Ok, so where does `car_params` usually come from (look at another working controller). Also, check out simply `params[:car]` and the much longer hash, `params`, to see what you've got in there.

**Comment by ghost** [comment]
Doesn't ```car_params```, at least the parameters themselves, come from the schema?

**Comment by ghost** [comment]
Alternatively,
 car_params comes from the controller itself

**Comment by danman01** [comment]
correct, `car_params` comes from the controller, and is simply a method which is used to ensure strong parameters are being used. It's based off of `params` which is a rails hash containing all sorts of things related to the incoming request, including data from form submissions and ajax requests.

**Comment by ghost** [comment]
So, I have a ```car_params``` in my Cars controller, I don't know why it is not working

**Comment by scottyscripts** [comment]
@rothenbg Any updates on this issue?

**Comment by danman01** [comment]
@rothenbg let's meet 1:1 to debug this. When is a good time for you?

**Comment by ghost** [comment]
Whenever you're good is fine

**Comment by ghost** [comment]
So i am going to close this issue for now, going to change it so cars belongs to the user instead of a separate database
