### ISSUE TITLE
include ActionView::Helpers ?

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/full-stack-project#932]
in a controller class I want to use a method from ActionView:Helpers. See <http://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html>

This did not work out of the box:
```
NoMethodError (undefined method `number_with_precision' for #<MatrixController:0x007f88a02f73f0>):
```
so I assumed the class lacked the helpers. I added an include:

```
class MatrixController < ProtectedController
  include ActionView::Helpers

```

The following generated a few hundred lines of error notifications in the back-end server... so many that I could not find the start.  Eventually I found what I think was the start of the error messages:
```
Started GET "/matrix" for 127.0.0.1 at 2017-06-12 13:28:41 -0400
  
Module::DelegationError (ActionView::Helpers::ControllerHelper#action_name delegated to controller.action_name, but controller is nil:
```

**Comment by danman01** [comment]
The ActionView::Helpers are available by default in views. In controllers, like you did, you may need to require them or do something special. Here's something I found on SO, and there may be another option...but give this a shot:

```
class MyClass
  include ActionView::Helpers::NumberHelper

  def my_method
    ...
    number_with_precision(number, precision: 2)
    ...
  end
end
```
source: https://stackoverflow.com/questions/6853015/how-do-i-use-an-actionviewhelper-in-a-ruby-script-outside-of-rails

**Comment by danman01** [comment]
Looks like this is more relevant to using helpers in controllers (check out user Grossers' answer and Gerry Shaw's): https://stackoverflow.com/questions/5130150/rails-how-to-use-a-helper-inside-a-controller

**Comment by MicFin** [comment]
I agree with Danny.  Avoid using Helper methods in your Model.

**Comment by EricLScace** [comment]
```
class MyClass
  include ActionView::Helpers::NumberHelper
```
worked fine
