### ISSUE TITLE
Cannot Initialize Modal Form Dialog For The Update Function

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/full-stack-project#935]
I am using a Bootstrap table to show all items. Each row has an Edit button that brings up the update form,. I first tried adding a handler when the Edit button is clicked. I have a console log to show that my click handler is being called prior to the form being displayed.. In Chrome's console I have tried to enter values but when the form displays, the fields are blank.

Thinking that this handler might be getting called to early, I consulted the Bootstrap documentation and added a handler for show.bs.modal as per the Bootstrap documentation. Unfortunately the result was the same. 

I tried googling and StackOverflow again with no luck. Any ideas would be much appreciated. Thanks!

**Comment by scottyscripts** [comment]
Can you please post the code for your event handler as well as the logic for updating input values on your form? If you are unable to update the values even in the chrome console, it is possible that the selectors for the inputs are incorrect.

**Comment by MarcyNash** [comment]
Event Handler for showing update modal and setting the breakpoints --

```
const onShowUpdateForm = function (event) {
  console.log('onShowUpdateForm')
  const recipeID = event.relatedTarget.parentNode.getAttribute('data-id')
  $('h4.modal-title').val('Update Recipe' + recipeID)
}

const onUpdateRecipe = function (event) {
  event.preventDefault()
  // $('#update-recipe').show()
  // const recipeID = event.currentTarget.parentNode.getAttribute('data-id')
  // $('#test').show()
  const data = getFormFields(event.target)
  api.update(data)
  .then((response) => {
  })
  .then(ui.onUpdateRecipeSuccess)
  .catch(ui.onUpdateRecipeFailure)
}
```

```
const addHandlers = () => {
  $('#add-recipe').on('submit', onCreateRecipe)
  $('#update-recipe').on('show.bs.modal', onShowUpdateForm)
  $('#show-my-recipes-btn').on('click', onGetRecipes)
  $('body').on('click', '.deleteRecipe', onDeleteRecipe)
  // $('body').on('click', '.editRecipe', onShowUpdateForm)
  $('#update-recipe').on('submit', onUpdateRecipe)
}

module.exports = {
  addHandlers,
  onShowUpdateForm,
  onUpdateRecipe,
  onCreateRecipe,
  onGetRecipes,
  onGetRecipe,
  onDeleteRecipe
}
```

Handlebars code to create the table and Edit button --

```{{#each recipes as |recipe|}}

  <tr data-id="{{recipe.id}}">
    <td data-id="{{recipe.id}}"><button id="editRecipe{{recipe.id}}" class="btn btn-default editRecipe" data-toggle="modal" data-target="#updateRecipe">Edit</button></td>
    <td data-id="{{recipe.id}}"><button id="deleteRecipe{{recipe.id}}" class="btn btn-default deleteRecipe">Delete</button></td>
    <td name="[recipe][name]">{{recipe.name}}</td>
    <td name="[recipe][location]">{{recipe.location}}</td>
    <td name="[recipe][comment]">{{recipe.comment}}</td>
  </tr>

{{/each}}
```

**Comment by MarcyNash** [comment]
Scott helped me / showed me how to correctly use jQuery to get values from the table and set the title and inputs in the modal dialog. 

Thank you!!!
