### ISSUE TITLE
cannot send images over GA-guest wifi

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/full-stack-project#939]
OK, this isn't specific to the project, but it is a general issue for students.

The GA-guest wiki network blocks transmission/reception of photos and PDFs over iMessage. Is there a reason for this? or is it an accidental fall-out from some other wi-fi policy?

**Comment by danman01** [comment]
Hmm not sure...we can bring this up to our IT people if it is an issue. Do you need this functionality for the project or something?

**Comment by EricLScace** [comment]
Not critical. Just something I keep stumbling across. My partner is a good outside tester for the deployed URL — if it works for her, then I know it's working for the general public. If she (or I) want to send a screen snapshot to clarify an issue, we can't unless I tether to my phone and pull it off GA-Guest ... which Apple then conveniently propagates to my laptop, so that my laptop forgets the GA-Guest wifi credentials.

It's just an annoyance. I can work around it. But maybe an IT person can check it out at her convenience. Thanks.

**Comment by danman01** [comment]
Alright, thanks for explaining why it's important to have that functionality. Will pass this on!

**Comment by danman01** [comment]
Hi @EricLScace, what’s your MAC address? We are going to dig into the issue further.

**Comment by EricLScace** [comment]
20:c9:d0:46:d8:ab for my laptop.
This isn't limited to one device. My phone can't send/receive images either: d8:06:95:0c:32:6d

**Comment by payne-chris-r** [comment]
This is not a full-stack-project issue.
