### ISSUE TITLE
Unable to curl 3rd-party API 

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/full-stack-project#940]
Hoping to get another pair of eyes on the documentation for a 3rd party API I'd like to use. 

Currently, attempting to curl to get a single brewery back:
http://www.brewerydb.com/developers/docs-endpoint/brewery_index

I can't find an email of how request data should be formatted in their documentation, but I also may not recognize how it was specified. 

```sh
curl "http://api.brewerydb.com/v2/breweries?key=dd09ca49543b01f22953eed07410b022" \
--include \
--request POST \
--header "Content-Type: application/json" \
--data '{
  "name": "Cambridge Brewing Company"
}'
```
This is the response:

HTTP/1.1 400 Bad Request
Content-Type: application/json
Date: Tue, 13 Jun 2017 14:42:34 GMT
Server: Apache/2.4.23 (Amazon) OpenSSL/1.0.1k-fips PHP/5.5.38
Vary: User-Agent
X-Powered-By: PHP/5.5.38
X-Ratelimit-Limit: 400
X-Ratelimit-Remaining: 400
Content-Length: 168
Connection: keep-alive

{"errorMessage":"The data passed to this method was invalid","invalidFields":{"name":{"isEmpty":"You must give a non-empty value for field 'name'"}},"status":"failure"}

**Comment by scottyscripts** [comment]
What type of request are you trying to make here? Are you sure it's the correct type?

**Comment by artpylon** [comment]
Danny pointed out the request type was wrong, should be GET. Also, needed to send the data as urlencoded instead of json. Here's the working request:

curl "http://api.brewerydb.com/v2/breweries?key=dd09ca49543b01f22953eed07410b022&name=Cambridge%20Brewing%20Company" \
--include \
--request GET \
--header "Content-Type: application/x-www-form-urlencoded"
