### ISSUE TITLE
assets/scripts/config.js

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/full-stack-project#941]
My notes are too sketchy and my tic-tac-toe isn't helping.

I've search around for the deployment instructions repo for the browser client (both on GA and in my own copies of the repos), and can't find anything that addresses how the config.js file should be set up. gh-pages-deployment-guide didn't help.

I remember there was a list of steps to perform to configure the GItHub settings and do some things (with grunt?) in order to deploy to production. Right now I have a lorem ipsum landing page at <https://ericlscace.github.io/All-the-Matrices-front-end/>.

The browser template contains:
```
const config = {
  apiOrigins: {
    production: 'https://ga-wdi-boston.herokuapp.com'
  }
}
```

My tic-tac-toe config.js contains:
```
const config = {
  apiOrigins: {
    development: 'http://tic-tac-toe.wdibos.com',
    production: 'https://aqueous-atoll-85096.herokuapp.com'
  }
}
```

I'm missing something to get the front-end deployed onto Heroku. Can you point me to that list?

**Comment by scottyscripts** [comment]
The browser template is configured to deploy to GHPages with the command `grunt deploy`. We will be hosting our client on GH-pages not heroku. However our API will be hosted on heroku. 

Config.js is just used to tell your client where it should be making requests. The value of `development` should be the url of your API when you are developing (localhost) and the value of `production` should be the url of where you are hosting your API (your heroku link)

**Comment by scottyscripts** [comment]
The `grunt deploy command` is specified in the repo for `browser-template` 
```
To deploy a browser-template based SPA, run grunt deploy.
``` 
https://git.generalassemb.ly/ga-wdi-boston/browser-template

**Comment by EricLScace** [comment]
OK thanks. My `grunt deploy` was working fine here <https://ericlscace.github.io/All-the-Matrices-front-end/> I was just wondering if the client side was to go onto Heroku as well.

Weren't there some GitHub repo config settings to be changed? Or did this all just seem more complex 2 weeks ago and now we're in the "yah, that should be easy" stage? Ha!

**Comment by danman01** [comment]
The client side needs to know about the backend API url, hence this config:

```
const config = {
  apiOrigins: {
    development: 'http://tic-tac-toe.wdibos.com',
    production: 'https://aqueous-atoll-85096.herokuapp.com'
  }
}
```

If `grunt deploy` is working fine, that is great! I think it was definitely more complicated 2 weeks ago :)
