### ISSUE TITLE
Ajax - 3rd party API - Unable to get form data into urlencoded request

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/full-stack-project#943]
I've created a form where a user can "search" for a beer by submitting the beer's name. 

When the form is submitted, an ajax request is submitted to the 3rd party brewerydb API. 

This API requires that the name of the beer be passed with the GET request and that the name be included in the request URL. This curl request works:

curl "http://api.brewerydb.com/v2/beers?key=dd09ca49543b01f22953eed07410b022&name=Big%20Man%20IPA" \
--include \
--request GET \
--header "Content-Type: application/x-www-form-urlencoded"

I have this for the ajax:

```js
const findBeer = function (data) {
  console.log(data)
  return $.ajax({
    url: 'http://api.brewerydb.com/v2/beers?key=dd09ca49543b01f22953eed07410b022&name=' + data,
    method: 'GET'
  })
}
```

This is the form where that data is entered:
```handlebars
<form id="findBeerForm">

  <div class="form-group">
    <label>Search by Name:</label>
    <input type="text" name="[name]" placeholder="Name" class="form-control name">
  </div>

  <input type="submit" class="button btn btn-default" name="submit">

</form>
```

**Comment by artpylon** [comment]
<img width="1195" alt="screen shot 2017-06-13 at 11 59 10 am" src="https://user-images.githubusercontent.com/26583372/27091959-bd5e5cba-502f-11e7-80ef-03a91970c7c7.png">

**Comment by scottyscripts** [comment]
When you console.log `data` in findBeer, is it a string like you are expecting it to be?

**Comment by danman01** [comment]
Take a look at the url in the error, looks like the name / data like Scott mentioned is not what you expect. Also, a CORS error from the API...do they allow access via AJAX? You may need to search their docs and see how they want AJAX requests sent. Might be different than curl.

**Comment by artpylon** [comment]
Interesting, so yes it sounds like you can't make ajax requests, per this in their forum:

"We don’t support cross-origin requests from the browser, so you’ll need to proxy your requests through a server-side script of some sort.  That’s why you get that error.  

Check out http://www.brewerydb.com/developers/docs-library for a number of pre-written service libraries that can help you interact with the API."

They apparently have a ruby gem, perhaps that's what I should use:
https://github.com/cmar/brewerydb
https://rubygems.org/gems/brewerydb

When you have time, could we talk at a high level about how I'd go about implementing this?

**Comment by danman01** [comment]
Sure, yes doing the call on the backend is an option. Also sometimes you can get away with using JSONP: https://www.sitepoint.com/jsonp-examples/

**Comment by artpylon** [comment]
Thanks!
