### ISSUE TITLE
Rails Backend .save isnt saving to the database

### ISSUE THREAD

**Issue by slammyde7113** [ga-wdi-boston/full-stack-project#944]
Here's my update request:
```
def update
      @profile.menu_item.price = 0
      @profile.save(validate: false)
      render json: @profile
    # else
    #   render json: @profile.errors, status: :unprocessable_entity
    # end
  end
```
But when I query the database to show all the profile elements, it returns the profile unchanged. Am I missing something with the .save function?

**Comment by scottyscripts** [comment]
Any reason you are not using active record methods to update your record? For example, `@profile.menu_item.update()`

**Comment by slammyde7113** [comment]
I tried like a million ways to get profile.update() to work and so far this is the only way I've been able to get a full PATCH request through. Honestly, i just want to figure out why the data isn't saving lol

**Comment by danman01** [comment]
This is a good place for the debugger.

```
def update
      binding.pry # <--- here's a good spot
      @profile.menu_item.price = 0
      @profile.save(validate: false)
      render json: @profile
    # else
    #   render json: @profile.errors, status: :unprocessable_entity
    # end
  end
```
And then try each line of code, line by line, in the pry debugger console.

Also, why validate: false?? Validations are good.

Call `@profile.errors` after attempting `.save()` to see what errors are generated on your object.

**Comment by slammyde7113** [comment]
```
def update
  #  binding.pry
      @profile.menu_item.price = 0
      @profile.menu_item.save(validate: true)
      render json: @profile
    # else
    #   render json: @profile.errors, status: :unprocessable_entity
    # end
  end
```
@profile doesnt have a price attribute so save wasn't doing anything. I had to specify where price was in order to change it.
