### ISSUE TITLE
Displaying an object's array

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#945]
So I am trying to display an array that is within an object on the front page but all I can display is "object Object", how do I display the actual information.  My code is:
```$('.text-box').text(data.cars)```jquery/js

**Comment by ghost** [comment]
Some clarification, it is an object within an array within an object that I want to display onscreen

**Comment by jordanallain** [comment]
so to clarify, `data` is an object?

`data.cars` is an array of objects?

**Comment by ghost** [comment]
yes, just console.logged it to confirm

**Comment by danman01** [comment]
Have you searched on Google for how to display an object's properties in javascript?

Accessing an array index should be pretty straightforward, and accessing the properties of the inner object gets a little more involved. At the end of the day, it's simply a key value store.

**Comment by ghost** [comment]
Looking right now will report back

**Comment by ghost** [comment]
Tried most array and object methods I could find, couldn't get it to return what I expect

**Comment by jordanallain** [comment]
what did you try?

remember we use dot notation to access properties of an object, and bracket notation to specify an index in an array.

and these can be combined to access nested data structures.

**Comment by ghost** [comment]
Primarily trying the .toString() method

**Comment by jordanallain** [comment]
what are you calling `.toString()` on? are you trying to turn the whole object into a string or are you trying to display one property of the object?

**Comment by ghost** [comment]
I am trying to turn each index element into a string then display it as text

**Comment by jordanallain** [comment]
But each element is an object, so I don't think calling toString on it will have the effect you want. Are you attempting to use handlebars at all?

**Comment by ghost** [comment]
No

**Comment by ghost** [comment]
I'm trying to figure out a way to reference all of the objects in the array at once

**Comment by ghost** [comment]
Issue solved, Scott helped me add handlebars and to reconfigure the template
