### ISSUE TITLE
User's chores still show after sign out

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/full-stack-project#948]
...and that's not good! 

I am trying to use my signOutSuccess function in ui.js to clear a user's chores after they sign out, but I'm not having a lot of luck. Have done much googling and reading of StackOverflow but have not found a solution. 

Here's the relevant HTML: 

```
<div class="container">
  <div class="row article">
  <div class="col-lg-12 col-md-12 col-sm-12col-xs-12">

      <h2>Show all chores</h2>
        <form id="show-chore">
          <fieldset>
          <input type ="submit" name="submit" value="Show all chores">
          </fieldset>
        </form>
        <br><br><br>

<!-- Using AJAX to return list of chores in the 'list' div -->
<!-- This returns the list of chores. chore-list.handlebars targets the "chore-list" div. -->
 <div id="chore-list">

           </div>

         </div>
       </div>
     </div>

```
I use Bootstrap to target `<div id="chore list">`.  When a user clicks Show Chores, Bootstrap iterates through each chore and does this with them: 

```
{{#each chores as |chore|}}

<div class="container">
<div class="row">
  <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
    <div class="thumbnail">
      <div class="caption">
<div id='chore-listing' data-id="{{chore.id}}">
  <!-- <p>Chore ID: {{chore.id}}</p> -->
  <p>{{chore.chore_name}}</p>
  <p>Chore ID: {{chore.id}}</p>
  <p>Directions: {{chore.directions}}</p>
  <p>Day of Week: {{chore.day_of_week}}</p>
</div>
</div>
</div>

```
Finally, here's the signOutSuccess function: 

``` 
const signOutSuccess = () => {
  console.log('signOut success ran. and nothing was returned')
  store.user = null
  // $('#signOutSuccessPrompt').text('You have signed out. See you soon!')
  console.log('Signout success prompt ran')

  $('#sign-out').on('submit', function () {
    $('chore-list').html('')

    return false
  })

  // $('sign-out').onSubmit(function () {
  //   $('thumbnail').html('')
  // })
  // document.getElementByID("chore-list").innerHTML = ""
  console.log('We are at the end of the signOutSuccess function')
}
```

I'm leaving in some commented-out stuff just to show other approaches I tried that did not work. 
When  I run this, the console.log statements at the beginning and end of the function appear in the console...but the one that reads `    $('chore-list').html('')` does not.

**Comment by lisawilliams** [comment]
cc @sdavidson140

**Comment by scottyscripts** [comment]
In jQuery when selecting ids, we also want to use `#` in our selector. So to get 
```
<div id="example"></div>
```
We could do `$('#example')`
So you want to make sure your are selecting by id correctly in your jQuery selector.
Also make sure that the id you are selecting matches that in your markup. I don't see any HTML with an id of `chore-list`

**Comment by lisawilliams** [comment]
#headdesk  :) Just leaving this open for a minute to see if I can get it working.

**Comment by lisawilliams** [comment]
Okay, so here's what worked.  I made a new div called 'chore-container' to wrap around all the chores. 
Then I realize, why do I need an .on('submit') function at all? The button/form has already been submitted.  So I trimmed it down to: 

```
const signOutSuccess = () => {
  console.log('signOut success ran. and nothing was returned')
  $('#chore-container').html('')
  console.log('clear content function ran')
  store.user = null
  console.log('We are at the end of the signOutSuccess function')
}
```
Oh and I put that pesky # where it's supposed to go, too!
