### ISSUE TITLE
Border around select box and field input dissappearing

### ISSUE THREAD

**Issue by constaac** [ga-wdi-boston/full-stack-project#949]
I have a modal that has a div at the bottom containing two rows. I have been trying to keep everything neat and functioning on an Iphone 6 screen. The two rows contain a dropdown (select) with a label tag, and then a text input box followed by a Load and Save button. 

When the window is "normal" size it looks fine, but as soon as the screen is iphone 6 size, the borders dissapear, and it becomes really hard to tell that a dropdown exists. I think it has something to do with the line height shrinking when it scales down, because when I add a blue boarder, I can see small bits of it. 

I have tried using a bootstrap plugin to circumvent the issue, increasing and decreasing the width of the select box, and putting them on the same row, with no success. I will paste my modal code, as well as two screenshots of the issue -> one at normal browser size and one at iphone 6 size. Thanks!

```<!-- Set Table Modal -->
  <div class="modal fade" id="tableModal" tabindex="-1" role="dialog" aria-labelledby="table">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="table-label">Set Total Number of Seats</h4>
        </div>
        <div class="modal-body">
          <ul class="pagination set-seat-number">
            <li><a type="button" class="btn" id="seat-button-2">2</a></li>
            <li><a type="button" class="btn" id="seat-button-3">3</a></li>
            <li><a type="button" class="btn" id="seat-button-4">4</a></li>
            <li><a type="button" class="btn" id="seat-button-5">5</a></li>
            <li><a type="button" class="btn" id="seat-button-6">6</a></li>
            <li><a type="button" class="btn" id="seat-button-7">7</a></li>
            <li><a type="button" class="btn" id="seat-button-8">8</a></li>
            <li><a type="button" class="btn" id="seat-button-9">9</a></li>
            <li><a type="button" class="btn" id="seat-button-10">10</a></li>
          </ul><br>
          <div id="seats-table" class="panel panel-default">

          </div>
          <div class="container-fluid">
              <div class="row">
                <label class="item-input item-select">
                  Seat Number:
                    <select>
                    <option selected>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>6</option>
                    <option>7</option>
                    <option>8</option>
                    <option>9</option>
                    <option>10</option>
                  </select>
                </label>
              </div>
              <div class="row">
                <div class="item-input-inset">
                  <label class="item-input-wrapper">
                    <input type="text" placeholder="Player Name">
                  </label>
                  <button class="btn btn-primary">
                    Save
                  </button>
                  <button class="btn btn-primary">
                    Load
                  </button>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>```

**Comment by constaac** [comment]
Normal Size - http://imgur.com/a/fe7vV
Iphone Size = http://imgur.com/a/0WyDO

**Comment by danman01** [comment]
You mean the seat numbers and Player Number borders disappear? Is that a feature of the iphone bootstrap styles, which make it function more like a phone interface? Do they assume you need to click to start typing, and therefore borders don't mesh well with their perceived iphone style? 

At any rate, you can use the chrome dev tools to inspect element on that specific element at that specific size, and hone in on the element which needs some tweaking. You may need to override bootstrap styles, so read up on how to do that, as well as media queries.

**Comment by constaac** [comment]
I'm not sure, I'm viewing it by using the dev tools to resize the browser to an iphone 6's  screen size. 

None of the checkboxes seem to do anything to affect it. I guess it's not a bug, just rather a bit confusing. The website idea is ideally used on an iphone, so I figured it should be apparent that the seat drop down is clearly something that can/should be modified.

**Comment by constaac** [comment]
You can see the difference in the two screenshots i linked via imgur

**Comment by danman01** [comment]
Are you able to target those elements and change the associated styles in the dev tools? Do you know how to override bootstrap styles + try out your own media queries? If so, are your customized styles taking affect?

**Comment by constaac** [comment]
I know how yes, and Im using dev tools to try to find a styling that is causing that effect, but can't seem to find it. I can set up a media query, but I'm not sure what property needs to be modified.

**Comment by Jcornmanhomonoff** [comment]
@constaac have you solved this issue yet?

**Comment by constaac** [comment]
There might be an issue with the way chrome inspector was displaying the site; when the window width is changed manually, the problem doesn't occur. 

Solved the problem by using col-4 classes instead of btn-group-justified.

Thanks!
