### ISSUE TITLE
Form input type="time" displaying with extra data ie. 2000-01-01T00:12:00.000Z

### ISSUE THREAD

**Issue by RoryEnright** [ga-wdi-boston/full-stack-project#950]
front end: form input type ="time"
Back end schema :
```
  create_table "reminders", force: :cascade do |t|
    t.string   "content",    null: false
    t.date     "day"
    t.time     "when"
    t.integer  "user_id",    null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_reminders_on_user_id", using: :btree
  end
```
Database table: 00:12:00 for 'when' column.
Somewhere the time formats are getting mixed and I'm not sure where.  Googling date/time format leads to all sorts of config files and such.  Not sure what's worth looking at, can anyone give me a direction?

https://stackoverflow.com/questions/3928275/in-ruby-on-rails-whats-the-difference-between-datetime-timestamp-time-and-da

http://www.jmp.com/support/help/Date-Time_Functions_and_Formats.shtml

**Comment by danman01** [comment]
What's your goal here? To display a form input that has a date and time selector?

Can you screenshot what is displayed currently, and then say what you'd like to change?

There are numerous helpers within Rails and javascript to format dates and times (with timezones) into nice looking strings.

**Comment by MicFin** [comment]
Date != Time in HTML or Rails

HTML 
https://www.w3schools.com/html/html_form_input_types.asp

Rails
http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_column

What are you actually trying to get from the user and save?
Date `June 13, 2017`?
Time `12:21:30`?
DateTime `June 13, 2017 12:21:30`?

Like @danman01 said, maybe you can just use a string if you aren't doing anything fancy (computations or comparisons) with the date.

**Comment by RoryEnright** [comment]
![screenshot from 2017-06-13 15-37-10](https://user-images.githubusercontent.com/28019155/27101051-3c99bcae-504e-11e7-9052-104322d9fdbe.png)

**Comment by RoryEnright** [comment]
Trying to get the user to save a date and time to go with their reminder. 'Date: June 13, 2017' would also be easier for the user to read.  Input field for time is handy, but that string is what gets saved.  I would like to save the time HH:mm AM/PM if possible.

**Comment by danman01** [comment]
Ok, so sounds like you need to format an ugly date / datetime string into a nice readable string. You are using javascript / handlebars on the front end to display this value retrieved from your API, I believe. Can you search Google for how to do that and let us know if you find something useful?

**Comment by RoryEnright** [comment]
So I redefined my :when attribute on the serializer to reformat the time being displayed client side.
```
# frozen_string_literal: true
class ReminderSerializer < ActiveModel::Serializer
  attributes :id, :content, :day, :when, :editable

  def editable
    scope == object.user
  end

  def when
    object.when.strftime('%I:%M %p')
  end
end
```
Ref: https://hackhands.com/format-datetime-ruby/ (thanks @sdavidson140 )
Now it only shows HH:mm AM/PM on a 12hr clock
