### ISSUE TITLE
Heroku isn't working

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#951]
When I open my heroku app to test the production server I get the following message:
```The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information.```

**Comment by jordanallain** [comment]
what did you do to get this message? what do you mean by open my heroku app?

**Comment by ghost** [comment]
I went to the heroku site, and on the dashboard clicked "open app". I get the message that it does not exist.

**Comment by jordanallain** [comment]
have you ran `git push heroku master` from your terminal at any point?

**Comment by ghost** [comment]
yes

**Comment by jordanallain** [comment]
have you run any heroku migrations that need to be run?

**Comment by ghost** [comment]
Possibly not, how do you run a heroku migration?

**Comment by jordanallain** [comment]
`heroku run rake db:migrate`

**Comment by jordanallain** [comment]
if it runs a migration you will likely need to `restart` your `heroku` app

**Comment by ghost** [comment]
Terminal blew up, got following error:
```
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column "people_id" of relation "cars" does not exist
```

**Comment by jordanallain** [comment]
cool looks like you need a column on your cars table

**Comment by ghost** [comment]
I joined the cars to a different table than people though

**Comment by danman01** [comment]
You currently have a migration somewhere in `db/migrations` that references `people_id`. Can you find that migration and edit it by hand? Because you no longer want to reference `people_id`, correct?

**Comment by ghost** [comment]
tried adding that column but I still get the same error

**Comment by ghost** [comment]
Do I need to push to heroku master before heroku migrationing

**Comment by jordanallain** [comment]
adding what column to what?

**Comment by ghost** [comment]
Adding ```people_id``` to ```cars```

**Comment by jordanallain** [comment]
do you want a `people_id` column in the cars table? you said earlier you had it joined to a different table.

**Comment by ghost** [comment]
Issue solved, migration wasn't accounted for and branches were misaligned because of it
