### ISSUE TITLE
500 Internal Server Error when I try to delete a recipe

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/full-stack-project#953]
Completed 500 Internal Server Error in 21ms (ActiveRecord: 0.6ms)
  
NoMethodError (undefined method `Recipe' for #<User:0x007fccbfc56a00>
Did you mean?  recipes
               recipes=):

app/controllers/recipes_controller.rb:47:in `set_recipe'

**Comment by jordanallain** [comment]
can you post the recipes_controller?

**Comment by danman01** [comment]
☝️ and this line specifically: `app/controllers/recipes_controller.rb:47:in `set_recipe'`

**Comment by MarcyNash** [comment]
set_recipe was not correct. Danny helped me compare the examples controller code with my recipe controller code to find the error.

Thanks!
