### ISSUE TITLE
can't get response from my local server?

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/full-stack-project#955]
sending a GET to the local server, which it never sees. Client receives a response that triggers the .catch callback ... with an object that has no HTML status codes, etc. 

Clearly missing a connection here. Not sure where to look.

**Comment by jordanallain** [comment]
is your server running? did you try to hit it with a curl request?

**Comment by EricLScace** [comment]
Server running. But curl script causes this error:
```
~/wdi/projects/All-the-Matrices-back (master)$ scripts/matrix-get.sh
curl: (7) Failed to connect to localhost port 4741: Connection refused

```
and then server stops.

This was working last night.

**Comment by EricLScace** [comment]
I have responses now... but not from GitHub and the Heroku page is still display no-site.

**Comment by EricLScace** [comment]
Thanks, as always.
