### ISSUE TITLE
linter complains about module.exports for no obvious reason

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/full-stack-project#956]
<img width="1070" alt="screen shot 2017-06-13 at 16 56 42" src="https://user-images.githubusercontent.com/6785602/27104198-66262d86-5059-11e7-97a5-b021d8b9bbb3.png">

**Comment by MicFin** [comment]
Maybe it doesn't like that there is a line 10 that is blank?

**Comment by benjimelito** [comment]
Has this been resolved?

**Comment by jordanallain** [comment]
@EricLScace think its safe to close this one now!
