### ISSUE TITLE
XMLHttpRequest cannot load https://safe-tundra-54607.herokuapp.com/sign-up/. No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#958]
When deployed I get the following error:

```XMLHttpRequest cannot load https://safe-tundra-54607.herokuapp.com/sign-up/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://rothenbg.github.io' is therefore not allowed access.```

What does this mean?

**Comment by MicFin** [comment]
From your Rails API folder, what does the command `heroku config` return?

**Comment by MicFin** [comment]
Also, take a look at these and see if they help:
#835
#518

**Comment by ghost** [comment]
Returns:
```=== safe-tundra-54607 Config Vars
DATABASE_URL:             postgres://jvldyzxkxonyvf:b8babf084eae649c9e6fa0c56c023cf457a2086fb07ab6ec6b024647dc94cbcc@ec2-107-20-186-238.compute-1.amazonaws.com:5432/d7f5uo4i17j6c5
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_LOG_TO_STDOUT:      enabled
RAILS_SERVE_STATIC_FILES: enabled
SECRET_KEY_BASE:          d120d7756880375621143c6d2a3f8c757b6f3657265836c9d6c469cedf2da8d2acbb5741fa900015b3fe5ad54b862c590b73e02735303e652ae4e65197cbf220``` I'll take a look at the other issues

**Comment by MicFin** [comment]
Did you complete all these steps?
https://git.generalassemb.ly/ga-wdi-boston/rails-heroku-setup-guide#set-your-secrets

**Comment by ghost** [comment]
Just set Client origin and it worked, do I need the other secrets?

**Comment by MicFin** [comment]
Yes those will be used with authentication.

**Comment by ghost** [comment]
OK, issue was resolved I did not have the heroku configured right, no Secret Keys or client origin
