### ISSUE TITLE
i am not getting the list . of cars when i signout and sign-in again without refreshing the page

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/full-stack-project#959]
```my ui file where i m invoking the function

const getAllCarsSuccess = (data) => {
  // $('.bleh').empty()
  if (data.cars.length === 0) {
    $('#success').show()
    $('#succmsg').text('no cars')
    // $('#succmsg').fadeout()
  } else {
    console.log(data)
    $('#tog').empty()
    const showcarsHtml = showCarsTemplate({ cars: data.cars })
    $('#alcr').html(showcarsHtml)
    $('#success').show()
    $('#error').hide()
    $('#succmsg').text('list of cars')
  }
 
}

**Comment by constaac** [comment]
What calls this function? Is it "on login"?

**Comment by isharma-sharma** [comment]
no i have a button which when clicks invokes the function
```code for get all cars```

const onGetAllCars = function (event) {
  event.preventDefault()
  // const data = getFormFields(event.target)
  api.getAllCars()
    .then(ui.getAllCarsSuccess)
    .catch(ui.getAllCarsFailure)
}

$('#allcars').on('click', onGetAllCars)

**Comment by constaac** [comment]
Is the console.log (in getAllCarsSuccess) firing when you click the get cars button? 

If so, what is the data?

**Comment by constaac** [comment]
Also, can you copy/paste the div containing where the stuff is being appended? 

The HTML stuff with the IDs of "tog" and "alcr"

**Comment by isharma-sharma** [comment]
my html
```
  <button id="allcars" class="btn btn-default" class="col-md-2"><span class="glyphicon glyphicon-ok"></span>CARS-LIST</button>
        <div id="alcr" class="col-md-6" class='msg'>
          <!--show button to show cars grid starts-->

        </div>

HandleBars````
```
{{#each cars as |car|}}
<div class="bleh">

<ul id='tog' data-id="{{car.id}}">
  <li><small>carId:{{car.id}}</small></li>
  <li><small>Model:{{car.model}}</small></li>
  <li><small>Color-of-car:{{car.color}}</small></li>
  <li><small>licence-plate-no:{{car.lcp}}</small></li>
  <li><small>Repair-needed:<span class = "rep">{{car.repair}}</span></small></li>
  <li><form class="updetail">
      <div class="form-group">
        <label for="rpnd">Change-Needed:</label>
        <input type="text" name="car[repair]" class="form-control" id="rep">
      </div>
          <button class ="update" type="submit" class="btn btn-info btn-block">Submit</button>
  </form></li>
  <li><button class="removebtn" class="btn btn-primary btn-block">Remove Cars list!</button></li>

</ul>
</div>
{{/each}}

**Comment by isharma-sharma** [comment]
if i refresh the page and then click the button i am able to see my list after clicking the button

**Comment by constaac** [comment]
but not when you sign out and back in right?

**Comment by constaac** [comment]
I don't see an HTML element with id="tog"

Looking at 
``` 
    console.log(data)
    $('#tog').empty()
    const showcarsHtml = showCarsTemplate({ cars: data.cars })
    $('#alcr').html(showcarsHtml)
```

I'm trying to figure out exactly what is being emptied

**Comment by isharma-sharma** [comment]
i dont have #tog in html this is my id in handle bar

{{#each cars as |car|}}
<div class="bleh">

<ul id='tog' data-id="{{car.id}}">
  <li><small>carId:{{car.id}}</small></li>
  <li><small>Model:{{car.model}}</small></li>
  <li><small>Color-of-car:{{car.color}}</small></li>
  <li><small>licence-plate-no:{{car.lcp}}</small></li>
  <li><small>Repair-needed:<span class = "rep">{{car.repair}}</span></small></li>
  <li><form class="updetail">
      <div class="form-group">
        <label for="rpnd">Change-Needed:</label>
        <input type="text" name="car[repair]" class="form-control" id="rep">
      </div>
          <button class ="update" type="submit" class="btn btn-info btn-block">Submit</button>
  </form></li>
  <li><button class="removebtn" class="btn btn-primary btn-block">Remove Cars list!</button></li>

</ul>
</div>
{{/each}}

**Comment by isharma-sharma** [comment]
i dont know why it is not showing in here in my handlebars

**Comment by constaac** [comment]
Is your code on your github up to date? Can I have the link? (For frontend and backend)

**Comment by isharma-sharma** [comment]
https://github.com/isharma-sharma/car-booking-front

**Comment by constaac** [comment]
back end as well

**Comment by isharma-sharma** [comment]
https://github.com/isharma-sharma/car-booking-back

**Comment by constaac** [comment]
Try adding  ```$('#allcars').hide()``` to your signOutSuccess function, 

The signin function has a JQuery show method that sets the CSS display value for the AllCars div to actually display. I couldn't track down exactly what was causing it, but when you signed out, both the Allcars and alc divs were being set to have a CSS display value of None (hiding both divs).

Without adding .hide to the signout, it seems the .show in your signin doesn't function how we were expecting it to. 

That fixes the issue with the Allcars div being hidden after logging out and back in, but the "alc" div within the allcars div still has the issue of being hidden after logging out/in. To fix that you might want to add something to your GetAllCars function that explicitly shows that "alc" div

Take a look at these changes to getAllCarsSuccess: 
```
const getAllCarsSuccess = (data) => {
  $('.bleh').empty()
  if (data.cars.length === 0) {
    $('#success').show()
    $('#succmsg').text('no cars')
    // $('#succmsg').fadeout()
  } else {
    console.log('made it to else statement')
    console.log(data)
    // $('.bleh').empty()
    const showcarsHtml = showCarsTemplate({ cars: data.cars })
    $('#alcr').show()
    $('#alcr').empty()
    $('#alcr').append(showcarsHtml)
    $('#success').show()
    $('#error').hide()
    $('#succmsg').text('list of cars')
  }
  // <!-- have uncommented because it shows on when their  is no cars in the list -->
}
```

We used the .append method with handle bars in class, I'm not sure if I have the best explanation for you as to why, but instead of .html changing the html text within the div, .append just adds "DOM children" to the div. 

It was hard to track down what exactly was going on. I tend to use 

```$('#mydiv').css('display', '<block/inline or none>'```

to explicitly set how the div is displaying.

**Comment by constaac** [comment]
I used google chrome's dev tools to target the div that displays the cars list. Once you target that div, you can see when it has and doesn't have the display: none characteristic. Check it out, somehow, signing out assigns the display: none to both divs. You can see when the divs are and aren't displaying.

Luckily it seems like a display(show/hide) issue, your handlebars was working as expected! Thumbs up to that!

**Comment by isharma-sharma** [comment]
when
