### ISSUE TITLE
Github compare says two branches are the same. How can they be acting differently?!

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/full-stack-project#960]
Hi, all: 

I've been working on a feature branch to create a cycle of show/hide actions to respond to the following feedback on my full stack project: 

```

Must not have any obvious user-facing errors.
All buttons and links perform expected user action.
All user and crud actions present on landing page, none can be used before signing in.
No error messaging when trying to interact with chores before logging in.

```
So I was able to fix these on my feature branch, which is called hide-show-alt. When I got everything working, I committed and pushed the changes to hide-show-alt, then did `git checkout deploy`. I use the deploy branch as a staging area to clean up things like commented-out code or console log statements before merging deploy into master. While on the deploy branch, I run `git merge hide-show-alt`. 

Github now shows no difference between these two branches ([see the comparison here](https://github.com/lisawilliams/auto-mom-front/compare/deploy...hide-show-alt)). 

However, when I switch to the deploy branch and run it on localhost, the deploy and hide-show-alt branches have different behavior! In particular, while hide-show-alt shows the user a sign up and sign out box when they log out, deploy shows nothing, which means after one user logs out the next user cannot log in. 

HOW CAN THIS BE!? 

Thank you!

**Comment by lisawilliams** [comment]
(I have not pushed these branches live, because, well, they're broken! I don't want to merge deploy into master if deploy is not working; I don't push to the public facing site/servers until it is).

**Comment by lisawilliams** [comment]
Oh also: if I check out into hide-show-alt, it works. Check out deploy, doesn't work.

**Comment by BenGitsCode** [comment]
Are both branches pushed up to the remote?

**Comment by BenGitsCode** [comment]
If i clone your repository, fetch the branches, checkout to `hide-show-alt` and run `git diff deploy` I get the following diff.

```diff
diff --git a/assets/scripts/auth/ui.js b/assets/scripts/auth/ui.js
index 403f858..eb33ca2 100644
--- a/assets/scripts/auth/ui.js
+++ b/assets/scripts/auth/ui.js
@@ -48,12 +48,6 @@ const onSignInSuccess = (response) => {
   $('#sign-up-wrapper').addClass('hidden')
   $('#sign-in-wrapper').addClass('hidden')
   $('#usermessages').text('You are signed in. Get ready to have organized chores!')
-  $('.create-chore-box').show()
-  $('.delete-chore-box').show()
-  $('.update-chore-box').show()
-  $('#show-chore-button').show()
-  $('.sign-up-box').hide()
-  $('.sign-in-box').hide()
 }

 const onSignInFailure = (response) => {
@@ -93,9 +87,6 @@ const signOutSuccess = () => {
   $('#sign-up-wrapper').removeClass('hidden')
   $('#sign-in-wrapper').removeClass('hidden')
   $('#usermessages').text('You are signed out. Thanks for visiting! Text your mama :)')
-  $('.create-chore-box').hide()
-  $('.delete-chore-box').hide()
-  $('.update-chore-box').hide()
 }

 const signOutFailure = (error) => {
diff --git a/assets/scripts/chores/api.js b/assets/scripts/chores/api.js
index 07ade2d..5b29847 100644
--- a/assets/scripts/chores/api.js
+++ b/assets/scripts/chores/api.js
@@ -52,6 +52,9 @@ const updateChore = function (choreObject, choreNumber) {

 // API DELETE, deletes a selected chore

+// This briefly had a method of GET, and it worked, so adapting it
+// may work for a GET for a single chore. Nota bene.
+
 const deleteChore = (id) => {
   return $.ajax({
     url: config.apiOrigin + '/chores/' + id,
diff --git a/assets/scripts/templates/chore-list.handlebars b/assets/scripts/templates/chore-list.handlebars
index f890f27..a9cbe0b 100644
--- a/assets/scripts/templates/chore-list.handlebars
+++ b/assets/scripts/templates/chore-list.handlebars
@@ -2,7 +2,6 @@
 {{#each chores as |chore|}}

 <div class="container">
-  <!-- change back to row below -->
 <div class="row">
   <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
     <div class="thumbnail">
```

**Comment by lisawilliams** [comment]
@BenGitsCode THANK YOU SO MUCH! I really thought I was losing my mind!  Closing issue.

**Comment by BenGitsCode** [comment]
¯\_(ツ)_/¯
