### ISSUE TITLE
schema.rb not updating

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#962]
So I had a migration that I wanted to destroyed using ```rails d migration AddPeopleIdtoCars``` I ran the command as well as the db:migrate commandbut my schema.rb file is not updating.  It still shows 
```create_table "cars", force: :cascade do |t|
    t.string   "brand"
    t.string   "model"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
    t.integer  "people_id"
    t.index ["user_id"], name: "index_cars_on_user_id", using: :btree
  end```

My terminal seems to have short-circuited the migration it ran the spring preloader but only partially
as in ```Running via Spring preloader in process 7147``` and nothing else.  What is wrong?

**Comment by jordanallain** [comment]
why did you want to destroy a migration?

**Comment by ghost** [comment]
It was extraneous code that I added by accident

**Comment by jordanallain** [comment]
what was extraneous? could you have made a new migration to remove the code?

**Comment by ghost** [comment]
```AddPeopleIdToCars```Migration was extraneous, added by accident.  Should've done what you suggested but didn't

**Comment by jordanallain** [comment]
did you migrate the AddPeopleToCars migration? if so, can you rollback to before it was migrated?

**Comment by ghost** [comment]
I'll try it when I get the chance and report back.  Thanks

**Comment by ghost** [comment]
Had some troubles but fixed issue.  Generated a RemovePeopleIdFromCars migration which updated the schema
