### ISSUE TITLE
1:1

### ISSUE THREAD

**Issue by jbculbertson** [ga-wdi-boston/full-stack-project#964]
Hi - I'd love to have a 1:1 to discuss the resources for my project. Below is my current ERD, user stories and wireframes.

ERD - currently, in addition to users, I only have one resource, recipes, containing a string of ingredients that the recipe contains. I want to make ingredients their own resource, but I'd love to talk it through first.

USER STORIES
As a user, I want to be able to:
// auth features
: create an account with a name, username and password
: be able to login to view my account
: be able to change my password
: be able to logout

// recipe board
: be able to add my favorite recipes to my account, with properties of (name, ingredients, written directions, link, pic)
: be able to click on specific ingredients in a recipe to add them to a grocery list
: be able to click on specific recipe to add them to a menu list
: be able to edit an existing recipe
: be able to view other peoples recipes?

// menu list
:be able to see all of the meals I’ve selected for this week
:be able to see all of the meals I’ve selected for next week?

// on my grocery list
: be able to checkoff items from my grocery list once purchased
: be able to reorganize items on my grocery list
: be able to view my grocery list by itself
: be able to add other ingredients to the grocery list as well

WIREFRAMES:
https://wwwjeffculbertsoncom.mybalsamiq.com/projects/whatsfordinner/prototype/New%20mockup%202?key=238cebe745b787702f175cc9c329aa838949de62
https://wwwjeffculbertsoncom.mybalsamiq.com/projects/whatsfordinner/prototype/New%20mockup?key=238cebe745b787702f175cc9c329aa838949de62

**Comment by tvcrawley** [comment]
@jbculbertson Please close this issue if all concerns were satisfactorily addressed.
