### ISSUE TITLE
1:1 please!

### ISSUE THREAD

**Issue by jillrizley** [ga-wdi-boston/full-stack-project#965]
I am planning on doing a db of concerts at a venue, including the artists, dates, start and end times of the shows. I also want to be able to join together user and the show list to create a 'my shows' list that only the user can access. I am not exactly sure what this project is supposed to look like? I assume the sign up/sign portion to be similar to tic-tac-toe, but unsure about the rest! Also not exactly sure my ERD is correct.

potential wireframe: https://wireframe.cc/0NpiaF

ERD idea
User ---My Shows---<Shows

user stories

As a user, I want to be able to login to my account
As a potential user, I want to be able to sign-up and have it log me in at the same time.
-As a user, I want to be able to look for a show based on a specific date
-As a user, I want to be able to see the full list of shows in the database
-As a user, I want to be able to save my favorite shows

**Comment by jordanallain** [comment]
@jillrizley wanna update with the new ERD and close this issue!

**Comment by jillrizley** [comment]
updated ERD to user>---<shows through a user_shows join table
