### ISSUE TITLE
1:1

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/full-stack-project#966]
If possible, it would be great to have a brief 1 on 1 with a consultant to go over my movie list idea.

Items to discuss: project scope and Users as a rails object/table

Wireframe: https://wireframe.cc/FLjXMr

User stories:

As a user, I want to be able to login to see my list.
As a user, I want to be able to change my password.
As a user, I want to be able to log-out.
As a potential user, I want to be able to sign-up and have it log me in at the same time.
As a user, I want to be able to create a new list.
As a user, I want to be able to add more movies to my list
As a user, I want to be able to change the order of my list.
As a user, I want to be able to export my list or send it to someone via social media or text.
ERD: I believe the ERD is a straightforward one - to - many with Users "has_many" lists and lists "belong_to" User.

**Comment by tvcrawley** [comment]
@CoreyFedde Please close this issue if all concerns were satisfactorily addressed.
