### ISSUE TITLE
Franklin's ERD, user stories, and wireframes

### ISSUE THREAD

**Issue by Fcarrion001** [ga-wdi-boston/full-stack-project#967]
USER STORIES
--------
1. As a user, I want to use a budget calculator, so that I have a better
   understanding of my finances.

2. As a user, I want to be able to save my work, so that I can reference it at
   a later date.

3. As a user, I want to be able to change my password and sign out so that I can
   keep my personal information secure.
--------

ERD DIAGRAM
--------
http://imgur.com/IvpntHC
--------

WIREFRAME
--------
http://imgur.com/fb0UYx8
--------

**Comment by jordanallain** [comment]
@Fcarrion001 wanna close this issue if you're set with this?
