### ISSUE TITLE
1:1 Pls !!

### ISSUE THREAD

**Issue by Azinck94** [ga-wdi-boston/full-stack-project#968]
ERD:
imgur link => http://imgur.com/a/a5gPH

Wireframes:
imgur link => http://imgur.com/a/TqZM1

0- I want to create an informational database to store and display request information regarding my definitive top 25 NBA players. 1- As a user I want to be able to find the shoe preferences and shooting percentages of NBA players. 2- As a user I want to be able to find the brand name of the shoe that any given NBA player wears. 3- As a user I want to be able to find the color of the shoe that a given NBA player wears 4- As a user I want to be able to find the shoe preferences/ demographics of each NBA team. 5- As a user I want to be able to find how different shoe attributes relate to shooting percentages across the league.

**Comment by jordanallain** [comment]
If you're all set you can close thise @Azinck94 !

**Comment by jordanallain** [comment]
paging doctor @Azinck94
