### ISSUE TITLE
1:1

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/full-stack-project#969]
I am ready for my 1:1.

Tables: http://imgur.com/V2JVNyq
ERD: http://imgur.com/rIIA2if
Wireframe: http://imgur.com/mpHPj4D

User Stories:
As a new user, I want to be able to quickly see and understand what the site offers as soon as I arrive on the homepage so I can know whether I want to sign up.
As a new user, I want to be able to quickly and easily make a new account once I've decided that I want to use the service.
As a returning user, I want to be able to see the most relevant information from my account upon logging in, including most recent games played.
As a frequent user, I want to be able to quickly update information without needing to jump through a bunch of menus and forms.

**Comment by tvcrawley** [comment]
@bradleyden Please close this issue if all concerns were satisfactorily addressed.
