### ISSUE TITLE
1:1

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/full-stack-project#971]
Hello!

Here is my idea: An app that allows users to plan a beach day based on factors such as how long of a drive the beach is from the city, water conditions, and whether there are amenities like bathrooms, etc. Users can create entries for beaches, modify, delete, or view entries based on the criteria they choose.

User stories:
- The user should be able to find beaches that are less than an hour outside of boston.
- The user should be able to find beaches with calm waters (as opposed to good surf).
- The user should be able to add an entry for a beach.
- The user should be able to delete an entry for a beach.
- The user should be able to log in and out.

Wireframe: https://wireframe.cc/9VcsNy

ERD: https://wireframe.cc/Ok1u9P

I think there are issues with my ERD, but not sure.

**Comment by jordanallain** [comment]
If you're all set here can you close this @jingrid ?
