### ISSUE TITLE
1:1

### ISSUE THREAD

**Issue by mak1323** [ga-wdi-boston/full-stack-project#972]
I'm looking to start my one to one. The following are my user stories, erd, and wireframe. Model is to come after I have tested my front end logics. 

DESCRIPTION

I want to make a toolset for writers, gamers, and educators in order to help facilitate the creative process. The idea behind this project is to make this an ongoing piece. The first tool in this writer's toolbox is the name generator.

Have you ever been playing a game and sat there staring at a screen or character sheet thinking "What the hell should I name this?" Maybe it was a starship, a pirate ship, a bar, restaurant. Heck maybe you just couldn't think of a password?  (https://xkcd.com/936/)

This is for naming ships, taverns, bars, etc. This follows the logic all great ships and bars follow a logic as follows:
The Millennium Falcon
The Barking Crab
The Black Dog
The Lost Fox
The Hairy Monk (This is a real place, look: https://img.buzzfeed.com/buzzfeed-static/static/enhanced/webdr05/2013/8/5/12/enhanced-buzz-11133-1375719715-10.jpg?downsize=715:*&output-format=auto&output-quality=auto )
etc

So it follows this logic

“The”+ verb || adjective || adverb + Noun

So in theory I can make a database of each of these and then generate a random name according to the pulling of parameters from each.

USER STORIES
Name generator User Stories

-I want to generate a name according to noun themes (animal, avian, food, etc)
-I want to save my names
-I want to add a comment to my generated name telling me later what ideas I could use this for. 
-I want to edit my comments once I have made them.
-I want to delete names that I realize are not what I want.
-I want to see all my names and comments.

Reach goal:
-I want to be able to export my names and comments.

SCHEDULE
day one and two
https://photos.app.goo.gl/txxpdBR9TqmpN7D52
day three and four
https://photos.app.goo.gl/OEVS0FNs3140FeZF3

WIREFRAME
homepage
https://photos.app.goo.gl/9qb4h1meCGtDAoZI3
name generator
https://photos.app.goo.gl/f2G1Qa4xg6RmCw1h1

ERD (and some logic)
https://photos.app.goo.gl/INRqxyhkbVfqta7r2

**Comment by tvcrawley** [comment]
@mak1323 Please close this issue if all concerns were satisfactorily addressed.
