### ISSUE TITLE
Question with Generate Scaffold for a Join Table

### ISSUE THREAD

**Issue by kailinc** [ga-wdi-boston/full-stack-project#973]
I am trying to make a join table for Shoes and Collections. The idea is that shoes can be in many collections. Collections can have many shoes. I was thinking of using a join table for this purpose. 
I typed the command and it is giving me an error to use shoes

Command I typed
```ruby 
bin/rails generate scaffold shoe:references collection:references
```

Error/Warning I got 
```terminal 
[WARNING] The model name 'shoe:references' was recognized as a plural,
 using the singular 'shoe:reference' instead. Override with --force-plural or 
setup custom inflection rules for this noun before running the generator.
```

Should I use "bin/rails generate scaffold shoes:references collections:references" instead?

**Comment by jordanallain** [comment]
sounds like its worth a shot!

**Comment by kailinc** [comment]
Solved! I forgot to include a table name. I used the command of 

```git
bin/rails generate scaffold shoe_collection_rel shoe:references collection:references
```
