### ISSUE TITLE
POST request not going through

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/full-stack-project#974]
Trying to run a POST request, keep getting 400 Bad Request.

Here is my controller code for create:
`def create
    @beach = Beach.new(beach_params)

    if @beach.save
      render json: @beach, status: :created, location: @beach
    else
      render json: @beach.errors, status: :unprocessable_entity
    end
  end`

Routes code:
`  resources :beaches, except: [:new, :edit]`

sh file:
`API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/beaches"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  # --header "Authorization: Token token=$TOKEN" \
  --data '{
    "beach": {
      "name": "'"${TEXT}"'",
      "address": "'"${TEXT}"'",
      "drive_time": "'"${TEXT}"'",
      "water_condition": "'"${TEXT}"'",
      "amenities": "'"${TEXT}"'"
    }
  }'

echo`

What I ran in bash:

`NAME="Crane Beach" ADDRESS="444 beach st" DRIVE_TIME="1 hr" WATER_CONDITION="calm" AMENITIES="bathrooms" sh scripts/create-beach.sh`

pls help! thx u

**Comment by jordanallain** [comment]
Did you successfully sign in first?

**Comment by jingrid** [comment]
no, I haven't done any of the sign in/out stuff.

I commented out the token part, but I just uncommented it and now it works!
