### ISSUE TITLE
production url for front end heroku

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/full-stack-project#976]
I have heroku set up
I have front end and back end repos set up 
for front end config, where can I find the heroku url for production? 
I checked heroku settings for my app and looked in config vars 
I know I don't have to worry about this right now but I'm opening the issue so I don't forget down the road

**Comment by jordanallain** [comment]
in your back end repo, from the terminal, what happens when you enter `heroku open` ?

**Comment by ryanwk** [comment]
it brings me to my apps heroku url and displays 
The page you were looking for doesn't exist.
which is a good thing right?

**Comment by ryanwk** [comment]
so would I just use the url it directs me to as the production url?
