### ISSUE TITLE
getFormFields

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/full-stack-project#977]
I'm setting up my front end for user Auth actions (sign-up, sign-in, etc).
I'm using the tic-tac-toe game as a reference. 
what is getFormFields? I want to get the same functionality I had with tic-tac-toe but I'm having trouble understanding how getFormFields got user data. When a user clicks the sign-up,  button I need to pass the data on to the signIn function that governs the ajax POST request.
```js
$(() => {
  $('#sign-up-form').on('submit', function (e) {
    // const data = getFormFields(this)
    e.preventDefault()
    signUp.onSignUp(data)
  })
  $('#sign-in-form').on('submit', function (e) {
    // const data = getFormFields(this)
    e.preventDefault()
    signIn.onSignIn(data)
  })
  $('#sign-out').on('click', function (e) {
    e.preventDefault()
    signOut.onSignOut()
  })
  $('#saveExerciseData').on('click', function (e) {
    e.preventDefault()
    saveExerciseData.onSaveExerciseData()
  })
})
```
so data is POSTed to the server and then I need to GET it somehow. I'm studying the rails-api docs and tic-tac-toe api docs to understand how to implement this process. Should I create a get-form-fields.js module within the front end of my app? I don't understand how the back end and front end work with this data together. 

I guess I don't fully understand how the front-end and back-end work together to achieve the following (from rails-api docs):
A user interacts with a front-end application, triggering a POST, and this POST request contains data - specifically, the latest measurements of height and weight.
When the POST request is received by the server, the API app parses the request and extracts the relevant information.
The data from the POST request gets added to our records.
As confirmation, a JSON with a unique identifier (so we can refer to this specific measurement in the future) gets sent to the front end.
Something on the front-end (probably driven by user interaction) triggers a GET request that asks for a specific record.
When the GET request is received by the server, the API app parses the request and identifies which measurement record is being requested.
The data for the desired measurement gets retrieved from our set of records.
Finally, the desired data gets put into a JSON and sent back to the front end.

**Comment by jordanallain** [comment]
getFormFields is a function that grabs data from a form. it uses the name attribute to turn the data into a javascript object. you can check out the file in the lib directory.

**Comment by ryanwk** [comment]
OK, I've determined that I will copy the getFormFields from the tic-tac-toe lib directory and use it with my front end. This will allow me to get the text from the sign-in/sign-up fields and pass it to my patch/post requests. So now I can send data to the back-end.

**Comment by jordanallain** [comment]
did you use browser-template to start your project? getFormFields is included you shouldn't need to bring it over.

**Comment by jordanallain** [comment]
@ryanwk any updates on this? the file should already be there you will just need to require it in whatever file you are trying to use it in.

**Comment by ryanwk** [comment]
yep, got it. Thank you!
