### ISSUE TITLE
one on one

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/full-stack-project#979]
Ready for my initial one on one to discuss my project.

User stories:
![groovy movie user stories](https://user-images.githubusercontent.com/28842407/28465330-57c44efc-6df6-11e7-832a-35bc62930037.png)

Wireframes:
![ibzevs3](https://user-images.githubusercontent.com/28842407/28465344-628b82b0-6df6-11e7-98c6-7caec5b32bf8.jpg)

ERD: 
![img_1228](https://user-images.githubusercontent.com/28842407/28465354-6a990284-6df6-11e7-8b0c-d431d6ed4fa0.JPG)

**Comment by jordanallain** [comment]
@3point14guy if you're all set you can close this now, thanks!

**Comment by 3point14guy** [comment]
Went over ERD with Maria and Jess and revised game plan for mvp and stretch goals.
