### ISSUE TITLE
patch to server works, but page refreshes whenever ajax goes through

### ISSUE THREAD

**Issue by scottyscripts** [ga-wdi-boston/full-stack-project#98]

**Comment by resource11** [comment]
Same issue here, Scott.

**Comment by tdyer** [comment]
Could be that you are not adding the preventDefault method to http://api.jquery.com/event.preventdefault/ to the click/submit handler.

**Comment by scottyscripts** [comment]
YES! THANK YOU. I wrote an anon function for the callback and forgot! THANK YOU
