### ISSUE TITLE
can't get change password curl request to work

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/full-stack-project#980]
Hello!

Having issues get change-password.sh to run, keep getting 400 Bad Request. 

My curl code:
```rb
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/change-password"
curl "${API}${URL_PATH}/${ID}" \
  --include \
  --request PATCH \
  --header "Authorization: Token token=${TOKEN}" \
  --header "Content-Type: application/json" \
  --data '{
    "passwords": {
      "old": "'"${OLDPW}"'",
      "new": "'"${NEWPW}"'"
    }
  }'

echo
```

What I type into terminal:

ID=1 TOKEN="BAhJIiVlMjUxMWVhZDk4NDdhMzg1NjI4YzQ4NmI3OTliZmE5ZAY6BkVG--b3b4ccdc858686b26dc998c201c2ed63d835dcc3" OLD="ingrid" NEW="jingrid" sh scripts/change-password.sh 

The token I use is the token I get when I sign in.

sos

**Comment by Jcornmanhomonoff** [comment]
So it looks like you're trying to insert variable names that don't exist. ie: `OLD` and `NEW`. Look at what you're using for the names of your variables for old and new in your password object.

**Comment by jingrid** [comment]
Ah, that was it! 

Thanks!
