### ISSUE TITLE
creating entity & working with back-end

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/full-stack-project#981]
I'm using the rails-api-library-demo as a reference, while attempting to create my first resources (user & exercise). I'm having trouble getting started. 

when setting up my database I used:
```js
bin/rake db:drop db:create db:migrate db:seed db:examples
```
should examples be replaced with 'exercise'?
```js
bin/rake db:drop db:create db:migrate db:seed db:exercises
```
looking at the rails-api docs, it recommends using scaffold, so I should probably do this instead of what I did ? 
```js
bin/rails generate scaffold exercise date:integer name:string weight:integer user_id:foreignkey user:references
```
I think I should use scaffold because it creates more things for me?
if I do use scaffold what does user:references do?
I want to add user_id so that I can link the exercise table to user, is this something I should include in my initial scaffold?

In the rails-api template, we have an 'examples' model and an 'examples' controller. Should I manually edit these files and replace the name with exercise? what are the 'example' files doing and why are they there?

I might benefit from a brief 1:1 to answer all of these questions or provide a refresher on these topics. I feel like I don't understand some fundamentals parts to creating my back-end.

**Comment by jordanallain** [comment]
you don't need to say user_id:foreignkey in the scaffold command, that is essentially what user:references is doing. it is saying that it will reference the user table.

**Comment by jordanallain** [comment]
@ryanwk any updates on this?

**Comment by ryanwk** [comment]
I used scaffold, and created my entity 'exercises'. All the files look good. 

```rb
models:
class Exercise < ApplicationRecord
  belongs_to :user
end

class User < ApplicationRecord
  include Authentication
  has_many :examples
end

exercise controller:
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :update, :destroy]

  # GET /exercises
  def index
    @exercises = Exercise.all

    render json: @exercises
  end

  # GET /exercises/1
  def show
    render json: @exercise
  end

  # POST /exercises
  def create
    @exercise = Exercise.new(exercise_params)

    if @exercise.save
      render json: @exercise, status: :created, location: @exercise
    else
      render json: @exercise.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /exercises/1
  def update
    if @exercise.update(exercise_params)
      render json: @exercise
    else
      render json: @exercise.errors, status: :unprocessable_entity
    end
  end

  # DELETE /exercises/1
  def destroy
    @exercise.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def exercise_params
      params.require(:exercise).permit(:date, :name, :weight, :user_id)
    end
end

```
I added this to my routes, because I just want exercises to be created, indexed, deleted, and updated by a user. I don't think I want them to show a single exercise just yet. 
```rb
resources :exercises, except: %i[show]
```
I migrated these things. I'm now trying to perform CRUD on my exercise entity. I created this curl script.
```rb
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/exercises"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "exercise": {
      "name": "'"${name}"'",
      "weight": "'"${weight}"'"
      "date": "'"${date}"'"
    }
  }'

echo
```
how do I test with curl scripts? 
I've also tried using bin/rails console and typed the following into it:
```rb
[4] pry(main)> squats = exercise.create({name: 'Squat', weight: 135, date: '2017-07-20'})
NameError: undefined local variable or method `exercise' for main:Object
from (pry):5:in `<main>'
```
can someone walk me through how to perform CRUD actions on this entity? and how to use curl scripts? and explain what the difference is?

**Comment by jordanallain** [comment]
```ruby
class User < ApplicationRecord
  include Authentication
  has_many :examples
end
```

Shouldn't user have many exercises?

**Comment by ryanwk** [comment]
Yes, whoops. Franklin just told me how to to perform Curl requests. 
should I do what I was doing in the console?  or should I stick to creating curl requests to test api endpoints?

**Comment by ryanwk** [comment]
I'm trying to create an exercise but I'm getting this back from my browser (http://localhost:4741/exercises)

this is what I type into the terminal: 
$ NAME="CURL" WEIGHT=100 DATE=2010-05-10 sh scripts/create-exercise.sh 

```rb
{
"exercises": [
{
"id": 1,
"date": null,
"name": "",
"weight": null
},
{
"id": 2,
"date": null,
"name": "",
"weight": null
}
]
}
```
this is what my migration looks like: 
```rb
class CreateExercises < ActiveRecord::Migration[5.0]
  def change
    create_table :exercises do |t|
      t.date :date
      t.string :name
      t.integer :weight
      t.references :user, foreign_key: true

      t.timestamps
    end
  end
end
```
this is what my curl script looks like:
```rb
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/exercises"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "exercise": {
      "name": "'"${name}"'",
      "weight": "'"${weight}"'",
      "date": "'"${date}"'"
    }
  }'

echo
```
I've tried many different variations of the terminal command (w/ quotes, w/o quotes, various date types, etc): 
$ NAME="CURL" WEIGHT=100 DATE=2010-05-10 sh scripts/create-exercise.sh

**Comment by Jcornmanhomonoff** [comment]
What is the error you are receiving?

**Comment by ryanwk** [comment]
I'm not getting an error. I get a 201 created. But when I check the browser I get this: 
```rb
{
"exercises": [
{
"id": 1,
"date": null,
"name": "",
"weight": null
},
{
"id": 2,
"date": null,
"name": "",
"weight": null
}
]
}
```
there should be values for each parameter. 
$ NAME=CURL WEIGHT=100 DATE=2010-05-10 sh scripts/create-exercise.sh

**Comment by jordanallain** [comment]
hey ryan wanna sit in the kitchen and walk through this?

**Comment by ryanwk** [comment]
yes thanks!

**Comment by ryanwk** [comment]
Turns out I needed to write the curl request like this: 
```rb
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/exercises"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "exercise": {
      "name": "squat",
      "weight": "300"
    }
  }'
```
string interpolation was holding me back. Thank you Jordan and Jess!!!
