### ISSUE TITLE
trying to link sign in/out back end to front end

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/full-stack-project#984]
I'm in the process of linking my back end and front end for sign in/out actions. However, when I try to sign up or sign in, it doesn't log anything into my users table.

I basically copy+pasted the ui, api, events, config files from tic tac toe and changed the api url to the localhost url that my users table is running on.

I've tried console logging all the functions, but none are showing up, even the one that is supposed to respond to the click of the 'submit' button for signing up.

**Comment by jordanallain** [comment]
did you attach your click handlers in a document.ready function?

**Comment by jingrid** [comment]
No, I just have them as jQuery in my events.js file, as I did in tic tac toe. 

Not sure how to attach into a document.ready function ?

**Comment by jordanallain** [comment]
you did this for tic tac toe, the document.ready function probably is the shorthand jquery one in your index.js

```js
$(() => {
    
})
```
should look something like that

**Comment by jordanallain** [comment]
you can also refer back to the jquery-ajax lessons, we did something similar where we added event listeners to an addHandlers function, and then we called that function in the document.ready

**Comment by jingrid** [comment]
ohhhh got it! thanks
