### ISSUE TITLE
'Delete' form refreshes page despite event.preventDefault()

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/full-stack-project#985]
I'm using handlebars to include a delete form for each item that is listed using the index request. The way it's set up is the form contains a hidden input that passes the game id and a submit button. Since a version of the form is created for each object, I added a class 'delete-game' rather than an id and set the event listener to listen for the entire class.
My issue is that when I load up the games, the delete forms appear, but when I submit one them, the page is refreshed even though the function on the listener contains event.preventDefault(). I have several other forms where the prevent default is working like it's supposed to, but the ones created through handlebars are not.

Event function and listeners:
```JavaScript
const onDeleteGame = function (event) {
  event.preventDefault()
  const data = getFormFields(this)
  console.log(data)
  api.deleteGame(data)
     .then(ui.deleteGameSuccess)
     .catch(ui.deleteGameFailure)
}

const addHandlers = () => {
  $('#sign-up').on('submit', onSignUp)
  $('#sign-in').on('submit', onSignIn)
  $('#change-pw').on('submit', onChangePassword)
  $('#sign-out').on('submit', onSignOut)
  $('#index-games').on('submit', onShowGames)
  $('#show-game').on('submit', onShowGame)
  $('#create-game').on('submit', onCreateGame)
  $('#update-game').on('submit', onUpdateGame)
  $('.delete-game').on('submit', onDeleteGame)
}
```
delete form included in the handlebars {{each}} statement:
```html
  <form class="delete-game">
      <fieldset>
        <input class='pop-up-fields text-field' type='hidden' value={{game.id}} name='game[id]'> <br> <br>
        <input type="submit" name="submit" value="Delete Game">
      </fieldset><br>
    </form>
```
Any help would be appreciated! I'm hitting a wall because the page refreshing makes it tough to debug using errors and console.logs. Thanks!

**Comment by jordanallain** [comment]
do you need a form for this? if you only need a delete button, you can ignore the form and just listen for the click of the button. you can even store the game.id on the button itself as a data-attribute.

**Comment by bradleyden** [comment]
That's a good idea, I didn't think to use data-attribute to store the id instead of a hidden form field.

If I do this, getFormFields won't work anymore though, correct? What would be the best way to pass the data-attribute value of the button to the ajax request?

**Comment by jordanallain** [comment]
you will not need getFormFields anymore correct. when someone clicks the delete button that should trigger an ajax request, the event.target will be the button which will have the ID stored in it so you can just grab it from there.

**Comment by bradleyden** [comment]
okay, awesome thanks, that makes sense. I will try it after lunch and close the issue if it works!

**Comment by bradleyden** [comment]
problem solved!
The issue was that the event listeners were bound to the html elements before the handlebars template loaded the form/button html into the dom. I fixed it by adding an event listener to bind to the html every time the handlebars template is loaded in the index function like so:
```JavaScript
const onShowGames = function (event) {
  event.preventDefault()
  api.getAllGames()
     .then(ui.loadGamesSuccess)
     .catch(ui.loadGamesFailure)
  $(document).on('submit', '.delete-game', onDeleteGame)
}
```
Using this method I was actually able to get it working with the form as I originally had it- the problem was that it wasn't even triggering the event listener to begin with which is why the prevent default wasn't working. Now the page does not refresh and the delete button works!

**Comment by jordanallain** [comment]
Nice you learned a good lesson! You can't attach an event listener to a node unless the DOM has rendered it already.
