### ISSUE TITLE
Can't find my table

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/full-stack-project#986]
I created my table with generate scaffold and did db:migrate, but when I go into psql and run \d, my table doesn't show up. My schema file does show that it was created.

I went over the lesson plan for rails-api one to many to find pointers, I attempted to google, but I can't seem to come up with a search string that gets me the info I am after and review of the closed issues doesn't show anything comparable to my current issue.

I am missing a step, please help me get back on track.

**Comment by Jcornmanhomonoff** [comment]
What database are you connected to?

**Comment by 3point14guy** [comment]
Good question?  How do I tell?  It must not be the right one because I see tables for recipes, ingredients, books, etc.

**Comment by Jcornmanhomonoff** [comment]
When you're in the console, it's the name to the left. ie:
<img width="938" alt="screen shot 2017-07-21 at 11 50 53 am" src="https://user-images.githubusercontent.com/17557070/28471369-ec700140-6e0a-11e7-9698-ecbe7e1d1c5c.png">

When we go into our sql-crud DB it changes from `<yourname>` to `sql-crud`

**Comment by 3point14guy** [comment]
~/wdi/projects/groovy-movie2/back-end/rails-api-groovy-movie (master)
$ psql sql-crud
psql (9.6.3)
Type "help" for help.

sql-crud=# 

Ok, so maybe I wasn't going to quite the right place, but even under just psql, I don't see my new table.

**Comment by Jcornmanhomonoff** [comment]
Unless I'm misunderstanding and you've already checked there, I would try checking your main DB, not your `sql-crud` DB. We were using `sql-crud` for our lessons.

**Comment by 3point14guy** [comment]
Yes, I just checked using just psql.  I get a different list of tables but not the new one I am creating for this project.
nicholaspiaskoski=# \d
                     List of relations
 Schema |        Name        |   Type   |       Owner       
--------+--------------------+----------+-------------------
 public | ingredients        | table    | nicholaspiaskoski
 public | ingredients_id_seq | sequence | nicholaspiaskoski
 public | patients           | table    | nicholaspiaskoski
 public | patients_id_seq    | sequence | nicholaspiaskoski
(4 rows)

**Comment by 3point14guy** [comment]
got it: 
rails-api-groovy-movie_development=# 
it's there
