### ISSUE TITLE
Issue trouble shooting table

### ISSUE THREAD

**Issue by mak1323** [ga-wdi-boston/full-stack-project#987]
I created a table called nouns, and that table is populated as such:
 id |  noun   |       attribute        
----+---------+------------------------
  1 | Hawk    | Animal
  2 | Tiger   | Animal
  3 | Sword   | Weapon
  4 | Musket  | Weapon
  5 | Whiskey | Cocktail and Drink
  6 | Mustang | Vehicle
  7 | Truck   | Vehicle
  8 | Goblin  | Mythology and Folklore
  9 | Dragon  | Mythology and Folklore
 10 | Pen     | Literature and Writer

When I try to access it through the browser, I am falling into an error of "status": 500,
"error": "Internal Server Error". "exception": "#<ActiveRecord::DangerousAttributeError: attribute is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.>"

I'm trying to decide what the best course of action is in fixing this, or if I really need to. Would it be better to Empty the db, and migrate it with a new key instead of noun(maybe word?) or should I roll back my migration and delete all the files associated with it?

**Comment by jordanallain** [comment]
you can create a migration to change the column name

**Comment by mak1323** [comment]
Cool.
