### ISSUE TITLE
500 error: undefined local variable or method `user'

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/full-stack-project#988]
Trying to do a curl request to create an entry on my table and I get a 500 error:

{"status":500,"error":"Internal Server Error","exception":"#\u003cNameError: undefined local variable or method `user' for #\u003cClass:0x007f82048e1088\u003e\u003e",

Researching this error on Google it makes me think that the error is indicating that I need to define a user, but the table I am working with does not have a user column.

There were plenty of issues in the issue queue about 500 errors, but none that talked about a undefined local variable.

**Comment by cpearce31** [comment]
Does it give you a line number for that error? Can you post the curl request and the controller code?

**Comment by 3point14guy** [comment]
Turns out it did in terminal where the server was running.  It pointed me right to the problem: now got 404.  Will close this one and open a new one if I continue to have problems.

Thanks!
