### ISSUE TITLE
how to string together click handler and delete/edits

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/full-stack-project#99]
I have the click event on a list of honeys, and a delete button and an edit button. I can select from the honey list and get the hiney id. I don't know how to have the delete and edit functions see that id. And I am not sure my deletes work. HELP please!

**Comment by LaurisaNeuwirth** [comment]
And I cannot get my Honey list to automatically refresh once I add a honey.

**Comment by tdyer** [comment]
Working now.
