### ISSUE TITLE
unable to send POST request via front end

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/full-stack-project#990]
Trying to create an entry (POST request) via front end ajax.

I keep getting 400 Bad Request, not sure what's not lining up. The cURL requests I've run in the back end work fine.

**Comment by jordanallain** [comment]
is there anything in your rails server logs that seems helpful?

**Comment by jingrid** [comment]
This is the error msg:

Started POST "/beaches" for 127.0.0.1 at 2017-07-21 15:15:08 -0400
Processing by BeachesController#create as */*
  Parameters: {"name"=>{"name"=>"zxc"}, "address"=>{"address"=>"zxc"}, "driveTime"=>{"drive_time"=>"zxc"}, "waterCondition"=>{"water_condition"=>"zxc"}, "amenities"=>{"amenities"=>"zxc"}, "submit"=>"Create entry!"}
Completed 400 Bad Request in 2ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: beach):
  
app/controllers/beaches_controller.rb:49:in `beach_params'
app/controllers/beaches_controller.rb:18:in `create'

Maybe its the "submit" that's throwing it off?

**Comment by jingrid** [comment]
Or maybe the params shouldn't be their own objects? For example,
{"name"=>{"name"=>"zxc"} should be just {"name"=>"zxc"} ?

**Comment by jordanallain** [comment]
you want to send a data object. the data object should have one key `beach`, that should point to another object. That object should have keys that match the params you have accepted in your beaches_params.

**Comment by jordanallain** [comment]
and also, you don't want to be sending the submit

**Comment by jingrid** [comment]
oh oops! Changed all the keys to 'beach' and now it's working
