### ISSUE TITLE
Trouble parsing out new ERD with a join table

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/full-stack-project#991]
I am trying to create a list of movies that is created in the Rails API and then displayed through handlebars on the frontend. Currently, I have a one to many relationship with a User having_many lists and lists belong_to user (with a column for user_id foreign keys in my list table). The Lists table also has one column for titles.

As I think about moving forward, I am realizing I will run into problems with the single column for titles. Either a) I will need to pass a string containing multiple movie titles into the column, but then will have trouble using handlebars to divide the string into multiple list items or b) will need to create a different field for each title, but then will have a cap on how many entries a user could make... along with a host of trouble I envision in updating the list.

I think the solution is to create a join table entitled "Movies" that belongs to both Lists and Users. Users has_many Movies and Lists has_many movies, but I am having trouble diagraming the relationship and thinking through how to change my current back-end. Any advice?

**Comment by jordanallain** [comment]
would you like to sit down with me and draw this out to see if we can make sense of it?

**Comment by CoreyFedde** [comment]
That would be great!

**Comment by jordanallain** [comment]
cool ill head to the kitchen

**Comment by CoreyFedde** [comment]
A join-table is not needed unless I was seeding a database with movies and not letting users create their own. Instead, I could add a "movies" column to the list table that would reference a separate table populated with individual movies.
