### ISSUE TITLE
patch request

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/full-stack-project#992]
attempting PATCH request to update an exercise. It doesn't seem to find the exercise with ID = 7. However, this exercise does exist. 

$ TOKEN=BAhJIiUxNTAxZDVlOWExNTA3Y2QzOGU1ODgxNDYxMjRjYTE4NQY6BkVG--aa392b5aa804c640a058aa561da3719b7bb5d71a ID="7" WEIGHT="350" sh scripts/update-exercise.sh 
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8
X-Request-Id: 8dbd5cba-1342-4001-9133-92556c26414f
X-Runtime: 0.009018
Vary: Origin
Content-Length: 3780

{"status":404,"error":"Not Found","exception":"#\u003cActionController::RoutingError: No route matches [PATCH] \"/update-exercise/7\"\u003e","traces"

I tried typing this:
ID="7" WEIGHT="350" 
with and without quotes
when creating the curl script I typed it all in by hand, instead of copy/paste.

removing interpolation did not fix the problem. 

I checked my browser (http://localhost:4741/exercises/7) and got this: 
```rb
"status": 404,
"error": "Not Found",
"exception": "#<ActionController::RoutingError: No route matches [GET] \"/exercises/7\">",
"traces": {
"Application Trace": [],
"Framework Trace": [
``` 

these are my routes
```rb
Rails.application.routes.draw do
  resources :exercises, except: %i[show new edit]
  resources :examples, except: %i[new edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: %i[index show]
end

```

**Comment by Jcornmanhomonoff** [comment]
Can you paste in your request?

**Comment by ryanwk** [comment]
request:
```rb
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/update-exercise"
curl "${API}${URL_PATH}/${ID}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \
  --data '{
    "exercise": {
      "weight": "300"
    }
  }'

echo
```

**Comment by Jcornmanhomonoff** [comment]
Let's start by looking at your path. Is `update-exercise` the correct path that a PATCH request is expecting?

**Comment by Jcornmanhomonoff** [comment]
If you look in your controller, Rails does a nice display of paths based on the action it expects.

**Comment by ryanwk** [comment]
that fixed it, had to correct the path. Thank you.
```rb
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/exercises"
curl "${API}${URL_PATH}/${ID}" \
```
