### ISSUE TITLE
DELETE

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/full-stack-project#994]
attempting DELETE request to destroy an exercise. It doesn't seem to find the exercise with ID = 1. 

```rb
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/exercises"
curl "${API}${URL_PATH}/${ID}" \
  --include \
  --request DELETE \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN"

here's the routes:
exercise PATCH  /exercises/:id(.:format)       exercises#update
          PUT    /exercises/:id(.:format)       exercises#update
          DELETE /exercises/:id(.:format)       exercises#destroy
```
I used the correct route, and I see this with the terminal after running the sh script:

~/wdi/projects/strongerBackEnd (feature)
$ TOKEN=BAhJIiUxNTAxZDVlOWExNTA3Y2QzOGU1ODgxNDYxMjRjYTE4NQY6BkVG--aa392b5aa804c640a058aa561da3719b7bb5d71a ID=2 sh scripts/destroy_exercise.sh 
HTTP/1.1 404 Not Found
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: c2094290-ad80-4da4-8dcb-408120a55284
X-Runtime: 0.011580
Vary: Origin
Transfer-Encoding: chunked

{"error":{"message":"Not Found"}}

However, when I do an index I still see the exercise with that ID. 

~/wdi/projects/strongerBackEnd (feature)
$ TOKEN=BAhJIiUxNTAxZDVlOWExNTA3Y2QzOGU1ODgxNDYxMjRjYTE4NQY6BkVG--aa392b5aa804c640a058aa561da3719b7bb5d71a  sh scripts/index-exercise.sh 
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"292db7933cf25a65096a4102d739b7e8"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 0387f177-7b44-489a-a86d-fe1684d0d446
X-Runtime: 0.010047
Vary: Origin
Transfer-Encoding: chunked

{"exercises":[{"id":1,"name":"","weight":null},{"id":2,"name":"","weight":null},{"id":3,"name":"","weight":null},{"id":4,"name":"","weight":null},{"id":5,"name":"","weight":null},{"id":6,"name":"","weight":null},{"id":7,"name":"squat","weight":300}]}

**Comment by Jcornmanhomonoff** [comment]
What is the error you are getting back?

**Comment by ryanwk** [comment]
nevermind, I tried it with the exercise with the id 7 and it worked.

**Comment by ryanwk** [comment]
For some reason those first 6 exercises aren't recognized
