### ISSUE TITLE
sign-up front-end 

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/full-stack-project#997]
So I've set up the back end, user authentication, my entities all work properly with CRUD. 
Testing out the front end, by signing up and clicking 'submit', I get this error:

one saying it failed and one saying it passed.

Request URL:http://localhost:7165//sign-up
Request Method:POST
Status Code:404 Not Found

16:31:42.738 jquery.js:9566 XHR finished loading: POST "http://localhost:7165//sign-up".

So I opened up my backend terminal and did this curl request to see all users 
{"users":[{"id":2,"email":"ryan@email.com"},{"id":1,"email":"fc@cf"}]}

the user I created was not there. 

Here's my front end api logic:
(everything is required properly, linter is happy, etc)
```js 
$(() => {
  $('#sign-up-form').on('submit', function (e) {
    const data = getFormFields(this)
    e.preventDefault()
    signUp.onSignUp(data)
  })
  $('#sign-in-form').on('submit', function (e) {
    const data = getFormFields(this)
    e.preventDefault()
    signIn.onSignIn(data)
  })
  $('#sign-out').on('click', function (e) {
    e.preventDefault()
    signOut.onSignOut()
  })

'use strict'
const ui = require('./ui')
const config = require('./config')

const onSignUp = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data
  })
  .done(ui.signUpSuccess)
  .fail(ui.signUpFailure)
}
module.exports = {
  onSignUp
}
```
How can I sign up, what's not working properly here?

**Comment by Jcornmanhomonoff** [comment]
What does your config file look like?

**Comment by ryanwk** [comment]
```js
const config = {
  apiOrigins: {
    production: 'https://stronger.herokuapp.com/',
    development: 'http://localhost:7165/'
  }
}

module.exports = config
```

**Comment by Jcornmanhomonoff** [comment]
Look at the url that it's trying to make a post to. What looks wrong with it?
`Request URL:http://localhost:7165//sign-up`

**Comment by ryanwk** [comment]
too many /'s ?

**Comment by Jcornmanhomonoff** [comment]
So in your `config` file you end your paths with a `/` but you're also adding a `/` in your ajax requests. I would choose one way or the other. Whichever will be easier for you to make sense of.

**Comment by ryanwk** [comment]
I took em out, stil no luck.

```js
const config = {
  apiOrigins: {
    production: 'https://stronger.herokuapp.com',
    development: 'http://localhost:7165'
  }
}

module.exports = config
```

**Comment by payne-chris-r** [comment]
Good catch with the /
What does the req look like on the rails side?
You should have a server log for the req.

**Comment by payne-chris-r** [comment]
Is it hitting your deployed api or your local API?

**Comment by payne-chris-r** [comment]
What is the URL for your local API? What port does it run on?

**Comment by ryanwk** [comment]
it's hitting the local api
```sh
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/sign-up"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "'"${EMAIL}"'",
      "password": "'"${PASSWORD}"'"
    }
  }'
```

**Comment by ryanwk** [comment]
```sh
'use strict'
const ui = require('./ui')
const config = require('./config')

const onSignUp = (data) => {
  console.log('sign up ajax request invoked')
  return $.ajax({
    url: config.apiOrigin + 'sign-up',
    method: 'POST',
    data
  })
  .done(ui.signUpSuccess)
  .fail(ui.signUpFailure)
}

module.exports = {
  onSignUp
}
```
@Jcornmanhomonoff @payne-chris-r @jordanallain @sdavidson140 @MicFin @BenGitsCode @tvlangley @benjimelito

**Comment by ryanwk** [comment]
Request URL:http://localhost:7165/sign-up
Request Method:POST
Status Code:404 Not Found
Remote Address:127.0.0.1:7165
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Connection:keep-alive
Content-Length:147
Content-Security-Policy:default-src 'self'
Content-Type:text/html; charset=utf-8
Date:Sat, 22 Jul 2017 17:41:02 GMT
X-Content-Type-Options:nosniff
X-Powered-By:Express
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Content-Length:66
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Host:localhost:7165
Origin:http://localhost:7165
Pragma:no-cache
Referer:http://localhost:7165/?credentials%5Bemail%5D=kai%40kai.com&credentials%5Bpassword%5D=kai
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
X-Requested-With:XMLHttpRequest
Form Data
view source
view URL encoded
credentials[email]:rza@rza.com
credentials[password]:rza

**Comment by ryanwk** [comment]
had to change front end config file to this!
```js
const config = {
  apiOrigins: {
    production: 'https://stronger.herokuapp.com/',
    development: 'http://localhost:4741/'
  }
}
```
module.exports = config
