### ISSUE TITLE
UnknownAttributeError

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/full-stack-project#998]
ActiveModel::UnknownAttributeError (unknown attribute 'user_id' for Movie.):

Jordan, Jess and I have been working on this for a little while and we think we have all our i's dotted and t's crossed.

from schema:
```rb
  create_table "movies", force: :cascade do |t|
    t.string   "name"
    t.date     "year"
    t.float    "rating"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
    t.index ["user_id"], name: "index_movies_on_user_id", using: :btree
  end
```
from controller:
```rb
def movie_params
      params.require(:movie).permit(:name, :year, :rating, :user_id)
    end
```
from  serializer:
```rb
class MovieSerializer < ActiveModel::Serializer
  attributes :id, :name, :year, :rating, :user_id
  belongs_to :user
end
```
from movie model:
```rb
class Movie < ApplicationRecord
  belongs_to :user
end
```

Need help with the next step please!

**Comment by payne-chris-r** [comment]
What causes the error?

**Comment by payne-chris-r** [comment]
Can you post your migration file?

**Comment by 3point14guy** [comment]
Doing this post request creates the error:

```rb
curl --include --request POST http://localhost:4741/movies \
 --header "Content-Type: application/json" \
 --header "Authorization: Token token=BAhJIiU3NzUzM2Q0Y2NiOGYxMzI5Mzk5NzM2OGY5NzY1OTk3YQY6BkVG--a6b88513afca27fb9a3ce32f3d4c8fc4f38bac13" \
 --data '{
   "movie": {
     "name": "Star Wars",
     "year": "1977-01-10",
     "rating": "5.0"
   }
 }'
```

this is the last migration file and it is up to date with the schema

```rb
class AddUserIdToMovies < ActiveRecord::Migration[5.0]
  def change
    add_reference :movies, :user, foreign_key: true
  end
end
```

**Comment by 3point14guy** [comment]
The error points to this line:

app/controllers/movies_controller.rb:18:in `create'

but Jordan says it is somewhere else.

**Comment by 3point14guy** [comment]
This is line 18 from the controller file:
```rb
  def create
    @movie = current_user.movies.build(movie_params)
```

**Comment by 3point14guy** [comment]
Well, FLIP!

I made a colossal screw up trying to push my changes to Github and was in the wrong branch and somehow lost what I was working on.  Maybe when I rebuild the table and try again, everything will be fine.  Will keep this open until I get back to that point and know for sure.

**Comment by jordanallain** [comment]
what happened?

**Comment by 3point14guy** [comment]
I realized I had been working on the master when I went to commit.  I tried switch branches before committing to see if that would let me leave the master clean.  It didn't.  So, I am back to checking my curl scripts on my movie table BEFORE establishing the relationship to the user table.  It is going fine, just slow.  I will update again in the morning.

**Comment by jordanallain** [comment]
if you hadn't committed you can switch branches and the changes will come with you to the new branch. i'm guessing you already had committed previously on the master branch though which is okay, i'll check again tomorrow.

**Comment by 3point14guy** [comment]
OK.  Built it up again.  Ran curls. Got the same error at first when I got to the POST request using .build in def create of the controller file.  Got the curl request to work when I used .new there instead.  Went back to .build and it all worked fine!! Don't know why that worked, as everything is back to looking as it did when I originally reported the issue.  ????

Closing this issue.

**Comment by jordanallain** [comment]
Hah so weird I knew it felt like we had done it right!
