### ISSUE TITLE
not sure how to return only entries created by current user

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/full-stack-project#999]
I want to make a GET request for getting all entries created by the currently signed in user. 

However, I'm unable to adjust :index to make it only display the entries created by the signed-in user.

What is the best way I should go about doing this?

**Comment by payne-chris-r** [comment]
Is there a method you could call? How did I get all the patients that belonged to a Doctor?

You can also get all of them and filter. 

You can also look at `editable` in ExamplesSerializer and try to figure out what's going on there!!

**Comment by jingrid** [comment]
oh got it! Modified the index for my controller to be current_user.entries.all
